import type { RawPack } from '../core/packs';

export const animeMediumPack: RawPack = {
  id: 'anime-medium',
  name: 'Anime · Medium',
  description: 'Heroes, villains, studios and arcs from the shows every fan knows.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '⛩️',
  accent: '#be123c',
  letters: {
    A: [
      { q: 'Katsuhiro Otomo\'s 1988 cyberpunk film in which biker Kaneda chases his transformed friend Tetsuo across Neo-Tokyo.', a: 'Akira' },
      { q: 'The blond strategist and childhood friend of Eren and Mikasa who later inherits the Colossal power.', a: 'Armin', alt: ['Armin Arlert'] },
      { q: 'The younger Elric brother, whose soul is bound to a giant suit of armor.', a: 'Alphonse', alt: ['Alphonse Elric', 'Al'] },
      { q: 'The science of equivalent exchange practiced by the Elric brothers.', a: 'Alchemy' },
      { q: 'The ever-smiling Symbol of Peace who passes his power to Izuku Midoriya.', a: 'All Might' },
      { q: 'The proud red-plugsuit pilot of Evangelion Unit-02.', a: 'Asuka', alt: ['Asuka Langley', 'Asuka Langley Soryu'] },
      { q: 'Naruto\'s organization of rogue ninja who wear black cloaks patterned with red clouds.', a: 'Akatsuki' },
      { q: 'Spy x Family\'s pink-haired telepathic little girl, adopted by a spy and an assassin.', a: 'Anya', alt: ['Anya Forger'] },
      { q: 'The surname shared by Mikasa and Levi, marking a bloodline of unnaturally strong fighters.', a: 'Ackerman' },
      { q: 'Osamu Tezuka\'s rocket-booted robot child, star of Japan\'s first weekly TV anime in 1963.', a: 'Astro Boy', alt: ['Atom', 'Tetsuwan Atom'] },
      { q: 'Black Clover\'s loud, magicless orphan who wields anti-magic swords.', a: 'Asta' },
    ],
    B: [
      { q: 'The genius heiress of Capsule Corporation who invents the Dragon Radar.', a: 'Bulma' },
      { q: 'Kentaro Miura\'s dark fantasy manga following the branded swordsman Guts.', a: 'Berserk' },
      { q: 'The Straw Hats\' afro-sporting skeleton musician.', a: 'Brook' },
      { q: 'Tite Kubo\'s series about a teenager who becomes a substitute Soul Reaper.', a: 'Bleach' },
      { q: 'The Hyuga clan\'s all-seeing white-eyed ability.', a: 'Byakugan' },
      { q: 'The fishing-ship-turned-spacecraft that Spike Spiegel and Jet Black call home.', a: 'Bebop' },
      { q: 'Izuku Midoriya\'s explosive childhood friend and rival, hero name Dynamight.', a: 'Bakugo', alt: ['Katsuki Bakugo', 'Bakugou'] },
      { q: 'The hulking Legendary Super Saiyan who finally got a canon reboot movie in 2018.', a: 'Broly' },
      { q: 'The final, most powerful release form of a Soul Reaper\'s zanpakuto.', a: 'Bankai' },
      { q: 'The purple cat-like God of Destruction who comes to Earth craving pudding.', a: 'Beerus' },
    ],
    C: [
      { q: 'The Straw Hats\' blue-nosed reindeer doctor who ate the Human-Human Fruit.', a: 'Chopper', alt: ['Tony Tony Chopper'] },
      { q: 'Dr. Gero\'s bio-android villain who reaches his Perfect form by absorbing Androids 17 and 18.', a: 'Cell' },
      { q: 'The ten-year-old girl forced to work in a spirit bathhouse to save her parents in Spirited Away.', a: 'Chihiro' },
      { q: 'Series in which an exiled prince gains an eye power of absolute obedience and leads a rebellion against Britannia.', a: 'Code Geass' },
      { q: 'Tatsuki Fujimoto\'s series about the debt-ridden Denji, who merges with his devil dog Pochita.', a: 'Chainsaw Man' },
      { q: 'The middle ninja rank Naruto\'s class attempts to earn in a famous multi-stage exam arc.', a: 'Chunin' },
      { q: 'The sorcerer who created the magical cards Sakura Kinomoto must recapture.', a: 'Clow Reed', alt: ['Clow'] },
      { q: 'Berserk\'s female commander of the Band of the Hawk, left broken by the Eclipse.', a: 'Casca' },
      { q: 'The steaming, skinless sixty-meter giant that peers over Wall Maria in the story\'s very first episode.', a: 'Colossal Titan' },
      { q: 'Shrunken teen detective Shinichi Kudo takes this alias, borrowed from a famous British mystery author.', a: 'Conan', alt: ['Edogawa Conan', 'Detective Conan'] },
    ],
    D: [
      { q: 'Tsugumi Ohba and Takeshi Obata\'s thriller pitting Light Yagami against the detective L.', a: 'Death Note' },
      { q: 'The hero name Izuku Midoriya adopts, reclaiming a childhood insult.', a: 'Deku' },
      { q: 'Jujutsu Kaisen\'s ultimate technique, trapping foes inside a sorcerer\'s guaranteed-hit inner territory.', a: 'Domain Expansion' },
      { q: 'The vampire arch-nemesis of the Joestar family, who begins as Jonathan\'s adopted brother.', a: 'Dio', alt: ['Dio Brando'] },
      { q: 'Akira Toriyama\'s saga that began with a monkey-tailed boy hunting seven wish-granting orbs.', a: 'Dragon Ball' },
      { q: 'The earless blue robot cat sent from the future to help hapless Nobita.', a: 'Doraemon' },
      { q: 'The Akatsuki bomber who sculpts explosive clay and insists that art is a blast.', a: 'Deidara' },
      { q: 'The broke teenager who becomes a chainsaw-headed devil hero after merging with his pet.', a: 'Denji' },
      { q: 'The blue-flame League of Villains member secretly Endeavor\'s eldest son.', a: 'Dabi' },
      { q: 'The pink-feathered One Piece warlord who rules Dressrosa with string powers.', a: 'Doflamingo', alt: ['Donquixote Doflamingo'] },
    ],
    E: [
      { q: 'Attack on Titan\'s protagonist, who swears to wipe out every giant after watching his mother die.', a: 'Eren', alt: ['Eren Yeager', 'Eren Jaeger'] },
      { q: 'Hideaki Anno\'s 1995 series in which traumatized teens pilot bio-mechanical units against Angels.', a: 'Evangelion', alt: ['Neon Genesis Evangelion'] },
      { q: 'The short-tempered alchemist nicknamed Fullmetal, who traded an arm and a leg.', a: 'Edward Elric', alt: ['Edward', 'Ed'] },
      { q: 'Fairy Tail\'s armored redhead who can requip weapons and armor mid-battle.', a: 'Erza', alt: ['Erza Scarlet'] },
      { q: 'The genetically engineered data corgi adopted by the Bebop crew.', a: 'Ein' },
      { q: 'The Seven Deadly Sins\' Lion Sin of Pride, invincible at high noon.', a: 'Escanor' },
      { q: 'The flame hero who becomes number one after All Might retires, father of Shoto.', a: 'Endeavor' },
      { q: 'The Survey Corps commander who leads his recruits in a suicidal final charge against the Beast Titan.', a: 'Erwin', alt: ['Erwin Smith'] },
      { q: 'The Pokemon famous for evolving into many different elemental forms.', a: 'Eevee' },
    ],
    F: [
      { q: 'The galactic tyrant who destroyed Planet Vegeta and is finally beaten by a Super Saiyan on Namek.', a: 'Frieza', alt: ['Freeza'] },
      { q: 'Hiromu Arakawa\'s series about two brothers who pay a terrible price for trying to resurrect their mother.', a: 'Fullmetal Alchemist' },
      { q: 'Hiro Mashima\'s series about a rowdy wizard guild whose members include Natsu and Lucy.', a: 'Fairy Tail' },
      { q: 'Cowboy Bebop\'s amnesiac gambler bounty huntress, frozen in cryosleep for over fifty years.', a: 'Faye', alt: ['Faye Valentine'] },
      { q: 'The cola-powered cyborg shipwright who joins the Straw Hats after Water 7.', a: 'Franky' },
      { q: 'The stoic Jujutsu Kaisen student who summons shikigami from shadows (surname).', a: 'Fushiguro', alt: ['Megumi Fushiguro', 'Megumi'] },
      { q: 'The long-lived elf mage who retraces her old hero party\'s journey to understand humans.', a: 'Frieren' },
      { q: 'Atsushi Ohkubo\'s series about pyrokinetic firefighters battling spontaneous human combustion.', a: 'Fire Force' },
    ],
    G: [
      { q: 'The Saiyan sent to Earth as a baby, originally named Kakarot.', a: 'Goku' },
      { q: 'Jujutsu Kaisen\'s blindfolded strongest sorcerer, bearer of the Six Eyes.', a: 'Gojo', alt: ['Satoru Gojo'] },
      { q: 'The studio founded in 1985 by Hayao Miyazaki and Isao Takahata, named after a Saharan wind.', a: 'Ghibli', alt: ['Studio Ghibli'] },
      { q: 'The 1979 franchise that launched the real-robot genre with Amuro Ray and the RX-78-2.', a: 'Gundam', alt: ['Mobile Suit Gundam'] },
      { q: 'Hunter x Hunter\'s cheerful island boy searching for the father who abandoned him.', a: 'Gon', alt: ['Gon Freecss'] },
      { q: 'Luffy\'s white-haired awakened form, revealed to channel the Sun God Nika.', a: 'Gear Five', alt: ['Gear 5'] },
      { q: 'The Band of the Hawk\'s angelic leader who sacrifices his comrades to become a demon king.', a: 'Griffith' },
      { q: 'Goku\'s studious eldest son, who finishes off Cell as a child.', a: 'Gohan' },
      { q: 'The comedy about a silver-haired odd-jobs samurai named Gintoki in an alien-occupied Edo.', a: 'Gintama' },
      { q: 'Isao Takahata\'s devastating film about siblings Seita and Setsuko in wartime Kobe.', a: 'Grave of the Fireflies' },
      { q: 'The eye-borne power of absolute command that the witch C.C. grants Lelouch.', a: 'Geass' },
      { q: 'Berserk\'s towering swordsman, branded for sacrifice and hunted by demons every night.', a: 'Guts' },
    ],
    H: [
      { q: 'Yoshihiro Togashi\'s series in which candidates endure a deadly licensing exam.', a: 'Hunter x Hunter' },
      { q: 'The unpredictable jester-magician with a star and a teardrop painted on his face, obsessed with fighting ripe opponents.', a: 'Hisoka' },
      { q: 'Miyazaki\'s 2004 film in which young Sophie is cursed into an old woman by the Witch of the Waste.', a: 'Howl\'s Moving Castle' },
      { q: 'The boy in Spirited Away who is secretly the spirit of the Kohaku River.', a: 'Haku' },
      { q: 'The title held by the leader of the Hidden Leaf Village.', a: 'Hokage' },
      { q: 'The laid-back winged hero ranked number two in My Hero Academia.', a: 'Hawks' },
      { q: 'The titan-obsessed scientist who becomes the Survey Corps\' fourteenth commander.', a: 'Hange', alt: ['Hange Zoe'] },
      { q: 'The shy Hyuga heiress who has loved Naruto since childhood and later marries him.', a: 'Hinata', alt: ['Hinata Hyuga'] },
      { q: 'The volleyball series in which tiny Shoyo teams up with a genius setter at Karasuno High.', a: 'Haikyuu', alt: ['Haikyu!!', 'Haikyuu!!'] },
      { q: 'Attack on Titan\'s hidden royal, crowned queen after living as the soldier Krista.', a: 'Historia', alt: ['Historia Reiss'] },
    ],
    I: [
      { q: 'Bleach\'s orange-haired teen who can see ghosts and inherits a Soul Reaper\'s powers.', a: 'Ichigo', alt: ['Ichigo Kurosaki'] },
      { q: 'Sasuke\'s older brother, who slaughtered his entire clan on secret orders.', a: 'Itachi', alt: ['Itachi Uchiha'] },
      { q: 'Rumiko Takahashi\'s series about a half dog-demon pinned to a tree for fifty years by a sacred arrow.', a: 'Inuyasha' },
      { q: 'The given name of the quirkless fanboy who inherits One For All.', a: 'Izuku', alt: ['Izuku Midoriya', 'Midoriya'] },
      { q: 'The timid delivery boy turned featherweight champion in a long-running boxing series.', a: 'Ippo' },
      { q: 'The Jujutsu Kaisen protagonist who swallows a rotting cursed finger to save his friends (surname).', a: 'Itadori', alt: ['Yuji Itadori', 'Yuji'] },
      { q: 'The underwater One Piece prison from which Luffy stages a mass breakout.', a: 'Impel Down' },
      { q: 'The genre term for stories where a protagonist is transported or reborn into another world.', a: 'Isekai' },
    ],
    J: [
      { q: 'The toad sage and self-proclaimed super pervert who mentors Naruto.', a: 'Jiraiya' },
      { q: 'Hirohiko Araki\'s generational saga in which fighters battle using spirit avatars called Stands.', a: 'JoJo\'s Bizarre Adventure', alt: ['JoJo'] },
      { q: 'Gege Akutami\'s series set at a Tokyo school for sorcerers who exorcise curses.', a: 'Jujutsu Kaisen' },
      { q: 'The bonsai-tending ex-cop with a cybernetic arm who partners with Spike Spiegel.', a: 'Jet', alt: ['Jet Black'] },
      { q: 'The stoic Joestar in a school cap whose Stand, Star Platinum, can stop time.', a: 'Jotaro', alt: ['Jotaro Kujo'] },
      { q: 'The whale-shark fish-man and former warlord who becomes the Straw Hats\' helmsman.', a: 'Jinbe', alt: ['Jimbei'] },
    ],
    K: [
      { q: 'The perpetually late copy ninja who reads romance novels and leads Team 7.', a: 'Kakashi', alt: ['Kakashi Hatake'] },
      { q: 'The alias the public gives Death Note\'s mysterious criminal-punisher, derived from the English word killer.', a: 'Kira' },
      { q: 'The romcom in which a student council president and vice president each scheme to make the other confess first.', a: 'Kaguya-sama: Love Is War', alt: ['Kaguya-sama'] },
      { q: 'Goku\'s signature energy wave, learned by watching Master Roshi perform it once.', a: 'Kamehameha' },
      { q: 'Tokyo Ghoul\'s protagonist, turned half-monster by an organ transplant (surname).', a: 'Kaneki', alt: ['Ken Kaneki'] },
      { q: 'The wandering swordsman with a cross-shaped scar who fights with a reverse-blade sword.', a: 'Kenshin', alt: ['Himura Kenshin'] },
      { q: 'The white-haired ex-assassin heir who becomes Gon\'s best friend.', a: 'Killua', alt: ['Killua Zoldyck'] },
      { q: 'The nine-tailed fox spirit sealed inside Naruto at birth.', a: 'Kurama' },
      { q: 'The One Piece emperor called the strongest creature alive, who transforms into an azure dragon.', a: 'Kaido' },
      { q: 'Miyazaki\'s thirteen-year-old witch who starts a flying delivery service with her black cat Jiji.', a: 'Kiki' },
      { q: 'Haikyuu\'s prodigy setter, once mocked as the King of the Court.', a: 'Kageyama', alt: ['Tobio Kageyama'] },
    ],
    L: [
      { q: 'One Piece\'s rubber-bodied captain of the Straw Hat pirates.', a: 'Luffy', alt: ['Monkey D. Luffy'] },
      { q: 'Humanity\'s strongest soldier, a short clean-freak captain in the Survey Corps.', a: 'Levi', alt: ['Levi Ackerman'] },
      { q: 'The sweets-loving detective who crouches on chairs while hunting Kira.', a: 'L' },
      { q: 'The exiled Britannian prince behind the masked persona Zero.', a: 'Lelouch', alt: ['Lelouch Lamperouge', 'Lelouch vi Britannia'] },
      { q: 'The top honor student who finds a shinigami\'s notebook and decides to become the god of a new world (first name).', a: 'Light' },
      { q: 'The lost flying island Sheeta and Pazu seek in Miyazaki\'s 1986 adventure.', a: 'Laputa', alt: ['Castle in the Sky'] },
      { q: 'Monkey Punch\'s gentleman thief, grandson of a famous French burglar.', a: 'Lupin', alt: ['Lupin III', 'Lupin the Third'] },
      { q: 'The Fullmetal Alchemist homunculus with extendable spear-like fingers, named for a deadly sin.', a: 'Lust' },
      { q: 'The Spy x Family father whose spy codename is Twilight.', a: 'Loid', alt: ['Loid Forger'] },
    ],
    M: [
      { q: 'The legendary director of My Neighbor Totoro and Princess Mononoke (surname).', a: 'Miyazaki', alt: ['Hayao Miyazaki'] },
      { q: 'The scarf-wearing adoptive sister sworn to protect Eren.', a: 'Mikasa', alt: ['Mikasa Ackerman'] },
      { q: 'The bubblegum-pink magical menace released by the wizard Babidi.', a: 'Majin Buu', alt: ['Buu'] },
      { q: 'The legendary Uchiha who declares war on the ninja world and casts the Infinite Tsukuyomi.', a: 'Madara', alt: ['Madara Uchiha'] },
      { q: 'ONE\'s series about a repressed psychic schoolboy and his con-man mentor Reigen.', a: 'Mob Psycho 100', alt: ['Mob Psycho'] },
      { q: 'Kohei Horikoshi\'s series set in a world where eighty percent of people are born with superpowers.', a: 'My Hero Academia' },
      { q: 'Chainsaw Man\'s red-haired Control Devil, who keeps Denji on a very short leash.', a: 'Makima' },
      { q: 'Samurai Champloo\'s breakdance-fighting swordsman from the Ryukyu Islands.', a: 'Mugen' },
      { q: 'The progenitor of all demons in Demon Slayer, who hides among humans in elegant disguises.', a: 'Muzan', alt: ['Muzan Kibutsuji'] },
      { q: 'The genetically engineered psychic clone at the center of the first Pokemon movie.', a: 'Mewtwo' },
      { q: 'The Flame Alchemist colonel who aims to become Fuhrer, famously useless on rainy days.', a: 'Mustang', alt: ['Roy Mustang'] },
      { q: 'The pink-haired heroine of Shaft\'s 2011 magical-girl tragedy, whose contracts are brokered by the cat-like Kyubey.', a: 'Madoka' },
    ],
    N: [
      { q: 'Masashi Kishimoto\'s knucklehead ninja who dreams of leading his village.', a: 'Naruto' },
      { q: 'The demon-turned little sister carried around in a box, muzzled with bamboo.', a: 'Nezuko', alt: ['Nezuko Kamado'] },
      { q: 'The Straw Hats\' money-loving navigator who dreams of mapping the whole world.', a: 'Nami' },
      { q: 'Hunter x Hunter\'s life-energy power system, unlocked by opening one\'s aura nodes.', a: 'Nen' },
      { q: 'The secret organization commanded by Gendo Ikari to fight the Angels.', a: 'NERV' },
      { q: 'Miyazaki\'s 1984 heroine who glides over a toxic jungle to protect her valley.', a: 'Nausicaa', alt: ['Nausicaä'] },
      { q: 'The shapeshifting half-demon villain who manipulates events across Inuyasha.', a: 'Naraku' },
      { q: 'The color-changing sword forged from sun-drenched ore, the only weapon that permanently beheads demons.', a: 'Nichirin Blade', alt: ['Nichirin', 'Nichirin Sword'] },
      { q: 'Fairy Tail\'s fire dragon slayer, raised by the dragon Igneel.', a: 'Natsu', alt: ['Natsu Dragneel'] },
      { q: 'Jujutsu Kaisen\'s hammer-and-nails sorcerer from the countryside (first name).', a: 'Nobara', alt: ['Nobara Kugisaki'] },
    ],
    O: [
      { q: 'Eiichiro Oda\'s pirate saga, the best-selling manga series of all time.', a: 'One Piece' },
      { q: 'The series whose bald caped hero grew too strong to enjoy any fight.', a: 'One-Punch Man', alt: ['One Punch Man'] },
      { q: 'The Uchiha believed crushed by a boulder who returns as the masked Tobi.', a: 'Obito', alt: ['Obito Uchiha'] },
      { q: 'The snake sannin obsessed with immortality who marks Sasuke with a curse seal.', a: 'Orochimaru' },
      { q: 'The surname of the mangaka who has drawn One Piece weekly since 1997.', a: 'Oda', alt: ['Eiichiro Oda'] },
      { q: 'The Japanese term for an obsessive superfan of anime and manga.', a: 'Otaku' },
      { q: 'The stockpiled transferable power secretly passed down through nine holders.', a: 'One For All' },
    ],
    P: [
      { q: 'Ash Ketchum\'s electric partner, who famously refuses to stay in its ball.', a: 'Pikachu' },
      { q: 'Miyazaki\'s 1997 epic in which Ashitaka stands between an iron town and the wolf-raised girl San.', a: 'Princess Mononoke', alt: ['Mononoke'] },
      { q: 'The Namekian warrior who trains young Gohan and fuses with Kami.', a: 'Piccolo' },
      { q: 'The goldfish princess who longs to become human in Miyazaki\'s 2008 seaside tale.', a: 'Ponyo' },
      { q: 'The Rinnegan-eyed Akatsuki figurehead who flattens the Hidden Leaf demanding Naruto.', a: 'Pain', alt: ['Nagato'] },
      { q: 'U.A. High\'s motto, urging heroes to go further beyond.', a: 'Plus Ultra' },
      { q: 'Miyazaki\'s 1992 film about a cursed Italian seaplane ace with the face of a pig.', a: 'Porco Rosso' },
      { q: 'Hunter x Hunter\'s spider-tattooed band of thieves led by Chrollo.', a: 'Phantom Troupe' },
    ],
    Q: [
      { q: 'My Hero Academia\'s word for an innate superpower.', a: 'Quirk' },
      { q: 'The plague-spreading Beast Pirates all-star, a cyborg scientist who performs in Wano.', a: 'Queen' },
    ],
    R: [
      { q: 'Naruto\'s spiraling sphere of chakra, developed by the Fourth Hokage.', a: 'Rasengan' },
      { q: 'The apple-addicted shinigami who drops his notebook into the human world out of boredom.', a: 'Ryuk' },
      { q: 'Re:Zero\'s devoted blue-haired oni maid, twin sister of Ram.', a: 'Rem' },
      { q: 'The Straw Hats\' archaeologist, the only person alive who can read the Poneglyphs.', a: 'Robin', alt: ['Nico Robin'] },
      { q: 'The Flame Hashira who defends a train full of sleeping passengers and falls to the Upper Rank Akaza.', a: 'Rengoku', alt: ['Kyojuro Rengoku'] },
      { q: 'The quiet blue-haired First Child who pilots Evangelion Unit-00.', a: 'Rei', alt: ['Rei Ayanami'] },
      { q: 'The bowl-cut Leaf genin who can only use taijutsu and drops his leg weights to reveal blinding speed.', a: 'Rock Lee' },
    ],
    S: [
      { q: 'The last surviving Uchiha of Team 7, who defects to Orochimaru seeking power.', a: 'Sasuke', alt: ['Sasuke Uchiha'] },
      { q: 'The bored hero whose training was one hundred push-ups, sit-ups, squats and a ten kilometer run every day.', a: 'Saitama' },
      { q: 'The Bebop\'s jazz-loving bounty hunter with a fake eye and a fluid martial-arts style.', a: 'Spike', alt: ['Spike Spiegel'] },
      { q: 'The series in which self-styled mad scientist Okabe sends texts to the past with a modified microwave.', a: 'Steins;Gate' },
      { q: 'The first anime feature ever to win the Academy Award for Best Animated Feature.', a: 'Spirited Away' },
      { q: 'Jujutsu Kaisen\'s four-armed King of Curses, revived finger by finger.', a: 'Sukuna', alt: ['Ryomen Sukuna'] },
      { q: 'Usagi Tsukino\'s moonlit guardian identity in Naoko Takeuchi\'s classic.', a: 'Sailor Moon' },
      { q: 'The golden-haired legendary transformation first achieved by Goku in his rage against Frieza.', a: 'Super Saiyan' },
      { q: 'The Straw Hats\' chivalrous cook, who fights only with kicks to protect his hands.', a: 'Sanji' },
      { q: 'The weekly magazine that serialized Naruto, One Piece and Bleach simultaneously.', a: 'Shonen Jump', alt: ['Weekly Shonen Jump'] },
      { q: 'The Uchiha clan\'s red eye that copies techniques and casts illusions.', a: 'Sharingan' },
      { q: 'The X-marked Ishvalan who hunts state alchemists to avenge his people.', a: 'Scar' },
      { q: 'The reluctant Third Child ordered into Unit-01 by his cold father Gendo.', a: 'Shinji', alt: ['Shinji Ikari'] },
      { q: 'The wings-of-freedom military branch that explores beyond the walls.', a: 'Survey Corps', alt: ['Scout Regiment', 'Scouts'] },
    ],
    T: [
      { q: 'The giant furry forest spirit met by sisters Mei and Satsuki under a camphor tree.', a: 'Totoro' },
      { q: 'Demon Slayer\'s kind-hearted protagonist, a charcoal seller with a hanafuda-card earring.', a: 'Tanjiro', alt: ['Tanjiro Kamado'] },
      { q: 'The godfather of manga who created Astro Boy and Black Jack (surname).', a: 'Tezuka', alt: ['Osamu Tezuka'] },
      { q: 'The Surgeon of Death who allies with Luffy and wields the Op-Op Fruit.', a: 'Trafalgar Law', alt: ['Law'] },
      { q: 'The sword-carrying half-Saiyan who travels back in time to warn of the androids.', a: 'Trunks' },
      { q: 'Sui Ishida\'s series about a Japanese college student turned half flesh-eater after an organ transplant.', a: 'Tokyo Ghoul' },
      { q: 'The Straw Hats\' lion-figurehead second ship, successor to the Going Merry.', a: 'Thousand Sunny' },
      { q: 'The half-hot half-cold U.A. student who long refused to use his father\'s fire (surname).', a: 'Todoroki', alt: ['Shoto Todoroki', 'Shoto'] },
      { q: 'The legendary gambling medical ninja who becomes the Fifth Hokage.', a: 'Tsunade' },
      { q: 'The 1998 space western about a pacifist outlaw gunman worth sixty billion double dollars.', a: 'Trigun' },
      { q: 'Jessie, James and Meowth blast off again as members of this villainous group.', a: 'Team Rocket' },
    ],
    U: [
      { q: 'The Leaf clan famed for its copying eyes, wiped out by one of its own sons.', a: 'Uchiha' },
      { q: 'The silver-haired autonomous state Goku attains during the Tournament of Power.', a: 'Ultra Instinct' },
      { q: 'Deku\'s cheerful classmate whose quirk makes anything she touches float (surname).', a: 'Uraraka', alt: ['Ochaco Uraraka', 'Ochaco'] },
      { q: 'The long-nosed Straw Hat sniper whose tall tales keep coming true.', a: 'Usopp' },
      { q: 'The exiled genius inventor who runs a candy shop and mentors Ichigo in Bleach (surname).', a: 'Urahara', alt: ['Kisuke Urahara'] },
      { q: 'Naruto\'s clan surname, inherited from his mother\'s whirlpool village.', a: 'Uzumaki' },
    ],
    V: [
      { q: 'The prideful Saiyan prince who begins as an invader and ends up a family man on Earth.', a: 'Vegeta' },
      { q: 'Trigun\'s donut-loving pacifist gunman known as the Humanoid Typhoon.', a: 'Vash', alt: ['Vash the Stampede'] },
      { q: 'Kyoto Animation\'s drama about an ex-child-soldier who ghostwrites letters to learn what love means.', a: 'Violet Evergarden' },
      { q: 'Makoto Yukimura\'s Viking epic following Thorfinn from revenge toward a land without war.', a: 'Vinland Saga' },
    ],
    W: [
      { q: 'The mustachioed pirate emperor called the strongest man in the world, who dies standing at Marineford.', a: 'Whitebeard' },
      { q: 'The outermost of the three great walls, breached in Attack on Titan\'s first episode.', a: 'Wall Maria' },
      { q: 'Beerus\'s blue-skinned angel attendant, an even stronger martial arts teacher.', a: 'Whis' },
      { q: 'The isolationist samurai country where Luffy\'s alliance finally topples Kaido.', a: 'Wano' },
    ],
    Y: [
      { q: 'Makoto Shinkai\'s 2016 body-swapping hit about Taki and Mitsuha.', a: 'Your Name', alt: ['Kimi no Na wa'] },
      { q: 'The family name shared by Death Note\'s genius protagonist and his police chief father.', a: 'Yagami' },
      { q: 'The desert-bandit-turned-baseball-player whose crater death pose became a meme.', a: 'Yamcha' },
      { q: 'Spy x Family\'s gentle mother, secretly the assassin called Thorn Princess.', a: 'Yor', alt: ['Yor Forger'] },
      { q: 'The delinquent spirit detective revived after dying to save a child, in Togashi\'s earlier hit.', a: 'Yusuke', alt: ['Yusuke Urameshi'] },
      { q: 'Noragami\'s stray god of calamity who grants any wish for five yen.', a: 'Yato' },
    ],
    Z: [
      { q: 'The green-haired swordsman who fights with three blades and gets lost walking in a straight line.', a: 'Zoro', alt: ['Roronoa Zoro'] },
      { q: 'The cowardly lightning-breath user who only fights while fast asleep.', a: 'Zenitsu', alt: ['Zenitsu Agatsuma'] },
      { q: 'Darling in the Franxx\'s horned pink-haired pilot who calls her partner darling.', a: 'Zero Two' },
      { q: 'Eren\'s half-brother, the Beast Titan with a devastating throwing arm.', a: 'Zeke', alt: ['Zeke Yeager'] },
    ],
  },
};
