import type { RawPack } from '../core/packs';

export const architectureLandmarksPack: RawPack = {
  id: 'architecture-landmarks',
  name: 'Architecture and Landmarks',
  description: 'Towers, bridges, temples, palaces, skyscrapers, architects and world wonders.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🗼',
  accent: '#0f766e',
  letters: {
    A: [
      { q: 'Red-walled Nasrid palace complex on the hill above Granada.', a: 'Alhambra' },
      { q: 'Vast Khmer temple complex in Cambodia, the largest religious monument on earth.', a: 'Angkor Wat', alt: ['Angkor'] },
      { q: 'The rocky citadel above Athens crowned by the Parthenon.', a: 'Acropolis' },
      { q: 'Roman channel carried on tiers of arches to bring water to a city.', a: 'Aqueduct' },
      { q: 'Curved structural opening that carries load out to its sides, perfected by Rome.', a: 'Arch' },
      { q: 'Central top-lit courtyard space at the heart of a Roman house or a modern hotel.', a: 'Atrium' },
      { q: 'Napoleonic monument standing at the top of the Champs-Elysees.', a: 'Arc de Triomphe' },
      { q: 'Catalan architect of Casa Batllo and Park Guell.', a: 'Antoni Gaudi', alt: ['Gaudi', 'Gaudí'] },
      { q: 'Brussels landmark of nine linked steel spheres built for the 1958 world fair.', a: 'Atomium' },
      { q: 'The semicircular recess at the altar end of a church.', a: 'Apse' },
      { q: 'Oval Roman arena with tiered seating running all the way round.', a: 'Amphitheatre', alt: ['Amphitheater'] },
      { q: 'Squared, smoothly dressed masonry laid in even courses.', a: 'Ashlar' },
      { q: 'A run of arches carried on piers or columns.', a: 'Arcade' },
      { q: 'Finnish modernist architect and furniture designer, famous for bent plywood.', a: 'Alvar Aalto', alt: ['Aalto'] },
      { q: 'Egyptian rock-cut temples of Ramesses II moved uphill to escape a rising reservoir.', a: 'Abu Simbel' },
      { q: 'Emirate whose Sheikh Zayed Grand Mosque holds the largest hand-knotted carpet.', a: 'Abu Dhabi' },
    ],
    B: [
      { q: 'Nickname of the great bell, and now the clock tower, at Westminster.', a: 'Big Ben' },
      { q: "Dubai skyscraper that has held the world's height record since 2010.", a: 'Burj Khalifa' },
      { q: 'Masonry pier built against a wall to take the outward thrust of a vault.', a: 'Buttress' },
      { q: 'Purpose-built Brazilian capital laid out by Lucio Costa in the 1950s.', a: 'Brasilia' },
      { q: 'Postwar style of raw exposed concrete and blunt massive forms.', a: 'Brutalism' },
      { q: 'Roman hall type that became the standard plan of early Christian churches.', a: 'Basilica' },
      { q: 'Istanbul mosque of 1616 whose Iznik tiles give it a colourful nickname.', a: 'Blue Mosque', alt: ['Sultan Ahmed Mosque'] },
      { q: 'East River crossing of 1883, the first steel-wire suspension span of its kind.', a: 'Brooklyn Bridge' },
      { q: 'London home of the British monarch since 1837.', a: 'Buckingham Palace' },
      { q: 'Basque city transformed by a titanium-clad Guggenheim museum.', a: 'Bilbao' },
      { q: 'Ninth-century Buddhist monument of stacked stone terraces on Java.', a: 'Borobudur' },
      { q: 'Sail-shaped Dubai hotel standing on its own artificial island.', a: 'Burj Al Arab' },
      { q: 'Lebanese site with the enormous Roman temple of Jupiter.', a: 'Baalbek' },
      { q: 'Manama landmark of 1949 marking the entrance to the old customs area.', a: 'Bab al-Bahrain' },
    ],
    C: [
      { q: "Rome's giant oval arena where gladiators fought.", a: 'Colosseum' },
      { q: 'New York tower of 1930 with a stainless steel crown of sunbursts.', a: 'Chrysler Building' },
      { q: 'Mix of cement, aggregate and water that the Romans used for huge domes.', a: 'Concrete' },
      { q: 'Beam supported at one end only, projecting out into space.', a: 'Cantilever' },
      { q: 'The most ornate classical order, its capital carved with acanthus leaves.', a: 'Corinthian' },
      { q: 'French cathedral renowned for its 12th century blue stained glass.', a: 'Chartres' },
      { q: 'German Gothic cathedral with twin spires, finished in 1880 after six centuries.', a: 'Cologne Cathedral', alt: ['Cologne'] },
      { q: "Toronto's concrete communications landmark with a glass floor.", a: 'CN Tower' },
      { q: 'Art Deco statue with outstretched arms above Rio de Janeiro.', a: 'Christ the Redeemer' },
      { q: 'Small rounded structure crowning a roof, often lantern-like.', a: 'Cupola' },
      { q: 'Washington building with a cast-iron dome where Congress meets.', a: 'Capitol' },
      { q: 'Mayan site in Yucatan dominated by the stepped pyramid of Kukulcan.', a: 'Chichen Itza' },
      { q: 'Projecting moulded ledge that crowns a wall or a classical order.', a: 'Cornice' },
      { q: 'Outer weatherproof skin fixed onto a structural frame.', a: 'Cladding' },
      { q: 'Vaulted chamber beneath a church floor used for burials.', a: 'Crypt' },
      { q: 'Barcelona apartment block with a wavy stone frontage and twisted chimneys.', a: 'Casa Mila', alt: ['La Pedrera'] },
    ],
    D: [
      { q: 'Curved roof shape produced by rotating an arch about its centre.', a: 'Dome' },
      { q: 'The Italian word for a city cathedral, most famously the one in Florence.', a: 'Duomo' },
      { q: "Pink Gothic seat of Venice's rulers beside Saint Mark's.", a: "Doge's Palace" },
      { q: 'Style of fragmented, warped and colliding forms associated with Gehry and Hadid.', a: 'Deconstructivism' },
      { q: 'Span that lifts to block the entrance to a castle.', a: 'Drawbridge' },
      { q: 'Indian capital whose Rashtrapati Bhavan was completed in 1929.', a: 'Delhi', alt: ['New Delhi'] },
      { q: 'Window set upright in a sloping roof.', a: 'Dormer' },
      { q: 'The plainest and sturdiest of the Greek orders, its capital a simple cushion.', a: 'Doric' },
      { q: 'Emirati landmark of 2018 shaped like a giant rectangular picture surround.', a: 'Dubai Frame' },
    ],
    E: [
      { q: 'Wrought-iron Paris landmark built for the 1889 world fair.', a: 'Eiffel Tower' },
      { q: 'New York skyscraper of 1931 that held the height record for forty years.', a: 'Empire State Building' },
      { q: 'Vast granite palace and monastery near Madrid built by Philip II.', a: 'El Escorial', alt: ['Escorial'] },
      { q: 'Ancient Anatolian city whose Library of Celsus facade still stands.', a: 'Ephesus' },
      { q: 'The horizontal band of architrave, frieze and cornice above classical columns.', a: 'Entablature' },
      { q: 'Fortress on an extinct volcanic plug above a Scottish capital.', a: 'Edinburgh Castle' },
      { q: 'The overhanging lower edge of a roof.', a: 'Eaves' },
      { q: 'Cornish attraction of linked domes made of hexagonal cushions.', a: 'Eden Project' },
      { q: 'Finnish-American architect of the TWA Flight Center at Idlewild.', a: 'Eero Saarinen', alt: ['Saarinen'] },
    ],
    F: [
      { q: 'American architect of Taliesin and the spiral New York museum.', a: 'Frank Lloyd Wright', alt: ['Wright'] },
      { q: 'Arched external prop that carries roof thrust across an aisle to a distant pier.', a: 'Flying buttress' },
      { q: "Beijing's walled imperial palace complex of almost a thousand buildings.", a: 'Forbidden City' },
      { q: "British architect of the Gherkin and of the Reichstag's glass dome (surname).", a: 'Foster', alt: ['Norman Foster'] },
      { q: 'House that Frank Lloyd Wright cantilevered over a Pennsylvania waterfall.', a: 'Fallingwater' },
      { q: 'Sculpted or painted horizontal band running along the upper part of a wall.', a: 'Frieze' },
      { q: 'Open civic square at the centre of a Roman town.', a: 'Forum' },
      { q: 'Abandoned Mughal capital of red sandstone built near Agra by Akbar.', a: 'Fatehpur Sikri' },
    ],
    G: [
      { q: 'Medieval style of pointed arches, ribbed vaults and soaring stained glass.', a: 'Gothic' },
      { q: 'Orange-red suspension crossing at the mouth of San Francisco Bay.', a: 'Golden Gate Bridge' },
      { q: 'Nickname of the pickle-shaped London tower at 30 St Mary Axe.', a: 'Gherkin' },
      { q: 'Defensive barrier thousands of miles long across northern China.', a: 'Great Wall' },
      { q: 'Egyptian plateau where the tombs of Khufu, Khafre and Menkaure stand.', a: 'Giza' },
      { q: 'Carved waterspout on a medieval church, often shaped as a grotesque beast.', a: 'Gargoyle' },
      { q: 'Stainless steel catenary curve rising 630 feet over St Louis.', a: 'Gateway Arch' },
      { q: 'Hard speckled igneous stone used for kerbs and monuments.', a: 'Granite' },
      { q: 'The triangular upper part of a wall beneath a pitched roof.', a: 'Gable' },
      { q: "Canadian-American architect of Los Angeles's Walt Disney Concert Hall.", a: 'Frank Gehry', alt: ['Gehry'] },
      { q: 'The largest mud-brick building in the world, standing in Mali.', a: 'Great Mosque of Djenne', alt: ['Djenne'] },
    ],
    H: [
      { q: 'Istanbul monument raised by Justinian as a church, later converted to a mosque.', a: 'Hagia Sophia' },
      { q: 'Arch-gravity barrier on the Colorado River completed in 1936.', a: 'Hoover Dam' },
      { q: 'The wonder of Babylon that may never have existed at all.', a: 'Hanging Gardens' },
      { q: "Iraqi-British architect of fluid curving forms and Baku's Heydar Aliyev Center (surname).", a: 'Hadid', alt: ['Zaha Hadid'] },
      { q: 'Hall whose roof rests on dense rows of columns, as at Karnak.', a: 'Hypostyle' },
      { q: "Japan's finest surviving castle, nicknamed the white heron.", a: 'Himeji Castle', alt: ['Himeji'] },
      { q: 'Roman frontier barrier built across northern England.', a: "Hadrian's Wall" },
      { q: 'Japanese temple said to hold the oldest wooden building on earth.', a: 'Horyu-ji', alt: ['Horyuji'] },
    ],
    I: [
      { q: 'Classical order recognised by the paired scrolls of its capital.', a: 'Ionic' },
      { q: 'Metal cast into columns and beams that made Victorian train sheds possible.', a: 'Iron' },
      { q: 'Dome of snow blocks built for shelter by Inuit hunters.', a: 'Igloo' },
      { q: 'Japanese shrine whose vermilion gateway stands out in the sea.', a: 'Itsukushima', alt: ['Miyajima'] },
      { q: 'Vaulted hall walled on three sides and open on the fourth, typical of Persian mosques.', a: 'Iwan' },
      { q: 'Shropshire span of 1779, the first major structure cast in that metal.', a: 'Iron Bridge' },
    ],
    J: [
      { q: 'Saudi skyscraper begun in 2013 and intended to pass one kilometre in height.', a: 'Jeddah Tower' },
      { q: 'Domed Washington monument honouring the third US president.', a: 'Jefferson Memorial' },
      { q: 'Jordanian city with remarkably complete Roman streets and gateways.', a: 'Jerash' },
      { q: 'Indian city of the Hawa Mahal and a pink-washed old quarter.', a: 'Jaipur' },
      { q: "Delhi's largest mosque, built by Shah Jahan in the 1650s.", a: 'Jama Masjid' },
    ],
    K: [
      { q: "Cube-shaped structure at the centre of Mecca's Grand Mosque.", a: 'Kaaba', alt: ['Kabah'] },
      { q: 'The wedge-shaped block at the crown of an arch that locks it together.', a: 'Keystone' },
      { q: 'Enormous Egyptian temple complex near Luxor dedicated to Amun.', a: 'Karnak' },
      { q: 'Fortified Moscow citadel of towers, palaces and cathedrals.', a: 'Kremlin' },
      { q: 'Malaysian capital whose skyline is dominated by twin 88-storey towers.', a: 'Kuala Lumpur' },
      { q: 'Kyoto pavilion sheathed in gold leaf beside a mirror pond.', a: 'Kinkaku-ji', alt: ['Kinkakuji'] },
      { q: 'Three spiked spheres on a Gulf capital waterfront, opened in 1979.', a: 'Kuwait Towers' },
    ],
    L: [
      { q: 'Glass entrance structure added to a Paris museum courtyard in 1989.', a: 'Louvre Pyramid', alt: ['Louvre'] },
      { q: 'Swiss-French pioneer of modernism who wrote Towards a New Architecture.', a: 'Le Corbusier', alt: ['Corbusier'] },
      { q: 'Ancient wonder that guided ships safely into an Egyptian harbour.', a: 'Lighthouse of Alexandria', alt: ['Pharos'] },
      { q: 'The horizontal beam spanning the top of a door or window opening.', a: 'Lintel' },
      { q: 'Italian bell tower whose sinking foundations left it tilted.', a: 'Leaning Tower of Pisa', alt: ['Leaning Tower', 'Tower of Pisa'] },
      { q: "British architect who planned New Delhi's imperial avenues (surname).", a: 'Lutyens', alt: ['Edwin Lutyens'] },
      { q: 'Gallery open along one side through columns or arches.', a: 'Loggia' },
      { q: 'City of London insurance headquarters by Richard Rogers with its services on the outside.', a: "Lloyd's building", alt: ["Lloyd's of London"] },
    ],
    M: [
      { q: "Inca citadel on a ridge high above Peru's Urubamba valley.", a: 'Machu Picchu' },
      { q: 'Slender tower from which the call to prayer is given.', a: 'Minaret' },
      { q: 'Monumental tomb, named after a ruler buried at Halicarnassus.', a: 'Mausoleum' },
      { q: 'Niche in a mosque wall showing the direction of Mecca.', a: 'Mihrab' },
      { q: 'French cable-stayed crossing with the tallest bridge piers in the world.', a: 'Millau Viaduct', alt: ['Millau'] },
      { q: 'Architect of the Barcelona Pavilion who said that less is more.', a: 'Mies van der Rohe', alt: ['Mies'] },
      { q: 'The largest mosque in the world, wrapped around the Kaaba.', a: 'Masjid al-Haram', alt: ['Grand Mosque'] },
      { q: 'Rio stadium that hosted the 1950 and 2014 World Cup finals.', a: 'Maracana', alt: ['Maracanã'] },
      { q: 'Water-filled ditch dug around a fortress for defence.', a: 'Moat' },
      { q: 'Steep four-sided roof with a second shallower slope, named after a French architect.', a: 'Mansard' },
      { q: 'Singapore resort of three towers carrying a rooftop pool shaped like a ship.', a: 'Marina Bay Sands' },
    ],
    N: [
      { q: 'Paris cathedral on the Ile de la Cite, badly damaged by fire in 2019.', a: 'Notre-Dame', alt: ['Notre Dame'] },
      { q: 'Bavarian fantasy castle built for Ludwig II that inspired Disney.', a: 'Neuschwanstein' },
      { q: 'The long central body of a church where the congregation sits.', a: 'Nave' },
      { q: "Brazilian architect of Brasilia's white curving civic buildings (surname).", a: 'Niemeyer', alt: ['Oscar Niemeyer'] },
      { q: "Beijing's 2008 Olympic venue nicknamed the bird's nest.", a: 'National Stadium' },
    ],
    O: [
      { q: 'Tall four-sided tapering stone shaft with a pointed cap.', a: 'Obelisk' },
      { q: "The round opening at the top of the Pantheon's dome.", a: 'Oculus' },
      { q: 'New York tower completed in 2014 on the site of the twin towers.', a: 'One World Trade Center', alt: ['Freedom Tower'] },
      { q: 'Bulbous bulb-shaped roof typical of Russian churches.', a: 'Onion dome' },
      { q: 'Moscow broadcasting tower, the tallest free-standing structure in Europe.', a: 'Ostankino Tower', alt: ['Ostankino'] },
    ],
    P: [
      { q: 'Temple to Athena that crowns the citadel of Athens.', a: 'Parthenon' },
      { q: 'Roman rotunda with the largest unreinforced concrete dome ever built.', a: 'Pantheon' },
      { q: 'Nabataean city in Jordan whose Treasury is carved into rose-red rock.', a: 'Petra' },
      { q: 'Tiered tower with multiple overhanging eaves found at East Asian temples.', a: 'Pagoda' },
      { q: 'Four-sided tomb shape built for the kings of ancient Egypt.', a: 'Pyramid' },
      { q: 'Roofed porch of columns forming the entrance front of a temple.', a: 'Portico' },
      { q: 'The highest international award in architecture, first given in 1979.', a: 'Pritzker Prize', alt: ['Pritzker'] },
      { q: 'Venetian Renaissance architect whose villas inspired an English country style.', a: 'Palladio', alt: ['Andrea Palladio'] },
      { q: 'Malaysian twin skyscrapers linked by a skybridge on the 41st floor.', a: 'Petronas Towers', alt: ['Petronas'] },
      { q: 'Chinese-American architect of the glass entrance to a Paris museum (surname).', a: 'Pei', alt: ['I. M. Pei'] },
      { q: 'The triangular gable above a classical portico.', a: 'Pediment' },
      { q: 'Flattened column attached to a wall purely for decoration.', a: 'Pilaster' },
      { q: 'Three-tiered Roman water bridge over a river in southern France.', a: 'Pont du Gard' },
    ],
    Q: [
      { q: 'Brick tower in Delhi begun in 1193, the tallest of its kind in the world.', a: 'Qutb Minar', alt: ['Qutub Minar'] },
      { q: 'Dressed stones that strengthen and decorate the external corner of a wall.', a: 'Quoin' },
      { q: 'Rectangular courtyard enclosed by the buildings of a college.', a: 'Quadrangle', alt: ['Quad'] },
    ],
    R: [
      { q: "Stone arch over Venice's Grand Canal, lined with shops.", a: 'Rialto Bridge', alt: ['Rialto'] },
      { q: 'Round building or room, usually covered by a dome.', a: 'Rotunda' },
      { q: 'Berlin parliament building topped by a walkable glass dome.', a: 'Reichstag' },
      { q: 'Pre-Gothic medieval style of thick walls, round arches and small windows.', a: 'Romanesque' },
      { q: 'Circular tracery opening filled with stained glass in a Gothic front.', a: 'Rose window' },
      { q: "Mughal sandstone citadel in Delhi from which India's prime minister addresses the nation.", a: 'Red Fort', alt: ['Lal Qila'] },
      { q: "Italian architect of the Pompidou complex and of London's tallest tower.", a: 'Renzo Piano', alt: ['Piano'] },
      { q: 'Masonry cut with deep joints and rough faces to give a heavy look.', a: 'Rustication' },
    ],
    S: [
      { q: 'Unfinished Barcelona basilica begun in 1882 with towers for the apostles.', a: 'Sagrada Familia' },
      { q: 'Concert venue of white shell roofs on the Bennelong Point peninsula.', a: 'Sydney Opera House' },
      { q: 'Prehistoric ring of standing stones on Salisbury Plain.', a: 'Stonehenge' },
      { q: 'Tapering point rising from the top of a church tower.', a: 'Spire' },
      { q: 'Term coined in 1880s Chicago for a very tall steel-framed building.', a: 'Skyscraper' },
      { q: 'Copper figure given by France, standing in New York harbour.', a: 'Statue of Liberty' },
      { q: 'Glass splinter-shaped London tower finished in 2012.', a: 'The Shard', alt: ['Shard'] },
      { q: 'Moscow church of swirling coloured domes on Red Square.', a: "Saint Basil's Cathedral", alt: ["St Basil's"] },
      { q: 'Vatican church whose dome was designed by Michelangelo.', a: "Saint Peter's Basilica", alt: ["St Peter's"] },
      { q: 'Plaster render applied to an outside wall and often moulded into decoration.', a: 'Stucco' },
      { q: "Limestone lion with a pharaoh's head guarding the Giza plateau.", a: 'Sphinx' },
      { q: 'Solid mound-like Buddhist reliquary structure.', a: 'Stupa' },
      { q: 'Yemeni walled town of mud-brick high-rises called the Manhattan of the desert.', a: 'Shibam' },
    ],
    T: [
      { q: 'White marble tomb Shah Jahan built at Agra for his wife.', a: 'Taj Mahal' },
      { q: 'London bascule crossing with two Gothic-style towers and high walkways.', a: 'Tower Bridge' },
      { q: 'The largest power station in the world, a concrete wall across the Yangtze.', a: 'Three Gorges Dam' },
      { q: 'Baroque Roman waterworks where visitors toss coins over their shoulder.', a: 'Trevi Fountain', alt: ['Trevi'] },
      { q: 'Stone ribwork that divides and supports a Gothic window.', a: 'Tracery' },
      { q: "Broadcasting mast that has been Japan's tallest structure since 2012.", a: 'Tokyo Skytree', alt: ['Skytree'] },
      { q: 'Rigid framework of triangles used to span a roof or a bridge.', a: 'Truss' },
      { q: 'Japanese shrine gateway of two uprights and two crossbars.', a: 'Torii' },
      { q: 'The arms that cross a church nave to form a cruciform plan.', a: 'Transept' },
      { q: 'English style of black timbers, brick and tall chimneys under a sixteenth-century dynasty.', a: 'Tudor' },
      { q: 'Ancient wonder at Ephesus that was rebuilt after an arsonist burned it.', a: 'Temple of Artemis' },
      { q: 'Norman fortress beside the Thames that guards the Crown Jewels.', a: 'Tower of London' },
    ],
    U: [
      { q: "Danish architect who won the 1957 competition for Sydney's harbour concert hall (surname).", a: 'Utzon', alt: ['Jorn Utzon'] },
      { q: 'Damascus mosque built in the early eighth century on a Roman temple site.', a: 'Umayyad Mosque' },
      { q: 'Sumerian city whose great stepped platform still stands in southern Iraq.', a: 'Ur' },
    ],
    V: [
      { q: 'Arched ceiling of stone or brick spanning a space.', a: 'Vault' },
      { q: 'Palace of the Sun King outside Paris, with its Hall of Mirrors.', a: 'Versailles' },
      { q: 'Roman writer whose ten books demanded firmness, commodity and delight.', a: 'Vitruvius' },
      { q: 'Long bridge of arches carrying a road or railway over a valley.', a: 'Viaduct' },
      { q: 'The spiral scroll carved on an Ionic capital.', a: 'Volute' },
      { q: 'White house at Poissy raised on slender pillars, a manifesto of modern living.', a: 'Villa Savoye' },
    ],
    W: [
      { q: 'London stadium rebuilt in 2007 beneath a 133-metre steel arch.', a: 'Wembley' },
      { q: 'London church where English monarchs are crowned.', a: 'Westminster Abbey' },
      { q: 'Chicago skyscraper of nine bundled tubes, long known by a retailer name.', a: 'Willis Tower', alt: ['Sears Tower'] },
      { q: 'Neoclassical Washington residence at 1600 Pennsylvania Avenue.', a: 'White House' },
    ],
    X: [
      { q: 'Chinese city ringed by Ming walls, close to the buried terracotta warriors.', a: "Xi'an", alt: ['Xian'] },
    ],
    Y: [
      { q: 'Portable round felt-covered dwelling of Central Asian herders.', a: 'Yurt', alt: ['Ger'] },
      { q: 'Architect of the original World Trade Center twin towers.', a: 'Minoru Yamasaki', alt: ['Yamasaki'] },
    ],
    Z: [
      { q: 'Stepped Mesopotamian temple platform built of mud brick.', a: 'Ziggurat' },
      { q: 'Ancient wonder that was a giant seated ivory and gold figure at Olympia.', a: 'Statue of Zeus', alt: ['Zeus'] },
    ],
  },
};
