import type { RawPack } from '../core/packs';

export const artPaintersPack: RawPack = {
  id: 'art-painters',
  name: 'Art and Painters',
  description: 'Painters, masterpieces, movements, museums, pigments and famous heists.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎨',
  accent: '#a21caf',
  letters: {
    A: [
      { q: 'The postwar New York movement of Pollock and Rothko working on huge gestural canvases.', a: 'Abstract Expressionism' },
      { q: 'Fast-drying synthetic polymer paint that artists took up in the 1950s.', a: 'Acrylic', alt: ['Acrylics'] },
      { q: 'The decorative style around 1900 marked by flowing plant-like lines, seen in Paris Metro entrances.', a: 'Art Nouveau' },
      { q: 'The geometric, luxurious style of the 1920s and 1930s seen in the Chrysler Building spire.', a: 'Art Deco' },
      { q: 'American photographer famous for black-and-white images of Yosemite.', a: 'Ansel Adams' },
      { q: 'Pop artist who silkscreened soup cans and ran a New York studio called the Factory.', a: 'Andy Warhol', alt: ['Warhol'] },
      { q: 'Baroque painter, daughter of Orazio, known for a ferocious Judith Slaying Holofernes.', a: 'Artemisia Gentileschi', alt: ['Gentileschi'] },
      { q: 'German Renaissance master engraver who made Melencolia I and the Praying Hands study.', a: 'Albrecht Durer', alt: ['Durer', 'Albrecht Dürer', 'Dürer'] },
      { q: 'Fossilised tree resin carved into beads and inlays.', a: 'Amber' },
      { q: 'Etching technique using powdered resin to bite broad tonal areas into a plate.', a: 'Aquatint' },
      { q: "Sculptor behind Chicago's mirrored bean-shaped Cloud Gate.", a: 'Anish Kapoor', alt: ['Kapoor'] },
      { q: 'Southern French town where van Gogh painted his yellow house and his sunflowers.', a: 'Arles' },
      { q: "American realist who painted Christina's World.", a: 'Andrew Wyeth', alt: ['Wyeth'] },
      { q: 'Devotional subject showing the angel Gabriel telling Mary she will bear a son.', a: 'Annunciation' },
    ],
    B: [
      { q: 'The dramatic, theatrical European style of the 17th century, full of movement and strong light.', a: 'Baroque' },
      { q: 'German school founded by Walter Gropius in 1919 that fused craft with industrial design.', a: 'Bauhaus' },
      { q: 'Florentine painter of The Birth of Venus and Primavera.', a: 'Botticelli', alt: ['Sandro Botticelli'] },
      { q: 'The copper and tin alloy most often cast into statues.', a: 'Bronze' },
      { q: 'Anonymous British street artist whose Girl with Balloon shredded itself at auction.', a: 'Banksy' },
      { q: "The name given to Picasso's melancholy works of 1901 to 1904, dominated by one cool colour.", a: 'Blue Period' },
      { q: 'Romanian sculptor of Bird in Space, famous for radically simplified forms.', a: 'Brancusi', alt: ['Constantin Brancusi'] },
      { q: 'Flemish painter of peasant weddings, hunters in the snow and the Tower of Babel.', a: 'Bruegel', alt: ['Pieter Bruegel', 'Brueghel'] },
      { q: 'Baroque sculptor of Apollo and Daphne and the Ecstasy of Saint Teresa.', a: 'Bernini', alt: ['Gian Lorenzo Bernini'] },
      { q: 'Carving that projects only slightly from its background surface.', a: 'Bas-relief', alt: ['Bas relief', 'Low relief'] },
      { q: 'New York painter who moved from tagging the streets as SAMO to celebrated crowned figures.', a: 'Basquiat', alt: ['Jean-Michel Basquiat'] },
      { q: 'Irish-born painter of screaming popes and writhing triptych figures (surname).', a: 'Bacon', alt: ['Francis Bacon'] },
    ],
    C: [
      { q: 'The movement Picasso and Braque invented, breaking objects into flat geometric planes.', a: 'Cubism' },
      { q: 'Italian master of harsh light and deep shadow who fled Rome after killing a man.', a: 'Caravaggio' },
      { q: 'The stretched woven fabric that replaced wooden panels as the usual painting support.', a: 'Canvas' },
      { q: 'The Italian term for the strong contrast of light and dark modelling in a picture.', a: 'Chiaroscuro' },
      { q: 'Post-Impressionist who painted Mont Sainte-Victoire again and again and is called the father of modern art.', a: 'Cezanne', alt: ['Paul Cezanne', 'Cézanne'] },
      { q: 'Belarusian-French painter of floating lovers, fiddlers and dreamlike village scenes.', a: 'Chagall', alt: ['Marc Chagall'] },
      { q: 'Burnt willow or vine sticks used for soft black drawing.', a: 'Charcoal' },
      { q: 'English painter of Suffolk countryside and The Hay Wain (surname).', a: 'Constable', alt: ['John Constable'] },
      { q: 'Crimson dye made from crushed insects farmed on cactus in Mexico.', a: 'Cochineal' },
      { q: 'Artist who with Jeanne-Claude wrapped the Reichstag in silver fabric.', a: 'Christo' },
      { q: 'Technique of gluing paper, fabric and found scraps onto a surface.', a: 'Collage' },
      { q: 'American Impressionist working in Paris, known for tender mother-and-child scenes (surname).', a: 'Cassatt', alt: ['Mary Cassatt'] },
      { q: 'French Realist who painted The Stone Breakers and A Burial at Ornans.', a: 'Courbet', alt: ['Gustave Courbet'] },
      { q: 'Soft earth material shaped by a potter and hardened by firing.', a: 'Clay' },
      { q: 'Advertising tycoon whose collecting launched the Young British Artists.', a: 'Charles Saatchi', alt: ['Saatchi'] },
    ],
    D: [
      { q: 'Spanish Surrealist of melting clocks and an outrageous waxed moustache.', a: 'Dali', alt: ['Salvador Dali', 'Salvador Dalí'] },
      { q: 'The anti-art movement born at the Cabaret Voltaire in Zurich during the First World War.', a: 'Dada' },
      { q: 'French Impressionist obsessed with ballet dancers and racehorses.', a: 'Degas', alt: ['Edgar Degas'] },
      { q: 'Romantic painter of Liberty Leading the People.', a: 'Delacroix', alt: ['Eugene Delacroix'] },
      { q: 'Florentine sculptor of the first free-standing nude bronze of the Renaissance.', a: 'Donatello' },
      { q: 'Artist who submitted a urinal titled Fountain to a 1917 exhibition.', a: 'Duchamp', alt: ['Marcel Duchamp'] },
      { q: 'A picture made of two hinged panels.', a: 'Diptych' },
      { q: 'Intaglio method that scratches straight into the plate, leaving a burr and a velvety line.', a: 'Drypoint' },
      { q: 'Sienese painter of the great Maesta altarpiece.', a: 'Duccio' },
    ],
    E: [
      { q: 'The wooden stand that holds a canvas upright while an artist works.', a: 'Easel' },
      { q: 'Medium binding pigment with yolk, standard before oil took over.', a: 'Egg tempera', alt: ['Tempera'] },
      { q: 'Printmaking method in which acid bites lines into a wax-coated metal plate.', a: 'Etching' },
      { q: 'Dutch graphic artist of impossible staircases and tessellating birds.', a: 'Escher', alt: ['M. C. Escher', 'MC Escher'] },
      { q: 'The early 20th century German movement that distorted form and colour to convey raw emotion.', a: 'Expressionism' },
      { q: 'Cretan-born painter of elongated saints who worked in Toledo, Spain.', a: 'El Greco' },
      { q: 'British artist who exhibited her own unmade bed (surname).', a: 'Emin', alt: ['Tracey Emin'] },
    ],
    F: [
      { q: 'Technique of painting into wet plaster so the colour becomes part of the wall.', a: 'Fresco' },
      { q: 'The movement whose wild unnatural colour earned its members a nickname meaning wild beasts.', a: 'Fauvism' },
      { q: 'Mexican painter of unflinching self-portraits, married to Diego Rivera.', a: 'Frida Kahlo', alt: ['Kahlo'] },
      { q: 'Italian city of the Uffizi and the cradle of the Renaissance.', a: 'Florence' },
      { q: 'Italian movement launched in 1909 glorifying speed, machines and modern city life.', a: 'Futurism' },
      { q: 'Rococo painter of The Swing.', a: 'Fragonard' },
      { q: 'Italian artist who slashed his monochrome canvases with a blade (surname).', a: 'Fontana', alt: ['Lucio Fontana'] },
      { q: 'Jeweller to the tsars, famous for ornate imperial eggs.', a: 'Faberge', alt: ['Fabergé'] },
    ],
    G: [
      { q: 'Opaque water-based paint, like watercolour with added white filler.', a: 'Gouache' },
      { q: 'Museum whose New York spiral was designed by Frank Lloyd Wright.', a: 'Guggenheim' },
      { q: 'Post-Impressionist who left France for Tahiti and painted its people in flat bold colour.', a: 'Gauguin', alt: ['Paul Gauguin'] },
      { q: "Picasso's huge grey mural protesting the 1937 bombing of a Basque town.", a: 'Guernica' },
      { q: 'White chalky ground brushed onto a panel to prepare it for paint.', a: 'Gesso' },
      { q: 'Spanish court painter of the Black Paintings and The Third of May 1808.', a: 'Goya', alt: ['Francisco Goya'] },
      { q: 'Late medieval Florentine who frescoed the Scrovegni Chapel in Padua.', a: 'Giotto' },
      { q: 'Applying wafer-thin leaves of gold to a surface.', a: 'Gilding' },
      { q: 'Swiss sculptor of extremely thin, elongated walking figures.', a: 'Giacometti', alt: ['Alberto Giacometti'] },
      { q: 'Boston institution robbed in 1990 of thirteen works that are still missing.', a: 'Gardner Museum', alt: ['Isabella Stewart Gardner Museum'] },
      { q: 'American writer whose Paris salon championed early Picasso and Matisse.', a: 'Gertrude Stein', alt: ['Stein'] },
    ],
    H: [
      { q: 'Japanese artist of The Great Wave off Kanagawa.', a: 'Hokusai' },
      { q: "Vast Saint Petersburg museum housed in the tsars' Winter Palace.", a: 'Hermitage' },
      { q: 'American painter of lonely diners and Nighthawks (surname).', a: 'Hopper', alt: ['Edward Hopper'] },
      { q: "The word for a colour's position on the spectrum, apart from its lightness or saturation.", a: 'Hue' },
      { q: 'Dutch painter of The Garden of Earthly Delights and its nightmarish creatures.', a: 'Hieronymus Bosch', alt: ['Bosch'] },
      { q: 'Drawing shade with closely spaced parallel lines.', a: 'Hatching' },
      { q: 'German portraitist at the court of Henry VIII who painted The Ambassadors.', a: 'Holbein', alt: ['Hans Holbein'] },
      { q: 'British artist who preserved a tiger shark in formaldehyde (surname).', a: 'Hirst', alt: ['Damien Hirst'] },
      { q: 'Haarlem portraitist of The Laughing Cavalier (surname).', a: 'Hals', alt: ['Frans Hals'] },
    ],
    I: [
      { q: 'Movement named mockingly after a Monet sunrise, famous for loose brushwork and shifting light.', a: 'Impressionism' },
      { q: 'Paint laid on so thickly that brush or knife marks stand up from the surface.', a: 'Impasto' },
      { q: 'Deep blue plant dye traditionally used to colour denim.', a: 'Indigo' },
      { q: 'Devotional panel image of a saint in the Orthodox Christian tradition.', a: 'Icon' },
      { q: 'Elephant tusk material once carved into miniatures and now banned from trade.', a: 'Ivory' },
      { q: 'Neoclassical French painter of La Grande Odalisque.', a: 'Ingres' },
      { q: 'Work made as a whole environment the viewer walks into rather than an object on a wall.', a: 'Installation' },
      { q: 'Printing family in which the image sits in lines cut below the surface of the plate.', a: 'Intaglio' },
    ],
    J: [
      { q: 'American artist who dripped and flung house paint across canvases laid on the floor.', a: 'Jackson Pollock', alt: ['Pollock'] },
      { q: 'Hard green stone carved in China for thousands of years.', a: 'Jade' },
      { q: 'American who painted targets and the Stars and Stripes as flat everyday objects.', a: 'Jasper Johns', alt: ['Johns'] },
      { q: 'Flemish pioneer of oil painting, creator of the Arnolfini Portrait.', a: 'Jan van Eyck', alt: ['Van Eyck'] },
      { q: 'American artist of giant mirror-polished balloon animals.', a: 'Jeff Koons', alt: ['Koons'] },
      { q: "Pope who commissioned the Sistine ceiling and Raphael's Vatican rooms.", a: 'Julius II' },
    ],
    K: [
      { q: 'Viennese painter of The Kiss, lavish with gold leaf (surname).', a: 'Klimt', alt: ['Gustav Klimt'] },
      { q: 'Russian painter credited with the first purely non-representational canvases.', a: 'Kandinsky', alt: ['Wassily Kandinsky'] },
      { q: 'The oven in which clay is fired to become ceramic.', a: 'Kiln' },
      { q: 'Swiss-German painter of small, playful, sign-filled works who taught at the Bauhaus (surname).', a: 'Klee', alt: ['Paul Klee'] },
      { q: 'Movement in which sculptures actually move, driven by motors or air currents.', a: 'Kinetic art' },
      { q: 'German artist who embeds straw, ash and lead in vast dark canvases about history (surname).', a: 'Kiefer', alt: ['Anselm Kiefer'] },
      { q: 'Abstract Expressionist painter who was married to Jackson Pollock (surname).', a: 'Krasner', alt: ['Lee Krasner'] },
    ],
    L: [
      { q: 'Renaissance polymath who painted the Mona Lisa and The Last Supper.', a: 'Leonardo da Vinci', alt: ['Leonardo', 'Da Vinci'] },
      { q: 'Paris museum, once a royal palace, entered through a glass pyramid.', a: 'Louvre' },
      { q: 'Printing from a flat stone using the mutual repulsion of grease and water.', a: 'Lithography', alt: ['Lithograph'] },
      { q: 'Semi-precious blue stone ground to make the costliest medieval pigment.', a: 'Lapis lazuli' },
      { q: 'The genre in which scenery rather than people is the subject.', a: 'Landscape' },
      { q: 'English painter of matchstick figures outside northern mills (surname).', a: 'Lowry', alt: ['L. S. Lowry'] },
      { q: 'Slow-drying liquid pressed from flax and used as the binder in traditional paints.', a: 'Linseed oil' },
      { q: 'French cave whose prehistoric bulls were found by boys in 1940.', a: 'Lascaux' },
    ],
    M: [
      { q: 'Impressionist who painted water lilies at Giverny over and over.', a: 'Monet', alt: ['Claude Monet'] },
      { q: "The Louvre's most visited portrait, of a Florentine merchant's wife with an enigmatic smile.", a: 'Mona Lisa' },
      { q: 'Sculptor of the Pieta who also painted the Sistine Chapel ceiling.', a: 'Michelangelo' },
      { q: 'French artist whose late paper cut-outs include Blue Nude and The Snail.', a: 'Matisse', alt: ['Henri Matisse'] },
      { q: 'Norwegian Symbolist painter of Madonna, The Sick Child and Anxiety.', a: 'Munch', alt: ['Edvard Munch'] },
      { q: 'Picture built from small pieces of coloured glass or stone set in mortar.', a: 'Mosaic' },
      { q: 'Belgian Surrealist of bowler hats and a pipe labelled as not being one.', a: 'Magritte', alt: ['Rene Magritte'] },
      { q: 'Any artwork painted directly onto a wall.', a: 'Mural' },
      { q: 'Italian painter in Paris known for long necks and blank almond eyes.', a: 'Modigliani' },
      { q: 'Catalan Surrealist of biomorphic shapes, stars and bright primary colours.', a: 'Miro', alt: ['Joan Miro', 'Joan Miró'] },
      { q: 'Painter whose Olympia and Luncheon on the Grass scandalised Paris.', a: 'Manet', alt: ['Edouard Manet'] },
      { q: 'The metamorphic stone that Carrara supplied for Renaissance statues.', a: 'Marble' },
      { q: 'Dutch painter of grids of black lines with red, yellow and blue rectangles.', a: 'Mondrian', alt: ['Piet Mondrian'] },
      { q: 'Surrealist who invented frottage, rubbing textures through paper.', a: 'Max Ernst', alt: ['Ernst'] },
      { q: 'Paris museum of Impressionism housed in a former railway station.', a: "Musee d'Orsay", alt: ['Orsay', "Musée d'Orsay"] },
      { q: 'Florentine banking dynasty who bankrolled Michelangelo and Botticelli.', a: 'Medici' },
    ],
    N: [
      { q: 'Late 18th century style reviving Greek and Roman restraint and order.', a: 'Neoclassicism' },
      { q: 'Rembrandt group portrait of an Amsterdam militia, slashed by a vandal in 1975.', a: 'The Night Watch', alt: ['Night Watch'] },
      { q: "Painted limestone bust of an Egyptian queen, the pride of Berlin's Neues Museum.", a: 'Nefertiti' },
      { q: 'The genre depicting the unclothed human body.', a: 'Nude' },
      { q: 'German Expressionist watercolourist condemned as degenerate by the Nazis (surname).', a: 'Nolde', alt: ['Emil Nolde'] },
      { q: 'Glowing gas tubes used as a sculptural medium by artists such as Bruce Nauman.', a: 'Neon' },
    ],
    O: [
      { q: 'Medium of pigment ground in a slow-drying vegetable liquid, perfected in 15th century Flanders.', a: 'Oil paint', alt: ['Oils', 'Oil'] },
      { q: 'American painter of enormous flowers and New Mexico desert bones (surname).', a: "O'Keeffe", alt: ["Georgia O'Keeffe"] },
      { q: 'Natural earth pigment ranging from pale yellow to red, used since prehistory.', a: 'Ochre', alt: ['Ocher'] },
      { q: '1960s style using precise patterns to make a flat surface seem to vibrate.', a: 'Op art' },
      { q: 'American artist of giant soft sculptures of everyday things such as a clothespin (surname).', a: 'Oldenburg', alt: ['Claes Oldenburg'] },
    ],
    P: [
      { q: "Malaga-born artist who co-founded Cubism and painted Les Demoiselles d'Avignon.", a: 'Picasso', alt: ['Pablo Picasso'] },
      { q: 'The finely ground powder that gives paint its colour.', a: 'Pigment' },
      { q: 'Madrid museum with the greatest holdings of Velazquez and Goya.', a: 'Prado' },
      { q: 'Technique of building an image from tiny separate dots of pure colour.', a: 'Pointillism' },
      { q: 'The board on which a painter mixes colours.', a: 'Palette' },
      { q: 'The greenish film that forms on weathered copper statues.', a: 'Patina' },
      { q: 'Stick of powdered pigment bound with gum, giving soft chalky colour.', a: 'Pastel' },
      { q: 'Fine white translucent ceramic first perfected in China.', a: 'Porcelain' },
      { q: 'The geometric system formalised in Renaissance Florence that makes depth convincing on a flat surface.', a: 'Perspective' },
      { q: 'Sculptural subject of Mary cradling the body of the dead Christ.', a: 'Pieta', alt: ['Pietà'] },
      { q: 'Movement that took its imagery from comics, advertising and supermarket packaging.', a: 'Pop art' },
      { q: 'The first sealing coat applied to a support before painting begins.', a: 'Primer' },
      { q: 'Paris arts complex famous for wearing its pipes and ducts on the outside.', a: 'Pompidou', alt: ['Centre Pompidou'] },
      { q: 'Italian handyman who walked out of the Louvre with the Mona Lisa in 1911 (surname).', a: 'Peruggia', alt: ['Vincenzo Peruggia'] },
    ],
    Q: [
      { q: 'The Italian term for the 1400s, the century of the early Renaissance.', a: 'Quattrocento' },
      { q: 'Feather cut to a nib for drawing in ink.', a: 'Quill' },
      { q: "Stitched and padded textile artwork, famously made by the women of Gee's Bend.", a: 'Quilt' },
    ],
    R: [
      { q: 'Dutch Golden Age master of dozens of searching self-portraits.', a: 'Rembrandt' },
      { q: 'The rebirth of classical learning and art that began in 14th century Italy.', a: 'Renaissance' },
      { q: 'French sculptor of The Thinker and The Kiss.', a: 'Rodin', alt: ['Auguste Rodin'] },
      { q: 'Painter of huge soft-edged blocks of colour, with a meditative chapel in Houston.', a: 'Rothko', alt: ['Mark Rothko'] },
      { q: 'Flemish Baroque painter famous for fleshy, dynamic figures.', a: 'Rubens', alt: ['Peter Paul Rubens'] },
      { q: 'Playful, ornate 18th century style of pale colours and curling shell forms.', a: 'Rococo' },
      { q: 'Painter of The School of Athens in the Vatican, dead at 37.', a: 'Raphael' },
      { q: 'The mid 19th century commitment to depicting ordinary life without idealising it.', a: 'Realism' },
      { q: 'Mexican muralist whose Detroit Industry frescoes wrap a courtyard (surname).', a: 'Rivera', alt: ['Diego Rivera'] },
      { q: "Amsterdam museum built to hold the nation's Golden Age treasures.", a: 'Rijksmuseum' },
    ],
    S: [
      { q: "Movement launched by Andre Breton's 1924 manifesto, mining dreams and the unconscious.", a: 'Surrealism' },
      { q: "Leonardo's technique of smoky, imperceptible transitions between tones.", a: 'Sfumato' },
      { q: 'Vatican room whose ceiling shows the Creation of Adam.', a: 'Sistine Chapel' },
      { q: 'Pointillist painter of A Sunday Afternoon on the Island of La Grande Jatte.', a: 'Seurat', alt: ['Georges Seurat'] },
      { q: 'The genre of arranged inanimate objects such as fruit, flowers and skulls.', a: 'Still life' },
      { q: 'Warm brown ink originally made from cuttlefish.', a: 'Sepia' },
      { q: 'Printing method that forces ink through a stencilled mesh, favoured by Warhol.', a: 'Silkscreen', alt: ['Screen printing', 'Serigraphy'] },
      { q: "Malevich's movement of pure geometric form, launched with a single black square.", a: 'Suprematism' },
      { q: 'Munch work stolen twice from Oslo galleries, in 1994 and again in 2004.', a: 'The Scream', alt: ['Scream'] },
      { q: "Rusted curving plates of this alloy make up Richard Serra's largest sculptures.", a: 'Steel' },
    ],
    T: [
      { q: 'London gallery of contemporary art inside a converted Bankside power station.', a: 'Tate Modern', alt: ['Tate'] },
      { q: 'English painter of storms, steam and light who left his works to the nation (surname).', a: 'Turner', alt: ['J. M. W. Turner'] },
      { q: 'Fired unglazed earthenware, the material of thousands of buried Chinese warriors.', a: 'Terracotta' },
      { q: 'Venetian master of colour who painted Bacchus and Ariadne.', a: 'Titian' },
      { q: 'A work made of three hinged panels.', a: 'Triptych' },
      { q: 'Short-statured painter of Montmartre cabarets and the posters advertising them.', a: 'Toulouse-Lautrec', alt: ['Henri de Toulouse-Lautrec'] },
      { q: 'Painting so convincing that it tricks the eye into seeing real objects.', a: "Trompe l'oeil", alt: ['Trompe loeil'] },
      { q: 'A circular painting, popular in Renaissance Florence.', a: 'Tondo' },
      { q: 'Picture woven on a loom and hung on a wall.', a: 'Tapestry' },
    ],
    U: [
      { q: "Florence gallery holding Botticelli's Birth of Venus.", a: 'Uffizi' },
      { q: 'The intense blue once made by grinding lapis lazuli.', a: 'Ultramarine' },
      { q: 'Earth pigment that turns richer and warmer when roasted, hence the burnt variety.', a: 'Umber' },
      { q: 'Japanese printmaker famed for elegant portraits of beautiful women.', a: 'Utamaro' },
    ],
    V: [
      { q: 'Dutch painter of Sunflowers who cut off part of his own ear.', a: 'Van Gogh', alt: ['Vincent van Gogh'] },
      { q: 'Spanish court painter of Las Meninas.', a: 'Velazquez', alt: ['Velázquez', 'Diego Velazquez'] },
      { q: 'Delft painter of quiet interiors and Girl with a Pearl Earring.', a: 'Vermeer', alt: ['Johannes Vermeer'] },
      { q: 'Clear protective coat brushed over a finished painting.', a: 'Varnish' },
      { q: 'Armless Greek marble goddess displayed in the Louvre.', a: 'Venus de Milo' },
      { q: 'Still life type loaded with skulls and hourglasses as reminders of death.', a: 'Vanitas' },
      { q: 'Flemish portraitist who became court painter to Charles I of England.', a: 'Van Dyck', alt: ['Anthony van Dyck'] },
      { q: 'Renaissance painter whose Lives of the Artists founded the writing of art history.', a: 'Vasari' },
    ],
    W: [
      { q: 'Transparent paint bound with gum arabic and worked on paper.', a: 'Watercolour', alt: ['Watercolor'] },
      { q: 'American painter whose Arrangement in Grey and Black is known as a portrait of his mother.', a: 'Whistler', alt: ['James Whistler'] },
      { q: 'Relief print taken from a carved block of timber.', a: 'Woodcut' },
      { q: 'Material modelled for casting and melted with pigment in encaustic painting.', a: 'Wax' },
      { q: 'New York museum devoted to American art, now in the Meatpacking District.', a: 'Whitney' },
      { q: 'French painter of elegant outdoor party scenes called fetes galantes.', a: 'Watteau' },
    ],
    X: [
      { q: 'The technical term for engraving and printing from carved blocks.', a: 'Xylography' },
    ],
    Y: [
      { q: 'French artist who patented an intense blue and used it for nearly everything.', a: 'Yves Klein', alt: ['Klein'] },
      { q: 'Japanese artist of polka dots, pumpkins and infinity mirror rooms.', a: 'Yayoi Kusama', alt: ['Kusama'] },
    ],
    Z: [
      { q: 'Non-toxic pigment adopted in the 1830s to replace the poisonous lead-based one.', a: 'Zinc white', alt: ['Zinc'] },
      { q: 'Spanish Baroque painter of austere monks and still lifes of plain pottery.', a: 'Zurbaran', alt: ['Zurbarán', 'Francisco de Zurbaran'] },
    ],
  },
};
