import type { RawQuestion } from '../core/packs';

// Additional Bahrain trivia. Grouped here by the first letter of the answer for
// readability; `rebucketByAnswer` in index.ts re-files every question by its
// answer's true first letter at load time, so the grouping is purely for humans.
export const bahrainExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: 'The loose, flowing black cloak worn over clothing by many Gulf women in public.', a: 'Abaya', category: 'bahrain', difficulty: 3 },
    { q: 'The black cord looped over the men\'s white headcloth to hold it in place.', a: 'Agal', category: 'bahrain', difficulty: 4, alt: ['Igal'] },
    { q: 'The Muslim call to prayer broadcast from minarets five times each day.', a: 'Adhan', category: 'bahrain', difficulty: 4, alt: ['Azan'] },
    { q: 'The continent the kingdom belongs to, lying just off the eastern edge of the Arabian landmass.', a: 'Asia', category: 'bahrain', difficulty: 2 },
    { q: 'This Semitic tongue, written right-to-left, is the kingdom\'s official language and the medium of its courts and government.', a: 'Arabic', category: 'bahrain', difficulty: 1 },
    { q: 'The Shia day of mourning for the martyrdom of Imam Husayn, observed solemnly in many island towns.', a: 'Ashura', category: 'bahrain', difficulty: 4 },
    { q: 'The purpose-built oil-company town in the island\'s interior, founded in the 1930s to house petroleum workers near the first wells.', a: 'Awali', category: 'bahrain', difficulty: 5 },
    { q: 'The freshwater natural spring and bathing pool southwest of the capital, fed from underground, a famous old picnic spot.', a: 'Adhari', category: 'bahrain', difficulty: 5, alt: ['Adhari Spring', 'Ain Adhari'] },
    { q: 'The traditional men\'s line dance with sticks and drums, performed at weddings and on national celebrations.', a: 'Ardha', category: 'bahrain', difficulty: 5, alt: ['Ayyala'] },
    { q: 'The wider grouping of Arabic-speaking nations the kingdom belongs to, sharing language, faith and customs.', a: 'Arab world', category: 'bahrain', difficulty: 3, alt: ['Arab nations'] },
    { q: 'The four-yearly contest in which the kingdom\'s footballers compete against other continental sides for a regional title.', a: 'Asian Cup', category: 'bahrain', difficulty: 4 },
  ],
  B: [
    { q: 'The everyday word for a citizen or national of the kingdom.', a: 'Bahraini', category: 'bahrain', difficulty: 2 },
    { q: 'The old merchant district on Muharraq island named after a former pearl-trading family.', a: 'Busaiteen', category: 'bahrain', difficulty: 5 },
    { q: 'The black face-mask of beaten gold-coloured cloth once commonly worn by older Gulf women.', a: 'Battoulah', category: 'bahrain', difficulty: 5, alt: ['Burqa'] },
    { q: 'The thin flat round loaf baked on a domed griddle and eaten with most island meals.', a: 'Bread', category: 'bahrain', difficulty: 2, alt: ['Khubz'] },
    { q: 'The white-uniformed armed force that defends the kingdom on land, sea and air, abbreviated BDF.', a: 'Bahrain Defence Force', category: 'bahrain', difficulty: 4, alt: ['BDF'] },
    { q: 'The institution in Manama housing the kingdom\'s antiquities and Dilmun-era treasures, opened in 1988.', a: 'Bahrain National Museum', category: 'bahrain', difficulty: 3, alt: ['National Museum'] },
    { q: 'The traditional hand-craft of constructing the wooden dhows used for pearling and trade, kept alive at heritage workshops.', a: 'Boatbuilding', category: 'bahrain', difficulty: 4, alt: ['Dhow building'] },
    { q: 'The honorific Arabic word meaning "son of", linking a man\'s name to his father\'s, as in the rulers\' names.', a: 'Bin', category: 'bahrain', difficulty: 4, alt: ['Ibn'] },
    { q: 'The beautiful sandy or rocky shores fringing the islands, where families gather and turtles sometimes nest.', a: 'Beaches', category: 'bahrain', difficulty: 2, alt: ['Beach'] },
  ],
  C: [
    { q: 'The form of government the kingdom adopted in 2002, blending a hereditary king with an elected legislature.', a: 'Constitutional monarchy', category: 'bahrain', difficulty: 3 },
    { q: 'The 2002 founding legal document that established the kingdom and its two-chamber parliament.', a: 'Constitution', category: 'bahrain', difficulty: 3 },
    { q: 'The big covered shopping-and-leisure complex on the Seef–Manama boundary, anchored by a water park and cinemas.', a: 'City Centre Bahrain', category: 'bahrain', difficulty: 3, alt: ['City Centre', 'Bahrain City Centre'] },
    { q: 'The humped desert animal raced on the royal track near Sakhir and long central to Gulf Bedouin life.', a: 'Camel', category: 'bahrain', difficulty: 2 },
    { q: 'The aromatic green pods, the signature spice flavouring Arabic coffee, ground in alongside the roasted beans.', a: 'Cardamom', category: 'bahrain', difficulty: 3, alt: ['Hail'] },
    { q: 'The pinching marine crustaceans, including the prized blue swimmer, netted in the warm shallows for the local table.', a: 'Crabs', category: 'bahrain', difficulty: 3, alt: ['Crab'] },
    { q: 'The traditional Bani Jamra hand-looms weave fine cloth from this soft white plant fibre, the village\'s signature craft material.', a: 'Cotton', category: 'bahrain', difficulty: 4 },
    { q: 'The small minority faith of the kingdom that has its own churches in the capital, served by long-resident expatriate worshippers.', a: 'Christianity', category: 'bahrain', difficulty: 4 },
    { q: 'The northeastern administrative region covering the old-capital island and its airport, one of the kingdom\'s four such divisions.', a: 'Muharraq Governorate', category: 'bahrain', difficulty: 4 },
  ],
  D: [
    { q: 'The arid, sandy and rocky terrain covering most of the interior of the main island.', a: 'Desert', category: 'bahrain', difficulty: 1 },
    { q: 'The process of removing salt from seawater, on which the islands depend for most of their drinking supply.', a: 'Desalination', category: 'bahrain', difficulty: 3 },
    { q: 'The embassy-and-bank-tower quarter of the capital, built on reclaimed land off Manama.', a: 'Diplomatic Area', category: 'bahrain', difficulty: 4 },
    { q: 'The men who descended on a single breath to gather oysters from the seabed, the backbone of the old island economy.', a: 'Divers', category: 'bahrain', difficulty: 2, alt: ['Pearl divers'] },
    { q: 'The nose-clip, finger-guards and a weighted stone helped old breath-hold gatherers sink quickly to the oyster beds; this was their underwater pursuit.', a: 'Diving', category: 'bahrain', difficulty: 3 },
    { q: 'The reddish-brown dye made from a plant, painted in intricate patterns on women\'s hands for weddings and Eid.', a: 'Henna', category: 'bahrain', difficulty: 3 },
  ],
  E: [
    { q: 'The festival of sacrifice that marks the end of the pilgrimage season, the second great Muslim holiday.', a: 'Eid al-Adha', category: 'bahrain', difficulty: 3 },
    { q: 'The vast tidal mudflats and shallow seas around the islands form a rich one of these biological systems for marine life.', a: 'Ecosystem', category: 'bahrain', difficulty: 4 },
    { q: 'The plentiful sunshine drives growing interest in this renewable, panel-generated form of power.', a: 'Energy', category: 'bahrain', difficulty: 3 },
    { q: 'The diplomatic missions of foreign governments, clustered in the capital\'s designated quarter, are these official buildings.', a: 'Embassies', category: 'bahrain', difficulty: 3, alt: ['Embassy'] },
  ],
  F: [
    { q: 'The act of abstaining from food and drink from dawn to dusk during the holy month, a pillar of the faith.', a: 'Fasting', category: 'bahrain', difficulty: 2 },
    { q: 'The kingdom became a leading regional hub for banks, insurers and investment houses in this sector.', a: 'Finance', category: 'bahrain', difficulty: 3, alt: ['Banking'] },
    { q: 'The obligatory acts of the faith — declaration, prayer, charity, fasting and pilgrimage — are known together as these supporting columns.', a: 'Five Pillars', category: 'bahrain', difficulty: 4, alt: ['Pillars of Islam'] },
    { q: 'The rhythmic seafaring work-songs of the pearl divers, sung to coordinate hauling the heavy oyster baskets.', a: 'Fidjeri', category: 'bahrain', difficulty: 5, alt: ['Fjiri'] },
    { q: 'The cloth banner of red and white with five serrated points, flown over the kingdom\'s buildings and ships.', a: 'Flag', category: 'bahrain', difficulty: 2 },
  ],
  G: [
    { q: 'The fried sweet dumplings drizzled with date syrup, sold from Ramadan stalls across the Gulf.', a: 'Gaimat', category: 'bahrain', difficulty: 4, alt: ['Luqaimat'] },
    { q: 'The communal late evening meal shared after the daytime fast during the holy month.', a: 'Ghabga', category: 'bahrain', difficulty: 5 },
    { q: 'The brackish well supply once tapped by traditional date-gardens across the northern villages.', a: 'Groundwater', category: 'bahrain', difficulty: 4 },
    { q: 'The four administrative regions are each headed by an appointed official holding this title.', a: 'Governor', category: 'bahrain', difficulty: 3 },
    { q: 'The bitter, cardamom-scented brew poured from a long-spouted pot to every visitor, known by this Arabic name.', a: 'Gahwa', category: 'bahrain', difficulty: 4, alt: ['Qahwa'] },
    { q: 'The precious yellow metal traded heavily in the capital\'s old market, where jewellery is sold by weight.', a: 'Gold', category: 'bahrain', difficulty: 2 },
    { q: 'The annual spring sporting weekend that brings global crowds to Sakhir for high-speed single-seater racing.', a: 'Grand Prix', category: 'bahrain', difficulty: 3 },
  ],
  H: [
    { q: 'The popular firm white reef grouper, served grilled or in machboos across the kingdom.', a: 'Hamour', category: 'bahrain', difficulty: 4, alt: ['Hammour'] },
    { q: 'The pilgrimage to Mecca that observant Muslims aim to undertake once in a lifetime.', a: 'Hajj', category: 'bahrain', difficulty: 3 },
    { q: 'The modern planned residential city southwest of the capital, named after the reigning king.', a: 'Hamad Town', category: 'bahrain', difficulty: 4 },
    { q: 'The warm welcome of guests with coffee, dates and incense, a deeply prized social value here.', a: 'Hospitality', category: 'bahrain', difficulty: 2 },
    { q: 'The high moisture in the summer air off the Gulf, which makes the heat feel far more oppressive.', a: 'Humidity', category: 'bahrain', difficulty: 3 },
    { q: 'The fortified merchant homes of old Muharraq, with carved doors and wind towers, are preserved as this kind of built legacy.', a: 'Heritage houses', category: 'bahrain', difficulty: 4 },
    { q: 'The dietary law that governs which foods Muslims may eat, ensuring meat is permissible and properly slaughtered.', a: 'Halal', category: 'bahrain', difficulty: 3 },
  ],
  I: [
    { q: 'The fragrant burning resin smoke wafted around guests and clothing as a mark of welcome, known here as bukhoor.', a: 'Incense', category: 'bahrain', difficulty: 3, alt: ['Bukhoor'] },
    { q: 'The leader who guides the congregation in prayer at a mosque and often delivers the sermon.', a: 'Imam', category: 'bahrain', difficulty: 3 },
    { q: 'The cluster of aluminium, petrochemical and shipyard plants near Askar makes up the kingdom\'s heavy one of these.', a: 'Industry', category: 'bahrain', difficulty: 3 },
    { q: 'The vast Gulf shipyard near Hidd, one of the region\'s largest, that repairs and overhauls supertankers and naval vessels.', a: 'ASRY', category: 'bahrain', difficulty: 5, alt: ['Arab Shipbuilding and Repair Yard'] },
    { q: 'The fast-breaking evening meal that ends each day\'s abstinence during the holy month, taken at sunset.', a: 'Iftar', category: 'bahrain', difficulty: 3 },
    { q: 'The lunar-based dating system that sets the timing of Ramadan and the two Eids each year.', a: 'Islamic calendar', category: 'bahrain', difficulty: 4, alt: ['Hijri calendar'] },
  ],
  J: [
    { q: 'The densely built southeastern Manama district, home to many expatriate apartments and the US naval base.', a: 'Juffair', category: 'bahrain', difficulty: 4 },
    { q: 'The kingdom is unusual in the Gulf for hosting a small, long-established community of followers of this faith, who have a synagogue in the capital.', a: 'Judaism', category: 'bahrain', difficulty: 5, alt: ['Jewish faith'] },
    { q: 'The midday congregational worship and sermon held each end-of-week holy day that fills the kingdom\'s mosques.', a: 'Jummah', category: 'bahrain', difficulty: 4, alt: ['Jumua', 'Friday prayer'] },
  ],
  K: [
    { q: 'The sweet, spiced milky tea sold at roadside stalls everywhere, a hugely popular Gulf street drink.', a: 'Karak', category: 'bahrain', difficulty: 3, alt: ['Chai Karak', 'Karak tea'] },
    { q: 'The shallow Gulf coastal inlet or creek; the Arabic word appears in many Gulf place-names for such warm, sheltered waters.', a: 'Khor', category: 'bahrain', difficulty: 5, alt: ['Creek', 'Inlet'] },
    { q: 'The restored 19th-century crescent-shaped stronghold overlooking the Hunanaiya valley, the royal family\'s old seat.', a: 'Riffa Fort', category: 'bahrain', difficulty: 4, alt: ['Sheikh Salman bin Ahmed Al Fateh Fort'] },
    { q: 'The everyday spoken Gulf dialect of the official language, peppered with words from Persian, English and Hindi.', a: 'Khaleeji', category: 'bahrain', difficulty: 5, alt: ['Gulf Arabic'] },
  ],
  L: [
    { q: 'The soft, pale sedimentary rock that makes up much of the islands\' low, flat terrain.', a: 'Limestone', category: 'bahrain', difficulty: 3 },
    { q: 'The tender young red meat, often slow-cooked into the spiced rice national dish, a Gulf feast favourite.', a: 'Lamb', category: 'bahrain', difficulty: 2, alt: ['Mutton'] },
    { q: 'The official spoken and written tongue of the kingdom, with English widely used as a second one of these.', a: 'Language', category: 'bahrain', difficulty: 2 },
  ],
  M: [
    { q: 'The first lunar month of mourning when Shia citizens commemorate the martyrdom at Karbala.', a: 'Muharram', category: 'bahrain', difficulty: 4 },
    { q: 'A follower of the kingdom\'s majority religion is described by this single word.', a: 'Muslim', category: 'bahrain', difficulty: 2 },
    { q: 'The Arabic word of welcome a host offers a guest on arrival.', a: 'Marhaba', category: 'bahrain', difficulty: 4 },
    { q: 'The slender prayer-call towers rising beside each mosque, from which the muezzin\'s call once sounded.', a: 'Minarets', category: 'bahrain', difficulty: 3, alt: ['Minaret'] },
    { q: 'The mosque official who traditionally chanted the call to prayer from the minaret.', a: 'Muezzin', category: 'bahrain', difficulty: 4 },
    { q: 'The holiest city of Islam, toward which the kingdom\'s Muslims turn in prayer and make the great pilgrimage.', a: 'Mecca', category: 'bahrain', difficulty: 2, alt: ['Makkah'] },
    { q: 'The strong, sweet date-based syrup poured over breakfast bread, made by boiling down the palm fruit.', a: 'Molasses', category: 'bahrain', difficulty: 4, alt: ['Date molasses'] },
    { q: 'The semicircular niche in a mosque wall that marks the direction worshippers face for prayer.', a: 'Mihrab', category: 'bahrain', difficulty: 5 },
    { q: 'The compass direction toward Mecca that Muslims face when they pray, marked in every mosque.', a: 'Qibla', category: 'bahrain', difficulty: 4 },
  ],
  N: [
    { q: 'The black face-veil worn by some women, leaving only the eyes uncovered.', a: 'Niqab', category: 'bahrain', difficulty: 3 },
    { q: 'A person born and holding citizenship of the kingdom is described by this word, as opposed to an expatriate.', a: 'National', category: 'bahrain', difficulty: 3, alt: ['Citizen'] },
    { q: 'The branch of the armed services that patrols the kingdom\'s waters and protects its ports and offshore platforms.', a: 'Navy', category: 'bahrain', difficulty: 3, alt: ['Coast Guard'] },
    { q: 'The roasted, salted seeds set out in bowls for guests alongside coffee and dates.', a: 'Nuts', category: 'bahrain', difficulty: 2 },
    { q: 'The tightly woven hand-knotted floor coverings, often imported from Persia, that grace traditional majlis sitting rooms.', a: 'Carpets', category: 'bahrain', difficulty: 3, alt: ['Rugs'] },
    { q: 'The pale, fine, wind-blown grains that drift across the southern interior and pile into low dunes.', a: 'Sand', category: 'bahrain', difficulty: 2 },
  ],
  O: [
    { q: 'The numeral by which the kingdom marks its sovereignty from Britain: nineteen seventy-___.', a: 'One', category: 'bahrain', difficulty: 3 },
    { q: 'The fragrant agarwood whose smoke is wafted over guests and clothes, the most prized of Gulf perfumery ingredients.', a: 'Oud', category: 'bahrain', difficulty: 4, alt: ['Agarwood'] },
  ],
  P: [
    { q: 'The Manama traffic circle whose tall monument of six dhow sails cradling a sphere was demolished in 2011.', a: 'Pearl Roundabout', category: 'bahrain', difficulty: 4, alt: ['Lulu Roundabout', 'Pearl Square'] },
    { q: 'The legislative branch revived in 2002, with an appointed upper house and an elected lower one.', a: 'Parliament', category: 'bahrain', difficulty: 3 },
    { q: 'The diving, sorting, trading and financing of oysters and their gems made up this old maritime economy.', a: 'Pearling', category: 'bahrain', difficulty: 3, alt: ['Pearl trade'] },
    { q: 'The act of worship performed five times daily by Muslims, facing Mecca, central to life in the kingdom.', a: 'Prayer', category: 'bahrain', difficulty: 2, alt: ['Salah', 'Salat'] },
    { q: 'The body of salt water lying between the islands and Iran, narrowing to the Strait of Hormuz in the southeast.', a: 'Persian Gulf', category: 'bahrain', difficulty: 3, alt: ['Arabian Gulf'] },
    { q: 'The crowned ruler\'s formal residence and seat of state ceremony, an opulent building of the royal family.', a: 'Palace', category: 'bahrain', difficulty: 3 },
    { q: 'The vivid green tracts of fronded trees in the north, irrigated from old springs, that gave the islands their lush reputation.', a: 'Palm groves', category: 'bahrain', difficulty: 3, alt: ['Date groves'] },
    { q: 'The British colonial-era official who represented London\'s interests in the islands under the protection treaties.', a: 'Political Agent', category: 'bahrain', difficulty: 5, alt: ['British Agent'] },
    { q: 'The small, sweet, cardamom-flavoured pancakes folded over cream and nuts, a beloved Ramadan-stall treat.', a: 'Qatayef', category: 'bahrain', difficulty: 5 },
    { q: 'The ruby-seeded fruit grown in island gardens, its juice a refreshing traditional drink and its tree prized for shade.', a: 'Pomegranate', category: 'bahrain', difficulty: 3 },
  ],
  Q: [
    { q: 'The holy book of Islam, recited and studied in the kingdom\'s mosques and schools.', a: 'Quran', category: 'bahrain', difficulty: 2, alt: ['Koran'] },
  ],
  R: [
    { q: 'The luxury reclaimed-land development of homes and a marina on the northern coast, marketed Riviera-style.', a: 'Reef Island', category: 'bahrain', difficulty: 5 },
    { q: 'The boiled long-grain staple, often spiced and cooked with meat or fish, that forms the base of machboos.', a: 'Rice', category: 'bahrain', difficulty: 2 },
    { q: 'The silvery local reef-dweller known in Arabic as safi, a prized everyday catch from Gulf waters.', a: 'Rabbitfish', category: 'bahrain', difficulty: 5, alt: ['Safi'] },
    { q: 'The single bold colour filling most of the kingdom\'s national flag, set against a white serrated band.', a: 'Red', category: 'bahrain', difficulty: 3 },
  ],
  S: [
    { q: 'The upmarket commercial and shopping district of the capital, lined with malls and hotels.', a: 'Seef', category: 'bahrain', difficulty: 3, alt: ['Seef District'] },
    { q: 'The appointed upper chamber of parliament, named with an Arabic word for consultation.', a: 'Shura Council', category: 'bahrain', difficulty: 4, alt: ['Shura', 'Consultative Council'] },
    { q: 'The larger of Islam\'s two main branches, followed by the ruling family and many citizens.', a: 'Sunni', category: 'bahrain', difficulty: 3 },
    { q: 'The branch of Islam, also called Twelver, followed by a large share of the island\'s indigenous citizens.', a: 'Shia', category: 'bahrain', difficulty: 3, alt: ['Shi\'a', 'Shiite'] },
    { q: 'The peace greeting exchanged between Muslims, the phrase that opens nearly every conversation.', a: 'Salam', category: 'bahrain', difficulty: 3, alt: ['Salaam', 'As-salamu alaykum'] },
    { q: 'The high-heat half of the year, running roughly May to September, that drives everyone indoors.', a: 'Summer', category: 'bahrain', difficulty: 2 },
    { q: 'The pre-dawn meal eaten before the day\'s fast begins during the holy month.', a: 'Suhoor', category: 'bahrain', difficulty: 4, alt: ['Sahur'] },
    { q: 'The salty tidal flats fringing the coast, baked hard in the heat, where wading birds feed at low tide.', a: 'Sabkha', category: 'bahrain', difficulty: 5, alt: ['Mudflats'] },
    { q: 'The crown prince and prime minister since 2020, the king\'s eldest son — his given name.', a: 'Salman', category: 'bahrain', difficulty: 4, alt: ['Salman bin Hamad'] },
    { q: 'The classroom system that, since the 1919 opening of Al-Hidaya, gave the islands one of the Gulf\'s oldest modern ones.', a: 'Schools', category: 'bahrain', difficulty: 4, alt: ['School'] },
    { q: 'The low-lying island just south of the capital, home to the kingdom\'s oil refinery and tank farms.', a: 'Sitra', category: 'bahrain', difficulty: 4 },
    { q: 'The pink-shelled crustaceans, a staple of Gulf cuisine, harvested from the islands\' waters and served in machboos.', a: 'Shrimp', category: 'bahrain', difficulty: 2, alt: ['Prawns', 'Prawn'] },
    { q: 'The flat-bottomed meadows of underwater plants in the warm shallows that feed the kingdom\'s grazing dugong herds.', a: 'Seagrass', category: 'bahrain', difficulty: 4 },
    { q: 'The towering modern office and residential blocks that crowd the capital\'s reclaimed waterfront and skyline.', a: 'Skyscrapers', category: 'bahrain', difficulty: 3, alt: ['Towers'] },
    { q: 'The narrow sea channel at the Gulf\'s mouth, opening into the Gulf of Oman, the vital tanker chokepoint the kingdom sits well inland of.', a: 'Strait of Hormuz', category: 'bahrain', difficulty: 4, alt: ['Hormuz'] },
  ],
  T: [
    { q: 'The visitor industry, drawing weekenders across the causeway, that the kingdom promotes to diversify its income.', a: 'Tourism', category: 'bahrain', difficulty: 2 },
    { q: 'The 1971 agreement ending the islands\' protected status returned full control of their own affairs through this kind of accord with Britain.', a: 'Treaty', category: 'bahrain', difficulty: 3 },
    { q: 'The Gulf shipping lane the islands sit beside has carried this seaborne exchange of goods since Dilmun times.', a: 'Trade', category: 'bahrain', difficulty: 2 },
    { q: 'The hereditary kin-groups, such as the Dawasir and the Utub, around which old Gulf society and the pearling fleets were organised.', a: 'Tribes', category: 'bahrain', difficulty: 4, alt: ['Tribe'] },
    { q: 'The leathery-shelled marine reptiles, including the hawksbill and green, that nest on the kingdom\'s quieter beaches.', a: 'Turtles', category: 'bahrain', difficulty: 3, alt: ['Sea turtles'] },
    { q: 'The cylindrical hand-drum, played with the palms, that drives the rhythm of pearl-divers\' songs and folk dances.', a: 'Tabla', category: 'bahrain', difficulty: 4, alt: ['Drum'] },
    { q: 'The pearl merchants who financed and equipped the diving fleets, profiting from the gems the divers brought up, were called these.', a: 'Tawash', category: 'bahrain', difficulty: 5, alt: ['Pearl merchant'] },
  ],
  U: [
    { q: 'The flat, mostly private island west of the main one, owned by the royal family, that the causeway to Saudi Arabia crosses on its way west.', a: 'Umm an Nasan', category: 'bahrain', difficulty: 5, alt: ['Umm Nasan'] },
  ],
  V: [
    { q: 'The hardy, salt-tolerant shrubs and palms that survive the islands\' arid, briny soil make up its sparse natural one of these.', a: 'Vegetation', category: 'bahrain', difficulty: 4, alt: ['Flora'] },
  ],
  W: [
    { q: 'The hot daytime and mild cool-season pattern of this desert nation makes it a popular winter escape.', a: 'Weather', category: 'bahrain', difficulty: 2 },
    { q: 'The mild, pleasant half of the year, roughly December to February, prized for outdoor events and the Grand Prix.', a: 'Winter', category: 'bahrain', difficulty: 2 },
    { q: 'The architectural shaft built atop old Gulf houses to catch and funnel cooling breezes down into the rooms.', a: 'Wind tower', category: 'bahrain', difficulty: 4, alt: ['Badgir', 'Barjeel'] },
    { q: 'The festive ceremony, with its henna nights, feasting and the men\'s stick dance, that is among the most elaborate of island family events.', a: 'Wedding', category: 'bahrain', difficulty: 3 },
  ],
};
