import type { RawPack } from '../core/packs';

export const boardGamesPack: RawPack = {
  id: 'board-games',
  name: 'Board Games & Puzzles',
  description: 'Classic tabletop games, their pieces, rules and champions.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '🎲',
  accent: '#0d9488',
  letters: {
    A: [
      { q: 'French abstract game for two in which players push rows of marbles off a hexagonal board.', a: 'Abalone' },
      { q: 'Uwe Rosenberg game in which players plough fields and must feed a family in 17th century Europe.', a: 'Agricola' },
      { q: 'Indian grandmaster who held the world chess title from 2007 to 2013.', a: 'Anand' },
      { q: 'Card that outranks a king in poker.', a: 'Ace' },
      { q: 'Medieval game brought to Spain by the Moors, played on a five by five grid of lines and seen as an ancestor of draughts.', a: 'Alquerque' },
      { q: 'Tile drafting game about decorating a Portuguese palace, winner of the 2018 Spiel des Jahres.', a: 'Azul' },
      { q: 'Word puzzle whose solution rearranges every letter of the given phrase.', a: 'Anagram' },
      { q: 'Russian born player who died in 1946 while still holding the world chess crown.', a: 'Alekhine' },
      { q: 'Go term for a stone or group left with only one liberty, so it can be captured next turn.', a: 'Atari' },
      { q: 'The standard system for recording chess moves, in which every square has a letter and a number.', a: 'Algebraic notation' },
      { q: 'Puzzle in which the first letters of the answers spell out a hidden phrase.', a: 'Acrostic' },
    ],
    B: [
      { q: 'Ancient race game for two played on a board of 24 narrow triangles.', a: 'Backgammon' },
      { q: 'Chess piece that may only travel along diagonals.', a: 'Bishop' },
      { q: 'Abstract game in which four players place coloured shapes that may touch only at the corners.', a: 'Blokus' },
      { q: 'Scrabble slang for playing all seven of your tiles in one turn for a 50 point bonus.', a: 'Bingo' },
      { q: 'Word game with 16 lettered cubes shaken in a tray and a three minute sand timer.', a: 'Boggle' },
      { q: 'Fast chess variant played on two boards by teams of two, with captured pieces passed to a partner.', a: 'Bughouse' },
      { q: 'Trick taking card game for four in partnerships, famous for its auction and its exposed hand.', a: 'Bridge' },
      { q: 'Two player guessing game on hidden grids where you call out coordinates to sink a fleet.', a: 'Battleship' },
      { q: 'Nineteenth century French card game for two using a 64 card pack, the ancestor of pinochle.', a: 'Bezique' },
      { q: 'Soviet engineer known as the Patriarch, world chess champion for most of the years between 1948 and 1963.', a: 'Botvinnik' },
      { q: 'Casino card game in which you try to get closer to 21 than the dealer without going over.', a: 'Blackjack' },
      { q: 'The auction phase of bridge, in which partnerships describe their hands.', a: 'Bidding' },
    ],
    C: [
      { q: 'American name for the game of draughts, played with 12 discs a side on 64 squares.', a: 'Checkers' },
      { q: 'Game with 32 pieces on 64 squares in which the aim is to trap the enemy king.', a: 'Chess' },
      { q: 'British title of the murder mystery board game in which you deduce the room, the weapon and the culprit.', a: 'Cluedo' },
      { q: 'Tile laying game about a walled town in southern France, with roads, cloisters and farmers.', a: 'Carcassonne' },
      { q: 'Klaus Teuber game in which players trade wood, brick, sheep, wheat and ore to build roads and settlements.', a: 'Catan' },
      { q: 'The only chess turn that shifts two of your own pieces at once, tucking the king behind a rook.', a: 'Castling' },
      { q: 'Card game traditionally scored by moving pegs along a holed wooden board, counting fifteens and pairs.', a: 'Cribbage' },
      { q: 'Party game in which a player acts out a title in silence for their team to work out.', a: 'Charades' },
      { q: 'Cuban who took the world chess title from Lasker in 1921 and lost it to Alekhine in 1927.', a: 'Capablanca' },
      { q: 'Vlaada Chvatil word game in which two spymasters give one word hints to link agents on a grid of 25 cards.', a: 'Codenames' },
      { q: 'Newspaper puzzle of black and white squares filled from numbered clues, across and down.', a: 'Crossword' },
      { q: 'Milton Bradley game in which players drop discs into a standing rack of seven columns, trying to line up a quartet.', a: 'Connect Four' },
      { q: 'South Asian tabletop game in which players flick a striker to pot small wooden discs into corner pockets.', a: 'Carrom' },
      { q: 'Indian game of the Gupta era with four divisions of the army, regarded as the ancestor of modern chess.', a: 'Chaturanga' },
    ],
    D: [
      { q: 'Tiles marked with two halves of pips, laid end to end so that matching numbers touch.', a: 'Dominoes' },
      { q: 'British name for the game played with 24 discs that jump diagonally and are crowned on the far row.', a: 'Draughts' },
      { q: 'Cubes with pips on each face, thrown to decide moves in Monopoly and backgammon.', a: 'Dice' },
      { q: 'Storytelling game in which a player gives a clue for one of their dreamlike illustrated cards and the others try to pick it.', a: 'Dixit' },
      { q: 'In bridge, the partner whose 13 cards are laid face up on the table and played by the declarer.', a: 'Dummy' },
      { q: 'Fast spotting game whose round cards always share exactly one symbol, sold as Spot It in America.', a: 'Dobble' },
      { q: 'Result in chess when neither side wins, worth half a point each.', a: 'Draw' },
      { q: 'The full pack of 52 playing cards.', a: 'Deck' },
      { q: 'Russian trainer whose Endgame Manual is a standard reference for advanced chess players.', a: 'Dvoretsky' },
      { q: 'Six sided marker in backgammon showing 2, 4, 8, 16, 32 and 64, used to raise the stakes.', a: 'Doubling cube' },
      { q: 'IBM machine that beat a reigning world chess champion in a match in 1997.', a: 'Deep Blue' },
    ],
    E: [
      { q: 'Chess capture of a pawn that has just advanced two squares, taken as though it had gone only one.', a: 'En passant' },
      { q: 'Trick taking card game of the American Midwest played with 24 cards and a right and left bower.', a: 'Euchre' },
      { q: 'The final phase of a chess battle, when only a few pieces are left.', a: 'Endgame' },
      { q: 'Rating system for chess players devised by a Hungarian American physics professor.', a: 'Elo' },
      { q: 'Woodland board game in which animal characters build a city of critters and constructions over four seasons.', a: 'Everdell' },
      { q: 'Card game by Matthew Inman in which drawing the wrong card blows you up unless you hold a defuse.', a: 'Exploding Kittens' },
      { q: 'Parker Brothers game about prisoners of war breaking out of a German castle.', a: 'Escape from Colditz' },
      { q: 'Dutch mathematics teacher who was world chess champion from 1935 to 1937.', a: 'Euwe' },
      { q: 'In chess, a trade of pieces of equal value.', a: 'Exchange' },
    ],
    F: [
      { q: 'Chess plan of developing a bishop to the long diagonal after advancing the knight pawn one square.', a: 'Fianchetto' },
      { q: 'American who beat Spassky in Reykjavik in 1972 to become world chess champion.', a: 'Fischer' },
      { q: 'Chess tactic in which a single piece attacks two enemy pieces at the same time.', a: 'Fork' },
      { q: 'Chess draw claim available when no capture and no pawn advance has happened for 50 turns by each side.', a: 'Fifty-move rule' },
      { q: 'Solitaire card game bundled with Windows in which four corner spaces each hold a single card.', a: 'Freecell' },
      { q: 'Card game by Looney Labs in which the rules and the winning condition keep changing during play.', a: 'Fluxx' },
      { q: 'Card game of betting on which rank will be dealt, hugely popular in saloons of the American Old West.', a: 'Faro' },
      { q: 'German chess program that drew a match with Kramnik in 2002.', a: 'Fritz' },
    ],
    G: [
      { q: 'Ancient East Asian game of surrounding territory with black and white stones on a 19 by 19 grid.', a: 'Go' },
      { q: 'Japanese name for the game of getting five stones in a row on a grid.', a: 'Gomoku' },
      { q: 'Chess opening in which a player offers a pawn to gain rapid development.', a: 'Gambit' },
      { q: 'Two player card game where you form sets and runs and then knock to end the hand.', a: 'Gin Rummy' },
      { q: 'Two player game of yes or no questions to work out which face on a rack of flip down cards your rival holds.', a: 'Guess Who' },
      { q: 'Simple children\'s card game of asking an opponent for a rank you already hold.', a: 'Go Fish' },
      { q: 'Huge 2017 campaign board game of dungeon crawling mercenaries with a branching story.', a: 'Gloomhaven' },
      { q: 'The highest title awarded for life by the world chess federation.', a: 'Grandmaster' },
      { q: 'Result worth double the stake in a race game with a doubling cube, when the loser has not borne off a single checker.', a: 'Gammon' },
    ],
    H: [
      { q: 'Connection game on a rhombus of hexagons, invented by Piet Hein and rediscovered by John Nash.', a: 'Hex' },
      { q: 'Norse board game in which a king and his few defenders try to escape while a larger attacking force surrounds them.', a: 'Hnefatafl' },
      { q: 'Tile game with no board, where insect pieces such as the beetle and the grasshopper try to surround a queen bee.', a: 'Hive' },
      { q: 'Trick taking card game where you avoid points and try to dodge the queen of spades.', a: 'Hearts' },
      { q: 'Nineteenth century game of jumping pieces across a chequered board, the ancestor of Chinese Checkers.', a: 'Halma' },
      { q: 'Cooperative card game in which players hold their cards facing outward and build fireworks together.', a: 'Hanabi' },
      { q: 'Eighteenth century Englishman whose name became a byword for the authoritative rules of card games.', a: 'Hoyle' },
      { q: 'American toy company that owns Monopoly, Cluedo and Scrabble in the United States.', a: 'Hasbro' },
      { q: 'Pencil and paper word game where each wrong letter adds a part to a gallows drawing.', a: 'Hangman' },
    ],
    I: [
      { q: 'Reiner Knizia abstract game in which you place double hexagon tiles and your score is your weakest colour.', a: 'Ingenious' },
      { q: 'Board game about moving a merchant and his assistants around a Turkish bazaar to collect rubies.', a: 'Istanbul' },
      { q: 'Blackjack side bet offered when the dealer shows an ace.', a: 'Insurance' },
      { q: 'Country where the ancestors of both chess and Ludo were first played.', a: 'India' },
      { q: 'Tile laying game about Scottish landscapes, winner of the 2016 Kennerspiel des Jahres.', a: 'Isle of Skye' },
      { q: 'Ukrainian grandmaster nicknamed Chucky who won the world rapid chess title in 2016.', a: 'Ivanchuk' },
      { q: 'Looney Labs game played with plastic pyramids that are placed pointing at other pieces.', a: 'Icehouse' },
    ],
    J: [
      { q: 'Game of pulling wooden blocks from a tower and stacking them on top without a collapse.', a: 'Jenga' },
      { q: 'Picture puzzle cut into interlocking pieces.', a: 'Jigsaw' },
      { q: 'Extra card outside the four suits, used as a wild card in many games.', a: 'Joker' },
      { q: 'Two player card game of camels and goods, set in a market in Rajasthan.', a: 'Jaipur' },
      { q: 'Court card ranked between the ten and the queen.', a: 'Jack' },
      { q: 'Newspaper puzzle in which scrambled words are sorted out and their circled letters give a final answer.', a: 'Jumble' },
      { q: 'Hungarian who became the strongest female chess player in history and beat several world champions.', a: 'Judit Polgar' },
    ],
    K: [
      { q: 'Chess piece that moves one square in any direction and must never be left in check.', a: 'King' },
      { q: 'Chess piece that moves in an L shape and can leap over other pieces.', a: 'Knight' },
      { q: 'Russian who lost a 1997 match to the IBM computer Deep Blue.', a: 'Kasparov' },
      { q: 'Russian who took the world chess title in London in 2000.', a: 'Kramnik' },
      { q: 'Japanese number puzzle where each run of white cells must add up to a given total with no repeats.', a: 'Kakuro' },
      { q: 'Grid puzzle of cages with arithmetic targets, created by the Japanese teacher Tetsuya Miyamoto.', a: 'KenKen' },
      { q: 'The most familiar solitaire layout, with seven piles and four foundations.', a: 'Klondike' },
      { q: 'Modern commercial mancala with two rows of six pits and a store at each end.', a: 'Kalah' },
      { q: 'Tile game where you build a 5 by 5 realm from two square pieces, winner of the 2017 Spiel des Jahres.', a: 'Kingdomino' },
    ],
    L: [
      { q: 'British race game with four tokens a side, based on the Indian game Pachisi.', a: 'Ludo' },
      { q: 'Ravensburger game in which you push a row of maze tiles to open a path to your treasure.', a: 'Labyrinth' },
      { q: 'German mathematician who held the world chess title for 27 years from 1894.', a: 'Lasker' },
      { q: 'In Go, an empty point next to a stone; when the last one goes, the stone is captured.', a: 'Liberty' },
      { q: 'Bluffing game with five hidden cubes under a cup, where each bid must raise the last.', a: 'Liar\'s Dice' },
      { q: 'Reiner Knizia two player card game about mounting expeditions to five ancient sites.', a: 'Lost Cities' },
      { q: 'Small game of just 16 cards in which you try to reach the princess by outguessing your rivals.', a: 'Love Letter' },
      { q: 'Solid chess opening for White with a pawn on d4 and the dark squared bishop developed early to f4.', a: 'London System' },
      { q: 'Famous winning rook endgame technique in which the king shelters behind a bridge made by the rook.', a: 'Lucena position' },
    ],
    M: [
      { q: 'Property trading board game with Mayfair, Park Lane and a jail corner.', a: 'Monopoly' },
      { q: 'Chinese tile game for four with suits of bamboo, circles and characters plus winds and dragons.', a: 'Mahjong' },
      { q: 'Family of African sowing games in which seeds are dropped one by one into a row of pits.', a: 'Mancala' },
      { q: 'Two player code breaking game with rows of coloured pegs and small black and white key pegs.', a: 'Mastermind' },
      { q: 'Nickname for the little wooden person shaped playing figure popularised by Carcassonne.', a: 'Meeple' },
      { q: 'Ancient game of three in a row on 24 points, in which each side has nine men.', a: 'Morris' },
      { q: 'Board game whose main feature is a Rube Goldberg contraption built during play to catch a plastic rodent.', a: 'Mouse Trap' },
      { q: 'Game of pulling thin sticks from a pile without disturbing the rest.', a: 'Mikado' },
      { q: 'Norwegian who became world chess champion in 2013 and then dominated the rating list.', a: 'Magnus Carlsen' },
      { q: 'French card game about a road trip, with hazards such as a flat tyre and remedies to fix them.', a: 'Mille Bornes' },
      { q: 'Steve Jackson Games card game that parodies dungeon crawling, with monsters, treasure and backstabbing.', a: 'Munchkin' },
    ],
    N: [
      { q: 'Mathematical game of removing objects from heaps where the winning strategy uses binary addition.', a: 'Nim' },
      { q: 'Japanese logic puzzle in which numbers beside a grid tell you which cells to shade to reveal a picture.', a: 'Nonogram' },
      { q: 'Latvian born theorist of the hypermodern chess school who wrote My System.', a: 'Nimzowitsch' },
      { q: 'American grandmaster and five time United States chess champion, also a star of online streaming.', a: 'Nakamura' },
      { q: 'Fast competitive card game in which several players race to play patience onto shared centre piles.', a: 'Nertz' },
      { q: 'Nikoli puzzle in which you join matching pairs of digits with paths that never cross.', a: 'Numberlink' },
      { q: 'Card game in which you either take the face up number or pay a chip to decline it.', a: 'No Thanks!' },
    ],
    O: [
      { q: 'Disc flipping game on an 8 by 8 board where trapped pieces turn to your colour, named after a Shakespeare play.', a: 'Othello' },
      { q: 'The first phase of a chess game, with named lines such as the Sicilian and the Italian.', a: 'Opening' },
      { q: 'Two player abstract game on a 5 by 5 board where shared move cards are passed to the opponent after use.', a: 'Onitama' },
      { q: 'Children\'s card game in which players discard pairs and the loser is left holding a single unmatched card.', a: 'Old Maid' },
      { q: 'National mancala game of Ghana, played with 48 seeds in two rows of six pits.', a: 'Oware' },
      { q: 'Trick taking card game in which you must bid the exact number of tricks you will win.', a: 'Oh Hell' },
      { q: 'Battery powered dexterity game of removing plastic ailments with tweezers without setting off a buzz.', a: 'Operation' },
      { q: 'In bridge, a round won beyond what the contract required.', a: 'Overtrick' },
    ],
    P: [
      { q: 'The least valuable chess piece, which may capture only diagonally.', a: 'Pawn' },
      { q: 'Indian cross shaped race game played with cowrie shells, the ancestor of Ludo.', a: 'Pachisi' },
      { q: 'Party game of drawing a word on a pad while your team shouts guesses against a timer.', a: 'Pictionary' },
      { q: 'Betting card game of five card hands ranked from a pair up to a royal flush.', a: 'Poker' },
      { q: 'British word for a card game played alone.', a: 'Patience' },
      { q: 'Any of the 12 flat shapes that can be made by joining five squares edge to edge.', a: 'Pentomino' },
      { q: 'What happens when a pawn reaches the far rank and becomes a stronger piece.', a: 'Promotion' },
      { q: 'Cooperative board game in which a team of specialists races to cure four diseases before outbreaks spread.', a: 'Pandemic' },
      { q: 'Board game of colonial plantations in which players take roles such as captain, trader and builder.', a: 'Puerto Rico' },
      { q: 'American partnership card game using a 48 card pack, with melds such as a queen and a jack of different suits.', a: 'Pinochle' },
      { q: 'Loud card game in which players shout out trades of wheat, corn and other commodities.', a: 'Pit' },
      { q: 'Armenian world chess champion from 1963 to 1969, famous for his defensive prophylaxis.', a: 'Petrosian' },
      { q: 'Chess tactic in which a piece cannot move because a more valuable one stands behind it.', a: 'Pin' },
    ],
    R: [
      { q: 'Chess piece that travels along ranks and files and takes part in castling.', a: 'Rook' },
      { q: 'Board game of world conquest with armies, continent bonuses and battles decided by dice.', a: 'Risk' },
      { q: 'Victorian game of double sided counters that is the direct forerunner of Othello.', a: 'Reversi' },
      { q: 'Tile game of runs and groups numbered 1 to 13 in four colours, with two jokers.', a: 'Rummikub' },
      { q: 'Coloured twisting puzzle of 26 outer pieces invented by a Hungarian architecture professor in 1974.', a: 'Rubik\'s Cube' },
      { q: 'Family of card games in which you draw, discard and meld sets and sequences.', a: 'Rummy' },
      { q: 'What a chess player does by stopping the clock and offering a handshake in a hopeless position.', a: 'Resign' },
      { q: 'Chess draw claimed when the same position occurs three times with the same player to move.', a: 'Repetition' },
      { q: 'Declaration in Japanese mahjong that you are one tile away from a winning hand.', a: 'Riichi' },
      { q: 'Leder Games board game of asymmetric woodland factions fighting for control of a forest.', a: 'Root' },
    ],
    S: [
      { q: 'Word game of 100 lettered tiles on a 15 by 15 board with triple word squares.', a: 'Scrabble' },
      { q: 'Japanese named number puzzle where each row, column and 3 by 3 box holds the digits 1 to 9 once.', a: 'Sudoku' },
      { q: 'Japanese chess played on nine ranks, in which captured pieces can be dropped back into play.', a: 'Shogi' },
      { q: 'Ancient Egyptian race game found in the tomb of Tutankhamun, played on three rows of ten squares.', a: 'Senet' },
      { q: 'American term for a one player card game such as Klondike or Spider.', a: 'Solitaire' },
      { q: 'Chess draw when the player to move has no legal option and is not in check.', a: 'Stalemate' },
      { q: 'Race game of pure luck from India where some squares send you soaring and others drop you back.', a: 'Snakes and Ladders' },
      { q: 'Card game of buying gem mines with chips and attracting nobles to your engine.', a: 'Splendor' },
      { q: 'Two player war game of hidden ranks where a marshal falls to a spy and bombs guard the flag.', a: 'Stratego' },
      { q: 'Partnership trick taking game where one suit is always trump and you bid the tricks you will take.', a: 'Spades' },
      { q: 'Party game of listing things in given categories that all begin with a rolled letter.', a: 'Scattergories' },
      { q: 'Bohemian born player recognised as the first official world chess champion in 1886.', a: 'Steinitz' },
      { q: 'Japanese computer puzzle in which a warehouse keeper pushes crates onto marked targets.', a: 'Sokoban' },
      { q: 'Parker Brothers race game of sliding pawns where one card lets you bump a rival back to the start.', a: 'Sorry!' },
      { q: 'Soviet champion who lost the 1972 world chess match in Iceland.', a: 'Spassky' },
      { q: 'Board and card game in which you cover a matching space with a chip and try to make two lines of five.', a: 'Sequence' },
    ],
    T: [
      { q: 'Falling block puzzle created by Alexey Pajitnov in 1984.', a: 'Tetris' },
      { q: 'Party game played on a plastic mat of coloured circles, where a spinner tells you where to put a hand or foot.', a: 'Twister' },
      { q: 'Chinese dissection puzzle of seven flat pieces rearranged into silhouettes.', a: 'Tangram' },
      { q: 'Any of the flat shapes formed by joining four squares edge to edge, as used in Tetris.', a: 'Tetromino' },
      { q: 'Quiz board game in which you collect six coloured wedges for a plastic wheel.', a: 'Trivial Pursuit' },
      { q: 'Latvian attacking genius nicknamed the Magician from Riga, world chess champion in 1960.', a: 'Tal' },
      { q: 'Alan Moon game of collecting coloured train cards to claim railway routes on a map of North America.', a: 'Ticket to Ride' },
      { q: 'Pencil game on a three by three grid where crosses and noughts race to make a line.', a: 'Tic-tac-toe' },
      { q: 'The suit chosen to beat all others in whist and bridge.', a: 'Trump' },
      { q: 'Games Workshop fantasy board game of a race to the Crown of Command in the inner region.', a: 'Talisman' },
      { q: 'Card pack of 78 with a fool and its own suit of trumps, still used for a popular trick taking game in France.', a: 'Tarot' },
    ],
    U: [
      { q: 'Card game of matching colours and numbers where you shout when a single card is left in your hand.', a: 'Uno' },
      { q: 'Royal Game of ancient Mesopotamia, whose rules survive on a Babylonian tablet.', a: 'Ur' },
      { q: 'Choosing a knight or a rook instead of a queen when a pawn reaches the last rank.', a: 'Underpromotion' },
      { q: 'Tile game like Scrabble, but with pieces that stack on top of each other to change what is spelt.', a: 'Upwords' },
      { q: 'In gin rummy, having equal or less deadwood than the player who knocked, which earns you a bonus.', a: 'Undercut' },
    ],
    V: [
      { q: 'French name of the card game of 21, from which blackjack grew.', a: 'Vingt-et-un' },
      { q: 'In bridge, holding no cards at all in a particular suit.', a: 'Void' },
      { q: 'In rubber bridge, the state of a side that has won one game, raising both its bonuses and its penalties.', a: 'Vulnerable' },
      { q: 'French grandmaster known as MVL, a leading exponent of the Najdorf Sicilian.', a: 'Vachier-Lagrave' },
      { q: 'Chess opening in which White answers e5 with the queenside knight to c3, named after an Austrian city.', a: 'Vienna Game' },
    ],
    W: [
      { q: 'English trick taking game of 52 cards, the ancestor of bridge.', a: 'Whist' },
      { q: 'The side that always moves first in chess.', a: 'White' },
      { q: 'Elizabeth Hargrave board game about attracting birds to habitats with food and eggs.', a: 'Wingspan' },
      { q: 'Social deduction party game of villagers voting by day while hidden killers strike by night.', a: 'Werewolf' },
      { q: 'Simplest of card games, where the higher card takes both and a tie triggers a showdown.', a: 'War' },
      { q: 'Daily online puzzle of guessing a five letter word in six tries, with green and yellow hints.', a: 'Wordle' },
      { q: 'Card game of exact trick prediction using 60 cards, including four jesters.', a: 'Wizard' },
      { q: 'Chinese name for the ancient game of surrounding territory with stones on a 19 by 19 grid.', a: 'Weiqi' },
    ],
    Y: [
      { q: 'Dice game of five cubes and three throws a turn, with a 50 point bonus for five of a kind.', a: 'Yahtzee' },
      { q: 'Kris Burm abstract game where you move rings that flip a line of markers, part of the GIPF project.', a: 'Yinsh' },
      { q: 'Korean new year board game played by throwing four wooden sticks.', a: 'Yut' },
      { q: 'Israeli card game where you may call to end the round once your hand is worth seven or less.', a: 'Yaniv' },
    ],
  },
};
