import type { RawPack } from '../core/packs';

export const businessBrandsPack: RawPack = {
  id: 'business-brands',
  name: 'Business and Brands',
  description: 'Founders, logos, mergers and mascots behind the world\'s biggest companies.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '💼',
  accent: '#0f766e',
  letters: {
    A: [
      { q: 'The three-stripe German sportswear giant based in Herzogenaurach, started in 1949 by a shoemaker who fell out with his brother.', a: 'Adidas' },
      { q: 'Online retailer that Jeff Bezos launched from a Seattle garage in 1994 selling only books.', a: 'Amazon' },
      { q: 'Technology company founded in 1976 by Steve Wozniak, Ronald Wayne and a man who had worked at a fruit orchard commune.', a: 'Apple' },
      { q: 'European aerospace consortium formed in 1970 to compete with Boeing on airliners.', a: 'Airbus' },
      { q: 'German discount grocery chain built by the Albrecht brothers and split into Nord and Sud arms in 1960.', a: 'Aldi' },
      { q: 'Door-to-door cosmetics company founded in 1886 as the California Perfume Company.', a: 'Avon' },
      { q: 'Lodging marketplace begun in 2007 when two San Francisco roommates rented out floor space to design-conference visitors.', a: 'Airbnb' },
      { q: 'German car brand whose four interlocking rings stand for a 1932 merger of four manufacturers.', a: 'Audi' },
      { q: 'Consulting firm spun out of the Arthur Andersen partnership and given a new invented name in 2001.', a: 'Accenture' },
      { q: 'Charge-card and travellers-cheque company founded in 1850 as a freight forwarding business.', a: 'American Express', alt: ['Amex'] },
    ],
    B: [
      { q: 'Aerospace company founded in Seattle in 1916 by a timber magnate (surname).', a: 'Boeing' },
      { q: 'Munich carmaker whose blue and white roundel echoes the colours of the Bavarian flag.', a: 'BMW' },
      { q: 'British luxury marque founded in 1919 that won Le Mans five times in the 1920s (founder\'s surname).', a: 'Bentley' },
      { q: 'British fashion house that invented gabardine cloth and whose beige check became a status symbol.', a: 'Burberry' },
      { q: 'Vermont ice cream company started in 1978 by two childhood friends in a converted petrol station.', a: 'Ben and Jerry\'s', alt: ['Ben & Jerry\'s'] },
      { q: 'Founder of Amazon who bought The Washington Post in 2013 (surname).', a: 'Bezos' },
      { q: 'Mattel fashion doll launched in 1959 and named after the founder\'s daughter.', a: 'Barbie' },
      { q: 'Financial data terminal company founded in 1981 by a trader laid off from Salomon Brothers.', a: 'Bloomberg' },
      { q: 'Chairman of Berkshire Hathaway nicknamed the Oracle of Omaha (surname).', a: 'Buffett' },
      { q: 'French company that made the cheap disposable ballpoint pen a global standard, later adding lighters and razors.', a: 'Bic' },
      { q: 'Rum brand founded in Santiago de Cuba in 1862 whose emblem is a bat.', a: 'Bacardi' },
    ],
    C: [
      { q: 'Atlanta pharmacist John Pemberton mixed the first batch of this syrup in 1886.', a: 'Coca-Cola', alt: ['Coke'] },
      { q: 'Paris couture house whose founder popularised the little black dress and a tweed suit.', a: 'Chanel' },
      { q: 'Detroit carmaker founded in 1925 that merged with Daimler in 1998 (founder\'s surname).', a: 'Chrysler' },
      { q: 'Warehouse membership club founded in Seattle in 1983, famous for keeping its rotisserie chicken cheap on purpose.', a: 'Costco' },
      { q: 'Birmingham Quaker chocolate maker behind the Dairy Milk bar.', a: 'Cadbury' },
      { q: 'French carmaker whose double chevron badge represents helical gear teeth.', a: 'Citroen', alt: ['Citroën'] },
      { q: 'French hypermarket chain whose name is the local word for crossroads.', a: 'Carrefour' },
      { q: 'The largest privately held American company, a grain and agricultural trading giant founded in 1865.', a: 'Cargill' },
      { q: 'Toothpaste brand that began in 1806 as a New York soap and candle business.', a: 'Colgate' },
      { q: 'Executive who took over as Apple chief in 2011 after Steve Jobs stepped down (surname).', a: 'Cook' },
    ],
    D: [
      { q: 'Studio founded in 1923 by two brothers in Hollywood whose first big hit was a cartoon mouse.', a: 'Disney' },
      { q: 'Personal computer company started in 1984 in a University of Texas dorm room (founder\'s surname).', a: 'Dell' },
      { q: 'British engineer whose bagless vacuum cleaner took 5,127 prototypes (surname).', a: 'Dyson' },
      { q: 'Paris couturier whose 1947 New Look revived French fashion (surname).', a: 'Dior' },
      { q: 'Massachusetts coffee and doughnut chain that opened in 1950 under the name Open Kettle.', a: 'Dunkin', alt: ['Dunkin Donuts'] },
      { q: 'Illinois blacksmith who invented the self-scouring steel plough in 1837 (surname).', a: 'Deere' },
      { q: 'Atlanta-based airline that began life in 1925 as a crop-dusting operation.', a: 'Delta' },
      { q: 'French food company founded in Barcelona in 1919 and named after the founder\'s son Daniel.', a: 'Danone' },
      { q: 'Logistics company founded in 1969 whose name is simply the initials of its three founders.', a: 'DHL' },
      { q: 'Bologna motorcycle maker that started out in 1926 making radio components.', a: 'Ducati' },
    ],
    E: [
      { q: 'Houston energy trader whose 2001 accounting collapse also destroyed its auditor Arthur Andersen.', a: 'Enron' },
      { q: 'Swedish telecom equipment maker founded in 1876 as a telegraph repair shop.', a: 'Ericsson' },
      { q: 'Oil company created when Standard Oil of New Jersey adopted a new invented name in 1972.', a: 'Exxon' },
      { q: 'Cosmetics empire begun in 1946 by a woman from Queens selling four skin creams (full name).', a: 'Estee Lauder' },
      { q: 'Flag carrier airline of Abu Dhabi, founded in 2003.', a: 'Etihad' },
      { q: 'Flag carrier airline of Dubai, launched in 1985 with two leased aircraft.', a: 'Emirates' },
      { q: 'Online auction site founded in 1995 whose first completed sale was a broken laser pointer.', a: 'eBay' },
      { q: 'French bottled water drawn from a spa town on the south shore of Lake Geneva.', a: 'Evian' },
      { q: 'Swedish appliance maker that popularised the household vacuum cleaner from 1919.', a: 'Electrolux' },
    ],
    F: [
      { q: 'Detroit carmaker whose 1913 moving assembly line slashed the build time of the Model T (founder\'s surname).', a: 'Ford' },
      { q: 'Maranello sports car maker whose prancing horse badge appears on every model (founder\'s surname).', a: 'Ferrari' },
      { q: 'Overnight delivery company founded in 1971 whose wordmark hides a white arrow.', a: 'FedEx' },
      { q: 'Turin carmaker founded in 1899 whose name is an Italian acronym for a factory of cars.', a: 'Fiat' },
      { q: 'Orange soft drink created in Germany during the Second World War by the local Coca-Cola bottler.', a: 'Fanta' },
      { q: 'Japanese information technology group founded in 1935 and long its country\'s largest computer maker.', a: 'Fujitsu' },
      { q: 'Social network that Mark Zuckerberg launched from a Harvard dorm room in 2004.', a: 'Facebook' },
      { q: 'Californian company whose Stratocaster electric guitar debuted in 1954 (founder\'s surname).', a: 'Fender' },
      { q: 'Tyre company founded in Akron in 1900 that became Ford\'s main supplier (founder\'s surname).', a: 'Firestone' },
    ],
    G: [
      { q: 'Search company founded in 1998 by two Stanford graduate students, whose project was first called BackRub.', a: 'Google' },
      { q: 'Florentine leather goods house founded in 1921 (founder\'s surname).', a: 'Gucci' },
      { q: 'Wall Street bank founded in 1869 by a German immigrant and later joined by his son-in-law (both surnames).', a: 'Goldman Sachs' },
      { q: 'Dark Irish stout brewed at St James\'s Gate in Dublin since 1759.', a: 'Guinness' },
      { q: 'Razor company that pioneered giving away the handle to sell the blades (founder\'s surname).', a: 'Gillette' },
      { q: 'Microsoft co-founder who left Harvard to write a BASIC interpreter for the Altair (surname).', a: 'Gates' },
      { q: 'Company formed in 1892 by merging Thomas Edison\'s lighting business with a rival firm.', a: 'General Electric', alt: ['GE'] },
      { q: 'San Francisco clothing chain founded in 1969 selling jeans, named after a divide between generations.', a: 'Gap' },
      { q: 'American intercity bus line founded in Minnesota in 1914 whose running-dog emblem is on every coach.', a: 'Greyhound' },
    ],
    H: [
      { q: 'Japanese company that began in 1948 by bolting small engines onto bicycles (founder\'s surname).', a: 'Honda' },
      { q: 'Pittsburgh food company whose slogan boasted of 57 varieties.', a: 'Heinz' },
      { q: 'Paris luxury house that started in 1837 making harnesses and saddles for carriages.', a: 'Hermes' },
      { q: 'South Korean industrial group founded in 1947 whose name means modernity.', a: 'Hyundai' },
      { q: 'Rhode Island toy company behind Monopoly, G.I. Joe and Transformers.', a: 'Hasbro' },
      { q: 'Hotel chain that began in 1919 when its founder bought a small property in Cisco, Texas.', a: 'Hilton' },
      { q: 'Milwaukee motorcycle company founded in 1903 by two families working in a wooden shed (both surnames).', a: 'Harley-Davidson' },
      { q: 'Vacuum cleaner brand so dominant in Britain that its name turned into a verb.', a: 'Hoover' },
      { q: 'Bank founded in 1865 to finance trade in the British colony that is now a special administrative region of China.', a: 'HSBC' },
      { q: 'Car rental company founded in Chicago in 1918 with a dozen Model Ts (founder\'s surname).', a: 'Hertz' },
    ],
    I: [
      { q: 'Swedish flat-pack furniture retailer founded in 1943 by a seventeen-year-old.', a: 'IKEA' },
      { q: 'Computing giant nicknamed Big Blue, formed in 1911 as Computing-Tabulating-Recording.', a: 'IBM' },
      { q: 'Chipmaker founded in 1968 by Robert Noyce and Gordon Moore.', a: 'Intel' },
      { q: 'Photo sharing app that Facebook bought for about a billion dollars in 2012.', a: 'Instagram' },
      { q: 'Flag carrier airline of Spain, founded in 1927.', a: 'Iberia' },
      { q: 'Procter and Gamble soap launched in 1879 and advertised as 99 and 44 hundredths percent pure.', a: 'Ivory' },
      { q: 'Nissan\'s luxury division, launched in North America in 1989.', a: 'Infiniti' },
    ],
    J: [
      { q: 'Apple co-founder who returned to the company in 1997 and launched the iMac (surname).', a: 'Jobs' },
      { q: 'American bank named after the financier who assembled U.S. Steel in 1901.', a: 'JPMorgan', alt: ['JPMorgan Chase'] },
      { q: 'British marque founded in 1922 as the Swallow Sidecar Company.', a: 'Jaguar' },
      { q: 'New Jersey firm founded in 1886 that pioneered sterile surgical dressings and the sticking plaster.', a: 'Johnson and Johnson', alt: ['Johnson & Johnson'] },
      { q: 'Brand born from the light utility vehicle Willys built for the American army in the Second World War.', a: 'Jeep' },
      { q: 'New York low-cost airline launched in 2000 out of Kennedy Airport.', a: 'JetBlue' },
      { q: 'Tennessee whiskey filtered through sugar maple charcoal and distilled in Lynchburg.', a: 'Jack Daniel\'s' },
      { q: 'Filipino fast-food chain that outsells McDonald\'s in its home market.', a: 'Jollibee' },
    ],
    K: [
      { q: 'Battle Creek brothers who stumbled on flaked cereal in 1894 while boiling wheat (surname).', a: 'Kellogg' },
      { q: 'Rochester film company whose founder invented a short meaningless name he thought sounded strong.', a: 'Kodak' },
      { q: 'Fried chicken chain built by Harland Sanders, who began franchising his secret recipe in 1952.', a: 'KFC' },
      { q: 'Chicago cheese company founded in 1903 that invented shelf-stable processed cheese in a tin.', a: 'Kraft' },
      { q: 'South Korean carmaker that began in 1944 making bicycle parts.', a: 'Kia' },
      { q: 'Cincinnati grocery chain founded in 1883, the largest supermarket operator in America.', a: 'Kroger' },
      { q: 'Japanese maker of yellow construction machinery, second in the world only to Caterpillar.', a: 'Komatsu' },
      { q: 'Doughnut chain founded in Winston-Salem in 1937, known for a glowing Hot Now sign.', a: 'Krispy Kreme' },
      { q: 'Japanese heavy industry group whose green motorcycles include the Ninja.', a: 'Kawasaki' },
    ],
    L: [
      { q: 'Danish toy company founded in 1932 by a carpenter, its name a contraction of play well.', a: 'Lego' },
      { q: 'Bavarian immigrant\'s San Francisco firm that patented riveted work trousers in 1873.', a: 'Levi\'s' },
      { q: 'Paris trunk maker founded in 1854 whose monogram canvas appeared in 1896 (full name).', a: 'Louis Vuitton' },
      { q: 'Flag carrier airline of Germany, whose crane emblem dates to 1918.', a: 'Lufthansa' },
      { q: 'Italian supercar maker started by a tractor manufacturer annoyed by Enzo Ferrari.', a: 'Lamborghini' },
      { q: 'Tea brand created by a Glasgow grocer who bought his own plantations in Ceylon.', a: 'Lipton' },
      { q: 'London insurance market that grew out of a seventeenth-century coffee house.', a: 'Lloyd\'s' },
      { q: 'Toyota\'s luxury division, launched in 1989 with the LS 400 saloon.', a: 'Lexus' },
      { q: 'French cosmetics giant founded in 1909 by a chemist selling a safe hair dye.', a: 'L\'Oreal', alt: ['LOreal'] },
    ],
    M: [
      { q: 'Fast-food chain that Ray Kroc franchised from two brothers running a stand in San Bernardino.', a: 'McDonald\'s' },
      { q: 'Company founded in Albuquerque in 1975 by two school friends to sell a BASIC interpreter.', a: 'Microsoft' },
      { q: 'German luxury car brand named after the daughter of an Austrian businessman who ordered custom Daimlers.', a: 'Mercedes' },
      { q: 'French tyre company whose restaurant guide awards stars.', a: 'Michelin' },
      { q: 'California toy company founded in 1945 whose name blends the names of two of its founders.', a: 'Mattel' },
      { q: 'Family-owned American confectioner behind Snickers, Skittles and pet food brands.', a: 'Mars' },
      { q: 'Wall Street firm founded in 1935 after the Glass-Steagall Act forced a bank to split (both surnames).', a: 'Morgan Stanley' },
      { q: 'Chicago company whose engineer made the first handheld mobile phone call in 1973.', a: 'Motorola' },
      { q: 'Chief executive of Tesla and SpaceX, born in Pretoria (surname).', a: 'Musk' },
      { q: 'Danish company that operates the world\'s largest container shipping line.', a: 'Maersk' },
    ],
    N: [
      { q: 'Oregon sportswear company founded in 1964 under the name Blue Ribbon Sports.', a: 'Nike' },
      { q: 'Kyoto company founded in 1889 that spent decades making playing cards.', a: 'Nintendo' },
      { q: 'Swiss food group founded in 1866, the largest in the world by revenue.', a: 'Nestle' },
      { q: 'Finnish company that began in 1865 as a riverside pulp mill.', a: 'Nokia' },
      { q: 'Service launched in 1997 posting DVDs by mail that later helped bury Blockbuster.', a: 'Netflix' },
      { q: 'Japanese carmaker that retired its Datsun export brand in the early 1980s.', a: 'Nissan' },
      { q: 'Graphics chip company founded in 1993 after meetings at a Denny\'s in San Jose.', a: 'Nvidia' },
      { q: 'Seattle retailer that began in 1901 as a shoe shop opened by a Swedish immigrant.', a: 'Nordstrom' },
      { q: 'Electronic stock market launched in 1971 that lists many technology companies.', a: 'Nasdaq' },
    ],
    O: [
      { q: 'Database software company co-founded by Larry Ellison in 1977.', a: 'Oracle' },
      { q: 'Shaving and deodorant brand launched in 1937 with sailing ship packaging.', a: 'Old Spice' },
      { q: 'Chocolate sandwich biscuit introduced by Nabisco in 1912.', a: 'Oreo' },
      { q: 'Skin care brand created in South Africa in the 1950s and sold as a pink beauty fluid.', a: 'Olay', alt: ['Oil of Olay'] },
      { q: 'German carmaker founded in 1862 making sewing machines, later owned for decades by General Motors.', a: 'Opel' },
      { q: 'Swiss watchmaker whose Speedmaster was worn on the Moon in 1969.', a: 'Omega' },
      { q: 'Company whose founder demonstrated a safety brake for passenger lifts in 1854 (surname).', a: 'Otis' },
      { q: 'Telecom brand that France Telecom adopted for the whole group in 2006.', a: 'Orange' },
    ],
    P: [
      { q: 'Cola created in 1893 by a North Carolina pharmacist and first sold as Brad\'s Drink.', a: 'Pepsi' },
      { q: 'Stuttgart sports car maker whose rear-engined 911 debuted in 1963 (founder\'s surname).', a: 'Porsche' },
      { q: 'Cincinnati partnership formed in 1837 between a candlemaker and a soapmaker (both surnames).', a: 'Procter and Gamble', alt: ['P&G'] },
      { q: 'Milan house founded in 1913 for leather goods that became famous in the 1980s for nylon bags.', a: 'Prada' },
      { q: 'Japanese electronics company founded in 1918 by Konosuke Matsushita.', a: 'Panasonic' },
      { q: 'French carmaker whose lion badge came from its nineteenth-century steel and saw blade business.', a: 'Peugeot' },
      { q: 'Brooklyn chemical firm founded in 1849 whose first hit product was a palatable worm treatment.', a: 'Pfizer' },
      { q: 'Animation studio spun out of Lucasfilm\'s computer division and bought by Steve Jobs in 1986.', a: 'Pixar' },
      { q: 'Dutch electronics company founded in Eindhoven in 1891 to make light bulbs.', a: 'Philips' },
      { q: 'German sportswear firm founded by Rudolf Dassler after a bitter split with his sibling.', a: 'Puma' },
    ],
    Q: [
      { q: 'Flag carrier airline of Australia, founded in 1920 and one of the oldest still flying.', a: 'Qantas' },
      { q: 'Cereal company that in 1877 registered the first American trademark for a breakfast food, using a man in a wide hat.', a: 'Quaker Oats', alt: ['Quaker'] },
      { q: 'Doha-based airline founded in 1993 and a member of the Oneworld alliance.', a: 'Qatar Airways' },
      { q: 'Surfwear brand founded in 1969 in Torquay, Victoria.', a: 'Quiksilver' },
      { q: 'San Diego company founded in 1985 whose Snapdragon processors power many phones.', a: 'Qualcomm' },
    ],
    R: [
      { q: 'Geneva watchmaker founded in London in 1905 whose Oyster case was the first waterproof wristwatch.', a: 'Rolex' },
      { q: 'French carmaker founded in 1899 and nationalised after the Second World War.', a: 'Renault' },
      { q: 'British marque born of a 1904 meeting between an aristocratic car dealer and an engineer (both surnames).', a: 'Rolls-Royce' },
      { q: 'British sportswear brand named after an African gazelle and bought by Adidas in 2006.', a: 'Reebok' },
      { q: 'Irish low-cost airline founded in 1984 that pioneered very cheap European fares.', a: 'Ryanair' },
      { q: 'Founder of Standard Oil and the first American billionaire (surname).', a: 'Rockefeller' },
      { q: 'American designer who started with wide neckties in 1967 and built a polo-themed empire (full name).', a: 'Ralph Lauren' },
      { q: 'Austrian energy drink adapted in 1987 from a Thai tonic called Krating Daeng.', a: 'Red Bull' },
    ],
    S: [
      { q: 'South Korean group founded in 1938 as a trading company selling dried fish and noodles.', a: 'Samsung' },
      { q: 'Tokyo company founded in 1946 as Tokyo Tsushin Kogyo before adopting a short global name.', a: 'Sony' },
      { q: 'Seattle coffee chain founded in 1971 and named after a character in Moby-Dick.', a: 'Starbucks' },
      { q: 'German engineering group founded in 1847 around an improved pointer telegraph (founder\'s surname).', a: 'Siemens' },
      { q: 'Oil major whose founder\'s family firm first imported oriental curios to London.', a: 'Shell' },
      { q: 'Japanese carmaker whose badge shows six stars of the Pleiades cluster.', a: 'Subaru' },
      { q: 'Airline that split from the Malaysian carrier in 1972 and made its sarong kebaya uniform famous.', a: 'Singapore Airlines' },
      { q: 'Swiss company whose cheap plastic quartz watches rescued the national industry in the 1980s.', a: 'Swatch' },
      { q: 'American retailer whose mail-order catalogue once sold entire kit houses.', a: 'Sears' },
      { q: 'Swedish music streaming service launched in 2008.', a: 'Spotify' },
    ],
    T: [
      { q: 'Japanese carmaker that grew out of a loom business and changed one letter of the family name.', a: 'Toyota' },
      { q: 'Electric car company founded in 2003 and named after a Serbian-American inventor.', a: 'Tesla' },
      { q: 'New York jeweller founded in 1837 whose robin\'s egg blue box colour is trademarked.', a: 'Tiffany' },
      { q: 'Microblogging service launched in 2006 that limited posts to 140 characters.', a: 'Twitter' },
      { q: 'Minneapolis discount retailer launched in 1962 by the Dayton department store company.', a: 'Target' },
      { q: 'Japanese electronics group formed in 1939 by merging two Tokyo engineering firms.', a: 'Toshiba' },
      { q: 'Indian conglomerate founded in 1868 that bought Jaguar Land Rover in 2008.', a: 'Tata' },
      { q: 'Airtight plastic container brand sold from the late 1940s through home parties.', a: 'Tupperware' },
      { q: 'Shenzhen company behind WeChat, founded in 1998.', a: 'Tencent' },
    ],
    U: [
      { q: 'Ride-hailing company founded in San Francisco in 2009 by Travis Kalanick and Garrett Camp.', a: 'Uber' },
      { q: 'Anglo-Dutch consumer goods group formed in 1929 from a soap maker and a margarine maker.', a: 'Unilever' },
      { q: 'Parcel company founded in Seattle in 1907 as a bicycle messenger service, known for brown vans.', a: 'UPS' },
      { q: 'Japanese clothing retailer owned by the Fast Retailing group.', a: 'Uniqlo' },
      { q: 'Baltimore sportswear brand founded in 1996 by a former college footballer selling sweat-wicking shirts.', a: 'Under Armour' },
      { q: 'Company created in 1901 in the first billion-dollar corporate deal in history.', a: 'US Steel' },
    ],
    V: [
      { q: 'German carmaker founded in 1937 whose Beetle became the best-selling single car design.', a: 'Volkswagen' },
      { q: 'Swedish carmaker that gave its three-point seatbelt patent away free in 1959.', a: 'Volvo' },
      { q: 'Payment card network that started in 1958 as BankAmericard.', a: 'Visa' },
      { q: 'Group founded by Richard Branson, starting with a mail-order record business in 1970.', a: 'Virgin' },
      { q: 'British mobile operator that carried the first cellular call in the United Kingdom in 1985.', a: 'Vodafone' },
      { q: 'Italian fashion house founded in 1978 whose logo is the head of Medusa.', a: 'Versace' },
    ],
    W: [
      { q: 'Retailer founded in Rogers, Arkansas in 1962 and now the largest company in the world by revenue.', a: 'Walmart' },
      { q: 'Square-patty burger chain founded in Columbus, Ohio in 1969 and named after the founder\'s daughter.', a: 'Wendy\'s' },
      { q: 'Chicago company that gave away chewing gum to sell baking powder before switching to gum alone.', a: 'Wrigley' },
      { q: 'Bank founded in 1852 whose stagecoach emblem recalls its express delivery past (both surnames).', a: 'Wells Fargo' },
      { q: 'Michigan appliance maker founded in 1911 making electric wringer washing machines.', a: 'Whirlpool' },
      { q: 'Messaging app that Facebook bought in 2014 for about nineteen billion dollars.', a: 'WhatsApp' },
      { q: 'Five-and-dime pioneer whose New York headquarters was the world\'s tallest building in 1913.', a: 'Woolworth' },
    ],
    X: [
      { q: 'Company whose 1959 plain-paper copier was so dominant that its name became a verb.', a: 'Xerox' },
      { q: 'Beijing electronics company founded in 2010 and known for value-priced smartphones.', a: 'Xiaomi' },
      { q: 'Microsoft\'s games console brand, launched in 2001.', a: 'Xbox' },
    ],
    Y: [
      { q: 'Web directory and portal founded by Jerry Yang and David Filo in 1994.', a: 'Yahoo' },
      { q: 'Japanese company that makes both grand pianos and motorcycles, with tuning forks in its logo.', a: 'Yamaha' },
      { q: 'Japanese company that dominates the global market for zip fasteners.', a: 'YKK' },
      { q: 'French designer who took charge at Dior aged twenty-one and later put women in tuxedos (full name).', a: 'Yves Saint Laurent', alt: ['YSL'] },
      { q: 'Company spun off from PepsiCo in 1997 that owns Taco Bell, KFC and Pizza Hut.', a: 'Yum Brands', alt: ['Yum'] },
    ],
    Z: [
      { q: 'Spanish fast-fashion chain founded in 1975 in A Coruna by Amancio Ortega.', a: 'Zara' },
      { q: 'German optics company founded in Jena in 1846 (founder\'s surname).', a: 'Zeiss' },
      { q: 'Windproof metal lighter brand made in Bradford, Pennsylvania since 1932.', a: 'Zippo' },
      { q: 'Video conferencing company founded in 2011 by a former Cisco engineer.', a: 'Zoom' },
    ],
  },
};
