import type { RawPack } from '../core/packs';

export const carsMotorsportPack: RawPack = {
  id: 'cars-motorsport',
  name: 'Cars and Motorsport',
  description: 'Marques, models, circuits, champions and the language of machines.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🏎️',
  accent: '#b91c1c',
  letters: {
    A: [
      { q: 'Italian marque founded in Milan in 1910 whose badge pairs a red cross with a crowned serpent.', a: 'Alfa Romeo' },
      { q: 'German marque whose badge is four interlocking rings, marking a merger of four firms in 1932.', a: 'Audi' },
      { q: 'British maker of the DB5 driven by James Bond in Goldfinger.', a: 'Aston Martin' },
      { q: 'Brazilian triple world champion who was killed at Imola in 1994.', a: 'Ayrton Senna', alt: ['Senna'] },
      { q: 'Italian driver who took back to back world titles in 1952 and 1953.', a: 'Alberto Ascari', alt: ['Ascari'] },
      { q: 'Premium badge that Honda created for the North American market in 1986.', a: 'Acura' },
      { q: 'Tuning marque with a scorpion badge, long tied to hot versions of small Fiats.', a: 'Abarth' },
      { q: 'Lamborghini V12 flagship launched in 2011 and named after a fighting bull.', a: 'Aventador' },
      { q: 'Belt driven generator that keeps a running engine charging the battery.', a: 'Alternator' },
      { q: 'German motorway network famous for long stretches with no posted speed limit.', a: 'Autobahn' },
      { q: 'Frenchman nicknamed the Professor who won four world championships.', a: 'Alain Prost', alt: ['Prost'] },
    ],
    B: [
      { q: 'Molsheim based French marque that built the Veyron.', a: 'Bugatti' },
      { q: 'British luxury marque founded in 1919 with a winged letter badge, now owned by Volkswagen.', a: 'Bentley' },
      { q: 'Munich maker whose badge is a blue and white quartered roundel.', a: 'BMW' },
      { q: 'Only Formula One team whose founder won a drivers title driving one of its own cars.', a: 'Brabham' },
      { q: 'New South Wales town whose Mount Panorama circuit hosts a famous 1000 km touring car race.', a: 'Bathurst' },
      { q: 'Air cooled, rear engined Volkswagen that became the best selling car of its era.', a: 'Beetle' },
      { q: 'Italian firm best known for high performance brake calipers and discs.', a: 'Brembo' },
      { q: 'Utah salt flats long used for land speed record runs.', a: 'Bonneville' },
      { q: 'Flat layout in which opposed pistons punch outward, used by Subaru and Porsche.', a: 'Boxer engine', alt: ['Boxer'] },
      { q: 'General Motors division founded by a Scottish born engineer, badge of three shields.', a: 'Buick' },
      { q: 'Surrey banked oval opened in 1907, the first purpose built motor racing circuit in the world.', a: 'Brooklands' },
    ],
    C: [
      { q: 'General Motors division founded in 1911 and known for its bowtie badge.', a: 'Chevrolet' },
      { q: 'American sports car launched in 1953 and still built today, the longest running nameplate of its kind.', a: 'Corvette' },
      { q: 'French marque with a double chevron badge, maker of the futuristic DS.', a: 'Citroen', alt: ['Citroën'] },
      { q: 'General Motors luxury division named after the French officer who founded Detroit.', a: 'Cadillac' },
      { q: 'Chevrolet pony car launched in 1967 to answer the Ford Mustang.', a: 'Camaro' },
      { q: 'Device that mixed air and petrol before injection systems took over.', a: 'Carburettor', alt: ['Carburetor'] },
      { q: 'Lobed rotating part that pushes an engine valve open at exactly the right moment.', a: 'Camshaft' },
      { q: 'Pedal operated coupling that disconnects the engine from the gearbox.', a: 'Clutch' },
      { q: 'British engine firm whose DFV V8 dominated Formula One from 1967.', a: 'Cosworth' },
      { q: 'Founder of Lotus, famous for the maxim about adding lightness.', a: 'Colin Chapman' },
      { q: 'Tight artificial sequence of bends inserted to slow cars on a fast straight.', a: 'Chicane' },
      { q: 'British team that put the engine behind the driver and took the 1959 world title.', a: 'Cooper' },
    ],
    D: [
      { q: 'American brand with a ram head badge, maker of the Viper.', a: 'Dodge' },
      { q: 'Export badge that Nissan retired in the mid 1980s.', a: 'Datsun' },
      { q: 'Florida speedway that hosts the season opening 500 mile stock car race.', a: 'Daytona' },
      { q: 'Gearset that lets the driven wheels turn at unequal speeds through a corner.', a: 'Differential' },
      { q: 'Stainless steel gullwing coupe built in Northern Ireland and made famous by a film trilogy.', a: 'DeLorean' },
      { q: 'Compression ignition engine type named after its German inventor.', a: 'Diesel' },
      { q: 'Briton who won the 1996 world title, the son of a two time champion.', a: 'Damon Hill' },
      { q: 'American luxury marque of the 1920s and 1930s whose Model J was the ultimate car of the era.', a: 'Duesenberg' },
      { q: 'Rally raid event first run from Paris to a West African capital.', a: 'Dakar' },
      { q: 'Aerodynamic load that presses a race car onto the track surface.', a: 'Downforce' },
    ],
    E: [
      { q: 'Founder of the Maranello racing team and marque that carries his surname.', a: 'Enzo Ferrari' },
      { q: 'Small Ford that won rallies across Europe in its first and second generation forms.', a: 'Escort' },
      { q: 'Brazilian who became the youngest world champion in 1972.', a: 'Emerson Fittipaldi', alt: ['Fittipaldi'] },
      { q: 'System that carries burnt gases away from the engine and out of the car.', a: 'Exhaust' },
      { q: 'Portuguese circuit that hosted a grand prix from 1984 to 1996.', a: 'Estoril' },
      { q: 'Lotus lightweight roadster of 1996, named after the granddaughter of the chairman.', a: 'Elise' },
      { q: 'Steeply uphill left then right sweep at Spa, the most famous corner in Formula One.', a: 'Eau Rouge' },
      { q: 'Computer that manages fuelling and ignition timing in a modern car.', a: 'Engine control unit', alt: ['ECU'] },
    ],
    F: [
      { q: 'Only team to have entered every world championship season since 1950.', a: 'Ferrari' },
      { q: 'Detroit maker whose founder introduced the moving assembly line in 1913.', a: 'Ford' },
      { q: 'Turin based Italian maker of the tiny 500 city car.', a: 'Fiat' },
      { q: 'Spaniard who won world titles in 2005 and 2006 driving for Renault.', a: 'Fernando Alonso', alt: ['Alonso'] },
      { q: 'Ford global compact launched in 1998 to replace the Escort.', a: 'Focus' },
      { q: 'Layout of opposed cylinders that Porsche used in the 911 for decades.', a: 'Flat six' },
      { q: 'Top single seater world series, first contested in 1950.', a: 'Formula One' },
      { q: 'System that sprays petrol precisely into the intake or the cylinder.', a: 'Fuel injection' },
      { q: 'Heavy disc bolted to the crankshaft that smooths out engine rotation.', a: 'Flywheel' },
      { q: 'Body style with a roofline that slopes continuously down to the tail.', a: 'Fastback' },
      { q: 'Japanese circuit at the foot of the tallest volcano in the country, host of the 1976 and 1977 grands prix.', a: 'Fuji Speedway', alt: ['Fuji'] },
      { q: 'Ford supermini launched in 1976 and built for more than four decades.', a: 'Fiesta' },
    ],
    G: [
      { q: 'South African designer of the Brabham fan car and the McLaren F1 road car.', a: 'Gordon Murray' },
      { q: 'Nickname for the upward hinged doors of the Mercedes 300 SL.', a: 'Gullwing' },
      { q: 'Volkswagen hatchback introduced in 1974 to replace the Beetle.', a: 'Golf', alt: ['Rabbit'] },
      { q: 'Assembly of ratios that matches engine speed to road speed.', a: 'Gearbox' },
      { q: 'Sussex estate whose Festival of Speed hillclimb draws huge crowds each summer.', a: 'Goodwood' },
      { q: 'French Canadian Ferrari driver who was killed at Zolder in 1982.', a: 'Gilles Villeneuve' },
      { q: 'French term used worldwide for a top level motor race.', a: 'Grand Prix' },
      { q: 'Detroit giant that owns Chevrolet, Cadillac and Buick.', a: 'General Motors', alt: ['GM'] },
      { q: 'Ford racer built to beat Ferrari at Le Mans, named for its height in inches.', a: 'GT40' },
      { q: 'Only driver to win at Monaco, at Indianapolis and at Le Mans.', a: 'Graham Hill' },
    ],
    H: [
      { q: 'Japanese maker that began with motorcycles and won its first grand prix in 1965.', a: 'Honda' },
      { q: 'South Korean maker founded in 1967 that later won the world rally makers title.', a: 'Hyundai' },
      { q: 'Civilian brand spun off from an American military light utility truck.', a: 'Hummer' },
      { q: 'Drivetrain that combines a petrol engine with one or more electric motors.', a: 'Hybrid' },
      { q: 'Unit of engine output first defined by James Watt.', a: 'Horsepower' },
      { q: 'German circuit in the Rhine valley where Jim Clark was killed in 1968.', a: 'Hockenheim' },
      { q: 'Chrysler engine family named for its domed combustion chambers.', a: 'Hemi' },
      { q: 'Corner that doubles back on itself through nearly 180 degrees.', a: 'Hairpin' },
      { q: 'Lever or pedal that locks the rear wheels when a car is parked.', a: 'Handbrake' },
    ],
    I: [
      { q: 'American oval race run over 200 laps every Memorial Day weekend.', a: 'Indianapolis 500', alt: ['Indy 500'] },
      { q: 'Italian circuit named after Enzo and Dino Ferrari.', a: 'Imola' },
      { q: 'System that fires the spark plugs at exactly the right instant.', a: 'Ignition' },
      { q: 'Premium badge that Nissan launched in 1989.', a: 'Infiniti' },
      { q: 'Japanese maker that left the car market to concentrate on trucks and pickups.', a: 'Isuzu' },
      { q: 'Radiator that cools compressed air before it reaches the cylinders.', a: 'Intercooler' },
      { q: 'Subaru saloon that carried the brand to three straight rally makers titles in the 1990s.', a: 'Impreza' },
    ],
    J: [
      { q: 'British marque whose D-Type won at Le Mans three years running.', a: 'Jaguar' },
      { q: 'American off road brand descended from a wartime light utility vehicle.', a: 'Jeep' },
      { q: 'Argentine who won five world titles in the 1950s with four different teams.', a: 'Juan Manuel Fangio', alt: ['Fangio'] },
      { q: 'Scot who won two world titles and also the 1965 Indianapolis 500.', a: 'Jim Clark' },
      { q: 'Three time champion from Scotland who led the 1970s campaign for circuit safety.', a: 'Jackie Stewart' },
      { q: 'Briton who won the 2009 world title driving for Brawn.', a: 'Jenson Button' },
      { q: 'Andalusian circuit long used for winter testing.', a: 'Jerez' },
      { q: 'Only man to win world championships on two wheels and on four.', a: 'John Surtees' },
    ],
    K: [
      { q: 'South Korean maker that is the sister company of Hyundai.', a: 'Kia' },
      { q: 'Finn who took the 2007 world title for Ferrari by a single point.', a: 'Kimi Raikkonen', alt: ['Räikkönen', 'Raikkonen'] },
      { q: 'Swedish hypercar maker founded in 1994.', a: 'Koenigsegg' },
      { q: 'South African circuit near Johannesburg that hosted grands prix.', a: 'Kyalami' },
      { q: 'Small chassis category where nearly every modern champion began.', a: 'Karting' },
      { q: 'Uncontrolled combustion that makes an engine ping when it is labouring.', a: 'Knock' },
    ],
    L: [
      { q: 'Italian supercar maker founded in 1963 by a tractor magnate.', a: 'Lamborghini' },
      { q: 'French town whose 24 hour race is the greatest prize in endurance racing.', a: 'Le Mans' },
      { q: 'British marque founded by Colin Chapman in 1952.', a: 'Lotus' },
      { q: 'British maker of the Defender and the Discovery.', a: 'Land Rover' },
      { q: 'Briton who took a record equalling seventh world title in 2020.', a: 'Lewis Hamilton' },
      { q: 'Italian marque that won six straight world rally makers titles from 1987.', a: 'Lancia' },
      { q: 'Luxury badge that Toyota launched in 1989 with the LS 400.', a: 'Lexus' },
      { q: 'Ford luxury division named after an American president.', a: 'Lincoln' },
      { q: 'Device that stops one spinning wheel from taking all the torque.', a: 'Limited slip differential', alt: ['LSD'] },
      { q: 'Californian circuit famous for the plunging Corkscrew.', a: 'Laguna Seca' },
      { q: 'Soviet marque built at Togliatti using licensed Fiat designs.', a: 'Lada' },
      { q: 'Rally technique of slowing the car with one pedal while keeping the throttle open.', a: 'Left foot braking' },
    ],
    M: [
      { q: 'German marque whose three pointed star stands for land, sea and air.', a: 'Mercedes-Benz', alt: ['Mercedes'] },
      { q: 'Woking based team founded by a New Zealander in 1963.', a: 'McLaren' },
      { q: 'German who won five consecutive world titles from 2000 to 2004.', a: 'Michael Schumacher', alt: ['Schumacher'] },
      { q: 'Street race through a principality, first run in 1929.', a: 'Monaco' },
      { q: 'Italian circuit set in a royal park and nicknamed the temple of speed.', a: 'Monza' },
      { q: 'Ford pony car of 1964 with a galloping horse badge.', a: 'Mustang' },
      { q: 'Alec Issigonis design of 1959 that turned the engine sideways to save space.', a: 'Mini' },
      { q: 'Japanese maker that won Le Mans in 1991 with a rotary powered car.', a: 'Mazda' },
      { q: 'Marque founded in Bologna whose badge is a trident.', a: 'Maserati' },
      { q: 'German luxury name revived by Mercedes in 2002.', a: 'Maybach' },
      { q: 'Set of passages that feeds air into or gathers gases from the cylinders.', a: 'Manifold' },
      { q: 'Alpine season opener of the world championship, famous for icy mountain passes above the Alpes-Maritimes.', a: 'Monte Carlo Rally', alt: ['Monte Carlo'] },
      { q: 'Japanese maker whose Lancer Evolution took four straight rally drivers titles with Tommi Makinen.', a: 'Mitsubishi' },
      { q: 'Thousand mile Italian road race that was banned after a fatal crash in 1957.', a: 'Mille Miglia' },
      { q: 'French tyre maker whose mascot is built from stacked white rings.', a: 'Michelin' },
    ],
    N: [
      { q: 'Japanese maker of the GT-R, sold abroad under a different badge until the 1980s.', a: 'Nissan' },
      { q: 'Eifel circuit whose 20.8 km Nordschleife loop is called the Green Hell.', a: 'Nurburgring', alt: ['Nürburgring'] },
      { q: 'American stock car series founded at Daytona Beach in 1948.', a: 'NASCAR' },
      { q: 'Briton who won the 1992 world title and the 1993 American open wheel crown.', a: 'Nigel Mansell', alt: ['Mansell'] },
      { q: 'Austrian who returned to racing six weeks after a fiery crash in 1976.', a: 'Niki Lauda', alt: ['Lauda'] },
      { q: 'Gas injected into an engine to add oxygen and give a brief power boost.', a: 'Nitrous oxide' },
      { q: 'Gearbox position in which no drive reaches the wheels at all.', a: 'Neutral' },
      { q: 'Engine that draws in air without a turbo or a supercharger.', a: 'Naturally aspirated' },
    ],
    O: [
      { q: 'General Motors division founded in 1897 and shut down in 2004.', a: 'Oldsmobile' },
      { q: 'German General Motors brand that began as a sewing machine firm, badge of a lightning bolt.', a: 'Opel' },
      { q: 'Rating of how well a fuel resists knocking.', a: 'Octane' },
      { q: 'Track shape used for most American stock car racing.', a: 'Oval' },
      { q: 'Instrument that records the total distance a car has covered.', a: 'Odometer' },
    ],
    P: [
      { q: 'Stuttgart maker with a record nineteen outright wins at Le Mans.', a: 'Porsche' },
      { q: 'French marque with a lion badge that began as a steel and tools business.', a: 'Peugeot' },
      { q: 'Italian tyre maker that has been the sole Formula One supplier since 2011.', a: 'Pirelli' },
      { q: 'General Motors division that built the GTO and the Firebird.', a: 'Pontiac' },
      { q: 'Scheduled halt during a race for fresh tyres and fuel.', a: 'Pit stop' },
      { q: 'Front spot on the starting grid, earned by the fastest qualifier.', a: 'Pole position' },
      { q: 'Component that slides inside a cylinder and turns the crankshaft.', a: 'Piston' },
      { q: 'Chrysler division that built the Barracuda and the Road Runner.', a: 'Plymouth' },
      { q: 'Modena based hypercar maker of the Zonda and the Huayra.', a: 'Pagani' },
      { q: 'Colorado mountain hillclimb known as the Race to the Clouds.', a: 'Pikes Peak' },
      { q: 'Enclosure behind the pits where teams park their transporters.', a: 'Paddock' },
      { q: 'Toyota model of 1997 that took hybrid cars into the mainstream.', a: 'Prius' },
    ],
    Q: [
      { q: 'Audi coupe of 1980 whose four wheel drive transformed rallying.', a: 'Quattro' },
      { q: 'Session that decides the starting order for a race.', a: 'Qualifying' },
    ],
    R: [
      { q: 'French maker that pioneered turbocharged engines in Formula One from 1977.', a: 'Renault' },
      { q: 'British marque whose bonnet mascot is the Spirit of Ecstasy.', a: 'Rolls-Royce' },
      { q: 'Racing format run on closed public roads in timed stages.', a: 'Rally' },
      { q: 'Finned unit at the front of a car that sheds heat from the coolant.', a: 'Radiator' },
      { q: 'Brazilian who partnered Michael Schumacher at Ferrari for six seasons.', a: 'Rubens Barrichello', alt: ['Barrichello'] },
      { q: 'Tubular structure that protects the occupants of a competition car.', a: 'Roll cage' },
      { q: 'Croatian electric hypercar firm founded in 2009.', a: 'Rimac' },
      { q: 'Luxury off roader launched in 1970 that created a whole premium class.', a: 'Range Rover' },
      { q: 'Layout that sends power to the back axle only.', a: 'Rear-wheel drive' },
      { q: 'French circuit in the Champagne country that hosted grands prix until 1966.', a: 'Reims' },
    ],
    S: [
      { q: 'Japanese maker with a six star badge and a fondness for opposed engines.', a: 'Subaru' },
      { q: 'Czech maker founded in 1895 and now part of the Volkswagen group.', a: 'Skoda', alt: ['Škoda'] },
      { q: 'Former airfield in Northamptonshire that held the first world championship race in 1950.', a: 'Silverstone' },
      { q: 'German who took four straight world titles with Red Bull.', a: 'Sebastian Vettel', alt: ['Vettel'] },
      { q: 'Belgian circuit in the Ardennes forest, home of the Eau Rouge sweep.', a: 'Spa-Francorchamps', alt: ['Spa'] },
      { q: 'Figure of eight Japanese circuit owned by Honda.', a: 'Suzuka' },
      { q: 'Springs and dampers that link the wheels to the body.', a: 'Suspension' },
      { q: 'Belt driven compressor that forces extra air into an engine.', a: 'Supercharger' },
      { q: 'Briton often called the greatest driver never to win a world title.', a: 'Stirling Moss', alt: ['Moss'] },
      { q: 'Swiss team that entered Formula One in 1993.', a: 'Sauber' },
      { q: 'American term for a three box body with a separate boot.', a: 'Sedan', alt: ['Saloon'] },
      { q: 'Dial that shows how fast a car is travelling.', a: 'Speedometer' },
      { q: 'Spanish maker founded in 1950 and now part of the Volkswagen group.', a: 'Seat', alt: ['SEAT'] },
      { q: 'Vehicle that leads the field at reduced pace after an incident.', a: 'Safety car' },
      { q: 'Swedish maker of the 900 that grew out of an aircraft company.', a: 'Saab' },
    ],
    T: [
      { q: 'Japanese firm that was the largest carmaker in the world through much of the 2010s.', a: 'Toyota' },
      { q: 'American electric maker whose first model was the Roadster.', a: 'Tesla' },
      { q: 'Exhaust driven compressor that raises the output of an engine.', a: 'Turbocharger', alt: ['Turbo'] },
      { q: 'Sicilian road race first run in 1906.', a: 'Targa Florio' },
      { q: 'Twisting force an engine produces, measured in newton metres.', a: 'Torque' },
      { q: 'Electronic system that cuts power when a driven wheel starts to spin.', a: 'Traction control' },
      { q: 'Italian pre-war ace who beat the German teams at the 1935 German Grand Prix.', a: 'Tazio Nuvolari', alt: ['Nuvolari'] },
      { q: 'East German car with a body made of resin reinforced cotton waste.', a: 'Trabant' },
      { q: 'Jet propelled car that set the first supersonic land speed record in 1997.', a: 'Thrust SSC' },
    ],
    U: [
      { q: 'Australian term for a pickup built on a passenger car body.', a: 'Ute' },
      { q: 'Handling trait in which the front tyres lose grip and the car runs wide.', a: 'Understeer' },
      { q: 'Mercedes built go anywhere utility truck introduced after the Second World War.', a: 'Unimog' },
    ],
    V: [
      { q: 'Wolfsburg based maker whose name translates as the car of the people.', a: 'Volkswagen', alt: ['VW'] },
      { q: 'Swedish maker that gave away its three point seatbelt patent in 1959.', a: 'Volvo' },
      { q: 'British General Motors brand whose badge is a griffin.', a: 'Vauxhall' },
      { q: 'Bugatti flagship of 2005 with 1001 horsepower from a W16 engine.', a: 'Veyron' },
      { q: 'Dodge sports car of 1992 powered by a ten cylinder engine.', a: 'Viper' },
      { q: 'Poppet part that lets gases into and out of a cylinder.', a: 'Valve' },
      { q: 'British team that won the first constructors championship in 1958.', a: 'Vanwall' },
      { q: 'Cylinder layout used by the Ferrari 250 GTO and the Lamborghini Aventador.', a: 'V12' },
    ],
    W: [
      { q: 'Grove based team that has won nine constructors championships.', a: 'Williams' },
      { q: 'German engineer whose rotary engine design Mazda put into production.', a: 'Wankel' },
      { q: 'Distance between the centres of the front and rear axles.', a: 'Wheelbase' },
      { q: 'Aerofoil fitted to a race car to generate downforce.', a: 'Wing' },
      { q: 'New York circuit that hosted the United States Grand Prix from 1961 to 1980.', a: 'Watkins Glen' },
      { q: 'Series contested on gravel, tarmac and snow since 1973.', a: 'World Rally Championship', alt: ['WRC'] },
    ],
    X: [
      { q: 'Gas used in the bright bluish headlamp bulbs of the 1990s and 2000s.', a: 'Xenon' },
    ],
    Y: [
      { q: 'Japanese firm best known for motorcycles that also supplied Formula One engines in the 1990s.', a: 'Yamaha' },
      { q: 'Japanese tyre maker named after a large port city.', a: 'Yokohama' },
    ],
    Z: [
      { q: 'First Pagani road car, named after an Argentine wind.', a: 'Zonda' },
      { q: 'Belgian circuit where Gilles Villeneuve was killed in 1982.', a: 'Zolder' },
      { q: 'Dutch seaside circuit that returned to the grand prix calendar in 2021.', a: 'Zandvoort' },
    ],
  },
};
