import type { RawPack } from '../core/packs';

export const castlesPack: RawPack = {
  id: 'castles',
  name: 'Castles & Fortresses',
  description: 'Walls, keeps, sieges and the great strongholds of the world.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🏰',
  accent: '#78716c',
  letters: {
    A: [
      { q: 'The Spanish word for a Moorish royal fortress, as at Segovia and Seville.', a: 'Alcazar' },
      { q: 'The red Moorish palace and citadel that crowns the hill above Granada.', a: 'Alhambra' },
      { q: 'The narrow vertical slit in a wall through which a bowman could shoot.', a: 'Arrowslit' },
      { q: 'The West Sussex seat of the Dukes of Norfolk, rebuilt in Victorian Gothic.', a: 'Arundel' },
      { q: 'The Northumberland seat of the Percy family, used as Hogwarts on screen.', a: 'Alnwick' },
      { q: 'The Syrian citadel on a great mound, one of the oldest fortified sites in use.', a: 'Aleppo' },
      { q: 'Smooth squared masonry, cut and laid in even courses.', a: 'Ashlar' },
      { q: 'The Rajasthani hill fort above a lake near Jaipur, reached by a long ramp.', a: 'Amber' },
      { q: 'The dynasty of Henry II that raised great square towers across France and England.', a: 'Angevin' },
      { q: 'The Malaga fortification below the Gibralfaro, its name a Moorish diminutive.', a: 'Alcazaba' },
      { q: 'The crusader city of the Levant whose walls the Hospitallers held until 1291.', a: 'Acre' },
    ],
    B: [
      { q: 'The enclosed yard inside the walls of a Norman stronghold.', a: 'Bailey' },
      { q: 'The notched parapet along the top of a wall.', a: 'Battlement' },
      { q: 'The outer work built to shield a gateway.', a: 'Barbican' },
      { q: 'The pointed projecting angle of a star-shaped artillery defence.', a: 'Bastion' },
      { q: 'The Northumbrian coastal stronghold on a basalt crag above the North Sea.', a: 'Bamburgh' },
      { q: 'The unfinished concentric fortress of Edward I on Anglesey.', a: 'Beaumaris' },
      { q: 'The Irish stronghold near Cork whose stone visitors kiss for eloquence.', a: 'Blarney' },
      { q: 'The moated East Sussex showpiece of 1385, built against French raids.', a: 'Bodiam' },
      { q: 'The German word for a fortified hill residence, found in many place names.', a: 'Burg' },
      { q: 'The Roman engine that shot a heavy bolt by twisted sinew.', a: 'Ballista' },
      { q: 'The Hospitaller work above the Sea of Galilee, the first true concentric plan.', a: 'Belvoir' },
      { q: 'The Transylvanian stronghold marketed to tourists as the home of Dracula.', a: 'Bran' },
    ],
    C: [
      { q: 'The fortified heart of an ancient or medieval city.', a: 'Citadel' },
      { q: 'The gap between two solid blocks of a battlement, for shooting through.', a: 'Crenel' },
      { q: 'The main defensive wall running from tower to tower.', a: 'Curtain' },
      { q: 'The banded stone giant of Edward I on the Menai Strait, with polygonal towers.', a: 'Caernarfon' },
      { q: 'The Edwardian stronghold and complete town walls on a north Welsh estuary.', a: 'Conwy' },
      { q: 'The lakeside Swiss stronghold near Montreux that Byron made famous in verse.', a: 'Chillon' },
      { q: 'The stone bracket projecting from a wall to carry a beam or a turret.', a: 'Corbel' },
      { q: 'The huge Welsh work of the de Clares whose south tower leans badly.', a: 'Caerphilly' },
      { q: 'The Hospitaller stronghold in Syria that Lawrence called the finest in the world.', a: 'Crac des Chevaliers' },
      { q: 'The walled southern French town restored, controversially, by Viollet-le-Duc.', a: 'Carcassonne' },
      { q: 'The Saxon prisoner-of-war stronghold famous for escape attempts.', a: 'Colditz' },
      { q: 'The Monmouthshire keep of 1067, the oldest surviving stone fortification in Britain.', a: 'Chepstow' },
    ],
    D: [
      { q: 'The lifting span over a moat, hauled up by chains.', a: 'Drawbridge' },
      { q: 'The underground cell where prisoners were held.', a: 'Dungeon' },
      { q: 'The Norman French name for the great lord tower, root of that prison word.', a: 'Donjon' },
      { q: 'The Kentish coastal stronghold called the key of the kingdom.', a: 'Dover' },
      { q: 'The Skye seat of the MacLeods, held by one family for eight centuries.', a: 'Dunvegan' },
      { q: 'The Aberdeenshire ruin on a sea stack where the Scottish crown jewels were hidden.', a: 'Dunnottar' },
      { q: 'The Perthshire tower house of the Regent Albany, used in Monty Python and Outlander.', a: 'Doune' },
      { q: 'The clover-shaped Kentish gun fort of Henry VIII on the Channel shore.', a: 'Deal' },
      { q: 'The Snowdonian round tower of the Welsh princes above Llanberis.', a: 'Dolbadarn' },
      { q: 'The Croatian walled port whose ramparts stood in for a fictional capital on screen.', a: 'Dubrovnik' },
      { q: 'The Northumbrian coastal ruin between Craster and Embleton, held by John of Gaunt.', a: 'Dunstanburgh' },
    ],
    E: [
      { q: 'The splayed opening in a parapet cut for a cannon.', a: 'Embrasure' },
      { q: 'The complete ring of works enclosing a fortified place.', a: 'Enceinte' },
      { q: 'The much-photographed island stronghold where three Scottish lochs meet.', a: 'Eilean Donan' },
      { q: 'The Scottish rock fortress that looms over Princes Street.', a: 'Edinburgh' },
      { q: 'The steep inner slope of a ditch, facing the attacker.', a: 'Escarp' },
      { q: 'Storming a wall by ladders, without waiting for a breach.', a: 'Escalade' },
      { q: 'The German family stronghold on a Moselle crag, never taken and never sold.', a: 'Eltz' },
      { q: 'The English king whose iron ring of Welsh strongholds was built after 1277.', a: 'Edward the First' },
      { q: 'The Danish town of Kronborg, where Shakespeare set his Danish prince.', a: 'Elsinore' },
    ],
    F: [
      { q: 'A defended military post, smaller than a great stronghold.', a: 'Fort' },
      { q: 'The whole art and science of building defences.', a: 'Fortification' },
      { q: 'The French word for a defensive ditch, wet or dry.', a: 'Fosse' },
      { q: 'The Norman town whose rock keep was the birthplace of the Conqueror.', a: 'Falaise' },
      { q: 'The tower set at the angle of a wall so its shooters can rake the face.', a: 'Flanking tower' },
      { q: 'The arrowhead-shaped outwork of a star-plan defence.', a: 'Fleche' },
      { q: 'The Suffolk ruin of the Howards, ringed by thirteen mural towers and no keep.', a: 'Framlingham' },
      { q: 'The Breton stronghold of thirteen towers, among the largest in Europe.', a: 'Fougeres' },
      { q: 'The system by which land was held in return for military service.', a: 'Feudalism' },
      { q: 'The Ethiopian walled compound of the emperors at Gondar.', a: 'Fasil Ghebbi' },
    ],
    G: [
      { q: 'The main entrance through a defensive wall.', a: 'Gateway' },
      { q: 'The tower and lodging built over that entrance.', a: 'Gatehouse' },
      { q: 'The body of soldiers stationed to hold a place.', a: 'Garrison' },
      { q: 'The carved waterspout that throws rain clear of a wall.', a: 'Gargoyle' },
      { q: 'The tunnelled British rock at the mouth of the Mediterranean.', a: 'Gibraltar' },
      { q: 'The bare sloping ground kept clear in front of a defence.', a: 'Glacis' },
      { q: 'The moated stone seat of the counts in the middle of Ghent.', a: 'Gravensteen' },
      { q: 'The small room beside a gate where the watch was kept.', a: 'Guardroom' },
      { q: 'The splayed hole cut low in a wall for a cannon muzzle.', a: 'Gunport' },
      { q: 'The Indian fortress near Hyderabad whose gate carries a clap to the summit.', a: 'Golconda' },
      { q: 'The Herefordshire red sandstone ruin above the Wye, held for the king in 1646.', a: 'Goodrich' },
    ],
    H: [
      { q: 'The largest room of a stronghold, where the lord ate, judged and entertained.', a: 'Hall' },
      { q: 'The Edwardian stronghold on a Welsh crag that the sea once reached.', a: 'Harlech' },
      { q: 'The white heron stronghold of Japan, the finest to survive there.', a: 'Himeji' },
      { q: 'The vast Austrian fortress that broods over Mozart birthplace.', a: 'Hohensalzburg' },
      { q: 'The timber gallery built out over a parapet to cover the wall foot.', a: 'Hoarding' },
      { q: 'The order of knights who ran hospitals and held Rhodes and Malta.', a: 'Hospitallers' },
      { q: 'The brick East Sussex moated house of 1441, one of the earliest in that material.', a: 'Herstmonceux' },
      { q: 'The German university town whose ruined red palace overlooks the Neckar.', a: 'Heidelberg' },
      { q: 'The Sussex town where the Normans threw up their first motte in 1066.', a: 'Hastings' },
      { q: 'The Austrian rock fortress above Werfen, twin in look to the Salzburg one.', a: 'Hohenwerfen' },
    ],
    I: [
      { q: 'The Highland capital whose old stronghold guarded the Great Glen.', a: 'Inverness' },
      { q: 'The Kentish moated manor of Mote, remarkably little altered since 1340.', a: 'Ightham' },
      { q: 'The formal siege term for surrounding a place and cutting it off.', a: 'Investment' },
      { q: 'The word for a place that cannot be taken by force.', a: 'Impregnable' },
      { q: 'The earthwork enclosure on a British hilltop, the defence before stone was used.', a: 'Iron Age hillfort' },
      { q: 'The Edwardian ring of Welsh works is often called this kind of ring.', a: 'Iron' },
    ],
    J: [
      { q: 'The Japanese word for a fortified lord residence, as at Osaka and Nagoya.', a: 'Jo' },
      { q: 'The Channel Island whose Mont Orgueil rises above Gorey harbour.', a: 'Jersey' },
      { q: 'The elite Ottoman infantry who garrisoned the sultan strongholds.', a: 'Janissaries' },
      { q: 'The mounted contest of lances held in the tilting ground outside the walls.', a: 'Joust' },
    ],
    K: [
      { q: 'The strong central tower and last refuge of a Norman stronghold.', a: 'Keep' },
      { q: 'The Warwickshire ruin where Robert Dudley entertained Elizabeth I for weeks.', a: 'Kenilworth' },
      { q: 'The walled citadel at the heart of Moscow.', a: 'Kremlin' },
      { q: 'The armoured horseman who held land in return for service.', a: 'Knight' },
      { q: 'The Belgrade fortress where the Sava meets the Danube.', a: 'Kalemegdan' },
      { q: 'The Japanese stronghold of Kyushu, famous for its curving stone bases.', a: 'Kumamoto' },
      { q: 'The Danish Renaissance fortress at Helsingor, guarding the Sound.', a: 'Kronborg' },
      { q: 'The Irish stronghold of the Butlers above the Nore.', a: 'Kilkenny' },
      { q: 'The Arabic-rooted word crusaders used for a great fortified place, as in Syria.', a: 'Krak' },
    ],
    L: [
      { q: 'The narrow window slit, wider inside than out, for shooting through.', a: 'Loophole' },
      { q: 'The Kentish showpiece set on two islands in a lake, beloved of medieval queens.', a: 'Leeds' },
      { q: 'The Parisian fortress of Philip Augustus that became the world greatest museum.', a: 'Louvre' },
      { q: 'The fenced ground outside the walls where tournaments were fought.', a: 'Lists' },
      { q: 'The yew weapon that could pierce armour at two hundred paces.', a: 'Longbow' },
      { q: 'The Shropshire ruin with a round Norman chapel, seat of the Council of the Marches.', a: 'Ludlow' },
      { q: 'The French river valley whose chateaux replaced fortresses with pleasure palaces.', a: 'Loire' },
      { q: 'The English city whose Norman work faces its cathedral across the hill.', a: 'Lincoln' },
      { q: 'The Aragonese Romanesque stronghold on a rock in Huesca, used in Kingdom of Heaven.', a: 'Loarre' },
    ],
    M: [
      { q: 'The water-filled ditch that rings a wall.', a: 'Moat' },
      { q: 'The artificial earth mound on which an early Norman tower stood.', a: 'Motte' },
      { q: 'The solid upright block of a battlement, between the gaps.', a: 'Merlon' },
      { q: 'The Judaean cliff stronghold where the last rebels defied Rome in 73 AD.', a: 'Masada' },
      { q: 'The Rajput fortress whose walls rise sheer above the blue city of Jodhpur.', a: 'Mehrangarh' },
      { q: 'The projecting stone gallery with floor holes for dropping missiles.', a: 'Machicolation' },
      { q: 'The single-armed engine that flung a stone from a sling.', a: 'Mangonel' },
      { q: 'The tunnel driven under a wall to collapse it.', a: 'Mine' },
      { q: 'The Teutonic Knights brick giant on the Nogat, the largest of its kind on Earth.', a: 'Malbork' },
      { q: 'The abbey and fortified rock in Normandy, cut off by every high tide.', a: 'Mont Saint-Michel' },
      { q: 'The Rhineland hill stronghold at Braubach, never destroyed in eight centuries.', a: 'Marksburg' },
    ],
    N: [
      { q: 'The Bavarian fantasy palace of Ludwig II that inspired a theme park emblem.', a: 'Neuschwanstein' },
      { q: 'The Tyneside city named after the fortification William son of the Conqueror built.', a: 'Newcastle' },
      { q: 'The people from northern France who covered England with mottes after 1066.', a: 'Normans' },
      { q: 'The Midlands city whose rock and caves lie under a much-besieged fortification.', a: 'Nottingham' },
      { q: 'The Japanese city whose golden dolphins topped its great donjon.', a: 'Nagoya' },
      { q: 'The Kyoto stronghold of the Tokugawa with singing nightingale floors.', a: 'Nijo' },
      { q: 'The Muslim dynasty of Granada that built the red palace on the hill.', a: 'Nasrids' },
      { q: 'The Tweed-side English tower much battered by Scottish raids and by Turner brush.', a: 'Norham' },
    ],
    O: [
      { q: 'Any defensive work built beyond the main line of walls.', a: 'Outwork' },
      { q: 'The Japanese merchant city whose vast fortification Hideyoshi raised in the 1580s.', a: 'Osaka' },
      { q: 'The bottle-shaped pit into which a prisoner was dropped and forgotten.', a: 'Oubliette' },
      { q: 'The projecting upper window, carried on a corbel, of a late medieval hall.', a: 'Oriel' },
      { q: 'The military word for artillery and its stores.', a: 'Ordnance' },
      { q: 'The university city whose Norman mound and St George tower survive by the prison.', a: 'Oxford' },
      { q: 'The Slovak stronghold on a rock above a river, used in the 1922 film Nosferatu.', a: 'Orava' },
    ],
    P: [
      { q: 'The heavy iron grid dropped to seal a gateway.', a: 'Portcullis' },
      { q: 'The low wall at the outer edge of a wall walk.', a: 'Parapet' },
      { q: 'The fence of sharpened stakes set on an earth bank.', a: 'Palisade' },
      { q: 'The small back door through which a garrison could slip out.', a: 'Postern' },
      { q: 'The Czech complex above the Vltava, the largest fortified precinct in the world.', a: 'Prague Castle' },
      { q: 'The Welsh birthplace of Henry VII, with a great cylindrical Norman tower.', a: 'Pembroke' },
      { q: 'The small thick-walled Border tower of the Scottish and English reivers.', a: 'Peel tower' },
      { q: 'The Yorkshire stronghold where Richard II died, later slighted by Parliament.', a: 'Pontefract' },
      { q: 'The Slovenian stronghold built into the mouth of a cave.', a: 'Predjama' },
      { q: 'The French stronghold of the Duke of Orleans, rebuilt as a Gothic dream in the 1860s.', a: 'Pierrefonds' },
    ],
    Q: [
      { q: 'The lodgings of the soldiers within the walls.', a: 'Quarters' },
      { q: 'The dressed cornerstone that strengthens the angle of a wall.', a: 'Quoin' },
      { q: 'The four-sided court around which later fortified houses were planned.', a: 'Quadrangle' },
    ],
    R: [
      { q: 'The broad earth or stone bank with a walk along its top.', a: 'Rampart' },
      { q: 'The small enclosed work thrown up in haste, standing on its own.', a: 'Redoubt' },
      { q: 'The Medway stronghold whose tall square tower King John undermined in 1215.', a: 'Rochester' },
      { q: 'The Welsh stronghold of the Marcher lords at the mouth of the Clwyd.', a: 'Rhuddlan' },
      { q: 'The detached triangular outwork in front of a curtain, in a star plan.', a: 'Ravelin' },
      { q: 'The perfectly circular Cornish shell keep above the Fowey valley.', a: 'Restormel' },
      { q: 'The Monmouthshire late medieval showpiece with a hexagonal Yellow Tower.', a: 'Raglan' },
      { q: 'The Aegean island whose Street of the Knights and walls held out until 1522.', a: 'Rhodes' },
    ],
    S: [
      { q: 'The surrounding of a fortified place to force it to give in.', a: 'Siege' },
      { q: 'The private upper chamber of the lord and his family, beyond the hall.', a: 'Solar' },
      { q: 'The Scottish fortress on a volcanic crag above the Forth plain and Bannockburn.', a: 'Stirling' },
      { q: 'The narrow gate from which a garrison rushed out to attack the besiegers.', a: 'Sallyport' },
      { q: 'The round wall raised on top of an early earth mound, in place of a tower.', a: 'Shell keep' },
      { q: 'The Castilian city whose Alcazar looks like the prow of a ship.', a: 'Segovia' },
      { q: 'The Austrian city under the largest fully preserved fortress in central Europe.', a: 'Salzburg' },
      { q: 'The Slovak ruin that is one of the largest fortified sites in central Europe.', a: 'Spis' },
      { q: 'The Charleston harbour fort where the American Civil War began.', a: 'Sumter' },
      { q: 'The word for any strongly held place, whatever its shape.', a: 'Stronghold' },
      { q: 'The wooden tower on wheels rolled up so attackers could cross a wall.', a: 'Siege tower' },
    ],
    T: [
      { q: 'The tall narrow structure, round or square, that guards an angle of a wall.', a: 'Turret' },
      { q: 'The counterweight engine that slung great stones over a wall.', a: 'Trebuchet' },
      { q: 'The Roman shield formation named after a shelled creature.', a: 'Testudo' },
      { q: 'The crusading order of poor knights of the Temple, suppressed in 1312.', a: 'Templars' },
      { q: 'The Cornish headland ruin tied by legend to King Arthur.', a: 'Tintagel' },
      { q: 'The Ottoman sultans palace and fortified precinct above the Bosphorus.', a: 'Topkapi' },
      { q: 'The zigzag ditch a besieger dug forward so it could not be raked by fire.', a: 'Trench' },
      { q: 'The East Lothian red curtain wall on a cliff, battered by Cromwell guns.', a: 'Tantallon' },
      { q: 'The largest Norman work in Ireland, on the Boyne, used in Braveheart.', a: 'Trim' },
      { q: 'The Lithuanian island stronghold in a lake near Vilnius.', a: 'Trakai' },
      { q: 'The riverside stronghold of the English capital, begun in 1078 with a white keep.', a: 'Tower of London' },
    ],
    U: [
      { q: 'Digging beneath a wall so that it falls of its own weight.', a: 'Undermining' },
      { q: 'The ruin on the shore of the loch said to hold a monster.', a: 'Urquhart' },
      { q: 'The innermost and highest enclosure of a large fortification.', a: 'Upper ward' },
      { q: 'The Danube city of Germany whose 19th-century ring of forts was among the largest.', a: 'Ulm' },
      { q: 'The Swedish university city whose Vasa fortification looks down on the cathedral.', a: 'Uppsala' },
    ],
    V: [
      { q: 'The marshal who ringed the France of Louis XIV with star-shaped forts.', a: 'Vauban' },
      { q: 'The arched stone ceiling over a hall, chapel or cellar.', a: 'Vault' },
      { q: 'The tall 14th-century royal donjon east of Paris, later a state prison.', a: 'Vincennes' },
      { q: 'The Maltese capital, fortified by the Knights after the great siege of 1565.', a: 'Valletta' },
      { q: 'The Italian city whose Castelvecchio has swallowtail battlements on the Adige.', a: 'Verona' },
      { q: 'The Karelian stronghold founded by Sweden, now a Russian border town.', a: 'Vyborg' },
    ],
    W: [
      { q: 'The Berkshire royal residence, the oldest still inhabited in the world.', a: 'Windsor' },
      { q: 'The word for each defended enclosure of a fortification, inner or outer.', a: 'Ward' },
      { q: 'The Norman duke who took England in 1066 and began building at once.', a: 'William' },
      { q: 'The Coquet-side Northumbrian tower of the Percys, with a cross-shaped keep.', a: 'Warkworth' },
      { q: 'The Thuringian hill stronghold where Luther put the New Testament into German.', a: 'Wartburg' },
      { q: 'The Hampshire city whose great hall holds a famous painted round table.', a: 'Winchester' },
      { q: 'The lookout structure set on a wall or a hill to watch the country round.', a: 'Watchtower' },
      { q: 'The Avon-side Midlands seat of the Beauchamps, with Caesar and Guy towers.', a: 'Warwick' },
      { q: 'The Kraków hill of the Polish kings, with cathedral, palace and dragon cave.', a: 'Wawel' },
      { q: 'The upright barrier of stone or brick that is the basic element of any defence.', a: 'Wall' },
    ],
    X: [
      { q: 'The Chinese city whose Ming ramparts are the most complete surviving circuit.', a: 'Xian' },
      { q: 'The Valencian hill stronghold of two castles joined along a ridge.', a: 'Xativa' },
    ],
    Y: [
      { q: 'The English cathedral city whose Roman and medieval walls still ring the centre.', a: 'York' },
      { q: 'The tough springy wood from which the English war bow was cut.', a: 'Yew' },
      { q: 'The Japanese term for a stronghold built on a mountain, not on a plain.', a: 'Yamashiro' },
      { q: 'The fortress of seven towers in the Theodosian walls of Istanbul.', a: 'Yedikule' },
    ],
    Z: [
      { q: 'The German word for the killing ground between an outer and an inner wall.', a: 'Zwinger' },
      { q: 'The southern African mortarless stone enclosure that gave a modern nation its name.', a: 'Zimbabwe' },
      { q: 'The Polish word for a fortified lord residence, as at Kraków and Malbork.', a: 'Zamek' },
    ],
  },
};
