import type { RawPack } from '../core/packs';

export const chemistryPack: RawPack = {
  id: 'chemistry',
  name: 'Chemistry & Elements',
  description: 'The periodic table, reactions, lab kit and the chemists behind them.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🧪',
  accent: '#0891b2',
  letters: {
    A: [
      { q: 'This noble gas makes up just under one percent of the air by volume.', a: 'Argon' },
      { q: 'Bauxite is the chief ore of this light metal with symbol Al.', a: 'Aluminium' },
      { q: 'The constant 6.022 times ten to the 23rd is named after this Italian scientist.', a: 'Avogadro' },
      { q: 'Element 95, used in tiny amounts inside household smoke detectors.', a: 'Americium' },
      { q: 'The Haber process combines nitrogen and hydrogen to make this pungent gas, NH3.', a: 'Ammonia' },
      { q: 'Element 51 has the symbol Sb, from its Latin name stibium.', a: 'Antimony' },
      { q: 'Element 33, a notorious poison with the symbol As.', a: 'Arsenic' },
      { q: 'Element 85, a halogen so radioactive that only traces exist in nature.', a: 'Astatine' },
      { q: 'Element 89, symbol Ac, identified by Andre Debierne in 1899.', a: 'Actinium' },
      { q: 'The family name for saturated hydrocarbons such as methane and propane.', a: 'Alkane' },
      { q: 'Brass and bronze are both examples of this kind of metal mixture.', a: 'Alloy' },
      { q: 'In electrolysis this is the electrode where oxidation takes place.', a: 'Anode' },
      { q: 'The smallest unit of an element that keeps its chemical identity.', a: 'Atom' },
      { q: 'The simplest ketone, sold in shops as nail polish remover.', a: 'Acetone' },
      { q: 'Acetylsalicylic acid is sold under this much shorter name.', a: 'Aspirin' },
      { q: 'Group 1 of the periodic table is named for these reactive substances that form strong bases in water.', a: 'Alkali metals' },
    ],
    B: [
      { q: 'Element 5, symbol B, extracted from the mineral borax.', a: 'Boron' },
      { q: 'A patient swallows a meal containing this element\'s sulfate before an X-ray of the gut.', a: 'Barium' },
      { q: 'Element 4, a very light metal found in the gemstone emerald.', a: 'Beryllium' },
      { q: 'Element 83, whose oxide layers give lab-grown crystals rainbow colours.', a: 'Bismuth' },
      { q: 'The only nonmetal that is a liquid at room temperature.', a: 'Bromine' },
      { q: 'The standard gas flame source on a school lab bench, named after a German chemist.', a: 'Bunsen burner' },
      { q: 'A long graduated glass tube with a tap, used to deliver measured volumes in a titration.', a: 'Burette' },
      { q: 'The plain cylindrical lab glass with a lip for pouring.', a: 'Beaker' },
      { q: 'A mixture of a weak acid and its salt that resists changes in pH.', a: 'Buffer' },
      { q: 'The opposite of an acid on the pH scale.', a: 'Base' },
      { q: 'This Anglo-Irish scientist gave his name to the law linking gas pressure and volume.', a: 'Boyle' },
      { q: 'The SI unit of radioactivity is named after this French physicist.', a: 'Becquerel' },
      { q: 'A ring of six carbon atoms with the formula C6H6.', a: 'Benzene' },
      { q: 'The main aluminium ore, mined heavily in Australia and Guinea.', a: 'Bauxite' },
      { q: 'The four-carbon alkane burned in cigarette lighters, formula C4H10.', a: 'Butane' },
      { q: 'The everyday name for the hydrogen carbonate ion.', a: 'Bicarbonate' },
    ],
    C: [
      { q: 'Element 6, the backbone of every organic molecule.', a: 'Carbon' },
      { q: 'Element 20, the metal that makes up much of bone and limestone.', a: 'Calcium' },
      { q: 'Element 17, a green-yellow gas used to disinfect swimming pools.', a: 'Chlorine' },
      { q: 'Element 24, the metal that makes stainless steel shiny and rust-resistant.', a: 'Chromium' },
      { q: 'Element 27, whose compounds give glass a deep blue.', a: 'Cobalt' },
      { q: 'Element 29, symbol Cu, the metal used for household wiring.', a: 'Copper' },
      { q: 'Element 55, whose atomic transitions define the SI second.', a: 'Caesium' },
      { q: 'Marie and Pierre shared this surname and a 1903 Nobel Prize in Physics.', a: 'Curie' },
      { q: 'This English scientist identified hydrogen as a distinct substance in 1766.', a: 'Cavendish' },
      { q: 'A small heat-proof dish used to roast a solid at very high temperature.', a: 'Crucible' },
      { q: 'The water-jacketed glass tube that turns vapour back to liquid during distillation.', a: 'Condenser' },
      { q: 'A substance that speeds up a reaction without being used up by it.', a: 'Catalyst' },
      { q: 'The technique that separates a mixture as it travels through paper or a column.', a: 'Chromatography' },
      { q: 'The reaction of a fuel with oxygen that releases heat and light.', a: 'Combustion' },
      { q: 'The kind of chemical link formed when two atoms share a pair of electrons.', a: 'Covalent bond' },
      { q: 'A positively charged ion, drawn towards the negative electrode.', a: 'Cation' },
      { q: 'The temperature scale on which pure water freezes at zero degrees.', a: 'Celsius' },
      { q: 'The refinery process that breaks long hydrocarbon chains into shorter, more useful ones.', a: 'Cracking' },
    ],
    D: [
      { q: 'This English chemist published an early atomic theory in 1808.', a: 'Dalton' },
      { q: 'The English chemist who invented a miners\' safety lamp and isolated potassium in 1807.', a: 'Davy' },
      { q: 'The hardest natural form of carbon, used on drill tips.', a: 'Diamond' },
      { q: 'Separating liquids by boiling a mixture and then cooling the vapour.', a: 'Distillation' },
      { q: 'A sealed glass container holding a drying agent that keeps a sample free of moisture.', a: 'Desiccator' },
      { q: 'The spreading of a gas or solute from high to low concentration.', a: 'Diffusion' },
      { q: 'Element 66, a rare earth added to high-strength magnets.', a: 'Dysprosium' },
      { q: 'The hydrogen isotope whose nucleus holds one proton and one neutron.', a: 'Deuterium' },
      { q: 'To pour a liquid off a settled solid without disturbing it.', a: 'Decant' },
      { q: 'Mass divided by volume.', a: 'Density' },
      { q: 'Solid carbon dioxide, which sublimes at minus 78 degrees Celsius.', a: 'Dry ice' },
    ],
    E: [
      { q: 'The negatively charged particle that surrounds an atomic nucleus.', a: 'Electron' },
      { q: 'Passing a current through a molten or dissolved compound in order to split it.', a: 'Electrolysis' },
      { q: 'The alcohol in beer and wine, formula C2H5OH.', a: 'Ethanol' },
      { q: 'The two-carbon alkene polymerised to make polythene, formula C2H4.', a: 'Ethene' },
      { q: 'Describes a reaction that takes in heat from its surroundings.', a: 'Endothermic' },
      { q: 'Element 68, a rare earth whose ions amplify signals in fibre-optic cables.', a: 'Erbium' },
      { q: 'Element 63, a lanthanide used in the red phosphors of older colour televisions.', a: 'Europium' },
      { q: 'A mixture of tiny droplets of one liquid suspended in another, like milk.', a: 'Emulsion' },
      { q: 'A pure substance made of just one kind of atom.', a: 'Element' },
      { q: 'A protein that acts as a biological catalyst.', a: 'Enzyme' },
      { q: 'The change from liquid to gas at a surface, below boiling point.', a: 'Evaporation' },
    ],
    F: [
      { q: 'Element 9, the most reactive of the halogens.', a: 'Fluorine' },
      { q: 'Separating an insoluble solid from a liquid using paper in a funnel.', a: 'Filtration' },
      { q: 'This English scientist discovered electromagnetic induction and coined the word electrode.', a: 'Faraday' },
      { q: 'Element 100, named after an Italian-born physicist.', a: 'Fermium' },
      { q: 'The word describing iron in its plus-two oxidation state.', a: 'Ferrous' },
      { q: 'Element 87, the heaviest of the Group 1 metals.', a: 'Francium' },
      { q: 'The family of hollow carbon cages that includes the 60-atom buckyball.', a: 'Fullerene' },
      { q: 'The simplest aldehyde, long used to preserve biological specimens.', a: 'Formaldehyde' },
      { q: 'The cone-shaped piece of glassware that guides a liquid into a narrow neck.', a: 'Funnel' },
      { q: 'The formal name for melting, used in the phrase latent heat.', a: 'Fusion' },
    ],
    G: [
      { q: 'Element 79, symbol Au.', a: 'Gold' },
      { q: 'Element 31, a metal that melts in the warmth of a human hand.', a: 'Gallium' },
      { q: 'Element 32, the semiconductor used in the earliest transistors.', a: 'Germanium' },
      { q: 'The soft, slippery form of carbon used in pencil leads.', a: 'Graphite' },
      { q: 'A single one-atom-thick sheet of carbon in a honeycomb pattern.', a: 'Graphene' },
      { q: 'The six-carbon sugar with formula C6H12O6 that blood carries as fuel.', a: 'Glucose' },
      { q: 'Calcium sulfate dihydrate, the mineral roasted to make plaster of Paris.', a: 'Gypsum' },
      { q: 'The state of matter with neither fixed shape nor fixed volume.', a: 'Gas' },
      { q: 'The three-carbon alcohol with three hydroxyl groups, a by-product of soap making.', a: 'Glycerol' },
    ],
    H: [
      { q: 'Element 1, the lightest of them all.', a: 'Hydrogen' },
      { q: 'Element 2, the gas that makes party balloons float.', a: 'Helium' },
      { q: 'This German chemist won the 1918 Nobel Prize in Chemistry for synthesising ammonia.', a: 'Haber' },
      { q: 'The group name shared by fluorine, chlorine, bromine and iodine.', a: 'Halogen' },
      { q: 'Element 72, named after the Latin word for Copenhagen.', a: 'Hafnium' },
      { q: 'The OH minus ion found in alkaline solutions.', a: 'Hydroxide' },
      { q: 'The strong acid in the stomach, formula HCl.', a: 'Hydrochloric acid' },
      { q: 'A crystal that holds water inside its structure, like blue copper sulfate.', a: 'Hydrate' },
      { q: 'The six-carbon alkane used as a solvent to extract cooking oils.', a: 'Hexane' },
      { q: 'The time taken for half of a radioactive sample to decay.', a: 'Half-life' },
    ],
    I: [
      { q: 'Element 26, symbol Fe, the main ingredient of steel.', a: 'Iron' },
      { q: 'Element 53, a dark grey solid whose vapour is violet.', a: 'Iodine' },
      { q: 'Element 49, whose oxide with tin forms the clear conductor on touchscreens.', a: 'Indium' },
      { q: 'Element 77, a very dense metal enriched in the clay layer that marks the end of the Cretaceous.', a: 'Iridium' },
      { q: 'An atom or group of atoms carrying an electric charge.', a: 'Ion' },
      { q: 'Atoms of the same element with different numbers of neutrons.', a: 'Isotope' },
      { q: 'The link formed when one atom transfers an electron to another.', a: 'Ionic bond' },
      { q: 'One of two compounds with the same formula but a different arrangement of atoms.', a: 'Isomer' },
      { q: 'The old collective term for the noble gases, meaning unreactive.', a: 'Inert gas' },
    ],
    J: [
      { q: 'The SI unit of energy.', a: 'Joule' },
      { q: 'Irene and Frederic won the 1935 Nobel Prize in Chemistry for making new radioactive elements.', a: 'Joliot-Curie' },
      { q: 'An opaque red-brown variety of silica used as an ornamental stone.', a: 'Jasper' },
      { q: 'The tough green ornamental stone that is either nephrite or jadeite.', a: 'Jade' },
      { q: 'A black gemstone formed from fossilised wood, popular in Victorian mourning jewellery.', a: 'Jet' },
    ],
    K: [
      { q: 'Element 36, a noble gas used in some high-performance lighting.', a: 'Krypton' },
      { q: 'The SI base unit of temperature.', a: 'Kelvin' },
      { q: 'This German chemist described the ring structure of benzene in 1865.', a: 'Kekule' },
      { q: 'The class of carbonyl compounds with a carbon group on either side, such as propanone.', a: 'Ketone' },
      { q: 'The SI base unit of mass.', a: 'Kilogram' },
      { q: 'The soft white clay mineral used to make porcelain.', a: 'Kaolin' },
    ],
    L: [
      { q: 'Element 82, symbol Pb, once added to paint and petrol.', a: 'Lead' },
      { q: 'Element 3, the metal at the heart of rechargeable phone batteries.', a: 'Lithium' },
      { q: 'Element 57, which gives its name to the series of 15 rare earth metals.', a: 'Lanthanum' },
      { q: 'This French chemist named oxygen and was guillotined in 1794.', a: 'Lavoisier' },
      { q: 'The lichen-derived dye on paper that turns red in acid and blue in alkali.', a: 'Litmus' },
      { q: 'The clear solution that turns milky when carbon dioxide is bubbled through it.', a: 'Limewater' },
      { q: 'The state of matter with a fixed volume but no fixed shape.', a: 'Liquid' },
      { q: 'This French chemist gave his name to the principle about how equilibria shift.', a: 'Le Chatelier' },
      { q: 'The regular repeating three-dimensional arrangement of particles in a crystal.', a: 'Lattice' },
    ],
    M: [
      { q: 'Element 80, the only metal that is liquid at room temperature.', a: 'Mercury' },
      { q: 'Element 12, a metal that burns with a brilliant white flame.', a: 'Magnesium' },
      { q: 'Element 25, symbol Mn, whose purple permanganate is a strong oxidiser.', a: 'Manganese' },
      { q: 'Element 42, symbol Mo, added to steel for strength at high temperature.', a: 'Molybdenum' },
      { q: 'This Russian chemist published a periodic table in 1869 that predicted unknown elements.', a: 'Mendeleev' },
      { q: 'The simplest hydrocarbon, CH4, and the main component of natural gas.', a: 'Methane' },
      { q: 'The one-carbon alcohol, poisonous if drunk, formula CH3OH.', a: 'Methanol' },
      { q: 'The SI base unit for amount of substance.', a: 'Mole' },
      { q: 'The green copper carbonate mineral prized as an ornamental stone.', a: 'Malachite' },
      { q: 'Two or more substances together that are not chemically joined.', a: 'Mixture' },
      { q: 'The curved liquid surface you read at eye level in a measuring cylinder.', a: 'Meniscus' },
    ],
    N: [
      { q: 'Element 7, which makes up about 78 percent of the air.', a: 'Nitrogen' },
      { q: 'Element 10, the noble gas that glows orange-red in a discharge tube.', a: 'Neon' },
      { q: 'Element 28, symbol Ni, alloyed with chromium in stainless steel.', a: 'Nickel' },
      { q: 'Element 41, symbol Nb, used in superconducting magnet wire.', a: 'Niobium' },
      { q: 'Element 60, the rare earth in the strongest permanent magnets.', a: 'Neodymium' },
      { q: 'Element 93, named after the planet beyond Uranus.', a: 'Neptunium' },
      { q: 'Element 102, named after the founder of the famous prizes.', a: 'Nobelium' },
      { q: 'The uncharged particle found in an atomic nucleus.', a: 'Neutron' },
      { q: 'The dense central part of an atom, holding its protons.', a: 'Nucleus' },
      { q: 'The strong acid with formula HNO3, used to make fertilisers and explosives.', a: 'Nitric acid' },
      { q: 'The white solid with two fused benzene rings, once used in mothballs.', a: 'Naphthalene' },
    ],
    O: [
      { q: 'Element 8, which makes up about 21 percent of the air.', a: 'Oxygen' },
      { q: 'Element 76, the densest of the naturally occurring metals.', a: 'Osmium' },
      { q: 'Water moving through a partly permeable membrane from dilute to concentrated.', a: 'Osmosis' },
      { q: 'The loss of electrons by a substance during a reaction.', a: 'Oxidation' },
      { q: 'The three-atom form of oxygen that shields Earth from ultraviolet.', a: 'Ozone' },
      { q: 'The branch of the subject that studies carbon compounds.', a: 'Organic chemistry' },
      { q: 'The region around a nucleus where an electron is likely to be found.', a: 'Orbital' },
    ],
    P: [
      { q: 'Element 15, whose white form glows in air and catches fire easily.', a: 'Phosphorus' },
      { q: 'Element 19, symbol K, which fizzes and burns when dropped on water.', a: 'Potassium' },
      { q: 'Element 78, the precious metal used in catalytic converters.', a: 'Platinum' },
      { q: 'Element 46, symbol Pd, a precious metal that soaks up large volumes of hydrogen.', a: 'Palladium' },
      { q: 'Element 94, used in the core of some nuclear weapons.', a: 'Plutonium' },
      { q: 'Element 84, found in 1898 and named after Marie Curie\'s homeland.', a: 'Polonium' },
      { q: 'Element 59, a lanthanide whose salts are green.', a: 'Praseodymium' },
      { q: 'The positively charged particle in a nucleus.', a: 'Proton' },
      { q: 'The slender glass tube used to transfer an exact volume of liquid.', a: 'Pipette' },
      { q: 'This French scientist gave his name to the gentle heating that makes milk safe.', a: 'Pasteur' },
      { q: 'This American chemist won the 1954 Nobel Prize in Chemistry for work on the chemical bond.', a: 'Pauling' },
      { q: 'The insoluble solid that appears when two clear solutions are mixed.', a: 'Precipitate' },
      { q: 'A long molecule built by joining many small repeating units.', a: 'Polymer' },
      { q: 'The chart that arranges the elements by atomic number into rows and groups.', a: 'Periodic table' },
      { q: 'The plastic made by joining many ethene molecules, used for carrier bags.', a: 'Polythene' },
      { q: 'The brassy iron sulfide mineral nicknamed fool\'s gold.', a: 'Pyrite' },
    ],
    Q: [
      { q: 'Silicon dioxide crystal, the main mineral in most sand.', a: 'Quartz' },
      { q: 'The common name for calcium oxide, made by roasting limestone.', a: 'Quicklime' },
      { q: 'The word for the smallest discrete packet of energy.', a: 'Quantum' },
      { q: 'The old name for the liquid metal with symbol Hg.', a: 'Quicksilver' },
      { q: 'Cooling hot metal rapidly in water or oil to harden it.', a: 'Quenching' },
    ],
    R: [
      { q: 'Element 88, isolated by Marie and Pierre Curie in 1898.', a: 'Radium' },
      { q: 'Element 86, a radioactive noble gas that seeps from granite into basements.', a: 'Radon' },
      { q: 'Element 37, symbol Rb, a soft Group 1 metal that ignites in air.', a: 'Rubidium' },
      { q: 'Element 45, a precious metal used to plate white gold jewellery.', a: 'Rhodium' },
      { q: 'This New Zealand-born scientist won the 1908 Nobel Prize in Chemistry for work on radioactive decay.', a: 'Rutherford' },
      { q: 'The gain of electrons by a substance during a reaction.', a: 'Reduction' },
      { q: 'Boiling a mixture under a vertical condenser so that nothing escapes.', a: 'Reflux' },
      { q: 'The flaky red-brown hydrated iron oxide that forms in damp air.', a: 'Rust' },
      { q: 'Element 44, symbol Ru, one of the platinum group metals.', a: 'Ruthenium' },
    ],
    S: [
      { q: 'Element 16, the yellow solid that burns with a blue flame.', a: 'Sulfur' },
      { q: 'Element 11, symbol Na, whose chloride is table salt.', a: 'Sodium' },
      { q: 'Element 14, the semiconductor at the heart of computer chips.', a: 'Silicon' },
      { q: 'Element 47, symbol Ag, the best electrical conductor of all the metals.', a: 'Silver' },
      { q: 'Element 38, whose salts colour fireworks bright red.', a: 'Strontium' },
      { q: 'Element 21, symbol Sc, a light metal added to some aluminium alloys.', a: 'Scandium' },
      { q: 'Element 34, once used in photocopier drums for its light-sensitive conductivity.', a: 'Selenium' },
      { q: 'Element 106, named after an American nuclear chemist.', a: 'Seaborgium' },
      { q: 'The change straight from solid to gas without melting on the way.', a: 'Sublimation' },
      { q: 'The liquid in which a solute dissolves.', a: 'Solvent' },
      { q: 'The substance that dissolves in a liquid to form a solution.', a: 'Solute' },
      { q: 'Describes a mixture holding as much dissolved solid as it can at that temperature.', a: 'Saturated solution' },
      { q: 'The alloy of iron and carbon used for girders and cutlery.', a: 'Steel' },
      { q: 'The general name for the ionic product of an acid and a base.', a: 'Salt' },
      { q: 'The dense oily strong acid with formula H2SO4.', a: 'Sulfuric acid' },
      { q: 'Studying how a substance absorbs or emits light in order to identify it.', a: 'Spectroscopy' },
      { q: 'Describes a substance that dissolves readily in water.', a: 'Soluble' },
      { q: 'The arithmetic of reacting amounts in a balanced equation.', a: 'Stoichiometry' },
    ],
    T: [
      { q: 'Element 22, a strong light metal used in aircraft and hip implants.', a: 'Titanium' },
      { q: 'Element 50, symbol Sn, mixed with copper to make bronze.', a: 'Tin' },
      { q: 'Element 74, symbol W, long used for light bulb filaments.', a: 'Tungsten' },
      { q: 'Element 73, symbol Ta, used in the capacitors inside phones.', a: 'Tantalum' },
      { q: 'Element 90, a radioactive metal named after a Norse god.', a: 'Thorium' },
      { q: 'Element 43, whose metastable isotope is injected for medical scans.', a: 'Technetium' },
      { q: 'Adding measured acid to alkali until an indicator changes colour.', a: 'Titration' },
      { q: 'The three-legged metal stand that supports a gauze above a burner.', a: 'Tripod' },
      { q: 'The mixture of aluminium powder and iron oxide that burns hot enough to weld rails.', a: 'Thermite' },
      { q: 'Element 52, symbol Te, a brittle metalloid named after the Earth.', a: 'Tellurium' },
      { q: 'Element 65, a rare earth used in green phosphors.', a: 'Terbium' },
      { q: 'Element 81, symbol Tl, a very toxic soft metal.', a: 'Thallium' },
      { q: 'The instrument that measures how hot something is.', a: 'Thermometer' },
    ],
    U: [
      { q: 'Element 92, whose 235 isotope fuels nuclear reactors.', a: 'Uranium' },
      { q: 'The nitrogen compound in urine, made from an inorganic salt by Wohler in 1828.', a: 'Urea' },
      { q: 'This American chemist won the 1934 Nobel Prize in Chemistry for discovering deuterium.', a: 'Urey' },
      { q: 'The mixed dye that shows the whole pH range as a spread of colours.', a: 'Universal indicator' },
      { q: 'Describes a hydrocarbon that contains a double or triple carbon link.', a: 'Unsaturated' },
    ],
    V: [
      { q: 'Element 23, symbol V, added to steel for tool strength.', a: 'Vanadium' },
      { q: 'The SI unit of electrical potential difference.', a: 'Volt' },
      { q: 'The number of chemical links an atom can form.', a: 'Valency' },
      { q: 'A liquid\'s resistance to flowing.', a: 'Viscosity' },
      { q: 'The gaseous form of a substance below its boiling point.', a: 'Vapour' },
      { q: 'Heating rubber with sulfur to make it harder and more elastic.', a: 'Vulcanisation' },
      { q: 'The weak attractions between molecules, named after a Dutch physicist.', a: 'Van der Waals' },
    ],
    W: [
      { q: 'The compound with formula H2O.', a: 'Water' },
      { q: 'This German chemist made urea from an inorganic salt in 1828.', a: 'Wohler' },
      { q: 'The SI unit of power.', a: 'Watt' },
      { q: 'The solid burned in candles, a mixture of long hydrocarbons.', a: 'Wax' },
      { q: 'The alternative name for element 74 that explains its symbol W.', a: 'Wolfram' },
      { q: 'The square metal mesh laid on a tripod to spread a flame.', a: 'Wire gauze' },
    ],
    X: [
      { q: 'Element 54, a noble gas used in bright car headlamps and camera flashes.', a: 'Xenon' },
      { q: 'The aromatic solvent that is a benzene ring carrying two methyl groups.', a: 'Xylene' },
      { q: 'The technique that reveals atomic structure by diffracting short-wavelength radiation from a crystal.', a: 'X-ray crystallography' },
      { q: 'The sugar alcohol used to sweeten sugar-free chewing gum.', a: 'Xylitol' },
      { q: 'The class of yellow leaf pigments related to carotene.', a: 'Xanthophyll' },
    ],
    Y: [
      { q: 'Element 39, symbol Y, used in red television phosphors and in superconductors.', a: 'Yttrium' },
      { q: 'Element 70, a rare earth named after the Swedish village of Ytterby.', a: 'Ytterbium' },
      { q: 'The organism whose enzymes turn sugar into alcohol during fermentation.', a: 'Yeast' },
      { q: 'The amount of product actually obtained from a reaction, often quoted as a percentage.', a: 'Yield' },
      { q: 'The concentrated uranium oxide powder produced at a mine.', a: 'Yellowcake' },
    ],
    Z: [
      { q: 'Element 30, the metal that coats galvanised steel.', a: 'Zinc' },
      { q: 'Element 40, whose cubic oxide is sold as a diamond substitute.', a: 'Zirconium' },
      { q: 'The porous aluminosilicate mineral used as a molecular sieve and water softener.', a: 'Zeolite' },
      { q: 'An amino acid form that carries a positive and a negative charge at the same time.', a: 'Zwitterion' },
    ],
  },
};
