import type { RawPack } from '../core/packs';

export const chessPack: RawPack = {
  id: 'chess',
  name: 'Chess',
  description: 'Pieces, tactics, openings, endings and the champions who defined them.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '♟️',
  accent: '#57534e',
  letters: {
    A: [
      { q: 'The Russian-French world champion who held the title from 1927 until his death in 1946.', a: 'Alekhine' },
      { q: 'The Indian who won the world title in 2007 and is called the Tiger of Madras.', a: 'Anand' },
      { q: 'The old practice of sealing a secret continuation and finishing a long game next day.', a: 'Adjournment' },
      { q: 'The modern system in which each square is named by a file letter and a rank number.', a: 'Algebraic notation' },
      { q: 'The tie-break game in which White has more clock but only a win will do.', a: 'Armageddon' },
      { q: 'The knight-and-rook finish that traps a king on the edge, named after a German novel.', a: 'Anastasia mate' },
      { q: 'A move or plan that threatens to win something by force.', a: 'Attack' },
      { q: 'The Armenian grandmaster, born 1982, who won the World Cup in 2005 and 2017.', a: 'Aronian' },
      { q: 'The word for the edge one side holds in material or in position.', a: 'Advantage' },
      { q: 'Study of a finished game to find where it went right and wrong.', a: 'Analysis' },
    ],
    B: [
      { q: 'The piece that travels only along diagonals.', a: 'Bishop' },
      { q: 'The fast control of roughly three to five minutes a side.', a: 'Blitz' },
      { q: 'A terrible slip that throws away a winning game.', a: 'Blunder' },
      { q: 'The Soviet Patriarch who won the 1948 title match-tournament and coached a generation.', a: 'Botvinnik' },
      { q: 'The four-player variant on two sets where captured men are handed to a partner.', a: 'Bughouse' },
      { q: 'The very fastest online control, one minute or less a side.', a: 'Bullet' },
      { q: 'Two heavy pieces stacked on the same file so their force is combined.', a: 'Battery' },
      { q: 'The rock-solid reply 3...Nf6 to the Spanish, a wall at elite level.', a: 'Berlin' },
      { q: 'The free point a competitor receives when there is nobody to pair them with.', a: 'Bye' },
      { q: 'The sixty-four squares themselves, eight by eight, light and dark.', a: 'Board' },
      { q: 'The Soviet who drew the 1951 title match and so failed to take the crown.', a: 'Bronstein' },
    ],
    C: [
      { q: 'The only move that shifts two of your own men at the same time.', a: 'Castling' },
      { q: 'The state of a king under direct attack, which must be answered at once.', a: 'Check' },
      { q: 'The attack on a king that cannot be met, ending the game there and then.', a: 'Checkmate' },
      { q: 'Taking an enemy man and removing it from play.', a: 'Capture' },
      { q: 'The Norwegian who won the title in 2013 and reached a rating of 2882.', a: 'Carlsen' },
      { q: 'The Cuban champion of 1921 to 1927, famed for flawless endgame technique.', a: 'Capablanca' },
      { q: 'A forcing sequence, usually starting with a sacrifice, that wins by calculation.', a: 'Combination' },
      { q: 'The eight-player event that decides who challenges for the world title.', a: 'Candidates' },
      { q: 'The four middle squares that both sides fight to command.', a: 'Centre' },
      { q: 'The two-faced device that limits how long each side may think.', a: 'Clock' },
      { q: 'The prize-money contest where two players meet over many games for the title.', a: 'Championship' },
      { q: 'The Fischer variant in which the back row is shuffled at random before play.', a: 'Chess960' },
    ],
    D: [
      { q: 'The result in which the point is shared.', a: 'Draw' },
      { q: 'The system Black chooses in reply to the opening move.', a: 'Defence' },
      { q: 'Bringing your men off their starting squares into useful play.', a: 'Development' },
      { q: 'The tactic that lures a guard away from the square it has to watch.', a: 'Deflection' },
      { q: 'The fiery Sicilian line in which Black puts the bishop on g7 and races.', a: 'Dragon' },
      { q: 'Two of your own foot soldiers stuck one behind the other on a single file.', a: 'Doubled pawns' },
      { q: 'Moving one man aside so that the piece behind it strikes.', a: 'Discovery' },
      { q: 'A doomed piece that grabs whatever it can before it is taken.', a: 'Desperado' },
      { q: 'Luring an enemy man onto a square where a tactic hits it.', a: 'Decoy' },
      { q: 'The IBM machine that beat Kasparov in a match in 1997.', a: 'Deep Blue' },
    ],
    E: [
      { q: 'The special capture of a foot soldier that has just leapt two squares.', a: 'En passant' },
      { q: 'The last phase, with few men left and the king turning into a fighter.', a: 'Endgame' },
      { q: 'A trade of men of roughly equal worth.', a: 'Exchange' },
      { q: 'The French term for a piece left hanging and free for the taking.', a: 'En prise' },
      { q: 'The rating system named after a Hungarian-American physics professor.', a: 'Elo' },
      { q: 'The Dutch schoolmaster who held the world title from 1935 to 1937.', a: 'Euwe' },
      { q: 'The 19th-century line in which White offers a b-file soldier straight after Bc4.', a: 'Evans Gambit' },
      { q: 'The finish where a king is boxed in by its own two rooks, one on either side.', a: 'Epaulette mate' },
      { q: 'The computer program that calculates lines and gives a numeric assessment.', a: 'Engine' },
      { q: 'The Kalmyk capital that hosted the 2006 reunification match.', a: 'Elista' },
    ],
    F: [
      { q: 'The American who beat Spassky in Reykjavik in 1972.', a: 'Fischer' },
      { q: 'One man attacking two enemy units at once.', a: 'Fork' },
      { q: 'Putting a bishop on the long diagonal behind an advanced flank soldier.', a: 'Fianchetto' },
      { q: 'A vertical line of eight squares, lettered a to h.', a: 'File' },
      { q: 'The world governing body founded in Paris in 1924.', a: 'FIDE' },
      { q: 'Winning because the opponent has run the clock down to zero.', a: 'Flagging' },
      { q: 'The defence that answers 1.e4 with e6.', a: 'French' },
      { q: 'A continuation that is the only legal or only sensible reply.', a: 'Forced' },
      { q: 'The number of moves without a capture or a push that lets a draw be claimed.', a: 'Fifty' },
      { q: 'The starting arrangement of the men, or any legal set-up of them.', a: 'Formation' },
    ],
    G: [
      { q: 'A deliberate offer of material in return for speed and activity.', a: 'Gambit' },
      { q: 'The highest title the world body awards, and one held for life.', a: 'Grandmaster' },
      { q: 'The defence that lets White build a broad centre, then shoots at it from g7.', a: 'Grunfeld' },
      { q: 'The Indian teenager who became the youngest ever world champion in 2024.', a: 'Gukesh' },
      { q: 'The Italian opening whose name translates as "the quiet game".', a: 'Giuoco Piano' },
      { q: 'The classic bishop sacrifice on h7 against a castled king, named for a wooden horse.', a: 'Greek gift' },
      { q: 'The eccentric first move 1.g4, named after a Swiss master.', a: 'Grob' },
      { q: 'One complete contest, from the first move to the result.', a: 'Game' },
      { q: 'The Yugoslav grandmaster who was for decades the strongest player his country produced.', a: 'Gligoric' },
      { q: 'The 17th-century Italian whose recorded brilliancies formed the first great collection.', a: 'Greco' },
    ],
    H: [
      { q: 'Left undefended and free to be taken.', a: 'Hanging' },
      { q: 'The 1920s school of Reti and Nimzowitsch that struck at the centre from a distance.', a: 'Hypermodern' },
      { q: 'The engine flaw of not seeing just past the end of its own search.', a: 'Horizon effect' },
      { q: 'The cramped but springy set-up where Black keeps his men on the sixth rank.', a: 'Hedgehog' },
      { q: 'A file on which only one of the two sides still has a foot soldier.', a: 'Half-open' },
      { q: 'The English seaside town of the great 1895 tournament and a New Year congress ever since.', a: 'Hastings' },
      { q: 'Giving material or extra turns to a weaker opponent, as in the old odds games.', a: 'Handicap' },
      { q: 'The Chinese woman who became world champion at sixteen, surname Hou.', a: 'Hou Yifan' },
    ],
    I: [
      { q: 'Holding the power to make the threats and dictate the play.', a: 'Initiative' },
      { q: 'A move the rules do not permit, which must be retracted.', a: 'Illegal' },
      { q: 'A foot soldier with no friendly one on either neighbouring file.', a: 'Isolated pawn' },
      { q: 'Cutting the line between a guard and what it guards by dropping a man in the way.', a: 'Interference' },
      { q: 'The old opening 1.e4 e5 2.Nf3 Nc6 3.Bc4, named after a country.', a: 'Italian' },
      { q: 'The few seconds added to a clock after every turn.', a: 'Increment' },
      { q: 'The qualifying stage above the zonal in the old world-title cycle.', a: 'Interzonal' },
      { q: 'The title one rank below grandmaster.', a: 'International Master' },
    ],
    J: [
      { q: 'The Hungarian, strongest woman ever, who beat a string of world champions including Kasparov.', a: 'Judit Polgar' },
      { q: 'The engine, sold as Deep this, that drew a match with Kasparov in 2003.', a: 'Junior' },
      { q: 'The wild 19th-century American line that throws two pieces at f7.', a: 'Jerome Gambit' },
      { q: 'The Russian theorist whose gambit 3...f5 answers the Spanish.', a: 'Jaenisch' },
      { q: 'The Georgian grandmaster whose d4, Nc3 and Bf4 system carries his name.', a: 'Jobava' },
    ],
    K: [
      { q: 'The man that may never be taken.', a: 'King' },
      { q: 'The only piece that jumps, moving in the shape of an L.', a: 'Knight' },
      { q: 'The Baku-born champion who lost to a computer in 1997.', a: 'Kasparov' },
      { q: 'The Soviet champion of 1975 to 1985, whose title matches with his rival ran to five.', a: 'Karpov' },
      { q: 'The Russian who took the crown from Kasparov in London in 2000.', a: 'Kramnik' },
      { q: 'The half of the board on files e to h, where the royal pair begins.', a: 'Kingside' },
      { q: 'The spectator who cannot resist commenting on a game in progress.', a: 'Kibitzer' },
      { q: 'The Estonian who was a candidate five times but never played a title match.', a: 'Keres' },
      { q: 'The Russian who took Carlsen to tie-breaks in the 2016 title match.', a: 'Karjakin' },
    ],
    L: [
      { q: 'The German who held the world title for twenty-seven years, longer than anyone.', a: 'Lasker' },
      { q: 'The German word for the escape square a king makes for itself.', a: 'Luft' },
      { q: 'The solid system in which White plays d4 and puts the dark bishop on f4.', a: 'London System' },
      { q: 'The winning rook-and-pawn method that builds a bridge for the king.', a: 'Lucena' },
      { q: 'A soldier pushed forward to attack an enemy chain and prise it open.', a: 'Lever' },
      { q: 'A sequence of moves given in an opening book or in analysis.', a: 'Line' },
      { q: 'The free browser-based site, run as a charity, that rivals the big commercial one.', a: 'Lichess' },
      { q: 'The English city that hosted the 2000 and 2018 world title matches.', a: 'London' },
    ],
    M: [
      { q: 'The finish that ends the game outright.', a: 'Mate' },
      { q: 'The total worth of the men a side still has.', a: 'Material' },
      { q: 'The phase after the opening, where plans and tactics collide.', a: 'Middlegame' },
      { q: 'The New Orleans genius who swept Europe in 1858, then gave up the game.', a: 'Morphy' },
      { q: 'The collective word for bishops and knights.', a: 'Minor pieces' },
      { q: 'How many squares your men can reach, a key term in engine evaluation.', a: 'Mobility' },
      { q: 'The American who gave his name to a fierce counter-gambit in the Spanish.', a: 'Marshall' },
      { q: 'A game won inside twenty-five moves.', a: 'Miniature' },
      { q: 'The squeeze with soldiers on c4 and e4 against the Sicilian, named for a Hungarian.', a: 'Maroczy bind' },
      { q: 'One turn by one side, written as a number with two halves.', a: 'Move' },
    ],
    N: [
      { q: 'The author of "My System", who taught the world about blockade and overprotection.', a: 'Nimzowitsch' },
      { q: 'The American five-time national champion and streaming star, born 1987.', a: 'Nakamura' },
      { q: 'The written record of a game, move by move.', a: 'Notation' },
      { q: 'The first fresh idea played in a well-known theoretical line.', a: 'Novelty' },
      { q: 'The tournament result a player needs three of to earn the top title.', a: 'Norm' },
      { q: 'The Sicilian line with a6 on the fifth turn, named for a Polish-Argentine master.', a: 'Najdorf' },
      { q: 'The defence 1.d4 Nf6 2.c4 e6 3.Nc3 Bb4.', a: 'Nimzo-Indian' },
      { q: 'The English grandmaster and mathematician who wrote widely on endings.', a: 'Nunn' },
    ],
    O: [
      { q: 'The first phase of a game, where theory runs deepest.', a: 'Opening' },
      { q: 'The king-against-king standoff that decides a great many pawn endings.', a: 'Opposition' },
      { q: 'A square deep in enemy ground where a knight can sit safe from foot soldiers.', a: 'Outpost' },
      { q: 'A column with no foot soldiers of either colour left on it.', a: 'Open file' },
      { q: 'The Nimzowitsch idea of guarding a strong point more times than strictly needed.', a: 'Overprotection' },
      { q: 'The biennial team event where nations field four boards.', a: 'Olympiad' },
      { q: 'The nickname Kasparov gave a knight on d3 that seemed to touch everything.', a: 'Octopus' },
      { q: 'The stored list of theoretical lines an engine plays straight from memory.', a: 'Opening book' },
      { q: 'Asking one defender to guard two things at once, then punishing it.', a: 'Overloading' },
    ],
    P: [
      { q: 'The foot soldier, counted as one point.', a: 'Pawn' },
      { q: 'What happens when a foot soldier reaches the far rank.', a: 'Promotion' },
      { q: 'Freezing a man because shifting it would expose something worse behind.', a: 'Pin' },
      { q: 'A foot soldier with no enemy one left to stop it reaching the end.', a: 'Passed pawn' },
      { q: 'The endless series of checks that rescues a lost game by repetition.', a: 'Perpetual' },
      { q: 'The Armenian Iron Tigran, champion from 1963 to 1969.', a: 'Petrosian' },
      { q: 'Playing a quiet move purely to stop what the opponent wants to do.', a: 'Prophylaxis' },
      { q: 'The arrangement of all the men at a given moment.', a: 'Position' },
      { q: 'The 18th-century Frenchman who called the foot soldiers the soul of the game.', a: 'Philidor' },
      { q: 'A set problem you are asked to solve, often "mate in two".', a: 'Puzzle' },
      { q: 'The defence 1.e4 d6 2.d4 Nf6, named after a Slovenian master.', a: 'Pirc' },
    ],
    Q: [
      { q: 'The strongest piece, sweeping any distance in any direction.', a: 'Queen' },
      { q: 'The half of the board on files a to d.', a: 'Queenside' },
      { q: 'The old opening 1.d4 d5 2.c4, and the title of a Netflix hit.', a: 'Queens Gambit' },
      { q: 'A subtle non-forcing continuation inside a combination that is nonetheless deadly.', a: 'Quiet move' },
      { q: 'The four-player all-play-all group used in American weekend events.', a: 'Quads' },
    ],
    R: [
      { q: 'The piece that runs in straight lines and counts as five.', a: 'Rook' },
      { q: 'The number that measures how strong a player is.', a: 'Rating' },
      { q: 'Reaching the identical position three times, which allows a draw claim.', a: 'Repetition' },
      { q: 'To give up rather than be mated.', a: 'Resign' },
      { q: 'A horizontal row of eight squares, numbered one to eight.', a: 'Rank' },
      { q: 'The Spanish opening named after a 16th-century priest.', a: 'Ruy Lopez' },
      { q: 'The Czech hypermodern who wrote "Modern Ideas in Chess".', a: 'Reti' },
      { q: 'The format in which every entrant plays every other.', a: 'Round robin' },
      { q: 'The 19th-century era of wild sacrifices, before technique took charge.', a: 'Romantic' },
    ],
    S: [
      { q: 'The draw that comes when a side has no legal move yet is not in check.', a: 'Stalemate' },
      { q: 'Giving up material on purpose in return for an attack.', a: 'Sacrifice' },
      { q: 'The Soviet champion who lost the 1972 match in Iceland.', a: 'Spassky' },
      { q: 'The sharpest answer to 1.e4, played with c5.', a: 'Sicilian' },
      { q: 'The knight finish in which a king is hemmed in entirely by its own men.', a: 'Smothered mate' },
      { q: 'One of the sixty-four units of the board.', a: 'Square' },
      { q: 'The first official world champion, crowned in 1886.', a: 'Steinitz' },
      { q: 'The pairing system that matches equal scores without knocking anyone out.', a: 'Swiss' },
      { q: 'The reverse of a pin, hitting the valuable man in front so the lesser one falls.', a: 'Skewer' },
      { q: 'The amount of ground a side controls.', a: 'Space' },
      { q: 'The display in which one master takes on dozens of opponents at the same time.', a: 'Simul' },
    ],
    T: [
      { q: 'The Latvian Magician from Riga, champion in 1960, famous for wild sacrifices.', a: 'Tal' },
      { q: 'One unit of speed in the opening, gained or lost with each turn.', a: 'Tempo' },
      { q: 'Short forcing sequences such as forks, pins and skewers.', a: 'Tactics' },
      { q: 'The rule that sets how long each side has, such as 90 minutes plus 30 seconds.', a: 'Time control' },
      { q: 'The rule that if you handle a man you must play it.', a: 'Touch-move' },
      { q: 'The three-square king manoeuvre that hands the turn back to the opponent.', a: 'Triangulation' },
      { q: 'A tempting but poisoned continuation set for the opponent to fall into.', a: 'Trap' },
      { q: 'Reaching a known opening through a different order of turns.', a: 'Transposition' },
      { q: 'A move that promises damage next turn unless it is answered.', a: 'Threat' },
      { q: 'The Bulgarian who was world number one in 2006 and played the 2010 title match.', a: 'Topalov' },
      { q: 'The German doctor and dogmatist who preached open lines for the pieces.', a: 'Tarrasch' },
    ],
    U: [
      { q: 'Choosing a knight or a rook instead of the strongest piece at the far rank.', a: 'Underpromotion' },
      { q: 'Removing the man that props up the enemy defence.', a: 'Undermining' },
      { q: 'Freeing a frozen piece by shifting the valuable one behind it.', a: 'Unpin' },
      { q: 'The fifteen-second control offered on the free charity site.', a: 'UltraBullet' },
      { q: 'The federation that rates tournament play in America.', a: 'USCF' },
    ],
    V: [
      { q: 'A branch of moves considered instead of the main continuation.', a: 'Variation' },
      { q: 'The opening 1.e4 e5 2.Nc3, named after a European capital.', a: 'Vienna' },
      { q: 'The point count of a piece, such as three for a knight.', a: 'Value' },
      { q: 'The affectionate nickname of the Indian world champion Anand.', a: 'Vishy' },
      { q: 'The French number one, born 1990, known everywhere by the initials MVL.', a: 'Vachier-Lagrave' },
      { q: 'The clearance manoeuvre in which a piece steps aside to free a square for a friend.', a: 'Vacating' },
    ],
    W: [
      { q: 'The side that moves first.', a: 'White' },
      { q: 'The full point.', a: 'Win' },
      { q: 'A square or a man that is hard to hold and easy to hit.', a: 'Weakness' },
      { q: 'Either flank of the board, away from the middle.', a: 'Wing' },
      { q: 'A quiet placeholder played only to pass the turn along.', a: 'Waiting move' },
      { q: 'The Dutch village whose January super-tournament is played beside the sea.', a: 'Wijk aan Zee' },
      { q: 'The Chinese player who won the women title in 2018 and again in 2020, surname Ju.', a: 'Wenjun' },
    ],
    X: [
      { q: 'The tactic in which a piece acts through an enemy man to the square beyond.', a: 'X-ray' },
      { q: 'The Chinese cousin of the game, played on the lines of the board across a river.', a: 'Xiangqi' },
    ],
    Y: [
      { q: 'The plan of Be3, Qd2 and long castling used against the Dragon.', a: 'Yugoslav Attack' },
      { q: 'The Seattle grandmaster and commentator Seirawan, by his first name.', a: 'Yasser' },
      { q: 'The annual age-group events for under-eighteens and younger.', a: 'Youth championships' },
    ],
    Z: [
      { q: 'The German term for being forced to play when every option makes things worse.', a: 'Zugzwang' },
      { q: 'The in-between shot that interrupts an expected sequence.', a: 'Zwischenzug' },
      { q: 'The old regional qualifying stage below the interzonal.', a: 'Zonal' },
      { q: 'The Polish-born master who lost the first world title match in 1886.', a: 'Zukertort' },
    ],
  },
};
