import type { RawPack } from '../core/packs';

export const codesSpiesPack: RawPack = {
  id: 'codes-spies',
  name: 'Codes, Ciphers & Spies',
  description: 'Secret writing, codebreakers, spycraft and the agencies that ran them.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🕵️',
  accent: '#334155',
  letters: {
    A: [
      { q: 'The modern American encryption standard adopted in 2001, three initials.', a: 'AES' },
      { q: 'The traditional name given to the sender in every textbook example.', a: 'Alice' },
      { q: 'The kind of cryptography that uses one key to lock and a different one to unlock.', a: 'Asymmetric' },
      { q: 'The ancient Hebrew scheme that swaps the first letter for the last, and so on.', a: 'Atbash' },
      { q: 'The proving that a message really came from who it claims.', a: 'Authentication' },
      { q: 'The German field cipher of 1918 that used only six letters in its grid.', a: 'ADFGVX' },
      { q: 'A rearrangement of the letters of a word to make another.', a: 'Anagram' },
      { q: 'The person a case officer recruits to steal secrets from the inside.', a: 'Asset' },
      { q: 'The CIA officer arrested in 1994 after selling names to Moscow for nine years.', a: 'Ames' },
      { q: 'The undercover operator sent to gather information in the field.', a: 'Agent' },
      { q: 'The ordered set of letters that any substitution scheme shuffles.', a: 'Alphabet' },
      { q: 'The Soviet illegal who lived in Brooklyn as a photographer until 1957.', a: 'Abel' },
      { q: 'The step-by-step procedure a cipher machine or a program follows.', a: 'Algorithm' },
    ],
    B: [
      { q: 'The Buckinghamshire mansion where British codebreakers worked from 1939.', a: 'Bletchley Park' },
      { q: 'The traditional name of the receiver in every textbook example.', a: 'Bob' },
      { q: 'The scheme that encrypts a fixed lump of data at a time, not letter by letter.', a: 'Block cipher' },
      { q: 'The attack that simply tries every possible key until one works.', a: 'Brute force' },
      { q: 'The deliberate hidden weakness left in a system for later use.', a: 'Backdoor' },
      { q: 'The chained ledger of hashed records that underpins Bitcoin.', a: 'Blockchain' },
      { q: 'The electromechanical machine Turing designed to search Enigma settings.', a: 'Bombe' },
      { q: 'The way of writing arbitrary data using 64 printable characters.', a: 'Base64' },
      { q: 'The art historian and Soviet spy of the Cambridge ring, unmasked in 1979.', a: 'Blunt' },
      { q: 'The Foreign Office member of that same ring who fled to Moscow in 1951.', a: 'Burgess' },
      { q: 'The planting of a concealed microphone in a room or a phone.', a: 'Bugging' },
      { q: 'The pair of letters treated as a unit by the 1854 British square scheme.', a: 'Bigram' },
      { q: 'The divided city that was the front line of Cold War spying.', a: 'Berlin' },
    ],
    C: [
      { q: 'A method of secret writing in which letters are replaced or moved.', a: 'Cipher' },
      { q: 'The whole science of keeping messages secret.', a: 'Cryptography' },
      { q: 'The scrambled output of an encryption, unreadable without a key.', a: 'Ciphertext' },
      { q: 'The shift-by-three scheme named after the Roman general who used it.', a: 'Caesar cipher' },
      { q: 'The event, fatal to a hash function, of two inputs giving the same digest.', a: 'Collision' },
      { q: 'The Bletchley valve machine of 1943 that attacked the German teleprinter traffic.', a: 'Colossus' },
      { q: 'The science of breaking secret writing without being given the key.', a: 'Cryptanalysis' },
      { q: 'The signed electronic document that vouches for a website identity.', a: 'Certificate' },
      { q: 'The guessed piece of plaintext, such as a weather report, that opened Enigma.', a: 'Crib' },
      { q: 'The ring of Soviet spies recruited at an English university in the 1930s.', a: 'Cambridge Five' },
      { q: 'The American foreign intelligence agency created in 1947, three initials.', a: 'CIA' },
      { q: 'The false identity and job under which an operative works abroad.', a: 'Cover' },
      { q: 'The forty-year standoff of the two blocs, the golden age of the trade.', a: 'Cold War' },
      { q: 'The first Soviet secret police, founded under Dzerzhinsky in 1917.', a: 'Cheka' },
    ],
    D: [
      { q: 'To turn a scrambled message back into readable text with the key.', a: 'Decrypt' },
      { q: 'The 1977 American standard with a 56-bit key, broken in public by 1998.', a: 'DES' },
      { q: 'The American who, with Hellman in 1976, published the first public key exchange.', a: 'Diffie' },
      { q: 'The cryptographic proof that a file came from a named sender and was not altered.', a: 'Digital signature' },
      { q: 'The method that works through a long wordlist, one entry at a time.', a: 'Dictionary attack' },
      { q: 'The hiding place where two spies leave material without ever meeting.', a: 'Dead drop' },
      { q: 'The spy who works for one side while pretending to serve the other.', a: 'Double agent' },
      { q: 'The intelligence officer or official who changes sides and flees abroad.', a: 'Defector' },
      { q: 'The first civilian head of the American agency, in office from 1953 to 1961.', a: 'Dulles' },
      { q: 'The file of collected material on a person or a target.', a: 'Dossier' },
      { q: 'The method that scrambles a message twice by moving its letters about, then again.', a: 'Double transposition' },
    ],
    E: [
      { q: 'The rotor machine the German forces relied on throughout the Second World War.', a: 'Enigma' },
      { q: 'To turn readable text into a form nobody else can read.', a: 'Encrypt' },
      { q: 'The public key method built on points of a certain algebraic shape, used in phones.', a: 'Elliptic curve' },
      { q: 'The measure of unpredictability in a key or a password.', a: 'Entropy' },
      { q: 'The listener on the wire, traditionally called Eve in textbooks.', a: 'Eavesdropper' },
      { q: 'The protection in which only the two devices, not the server, can read a chat.', a: 'End-to-end' },
      { q: 'The practice of spying, whatever the state or the century.', a: 'Espionage' },
      { q: 'The getting of an agent or a document safely out of hostile territory.', a: 'Exfiltration' },
      { q: 'The turning of characters into another representation, without any secrecy.', a: 'Encoding' },
      { q: 'The British engineer at GCHQ who conceived public key secrecy in 1970, unpublished.', a: 'Ellis' },
    ],
    F: [
      { q: 'The counting of how often each letter appears, which breaks simple substitution.', a: 'Frequency analysis' },
      { q: 'The network barrier that filters what traffic may pass.', a: 'Firewall' },
      { q: 'The short summary of a public key, read out to check no swap has happened.', a: 'Fingerprint' },
      { q: 'The splitting of a large number into its primes, on whose difficulty RSA rests.', a: 'Factorisation' },
      { q: 'The German-American whose network structure underlies most block ciphers.', a: 'Feistel' },
      { q: 'The American domestic security bureau, three initials.', a: 'FBI' },
      { q: 'The German-born physicist who passed atom bomb secrets to Moscow from Los Alamos.', a: 'Fuchs' },
      { q: 'The operation staged to look like the work of another nation.', a: 'False flag' },
      { q: 'The American who founded his country signals intelligence and coined cryptanalysis.', a: 'Friedman' },
      { q: 'The producing of a document or a signature that pretends to be from someone else.', a: 'Forgery' },
    ],
    G: [
      { q: 'The British signals intelligence service, successor to Bletchley, four initials.', a: 'GCHQ' },
      { q: 'The card with holes laid over a page to reveal the hidden words.', a: 'Grille' },
      { q: 'The unbroken nomenclator of Louis XIV, deciphered only in 1893.', a: 'Great Cipher' },
      { q: 'The Poe story of 1843 whose plot turns on a substitution puzzle and buried treasure.', a: 'Gold-Bug' },
      { q: 'The Soviet and Russian military intelligence directorate, three initials.', a: 'GRU' },
      { q: 'The Berlin tunnel of 1954 that tapped Soviet cables, betrayed from the very start.', a: 'Gold' },
      { q: 'The mathematical set with one operation, on which modern key exchange is built.', a: 'Group' },
      { q: 'The Nazi secret state police, whose name is a contraction of three German words.', a: 'Gestapo' },
      { q: 'The Soviet labour camp system whose survivors testified to the West.', a: 'Gulag' },
    ],
    H: [
      { q: 'The one-way function that turns any file into a short fixed-length digest.', a: 'Hash' },
      { q: 'The Egyptian picture writing that stayed unread until the 1820s.', a: 'Hieroglyphs' },
      { q: 'The padlocked version of the web protocol, five letters.', a: 'HTTPS' },
      { q: 'The 1929 scheme that encrypts blocks of letters using matrix multiplication.', a: 'Hill cipher' },
      { q: 'The opening exchange in which two machines agree on keys.', a: 'Handshake' },
      { q: 'The substitution that gives common letters several different symbols each.', a: 'Homophonic' },
      { q: 'The seduction of a target in order to gain secrets or leverage.', a: 'Honeytrap' },
      { q: 'The officer who runs an agent, meets them and passes on their product.', a: 'Handler' },
      { q: 'The first director of the American domestic bureau, in post for 48 years.', a: 'Hoover' },
      { q: 'The German-born rotor machine inventor whose patents predated Enigma, an American.', a: 'Hebern' },
    ],
    I: [
      { q: 'The guarantee that a message has not been altered on the way.', a: 'Integrity' },
      { q: 'The random block fed in at the start so the same text never encrypts alike.', a: 'Initialisation vector' },
      { q: 'The writing that shows only when the paper is heated or treated.', a: 'Invisible ink' },
      { q: 'The statistic that reveals how many alphabets a polyalphabetic scheme used.', a: 'Index of coincidence' },
      { q: 'The placing of an operative inside a hostile organisation.', a: 'Infiltration' },
      { q: 'The information a state gathers about its rivals, and the trade of gathering it.', a: 'Intelligence' },
      { q: 'The person who quietly passes on what they see, without formal recruitment.', a: 'Informant' },
      { q: 'The questioning of a captured operative to get what they know.', a: 'Interrogation' },
      { q: 'The deep-cover officer who lives abroad with no diplomatic protection at all.', a: 'Illegal' },
    ],
    J: [
      { q: 'The American president who invented a wheel cypher device in the 1790s.', a: 'Jefferson' },
      { q: 'The Japanese naval code the Americans read before Midway.', a: 'JN-25' },
      { q: 'The plain-sounding phrase that carries a hidden meaning agreed in advance.', a: 'Jargon code' },
      { q: 'The fictional British agent, number 007, created by Ian Fleming.', a: 'James Bond' },
    ],
    K: [
      { q: 'The secret value that locks and unlocks a message.', a: 'Key' },
      { q: 'The Dutchman whose 1883 principle says only the key, not the method, need be secret.', a: 'Kerckhoffs' },
      { q: 'The protocol by which two parties agree a shared secret over an open line.', a: 'Key exchange' },
      { q: 'The malicious program that records every keystroke a victim types.', a: 'Keylogger' },
      { q: 'The Prussian officer whose 1863 method finds the length of a repeating key.', a: 'Kasiski' },
      { q: 'The Soviet security and intelligence committee, three initials.', a: 'KGB' },
      { q: 'The Russian word for damaging material collected to blackmail someone.', a: 'Kompromat' },
      { q: 'The word that sets a polyalphabetic scheme, repeated along the message.', a: 'Keyword' },
    ],
    L: [
      { q: 'The German teleprinter machine whose traffic Bletchley called Tunny.', a: 'Lorenz' },
      { q: 'The IBM design of the early 1970s that was cut down to become the US standard.', a: 'Lucifer' },
      { q: 'The false life story an illegal operative memorises and lives.', a: 'Legend' },
      { q: 'The English novelist and former officer who wrote Tinker Tailor Soldier Spy.', a: 'Le Carre' },
      { q: 'The Moscow headquarters and prison of the Soviet security service.', a: 'Lubyanka' },
      { q: 'The attack, published in 1993, that finds approximations to a cipher behaviour.', a: 'Linear cryptanalysis' },
      { q: 'The single character, the smallest unit any classical scheme works on.', a: 'Letter' },
    ],
    M: [
      { q: 'The 1991 Rivest hash function, thoroughly broken and now forbidden.', a: 'MD5' },
      { q: 'The attack in which a third party sits between two talkers and relays both ways.', a: 'Man in the middle' },
      { q: 'The dot-and-dash telegraph alphabet of 1844.', a: 'Morse code' },
      { q: 'The Scottish queen beheaded in 1587 after Walsingham read her enciphered letters.', a: 'Mary Stuart' },
      { q: 'The photograph shrunk to the size of a full stop, hidden in a letter.', a: 'Microdot' },
      { q: 'The set of tradecraft habits an officer follows in a hostile capital.', a: 'Moscow rules' },
      { q: 'The agent who burrows into the enemy service and reports from within.', a: 'Mole' },
      { q: 'The British domestic security service, three characters.', a: 'MI5' },
      { q: 'The British foreign intelligence service, three characters.', a: 'MI6' },
      { q: 'The Dutch dancer shot by the French in 1917 as a German spy.', a: 'Mata Hari' },
      { q: 'The scheme that uses only one fixed replacement alphabet throughout.', a: 'Monoalphabetic' },
      { q: 'The text a sender actually wants to get through, whatever the wrapping.', a: 'Message' },
    ],
    N: [
      { q: 'The American signals intelligence agency founded in 1952, three initials.', a: 'NSA' },
      { q: 'The Native American language used as an unbreakable field code in the Pacific war.', a: 'Navajo' },
      { q: 'The number used once, included so a captured message cannot be replayed.', a: 'Nonce' },
      { q: 'The scheme that hides the real letters among a mass of meaningless ones.', a: 'Null cipher' },
      { q: 'The branch of mathematics on which nearly all public key methods rest.', a: 'Number theory' },
      { q: 'The Soviet interior commissariat of the 1930s purges, four initials.', a: 'NKVD' },
      { q: 'The 16th-century list that gave a symbol to each word as well as each letter.', a: 'Nomenclator' },
      { q: 'The Russian revolutionary scheme that adds key numbers to a lettered square.', a: 'Nihilist cipher' },
    ],
    O: [
      { q: 'The only provably unbreakable scheme, if the random key is used just once.', a: 'One-time pad' },
      { q: 'The deliberate muddling of code so nobody can read what it does.', a: 'Obfuscation' },
      { q: 'The wrapping of traffic in layers of encryption, each hop peeling one off.', a: 'Onion routing' },
      { q: 'The system that leaks a little information with each query, and so can be broken.', a: 'Oracle' },
      { q: 'The American wartime intelligence service, forerunner of the CIA, three initials.', a: 'OSS' },
      { q: 'The staff member of an agency who actually runs operations in the field.', a: 'Operative' },
      { q: 'The publishing of a design so that anyone may inspect it for weaknesses.', a: 'Open source' },
    ],
    P: [
      { q: 'The readable original message before any scrambling.', a: 'Plaintext' },
      { q: 'The freely published half of an asymmetric key pair.', a: 'Public key' },
      { q: 'The secret half of that same pair, which must never be shared.', a: 'Private key' },
      { q: 'The 1854 British scheme that encrypts letters in pairs on a five-by-five square.', a: 'Playfair' },
      { q: 'The 1991 program by Phil Zimmermann that put strong encryption in public hands.', a: 'PGP' },
      { q: 'The whole number divisible only by one and itself, the raw material of RSA.', a: 'Prime' },
      { q: 'The scheme that switches between several alphabets as it goes.', a: 'Polyalphabetic' },
      { q: 'The Japanese diplomatic machine the Americans solved and codenamed by colour.', a: 'Purple' },
      { q: 'The Cambridge ring member who rose high in British intelligence and fled in 1963.', a: 'Philby' },
      { q: 'The Soviet colonel who passed missile secrets to the West before the Cuban crisis.', a: 'Penkovsky' },
      { q: 'The secret word a user types to prove who they are.', a: 'Password' },
      { q: 'The one-way spread of a state message to shape what people believe.', a: 'Propaganda' },
      { q: 'The board of jumbled letter pairs that made wartime Enigma far harder.', a: 'Plugboard' },
    ],
    Q: [
      { q: 'The kind of machine whose arrival would break today public key methods.', a: 'Quantum computer' },
      { q: 'The basic unit of that new kind of machine.', a: 'Qubit' },
      { q: 'The Inca system of knotted cords that recorded numbers and perhaps words.', a: 'Quipu' },
    ],
    R: [
      { q: 'The 1977 public key method named after three MIT initials.', a: 'RSA' },
      { q: 'The turning wired wheel that made Enigma change its alphabet each keystroke.', a: 'Rotor' },
      { q: 'The slab of 196 BC whose three scripts unlocked Egyptian writing.', a: 'Rosetta Stone' },
      { q: 'The Belgian design chosen in 2000 as the new American standard.', a: 'Rijndael' },
      { q: 'The shift-by-thirteen scheme once used to hide punchlines on Usenet.', a: 'Rot13' },
      { q: 'The Polish mathematician who first broke Enigma in 1932.', a: 'Rejewski' },
      { q: 'The American couple executed in 1953 for passing atomic secrets.', a: 'Rosenbergs' },
      { q: 'The senior officer who runs a whole station under diplomatic cover.', a: 'Resident' },
      { q: 'The careful cultivation and turning of a source into an agent.', a: 'Recruitment' },
      { q: 'The unpredictable stream on which every good key depends.', a: 'Randomness' },
    ],
    S: [
      { q: 'The class of cipher in which each letter is replaced by another symbol.', a: 'Substitution' },
      { q: 'The American family of hash functions, three initials, now in its third version.', a: 'SHA' },
      { q: 'The hiding of a message so that nobody knows there is a message at all.', a: 'Steganography' },
      { q: 'The kind of encryption in which both parties share the same key.', a: 'Symmetric' },
      { q: 'The ancient Spartan rod around which a strip of leather was wound to write on.', a: 'Scytale' },
      { q: 'The random value added to a password before hashing so two alike differ.', a: 'Salt' },
      { q: 'The short-lived key agreed for one conversation and then thrown away.', a: 'Session key' },
      { q: 'The American who founded information theory and proved the pad unbreakable.', a: 'Shannon' },
      { q: 'The contractor who leaked American surveillance documents in 2013.', a: 'Snowden' },
      { q: 'The East German ministry of state security, notorious for its files.', a: 'Stasi' },
      { q: 'The agent who lives an ordinary life for years until activated.', a: 'Sleeper' },
      { q: 'The watching of a target by camera, car or on foot.', a: 'Surveillance' },
      { q: 'The quiet flat kept by a service for meetings nobody must see.', a: 'Safe house' },
      { q: 'The encrypted messaging app that made end-to-end chat ordinary.', a: 'Signal' },
    ],
    T: [
      { q: 'The class of cipher in which the letters stay the same but change places.', a: 'Transposition' },
      { q: 'The Cambridge mathematician who broke the naval Enigma and founded computing.', a: 'Turing' },
      { q: 'The protocol that puts the padlock on a web connection, three initials.', a: 'TLS' },
      { q: 'The mathematical function easy one way and hard to reverse without a secret.', a: 'Trapdoor' },
      { q: 'The anonymity network built on layered routing, three letters.', a: 'Tor' },
      { q: 'The Bletchley nickname for the German teleprinter traffic they attacked with valves.', a: 'Tunny' },
      { q: 'The whole body of practical skills of the spy: drops, brush passes, disguise.', a: 'Tradecraft' },
      { q: 'The crime of betraying your own country.', a: 'Treason' },
      { q: 'The physical or software object you must hold to be granted access.', a: 'Token' },
      { q: 'The 1974 novel in which Smiley hunts a Soviet mole in the Circus.', a: 'Tinker Tailor Soldier Spy' },
    ],
    U: [
      { q: 'The British codeword for the intelligence produced by breaking German machine traffic.', a: 'Ultra' },
      { q: 'The amount of ciphertext needed before a key can in principle be found.', a: 'Unicity distance' },
      { q: 'Working while hiding your real identity and employer.', a: 'Undercover' },
      { q: 'The American high-altitude spy plane shot down over Russia in 1960.', a: 'U-2' },
    ],
    V: [
      { q: 'The 16th-century French scheme that shifts each letter by a keyword letter.', a: 'Vigenere' },
      { q: 'The American whose 1917 teleprinter machine combined the message with a random tape.', a: 'Vernam' },
      { q: 'The illustrated manuscript, bought in 1912, that nobody has ever read.', a: 'Voynich' },
      { q: 'The American project that decrypted Soviet cables and exposed the atom spies.', a: 'Venona' },
      { q: 'The encrypted tunnel that hides your traffic from the local network, three initials.', a: 'VPN' },
      { q: 'The background checking of a person before they are trusted with secrets.', a: 'Vetting' },
    ],
    W: [
      { q: 'The Bletchley mathematician whose diagonal board made the Bombe far faster.', a: 'Welchman' },
      { q: 'The Elizabethan spymaster who trapped the Scottish queen with a forged postscript.', a: 'Walsingham' },
      { q: 'The volunteer who arrives unbidden at an embassy offering to sell secrets.', a: 'Walk-in' },
      { q: 'The tapping of a telephone line to listen in.', a: 'Wiretap' },
      { q: 'The hidden mark placed in a document so a leak can be traced to one copy.', a: 'Watermark' },
      { q: 'The obsolete wireless security scheme of 1999, broken within a few years.', a: 'WEP' },
    ],
    X: [
      { q: 'The exclusive-or operation on which the one-time pad and stream ciphers are built.', a: 'XOR' },
      { q: 'The standard, a number with a dot, that defines the format of a public certificate.', a: 'X.509' },
    ],
    Y: [
      { q: 'The American who ran the Black Chamber and then published its secrets in 1931.', a: 'Yardley' },
      { q: 'The small hardware key you touch to prove who you are.', a: 'Yubikey' },
      { q: 'The Crimean conference of 1945 whose deals the atom spies were already reporting on.', a: 'Yalta' },
    ],
    Z: [
      { q: 'The 1917 German message to Mexico whose decipherment helped bring America into the war.', a: 'Zimmermann Telegram' },
      { q: 'The method that convinces a checker you hold a secret without revealing any of it.', a: 'Zero-knowledge proof' },
      { q: 'The software hole for which no patch yet exists, prized by intelligence services.', a: 'Zero-day' },
    ],
  },
};
