import type { RawPack } from '../core/packs';

export const comicsGraphicNovelsPack: RawPack = {
  id: 'comics',
  name: 'Comics & Graphic Novels',
  description: 'Publishers, artists, classic runs and the art of sequential storytelling.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '💥',
  accent: '#c2410c',
  letters: {
    A: [
      { q: 'The bearded English writer of Watchmen and V for Vendetta.', a: 'Alan Moore' },
      { q: 'Osamu Tezuka\'s manga about a robot child, known in Japan as Mighty Atom.', a: 'Astro Boy' },
      { q: 'The DC hero who rules Atlantis.', a: 'Aquaman' },
      { q: 'The red-haired Riverdale teenager who has headlined comics since 1941.', a: 'Archie' },
      { q: 'The small Gaulish warrior created by Rene Goscinny and Albert Uderzo.', a: 'Asterix' },
      { q: 'The cartoonist who won a Pulitzer for Maus.', a: 'Art Spiegelman' },
      { q: 'The Marvel team assembled in 1963 with Thor, Iron Man and the Hulk.', a: 'Avengers' },
      { q: 'Katsuhiro Otomo\'s dystopian Neo-Tokyo manga.', a: 'Akira' },
      { q: 'The painter of photorealistic superhero art in Marvels and Kingdom Come.', a: 'Alex Ross' },
      { q: 'The actor who played Batman in the camp 1966 television series.', a: 'Adam West' },
      { q: 'The size-changing Marvel hero originally Hank Pym.', a: 'Ant-Man' },
      { q: 'The title whose fifteenth and final issue introduced Spider-Man in 1962.', a: 'Amazing Fantasy' },
      { q: 'The cartoonist who wrote Fun Home and gave her name to a movie test.', a: 'Alison Bechdel' },
      { q: 'Batman\'s loyal butler.', a: 'Alfred' },
    ],
    B: [
      { q: 'The Gotham vigilante created by Bob Kane and Bill Finger in 1939.', a: 'Batman' },
      { q: 'The Wakandan king who first appeared in Fantastic Four in 1966.', a: 'Black Panther' },
      { q: 'The reclusive creator of Calvin and Hobbes.', a: 'Bill Watterson' },
      { q: 'Craig Thompson\'s autobiographical graphic novel about a Wisconsin adolescence.', a: 'Blankets' },
      { q: 'The long-running British weekly that introduced Dennis the Menace.', a: 'Beano' },
      { q: 'Jeff Smith\'s black-and-white fantasy saga starring three pale cousins.', a: 'Bone' },
      { q: 'The writer of Ultimate Spider-Man who co-created Miles Morales.', a: 'Brian Michael Bendis' },
      { q: 'The alias adopted by Barbara Gordon in Gotham.', a: 'Batgirl' },
      { q: 'Captain America\'s wartime sidekick who returned as the Winter Soldier.', a: 'Bucky Barnes' },
      { q: 'The Marvel vampire hunter introduced in Tomb of Dracula in 1973.', a: 'Blade' },
      { q: 'Jean-Claude Forest\'s French science-fiction heroine of 1962.', a: 'Barbarella' },
      { q: 'The writer long denied official credit as Batman\'s co-creator.', a: 'Bill Finger' },
      { q: 'The Russian-trained Marvel spy Natasha Romanoff.', a: 'Black Widow' },
    ],
    C: [
      { q: 'The strip about a six-year-old and his stuffed tiger that ended in 1995.', a: 'Calvin and Hobbes' },
      { q: 'The shield-carrying hero created by Joe Simon and Jack Kirby in 1941.', a: 'Captain America' },
      { q: 'The writer of the 16-year X-Men run that produced the Dark Phoenix Saga.', a: 'Chris Claremont' },
      { q: 'The cartoonist who drew Peanuts for 50 years.', a: 'Charles Schulz' },
      { q: 'Dave Sim\'s 300-issue series about an aardvark.', a: 'Cerebus' },
      { q: 'The huge San Diego pop-culture convention held every July.', a: 'Comic-Con' },
      { q: 'The round-headed Peanuts boy who never gets to kick the football.', a: 'Charlie Brown' },
      { q: 'The chain-smoking Liverpool occult detective of Hellblazer.', a: 'Constantine' },
      { q: 'The X-Man whose eyes fire an optic blast.', a: 'Cyclops' },
      { q: 'Hugo Pratt\'s wandering Italian sailor.', a: 'Corto Maltese' },
      { q: 'The self-censorship body American publishers set up in 1954.', a: 'Comics Code Authority' },
      { q: 'The time-travelling mutant soldier created by Rob Liefeld.', a: 'Cable' },
      { q: 'The Gotham burglar Selina Kyle.', a: 'Catwoman' },
    ],
    D: [
      { q: 'The blind lawyer hero of Hell\'s Kitchen.', a: 'Daredevil' },
      { q: 'The Sorcerer Supreme created by Steve Ditko.', a: 'Doctor Strange' },
      { q: 'The British artist who drew Watchmen.', a: 'Dave Gibbons' },
      { q: 'The wisecracking mercenary created by Rob Liefeld and Fabian Nicieza.', a: 'Deadpool' },
      { q: 'Frank Miller\'s 1986 story of an ageing Batman coming out of retirement.', a: 'Dark Knight Returns' },
      { q: 'Scott Adams\'s strip about an engineer trapped in a cubicle.', a: 'Dilbert' },
      { q: 'The British weekly that starred Desperate Dan.', a: 'Dandy' },
      { q: 'Garry Trudeau\'s political strip, which won a Pulitzer in 1975.', a: 'Doonesbury' },
      { q: 'Tiziano Sclavi\'s Italian horror series about a nightmare investigator.', a: 'Dylan Dog' },
      { q: 'The tyrant of Apokolips created by Jack Kirby.', a: 'Darkseid' },
      { q: 'The Latverian monarch who is the Fantastic Four\'s greatest enemy.', a: 'Doctor Doom' },
      { q: 'The spiky-haired Beano troublemaker whose dog is called Gnasher.', a: 'Dennis the Menace' },
      { q: 'The publisher of Superman, Batman and Wonder Woman.', a: 'DC Comics' },
    ],
    E: [
      { q: 'The industry\'s annual prize, named after a pioneering graphic novelist.', a: 'Eisner Award' },
      { q: 'The 1950s horror and crime publisher of Tales from the Crypt.', a: 'EC Comics' },
      { q: 'The ninja assassin created by Frank Miller for Daredevil.', a: 'Elektra' },
      { q: 'The Marvel team of British-based mutants launched in 1988.', a: 'Excalibur' },
      { q: 'The cosmic race Jack Kirby introduced for Marvel in 1976.', a: 'Eternals' },
      { q: 'The writer whose Captain America run brought back the Winter Soldier.', a: 'Ed Brubaker' },
      { q: 'The White Queen of the Hellfire Club.', a: 'Emma Frost' },
      { q: 'The Daniel Clowes anthology that first serialised Ghost World.', a: 'Eightball' },
    ],
    F: [
      { q: 'Marvel\'s first family, launched in 1961.', a: 'Fantastic Four' },
      { q: 'The writer and artist behind Sin City and Batman: Year One.', a: 'Frank Miller' },
      { q: 'The scarlet speedster whose 1956 revival began the Silver Age.', a: 'Flash' },
      { q: 'The painter of muscular Conan and Death Dealer fantasy covers.', a: 'Frank Frazetta' },
      { q: 'Alan Moore and Eddie Campbell\'s dense graphic novel about the Whitechapel murders.', a: 'From Hell' },
      { q: 'Bill Willingham\'s Vertigo series about fairy-tale characters exiled in New York.', a: 'Fables' },
      { q: 'Alison Bechdel\'s memoir about her father, later a Broadway musical.', a: 'Fun Home' },
      { q: 'The Scottish artist of All-Star Superman.', a: 'Frank Quitely' },
      { q: 'Robert Crumb\'s tomcat who starred in an X-rated 1972 cartoon.', a: 'Fritz the Cat' },
    ],
    G: [
      { q: 'Jim Davis\'s lasagne-loving cat strip, launched in 1978.', a: 'Garfield' },
      { q: 'The DC hero whose ring is powered by willpower.', a: 'Green Lantern' },
      { q: 'Daniel Clowes\'s story of Enid and Rebecca after high school.', a: 'Ghost World' },
      { q: 'Sergio Aragones\'s dim-witted barbarian.', a: 'Groo' },
      { q: 'The fictional metropolis that Batman protects.', a: 'Gotham City' },
      { q: 'The bow-wielding DC hero Oliver Queen.', a: 'Green Arrow' },
      { q: 'The purple-helmeted devourer of worlds created by Jack Kirby.', a: 'Galactus' },
      { q: 'The Marvel space team that includes Rocket and Groot.', a: 'Guardians of the Galaxy' },
      { q: 'The Northern Irish writer of Preacher and The Boys.', a: 'Garth Ennis' },
      { q: 'The Cajun X-Man who throws charged playing cards.', a: 'Gambit' },
      { q: 'Peter Parker\'s girlfriend killed by the Green Goblin in 1973.', a: 'Gwen Stacy' },
    ],
    H: [
      { q: 'Mike Mignola\'s red demon investigator of the paranormal.', a: 'Hellboy' },
      { q: 'The Belgian pen name of Georges Remi, creator of Tintin.', a: 'Herge' },
      { q: 'The green giant created by Stan Lee and Jack Kirby in 1962.', a: 'Hulk' },
      { q: 'The Joker\'s accomplice, created for a 1992 animated series.', a: 'Harley Quinn' },
      { q: 'The archer of the Avengers, Clint Barton.', a: 'Hawkeye' },
      { q: 'The flaming member of the Fantastic Four, Johnny Storm.', a: 'Human Torch' },
      { q: 'The winged DC hero armed with a mace.', a: 'Hawkman' },
      { q: 'The Vertigo title starring a cynical English occultist.', a: 'Hellblazer' },
      { q: 'The cigar-chewing Marvel fowl created by Steve Gerber.', a: 'Howard the Duck' },
    ],
    I: [
      { q: 'The armoured Marvel hero created in 1963, alter ego Tony Stark.', a: 'Iron Man' },
      { q: 'The publisher founded in 1992 by seven artists who quit Marvel.', a: 'Image Comics' },
      { q: 'Sue Storm\'s alias in the Fantastic Four.', a: 'Invisible Woman' },
      { q: 'Jodorowsky and Moebius\'s psychedelic French science-fiction epic.', a: 'Incal' },
      { q: 'The Marvel royal family led by Black Bolt.', a: 'Inhumans' },
      { q: 'The 1991 Marvel event in which Thanos collects six gems.', a: 'Infinity Gauntlet' },
      { q: 'The teenage armoured hero Riri Williams.', a: 'Ironheart' },
      { q: 'Robert Kirkman\'s superhero series about Mark Grayson.', a: 'Invincible' },
    ],
    J: [
      { q: 'The artist nicknamed the King of Comics.', a: 'Jack Kirby' },
      { q: 'Batman\'s arch-enemy, who debuted in 1940.', a: 'Joker' },
      { q: 'The artist of the 1991 X-Men issue that sold over eight million copies.', a: 'Jim Lee' },
      { q: 'The 2000 AD lawman of Mega-City One.', a: 'Judge Dredd' },
      { q: 'The X-Man who becomes the Phoenix.', a: 'Jean Grey' },
      { q: 'The cartoonist who pioneered comics journalism with Palestine.', a: 'Joe Sacco' },
      { q: 'The former hero turned private investigator created in 2001 for Alias.', a: 'Jessica Jones' },
      { q: 'The artist and writer who relaunched Superman in 1986 with Man of Steel.', a: 'John Byrne' },
      { q: 'The scar-faced DC western bounty hunter.', a: 'Jonah Hex' },
    ],
    K: [
      { q: 'George Herriman\'s surreal strip set in Coconino County.', a: 'Krazy Kat' },
      { q: 'The 1996 painted DC epic by Mark Waid and Alex Ross.', a: 'Kingdom Come' },
      { q: 'Mark Millar and John Romita Jr\'s series about a teenager with no powers.', a: 'Kick-Ass' },
      { q: 'The big-game hunter who stalks Spider-Man.', a: 'Kraven' },
      { q: 'The crime boss Wilson Fisk.', a: 'Kingpin' },
      { q: 'The Jersey City teenager who became Ms. Marvel in 2014.', a: 'Kamala Khan' },
      { q: 'One of the two men who created the Teenage Mutant Ninja Turtles with Peter Laird.', a: 'Kevin Eastman' },
      { q: 'The green mineral that saps Superman\'s strength.', a: 'Kryptonite' },
    ],
    L: [
      { q: 'Winsor McCay\'s dream-world newspaper strip that began in 1905.', a: 'Little Nemo' },
      { q: 'The Daily Planet reporter who loves Superman.', a: 'Lois Lane' },
      { q: 'Superman\'s bald businessman nemesis.', a: 'Lex Luthor' },
      { q: 'Thor\'s adoptive brother and the god of mischief.', a: 'Loki' },
      { q: 'Joe Hill and Gabriel Rodriguez\'s horror series set in a New England house.', a: 'Locke and Key' },
      { q: 'The bulletproof Harlem hero with unbreakable skin.', a: 'Luke Cage' },
      { q: 'The Franco-Belgian cowboy who draws faster than his own shadow.', a: 'Lucky Luke' },
      { q: 'The Hernandez brothers\' long-running alternative series.', a: 'Love and Rockets' },
      { q: 'The Peanuts character who runs a five-cent psychiatry booth.', a: 'Lucy' },
    ],
    M: [
      { q: 'Art Spiegelman\'s Holocaust memoir drawn with mice.', a: 'Maus' },
      { q: 'The publisher of Spider-Man and the X-Men.', a: 'Marvel' },
      { q: 'The pen name of the French artist Jean Giraud.', a: 'Moebius' },
      { q: 'The X-Men\'s greatest foe, who bends metal to his will.', a: 'Magneto' },
      { q: 'The Brooklyn teenager who became a second Spider-Man.', a: 'Miles Morales' },
      { q: 'The redhead Peter Parker eventually married in 1987.', a: 'Mary Jane Watson' },
      { q: 'The Lee Falk newspaper magician whose strip began in 1934.', a: 'Mandrake' },
      { q: 'The British newspaper strip heroine created by Peter O\'Donnell in 1963.', a: 'Modesty Blaise' },
      { q: 'The Japanese word for comics.', a: 'Manga' },
      { q: 'Jack Kirby\'s escape artist from the Fourth World.', a: 'Mister Miracle' },
      { q: 'The shapeshifting blue mutant who opposes the X-Men.', a: 'Mystique' },
      { q: 'The satirical American magazine fronted by Alfred E. Neuman.', a: 'Mad' },
    ],
    N: [
      { q: 'The English author of The Sandman.', a: 'Neil Gaiman' },
      { q: 'The eyepatch-wearing spymaster who leads SHIELD.', a: 'Nick Fury' },
      { q: 'The identity Dick Grayson took after outgrowing his sidekick role.', a: 'Nightwing' },
      { q: 'The blue teleporting mutant with a pointed tail.', a: 'Nightcrawler' },
      { q: 'Masashi Kishimoto\'s manga about a young ninja.', a: 'Naruto' },
      { q: 'The prince of Atlantis who was one of Marvel\'s first characters in 1939.', a: 'Namor' },
      { q: 'The 1982 spin-off team of teenage X-Men trainees.', a: 'New Mutants' },
      { q: 'The Marvel hero Richard Rider, powered by an alien corps.', a: 'Nova' },
    ],
    O: [
      { q: 'The Japanese artist called the god of manga.', a: 'Osamu Tezuka' },
      { q: 'The menhir-carrying best friend of Asterix.', a: 'Obelix' },
      { q: 'Eiichiro Oda\'s pirate manga, the best-selling series of all time.', a: 'One Piece' },
      { q: 'The codename Barbara Gordon used as a wheelchair-bound information broker.', a: 'Oracle' },
      { q: 'The real name of the weather-controlling X-Man called Storm.', a: 'Ororo Munroe' },
      { q: 'The Watchmen character whose real name is Adrian Veidt.', a: 'Ozymandias' },
      { q: 'The Autobot leader of the Transformers comics.', a: 'Optimus Prime' },
    ],
    P: [
      { q: 'The strip starring Snoopy and Charlie Brown.', a: 'Peanuts' },
      { q: 'Marjane Satrapi\'s memoir of growing up in Iran.', a: 'Persepolis' },
      { q: 'The skull-shirted vigilante Frank Castle.', a: 'Punisher' },
      { q: 'The spinach-eating sailor created by E. C. Segar.', a: 'Popeye' },
      { q: 'Garth Ennis and Steve Dillon\'s series about Jesse Custer.', a: 'Preacher' },
      { q: 'The bald founder of the X-Men, Charles Xavier.', a: 'Professor X' },
      { q: 'Walt Kelly\'s swamp strip whose possum said we have met the enemy and he is us.', a: 'Pogo' },
      { q: 'The photographer bitten by a radioactive spider.', a: 'Peter Parker' },
      { q: 'Hal Foster\'s Arthurian Sunday strip begun in 1937.', a: 'Prince Valiant' },
      { q: 'The plant-controlling Gotham villain Pamela Isley.', a: 'Poison Ivy' },
    ],
    R: [
      { q: 'Batman\'s original sidekick, introduced in 1940.', a: 'Robin' },
      { q: 'The underground cartoonist behind Zap and Fritz the Cat.', a: 'Robert Crumb' },
      { q: 'The masked Watchmen character with an ever-shifting inkblot face.', a: 'Rorschach' },
      { q: 'The artist who created Cable and launched Youngblood.', a: 'Rob Liefeld' },
      { q: 'Captain America\'s Nazi arch-enemy.', a: 'Red Skull' },
      { q: 'The town where Archie and his friends go to high school.', a: 'Riverdale' },
      { q: 'The immortal Batman foe who leads the League of Assassins.', a: 'Ra\'s al Ghul' },
      { q: 'The X-Man who absorbs the powers of anyone she touches.', a: 'Rogue' },
    ],
    S: [
      { q: 'The hero created by Stan Lee and Steve Ditko in Amazing Fantasy.', a: 'Spider-Man' },
      { q: 'The Krypton-born hero created by Jerry Siegel and Joe Shuster in 1938.', a: 'Superman' },
      { q: 'Neil Gaiman\'s Vertigo series about Morpheus, lord of dreams.', a: 'Sandman' },
      { q: 'The Marvel editor and writer who signed off with Excelsior.', a: 'Stan Lee' },
      { q: 'Frank Miller\'s crime series drawn in stark black and white, filmed in 2005.', a: 'Sin City' },
      { q: 'The teenage witch who debuted in an Archie title in 1962.', a: 'Sabrina' },
      { q: 'The plant creature whose series Alan Moore reinvented in the 1980s.', a: 'Swamp Thing' },
      { q: 'The chrome-skinned herald of Galactus.', a: 'Silver Surfer' },
      { q: 'The space-opera series begun in 2012 by Brian K. Vaughan and Fiona Staples.', a: 'Saga' },
      { q: 'Naoko Takeuchi\'s magical-girl manga.', a: 'Sailor Moon' },
      { q: 'The hero Billy Batson becomes when he says a magic word.', a: 'Shazam' },
      { q: 'Todd McFarlane\'s Image hero, formerly Al Simmons.', a: 'Spawn' },
      { q: 'The reclusive co-creator of Spider-Man and Doctor Strange.', a: 'Steve Ditko' },
      { q: 'The comics era that began with the 1956 revival of the Flash.', a: 'Silver Age' },
    ],
    T: [
      { q: 'Herge\'s quiff-haired Belgian reporter.', a: 'Tintin' },
      { q: 'The purple Titan who wields the Infinity Gauntlet.', a: 'Thanos' },
      { q: 'The hammer-wielding Asgardian of Marvel comics.', a: 'Thor' },
      { q: 'The artist who drew Amazing Spider-Man before creating Spawn.', a: 'Todd McFarlane' },
      { q: 'Warren Ellis and Darick Robertson\'s series about the gonzo journalist Spider Jerusalem.', a: 'Transmetropolitan' },
      { q: 'The British post-apocalyptic punk heroine created by Jamie Hewlett and Alan Martin.', a: 'Tank Girl' },
      { q: 'The Gotham villain formerly known as Harvey Dent.', a: 'Two-Face' },
      { q: 'DC\'s team of young sidekicks, revived in 1980 by Marv Wolfman and George Perez.', a: 'Teen Titans' },
      { q: 'The 1984 black-and-white parody comic about four reptilian martial artists.', a: 'Teenage Mutant Ninja Turtles' },
      { q: 'The rocky-skinned member of the Fantastic Four, Ben Grimm.', a: 'Thing' },
    ],
    U: [
      { q: 'The title of the mutant series Chris Claremont wrote for 16 years.', a: 'Uncanny X-Men' },
      { q: 'The 1960s counterculture self-published movement centred on San Francisco.', a: 'Underground Comix' },
      { q: 'Carl Barks\'s fabulously rich Disney duck.', a: 'Uncle Scrooge' },
      { q: 'The imprint launched in 2000 to restart the company\'s heroes for new readers.', a: 'Ultimate Marvel' },
      { q: 'Stan Sakai\'s samurai rabbit series.', a: 'Usagi Yojimbo' },
      { q: 'The murderous robot created by Hank Pym.', a: 'Ultron' },
    ],
    V: [
      { q: 'Alan Moore and David Lloyd\'s story of a masked anarchist in a fascist Britain.', a: 'V for Vendetta' },
      { q: 'The DC imprint for mature readers launched in 1993.', a: 'Vertigo' },
      { q: 'The alien symbiote foe of Spider-Man.', a: 'Venom' },
      { q: 'The French science-fiction series by Pierre Christin and Jean-Claude Mezieres.', a: 'Valerian' },
      { q: 'The synthetic Avenger built by Ultron.', a: 'Vision' },
      { q: 'The 1990s publisher of Bloodshot and X-O Manowar.', a: 'Valiant Comics' },
      { q: 'The Warren magazine vampire heroine introduced in 1969.', a: 'Vampirella' },
    ],
    W: [
      { q: 'The 1986 series about Rorschach, Dr Manhattan and Ozymandias.', a: 'Watchmen' },
      { q: 'The Amazon hero created by William Moulton Marston in 1941.', a: 'Wonder Woman' },
      { q: 'The clawed Canadian mutant who first appeared in an Incredible Hulk issue in 1974.', a: 'Wolverine' },
      { q: 'The creator of The Spirit who championed the graphic novel form.', a: 'Will Eisner' },
      { q: 'Robert Kirkman\'s zombie series begun in 2003.', a: 'Walking Dead' },
      { q: 'The English writer of Transmetropolitan and Planetary.', a: 'Warren Ellis' },
      { q: 'The pioneering artist behind Little Nemo in Slumberland.', a: 'Winsor McCay' },
      { q: 'The Kid Flash sidekick who later took on the lead speedster role.', a: 'Wally West' },
    ],
    Y: [
      { q: 'Brian K. Vaughan\'s series in which every male mammal but one dies.', a: 'Y: The Last Man' },
      { q: 'The 1890s Richard Outcault character often called the first strip star.', a: 'Yellow Kid' },
      { q: 'Kiyohiko Azuma\'s gentle manga about a curious little girl.', a: 'Yotsuba' },
      { q: 'The blue-skinned Guardians of the Galaxy member who steers an arrow by whistling.', a: 'Yondu' },
      { q: 'One of Hank Pym\'s later costumed identities.', a: 'Yellowjacket' },
    ],
  },
};
