import type { RawPack } from '../core/packs';

export const conspiracyEasyPack: RawPack = {
  id: 'conspiracy-easy',
  name: 'Conspiracy Theories',
  description: 'The famous ones — UFOs, cryptids and cover-ups everyone has heard of.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '👁️',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: 'Secretive US Air Force base in the Nevada desert long rumored to hide captured spacecraft.', a: 'Area 51', category: 'ufo', difficulty: 1 },
      { q: 'The lost city beneath the sea, first described by the philosopher Plato.', a: 'Atlantis', category: 'urban-legend', difficulty: 1 },
      { q: 'Beings from other worlds said to pilot flying saucers and visit Earth.', a: 'Aliens', category: 'ufo', difficulty: 1 },
      { q: 'When a person claims to have been taken aboard a spacecraft against their will.', a: 'Abduction', category: 'ufo', difficulty: 2 },
      { q: 'Idea that visitors from space helped early humans build their greatest monuments.', a: 'Ancient astronauts', category: 'ufo', difficulty: 2 },
      { q: 'The desert US state, full of military ranges, that hosts the secret base linked to saucer rumors.', a: 'Arizona', category: 'ufo', difficulty: 3 },
      { q: 'The vast continent, including the United States, where the most famous 1947 saucer-crash story unfolded.', a: 'America', category: 'ufo', difficulty: 2 },
      { q: 'Word for an unwelcome arrival from space, as in a fictional "______ invasion".', a: 'Alien', category: 'ufo', difficulty: 1 },
      { q: 'A ghostly figure that appears and fades, seen in a haunted house, is called an ______.', a: 'Apparition', category: 'paranormal', difficulty: 2 },
      { q: 'The 1962 disappearance of three prisoners from this island fortress fuels survival theories.', a: 'Alcatraz', category: 'urban-legend', difficulty: 2 },
      { q: 'Cattle found dead with strange precise wounds in remote fields are blamed by some on aliens — so-called cattle "______".', a: 'Aberration', category: 'ufo', difficulty: 3 },
      { q: 'The desert region of New Mexico and Nevada where so many sightings happen is part of the American Southwest, full of open ______.', a: 'Airspace', category: 'ufo', difficulty: 2 },
      { q: 'A person who claims to have been taken aboard a saucer is the supposed "______" who was carried off.', a: 'Abductee', category: 'ufo', difficulty: 2 },
    ],
    B: [
      { q: 'Large, hairy ape-like creature said to roam the forests of North America.', a: 'Bigfoot', category: 'cryptid', difficulty: 1 },
      { q: 'Stretch of ocean off Florida and Puerto Rico where ships and planes supposedly vanish.', a: 'Bermuda Triangle', category: 'urban-legend', difficulty: 1 },
      { q: 'The deep dark color of the unmarked suits worn by the agents who silence UFO witnesses — "Men in ______".', a: 'Black', category: 'ufo', difficulty: 1 },
      { q: 'Believers say the truth is hidden in a secret government one of these — a "______ box".', a: 'Black box', category: 'government', difficulty: 2 },
      { q: 'The region of Germany where the famous "enlightened" secret society was said to be founded.', a: 'Bavaria', category: 'secret-society', difficulty: 3 },
      { q: 'A grainy out-of-focus image is called a ______ photo — the usual quality of monster pictures.', a: 'Blurry', category: 'cryptid', difficulty: 2 },
      { q: 'A skeptic says many ghost and UFO sightings turn out to be made up, or simply ______.', a: 'Bogus', category: 'hoax', difficulty: 2 },
      { q: 'Many ancient-mystery theories ask who really built these huge stone tombs of Egypt.', a: 'Burial pyramids', category: 'paranormal', difficulty: 3 },
      { q: 'Country home to Loch Ness, Stonehenge and many cryptid sightings, also called the UK or ______.', a: 'Britain', category: 'cryptid', difficulty: 2 },
      { q: 'A spaceship from another world that aliens supposedly fly to Earth is their "saucer" or flying ______.', a: 'Boat of the sky', category: 'ufo', difficulty: 3 },
      { q: 'A claim that explains big events as a hidden plot by powerful people is, in short, a ______ in the truth.', a: 'Belief', category: 'government', difficulty: 1 },
    ],
    C: [
      { q: 'Trails left by aircraft that some claim are secret sprayed chemicals.', a: 'Chemtrails', category: 'government', difficulty: 1 },
      { q: 'Mysterious flattened patterns that appear overnight in fields of wheat.', a: 'Crop circles', category: 'paranormal', difficulty: 1 },
      { q: 'Carved human-head artifacts of clear quartz, said by some to hold mystical powers.', a: 'Crystal skulls', category: 'paranormal', difficulty: 2 },
      { q: 'Blood-sucking creature of Latin American legend said to attack goats and livestock.', a: 'Chupacabra', category: 'cryptid', difficulty: 2 },
      { q: 'When officials hide an embarrassing truth from the public, they are accused of staging this.', a: 'Cover-up', category: 'government', difficulty: 1 },
      { q: 'The deadly hex said to strike anyone who disturbs a pharaoh\'s tomb is known as the mummy\'s ______.', a: 'Curse', category: 'paranormal', difficulty: 1 },
      { q: 'Hairy ape-men and lake monsters that science doesn\'t recognize are all examples of these hidden ______.', a: 'Creatures', category: 'cryptid', difficulty: 1 },
      { q: 'A believer in plots, often pictured wearing a foil hat, is mockingly called a conspiracy ______.', a: 'Crackpot', category: 'urban-legend', difficulty: 2 },
      { q: 'The vast Asian country whose ancient deserts and walls feature in some "visitors from the stars" tales.', a: 'China', category: 'ufo', difficulty: 2 },
      { q: 'A secret meeting of powerful people plotting in private is called a shadowy ______ against the public.', a: 'Conspiracy', category: 'secret-society', difficulty: 1 },
      { q: 'A grainy, out-of-focus picture is the usual quality of so-called "evidence" — a low-quality ______ image.', a: 'Camera', category: 'cryptid', difficulty: 2 },
    ],
    D: [
      { q: 'Tales claim these prehistoric reptiles still survive hidden in remote jungles and lakes.', a: 'Dinosaurs', category: 'cryptid', difficulty: 2 },
      { q: 'What conspiracy believers say a secret group hides when they "cover up" — the secret ______.', a: 'Documents', category: 'government', difficulty: 1 },
      { q: 'A swirling sea funnel sometimes blamed for sinking ships in the Bermuda waters — a "deadly ______".', a: 'Downdraft', category: 'urban-legend', difficulty: 3 },
      { q: 'A spooky old house where ghosts are said to wander is a haunted one of these places to live.', a: 'Dwelling', category: 'paranormal', difficulty: 2 },
      { q: 'Strange lights in the night sky are often reported as flying ones of these — round metal craft shaped like plates.', a: 'Discs', category: 'ufo', difficulty: 2 },
      { q: 'Texas city where President Kennedy was shot, the focus of decades of assassination theories.', a: 'Dallas', category: 'assassination', difficulty: 2 },
      { q: 'A person who doubts official stories and digs for hidden truth is full of ______ about the authorities.', a: 'Doubt', category: 'government', difficulty: 1 },
      { q: 'Believers say the wreckage of a crashed saucer was secretly hauled off — the so-called recovered ______.', a: 'Debris', category: 'ufo', difficulty: 2 },
      { q: 'When ships and planes vanish in the Bermuda zone, people say they simply "______ed" off the map.', a: 'Disappear', category: 'urban-legend', difficulty: 1 },
      { q: 'The hidden underground burial chamber of an Egyptian pharaoh, said to be cursed, is buried this far below ground.', a: 'Deep', category: 'paranormal', difficulty: 2 },
    ],
    E: [
      { q: 'Pacific island famous for hundreds of giant carved stone heads, the Moai.', a: 'Easter Island', category: 'urban-legend', difficulty: 1 },
      { q: 'Rock-and-roll legend whose 1977 "death" some fans refuse to believe, claiming sightings ever since.', a: 'Elvis Presley', alt: ['Elvis'], category: 'urban-legend', difficulty: 1 },
      { q: 'Country of the pyramids and the Sphinx, central to many ancient-mystery theories.', a: 'Egypt', category: 'paranormal', difficulty: 1 },
      { q: 'Another word for a being from another planet, often shortened to "ET".', a: 'Extraterrestrial', category: 'ufo', difficulty: 1 },
      { q: 'Believers say a craft crashed and the wreckage was hidden away as physical proof, or hard ______.', a: 'Evidence', category: 'ufo', difficulty: 2 },
      { q: 'A close ______ of the third kind is a famous phrase for meeting beings from space.', a: 'Encounter', category: 'ufo', difficulty: 2 },
      { q: 'The whole planet, said by Flat-believers to be a disc rather than a globe — our home, ______.', a: 'Earth', category: 'urban-legend', difficulty: 1 },
      { q: 'A skeptic demands proof: the official files should be brought out and ______ to the public.', a: 'Exposed', category: 'government', difficulty: 2 },
      { q: 'A person who claims to have personally seen a UFO or a ghost is an ______-witness to it.', a: 'Eye', category: 'paranormal', difficulty: 1 },
      { q: 'A craft from another planet, an alien spaceship, is also called an "______" vehicle from beyond Earth.', a: 'ET', category: 'ufo', difficulty: 2 },
    ],
    F: [
      { q: 'Belief that our planet is a disc, not a globe, rejecting mainstream science.', a: 'Flat Earth', category: 'urban-legend', difficulty: 1 },
      { q: 'Common nickname for a disc-shaped UFO that "flies" across the sky.', a: 'Flying saucer', category: 'ufo', difficulty: 1 },
      { q: 'When something is staged or faked to deceive the public, conspiracy fans call it ______.', a: 'Fake', category: 'government', difficulty: 1 },
      { q: 'The US state, home to the Bermuda waters and Cape Canaveral, tied to many ocean-mystery tales.', a: 'Florida', category: 'urban-legend', difficulty: 2 },
      { q: 'Crop circles are said to appear overnight in these open farm areas of wheat and corn.', a: 'Fields', category: 'paranormal', difficulty: 1 },
      { q: 'Witnesses claim a crashed UFO was filmed; the grainy moving images are called the ______.', a: 'Footage', category: 'ufo', difficulty: 2 },
      { q: 'A thin sheet of shiny metal, jokingly worn as a hat to block mind control — "tin______".', a: 'Foil', category: 'urban-legend', difficulty: 2 },
      { q: 'A spooky old house where ghosts are said to wander is described by this adjective starting with F — frightening.', a: 'Frightful', category: 'paranormal', difficulty: 3 },
      { q: 'Believers say authorities staged a deception to mislead everyone, a deliberate ______ designed to deceive.', a: 'Fabrication', category: 'government', difficulty: 2 },
    ],
    G: [
      { q: 'Spirits of the dead said to haunt old houses, castles and battlefields.', a: 'Ghosts', category: 'paranormal', difficulty: 1 },
      { q: 'Common nickname for the short, big-eyed aliens described by people claiming abduction.', a: 'Greys', category: 'ufo', difficulty: 1 },
      { q: 'Believers accuse this body — the official authorities — of hiding UFO files from the public.', a: 'Government', category: 'government', difficulty: 1 },
      { q: 'Country whose philosopher Plato first wrote of the sunken city beneath the waves.', a: 'Greece', category: 'urban-legend', difficulty: 2 },
      { q: 'A spooky white sheeted figure is the classic cartoon image of a "______" — a friendly dead spirit.', a: 'Ghost', category: 'paranormal', difficulty: 1 },
      { q: 'The Egyptian plateau where the Great Pyramid and Sphinx stand, tied to many star-builder theories.', a: 'Giza', category: 'paranormal', difficulty: 2 },
      { q: 'Believers say the public is fooled and kept in the dark, or simply kept ______.', a: 'Guessing', category: 'government', difficulty: 2 },
      { q: 'A glowing flying object over a field at night, the classic shape of a UFO, hovers above the ______.', a: 'Ground', category: 'ufo', difficulty: 1 },
      { q: 'A blood-sucking beast of Mexican legend is said to attack these horned farm animals it is named after.', a: 'Goats', category: 'cryptid', difficulty: 2 },
      { q: 'The pale, see-through, eerie appearance of a spirit photographed at night is described as looking quite ______.', a: 'Ghastly', category: 'paranormal', difficulty: 2 },
    ],
    H: [
      { q: 'A trick or deception meant to fool people, like a faked monster photo.', a: 'Hoax', category: 'hoax', difficulty: 1 },
      { q: 'A house where ghosts are said to dwell is described as being this.', a: 'Haunted', category: 'paranormal', difficulty: 1 },
      { q: 'Snowman of the Himalayas, an Asian cousin of the North American Sasquatch legend.', a: 'Himalayan Yeti', alt: ['abominable snowman'], category: 'cryptid', difficulty: 2 },
      { q: 'The mountain range of Asia where the white-furred ape-creature is said to live.', a: 'Himalayas', category: 'cryptid', difficulty: 2 },
      { q: 'Believers say a UFO that crashed was wheeled off and stored in a secret aircraft "______".', a: 'Hangar', category: 'ufo', difficulty: 2 },
      { q: 'The supposed deadly power said to protect a pharaoh\'s tomb and strike those who open it is a "______".', a: 'Hex', category: 'paranormal', difficulty: 2 },
      { q: 'When a flying object stays still in the air over one spot, witnesses say it began to ______.', a: 'Hover', category: 'ufo', difficulty: 2 },
      { q: 'Many believe an event was secretly arranged, that the powerful pulled the strings ______ from view.', a: 'Hidden', category: 'government', difficulty: 1 },
      { q: 'A spirit said to throw objects and make noises in a haunted home is a noisy German-named ghost, a "poltergeist" — it brings the house this kind of trouble.', a: 'Havoc', category: 'paranormal', difficulty: 3 },
    ],
    I: [
      { q: 'Secret society, supposedly founded in Bavaria, said to control world events from the shadows.', a: 'Illuminati', category: 'secret-society', difficulty: 1 },
      { q: 'A piece of land surrounded by water, like the one famous for giant stone heads in the Pacific.', a: 'Island', category: 'urban-legend', difficulty: 1 },
      { q: 'Believers are sure aliens have come to Earth; they hold this firm "______" without solid proof.', a: 'Idea', category: 'ufo', difficulty: 1 },
      { q: 'Subcontinent whose ancient carved temples feature in some "built by visitors from space" claims.', a: 'India', category: 'ufo', difficulty: 2 },
      { q: 'A reported sighting of a strange light or craft is logged as a UFO "______" — an event report.', a: 'Incident', category: 'ufo', difficulty: 2 },
      { q: 'Believers claim a shadowy group secretly pulls the strings, exerting hidden ______ over the world.', a: 'Influence', category: 'secret-society', difficulty: 2 },
      { q: 'When aliens supposedly arrive in force to conquer Earth, sci-fi calls it an alien ______.', a: 'Invasion', category: 'ufo', difficulty: 1 },
      { q: 'A person who claims to have lived through being taken by aliens is the supposed ______ of the encounter.', a: 'Intended victim', category: 'ufo', difficulty: 3 },
      { q: 'Believers think a secret elite group quietly directs world events from the shadows, an unseen "______ hand".', a: 'Invisible', category: 'secret-society', difficulty: 2 },
    ],
    J: [
      { q: 'US president shot dead in Dallas in 1963, the subject of endless cover-up theories.', a: 'John F. Kennedy', alt: ['JFK', 'Kennedy'], category: 'assassination', difficulty: 1 },
      { q: 'Dense tropical forests where hidden surviving dinosaurs and lost cities are rumored to lie.', a: 'Jungle', category: 'cryptid', difficulty: 2 },
      { q: 'A skeptical reporter who digs into cover-ups and secret files is doing this kind of investigative work.', a: 'Journalism', category: 'government', difficulty: 2 },
      { q: 'Many sea-monster tales come from sailors\' tall stories during long ocean ones of these — long sea trips.', a: 'Journeys', category: 'cryptid', difficulty: 2 },
      { q: 'The slain 1963 president shares his three famous initials; his family name starts with this letter? No — his surname.', a: 'JFK', category: 'assassination', difficulty: 1 },
      { q: 'A witness who saw a UFO and wrote it down kept a personal ______, a dated record of the sighting.', a: 'Journal', category: 'ufo', difficulty: 2 },
      { q: 'Crashed-saucer wreckage that the military supposedly hauls away is treated as priceless alien "______" — the find of a lifetime.', a: 'Jackpot', category: 'ufo', difficulty: 3 },
      { q: 'A skeptic who refuses to believe in ghosts without proof is being skeptical and reserves ______.', a: 'Judgement', category: 'paranormal', difficulty: 3 },
      { q: 'The forested American state of Washington and Oregon, where Bigfoot is sought, sits in the Pacific North-this.', a: 'Jurisdiction of the woods', category: 'cryptid', difficulty: 3 },
    ],
    K: [
      { q: 'Giant tentacled sea monster of Norse legend said to drag whole ships under the waves.', a: 'Kraken', category: 'cryptid', difficulty: 1 },
      { q: 'A water spirit of Scottish folklore, a shape-shifting horse said to haunt lochs and rivers.', a: 'Kelpie', category: 'cryptid', difficulty: 3 },
      { q: 'The slain 1963 US president, famous by three initials, had this surname.', a: 'Kennedy', category: 'assassination', difficulty: 1 },
      { q: 'A royal one of these — a pharaoh — is whose ancient tomb the famous "curse" is said to protect.', a: 'King of Egypt', category: 'paranormal', difficulty: 2 },
      { q: 'The Asian mountain creature, the white-furred snowman, is sought by climbers who must be expert at this in snow.', a: 'Karabiner climbing', category: 'cryptid', difficulty: 3 },
      { q: 'A skeptic dismisses cover-up tales, saying believers should have better ______ of the facts.', a: 'Knowledge', category: 'government', difficulty: 2 },
      { q: 'The hairy ape-man and the lake monster are unknown to science; believers say their existence is ______ from official records.', a: 'Kept out', category: 'cryptid', difficulty: 3 },
      { q: 'A ghost in folklore that wails to foretell a death is an Irish spirit; more broadly such a spirit is said to ______ for the doomed.', a: 'Keen', category: 'paranormal', difficulty: 3 },
      { q: 'A king of ancient Egypt buried with treasure and a supposed curse is also called a "boy ______" if he died young, like Tutankhamun.', a: 'Kid pharaoh', category: 'paranormal', difficulty: 3 },
    ],
    L: [
      { q: 'Scottish freshwater lake home to the world\'s most famous lake monster, "Nessie".', a: 'Loch Ness', category: 'cryptid', difficulty: 1 },
      { q: 'Strange glowing ones of these in the night sky are the most common form of UFO sighting.', a: 'Lights', category: 'ufo', difficulty: 1 },
      { q: 'A deep body of water, like the Scottish one with the monster, is called this in Scots.', a: 'Loch', category: 'cryptid', difficulty: 1 },
      { q: 'Conspiracy theorists claim the 1969 Apollo walk was filmed on a movie one of these — a studio "______" set.', a: 'Lunar fake', category: 'hoax', difficulty: 3 },
      { q: 'The sunken city of Plato is a famous example of a once-great place now "______" beneath the waves.', a: 'Lost', category: 'urban-legend', difficulty: 2 },
      { q: 'The 1972 Andes survivors and other "they actually died" theories question whether anyone is still ______.', a: 'Living', category: 'urban-legend', difficulty: 2 },
      { q: 'A ghost is said to wander or ______ in the halls of a haunted house, never resting.', a: 'Linger', category: 'paranormal', difficulty: 2 },
      { q: 'The carved giant heads on a remote Pacific island, and the Egyptian pyramids, are huge stone ones of these — ancient ruins to visit.', a: 'Landmarks', category: 'urban-legend', difficulty: 2 },
      { q: 'When a flying saucer supposedly touches down, witnesses say they watched it slowly make a ______ on the ground.', a: 'Landing', category: 'ufo', difficulty: 1 },
    ],
    M: [
      { q: 'Conspiracy theory that NASA faked the 1969 walk on the lunar surface using a film studio.', a: 'Moon landing hoax', category: 'hoax', difficulty: 1 },
      { q: 'Dark-suited mysterious agents said to silence people who report UFO sightings.', a: 'Men in Black', category: 'ufo', difficulty: 1 },
      { q: 'Ship found drifting in 1872 with no crew aboard, an enduring sea mystery.', a: 'Mary Celeste', category: 'urban-legend', difficulty: 2 },
      { q: 'The supposed deadly hex that strikes those who disturb an Egyptian pharaoh\'s tomb — the "______ curse".', a: 'Mummy', category: 'paranormal', difficulty: 1 },
      { q: 'Sightings of strange creatures, ghosts and UFOs are all examples of unexplained ones of these — riddles.', a: 'Mysteries', category: 'urban-legend', difficulty: 1 },
      { q: 'Giant beasts of legend, from the Kraken to Nessie, are all called these.', a: 'Monsters', category: 'cryptid', difficulty: 1 },
      { q: 'A 16th-century French seer\'s rhymed predictions were collected; many search them for hidden ______.', a: 'Meanings', category: 'paranormal', difficulty: 2 },
      { q: 'The branch of armed forces believers accuse of hiding the alien wreckage at the secret base — the ______.', a: 'Military', category: 'ufo', difficulty: 2 },
      { q: 'The Egyptian preserved bodies wrapped in bandages, said to rise and curse tomb robbers, are called these.', a: 'Mummies', category: 'paranormal', difficulty: 1 },
    ],
    N: [
      { q: 'Affectionate nickname for the Loch Ness Monster.', a: 'Nessie', category: 'cryptid', difficulty: 1 },
      { q: '16th-century French seer whose cryptic verses are said to predict the future.', a: 'Nostradamus', category: 'paranormal', difficulty: 1 },
      { q: 'US space agency that some claim faked the famous 1969 lunar mission.', a: 'NASA', category: 'hoax', difficulty: 1 },
      { q: 'US state whose remote desert base is the most famous in alien-cover-up lore.', a: 'Nevada', category: 'ufo', difficulty: 2 },
      { q: 'A reported UFO event most often happens at this time of day, when strange lights are most easily seen.', a: 'Night', category: 'ufo', difficulty: 1 },
      { q: 'The US state where the famous 1947 saucer crash supposedly happened, full of military ranges — New ______.', a: 'New Mexico', category: 'ufo', difficulty: 2 },
      { q: 'A craft from space that nobody can identify is, by definition, a flying object that is "un______".', a: 'Named', category: 'ufo', difficulty: 3 },
      { q: 'Some refuse to believe a famous singer really died and claim he simply went into hiding — that the death was "______".', a: 'Not real', category: 'urban-legend', difficulty: 2 },
      { q: 'Crop circles and saucers are said to appear at this dark time, when the sky is best for seeing strange lights.', a: 'Nightfall', category: 'ufo', difficulty: 1 },
    ],
    O: [
      { q: 'The vast salt water the Bermuda Triangle sits in, where ships and planes are said to vanish.', a: 'Ocean', category: 'urban-legend', difficulty: 1 },
      { q: 'A secret one of these — a group with hidden rituals, like the Illuminati — is a shadowy "______".', a: 'Order', category: 'secret-society', difficulty: 1 },
      { q: 'Sea creature with eight arms, sometimes inflated by legend into a giant ship-eating monster.', a: 'Octopus', category: 'cryptid', difficulty: 2 },
      { q: 'A glowing ball of light captured in ghost photos is often called a spooky one of these.', a: 'Orb', category: 'paranormal', difficulty: 2 },
      { q: 'The letters U-F-"O" stand for an unidentified flying one of these.', a: 'Object', category: 'ufo', difficulty: 1 },
      { q: 'Believers demand the secret files be released and brought out into the ______, not hidden any longer.', a: 'Open', category: 'government', difficulty: 1 },
      { q: 'A witness to a strange light in the sky is also called an "______-looker" who happened to see it.', a: 'Onlooker', category: 'ufo', difficulty: 2 },
      { q: 'The Greek philosopher Plato is the original source for the tale of the sunken city, recorded long ago in his ______ writings.', a: 'Old', category: 'urban-legend', difficulty: 2 },
      { q: 'A skeptic says aliens, ghosts and monsters do not exist — they exist only in believers\' ______, not in reality.', a: 'Opinion', category: 'government', difficulty: 2 },
    ],
    P: [
      { q: 'Giant Egyptian stone monuments some claim were built with help from the stars.', a: 'Pyramids', category: 'paranormal', difficulty: 1 },
      { q: 'Things beyond normal science — ghosts, spirits and psychic events — are described by this word.', a: 'Paranormal', category: 'paranormal', difficulty: 1 },
      { q: 'A 16th-century seer\'s rhymed forecasts are studied as supposed ones of these — foretellings of the future.', a: 'Prophecies', category: 'paranormal', difficulty: 2 },
      { q: 'The famous "surgeon\'s photo" of 1934 supposedly showing Nessie was later admitted to be a deliberate ______.', a: 'Prank', category: 'cryptid', difficulty: 2 },
      { q: 'The ancient Egyptian ruler whose tomb the deadly curse is said to protect.', a: 'Pharaoh', category: 'paranormal', difficulty: 1 },
      { q: 'A skeptic asks believers for hard ______ before accepting any ghost or UFO claim.', a: 'Proof', category: 'government', difficulty: 1 },
      { q: 'The Greek philosopher who first wrote of the sunken city beneath the sea.', a: 'Plato', category: 'urban-legend', difficulty: 2 },
      { q: 'The Caribbean island, a US territory, that marks one corner of the famous three-sided ocean mystery zone.', a: 'Puerto Rico', category: 'urban-legend', difficulty: 3 },
      { q: 'Witnesses claim a saucer left scorch marks where it touched down; believers call this the alien "______ of arrival" or footprint.', a: 'Print', category: 'ufo', difficulty: 2 },
    ],
    R: [
      { q: 'New Mexico town where a crashed object in 1947 sparked the most famous UFO story.', a: 'Roswell', category: 'ufo', difficulty: 1 },
      { q: 'A circular pattern flattened into a wheat field is one type of crop circle, also a "fairy ______".', a: 'Ring', category: 'paranormal', difficulty: 2 },
      { q: 'When a craft from space supposedly crashes, theorists say the wreckage was secretly ______ — carried away.', a: 'Removed', category: 'ufo', difficulty: 2 },
      { q: 'A skeptic asks for proof and demands the cover-up files be made public — a call for full ______.', a: 'Release', category: 'government', difficulty: 2 },
      { q: 'The Puerto ______ corner anchors one point of the famous three-cornered ocean mystery.', a: 'Rico', category: 'urban-legend', difficulty: 3 },
      { q: 'Some say a famous singer faked his own death and lives on in hiding — that he never truly ______.', a: 'Rested', category: 'urban-legend', difficulty: 2 },
      { q: 'A ghost or spirit is the lingering soul of someone who cannot find peaceful ______ after death.', a: 'Rest', category: 'paranormal', difficulty: 1 },
      { q: 'Believers say a craft really did crash and call for the government to ______ what truly happened.', a: 'Reveal', category: 'government', difficulty: 1 },
      { q: 'The mysterious 1872 ship found drifting with no crew aboard was a sailing vessel discovered ______, with no one steering it.', a: 'Rudderless', category: 'urban-legend', difficulty: 3 },
    ],
    S: [
      { q: 'Another name for Bigfoot, the hairy giant of North American forests.', a: 'Sasquatch', category: 'cryptid', difficulty: 1 },
      { q: 'Ancient circle of standing stones on England\'s Salisbury Plain, of mysterious purpose.', a: 'Stonehenge', category: 'paranormal', difficulty: 1 },
      { q: 'Disc-shaped craft, the classic shape people report when they see a UFO.', a: 'Saucer', category: 'ufo', difficulty: 1 },
      { q: 'A hidden group that meets in private and is said to control events is called a secret one of these.', a: 'Society', category: 'secret-society', difficulty: 1 },
      { q: 'Ghosts, the souls of the dead said to linger, are also called these.', a: 'Spirits', category: 'paranormal', difficulty: 1 },
      { q: 'When a witness sees a strange light or craft in the sky, they report a UFO "______".', a: 'Sighting', category: 'ufo', difficulty: 1 },
      { q: 'Mythical lake and ocean beasts said to lurk in deep water are broadly called sea ______.', a: 'Serpents', category: 'cryptid', difficulty: 2 },
      { q: 'The carved giant stone heads of a remote Pacific island, sources of endless wonder, are called the ______.', a: 'Statues', category: 'urban-legend', difficulty: 2 },
      { q: 'The white frozen flakes that cover Himalayan peaks, where the "abominable" creature leaves its huge footprints.', a: 'Snow', category: 'cryptid', difficulty: 1 },
    ],
    T: [
      { q: 'Shiny metal headgear jokingly worn to stop the government from reading your mind.', a: 'Tinfoil hat', category: 'urban-legend', difficulty: 2 },
      { q: 'A claim that explains events as a secret plot — like a faked landing — is a conspiracy "______".', a: 'Theory', category: 'government', difficulty: 1 },
      { q: 'Believers say the official story is a lie and they are seeking the hidden ______.', a: 'Truth', category: 'government', difficulty: 1 },
      { q: 'Pharaoh whose 1922 tomb opening was followed by deaths blamed on the "curse".', a: 'Tutankhamun', alt: ['King Tut', 'Tut'], category: 'paranormal', difficulty: 2 },
      { q: 'Footprints in mud or snow, offered as proof a hairy giant passed by, are called its ones of these.', a: 'Tracks', category: 'cryptid', difficulty: 2 },
      { q: 'The Bermuda mystery zone is named for its three-cornered shape, a "______" on the map.', a: 'Triangle', category: 'urban-legend', difficulty: 1 },
      { q: 'A pharaoh\'s underground burial chamber, said to be cursed, is his ancient ______.', a: 'Tomb', category: 'paranormal', difficulty: 1 },
      { q: 'The city of Dallas, where Kennedy was shot, is in this US state — the Lone Star State of ______.', a: 'Texas', category: 'assassination', difficulty: 2 },
      { q: 'Crop circles, fairy rings and pyramid alignments are all said to mark a special powerful spot, an "energy ______".', a: 'Threshold', category: 'paranormal', difficulty: 3 },
    ],
    U: [
      { q: 'The three-letter term for a strange craft or light in the sky that can\'t be explained.', a: 'UFO', category: 'ufo', difficulty: 1 },
      { q: 'A strange light or craft that defies explanation is said to be "un______" — not known by name.', a: 'Unidentified', category: 'ufo', difficulty: 1 },
      { q: 'Ghosts, monsters and saucers are all things science calls these — events with no known cause.', a: 'Unexplained', category: 'paranormal', difficulty: 1 },
      { q: 'Strange beings from space are said to live somewhere out in this — all of space beyond Earth.', a: 'Universe', category: 'ufo', difficulty: 1 },
      { q: 'When a saucer supposedly lands, theorists say the wider public is left in the dark and totally ______.', a: 'Unaware', category: 'ufo', difficulty: 2 },
      { q: 'The official line is the United States, often shortened to the "U.S." or the ______.', a: 'USA', category: 'government', difficulty: 1 },
      { q: 'A craft from space is said to fly "______" into the night sky — toward the heavens overhead.', a: 'Upward', category: 'ufo', difficulty: 2 },
      { q: 'A flying object whose nature nobody knows is, by its very definition, a complete ______ to the people who saw it.', a: 'Unknown', category: 'ufo', difficulty: 1 },
      { q: 'The official body of government and military that believers accuse of the cover-up — the "______ States authorities".', a: 'United', category: 'government', difficulty: 1 },
    ],
    V: [
      { q: 'When ships or planes seem to disappear without a trace, people say they did this.', a: 'Vanish', category: 'urban-legend', difficulty: 1 },
      { q: 'Aliens who supposedly come to Earth in saucers are unwelcome ones of these — guests from afar.', a: 'Visitors', category: 'ufo', difficulty: 1 },
      { q: 'A swirling whirlpool said to swallow ships in the Bermuda waters is a deadly water "______".', a: 'Vortex', category: 'urban-legend', difficulty: 2 },
      { q: 'A real or claimed monster sighting on film gives believers their grainy ones of these — moving footage.', a: 'Videos', category: 'cryptid', difficulty: 2 },
      { q: 'A person claiming to have seen a UFO or a ghost gives their first-hand account, an eye-witness ______.', a: 'View', category: 'ufo', difficulty: 2 },
      { q: 'The lush, leafy thick growth of a jungle, where lost cities and surviving dinosaurs supposedly hide.', a: 'Vegetation', category: 'cryptid', difficulty: 2 },
      { q: 'A ship or plane that goes missing in the Bermuda zone is a lost or vanished sea ______.', a: 'Vessel', category: 'urban-legend', difficulty: 2 },
      { q: 'The pale, see-through, ghostly look of a spirit photographed in a haunted house makes it look almost ______.', a: 'Vaporous', category: 'paranormal', difficulty: 3 },
      { q: 'A glowing craft seen hovering and then darting away at night is a strange aerial ______, plain in sight yet unexplained.', a: 'Vision', category: 'ufo', difficulty: 2 },
    ],
    W: [
      { q: 'Crop circles are said to appear overnight in fields of this golden grain used to make bread.', a: 'Wheat', category: 'paranormal', difficulty: 1 },
      { q: 'A person who saw a UFO, a ghost or a monster and can tell their story is an eye-______.', a: 'Witness', category: 'ufo', difficulty: 1 },
      { q: 'The bigger picture some theorists distrust — global powers and the whole "New ______ Order" idea.', a: 'World', category: 'secret-society', difficulty: 1 },
      { q: 'Crashed-craft remains that believers say the military secretly hauled away is the alien ______.', a: 'Wreckage', category: 'ufo', difficulty: 2 },
      { q: 'The deep forested places of the Pacific Northwest where the hairy giant is said to roam — the dark ______.', a: 'Woods', category: 'cryptid', difficulty: 1 },
      { q: 'A swirling spinning funnel of water that supposedly sinks ships in the Bermuda mystery is a "______pool".', a: 'Whirlpool', category: 'urban-legend', difficulty: 2 },
      { q: 'When a saucer flies past at speed, witnesses describe a sudden rush of air, a "______" overhead.', a: 'Whoosh', category: 'ufo', difficulty: 2 },
      { q: 'The wide world of the unknown — aliens, ghosts and monsters — is full of strange things that make us ______ what is real.', a: 'Wonder', category: 'paranormal', difficulty: 1 },
      { q: 'The deep ocean of the Bermuda mystery, where ships sink, is a vast expanse of open salt ______.', a: 'Water', category: 'urban-legend', difficulty: 1 },
    ],
    Y: [
      { q: 'The "abominable snowman" of the Himalayas, a white-furred ape said to live in the snow.', a: 'Yeti', category: 'cryptid', difficulty: 1 },
      { q: 'A long-ago period; many "ancient mystery" tales claim things happened thousands of these ago.', a: 'Years past', category: 'paranormal', difficulty: 2 },
      { q: 'An Australian cousin of Bigfoot, a hairy ape-man of the outback whose name starts with Y.', a: 'Yowie', category: 'cryptid', difficulty: 3 },
      { q: 'Long, long ago — the setting of pyramid, Atlantis and ancient-astronaut legends — "back in ______".', a: 'Yesteryear', category: 'paranormal', difficulty: 3 },
      { q: 'A loud cry of fear someone might give on glimpsing a ghost or a monster in the dark, starting with Y.', a: 'Yell', category: 'paranormal', difficulty: 2 },
      { q: 'The shaggy snow-creature of Asia is famously sought by mountain climbers every passing one of these — a 365-day span.', a: 'Year', category: 'cryptid', difficulty: 2 },
      { q: 'A loud excited shout, like one a believer might give on finally spotting a monster, starting with Y.', a: 'Yelp', category: 'paranormal', difficulty: 3 },
    ],
  },
};
