import type { RawPack } from '../core/packs';

export const conspiracyMediumPack: RawPack = {
  id: 'conspiracy-medium',
  name: 'Conspiracy Theories',
  description: 'Secret societies, cover-ups, cryptids and the lore behind the legends.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '👁️',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: 'In Sumerian-myth-based fringe theories, the supposed ancient race from the skies said to have engineered humanity.', a: 'Anunnaki', category: 'ufo', difficulty: 3 },
      { q: 'The author Erich von Daniken argued visitors from space built the pyramids, in his "ancient ___" idea.', a: 'Astronauts', category: 'ufo', difficulty: 3 },
      { q: 'A person who claims to have been taken aboard a craft by non-human beings is called an alien ___.', a: 'Abductee', category: 'ufo', difficulty: 3 },
      { q: 'The killing of a prominent figure such as a president, the deed at the centre of the Kennedy and Lincoln theories.', a: 'Assassination', category: 'assassination', difficulty: 2 },
      { q: 'The 1942 wartime panic over a phantom air raid on a US west-coast city, when guns fired into the night sky; the Battle of Los ___.', a: 'Angeles', category: 'ufo', difficulty: 3 },
      { q: 'A person who claims to have witnessed strange aerial craft and is later "visited" and silenced; UFO lore calls such a frightened witness an ___ contact.', a: 'Abduction', category: 'ufo', difficulty: 2 },
      { q: 'The deliberate concealment of a crime or scandal by those in power, the goal of every cover-up in this pack; an "official ___-up".', a: 'Authorities', category: 'government', difficulty: 2 },
      { q: 'The American author Charles Fort collected reports of bizarre rains, falls and disappearances; such inexplicable phenomena are now called "Fortean" or simply ___.', a: 'Anomalies', category: 'paranormal', difficulty: 3 },
      { q: 'The undercover state operative, in French, planted in a protest movement to incite illegal acts so the group can be discredited and crushed.', a: 'Agent provocateur', category: 'government', difficulty: 4 },
      { q: 'The shape-shifting reptilian rulers of David Icke\'s theory are sometimes said to come from this star whose light reaches us across many years; the broad word for a far-off sun.', a: 'Aldebaran', category: 'ufo', difficulty: 5 },
    ],
    B: [
      { q: 'The annual invite-only gathering of around 130 powerful politicians and financiers, rumoured to secretly steer world affairs.', a: 'Bilderberg Group', category: 'secret-society', difficulty: 3 },
      { q: 'The exclusive Californian redwood camp where elite men hold a secret summer retreat with an owl-effigy ceremony.', a: 'Bohemian Grove', category: 'secret-society', difficulty: 3 },
      { q: 'The phenomenon where large crowds misremember a fact the same way; also called the Mandela effect, but named here for a children\'s-book family of cartoon bears.', a: 'Berenstain', category: 'paranormal', difficulty: 4, alt: ['Berenstain effect'] },
      { q: 'A purported deep-state plan to sicken the public via the air is the core of the chemtrail and "biological ___" fears.', a: 'Bioweapon', category: 'urban-legend', difficulty: 3 },
      { q: 'The dark-coloured unmarked helicopters that 1990s militia lore claimed were a secret UN or government force watching citizens; "black ___".', a: 'Birds', category: 'urban-legend', difficulty: 4, alt: ['Helicopters'] },
      { q: 'The Belgian region saw a famous 1989-90 triangular-craft flap, with thousands of witnesses and even fighter-jet radar locks; this Western European country\'s name.', a: 'Belgium', category: 'ufo', difficulty: 4 },
      { q: 'A shadowy ruling clique that QAnon and similar movements believe secretly controls governments and media from behind the scenes.', a: 'Backroom cabal', category: 'secret-society', difficulty: 3, alt: ['Cabal'] },
      { q: 'The high-altitude floating craft the US Air Force said was the real Roswell debris, part of the secret Project Mogul programme; a weather ___.', a: 'Balloon', category: 'government', difficulty: 3 },
      { q: 'A hairy ape-like cryptid of the Himalayas and a similar one in the Pacific Northwest are evidence-free "missing links"; the catch-all for a creature reported but never proven.', a: 'Beast', category: 'cryptid', difficulty: 2 },
      { q: 'A close-knit fraternal order bound by secret oaths, like the Freemasons; the word for such a sworn band of "brothers".', a: 'Brotherhood', category: 'secret-society', difficulty: 2 },
    ],
    C: [
      { q: 'The real, declassified FBI programme that secretly surveilled and disrupted activist groups in the 1950s-70s.', a: 'COINTELPRO', category: 'government', difficulty: 4 },
      { q: 'The carved stone humanoid unearthed in upstate New York in 1869, one of America\'s most famous archaeological frauds, named for a Welsh town.', a: 'Cardiff Giant', category: 'hoax', difficulty: 4 },
      { q: 'The 1917 photographs of small winged sprites taken by two English girls, exposed decades later as cardboard cut-outs; the ___ Fairies.', a: 'Cottingley', category: 'hoax', difficulty: 4 },
      { q: 'Paid performers a fringe claim says are secretly hired to fake victims and grief at staged disasters; the two-word phrase for these supposed paid mourners.', a: 'Crisis actors', category: 'urban-legend', difficulty: 3 },
      { q: 'The blood-sucking creature of Latin American legend whose name means "goat-sucker".', a: 'Chupacabra', category: 'cryptid', difficulty: 2 },
      { q: 'A coded message or scrambled text, like those the unidentified San Francisco killer sent to newspapers in the late 1960s.', a: 'Cipher', category: 'urban-legend', difficulty: 3 },
      { q: 'The secret inner ring of powerful people said to pull the strings of governments and banks; a synonym for a shadowy ruling clique.', a: 'Cabal', category: 'secret-society', difficulty: 2 },
      { q: 'A tightly bonded fringe religious group under a charismatic leader, like the one that died at Jonestown; the word for such a sect.', a: 'Cult', category: 'urban-legend', difficulty: 2 },
      { q: 'The harmless white condensation streaks behind jet engines, mistaken by some for deliberate toxic spraying; the "con___".', a: 'Contrails', category: 'urban-legend', difficulty: 3 },
      { q: 'The 1980 official US Air Force report dismissing the Bentwaters UFO event was kept brief; this two-word term means hiding the truth from the public.', a: 'Cover-up', category: 'government', difficulty: 2 },
      { q: 'The 1947 New Mexico debris field is, for believers, the all-time famous saucer ___; the everyday word for a vehicle smashing to the ground.', a: 'Crash', category: 'ufo', difficulty: 2 },
    ],
    D: [
      { q: 'Colorado\'s sprawling main air hub, subject of theories about underground bunkers and apocalyptic murals.', a: 'Denver Airport', category: 'urban-legend', difficulty: 3 },
      { q: 'The phrase for an alleged shadowy network of permanent officials said to secretly run the government regardless of elections.', a: 'Deep State', category: 'government', difficulty: 2 },
      { q: 'The codename of the anonymous Watergate source who guided two reporters, revealed decades later to be FBI man Mark Felt.', a: 'Deep Throat', category: 'government', difficulty: 3 },
      { q: 'A fringe belief, popularised online, that the giant prehistoric reptiles never existed and their fossils are a museum fabrication.', a: 'Dinosaur hoax', category: 'hoax', difficulty: 4 },
      { q: 'The fabled invisible-energy weapon attributed to inventor Nikola Tesla, said to be suppressed by governments; a "death ___".', a: 'Device', category: 'government', difficulty: 4, alt: ['Ray'] },
      { q: 'A long, snake-like creature, like the one supposedly seen in deep Scottish lochs; the basic cryptid "type" that lake monsters belong to, a serpent or sea ___.', a: 'Dragon', category: 'cryptid', difficulty: 3 },
      { q: 'The Dallas public square where President Kennedy was shot in 1963, overlooked by a grassy knoll and a book depository.', a: 'Dealey Plaza', category: 'assassination', difficulty: 3 },
      { q: 'The deliberate spreading of false information by a government or group to mislead the public; a darker cousin of mere rumour.', a: 'Disinformation', category: 'government', difficulty: 3 },
      { q: 'The end-of-the-world prophecy tied to Nibiru and the misread 2012 Maya calendar; a "___ scenario".', a: 'Doomsday', category: 'paranormal', difficulty: 2 },
      { q: 'The nine ill-fated hikers who froze on a slope in Russia\'s Ural mountains in 1959, with a slashed tent and strange injuries; their leader Igor lent his surname to this two-word mountain mystery.', a: 'Dyatlov Pass', category: 'paranormal', difficulty: 3 },
      { q: 'A self-published creator of conspiracy videos or forum posts, who pieces together "the truth" the mainstream supposedly hides; a fringe online ___.', a: 'Debunker', category: 'urban-legend', difficulty: 3 },
      { q: 'A classified location, blacked out on maps, where governments allegedly hide craft or hold prisoners; an off-the-books "black ___".', a: 'Detention site', category: 'government', difficulty: 3, alt: ['Black site'] },
    ],
    E: [
      { q: 'The broad term for beings from other worlds, the subject of most UFO lore.', a: 'Extraterrestrials', category: 'ufo', difficulty: 2 },
      { q: 'The 2013 leaker of NSA mass-surveillance documents, who fled and was granted asylum in Russia.', a: 'Edward Snowden', category: 'government', difficulty: 3 },
      { q: 'The author whose 1968 book "Chariots of the Gods?" launched the ancient-aliens craze; his full German name.', a: 'Erich von Daniken', category: 'ufo', difficulty: 4 },
      { q: 'The financier whose 2019 jail death by apparent suicide fuelled a viral "he didn\'t kill himself" meme.', a: 'Epstein', category: 'urban-legend', difficulty: 3, alt: ['Jeffrey Epstein'] },
      { q: 'The catch-all word for proof, the thing conspiracy theorists say is always being suppressed or hidden.', a: 'Evidence', category: 'urban-legend', difficulty: 1 },
      { q: 'In UFO lore, "of the third kind" describes meeting an alien directly; the general word for such close meetings with beings from space.', a: 'Encounters', category: 'ufo', difficulty: 3 },
      { q: 'The single all-seeing symbol in a triangle on the dollar bill, taken by some as a sign of Masonic power; the "all-seeing ___".', a: 'Eye', category: 'secret-society', difficulty: 2 },
      { q: 'Conspiracy theory holds our home planet is hollow with an inhabited interior; the famous "hollow ___" idea names the third rock from the Sun.', a: 'Earth', category: 'paranormal', difficulty: 2 },
      { q: 'A staged provocation that justifies a desired political response; theorists call a faked attack an "engineered ___".', a: 'Escalation', category: 'government', difficulty: 4 },
      { q: 'A person who claims to have been taken aboard an alien craft and examined, then returned, is said to have had an "alien ___" experience.', a: 'Examination', category: 'ufo', difficulty: 3 },
    ],
    F: [
      { q: 'The world\'s oldest and largest fraternal order, with lodges, aprons and secret handshakes, often linked to elite-control theories.', a: 'Freemasons', category: 'secret-society', difficulty: 2 },
      { q: 'A staged event meant to look as if an enemy carried it out, blamed by theorists for many attacks; a "false ___" operation.', a: 'Flag', category: 'government', difficulty: 3, alt: ['False Flag'] },
      { q: 'The naturally occurring compound added to drinking water that some claim is a scheme to sedate citizens.', a: 'Fluoride', category: 'urban-legend', difficulty: 3 },
      { q: 'The pilot Kenneth Arnold\'s 1947 sighting of nine objects near Mount Rainier coined this two-word term for a disc-shaped craft.', a: 'Flying Saucer', category: 'ufo', difficulty: 3 },
      { q: 'The 1995 leaked black-and-white film purporting to show a doctor cutting open a Roswell extraterrestrial, later admitted to be staged; the "alien ___" hoax.', a: 'Footage', category: 'hoax', difficulty: 4, alt: ['Autopsy'] },
      { q: 'A made-up or invented story passed off as real, like the carved Cardiff Giant or the bat-men-on-the-Moon news; a deliberate ___.', a: 'Fabrication', category: 'hoax', difficulty: 2 },
      { q: 'The US Bureau of Investigation that ran the COINTELPRO surveillance programme; its three-letter name.', a: 'FBI', category: 'government', difficulty: 2 },
      { q: 'The covert money said to bankroll secret programmes, hidden in unaccountable government budgets; "black ___".', a: 'Funding', category: 'government', difficulty: 3 },
      { q: 'The hidden file or dossier a government supposedly keeps on a citizen or on UFO cases, locked away in a "secret ___".', a: 'Folder', category: 'government', difficulty: 3, alt: ['File'] },
    ],
    G: [
      { q: 'A real Cold-War US Army effort studied psychic "remote viewing"; this hooved farm beast featured in the film about men who stare at them.', a: 'Goats', category: 'government', difficulty: 4 },
      { q: 'The grassy mound in Dealey Plaza from which theorists believe a second gunman fired at Kennedy; the "grassy ___".', a: 'Gunner\'s knoll', category: 'assassination', difficulty: 3, alt: ['Grassy Knoll'] },
      { q: 'A dismissive 1960s nickname for secretive Swiss bankers said to manipulate world currency from Zurich; the "___ of Zurich".', a: 'Gnomes', category: 'secret-society', difficulty: 4 },
      { q: 'The all-seeing single eye in a triangle, taken by theorists as proof of secret influence; the "___ of Providence".', a: 'Gaze', category: 'secret-society', difficulty: 4, alt: ['Eye'] },
      { q: 'A West Virginia cryptid, a faceless white creature reported in 1964, less famous than its winged red-eyed neighbour, named for the small town where it was seen.', a: 'Grafton Monster', category: 'cryptid', difficulty: 5 },
      { q: 'A hidden global financial-control idea centres on this Swiss city\'s banks and the secretive trade meetings held there.', a: 'Geneva', category: 'secret-society', difficulty: 4 },
      { q: 'The fenced US naval base in Cuba, scene of detainee and "black site" allegations; nicknamed "Gitmo".', a: 'Guantanamo Bay', category: 'government', difficulty: 3 },
      { q: 'The 17th-century failed plot to blow up the English Parliament, marked each November the fifth; the conspirator named here is the cellar guard, ___ Fawkes.', a: 'Guy', category: 'secret-society', difficulty: 3, alt: ['Guy Fawkes'] },
      { q: 'The unseen shadowy figure conspiracy theorists picture pulling the strings of governments and markets; a "___ controller" behind the scenes.', a: 'Globalist', category: 'secret-society', difficulty: 3 },
    ],
    H: [
      { q: 'The Alaska-based atmospheric research array conspiracy theorists wrongly accuse of controlling the weather and minds.', a: 'HAARP', category: 'government', difficulty: 3 },
      { q: 'The theory that our planet is not solid but contains a vast inhabited interior, reached through polar openings.', a: 'Hollow Earth', category: 'paranormal', difficulty: 3 },
      { q: 'A deliberate trick or fabrication designed to deceive the public, like the carved Cardiff Giant of 1869.', a: 'Hoax', category: 'hoax', difficulty: 1 },
      { q: 'The 1955 Kentucky farmhouse "siege" by little silver goblins is named for this town and led to the little-green-men legend.', a: 'Hopkinsville', category: 'ufo', difficulty: 5 },
      { q: 'The unmarked dark aircraft of 1990s militia lore, said to be a covert UN or government force surveilling citizens; "black ___".', a: 'Helicopters', category: 'urban-legend', difficulty: 3 },
      { q: 'The 1937 disaster of a German airship bursting into flame at Lakehurst spawned sabotage theories; that doomed hydrogen craft\'s name.', a: 'Hindenburg', category: 'government', difficulty: 4 },
      { q: 'A spooky residence where ghosts supposedly dwell, the setting of countless paranormal investigations; a "___ house".', a: 'Haunted', category: 'paranormal', difficulty: 2 },
      { q: 'The 1947 wave of nine objects spotted near Mount Rainier popularised the saucer; the witness pilot was Kenneth Arnold, but name simply the great commotion such a scare causes; a media "___".', a: 'Hysteria', category: 'urban-legend', difficulty: 3 },
      { q: 'A government\'s standard "neither confirm nor deny" reply, a stonewalling answer theorists take as proof of secrets; a famously evasive ___.', a: 'Hedge', category: 'government', difficulty: 4 },
    ],
    I: [
      { q: 'Conspiracy lore claims tiny tracking chips are secretly injected via vaccines; these embedded devices are called micro___.', a: 'Implants', category: 'urban-legend', difficulty: 3 },
      { q: 'The act of placing a hidden agent inside a group to spy or stir trouble, as the FBI did under COINTELPRO.', a: 'Infiltration', category: 'government', difficulty: 3 },
      { q: 'The general term for people who claim to have secret knowledge of how power really works; the opposite of outsiders.', a: 'Insiders', category: 'secret-society', difficulty: 2 },
      { q: 'The hidden hand said to guide markets and history, often called an "invisible ___" by theorists.', a: 'Influence', category: 'secret-society', difficulty: 3 },
      { q: 'A person who claims first-hand contact with aliens or hidden agencies, offering testimony but no proof.', a: 'Informant', category: 'government', difficulty: 3 },
      { q: 'The general term for the spy agencies at the heart of cover-up theories, the "___ community".', a: 'Intelligence', category: 'government', difficulty: 2 },
      { q: 'A staged event that triggers a desired political reaction by deception; an engineered "___".', a: 'Incident', category: 'government', difficulty: 3 },
      { q: 'The official process of probing a UFO case or cover-up to find buried facts; the FBI or Air Force opens a formal ___ into the matter.', a: 'Investigation', category: 'government', difficulty: 2 },
      { q: 'The secret enlightened order founded in Bavaria in 1776 inspired the modern myth of hidden rulers; the everyday word for being shown the secret light or knowledge.', a: 'Initiation', category: 'secret-society', difficulty: 3 },
    ],
    J: [
      { q: 'A winged, hoofed cryptid said to haunt the Pine Barrens of a US Garden State, born of legend to Mother Leeds.', a: 'Jersey Devil', category: 'cryptid', difficulty: 3 },
      { q: 'The cult leader whose followers died by poisoned drink in 1978 Guyana, source of the phrase "drinking the Kool-Aid"; his full name.', a: 'Jim Jones', category: 'urban-legend', difficulty: 3 },
      { q: 'The Guyana settlement where over 900 cult members died in 1978, feeding CIA mind-control rumours.', a: 'Jonestown', category: 'urban-legend', difficulty: 4 },
      { q: 'The financier accused of running an abuse ring, whose 2019 cell death is disputed; his first name.', a: 'Jeffrey', category: 'urban-legend', difficulty: 3, alt: ['Jeffrey Epstein'] },
      { q: 'The professional skeptic and stage magician, born Zwinge, who debunked psychics and offered a million-dollar prize for proof of the paranormal.', a: 'James Randi', category: 'paranormal', difficulty: 4 },
      { q: 'The nightclub owner who shot Lee Harvey Oswald on live television in 1963; his first name.', a: 'Jack', category: 'assassination', difficulty: 3, alt: ['Jack Ruby'] },
      { q: 'The WikiLeaks founder, an Australian, who published vast troves of leaked classified files and spent years sheltering in Ecuador\'s London embassy; his full name.', a: 'Julian Assange', category: 'government', difficulty: 3 },
      { q: 'The mythical horned rabbit of American tall tales, sold as a taxidermy hoax to gullible tourists in the West; a "warrior rabbit" made by gluing antlers on a hare.', a: 'Jackalope', category: 'hoax', difficulty: 4 },
    ],
    K: [
      { q: 'The medieval warrior-monk order, suppressed in 1307, that lives on in Holy-Grail and treasure lore.', a: 'Knights Templar', category: 'secret-society', difficulty: 2 },
      { q: 'The director of "2001: A Space Odyssey" whom moon-hoax believers claim secretly filmed the fake lunar footage.', a: 'Kubrick', category: 'hoax', difficulty: 3, alt: ['Stanley Kubrick'] },
      { q: 'The president shot in Dallas in 1963, the most theorised assassination in history; his surname.', a: 'Kennedy', category: 'assassination', difficulty: 2, alt: ['John F. Kennedy'] },
      { q: 'The poisoned soft-drink powder darkly associated with the 1978 Guyana cult deaths; to "drink the ___".', a: 'Kool-Aid', category: 'urban-legend', difficulty: 3 },
      { q: 'The white-hooded secret society of the American South, infamous for terror and cross-burnings; abbreviated KKK.', a: 'Ku Klux Klan', category: 'secret-society', difficulty: 2 },
      { q: 'A serpent cryptid of Canada\'s Okanagan and similar lakes; the Scottish water-horse of folklore lends this name.', a: 'Kelpie', category: 'cryptid', difficulty: 4 },
      { q: 'The hidden secret a society guards, the prize a conspiracy theorist claims to seek; secret orders promise their initiates forbidden ___.', a: 'Knowledge', category: 'secret-society', difficulty: 2 },
    ],
    L: [
      { q: 'The David Icke theory that shape-shifting reptilian beings disguised as elites secretly rule humanity.', a: 'Lizard People', category: 'paranormal', difficulty: 2, alt: ['Reptilians'] },
      { q: 'The accused 1963 presidential gunman, shot dead by Jack Ruby before he could stand trial; his full name.', a: 'Lee Harvey Oswald', category: 'assassination', difficulty: 3 },
      { q: 'The fabled lost continent said by occultists to have sunk beneath the Indian or Pacific ocean, a cousin of Atlantis.', a: 'Lemuria', category: 'paranormal', difficulty: 4 },
      { q: 'A 19th-century newspaper fabrication described bat-winged beings on the Moon spotted by a telescope; the Great Moon ___.', a: 'Lunar hoax', category: 'hoax', difficulty: 4 },
      { q: 'The meeting place of a Masonic chapter, where the brotherhood holds its secret rituals.', a: 'Lodge', category: 'secret-society', difficulty: 2 },
      { q: 'The unauthorised release of secret documents to the press, as with the Pentagon Papers or the Snowden files; a "___" of classified files.', a: 'Leak', category: 'government', difficulty: 2 },
      { q: 'The 1908 Siberian blast over the Stony Tunguska river flattened a forest; this US-state-sized term means the destruction reached for many miles in every direction; over a vast ___ of trees fell.', a: 'Landscape', category: 'paranormal', difficulty: 3 },
      { q: 'The Bavarian secret order founded in 1776 by Adam Weishaupt sits at the heart of the "hidden rulers" myth; name the act of bringing hidden truth into the open, the opposite of a cover-up.', a: 'Light', category: 'secret-society', difficulty: 2 },
    ],
    M: [
      { q: 'The CIA\'s real, declassified 1950s-60s program of illegal mind-control experiments using drugs like LSD.', a: 'MKUltra', category: 'government', difficulty: 3 },
      { q: 'The red-eyed winged cryptid sighted in Point Pleasant, West Virginia, before a 1967 bridge collapse.', a: 'Mothman', category: 'cryptid', difficulty: 2 },
      { q: 'The effect where large groups vividly share a false memory, named after a South African leader\'s wrongly-remembered prison death.', a: 'Mandela effect', category: 'paranormal', difficulty: 3 },
      { q: 'The real CIA effort to influence journalists and news outlets in the Cold War, codenamed for a bird; Operation ___.', a: 'Mockingbird', category: 'government', difficulty: 4, alt: ['Operation Mockingbird'] },
      { q: 'The 1947 New Mexico rancher who found the strange debris that launched the famous saucer-crash story; the foreman\'s surname.', a: 'Mac Brazel', category: 'ufo', difficulty: 5, alt: ['Brazel'] },
      { q: 'The brainwashed-assassin film whose title became shorthand for a programmed killer; "The ___ Candidate".', a: 'Manchurian', category: 'government', difficulty: 3 },
      { q: 'The general practice of controlling people\'s thoughts and behaviour against their will, the goal of the CIA\'s MKUltra; "mind ___".', a: 'Manipulation', category: 'government', difficulty: 2 },
      { q: 'The 1938 Orson Welles radio drama dramatising H.G. Wells caused a famous panic; this red neighbour planet was the invaders\' supposed home world.', a: 'Mars', category: 'hoax', difficulty: 3 },
      { q: 'A staged mass tragedy that conspiracy theorists falsely claim was performed by paid actors; a "___ shooting" hoax claim.', a: 'Manufactured', category: 'urban-legend', difficulty: 3 },
      { q: 'The fringe doctrine that humanity will be reduced in number by a secret elite via disease or famine; the dreaded "great ___" plan.', a: 'Massacre', category: 'urban-legend', difficulty: 4, alt: ['Depopulation'] },
    ],
    N: [
      { q: 'The phrase for an alleged single planet-wide authoritarian government that theorists fear will replace all nations; abbreviated NWO.', a: 'New World Order', category: 'secret-society', difficulty: 2 },
      { q: 'The hypothetical rogue planet, drawn from Zecharia Sitchin\'s writings, predicted to swing by and devastate the Earth.', a: 'Nibiru', category: 'paranormal', difficulty: 3 },
      { q: 'The president forced to resign in 1974 after a cover-up of a break-in at Democratic headquarters; his surname.', a: 'Nixon', category: 'government', difficulty: 2, alt: ['Richard Nixon'] },
      { q: 'The US agency exposed for bulk telephone and internet surveillance by a 2013 leak; its three-letter name.', a: 'NSA', category: 'government', difficulty: 2 },
      { q: 'Under Operation Paperclip the US secretly recruited rocket experts who had served this defeated WWII German regime; its four-letter party name.', a: 'Nazi recruits', category: 'government', difficulty: 3 },
      { q: 'The undiscovered world some astronomers hypothesise far beyond Neptune, conflated by doomsday fans with rogue Nibiru and "Planet X"; spell out the lone digit in "Planet ___".', a: 'Nine', category: 'paranormal', difficulty: 4 },
      { q: 'The US eavesdropping body nicknamed "No Such Body", revealed in 2013 to be vacuuming up the world\'s phone and internet traffic; spell out its three-letter abbreviation in full.', a: 'National Security Agency', category: 'government', difficulty: 3 },
    ],
    O: [
      { q: 'The talking spirit-tablet with letters and a planchette that supposedly lets the dead spell out messages.', a: 'Ouija board', category: 'paranormal', difficulty: 2 },
      { q: 'The lake monster of British Columbia\'s Okanagan, Canada\'s most famous water cryptid.', a: 'Ogopogo', category: 'cryptid', difficulty: 4 },
      { q: 'The general word for a coordinated secret mission by intelligence or military bodies, the head-noun of many code names like Mockingbird and Paperclip.', a: 'Operation', category: 'government', difficulty: 1 },
      { q: 'The accused assassin of President Kennedy, killed two days later by Jack Ruby; his surname.', a: 'Oswald', category: 'assassination', difficulty: 3, alt: ['Lee Harvey Oswald'] },
      { q: 'The classified high-altitude reconnaissance flights of the 1950s, like the U-2, often mistaken for craft from another world; covert "___ flights".', a: 'Overflight', category: 'government', difficulty: 4 },
      { q: 'The pervasive watching of citizens that surveillance theories warn of; an all-seeing "Big Brother" society practises constant ___.', a: 'Observation', category: 'government', difficulty: 2 },
      { q: 'The English air bases RAF Bentwaters and RAF Woodbridge sat beside the 1980 Rendlesham UFO site; name the broad spread of woodland and heath, the open ___, around them.', a: 'Outdoors', category: 'ufo', difficulty: 4 },
      { q: 'A sworn written statement an insider files to expose wrongdoing; whistleblower testimony in a cover-up case is often submitted as a legal ___.', a: 'Oath', category: 'government', difficulty: 3 },
      { q: 'The 1938 radio drama by Orson Welles dramatising a Martian invasion sparked a famous public panic in the tenth month of the year; name that autumn month.', a: 'October', category: 'hoax', difficulty: 4 },
    ],
    P: [
      { q: 'The real WWII operation that smuggled German rocket scientists like Wernher von Braun into the US, named for an office supply.', a: 'Paperclip', category: 'government', difficulty: 3, alt: ['Operation Paperclip'] },
      { q: 'The 1971 leak of a secret Vietnam-War study exposing government deception; the Pentagon ___.', a: 'Papers', category: 'government', difficulty: 4, alt: ['Pentagon Papers'] },
      { q: 'The alleged 1943 US Navy invisibility-and-teleportation test of a warship in a dockyard, named for a Pennsylvania city.', a: 'Philadelphia Experiment', category: 'government', difficulty: 3 },
      { q: 'The 1947 New Mexico debris was secretly a spy device to detect Soviet nuclear tests; this classified balloon-train programme\'s codename.', a: 'Project Mogul', category: 'government', difficulty: 4, alt: ['Mogul'] },
      { q: 'A ghostly apparition or spirit said to manifest in haunted places; the paranormal sense of a "spectral ___".', a: 'Phantom', category: 'paranormal', difficulty: 2 },
      { q: 'The fringe belief that crisis-actors stage tragedies and no one was really hurt; such events are dismissed as elaborate "___".', a: 'Productions', category: 'urban-legend', difficulty: 4 },
      { q: 'A secret scheme or covert design by a group to commit a wrong, the very thing a conspiracy theory alleges; to "hatch a ___".', a: 'Plot', category: 'urban-legend', difficulty: 1 },
      { q: 'A self-styled gifted person who claims to read minds or contact the dead, often exposed by the skeptic James Randi.', a: 'Psychic', category: 'paranormal', difficulty: 2 },
      { q: 'The hard ridges of the Giza monuments built by Khufu\'s workers, but credited by ancient-alien theorists to visitors from space; the great Egyptian ___.', a: 'Pyramids', category: 'ufo', difficulty: 2 },
      { q: 'The biased, often-false messaging a state pushes to shape public opinion, which Operation Mockingbird allegedly planted in the press; wartime "___ posters" are a classic example.', a: 'Propaganda', category: 'government', difficulty: 2 },
    ],
    Q: [
      { q: 'The sprawling internet movement that grew from anonymous "drop" posts claiming a secret battle against a cabal.', a: 'QAnon', category: 'urban-legend', difficulty: 2 },
      { q: 'The act of doubting an official account and demanding hidden truth, the mindset behind "do your own research".', a: 'Questioning', category: 'urban-legend', difficulty: 2 },
      { q: 'The hush money or enforced silence demanded to keep a cover-up buried; to keep a witness ___.', a: 'Quiet', category: 'government', difficulty: 3 },
      { q: 'A swampy word meaning a hopeless, murky mess; the anonymous "Q" online movement descended into exactly such a ___.', a: 'Quagmire', category: 'urban-legend', difficulty: 4 },
      { q: 'A secret search or investigation into hidden truths; conspiracy researchers see themselves on a ___ for buried facts.', a: 'Quest', category: 'secret-society', difficulty: 4 },
      { q: 'To forcibly put down a riot or uprising, which a "false flag" might be staged to justify; to ___ unrest.', a: 'Quell', category: 'government', difficulty: 5 },
      { q: 'The enforced isolation of the sick that lockdown-conspiracy theorists recast as a sinister tool of control; an imposed medical ___.', a: 'Quarantine', category: 'urban-legend', difficulty: 3 },
    ],
    R: [
      { q: 'The wealthy European banking dynasty endlessly accused of secretly controlling the world\'s finances.', a: 'Rothschilds', category: 'secret-society', difficulty: 2 },
      { q: 'The David-Icke shape-shifting alien-overlord beings, said to hide among the elite as "lizard people".', a: 'Reptilians', category: 'paranormal', difficulty: 2 },
      { q: 'The 1980 UFO incident in an English woodland near two US air bases, dubbed "Britain\'s Roswell"; the Suffolk site\'s name.', a: 'Rendlesham Forest', category: 'ufo', difficulty: 4 },
      { q: 'The nightclub owner who shot Lee Harvey Oswald on live television in 1963; his surname.', a: 'Ruby', category: 'assassination', difficulty: 3, alt: ['Jack Ruby'] },
      { q: 'The psychic skill the US Stargate Project studied: the alleged power to perceive a faraway, unseen location using only the mind, from afar.', a: 'Remote viewing', category: 'government', difficulty: 4 },
      { q: 'The lost English colony on this island off North Carolina vanished by 1590, leaving only the carved word "Croatoan".', a: 'Roanoke', category: 'urban-legend', difficulty: 3 },
      { q: 'A widely shared but unverified story, the lifeblood of conspiracy culture; an unconfirmed claim passed person to person.', a: 'Rumour', category: 'urban-legend', difficulty: 1, alt: ['Rumor'] },
      { q: 'The invisible beams that tinfoil-hat lore claims are aimed at the public to read or control their minds; harmful "mind ___".', a: 'Rays', category: 'urban-legend', difficulty: 3 },
    ],
    S: [
      { q: 'The secretive Yale undergraduate society whose members reportedly include presidents and spymasters.', a: 'Skull and Bones', category: 'secret-society', difficulty: 3 },
      { q: 'The contested 1967 home movie by Patterson and Gimlin appearing to show a striding Bigfoot; such grainy proof a believer offers is a single fuzzy ___ of the creature.', a: 'Snapshot', category: 'cryptid', difficulty: 3 },
      { q: 'The author Zecharia of this surname read ancient texts to claim a rogue planet and alien gods; he popularised Nibiru.', a: 'Sitchin', category: 'paranormal', difficulty: 4 },
      { q: 'The famous 1934 image that seemed to show the Loch Ness Monster\'s head and neck, faked with a toy on a model and credited to an unnamed doctor; the "___ Picture", named for that medical man\'s job.', a: 'Surgeon\'s Photo', category: 'hoax', difficulty: 4, alt: ['Surgeon\'s Photograph'] },
      { q: 'The thin shiny metal headgear, worn half-jokingly to "block" mind rays; a tinfoil version of this.', a: 'Sheet hat', category: 'urban-legend', difficulty: 3 },
      { q: 'The covert monitoring of people\'s movements and messages by the state, exposed on a vast scale by the 2013 NSA leaks.', a: 'Surveillance', category: 'government', difficulty: 2 },
      { q: 'A long, snake-like creature said to swim in deep lochs and seas, the basic type that Nessie belongs to; a "lake ___".', a: 'Serpent', category: 'cryptid', difficulty: 3 },
      { q: 'A clandestine fraternal organisation with hidden rituals and oaths, like the Freemasons or Skull and Bones; the genre of this whole pack.', a: 'Secret society', category: 'secret-society', difficulty: 1 },
      { q: 'A person who undertakes covert intelligence work for a government, gathering hidden information; an undercover agent.', a: 'Spy', category: 'government', difficulty: 1 },
      { q: 'The fringe claim that powerful interests hide cures or clean-energy inventions to protect profits; the alleged "___ of technology".', a: 'Suppression', category: 'government', difficulty: 3 },
      { q: 'The reflective metal headgear worn half-jokingly to block "mind rays"; foil shaped into a protective ___ for the head.', a: 'Shield', category: 'urban-legend', difficulty: 2 },
    ],
    T: [
      { q: 'The massive 1908 Siberian forest explosion, likely a meteor air-burst, that fuels alien and death-ray theories.', a: 'Tunguska event', category: 'paranormal', difficulty: 3 },
      { q: 'The slang protective hat made of metal foil, worn by those fearing the government reads their thoughts.', a: 'Tinfoil hat', category: 'urban-legend', difficulty: 2 },
      { q: 'The inventor and free-energy pioneer whose "death ray" and wireless-power ideas feed suppressed-technology theories; his surname.', a: 'Tesla', category: 'government', difficulty: 3, alt: ['Nikola Tesla'] },
      { q: 'The Knights of this medieval crusading order were crushed by France in 1307 and live on in Grail and treasure lore.', a: 'Templar', category: 'secret-society', difficulty: 3, alt: ['Knights Templar'] },
      { q: 'A staged event meant to be blamed on an opponent, the core idea behind a "false flag"; an act of deception or ___.', a: 'Trickery', category: 'government', difficulty: 3 },
      { q: 'A government-employed agent who secretly betrays their own side, the villain of many spy and cover-up tales; one guilty of treason.', a: 'Traitor', category: 'government', difficulty: 2 },
      { q: 'The witness or insider who tells the hidden facts under oath; sworn courtroom or hearing evidence is called this.', a: 'Testimony', category: 'government', difficulty: 2 },
      { q: 'The Babylonian creator deity, slain in myth to form the heavens, after whom Sitchin\'s rogue planet collision is sometimes named.', a: 'Tiamat', category: 'paranormal', difficulty: 5 },
      { q: 'An unproven idea offered to explain hidden causes of events; the suffix-word in "conspiracy ___".', a: 'Theory', category: 'urban-legend', difficulty: 1 },
      { q: 'The three-sided ocean region off Florida and Bermuda where ships and planes supposedly vanish; the geometric shape that names it.', a: 'Triangle', category: 'paranormal', difficulty: 2 },
    ],
    U: [
      { q: 'The newer official US government term for unexplained aerial sightings, replacing the old saucer label; the acronym.', a: 'UAP', category: 'ufo', difficulty: 3 },
      { q: 'A vast network of secret tunnels and bases, like those rumoured beneath Denver Airport; "___ bunkers".', a: 'Underground', category: 'urban-legend', difficulty: 2 },
      { q: 'The all-seeing eye and pyramid imagery feed a fear of one merged world authority; a single "___ government".', a: 'Unified', category: 'secret-society', difficulty: 3 },
      { q: 'A creature or event for which no scientific explanation yet exists, the broad category covering cryptids and ghosts; the ___.', a: 'Unexplained', category: 'paranormal', difficulty: 2 },
      { q: 'A widely circulated modern folk tale, often scary or cautionary and untrue, like the vanishing hitchhiker; a city-dwellers\' ___.', a: 'Urban legend', category: 'urban-legend', difficulty: 2 },
      { q: 'The 2017 New York Times disclosure of a secret Pentagon programme studying strange aerial sightings stunned the public; such sightings stay officially "___".', a: 'Unconfirmed', category: 'ufo', difficulty: 3 },
      { q: 'The hidden labyrinth of tunnels and chambers theorists imagine beneath Denver Airport and military sites; built far below the surface, an "___ complex".', a: 'Underworld', category: 'urban-legend', difficulty: 3 },
    ],
    V: [
      { q: 'The German rocket engineer Wernher of this surname, brought to the US under Operation Paperclip after building the Nazi V-2; he later led NASA\'s Moon programme.', a: 'Von Braun', category: 'government', difficulty: 4 },
      { q: 'A fringe claim holds that injected immunisations secretly carry tracking microchips; name the needle-delivered jab itself.', a: 'Vaccine', category: 'urban-legend', difficulty: 3 },
      { q: 'A faint ghostly form or appearance of a dead person seen in a haunted place; a spectral ___.', a: 'Vision', category: 'paranormal', difficulty: 3, alt: ['Apparition'] },
      { q: 'The supposed silencing of a witness or whistleblower to prevent disclosure; to "make someone ___" or disappear.', a: 'Vanish', category: 'government', difficulty: 4 },
      { q: 'A blood-drinking undead of folklore, linked by some to real "exhumed corpse" panics in 18th-century Europe; a creature warded off by garlic.', a: 'Vampire', category: 'urban-legend', difficulty: 2 },
      { q: 'The tiny city-state whose "Secret Archive" of locked papal documents fuels endless theories about hidden Church knowledge; the seat of the pope.', a: 'Vatican', category: 'secret-society', difficulty: 3 },
    ],
    W: [
      { q: 'The 1972 break-in and cover-up scandal at a Washington office complex that toppled President Nixon.', a: 'Watergate', category: 'government', difficulty: 2 },
      { q: 'A person who exposes secret wrongdoing inside an organisation, like Edward Snowden or Mark Felt.', a: 'Whistleblower', category: 'government', difficulty: 2 },
      { q: 'The Alaska array HAARP is accused of using to manipulate the climate; the supposed control of rain and storms is "___ modification".', a: 'Weather', category: 'government', difficulty: 3 },
      { q: 'The science-fiction radio drama by Orson Welles that triggered the 1938 invasion panic; "The ___ of the Worlds".', a: 'War', category: 'hoax', difficulty: 3 },
      { q: 'A mythical hairy giant of forests worldwide; the umbrella term for Bigfoot, Yeti and Sasquatch sightings is the "___ man".', a: 'Wild', category: 'cryptid', difficulty: 2 },
      { q: 'The organisation founded by Julian Assange that published vast troves of classified diplomatic and military files in 2010.', a: 'WikiLeaks', category: 'government', difficulty: 3 },
      { q: 'A man who turns into a wolf under the full moon, a staple of European folklore and horror.', a: 'Werewolf', category: 'cryptid', difficulty: 2 },
      { q: 'A person who saw a UFO, a crash, or a crime and gives sworn testimony, the figure whom "men in black" lore says is silenced; a key trial ___.', a: 'Witness', category: 'urban-legend', difficulty: 2 },
    ],
    Y: [
      { q: 'The secretive society at this Connecticut university hosts the Skull and Bones order; its name.', a: 'Yale', category: 'secret-society', difficulty: 3 },
      { q: 'The hairy hominid cryptid of the Australian bush, that continent\'s answer to Bigfoot.', a: 'Yowie', category: 'cryptid', difficulty: 4 },
      { q: 'The single year, 2000, of a feared global computer-clock meltdown that some called an engineered panic; the "___ bug".', a: 'Y2K', category: 'urban-legend', difficulty: 3 },
      { q: 'The tabloid newspaper style famous for alien-baby and Bigfoot front pages; sensational gossip rags are this colour of journalism.', a: 'Yellow press', category: 'hoax', difficulty: 4 },
      { q: 'The video-sharing site flooded with conspiracy and UFO content, where many theories first go viral.', a: 'YouTube', category: 'urban-legend', difficulty: 2 },
      { q: 'A long, far-fetched and probably invented story, the kind a conspiracy buff spins at length; to "spin a ___".', a: 'Yarn', category: 'urban-legend', difficulty: 3 },
    ],
    Z: [
      { q: 'Abraham of this surname shot the home-movie footage that captured the 1963 Dallas presidential killing frame by frame.', a: 'Zapruder', category: 'assassination', difficulty: 3, alt: ['Zapruder film'] },
      { q: 'The unidentified 1968-69 serial murderer who taunted San Francisco newspapers with ciphers, sharing a name with the band of star signs.', a: 'Zodiac Killer', category: 'urban-legend', difficulty: 3 },
      { q: 'The author Sitchin\'s first name, who claimed ancient Sumerians knew of a hidden planet and alien gods.', a: 'Zecharia', category: 'paranormal', difficulty: 4 },
      { q: 'In "patient ___" and "ground ___", the single number that marks the origin point of an outbreak or blast, much sought in any cover-up.', a: 'Zero', category: 'government', difficulty: 3 },
      { q: 'A secret government collection of captured exotic or alien creatures would be a covert version of this animal-housing institution.', a: 'Zoo', category: 'cryptid', difficulty: 3 },
      { q: 'The dark fascination with reanimated corpses rising to feed, central to bioweapon-apocalypse fears; an undead ghoul of horror films.', a: 'Zombie', category: 'urban-legend', difficulty: 2 },
    ],
  },
};
