import type { RawPack } from '../core/packs';

export const conspiracyPack: RawPack = {
  id: 'conspiracy-theories',
  name: 'Conspiracy Theories',
  description: 'Secret societies, cover-ups, UFOs and the lore behind the legends.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '👁️',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: 'The remote Nevada US Air Force facility long rumoured to hold recovered alien craft.', a: 'Area 51', category: 'ufo', difficulty: 2 },
      { q: 'In Sumerian-myth-based fringe theories, the supposed ancient race from the skies said to have engineered humanity.', a: 'Anunnaki', category: 'ufo', difficulty: 3 },
      { q: 'The experience reported by people who claim a UFO took them aboard for examination.', a: 'Abduction', category: 'ufo', difficulty: 2 },
      { q: 'The 1940s nuclear weapons project at Los Alamos, the subject of many secrecy and cover-up claims.', a: 'Atomic bomb', category: 'government', difficulty: 2 },
      { q: 'The legendary sunken civilisation described by Plato, often tied to lost-technology and alien lore.', a: 'Atlantis', category: 'paranormal', difficulty: 2 },
      { q: 'The author Erich von Daniken argued visitors from space built the pyramids, in his "ancient ___" idea.', a: 'Astronauts', category: 'ufo', difficulty: 3 },
      { q: 'The classified high-altitude US spy plane often blamed for "saucer" sightings in the 1950s and 60s.', a: 'A-12 Oxcart', category: 'government', difficulty: 4 },
      { q: 'The Italian word, meaning "harvest", that names the supposed lost continent some occultists place in the Pacific; a cousin idea to Lemuria.', a: 'Avalon', category: 'paranormal', difficulty: 5 },
      { q: 'The Roswell debris was officially explained as the wreckage of one of these floating craft used for high-altitude spying.', a: 'Air balloon', category: 'government', difficulty: 3, alt: ['Weather balloon'] },
      { q: 'A person who claims to have been taken aboard a craft by non-human beings is called an alien ___.', a: 'Abductee', category: 'ufo', difficulty: 3 },
      { q: 'The supposed underground network of secret bases beneath the New Mexico desert, often linked to alien collaboration; the "___ base" myth.', a: 'Archuleta', category: 'ufo', difficulty: 5, alt: ['Dulce'] },
      { q: 'The killing of a prominent figure such as a president or leader, the deed at the centre of the Kennedy and Lincoln theories.', a: 'Assassination', category: 'assassination', difficulty: 2 },
      { q: 'The fringe field claiming visitors from space shaped early human history and built ancient monuments; the "ancient ___" theory.', a: 'Aliens', category: 'ufo', difficulty: 2 },
    ],
    B: [
      { q: 'The annual invite-only gathering of around 130 powerful politicians and financiers, rumoured to secretly steer world affairs.', a: 'Bilderberg Group', category: 'secret-society', difficulty: 3 },
      { q: 'The hairy ape-like cryptid said to roam the forests of the Pacific Northwest.', a: 'Bigfoot', category: 'cryptid', difficulty: 1 },
      { q: 'The notorious stretch of Atlantic ocean off Florida and Puerto Rico where ships and planes supposedly vanish.', a: 'Bermuda Triangle', category: 'paranormal', difficulty: 2 },
      { q: 'The exclusive Californian redwood camp where elite men hold a secret summer retreat with an owl-effigy ceremony.', a: 'Bohemian Grove', category: 'secret-society', difficulty: 3 },
      { q: 'The US Air Force\'s official 1952-1969 study of flying-saucer reports, codenamed for its colour and a kind of paper.', a: 'Blue Book', category: 'government', difficulty: 3 },
      { q: 'The phenomenon where large crowds misremember a fact the same way; also called the Mandela effect, but named here for a children\'s-book family.', a: 'Berenstain effect', category: 'paranormal', difficulty: 4, alt: ['Berenstein effect'] },
      { q: 'The financial dynasty other than the Rothschilds, founders of a London merchant bank that collapsed in 1995, often named in elite-money claims.', a: 'Barings', category: 'secret-society', difficulty: 5 },
      { q: 'The "men in ___" are the mysterious dark-suited agents said to intimidate UFO witnesses; the colour of their clothing.', a: 'Black', category: 'ufo', difficulty: 2 },
      { q: 'A purported deep-state plan to depopulate or sicken the public via the air is the core of the chemtrail and "biological ___" fears.', a: 'Bioweapon', category: 'urban-legend', difficulty: 3 },
      { q: 'The shadowy ruling clique that QAnon and other movements believe secretly controls governments and media from behind the scenes.', a: 'Backroom cabal', category: 'secret-society', difficulty: 3, alt: ['Cabal'] },
    ],
    C: [
      { q: 'The claim that the white trails left by aircraft are deliberate toxic spraying, not condensation.', a: 'Chemtrails', category: 'urban-legend', difficulty: 2 },
      { q: 'The blood-sucking creature of Latin American legend whose name means "goat-sucker".', a: 'Chupacabra', category: 'cryptid', difficulty: 2 },
      { q: 'The real, declassified FBI programme that secretly surveilled and disrupted activist groups in the 1950s-70s.', a: 'COINTELPRO', category: 'government', difficulty: 4 },
      { q: 'The US intelligence agency at the centre of countless mind-control and assassination theories, founded in 1947.', a: 'CIA', category: 'government', difficulty: 1 },
      { q: 'The carved stone humanoid unearthed in upstate New York in 1869, one of America\'s most famous archaeological frauds, named for a Welsh town.', a: 'Cardiff Giant', category: 'hoax', difficulty: 4 },
      { q: 'The 1947 wave of saucer reports popularised a Cold-War-era panic; this general state of public alarm shares its name with a "red ___".', a: 'Crisis', category: 'urban-legend', difficulty: 3 },
      { q: 'The geometric patterns flattened into fields overnight, claimed by some to be alien messages; the "crop ___".', a: 'Circles', category: 'paranormal', difficulty: 2 },
      { q: 'The secret inner ring of powerful people said to pull the strings of governments and banks; a synonym for a shadowy ruling clique.', a: 'Cabal', category: 'secret-society', difficulty: 2 },
      { q: 'A coded message or scrambled text, like those the unidentified San Francisco killer sent to newspapers in the late 1960s.', a: 'Cipher', category: 'urban-legend', difficulty: 3 },
      { q: 'The general act of concealing a crime or scandal from the public, the goal of every conspiracy in this pack; a "___-up".', a: 'Cover', category: 'government', difficulty: 1 },
      { q: 'A tightly bonded religious or fringe group under a charismatic leader, like the one that died at Jonestown; the word for such a sect.', a: 'Cult', category: 'urban-legend', difficulty: 2 },
      { q: 'The condensation streaks behind jet engines, mistaken by some for deliberate toxic spraying; the harmless white "con___".', a: 'Contrails', category: 'urban-legend', difficulty: 3 },
    ],
    D: [
      { q: 'Colorado\'s sprawling main hub, subject of theories about underground bunkers and apocalyptic murals.', a: 'Denver Airport', category: 'urban-legend', difficulty: 3 },
      { q: 'The phrase for an alleged shadowy network of permanent officials said to secretly run the government regardless of elections.', a: 'Deep State', category: 'government', difficulty: 2 },
      { q: 'The classic flying-saucer description: a metallic craft shaped like two plates joined rim to rim; a flying ___.', a: 'Disc', category: 'ufo', difficulty: 2 },
      { q: 'The codename of the anonymous Watergate source who guided two reporters, revealed decades later to be FBI man Mark Felt.', a: 'Deep Throat', category: 'government', difficulty: 3 },
      { q: 'A fringe belief, popularised online, that the giant prehistoric reptiles never existed and their fossils are a museum fabrication.', a: 'Dinosaur hoax', category: 'hoax', difficulty: 4 },
      { q: 'The 1942 wartime panic over a phantom air raid on a US west-coast city, when guns fired into the night sky; the Battle of Los ___.', a: 'District', category: 'ufo', difficulty: 5, alt: ['Angeles'] },
      { q: 'The fabled rays or invisible-energy weapon attributed to inventor Nikola Tesla, said to be suppressed by governments; a "death ___".', a: 'Device', category: 'government', difficulty: 4 },
      { q: 'The New Mexico town near a supposed secret underground alien base, less famous than nearby Roswell.', a: 'Dulce', category: 'ufo', difficulty: 5 },
      { q: 'The Dallas public square where President Kennedy was shot in 1963, overlooked by a grassy knoll and a book depository.', a: 'Dealey Plaza', category: 'assassination', difficulty: 3 },
      { q: 'The act of exposing a theory as false through evidence and reason; skeptics make a living doing this to myths.', a: 'Debunking', category: 'urban-legend', difficulty: 2 },
      { q: 'The deliberate spreading of false information by a government or group to mislead the public; a darker cousin of mere rumour.', a: 'Disinformation', category: 'government', difficulty: 3 },
      { q: 'The end-of-the-world prophecy tied to Nibiru and the misread 2012 Maya calendar; a "___ scenario".', a: 'Doomsday', category: 'paranormal', difficulty: 2 },
    ],
    E: [
      { q: 'The rock-and-roll king whose fans claim he faked his 1977 death and has been spotted alive ever since.', a: 'Elvis sightings', category: 'urban-legend', difficulty: 2 },
      { q: 'The broad term for beings from other worlds, the subject of most UFO lore.', a: 'Extraterrestrials', category: 'ufo', difficulty: 2 },
      { q: 'The 2013 leaker of NSA mass-surveillance documents, who fled and was granted asylum in Russia.', a: 'Edward Snowden', category: 'government', difficulty: 3 },
      { q: 'The author whose 1968 book "Chariots of the Gods?" launched the ancient-aliens craze; his German surname.', a: 'Erich von Daniken', category: 'ufo', difficulty: 4 },
      { q: 'The financier whose 2019 jail death by apparent suicide fuelled a viral "he didn\'t kill himself" meme.', a: 'Epstein', category: 'urban-legend', difficulty: 3, alt: ['Jeffrey Epstein'] },
      { q: 'The catch-all word for proof, the thing conspiracy theorists say is always being suppressed or hidden.', a: 'Evidence', category: 'urban-legend', difficulty: 1 },
      { q: 'A close encounter "of the third kind" means seeing an alien; this whole field of meeting beings from space is the study of close ___.', a: 'Encounters', category: 'ufo', difficulty: 3 },
      { q: 'The 1947 New Mexico debris find spawned this town\'s fame; one of America\'s most theorised crash sites lies near it. (Hint: not Roswell.)', a: 'Eddy County', category: 'ufo', difficulty: 5 },
      { q: 'The single all-seeing symbol in a triangle on the dollar bill, taken by some as a sign of Masonic power; the "all-seeing ___".', a: 'Eye', category: 'secret-society', difficulty: 2 },
      { q: 'The supposed shadow-power process of staging a phony attack to justify war; an "___-engineered crisis".', a: 'Elite', category: 'government', difficulty: 3 },
    ],
    F: [
      { q: 'The belief that our planet is a disc, not a globe, championed by a society founded by Samuel Shenton.', a: 'Flat Earth', category: 'paranormal', difficulty: 1 },
      { q: 'The world\'s oldest and largest fraternal order, with lodges, aprons and secret handshakes, often linked to elite-control theories.', a: 'Freemasons', category: 'secret-society', difficulty: 2 },
      { q: 'A staged event meant to look as if an enemy carried it out, blamed by theorists for many attacks; a "false ___" operation.', a: 'Flag', category: 'government', difficulty: 3, alt: ['False Flag'] },
      { q: 'The naturally occurring compound added to drinking water that some claim is a scheme to sedate citizens.', a: 'Fluoride', category: 'urban-legend', difficulty: 3 },
      { q: 'The pilot Kenneth Arnold\'s 1947 sighting of nine objects near Mount Rainier coined this two-word term for a disc-shaped craft.', a: 'Flying Saucer', category: 'ufo', difficulty: 3 },
      { q: 'The supposed network of cooperating intelligence agencies sharing surveillance, named for the number of English-speaking allies; the "___ Eyes".', a: 'Five', category: 'government', difficulty: 4 },
      { q: 'The covert money said to bankroll secret programmes, hidden in unaccountable government budgets; "black ___".', a: 'Funding', category: 'government', difficulty: 3 },
      { q: 'The men in this fraternal order wear aprons and exchange secret signs; a member of the world\'s largest lodge brotherhood.', a: 'Freemason', category: 'secret-society', difficulty: 2 },
      { q: 'A made-up or invented story passed off as real, like the carved Cardiff Giant or the bat-men-on-the-Moon news; a deliberate ___.', a: 'Fabrication', category: 'hoax', difficulty: 2 },
      { q: 'The US Bureau of Investigation that ran the COINTELPRO surveillance programme; its three-letter name.', a: 'FBI', category: 'government', difficulty: 2 },
    ],
    G: [
      { q: 'The classic small alien with a large head and big black eyes, the most reported "type" in abduction accounts.', a: 'Greys', category: 'ufo', difficulty: 2, alt: ['Grays'] },
      { q: 'A real Cold-War US Army effort studied psychic "remote viewing"; this hooved farm beast featured in the film about men who stare at them.', a: 'Goats', category: 'government', difficulty: 4 },
      { q: 'The grassy mound in Dealey Plaza from which theorists believe a second gunman fired at Kennedy; the grassy ___.', a: 'Gunner\'s knoll', category: 'assassination', difficulty: 3, alt: ['Grassy Knoll'] },
      { q: 'The wealthy banking dynasty other than the Rothschilds; financier J.P. of this surname is named in many money-power theories.', a: 'Goldman', category: 'secret-society', difficulty: 4 },
      { q: 'A West Virginia cryptid, a faceless white creature reported in 1964, less famous than its winged red-eyed neighbour, named for the small town where it was seen.', a: 'Grafton Monster', category: 'cryptid', difficulty: 5 },
      { q: 'The all-seeing single eye in a triangle, taken by theorists as proof of secret influence; the "___ of Providence".', a: 'Gaze', category: 'secret-society', difficulty: 4 },
      { q: 'The spectre of a dead person, said to linger in haunted houses; the central figure of paranormal-investigation TV shows.', a: 'Ghost', category: 'paranormal', difficulty: 1 },
      { q: 'A hidden global financial-control idea centres on this Swiss city\'s banks and the secretive trade meetings held there.', a: 'Geneva', category: 'secret-society', difficulty: 4 },
      { q: 'The clandestine assembly of world leaders at summits like the G7 is wrongly cast by theorists as a "secret ___" of rulers.', a: 'Gathering', category: 'secret-society', difficulty: 3 },
      { q: 'The fenced US naval base in Cuba, scene of detainee and "black site" allegations; nicknamed "Gitmo".', a: 'Guantanamo Bay', category: 'government', difficulty: 3 },
    ],
    H: [
      { q: 'The Alaska-based atmospheric research array conspiracy theorists wrongly accuse of controlling the weather and minds.', a: 'HAARP', category: 'government', difficulty: 3 },
      { q: 'The theory that our planet is not solid but contains a vast inhabited interior, reached through polar openings.', a: 'Hollow Earth', category: 'paranormal', difficulty: 3 },
      { q: 'A deliberate trick or fabrication designed to deceive the public, like the carved Cardiff Giant of 1869.', a: 'Hoax', category: 'hoax', difficulty: 1 },
      { q: 'The 1955 Kentucky farmhouse "siege" by little silver goblins is named for this town and led to the little-green-men legend.', a: 'Hopkinsville', category: 'ufo', difficulty: 5 },
      { q: 'The director of "2001: A Space Odyssey" need not apply here; instead, name the act of taking control of an aircraft, which 9/11 theories dispute happened.', a: 'Hijacking', category: 'government', difficulty: 3 },
      { q: 'The man-into-wolf transformation under a full moon, a staple of European folklore and horror; the half-human, half-canine being.', a: 'Howler beast', category: 'cryptid', difficulty: 4, alt: ['Werewolf'] },
      { q: 'A spooky residence where ghosts supposedly dwell, the setting of countless paranormal investigations; a "___ house".', a: 'Haunted', category: 'paranormal', difficulty: 2 },
      { q: 'The act of secretly altering history or records to hide the truth, a frequent claim about textbooks and archives; a "___-up" of facts.', a: 'Hush', category: 'government', difficulty: 3 },
      { q: 'The 1937 disaster of a German airship bursting into flame at Lakehurst spawned sabotage theories; that doomed hydrogen craft\'s name.', a: 'Hindenburg', category: 'government', difficulty: 4 },
      { q: 'The unproven contact-with-a-spirit phenomenon investigated by mediums and seances; a "___" or apparition from beyond.', a: 'Haunting', category: 'paranormal', difficulty: 2 },
    ],
    I: [
      { q: 'The supposed secret enlightened order, founded in Bavaria in 1776, blamed for orchestrating world events from the shadows.', a: 'Illuminati', category: 'secret-society', difficulty: 1 },
      { q: 'Conspiracy lore claims tiny tracking chips are secretly injected via vaccines; these embedded devices are called micro___.', a: 'Implants', category: 'urban-legend', difficulty: 3 },
      { q: 'The act of placing a hidden agent inside a group to spy or stir trouble, as the FBI did under COINTELPRO.', a: 'Infiltration', category: 'government', difficulty: 3 },
      { q: 'The general term for people who claim to have secret knowledge of how power really works; the opposite of outsiders.', a: 'Insiders', category: 'secret-society', difficulty: 2 },
      { q: 'The hidden hand said to guide markets and history, often called an "invisible ___" by theorists.', a: 'Influence', category: 'secret-society', difficulty: 3 },
      { q: 'A person who claims first-hand contact with aliens or hidden agencies, offering testimony but no proof.', a: 'Informant', category: 'government', difficulty: 3 },
      { q: 'The general term for the spy agencies at the heart of cover-up theories, the "___ community".', a: 'Intelligence', category: 'government', difficulty: 2 },
      { q: 'A staged event that triggers a desired political reaction by deception; an engineered "___ operation".', a: 'Incident', category: 'government', difficulty: 3 },
      { q: 'The fringe anti-vaccine claim that injected fluids carry secret nanotech or harmful agents; needle-delivered "___".', a: 'Injections', category: 'urban-legend', difficulty: 3 },
    ],
    J: [
      { q: 'The 1963 Dallas killing of a US president that spawned grassy-knoll and second-shooter theories.', a: 'JFK assassination', category: 'assassination', difficulty: 2 },
      { q: 'A winged, hoofed cryptid said to haunt the Pine Barrens of a US Garden State, born of legend to Mother Leeds.', a: 'Jersey Devil', category: 'cryptid', difficulty: 3 },
      { q: 'The cult leader whose followers died by poisoned drink in 1978 Guyana, source of the phrase "drinking the Kool-Aid"; his full name.', a: 'Jim Jones', category: 'urban-legend', difficulty: 3 },
      { q: 'The Guyana settlement where over 900 cult members died in 1978, feeding CIA mind-control rumours.', a: 'Jonestown', category: 'urban-legend', difficulty: 4 },
      { q: 'The financier accused of running an abuse ring, whose 2019 cell death is disputed; his first name.', a: 'Jeffrey', category: 'urban-legend', difficulty: 3, alt: ['Jeffrey Epstein'] },
      { q: 'The professional skeptic and stage magician, born Zwinge, who debunked psychics and offered a million-dollar prize for proof of the paranormal.', a: 'James Randi', category: 'paranormal', difficulty: 4 },
    ],
    K: [
      { q: 'The medieval warrior-monk order, suppressed in 1307, that lives on in Holy-Grail and treasure lore.', a: 'Knights Templar', category: 'secret-society', difficulty: 2 },
      { q: 'The director of "2001: A Space Odyssey" whom moon-hoax believers claim secretly filmed the fake lunar footage.', a: 'Kubrick', category: 'hoax', difficulty: 3, alt: ['Stanley Kubrick'] },
      { q: 'The brainwashing trope where a captive is conditioned to kill on a trigger word, from the film "The ___ Candidate".', a: 'Korean', category: 'government', difficulty: 4, alt: ['Manchurian'] },
      { q: 'The president shot in Dallas in 1963, the most theorised assassination in history; his surname.', a: 'Kennedy', category: 'assassination', difficulty: 1, alt: ['John F. Kennedy'] },
      { q: 'The poisoned soft-drink powder darkly associated with the 1978 Guyana cult deaths; to "drink the ___".', a: 'Kool-Aid', category: 'urban-legend', difficulty: 3 },
      { q: 'A serpent cryptid of Canada\'s Okanagan and similar lakes; the Scottish water-horse of folklore lends this name.', a: 'Kelpie', category: 'cryptid', difficulty: 4 },
      { q: 'The white-hooded secret society of the American South, infamous for terror and cross-burnings; abbreviated KKK.', a: 'Ku Klux Klan', category: 'secret-society', difficulty: 2 },
    ],
    L: [
      { q: 'The famous Scottish cryptid said to lurk in a deep Highland body of water near Inverness.', a: 'Loch Ness Monster', category: 'cryptid', difficulty: 1 },
      { q: 'The David Icke theory that shape-shifting reptilian beings disguised as elites secretly rule humanity.', a: 'Lizard People', category: 'paranormal', difficulty: 2, alt: ['Reptilians'] },
      { q: 'The accused 1963 presidential gunman, shot dead by Jack Ruby before he could stand trial; his full name.', a: 'Lee Harvey Oswald', category: 'assassination', difficulty: 3 },
      { q: 'The fabled lost continent said by occultists to have sunk beneath the Indian or Pacific ocean, a cousin of Atlantis.', a: 'Lemuria', category: 'paranormal', difficulty: 4 },
      { q: 'A 19th-century newspaper fabrication described bat-winged beings on the Moon spotted by a telescope; the Great Moon ___.', a: 'Lunar hoax', category: 'hoax', difficulty: 4 },
      { q: 'The small green humanoid aliens of pop culture and the Hopkinsville siege; "little green ___".', a: 'Lifeforms', category: 'ufo', difficulty: 3, alt: ['Men'] },
      { q: 'The meeting place of a Masonic chapter, where the brotherhood holds its secret rituals.', a: 'Lodge', category: 'secret-society', difficulty: 2 },
      { q: 'An intentional falsehood spread to deceive the public, the basic ingredient of every cover-up; the opposite of the truth.', a: 'Lie', category: 'government', difficulty: 1 },
      { q: 'The unauthorised release of secret documents to the press, as with the Pentagon Papers or the Snowden files; a "___" of classified files.', a: 'Leak', category: 'government', difficulty: 2 },
    ],
    M: [
      { q: 'The CIA\'s real, declassified 1950s-60s program of illegal mind-control experiments using drugs like LSD.', a: 'MKUltra', category: 'government', difficulty: 3 },
      { q: 'The dark-suited mysterious agents said to visit and silence UFO witnesses.', a: 'Men in Black', category: 'ufo', difficulty: 2 },
      { q: 'The red-eyed winged cryptid sighted in Point Pleasant, West Virginia, before a 1967 bridge collapse.', a: 'Mothman', category: 'cryptid', difficulty: 2 },
      { q: 'The alleged secret committee of twelve officials supposedly formed to handle recovered alien tech; "MJ-12".', a: 'Majestic 12', category: 'ufo', difficulty: 4 },
      { q: 'The effect where large groups vividly share a false memory, named after a South African leader\'s wrongly-remembered prison death.', a: 'Mandela effect', category: 'paranormal', difficulty: 3 },
      { q: 'The real CIA effort to influence journalists and news outlets in the Cold War, codenamed for a bird; Operation ___.', a: 'Mockingbird', category: 'government', difficulty: 4, alt: ['Operation Mockingbird'] },
      { q: 'The supposed faking of the 1969 lunar visit on a film set; the "faked ___ landing".', a: 'Moon', category: 'hoax', difficulty: 2 },
      { q: 'The 1947 New Mexico rancher who found the strange debris that launched the famous saucer-crash story; the foreman\'s surname was this.', a: 'Mac Brazel', category: 'ufo', difficulty: 5, alt: ['Brazel'] },
      { q: 'A staged mass tragedy that conspiracy theorists falsely claim was performed by paid actors; a "___ shooting" hoax claim.', a: 'Manufactured', category: 'urban-legend', difficulty: 3 },
      { q: 'The brainwashed-assassin film whose title became shorthand for a programmed killer; "The ___ Candidate".', a: 'Manchurian', category: 'government', difficulty: 3 },
      { q: 'The general practice of controlling people\'s thoughts and behaviour against their will, the goal of the CIA\'s MKUltra; "mind ___".', a: 'Manipulation', category: 'government', difficulty: 2 },
    ],
    N: [
      { q: 'The phrase for an alleged single planet-wide authoritarian government that theorists fear will replace all nations; abbreviated NWO.', a: 'New World Order', category: 'secret-society', difficulty: 2 },
      { q: 'The hypothetical rogue planet, drawn from Zecharia Sitchin\'s writings, predicted to swing by and devastate the Earth.', a: 'Nibiru', category: 'paranormal', difficulty: 3 },
      { q: 'The affectionate Scottish nickname for the elusive monster of a famous Highland loch.', a: 'Nessie', category: 'cryptid', difficulty: 2 },
      { q: 'The president forced to resign in 1974 after a cover-up of a break-in at Democratic headquarters; his surname.', a: 'Nixon', category: 'government', difficulty: 2, alt: ['Richard Nixon'] },
      { q: 'The US agency exposed for bulk telephone and internet surveillance by a 2013 leak; its three-letter name.', a: 'NSA', category: 'government', difficulty: 2 },
      { q: 'Under Operation Paperclip the US secretly recruited rocket experts who had served this defeated WWII German regime; its four-letter party name.', a: 'Nazi recruits', category: 'government', difficulty: 3 },
      { q: 'The US eavesdropping body nicknamed "No Such Body", revealed in 2013 to be vacuuming up the world\'s phone and internet traffic; spell out NSA in full.', a: 'National Security Agency', category: 'government', difficulty: 3 },
      { q: 'The undiscovered world some astronomers hypothesise beyond Neptune, conflated by doomsday fans with the rogue Nibiru; "Planet X" or the ___ rock from the Sun.', a: 'Nine', category: 'paranormal', difficulty: 4 },
    ],
    O: [
      { q: 'The talking spirit-tablet with letters and a planchette that supposedly lets the dead spell out messages.', a: 'Ouija board', category: 'paranormal', difficulty: 2 },
      { q: 'The lake monster of British Columbia\'s Okanagan, Canada\'s most famous water cryptid.', a: 'Ogopogo', category: 'cryptid', difficulty: 4 },
      { q: 'The general word for a coordinated secret mission by intelligence or military bodies, the head-noun of many code names.', a: 'Operation', category: 'government', difficulty: 1 },
      { q: 'The accused assassin of President Kennedy, killed two days later by Jack Ruby; his surname.', a: 'Oswald', category: 'assassination', difficulty: 3, alt: ['Lee Harvey Oswald'] },
      { q: 'The all-seeing single ___ in a triangle, atop the pyramid on the US dollar, read as a symbol of secret power.', a: 'Orb', category: 'secret-society', difficulty: 3, alt: ['Eye'] },
      { q: 'The classified high-altitude reconnaissance flights of the 1950s, like the U-2, often mistaken for craft from another world; covert "___ flights".', a: 'Overflight', category: 'government', difficulty: 4 },
      { q: 'The pervasive watching of citizens that surveillance theories warn of; an all-seeing "Big Brother" society practises constant ___.', a: 'Observation', category: 'government', difficulty: 2 },
      { q: 'The 1938 Orson Welles radio drama of "War of the Worlds" sparked famed public alarm over a fake Martian invasion; it aired in the tenth month of the year.', a: 'October scare', category: 'hoax', difficulty: 4 },
      { q: 'The sworn statement under penalty given by an insider exposing wrongdoing; a written declaration in a legal cover-up case.', a: 'Oath', category: 'government', difficulty: 3 },
    ],
    P: [
      { q: 'The viral 2016 hoax alleging a child-abuse ring run from a Washington restaurant basement.', a: 'Pizzagate', category: 'hoax', difficulty: 2 },
      { q: 'The real WWII operation that smuggled German rocket scientists like Wernher von Braun into the US, named for an office supply.', a: 'Paperclip', category: 'government', difficulty: 3, alt: ['Operation Paperclip'] },
      { q: 'The 1971 leak of a secret Vietnam-War study exposing government deception; the Pentagon ___.', a: 'Papers', category: 'government', difficulty: 4, alt: ['Pentagon Papers'] },
      { q: 'The contested 1967 footage by Roger Patterson and Bob Gimlin purporting to show Bigfoot striding through the woods; its first photographer\'s surname is Patterson, the second is this.', a: 'Pacific shoot', category: 'cryptid', difficulty: 4, alt: ['Gimlin'] },
      { q: 'The alleged 1943 US Navy invisibility-and-teleportation test of a warship in a dockyard, named for a Pennsylvania city.', a: 'Philadelphia Experiment', category: 'government', difficulty: 3 },
      { q: 'The hard ridges of the Giza monuments built by Khufu\'s workers, but credited by ancient-alien theorists to visitors; the Egyptian ___.', a: 'Pyramids', category: 'ufo', difficulty: 2 },
      { q: 'A ghostly apparition or spirit said to manifest in haunted places; the paranormal sense of a "spectral ___".', a: 'Phantom', category: 'paranormal', difficulty: 2 },
      { q: 'The fringe belief that crisis-actors stage tragedies and that no one was really hurt; such events are dismissed as "false-flag ___".', a: 'Productions', category: 'urban-legend', difficulty: 4 },
      { q: 'The 1947 New Mexico recovery is "the ___" event for UFO believers; the all-time most-cited word for a vehicle smashing into the ground.', a: 'Plane wreck', category: 'ufo', difficulty: 3, alt: ['Crash'] },
      { q: 'A secret scheme or covert design by a group to commit a wrong, the very thing a conspiracy theory alleges; to "hatch a ___".', a: 'Plot', category: 'urban-legend', difficulty: 1 },
      { q: 'A self-styled gifted person who claims to read minds or contact the dead, often exposed by the skeptic James Randi.', a: 'Psychic', category: 'paranormal', difficulty: 2 },
    ],
    Q: [
      { q: 'The sprawling internet movement that grew from anonymous "drop" posts claiming a secret battle against a cabal.', a: 'QAnon', category: 'urban-legend', difficulty: 2 },
      { q: 'The act of doubting an official account and demanding hidden truth, the mindset behind "do your own research".', a: 'Questioning', category: 'urban-legend', difficulty: 2 },
      { q: 'The hush money or enforced silence demanded to keep a cover-up buried; to keep a witness ___.', a: 'Quiet', category: 'government', difficulty: 3 },
      { q: 'A 2021 documentary about the rise of the anonymous online cult was titled "Q: Into the Storm"; this swampy word means a hopeless, murky mess like the movement became.', a: 'Quagmire', category: 'urban-legend', difficulty: 4 },
      { q: 'The Roman-era practice of disturbing public order to justify a crackdown, a "false flag" idea in essence; to ___ a riot for political gain.', a: 'Quell', category: 'government', difficulty: 5 },
      { q: 'A secret search or investigation, often into hidden truths; the medieval Church\'s feared inquisitorial version was the Inquisition, but the everyday word is this "___".', a: 'Quest', category: 'secret-society', difficulty: 4 },
    ],
    R: [
      { q: 'The New Mexico town synonymous with the most famous alleged 1947 flying-saucer crash and military cover-up.', a: 'Roswell', category: 'ufo', difficulty: 1 },
      { q: 'The wealthy European banking dynasty endlessly accused of secretly controlling the world\'s finances.', a: 'Rothschilds', category: 'secret-society', difficulty: 2 },
      { q: 'The David-Icke shape-shifting alien-overlord beings, said to hide among the elite as "lizard people".', a: 'Reptilians', category: 'paranormal', difficulty: 2 },
      { q: 'The 1980 UFO incident in an English woodland near two US air bases, dubbed "Britain\'s Roswell"; the Suffolk site\'s name.', a: 'Rendlesham Forest', category: 'ufo', difficulty: 4 },
      { q: 'The nightclub owner who shot Lee Harvey Oswald on live television in 1963; his surname.', a: 'Ruby', category: 'assassination', difficulty: 3, alt: ['Jack Ruby'] },
      { q: 'The invisible beams that mind-control theorists claim are aimed at the public, blocked supposedly by a tinfoil hat; harmful "mind ___".', a: 'Rays', category: 'urban-legend', difficulty: 3 },
      { q: 'The psychic skill the US Stargate Project studied: the alleged power to perceive a faraway, unseen location using only the mind, from afar.', a: 'Remote viewing', category: 'government', difficulty: 4 },
      { q: 'The 1947 alleged saucer event gives this New Mexico town its worldwide fame as the most iconic of all UFO place names; the named "happening" there.', a: 'Roswell incident', category: 'ufo', difficulty: 2 },
      { q: 'A widely shared but unverified story, the lifeblood of conspiracy culture; an unconfirmed claim passed person to person.', a: 'Rumour', category: 'urban-legend', difficulty: 1, alt: ['Rumor'] },
    ],
    S: [
      { q: 'The secretive Yale undergraduate society whose members reportedly include presidents and spymasters.', a: 'Skull and Bones', category: 'secret-society', difficulty: 3 },
      { q: 'Another name for Bigfoot, derived from a Salish First Nations word for the wild hairy forest man.', a: 'Sasquatch', category: 'cryptid', difficulty: 2 },
      { q: 'The US Defense program that researched psychic "remote viewing", named for a celestial portal.', a: 'Stargate Project', category: 'government', difficulty: 4 },
      { q: 'The 2013 NSA leaker who exposed the scale of global surveillance; his surname.', a: 'Snowden', category: 'government', difficulty: 2, alt: ['Edward Snowden'] },
      { q: 'The author Zecharia of this surname read ancient texts to claim a rogue planet and alien gods; he popularised Nibiru.', a: 'Sitchin', category: 'paranormal', difficulty: 4 },
      { q: 'The pseudoscience claiming the Earth is a stationary disc; believers say NASA fakes the globe with this kind of doctored picture.', a: 'Staged photo', category: 'paranormal', difficulty: 3 },
      { q: 'The thin shiny metal headgear, worn half-jokingly to "block" mind rays; a tinfoil version of this.', a: 'Sheet hat', category: 'urban-legend', difficulty: 3 },
      { q: 'The covert monitoring of people\'s movements and messages by the state, exposed on a vast scale by the 2013 NSA leaks.', a: 'Surveillance', category: 'government', difficulty: 2 },
      { q: 'A long, snake-like creature said to swim in deep lochs and seas, the basic type that Nessie belongs to; a "lake ___".', a: 'Serpent', category: 'cryptid', difficulty: 3 },
      { q: 'A clandestine fraternal organisation with hidden rituals and oaths, like the Freemasons or Skull and Bones; the genre of this whole pack.', a: 'Secret society', category: 'secret-society', difficulty: 1 },
      { q: 'A person who undertakes covert intelligence work for a government, gathering hidden information; an undercover agent or ___.', a: 'Spy', category: 'government', difficulty: 1 },
      { q: 'The fringe claim that powerful interests hide cures or clean-energy inventions to protect profits; the alleged "___ of technology".', a: 'Suppression', category: 'government', difficulty: 3 },
    ],
    T: [
      { q: 'The massive 1908 Siberian forest explosion, likely a meteor air-burst, that fuels alien and death-ray theories.', a: 'Tunguska event', category: 'paranormal', difficulty: 3 },
      { q: 'The slang protective hat made of metal foil, worn by those fearing the government reads their thoughts.', a: 'Tinfoil hat', category: 'urban-legend', difficulty: 2 },
      { q: 'The inventor and free-energy pioneer whose "death ray" and wireless-power ideas feed suppressed-technology theories; his surname.', a: 'Tesla', category: 'government', difficulty: 3, alt: ['Nikola Tesla'] },
      { q: 'The Knights of this medieval crusading order were crushed by France in 1307 and live on in Grail and treasure lore.', a: 'Templar', category: 'secret-society', difficulty: 3, alt: ['Knights Templar'] },
      { q: 'A staged event meant to be blamed on an opponent, the core idea behind a "false flag"; an act of deception or ___.', a: 'Trickery', category: 'government', difficulty: 3 },
      { q: 'The three-sided ocean region off Florida and Bermuda where vessels supposedly disappear; the geometric shape giving it its name.', a: 'Triangle', category: 'paranormal', difficulty: 2 },
      { q: 'A government-employed agent who secretly betrays their own side, the villain of many spy and cover-up tales; one guilty of treason.', a: 'Traitor', category: 'government', difficulty: 2 },
      { q: 'The witness or insider who tells the hidden facts under oath; sworn courtroom or hearing evidence is called this.', a: 'Testimony', category: 'government', difficulty: 2 },
      { q: 'The doomsday rogue planet Nibiru is also linked to this Babylonian creator deity, after whom some call "Planet X".', a: 'Tiamat', category: 'paranormal', difficulty: 5 },
      { q: 'An unproven idea offered to explain hidden causes of events; the suffix-word in "conspiracy ___".', a: 'Theory', category: 'urban-legend', difficulty: 1 },
    ],
    U: [
      { q: 'The three-letter abbreviation for a flying object in the sky that the observer cannot identify.', a: 'UFO', category: 'ufo', difficulty: 1 },
      { q: 'The newer official US government term for unexplained aerial sightings, replacing the old saucer label; the acronym ___.', a: 'UAP', category: 'ufo', difficulty: 3 },
      { q: 'A vast network of secret tunnels and bases, like those rumoured beneath Denver Airport; "___ bunkers".', a: 'Underground', category: 'urban-legend', difficulty: 2 },
      { q: 'The 2017-leaked US Navy footage of fast-moving objects, three clips nicknamed Gimbal, Go Fast and this Pentagon-confirmed term for the unexplained.', a: 'Unidentified', category: 'ufo', difficulty: 3 },
      { q: 'The all-seeing eye and pyramid imagery feed a fear of one merged world authority; a single "___ government".', a: 'Unified', category: 'secret-society', difficulty: 3, alt: ['Unity'] },
      { q: 'A creature or event for which no scientific explanation yet exists, the broad category covering cryptids and ghosts; the ___.', a: 'Unexplained', category: 'paranormal', difficulty: 2 },
      { q: 'The hidden, often-feared global authority that New-World-Order theorists believe is forming; a single planet-wide "___ government".', a: 'United', category: 'secret-society', difficulty: 3 },
      { q: 'The 2017 New York Times disclosure of a secret Pentagon programme studying strange aerial sightings stunned the public; such sightings stay officially "___".', a: 'Unconfirmed', category: 'ufo', difficulty: 3 },
      { q: 'A widely circulated modern folk tale, often scary or cautionary and untrue, like the vanishing hitchhiker; a city-dwellers\' ___.', a: 'Urban legend', category: 'urban-legend', difficulty: 2 },
      { q: 'The hidden labyrinth of tunnels and chambers theorists imagine beneath Denver Airport or military bases; built far below the surface, it is "___".', a: 'Underground complex', category: 'urban-legend', difficulty: 3 },
    ],
    W: [
      { q: 'The 1972 break-in and cover-up scandal at a Washington office complex that toppled President Nixon.', a: 'Watergate', category: 'government', difficulty: 2 },
      { q: 'A man who turns into a wolf under the full moon, a staple of European folklore and horror.', a: 'Werewolf', category: 'cryptid', difficulty: 2 },
      { q: 'The hairy upright cryptid of the Australian bush, that continent\'s version of Bigfoot.', a: 'Wendigo', category: 'cryptid', difficulty: 4, alt: ['Yowie'] },
      { q: 'A person who exposes secret wrongdoing inside an organisation, like Edward Snowden or Mark Felt.', a: 'Whistleblower', category: 'government', difficulty: 2 },
      { q: 'The Alaska array HAARP is accused of using to manipulate the climate; the supposed control of rain and storms is "___ modification".', a: 'Weather', category: 'government', difficulty: 3 },
      { q: 'The pseudoscientific star-system Sumerians supposedly knew of via alien gods feeds many theories; but name simply the constant Orwellian act of being observed by Big Brother; to be under ___.', a: 'Watch', category: 'government', difficulty: 3, alt: ['Surveillance'] },
      { q: 'The science-fiction radio drama by Orson Welles that triggered the 1938 invasion panic; "The ___ of the Worlds".', a: 'War', category: 'hoax', difficulty: 3 },
      { q: 'A mythical hairy giant of forests worldwide; the umbrella term for Bigfoot, Yeti and Sasquatch sightings is the "___ man".', a: 'Wild', category: 'cryptid', difficulty: 2 },
      { q: 'The organisation founded by Julian Assange that published vast troves of classified diplomatic and military files in 2010.', a: 'WikiLeaks', category: 'government', difficulty: 3 },
    ],
    Y: [
      { q: 'The Himalayan cryptid also called the "abominable snowman" of high-altitude legend.', a: 'Yeti', category: 'cryptid', difficulty: 2 },
      { q: 'The hairy hominid cryptid of the Australian bush, that continent\'s answer to Bigfoot.', a: 'Yowie', category: 'cryptid', difficulty: 4 },
      { q: 'The secretive society at this Connecticut university hosts the Skull and Bones order; its name.', a: 'Yale', category: 'secret-society', difficulty: 3 },
      { q: 'The video-sharing site flooded with conspiracy and UFO content, where many theories first go viral.', a: 'YouTube', category: 'urban-legend', difficulty: 1 },
      { q: 'The single year, 2000, of a feared global computer-clock meltdown that some called an engineered panic; the "___ bug".', a: 'Y2K', category: 'urban-legend', difficulty: 3 },
      { q: 'The tabloid newspaper format and supermarket "weekly" famous for alien-baby and Bigfoot front pages; sensational gossip rags are this colour of journalism.', a: 'Yellow press', category: 'hoax', difficulty: 4 },
    ],
    Z: [
      { q: 'Abraham of this surname shot the home-movie footage that captured the 1963 Dallas presidential killing frame by frame.', a: 'Zapruder', category: 'assassination', difficulty: 3, alt: ['Zapruder film'] },
      { q: 'The unidentified 1968-69 serial murderer who taunted San Francisco newspapers with ciphers, sharing a name with the band of star signs.', a: 'Zodiac Killer', category: 'urban-legend', difficulty: 3 },
      { q: 'The fictional plague of reanimated corpses that some claim secret labs could engineer as a bioweapon.', a: 'Zombie outbreak', category: 'urban-legend', difficulty: 2 },
      { q: 'The author Sitchin\'s first name, who claimed ancient Sumerians knew of a hidden planet and alien gods.', a: 'Zecharia', category: 'paranormal', difficulty: 4 },
      { q: 'In "patient ___" and "ground ___", the single number that marks the origin point of an outbreak or blast, much sought in any cover-up.', a: 'Zero', category: 'government', difficulty: 3 },
      { q: 'A secret government collection of captured exotic or alien creatures would be a covert version of this animal-housing institution.', a: 'Zoo', category: 'cryptid', difficulty: 3 },
      { q: 'The dark fascination with the dead returning to life, central to bioweapon-apocalypse fears; an undead reanimated corpse of horror films.', a: 'Zombie', category: 'urban-legend', difficulty: 2 },
    ],
  },
};
