import type { RawPack } from '../core/packs';

export const conspiracyHardPack: RawPack = {
  id: 'conspiracy-hard',
  name: 'Conspiracy Theories',
  description: 'Declassified ops and deep-cut lore for the true believers.',
  locale: 'en',
  difficulty: 'hard',
  contentRating: 'everyone',
  emoji: '👁️',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: 'Declassified 1960s CIA project that surgically wired a feline with a microphone and antenna to eavesdrop on the Soviets.', a: 'Acoustic Kitty', category: 'government', difficulty: 5 },
      { q: '1953 CIA/MI6 coup, codenamed for a household cleaner, that toppled Iran’s elected premier Mosaddegh.', a: 'Ajax', category: 'government', difficulty: 4 },
      { q: '1974 CIA mission, fronted by Howard Hughes, to raise a sunken Soviet submarine from the Pacific floor (a sea-region codeword).', a: 'Azorian', category: 'government', difficulty: 5 },
      { q: 'CIA director who launched the agency’s 1953 behavioral-control research and was brother to a Secretary of State (full name).', a: 'Allen Dulles', category: 'government', difficulty: 4, alt: ['Dulles'] },
      { q: 'Vietnam-era defoliant identified by the colored band painted on its drums, dispersed under a “Ranch Hand” campaign.', a: 'Agent Orange', category: 'government', difficulty: 4 },
      { q: 'CIA counterintelligence chief James, whose obsessive mole-hunts paralyzed the agency for years (surname).', a: 'Angleton', category: 'government', difficulty: 5, alt: ['James Angleton'] },
      { q: 'Cleric-led 1979 takeover that ended the U.S.-backed monarchy the CIA had restored in Iran (the country’s religious revolution adjective + “revolution”).', a: 'Ayatollah revolution', category: 'government', difficulty: 5, alt: ['Iranian Revolution'] },
      { q: 'Aldrich ___ — the CIA officer exposed in 1994 as a long-running paid mole for Moscow (surname).', a: 'Ames', category: 'government', difficulty: 5, alt: ['Aldrich Ames'] },
      { q: 'Rumored hypersonic U.S. spy aircraft of the late 1980s, never officially confirmed, whose name shares it with the northern polar lights (the codename).', a: 'Aurora', category: 'ufo', difficulty: 5 },
      { q: '1983 NATO command-post exercise so realistic the Soviets briefly feared a genuine first strike, nearly triggering nuclear war (the wargame’s two-word codename, suggesting a capable bowman).', a: 'Able Archer', category: 'government', difficulty: 5 },
      { q: 'The 2001 mailing of a deadly powdered bacterium to U.S. senators and newsrooms, an attack steeped in cover-up and false-attribution theories (the disease the spores cause).', a: 'Anthrax attacks', category: 'government', difficulty: 5, alt: ['Anthrax'] },
    ],
    B: [
      { q: 'Early-1990s scandal of a bank nicknamed the “Bank of Crooks and Criminals,” tied to laundering and intelligence money (four-letter acronym).', a: 'BCCI', category: 'government', difficulty: 5 },
      { q: '1933 alleged corporate scheme, exposed by General Smedley Butler, to overthrow President Roosevelt by force (two words).', a: 'Business Plot', category: 'government', difficulty: 5 },
      { q: 'Vatican-tied Milan bank whose 1982 collapse and the death of Roberto Calvi rocked Italy (Italian for “Saint Ambrose”).', a: 'Banco Ambrosiano', category: 'secret-society', difficulty: 5 },
      { q: 'London span beneath which financier Roberto Calvi was found hanged in 1982, its name evoking medieval friars.', a: 'Blackfriars Bridge', category: 'secret-society', difficulty: 5 },
      { q: 'West Germany’s foreign intelligence service, successor to the Gehlen Organization, named in NATO secret-army claims (three-letter German acronym).', a: 'BND', category: 'government', difficulty: 5 },
      { q: 'Smedley ___ — the much-decorated Marine general who testified to Congress about the alleged 1933 plot against the president (surname).', a: 'Butler', category: 'government', difficulty: 5, alt: ['Smedley Butler'] },
      { q: 'Andrew ___ — the man who claims he was a child participant in an alleged DARPA time-travel program (surname).', a: 'Basiago', category: 'paranormal', difficulty: 5, alt: ['Andrew Basiago'] },
      { q: '1961 botched CIA-backed landing of Cuban exiles at a southern coastal inlet, a fiasco that fueled later anti-Castro covert plots (the swine-named beachhead).', a: 'Bay of Pigs', category: 'government', difficulty: 5 },
      { q: '1950 CIA precursor to its later mind-control research, an early interrogation-and-hypnosis study named for a small songbird (the codename).', a: 'Bluebird', category: 'government', difficulty: 5 },
      { q: 'Yuri ___ — the Soviet KGB defector whose 1980s lectures on “ideological subversion” are endlessly quoted in disinformation lore (surname).', a: 'Bezmenov', category: 'government', difficulty: 5, alt: ['Yuri Bezmenov'] },
      { q: 'British journalist and intelligence-linked anti-communist who long chaired the secretive Le Cercle forum (full name).', a: 'Brian Crozier', category: 'secret-society', difficulty: 5, alt: ['Crozier'] },
    ],
    C: [
      { q: 'CIA domestic-spying program of 1967–74 that infiltrated antiwar and student movements (a Greek-myth word for disorder).', a: 'CHAOS', category: 'government', difficulty: 5 },
      { q: '1979–89 covert U.S. effort to arm Afghan mujahideen against the Soviets (named for a violent windstorm).', a: 'Cyclone', category: 'government', difficulty: 4 },
      { q: 'Le ___ — a secretive transatlantic anti-communist foreign-policy forum founded around 1951 (one French word for a ring).', a: 'Cercle', category: 'secret-society', difficulty: 5 },
      { q: 'Journalist Danny ___ died in 1991 investigating an alleged “Octopus” web of intelligence crimes (surname).', a: 'Casolaro', category: 'government', difficulty: 5 },
      { q: '1970s multi-nation South American campaign of political repression and assassination, codenamed for a bird of prey.', a: 'Condor', category: 'government', difficulty: 5 },
      { q: 'Nicaraguan rebels secretly funded by Iranian arms sales in the 1980s scandal (Spanish for “against”).', a: 'Contras', category: 'government', difficulty: 4 },
      { q: 'Roberto ___ — the “God’s Banker” found dead beneath a London bridge in 1982 (surname).', a: 'Calvi', category: 'secret-society', difficulty: 5, alt: ['Roberto Calvi'] },
      { q: 'Fidel ___ — the Cuban leader targeted by exploding-cigar, poison, and seashell assassination schemes hatched under Operation Mongoose (surname).', a: 'Castro', category: 'government', difficulty: 4, alt: ['Fidel Castro'] },
      { q: 'Spy agency, founded 1947, whose 1973 internal catalogue of abuses was nicknamed the “Family Jewels” (its three-letter acronym).', a: 'CIA', category: 'government', difficulty: 3 },
      { q: '1975–76 U.S. Senate investigation, led by an Idaho senator surnamed after a place of worship, that exposed CIA assassination plots and domestic spying (the senator’s surname + the panel word).', a: 'Church Committee', category: 'government', difficulty: 5 },
      { q: 'The exploding seashell and poisoned wetsuit were among bizarre CIA schemes to kill the Cuban leader; this Caribbean island nation was the target of those plots (the country).', a: 'Cuba', category: 'government', difficulty: 4 },
      { q: 'Code name for the Iraqi defector whose fabricated claims about mobile bioweapon labs helped justify the 2003 invasion (a baseball-pitch nickname).', a: 'Curveball', category: 'government', difficulty: 5 },
    ],
    D: [
      { q: '1518 Strasbourg mania in which dozens reportedly moved compulsively for days on end (two-word phenomenon).', a: 'Dancing Plague', category: 'urban-legend', difficulty: 5 },
      { q: 'New Mexico town of UFO legend said to sit atop an underground extraterrestrial facility.', a: 'Dulce', category: 'ufo', difficulty: 5 },
      { q: 'Term for an alleged shadow network of unelected officials covertly steering policy from inside government (two words).', a: 'Deep state', category: 'government', difficulty: 4 },
      { q: 'Fort ___ in Maryland, the U.S. Army biological-warfare center that partnered on the CIA’s MK-Naomi toxin work (the fort’s name).', a: 'Detrick', category: 'government', difficulty: 5, alt: ['Fort Detrick'] },
      { q: 'CIA director who launched the agency’s 1953 mind-control research, brother of a Secretary of State (surname; Allen).', a: 'Dulles brothers', category: 'government', difficulty: 4, alt: ['Allen Dulles'] },
      { q: 'Andrew Basiago alleges this Pentagon research agency ran a secret teleportation and time-travel program called Pegasus (the famed advanced-projects body, six-letter acronym).', a: 'DARPA', category: 'paranormal', difficulty: 5 },
      { q: 'A secret personal file of damaging information, the kind J. Edgar Hoover was said to keep on politicians (French-rooted word for such a folder).', a: 'Dossier', category: 'government', difficulty: 5 },
      { q: 'South Vietnamese president overthrown and killed in a 1963 CIA-supported coup, weeks before Kennedy’s own death (surname; Ngo Dinh ___).', a: 'Diem', category: 'assassination', difficulty: 5, alt: ['Ngo Dinh Diem'] },
      { q: 'Pentagon’s military intelligence body, founded 1961, whose first chief co-authored the secret Alaska stay-behind plan (the three-letter acronym).', a: 'DIA', category: 'government', difficulty: 5 },
      { q: 'Semi-automatic Soviet doomsday system, revealed after the Cold War, designed to launch nuclear retaliation even with leadership wiped out (a chilling two-word nickname: lifeless, plus a body part for grasping).', a: 'Dead Hand', category: 'government', difficulty: 5 },
      { q: '“Wild Bill” ___ — the WWII spymaster who led the OSS, the CIA’s direct forerunner (surname).', a: 'Donovan', category: 'government', difficulty: 5, alt: ['William Donovan'] },
      { q: 'A planted insider who secretly observes and reports from within an enemy organization (the spy term, also a small burrowing mammal).', a: 'Double-agent mole', category: 'government', difficulty: 4, alt: ['Mole'] },
    ],
    E: [
      { q: 'Five-nation signals-intelligence collection network exposed by European inquiries in the late 1990s.', a: 'Echelon', category: 'government', difficulty: 4 },
      { q: 'U.S. Air Force general and CIA operative (first name a king’s) who masterminded the anti-Castro sabotage campaign Operation Mongoose (full name).', a: 'Edward Lansdale', category: 'government', difficulty: 5, alt: ['Lansdale'] },
      { q: 'Outgoing 1961 presidential warning about the “military-industrial complex” came from this former five-star general turned commander-in-chief (surname).', a: 'Eisenhower', category: 'government', difficulty: 4 },
      { q: 'Surname of Daniel, the RAND analyst who leaked the secret Pentagon study of the Vietnam War to the press in 1971.', a: 'Ellsberg', category: 'government', difficulty: 5, alt: ['Daniel Ellsberg'] },
      { q: 'German WWII cipher device cracked at Bletchley Park, a frequent fixture of secret-history intelligence lore (the puzzle-evoking name of the rotor coder).', a: 'Enigma', category: 'government', difficulty: 4 },
      { q: 'The signals-intelligence alliance of the U.S., U.K., Canada, Australia and New Zealand is nicknamed for five of these watching organs of sight (the plural body part).', a: 'Eyes', category: 'government', difficulty: 5, alt: ['Five Eyes'] },
      { q: 'NSA contractor whose 2013 leaks exposed sweeping global mass-surveillance programs and who fled to Moscow (full name).', a: 'Edward Snowden', category: 'government', difficulty: 4, alt: ['Snowden'] },
      { q: 'Diplomatic buildings were prime Cold War listening targets; the U.S. one in Moscow was riddled with hidden Soviet microphones (the kind of diplomatic mission, a building housing an ambassador).', a: 'Embassy', category: 'government', difficulty: 5 },
      { q: 'North African country where Israeli agents in 1954 bombed Western targets in a false-flag plot, the Lavon Affair (the nation, home of the pyramids).', a: 'Egypt', category: 'government', difficulty: 4 },
      { q: 'The crime and practice of spying to obtain secret state information, the legal charge faced by leakers and moles alike (a noun, the “act of spying”).', a: 'Espionage', category: 'government', difficulty: 4 },
    ],
    F: [
      { q: 'ATF gun-walking operation (2009–11) that let firearms cross into Mexico to trace cartels, named for speed and anger.', a: 'Fast and Furious', category: 'government', difficulty: 4 },
      { q: '1973 internal CIA report cataloguing the agency’s illegal activities, nicknamed for precious heirlooms.', a: 'Family Jewels', category: 'government', difficulty: 5 },
      { q: 'A hostile act staged to look like another party’s doing, the premise of the rejected Northwoods proposal (the deceptive-banner attack, two words).', a: 'False flag', category: 'government', difficulty: 4 },
      { q: 'Fort ___ — the Maryland Army center for biological-warfare research linked to the CIA’s toxin program (the place name).', a: 'Fort Detrick', category: 'government', difficulty: 5, alt: ['Detrick'] },
      { q: 'The U.S. domestic security and law-enforcement bureau, long run by J. Edgar Hoover, accused of decades of political spying (three-letter acronym).', a: 'FBI', category: 'government', difficulty: 3 },
      { q: 'Bletchley codebreakers aside; the airman shot down over the USSR in 1960 was first-named after the country’s patron saint of Assisi; give that given name (a saint’s name, also a common male first name).', a: 'Francis', category: 'government', difficulty: 5, alt: ['Francis Gary Powers'] },
      { q: 'Adding this chemical to public drinking water, a routine dental-health measure, is the subject of a long-running mass-poisoning conspiracy theory (the tooth-strengthening element added to tap water).', a: 'Fluoride', category: 'hoax', difficulty: 4 },
      { q: 'James ___ — the first U.S. Secretary of Defense, whose 1949 fall from a hospital window fuels enduring conspiracy claims (surname).', a: 'Forrestal', category: 'assassination', difficulty: 5, alt: ['James Forrestal'] },
      { q: 'A deliberately fabricated document passed off as genuine, the category to which the 1924 anti-Labour Zinoviev letter belongs (a noun for such a counterfeit).', a: 'Forgery', category: 'government', difficulty: 4 },
      { q: 'U.S. Army biochemist who plunged to his death from a hotel window in 1953, days after the CIA secretly dosed him with LSD (full name).', a: 'Frank Olson', category: 'government', difficulty: 5, alt: ['Olson'] },
    ],
    G: [
      { q: '1964 disputed naval episode off Vietnam whose questionable second attack helped justify wider war (the body of water).', a: 'Gulf of Tonkin', category: 'government', difficulty: 4 },
      { q: 'NATO’s secret Cold War “stay-behind” armies in Europe, exposed in 1990 and named for a Roman sword.', a: 'Gladio', category: 'government', difficulty: 4 },
      { q: 'Hughes-built deep-sea vessel, publicly a mining ship, that secretly tried to recover a Soviet sub in 1974 (two-word ship name).', a: 'Glomar Explorer', category: 'government', difficulty: 5 },
      { q: 'Surname (Sidney) of the CIA chemist who ran the agency’s LSD, poison, and behavioral-control research.', a: 'Gottlieb', category: 'government', difficulty: 5, alt: ['Sidney Gottlieb'] },
      { q: 'Reinhard ___ — the ex-Nazi general whose West German spy network folded into the BND (surname).', a: 'Gehlen', category: 'government', difficulty: 5 },
      { q: 'Licio ___ — the grandmaster of Italy’s secret P2 masonic lodge whose hidden roster shook the 1981 government (surname).', a: 'Gelli', category: 'secret-society', difficulty: 5, alt: ['Licio Gelli'] },
      { q: 'The Scientology unit that carried out the 1970s infiltration of U.S. agencies was named for a protector role — a watchful sentinel (the singular protector noun).', a: 'Guardian’s Office', category: 'secret-society', difficulty: 5 },
      { q: 'Anatoliy ___ — the KGB defector whose sweeping claims of Soviet deception deeply influenced and divided Western counterintelligence (surname).', a: 'Golitsyn', category: 'government', difficulty: 5, alt: ['Anatoliy Golitsyn'] },
      { q: 'Chronic multi-symptom illness reported by 1991 Persian-conflict veterans, blamed variously on nerve agents or vaccines amid cover-up claims (named for the inlet-bordered region where that conflict was fought).', a: 'Gulf War syndrome', category: 'government', difficulty: 5 },
      { q: 'Nazi Germany’s secret state police, a recurring shorthand for totalitarian surveillance in conspiracy writing (the feared force’s common contracted name).', a: 'Gestapo', category: 'government', difficulty: 4 },
      { q: 'Oleg, the senior KGB officer in London who secretly spied for British intelligence through the 1970s–80s before a dramatic exfiltration (surname).', a: 'Gordievsky', category: 'government', difficulty: 5, alt: ['Oleg Gordievsky'] },
    ],
    H: [
      { q: 'Reclusive billionaire who fronted the CIA’s 1974 submarine-recovery cover story (full name).', a: 'Howard Hughes', category: 'government', difficulty: 4 },
      { q: 'Surname of the long-serving FBI director, J. Edgar, whose Bureau ran decades of domestic surveillance.', a: 'Hoover', category: 'government', difficulty: 3 },
      { q: 'L. Ron ___ founded the church behind the 1970s “Snow White” infiltration of U.S. agencies (surname).', a: 'Hubbard', category: 'secret-society', difficulty: 5 },
      { q: 'Robert ___ — the FBI agent unmasked in 2001 as a long-time mole for Moscow (surname).', a: 'Hanssen', category: 'government', difficulty: 5, alt: ['Robert Hanssen'] },
      { q: 'Seymour ___ — the investigative journalist whose 1974 reporting forced the CIA’s “Family Jewels” into public view (surname).', a: 'Hersh', category: 'government', difficulty: 5, alt: ['Seymour Hersh'] },
      { q: 'Richard ___ — the CIA director convicted of misleading Congress, who had ordered the destruction of the agency’s mind-control research files (surname).', a: 'Helms', category: 'government', difficulty: 5, alt: ['Richard Helms'] },
      { q: 'UFO legend names a specific numbered aircraft shelter at an Ohio air base as the storage place for crashed-saucer wreckage; give that famed shelter (the building word + the number 18).', a: 'Hangar 18', category: 'ufo', difficulty: 5 },
      { q: 'Rudolf ___ — the deputy Führer whose 1941 solo flight to Britain and later prison death spawned body-double and cover-up theories (surname).', a: 'Hess', category: 'government', difficulty: 5, alt: ['Rudolf Hess'] },
      { q: 'CIA cryptonym for its illegal Cold War mail-opening program that secretly read citizens’ overseas letters; oddly, it echoes a language word (the codename, “HT-___”).', a: 'HTLINGUAL', category: 'government', difficulty: 5 },
    ],
    I: [
      { q: '1980s scandal in which arms were secretly sold to Tehran to fund Nicaraguan rebels (the two-part hyphenated scandal name).', a: 'Iran-Contra affair', category: 'government', difficulty: 4 },
      { q: 'Small Washington software firm whose PROMIS case-tracking program the Justice Department was found to have stolen.', a: 'Inslaw', category: 'government', difficulty: 5 },
      { q: 'Middle Eastern nation whose elected premier was deposed and whose monarch was restored by a 1953 CIA coup.', a: 'Iran', category: 'government', difficulty: 3 },
      { q: 'PROMIS-software theft case aside; the act of secretly placing agents within a target organization, as Scientology did to U.S. agencies, is termed this (a noun for clandestine penetration).', a: 'Infiltration', category: 'secret-society', difficulty: 4 },
      { q: 'Aerial spy plane shot down over the USSR in 1960 was on a reconnaissance flight — gathering this, the product spy agencies exist to collect (the “int” word, a noun for gathered secret knowledge).', a: 'Intelligence', category: 'government', difficulty: 4 },
      { q: 'Satirical 1967 book, often mistaken for a real leaked study, arguing that permanent peace would destabilize society; it was named for a fictional secret think-tank location (“Report from ___ Mountain”).', a: 'Iron Mountain', category: 'hoax', difficulty: 5 },
      { q: 'Soviet cipher clerk in Ottawa whose 1945 defection exposed Stalin’s atomic-spy rings and helped open the Cold War (full name).', a: 'Igor Gouzenko', category: 'government', difficulty: 5, alt: ['Gouzenko'] },
      { q: '444-day ordeal beginning in 1979 when revolutionaries seized the U.S. embassy in Tehran, the backdrop to the alleged “October Surprise” (three words: the captor nation, the captives, and an emergency).', a: 'Iran hostage crisis', category: 'government', difficulty: 4, alt: ['Hostage crisis'] },
      { q: 'Country whose Mossad agents staged the 1954 false-flag bombings in Egypt (the Lavon Affair) and figure in countless covert-op theories (the nation).', a: 'Israel', category: 'government', difficulty: 4 },
    ],
    J: [
      { q: 'Surname of the President (Lyndon) who escalated the Vietnam War after the 1964 naval-incident reports.', a: 'Johnson', category: 'government', difficulty: 3 },
      { q: 'CIA counterintelligence chief, first-named after a biblical apostle, whose paranoid mole-hunts gripped the agency (full name).', a: 'James Angleton', category: 'government', difficulty: 5, alt: ['Angleton'] },
      { q: 'Highland New Mexico Apache community near the alleged underground alien base, lending its Spanish name to ranch UFO lore.', a: 'Jicarilla', category: 'ufo', difficulty: 5 },
      { q: 'The CIA’s 1973 internal catalogue of misdeeds was nicknamed for these treasured family heirlooms (the gem-word, plural).', a: 'Jewels', category: 'government', difficulty: 5, alt: ['Family Jewels'] },
      { q: 'Air Force general who, with the FBI director, formulated the secret Alaska stay-behind plan and became the first head of the DIA (full name).', a: 'Joseph Carroll', category: 'government', difficulty: 5, alt: ['Carroll'] },
      { q: 'Guyana settlement where over 900 followers of a charismatic preacher died in a 1978 mass poisoning, a tragedy long linked to mind-control speculation (the place name).', a: 'Jonestown', category: 'paranormal', difficulty: 4 },
      { q: 'Reagan national-security adviser convicted, then cleared on appeal, over the arms-for-hostages affair (full name).', a: 'John Poindexter', category: 'government', difficulty: 5, alt: ['Poindexter'] },
      { q: 'The U.S. top military command body whose 1962 staff drafted the rejected false-flag Northwoods plan against Cuba (two words: a togetherness adjective + the leaders “of Staff”).', a: 'Joint Chiefs', category: 'government', difficulty: 5 },
      { q: 'Nightclub owner who shot dead the accused presidential assassin Lee Harvey Oswald on live television in 1963 (full name).', a: 'Jack Ruby', category: 'assassination', difficulty: 5, alt: ['Ruby'] },
    ],
    K: [
      { q: 'Soviet-era state security committee whose acronym is shorthand for Cold War spycraft.', a: 'KGB', category: 'government', difficulty: 3 },
      { q: 'Henry ___ — the diplomat whose name recurs across Operation Condor and 1970s coup claims (surname).', a: 'Kissinger', category: 'government', difficulty: 4 },
      { q: 'Ruling family dynasty of North Korea, woven into Cold War disinformation lore (the dynasty’s surname).', a: 'Kim dynasty', category: 'government', difficulty: 4 },
      { q: 'Soviet republic hosting the secret nuclear test ground nicknamed “the Polygon,” near Semipalatinsk (the country).', a: 'Kazakhstan', category: 'government', difficulty: 5 },
      { q: 'President assassinated in 1963 who had personally rejected the false-flag Northwoods proposal a year earlier (surname).', a: 'Kennedy', category: 'assassination', difficulty: 4 },
      { q: 'British intelligence officer revealed as the most damaging of the Cambridge Five spies for Moscow (full name; first name is a girl’s and a boy’s alike).', a: 'Kim Philby', category: 'government', difficulty: 5, alt: ['Philby'] },
      { q: 'Russian nuclear submarine that sank with all hands in 2000, its loss trailed by official cover-up accusations (the boat’s name, shared with a great 1943 tank-battle Russian city).', a: 'Kursk', category: 'government', difficulty: 5 },
      { q: 'Jamal ___ — the Saudi journalist murdered inside his country’s Istanbul consulate in 2018, a killing tied to the highest levels of his government (surname).', a: 'Khashoggi', category: 'assassination', difficulty: 5, alt: ['Jamal Khashoggi'] },
      { q: 'CIA cryptonym titling its declassified 1963 counterintelligence interrogation manual, a grim document of Cold War coercion methods (the codeword, used as the manual’s name).', a: 'KUBARK', category: 'government', difficulty: 5 },
    ],
    L: [
      { q: '1954 Israeli false-flag scandal in Egypt, in which agents bombed Western targets to be blamed on locals (named for a defense minister).', a: 'Lavon Affair', category: 'government', difficulty: 5 },
      { q: '1957–58 U.S. Army “Large Area Coverage” trials that dispersed particles over cities to study aerosol spread (the three-letter acronym).', a: 'LAC', category: 'government', difficulty: 5 },
      { q: 'Mind-altering drug, abbreviated by three letters, secretly given to unwitting subjects in CIA safehouse stings (the chemical’s full chemical name).', a: 'Lysergic acid diethylamide', category: 'government', difficulty: 5, alt: ['LSD'] },
      { q: 'Licio Gelli led a clandestine masonic chapter, “P2,” whose hidden roster shook Italy in 1981; a masonic local chapter is generically called one of these (a four-letter fraternal-branch noun).', a: 'Lodge', category: 'secret-society', difficulty: 5, alt: ['Masonic lodge'] },
      { q: 'Alexander ___ — the defected ex-KGB officer fatally poisoned with polonium-210 in London in 2006, a cause célèbre of state-assassination claims (surname).', a: 'Litvinenko', category: 'assassination', difficulty: 5, alt: ['Alexander Litvinenko'] },
      { q: 'U.S. Air Force general (surname) and CIA man who ran the anti-Castro sabotage program Operation Mongoose; first-named Edward.', a: 'Lansdale', category: 'government', difficulty: 5, alt: ['Edward Lansdale'] },
      { q: 'U.S. Navy intelligence ship attacked by Israeli forces in 1967, the incident shrouded in cover-up allegations (the vessel’s name, a synonym for freedom; the “USS ___”).', a: 'Liberty', category: 'government', difficulty: 5, alt: ['USS Liberty'] },
      { q: 'Scottish town over which Pan Am Flight 103 was bombed in 1988, its investigation and verdict long disputed by conspiracy theorists (the place name).', a: 'Lockerbie', category: 'government', difficulty: 5 },
      { q: 'Moscow building that served as KGB headquarters and a notorious prison, its very name a Cold War byword for the secret police (the structure).', a: 'Lubyanka', category: 'government', difficulty: 5 },
    ],
    M: [
      { q: 'Alleged secret committee of twelve said to manage recovered-craft secrets, of disputed-document fame (“___ 12”).', a: 'Majestic', category: 'ufo', difficulty: 5 },
      { q: 'Long Island Air Force–station legend of time-travel and mind-control experiments, named for the seaside hamlet at its location (the place name).', a: 'Montauk', category: 'paranormal', difficulty: 5, alt: ['Montauk Project'] },
      { q: '1961–62 covert U.S. campaign of sabotage and assassination plots against Castro’s Cuba (codenamed for a snake-killing mammal).', a: 'Mongoose', category: 'government', difficulty: 5 },
      { q: 'CIA biological-agent stockpile program run with the Army, sharing a woman’s-name suffix with its parent project (“MK-___”).', a: 'MK-Naomi', category: 'government', difficulty: 5 },
      { q: 'A darker sister-program for operational covert dosing of unwitting targets, named with a Greek letter (“MK-___”).', a: 'MKDELTA', category: 'government', difficulty: 5 },
      { q: 'San Francisco safehouse sting where sex workers lured men to be secretly dosed with LSD, its codename pairing the witching hour with a peak moment (two words).', a: 'Midnight Climax', category: 'government', difficulty: 5 },
      { q: 'Iran’s elected premier (first name Mohammad), ousted by the 1953 coup the operation was built to bring down (surname).', a: 'Mosaddegh', category: 'government', difficulty: 5 },
      { q: 'Israel’s national intelligence service, blamed in countless covert-operation theories worldwide (its short Hebrew-derived name).', a: 'Mossad', category: 'government', difficulty: 4 },
      { q: 'Afghan rebels armed by the CIA’s 1980s Operation Cyclone against Soviet forces (the Arabic-derived term for these holy-war fighters).', a: 'Mujahideen', category: 'government', difficulty: 4 },
      { q: 'The metallic element whose seafloor nodules the Glomar Explorer pretended to harvest as cover for raising a Soviet sub (the metal, symbol Mn).', a: 'Manganese', category: 'government', difficulty: 5 },
      { q: 'Donald ___ — one of the Cambridge spy ring who, with Guy Burgess, defected to Moscow in 1951 (surname).', a: 'Maclean', category: 'government', difficulty: 5, alt: ['Donald Maclean'] },
    ],
    N: [
      { q: '1962 Joint Chiefs proposal to stage false attacks on Americans to justify war with Cuba, rejected by the president (a wooded-direction codename).', a: 'Northwoods', category: 'government', difficulty: 5 },
      { q: 'Surname of the Marine colonel (Oliver) at the center of the 1980s arms-for-hostages affair — also a compass direction.', a: 'North', category: 'government', difficulty: 4 },
      { q: 'The CIA toxin program “MK-___” took its suffix from this biblical woman’s name.', a: 'Naomi', category: 'government', difficulty: 5 },
      { q: 'Reinhard Gehlen recycled veterans of this defeated German regime into West German intelligence (the regime’s common one-word label, plural).', a: 'Nazis', category: 'government', difficulty: 4 },
      { q: 'Alliance whose secret “stay-behind” armies across Cold War Europe were exposed in 1990 (the Western military pact’s four-letter acronym).', a: 'NATO', category: 'government', difficulty: 4 },
      { q: 'Mineral lumps on the deep seabed that the Glomar Explorer pretended to be mining as its submarine-salvage cover (the word for these small rounded ore deposits, plural).', a: 'Nodules', category: 'government', difficulty: 5 },
      { q: 'U.S. signals-intelligence agency, target of Snowden’s 2013 disclosures, jokingly back-named “No Such Agency” (its three-letter acronym).', a: 'NSA', category: 'government', difficulty: 4 },
      { q: 'Soviet-developed military nerve-agent class used in the 2018 Salisbury poisoning of a defector, central to state-assassination claims (the Russian-named toxin, meaning “newcomer”).', a: 'Novichok', category: 'assassination', difficulty: 5 },
      { q: 'First name of the Kuwaiti girl whose tearful, later-discredited 1990 U.S. congressional testimony about incubators helped sell the Gulf War — a PR fabrication (her given name).', a: 'Nayirah', category: 'hoax', difficulty: 5 },
    ],
    O: [
      { q: 'Marine colonel tried over the Iran arms-and-rebel-funds affair (full name).', a: 'Oliver North', category: 'government', difficulty: 4, alt: ['North'] },
      { q: 'Mega-conspiracy nickname journalist Danny Casolaro gave the alleged web linking software theft, banks, and spies (an eight-armed sea creature).', a: 'Octopus', category: 'government', difficulty: 5 },
      { q: 'Soviet 1920s–30s secret police that preceded the KGB and was impersonated by the 1924 British forged letter (the four-letter acronym).', a: 'OGPU', category: 'government', difficulty: 5 },
      { q: 'Swedish prime minister shot dead in a Stockholm street in 1986, his unsolved killing a magnet for conspiracy theories (full name).', a: 'Olof Palme', category: 'assassination', difficulty: 5, alt: ['Palme'] },
      { q: 'Aerial defoliation campaign over Vietnam, dispersing herbicide to strip jungle cover; its codename evoked a cattle spread and a farmhand (two words).', a: 'Operation Ranch Hand', category: 'government', difficulty: 5, alt: ['Ranch Hand'] },
      { q: 'WWII U.S. intelligence agency, led by “Wild Bill” Donovan, that was the direct forerunner of the CIA (the three-letter acronym, “Office of Strategic Services”).', a: 'OSS', category: 'government', difficulty: 4 },
      { q: 'CIA codename for the top-secret A-12 reconnaissance aircraft program of the 1960s, a precursor to the SR-71 (the codename, evoking a slow ox-drawn wagon).', a: 'Oxcart', category: 'government', difficulty: 5 },
      { q: 'Alleged secret 1980 deal to delay the release of the Iran hostages until after the U.S. election, helping Reagan win (a two-word phrase for a late campaign bombshell).', a: 'October Surprise', category: 'government', difficulty: 5 },
      { q: 'U.S. city whose 1995 federal-building bombing by domestic extremists spawned a thicket of cover-up and “second-bomb” theories (the city, capital of its state).', a: 'Oklahoma City', category: 'government', difficulty: 4 },
    ],
    P: [
      { q: 'Vietnam-era CIA counterinsurgency campaign of capture, interrogation, and assassination of suspected organizers (a fire-bird codename).', a: 'Phoenix Program', category: 'government', difficulty: 5 },
      { q: 'Secret Italian masonic lodge, “Propaganda Due,” that scandalized 1981 Italy (its short two-character designation).', a: 'P2', category: 'secret-society', difficulty: 5 },
      { q: '1971 leaked study revealing the hidden history of America’s Vietnam policy, named for the U.S. defense headquarters building.', a: 'Pentagon Papers', category: 'government', difficulty: 4 },
      { q: 'Alleged DARPA time-travel and teleportation program of fringe lore, said to involve Andrew Basiago (a winged-horse codename).', a: 'Pegasus', category: 'paranormal', difficulty: 5 },
      { q: 'Inslaw’s case-tracking software, allegedly stolen and back-doored by the Justice Department (the program’s five-letter name).', a: 'PROMIS', category: 'government', difficulty: 5 },
      { q: 'Secret Soviet nuclear test ground in Kazakhstan, known by this fortification-shaped nickname (“the ___”).', a: 'Polygon', category: 'government', difficulty: 5 },
      { q: 'Francis Gary ___ — the airman whose 1960 shoot-down over the USSR exposed the high-altitude reconnaissance flights (surname).', a: 'Powers', category: 'government', difficulty: 5, alt: ['Francis Gary Powers'] },
      { q: 'Post-WWII U.S. program that secretly brought German rocket and weapons scientists, some ex-Nazis, into American service (codenamed for an office fastener).', a: 'Paperclip', category: 'government', difficulty: 5 },
      { q: 'Rare radioactive element used to fatally poison a defected ex-KGB officer in London in 2006, traced back to a state laboratory (the element, symbol Po).', a: 'Polonium', category: 'assassination', difficulty: 5 },
    ],
    R: [
      { q: '1962–71 U.S. defoliation campaign over Vietnam, pairing a farming word with a property where cattle are raised (the codename’s two words).', a: 'Ranch Hand', category: 'government', difficulty: 5 },
      { q: 'Claimed psychic ability to perceive faraway places with the mind alone, the focus of the Stargate intelligence effort (two words, the second meaning “seeing”).', a: 'Remote viewing', category: 'paranormal', difficulty: 5 },
      { q: 'Surname (Ronald) of the U.S. president whose administration was rocked by the arms-for-hostages-and-rebels affair.', a: 'Reagan', category: 'government', difficulty: 3 },
      { q: 'Mohammad ___ Pahlavi, the Iranian monarch the 1953 coup returned to power (his dynastic middle name, also a Persian royal title).', a: 'Reza', category: 'government', difficulty: 5, alt: ['Reza Pahlavi'] },
      { q: 'The 1979 uprising that toppled the U.S.-installed Shah and ended the Pahlavi dynasty restored in 1953 (a noun for a violent overthrow of a regime).', a: 'Revolution', category: 'government', difficulty: 4, alt: ['Iranian Revolution'] },
      { q: 'West Germany’s early intelligence chief, an ex-Wehrmacht general whose private spy network became the BND (full name).', a: 'Reinhard Gehlen', category: 'government', difficulty: 5, alt: ['Gehlen'] },
      { q: 'Aircraft brought down over Soviet airspace in 1960; the broader Cold War practice of gathering enemy secrets by overflight and listening posts goes by this term (a noun for military scouting and observation).', a: 'Reconnaissance', category: 'government', difficulty: 4 },
      { q: 'Idaho mountain site of a deadly 1992 federal siege of the Weaver family, a rallying cry for distrust of the government (the two-word place name).', a: 'Ruby Ridge', category: 'government', difficulty: 5 },
      { q: 'Julius and Ethel ___ — the American couple executed in 1953 for passing atomic secrets to Moscow, their guilt long debated (surname).', a: 'Rosenbergs', category: 'government', difficulty: 5, alt: ['Rosenberg'] },
      { q: 'Greenpeace ship sunk in a New Zealand harbor by French secret-service agents in 1985, killing a photographer (the vessel’s name, evoking a colorful sky arc and a fighter).', a: 'Rainbow Warrior', category: 'government', difficulty: 5 },
    ],
    S: [
      { q: '1972 U.S. Army/DIA program studying psychic “remote viewing” for spying (named for a celestial-body gateway).', a: 'Stargate', category: 'paranormal', difficulty: 5 },
      { q: '1950 U.S. Navy test that secretly released bacteria over San Francisco to model a biological attack (a coastal-mist codename).', a: 'Sea-Spray', category: 'government', difficulty: 5 },
      { q: 'Church of Scientology’s 1970s campaign to infiltrate federal agencies and destroy files, named for a wintry fairy tale.', a: 'Snow White', category: 'secret-society', difficulty: 5 },
      { q: 'East Germany’s feared Ministry for State Security, its short name a byword for total surveillance.', a: 'Stasi', category: 'government', difficulty: 4 },
      { q: 'CIA chemist (first name a city on the Thames) who oversaw the agency’s drug, poison, and behavioral research — the so-called “poisoner in chief” (full name).', a: 'Sidney Gottlieb', category: 'government', difficulty: 5, alt: ['Gottlieb'] },
      { q: 'Royal Persian title, “King of Kings,” held by the U.S.-backed monarch the 1953 coup restored.', a: 'Shah', category: 'government', difficulty: 4 },
      { q: 'Kazakh city beside the secret Soviet nuclear test ground nicknamed “the Polygon,” where hundreds of bombs were detonated (the test-site city’s name).', a: 'Semipalatinsk', category: 'government', difficulty: 5 },
      { q: 'Sergei ___ — the former Russian double-agent poisoned with a nerve agent in Salisbury, England, in 2018 (surname).', a: 'Skripal', category: 'assassination', difficulty: 5, alt: ['Sergei Skripal'] },
      { q: 'Edward, the NSA contractor who in 2013 leaked the scale of secret mass surveillance, then fled abroad (surname).', a: 'Snowden', category: 'government', difficulty: 4, alt: ['Edward Snowden'] },
      { q: 'Lockheed’s legendary secret advanced-aircraft division behind the U-2 and the A-12, nicknamed after a smelly black-and-white animal’s comic-strip moonshine factory (two words).', a: 'Skunk Works', category: 'government', difficulty: 5 },
      { q: 'Stanford Research Institute, the California lab where the government funded its 1970s psychic remote-viewing experiments, is abbreviated by these three letters.', a: 'SRI', category: 'paranormal', difficulty: 5 },
    ],
    T: [
      { q: 'Gulf off Vietnam where the disputed 1964 naval clash gave Congress its escalation pretext (the gulf’s name).', a: 'Tonkin', category: 'government', difficulty: 4 },
      { q: 'British social-science body, founded 1947, that fringe theory accuses of mass psychological manipulation (named for a London district known for its square).', a: 'Tavistock Institute', category: 'secret-society', difficulty: 5 },
      { q: '1932–72 unethical Alabama research that withheld syphilis treatment from Black men, named for the institute that hosted it (the place name).', a: 'Tuskegee', category: 'government', difficulty: 4, alt: ['Tuskegee study'] },
      { q: 'CIA cryptonym for the 1953 Iran coup, a two-letter prefix joined to a Greek hero’s name (the full code word).', a: 'TPAJAX', category: 'government', difficulty: 5 },
      { q: 'Jeweled Persian royal seat, named for a colorful fan-tailed bird, that the CIA restored a monarch to in 1953 (the seat itself, a four-letter word for a king’s chair).', a: 'Throne', category: 'government', difficulty: 5, alt: ['Peacock Throne'] },
      { q: 'Andrew Basiago claims he was a child participant in an alleged DARPA program for moving through the fourth dimension — that of duration itself (a four-letter noun for what clocks measure).', a: 'Time travel', category: 'paranormal', difficulty: 5 },
      { q: 'Soviet espionage practice and craft of secret agent work — dead drops, brush passes, and disguises — a term beloved of spy-conspiracy writers (one word, “trade-” plus a skill noun).', a: 'Tradecraft', category: 'government', difficulty: 4 },
      { q: 'Iranian capital where the 1953 CIA/MI6 coup unfolded, restoring the Shah to power (the city).', a: 'Tehran', category: 'government', difficulty: 4 },
      { q: 'U.S. president who signed the 1947 act creating the CIA, the agency at the heart of so many later conspiracy claims (surname).', a: 'Truman', category: 'government', difficulty: 4, alt: ['Harry Truman'] },
      { q: 'Toxic metallic element the CIA once plotted to dust into Castro’s shoes to make his iconic beard fall out (the poison, symbol Tl).', a: 'Thallium', category: 'government', difficulty: 5 },
    ],
    U: [
      { q: '1960 affair in which a high-altitude American spy plane was downed over Soviet airspace; name the aircraft by its letter-number designation.', a: 'U-2', category: 'government', difficulty: 4, alt: ['U-2 incident'] },
      { q: '1946 secret U.K.–U.S. signals-intelligence accord underpinning global communications interception (the country-pair name).', a: 'UKUSA Agreement', category: 'government', difficulty: 5 },
      { q: 'Cold War rival superpower, dissolved in 1991, whose spies recur across deception lore (the federation’s full long-form name).', a: 'Union of Soviet Socialist Republics', category: 'government', difficulty: 5, alt: ['Soviet Union', 'USSR'] },
      { q: 'A person dosed or tested in secret without their consent, as in the LSD safehouse stings, is described as this kind of victim — kept unaware of what was done to them (a seven-letter adjective for “unknowing”).', a: 'Unwitting', category: 'government', difficulty: 5 },
      { q: 'The Stargate effort and MK-Naomi alike involved this — undisclosed federal trials run on people, condemned as a betrayal of medical consent (a two-word phrase for off-the-books research; “unethical ___”).', a: 'Unauthorized testing', category: 'government', difficulty: 5 },
      { q: 'Imperial Japanese Army biological- and chemical-warfare detachment that conducted lethal human experiments in WWII, its records reportedly shielded by a postwar U.S. deal (the secret outfit’s designation: the squad word + the number 731).', a: 'Unit 731', category: 'government', difficulty: 5 },
      { q: 'U.S. Navy warship whose 1898 explosion in Havana harbor — “Remember the ___!” — pushed America into war with Spain amid lasting false-flag suspicion (the ship’s name, a New England state).', a: 'USS Maine', category: 'government', difficulty: 5, alt: ['Maine'] },
      { q: 'Israeli self-styled psychic, famous for spoon-bending, who was tested for paranormal abilities under the U.S. military’s remote-viewing research at SRI (full name).', a: 'Uri Geller', category: 'paranormal', difficulty: 5, alt: ['Geller'] },
      { q: 'Radioactive metal whose forged “yellowcake” purchase documents — supposedly an Iraq–Niger deal — were used to justify the 2003 war (the element, symbol U).', a: 'Uranium', category: 'government', difficulty: 5 },
    ],
    W: [
      { q: '1951–59 secret FBI/Air Force plan to plant “stay-behind” agents in Alaska against a Soviet invasion (an operation named for a laundry tub).', a: 'Washtub', category: 'government', difficulty: 5 },
      { q: 'Caspar ___ — the Reagan defense secretary indicted then pardoned over the arms-for-hostages affair (surname).', a: 'Weinberger', category: 'government', difficulty: 5 },
      { q: 'Cold War democratic state, partitioned from its communist twin, whose foreign-intelligence BND grew from Reinhard Gehlen’s ex-Wehrmacht spy network (the country, in its divided-era name).', a: 'West Germany', category: 'government', difficulty: 5, alt: ['Germany'] },
      { q: 'Covert interception of phone calls, a staple of the FBI surveillance abuses catalogued in the “Family Jewels” (the eavesdropping practice on phone lines, one compound word).', a: 'Wiretapping', category: 'government', difficulty: 5, alt: ['Wiretaps'] },
      { q: 'CIA director who in 1973 ordered the compilation of the agency’s “Family Jewels” catalogue of abuses (full name).', a: 'William Colby', category: 'government', difficulty: 5, alt: ['Colby'] },
      { q: 'German rocket engineer brought to the U.S. under Operation Paperclip who went on to lead NASA’s moon-rocket effort (full name).', a: 'Wernher von Braun', category: 'government', difficulty: 5, alt: ['von Braun'] },
      { q: '1993 deadly federal siege of a Texas religious compound, a touchstone for anti-government conspiracy movements (the place name, near Mount Carmel).', a: 'Waco', category: 'government', difficulty: 4 },
      { q: 'Chinese city home to a virology institute at the center of the lab-leak debate over the COVID-19 pandemic’s origin (the city).', a: 'Wuhan', category: 'government', difficulty: 4 },
      { q: 'The kind of insider who exposes secret wrongdoing, like the analyst who leaked the Pentagon Papers (the term for such a leaker — a referee’s noisemaker joined to one who reveals).', a: 'Whistleblower', category: 'government', difficulty: 4 },
    ],
    Z: [
      { q: '1924 forgery, attributed to a Communist International chairman, that damaged Britain’s Labour party before an election (the document, named for its supposed author).', a: 'Zinoviev Letter', category: 'government', difficulty: 5 },
      { q: 'Surname (Grigory) of the Bolshevik Comintern head a notorious 1924 British forgery impersonated.', a: 'Zinoviev', category: 'government', difficulty: 5 },
      { q: 'Conspiracy lore’s nickname for a heavily restricted off-limits secret site, such as a test ground (a four-letter geometric-region word, “the ___”).', a: 'Zone', category: 'urban-legend', difficulty: 5 },
      { q: 'East German secret-police tactic of covertly “decomposing” a target’s life — sabotaging relationships and sanity to break dissidents without arrest (the German term, literally “decomposition”).', a: 'Zersetzung', category: 'government', difficulty: 5 },
      { q: 'CIA codename for the 1961 amphibious invasion of Cuba at the Bay of Pigs, taken from a nearby Cuban swamp region (the operation’s name).', a: 'Zapata', category: 'government', difficulty: 5, alt: ['Operation Zapata'] },
      { q: 'Pakistani military ruler killed in a still-unexplained 1988 plane crash that also took the U.S. ambassador, fueling sabotage theories (his surname, “___-ul-Haq”).', a: 'Zia-ul-Haq', category: 'assassination', difficulty: 5, alt: ['Zia'] },
      { q: 'Ernst ___ — the Canadian-based Holocaust-denial publisher whose trials became a focus of far-right disinformation networks (surname).', a: 'Zündel', category: 'hoax', difficulty: 5, alt: ['Ernst Zundel'] },
    ],
  },
};
