import type { RawPack } from '../core/packs';

export const cyclingPack: RawPack = {
  id: 'cycling',
  name: 'Cycling',
  description: 'Grand tours, great riders, mountain passes and the machine itself.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🚴',
  accent: '#eab308',
  letters: {
    A: [
      { q: 'The Frenchman who was the first to win the Tour five times.', a: 'Anquetil' },
      { q: 'The Dutch one-day race that finishes above Valkenburg in April.', a: 'Amstel Gold' },
      { q: 'The Alpine climb of twenty-one numbered hairpins above Bourg d Oisans.', a: 'Alpe d Huez' },
      { q: 'The sudden effort by which a rider tries to leave the group behind.', a: 'Attack' },
      { q: 'The extensions clamped to a time trial bar, on which the elbows rest.', a: 'Aero bars' },
      { q: 'The American stripped of seven Tour titles in 2012.', a: 'Armstrong' },
      { q: 'The Kazakh team in sky blue, founded in 2006.', a: 'Astana' },
      { q: 'The Belgian hills whose week of classics ends at Liege.', a: 'Ardennes' },
      { q: 'The Belgian town that hosted the Liege finish for years, a suburb on a hill.', a: 'Ans' },
      { q: 'The Italian who was world champion in 1968 and later a famous commentator.', a: 'Adorni' },
      { q: 'The light metal that replaced steel in racing frames in the 1980s.', a: 'Aluminium' },
    ],
    B: [
      { q: 'The Italian of the 1930s and 40s whose rivalry with Coppi split his country.', a: 'Bartali' },
      { q: 'The French word, used everywhere, for the rider water bottle.', a: 'Bidon' },
      { q: 'The bearing assembly in which the cranks turn, at the base of the frame.', a: 'Bottom bracket' },
      { q: 'The escape that gets clear of the bunch and stays away.', a: 'Breakaway' },
      { q: 'The Italian who won the Giro twice and the 2006 edition by nine minutes.', a: 'Basso' },
      { q: 'The Belgian who won Flanders three times and Roubaix four, a cobbles specialist.', a: 'Boonen' },
      { q: 'The lever and caliper that slow the wheel.', a: 'Brake' },
      { q: 'The time awarded at a mid-stage line, which can decide a close overall lead.', a: 'Bonus seconds' },
      { q: 'The Briton who broke the hour record in 1996 in a crouched superman position.', a: 'Boardman' },
      { q: 'The mass finish of the entire field at forty miles an hour.', a: 'Bunch sprint' },
      { q: 'The Italian who won the 2004 Olympic road race and two world titles, Paolo of that surname.', a: 'Bettini' },
      { q: 'The German team in green and black for which Sagan rode after 2017.', a: 'Bora' },
    ],
    C: [
      { q: 'The Italian campionissimo who won the Giro and Tour double twice.', a: 'Coppi' },
      { q: 'The stone-paved sectors of the north that decide the Hell of the North.', a: 'Cobbles' },
      { q: 'The block of sprockets on the rear hub.', a: 'Cassette' },
      { q: 'The arm that carries the pedal and turns the chainset.', a: 'Crank' },
      { q: 'The winter discipline of muddy laps, hurdles and running with the bike.', a: 'Cyclocross' },
      { q: 'The Spaniard who won all three grand tours between 2007 and 2015.', a: 'Contador' },
      { q: 'The Manxman with more Tour stage wins than anyone.', a: 'Cavendish' },
      { q: 'The linked loop that carries the drive to the back wheel.', a: 'Chain' },
      { q: 'The pedalling rate, in revolutions a minute.', a: 'Cadence' },
      { q: 'The official in the car who enforces the rules and hands out fines.', a: 'Commissaire' },
      { q: 'The Swiss time trial and cobbles star nicknamed Spartacus.', a: 'Cancellara' },
      { q: 'The Italian sprinter of the 1990s called the Lion King, Mario of that surname.', a: 'Cipollini' },
      { q: 'The toothed front wheel over which the chain runs.', a: 'Chainring' },
    ],
    D: [
      { q: 'The Spaniard who won the 1988 Tour and the 1985 Vuelta.', a: 'Delgado' },
      { q: 'The mechanism that moves the chain from one sprocket to the next.', a: 'Derailleur' },
      { q: 'The team rider whose whole job is to serve the leader.', a: 'Domestique' },
      { q: 'The plunge off a pass, tucked in at over eighty kilometres an hour.', a: 'Descent' },
      { q: 'The Frenchman who ran the race for decades from the paper that founded it.', a: 'Desgrange' },
      { q: 'The riding in the shelter of the rider ahead, which saves a third of the effort.', a: 'Drafting' },
      { q: 'The taking of banned substances, which scarred the sport for two decades.', a: 'Doping' },
      { q: 'The Dutchman who won the 2017 Giro after a famous roadside stop.', a: 'Dumoulin' },
      { q: 'The team boss who drives behind and shouts the tactics.', a: 'Directeur sportif' },
      { q: 'The curved bar shape of a road machine, gripped low for speed.', a: 'Drop bar' },
      { q: 'The mountain bike discipline raced entirely down the slope against the clock.', a: 'Downhill' },
      { q: 'The French Alpine week-long race in June, a dress rehearsal for July.', a: 'Dauphine' },
    ],
    E: [
      { q: 'The diagonal line riders form to shelter each other in a crosswind.', a: 'Echelon' },
      { q: 'The blood-boosting hormone abused through the 1990s, three letters.', a: 'EPO' },
      { q: 'The getting clear of the bunch by a small group.', a: 'Escape' },
      { q: 'The French word for one day leg of a stage race.', a: 'Etape' },
      { q: 'The Belgian prodigy who won the Vuelta in 2022 and the world title the same year.', a: 'Evenepoel' },
      { q: 'The Australian who won the 2011 Tour, the first from his country.', a: 'Evans' },
      { q: 'The pedal-assisted machine that has transformed city riding.', a: 'Electric bike' },
      { q: 'The capacity to keep going for six hours, the first quality a professional needs.', a: 'Endurance' },
      { q: 'The Tuscan vintage ride on white gravel roads, held every October.', a: 'Eroica' },
    ],
    F: [
      { q: 'The Briton who won the Tour four times between 2013 and 2017.', a: 'Froome' },
      { q: 'The Belgian region of short cobbled hills and April racing.', a: 'Flanders' },
      { q: 'The bare frame and forks, before any parts are fitted.', a: 'Frameset' },
      { q: 'The pair of blades that hold the front wheel.', a: 'Fork' },
      { q: 'The Frenchman with the ponytail who won the Tour in 1983 and 1984.', a: 'Fignon' },
      { q: 'The stretch of road where riders collect a cloth bag of food.', a: 'Feed zone' },
      { q: 'The red triangle hung over the road one kilometre from the line.', a: 'Flamme rouge' },
      { q: 'The track machine with no coasting and no brakes.', a: 'Fixed gear' },
      { q: 'The Spanish sprinter who won three world road titles between 1999 and 2004, Oscar of that surname.', a: 'Freire' },
      { q: 'The ratchet that lets the rear wheel spin on while the pedals are still.', a: 'Freewheel' },
      { q: 'The Flemish word for a rider who thrives on cobbles, wind and rain.', a: 'Flandrien' },
    ],
    G: [
      { q: 'The Italian who won the 1965 Tour and rode all his career against Merckx.', a: 'Gimondi' },
      { q: 'The ratio between the chainring and the sprocket.', a: 'Gear' },
      { q: 'The collective name for the three-week races of France, Italy and Spain.', a: 'Grand tour' },
      { q: 'The mass amateur ride over a professional route, an Italian term.', a: 'Gran fondo' },
      { q: 'The top worn by the leader of the points competition in France.', a: 'Green jersey' },
      { q: 'The Italian three-week race, held in May.', a: 'Giro' },
      { q: 'The complete set of shifters, brakes and derailleurs from one maker.', a: 'Groupset' },
      { q: 'The steepness of a climb, given as a percentage.', a: 'Gradient' },
      { q: 'The German sprinter nicknamed the Gorilla, winner of eleven Tour stages.', a: 'Greipel' },
      { q: 'The Belgian who won the 2012 world title and all the Ardennes races.', a: 'Gilbert' },
      { q: 'The distance in seconds between one rider and the next on the road.', a: 'Gap' },
    ],
    H: [
      { q: 'The Frenchman known as the Badger, winner of five Tours.', a: 'Hinault' },
      { q: 'The Flemish word for the short steep climbs of the north.', a: 'Hellingen' },
      { q: 'The shell made compulsory in professional road racing in 2003.', a: 'Helmet' },
      { q: 'The bar the rider holds to steer.', a: 'Handlebar' },
      { q: 'The short front frame member in which the steerer turns.', a: 'Head tube' },
      { q: 'The solo attempt to ride as far as possible in sixty minutes on a track.', a: 'Hour record' },
      { q: 'The centre of the wheel, on which it spins.', a: 'Hub' },
      { q: 'The Norwegian who took the green jersey in 2005 and 2009 and the world title in 2010.', a: 'Hushovd' },
      { q: 'The category four rise that is barely more than a bump.', a: 'Hill' },
      { q: 'The American classics rider who started seventeen Tours, George of that surname.', a: 'Hincapie' },
    ],
    I: [
      { q: 'The Spaniard who won five Tours in a row from 1991.', a: 'Indurain' },
      { q: 'The British team that grew out of Sky and now carries a chemical company name.', a: 'Ineos' },
      { q: 'The extra line partway through a stage, worth points and bonus time.', a: 'Intermediate sprint' },
      { q: 'The rubber bladder inside the tyre.', a: 'Inner tube' },
      { q: 'The race against the clock ridden alone, as against the team version.', a: 'Individual time trial' },
      { q: 'The Middle Eastern squad that rides as Premier Tech and once signed Froome.', a: 'Israel' },
    ],
    J: [
      { q: 'The coloured top that marks the leader of a classification.', a: 'Jersey' },
      { q: 'The Frenchman who won the Tour points jersey in 1992 and 1995, later a mountains winner.', a: 'Jalabert' },
      { q: 'The Dutch team, sponsored by a supermarket, that won all three grand tours in 2023.', a: 'Jumbo' },
      { q: 'The explosive acceleration a sprinter makes in the last two hundred metres.', a: 'Jump' },
      { q: 'The Australian squad in green, named after a caravan maker.', a: 'Jayco' },
    ],
    K: [
      { q: 'The Irishman who won the 1988 Vuelta and four Tour points jerseys.', a: 'Kelly' },
      { q: 'The cobbled Flemish ramp climbed three times in the Ronde.', a: 'Kwaremont' },
      { q: 'The unit in which every stage is measured.', a: 'Kilometre' },
      { q: 'The German sprinter who won four stages in a single Tour twice over.', a: 'Kittel' },
      { q: 'The Dutch climber who led the 2016 Giro until a crash on a snowbank.', a: 'Kruijswijk' },
      { q: 'The Belgian town whose one-day race follows the opening weekend classic.', a: 'Kuurne' },
    ],
    L: [
      { q: 'The American who won the 1986 Tour, the first from his country.', a: 'LeMond' },
      { q: 'The Belgian city that starts and ends the oldest of the classics.', a: 'Liege' },
      { q: 'The rider at the top of the general classification.', a: 'Leader' },
      { q: 'The affectionate title of the last rider on the overall standings.', a: 'Lanterne rouge' },
      { q: 'The teammate who tows the sprinter to within metres of the line.', a: 'Lead-out' },
      { q: 'The stretchy fabric of every racing kit since the 1980s.', a: 'Lycra' },
      { q: 'The Italian autumn classic of the falling leaves, around a northern lake.', a: 'Lombardia' },
      { q: 'The American stripped of the 2006 Tour after a positive test.', a: 'Landis' },
      { q: 'The Basque climber Mikel of that surname, a fixture in grand tour top tens.', a: 'Landa' },
    ],
    M: [
      { q: 'The Belgian called the Cannibal, winner of eleven grand tours.', a: 'Merckx' },
      { q: 'The first great classic of the season, from a northern Italian city to the coast.', a: 'Milan-Sanremo' },
      { q: 'The bare Provencal giant climbed from Bedoin, where Tom Simpson died.', a: 'Mont Ventoux' },
      { q: 'The team helper who changes a wheel from the following car.', a: 'Mechanic' },
      { q: 'The cloth shoulder bag of food handed up in the feed zone.', a: 'Musette' },
      { q: 'The French name for the yellow leader top.', a: 'Maillot jaune' },
      { q: 'The rider who thrives when the road tilts up for twenty kilometres.', a: 'Mountain specialist' },
      { q: 'The German who won four world time trial titles, Tony of that surname.', a: 'Martin' },
      { q: 'The Spanish climber Enric of that surname, twice runner-up in the Vuelta.', a: 'Mas' },
      { q: 'The Spanish team in dark blue that has raced under many sponsors since 1980.', a: 'Movistar' },
    ],
    N: [
      { q: 'The Italian called the Shark, winner of all three grand tours.', a: 'Nibali' },
      { q: 'The rolled-out first kilometres behind the lead car, before racing starts.', a: 'Neutral zone' },
      { q: 'The Colombian who won the 2014 Giro and the 2016 Vuelta, first name of Quintana.', a: 'Nairo' },
      { q: 'The Italian sprinter who wore the Giro points top without winning a stage.', a: 'Nizzolo' },
      { q: 'The following car that carries spare wheels for any rider of any team.', a: 'Neutral support' },
      { q: 'The science of eating and drinking enough while racing for six hours.', a: 'Nutrition' },
    ],
    O: [
      { q: 'The Spaniard whose duel with Merckx ended with a crash on the Mente in 1971.', a: 'Ocana' },
      { q: 'The full name of the Flemish ramp climbed three times each Ronde.', a: 'Oude Kwaremont' },
      { q: 'The standing on total time that decides the winner of a stage race.', a: 'Overall classification' },
      { q: 'The four-yearly games at which both road and track medals are decided.', a: 'Olympics' },
      { q: 'The race decided in a single day, as against a stage race.', a: 'One-day race' },
      { q: 'The lubricant dripped onto the chain before every ride.', a: 'Oil' },
    ],
    P: [
      { q: 'The Italian climber who won the Giro and Tour in 1998 and died in 2004.', a: 'Pantani' },
      { q: 'The cobbled classic that ends on an open velodrome in the north of France.', a: 'Paris-Roubaix' },
      { q: 'The platform on which the foot presses.', a: 'Pedal' },
      { q: 'The main bunch of riders, from the French for platoon.', a: 'Peloton' },
      { q: 'The flat tyre that can cost a rider the race.', a: 'Puncture' },
      { q: 'The Slovenian who won the Tour in 2020, 2021 and 2024.', a: 'Pogacar' },
      { q: 'The effort measured in watts by a crank-mounted meter.', a: 'Power' },
      { q: 'The raised stage on which the top three are presented.', a: 'Podium' },
      { q: 'The short time trial that opens some grand tours.', a: 'Prologue' },
      { q: 'The French word for the cobbled stones of the north.', a: 'Pave' },
      { q: 'The Italian sprinter who took twenty-two Giro stage wins, Alessandro of that surname.', a: 'Petacchi' },
      { q: 'The track event in which two riders start on opposite sides and chase each other.', a: 'Pursuit' },
    ],
    Q: [
      { q: 'The Colombian of Combita who won the 2014 Giro and the 2016 Vuelta.', a: 'Quintana' },
      { q: 'The Belgian team of Patrick Lefevere, famous for its sprinters and classics men.', a: 'Quick-Step' },
      { q: 'The lever that opens the axle so a wheel can be changed in seconds.', a: 'Quick release' },
    ],
    R: [
      { q: 'The Irishman who won the Giro, the Tour and the world title all in 1987.', a: 'Roche' },
      { q: 'The northern French town whose velodrome ends the cobbled classic.', a: 'Roubaix' },
      { q: 'The Flemish name for the Tour of Flanders.', a: 'Ronde' },
      { q: 'The metal hoop that carries the tyre.', a: 'Rim' },
      { q: 'The Slovenian who won three Vueltas in a row from 2019.', a: 'Roglic' },
      { q: 'The day off in the middle of a three-week race.', a: 'Rest day' },
      { q: 'The striped top worn for a year by the world champion.', a: 'Rainbow jersey' },
      { q: 'The French word for the strong all-day rider who is neither climber nor sprinter.', a: 'Rouleur' },
      { q: 'The Catalan climber nicknamed Purito, Joaquim of that surname.', a: 'Rodriguez' },
    ],
    S: [
      { q: 'The Briton who collapsed and died on the bare Provencal mountain in 1967.', a: 'Simpson' },
      { q: 'The seat on which the rider sits.', a: 'Saddle' },
      { q: 'The Slovak who won the green competition seven times and three world titles.', a: 'Sagan' },
      { q: 'The wire that connects hub to rim.', a: 'Spoke' },
      { q: 'The single day leg of a three-week race.', a: 'Stage' },
      { q: 'The British team that won seven Tours in eight years in pale blue.', a: 'Sky' },
      { q: 'The stage that ends at the top of a mountain, where most grand tours are decided.', a: 'Summit finish' },
      { q: 'The all-out effort for the line.', a: 'Sprint' },
      { q: 'The Japanese maker of most of the gears in the world.', a: 'Shimano' },
      { q: 'The team masseur who works on tired legs every evening.', a: 'Soigneur' },
      { q: 'The pocket of still air behind a moving rider.', a: 'Slipstream' },
      { q: 'The Belgian squad of Lefevere now carries this Australian door brand.', a: 'Soudal' },
    ],
    T: [
      { q: 'The Welshman who won the 2018 edition of the French race.', a: 'Thomas' },
      { q: 'The three-week French race founded in 1903.', a: 'Tour de France' },
      { q: 'The banked oval on which the sprint and the pursuit are raced.', a: 'Track' },
      { q: 'The rubber ring that meets the road.', a: 'Tyre' },
      { q: 'The spell a rider spends at the front before swinging aside.', a: 'Turn' },
      { q: 'The stage in which a whole squad rides against the clock together.', a: 'Team time trial' },
      { q: 'The passionate Italian fans who crowd the mountain roads.', a: 'Tifosi' },
      { q: 'The wind at your back, which turns a hard stage into a fast one.', a: 'Tailwind' },
      { q: 'The steady hard rhythm just below the limit, ridden for an hour.', a: 'Tempo' },
      { q: 'The Dutch cobbles specialist who won Roubaix in 2014, Niki of that surname.', a: 'Terpstra' },
      { q: 'The American frame maker whose name is carried by a WorldTour squad.', a: 'Trek' },
    ],
    U: [
      { q: 'The German who won the 1997 Tour and finished second five times.', a: 'Ullrich' },
      { q: 'The world governing body of the sport, three initials.', a: 'UCI' },
      { q: 'The Emirati team for which Pogacar rides.', a: 'UAE Team Emirates' },
      { q: 'The Colombian from Urrao who finished runner-up in the 2017 Tour.', a: 'Uran' },
      { q: 'The direction of travel that separates climbers from sprinters.', a: 'Uphill' },
    ],
    V: [
      { q: 'The Dane who won the French race in 2022 and 2023.', a: 'Vingegaard' },
      { q: 'The banked arena of the winter six-day meetings.', a: 'Velodrome' },
      { q: 'The Spanish three-week race, whose leader wears red.', a: 'Vuelta' },
      { q: 'The Belgian all-rounder Wout, a winner in the mountains, the sprints and the cross.', a: 'Van Aert' },
      { q: 'The Spaniard who raced into his forties and won the 2018 world title.', a: 'Valverde' },
      { q: 'The Dutchman Mathieu, grandson of a French great, who wins on road and mud alike.', a: 'Van der Poel' },
      { q: 'The Frenchman who wore yellow for ten days in 2004 and again in 2011.', a: 'Voeckler' },
      { q: 'The Frenchman who won the Tour mountains prize seven times, Richard of that surname.', a: 'Virenque' },
    ],
    W: [
      { q: 'The Briton who won the 2012 Tour and Olympic gold weeks later.', a: 'Wiggins' },
      { q: 'The round part that turns on the hub.', a: 'Wheel' },
      { q: 'The annual title race whose winner earns the rainbow bands.', a: 'World Championship' },
      { q: 'The unit of power in which every effort is now measured.', a: 'Watts' },
      { q: 'The Belgian who has won Lombardia and the Ardennes classics, Tim of that name.', a: 'Wellens' },
      { q: 'The rider who never comes to the front, in the unkind slang of the bunch.', a: 'Wheelsucker' },
    ],
    Y: [
      { q: 'The colour of the top worn by the leader of the French race.', a: 'Yellow jersey' },
      { q: 'The British twins, Simon and Adam, who have both won a grand tour or a podium.', a: 'Yates' },
      { q: 'The classification for riders under twenty-six, marked by a white top.', a: 'Young rider' },
      { q: 'The English county that staged the 2014 Grand Depart and the 2019 world titles.', a: 'Yorkshire' },
    ],
    Z: [
      { q: 'The Dutchman who finished the French race sixteen times and won it in 1980.', a: 'Zoetemelk' },
      { q: 'The German who took the green competition six years in a row from 1996.', a: 'Zabel' },
      { q: 'The indoor platform on which professionals now race each other virtually.', a: 'Zwift' },
    ],
  },
};
