import type { RawPack } from '../core/packs';

export const dancePack: RawPack = {
  id: 'dance',
  name: 'Dance & Ballet',
  description: 'Steps, styles, great ballets and the dancers who made them famous.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🩰',
  accent: '#be185d',
  letters: {
    A: [
      { q: 'The pose on one leg with the other stretched straight out behind.', a: 'Arabesque' },
      { q: 'The musical direction for fast, lively steps in a ballet class.', a: 'Allegro' },
      { q: 'The slow controlled section that opens a classical duet.', a: 'Adagio' },
      { q: 'The pose on one leg with the raised knee bent, as in the Mercury statue.', a: 'Attitude' },
      { q: 'The jump in which both feet leave the floor together and land together.', a: 'Assemble' },
      { q: 'The British choreographer of La Fille mal gardee and Cinderella, knighted in 1962.', a: 'Ashton' },
      { q: 'The Russian whose Dying Swan solo made her the most famous dancer of her age.', a: 'Anna Pavlova' },
      { q: 'The Balanchine work of 1928 in which the god of music leads three muses.', a: 'Apollo' },
      { q: 'The Hollywood partner of Ginger Rogers, in top hat and tails.', a: 'Astaire' },
      { q: 'The Cuban prima who founded her national company and danced almost blind.', a: 'Alicia Alonso' },
      { q: 'The American whose company, founded in 1958, made Revelations its signature.', a: 'Ailey' },
      { q: 'The princess whose Rose Adagio in Act One tests every classical ballerina.', a: 'Aurora' },
    ],
    B: [
      { q: 'The wooden rail a dancer holds for the first half of every class.', a: 'Barre' },
      { q: 'The Russian-born founder of the New York City company, who made plotless works.', a: 'Balanchine' },
      { q: 'The great Moscow theatre and its company, whose name means grand.', a: 'Bolshoi' },
      { q: 'The female principal of a classical company.', a: 'Ballerina' },
      { q: 'The quick step on the balls of the feet that travels across the floor.', a: 'Bourree' },
      { q: 'The oldest classical dance form of Tamil Nadu, with sharp geometric poses.', a: 'Bharatanatyam' },
      { q: 'The Ravel score of 1928 built on one long repeated rhythm, danced by Bejart.', a: 'Bolero' },
      { q: 'The category that covers waltz, foxtrot, tango and quickstep together.', a: 'Ballroom' },
      { q: 'The Latvian who defected in 1974 and became the biggest star in America.', a: 'Baryshnikov' },
      { q: 'The German who founded Tanztheater Wuppertal and filled her stages with soil and water.', a: 'Bausch' },
      { q: 'The Petipa ballet set in India, whose Kingdom of the Shades is a test of a corps.', a: 'Bayadere' },
      { q: 'The company Diaghilev ran from 1909, which turned Paris upside down.', a: 'Ballets Russes' },
    ],
    C: [
      { q: 'The art of composing steps and patterns for the stage.', a: 'Choreography' },
      { q: 'The body of dancers who move as one behind the principals.', a: 'Corps de ballet' },
      { q: 'The Delibes ballet of 1870 about a doll that seems to come alive.', a: 'Coppelia' },
      { q: 'The Cuban ballroom dance named for the rhythm of its three quick steps.', a: 'Cha-cha' },
      { q: 'The broad modern style that grew out of and against the older modern school.', a: 'Contemporary' },
      { q: 'The American radical who used chance procedures and worked with John Cage.', a: 'Cunningham' },
      { q: 'The high-kicking Parisian music-hall number of the 1890s.', a: 'Can-can' },
      { q: 'The fast brilliant finale of a classical duet, after the two solos.', a: 'Coda' },
      { q: 'The Brazilian martial art danced to the berimbau, born among enslaved Africans.', a: 'Capoeira' },
      { q: 'The Italian whose strict method became one of the standard teaching systems.', a: 'Cecchetti' },
      { q: 'The series of small linked turns travelling in a straight line.', a: 'Chaines' },
      { q: 'The 1920s craze danced with flapping arms and kicking heels, named for a US city.', a: 'Charleston' },
      { q: 'The line dance in which everyone holds the waist ahead and kicks on the fourth beat.', a: 'Conga' },
      { q: 'The Prokofiev ballet of a lost slipper and a bell at midnight.', a: 'Cinderella' },
    ],
    D: [
      { q: 'A number danced by exactly two people.', a: 'Duet' },
      { q: 'The slow unfolding of the working leg from the knee to full stretch.', a: 'Developpe' },
      { q: 'The Russian impresario who brought Nijinsky and Stravinsky to Paris.', a: 'Diaghilev' },
      { q: 'The string of short showpiece numbers with no plot, often in Act Three.', a: 'Divertissement' },
      { q: 'The Minkus ballet of the Spanish knight, famous for its fan-and-fouette duet.', a: 'Don Quixote' },
      { q: 'The mirror-balled floor style of the mid-1970s and Saturday Night Fever.', a: 'Disco' },
      { q: 'The French painter who made hundreds of studies of the Paris Opera rehearsal room.', a: 'Degas' },
      { q: 'The whirling Sufi of Konya, who turns as an act of worship.', a: 'Dervish' },
      { q: 'The American barefoot pioneer who danced in a Greek tunic and scorned pointe shoes.', a: 'Duncan' },
      { q: 'The Saint-Saens solo made for Pavlova, in which a bird slowly dies.', a: 'Dying Swan' },
    ],
    E: [
      { q: 'The jump in which the legs cross and beat in the air before landing.', a: 'Entrechat' },
      { q: 'The angling of head and shoulders that gives a classical pose its life.', a: 'Epaulement' },
      { q: 'The whole group of performers taken together.', a: 'Ensemble' },
      { q: 'The height a dancer reaches in a jump, and the ability to hang there.', a: 'Elevation' },
      { q: 'Dancing on the tips of the toes in blocked shoes.', a: 'En pointe' },
      { q: 'A linked sequence of steps set by a teacher in class.', a: 'Enchainement' },
      { q: 'The rank of principal at the Paris Opera, French for star.', a: 'Etoile' },
      { q: 'How high a dancer can lift and hold the working leg.', a: 'Extension' },
      { q: 'The body position turned obliquely away from the audience, French for shaded.', a: 'Efface' },
      { q: 'The Perrot ballet after Victor Hugo, about a gypsy girl in medieval Paris.', a: 'Esmeralda' },
    ],
    F: [
      { q: 'The Andalusian style of guitar, song, hand-clapping and stamping heels.', a: 'Flamenco' },
      { q: 'The whipping turn on one leg of which Odile does thirty-two in a row.', a: 'Fouette' },
      { q: 'The smooth gliding ballroom dance in slow-quick-quick time.', a: 'Foxtrot' },
      { q: 'The British ballerina, partner of Nureyev, created a dame in 1956.', a: 'Fonteyn' },
      { q: 'The American whose jazz style of bowler hats and turned-in knees shaped Chicago.', a: 'Fosse' },
      { q: 'The traditional dancing of a region, passed on outside the theatre.', a: 'Folk dance' },
      { q: 'The Stravinsky ballet of 1910 about a magical bird and an ogre.', a: 'Firebird' },
      { q: 'The Spanish courtship dance in triple time, with castanets.', a: 'Fandango' },
      { q: 'The class exercise in which the foot strikes the floor and springs out sharply.', a: 'Frappe' },
      { q: 'The basic stance with heels together and toes turned out, numbered one.', a: 'First position' },
    ],
    G: [
      { q: 'The Adolphe Adam ballet of 1841 about a peasant girl who dies and returns as a ghost.', a: 'Giselle' },
      { q: 'The big travelling leap that splits the legs in the air.', a: 'Grand jete' },
      { q: 'The Ukrainian folk dance of squats, leaps and heel clicks.', a: 'Gopak' },
      { q: 'The American matriarch of modern dance, whose technique is built on contraction.', a: 'Graham' },
      { q: 'The small linking step that glides from one position into a jump.', a: 'Glissade' },
      { q: 'The stately French court dance in four-four, with a little hop.', a: 'Gavotte' },
      { q: 'The big controlled kick of the straight leg to the front, side or back.', a: 'Grand battement' },
      { q: 'The Hollywood star who sang and tapped through a downpour in 1952.', a: 'Gene Kelly' },
      { q: 'The one-off charity or celebration performance of mixed highlights.', a: 'Gala' },
    ],
    H: [
      { q: 'The street style born in the Bronx in the 1970s, with popping and locking.', a: 'Hip hop' },
      { q: 'The lively solo of British sailors, danced with arms folded.', a: 'Hornpipe' },
      { q: 'The Hawaiian dance that tells a story with swaying hips and hands.', a: 'Hula' },
      { q: 'The Cuban dance in two-four whose rhythm crossed to Spain and to Bizet.', a: 'Habanera' },
      { q: 'The Scottish solo danced on the spot with arms curved above the head.', a: 'Highland fling' },
      { q: 'The 1970s partner disco style revived by the film with John Travolta.', a: 'Hustle' },
      { q: 'The Maori ceremonial challenge of stamping, chanting and slapping.', a: 'Haka' },
      { q: 'The American country dance called at speed by a caller, with a fiddle band.', a: 'Hoedown' },
      { q: 'The commedia character in a diamond-patterned suit, danced in many ballets.', a: 'Harlequin' },
      { q: 'The American modern pioneer whose theory of movement was fall and recovery.', a: 'Humphrey' },
    ],
    I: [
      { q: 'Making up movement on the spot rather than performing set steps.', a: 'Improvisation' },
      { q: 'The style of rigid arms and flying feet, taken worldwide by Riverdance.', a: 'Irish step dance' },
      { q: 'The name of the Russian company and school before the revolution.', a: 'Imperial Ballet' },
      { q: 'The jazz-class trick of moving one part of the body while the rest stays still.', a: 'Isolation' },
      { q: 'The turning-in of the working leg, the opposite of the classical stance.', a: 'Inward rotation' },
    ],
    J: [
      { q: 'The fast bouncy ballroom dance of the rock-and-roll era, in six-eight.', a: 'Jive' },
      { q: 'Any leap from one foot onto the other, French for thrown.', a: 'Jete' },
      { q: 'The theatre style of Broadway, born from ragtime and swing.', a: 'Jazz dance' },
      { q: 'The lively Irish and Scottish folk dance in six-eight time.', a: 'Jig' },
      { q: 'The Chicago-born choreographer whose American company still tours under his name.', a: 'Joffrey' },
      { q: 'The wartime swing craze of lifts and throws, danced to big bands.', a: 'Jitterbug' },
      { q: 'The splayed open palms held out flat in Broadway show style.', a: 'Jazz hands' },
    ],
    K: [
      { q: 'The north Indian classical form of spinning turns and bell-covered ankles.', a: 'Kathak' },
      { q: 'The Japanese theatre of stylised movement, white make-up and male actors.', a: 'Kabuki' },
      { q: 'The name the Saint Petersburg company carried through the Soviet years.', a: 'Kirov' },
      { q: 'The aggressive hip-hop battle style of exaggerated arm swings, born in Los Angeles.', a: 'Krump' },
      { q: 'The Angolan partner dance of slow close steps that spread through Lisbon.', a: 'Kizomba' },
      { q: 'The Kerala dance drama of towering headdresses, green paint and all-night stories.', a: 'Kathakali' },
    ],
    L: [
      { q: 'The close-fitting one-piece garment worn for class, named after a French acrobat.', a: 'Leotard' },
      { q: 'The move in which one partner raises the other clear off the floor.', a: 'Lift' },
      { q: 'The formation dance in which everyone faces the same way and repeats a sequence.', a: 'Line dance' },
      { q: 'The Mexican-born American whose modern technique is built on fall and recovery.', a: 'Limon' },
      { q: 'The Harlem swing dance of the 1930s, named after a famous flight.', a: 'Lindy hop' },
      { q: 'The system of symbols invented in 1928 to write movement down.', a: 'Labanotation' },
      { q: 'The Fokine ballet of moonlit sylphs in white, set to Chopin.', a: 'Les Sylphides' },
      { q: 'The Brazilian craze of 1989, danced hip to hip in a forbidden style.', a: 'Lambada' },
      { q: 'The funk style of freezing suddenly in the middle of a movement.', a: 'Locking' },
    ],
    M: [
      { q: 'The Polish dance in triple time with a stamp on the second beat.', a: 'Mazurka' },
      { q: 'The slow stately court dance of the 18th century in three-four.', a: 'Minuet' },
      { q: 'The barefoot American school of Graham, Humphrey and Limon.', a: 'Modern dance' },
      { q: 'The Dominican dance of quick limping steps in two-four.', a: 'Merengue' },
      { q: 'The silent acting by which a classical ballet tells its plot.', a: 'Mime' },
      { q: 'The Kirov ballerina who defected in London in 1970 and starred in New York.', a: 'Makarova' },
      { q: 'The Cuban style of the 1940s that came between rumba and cha-cha.', a: 'Mambo' },
      { q: 'The big circle of jumps or turns a soloist makes round the stage.', a: 'Manege' },
      { q: 'The gliding backwards step Michael Jackson showed the world in 1983.', a: 'Moonwalk' },
      { q: 'The stage form in which song, story and dance carry the plot together.', a: 'Musical' },
      { q: 'The Ballets Russes choreographer of Parade and Le Tricorne.', a: 'Massine' },
    ],
    N: [
      { q: 'The Tchaikovsky ballet of a toy soldier, a rat king and a snowy journey.', a: 'Nutcracker' },
      { q: 'The Russian star of the Ballets Russes who choreographed the Rite of Spring.', a: 'Nijinsky' },
      { q: 'The Tatar-born dancer who defected in Paris in 1961 and partnered Fonteyn.', a: 'Nureyev' },
      { q: 'The sister of that Russian star, who made Les Noces and Les Biches.', a: 'Nijinska' },
      { q: 'The company Balanchine and Kirstein founded in 1948 at Lincoln Center.', a: 'New York City Ballet' },
      { q: 'The character numbers of a country, adapted for the classical stage.', a: 'National dances' },
    ],
    O: [
      { q: 'The white swan queen of the Tchaikovsky lakeside ballet.', a: 'Odette' },
      { q: 'The black-clad daughter of the sorcerer who tricks the prince in that same ballet.', a: 'Odile' },
      { q: 'The Cranko ballet after Pushkin, in which a letter is torn up twice.', a: 'Onegin' },
      { q: 'The orchestral opening played before the curtain rises.', a: 'Overture' },
      { q: 'The early ballroom fashion of the 1910s, a single move to each beat of a march.', a: 'One-step' },
      { q: 'The Israeli who led Batsheva and invented the Gaga movement language.', a: 'Ohad Naharin' },
    ],
    P: [
      { q: 'The blocked slipper that lets a dancer rise onto the tips of the toes.', a: 'Pointe shoe' },
      { q: 'The classical duet of entry, two solos and a fast finish.', a: 'Pas de deux' },
      { q: 'The bending of the knees with which every class begins.', a: 'Plie' },
      { q: 'The complete turn of the body on one supporting leg.', a: 'Pirouette' },
      { q: 'The Frenchman who ruled the Russian stage and made Swan Lake and Sleeping Beauty.', a: 'Petipa' },
      { q: 'The bouncy Bohemian dance in two-four that swept Europe in the 1840s.', a: 'Polka' },
      { q: 'The light springing jump named after the step of a cat.', a: 'Pas de chat' },
      { q: 'The Spanish ballroom dance in which the man plays the bullfighter.', a: 'Paso doble' },
      { q: 'The carriage and movement of the arms in classical technique.', a: 'Port de bras' },
      { q: 'The highest rank in a classical company, above soloist.', a: 'Principal' },
      { q: 'The meringue dessert named after the Russian ballerina who toured Australasia.', a: 'Pavlova' },
      { q: 'The Stravinsky ballet of a puppet who comes to life at a Russian fair.', a: 'Petrushka' },
    ],
    Q: [
      { q: 'The fastest of the standard ballroom dances, full of hops and runs.', a: 'Quickstep' },
      { q: 'The square set dance for four couples, popular in Napoleonic ballrooms.', a: 'Quadrille' },
    ],
    R: [
      { q: 'The slow Cuban ballroom dance of swaying hips in four-four.', a: 'Rumba' },
      { q: 'The class exercise that traces a circle on the floor with the pointed foot.', a: 'Rond de jambe' },
      { q: 'The working practice in the studio before a performance.', a: 'Rehearsal' },
      { q: 'The staff member who teaches the company its steps and keeps the standard.', a: 'Repetiteur' },
      { q: 'The Prokofiev ballet of the Verona lovers, with its heavy Dance of the Knights.', a: 'Romeo and Juliet' },
      { q: 'The Stravinsky score of 1913 whose first night ended in a riot.', a: 'Rite of Spring' },
      { q: 'The American who made West Side Story and Fancy Free.', a: 'Robbins' },
      { q: 'The precision kick line that has played Radio City since 1932.', a: 'Rockettes' },
      { q: 'The Scottish and Irish country dance in quick duple time.', a: 'Reel' },
      { q: 'The film partner who did everything Astaire did, backwards and in heels.', a: 'Rogers' },
      { q: 'The 1994 Eurovision interval act that became a global Irish show.', a: 'Riverdance' },
    ],
    S: [
      { q: 'The Tchaikovsky ballet in which a prince swears love to the wrong woman.', a: 'Swan Lake' },
      { q: 'The Latin club dance of New York Puerto Ricans, danced on one or on two.', a: 'Salsa' },
      { q: 'The Brazilian carnival dance of quick bouncing steps in two-four.', a: 'Samba' },
      { q: 'The Petipa ballet in which Aurora pricks her finger and sleeps a century.', a: 'Sleeping Beauty' },
      { q: 'The jump from two feet to one, named after a French scissor movement.', a: 'Sissonne' },
      { q: 'The 1930s big-band style of triple steps and rock steps.', a: 'Swing' },
      { q: 'The Russian composer of Firebird, Petrushka and the score that caused a riot.', a: 'Stravinsky' },
      { q: 'The Khachaturian ballet of a slave revolt, a Bolshoi showpiece since 1968.', a: 'Spartacus' },
      { q: 'The village girl who dresses up as the doll in the Delibes ballet.', a: 'Swanilda' },
      { q: 'The trick of fixing the eyes on one point to keep from getting dizzy in turns.', a: 'Spotting' },
      { q: 'The American folk form for four couples, guided by a caller.', a: 'Square dance' },
      { q: 'The Greek line dance of slow steps quickening, made famous by a 1964 film.', a: 'Sirtaki' },
      { q: 'The 1920s move of shaking the shoulders while the hips stay still.', a: 'Shimmy' },
      { q: 'The mirrored room with a sprung floor where a company works.', a: 'Studio' },
    ],
    T: [
      { q: 'The stiff or soft skirt of layered net worn by a classical dancer.', a: 'Tutu' },
      { q: 'The dance of Buenos Aires, of close embrace and sudden pauses.', a: 'Tango' },
      { q: 'The style danced in metal-plated shoes for rhythm as much as for looks.', a: 'Tap' },
      { q: 'The outward rotation of the legs from the hip that all classical work rests on.', a: 'Turnout' },
      { q: 'The whirling southern Italian dance said to cure a spider bite.', a: 'Tarantella' },
      { q: 'The 1960s craze of swivelling hips with no partner contact at all.', a: 'Twist' },
      { q: 'The Greek muse of dance and chorus.', a: 'Terpsichore' },
      { q: 'The close-fitting legwear that every dancer puts on before class.', a: 'Tights' },
      { q: 'The jump that makes a full turn in the air before landing, French for in the air.', a: 'Tour en lair' },
      { q: 'The country and western couple dance of quick-quick-slow-slow.', a: 'Two-step' },
      { q: 'The Russian composer of the three great classical scores of the 19th century.', a: 'Tchaikovsky' },
      { q: 'The Italian romantic ballerina who created La Sylphide in 1832.', a: 'Taglioni' },
    ],
    U: [
      { q: 'The Bolshoi ballerina, born 1910, whose Giselle was called the greatest of the century.', a: 'Ulanova' },
      { q: 'The direction away from the audience, at the back of the playing area.', a: 'Upstage' },
      { q: 'Dancing exactly together, every body doing the same thing at the same time.', a: 'Unison' },
      { q: 'The partner move in which the joined hands pass above the head.', a: 'Underarm turn' },
    ],
    V: [
      { q: 'The solo section of a classical duet, danced by one performer.', a: 'Variation' },
      { q: 'The Leningrad teacher whose method became the Russian standard, published in 1934.', a: 'Vaganova' },
      { q: 'The fast whirling ballroom dance in three-four, at sixty bars a minute.', a: 'Viennese waltz' },
      { q: 'The Harlem ballroom style of poses and dips, born in the drag scene.', a: 'Voguing' },
      { q: 'The first name of the Ballets Russes star who leapt in Le Spectre de la Rose.', a: 'Vaslav' },
    ],
    W: [
      { q: 'The oldest of the standard ballroom dances, in three-four with a rise and fall.', a: 'Waltz' },
      { q: 'The gentle work at the start of a class that prepares the muscles.', a: 'Warm-up' },
      { q: 'The 1970s Los Angeles style of whipping arm rotations to disco records.', a: 'Waacking' },
      { q: 'The Bernstein and Robbins musical that set Shakespeare on a New York street.', a: 'West Side Story' },
      { q: 'The ghost maidens of the second act of the 1841 romantic ballet.', a: 'Wilis' },
      { q: 'The side spaces of a stage from which dancers enter.', a: 'Wings' },
      { q: 'The British choreographer of Chroma, resident at the Royal Opera House.', a: 'Wayne McGregor' },
    ],
    X: [
      { q: 'The Tsonga dance of South Africa performed in a thick fringed skirt.', a: 'Xibelani' },
    ],
    Y: [
      { q: 'The Chinese folk dance of drums, ribbons and stilts, seen at new year.', a: 'Yangge' },
      { q: 'The French ballerina, born 1917, remembered as the great Giselle of Paris.', a: 'Yvette Chauvire' },
      { q: 'The young dancer in the corps, still working up to a solo.', a: 'Youngest member' },
    ],
    Z: [
      { q: 'The Colombian-born fitness class that turned Latin rhythms into a workout.', a: 'Zumba' },
      { q: 'The rapid Spanish heel-stamping technique of flamenco.', a: 'Zapateado' },
      { q: 'The Cretan character whose 1964 film dance is really the sirtaki.', a: 'Zorba' },
    ],
  },
};
