import type { RawPack } from '../core/packs';

export const dinosaursPack: RawPack = {
  id: 'dinosaurs',
  name: 'Dinosaurs & Fossils',
  description: 'Prehistoric giants, the people who found them and the ages they lived in.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '🦖',
  accent: '#15803d',
  letters: {
    A: [
      { q: 'The most common large predator in the Late Jurassic Morrison Formation of the western United States.', a: 'Allosaurus' },
      { q: 'The heavily armoured Cretaceous plant-eater famous for the bony club on the end of its tail.', a: 'Ankylosaurus' },
      { q: 'This Jurassic sauropod\'s name means "deceptive lizard", and it was long confused with Brontosaurus.', a: 'Apatosaurus' },
      { q: 'The feathered animal from Bavarian limestone, first described in 1861, often called the earliest known bird.', a: 'Archaeopteryx' },
      { q: 'A titanosaur from South America that is among the largest land animals ever discovered.', a: 'Argentinosaurus' },
      { q: 'The coiled, spiral-shelled sea molluscs whose remains fill Jurassic rocks and which vanished with the dinosaurs.', a: 'Ammonite' },
      { q: 'Fossilised tree resin, prized because it can trap insects and feathers in three dimensions.', a: 'Amber' },
      { q: 'The Canadian province home to Dinosaur Provincial Park and the Royal Tyrrell Museum.', a: 'Alberta' },
      { q: 'A smaller North American relative of Tyrannosaurus, named after a Canadian province.', a: 'Albertosaurus' },
      { q: 'A South American sauropod with a double row of tall spines running along its neck.', a: 'Amargasaurus' },
      { q: 'The huge space rock whose impact at Chicxulub is blamed for the end of the dinosaur age.', a: 'Asteroid' },
      { q: 'A crow-sized Jurassic Chinese dinosaur whose plumage colours were reconstructed as grey with a reddish crest.', a: 'Anchiornis' },
      { q: 'The frozen continent where the crested predator Cryolophosaurus was discovered.', a: 'Antarctica' },
    ],
    B: [
      { q: 'This Jurassic giant held its head high on a steeply sloping neck, with front legs longer than its hind legs.', a: 'Brachiosaurus' },
      { q: 'A famous sauropod name declared invalid for decades before a 2015 study revived it.', a: 'Brontosaurus' },
      { q: 'A fish-eating British dinosaur found in Surrey in 1983, known for the huge hooked claw on its thumb.', a: 'Baryonyx' },
      { q: 'The term for an animal that walks on two legs, as all theropods did.', a: 'Bipedal' },
      { q: 'Modern members of this group are the only dinosaurs still alive today.', a: 'Birds' },
      { q: 'The American Museum of Natural History collector who unearthed the first Tyrannosaurus skeleton in 1902.', a: 'Barnum Brown' },
      { q: 'The country where dozens of Iguanodon skeletons were dug out of a coal mine at Bernissart in 1878.', a: 'Belgium' },
      { q: 'The German region whose Solnhofen limestone yields exquisitely preserved Jurassic fossils.', a: 'Bavaria' },
      { q: 'This Canadian rock unit from the Cambrian preserves soft-bodied animals such as Anomalocaris.', a: 'Burgess Shale' },
      { q: 'Despite a name meaning "king lizard", this Eocene giant turned out to be an early whale.', a: 'Basilosaurus' },
      { q: 'The name given to the fierce 19th-century fossil-hunting rivalry between Cope and Marsh.', a: 'Bone Wars' },
    ],
    C: [
      { q: 'The last period of the Mesozoic, ending 66 million years ago.', a: 'Cretaceous' },
      { q: 'The scientific name for fossilised dung.', a: 'Coprolite' },
      { q: 'A chicken-sized Jurassic predator from Germany, once thought to be the smallest dinosaur.', a: 'Compsognathus' },
      { q: 'A short-snouted South American predator with a pair of blunt horns above its eyes and very short arms.', a: 'Carnotaurus' },
      { q: 'This African giant predator\'s name refers to teeth like those of a great white shark.', a: 'Carcharodontosaurus' },
      { q: 'The buried crater on Mexico\'s Yucatan Peninsula marking the impact at the end of the Cretaceous.', a: 'Chicxulub' },
      { q: 'The country whose Liaoning Province produced the first widely accepted feathered dinosaur fossils.', a: 'China' },
      { q: 'The period beginning about 539 million years ago whose "explosion" saw most animal groups appear.', a: 'Cambrian' },
      { q: 'The group name for the horned, frilled plant-eating dinosaurs.', a: 'Ceratopsian' },
      { q: 'A slender Triassic predator found by the hundreds at Ghost Ranch in New Mexico.', a: 'Coelophysis' },
      { q: 'The period known for vast coal swamps and giant insects, long before the dinosaurs.', a: 'Carboniferous' },
      { q: 'An Early Jurassic Antarctic predator with a crest running crosswise above its eyes.', a: 'Cryolophosaurus' },
      { q: 'The most abundant sauropod of the Morrison Formation, shorter-necked than Diplodocus.', a: 'Camarasaurus' },
    ],
    D: [
      { q: 'The whip-tailed Jurassic sauropod named by Othniel Marsh in 1878, whose casts stand in museums worldwide.', a: 'Diplodocus' },
      { q: 'The sickle-clawed North American raptor whose 1969 study by John Ostrom revived the idea that dinosaurs were active and bird-like.', a: 'Deinonychus' },
      { q: 'An Early Jurassic Arizona predator with a pair of thin crests on its skull.', a: 'Dilophosaurus' },
      { q: 'A sail-backed Permian animal often mistaken for a dinosaur, though it was closer to mammals.', a: 'Dimetrodon' },
      { q: 'A short-winged Jurassic flying reptile with a deep, puffin-like head, first found by Mary Anning.', a: 'Dimorphodon' },
      { q: 'A small, beaked, fast-running plant-eater of the Late Jurassic Morrison Formation.', a: 'Dryosaurus' },
      { q: 'The period nicknamed the Age of Fishes, when the first four-limbed vertebrates came ashore.', a: 'Devonian' },
      { q: 'A huge titanosaur from Argentina named in 2014 after a class of battleship.', a: 'Dreadnoughtus' },
      { q: 'An armoured Devonian fish with shearing bony plates instead of true teeth.', a: 'Dunkleosteus' },
      { q: 'The family name for the raptor dinosaurs, including Velociraptor and Utahraptor.', a: 'Dromaeosaurid' },
      { q: 'The vast Indian lava beds erupted around the time the dinosaurs died out.', a: 'Deccan Traps' },
    ],
    E: [
      { q: 'A large, flat-headed duck-billed dinosaur of the latest Cretaceous in North America.', a: 'Edmontosaurus' },
      { q: 'One of the earliest known dinosaurs, a small Triassic hunter from Argentina.', a: 'Eoraptor' },
      { q: 'The event 66 million years ago that wiped out about three quarters of species on Earth.', a: 'Extinction' },
      { q: 'The Philadelphia naturalist whose bitter rivalry with Othniel Marsh drove the Bone Wars.', a: 'Edward Drinker Cope' },
      { q: 'The epoch after the Paleocene, when early whales and horses appeared.', a: 'Eocene' },
      { q: 'Fossils of these were first recognised as dinosaur remains during American expeditions to Mongolia in 1923.', a: 'Eggs' },
      { q: 'A Canadian armoured dinosaur with bony eyelids and a clubbed tail.', a: 'Euoplocephalus' },
      { q: 'A long-necked marine reptile whose head Edward Cope famously placed on the wrong end.', a: 'Elasmosaurus' },
      { q: 'The gradual wearing away of rock that exposes buried fossils at the surface.', a: 'Erosion' },
    ],
    F: [
      { q: 'The preserved remains or traces of an ancient organism in rock.', a: 'Fossil' },
      { q: 'Specimens from Liaoning in China showed that many small theropods were covered in these.', a: 'Feathers' },
      { q: 'The thigh bone, usually the largest single bone in a dinosaur skeleton.', a: 'Femur' },
      { q: 'Trace fossils left by a walking animal, used to estimate how fast it moved.', a: 'Footprints' },
      { q: 'The spore-bearing plants that formed much of the low greenery Jurassic sauropods browsed.', a: 'Ferns' },
      { q: 'The European country where large numbers of fossil dinosaur eggs are found in Provence.', a: 'France' },
      { q: 'The basic named unit of layered rock used by geologists.', a: 'Formation' },
    ],
    G: [
      { q: 'Smooth stones swallowed by some dinosaurs to help grind food in the gut.', a: 'Gastroliths' },
      { q: 'A Canadian tyrannosaur, close relative of Albertosaurus, from the Dinosaur Park Formation.', a: 'Gorgosaurus' },
      { q: 'A South American predator, described in 1995, that rivalled or exceeded Tyrannosaurus in length.', a: 'Giganotosaurus' },
      { q: 'This Asian desert has produced Velociraptor, Protoceratops and the first known dinosaur nests.', a: 'Gobi Desert' },
      { q: 'An early crested tyrannosauroid from Jurassic China.', a: 'Guanlong' },
      { q: 'The southern supercontinent that included South America, Africa, India, Australia and Antarctica.', a: 'Gondwana' },
      { q: 'A giant beaked, feathered dinosaur from Inner Mongolia, far larger than its parrot-headed relatives.', a: 'Gigantoraptor' },
      { q: 'The tall African sauropod, once called Brachiosaurus brancai, whose skeleton is mounted in Berlin.', a: 'Giraffatitan' },
      { q: 'The Arctic island whose Devonian rocks yielded Ichthyostega.', a: 'Greenland' },
    ],
    H: [
      { q: 'The common group name for the duck-billed dinosaurs.', a: 'Hadrosaur' },
      { q: 'An animal that eats only plants, as the great sauropods did.', a: 'Herbivore' },
      { q: 'A small Early Jurassic South African dinosaur notable for having several different tooth shapes.', a: 'Heterodontosaurus' },
      { q: 'The Montana rock formation that yields Tyrannosaurus and Triceratops from the very end of the Cretaceous.', a: 'Hell Creek' },
      { q: 'A small, agile Cretaceous plant-eater best known from the Isle of Wight.', a: 'Hypsilophodon' },
      { q: 'One of the oldest known predatory dinosaurs, from Triassic rocks in Argentina.', a: 'Herrerasaurus' },
      { q: 'Triceratops carried three of these on its face.', a: 'Horns' },
      { q: 'The single specimen that formally defines a newly named species.', a: 'Holotype' },
      { q: 'A flightless, toothed diving bird of the Cretaceous seas of North America.', a: 'Hesperornis' },
    ],
    I: [
      { q: 'One of the first dinosaurs ever named, a large plant-eater with a spike on its thumb.', a: 'Iguanodon' },
      { q: 'A dolphin-shaped marine reptile of the Mesozoic, many found in Dorset by Mary Anning.', a: 'Ichthyosaur' },
      { q: 'The rare metal found in a worldwide clay layer, key evidence for an impact at the end of the Cretaceous.', a: 'Iridium' },
      { q: 'This English island is nicknamed Dinosaur Island for its rich Cretaceous fossils.', a: 'Isle of Wight' },
      { q: 'An early four-limbed animal from Devonian Greenland, close to the move from water onto land.', a: 'Ichthyostega' },
      { q: 'The country whose Narmada valley produced the horned predator Rajasaurus.', a: 'India' },
      { q: 'The popular name for the recent glacial times when mammoths roamed Europe.', a: 'Ice Age' },
      { q: 'A Brazilian spinosaur named in 1996 after the annoyance its doctored fossil caused researchers.', a: 'Irritator' },
    ],
    J: [
      { q: 'The middle period of the Mesozoic, famous for its giant sauropods.', a: 'Jurassic' },
      { q: 'The Yale palaeontologist whose work on Deinonychus linked birds to dinosaurs.', a: 'John Ostrom' },
      { q: 'The American anatomist who in 1858 described Hadrosaurus, the first nearly complete dinosaur skeleton found in North America.', a: 'Joseph Leidy' },
      { q: 'A sauropod from Niger, named in 1999 after a creature of local legend.', a: 'Jobaria' },
      { q: 'The name for the exceptionally preserved Early Cretaceous fossil community of north-eastern China.', a: 'Jehol Biota' },
      { q: 'The stretch of English shoreline in Dorset and Devon listed as a World Heritage Site for its fossils.', a: 'Jurassic Coast' },
    ],
    K: [
      { q: 'A spiky African relative of Stegosaurus from the Tendaguru beds of Tanzania.', a: 'Kentrosaurus' },
      { q: 'A huge Australian pliosaur of the Early Cretaceous with a skull over two metres long.', a: 'Kronosaurus' },
      { q: 'This American state\'s Cretaceous chalk beds, laid down in a shallow sea, yield mosasaurs and giant fish.', a: 'Kansas' },
      { q: 'A Late Jurassic English mudstone unit rich in marine reptile fossils.', a: 'Kimmeridge Clay' },
      { q: 'The South African region whose Permian and Triassic rocks preserve mammal-like reptiles.', a: 'Karoo' },
      { q: 'A Utah horned dinosaur named in 2010 for the elaborate hooks along its frill.', a: 'Kosmoceratops' },
    ],
    L: [
      { q: 'A duck-billed dinosaur with a hollow, hatchet-shaped crest on its head.', a: 'Lambeosaurus' },
      { q: 'The Chinese province whose ancient lake beds preserve feathered dinosaurs and early birds.', a: 'Liaoning' },
      { q: 'The soft white rock type of the Solnhofen quarries in Germany, formed on a Jurassic sea floor.', a: 'Limestone' },
      { q: 'A tusked, pig-sized Permian and Triassic plant-eater that survived the largest mass extinction.', a: 'Lystrosaurus' },
      { q: 'A small Australian plant-eating dinosaur named after the daughter of the couple who found it.', a: 'Leaellynasaura' },
      { q: 'The first complete dinosaur skeleton mounted in China, a Jurassic long-necked plant-eater from Yunnan.', a: 'Lufengosaurus' },
      { q: 'The name for the western landmass of North America when a seaway split the continent in the Late Cretaceous.', a: 'Laramidia' },
    ],
    M: [
      { q: 'The first dinosaur to be formally named, described by William Buckland in 1824.', a: 'Megalosaurus' },
      { q: 'The Lyme Regis fossil hunter who found the first ichthyosaur and plesiosaur skeletons known to science.', a: 'Mary Anning' },
      { q: 'The era spanning the Triassic, Jurassic and Cretaceous periods.', a: 'Mesozoic' },
      { q: 'A Montana duck-bill whose nesting colonies showed that dinosaurs cared for their young; the name means "good mother lizard".', a: 'Maiasaura' },
      { q: 'A large marine lizard with paddle-like limbs that ruled Late Cretaceous seas.', a: 'Mosasaur' },
      { q: 'A crow-sized Chinese dinosaur with long flight feathers on all four limbs.', a: 'Microraptor' },
      { q: 'The Asian country where the "fighting dinosaurs" fossil of Velociraptor and Protoceratops was found.', a: 'Mongolia' },
      { q: 'The American state where Barnum Brown dug up the first Tyrannosaurus skeleton in 1902.', a: 'Montana' },
      { q: 'The Late Jurassic rock unit of the American West that has yielded Allosaurus, Stegosaurus and Diplodocus.', a: 'Morrison Formation' },
      { q: 'A Chinese sauropod famous for having one of the longest necks of any animal.', a: 'Mamenchisaurus' },
      { q: 'The shaggy Ice Age elephant relative whose frozen bodies are found in Siberia.', a: 'Mammoth' },
      { q: 'An Australian plant-eating dinosaur named after the Queensland town where it was found.', a: 'Muttaburrasaurus' },
      { q: 'An extinct giant shark known mainly from its huge triangular teeth.', a: 'Megalodon' },
    ],
    N: [
      { q: 'An African sauropod with a wide, straight-edged muzzle holding hundreds of tiny teeth.', a: 'Nigersaurus' },
      { q: 'Oviraptor was found brooding on one of these, clearing its name.', a: 'Nests' },
      { q: 'The armoured dinosaur group that lacked a tail club, unlike the ankylosaurids.', a: 'Nodosaur' },
      { q: 'An extinct human relative whose first recognised remains came from a German valley in 1856.', a: 'Neanderthal' },
      { q: 'The American state where Coelophysis skeletons pile up at Ghost Ranch.', a: 'New Mexico' },
      { q: 'A Tanzanian animal from the Middle Triassic that may be the oldest known dinosaur.', a: 'Nyasasaurus' },
    ],
    O: [
      { q: 'The "bird-hipped" of the two great dinosaur groups, containing the horned and armoured plant-eaters.', a: 'Ornithischian' },
      { q: 'A Mongolian beaked dinosaur wrongly accused of stealing eggs; the nest it sat on was its own.', a: 'Oviraptor' },
      { q: 'The Yale professor who named Stegosaurus, Triceratops and Allosaurus during the Bone Wars.', a: 'Othniel Charles Marsh' },
      { q: 'A long-legged, toothless Cretaceous dinosaur whose name means "bird mimic".', a: 'Ornithomimus' },
      { q: 'In Australia, some fossil bones from Lightning Ridge have been replaced by this gemstone.', a: 'Opal' },
      { q: 'The period after the Cambrian, which ended in a great extinction as ice spread.', a: 'Ordovician' },
      { q: 'The English county whose Stonesfield quarries yielded the first Megalosaurus bones.', a: 'Oxfordshire' },
    ],
    P: [
      { q: 'The first flying reptile ever given a scientific name, described by Georges Cuvier in 1809.', a: 'Pterodactylus' },
      { q: 'A crested, toothless flying reptile of the Cretaceous with a wingspan over six metres.', a: 'Pteranodon' },
      { q: 'A four-flippered marine reptile with a long neck and a small head.', a: 'Plesiosaur' },
      { q: 'A sheep-sized Mongolian horned dinosaur with a bony frill but no long face horns.', a: 'Protoceratops' },
      { q: 'A duck-bill with a long, backward-curving hollow tube on its head that may have been used to make sound.', a: 'Parasaurolophus' },
      { q: 'The period that ended 252 million years ago in the largest mass extinction known.', a: 'Permian' },
      { q: 'The single supercontinent that existed when the first dinosaurs appeared in the Triassic.', a: 'Pangaea' },
      { q: 'A Cretaceous plant-eater with an extremely thick, domed skull roof.', a: 'Pachycephalosaurus' },
      { q: 'The study of ancient life through fossils.', a: 'Palaeontology' },
      { q: 'Wood turned to stone by mineral replacement is described by this word.', a: 'Petrified' },
      { q: 'An early Chinese horned dinosaur with a parrot-like beak, known from hundreds of specimens.', a: 'Psittacosaurus' },
      { q: 'A common Late Triassic European plant-eater, found by the dozens at Trossingen in Germany.', a: 'Plateosaurus' },
      { q: 'The epoch immediately after the dinosaur extinction, when mammals began to diversify.', a: 'Paleocene' },
    ],
    Q: [
      { q: 'One of the largest flying animals ever, a Cretaceous pterosaur from Texas with a wingspan near ten metres.', a: 'Quetzalcoatlus' },
      { q: 'A pit where stone is cut or dug out, often the place where fossils come to light.', a: 'Quarry' },
      { q: 'The Australian state where Muttaburrasaurus and huge sauropod trackways were found.', a: 'Queensland' },
      { q: 'The most recent geological period, covering the ice ages and the present day.', a: 'Quaternary' },
    ],
    R: [
      { q: 'The British anatomist who coined the word "dinosaur" in 1842.', a: 'Richard Owen' },
      { q: 'A long-tailed Jurassic flying reptile from Solnhofen with needle-like teeth.', a: 'Rhamphorhynchus' },
      { q: 'The Drumheller institution in Alberta devoted to palaeontology.', a: 'Royal Tyrrell Museum' },
      { q: 'A heavy Late Triassic plant-eater from north-western Argentina.', a: 'Riojasaurus' },
      { q: 'Dinosaurs belong to this broad group of scaly, egg-laying vertebrates.', a: 'Reptile' },
      { q: 'The American explorer who led the 1920s Gobi expeditions that found the first recognised dinosaur eggs.', a: 'Roy Chapman Andrews' },
    ],
    S: [
      { q: 'A Jurassic plant-eater with two rows of tall back plates and four tail spikes.', a: 'Stegosaurus' },
      { q: 'A huge North African predator with a tall sail on its back and a crocodile-like snout.', a: 'Spinosaurus' },
      { q: 'The group of long-necked, four-legged giant plant-eating dinosaurs.', a: 'Sauropod' },
      { q: 'The nickname of the largest and most complete Tyrannosaurus skeleton, on show in Chicago.', a: 'Sue' },
      { q: 'The "lizard-hipped" dinosaur group that includes the theropods and the sauropods.', a: 'Saurischian' },
      { q: 'The first dinosaur found with clear evidence of a fuzzy body covering, reported from China in 1996.', a: 'Sinosauropteryx' },
      { q: 'The class of rock, laid down in layers, in which nearly all fossils are found.', a: 'Sedimentary' },
      { q: 'The Bavarian quarry town whose fine Jurassic slabs preserved Archaeopteryx.', a: 'Solnhofen' },
      { q: 'An ostrich-like Canadian dinosaur with no teeth and very long legs.', a: 'Struthiomimus' },
      { q: 'A Cretaceous North American sauropod estimated at 17 metres tall, known from enormous neck bones.', a: 'Sauroposeidon' },
      { q: 'The period when the first simple land plants spread, between the Ordovician and the Devonian.', a: 'Silurian' },
      { q: 'The sabre-toothed cat of the Americas, abundant in the La Brea tar pits.', a: 'Smilodon' },
      { q: 'Layered mounds built by microbial mats, among the oldest fossils on Earth.', a: 'Stromatolite' },
      { q: 'A horned dinosaur with a fan of long spikes around the rim of its frill.', a: 'Styracosaurus' },
      { q: 'One of the longest dinosaurs known, a Morrison Formation sauropod possibly over 30 metres.', a: 'Supersaurus' },
    ],
    T: [
      { q: 'The most famous Late Cretaceous predator of North America, first described by Henry Fairfield Osborn in 1905.', a: 'Tyrannosaurus' },
      { q: 'The best known horned dinosaur, a heavy plant-eater from the Hell Creek Formation.', a: 'Triceratops' },
      { q: 'The period in which the first dinosaurs appeared, following the Permian.', a: 'Triassic' },
      { q: 'A Mongolian dinosaur with hand claws up to a metre long.', a: 'Therizinosaurus' },
      { q: 'The group of two-legged, mostly meat-eating dinosaurs from which birds arose.', a: 'Theropod' },
      { q: 'The African country whose Tendaguru beds produced Giraffatitan and Kentrosaurus.', a: 'Tanzania' },
      { q: 'The sauropod group that included the very largest dinosaurs and survived to the end of the Cretaceous.', a: 'Titanosaur' },
      { q: 'An extinct segmented marine arthropod, very common in Palaeozoic rocks, that died out in the Permian extinction.', a: 'Trilobite' },
      { q: 'The natural asphalt seeps at La Brea trapped Ice Age animals in this sticky substance.', a: 'Tar' },
      { q: 'A horned dinosaur with an enormous frill pierced by two large openings.', a: 'Torosaurus' },
      { q: 'A small North American theropod with a large brain for its size and serrated teeth.', a: 'Troodon' },
      { q: 'A Devonian fish from Arctic Canada with sturdy limb-like fins, a key fossil in the move onto land.', a: 'Tiktaalik' },
    ],
    U: [
      { q: 'The largest known raptor dinosaur, from Early Cretaceous rocks in the American West.', a: 'Utahraptor' },
      { q: 'The American state whose Cleveland-Lloyd Quarry holds a dense jumble of Allosaurus bones.', a: 'Utah' },
      { q: 'A rhino-sized Eocene mammal with six blunt horns on its skull.', a: 'Uintatherium' },
      { q: 'An Argentine raptor named in 1997 whose arm bones suggested bird-like wing folding.', a: 'Unenlagia' },
      { q: 'This radioactive element\'s decay into lead lets geologists date rocks in millions of years.', a: 'Uranium' },
    ],
    V: [
      { q: 'A turkey-sized Mongolian raptor much smaller than its film portrayal.', a: 'Velociraptor' },
      { q: 'One of the bones of the backbone; sauropod examples are hollowed out to save weight.', a: 'Vertebra' },
      { q: 'The Deccan Traps in India record massive activity of this kind near the end of the Cretaceous.', a: 'Volcanism' },
      { q: 'An Early Jurassic sauropod from Zimbabwe, among the oldest known.', a: 'Vulcanodon' },
    ],
    W: [
      { q: 'The Oxford clergyman and geologist who named Megalosaurus in 1824.', a: 'William Buckland' },
      { q: 'The American state where Como Bluff produced a flood of Jurassic dinosaurs during the Bone Wars.', a: 'Wyoming' },
      { q: 'The Early Cretaceous rock group of southern England that yields Iguanodon and Baryonyx.', a: 'Wealden' },
      { q: 'An Ice Age grazer with two horns and a thick coat, known from Siberian remains and cave art.', a: 'Woolly rhinoceros' },
      { q: 'A scale-covered Cambrian sea-floor animal known from the Burgess Shale.', a: 'Wiwaxia' },
    ],
    X: [
      { q: 'A horned dinosaur named in 2012, the oldest known large ceratopsid in Canada.', a: 'Xenoceratops' },
      { q: 'A large predatory fish of the Cretaceous Western Interior Seaway, famous for a specimen that died swallowing its prey.', a: 'Xiphactinus' },
      { q: 'A small feathered Chinese dinosaur described in 2011 that was compared closely with Archaeopteryx.', a: 'Xiaotingia' },
      { q: 'The Chinese palaeontologist who has named more dinosaur species than almost anyone else alive.', a: 'Xu Xing' },
    ],
    Y: [
      { q: 'The Mexican peninsula beneath which the end-Cretaceous impact crater lies.', a: 'Yucatan' },
      { q: 'A nine-metre Chinese tyrannosauroid preserved with long filamentous feathers.', a: 'Yutyrannus' },
      { q: 'The American university whose Peabody Museum was built around Marsh\'s fossil collection.', a: 'Yale' },
      { q: 'A large Jurassic predator from Sichuan in China, similar in build to Allosaurus.', a: 'Yangchuanosaurus' },
      { q: 'The Chinese rock unit whose volcanic ash beds preserve feathered dinosaurs in fine detail.', a: 'Yixian Formation' },
    ],
    Z: [
      { q: 'An early horned dinosaur from New Mexico, one of the first with true brow horns.', a: 'Zuniceratops' },
      { q: 'A Chinese raptor named in 2015 with large, well-developed wing feathers despite short arms.', a: 'Zhenyuanlong' },
      { q: 'An armoured dinosaur named in 2017 after a horned creature from the film Ghostbusters.', a: 'Zuul' },
      { q: 'A stocky plant-eating dinosaur from the Late Cretaceous island fauna of Romania.', a: 'Zalmoxes' },
    ],
  },
};
