import type { RawPack } from '../core/packs';

export const drinksPack: RawPack = {
  id: 'drinks',
  name: 'Wine, Coffee & Tea',
  description: 'Grapes, beans, leaves and everything else worth pouring into a glass.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '☕',
  accent: '#7c2d12',
  letters: {
    A: [
      { q: 'The finer of the two great coffee species, grown high and picked by hand.', a: 'Arabica' },
      { q: 'The long black made by adding hot water to a shot, named for wartime soldiers.', a: 'Americano' },
      { q: 'The warm-fermented British beer, as against the cold-fermented kind.', a: 'Ale' },
      { q: 'The green wormwood spirit banned across Europe for most of the 20th century.', a: 'Absinthe' },
      { q: 'The big dried-grape red of the Valpolicella hills.', a: 'Amarone' },
      { q: 'The small drink taken before a meal to sharpen the appetite.', a: 'Aperitif' },
      { q: 'The strong malty black tea of a north-eastern Indian state.', a: 'Assam' },
      { q: 'The intoxicating compound that fermentation produces.', a: 'Alcohol' },
      { q: 'The smell of a wine or a fresh brew, half of its whole flavour.', a: 'Aroma' },
      { q: 'The spiky Mexican plant whose heart is roasted to make tequila.', a: 'Agave' },
      { q: 'The Italian almond liqueur sold in a square bottle.', a: 'Amaretto' },
      { q: 'The Jerez style that sits between the palest and the darkest, nutty and dry.', a: 'Amontillado' },
      { q: 'The Piedmont town whose sweet sparkling moscato is named after it.', a: 'Asti' },
    ],
    B: [
      { q: 'The person who pulls the shots behind a coffee counter.', a: 'Barista' },
      { q: 'The great claret region around a river-mouth city in south-west France.', a: 'Bordeaux' },
      { q: 'The eastern French region of the finest pinot noir and chardonnay.', a: 'Burgundy' },
      { q: 'The village-by-village Gamay region just south of that same French one.', a: 'Beaujolais' },
      { q: 'The citrus oil that flavours Earl Grey.', a: 'Bergamot' },
      { q: 'The American corn whiskey named after a Kentucky county.', a: 'Bourbon' },
      { q: 'The spirit distilled from wine, of which cognac is the finest.', a: 'Brandy' },
      { q: 'The world most drunk alcoholic drink, made from malted grain and hops.', a: 'Beer' },
      { q: 'The oak vessel in which wine and whisky are aged.', a: 'Barrel' },
      { q: 'The roasted seed of the coffee cherry.', a: 'Bean' },
      { q: 'The hoppy English pale ale served from a hand pump.', a: 'Bitter' },
      { q: 'The Italian herbal aperitif, bright red, drunk with soda and orange.', a: 'Bitters' },
      { q: 'The label word for a sparkling wine that is dry, with little sugar added.', a: 'Brut' },
      { q: 'The Berlin sour wheat beer, served cloudy with a shot of syrup.', a: 'Berliner Weisse' },
    ],
    C: [
      { q: 'The drink made from roasted ground seeds, among the most traded farm goods on Earth.', a: 'Coffee' },
      { q: 'The Italian breakfast drink of espresso, steamed milk and a cap of foam.', a: 'Cappuccino' },
      { q: 'The white grape of Chablis, Meursault and most sparkling wine.', a: 'Chardonnay' },
      { q: 'The sparkling wine that may only carry that name if grown near Reims and Epernay.', a: 'Champagne' },
      { q: 'The thick-skinned black grape that dominates the Medoc, full name ends sauvignon.', a: 'Cabernet' },
      { q: 'The spiced milky tea of the Indian street stall.', a: 'Chai' },
      { q: 'The fermented apple drink of Somerset, Normandy and Asturias.', a: 'Cider' },
      { q: 'The double-distilled grape spirit of a town on the Charente.', a: 'Cognac' },
      { q: 'The old name of Sri Lanka, still used for its tea.', a: 'Ceylon' },
      { q: 'The Spanish small drink of espresso cut with a little warm milk.', a: 'Cortado' },
      { q: 'The bark stopper that seals a wine bottle.', a: 'Cork' },
      { q: 'The stimulant that makes coffee and tea worth getting up for.', a: 'Caffeine' },
      { q: 'The Spanish sparkling wine of Penedes, made by the traditional method.', a: 'Cava' },
      { q: 'The Tuscan red of the sangiovese grape, once sold in a straw flask.', a: 'Chianti' },
      { q: 'The South American country whose mild washed beans are a byword for the drink.', a: 'Colombia' },
    ],
    D: [
      { q: 'Coffee with the stimulant taken out.', a: 'Decaf' },
      { q: 'The delicate muscatel tea of the Himalayan foothills, called the champagne of its kind.', a: 'Darjeeling' },
      { q: 'The sweet bottle served with pudding, such as Sauternes or Tokaji.', a: 'Dessert wine' },
      { q: 'The boiling and condensing that turns a fermented liquid into a spirit.', a: 'Distillation' },
      { q: 'The opposite of sweet, on a wine label.', a: 'Dry' },
      { q: 'The sediment left in the bottom of the cup or the cask.', a: 'Dregs' },
      { q: 'The double shot of espresso, two Italian syllables.', a: 'Doppio' },
      { q: 'The glass jug into which an old red is poured off its sediment.', a: 'Decanter' },
      { q: 'The large brown raw sugar crystals named after a district of Guyana.', a: 'Demerara' },
      { q: 'The Portuguese river valley of terraced vineyards where port is grown.', a: 'Douro' },
      { q: 'The Piedmont red grape whose name means little sweet one, though the wine is dry.', a: 'Dolcetto' },
    ],
    E: [
      { q: 'The small strong Italian shot forced through the grounds under pressure.', a: 'Espresso' },
      { q: 'The black tea scented with citrus oil, named after a British prime minister.', a: 'Earl Grey' },
      { q: 'The African country where coffee was first drunk, in the Kaffa highlands.', a: 'Ethiopia' },
      { q: 'The drawing of flavour out of the grounds, which can be over or under done.', a: 'Extraction' },
      { q: 'The creamy white flower whose cordial flavours summer drinks.', a: 'Elderflower' },
      { q: 'The German and Austrian sweet wine pressed from frozen grapes.', a: 'Eiswein' },
      { q: 'The single property whose grapes all go into one bottling.', a: 'Estate' },
      { q: 'The compound made by acid and alcohol that gives wine its fruity smell.', a: 'Ester' },
      { q: 'The chemical name of the alcohol in every drink.', a: 'Ethanol' },
    ],
    F: [
      { q: 'The paper cone through which slow coffee drips.', a: 'Filter' },
      { q: 'The turning of sugar into alcohol by yeast.', a: 'Fermentation' },
      { q: 'The glass cylinder with a plunger, invented in Italy but named for another country.', a: 'French press' },
      { q: 'The Antipodean drink of espresso with steamed milk and almost no foam.', a: 'Flat white' },
      { q: 'The iced whipped coffee of Greek beach cafes.', a: 'Frappe' },
      { q: 'The wine strengthened with spirit, as port and sherry are.', a: 'Fortified' },
      { q: 'The bubbly white cap on a well-pulled milk drink.', a: 'Foam' },
      { q: 'The taste that lingers after you swallow, long in a good wine.', a: 'Finish' },
      { q: 'The Italian straw-covered bottle in which cheap Chianti once came.', a: 'Fiasco' },
      { q: 'The bone-dry pale Jerez style aged under a veil of yeast.', a: 'Fino' },
      { q: 'The first gentle pressing of the grapes, before any hard squeezing.', a: 'Free run' },
      { q: 'The tall slender wine container with sloping shoulders, used in Alsace and the Mosel.', a: 'Flute' },
    ],
    G: [
      { q: 'The burr machine that reduces beans to an even powder.', a: 'Grinder' },
      { q: 'The fruit that all wine is made from.', a: 'Grape' },
      { q: 'The unoxidised Chinese and Japanese leaf, steamed or pan-fired.', a: 'Green tea' },
      { q: 'The juniper spirit of the London dry style.', a: 'Gin' },
      { q: 'The Japanese green leaf blended with toasted brown rice.', a: 'Genmaicha' },
      { q: 'The aromatic pink-skinned white grape of Alsace, hard to spell and to pronounce.', a: 'Gewurztraminer' },
      { q: 'The Central American country whose Antigua valley grows prized beans.', a: 'Guatemala' },
      { q: 'The vessel from which wine is properly drunk, on a stem.', a: 'Glass' },
      { q: 'The red grape of Chateauneuf and Priorat, called garnacha in Spain.', a: 'Grenache' },
      { q: 'The Austrian white grape of peppery, dry wines, first word means green.', a: 'Gruner Veltliner' },
    ],
    H: [
      { q: 'The caffeine-free infusion of leaves, flowers and roots.', a: 'Herbal tea' },
      { q: 'The red sour flower that makes a crimson infusion drunk from Egypt to Mexico.', a: 'Hibiscus' },
      { q: 'The bee-made sweetener stirred into a hot lemon drink.', a: 'Honey' },
      { q: 'The green cone that gives beer its bitterness and aroma.', a: 'Hops' },
      { q: 'The gathering of the grapes, in September in the northern hemisphere.', a: 'Harvest' },
      { q: 'The winter drink of melted cocoa and milk.', a: 'Hot chocolate' },
      { q: 'The everyday mixture a roaster sells as its own standard.', a: 'House blend' },
      { q: 'The Japanese maker of the ribbed glass cone beloved of speciality shops.', a: 'Hario' },
      { q: 'The tall glass of a single spirit topped up with a mixer and ice.', a: 'Highball' },
      { q: 'The old English word for Rhine wine, taken from the town of Hochheim.', a: 'Hock' },
    ],
    I: [
      { q: 'The freeze-dried powder that dissolves in hot water.', a: 'Instant coffee' },
      { q: 'The steeping of leaves or herbs in hot water.', a: 'Infusion' },
      { q: 'The summer drink of chilled black tea, invented for the 1904 St Louis fair.', a: 'Iced tea' },
      { q: 'The country of espresso, Chianti and vermouth.', a: 'Italy' },
      { q: 'The hot drink of whiskey, sugar and cream floated on a dark brew.', a: 'Irish coffee' },
      { q: 'The frozen water that ruins an espresso and makes a good gin and tonic.', a: 'Ice' },
      { q: 'The country of Assam, Darjeeling and Nilgiri leaf.', a: 'India' },
      { q: 'The fish-derived agent once used to clear a cloudy beer or wine.', a: 'Isinglass' },
    ],
    J: [
      { q: 'The Indonesian island whose name became slang for a cup of coffee.', a: 'Java' },
      { q: 'The white flower whose blossom scents a Chinese green tea.', a: 'Jasmine' },
      { q: 'The pressed liquid of a fruit, drunk unfermented.', a: 'Juice' },
      { q: 'The wide-mouthed vessel in which iced tea or sangria is served.', a: 'Jug' },
    ],
    K: [
      { q: 'The East African country whose AA grade beans are bright and blackcurranty.', a: 'Kenya' },
      { q: 'The vessel that boils the water.', a: 'Kettle' },
      { q: 'The fizzy fermented tea drink made with a bacterial culture.', a: 'Kombucha' },
      { q: 'The Indonesian coffee passed through a civet, and the most expensive in the world.', a: 'Kopi luwak' },
      { q: 'The smoky Chinese black leaf of Anhui province, a breakfast classic.', a: 'Keemun' },
      { q: 'The German cold-fermented pale beer of Cologne.', a: 'Kolsch' },
      { q: 'The Burgundian aperitif of white wine with blackcurrant liqueur.', a: 'Kir' },
    ],
    L: [
      { q: 'The milky Italian drink of one shot and a lot of steamed milk.', a: 'Latte' },
      { q: 'The Chinese black leaf dried over pine smoke.', a: 'Lapsang souchong' },
      { q: 'The yellow citrus squeezed into tea and into gin.', a: 'Lemon' },
      { q: 'The sweetened spirit drunk after dinner in a small glass.', a: 'Liqueur' },
      { q: 'The French river valley of Sancerre, Vouvray and Muscadet.', a: 'Loire' },
      { q: 'The dead yeast a wine rests on to gain a bready richness.', a: 'Lees' },
      { q: 'The bottom-fermented beer style that took over the world from Bohemia.', a: 'Lager' },
      { q: 'The Italian lemon liqueur of the Amalfi coast.', a: 'Limoncello' },
    ],
    M: [
      { q: 'The chocolate-and-coffee drink named after a Yemeni port.', a: 'Mocha' },
      { q: 'The soft plummy Bordeaux grape, the most planted there.', a: 'Merlot' },
      { q: 'The powdered Japanese green leaf whisked in a bowl.', a: 'Matcha' },
      { q: 'The inky black grape of Cahors that made its name in Argentina.', a: 'Malbec' },
      { q: 'The white liquid steamed and poured into a cappuccino.', a: 'Milk' },
      { q: 'The handled cup from which office coffee is drunk.', a: 'Mug' },
      { q: 'The North African infusion of green leaf, fresh leaves and much sugar.', a: 'Mint tea' },
      { q: 'The ancient grape family, grown for sweet wine and for table fruit alike.', a: 'Muscat' },
      { q: 'The espresso marked with just a spot of milk foam.', a: 'Macchiato' },
      { q: 'The fermented honey drink of the Vikings.', a: 'Mead' },
      { q: 'The Portuguese fortified wine of an Atlantic island, deliberately heated as it ages.', a: 'Madeira' },
      { q: 'The hot mix of crushed grain and water from which beer wort is drawn.', a: 'Mash' },
    ],
    N: [
      { q: 'The gas pushed into cold brew to give it a creamy head.', a: 'Nitro' },
      { q: 'The Californian valley that made American cabernet famous.', a: 'Napa' },
      { q: 'The smell of a wine, as a taster refers to it.', a: 'Nose' },
      { q: 'The tannic north Italian red grape behind Barolo and Barbaresco.', a: 'Nebbiolo' },
      { q: 'The sweet liquid of a flower, and a word for any delicious drink.', a: 'Nectar' },
    ],
    O: [
      { q: 'The half-oxidised Chinese and Taiwanese leaf, between green and black.', a: 'Oolong' },
      { q: 'The breakfast drink squeezed from a citrus fruit.', a: 'Orange juice' },
      { q: 'The browning reaction that turns a green leaf black, and spoils an open bottle.', a: 'Oxidation' },
      { q: 'The single farm or country a speciality bag names on its label.', a: 'Origin' },
      { q: 'The word for a white wine that has been aged in wood.', a: 'Oaked' },
      { q: 'The darkest and fullest of the Jerez styles, aged without a yeast veil.', a: 'Oloroso' },
      { q: 'The French or American wood vessel in which a fine red matures.', a: 'Oak' },
    ],
    P: [
      { q: 'The slow hand method of trickling water through a cone of grounds.', a: 'Pour over' },
      { q: 'The thin-skinned red grape of Burgundy and of Oregon.', a: 'Pinot noir' },
      { q: 'The Italian sparkling wine of the Glera grape, made in a tank.', a: 'Prosecco' },
      { q: 'The stovetop pot that cycles boiling water through the grounds again and again.', a: 'Percolator' },
      { q: 'The sweet fortified red of the Douro, shipped from a city at its mouth.', a: 'Port' },
      { q: 'The aged, fermented, earthy Chinese tea pressed into cakes.', a: 'Pu-erh' },
      { q: 'The metal basket and handle that clamps into an espresso machine.', a: 'Portafilter' },
      { q: 'The Czech city that gave its name to the golden lager style.', a: 'Pilsen' },
      { q: 'The setting that decides how coarse or fine the grounds come out.', a: 'Particle size' },
      { q: 'The Peruvian and Chilean grape brandy shaken into a sour with egg white.', a: 'Pisco' },
      { q: 'The Italian sweet wine pressed from grapes dried on straw mats.', a: 'Passito' },
    ],
    Q: [
      { q: 'The bitter bark compound that gives tonic water its taste and its glow.', a: 'Quinine' },
      { q: 'The Arabic word for coffee, from which the English name descends.', a: 'Qahwa' },
      { q: 'The vessel measure of two pints, in which milk is bought.', a: 'Quart' },
    ],
    R: [
      { q: 'The heating of green beans that develops all their flavour.', a: 'Roasting' },
      { q: 'The German white grape of the Mosel, high in acid and often off-dry.', a: 'Riesling' },
      { q: 'The Spanish red region on the Ebro, aged in American oak.', a: 'Rioja' },
      { q: 'The red bush infusion of South Africa, with no caffeine at all.', a: 'Rooibos' },
      { q: 'The short restricted espresso shot, sweeter and thicker.', a: 'Ristretto' },
      { q: 'The Caribbean spirit distilled from sugar cane and molasses.', a: 'Rum' },
      { q: 'The hardier, more bitter of the two coffee species, high in caffeine.', a: 'Robusta' },
      { q: 'The pink wine made by giving the juice only brief contact with the skins.', a: 'Rose' },
      { q: 'The stony French southern valley of Chateauneuf and Hermitage.', a: 'Rhone' },
      { q: 'The youngest and fruitiest of the port styles.', a: 'Ruby' },
    ],
    S: [
      { q: 'The trained wine waiter who advises on the list.', a: 'Sommelier' },
      { q: 'The everyday steamed green leaf of Japan.', a: 'Sencha' },
      { q: 'The sweetener stirred in, or the substance yeast turns into alcohol.', a: 'Sugar' },
      { q: 'The pressurised vapour a machine uses to heat and froth milk.', a: 'Steam' },
      { q: 'The flavoured sweet liquid pumped into a coffee-shop drink.', a: 'Syrup' },
      { q: 'The Australian name for the peppery Rhone red grape.', a: 'Shiraz' },
      { q: 'The Japanese rice drink, brewed rather than distilled.', a: 'Sake' },
      { q: 'The grassy white grape of Sancerre and Marlborough, second word is blanc.', a: 'Sauvignon' },
      { q: 'The word for any wine with bubbles in it.', a: 'Sparkling' },
      { q: 'The leaving of leaves in hot water for the right number of minutes.', a: 'Steeping' },
      { q: 'The fortified wine of Jerez in Andalusia.', a: 'Sherry' },
      { q: 'The sweet French white of Bordeaux, made from grapes attacked by noble rot.', a: 'Sauternes' },
    ],
    T: [
      { q: 'The world most drunk beverage after water, from the leaf of a camellia.', a: 'Tea' },
      { q: 'The drying compound from skins and stalks that makes a red wine grip.', a: 'Tannin' },
      { q: 'The lidded vessel in which the leaves are brewed.', a: 'Teapot' },
      { q: 'The Spanish black grape of Rioja and Ribera del Duero.', a: 'Tempranillo' },
      { q: 'The whole sense of place, soil and climate that a wine expresses.', a: 'Terroir' },
      { q: 'The unfiltered brew boiled with sugar in a long-handled pot, drunk in Istanbul.', a: 'Turkish coffee' },
      { q: 'The bitter mixer poured over gin, flavoured with cinchona bark.', a: 'Tonic' },
      { q: 'The straight-sided glass with no stem.', a: 'Tumbler' },
      { q: 'The Mexican agave spirit that must come from one named state.', a: 'Tequila' },
      { q: 'The Hungarian sweet wine of Aszu berries, once the drink of tsars.', a: 'Tokaji' },
      { q: 'The French word for an infusion made from any plant but the tea bush.', a: 'Tisane' },
    ],
    U: [
      { q: 'The Sri Lankan high-grown tea district on the eastern slopes.', a: 'Uva' },
      { q: 'The sour thin shot that comes out too fast, with flavour left behind.', a: 'Underextracted' },
      { q: 'The airspace between the wine and the cork, which grows as a bottle ages.', a: 'Ullage' },
      { q: 'The Japanese savoury fifth taste, strong in a good gyokuro.', a: 'Umami' },
    ],
    V: [
      { q: 'The planted field of vines.', a: 'Vineyard' },
      { q: 'The year the grapes were picked.', a: 'Vintage' },
      { q: 'The clear grain or potato spirit of Poland and Russia.', a: 'Vodka' },
      { q: 'The aromatic white grape of Condrieu, peachy and low in acid.', a: 'Viognier' },
      { q: 'The wine flavoured with wormwood and herbs, drunk in a martini.', a: 'Vermouth' },
      { q: 'The Latin-rooted botanical name of the European grapevine, two words.', a: 'Vitis vinifera' },
    ],
    W: [
      { q: 'The fermented juice of the grape.', a: 'Wine' },
      { q: 'The liquid that makes up 98 per cent of a cup of coffee.', a: 'Water' },
      { q: 'The grain spirit of Scotland, spelled without an e there.', a: 'Whisky' },
      { q: 'The least processed of the teas, made of unopened buds.', a: 'White tea' },
      { q: 'The sweet liquid drawn off the mash before the hops go in.', a: 'Wort' },
      { q: 'The person who makes the wine, from picking to bottling.', a: 'Winemaker' },
    ],
    X: [
      { q: 'The Catalan white grape that goes into most cava blends.', a: 'Xarel-lo' },
      { q: 'The Aztec bitter cocoa drink whose name became our word for chocolate.', a: 'Xocolatl' },
    ],
    Y: [
      { q: 'The South American infusion drunk through a metal straw from a gourd.', a: 'Yerba mate' },
      { q: 'The single-celled organism that turns sugar into alcohol.', a: 'Yeast' },
      { q: 'The Chinese province of dark malty tea and of pu-erh.', a: 'Yunnan' },
      { q: 'The Chinese unglazed clay from which the finest small teapots are made.', a: 'Yixing' },
    ],
    Z: [
      { q: 'The Californian black grape that makes jammy reds and blush wines.', a: 'Zinfandel' },
      { q: 'The outer peel of a citrus fruit, twisted over a cocktail.', a: 'Zest' },
    ],
  },
};
