import type { RawPack } from '../core/packs';

export const emojiEasyPack: RawPack = {
  id: 'emoji-easy',
  name: 'Emoji Puzzles · Easy',
  description: 'Read the emojis, guess the movie, place or thing.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '😀',
  accent: '#eab308',
  letters: {
    A: [
      { q: 'Guess the movie: 🪔🧞✨', a: 'Aladdin' },
      { q: 'Guess the movie: 😡🐦', a: 'Angry Birds' },
      { q: 'Guess the tiny insect: 🐜', a: 'Ant' },
      { q: 'Guess the country: 🗽🦅🍔', a: 'America', alt: ['USA', 'United States', 'The United States'] },
      { q: 'Guess the dessert: 🍎🥧', a: 'Apple Pie' },
      { q: 'Guess the job: 🚀🌕👨‍🚀', a: 'Astronaut' },
      { q: 'Guess the country: 🦘🐨', a: 'Australia' },
      { q: 'Guess the place: ✈️🛄🛫', a: 'Airport' },
      { q: 'Guess the fruit: 🥑', a: 'Avocado' },
      { q: 'Guess the vehicle: 🚑🚨', a: 'Ambulance' },
      { q: 'Guess the winged figure: 👼🕊️', a: 'Angel' },
      { q: 'Guess the compound word: ⏰🔔', a: 'Alarm Clock' },
    ],
    B: [
      { q: 'Guess the superhero: 🦇🌃', a: 'Batman' },
      { q: 'Guess the movie: 🏹👩‍🦰🐻', a: 'Brave' },
      { q: 'Guess the insect from the pieces: 🧈🪰', a: 'Butterfly' },
      { q: 'Guess the baked treat: 🍌🍞', a: 'Banana Bread' },
      { q: 'Guess the landmark: ⏰🇬🇧', a: 'Big Ben' },
      { q: 'Guess the sport: 🏀', a: 'Basketball' },
      { q: 'Guess the sport: ⚾', a: 'Baseball' },
      { q: 'Guess the buzzing insect: 🐝', a: 'Bee' },
      { q: 'Guess the job: 🥖🥐🎂', a: 'Baker' },
      { q: 'Guess the technology: 🔵🦷', a: 'Bluetooth' },
      { q: 'Guess the sport: 🎳', a: 'Bowling' },
      { q: 'Guess the place: 🏖️🌊☀️', a: 'Beach' },
      { q: 'Guess the drink: 🧋', a: 'Bubble Tea', alt: ['Boba'] },
      { q: 'Guess the flying animal: 🦇🌙', a: 'Bat' },
    ],
    C: [
      { q: 'Guess the fairy tale: 🧹👠🎃🕛', a: 'Cinderella' },
      { q: 'Guess the animated movie: 🏎️💨🏁', a: 'Cars' },
      { q: 'Guess the food: 🧀🍔', a: 'Cheeseburger' },
      { q: 'Guess the animal: 🐊', a: 'Crocodile', alt: ['Alligator'] },
      { q: 'Guess the job: 👨‍🍳🍳🔪', a: 'Chef', alt: ['Cook'] },
      { q: 'Guess the country: 🐼🥢🏮', a: 'China' },
      { q: 'Guess the compound word: 🐄👦', a: 'Cowboy' },
      { q: 'Guess the sport: 🏏', a: 'Cricket' },
      { q: 'Guess the dessert: 🥕🍰', a: 'Carrot Cake' },
      { q: 'Guess the drink: ☕', a: 'Coffee' },
      { q: 'Guess the holiday: 🎄🎅🎁', a: 'Christmas' },
      { q: 'Guess the crawling insect: 🐛🍃', a: 'Caterpillar' },
      { q: 'Guess the outdoor activity: ⛺🔥🌲', a: 'Camping' },
      { q: 'Guess the treat: 🧁', a: 'Cupcake' },
      { q: 'Guess the desert plant: 🌵', a: 'Cactus' },
    ],
    D: [
      { q: 'Guess the job: 👨‍⚕️💊🩺', a: 'Doctor' },
      { q: 'Guess the job: 🦷👨‍⚕️', a: 'Dentist' },
      { q: 'Guess the movie elephant: 🐘👂🎪', a: 'Dumbo' },
      { q: 'Guess the compound word: 🚪🔔', a: 'Doorbell' },
      { q: 'Guess the treat: 🍩', a: 'Donut', alt: ['Doughnut'] },
      { q: 'Guess the place: 🏜️🐪☀️', a: 'Desert' },
      { q: 'Guess the famous count: 🧛🏰⚰️', a: 'Dracula' },
      { q: 'Guess the game: 🎯', a: 'Darts' },
      { q: 'Guess the game piece: 🎲', a: 'Dice' },
      { q: 'Guess the animal: 🐬🌊', a: 'Dolphin' },
      { q: 'Guess the ancient animal: 🦖🦕', a: 'Dinosaur' },
      { q: 'Guess the instrument: 🥁', a: 'Drums', alt: ['Drum'] },
    ],
    E: [
      { q: 'Guess the landmark: 🗼🇫🇷', a: 'Eiffel Tower' },
      { q: 'Guess the big animal: 🐘', a: 'Elephant' },
      { q: 'Guess the bird: 🦅', a: 'Eagle' },
      { q: 'Guess the country: 🔺🐪🏺', a: 'Egypt' },
      { q: 'Guess the movie: 👽☎️🚲🌕', a: 'ET', alt: ['E.T.', 'E.T. the Extra-Terrestrial'] },
      { q: 'Guess the country: ☕👑🌧️⚽', a: 'England', alt: ['Britain', 'United Kingdom', 'UK'] },
      { q: 'Guess the compound word: 👂💍', a: 'Earring' },
      { q: 'Guess the breakfast food: 🍳', a: 'Eggs', alt: ['Egg', 'Fried Egg'] },
      { q: 'Guess the planet: 🌍', a: 'Earth' },
    ],
    F: [
      { q: 'Guess the movie: ❄️👸⛄', a: 'Frozen' },
      { q: 'Guess the movie: 🔍🐠', a: 'Finding Nemo' },
      { q: 'Guess the food: 🥔🍟', a: 'French Fries', alt: ['Fries'] },
      { q: 'Guess the animal: 🦊', a: 'Fox' },
      { q: 'Guess the compound word: 🔥🪰', a: 'Firefly' },
      { q: 'Guess the sport: 🏈', a: 'Football', alt: ['American Football'] },
      { q: 'Guess the job: 🔥🚒🧯', a: 'Firefighter', alt: ['Fireman'] },
      { q: 'Guess the sky sight: 🌕✨', a: 'Full Moon' },
      { q: 'Guess the fairy tale: 🐸👑💋', a: 'Frog Prince', alt: ['The Frog Prince'] },
      { q: 'Guess the country: 🥖🧀🍷', a: 'France' },
      { q: 'Guess the hobby: 🎣🐟', a: 'Fishing' },
      { q: 'Guess the night-sky show: 🎆🎇', a: 'Fireworks' },
    ],
    G: [
      { q: 'Guess the animal: 🦒', a: 'Giraffe' },
      { q: 'Guess the fairy tale: 👱‍♀️🥣🐻🐻🐻', a: 'Goldilocks' },
      { q: 'Guess the fruit: 🍇', a: 'Grapes', alt: ['Grape'] },
      { q: 'Guess the landmark: 🧱🐉', a: 'Great Wall', alt: ['Great Wall of China', 'The Great Wall'] },
      { q: 'Guess the movie: 👻🚫', a: 'Ghostbusters' },
      { q: 'Guess the sport: ⛳🏌️', a: 'Golf' },
      { q: 'Guess the fairy-tale treat: 🍪🏠🍬', a: 'Gingerbread House' },
      { q: 'Guess the animal: 🦍🍌', a: 'Gorilla' },
      { q: 'Guess the country: 🏛️🫒⚱️', a: 'Greece' },
      { q: 'Guess the instrument: 🎸', a: 'Guitar' },
      { q: 'Guess the spooky figure: 👻', a: 'Ghost' },
    ],
    H: [
      { q: 'Guess the movie: ⚡👓🧙', a: 'Harry Potter' },
      { q: 'Guess the fairy tale: 👦👧🍬🏠🌲', a: 'Hansel and Gretel' },
      { q: 'Guess the food: 🌭', a: 'Hot Dog', alt: ['Hotdog'] },
      { q: 'Guess the animal: 🦛', a: 'Hippo', alt: ['Hippopotamus'] },
      { q: 'Guess the compound word: 🐴👟', a: 'Horseshoe' },
      { q: 'Guess the US state: 🌺🏄🌋', a: 'Hawaii' },
      { q: 'Guess the job: ✂️💇', a: 'Hairdresser', alt: ['Barber', 'Hair Stylist'] },
      { q: 'Guess the movie: 🏠👦😱🎄', a: 'Home Alone' },
      { q: 'Guess the compound word: 🍯🌙', a: 'Honeymoon' },
      { q: 'Guess the sport: 🏒🥅', a: 'Hockey', alt: ['Ice Hockey'] },
      { q: 'Guess the vehicle: 🚁', a: 'Helicopter' },
      { q: 'Guess the sweet spread: 🍯', a: 'Honey' },
    ],
    I: [
      { q: 'Guess the frozen treat: 🍦', a: 'Ice Cream' },
      { q: 'Guess the country: 🍕🍝🛵', a: 'Italy' },
      { q: 'Guess the country: 🧊🌋♨️', a: 'Iceland' },
      { q: 'Guess the country: 🐘🍛🏏', a: 'India' },
      { q: 'Guess the movie: 🧊🦣🐿️', a: 'Ice Age' },
      { q: 'Guess the place: 🏝️🌴', a: 'Island' },
      { q: 'Guess the icy home: 🧊🏠', a: 'Igloo' },
    ],
    J: [
      { q: 'Guess the movie: 🦈😱🌊', a: 'Jaws' },
      { q: 'Guess the movie: 🦖🌴⚠️', a: 'Jurassic Park' },
      { q: 'Guess the spread: 🍓🍞🥄', a: 'Jam', alt: ['Jelly'] },
      { q: 'Guess the job: 🧑‍⚖️⚖️🔨', a: 'Judge' },
      { q: 'Guess the country: 🍣🗻🌸', a: 'Japan' },
      { q: 'Guess the movie: 👦🐻🐍🌴', a: 'Jungle Book', alt: ['The Jungle Book'] },
      { q: 'Guess the drink: 🧃🍊', a: 'Juice', alt: ['Orange Juice'] },
    ],
    K: [
      { q: 'Guess the animal: 🦘', a: 'Kangaroo' },
      { q: 'Guess the animal: 🐨🌿', a: 'Koala' },
      { q: 'Guess the movie: 🐼🥋', a: 'Kung Fu Panda' },
      { q: 'Guess the martial art: 🥋👊', a: 'Karate' },
      { q: 'Guess the royal: 👑🤴', a: 'King' },
      { q: 'Guess the fruit: 🥝', a: 'Kiwi' },
      { q: 'Guess the computer part: ⌨️', a: 'Keyboard' },
      { q: 'Guess the toy: 🪁💨', a: 'Kite' },
      { q: 'Guess the baby animal: 🐱🍼', a: 'Kitten' },
    ],
    L: [
      { q: 'Guess the movie: 🦁👑', a: 'Lion King', alt: ['The Lion King'] },
      { q: 'Guess the big cat: 🦁', a: 'Lion' },
      { q: 'Guess the city: 🎡🕰️☔', a: 'London' },
      { q: 'Guess the compound word: 💡🏠', a: 'Lighthouse' },
      { q: 'Guess the drink: 🍋🥤', a: 'Lemonade' },
      { q: 'Guess the spotted big cat: 🐆', a: 'Leopard', alt: ['Cheetah', 'Jaguar'] },
      { q: 'Guess the job: ⚖️💼📜', a: 'Lawyer', alt: ['Attorney'] },
      { q: 'Guess the insect: 🐞', a: 'Ladybug', alt: ['Ladybird'] },
      { q: 'Guess the fruit: 🍋', a: 'Lemon' },
      { q: 'Guess the animal: 🦙', a: 'Llama', alt: ['Alpaca'] },
    ],
    M: [
      { q: 'Guess the animal: 🐒🌴', a: 'Monkey' },
      { q: 'Guess the movie: 👹👁️🚪🏢', a: 'Monsters Inc', alt: ['Monsters, Inc.', 'Monsters Inc.'] },
      { q: 'Guess the place in the sky: 🌙🚀', a: 'Moon' },
      { q: 'Guess the food: 🍄', a: 'Mushroom' },
      { q: 'Guess the sea creature: 🧜‍♀️', a: 'Mermaid' },
      { q: 'Guess the country: 🌮🌵🎸', a: 'Mexico' },
      { q: 'Guess the famous painting: 🖼️👩🙂', a: 'Mona Lisa', alt: ['The Mona Lisa'] },
      { q: 'Guess the cartoon character: 🐭🏰✨', a: 'Mickey Mouse', alt: ['Mickey'] },
      { q: 'Guess the long race: 🏃🏃🏃🏅', a: 'Marathon' },
      { q: 'Guess the object: 🧲', a: 'Magnet' },
      { q: 'Guess the landform: ⛰️🧗', a: 'Mountain' },
      { q: 'Guess the drink: 🥛🐄', a: 'Milk' },
    ],
    N: [
      { q: 'Guess the city: 🗽🍎🚕', a: 'New York', alt: ['New York City', 'NYC'] },
      { q: 'Guess the sea animal: 🐋🦄', a: 'Narwhal' },
      { q: 'Guess the job: 💉🏥👩‍⚕️', a: 'Nurse' },
      { q: 'Guess the compound word (a bad dream): 🌙🐴', a: 'Nightmare' },
      { q: 'Guess the food: 🍜🥢', a: 'Noodles', alt: ['Noodle', 'Ramen'] },
      { q: 'Guess the sneaky fighter: 🥷', a: 'Ninja' },
      { q: 'Guess the place: 🎅❄️🧭', a: 'North Pole', alt: ['The North Pole'] },
      { q: 'Guess the jewelry: 📿💎', a: 'Necklace' },
      { q: 'Guess where birds keep their eggs: 🐣🌳🥚', a: 'Nest' },
    ],
    O: [
      { q: 'Guess the sea animal: 🐙', a: 'Octopus' },
      { q: 'Guess the night bird: 🦉', a: 'Owl' },
      { q: 'Guess the fruit: 🍊', a: 'Orange' },
      { q: 'Guess the place: 🌊🐋⛵', a: 'Ocean', alt: ['Sea'] },
      { q: 'Guess the sports event: 🏅🔥🌍', a: 'Olympics', alt: ['Olympic Games', 'The Olympics'] },
      { q: 'Guess the kitchen liquid: 🫒🧴', a: 'Olive Oil' },
      { q: 'Guess the vegetable that makes you cry: 🧅😢', a: 'Onion' },
      { q: 'Guess the breakfast: 🌾🥣', a: 'Oatmeal', alt: ['Porridge', 'Oats'] },
    ],
    P: [
      { q: 'Guess the city: 🗼🥐', a: 'Paris' },
      { q: 'Guess the animal: 🐧❄️', a: 'Penguin' },
      { q: 'Guess the animal: 🐼🎋', a: 'Panda' },
      { q: 'Guess the breakfast: 🥞🍁', a: 'Pancakes', alt: ['Pancake'] },
      { q: 'Guess the sea robbers: 🏴‍☠️⚓🦜', a: 'Pirates', alt: ['Pirate'] },
      { q: 'Guess the job: 👮🚓', a: 'Police Officer', alt: ['Policeman', 'Police', 'Cop'] },
      { q: 'Guess the fairy tale: 🤥👃🪵', a: 'Pinocchio' },
      { q: 'Guess the snack from the pieces: 💥🌽', a: 'Popcorn' },
      { q: 'Guess the instrument: 🎹', a: 'Piano' },
      { q: 'Guess the sport: 🏓', a: 'Ping Pong', alt: ['Table Tennis'] },
      { q: 'Guess the fairy-tale boy: 🧚⏰🐊🏴‍☠️', a: 'Peter Pan' },
      { q: 'Guess the Halloween vegetable: 🎃', a: 'Pumpkin' },
      { q: 'Guess the job: 🎨🖌️', a: 'Painter', alt: ['Artist'] },
      { q: 'Guess the food: 🥜🧈🍞', a: 'Peanut Butter' },
    ],
    Q: [
      { q: 'Guess the royal: 👸👑', a: 'Queen' },
      { q: 'Guess the hive ruler: 👑🐝', a: 'Queen Bee' },
      { q: 'Guess the symbol: ❓', a: 'Question Mark' },
      { q: 'Guess the sound a duck makes: 🦆💬', a: 'Quack' },
    ],
    R: [
      { q: 'Guess the compound word: 🌧️🎀', a: 'Rainbow' },
      { q: 'Guess the animal: 🐇🥕', a: 'Rabbit', alt: ['Bunny'] },
      { q: 'Guess the fairy tale: 👸🗼💇‍♀️', a: 'Rapunzel' },
      { q: 'Guess the fairy tale: 👧🔴🧥🐺', a: 'Red Riding Hood', alt: ['Little Red Riding Hood'] },
      { q: 'Guess the city: 🏛️🍝⛲', a: 'Rome' },
      { q: 'Guess the boxing movie: 🥊🏃🥩', a: 'Rocky' },
      { q: 'Guess the food: 🍚🥢', a: 'Rice' },
      { q: 'Guess the machine: 🤖', a: 'Robot' },
      { q: 'Guess the vehicle: 🚀🌌', a: 'Rocket' },
      { q: 'Guess the sport: 🏉', a: 'Rugby' },
      { q: 'Guess the jewelry: 💍', a: 'Ring' },
    ],
    S: [
      { q: 'Guess the superhero: 🕷️🕸️🦸', a: 'Spider-Man', alt: ['Spiderman'] },
      { q: 'Guess the fairy tale: ❄️👸🍎🪞', a: 'Snow White' },
      { q: 'Guess the fairy tale: 😴👸🌹💤', a: 'Sleeping Beauty' },
      { q: 'Guess the movie: ⭐⚔️🚀', a: 'Star Wars' },
      { q: 'Guess the compound word: ⭐🐟', a: 'Starfish' },
      { q: 'Guess the compound word: ☀️🌼', a: 'Sunflower' },
      { q: 'Guess the animal: 🦈🌊', a: 'Shark' },
      { q: 'Guess the animal: 🐍', a: 'Snake' },
      { q: 'Guess the food: 🍝', a: 'Spaghetti', alt: ['Pasta'] },
      { q: 'Guess the food: 🍣🥢', a: 'Sushi' },
      { q: 'Guess the country: 💃🥘🐂', a: 'Spain' },
      { q: 'Guess the sport: ⚽🥅', a: 'Soccer', alt: ['Football'] },
      { q: 'Guess the job: 🎤🎶', a: 'Singer' },
      { q: 'Guess the winter figure: ⛄', a: 'Snowman' },
      { q: 'Guess the water sport: 🏄🌊', a: 'Surfing' },
      { q: 'Guess the compound word: 🛹', a: 'Skateboard' },
      { q: 'Guess the slow animal: 🐌', a: 'Snail' },
      { q: 'Guess the season: ☀️🏖️🍉', a: 'Summer' },
    ],
    T: [
      { q: 'Guess the movie: 🚢🧊💔', a: 'Titanic' },
      { q: 'Guess the movie: 🤖🚗🔄', a: 'Transformers' },
      { q: 'Guess the animal: 🐯', a: 'Tiger' },
      { q: 'Guess the animal: 🐢', a: 'Turtle', alt: ['Tortoise'] },
      { q: 'Guess the food: 🌮', a: 'Taco', alt: ['Tacos'] },
      { q: 'Guess the city: 🗼🍣🎌', a: 'Tokyo' },
      { q: 'Guess the compound word: 🦷🪥', a: 'Toothbrush' },
      { q: 'Guess the job: 👩‍🏫📚🏫', a: 'Teacher' },
      { q: 'Guess the sport: 🎾', a: 'Tennis' },
      { q: 'Guess the landmark: 🕌🇮🇳', a: 'Taj Mahal', alt: ['The Taj Mahal'] },
      { q: 'Guess the movie: 🤠👨‍🚀🧸', a: 'Toy Story' },
      { q: 'Guess the weather: ⛈️⚡', a: 'Thunderstorm', alt: ['Storm', 'Thunder'] },
      { q: 'Guess what pirates hunt: 🗺️❌💰', a: 'Treasure' },
      { q: 'Guess the farm vehicle: 🚜🌾', a: 'Tractor' },
    ],
    U: [
      { q: 'Guess the rainy-day item: ☂️', a: 'Umbrella' },
      { q: 'Guess the magical animal: 🦄', a: 'Unicorn' },
      { q: 'Guess the flying mystery: 🛸👽', a: 'UFO', alt: ['Flying Saucer'] },
      { q: 'Guess the movie: 🎈🏠👴', a: 'Up' },
    ],
    V: [
      { q: 'Guess the mountain that erupts: 🌋', a: 'Volcano' },
      { q: 'Guess the spooky creature: 🧛🦇', a: 'Vampire' },
      { q: 'Guess the instrument: 🎻', a: 'Violin' },
      { q: 'Guess the city: 🚣🌊🎭', a: 'Venice' },
      { q: 'Guess the job: 🩺🐶🐱', a: 'Vet', alt: ['Veterinarian'] },
    ],
    W: [
      { q: 'Guess the animal: 🐺🌕', a: 'Wolf' },
      { q: 'Guess the sea giant: 🐋', a: 'Whale' },
      { q: 'Guess the fruit from the pieces: 💧🍈', a: 'Watermelon' },
      { q: 'Guess the movie: 🌪️👠🌈', a: 'Wizard of Oz', alt: ['The Wizard of Oz'] },
      { q: 'Guess the nature sight: 🌊⬇️🏞️', a: 'Waterfall' },
      { q: 'Guess the job: 🍽️📝💁', a: 'Waiter', alt: ['Waitress', 'Server'] },
      { q: 'Guess the season: ❄️🧣⛄', a: 'Winter' },
      { q: 'Guess the big event: 💒👰🤵', a: 'Wedding' },
      { q: 'Guess the spell-caster: 🧙‍♀️🧹🔮', a: 'Witch' },
    ],
    Y: [
      { q: 'Guess the exercise: 🧘', a: 'Yoga' },
      { q: 'Guess the toy: 🪀', a: 'Yo-yo', alt: ['Yoyo'] },
      { q: 'Guess the egg part: 🍳🟡', a: 'Yolk' },
    ],
    Z: [
      { q: 'Guess the striped animal: 🦓', a: 'Zebra' },
      { q: 'Guess the place: 🎟️🦁🐘🦒', a: 'Zoo' },
      { q: 'Guess the monster: 🧟🧠', a: 'Zombie' },
      { q: 'Guess the Greek god: ⚡🏛️👑', a: 'Zeus' },
    ],
  },
};
