import type { RawPack } from '../core/packs';

// Emoji Puzzles · Medium — multi-step emoji rebuses: movies/shows, idioms & phrases,
// songs, books, brands, countries/cities (landmark clues, no flags), compound
// concepts and famous duos. Every question is emoji-only plus a category label;
// answers are 1-3 words and bucketed by their first letter.
export const emojiMediumPack: RawPack = {
  id: 'emoji-medium',
  name: 'Emoji Puzzles · Medium',
  description: 'Trickier emoji riddles — idioms, titles and mashups.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🤔',
  accent: '#ca8a04',
  letters: {
    A: [
      { q: 'Brand: 🍎⌚', a: 'Apple Watch' },
      { q: 'Movie: 🔵🧑🌳🏹🪐', a: 'Avatar' },
      { q: 'Movie: 🦸🦸‍♀️🤝💥🧤', a: 'Avengers', alt: ['The Avengers'] },
      { q: 'Movie: 👽🥚🚀😱', a: 'Alien' },
      { q: 'Idiom: 🏛️🏹🦶', a: 'Achilles Heel' },
      { q: 'Song: 🙏🌧️🥁🌍', a: 'Africa' },
      { q: 'City: 🚲🌷🛶', a: 'Amsterdam' },
      { q: 'Book: 🐷🐴🚜', a: 'Animal Farm' },
      { q: 'Brand: 📦🙂➡️', a: 'Amazon' },
      { q: 'Country: 🦘🕷️🏄', a: 'Australia' },
      { q: 'Famous duo: 🧑👩🍎🐍', a: 'Adam and Eve' },
    ],
    B: [
      { q: 'Concept: 🧠➕⛈️', a: 'Brainstorm' },
      { q: 'Movie: 🦇🧑', a: 'Batman' },
      { q: 'Idiom: 🐝🦵🦵', a: 'Bees Knees', alt: ['Bee\'s Knees', 'The Bee\'s Knees'] },
      { q: 'Brand: 🍔➕👑', a: 'Burger King' },
      { q: 'Book: 💪🆕🌍', a: 'Brave New World' },
      { q: 'City: 🐻🧱🚧', a: 'Berlin' },
      { q: 'Country: ⚽💃🌴', a: 'Brazil' },
      { q: 'Famous duo: 🔫💑🚗💨', a: 'Bonnie and Clyde' },
      { q: 'Idiom: ⛏️🧊', a: 'Break the Ice' },
      { q: 'Phrase: 🔵➕🌕', a: 'Blue Moon' },
      { q: 'Concept: 📖➕🪱', a: 'Bookworm' },
    ],
    C: [
      { q: 'Idiom: 🧊❄️😐', a: 'Cold Shoulder', alt: ['The Cold Shoulder'] },
      { q: 'Idiom: 🛋️➕🥔', a: 'Couch Potato' },
      { q: 'Movie: 🚗😀🏁', a: 'Cars' },
      { q: 'Concept: 📋➕🐱', a: 'Copycat' },
      { q: 'Brand: 🔴🥤🐻‍❄️', a: 'Coca-Cola', alt: ['Coke', 'Coca Cola'] },
      { q: 'Country: 🍁🫎🏒', a: 'Canada' },
      { q: 'City: 🕌🔺🐫', a: 'Cairo' },
      { q: 'Idiom: 🐔🚪🏃', a: 'Chicken Out' },
      { q: 'Story: 👠🎃🕛', a: 'Cinderella' },
      { q: 'Concept: 🧗⛰️😱', a: 'Cliffhanger' },
      { q: 'Concept: 🐱➕🐟', a: 'Catfish' },
      { q: 'Concept: 🚗➕🏊', a: 'Carpool' },
    ],
    D: [
      { q: 'Book: 🦇🏰🩸', a: 'Dracula' },
      { q: 'Concept: 💀➕📏', a: 'Deadline' },
      { q: 'Brand: 🏀➕🍩', a: 'Dunkin Donuts', alt: ['Dunkin\' Donuts', 'Dunkin'] },
      { q: 'City: 🏗️🌴💰🏜️', a: 'Dubai' },
      { q: 'Country: 🧜‍♀️🧱🥐', a: 'Denmark' },
      { q: 'Song: 💃➕👑🪩', a: 'Dancing Queen' },
      { q: 'Movie: 🐘🪶✈️', a: 'Dumbo' },
      { q: 'Concept: ☀️➕💭', a: 'Daydream' },
      { q: 'Game: 🦍🛢️🍌', a: 'Donkey Kong' },
      { q: 'Game: 🏰⛓️🐉🎲', a: 'Dungeons and Dragons', alt: ['D&D'] },
    ],
    E: [
      { q: 'Idiom: ⏰🐦🪱', a: 'Early Bird', alt: ['The Early Bird'] },
      { q: 'Movie: 👽🚲🌕☎️', a: 'E.T.', alt: ['ET'] },
      { q: 'Landmark: 🗼✨🌃🥐', a: 'Eiffel Tower', alt: ['The Eiffel Tower'] },
      { q: 'Country: 🔺🐫📜', a: 'Egypt' },
      { q: 'Brand: 💻🛍️🔨', a: 'eBay' },
      { q: 'Concept: 🐇🥚🤫', a: 'Easter Egg' },
      { q: 'Concept: 👂➕🪱🎶', a: 'Earworm' },
      { q: 'Concept: 🦅➕👁️', a: 'Eagle Eye' },
      { q: 'Movie: 🏠✨🦋🕯️', a: 'Encanto' },
    ],
    F: [
      { q: 'Movie: ❄️👸⛄🎶', a: 'Frozen' },
      { q: 'Movie: 🔍🐠', a: 'Finding Nemo' },
      { q: 'Brand: 🔥➕🦊', a: 'Firefox' },
      { q: 'Song: 🎆🎤💥', a: 'Firework' },
      { q: 'Country: 🍷🥖🧀', a: 'France' },
      { q: 'Book: 🧟⚡🧪', a: 'Frankenstein' },
      { q: 'Idiom: 💰🐱', a: 'Fat Cat' },
      { q: 'Movie: 👊🧼🤫', a: 'Fight Club' },
      { q: 'Concept: 4️⃣🍀', a: 'Four Leaf Clover', alt: ['Four-Leaf Clover'] },
      { q: 'Phrase: 🐺🌕🎑', a: 'Full Moon' },
    ],
    G: [
      { q: 'Movie: 👻🚫🔫', a: 'Ghostbusters' },
      { q: 'Slang: 🐐🏆', a: 'GOAT', alt: ['The GOAT', 'Goat'] },
      { q: 'Brand: 🔍🌐', a: 'Google' },
      { q: 'Landmark: 🌉🌁🔴', a: 'Golden Gate Bridge', alt: ['The Golden Gate Bridge'] },
      { q: 'Landmark: 🧱⛰️🐉', a: 'Great Wall', alt: ['The Great Wall', 'Great Wall of China'] },
      { q: 'Country: 🏛️🫒⛵', a: 'Greece' },
      { q: 'Book: 🍇😡', a: 'Grapes of Wrath', alt: ['The Grapes of Wrath'] },
      { q: 'Movie: 🦎🏙️🔥', a: 'Godzilla' },
      { q: 'Idiom: 🟢👍🌱', a: 'Green Thumb' },
      { q: 'Concept: 🪿➕😨', a: 'Goosebumps' },
    ],
    H: [
      { q: 'Book: ⚡👓🧙', a: 'Harry Potter' },
      { q: 'Song: 👋☎️😢🎤', a: 'Hello' },
      { q: 'Idiom: 👊🌾😴', a: 'Hit the Hay' },
      { q: 'Idiom: ✋🐎🐎', a: 'Hold Your Horses' },
      { q: 'Food: 🔥➕🐶', a: 'Hot Dog' },
      { q: 'Place: 🎬⭐🪧⛰️', a: 'Hollywood' },
      { q: 'Country: sounds like 😋🍽️', a: 'Hungary' },
      { q: 'Book: 🏹🔥👧🎯', a: 'Hunger Games', alt: ['The Hunger Games'] },
      { q: 'Song: 💔➕🏨', a: 'Heartbreak Hotel' },
      { q: 'Movie: 🏠👦😱🎄', a: 'Home Alone' },
      { q: 'Concept: 🍯➕🌕', a: 'Honeymoon' },
    ],
    I: [
      { q: 'Movie: 👨‍🚀🪐⏳', a: 'Interstellar' },
      { q: 'Movie: 🧠😢😡😨', a: 'Inside Out' },
      { q: 'Brand: 🍏📱', a: 'iPhone' },
      { q: 'Country: 🍀🌈🍺', a: 'Ireland' },
      { q: 'Country: 🍕🍝🛵', a: 'Italy' },
      { q: 'Concept: 🧊⛰️🚢', a: 'Iceberg' },
      { q: 'Movie: 🔩🧑🦸', a: 'Iron Man' },
      { q: 'Book: 🫥🧑', a: 'Invisible Man', alt: ['The Invisible Man'] },
      { q: 'Song: 💭🎹☮️', a: 'Imagine' },
    ],
    J: [
      { q: 'Movie: 🦈🏖️😱', a: 'Jaws' },
      { q: 'Movie: 🦖🏝️⚠️', a: 'Jurassic Park' },
      { q: 'Story: 🌴🐻🐆👦', a: 'Jungle Book', alt: ['The Jungle Book'] },
      { q: 'Brand: ✈️➕🔵', a: 'JetBlue' },
      { q: 'Song: 🔔🔔🎄🛷', a: 'Jingle Bells' },
      { q: 'City: ✡️⛪🕌🧱', a: 'Jerusalem' },
      { q: 'Country: 🗻⛩️🍜', a: 'Japan' },
      { q: 'Concept: 🗑️➕🍔', a: 'Junk Food' },
      { q: 'Idiom: 🤸➕🔫', a: 'Jump the Gun' },
    ],
    K: [
      { q: 'Movie: 🦍🏢✈️👱‍♀️', a: 'King Kong' },
      { q: 'Movie: 🐼🥋', a: 'Kung Fu Panda' },
      { q: 'Brand: 🍗🪣🧓', a: 'KFC' },
      { q: 'Concept: 🔪➕🐋', a: 'Killer Whale' },
      { q: 'Idiom: 🦵➕🪣', a: 'Kick the Bucket' },
      { q: 'Country: 🦁🦒🏃🥇', a: 'Kenya' },
      { q: 'Movie: 🔪➕💵', a: 'Kill Bill' },
    ],
    L: [
      { q: 'Movie: 🦁➕👑', a: 'Lion King', alt: ['The Lion King'] },
      { q: 'Brand: 🧱🟥🟨🟦', a: 'Lego' },
      { q: 'City: 🕰️💂🎡', a: 'London' },
      { q: 'City: 😇😇🌴', a: 'Los Angeles', alt: ['LA'] },
      { q: 'Phrase: 📏➕🏹', a: 'Long Shot' },
      { q: 'Song: 🤲🐝🎶', a: 'Let It Be' },
      { q: 'Movie: 🎶🎹💃🌆', a: 'La La Land' },
      { q: 'Book: 🤏👩👩👩', a: 'Little Women' },
      { q: 'Concept: ❤️➕🔺', a: 'Love Triangle' },
    ],
    M: [
      { q: 'Brand: 🍔🍟🤡', a: 'McDonald\'s', alt: ['McDonalds'] },
      { q: 'Movie: 🔴💊🔵💊🕶️', a: 'Matrix', alt: ['The Matrix'] },
      { q: 'Concept: 🥛➕🛣️', a: 'Milky Way', alt: ['The Milky Way'] },
      { q: 'Idiom: 🐒➕💼', a: 'Monkey Business' },
      { q: 'City: 🏰🔴⬛❄️', a: 'Moscow' },
      { q: 'Country: 🌮🌵🎸', a: 'Mexico' },
      { q: 'Book: 🐋⚪🚢', a: 'Moby Dick' },
      { q: 'Concept: 🌕➕🚶🕺', a: 'Moonwalk' },
      { q: 'Famous duo: 🐭❤️🐭🎀', a: 'Mickey and Minnie' },
      { q: 'Slang: 🧠💥🤯', a: 'Mind Blown' },
      { q: 'Landmark: ⛰️🗿4️⃣', a: 'Mount Rushmore' },
    ],
    N: [
      { q: 'Brand: ✔️👟', a: 'Nike' },
      { q: 'Brand: 📺🍿🔴', a: 'Netflix' },
      { q: 'City: 🗽🍎🌆', a: 'New York', alt: ['New York City', 'NYC'] },
      { q: 'Concept: 🌙➕🦉', a: 'Night Owl' },
      { q: 'Country: 🧀🌷🚲', a: 'Netherlands', alt: ['The Netherlands', 'Holland'] },
      { q: 'Story: 🚪🧥❄️🦁', a: 'Narnia' },
      { q: 'Slang: 🚫➕🧠', a: 'No Brainer', alt: ['No-Brainer'] },
      { q: 'Landmark: 🌊⬇️🚣', a: 'Niagara Falls' },
      { q: 'Ballet: 🥜🔨🎄🩰', a: 'Nutcracker', alt: ['The Nutcracker'] },
    ],
    O: [
      { q: 'Movie: 💣🧑‍🔬🎩', a: 'Oppenheimer' },
      { q: 'Idiom: 🔓➕📖', a: 'Open Book', alt: ['An Open Book'] },
      { q: 'Idiom: 🔛🤏🧊', a: 'On Thin Ice' },
      { q: 'Book: 👦🍲🥄🌀', a: 'Oliver Twist' },
      { q: 'Brand: ⚫⚪⚫🍪🥛', a: 'Oreo' },
      { q: 'Movie: 🌊1️⃣1️⃣🎰💰', a: 'Ocean\'s Eleven', alt: ['Oceans Eleven', 'Oceans 11'] },
      { q: 'Phrase: 🫒➕🌿🕊️', a: 'Olive Branch', alt: ['An Olive Branch'] },
    ],
    P: [
      { q: 'Song: 🎹➕🧑🍺', a: 'Piano Man' },
      { q: 'Idiom: 🧩🍰', a: 'Piece of Cake', alt: ['A Piece of Cake'] },
      { q: 'Brand: 🍕➕🛖', a: 'Pizza Hut' },
      { q: 'City: 🗼❤️💋', a: 'Paris' },
      { q: 'Country: 🦙⛰️🏛️', a: 'Peru' },
      { q: 'Movie: 🧃📖🔫💃', a: 'Pulp Fiction' },
      { q: 'Book: 🦁➕🧐', a: 'Pride and Prejudice' },
      { q: 'Slang: 🎉➕🐾', a: 'Party Animal' },
      { q: 'Idiom: 🚰➕💭', a: 'Pipe Dream', alt: ['A Pipe Dream'] },
      { q: 'Song: 🟣➕🌧️', a: 'Purple Rain' },
    ],
    Q: [
      { q: 'Concept: 👑➕🐝', a: 'Queen Bee' },
      { q: 'Phrase: ⚡➕🔧', a: 'Quick Fix', alt: ['A Quick Fix'] },
    ],
    R: [
      { q: 'Movie: 🥊🥩🪜🏃', a: 'Rocky' },
      { q: 'Concept: 🛣️➕🧳🚗', a: 'Road Trip' },
      { q: 'Brand: 🔴➕🐂🪽', a: 'Red Bull' },
      { q: 'City: 🏛️⛲🐺', a: 'Rome' },
      { q: 'Country: 🐻❄️🪆', a: 'Russia' },
      { q: 'Play: 🧑❤️👩🏰🗡️😢', a: 'Romeo and Juliet' },
      { q: 'Book: 🏝️🧔⛵👣', a: 'Robinson Crusoe' },
      { q: 'Phrase: 🏃💨➕🕐🚗', a: 'Rush Hour' },
      { q: 'Movie: 🐀👨‍🍳🍲', a: 'Ratatouille' },
      { q: 'Concept: 🌧️➕🏹', a: 'Rainbow' },
    ],
    S: [
      { q: 'Movie: 🕷️🧑', a: 'Spider-Man', alt: ['Spiderman', 'Spider Man'] },
      { q: 'Movie: ⭐➕⚔️🚀', a: 'Star Wars' },
      { q: 'Brand: ⭐➕💵☕', a: 'Starbucks' },
      { q: 'Song: 🪜☁️😇🎸', a: 'Stairway to Heaven' },
      { q: 'Idiom: 🫗🫘', a: 'Spill the Beans' },
      { q: 'Idiom: 👃🐀', a: 'Smell a Rat' },
      { q: 'Country: 🦁⛲🏙️', a: 'Singapore' },
      { q: 'Country: 💃🥘🐂', a: 'Spain' },
      { q: 'Book: 🕵️🎻🔍', a: 'Sherlock Holmes' },
      { q: 'Movie: 🟢👹🧅', a: 'Shrek' },
      { q: 'TV show: 🧽➕👖', a: 'SpongeBob', alt: ['SpongeBob SquarePants'] },
      { q: 'Concept: 🤏➕💬', a: 'Small Talk' },
      { q: 'Concept: ☀️➕🌸', a: 'Sunflower' },
    ],
    T: [
      { q: 'Movie: 🚢🧊💔', a: 'Titanic' },
      { q: 'Movie: 🤖🕶️👍🔥', a: 'Terminator', alt: ['The Terminator'] },
      { q: 'Movie: 🤠🚀🧸', a: 'Toy Story' },
      { q: 'Brand: ⚡🚗🔋', a: 'Tesla' },
      { q: 'Landmark: 🕌⚪💕', a: 'Taj Mahal', alt: ['The Taj Mahal'] },
      { q: 'City: 🚄🏙️🍣🌸', a: 'Tokyo' },
      { q: 'Country: 🦃', a: 'Turkey' },
      { q: 'Idiom: ⏰➕🪰', a: 'Time Flies' },
      { q: 'Song: 🧟🕺🌕', a: 'Thriller' },
      { q: 'Famous duo: 🐱🔨🐭', a: 'Tom and Jerry' },
      { q: 'Slang: 3️⃣➕🛞', a: 'Third Wheel', alt: ['A Third Wheel'] },
    ],
    U: [
      { q: 'Idiom: ⬇️🌧️🤒', a: 'Under the Weather' },
      { q: 'Movie: 🎈🏠👴', a: 'Up' },
      { q: 'Concept: ⬇️➕🐶', a: 'Underdog', alt: ['The Underdog'] },
      { q: 'Country: 🗽🦅🏈', a: 'United States', alt: ['USA', 'America', 'United States of America', 'The United States'] },
      { q: 'Brand: 📦🟤🚚', a: 'UPS' },
    ],
    V: [
      { q: 'City: 🛶🎭🌊🌉', a: 'Venice' },
      { q: 'Country: 🍜🛵🌾', a: 'Vietnam' },
      { q: 'Concept: 🗣️➕📬', a: 'Voicemail' },
    ],
    W: [
      { q: 'Movie: 🤖🌱🗑️🚀', a: 'WALL-E', alt: ['WALLE', 'Wall E'] },
      { q: 'Movie: 🧙🌪️👠🟡🛣️', a: 'Wizard of Oz', alt: ['The Wizard of Oz'] },
      { q: 'Landmark: ⚪➕🏠', a: 'White House', alt: ['The White House'] },
      { q: 'Idiom: 🤪🪿🏃', a: 'Wild Goose Chase', alt: ['A Wild Goose Chase'] },
      { q: 'Brand: 🟢💬📞', a: 'WhatsApp' },
      { q: 'Book: ⚔️➕🕊️', a: 'War and Peace' },
      { q: 'Phrase: 🏆➕🏆', a: 'Win-Win', alt: ['Win Win'] },
      { q: 'Food: 💧➕🍈', a: 'Watermelon' },
    ],
    X: [
      { q: 'Movie: ❌🧬🦸', a: 'X-Men', alt: ['X Men', 'XMen'] },
      { q: 'Concept: ❌🦴📷', a: 'X-Ray', alt: ['X Ray', 'Xray'] },
    ],
    Y: [
      { q: 'Song: 🟡🛥️🌊⬇️🎶', a: 'Yellow Submarine' },
      { q: 'Brand: ▶️🔴📹', a: 'YouTube' },
      { q: 'Place: 🟡➕🪨♨️🐻', a: 'Yellowstone' },
    ],
    Z: [
      { q: 'Concept: 🦓➕🚶🛣️', a: 'Zebra Crossing', alt: ['A Zebra Crossing'] },
      { q: 'Movie: 🦊🐰👮🏙️', a: 'Zootopia' },
      { q: 'Brand: 💻📹👥', a: 'Zoom' },
    ],
  },
};
