import type { RawPack } from '../core/packs';

export const engineeringPack: RawPack = {
  id: 'engineering',
  name: 'Great Engineering',
  description: 'Bridges, tunnels, dams, canals, machines and the engineers behind them.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🏗️',
  accent: '#ca8a04',
  letters: {
    A: [
      { q: 'The channel or raised structure built to carry water across country.', a: 'Aqueduct' },
      { q: 'The curved form that carries a load in compression, used since Rome.', a: 'Arch' },
      { q: 'The Japanese suspension crossing near Kobe, the longest main span until 2022.', a: 'Akashi Kaikyo' },
      { q: 'The Greek of Syracuse credited with the screw pump and the law of buoyancy.', a: 'Archimedes' },
      { q: 'A metal mixed from two or more elements to make it stronger.', a: 'Alloy' },
      { q: 'The light metal, first made cheaply in the 1880s, that made aircraft possible.', a: 'Aluminium' },
      { q: 'The German motorway network begun in the 1930s, famous for having no limit.', a: 'Autobahn' },
      { q: 'The moving production method Henry Ford introduced at Highland Park in 1913.', a: 'Assembly line' },
      { q: 'The block of concrete that holds the ends of a suspension cable to the ground.', a: 'Anchorage' },
      { q: 'The part of a bridge that takes the thrust of the span into the ground at each end.', a: 'Abutment' },
      { q: 'The 1971 Egyptian dam whose lake drowned Nubia and stopped the annual flood.', a: 'Aswan High Dam' },
    ],
    B: [
      { q: 'The Victorian genius of the Great Western Railway, the Thames tunnel and the Clifton span.', a: 'Brunel' },
      { q: 'The 1883 East River crossing of stone towers and steel wire, then the longest anywhere.', a: 'Brooklyn Bridge' },
      { q: 'The sliding or rocking support that lets a span expand without cracking.', a: 'Bearing' },
      { q: 'The tracked machine with a broad blade that pushes earth about.', a: 'Bulldozer' },
      { q: 'The Englishman whose 1856 converter turned pig iron into cheap steel.', a: 'Bessemer' },
      { q: 'The Dubai spire that has been the tallest structure on Earth since 2010.', a: 'Burj Khalifa' },
      { q: 'The prefabricated military crossing invented in 1940 and carried on lorries.', a: 'Bailey bridge' },
      { q: 'The hollow closed beam, square or trapezoid in section, used in modern decks.', a: 'Box girder' },
      { q: 'The simplest structural member, resting on supports and bending under load.', a: 'Beam' },
      { q: 'The Alpine rail route under the Gotthard opened in 2016 is called a base one of these.', a: 'Bore' },
      { q: 'The mixture of gravel or stone that beds a railway track and drains it.', a: 'Ballast' },
      { q: 'The counterweighted lifting span, from the French for seesaw.', a: 'Bascule' },
    ],
    C: [
      { q: 'The structure that projects out from one support only, as at the Forth.', a: 'Cantilever' },
      { q: 'Sand, gravel and cement mixed with water to set hard as artificial stone.', a: 'Concrete' },
      { q: 'The lifting machine with a jib, essential to every large site.', a: 'Crane' },
      { q: 'A cut waterway made for boats.', a: 'Canal' },
      { q: 'The airtight box sunk to the river bed so men can work below the water.', a: 'Caisson' },
      { q: 'The burnt limestone powder, patented as Portland in 1824, that binds concrete.', a: 'Cement' },
      { q: 'The 50 km rail link under the Straits of Dover, opened in 1994.', a: 'Channel Tunnel' },
      { q: 'The modern bridge type whose deck hangs from straight cables running to a tower.', a: 'Cable-stayed' },
      { q: 'The software that replaced the drawing board, known by three letters.', a: 'CAD' },
      { q: 'The temporary watertight enclosure pumped dry so foundations can be built.', a: 'Cofferdam' },
      { q: 'The Prague stone crossing of 1357 with its file of baroque statues.', a: 'Charles Bridge' },
      { q: 'The Canadian 13 km link to Prince Edward Island, opened in 1997.', a: 'Confederation Bridge' },
      { q: 'The Bristol suspension span over the Avon, designed by Brunel and finished after his death.', a: 'Clifton' },
    ],
    D: [
      { q: 'The barrier built across a valley to hold back water.', a: 'Dam' },
      { q: 'The roadway or platform surface of a bridge.', a: 'Deck' },
      { q: 'The German who patented the compression-ignition engine in 1892.', a: 'Diesel' },
      { q: 'The machine that turns rotation into electric current.', a: 'Dynamo' },
      { q: 'The rotating tool that bores a hole in rock, wood or steel.', a: 'Drill' },
      { q: 'The vessel that scoops silt from a harbour or a channel to keep it deep.', a: 'Dredger' },
      { q: 'The Chinese high-speed viaduct near Shanghai, the longest bridge in the world.', a: 'Danyang-Kunshan' },
      { q: 'The ability of a metal to be drawn out and to bend without snapping.', a: 'Ductility' },
      { q: 'The Thames crossing of tunnels and a cable-stayed span east of London.', a: 'Dartford' },
      { q: 'The explosive Alfred Nobel patented in 1867, which transformed tunnelling.', a: 'Dynamite' },
      { q: 'The bank of earth or stone raised to keep the sea or a river off the land.', a: 'Dyke' },
    ],
    E: [
      { q: 'The tracked machine with a bucket on a jointed arm that digs foundations.', a: 'Excavator' },
      { q: 'The machine that turns fuel into motion.', a: 'Engine' },
      { q: 'The car in a shaft that carries people up a tall building.', a: 'Elevator' },
      { q: 'The Frenchman whose 1889 iron tower was meant to stand for twenty years.', a: 'Eiffel' },
      { q: 'The 1825 American waterway from Albany to Buffalo that opened the Midwest.', a: 'Erie Canal' },
      { q: 'The company name under which the cross-Channel rail link is operated.', a: 'Eurotunnel' },
      { q: 'The property by which a material springs back to its old shape.', a: 'Elasticity' },
      { q: 'The moving and shaping of soil and rock that begins most projects.', a: 'Earthworks' },
      { q: 'The St Louis steel arch of 1874, the first big use of that metal in a bridge.', a: 'Eads Bridge' },
      { q: 'The gap left in a deck, filled with a sliding plate, to allow for heat movement.', a: 'Expansion joint' },
      { q: 'The moving staircase that took the prize at the Paris exposition of 1900.', a: 'Escalator' },
    ],
    F: [
      { q: 'The part of a structure below ground, which carries the load into the soil.', a: 'Foundation' },
      { q: 'The Scottish red cantilever rail crossing of 1890, painted for over a century.', a: 'Forth Bridge' },
      { q: 'The resistance that opposes sliding between two surfaces.', a: 'Friction' },
      { q: 'The temporary mould into which wet concrete is poured.', a: 'Formwork' },
      { q: 'The road bridge that carries one route over another.', a: 'Flyover' },
      { q: 'The weakening of metal under repeated loading, which brought down many bridges.', a: 'Fatigue' },
      { q: 'The Detroit maker whose moving line made the Model T cheap.', a: 'Ford' },
      { q: 'The enclosed chamber in which metal is melted or heated.', a: 'Furnace' },
      { q: 'The Alpine road tunnel of 1980 between France and Italy, under a col near Modane.', a: 'Frejus' },
      { q: 'The pivot on which a lever turns.', a: 'Fulcrum' },
      { q: 'The bridge for people only, over a road or a river.', a: 'Footbridge' },
    ],
    G: [
      { q: 'The main horizontal beam of a bridge or a floor.', a: 'Girder' },
      { q: 'The 1937 orange-red suspension crossing at the mouth of San Francisco Bay.', a: 'Golden Gate' },
      { q: 'The Swiss Alpine pass whose road, rail and base tunnels all pierce it.', a: 'Gotthard' },
      { q: 'The bridge-like frame that carries a travelling crane along a site.', a: 'Gantry' },
      { q: 'The machine, driven by steam or water, that makes electricity in a power station.', a: 'Generator' },
      { q: 'The thin cement mixture pumped into cracks and around bolts to seal them.', a: 'Grout' },
      { q: 'The toothed wheel that transmits turning force between shafts.', a: 'Gear' },
      { q: 'Coating steel with zinc to stop it rusting.', a: 'Galvanising' },
      { q: 'The Danish fixed link of 1998 across a strait between Zealand and Funen.', a: 'Great Belt' },
      { q: 'The Tyne tilting crossing of 2001, nicknamed the winking eye.', a: 'Gateshead Millennium' },
      { q: 'The steep-sided cleft that a high bridge is often built to leap.', a: 'Gorge' },
    ],
    H: [
      { q: 'The 1936 concrete arch dam on the Colorado that made Lake Mead.', a: 'Hoover Dam' },
      { q: 'The use of pressurised liquid to move heavy things.', a: 'Hydraulics' },
      { q: 'The 1981 Humberside single-span crossing, then the longest in the world.', a: 'Humber Bridge' },
      { q: 'The device of rope and drum that lifts a load vertically.', a: 'Hoist' },
      { q: 'The large shed in which aircraft are kept and serviced.', a: 'Hangar' },
      { q: 'The unit of power, defined by Watt from the pull of a dray animal.', a: 'Horsepower' },
      { q: 'The 1927 Hudson River crossing to Manhattan, the first bore with forced ventilation.', a: 'Holland Tunnel' },
      { q: 'The Kolkata cantilever crossing of 1943 that carries a vast daily crowd.', a: 'Howrah' },
      { q: 'The 55 km sea link of 2018 between Hong Kong, Zhuhai and Macau.', a: 'HZMB' },
      { q: 'The Chinese 36 km sea crossing of 2008 in Zhejiang, one of the longest over open water.', a: 'Hangzhou Bay' },
    ],
    I: [
      { q: 'The 1779 Shropshire crossing, the first ever made of cast metal.', a: 'Iron Bridge' },
      { q: 'The material that keeps heat or electricity from passing through.', a: 'Insulation' },
      { q: 'The Brazil and Paraguay dam on the Parana, long the biggest producer of hydro power.', a: 'Itaipu' },
      { q: 'The simple machine, a ramp, that trades distance for effort.', a: 'Inclined plane' },
      { q: 'The first name of the Victorian engineer of the Great Western.', a: 'Isambard' },
      { q: 'The block of cast metal, ready to be rolled or forged.', a: 'Ingot' },
      { q: 'The tunnel built as a series of sunk prefabricated sections is called this kind of tube.', a: 'Immersed' },
      { q: 'The regular checking of a structure for cracks, rust and movement.', a: 'Inspection' },
      { q: 'The Egyptian pattern of channels that spread the flood water over the fields.', a: 'Irrigation' },
    ],
    J: [
      { q: 'The screw or hydraulic device that lifts a heavy weight a short way.', a: 'Jack' },
      { q: 'The place where two members of a structure meet and are fixed.', a: 'Joint' },
      { q: 'The projecting arm of a crane, from which the hook hangs.', a: 'Jib' },
      { q: 'The pneumatic hammer that breaks up concrete and rock.', a: 'Jackhammer' },
      { q: 'The London Underground line whose 1990s extension used huge new station boxes.', a: 'Jubilee' },
    ],
    K: [
      { q: 'The wedge-shaped stone at the crown of an arch, put in last.', a: 'Keystone' },
      { q: 'The oven in which bricks, cement and pottery are fired.', a: 'Kiln' },
      { q: 'The DuPont aramid fibre, stronger than steel for its weight.', a: 'Kevlar' },
      { q: 'The unit of a thousand watts, in which power output is usually sold.', a: 'Kilowatt' },
      { q: 'The propeller-type water turbine with adjustable blades, named for an Austrian.', a: 'Kaplan' },
      { q: 'The Thai river crossing of 1943, built by prisoners, made famous by a film.', a: 'Kwai' },
    ],
    L: [
      { q: 'The weight or force a structure has to carry.', a: 'Load' },
      { q: 'The simplest machine of all, a bar turning on a pivot.', a: 'Lever' },
      { q: 'The chamber with gates that raises a boat from one water level to another.', a: 'Lock' },
      { q: 'The open framework of criss-crossing bars used in masts and old bridges.', a: 'Lattice' },
      { q: 'The Norwegian road bore of 24.5 km, the longest of its kind in the world.', a: 'Laerdal' },
      { q: 'The bridge whose span rises bodily between towers to let a ship through.', a: 'Lift bridge' },
      { q: 'The steam machine on rails that hauls a train.', a: 'Locomotive' },
      { q: 'The Vancouver suspension crossing of 1938 over the First Narrows.', a: 'Lions Gate' },
      { q: 'The narrow beam of coherent light now used to set out levels and lines on site.', a: 'Laser' },
      { q: 'The 1937 second Hudson road crossing to Manhattan, of three tubes.', a: 'Lincoln Tunnel' },
    ],
    M: [
      { q: 'Building in stone or brick, laid in courses with mortar.', a: 'Masonry' },
      { q: 'The French motorway viaduct of 2004 whose piers are the tallest anywhere.', a: 'Millau' },
      { q: 'The paste of cement, sand and water that beds bricks together.', a: 'Mortar' },
      { q: 'The London footbridge of 2000 that had to be damped after it swayed.', a: 'Millennium Bridge' },
      { q: 'The Welsh chain crossing of 1826 by Telford, the first great one of its kind.', a: 'Menai' },
      { q: 'The 1965 Alpine road bore of 11.6 km beneath the highest summit in western Europe.', a: 'Mont Blanc Tunnel' },
      { q: 'The Istanbul rail link of 2013 that runs in a tube under the Bosphorus.', a: 'Marmaray' },
      { q: 'The underground urban railway, from the French for a capital line.', a: 'Metro' },
      { q: 'The turning effect of a force about a point, which bends a beam.', a: 'Moment' },
      { q: 'The Liverpool Queensway road bore of 1934, dug under the river to Birkenhead.', a: 'Mersey Tunnel' },
      { q: 'The stiffening of a long deck against flutter is done with these deep side beams.', a: 'Main girders' },
    ],
    N: [
      { q: 'The Englishman whose three laws of motion underpin all structural analysis.', a: 'Newton' },
      { q: 'The Victorian word for the labourer who dug the canals and railways by hand.', a: 'Navvy' },
      { q: 'The 1977 West Virginia steel arch, once the longest of that type in the world.', a: 'New River Gorge' },
      { q: 'The French cable-stayed crossing of 1995 over the Seine estuary near Le Havre.', a: 'Normandy Bridge' },
      { q: 'The threaded fastener that screws onto a bolt.', a: 'Nut' },
      { q: 'The Chinese city whose 1968 Yangtze crossing was a symbol of self-reliance.', a: 'Nanjing' },
      { q: 'The small steel spike, driven not screwed, that holds timber together.', a: 'Nail' },
    ],
    O: [
      { q: 'The 2000 rail and road link of bridge, island and tunnel between Denmark and Sweden.', a: 'Oresund' },
      { q: 'The structure that carries one road above another, seen from below.', a: 'Overpass' },
      { q: 'The word for engineering work built out at sea, as for wind and oil.', a: 'Offshore' },
      { q: 'The American whose 1853 safety brake made the passenger lift possible.', a: 'Otis' },
      { q: 'The steel plate stiffened with welded ribs, light enough to floor a very long span.', a: 'Orthotropic deck' },
      { q: 'The platform standing on legs in the sea to drill for hydrocarbons.', a: 'Oil rig' },
    ],
    P: [
      { q: 'The vertical support standing in a river to carry a span.', a: 'Pier' },
      { q: 'The tall mast from which the cables of a modern bridge run.', a: 'Pylon' },
      { q: 'The machine that raises or moves a liquid.', a: 'Pump' },
      { q: 'Concrete with its steel tensioned before loading, so it never cracks in service.', a: 'Prestressed' },
      { q: 'The grooved wheel and rope that changes the direction of a pull.', a: 'Pulley' },
      { q: 'The 1914 waterway with locks that cut 13,000 km off the voyage round the Horn.', a: 'Panama Canal' },
      { q: 'The sliding part inside a cylinder that an engine drives up and down.', a: 'Piston' },
      { q: 'The long column driven into soft ground to carry a load down to firm strata.', a: 'Pile' },
      { q: 'The covered Florentine crossing lined with goldsmith shops.', a: 'Ponte Vecchio' },
      { q: 'The floating bridge carried on boats or hollow cylinders.', a: 'Pontoon' },
      { q: 'The three-tier Roman water arcade over the Gardon in southern France.', a: 'Pont du Gard' },
      { q: 'The opening at each end of a tunnel, where it meets daylight.', a: 'Portal' },
    ],
    Q: [
      { q: 'The open pit from which stone is cut for building.', a: 'Quarry' },
      { q: 'The solid stone landing stage along which ships lie in a port.', a: 'Quay' },
      { q: 'The professional who prices and measures the work on a construction contract.', a: 'Quantity surveyor' },
      { q: 'The Chinese city whose Jiaozhou Bay crossing is among the longest over water.', a: 'Qingdao' },
    ],
    R: [
      { q: 'The soft metal pin hammered hot to fasten two plates, used before welding.', a: 'Rivet' },
      { q: 'The steel bars set inside concrete to carry the tension.', a: 'Reinforcement' },
      { q: 'The German-American family who designed and built the East River crossing of 1883.', a: 'Roebling' },
      { q: 'The permanent way of rails and sleepers on which trains run.', a: 'Railway' },
      { q: 'The artificial lake held behind a great wall of concrete or earth.', a: 'Reservoir' },
      { q: 'The heavy drum machine that compacts a new road surface.', a: 'Roller' },
      { q: 'The Greek cable-stayed crossing of 2004 over the Gulf of Corinth, built to move in a quake.', a: 'Rion-Antirion' },
      { q: 'The Venetian stone arch over the Grand Canal, lined with shops.', a: 'Rialto' },
      { q: 'The sloping approach that lifts traffic up onto a flyover.', a: 'Ramp' },
    ],
    S: [
      { q: 'The bridge type whose deck hangs from cables slung between towers.', a: 'Suspension' },
      { q: 'Iron with a little carbon, the metal that made tall buildings possible.', a: 'Steel' },
      { q: 'The distance a bridge crosses between two supports.', a: 'Span' },
      { q: 'The temporary tube framework put up around a building under work.', a: 'Scaffolding' },
      { q: 'The 1869 sea-level Egyptian waterway that joined two seas without locks.', a: 'Suez Canal' },
      { q: 'The measuring of a site with level and theodolite before any work starts.', a: 'Survey' },
      { q: 'The very tall framed building, born in 1880s Chicago.', a: 'Skyscraper' },
      { q: 'The protective cylinder pushed forward at the tunnel face, invented by Brunel.', a: 'Shield' },
      { q: 'The 1932 steel arch of Australia largest city, nicknamed the coathanger.', a: 'Sydney Harbour Bridge' },
      { q: 'The Japanese 54 km undersea rail bore between Honshu and Hokkaido.', a: 'Seikan' },
      { q: 'The stress that acts to slide one part of a member past another.', a: 'Shear' },
      { q: 'The 1966 crossing of the estuary west of Bristol, whose slim aerofoil deck changed design.', a: 'Severn Bridge' },
    ],
    T: [
      { q: 'The passage bored or cut through rock or under water.', a: 'Tunnel' },
      { q: 'The framework of triangles that carries a load with very little material.', a: 'Truss' },
      { q: 'The bladed wheel spun by steam, gas or water to make power.', a: 'Turbine' },
      { q: 'The Scottish engineer of the Menai chain crossing and a thousand miles of road.', a: 'Telford' },
      { q: 'The giant rotating cutter, known by three letters, that eats through rock.', a: 'TBM' },
      { q: 'The twisting force applied by a spanner or a shaft.', a: 'Torque' },
      { q: 'The 1894 bascule crossing beside the fortress of the English capital.', a: 'Tower Bridge' },
      { q: 'The 1940 Washington suspension crossing that tore itself apart in the wind.', a: 'Tacoma Narrows' },
      { q: 'The braced timber or steel framework that carries a railway across a shallow valley.', a: 'Trestle' },
      { q: 'The Hong Kong 1997 crossing to the airport island, the longest rail and road suspension span.', a: 'Tsing Ma' },
      { q: 'The Chinese dam on the Yangtze, the largest power station ever built.', a: 'Three Gorges' },
    ],
    U: [
      { q: 'The pedestrian passage dug beneath a road.', a: 'Underpass' },
      { q: 'The upward force that can lift a light structure or a foundation slab.', a: 'Uplift' },
      { q: 'The sound-based method of finding hidden cracks in a weld or a casting.', a: 'Ultrasonic testing' },
      { q: 'The service passage carrying pipes and cables beneath a city.', a: 'Utility tunnel' },
      { q: 'The digging out of a face by hand or machine, the first act of any tunnel.', a: 'Undercutting' },
    ],
    V: [
      { q: 'The long bridge of many arches or spans that carries a road or railway.', a: 'Viaduct' },
      { q: 'The fitting that lets fluid flow one way, or shuts it off.', a: 'Valve' },
      { q: 'The 1964 suspension crossing at the mouth of New York harbour.', a: 'Verrazzano' },
      { q: 'The forced movement of air that keeps a long road tunnel breathable.', a: 'Ventilation' },
      { q: 'The shaking of a structure, which must be damped before it does harm.', a: 'Vibration' },
      { q: 'The 17 km Lisbon crossing of 1998 over the Tagus, named for a navigator.', a: 'Vasco da Gama Bridge' },
      { q: 'The deep hole sunk from the surface to reach a tunnel drive below.', a: 'Vertical shaft' },
    ],
    W: [
      { q: 'Joining two pieces of metal by melting them together.', a: 'Welding' },
      { q: 'The Scot whose separate condenser of 1769 made the steam engine efficient.', a: 'Watt' },
      { q: 'The drum and cable machine that hauls a load along.', a: 'Winch' },
      { q: 'The bundle of drawn steel strands spun into a great suspension cable.', a: 'Wire rope' },
      { q: 'The chamber in which a model is blown at to test how a bridge behaves in a gale.', a: 'Wind tunnel' },
      { q: 'The tough hammered metal of Victorian rails and chains, before mild steel came in.', a: 'Wrought iron' },
      { q: 'The 1750 Thames crossing that first gave a clear view of the city from midstream.', a: 'Westminster Bridge' },
      { q: 'The Brooklyn crossing of 1903 upstream of its famous neighbour, of all-steel towers.', a: 'Williamsburg' },
    ],
    X: [
      { q: 'The radiation used on site to photograph a weld and find the flaws inside.', a: 'X-ray' },
      { q: 'The Chinese suspension crossing on the Zhoushan islands, among the longest anywhere.', a: 'Xihoumen' },
    ],
    Y: [
      { q: 'The stress at which steel stops springing back and begins to stretch for good.', a: 'Yield strength' },
      { q: 'The crossbar that couples two things, as on a shaft or a bell.', a: 'Yoke' },
      { q: 'The Chinese river whose Three Gorges Dam is the largest power station on Earth.', a: 'Yangtze' },
    ],
    Z: [
      { q: 'The metal used to coat steel against rust, and in a torch battery.', a: 'Zinc' },
      { q: 'The Dutch scheme of dykes and drainage that turned an inland sea into farmland.', a: 'Zuiderzee Works' },
      { q: 'The Chinese open-spandrel stone arch of 605 AD, the oldest of its kind standing.', a: 'Zhaozhou' },
    ],
  },
};
