import type { RawPack } from '../core/packs';

export const fairyTalesPack: RawPack = {
  id: 'fairy-tales',
  name: 'Fairy Tales and Folklore',
  description: 'Grimm and Andersen classics, Aesop morals, and folk creatures from every corner of the world.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '🧚',
  accent: '#9d174d',
  letters: {
    A: [
      { q: 'Ancient Greek storyteller credited with the tale of the tortoise and the hare.', a: 'Aesop' },
      { q: 'Danish writer who gave the world The Little Mermaid and The Ugly Duckling (surname).', a: 'Andersen' },
      { q: 'Poor street boy of Middle Eastern tales who finds a magic lamp in a cave.', a: 'Aladdin' },
      { q: 'Woodcutter who discovers a den of forty thieves and the words open sesame.', a: 'Ali Baba' },
      { q: 'Trickster spider of Ashanti and Caribbean folk stories.', a: 'Anansi' },
      { q: 'Name given to the sleeping princess in the Disney film.', a: 'Aurora' },
      { q: 'Name given to the little mermaid in the Disney film.', a: 'Ariel' },
      { q: 'Poisoned fruit the wicked queen uses to trick Snow White.', a: 'Apple' },
      { q: 'Hard-working insect that stores food all summer while the grasshopper sings.', a: 'Ant' },
      { q: 'Common English name for the story collection framed by Scheherazade telling tales to a king.', a: 'Arabian Nights', alt: ['One Thousand and One Nights'] },
      { q: 'Greek hero whose only weak point was his heel.', a: 'Achilles' },
    ],
    B: [
      { q: 'Prince cursed into a monstrous shape who falls in love with a merchant daughter named Belle.', a: 'Beast' },
      { q: 'Book-loving heroine of a French tale who breaks a prince curse with love.', a: 'Belle' },
      { q: 'Slavic witch who lives in a hut that stands on chicken legs.', a: 'Baba Yaga' },
      { q: 'Giant plant Jack climbs to reach a castle in the clouds.', a: 'Beanstalk' },
      { q: 'Rich husband of a French tale whose forbidden room hides his murdered wives.', a: 'Bluebeard' },
      { q: 'German name for the princess who pricks her finger and sleeps a hundred years.', a: 'Briar Rose', alt: ['Little Briar Rose'] },
      { q: 'German city that four runaway musical animals set out for in a Grimm tale.', a: 'Bremen' },
      { q: 'Irish spirit whose wailing cry foretells a death in the family.', a: 'Banshee' },
      { q: 'Largest of the three creatures whose porridge and chairs Goldilocks tries.', a: 'Bear' },
      { q: 'Enchanted footwear said to carry the wearer seven leagues at every step.', a: 'Boots', alt: ['Seven-league boots'] },
      { q: 'Structure the three billy goats must cross while a troll waits beneath.', a: 'Bridge' },
    ],
    C: [
      { q: 'Girl who leaves a glass slipper behind when she flees the royal ball.', a: 'Cinderella' },
      { q: 'Talking insect who serves as the conscience of a wooden puppet.', a: 'Cricket' },
      { q: 'Clever trickster animal at the heart of many Native American stories.', a: 'Coyote' },
      { q: 'One-eyed giant blinded by Odysseus in his cave.', a: 'Cyclops' },
      { q: 'Greek creature that is half man and half horse.', a: 'Centaur' },
      { q: 'Three-headed dog that guards the gate of the Greek underworld.', a: 'Cerberus' },
      { q: 'Flying floor covering that whisks heroes across the sky in Middle Eastern tales.', a: 'Carpet' },
      { q: 'Panicking bird of a folk tale who believes the sky is falling.', a: 'Chicken Little' },
      { q: 'Fairy infant secretly swapped for a human baby in European folklore.', a: 'Changeling' },
      { q: 'Black bird tricked into dropping its cheese by a flattering fox.', a: 'Crow' },
      { q: 'Big black pot a witch stirs her bubbling brew in.', a: 'Cauldron' },
    ],
    D: [
      { q: 'Seven little miners who shelter Snow White in the forest.', a: 'Dwarfs', alt: ['Dwarves'] },
      { q: 'Braying animal that leads the four musicians toward Bremen.', a: 'Donkey' },
      { q: 'Fire-breathing beast that Saint George slays in legend.', a: 'Dragon' },
      { q: 'Spirit of Arabian folklore bound to serve whoever holds its vessel.', a: 'Djinn', alt: ['Jinn'] },
      { q: 'Ugly young bird of an Andersen tale who grows into a swan.', a: 'Duckling' },
      { q: 'Poor London boy whose cat makes his fortune in English legend.', a: 'Dick Whittington' },
      { q: 'Headless horseman of Irish folklore who calls out a name to mark a death.', a: 'Dullahan' },
      { q: 'Restless spirit of Jewish folklore that clings to and possesses the living.', a: 'Dybbuk' },
      { q: 'Animal with eyes as big as saucers that guards treasure in the Andersen tinderbox tale.', a: 'Dog' },
    ],
    E: [
      { q: 'Vain ruler tricked by two swindlers into parading in invisible clothes.', a: 'Emperor' },
      { q: 'Tiny helpers who finish the poor shoemaker work overnight in a Grimm tale.', a: 'Elves' },
      { q: 'Legendary sword of King Arthur.', a: 'Excalibur' },
      { q: 'What the golden goose lays before its greedy owner kills it.', a: 'Egg' },
      { q: 'Greek nymph cursed to repeat only the last words of others.', a: 'Echo' },
      { q: 'Greek god of love whose Roman counterpart is Cupid.', a: 'Eros' },
      { q: 'Animal whose curiosity stretches its nose into a trunk in a Kipling tale.', a: 'Elephant' },
      { q: 'Sinister German forest spirit said to lure children to their death.', a: 'Erlking' },
    ],
    F: [
      { q: 'Animal that decides the grapes are sour once it cannot reach them.', a: 'Fox' },
      { q: 'Creature who fetches a golden ball from a well and demands a place at the princess table.', a: 'Frog' },
      { q: 'Magical helper who turns a pumpkin into a coach and rags into a gown.', a: 'Fairy Godmother' },
      { q: 'Russian winter figure who rewards a polite girl and punishes a rude one.', a: 'Father Frost', alt: ['Ded Moroz'] },
      { q: 'Monstrous wolf of Norse legend destined to devour Odin.', a: 'Fenrir' },
      { q: 'Norse goddess of love whose chariot is pulled by cats.', a: 'Freya', alt: ['Freyja'] },
      { q: 'Glowing Russian bird whose single feather sends a hero on a quest.', a: 'Firebird' },
      { q: 'German tale figure who shakes out her bedding to make snow fall on the world.', a: 'Frau Holle', alt: ['Mother Holle'] },
      { q: 'Poor man in a Grimm tale whose wife keeps demanding more from a magic flounder.', a: 'Fisherman' },
      { q: 'Small winged being of European folklore said to live in mounds and grass rings.', a: 'Fairy' },
    ],
    G: [
      { q: 'Girl who wanders into a cottage and tries three bowls, three chairs and three beds.', a: 'Goldilocks' },
      { q: 'Surname of the German brothers who collected Hansel and Gretel and Rapunzel.', a: 'Grimm' },
      { q: 'Sister who shoves the witch into the oven and frees her brother.', a: 'Gretel' },
      { q: 'Lamp spirit who grants wishes to whoever rubs the metal.', a: 'Genie' },
      { q: 'Huge man who lives at the top of the beanstalk and smells a boy.', a: 'Giant' },
      { q: 'Bird that lays golden eggs until its owner cuts it open.', a: 'Goose' },
      { q: 'Sweet building material of the witch house that Hansel nibbles.', a: 'Gingerbread' },
      { q: 'Small bearded earth dweller of European folklore said to guard buried treasure.', a: 'Gnome' },
      { q: 'Beast with the head and wings of an eagle and the body of a lion.', a: 'Griffin', alt: ['Gryphon'] },
      { q: 'Clay figure brought to life by a rabbi in a famous Prague legend.', a: 'Golem' },
      { q: 'Insect that fiddles all summer and begs for food when the snow comes.', a: 'Grasshopper' },
    ],
    H: [
      { q: 'Boy who drops breadcrumbs to mark the way home out of the woods.', a: 'Hansel' },
      { q: 'Overconfident animal that naps during a race and loses to a slow rival.', a: 'Hare' },
      { q: 'Bird of a folk tale who finds grain and gets no help baking her bread.', a: 'Hen' },
      { q: 'Nursery rhyme character who falls off a wall and cannot be put back together.', a: 'Humpty Dumpty' },
      { q: 'Many-headed swamp monster that grows two heads for every one cut off.', a: 'Hydra' },
      { q: 'Greek strongman who completed twelve famous labours.', a: 'Hercules', alt: ['Heracles'] },
      { q: 'Mischievous household spirit of English folklore, cousin to the brownie.', a: 'Hobgoblin' },
      { q: 'Wooden animal the Greeks hid inside to get through the gates of Troy.', a: 'Horse' },
      { q: 'Title given to the witty Nasreddin of Turkish folk stories.', a: 'Hodja', alt: ['Hoca'] },
      { q: 'Norwegian forest woman of folklore who hides a cow tail under her dress.', a: 'Huldra' },
      { q: 'Greek ruler of the underworld who carried Persephone away.', a: 'Hades' },
    ],
    I: [
      { q: 'Boy who flew too near the sun on wings of wax and feathers.', a: 'Icarus' },
      { q: 'Most common hero name in Russian folk tales, often the youngest of three sons.', a: 'Ivan' },
      { q: 'Metal of the red-hot shoes the wicked queen is forced to dance in.', a: 'Iron' },
      { q: 'Norse goddess who guards the apples that keep the gods young.', a: 'Idun', alt: ['Idunn'] },
      { q: 'Small mischievous demon of European folklore, often a witch helper.', a: 'Imp' },
      { q: 'Egyptian goddess who gathered up the scattered body of her murdered husband.', a: 'Isis' },
    ],
    J: [
      { q: 'Boy who trades the family cow for a handful of magic beans.', a: 'Jack' },
      { q: 'English folklore figure who paints icy patterns on windows and nips noses.', a: 'Jack Frost' },
      { q: 'Name of the princess in the Disney film about a street thief and a lamp.', a: 'Jasmine' },
      { q: 'Race of giants who are the sworn enemies of the Norse gods.', a: 'Jotun', alt: ['Jotnar'] },
      { q: 'Cunning animal that plays the trickster in the Indian Panchatantra stories.', a: 'Jackal' },
      { q: 'Greek leader of the Argonauts who sought the Golden Fleece.', a: 'Jason' },
      { q: 'Nursery rhyme pair who go up a hill to fetch a pail of water.', a: 'Jack and Jill' },
      { q: 'American tall-tale rabbit said to have the antlers of a deer.', a: 'Jackalope' },
    ],
    K: [
      { q: 'Water imp of Japanese folklore with a dish of water on top of its head.', a: 'Kappa' },
      { q: 'Enormous sea monster of Scandinavian sailor tales that drags ships under.', a: 'Kraken' },
      { q: 'Scottish water horse that lures riders into a loch and drowns them.', a: 'Kelpie' },
      { q: 'Shape-shifting fox spirit of Japanese folklore that grows extra tails with age.', a: 'Kitsune' },
      { q: 'Horned Alpine folk figure who punishes naughty children in December.', a: 'Krampus' },
      { q: 'Small object stained with blood that betrays a wife who opened a forbidden door.', a: 'Key' },
      { q: 'German household and mine sprite that helps or torments the people it lives with.', a: 'Kobold' },
      { q: 'Finnish national folk epic compiled by Elias Lonnrot.', a: 'Kalevala' },
      { q: 'Moon princess of a Japanese tale who is found inside a stalk of bamboo.', a: 'Kaguya' },
    ],
    L: [
      { q: 'Great cat caught in a hunter net and set free by a tiny rodent it had spared.', a: 'Lion' },
      { q: 'Norse trickster god and father of the great wolf.', a: 'Loki' },
      { q: 'Metal object Aladdin rubs to call up a wish-granting spirit.', a: 'Lamp' },
      { q: 'Irish shoemaker sprite who hides a pot of gold at the end of a rainbow.', a: 'Leprechaun' },
      { q: 'Girl in a red cloak who meets a wolf on the way to her grandmother house.', a: 'Little Red Riding Hood' },
      { q: 'Weeping ghost woman of Mexican folklore who searches rivers for her lost children.', a: 'La Llorona' },
      { q: 'Creature said to lurk in a long deep Scottish lake in the Highlands.', a: 'Loch Ness Monster', alt: ['Nessie'] },
      { q: 'Night demon of Jewish folklore said to threaten newborn babies.', a: 'Lilith' },
      { q: 'Irish king whose four children were turned into swans for nine hundred years.', a: 'Lir' },
    ],
    M: [
      { q: 'King whose touch turned everything, even his food, into gold.', a: 'Midas' },
      { q: 'Sea maiden with a fish tail who longs to become human in an Andersen tale.', a: 'Mermaid' },
      { q: 'Object on the wall the wicked queen asks who is fairest of all.', a: 'Mirror' },
      { q: 'Tiny animal who repays a great cat for its mercy by chewing through a net.', a: 'Mouse' },
      { q: 'German baron of tall tales who claims to have ridden a cannonball through the air.', a: 'Munchausen' },
      { q: 'Staff-wielding Chinese folk hero of the tale Journey to the West.', a: 'Monkey King', alt: ['Sun Wukong'] },
      { q: 'Snake-haired woman of Greek legend whose gaze turned people to stone.', a: 'Medusa' },
      { q: 'Bull-headed man kept at the centre of the Cretan labyrinth.', a: 'Minotaur' },
      { q: 'Traditional name given to the imaginary teller of nursery rhymes.', a: 'Mother Goose' },
      { q: 'Polynesian demigod who fished up islands with a magic hook.', a: 'Maui' },
      { q: 'Wizard who guides and protects the young King Arthur.', a: 'Merlin' },
    ],
    N: [
      { q: 'Bird whose plain song the Chinese emperor comes to prefer over a jewelled clockwork copy.', a: 'Nightingale' },
      { q: 'Wooden toy soldier who battles a mouse king on Christmas Eve.', a: 'Nutcracker' },
      { q: 'Body part that grows longer every time a wooden puppet tells a lie.', a: 'Nose' },
      { q: 'Greek youth who fell in love with his own reflection in a pool.', a: 'Narcissus' },
      { q: 'German water sprite who sings people into rivers and lakes.', a: 'Nixie' },
      { q: 'Three Norse women who spin and weave the fates of gods and men.', a: 'Norns' },
      { q: 'Chinese New Year beast frightened away by red banners and loud noise.', a: 'Nian' },
      { q: 'Minor Greek nature spirit of springs, trees and mountains.', a: 'Nymph' },
    ],
    O: [
      { q: 'Man-eating giant of French tales who is outwitted by a clever booted cat.', a: 'Ogre' },
      { q: 'One-eyed chief of the Norse gods who traded his sight for wisdom.', a: 'Odin' },
      { q: 'Greek king of Ithaca whose voyage home from war took ten years.', a: 'Odysseus' },
      { q: 'Hot place the witch means to cook two children in before Gretel acts.', a: 'Oven' },
      { q: 'Night bird treated in Greek and European folklore as the symbol of wisdom.', a: 'Owl' },
      { q: 'Greek musician who went down to the land of the dead to bring back his wife.', a: 'Orpheus' },
      { q: 'Horned Japanese demon usually pictured with an iron club.', a: 'Oni' },
    ],
    P: [
      { q: 'Wooden puppet carved by Geppetto who longs to become a real boy.', a: 'Pinocchio' },
      { q: 'Tiny vegetable hidden under twenty mattresses that bruises a real princess.', a: 'Pea' },
      { q: 'Rat catcher of Hamelin who leads away the children when the town will not pay.', a: 'Pied Piper' },
      { q: 'Vegetable a fairy turns into a coach for a girl going to the ball.', a: 'Pumpkin' },
      { q: 'Clever talking cat of a French tale who tricks an ogre and makes his master a marquis.', a: 'Puss in Boots' },
      { q: 'Greek woman who opened a forbidden jar and let every trouble loose.', a: 'Pandora' },
      { q: 'Greek goddess taken to the land of the dead who eats six pomegranate seeds.', a: 'Persephone' },
      { q: 'French collector of Cinderella and Sleeping Beauty who wrote before the Grimms (surname).', a: 'Perrault' },
      { q: 'Titan who stole fire for humankind and was chained to a rock as punishment.', a: 'Prometheus' },
      { q: 'Bird of legend that burns to ash and is born again from it.', a: 'Phoenix' },
      { q: 'Ancient Indian collection of animal fables told to teach young princes.', a: 'Panchatantra' },
    ],
    Q: [
      { q: 'Vain royal woman who orders a huntsman to bring back Snow White heart in a box.', a: 'Queen' },
      { q: 'Feathered serpent god of Aztec legend.', a: 'Quetzalcoatl' },
    ],
    R: [
      { q: 'Girl shut in a tower who lets her long hair down as a ladder.', a: 'Rapunzel' },
      { q: 'Imp who spins straw into gold and demands the queen guess his name.', a: 'Rumpelstiltskin' },
      { q: 'Outlaw of Sherwood Forest who robs the rich to give to the poor.', a: 'Robin Hood' },
      { q: 'Rodent that plagues Hamelin before a piper arrives with his tune.', a: 'Rat' },
      { q: 'Cursed golden object at the heart of the Norse Nibelung legend.', a: 'Ring' },
      { q: 'Black bird of Norse legend, one of a pair perched on the shoulders of Odin.', a: 'Raven' },
      { q: 'Flower the merchant picks in a garden, putting him in the debt of a monster.', a: 'Rose' },
      { q: 'Slavic water maiden with green hair who lures young men to drown.', a: 'Rusalka' },
      { q: 'Enormous bird of Arabian tales strong enough to carry off an elephant.', a: 'Roc' },
      { q: 'Andersen footwear that dances the wearer away and will not stop.', a: 'Red Shoes' },
    ],
    S: [
      { q: 'Storyteller who saves her own life by leaving every tale unfinished at dawn.', a: 'Scheherazade' },
      { q: 'Princess woken from a poisoned sleep after seven little miners keep watch over her.', a: 'Snow White' },
      { q: 'Sailor of Arabian tales who survives seven fantastic voyages.', a: 'Sinbad', alt: ['Sindbad'] },
      { q: 'Glass footwear left behind on the palace stairs at midnight.', a: 'Slipper' },
      { q: 'English title of the tale about a princess cursed to prick her finger.', a: 'Sleeping Beauty' },
      { q: 'Sharp part of a spinning wheel that pricks a princess and sends a kingdom to sleep.', a: 'Spindle' },
      { q: 'Graceful white bird the ugly grey chick turns out to be.', a: 'Swan' },
      { q: 'Seal of Scottish folklore that sheds its skin and walks as a human.', a: 'Selkie' },
      { q: 'Riddling creature outside Thebes with the head of a woman and the body of a lion.', a: 'Sphinx' },
      { q: 'Folk tale in which a hungry traveller tricks a village into filling a pot by boiling a rock.', a: 'Stone Soup' },
      { q: 'Figure of folklore who sprinkles dust in the eyes of children to bring dreams.', a: 'Sandman' },
      { q: 'Poor craftsman whose leather is stitched up each night by tiny naked helpers.', a: 'Shoemaker' },
      { q: 'Blade drawn from a stone to prove the rightful king of England.', a: 'Sword' },
    ],
    T: [
      { q: 'Slow shelled animal that wins a race through steady plodding.', a: 'Tortoise' },
      { q: 'Ugly Scandinavian creature that lives under bridges and turns to stone in sunlight.', a: 'Troll' },
      { q: 'Norse thunder god who wields the hammer Mjolnir.', a: 'Thor' },
      { q: 'Tiny Andersen heroine born inside a flower who marries a flower prince.', a: 'Thumbelina' },
      { q: 'Andersen object that a soldier strikes to summon three treasure-guarding dogs.', a: 'Tinderbox' },
      { q: 'One-legged Andersen toy who loves a paper dancer and melts in a stove.', a: 'Tin Soldier' },
      { q: 'Shape-shifting raccoon dog of Japanese folklore, famous for its round belly.', a: 'Tanuki' },
      { q: 'Scottish ballad knight rescued from the fairy queen by a girl who will not let go.', a: 'Tam Lin' },
      { q: 'Tale of a trio of farmyard siblings who build homes of straw, sticks and brick.', a: 'Three Little Pigs' },
      { q: 'Doorless stone structure where a witch keeps a long-haired girl hidden.', a: 'Tower' },
      { q: 'Giant root vegetable that a whole family and a mouse pull up in a Russian tale.', a: 'Turnip' },
    ],
    U: [
      { q: 'White one-horned horse of European legend said to be tamed only by a maiden.', a: 'Unicorn' },
      { q: 'Land of the dead in Greek folk belief, reached by crossing a river with a ferryman.', a: 'Underworld' },
      { q: 'German water spirit who gains a human soul by marrying a mortal man.', a: 'Undine' },
      { q: 'Name of the sea witch in the Disney mermaid film.', a: 'Ursula' },
    ],
    V: [
      { q: 'Undead blood-drinker of Eastern European folklore who fears garlic and sunlight.', a: 'Vampire' },
      { q: 'Norse warrior maiden who chooses which of the battle slain go to the hall of Odin.', a: 'Valkyrie' },
      { q: 'Russian tale girl sent to Baba Yaga for fire and helped by a magic doll.', a: 'Vasilisa' },
      { q: 'What the little mermaid trades to the sea witch in exchange for legs.', a: 'Voice' },
    ],
    W: [
      { q: 'Animal that huffs and puffs and blows down houses of straw and sticks.', a: 'Wolf' },
      { q: 'Old woman of countless tales who flies on a broom and curses the young.', a: 'Witch' },
      { q: 'Slender stick a fairy waves to work her magic.', a: 'Wand' },
      { q: 'Cannibal winter spirit of Algonquian folklore, gaunt and always hungry.', a: 'Wendigo' },
      { q: 'Person of European folklore who changes into a beast under the full moon.', a: 'Werewolf' },
      { q: 'Poor forest worker who is the father of Hansel and Gretel.', a: 'Woodcutter' },
      { q: 'Deep stone hole where the frog first appears holding a golden ball.', a: 'Well' },
      { q: 'Three of these are the usual gift from a lamp spirit.', a: 'Wishes' },
      { q: 'First name of the younger of the two German tale-collecting brothers.', a: 'Wilhelm' },
      { q: 'In a Greek fable this and the sun compete to strip a traveller of his cloak.', a: 'Wind' },
    ],
    Y: [
      { q: 'Great Norse ash tree whose branches and roots link the nine worlds.', a: 'Yggdrasil' },
      { q: 'Hairy man-beast said to leave tracks in the snows of the Himalayas.', a: 'Yeti' },
      { q: 'Pale Japanese snow woman who freezes travellers with her breath.', a: 'Yuki-onna' },
    ],
    Z: [
      { q: 'King of the Greek gods who hurls thunderbolts from Mount Olympus.', a: 'Zeus' },
      { q: 'Multi-headed dragon of Slavic folklore slain by folk heroes.', a: 'Zmey' },
      { q: 'Reanimated corpse of Haitian folk belief made to work for a sorcerer.', a: 'Zombie' },
    ],
  },
};
