import type { RawPack } from '../core/packs';

export const famousFirstsPack: RawPack = {
  id: 'famous-firsts',
  name: 'Famous Firsts',
  description: 'The first person, place or thing to ever do it.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🥇',
  accent: '#ca8a04',
  letters: {
    A: [
      { q: 'The first human to set foot on the lunar surface, in July 1969.', a: 'Armstrong' },
      { q: 'This American aviator was the first woman to fly solo across the Atlantic, in 1932.', a: 'Amelia Earhart' },
      { q: 'The 1969 NASA mission that first landed people on the Moon.', a: 'Apollo 11' },
      { q: 'This city hosted the first modern Olympic Games, in 1896.', a: 'Athens' },
      { q: 'In May 1961 he became the first American to travel into space.', a: 'Alan Shepard' },
      { q: 'This Scottish scientist first noticed the mould that kills bacteria, in 1928.', a: 'Alexander Fleming' },
      { q: 'In 1988 it issued the world\'s first polymer banknotes.', a: 'Australia' },
      { q: 'This nineteenth-century mathematician is often called the first computer programmer.', a: 'Ada Lovelace' },
      { q: 'In 2005 she became the first woman to serve as German chancellor.', a: 'Angela Merkel' },
      { q: 'These two aviators made the first non-stop flight across the Atlantic, in 1919.', a: 'Alcock and Brown' },
      { q: 'The last of the seven continents to be sighted by humans, in 1820.', a: 'Antarctica' },
      { q: 'The Swedish inventor of dynamite whose will funded a set of famous annual awards.', a: 'Alfred Nobel' },
      { q: 'In 2018 it became the first United States company to be worth one trillion dollars.', a: 'Apple' },
    ],
    B: [
      { q: 'He was granted the first United States patent for the telephone, in 1876.', a: 'Bell' },
      { q: 'In 1888 she made the first long-distance journey by motor car, from Mannheim to Pforzheim.', a: 'Bertha Benz' },
      { q: 'In 1970 this team became the first to win football\'s World Cup three times.', a: 'Brazil' },
      { q: 'In 2022 it became the first city to have hosted both the Summer and Winter Olympics.', a: 'Beijing' },
      { q: 'Entering service in 1970, this was the world\'s first wide-body jet airliner.', a: 'Boeing 747' },
      { q: 'Launched in 2009, it was the world\'s first decentralised cryptocurrency.', a: 'Bitcoin' },
      { q: 'In 2009 he became the first Black president of the United States.', a: 'Barack Obama' },
      { q: 'In 1988 she became the first woman elected to lead a Muslim-majority country.', a: 'Benazir Bhutto' },
      { q: 'The 1936 Games in this city were the first Olympics shown on television.', a: 'Berlin' },
      { q: 'In 1921 she became the first African American woman to earn a pilot\'s licence.', a: 'Bessie Coleman' },
      { q: 'This Scottish inventor gave the first public demonstration of a working television system, in 1926.', a: 'Baird' },
      { q: 'The rocket plane in which the sound barrier was first broken, in 1947.', a: 'Bell X-1' },
      { q: 'In 1932 it became the first place on the Arab side of the Gulf to strike oil.', a: 'Bahrain' },
    ],
    C: [
      { q: 'This American pilot first flew faster than the speed of sound, in 1947.', a: 'Chuck Yeager' },
      { q: 'In 1903 she became the first woman to win a Nobel Prize.', a: 'Curie' },
      { q: 'His 1492 voyage opened lasting European contact with the Americas.', a: 'Columbus' },
      { q: 'The Anglo-French airliner that began the first supersonic passenger service, in 1976.', a: 'Concorde' },
      { q: 'In 2019 this nation made the first soft landing on the far side of the Moon.', a: 'China' },
      { q: 'In 1927 he made the first solo non-stop flight across the Atlantic.', a: 'Charles Lindbergh' },
      { q: 'In 2018 it became the first G7 nation to legalise recreational cannabis.', a: 'Canada' },
      { q: 'In 2011 she became the first woman to lead the International Monetary Fund.', a: 'Christine Lagarde' },
      { q: 'In 2004 this NASA probe became the first to enter orbit around Saturn.', a: 'Cassini' },
      { q: 'He designed the Analytical Engine, the first general-purpose mechanical computer.', a: 'Charles Babbage' },
      { q: 'The building usually called the world\'s first skyscraper was completed in this city in 1885.', a: 'Chicago' },
      { q: 'He was the first person to decipher Egyptian hieroglyphs, in 1822.', a: 'Champollion' },
      { q: 'In 1981 it became the first space shuttle to reach orbit.', a: 'Columbia' },
    ],
    D: [
      { q: 'The sheep born in 1996 that was the first mammal cloned from an adult cell.', a: 'Dolly' },
      { q: 'In 1989 it became the first country to recognise same-sex partnerships in law.', a: 'Denmark' },
      { q: 'The IBM machine that in 1997 first beat a reigning world chess champion in a match.', a: 'Deep Blue' },
      { q: 'In 1964 she became the first British woman to win a Nobel Prize in science.', a: 'Dorothy Hodgkin' },
      { q: 'In December 1787 it became the first state to ratify the United States Constitution.', a: 'Delaware' },
      { q: 'He invented the computer mouse in the 1960s.', a: 'Douglas Engelbart' },
      { q: 'In 2008 she became the first woman to win an IndyCar race.', a: 'Danica Patrick' },
      { q: 'This NASA probe was the first to orbit two separate worlds beyond Earth, Vesta and Ceres.', a: 'Dawn' },
      { q: 'The founder of the Red Cross who shared the first Nobel Peace Prize, in 1901.', a: 'Dunant' },
      { q: 'With Wilhelm Maybach he built the first petrol-powered motorcycle, in 1885.', a: 'Daimler' },
    ],
    E: [
      { q: 'This New Zealander was one of the first two men to reach the summit of Mount Everest, in 1953.', a: 'Edmund Hillary' },
      { q: 'He opened the world\'s first industrial research laboratory, at Menlo Park.', a: 'Edison' },
      { q: 'In 2005 this Baltic country became the first to allow binding online voting in a nationwide vote.', a: 'Estonia' },
      { q: 'This country staged the first Cricket World Cup, in 1975.', a: 'England' },
      { q: 'Completed in 1889, it was the first structure to rise above 300 metres.', a: 'Eiffel Tower' },
      { q: 'In 1849 she became the first woman to receive a medical degree in the United States.', a: 'Elizabeth Blackwell' },
      { q: 'In 1979 it became the first Arab state to sign a peace treaty with Israel.', a: 'Egypt' },
      { q: 'The world\'s highest mountain, first climbed in 1953.', a: 'Everest' },
      { q: 'He led the team that produced the first controlled nuclear chain reaction, in 1942.', a: 'Enrico Fermi' },
      { q: 'In 2019 he ran the marathon distance in under two hours for the first time.', a: 'Eliud Kipchoge' },
      { q: 'In 1796 he carried out the first successful vaccination, against smallpox.', a: 'Edward Jenner' },
    ],
    F: [
      { q: 'His company introduced the first moving assembly line for cars, in 1913.', a: 'Ford' },
      { q: 'The first public screening of projected films took place in this country in 1895.', a: 'France' },
      { q: 'In 1906 it became the first European country to let women both vote and stand for parliament.', a: 'Finland' },
      { q: 'She founded the world\'s first secular nursing school, in London in 1860.', a: 'Florence Nightingale' },
      { q: 'This British engineer patented the turbojet engine in 1930.', a: 'Frank Whittle' },
      { q: 'In 2015 this SpaceX rocket made the first upright landing of an orbital-class booster.', a: 'Falcon 9' },
      { q: 'This physicist invented the mercury thermometer in 1714.', a: 'Fahrenheit' },
      { q: 'He led the first expedition to sail around the world, though he died on the way.', a: 'Ferdinand Magellan' },
      { q: 'This Canadian doctor co-discovered insulin in 1921.', a: 'Frederick Banting' },
      { q: 'In 2012 he became the first person to break the sound barrier in freefall.', a: 'Felix Baumgartner' },
    ],
    G: [
      { q: 'On 12 April 1961 he became the first human to travel into space.', a: 'Gagarin' },
      { q: 'Under Bismarck in 1883 it created the world\'s first national health insurance scheme.', a: 'Germany' },
      { q: 'By tradition this nation always enters first in the parade at an Olympic opening ceremony.', a: 'Greece' },
      { q: 'He printed Europe\'s first major book using movable metal type, in the 1450s.', a: 'Gutenberg' },
      { q: 'This American computer scientist wrote the first compiler for a programming language.', a: 'Grace Hopper' },
      { q: 'In 1610 he became the first person to see the four largest moons of Jupiter.', a: 'Galileo' },
      { q: 'In 1969 she became the first woman to serve as prime minister of Israel.', a: 'Golda Meir' },
      { q: 'An 1884 conference chose the meridian through this London district as the world\'s prime one.', a: 'Greenwich' },
      { q: 'In 1926 she became the first woman to swim the English Channel.', a: 'Gertrude Ederle' },
      { q: 'In 1957 it became the first colony in sub-Saharan Africa to win independence from Britain.', a: 'Ghana' },
    ],
    H: [
      { q: 'Launched in 1990, it was the first large optical observatory placed in Earth orbit.', a: 'Hubble' },
      { q: 'Founded in 1636, it is the oldest university in the United States.', a: 'Harvard' },
      { q: 'In 2016 she became the first woman nominated for president by a major American party.', a: 'Hillary Clinton' },
      { q: 'This English astronomer was the first to predict the return of a comet.', a: 'Halley' },
      { q: 'Its capital opened the first underground railway on mainland Europe, in 1896.', a: 'Hungary' },
      { q: 'In August 1945 it became the first city struck by an atomic bomb.', a: 'Hiroshima' },
      { q: 'In 1940 she became the first African American to win an Academy Award.', a: 'Hattie McDaniel' },
      { q: 'In 1804 it became the first nation in the Americas founded by a successful slave revolt.', a: 'Haiti' },
      { q: 'In 1922 he became the first person in millennia to enter the tomb of Tutankhamun.', a: 'Howard Carter' },
      { q: 'In 2005 this European probe made the first landing on Titan.', a: 'Huygens' },
      { q: 'This German physicist first proved that radio waves exist, in 1887.', a: 'Heinrich Hertz' },
    ],
    I: [
      { q: 'In 1980 it became the first country to directly elect a woman as head of state.', a: 'Iceland' },
      { q: 'In 2023 this nation made the first successful landing near the Moon\'s south pole.', a: 'India' },
      { q: 'The world\'s first purpose-built motorway opened near Milan in 1924, in this country.', a: 'Italy' },
      { q: 'Apple\'s first touchscreen smartphone, launched in 2007.', a: 'iPhone' },
      { q: 'In 2004 it became the first country to ban smoking in all indoor workplaces nationwide.', a: 'Ireland' },
      { q: 'He built the first practical reflecting telescope, in 1668.', a: 'Isaac Newton' },
      { q: 'Released in 1971, it was the first single-chip microprocessor sold commercially.', a: 'Intel 4004' },
      { q: 'The hormone first injected into a diabetic patient in 1922.', a: 'Insulin' },
      { q: 'This American motor race was first run in 1911.', a: 'Indianapolis 500' },
    ],
    J: [
      { q: 'In 1947 he broke the colour barrier in modern Major League Baseball.', a: 'Jackie Robinson' },
      { q: 'The first Olympic Games held in Asia, in 1964, took place in this country.', a: 'Japan' },
      { q: 'In 1962 he became the first American to orbit the Earth.', a: 'John Glenn' },
      { q: 'This Caribbean island entered its first Olympic bobsleigh team at the 1988 Winter Games.', a: 'Jamaica' },
      { q: 'Pioneer 10 made the first flyby of this planet, in 1973.', a: 'Jupiter' },
      { q: 'At the 1936 Games in Berlin he won four athletics gold medals.', a: 'Jesse Owens' },
      { q: 'He developed the first effective vaccine against polio.', a: 'Jonas Salk' },
      { q: 'This French explorer co-developed the Aqua-Lung breathing set.', a: 'Jacques Cousteau' },
      { q: 'Founded in 1607, it was the first permanent English settlement in America.', a: 'Jamestown' },
      { q: 'This Canadian teacher invented basketball in 1891.', a: 'James Naismith' },
      { q: 'In 1961 he became the first Roman Catholic president of the United States.', a: 'John F. Kennedy' },
      { q: 'He built the first working integrated circuit, at Texas Instruments in 1958.', a: 'Jack Kilby' },
    ],
    K: [
      { q: 'The Wright brothers made the first powered aeroplane flight near this North Carolina village in 1903.', a: 'Kitty Hawk' },
      { q: 'In 2021 she became the first woman to serve as vice president of the United States.', a: 'Kamala Harris' },
      { q: 'She was the first woman born in India to fly in space.', a: 'Kalpana Chawla' },
      { q: 'In 1997 he became the first reigning world chess champion to lose a match to a computer.', a: 'Kasparov' },
      { q: 'The first man to run the marathon distance in under two hours was born in this country.', a: 'Kenya' },
      { q: 'He patented the first practical petrol-driven automobile, in 1886.', a: 'Karl Benz' },
      { q: 'In 1967 she became the first woman to run the Boston Marathon as a registered entrant.', a: 'Kathrine Switzer' },
    ],
    L: [
      { q: 'The Soviet dog that became the first animal to orbit the Earth, in 1957.', a: 'Laika' },
      { q: 'Born in 1978, she was the world\'s first baby conceived by in vitro fertilisation.', a: 'Louise Brown' },
      { q: 'In 2006 it became the first African country to elect a woman as head of state.', a: 'Liberia' },
      { q: 'In 2012 it became the first city to host the modern Summer Olympics three times.', a: 'London' },
      { q: 'In 2020 it became the first country to make all public transport free nationwide.', a: 'Luxembourg' },
      { q: 'In 2007 he became the first Black driver to race in Formula One.', a: 'Lewis Hamilton' },
      { q: 'In 1970 this Soviet machine became the first remotely driven rover on another world.', a: 'Lunokhod 1' },
      { q: 'With Jacob Davis he patented riveted denim work trousers in 1873.', a: 'Levi Strauss' },
      { q: 'He created the first vaccine against rabies, used on a patient in 1885.', a: 'Louis Pasteur' },
    ],
    M: [
      { q: 'This Russian chemist published the first widely accepted periodic table, in 1869.', a: 'Mendeleev' },
      { q: 'In 1979 she became the first woman to lead the British government.', a: 'Margaret Thatcher' },
      { q: 'This NASA probe returned the first close-up pictures of Mars, in 1965.', a: 'Mariner 4' },
      { q: 'In 1986 it became the first nation to stage football\'s World Cup for a second time.', a: 'Mexico' },
      { q: 'He sent the first public telegraph message in 1844.', a: 'Morse' },
      { q: 'In 1901 he sent the first wireless signal across the Atlantic.', a: 'Marconi' },
      { q: 'In 2014, aged seventeen, she became the youngest ever Nobel laureate.', a: 'Malala Yousafzai' },
      { q: 'He was the first boxer to win the world heavyweight title three times.', a: 'Muhammad Ali' },
      { q: 'The world\'s first stored-program computer ran in this English city in 1948.', a: 'Manchester' },
      { q: 'Mariner 10 made the first flyby of this planet, in 1974.', a: 'Mercury' },
      { q: 'The 1976 Summer Olympics were the first held in Canada, in this city.', a: 'Montreal' },
      { q: 'In 2021 the Ingenuity helicopter made the first powered flight above this world.', a: 'Mars' },
    ],
    N: [
      { q: 'In 1893 it became the first self-governing country to grant women the vote.', a: 'New Zealand' },
      { q: 'The explorer who won the race to the South Pole in 1911 came from this country.', a: 'Norway' },
      { q: 'In 2001 it became the first country to open marriage to same-sex couples.', a: 'Netherlands' },
      { q: 'This American journalist travelled around the world alone in 72 days in 1890.', a: 'Nellie Bly' },
      { q: 'Found in 1846, it was the first planet located by mathematical prediction rather than sight.', a: 'Neptune' },
      { q: 'At the 1976 Games she became the first gymnast awarded a perfect ten.', a: 'Nadia Comaneci' },
      { q: 'His 1543 book first set out a Sun-centred model of the heavens.', a: 'Nicolaus Copernicus' },
      { q: 'In 2007 she became the first woman to serve as Speaker of the US House of Representatives.', a: 'Nancy Pelosi' },
      { q: 'The awards first handed out in 1901 under a Swedish chemist\'s will.', a: 'Nobel Prize' },
      { q: 'In 2019 she became the first Asian player ranked world number one in singles tennis.', a: 'Naomi Osaka' },
      { q: 'In 1994 he became the first Black president of South Africa.', a: 'Nelson Mandela' },
    ],
    O: [
      { q: 'It is the oldest university in the English-speaking world.', a: 'Oxford' },
      { q: 'The ancient Greek sanctuary where the original Games were held.', a: 'Olympia' },
      { q: 'This American talk-show host became the first Black woman billionaire.', a: 'Oprah Winfrey' },
      { q: 'He was at the controls for the first powered aeroplane flight, in December 1903.', a: 'Orville Wright' },
      { q: 'This American invented the elevator safety brake that made passenger lifts practical.', a: 'Otis' },
      { q: 'The Magnavox machine of 1972 that was the first home video game console.', a: 'Odyssey' },
      { q: 'Its Curved Dash of 1901 was the first American car built in large numbers.', a: 'Oldsmobile' },
    ],
    P: [
      { q: 'The first European sea route to India was opened by an explorer from this country.', a: 'Portugal' },
      { q: 'The first antibiotic to be mass-produced, obtained from a mould.', a: 'Penicillin' },
      { q: 'Abdus Salam, the first Muslim to win a Nobel Prize in science, came from this country.', a: 'Pakistan' },
      { q: 'The 1900 Games in this city were the first at which women competed.', a: 'Paris' },
      { q: 'In 1958, aged seventeen, he became the youngest player to score in a World Cup final.', a: 'Pele' },
      { q: 'In 1986 Corazon Aquino became Asia\'s first woman president, in this country.', a: 'Philippines' },
      { q: 'New Horizons returned the first close-up images of this dwarf planet in 2015.', a: 'Pluto' },
      { q: 'This American engineer invented the microwave oven after a radar experiment.', a: 'Percy Spencer' },
      { q: 'This Frenchman founded the modern Olympic movement.', a: 'Pierre de Coubertin' },
      { q: 'The 1972 Atari arcade machine that made video games a commercial success.', a: 'Pong' },
    ],
    R: [
      { q: 'In 1954 he became the first man to run a mile in under four minutes.', a: 'Roger Bannister' },
      { q: 'This Norwegian explorer led the first team to reach the South Pole.', a: 'Roald Amundsen' },
      { q: 'This physicist was the first to split the atomic nucleus artificially.', a: 'Rutherford' },
      { q: 'In 2008 it became the first country whose parliament had a female majority.', a: 'Rwanda' },
      { q: 'He won the very first Nobel Prize in Physics, in 1901.', a: 'Roentgen' },
      { q: 'In 2014 this European mission became the first to orbit a comet.', a: 'Rosetta' },
      { q: 'He built the first working railway steam locomotive, in 1804.', a: 'Richard Trevithick' },
      { q: 'The 2016 Games were the first Olympics held in South America, in this city.', a: 'Rio de Janeiro' },
      { q: 'In 1926 he launched the world\'s first liquid-fuelled rocket.', a: 'Robert Goddard' },
    ],
    S: [
      { q: 'Launched in October 1957, it was the first artificial satellite to orbit the Earth.', a: 'Sputnik' },
      { q: 'In 1909 it created the first national parks in Europe.', a: 'Sweden' },
      { q: 'In 1983 she became the first American woman to fly in space.', a: 'Sally Ride' },
      { q: 'He engineered the Liverpool and Manchester line, the first inter-city railway worked by steam.', a: 'Stephenson' },
      { q: 'In 2010 this nation staged the first football World Cup held on its own continent.', a: 'South Africa' },
      { q: 'In 1981 she became the first woman appointed to the United States Supreme Court.', a: 'Sandra Day O\'Connor' },
      { q: 'In 2017 it became the first country to grant citizenship to a robot.', a: 'Saudi Arabia' },
      { q: 'In 1968 she became the first Black woman elected to the United States Congress.', a: 'Shirley Chisholm' },
      { q: 'Launched in 1971, it was the world\'s first crewed space station.', a: 'Salyut 1' },
      { q: 'The 1928 cartoon that introduced Mickey Mouse with synchronised sound.', a: 'Steamboat Willie' },
    ],
    T: [
      { q: 'This Sherpa climber shared the first ascent of Everest in 1953.', a: 'Tenzing Norgay' },
      { q: 'The first bullet train service opened in 1964, running from this city to Osaka.', a: 'Tokyo' },
      { q: 'This 1962 satellite relayed the first live television pictures across the Atlantic.', a: 'Telstar' },
      { q: 'This British computer scientist wrote the world\'s first website, in 1991.', a: 'Tim Berners-Lee' },
      { q: 'The bathyscaphe that first reached the deepest point of the ocean, in 1960.', a: 'Trieste' },
      { q: 'This Englishman ran the first commercial package excursions, from the 1840s.', a: 'Thomas Cook' },
      { q: 'First held in 1903, it is the most famous stage race in cycling.', a: 'Tour de France' },
      { q: 'In 1997 he became the first Black golfer to win the Masters.', a: 'Tiger Woods' },
    ],
    U: [
      { q: 'It hosted and won the first football World Cup, in 1930.', a: 'Uruguay' },
      { q: 'He was the first sprinter to win both the 100 and 200 metres at three consecutive Olympics.', a: 'Usain Bolt' },
      { q: 'Found by William Herschel in 1781, it was the first planet discovered with a telescope.', a: 'Uranus' },
      { q: 'Delivered in 1951, it was the first commercial computer built in the United States.', a: 'UNIVAC' },
      { q: 'The Industrial Revolution began in this country in the eighteenth century.', a: 'United Kingdom' },
    ],
    V: [
      { q: 'In 1963 she became the first woman to fly in space.', a: 'Valentina Tereshkova' },
      { q: 'Venera 7 made the first soft landing on another planet when it touched down here in 1970.', a: 'Venus' },
      { q: 'In 2012 this probe became the first human-made object to reach interstellar space.', a: 'Voyager 1' },
      { q: 'In 1498 he became the first European to reach India by sea.', a: 'Vasco da Gama' },
      { q: 'The Soviet capsule that carried Yuri Gagarin into orbit in 1961.', a: 'Vostok 1' },
    ],
    W: [
      { q: 'First held in 1877, it is the oldest tennis championship in the world.', a: 'Wimbledon' },
      { q: 'At the 1960 Rome Games she became the first American woman to win three athletics golds at one Olympics.', a: 'Wilma Rudolph' },
      { q: 'He was the first president of the United States.', a: 'Washington' },
      { q: 'In 2004 this Kenyan environmentalist became the first African woman to win the Nobel Peace Prize.', a: 'Wangari Maathai' },
      { q: 'In 1953 these two scientists published the first accurate model of the DNA double helix.', a: 'Watson and Crick' },
      { q: 'The information system Tim Berners-Lee proposed at CERN in 1989.', a: 'World Wide Web' },
      { q: 'The aircraft that made the first powered, controlled aeroplane flight, in 1903.', a: 'Wright Flyer' },
    ],
  },
};
