import type { RawPack } from '../core/packs';

export const fandomMarvelPack: RawPack = {
  id: 'fandom-marvel',
  name: 'Marvel Universe',
  description: 'Heroes, villains, stones and lore from the MCU films, shows and the comics behind them.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🦸',
  accent: '#b91c1c',
  letters: {
    A: [
      { q: 'The golden realm ruled by Odin and defended by the God of Thunder.', a: 'Asgard' },
      { q: 'The codename Scott Lang takes when he shrinks using Pym Particles.', a: 'Ant-Man' },
      { q: 'The super team formed by Fury\'s initiative to stop Loki\'s invasion of New York.', a: 'Avengers' },
      { q: 'The near-indestructible metal alloy bonded to Wolverine\'s skeleton.', a: 'Adamantium' },
      { q: 'The elderly guardian who raises a certain web-slinger in Queens.', a: 'Aunt May' },
      { q: 'The nosy neighbour Agnes in WandaVision is really this centuries-old witch.', a: 'Agatha Harkness', alt: ['Agatha'] },
      { q: 'The Sorcerer Supreme who trains Stephen Strange in Kamar-Taj, played by Tilda Swinton.', a: 'Ancient One', alt: ['The Ancient One'] },
      { q: 'The Egyptian-era mutant villain born as En Sabah Nur.', a: 'Apocalypse' },
      { q: 'The winged founding X-Men member whose real name is Warren Worthington.', a: 'Angel', alt: ['Archangel'] },
      { q: 'The teenage hero who punches star-shaped portals between universes.', a: 'America Chavez' },
      { q: 'The glowing chest device that powers the armour and keeps shrapnel from a heart.', a: 'Arc Reactor' },
      { q: 'The Hydra scientist whose mind survives inside a Camp Lehigh computer.', a: 'Arnim Zola', alt: ['Zola'] },
      { q: 'The gold-skinned Sovereign high priestess who sends fleets after the Guardians.', a: 'Ayesha' },
      { q: 'The original leader of the Eternals, played by Salma Hayek.', a: 'Ajak' },
      { q: 'The mutated form of Emil Blonsky who battles the Hulk in Harlem.', a: 'Abomination' },
    ],
    B: [
      { q: 'The title held by the protector of Wakanda who wears a vibranium suit.', a: 'Black Panther' },
      { q: 'Rogers\' childhood friend brainwashed by Hydra into an assassin.', a: 'Bucky Barnes', alt: ['Bucky', 'James Barnes'] },
      { q: 'Romanoff\'s codename after her Red Room training.', a: 'Black Widow' },
      { q: 'The gamma radiation scientist with an enormous green alter ego.', a: 'Bruce Banner', alt: ['Banner'] },
      { q: 'The Sokovian who splits the Avengers apart using a Siberian security tape.', a: 'Baron Zemo', alt: ['Zemo', 'Helmut Zemo'] },
      { q: 'The blue furry genius X-Man born Hank McCoy.', a: 'Beast' },
      { q: 'The rainbow bridge that carries Asgardians between the realms.', a: 'Bifrost' },
      { q: 'The half-vampire hunter played by Wesley Snipes in 1998.', a: 'Blade' },
      { q: 'The fellow student who turns against Strange, played by Chiwetel Ejiofor.', a: 'Baron Mordo', alt: ['Mordo', 'Karl Mordo'] },
      { q: 'The nickname for the five-year gap between the snap and the return.', a: 'Blip', alt: ['The Blip'] },
      { q: 'The collective name of the four elite lieutenants who serve Thanos.', a: 'Black Order' },
    ],
    C: [
      { q: 'The title Rogers takes after Project Rebirth.', a: 'Captain America' },
      { q: 'The armoured alien foot soldiers Loki leads through the portal over Manhattan.', a: 'Chitauri' },
      { q: 'The Air Force pilot who gains binary powers from an exploding Kree engine.', a: 'Carol Danvers', alt: ['Danvers'] },
      { q: 'The visor-wearing X-Men field leader born Scott Summers.', a: 'Cyclops' },
      { q: 'The huge Russian mutant who turns his body into organic steel.', a: 'Colossus' },
      { q: 'The full civilian name of the archer Avenger.', a: 'Clint Barton' },
      { q: 'The teenage daughter of the shrinking hero who builds a Quantum Realm signal device.', a: 'Cassie Lang', alt: ['Cassie'] },
      { q: 'The heroic title Danvers uses once she embraces her powers.', a: 'Captain Marvel' },
      { q: 'The sentient red garment that chooses Strange as its wearer.', a: 'Cloak of Levitation', alt: ['Cloak'] },
      { q: 'The colossal cosmic beings whose severed head became the mining colony Knowhere.', a: 'Celestials' },
      { q: 'The hulking hammer-wielding brute among the adopted children of Thanos.', a: 'Cull Obsidian' },
    ],
    D: [
      { q: 'The arrogant neurosurgeon who ruins his hands and becomes a master of the mystic arts.', a: 'Doctor Strange', alt: ['Stephen Strange', 'Strange'] },
      { q: 'The blind lawyer hero who protects Hell\'s Kitchen.', a: 'Daredevil' },
      { q: 'The Destroyer who takes every metaphor completely literally.', a: 'Drax' },
      { q: 'The mouthy fourth-wall-breaking mercenary born Wade Wilson.', a: 'Deadpool' },
      { q: 'The Dark Dimension ruler trapped in an endless loop by a sorcerer.', a: 'Dormammu' },
      { q: 'The corrupted book of spells Wanda uses to dreamwalk.', a: 'Darkhold' },
      { q: 'The armoured Latverian monarch and arch-enemy of the Fantastic Four.', a: 'Doctor Doom', alt: ['Doom', 'Victor Von Doom'] },
      { q: 'The all-female royal guard that protects the Wakandan throne.', a: 'Dora Milaje' },
      { q: 'The eight-armed villain born Otto Octavius.', a: 'Doctor Octopus', alt: ['Doc Ock'] },
      { q: 'The ancient race led by Malekith who want the universe returned to blackness.', a: 'Dark Elves' },
    ],
    E: [
      { q: 'The Celestial who fathered Quill while posing as a living planet.', a: 'Ego' },
      { q: 'The immortal race created by the Celestials to fight Deviants on Earth.', a: 'Eternals' },
      { q: 'The wild-haired astrophysicist who works with Jane Foster and studies the Tesseract.', a: 'Erik Selvig', alt: ['Selvig'] },
      { q: 'The gaunt telekinetic servant of Thanos who tortures a sorcerer aboard his ship.', a: 'Ebony Maw' },
      { q: 'The lightning-powered villain played by Jamie Foxx.', a: 'Electro' },
      { q: 'The diamond-skinned White Queen of the Hellfire Club.', a: 'Emma Frost' },
      { q: 'The dwarf king of Nidavellir who forges Stormbreaker.', a: 'Eitri' },
      { q: 'The struggling journalist who bonds with a symbiote, played by Tom Hardy.', a: 'Eddie Brock' },
    ],
    F: [
      { q: 'Wilson\'s winged codename before he takes up the shield.', a: 'Falcon' },
      { q: 'The team of Reed Richards, Sue Storm, Johnny Storm and Ben Grimm.', a: 'Fantastic Four' },
      { q: 'Thor\'s mother, killed while protecting Jane Foster.', a: 'Frigga' },
      { q: 'The alien species that the cat named Goose actually belongs to.', a: 'Flerken' },
      { q: 'The blue-skinned race that inhabits the cold realm of Jotunheim.', a: 'Frost Giants' },
      { q: 'The law partner and closest friend of Matt Murdock.', a: 'Foggy Nelson', alt: ['Foggy'] },
    ],
    G: [
      { q: 'The green-skinned assassin sacrificed on Vormir by her adoptive father.', a: 'Gamora' },
      { q: 'The tree-like Guardian who speaks only three words.', a: 'Groot' },
      { q: 'The glider-riding villain identity of Norman Osborn.', a: 'Green Goblin' },
      { q: 'The Cajun mutant who charges playing cards with kinetic energy.', a: 'Gambit' },
      { q: 'The flamboyant ruler of Sakaar played by Jeff Goldblum.', a: 'Grandmaster' },
      { q: 'The orange cat that swallows the Tesseract whole.', a: 'Goose' },
      { q: 'The flaming-skull motorcycle antihero played by Nicolas Cage.', a: 'Ghost Rider' },
      { q: 'The team name Quill\'s crew adopt after saving Xandar.', a: 'Guardians', alt: ['Guardians of the Galaxy'] },
      { q: 'The God Butcher played by Christian Bale.', a: 'Gorr' },
      { q: 'The phasing, unstable villain of the second Ant-Man film.', a: 'Ghost' },
    ],
    H: [
      { q: 'The enormous superhuman alter ego of Banner.', a: 'Hulk' },
      { q: 'The codename of the arrow-shooting founding Avenger.', a: 'Hawkeye' },
      { q: 'The firstborn child of Odin, a Goddess of Death played by Cate Blanchett.', a: 'Hela' },
      { q: 'The all-seeing Asgardian gatekeeper played by Idris Elba.', a: 'Heimdall' },
      { q: 'The secret organisation whose motto promises two heads for each one cut off.', a: 'Hydra' },
      { q: 'Stark\'s driver and security chief played by Jon Favreau.', a: 'Happy Hogan', alt: ['Happy'] },
      { q: 'Tony\'s inventor father, one of the founders of SHIELD.', a: 'Howard Stark' },
      { q: 'The daughter of Hank Pym who fights beside Scott Lang in a winged suit.', a: 'Hope van Dyne', alt: ['Hope'] },
    ],
    I: [
      { q: 'The armoured identity Stark adopts after escaping the Ten Rings.', a: 'Iron Man' },
      { q: 'The golden glove built on Nidavellir to hold all six cosmic gems.', a: 'Infinity Gauntlet' },
      { q: 'The oversized armour Obadiah Stane builds from stolen designs.', a: 'Iron Monger' },
      { q: 'The Eternal played by Richard Madden who flies and fires beams from his eyes.', a: 'Ikaris' },
      { q: 'The mutant Bobby Drake who freezes whatever he touches.', a: 'Iceman' },
      { q: 'The hero identity of Sue Storm.', a: 'Invisible Woman' },
      { q: 'The armoured alter ego of the young inventor Riri Williams.', a: 'Ironheart' },
      { q: 'The collective name for the six most powerful gems in the universe.', a: 'Infinity Stones' },
    ],
    J: [
      { q: 'The astrophysicist who lifts Mjolnir and becomes the Mighty Thor.', a: 'Jane Foster' },
      { q: 'The polite artificial butler voiced by Paul Bettany before Vision existed.', a: 'Jarvis' },
      { q: 'The telepathic X-Man consumed by the Phoenix force.', a: 'Jean Grey' },
      { q: 'The super-strong private investigator played by Krysten Ritter.', a: 'Jessica Jones' },
      { q: 'The unstoppable helmeted step-brother of Charles Xavier.', a: 'Juggernaut' },
      { q: 'Hope\'s mother, stranded for decades in the Quantum Realm.', a: 'Janet van Dyne', alt: ['Janet'] },
    ],
    K: [
      { q: 'The Oakland-born cousin who seizes the Wakandan throne, played by Michael B. Jordan.', a: 'Killmonger', alt: ['Erik Killmonger'] },
      { q: 'The Nepalese sanctuary where sorcerers are trained.', a: 'Kamar-Taj' },
      { q: 'The blue-lipped conqueror of countless timelines, played by Jonathan Majors.', a: 'Kang' },
      { q: 'The young archer from a wealthy family who becomes Barton\'s protege.', a: 'Kate Bishop' },
      { q: 'The criminal identity of the enormous mob boss Wilson Fisk.', a: 'Kingpin' },
      { q: 'The soft-spoken rock warrior voiced by Taika Waititi.', a: 'Korg' },
      { q: 'The Jersey City teenager who idolises Danvers and gains bangle powers.', a: 'Kamala Khan', alt: ['Ms. Marvel'] },
      { q: 'The one-armed black-market dealer who stole vibranium from Wakanda.', a: 'Klaue', alt: ['Ulysses Klaue'] },
    ],
    L: [
      { q: 'The God of Mischief and adopted brother of Thor.', a: 'Loki' },
      { q: 'The unbreakable-skinned hero who defends Harlem.', a: 'Luke Cage' },
      { q: 'The Nigerian city where Wanda\'s mistake triggers the Sokovia Accords.', a: 'Lagos' },
      { q: 'The usual human name of the clawed mutant Wolverine.', a: 'Logan', alt: ['James Howlett'] },
      { q: 'The Frost Giant king revealed to be the true father of Loki.', a: 'Laufey' },
      { q: 'The fast-talking friend of Scott Lang famous for long rambling stories.', a: 'Luis' },
    ],
    M: [
      { q: 'The master of magnetism born Erik Lehnsherr.', a: 'Magneto' },
      { q: 'The hammer forged in a dying star that only the worthy can lift.', a: 'Mjolnir' },
      { q: 'The blue shapeshifting mutant played by Rebecca Romijn and Jennifer Lawrence.', a: 'Mystique' },
      { q: 'The antennaed empath who can put anyone to sleep with a touch.', a: 'Mantis' },
      { q: 'The Brooklyn teenager who becomes a web-slinger in Into the Spider-Verse.', a: 'Miles Morales' },
      { q: 'The caped avatar of Khonshu played by Oscar Isaac.', a: 'Moon Knight' },
      { q: 'The yellow gem hidden in Loki\'s sceptre that later sits in Vision\'s forehead.', a: 'Mind Stone' },
      { q: 'The Jabari mountain leader played by Winston Duke.', a: "M'Baku" },
      { q: 'The vampiric biochemist played by Jared Leto.', a: 'Morbius' },
      { q: 'The Dark Elf leader played by Christopher Eccleston.', a: 'Malekith' },
      { q: 'Fury\'s no-nonsense right hand played by Cobie Smulders.', a: 'Maria Hill' },
      { q: 'The rain-lashed ruined planet where Quill first steals the orb.', a: 'Morag' },
    ],
    N: [
      { q: 'The eyepatch-wearing SHIELD director played by Samuel L. Jackson.', a: 'Nick Fury', alt: ['Fury'] },
      { q: 'The cybernetic blue-skinned daughter of Thanos and sister of Gamora.', a: 'Nebula' },
      { q: 'The winged-ankled ruler of the undersea kingdom Talokan.', a: 'Namor' },
      { q: 'The dwarven forge realm ringed by a dying neutron star.', a: 'Nidavellir' },
      { q: 'The Xandarian police force that first imprisons the Guardians.', a: 'Nova Corps' },
      { q: 'The full name of the Widow who dies on Vormir so a friend can live.', a: 'Natasha Romanoff', alt: ['Natasha'] },
      { q: 'The teleporting blue mutant born Kurt Wagner.', a: 'Nightcrawler' },
      { q: 'The Wakandan spy and royal love interest played by Lupita Nyong\'o.', a: 'Nakia' },
    ],
    O: [
      { q: 'The one-eyed All-Father who rules Asgard.', a: 'Odin' },
      { q: 'The shaven-headed general of the Dora Milaje played by Danai Gurira.', a: 'Okoye' },
      { q: 'The executive who betrays Tony in the first film of the saga.', a: 'Obadiah Stane', alt: ['Obadiah', 'Stane'] },
      { q: 'The company run by the civilian identity of the Green Goblin.', a: 'Oscorp' },
      { q: 'The four-armed alien beasts Thanos unleashes on the Wakandan battlefield.', a: 'Outriders' },
    ],
    P: [
      { q: 'The Queens teenager bitten by a radioactive spider.', a: 'Peter Parker' },
      { q: 'The birth name of the Walkman-loving Guardian leader.', a: 'Peter Quill', alt: ['Quill'] },
      { q: 'The bald telepath who founds a school for gifted youngsters.', a: 'Professor X', alt: ['Charles Xavier', 'Xavier'] },
      { q: 'Stark\'s assistant who becomes chief executive and later his wife.', a: 'Pepper Potts', alt: ['Pepper'] },
      { q: 'The SHIELD agent stabbed by Loki aboard the Helicarrier.', a: 'Phil Coulson', alt: ['Coulson'] },
      { q: 'The shrinking substance discovered by the scientist Hank.', a: 'Pym Particles' },
      { q: 'The purple gem hidden inside the orb found on Morag.', a: 'Power Stone' },
      { q: 'The skull-shirted vigilante born Frank Castle.', a: 'Punisher' },
      { q: 'The SSR officer Rogers loves, who later helps found SHIELD.', a: 'Peggy Carter', alt: ['Peggy'] },
      { q: 'The cosmic fire entity that possesses Jean Grey.', a: 'Phoenix' },
    ],
    Q: [
      { q: 'The super-fast twin brother of Wanda, killed during the Sokovia battle.', a: 'Quicksilver', alt: ['Pietro Maximoff', 'Pietro'] },
      { q: 'The subatomic dimension explored throughout the Ant-Man films.', a: 'Quantum Realm' },
      { q: 'The signature aircraft flown by the Avengers.', a: 'Quinjet' },
    ],
    R: [
      { q: 'The genetically engineered raccoon Guardian obsessed with big guns.', a: 'Rocket' },
      { q: 'The Kree Accuser who wields a warhammer over Xandar.', a: 'Ronan' },
      { q: 'The nickname of the Air Force officer who pilots War Machine.', a: 'Rhodey', alt: ['James Rhodes', 'Rhodes'] },
      { q: 'The Hydra leader disfigured by the serum, later stranded as a stone keeper.', a: 'Red Skull', alt: ['Johann Schmidt'] },
      { q: 'The southern mutant who absorbs powers through skin contact.', a: 'Rogue' },
      { q: 'The band of space pirates captained by Yondu.', a: 'Ravagers' },
      { q: 'The red liquid gem also known as the Aether.', a: 'Reality Stone' },
      { q: 'The full name of the stretchy leader of the Fantastic Four.', a: 'Reed Richards', alt: ['Mister Fantastic'] },
      { q: 'The floating prison where Rogers\' team is locked up after the airport battle.', a: 'Raft', alt: ['The Raft'] },
    ],
    S: [
      { q: 'The Eastern European country whose capital Ultron lifts into the sky.', a: 'Sokovia' },
      { q: 'The Wakandan princess and technology genius.', a: 'Shuri' },
      { q: 'The skinny Brooklyn kid chosen for Project Rebirth.', a: 'Steve Rogers' },
      { q: 'The axe Thor forges to replace his shattered hammer.', a: 'Stormbreaker' },
      { q: 'The veteran who takes up the shield as a new Captain America on television.', a: 'Sam Wilson' },
      { q: 'The white-haired weather-controlling mutant born Ororo Munroe.', a: 'Storm' },
      { q: 'The feral clawed mutant born Victor Creed.', a: 'Sabretooth' },
      { q: 'The Greenwich Village mansion that houses New York\'s mystic protector.', a: 'Sanctum Sanctorum' },
      { q: 'The martial artist who confronts his father\'s ancient criminal organisation.', a: 'Shang-Chi' },
      { q: 'The orange gem that demands the sacrifice of a loved one.', a: 'Soul Stone' },
      { q: 'The blue gem hidden for decades inside the Tesseract.', a: 'Space Stone' },
      { q: 'The giant mutant-hunting robots of Days of Future Past.', a: 'Sentinels' },
      { q: 'The green shapeshifting aliens at the heart of Secret Invasion.', a: 'Skrulls' },
      { q: 'The self-given nickname of the Walkman-loving Guardian leader.', a: 'Star-Lord' },
      { q: 'The variant of Loki played by Sophia Di Martino.', a: 'Sylvie' },
      { q: 'The chaos magic title Wanda Maximoff finally claims.', a: 'Scarlet Witch' },
      { q: 'The Eternal played by Gemma Chan who transmutes matter with a touch.', a: 'Sersi' },
    ],
    T: [
      { q: 'The purple warlord obsessed with halving all life in the universe.', a: 'Thanos' },
      { q: 'The Asgardian God of Thunder played by Chris Hemsworth.', a: 'Thor' },
      { q: 'The glowing blue cube that contains the Space Stone.', a: 'Tesseract' },
      { q: 'The full name of the billionaire inventor inside the Iron Man armour.', a: 'Tony Stark' },
      { q: 'The green gem kept inside the Eye of Agamotto.', a: 'Time Stone' },
      { q: 'The ruined home world of Thanos.', a: 'Titan' },
      { q: 'The hidden underwater kingdom that goes to war with Wakanda.', a: 'Talokan' },
      { q: 'The masked fighter who instantly copies any opponent\'s moves.', a: 'Taskmaster' },
      { q: 'The organisation Wenwu leads, named after his ancient bracelet weapons.', a: 'Ten Rings' },
      { q: 'The rocky orange alter ego of Ben Grimm.', a: 'Thing', alt: ['The Thing'] },
      { q: 'The bureaucracy that prunes branching realities in the Loki series.', a: 'TVA', alt: ['Time Variance Authority'] },
      { q: 'The general who hunts the Hulk and later enforces the Sokovia Accords.', a: 'Thunderbolt Ross', alt: ['Ross'] },
      { q: 'The Skrull leader who impersonates Fury, played by Ben Mendelsohn.', a: 'Talos' },
    ],
    U: [
      { q: 'The murderous artificial intelligence accidentally created by Stark and Banner.', a: 'Ultron' },
      { q: 'The relative whose death teaches a young web-slinger about responsibility.', a: 'Uncle Ben' },
      { q: 'The cosmic observer voiced by Jeffrey Wright who narrates the animated What If series.', a: 'Uatu', alt: ['The Watcher'] },
    ],
    V: [
      { q: 'The synthezoid born from Ultron\'s body and the Mind Stone.', a: 'Vision' },
      { q: 'The Wakandan metal that absorbs kinetic energy.', a: 'Vibranium' },
      { q: 'The barren orange planet where the Soul Stone waits.', a: 'Vormir' },
      { q: 'The winged salvage-worker villain played by Michael Keaton.', a: 'Vulture' },
      { q: 'The hard-drinking Asgardian warrior played by Tessa Thompson.', a: 'Valkyrie' },
      { q: 'The black symbiote bonded to the journalist Eddie Brock.', a: 'Venom' },
    ],
    W: [
      { q: 'The hidden African nation made rich by a meteor of rare metal.', a: 'Wakanda' },
      { q: 'The clawed, healing mutant played for two decades by Hugh Jackman.', a: 'Wolverine' },
      { q: 'The full name of the hero titled the Scarlet Witch.', a: 'Wanda Maximoff' },
      { q: 'The heavily armed grey armour worn by Rhodey.', a: 'War Machine' },
      { q: 'The assassin identity Hydra forces onto Barnes.', a: 'Winter Soldier' },
      { q: 'The librarian sorcerer who becomes Sorcerer Supreme after the Blip.', a: 'Wong' },
      { q: 'The New Jersey town Wanda traps inside a sitcom.', a: 'Westview' },
      { q: 'The father of Shang-Chi, revealed as the true Mandarin.', a: 'Wenwu' },
      { q: 'The shrinking winged codename used by Hope van Dyne.', a: 'Wasp', alt: ['The Wasp'] },
      { q: 'The electrified whip villain played by Mickey Rourke.', a: 'Whiplash' },
    ],
    X: [
      { q: 'The planet whose Nova Corps once guarded the Power Stone.', a: 'Xandar' },
      { q: 'The sister of Shang-Chi who runs the Golden Daggers fight club.', a: 'Xu Xialing' },
      { q: 'The mutant team based at a Westchester school for gifted youngsters.', a: 'X-Men' },
    ],
    Y: [
      { q: 'The blue Ravager captain who controls an arrow by whistling.', a: 'Yondu' },
      { q: 'The Widow sister of Natasha, played by Florence Pugh.', a: 'Yelena Belova', alt: ['Yelena'] },
      { q: 'The world tree that links the Nine Realms in Asgardian lore.', a: 'Yggdrasil' },
    ],
    Z: [
      { q: 'The Greek god played by Russell Crowe in Love and Thunder.', a: 'Zeus' },
    ],
  },
};
