import type { RawPack } from '../core/packs';

export const fandomMarioPack: RawPack = {
  id: 'fandom-mario',
  name: 'Super Mario',
  description: 'Plumbers, power-ups, karts and kingdoms from the whole mushroom multiverse.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '🍄',
  accent: '#dc2626',
  letters: {
    A: [
      { q: 'The scowling celestial enemy that swoops down at the plumber in a desert level of the third NES platformer.', a: 'Angry Sun' },
      { q: 'The purple bat king who steals the Dark Stone in Dream Team.', a: 'Antasma' },
      { q: 'The young witch in a red dress with a demon sidekick named Red in the microgame series.', a: 'Ashley' },
      { q: 'The crackling ball of electricity that patrols in a circle and shocks the plumber on contact.', a: 'Amp' },
    ],
    B: [
      { q: 'The spiky-shelled Koopa king who repeatedly kidnaps the princess.', a: 'Bowser', alt: ['King Bowser'] },
      { q: 'The bandana-wearing son of the Koopa king who debuted in the 2002 tropical platformer.', a: 'Bowser Jr.', alt: ['Bowser Junior'] },
      { q: 'The round white ghost that covers its face when you look straight at it.', a: 'Boo' },
      { q: 'The pink dinosaur that spits eggs, first fought in the second NES platformer.', a: 'Birdo' },
      { q: 'The wind-up walking explosive enemy with feet and a lit fuse.', a: 'Bob-omb', alt: ['Bomb-omb'] },
      { q: 'The white squid enemy that drifts down at swimmers in underwater levels.', a: 'Blooper' },
      { q: 'The black projectile with arms and a smirk that is fired from a cannon.', a: 'Bullet Bill' },
      { q: 'The crying infant the green dinosaur carries on his back in the 1995 island platformer.', a: 'Baby Mario' },
      { q: 'The blue-shelled crawling enemy that is immune to fireballs.', a: 'Buzzy Beetle' },
      { q: 'The neighbouring realm the brothers travel to in Superstar Saga.', a: 'Beanbean Kingdom' },
      { q: 'The shelled enemy that hurls a curved weapon which flies back to its hand.', a: 'Boomerang Bro' },
      { q: 'The striped 2007 space-game power-up that grants the plumber wings and a fuzzy body.', a: 'Bee Mushroom' },
      { q: 'The lava-filled final course of most racing installments, home to the Koopa king.', a: 'Bowser\'s Castle' },
      { q: 'The yellow racing item that drivers drop behind them to make rivals spin out.', a: 'Banana', alt: ['Banana Peel'] },
      { q: 'The capital town of the Cap Kingdom in Odyssey, inhabited by top-hat ghosts.', a: 'Bonneton' },
      { q: 'The winged racing item that homes in on whoever is in first place.', a: 'Blue Shell', alt: ['Spiny Shell'] },
      { q: 'The quartet of rabbit wedding planners hired by the Koopa king in Odyssey.', a: 'Broodals' },
    ],
    C: [
      { q: 'The sentient white hat with eyes that the plumber throws in his 2017 adventure.', a: 'Cappy' },
      { q: 'The black iron-ball creature with huge teeth tethered to a wooden post.', a: 'Chain Chomp' },
      { q: 'The red swimming fish enemy that sometimes leaps out of the water.', a: 'Cheep Cheep' },
      { q: 'The headlamp-wearing mushroom explorer who stars in Treasure Tracker.', a: 'Captain Toad' },
      { q: 'The witch who steals the Beanstar in Superstar Saga.', a: 'Cackletta' },
      { q: 'The grumpy elderly ape with a cane and round glasses who dispenses advice.', a: 'Cranky Kong' },
      { q: 'The blonde ape who runs the save point in the Country games.', a: 'Candy Kong' },
      { q: 'The yellow item in the 1990 16-bit platformer that lets the plumber fly and spin.', a: 'Cape Feather' },
      { q: 'Rosalina\'s starship hub that the plumber restores in the 2007 space platformer.', a: 'Comet Observatory' },
      { q: 'The spinning yellow collectible; gathering one hundred grants an extra life.', a: 'Coin' },
      { q: 'The floating cackling-faced vehicle the Koopa king pilots in the 16-bit finale.', a: 'Clown Car', alt: ['Koopa Clown Car'] },
      { q: 'The 2010 space sequel power-up that lets the plumber make three platforms in midair.', a: 'Cloud Flower' },
      { q: 'The scaly purple thief who snatches the princess\'s brooch in the 1996 role-playing game.', a: 'Croco' },
    ],
    D: [
      { q: 'The tie-wearing gorilla who first appeared as the villain of a 1981 arcade game.', a: 'Donkey Kong', alt: ['DK'] },
      { q: 'The small cap-wearing ape sidekick who fights with peanut popguns.', a: 'Diddy Kong' },
      { q: 'The pigtailed ape who can spin her hair like a helicopter rotor.', a: 'Dixie Kong' },
      { q: 'The orange-dressed princess of Sarasaland, rescued in the first Game Boy platformer.', a: 'Daisy', alt: ['Princess Daisy'] },
      { q: 'The skeletal Koopa that collapses when stomped and then reassembles itself.', a: 'Dry Bones' },
      { q: 'The bleached skeleton form of the Koopa king, first unlocked as a racer on the DS.', a: 'Dry Bowser' },
      { q: 'The jester magician in a harlequin mask who betrays Count Bleck.', a: 'Dimentio' },
      { q: 'The sunny hub town where the plumber is falsely convicted of vandalism.', a: 'Delfino Plaza' },
      { q: 'The 3D World item that creates a second copy of the player character.', a: 'Double Cherry' },
      { q: 'The friendly purple plesiosaur swimming in the basement lake of the 1996 castle.', a: 'Dorrie' },
      { q: 'The 1994 pre-rendered platformer that revived the ape franchise on the 16-bit console.', a: 'Donkey Kong Country' },
    ],
    E: [
      { q: 'The tiny bespectacled inventor who builds the Poltergust vacuum.', a: 'E. Gadd', alt: ['Professor E. Gadd', 'Elvin Gadd'] },
      { q: 'The swordfish animal buddy the apes ride underwater.', a: 'Enguarde' },
      { q: 'The ostrich animal buddy that glides in the 1994 ape platformer.', a: 'Expresso' },
      { q: 'The giant polluted sea creature with a toothache at the bottom of Noki Bay.', a: 'Eely-Mouth' },
    ],
    F: [
      { q: 'The orange-and-yellow plant power-up that lets the plumber throw burning projectiles.', a: 'Fire Flower' },
      { q: 'The talking water-pump backpack strapped to the plumber in the 2002 tropical game.', a: 'FLUDD', alt: ['F.L.U.D.D.'] },
      { q: 'The bespectacled bean-shaped minion famous for announcing that he has fury.', a: 'Fawful' },
      { q: 'The sunglasses-wearing surfer ape who runs a flight and rental service.', a: 'Funky Kong' },
      { q: 'The small black spiky ball whose touch makes the whole screen wobble.', a: 'Fuzzy' },
      { q: 'The living flame boss of the second NES platformer who splits into smaller flames when hit.', a: 'Fryguy' },
      { q: 'The bullying construction boss who rivals the brothers in Wrecking Crew.', a: 'Foreman Spike' },
      { q: 'The rotating chain of flames anchored to a block in castle levels.', a: 'Fire Bar' },
      { q: 'The green swimming outfit introduced in the third NES platformer.', a: 'Frog Suit' },
      { q: 'The theatrical cloud woman partner who blows away obstacles in The Thousand-Year Door.', a: 'Flurrie' },
    ],
    G: [
      { q: 'The brown mushroom-shaped enemy that is the very first foe of the 1985 platformer.', a: 'Goomba' },
      { q: 'The green gelatinous clone of the plumber\'s brother introduced in the 2019 ghost game.', a: 'Gooigi' },
      { q: 'The archaeology student partner who headbonks and tattles in The Thousand-Year Door.', a: 'Goombella' },
      { q: 'The wooden doll possessed by a star spirit in the 1996 role-playing game.', a: 'Geno' },
      { q: 'The racing item that grants several boosts in a row for a short time.', a: 'Golden Mushroom' },
      { q: 'The most basic racing projectile, which bounces off walls.', a: 'Green Shell' },
      { q: 'The large power source collected at the end of each dome in the 2007 space game.', a: 'Grand Star' },
      { q: 'The domed-headed X-Naut leader in The Thousand-Year Door.', a: 'Grodus' },
      { q: 'The rounder cousin of the standard brown enemy that can be picked up and thrown.', a: 'Galoomba' },
      { q: 'The 1989 monochrome handheld that debuted the plumber\'s Land series.', a: 'Game Boy' },
      { q: 'The 2001 purple lunchbox-shaped console that launched the plumber\'s ghost-hunting debut.', a: 'GameCube' },
    ],
    H: [
      { q: 'The helmeted Koopa that lobs mallets down from a rooftop.', a: 'Hammer Bro' },
      { q: 'The black-and-silver outfit in the third NES platformer that lets the plumber throw mallets.', a: 'Hammer Suit' },
      { q: 'The talking paint can who partners with the plumber in Color Splash.', a: 'Huey' },
      { q: 'The giant crowned bee ruler of a 2007 hive world, later a racer on the 3DS.', a: 'Honey Queen' },
      { q: 'The owl in the 1996 game that carries the plumber when he grabs its legs.', a: 'Hoot' },
      { q: 'The pink-haired bomb-throwing member of the rabbit wedding planner quartet.', a: 'Hariet' },
    ],
    I: [
      { q: 'The dolphin-shaped tropical island setting of the 2002 platformer.', a: 'Isle Delfino' },
      { q: 'The lanky green-haired member of the seven royal siblings, who wears very thick glasses.', a: 'Iggy Koopa', alt: ['Iggy'] },
      { q: 'The blue power-up that lets the plumber freeze enemies into solid blocks.', a: 'Ice Flower' },
      { q: 'The 2009 handheld adventure in which the brothers explore the Koopa king\'s body.', a: 'Inside Story', alt: ['Bowser\'s Inside Story'] },
      { q: 'The frozen sixth world of the third NES platformer.', a: 'Ice Land' },
      { q: 'The masked runner who challenges the plumber to footraces in the 2002 tropical game.', a: 'Il Piantissimo' },
    ],
    J: [
      { q: 'The name the plumber was given in the original 1981 arcade cabinet.', a: 'Jumpman' },
      { q: 'The egg-shelled young Koopa who repeatedly ambushes the hero in the 2000 flat-paper game.', a: 'Jr. Troopa' },
      { q: 'The opening tropical-forest world of the 1999 64-bit ape platformer.', a: 'Jungle Japes' },
    ],
    K: [
      { q: 'The green turtle enemy whose shell can be kicked along as a weapon.', a: 'Koopa Troopa' },
      { q: 'The blue-robed sorcerer turtle who serves as the Koopa king\'s caretaker.', a: 'Kamek' },
      { q: 'The crowned ghost ruler who traps the plumber in a painting in the 2001 mansion game.', a: 'King Boo' },
      { q: 'The collective name for the seven siblings including Wendy, Roy and Ludwig.', a: 'Koopalings' },
      { q: 'The reptilian monarch who steals the ape family\'s banana hoard.', a: 'King K. Rool' },
      { q: 'The elderly broom-riding sorceress advising the villain in the 2000 flat-paper game.', a: 'Kammy Koopa' },
      { q: 'The condor that snatches the plumber\'s cap in the desert stage of the 1996 platformer.', a: 'Klepto' },
      { q: 'The crowned mustachioed explosive monarch fought at the top of the first course of the 1996 platformer.', a: 'King Bob-omb' },
      { q: 'The winged version of the standard turtle enemy that hops through the air.', a: 'Koopa Paratroopa' },
      { q: 'The surname shared by Diddy, Dixie, Funky and Cranky.', a: 'Kong' },
      { q: 'The reptilian species of henchmen serving the crocodile monarch in the Country games.', a: 'Kremling' },
    ],
    L: [
      { q: 'The taller, thinner, green-capped brother of the plumber.', a: 'Luigi' },
      { q: 'The cloud-riding Koopa that drops barbed enemies from above.', a: 'Lakitu' },
      { q: 'The youngest of the seven royal siblings, blue-haired and the first boss of the third NES platformer.', a: 'Larry Koopa', alt: ['Larry'] },
      { q: 'The smallest of the seven royal siblings, who balances on a ball and sports a rainbow mohawk.', a: 'Lemmy Koopa', alt: ['Lemmy'] },
      { q: 'The eldest of the seven royal siblings, with a blue Beethoven-style hairdo.', a: 'Ludwig von Koopa', alt: ['Ludwig'] },
      { q: 'The small star-shaped creature that Rosalina mothers in the 2007 space game.', a: 'Luma' },
      { q: 'The long-armed ape with an orange shirt in the 1999 64-bit ape platformer.', a: 'Lanky Kong' },
      { q: 'The 2001 console launch title in which the green-capped brother sucks up ghosts inside a haunted estate.', a: 'Luigi\'s Mansion' },
      { q: 'The racing item that shrinks every rival on the track at once.', a: 'Lightning', alt: ['Lightning Bolt'] },
      { q: 'The Odyssey world built of stew, cheese and bright pink molten rock.', a: 'Luncheon Kingdom' },
      { q: 'The hopping ball of magma in castle stages, also known as a Podoboo.', a: 'Lava Bubble' },
      { q: 'The purple captain who runs the planet-shaped ship in the 2010 space sequel.', a: 'Lubba' },
    ],
    M: [
      { q: 'The red-capped mustachioed plumber who is Nintendo\'s mascot.', a: 'Mario' },
      { q: 'The realm ruled by Princess Peach.', a: 'Mushroom Kingdom' },
      { q: 'The shiny silver alter ego created by a special cap in the 1996 platformer, later a racer.', a: 'Metal Mario' },
      { q: 'Nintendo\'s long-running racing spin-off series in which drivers fling shells at each other.', a: 'Mario Kart' },
      { q: 'The spin-off series in which four characters roll dice on a board and compete in minigames.', a: 'Mario Party' },
      { q: 'The item in the 2006 DS platformer that makes the hero enormous enough to flatten scenery.', a: 'Mega Mushroom' },
      { q: 'The burrowing brown critter that bursts out of the ground to chase the plumber.', a: 'Monty Mole' },
      { q: 'The sunglasses-wearing rodent boss who throws explosives in the second NES platformer.', a: 'Mouser' },
      { q: 'The wand-waving wizard turtle that fires geometric energy blasts.', a: 'Magikoopa' },
      { q: 'The cloud prince raised as a frog who joins the hero in the 1996 role-playing game.', a: 'Mallow' },
      { q: 'The hefty rhino-like general who serves the villain in the 2009 handheld adventure.', a: 'Midbus' },
      { q: 'The scooter-riding pizza-delivering girl of the microgame series.', a: 'Mona' },
      { q: 'The hooded fortune teller of the flat-paper games who speaks in riddles.', a: 'Merlon' },
      { q: 'The white rabbit in the 1996 castle basement that gives up a star when caught.', a: 'Mip', alt: ['MIPS'] },
      { q: 'The first and easiest four-course tournament in the racing games.', a: 'Mushroom Cup' },
    ],
    N: [
      { q: 'The purple rabbit thief who steals power-ups in the 2012 Wii U platformer.', a: 'Nabbit' },
      { q: 'The Kyoto company, founded in 1889, that publishes this entire series.', a: 'Nintendo' },
      { q: 'The skyscraper metropolis in Odyssey where Pauline serves as mayor.', a: 'New Donk City' },
      { q: 'The 1996 console with a three-pronged controller that hosted the plumber\'s first 3D outing.', a: 'Nintendo 64', alt: ['N64'] },
      { q: 'The small black hopping enemy in a hood, first seen in the second NES platformer.', a: 'Ninji' },
      { q: 'The tall canyon inlet with an ancient shell village in the 2002 tropical game.', a: 'Noki Bay' },
    ],
    O: [
      { q: 'The hat-shaped airship the plumber flies between kingdoms in his 2017 adventure.', a: 'Odyssey' },
      { q: 'The cheerful folded-paper sister of the villain in the 2020 crafted adventure.', a: 'Olivia' },
      { q: 'The 2020 Switch adventure whose villain, Olly, folds the world into creases.', a: 'Origami King' },
      { q: 'The long-necked bird enemy of the second NES platformer that carries a masked minion.', a: 'Ostro' },
    ],
    P: [
      { q: 'The blonde pink-dressed princess who is usually the kidnapping victim.', a: 'Peach', alt: ['Princess Peach'] },
      { q: 'The original damsel of the 1981 arcade cabinet, later the mayor of a big city.', a: 'Pauline' },
      { q: 'The green-stalked biting flower that emerges from warp tubes.', a: 'Piranha Plant' },
      { q: 'The huge polka-dot-trousered plant boss who first appeared in the 2002 tropical game.', a: 'Petey Piranha' },
      { q: 'The stacked-segment cactus enemy of the desert levels.', a: 'Pokey' },
      { q: 'The 2000 Nintendo 64 role-playing game in which the hero is a flat cut-out.', a: 'Paper Mario' },
      { q: 'The ghost-sucking vacuum cleaner worn on the back in the mansion games.', a: 'Poltergust' },
      { q: 'The 2009 Wii platformer outfit that lets the plumber slide on his belly and swim well.', a: 'Penguin Suit' },
      { q: 'The 2009 Wii platformer item that launches the plumber straight up with a flick of the wrist.', a: 'Propeller Mushroom' },
      { q: 'The stout palm-headed native species of the sunny island resort.', a: 'Pianta' },
      { q: 'The flamboyant blond hero of the neighbouring realm in Superstar Saga.', a: 'Prince Peasley' },
      { q: 'The mischievous ghost dog first befriended in Dark Moon.', a: 'Polterpup' },
      { q: 'The green tube the plumber enters to travel between areas.', a: 'Pipe', alt: ['Warp Pipe'] },
      { q: 'The feathered white item in the third NES platformer that grants a whole level of free flight.', a: 'P Wing' },
      { q: 'The pink-roofed home of the princess and hub of the 1996 platformer.', a: 'Peach\'s Castle' },
    ],
    Q: [
      { q: 'The floating yellow cube marked with a punctuation symbol that holds items.', a: 'Question Block' },
      { q: 'The enormous crowned insect ruler of the honeycomb planet in the 2007 space game.', a: 'Queen Bee' },
      { q: 'The huge green monarch of the realm the brothers visit in Superstar Saga.', a: 'Queen Bean' },
    ],
    R: [
      { q: 'The tall white-gowned mother of the star children who watches over the cosmos.', a: 'Rosalina' },
      { q: 'The tail-and-ears form gained from a leaf in the third NES platformer.', a: 'Raccoon Mario' },
      { q: 'The pink-headed one of the seven bratty siblings, who wears sunglasses and slams the ground.', a: 'Roy Koopa' },
      { q: 'The final racing course, a neon track suspended in outer space.', a: 'Rainbow Road' },
      { q: 'The homing racing projectile that chases the car directly ahead.', a: 'Red Shell' },
      { q: 'The rhinoceros animal buddy that charges through enemies in the ape platformers.', a: 'Rambi' },
      { q: 'The 2010 space sequel item that turns the plumber into a rolling boulder.', a: 'Rock Mushroom' },
      { q: 'The enormous scaled beast fought at the top of the crumbling stone kingdom in Odyssey.', a: 'Ruined Dragon' },
      { q: 'The muscular bird champion of the fighting league in The Thousand-Year Door.', a: 'Rawk Hawk' },
    ],
    S: [
      { q: 'The masked enemy in a white robe that shuffles along, very common in the island games.', a: 'Shy Guy' },
      { q: 'The red spotted item that doubles the plumber\'s size.', a: 'Super Mushroom' },
      { q: 'The red-shelled enemy with sharp barbs that a cloud rider drops from above.', a: 'Spiny' },
      { q: 'The flashing item that grants a few seconds of invincibility.', a: 'Star', alt: ['Super Star'] },
      { q: 'The 16-bit console whose 1991 pack-in game was the plumber\'s fourth main platformer.', a: 'Super Nintendo', alt: ['SNES'] },
      { q: 'The armoured weapon-forging final villain of the 1996 role-playing game.', a: 'Smithy' },
      { q: 'The 2002 GameCube platformer set on a polluted tropical island.', a: 'Sunshine', alt: ['Super Mario Sunshine'] },
      { q: 'The 2017 hybrid console that hosted both Odyssey and Wonder.', a: 'Switch', alt: ['Nintendo Switch'] },
      { q: 'The star-shaped guardian collectible of the sunny island resort.', a: 'Shine Sprite' },
      { q: 'The desert-and-pyramid kingdom ruled by the orange-dressed princess.', a: 'Sarasaland' },
      { q: 'The planet-shaped hub with a face that the plumber pilots in the 2010 space sequel.', a: 'Starship Mario' },
      { q: 'The enemy that coughs up metal balls and rolls them at the plumber.', a: 'Spike' },
      { q: 'The heaviest of the mallet-throwing siblings, whose landing stuns the player.', a: 'Sledge Bro' },
      { q: 'The 3D World item that dresses the plumber in a cat costume.', a: 'Super Bell' },
      { q: 'The tiny fairy princesses kidnapped by the Koopa king in the 2013 Wii U platformer.', a: 'Sprixie', alt: ['Sprixie Princess'] },
    ],
    T: [
      { q: 'The mushroom-capped retainer who says the princess is in another castle.', a: 'Toad' },
      { q: 'The pink-pigtailed mushroom girl who becomes Peachette with a magic crown.', a: 'Toadette' },
      { q: 'The elderly mustachioed mushroom steward who fusses over the princess.', a: 'Toadsworth' },
      { q: 'The stone slab with a scowl that slams down to crush the plumber.', a: 'Thwomp' },
      { q: 'The full raccoon-dog costume in the third NES platformer that allows turning to stone.', a: 'Tanooki Suit' },
      { q: 'The purple alien who hypnotises Sarasaland in the 1989 handheld debut.', a: 'Tatanga' },
      { q: 'The youngest sister of the pigtailed ape, playable in the 1999 64-bit ape game.', a: 'Tiny Kong' },
      { q: 'The home town of the skeletal sombrero-wearing folk in the Sand Kingdom.', a: 'Tostarena' },
      { q: 'The butterfly-like guide who tattles on enemies in the 2007 dimension-flipping game.', a: 'Tippi' },
      { q: 'The hat-stacking member of the rabbit wedding planner quartet.', a: 'Topper' },
      { q: 'The 2004 GameCube flat-paper sequel set in the port of Rogueport.', a: 'Thousand-Year Door' },
    ],
    U: [
      { q: 'The mischievous monkey that steals the plumber\'s cap on a tropical mountain.', a: 'Ukiki' },
      { q: 'The canine tool in Maker that reverses your last placement.', a: 'Undodog' },
    ],
    V: [
      { q: 'The shadow sister partner who hides the hero inside her own shade in the 2004 sequel.', a: 'Vivian' },
      { q: 'The headwear in the 1996 platformer that lets the plumber walk through metal fences.', a: 'Vanish Cap' },
      { q: 'The vain harpy-like usurper who seizes Nimbus Land in the 1996 role-playing game.', a: 'Valentina' },
    ],
    W: [
      { q: 'The greedy yellow-and-purple antihero with a zigzag mustache.', a: 'Wario' },
      { q: 'The lanky purple-clad rival of the green brother, first seen in the 2000 tennis game.', a: 'Waluigi' },
      { q: 'The frog king who is the final boss of the second NES platformer.', a: 'Wart' },
      { q: 'The yellow caterpillar with a flower on its head that turns red with rage when stomped.', a: 'Wiggler' },
      { q: 'The flat stone enemy that topples forward and must be stomped on its back.', a: 'Whomp' },
      { q: 'The 2006 motion-control console that hosted both of the space platformers.', a: 'Wii' },
      { q: 'The bow-wearing female of the seven royal siblings, who throws rings at the plumber.', a: 'Wendy O. Koopa', alt: ['Wendy'] },
      { q: 'The huge blue bird that snatches treasure away in the mushroom explorer\'s own game.', a: 'Wingo' },
      { q: 'The frantic microgame series starring the greedy antihero and his oddball friends.', a: 'WarioWare' },
      { q: 'The 2023 side-scroller item that warps a stage with surreal effects.', a: 'Wonder Flower' },
    ],
    X: [
      { q: 'The masked alien foot soldiers led by Grodus in the 2004 sequel.', a: 'X-Naut', alt: ['X-Nauts'] },
    ],
    Y: [
      { q: 'The green dinosaur with a long tongue and a saddle who swallows enemies.', a: 'Yoshi' },
      { q: 'The 1995 16-bit platformer with a crayon art style starring the little dinosaurs.', a: 'Yoshi\'s Island' },
      { q: 'The fourth playable mushroom retainer in the 2009 Wii platformer, dressed in a banana-coloured vest.', a: 'Yellow Toad' },
      { q: 'The 1997 Nintendo 64 picture-book platformer starring the little dinosaurs.', a: 'Yoshi\'s Story' },
      { q: 'The giant monster in Superstar Saga that swallows the brothers whole.', a: 'Yoob' },
      { q: 'The 1992 puzzle game about matching rows of biscuits.', a: 'Yoshi\'s Cookie' },
    ],
    Z: [
      { q: 'The gigantic bird deity awakened in the 2013 handheld dream adventure.', a: 'Zeekeeper' },
      { q: 'The grouchy cook of Rogueport who prepares recipes in the 2004 sequel.', a: 'Zess T.' },
    ],
  },
};
