import type { RawPack } from '../core/packs';

export const fandomTheOfficePack: RawPack = {
  id: 'fandom-the-office',
  name: 'The Office',
  description: 'Scranton superfan trivia: characters, cold opens, alter egos and running gags.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'teen',
  emoji: '📋',
  accent: '#0369a1',
  letters: {
    A: [
      { q: 'The head of the small number-crunching department who owns many cats and rules the party committee.', a: 'Angela', alt: ['Angela Martin'] },
      { q: 'The Cornell graduate salesman who plays the banjo and once sang in a college a cappella group.', a: 'Andy Bernard', alt: ['Andy'] },
      { q: 'The sports marketing company Jim helps found with an old college friend.', a: 'Athlead' },
      { q: 'The name Jan gives her baby daughter.', a: 'Astrid' },
      { q: 'The fried onion appetizer Michael and Jan share at a chain restaurant while closing a deal.', a: 'Awesome Blossom' },
      { q: 'The restaurant Michael insists makes the real thing, unlike the cheap knockoff whose delivery boy he detains.', a: 'Alfredo\'s Pizza Cafe' },
      { q: 'The secret pact Dwight forms with Jim in the warehouse during season one downsizing rumors.', a: 'Alliance', alt: ['The Alliance'] },
      { q: 'The department where Kevin, Oscar and Angela sit behind a partition.', a: 'Accounting' },
      { q: 'The actress who plays Michael\'s soulmate from human resources.', a: 'Amy Ryan' },
      { q: 'The actor who plays the finance chief and once worked as a real stockbroker.', a: 'Andy Buckley' },
      { q: 'The program Andy is sent to after punching a hole in the wall.', a: 'Anger management' },
    ],
    B: [
      { q: 'The business owner who marries Phyllis and always introduces himself using his company name.', a: 'Bob Vance' },
      { q: 'The root vegetable grown on the Schrute family land.', a: 'Beets', alt: ['Beet'] },
      { q: 'The science fiction series Dwight adores and Jim pretends to have watched.', a: 'Battlestar Galactica' },
      { q: 'The cat Dwight gives Angela to replace the one he put down.', a: 'Bandit' },
      { q: 'The documentary crew boom operator who steps in to protect Pam in season nine.', a: 'Brian' },
      { q: 'The sport in the season one episode where Michael picks a team to face the warehouse crew.', a: 'Basketball' },
      { q: 'The a cappella rival Andy resents, nicknamed after a green vegetable.', a: 'Broccoli Rob' },
      { q: 'The financial state Michael tries to declare by shouting it across the room.', a: 'Bankruptcy' },
      { q: 'The nickname Andy gives Jim after seeing his lunch on the first day.', a: 'Big Tuna' },
      { q: 'The German folklore figure Dwight dresses as, judging people impish or admirable.', a: 'Belsnickel' },
      { q: 'The episode where Michael tests candidates at a lake and Pam walks over hot coals.', a: 'Beach Games' },
      { q: 'The episode where Michael meets a woman under a sheet at a donation van.', a: 'Blood Drive' },
      { q: 'The writer and actor who plays the temp turned corporate executive.', a: 'B.J. Novak', alt: ['BJ Novak'] },
      { q: 'The episode set on a boat where Michael plays captain and Roy finally sets a wedding date.', a: 'Booze Cruise' },
      { q: 'The desk figurine Angela secretly gives Dwight in his own likeness.', a: 'Bobblehead' },
    ],
    C: [
      { q: 'The oldest employee, a probable identity thief who shares a name with a rock guitarist.', a: 'Creed', alt: ['Creed Bratton'] },
      { q: 'The Ivy League school Andy never stops mentioning.', a: 'Cornell' },
      { q: 'The chain restaurant that hosts the first Dundies and later bans Michael for life.', a: 'Chili\'s' },
      { q: 'The season two finale where the warehouse becomes a gambling hall and Jim confesses his feelings.', a: 'Casino Night' },
      { q: 'The name Michael gives the dance room he opens in his old downstairs work space.', a: 'Cafe Disco' },
      { q: 'The strict vice president in season five who cancels Michael\'s anniversary party.', a: 'Charles Miner', alt: ['Charles'] },
      { q: 'The animals Angela keeps at home in great numbers.', a: 'Cats', alt: ['Cat'] },
      { q: 'The first child born to Jim and Pam.', a: 'Cece', alt: ['CeCe', 'Cecelia'] },
      { q: 'The real estate agent Michael dates after she sells him his home.', a: 'Carol' },
      { q: 'The rainforest nation where Andy injures himself on a zip line in season six.', a: 'Costa Rica' },
      { q: 'The pot of food Kevin simmers overnight and then spills across the carpet.', a: 'Chili' },
      { q: 'The state Michael moves to so Holly can be near her parents.', a: 'Colorado' },
      { q: 'The kind of home Michael buys in season two and later shares with Jan.', a: 'Condo' },
      { q: 'The season two episode where Michael\'s video music player gift ruins a gift exchange.', a: 'Christmas Party' },
      { q: 'The actor and musician who plays the warehouse boss.', a: 'Craig Robinson' },
      { q: 'The one-person department Kelly runs out of the annex.', a: 'Customer service' },
      { q: 'The season nine hire nicknamed after Dwight because he looks so much like him.', a: 'Clark' },
      { q: 'The episode where Angela pushes Dwight to try to take Michael\'s job.', a: 'Coup', alt: ['The Coup'] },
      { q: 'The newspaper puzzle Stanley fills in through most meetings.', a: 'Crossword' },
      { q: 'The snack Ryan leaves in the toaster oven, setting the kitchen ablaze.', a: 'Cheese pita' },
    ],
    D: [
      { q: 'The beet farmer and top salesman who serves as a volunteer sheriff\'s deputy.', a: 'Dwight', alt: ['Dwight Schrute'] },
      { q: 'The annual employee awards ceremony Michael hosts at a chain restaurant.', a: 'Dundies', alt: ['The Dundies'] },
      { q: 'The name of the paper company whose Scranton branch the documentary follows.', a: 'Dunder Mifflin' },
      { q: 'The chief financial officer who later buys the company back and rewards Jim.', a: 'David Wallace' },
      { q: 'The warehouse foreman who teaches Michael fake slang and later joins Jim\'s startup.', a: 'Darryl', alt: ['Darryl Philbin'] },
      { q: 'The season one episode with a sensitivity seminar and index cards naming ethnicities.', a: 'Diversity Day' },
      { q: 'The short-lived replacement manager who injures himself trying to dunk a basketball.', a: 'Deangelo Vickers', alt: ['Deangelo'] },
      { q: 'Michael\'s famous misspelling of his deputy\'s first name on an award certificate.', a: 'Dwigt' },
      { q: 'The acclaimed episode at Michael and Jan\'s place featuring a tiny plasma television.', a: 'Dinner Party' },
      { q: 'The nickname Andy\'s family uses for him instead of his usual one.', a: 'Drew' },
      { q: 'The episode where Jan sues the company and Michael\'s diary is read aloud in court.', a: 'Deposition', alt: ['The Deposition'] },
      { q: 'The Hindu festival Kelly invites the whole staff to celebrate.', a: 'Diwali' },
      { q: 'The employee Michael fires on the costume holiday who later throws a rock through the window.', a: 'Devon' },
      { q: 'The name Ryan gives the flashy new website he launches in season four.', a: 'Dunder Mifflin Infinity' },
      { q: 'The system Dwight builds to email the chief executive if the staff make five errors.', a: 'Doomsday device', alt: ['Doomsday'] },
      { q: 'The rival traveling salesman Michael hires after learning Pam once dated him.', a: 'Danny Cordray', alt: ['Danny'] },
    ],
    E: [
      { q: 'The cheerful front desk worker raised in foster homes who dates Andy and later Pete.', a: 'Erin', alt: ['Erin Hannon'] },
      { q: 'The manager before Michael, later decapitated in a car accident.', a: 'Ed Truck' },
      { q: 'The nickname of Scranton shown on the welcome sign in the opening credits.', a: 'Electric City' },
      { q: 'The actress who plays the receptionist hired in season five.', a: 'Ellie Kemper' },
      { q: 'The episode where Michael reads everyone\'s messages and crashes a barbecue at Jim\'s house.', a: 'Email Surveillance' },
      { q: 'The actor who plays the banjo-strumming Cornell alumnus, also known for the Hangover films.', a: 'Ed Helms' },
      { q: 'The exotic dancer hired for Phyllis\'s bachelorette party.', a: 'Elizabeth' },
    ],
    F: [
      { q: 'The exclusive book and culture society whose only members are Pam, Oscar and Toby.', a: 'Finer Things Club' },
      { q: 'The season four premiere built around a charity race after a parking lot accident.', a: 'Fun Run' },
      { q: 'The state where the Sabre special project sends Dwight, Jim and Erin.', a: 'Florida' },
      { q: 'The box-of-paper snowshoe race invented during the staff games.', a: 'Flonkerton' },
      { q: 'The device Jim uses to send Dwight notes that seem to come from his future self.', a: 'Fax machine', alt: ['Fax'] },
      { q: 'The surname of the human resources man who works in the annex.', a: 'Flenderson' },
      { q: 'The warehouse worker whose crude drawing of Pam sparks a confrontation in season nine.', a: 'Frank' },
      { q: 'The season two episode in which Ryan destroys a toaster oven and forces an evacuation.', a: 'Fire', alt: ['The Fire'] },
      { q: 'Darryl\'s job title running the loading dock crew.', a: 'Foreman' },
      { q: 'The episode where Michael plants drugs in the human resources man\'s bag.', a: 'Frame Toby' },
      { q: 'The season nine episode about Dwight\'s relatives and their beet business, shot as a backdoor pilot.', a: 'The Farm' },
    ],
    G: [
      { q: 'The tall, awkward corporate liaison who dates Erin and loves horror films.', a: 'Gabe', alt: ['Gabe Lewis'] },
      { q: 'The candy-movie-inspired promotion where Michael hides discount coupons in paper shipments.', a: 'Golden Ticket' },
      { q: 'The name of the Dwight counterpart in the British original.', a: 'Gareth' },
      { q: 'The episode where Andy throws a lavish lawn event to impress his father.', a: 'Garden Party' },
      { q: 'The masked villain that Michael Scarn battles, played on screen by Jim.', a: 'Goldenface' },
      { q: 'The episode where Michael forces the staff to mourn his dead predecessor.', a: 'Grief Counseling' },
      { q: 'The surname of Jan\'s ex-husband, briefly hyphenated onto hers.', a: 'Gould' },
      { q: 'The first name of Oscar\'s boyfriend who attends the holiday party.', a: 'Gil' },
      { q: 'The season six premiere where Michael spreads rumors to hide one true secret.', a: 'Gossip' },
    ],
    H: [
      { q: 'The human resources replacement who becomes Michael\'s soulmate and moves west with him.', a: 'Holly', alt: ['Holly Flax'] },
      { q: 'Jan\'s young assistant at head office who records a song about her.', a: 'Hunter' },
      { q: 'The building security guard called whenever there is trouble in the lobby.', a: 'Hank' },
      { q: 'The surname Pam takes when she marries.', a: 'Halpert' },
      { q: 'The season one episode where Dwight picks a stingy insurance plan and invents fake diseases.', a: 'Health Care' },
      { q: 'The costume holiday episode in which Michael must let someone go by the end of the month.', a: 'Halloween' },
      { q: 'Andy\'s Cornell a cappella group, whose name puns on a musical term.', a: 'Here Comes Treble' },
      { q: 'The season one finale where a purse saleswoman visits and the men compete for her attention.', a: 'Hot Girl' },
    ],
    I: [
      { q: 'The crime Dwight insists is no joke because millions of families suffer every year.', a: 'Identity theft' },
      { q: 'The English actor who played the demanding vice president in season five.', a: 'Idris Elba' },
      { q: 'The episode where Michael burns his foot on a George Foreman grill.', a: 'Injury', alt: ['The Injury'] },
      { q: 'The comedy class Michael takes where he ruins every scene by pretending to have a gun.', a: 'Improv' },
      { q: 'Pam\'s bridesmaid friend whom Dwight briefly dates.', a: 'Isabel' },
      { q: 'The episode where Dwight takes Ryan to the beet farm for a bizarre sales rite.', a: 'Initiation' },
    ],
    J: [
      { q: 'The prank-loving salesman who often glances straight into the camera.', a: 'Jim', alt: ['Jim Halpert'] },
      { q: 'The corporate executive who dates Michael and later has a baby by a donor.', a: 'Jan', alt: ['Jan Levinson'] },
      { q: 'The wobbly dessert Jim suspends Dwight\'s stapler inside during a classic prank.', a: 'Jell-O', alt: ['Jello', 'Gelatin'] },
      { q: 'The Caribbean island where Michael vacations with Jan, exposed by photos left on the printer.', a: 'Jamaica' },
      { q: 'The Connecticut branch manager who bolts to a rival chain after using an offer as leverage.', a: 'Josh', alt: ['Josh Porter'] },
      { q: 'The Southern chief executive who brings two large dogs into the workplace.', a: 'Jo Bennett' },
      { q: 'The civic service Jim pretends to still be doing so he can stay home with the baby.', a: 'Jury duty' },
      { q: 'The crime-fighting rodent Jim jokes about after Dwight mishears a movie title.', a: 'Justice Beaver' },
      { q: 'The actor who plays the camera-glancing prankster and later directed episodes.', a: 'John Krasinski' },
      { q: 'The actress who plays the artist at the front desk.', a: 'Jenna Fischer' },
    ],
    K: [
      { q: 'The accountant known for terrible math, a spilled lunch and drumming in a tribute band.', a: 'Kevin', alt: ['Kevin Malone'] },
      { q: 'The chatty customer service worker obsessed with celebrity gossip.', a: 'Kelly Kapoor' },
      { q: 'The Connecticut transfer who dates Jim and later manages the Utica branch.', a: 'Karen', alt: ['Karen Filippelli'] },
      { q: 'The decorative fish feature Michael falls into during a client visit.', a: 'Koi pond' },
      { q: 'The temporary front desk worker who tries to seduce Jim on the southern trip.', a: 'Kathy' },
      { q: 'The made-up number Kevin invents so his figures add up.', a: 'Keleven' },
      { q: 'The first name on Erin\'s birth certificate that she chooses not to use.', a: 'Kelly' },
      { q: 'The first name of Roy\'s rowdy brother who also works in the warehouse.', a: 'Kenny' },
    ],
    L: [
      { q: 'The county Scranton sits in, named proudly in the branch\'s own commercial.', a: 'Lackawanna' },
      { q: 'The episode where Michael makes his own commercial featuring an animated paper hero.', a: 'Local Ad' },
      { q: 'The parasite outbreak Meredith is wrongly blamed for in season nine.', a: 'Lice' },
      { q: 'The rap parody video Michael and Dwight film as a welcome tour of their city.', a: 'Lazy Scranton' },
      { q: 'The two-part episode where Michael and Pam tour other branches to give talks.', a: 'Lecture Circuit' },
      { q: 'The surname of the state senator Angela marries.', a: 'Lipton' },
      { q: 'The season nine episode where Dwight is finally promoted to run the branch.', a: 'Livin\' the Dream' },
      { q: 'Michael\'s lazy nephew hired as an assistant and later spanked in the conference room.', a: 'Luke' },
    ],
    M: [
      { q: 'The regional manager who insists he is a friend first and a boss second.', a: 'Michael Scott', alt: ['Michael'] },
      { q: 'The supplier relations rep struck by a car during a charity race.', a: 'Meredith', alt: ['Meredith Palmer'] },
      { q: 'Dwight\'s beet-farming cousin who is terrified of the internet.', a: 'Mose' },
      { q: 'The secret agent hero of the spy film the branch manager writes and stars in.', a: 'Michael Scarn' },
      { q: 'The episode where Michael runs a Savannah-themed mystery game amid bankruptcy rumors.', a: 'Murder' },
      { q: 'The sensitivity consultant whose name Michael refuses to say aloud.', a: 'Mr. Brown' },
      { q: 'The criminal organization Michael believes an insurance salesman belongs to.', a: 'Mafia', alt: ['The Mafia'] },
      { q: 'The North African theme Phyllis chooses for the holiday party after taking charge.', a: 'Moroccan Christmas', alt: ['Moroccan'] },
      { q: 'The episode where the Connecticut staff arrive and unsettle everyone in Scranton.', a: 'Merger', alt: ['The Merger'] },
      { q: 'The two-part episode where Michael works nights at a telemarketing firm to pay debts.', a: 'Money' },
      { q: 'The writer and actress who plays the gossip-loving customer service worker.', a: 'Mindy Kaling' },
    ],
    N: [
      { q: 'The self-given nickname Andy uses, shortened from his surname.', a: 'Nard Dog' },
      { q: 'The British executive who simply declares herself manager after Andy leaves.', a: 'Nellie', alt: ['Nellie Bertram'] },
      { q: 'The city where the company head office sits.', a: 'New York' },
      { q: 'The dim handyman Dwight hires who later works in the warehouse.', a: 'Nate' },
      { q: 'The two-part episode where Jim and Pam marry near a famous waterfall.', a: 'Niagara' },
      { q: 'The American network that aired the series for nine seasons.', a: 'NBC' },
      { q: 'The number of seasons the American version ran.', a: 'Nine' },
    ],
    O: [
      { q: 'The accountant who corrects everyone and has an affair with a state senator.', a: 'Oscar', alt: ['Oscar Martinez'] },
      { q: 'The episode where the staff invent games with paper clips while Michael buys a condo.', a: 'Office Olympics' },
      { q: 'The title of the mockumentary series itself, shared with its British predecessor.', a: 'The Office' },
      { q: 'The job title Pam invents for herself after the store project ends.', a: 'Office Administrator' },
    ],
    P: [
      { q: 'The front desk worker turned saleswoman who marries her longtime prank partner.', a: 'Pam', alt: ['Pam Beesly'] },
      { q: 'The saleswoman who marries the refrigeration company owner.', a: 'Phyllis', alt: ['Phyllis Vance'] },
      { q: 'The once-a-year free snack event in the lobby that Stanley adores.', a: 'Pretzel Day' },
      { q: 'The bandana-wearing alter ego Michael uses to scare the staff about life behind bars.', a: 'Prison Mike' },
      { q: 'The city where Jim\'s sports marketing startup is based.', a: 'Philadelphia' },
      { q: 'The island territory where Jim and Pam honeymoon.', a: 'Puerto Rico' },
      { q: 'The single product the Scranton branch sells.', a: 'Paper' },
      { q: 'The staff group Angela chairs until Pam eventually takes it over.', a: 'Party Planning Committee' },
      { q: 'The bar where the staff drink after work.', a: 'Poor Richard\'s' },
      { q: 'The name Angela gives her son, which Dwight had also picked out.', a: 'Phillip', alt: ['Philip'] },
      { q: 'The must-have holiday doll Dwight buys up and resells at a huge markup.', a: 'Princess Unicorn' },
      { q: 'The extreme movement fad Michael, Dwight and Andy shout about while leaping onto boxes.', a: 'Parkour' },
      { q: 'The state the branch operates in.', a: 'Pennsylvania' },
      { q: 'The episode where an obscene drawing turns up watermarked on the company stock.', a: 'Product Recall' },
      { q: 'The season nine episode built around a folding contest for prize money.', a: 'Paper Airplane' },
      { q: 'The season nine hire nicknamed Plop who ends up with Erin.', a: 'Pete' },
    ],
    Q: [
      { q: 'The department Creed claims to run, which he mispronounces in his own way.', a: 'Quality assurance', alt: ['Quality Assurance'] },
    ],
    R: [
      { q: 'The temp who rises to a corporate job and is later arrested for fraud.', a: 'Ryan', alt: ['Ryan Howard'] },
      { q: 'The warehouse worker engaged to Pam for years before their breakup.', a: 'Roy', alt: ['Roy Anderson'] },
      { q: 'The costumed villain Dwight becomes every Earth Day to shame litterbugs.', a: 'Recyclops' },
      { q: 'The unsettling executive played by James Spader who talks his way into the top job.', a: 'Robert California' },
      { q: 'The disease Michael raises money to cure after the parking lot accident.', a: 'Rabies' },
      { q: 'The pediatrician Kelly leaves Scranton with at the end of season eight.', a: 'Ravi' },
      { q: 'The comedian who co-created the British original and cameos as a manager in a lift.', a: 'Ricky Gervais' },
      { q: 'The actor who plays the volunteer deputy and beet farmer.', a: 'Rainn Wilson' },
      { q: 'The front desk job Pam holds before moving into sales.', a: 'Receptionist' },
    ],
    S: [
      { q: 'The Pennsylvania city where the branch is located.', a: 'Scranton' },
      { q: 'The Florida printer company that buys the paper firm in season six.', a: 'Sabre' },
      { q: 'The crossword-loving salesman who suffers a heart attack during a meeting.', a: 'Stanley', alt: ['Stanley Hudson'] },
      { q: 'The Connecticut branch that merges into Scranton in season three.', a: 'Stamford' },
      { q: 'The agritourism bed and breakfast Dwight runs with his cousin.', a: 'Schrute Farms' },
      { q: 'The frail old cat Dwight freezes after ending its suffering.', a: 'Sprinkles' },
      { q: 'The candle business Michael\'s girlfriend starts after losing her corporate job.', a: 'Serenity by Jan' },
      { q: 'The online virtual world where Dwight plays a better version of himself.', a: 'Second Life' },
      { q: 'The two-part episode that opens with Dwight\'s terrifying staged fire drill.', a: 'Stress Relief' },
      { q: 'The episode where Michael threatens to jump off the roof onto a bouncy castle.', a: 'Safety Training' },
      { q: 'The actor who played the branch manager for seven seasons.', a: 'Steve Carell' },
      { q: 'The English town where the British original is set.', a: 'Slough' },
      { q: 'The two-woman pop act Kelly and Erin form to record a music video.', a: 'Subtle Sexuality' },
      { q: 'The Police tribute band Kevin drums for.', a: 'Scrantonicity' },
      { q: 'The desk tool Jim keeps hiding inside desserts and other objects to annoy Dwight.', a: 'Stapler' },
      { q: 'The first name of Toby\'s daughter.', a: 'Sasha' },
      { q: 'The winter projectile Dwight hurls at Jim relentlessly in a holiday episode.', a: 'Snowball' },
    ],
    T: [
      { q: 'The human resources representative Michael despises above all others.', a: 'Toby', alt: ['Toby Flenderson'] },
      { q: 'The title of the spy film Michael spends over a decade writing and shooting.', a: 'Threat Level Midnight' },
      { q: 'The Florida capital where the store project team is sent to work.', a: 'Tallahassee' },
      { q: 'The vulgar traveling salesman whose visits thrill Michael and horrify everyone else.', a: 'Todd Packer', alt: ['Packer'] },
      { q: 'The job title Ryan starts with, which Michael keeps using as an insult.', a: 'Temp' },
      { q: 'The holiday gift Jim gives Pam, hiding inside it a card he takes back out.', a: 'Teapot' },
    ],
    U: [
      { q: 'The New York branch Karen runs after leaving Scranton.', a: 'Utica' },
    ],
    V: [
      { q: 'The cooling business that shares the building with the paper branch.', a: 'Vance Refrigeration' },
      { q: 'The experienced telemarketer who befriends Michael at his second job.', a: 'Vikram' },
      { q: 'The romantic February episode where Michael visits head office and gifts fly around Scranton.', a: 'Valentine\'s Day' },
    ],
    W: [
      { q: 'The lower level of the building whose whole crew wins the lottery and quits.', a: 'Warehouse' },
      { q: 'The season five premiere in which the branches compete in a corporate slim-down contest.', a: 'Weight Loss' },
      { q: 'The all-at-once notification startup Ryan founds and loses money on.', a: 'Wuphf', alt: ['Wuphf.com'] },
      { q: 'The episode where the men learn about a mall trip after a flasher targets Phyllis.', a: 'Women\'s Appreciation' },
      { q: 'The season six finale about who leaked that the company printers catch fire.', a: 'Whistleblower' },
    ],
    Y: [
      { q: 'The gift exchange format Michael forces on the staff at the season two holiday party.', a: 'Yankee Swap' },
    ],
  },
};
