import type { RawPack } from '../core/packs';

export const fandomDisneyPack: RawPack = {
  id: 'fandom-disney',
  name: 'Disney and Pixar',
  description: 'Princesses, sidekicks, villains, songs and Pixar classics the whole family knows.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '🏰',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: 'The 1998 Pixar film about an ant colony that hires warrior insects for protection.', a: 'A Bug\'s Life', alt: ['Bugs Life'] },
      { q: 'The street rat of Agrabah who finds a magic lamp in the Cave of Wonders.', a: 'Aladdin' },
      { q: 'The youngest daughter of the sea king who longs to walk on land.', a: 'Ariel' },
      { q: 'Elsa\'s optimistic younger sister, who climbs the North Mountain to find her.', a: 'Anna' },
      { q: 'The red, fiery emotion who erupts in flames in the 2015 Pixar film.', a: 'Anger' },
      { q: 'The boy who owns Woody and Buzz Lightyear.', a: 'Andy' },
      { q: 'The 2001 Disney film subtitled The Lost Empire.', a: 'Atlantis' },
      { q: 'The pickpocketing monkey who travels with the street rat of Agrabah.', a: 'Abu' },
      { q: 'The princess who pricks her finger on a spindle and sleeps for a century.', a: 'Aurora', alt: ['Briar Rose'] },
      { q: 'The snowbound kingdom ruled by Queen Elsa.', a: 'Arendelle' },
      { q: 'The gaunt, pale food critic who is won over by a humble peasant dish.', a: 'Anton Ego', alt: ['Ego'] },
      { q: 'The girl who follows a white rabbit down a hole in a 1951 Disney film.', a: 'Alice' },
    ],
    B: [
      { q: 'The space ranger action figure who at first believes he is a real astronaut.', a: 'Buzz Lightyear', alt: ['Buzz'] },
      { q: 'The book-loving village girl who falls for a cursed prince in a 1991 Disney film.', a: 'Belle' },
      { q: 'The 1942 Disney film about a young deer of the forest whose mother is shot.', a: 'Bambi' },
      { q: 'The laid-back jungle bear who sings about the bare necessities.', a: 'Baloo' },
      { q: 'The tiny toddler girl who wanders through a closet door into the monster world.', a: 'Boo' },
      { q: 'The part-elephant imaginary friend Riley invented as a toddler.', a: 'Bing Bong' },
      { q: 'The porcelain shepherdess who returns as a fearless lost-toy adventurer.', a: 'Bo Peep' },
      { q: 'The great white shark who leads a support group for fish-friendly predators.', a: 'Bruce' },
      { q: 'The 2012 Pixar film set in the Scottish Highlands about a princess and her mother.', a: 'Brave' },
      { q: 'The mouse detective of Baker Street in a 1986 Disney film.', a: 'Basil' },
      { q: 'The cursed master of an enchanted castle who guards a single magic rose.', a: 'Beast' },
      { q: 'The inflatable healthcare robot in Big Hero 6.', a: 'Baymax' },
      { q: 'The Madrigal uncle nobody in the family will talk about.', a: 'Bruno' },
    ],
    C: [
      { q: 'The scullery maid who loses a glass slipper on the palace steps.', a: 'Cinderella' },
      { q: 'The 2017 Pixar film set in Mexico during the Day of the Dead.', a: 'Coco' },
      { q: 'The 2006 Pixar film in which a hotshot racer learns humility in a desert town.', a: 'Cars' },
      { q: 'The fur-obsessed woman who covets a coat made of Dalmatian puppies.', a: 'Cruella de Vil', alt: ['Cruella'] },
      { q: 'The widowed balloon salesman who flies his house toward Paradise Falls.', a: 'Carl Fredricksen', alt: ['Carl'] },
      { q: 'The small talking teacup son of the enchanted teapot.', a: 'Chip' },
      { q: 'The only woman cook in the Paris kitchen of a 2007 Pixar film.', a: 'Colette' },
      { q: 'The uptight mantel clock who runs the enchanted castle staff.', a: 'Cogsworth' },
      { q: 'The good-luck insect that Mulan\'s grandmother sends along in a little cage.', a: 'Cri-Kee' },
      { q: 'The one-eyed receptionist with snake hair who dates Mike Wazowski.', a: 'Celia' },
      { q: 'The gruff cape buffalo who runs the Zootopia police department.', a: 'Chief Bogo', alt: ['Bogo'] },
      { q: 'The hound puppy who secretly befriends a young fox.', a: 'Copper' },
    ],
    D: [
      { q: 'The 1941 Disney film about a big-eared circus elephant who learns to fly.', a: 'Dumbo' },
      { q: 'The forgetful blue tang who helps a clownfish father cross the ocean.', a: 'Dory' },
      { q: 'The silent youngest of the seven dwarfs.', a: 'Dopey' },
      { q: 'The talking golden retriever obsessed with squirrels in a 2009 Pixar film.', a: 'Dug' },
      { q: 'The grumpy town medic of Radiator Springs, secretly a three-time Piston Cup champion.', a: 'Doc Hudson', alt: ['Doc'] },
      { q: 'The green emotion who firmly refuses broccoli in a 2015 Pixar film.', a: 'Disgust' },
      { q: 'The sailor-suited waterfowl with a famously raspy voice, introduced in 1934.', a: 'Donald Duck', alt: ['Donald'] },
      { q: 'The Canadian stuntman toy voiced by Keanu Reeves.', a: 'Duke Caboom' },
      { q: 'The blue oil company sponsor that Lightning McQueen dreams of racing for.', a: 'Dinoco' },
      { q: 'The Madrigal sister blessed with super-sensitive hearing.', a: 'Dolores' },
      { q: 'The elegant white mother cat in The Aristocats.', a: 'Duchess' },
    ],
    E: [
      { q: 'The ice-powered queen who sings Let It Go.', a: 'Elsa' },
      { q: 'The gloomy grey donkey of the Hundred Acre Wood.', a: 'Eeyore' },
      { q: 'The sleek white probe robot who befriends a lonely trash-compacting machine.', a: 'EVE' },
      { q: 'The tiny fashion designer who insists that capes are a deadly mistake.', a: 'Edna Mode', alt: ['Edna'] },
      { q: 'Carl Fredricksen\'s adventurous wife, shown mostly in a silent montage.', a: 'Ellie' },
      { q: 'The fiery young woman at the heart of the 2023 Pixar film Elemental.', a: 'Ember' },
      { q: 'The heavyset brother of the rat chef in a 2007 Pixar film.', a: 'Emile' },
      { q: 'The 2021 Disney film about a magical Colombian family called the Madrigals.', a: 'Encanto' },
      { q: 'The Romani dancer pursued by Judge Frollo.', a: 'Esmeralda' },
      { q: 'The prince rescued from a shipwreck by a mermaid.', a: 'Eric' },
      { q: 'The stretchy superhero alias of Helen Parr.', a: 'Elastigirl' },
    ],
    F: [
      { q: 'Ariel\'s nervous yellow-and-blue fish friend.', a: 'Flounder' },
      { q: 'The 2013 Disney film loosely based on a Hans Christian Andersen snow queen tale.', a: 'Frozen' },
      { q: 'The inventive ant who accidentally destroys his colony\'s food offering.', a: 'Flik' },
      { q: 'The jittery purple emotion in a 2015 Pixar film.', a: 'Fear' },
      { q: 'The charming thief who helps a tower-bound girl escape.', a: 'Flynn Rider', alt: ['Flynn', 'Eugene'] },
      { q: 'The judge of Notre Dame who lusts after Esmeralda.', a: 'Frollo' },
      { q: 'Geppetto\'s black-and-white pet kitten.', a: 'Figaro' },
      { q: 'The 1940 Disney film built around eight animated classical music pieces.', a: 'Fantasia' },
      { q: 'Pocahontas\'s grumpy little hummingbird companion.', a: 'Flit' },
      { q: 'The spork craft toy that Bonnie makes at kindergarten orientation.', a: 'Forky' },
      { q: 'The 2003 Pixar film about a clownfish father who swims to Sydney.', a: 'Finding Nemo' },
    ],
    G: [
      { q: 'The wisecracking blue lamp dweller voiced by Robin Williams.', a: 'Genie' },
      { q: 'The vain village hunter who is determined to marry Belle.', a: 'Gaston' },
      { q: 'The lonely woodcarver who wishes his marionette were alive.', a: 'Geppetto' },
      { q: 'The tall, clumsy dog in a vest and floppy hat, pal of Mickey Mouse.', a: 'Goofy' },
      { q: 'The late Paris chef whose motto is that anyone can cook.', a: 'Gusteau' },
      { q: 'The perpetually scowling one of the seven dwarfs.', a: 'Grumpy' },
      { q: 'The scarred Moorish idol who leads the tank gang in a dentist\'s office.', a: 'Gill' },
      { q: 'The vain woman who steals a baby to keep her magic hair working.', a: 'Gothel', alt: ['Mother Gothel'] },
      { q: 'The little Italian forklift who performs lightning-fast tyre changes.', a: 'Guido' },
    ],
    H: [
      { q: 'The 1997 Disney film about the mortal-raised son of Zeus.', a: 'Hercules' },
      { q: 'The blue-flamed lord of the underworld in a 1997 Disney film.', a: 'Hades' },
      { q: 'The dim-witted rooster who stows away on Moana\'s canoe.', a: 'Hei Hei' },
      { q: 'The one-eyed insect tyrant who demands food from an ant colony.', a: 'Hopper' },
      { q: 'The sly top-hatted fox who leads a wooden puppet astray.', a: 'Honest John' },
      { q: 'The seven-legged octopus who helps Dory escape the aquarium.', a: 'Hank' },
      { q: 'The piggy bank toy voiced by John Ratzenberger.', a: 'Hamm' },
      { q: 'The teenage robotics prodigy of Big Hero 6.', a: 'Hiro' },
      { q: 'The cheeriest of the seven dwarfs.', a: 'Happy' },
    ],
    I: [
      { q: 'Jafar\'s sarcastic red parrot.', a: 'Iago' },
      { q: 'The 2015 Pixar film staged largely within the mind of an 11-year-old girl.', a: 'Inside Out' },
      { q: 'The 2004 Pixar film about a superhero family hiding in the suburbs.', a: 'The Incredibles', alt: ['Incredibles'] },
      { q: 'The shy teenage elf who casts a resurrection spell in a 2020 Pixar film.', a: 'Ian' },
      { q: 'Miguel\'s stern great-great-grandmother in the Land of the Dead.', a: 'Imelda' },
      { q: 'The Madrigal sister who conjures flowers wherever she walks.', a: 'Isabela' },
    ],
    J: [
      { q: 'The scheming grand vizier of Agrabah.', a: 'Jafar' },
      { q: 'The sultan\'s daughter who keeps a pet tiger named Rajah.', a: 'Jasmine' },
      { q: 'The top-hatted insect who serves as a wooden puppet\'s conscience.', a: 'Jiminy Cricket', alt: ['Jiminy'] },
      { q: 'The blue-haired lead emotion at the control console in a 2015 Pixar film.', a: 'Joy' },
      { q: 'The yodelling cowgirl doll from Woody\'s Roundup.', a: 'Jessie' },
      { q: 'The rabbit rookie officer of the Zootopia police force.', a: 'Judy Hopps', alt: ['Judy'] },
      { q: 'The Parr family baby who turns out to have dozens of powers.', a: 'Jack-Jack', alt: ['Jack Jack'] },
      { q: 'The Pumpkin King of Halloween Town.', a: 'Jack Skellington' },
    ],
    K: [
      { q: 'The ice harvester who travels with a reindeer named Sven.', a: 'Kristoff' },
      { q: 'The self-absorbed young emperor who is turned into a llama.', a: 'Kuzco' },
      { q: 'The hypnotic python who tries to eat Mowgli.', a: 'Kaa' },
      { q: 'The colourful flightless bird that Russell befriends at Paradise Falls.', a: 'Kevin' },
      { q: 'The trident-bearing sea ruler who is Ariel\'s father.', a: 'King Triton', alt: ['Triton'] },
      { q: 'Roo\'s mother in the Hundred Acre Wood.', a: 'Kanga' },
      { q: 'Yzma\'s dim but good-hearted muscular henchman.', a: 'Kronk' },
      { q: 'The Atlantean princess in a 2001 Disney adventure film.', a: 'Kida' },
    ],
    L: [
      { q: 'The red number 95 rookie racer of a 2006 Pixar film.', a: 'Lightning McQueen', alt: ['McQueen'] },
      { q: 'The 2021 Pixar film about a sea monster boy on the Italian Riviera.', a: 'Luca' },
      { q: 'The French candelabra who sings Be Our Guest.', a: 'Lumiere' },
      { q: 'The hopping desk lamp of a 1986 short who became the studio logo mascot.', a: 'Luxo Jr', alt: ['Luxo'] },
      { q: 'The director of the 1995 computer-animated hit who became the studio\'s chief creative officer (surname).', a: 'Lasseter' },
      { q: 'The Hawaiian girl who adopts a blue alien and passes him off as a dog.', a: 'Lilo' },
      { q: 'The strawberry-scented bear who secretly rules Sunnyside Daycare.', a: 'Lotso' },
      { q: 'The clumsy garbage boy who becomes a celebrated Paris chef with hidden help.', a: 'Linguini' },
      { q: 'The pampered cocker spaniel who shares a plate of spaghetti with a stray.', a: 'Lady' },
      { q: 'The trumpet-playing alligator in The Princess and the Frog.', a: 'Louis' },
      { q: 'The 1994 Disney film about a cub who flees Pride Rock and returns to rule.', a: 'The Lion King' },
      { q: 'The Madrigal sister with super strength who carries the donkeys.', a: 'Luisa' },
    ],
    M: [
      { q: 'The 1998 Disney film about a Chinese woman who joins the army for her father.', a: 'Mulan' },
      { q: 'The Polynesian chief\'s daughter who voyages to restore a goddess\'s heart.', a: 'Moana' },
      { q: 'The studio mascot who debuted in the 1928 short Steamboat Willie.', a: 'Mickey Mouse', alt: ['Mickey'] },
      { q: 'The short, round, one-eyed green monster who is Sulley\'s best friend.', a: 'Mike Wazowski', alt: ['Mike'] },
      { q: 'The overprotective clownfish father who searches the ocean for his son.', a: 'Marlin' },
      { q: 'The archery-loving Scottish princess of a 2012 Pixar film.', a: 'Merida' },
      { q: 'The boastful shape-shifting demigod with a magical fish hook.', a: 'Maui' },
      { q: 'The motherly enchanted teapot of the cursed castle.', a: 'Mrs Potts' },
      { q: 'The horned dark fairy who curses a baby princess at her christening.', a: 'Maleficent' },
      { q: 'The super-strong superhero alias of Bob Parr.', a: 'Mr Incredible' },
      { q: 'The rusty tow truck who is best friends with Lightning McQueen.', a: 'Mater' },
      { q: 'The only Madrigal grandchild who receives no magical gift.', a: 'Mirabel' },
      { q: 'The absent-minded wizard who tutors young Arthur in The Sword in the Stone.', a: 'Merlin' },
      { q: 'The boy raised by wolves in The Jungle Book.', a: 'Mowgli' },
      { q: 'The guitar-loving boy who crosses into the Land of the Dead.', a: 'Miguel' },
      { q: 'The small red dragon guardian sent by the ancestors to protect Mulan.', a: 'Mushu' },
      { q: 'The 2001 Pixar film set in a factory powered by the screams of children.', a: 'Monsters Inc', alt: ['Monsters Incorporated'] },
      { q: 'The lion ruler killed in a wildebeest stampede in a 1994 Disney film.', a: 'Mufasa' },
    ],
    N: [
      { q: 'The clownfish son taken by a diver near the reef drop-off.', a: 'Nemo' },
      { q: 'Simba\'s childhood friend who later becomes his queen.', a: 'Nala' },
      { q: 'The con-artist fox who reluctantly partners with a rabbit officer.', a: 'Nick Wilde', alt: ['Nick'] },
      { q: 'Lilo\'s stressed older sister and legal guardian.', a: 'Nani' },
      { q: 'The pelican who carries a clownfish father into a Sydney dentist\'s office.', a: 'Nigel' },
      { q: 'The Fang warrior who becomes Raya\'s bitter rival.', a: 'Namaari' },
    ],
    O: [
      { q: 'The cheerful snowman who dreams of what he would do in summer.', a: 'Olaf' },
      { q: 'The orphan kitten hero of a 1988 Disney film set in New York.', a: 'Oliver' },
      { q: 'The 2020 Pixar film about two elf brothers questing to see their father again.', a: 'Onward' },
      { q: 'The cheery trading post owner who greets customers with a big yoo-hoo.', a: 'Oaken' },
      { q: 'The lucky rabbit character created before Mickey Mouse and lost to Universal.', a: 'Oswald' },
    ],
    P: [
      { q: 'The 1940 Disney film about a wooden puppet who longs to be a real boy.', a: 'Pinocchio' },
      { q: 'The 1995 Disney film about a Powhatan woman and the settler John Smith.', a: 'Pocahontas' },
      { q: 'The flatulent warthog who befriends a meerkat named Timon.', a: 'Pumbaa' },
      { q: 'Mickey Mouse\'s yellow pet dog.', a: 'Pluto' },
      { q: 'The animation studio Steve Jobs bought from Lucasfilm in 1986.', a: 'Pixar' },
      { q: 'The timid small pink friend of Winnie the Pooh.', a: 'Piglet' },
      { q: 'The boy who refuses to grow up and lives in Neverland.', a: 'Peter Pan' },
      { q: 'The royal suitor who searches his kingdom for the owner of a glass slipper.', a: 'Prince Charming' },
      { q: 'Rapunzel\'s colour-changing pet chameleon.', a: 'Pascal' },
      { q: 'The winged horse given to Hercules as a companion.', a: 'Pegasus' },
    ],
    Q: [
      { q: 'The card-suited ruler of Wonderland who shouts Off with their heads.', a: 'Queen of Hearts' },
      { q: 'The hunchbacked bell ringer of Notre Dame.', a: 'Quasimodo' },
    ],
    R: [
      { q: 'The girl with 70 feet of magic golden hair locked in a hidden tower.', a: 'Rapunzel' },
      { q: 'The rat with a gourmet palate who cooks in a famous Paris kitchen.', a: 'Remy' },
      { q: 'The Minnesota girl whose five emotions run her mind.', a: 'Riley' },
      { q: 'The wise mandrill who presents the newborn cub to the animals of the savanna.', a: 'Rafiki' },
      { q: 'The 2007 Pixar film named after a rustic French vegetable dish.', a: 'Ratatouille' },
      { q: 'The eager Wilderness Explorer scout who joins Carl Fredricksen\'s trip.', a: 'Russell' },
      { q: 'The forgotten Route 66 town at the heart of a 2006 Pixar film.', a: 'Radiator Springs' },
      { q: 'The anxious green dinosaur toy who wishes he were scarier.', a: 'Rex' },
      { q: 'The camouflaging lizard-like villain of a 2001 Pixar film.', a: 'Randall' },
      { q: 'The 1973 Disney film that casts the outlaw of Sherwood Forest as a fox.', a: 'Robin Hood' },
      { q: 'The lone warrior who seeks the last dragon in a 2021 Disney film.', a: 'Raya' },
      { q: 'The gravel-voiced paperwork monster who secretly leads an undercover agency.', a: 'Roz' },
    ],
    S: [
      { q: 'The lion cub who flees Pride Rock after his father\'s death.', a: 'Simba' },
      { q: 'The dark-maned brother who seizes Pride Rock by treachery.', a: 'Scar' },
      { q: 'The big blue furry top scarer of Monsters Inc.', a: 'Sulley', alt: ['Sullivan', 'James P Sullivan'] },
      { q: 'The blue, tearful emotion in a 2015 Pixar film.', a: 'Sadness' },
      { q: 'Kristoff\'s loyal reindeer.', a: 'Sven' },
      { q: 'The 2020 Pixar film about a jazz pianist separated from his body.', a: 'Soul' },
      { q: 'The toy-torturing boy who lives next door to Andy.', a: 'Sid' },
      { q: 'The 1937 release that was the first full-length animated feature from the studio.', a: 'Snow White' },
      { q: 'The know-it-all seagull who calls a fork a dinglehopper.', a: 'Scuttle' },
      { q: 'The Jamaican crab court composer who sings Under the Sea.', a: 'Sebastian' },
      { q: 'The blue alien known officially as Experiment 626.', a: 'Stitch' },
      { q: 'The dachshund toy with a coiled metal spring for a middle.', a: 'Slinky Dog', alt: ['Slinky'] },
      { q: 'The Incredibles villain who was once a fanboy named Buddy Pine.', a: 'Syndrome' },
      { q: 'The last dragon who joins Raya\'s quest.', a: 'Sisu' },
    ],
    T: [
      { q: 'The New Orleans waitress who dreams of opening her own restaurant.', a: 'Tiana' },
      { q: 'The wisecracking meerkat who preaches Hakuna Matata.', a: 'Timon' },
      { q: 'The 2010 Disney retelling of the girl with magic hair in a tower.', a: 'Tangled' },
      { q: 'Peter Pan\'s jealous little pixie companion.', a: 'Tinker Bell', alt: ['Tink'] },
      { q: 'The 1995 release that was the first fully computer-animated feature film.', a: 'Toy Story' },
      { q: 'The 1999 Disney film about a man raised by gorillas in Africa.', a: 'Tarzan' },
      { q: 'Bambi\'s rabbit friend with a fast-tapping hind foot.', a: 'Thumper' },
      { q: 'Tarzan\'s rowdy female gorilla friend.', a: 'Terk' },
      { q: 'The streetwise stray dog who falls for a pampered spaniel.', a: 'Tramp' },
    ],
    U: [
      { q: 'The 2009 Pixar film that opens with a montage of Carl and Ellie\'s marriage.', a: 'Up' },
      { q: 'The sea witch who trades legs for a mermaid\'s voice.', a: 'Ursula' },
    ],
    V: [
      { q: 'The glitching kart racer girl in a 2012 arcade-set Disney film.', a: 'Vanellope' },
      { q: 'The shy Parr daughter who can turn invisible and make force fields.', a: 'Violet' },
    ],
    W: [
      { q: 'The pull-string cowboy doll who is Andy\'s favourite toy.', a: 'Woody' },
      { q: 'The 2008 Pixar film about a lonely trash-compacting robot left on Earth.', a: 'WALL-E', alt: ['Wall E'] },
      { q: 'The honey-loving bear of the Hundred Acre Wood.', a: 'Winnie the Pooh', alt: ['Pooh'] },
      { q: 'The 2012 Disney film about an arcade villain who wants to be a hero.', a: 'Wreck-It Ralph' },
      { q: 'The eldest Darling child who flies away to Neverland.', a: 'Wendy' },
      { q: 'The studio co-founder who first voiced Mickey Mouse and opened a California theme park in 1955.', a: 'Walt Disney' },
    ],
    Y: [
      { q: 'The scheming elderly royal advisor in The Emperor\'s New Groove.', a: 'Yzma' },
      { q: 'The short, hot-tempered soldier who trains alongside Mulan.', a: 'Yao' },
    ],
    Z: [
      { q: 'The 2016 Disney film set in a metropolis of talking mammals.', a: 'Zootopia' },
      { q: 'The fussy hornbill majordomo to the lion ruler of Pride Rock.', a: 'Zazu' },
      { q: 'The purple emperor toy who claims to be Buzz Lightyear\'s father.', a: 'Zurg' },
    ],
  },
};
