import type { RawPack } from '../core/packs';

export const fandomGotPack: RawPack = {
  id: 'fandom-got',
  name: 'Game of Thrones',
  description: 'Houses, sigils, dragons and Westerosi lore from the books and the shows.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'teen',
  emoji: '🐉',
  accent: '#0f766e',
  letters: {
    A: [
      { q: 'The younger daughter of Winterfell who trains with the guild of assassins in Braavos.', a: 'Arya', alt: ['Arya Stark'] },
      { q: 'The first Targaryen king to unite six of the seven kingdoms under one crown.', a: 'Aegon', alt: ['Aegon I'] },
      { q: 'The Slaver\'s Bay city where Daenerys buys her army of eunuch soldiers.', a: 'Astapor' },
      { q: 'The house of the Vale whose sigil is a white falcon and a crescent moon.', a: 'Arryn' },
      { q: 'The queen consort of King Viserys I who champions her own son for the throne.', a: 'Alicent Hightower', alt: ['Alicent'] },
      { q: 'The one-eyed second son of Queen Alicent, rider of the dragon Vhagar.', a: 'Aemond' },
      { q: 'The blind old maester of Castle Black who was secretly born a Targaryen.', a: 'Aemon' },
      { q: 'The English actor who plays Theon Greyjoy in the HBO series.', a: 'Alfie Allen' },
      { q: 'The Norvoshi captain of the guards who serves Prince Doran in the far south.', a: 'Areo Hotah' },
      { q: 'The island off the Reach famous for producing the finest wine in Westeros.', a: 'Arbor', alt: ['The Arbor'] },
      { q: 'The lady of Starfall long rumoured to be the true mother of Jon Snow.', a: 'Ashara Dayne', alt: ['Ashara'] },
      { q: 'The mad last Targaryen king, burned rulers alive and was slain in his own hall.', a: 'Aerys', alt: ['Aerys II'] },
    ],
    B: [
      { q: 'The Free City of the Titan and the House of Black and White.', a: 'Braavos' },
      { q: 'The crippled boy of Winterfell who becomes the Three-Eyed Raven.', a: 'Bran', alt: ['Brandon'] },
      { q: 'The tall woman warrior sworn to Catelyn who later joins the Kingsguard.', a: 'Brienne' },
      { q: 'The lowborn sellsword who fights for Tyrion in a trial by combat at the Eyrie.', a: 'Bronn' },
      { q: 'The house whose sigil is a crowned black stag on a gold field.', a: 'Baratheon' },
      { q: 'The Lord of the Iron Islands who declares himself king and falls from a bridge.', a: 'Balon Greyjoy', alt: ['Balon'] },
      { q: 'The Kingsguard knight called the Bold who is dismissed by Joffrey and later serves Daenerys.', a: 'Barristan Selmy', alt: ['Barristan'] },
      { q: 'The one-eyed leader of the Brotherhood Without Banners, revived again and again by Thoros.', a: 'Beric Dondarrion', alt: ['Beric'] },
      { q: 'The bay and the clash there in which Tyrion destroys the fleet of Stannis with green fire.', a: 'Blackwater' },
      { q: 'The house of the Dreadfort whose sigil is a flayed man.', a: 'Bolton' },
      { q: 'The brother of Ned, a First Ranger of the Night\'s Watch who vanishes beyond the Wall.', a: 'Benjen' },
      { q: 'The pious boy king for whom the Great Sept in the capital is named.', a: 'Baelor' },
    ],
    C: [
      { q: 'The Lannister queen and mother of Joffrey, Myrcella and Tommen.', a: 'Cersei' },
      { q: 'The wife of Ned Stark and mother of Robb, born a lady of Riverrun.', a: 'Catelyn' },
      { q: 'The seat of House Lannister, carved out of a great stone hill above Lannisport.', a: 'Casterly Rock' },
      { q: 'The main fortress of the Night\'s Watch and home of its Lord Commander.', a: 'Castle Black' },
      { q: 'The surname shared by the knight called the Hound and his monstrous brother.', a: 'Clegane' },
      { q: 'The wildling north of the Wall whose fortified home shelters the black brothers.', a: 'Craster' },
      { q: 'The Oldtown institution where maesters study and forge their chains.', a: 'Citadel', alt: ['The Citadel'] },
      { q: 'The undead ranger riding an elk who guides Bran to the cave of the greenseer.', a: 'Coldhands' },
      { q: 'The swamp-dwelling people of the Neck who travel by reed boat.', a: 'Crannogmen' },
      { q: 'The region ruled directly from the Iron Throne, containing the capital itself.', a: 'Crownlands', alt: ['The Crownlands'] },
    ],
    D: [
      { q: 'The exiled queen titled Mother of Dragons and Breaker of Chains.', a: 'Daenerys', alt: ['Dany'] },
      { q: 'The largest black and red dragon, named for the late husband of its rider.', a: 'Drogon' },
      { q: 'The horse-riding nomads of the great grass sea.', a: 'Dothraki' },
      { q: 'The hot southern kingdom ruled from Sunspear that dragons never conquered.', a: 'Dorne' },
      { q: 'The volcanic island fortress that was the Targaryen seat in Westeros.', a: 'Dragonstone' },
      { q: 'The former smuggler and Onion Knight who serves Stannis.', a: 'Davos', alt: ['Davos Seaworth'] },
      { q: 'The grim seat of House Bolton.', a: 'Dreadfort', alt: ['The Dreadfort'] },
      { q: 'The warlord who takes Daenerys as his bride and dies of an infected wound.', a: 'Drogo', alt: ['Khal Drogo'] },
      { q: 'The Valyrian steel sword of Visenya Targaryen, later carried by Brynden Rivers.', a: 'Dark Sister' },
      { q: 'The gout-stricken Prince of Dorne and elder brother of Oberyn.', a: 'Doran Martell', alt: ['Doran'] },
      { q: 'The pale milkglass blade of House Dayne, forged from a fallen star.', a: 'Dawn' },
      { q: 'The towering hedge knight who befriends a young prince in the novellas set a century earlier.', a: 'Duncan the Tall', alt: ['Duncan', 'Ser Duncan the Tall'] },
    ],
    E: [
      { q: 'The Lord of Winterfell and Hand of the King who is beheaded in the first season.', a: 'Eddard', alt: ['Eddard Stark'] },
      { q: 'The one-eyed pirate uncle of Yara who seizes the Salt Throne.', a: 'Euron' },
      { q: 'The vast eastern continent across the Narrow Sea.', a: 'Essos' },
      { q: 'The high castle of the Vale reached through the Bloody Gate.', a: 'Eyrie', alt: ['The Eyrie'] },
      { q: 'The English actress who plays Daenerys in the HBO series.', a: 'Emilia Clarke' },
      { q: 'The paramour of Oberyn who avenges him by poisoning a young princess.', a: 'Ellaria Sand', alt: ['Ellaria'] },
      { q: 'The Lord of Riverrun whose marriage feast becomes a massacre.', a: 'Edmure', alt: ['Edmure Tully'] },
      { q: 'The Dornish princess wed to Rhaegar who died during the sack of the capital.', a: 'Elia Martell', alt: ['Elia'] },
      { q: 'The Night\'s Watch castle at the far eastern end of the Wall.', a: 'Eastwatch' },
      { q: 'The ginger English pop singer who cameos as a Lannister soldier in season seven.', a: 'Ed Sheeran' },
    ],
    F: [
      { q: 'The guild of shape-changing assassins based in Braavos.', a: 'Faceless Men', alt: ['The Faceless Men'] },
      { q: 'What the wildlings beyond the Wall call themselves.', a: 'Free Folk', alt: ['The Free Folk'] },
      { q: 'The house of the Twins that betrays the northern army at a marriage feast.', a: 'Frey' },
      { q: 'The nine independent city states of western Essos, taken together.', a: 'Free Cities', alt: ['The Free Cities'] },
      { q: 'The three-word words of House Targaryen.', a: 'Fire and Blood' },
      { q: 'The bleak stony spit of land in the Vale where Petyr Baelish was born.', a: 'Fingers', alt: ['The Fingers'] },
    ],
    G: [
      { q: 'The house of Pyke whose sigil is a golden kraken.', a: 'Greyjoy' },
      { q: 'The bastard blacksmith son of King Robert who forges dragonglass weapons.', a: 'Gendry' },
      { q: 'The commander of the eunuch soldiers who falls in love with Missandei.', a: 'Grey Worm' },
      { q: 'The albino direwolf of Jon Snow.', a: 'Ghost' },
      { q: 'The wildling girl whom Sam rescues from her cruel father.', a: 'Gilly' },
      { q: 'The famous sellsword army of Essos that Cersei hires with Iron Bank gold.', a: 'Golden Company', alt: ['The Golden Company'] },
      { q: 'The giant knight nicknamed the Mountain.', a: 'Gregor Clegane', alt: ['Gregor'] },
      { q: 'The stone-skin disease that afflicts Shireen and threatens Jorah.', a: 'Greyscale' },
      { q: 'The faction supporting Aegon II during the Dance of the Dragons.', a: 'Greens', alt: ['The Greens'] },
    ],
    H: [
      { q: 'The simple giant stableboy of Winterfell who can say only one word.', a: 'Hodor' },
      { q: 'The lush seat of House Tyrell in the Reach.', a: 'Highgarden' },
      { q: 'The Tarly seat in the Reach where Samwell grew up.', a: 'Horn Hill' },
      { q: 'The vast burned castle on the God\'s Eye, cursed since dragonfire melted its towers.', a: 'Harrenhal' },
      { q: 'The nickname of the burned knight Sandor Clegane.', a: 'Hound', alt: ['The Hound'] },
      { q: 'The Oldtown house whose sigil is a lit white beacon on grey.', a: 'Hightower' },
      { q: 'The ruined wildling settlement where Jon first fights the walkers of ice.', a: 'Hardhome' },
      { q: 'The dying Lord of Riverrun and father of Catelyn.', a: 'Hoster', alt: ['Hoster Tully'] },
    ],
    I: [
      { q: 'The barbed seat in the Red Keep, said to be forged from a thousand surrendered blades.', a: 'Iron Throne', alt: ['The Iron Throne'] },
      { q: 'The reaving people of the western islands who follow the Drowned God.', a: 'Ironborn', alt: ['The Ironborn'] },
      { q: 'The Valyrian steel greatsword of House Stark, later reforged into two blades.', a: 'Ice' },
      { q: 'The Braavosi lending house whose motto insists it will have its due.', a: 'Iron Bank', alt: ['The Iron Bank'] },
      { q: 'The fat Pentoshi magister who arranges the marriage of Daenerys to a horselord.', a: 'Illyrio', alt: ['Illyrio Mopatis'] },
      { q: 'The bleak rocky home of the reavers, ruled from the castle of Pyke.', a: 'Iron Islands', alt: ['The Iron Islands'] },
      { q: 'The English actor who plays Bran in the HBO series.', a: 'Isaac Hempstead Wright' },
      { q: 'The great war navy commanded by Euron Greyjoy.', a: 'Iron Fleet', alt: ['The Iron Fleet'] },
    ],
    J: [
      { q: 'The bastard raised at Winterfell who becomes Lord Commander of the Night\'s Watch.', a: 'Jon Snow', alt: ['Jon'] },
      { q: 'The golden-haired knight who loses his sword hand to the men of Vargo Hoat.', a: 'Jaime', alt: ['Jaime Lannister'] },
      { q: 'The cruel boy king poisoned at his own wedding feast.', a: 'Joffrey' },
      { q: 'The exiled knight of Bear Island who loves Daenerys from afar.', a: 'Jorah', alt: ['Jorah Mormont'] },
      { q: 'The Braavosi assassin who owes three deaths to Arya.', a: 'Jaqen H\'ghar', alt: ['Jaqen'] },
      { q: 'The Lord Commander nicknamed the Old Bear.', a: 'Jeor Mormont', alt: ['Jeor'] },
      { q: 'The green-dreaming crannogman boy who guides Bran to the far north.', a: 'Jojen', alt: ['Jojen Reed'] },
      { q: 'The Hand of the King whose suspicious death sets the whole story in motion.', a: 'Jon Arryn' },
    ],
    K: [
      { q: 'The capital city of the Seven Kingdoms.', a: 'King\'s Landing' },
      { q: 'The order of seven sworn knights in white cloaks who protect the royal family.', a: 'Kingsguard', alt: ['The Kingsguard'] },
      { q: 'The Dothraki title given to the wife of their warlord.', a: 'Khaleesi' },
      { q: 'The English actor who plays Jon Snow in the HBO series.', a: 'Kit Harington' },
      { q: 'The northern house whose young lord Robb executes for murdering Lannister hostages.', a: 'Karstark' },
      { q: 'The mocking nickname Jaime earns for cutting down Aerys.', a: 'Kingslayer', alt: ['The Kingslayer'] },
      { q: 'The many-armed sea beast on the Greyjoy banner.', a: 'Kraken' },
    ],
    L: [
      { q: 'The rich house of Casterly Rock whose sigil is a golden lion.', a: 'Lannister' },
      { q: 'The Valyrian steel bastard sword given to Jon by the Old Bear.', a: 'Longclaw' },
      { q: 'The sister of Ned whose abduction by Rhaegar sparked Robert\'s Rebellion.', a: 'Lyanna Stark', alt: ['Lyanna'] },
      { q: 'The Knight of Flowers who jousts in the colours of Renly.', a: 'Loras', alt: ['Loras Tyrell'] },
      { q: 'The paranoid widow who rules the Vale and coddles her sickly son Robin.', a: 'Lysa', alt: ['Lysa Arryn'] },
      { q: 'The nickname of the schemer Petyr Baelish.', a: 'Littlefinger' },
      { q: 'The English actress who plays Cersei in the HBO series.', a: 'Lena Headey' },
      { q: 'The Free City famous for its subtle poisons and beautiful pleasure houses.', a: 'Lys' },
      { q: 'The fiery god R\'hllor is also known by this three-word title.', a: 'Lord of Light', alt: ['The Lord of Light'] },
    ],
    M: [
      { q: 'The red priestess of Asshai who serves the fire god and advises Stannis.', a: 'Melisandre' },
      { q: 'The clever rose of Highgarden who marries three separate kings.', a: 'Margaery', alt: ['Margaery Tyrell'] },
      { q: 'The largest of the Slaver\'s Bay cities, later ruled by Daenerys.', a: 'Meereen' },
      { q: 'The Naathi translator freed in Astapor who becomes a trusted adviser.', a: 'Missandei' },
      { q: 'The house of Bear Island whose sigil is a bear.', a: 'Mormont' },
      { q: 'The Dornish house whose sigil is a sun pierced by a spear.', a: 'Martell' },
      { q: 'The King Beyond the Wall who unites the free folk under one banner.', a: 'Mance Rayder', alt: ['Mance'] },
      { q: 'The ruined causeway stronghold that guards the swampy Neck.', a: 'Moat Cailin' },
      { q: 'The Lannister princess sent south to Dorne and killed by a poisoned kiss.', a: 'Myrcella' },
      { q: 'The second Targaryen king, a brutal warrior found dead upon the Iron Throne.', a: 'Maegor' },
      { q: 'The chained scholars and healers who serve the great castles of Westeros.', a: 'Maester', alt: ['Maesters'] },
    ],
    N: [
      { q: 'The short familiar name by which Eddard Stark is always called.', a: 'Ned' },
      { q: 'The black brotherhood sworn to guard the great barrier of ice.', a: 'Night\'s Watch', alt: ['The Night\'s Watch'] },
      { q: 'The blue-eyed leader of the walkers of ice in the HBO series.', a: 'Night King', alt: ['The Night King'] },
      { q: 'The slim thin sword that Jon gives to Arya as a parting gift.', a: 'Needle' },
      { q: 'The peaceful island home of Missandei, famed for its butterflies.', a: 'Naath' },
      { q: 'The direwolf of Arya, named for a Rhoynish warrior queen.', a: 'Nymeria' },
      { q: 'The body of water separating Westeros from the eastern continent.', a: 'Narrow Sea', alt: ['The Narrow Sea'] },
    ],
    O: [
      { q: 'The Red Viper of Dorne who fights as champion for Tyrion at his trial.', a: 'Oberyn', alt: ['Oberyn Martell'] },
      { q: 'The sharp-tongued grandmother of Highgarden called the Queen of Thorns.', a: 'Olenna', alt: ['Olenna Tyrell'] },
      { q: 'The wildling woman captured near Winterfell who later protects Rickon.', a: 'Osha' },
      { q: 'The ancient Winterfell servant who tells the children terrifying bedtime stories.', a: 'Old Nan' },
      { q: 'The name Brienne gives to the Valyrian steel sword she receives from Jaime.', a: 'Oathkeeper' },
      { q: 'The southern city of the Citadel and the Starry Sept.', a: 'Oldtown' },
      { q: 'The nameless deities of the North, worshipped before carved weirwood faces.', a: 'Old Gods', alt: ['The Old Gods'] },
    ],
    P: [
      { q: 'The loyal squire of Tyrion who later serves Brienne on the road.', a: 'Podrick', alt: ['Pod', 'Podrick Payne'] },
      { q: 'The crumbling Greyjoy castle built on sea stacks and bridges.', a: 'Pyke' },
      { q: 'The Master of Coin who rises from minor lordling to Lord Paramount of the Trident.', a: 'Petyr Baelish', alt: ['Petyr'] },
      { q: 'The doddering Grand Maester who bends with every wind in the capital.', a: 'Pycelle' },
      { q: 'The American actor who plays Tyrion in the HBO series.', a: 'Peter Dinklage' },
      { q: 'The Free City where Daenerys and Viserys shelter with a rich magister.', a: 'Pentos' },
      { q: 'The warlock of Qarth who splits into many copies of himself before Daenerys.', a: 'Pyat Pree' },
      { q: 'The Lannister soldier who steals Needle and is killed by Arya in a roadside inn.', a: 'Polliver' },
    ],
    Q: [
      { q: 'The disgraced maester who experiments on the Mountain for Cersei.', a: 'Qyburn' },
      { q: 'The wealthy walled city called the greatest that ever was or will be.', a: 'Qarth' },
      { q: 'The masked shadowbinder from Asshai who warns Daenerys in riddles.', a: 'Quaithe' },
      { q: 'The famous nickname of Olenna Tyrell.', a: 'Queen of Thorns', alt: ['The Queen of Thorns'] },
    ],
    R: [
      { q: 'The Young Wolf who is proclaimed King in the North by his father\'s bannermen.', a: 'Robb', alt: ['Robb Stark'] },
      { q: 'The hard-drinking king killed by a boar during a hunt.', a: 'Robert Baratheon', alt: ['Robert'] },
      { q: 'The silver-haired crown prince who lost to Robert in single combat at the ruby ford.', a: 'Rhaegar' },
      { q: 'The youngest Stark son, shot down by arrows before the Battle of the Bastards.', a: 'Rickon' },
      { q: 'The youngest brother of Robert who claims the throne and is slain by a shadow.', a: 'Renly' },
      { q: 'The Tully seat built where the Tumblestone joins the Red Fork.', a: 'Riverrun' },
      { q: 'The sadistic bastard of the Dreadfort who breaks and renames Theon.', a: 'Ramsay', alt: ['Ramsay Bolton', 'Ramsay Snow'] },
      { q: 'The soft-spoken northern lord who betrays Robb at the wedding at the Twins.', a: 'Roose', alt: ['Roose Bolton'] },
      { q: 'The royal castle of the capital, raised by the son of Aegon the Conqueror.', a: 'Red Keep', alt: ['The Red Keep'] },
      { q: 'The infamous massacre at the Twins during the marriage feast of Edmure.', a: 'Red Wedding', alt: ['The Red Wedding'] },
      { q: 'The Realm\'s Delight, named heir by King Viserys I in House of the Dragon.', a: 'Rhaenyra' },
      { q: 'The green dragon of Daenerys, shot down by a scorpion bolt near Dragonstone.', a: 'Rhaegal' },
    ],
    S: [
      { q: 'The eldest Stark daughter who is finally crowned Queen in the North.', a: 'Sansa' },
      { q: 'The bookish black brother who slays a walker of ice with a dragonglass dagger.', a: 'Samwell', alt: ['Sam', 'Samwell Tarly'] },
      { q: 'The stern middle brother of Robert who presses his claim with the red priestess.', a: 'Stannis' },
      { q: 'The burned knight who protects Sansa and fears fire above all.', a: 'Sandor Clegane', alt: ['Sandor'] },
      { q: 'The camp follower whom Tyrion loves and who testifies against him at his trial.', a: 'Shae' },
      { q: 'The house of Winterfell whose sigil is a grey direwolf.', a: 'Stark' },
      { q: 'The Baratheon castle on the cliffs above Shipbreaker Bay.', a: 'Storm\'s End' },
      { q: 'The English actress who plays Sansa in the HBO series.', a: 'Sophie Turner' },
      { q: 'The scarred daughter of Stannis who teaches Davos his letters.', a: 'Shireen' },
      { q: 'The Martell seat in the far south of Westeros.', a: 'Sunspear' },
      { q: 'The Braavosi water dancer who teaches Arya her first sword lessons.', a: 'Syrio Forel', alt: ['Syrio'] },
      { q: 'The direwolf of Bran.', a: 'Summer' },
    ],
    T: [
      { q: 'The clever youngest Lannister sibling, mocked as the Imp.', a: 'Tyrion' },
      { q: 'The stern Lannister patriarch who quietly arranges the massacre at the Twins.', a: 'Tywin' },
      { q: 'The Greyjoy ward of Winterfell who is broken and renamed Reek.', a: 'Theon' },
      { q: 'The dragonlord house that ruled Westeros for nearly three centuries.', a: 'Targaryen' },
      { q: 'The Riverrun house whose sigil is a leaping silver trout.', a: 'Tully' },
      { q: 'The gentle youngest son of Cersei who takes the crown after Joffrey.', a: 'Tommen' },
      { q: 'The red priest who brings Beric back to life again and again.', a: 'Thoros', alt: ['Thoros of Myr'] },
      { q: 'The Frey castle of paired towers joined by a long bridge.', a: 'Twins', alt: ['The Twins'] },
      { q: 'The Sapphire Isle, home island of Brienne.', a: 'Tarth' },
      { q: 'The great river where Robert crushed Rhaegar with his war hammer.', a: 'Trident', alt: ['The Trident'] },
      { q: 'The ancient greenseer in the cave beneath the white tree who trains Bran.', a: 'Three-Eyed Raven', alt: ['The Three-Eyed Raven'] },
      { q: 'The house of Highgarden whose sigil is a golden rose.', a: 'Tyrell' },
    ],
    U: [
      { q: 'The elite eunuch slave soldiers trained in Astapor.', a: 'Unsullied', alt: ['The Unsullied'] },
      { q: 'The northern house of Last Hearth known for its enormous lords.', a: 'Umber' },
      { q: 'The three-word words of House Martell.', a: 'Unbowed, Unbent, Unbroken' },
      { q: 'The stern woman of the Faith who follows Cersei ringing a bell and chanting shame.', a: 'Unella' },
    ],
    V: [
      { q: 'The doom-struck peninsula where dragonlords once ruled, now smoking ruins.', a: 'Valyria' },
      { q: 'The rare rippled metal that never dulls, forged with spells now lost.', a: 'Valyrian steel' },
      { q: 'The bald eunuch spymaster known as the Spider.', a: 'Varys' },
      { q: 'The cruel elder brother of Daenerys who is crowned with molten gold.', a: 'Viserys' },
      { q: 'The cream and gold dragon later raised from the dead by the enemy of ice.', a: 'Viserion' },
      { q: 'The oldest of the Free Cities, split in two by a huge black stone bridge.', a: 'Volantis' },
      { q: 'The mountainous eastern region ruled from the Eyrie.', a: 'Vale', alt: ['The Vale'] },
      { q: 'The largest living dragon in House of the Dragon, mount of Prince Aemond.', a: 'Vhagar' },
    ],
    W: [
      { q: 'The ancient northern seat with hot springs running through its walls.', a: 'Winterfell' },
      { q: 'The icy humanoid creatures created long ago by the children of the forest.', a: 'White Walkers', alt: ['The White Walkers', 'Others'] },
      { q: 'The pale tree with red leaves and a carved watching face.', a: 'Weirwood' },
      { q: 'The continent that holds the Seven Kingdoms.', a: 'Westeros' },
      { q: 'The green alchemists\' substance that burns even on water.', a: 'Wildfire' },
      { q: 'The seven hundred foot barrier of ice that guards the north.', a: 'Wall', alt: ['The Wall'] },
      { q: 'The three-word words of House Stark.', a: 'Winter Is Coming' },
      { q: 'The last giant to fight for Jon at the battle for Winterfell.', a: 'Wun Wun' },
      { q: 'The great forest lying west of Winterfell.', a: 'Wolfswood', alt: ['The Wolfswood'] },
    ],
    X: [
      { q: 'The wealthy merchant of Qarth who courts Daenerys and then steals her dragons.', a: 'Xaro Xhoan Daxos', alt: ['Xaro'] },
    ],
    Y: [
      { q: 'The red-haired spearwife who tells Jon that he knows nothing.', a: 'Ygritte' },
      { q: 'The fierce sister of Theon and captain of her own longship.', a: 'Yara', alt: ['Yara Greyjoy', 'Asha'] },
      { q: 'The black brother who takes Arya north with a wagon of new recruits.', a: 'Yoren' },
      { q: 'The Yellow City of Slaver\'s Bay taken by Daenerys after Astapor.', a: 'Yunkai' },
    ],
  },
};
