import type { RawPack } from '../core/packs';

export const fandomFriendsPack: RawPack = {
  id: 'fandom-friends',
  name: 'Friends',
  description: 'Ten seasons of the coffee house gang: jobs, exes, pets, catchphrases and running gags.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '☕',
  accent: '#a16207',
  letters: {
    A: [
      { q: 'Surname of Phoebe\'s birth mother, who sells seashell frames out in Montauk.', a: 'Abbott' },
      { q: 'The fake surname Joey gives himself when he introduces himself as Ken.', a: 'Adams', alt: ['Ken Adams'] },
      { q: 'The legal route Monica and Chandler take to become parents after fertility trouble.', a: 'Adoption' },
      { q: 'The actor who played Parker, Phoebe\'s relentlessly upbeat boyfriend.', a: 'Alec Baldwin', alt: ['Baldwin'] },
      { q: 'The home economics teacher who marries Phoebe\'s much younger half brother.', a: 'Alice', alt: ['Alice Knight'] },
      { q: 'The Italian restaurant where Monica becomes head chef and battles a hostile kitchen.', a: 'Allesandro\'s' },
      { q: 'The old neighbour with a fake British accent whom the girls keep dodging, played by Jennifer Coolidge.', a: 'Amanda', alt: ['Amanda Buffamonteezi'] },
      { q: 'Rachel\'s shallow younger sister played by Christina Applegate.', a: 'Amy', alt: ['Amy Green'] },
      { q: 'The actress who played Rachel for all ten seasons (surname).', a: 'Aniston', alt: ['Jennifer Aniston'] },
      { q: 'The Pottery Barn purchase Rachel claims came from a flea market.', a: 'Apothecary table' },
      { q: 'The costume Ross wears to teach Ben about Hanukkah when no Santa suit is left.', a: 'Armadillo', alt: ['Holiday Armadillo'] },
      { q: 'Joey\'s profession, which involves an endless stream of auditions.', a: 'Actor' },
    ],
    B: [
      { q: 'The Sir Mix-a-Lot hit that makes infant Emma laugh.', a: 'Baby Got Back' },
      { q: 'The Scottish instrument Ross insists on playing badly at the wedding.', a: 'Bagpipes' },
      { q: 'The absurdly complicated game show Joey auditions to host, full of wicked wango cards.', a: 'Bamboozled' },
      { q: 'The Caribbean island where the gang travel for Ross\'s conference and it rains all week.', a: 'Barbados' },
      { q: 'The fiancé Rachel abandons at the altar in the pilot.', a: 'Barry', alt: ['Barry Farber'] },
      { q: 'Surname of the software millionaire Monica dated who trained to be an ultimate fighting champion.', a: 'Becker', alt: ['Pete Becker'] },
      { q: 'The name of Ross and Carol\'s son.', a: 'Ben' },
      { q: 'The comic actor who played Tommy, Rachel\'s date who screams at people.', a: 'Ben Stiller', alt: ['Stiller'] },
      { q: 'Chandler\'s surname.', a: 'Bing' },
      { q: 'The department store where Rachel works as an assistant buyer.', a: 'Bloomingdale\'s' },
      { q: 'Ross\'s girlfriend, set up by Phoebe, who shaves her head completely bald.', a: 'Bonnie' },
      { q: 'The gaudy gold friendship jewellery Joey buys Chandler, who cannot stand it.', a: 'Bracelet' },
      { q: 'The actor, married to Jennifer Aniston at the time, who guest starred as a former classmate of Rachel.', a: 'Brad Pitt', alt: ['Pitt'] },
      { q: 'The Die Hard star who played the intimidating father of Ross\'s young girlfriend.', a: 'Bruce Willis', alt: ['Willis'] },
      { q: 'Phoebe\'s surname before she married.', a: 'Buffay' },
      { q: 'Surname of the moustachioed eye doctor Monica dated, played by Tom Selleck.', a: 'Burke', alt: ['Richard Burke'] },
    ],
    C: [
      { q: 'Ross\'s first wife, who left him for a woman and later bore his son.', a: 'Carol', alt: ['Carol Willick'] },
      { q: 'The hairless pet Rachel buys for a thousand dollars and then sells to Gunther.', a: 'Cat', alt: ['Sphynx cat'] },
      { q: 'The coffee house where the six friends spend most of their time.', a: 'Central Perk' },
      { q: 'Which friend works in statistical analysis and cannot stop cracking jokes?', a: 'Chandler', alt: ['Chandler Bing'] },
      { q: 'The garbled name printed on Chandler\'s magazine subscription label.', a: 'Chanandler Bong', alt: ['Ms. Chanandler Bong'] },
      { q: 'Chandler\'s estranged parent, a Las Vegas drag star.', a: 'Charles Bing', alt: ['Charles'] },
      { q: 'First name of the palaeontologist colleague, played by Aisha Tyler, whom both Joey and Ross date.', a: 'Charlie', alt: ['Charlie Wheeler'] },
      { q: 'The stolen dessert Rachel and Chandler eat off the hallway floor.', a: 'Cheesecake' },
      { q: 'Monica\'s profession throughout the series.', a: 'Chef' },
      { q: 'The baby bird Joey buys as a pet, later paired with a duck.', a: 'Chick' },
      { q: 'The copy shop girl Ross sleeps with on the night of the break.', a: 'Chloe' },
      { q: 'The junior advertising job Chandler starts as an unpaid intern before being hired.', a: 'Copywriter' },
      { q: 'The actress who played Monica (full name).', a: 'Courteney Cox', alt: ['Cox'] },
      { q: 'Co creator of the series with Marta Kauffman (surname).', a: 'Crane', alt: ['David Crane'] },
      { q: 'The name Mike legally adopts in protest at his wife\'s ridiculous new one.', a: 'Crap Bag' },
    ],
    D: [
      { q: 'The scientist Phoebe loves, played by Hank Azaria, who leaves for Minsk.', a: 'David' },
      { q: 'The actor who played Ross (full name).', a: 'David Schwimmer', alt: ['Schwimmer'] },
      { q: 'The long running soap opera where Joey plays a neurosurgeon.', a: 'Days of Our Lives' },
      { q: 'The fifties themed eatery where Monica waits tables in a blonde wig and roller skates.', a: 'Diner', alt: ['Moondance Diner'] },
      { q: 'The extinct creatures Ross studies and lectures about.', a: 'Dinosaurs' },
      { q: 'The legal ending Ross goes through three separate times.', a: 'Divorce' },
      { q: 'The elaborate toy home Monica inherits and will not let Phoebe play with.', a: 'Dollhouse' },
      { q: 'Chandler\'s boss at the data company, notorious for spanking his staff.', a: 'Doug' },
      { q: 'The name of the brain surgeon character Joey plays on daytime television.', a: 'Drake Ramoray', alt: ['Dr. Drake Ramoray'] },
      { q: 'The white waterfowl Joey keeps beside his baby bird.', a: 'Duck' },
      { q: 'The gay Canadian ice dancer Phoebe married so he could stay in the country.', a: 'Duncan' },
    ],
    E: [
      { q: 'The unsettling roommate Chandler takes in after Joey moves out, who refuses to leave.', a: 'Eddie', alt: ['Eddie Menuek'] },
      { q: 'The number of pages, front and back, in Rachel\'s furious letter to Ross.', a: 'Eighteen' },
      { q: 'The number of towel categories Monica keeps, by Rachel\'s count.', a: 'Eleven' },
      { q: 'Ross\'s student girlfriend, whose father is played by Bruce Willis.', a: 'Elizabeth', alt: ['Elizabeth Stevens'] },
      { q: 'The English woman Ross marries in London.', a: 'Emily', alt: ['Emily Waltham'] },
      { q: 'The name of Ross and Rachel\'s daughter.', a: 'Emma' },
      { q: 'The award the show won for outstanding comedy series in 2002.', a: 'Emmy' },
      { q: 'The episode title word for the trivia contest that costs Monica and Rachel their apartment.', a: 'Embryos' },
      { q: 'Ursula\'s fiancé, played by Sean Penn, who falls for Phoebe instead.', a: 'Eric' },
      { q: 'The pregnant young woman who chooses Monica and Chandler to raise her twins.', a: 'Erica' },
      { q: 'Joey\'s chain smoking talent agent.', a: 'Estelle', alt: ['Estelle Leonard'] },
      { q: 'The teenager Monica dates before discovering he is only seventeen.', a: 'Ethan' },
    ],
    F: [
      { q: 'The industry Rachel builds her career in after quitting the coffee house.', a: 'Fashion' },
      { q: 'The tasselled hat Monica adds to the bird on her head.', a: 'Fez' },
      { q: 'The table game in Joey and Chandler\'s apartment that swallows their pets.', a: 'Foosball' },
      { q: 'The Thanksgiving game the friends play for a troll doll trophy.', a: 'Football' },
      { q: 'Phoebe\'s half brother, who marries his former home economics teacher.', a: 'Frank Buffay Jr.', alt: ['Frank'] },
      { q: 'Where Joey stores frightening books so he can feel safe.', a: 'Freezer' },
      { q: 'The one word title of the series.', a: 'Friends' },
      { q: 'Monica\'s boyfriend nicknamed for his liveliness, which turns out to be drink.', a: 'Fun Bobby' },
    ],
    G: [
      { q: 'Rachel\'s charming rival at work during her maternity leave, played by Dermot Mulroney.', a: 'Gavin' },
      { q: 'The surname shared by Monica and Ross.', a: 'Geller' },
      { q: 'The troll doll trophy Ross and Monica compete for every Thanksgiving.', a: 'Geller Cup' },
      { q: 'Chandler\'s girlfriend with a prosthetic leg, played by Sherilyn Fenn.', a: 'Ginger' },
      { q: 'The lumpy art piece Phoebe gives Monica, with a torso bursting out of the frame.', a: 'Gladys' },
      { q: 'Rachel\'s maiden surname.', a: 'Green' },
      { q: 'The instrument Phoebe strums while performing her own songs.', a: 'Guitar' },
      { q: 'The item Chandler nervously accepts in an elevator, calling it perfection.', a: 'Gum' },
      { q: 'The bleach blond coffee house manager quietly in love with Rachel.', a: 'Gunther' },
    ],
    H: [
      { q: 'The Las Vegas act Joey plans with a stranger whose palms match his own exactly.', a: 'Hand twin' },
      { q: 'The Jewish festival Ross dresses up as an animal to explain to Ben.', a: 'Hanukkah' },
      { q: 'Surname of the piano playing man Phoebe marries, played by Paul Rudd.', a: 'Hannigan', alt: ['Mike Hannigan'] },
      { q: 'The cranky downstairs neighbour who bangs his broom on the ceiling.', a: 'Heckles', alt: ['Mr. Heckles'] },
      { q: 'The stage name used by Chandler\'s father in his Las Vegas show.', a: 'Helena Handbasket' },
      { q: 'Joey\'s signature three word pick up line.', a: 'How you doin', alt: ['How you doin?'] },
      { q: 'Joey\'s beloved bedtime penguin.', a: 'Hugsy' },
    ],
    I: [
      { q: 'The Japanese lipstick for men that Joey advertises in a commercial.', a: 'Ichiban' },
      { q: 'The aunt who teaches the women to play cards for money.', a: 'Iris', alt: ['Aunt Iris'] },
      { q: 'The upscale restaurant where Monica works as a sous chef in season one.', a: 'Iridium' },
      { q: 'The country Rachel\'s boyfriend Paolo comes from.', a: 'Italy' },
    ],
    J: [
      { q: 'First name of Monica and Ross\'s father, played by Elliott Gould.', a: 'Jack', alt: ['Jack Geller'] },
      { q: 'The actor who played the coffee house manager for a decade.', a: 'James Michael Tyler', alt: ['Tyler'] },
      { q: 'Chandler\'s nasal voiced on and off girlfriend, famous for shrieking Oh My God.', a: 'Janice', alt: ['Janice Litman'] },
      { q: 'The Australian dancer who briefly rooms with Joey and cannot stand Monica and Chandler.', a: 'Janine' },
      { q: 'The stinging sea creature behind a mortifying beach story.', a: 'Jellyfish' },
      { q: 'Rachel\'s spoiled sister played by Reese Witherspoon.', a: 'Jill', alt: ['Jill Green'] },
      { q: 'Rachel\'s domineering boss in the buying department who ties Chandler to a chair.', a: 'Joanna' },
      { q: 'Which friend refuses to share his food?', a: 'Joey', alt: ['Joey Tribbiani'] },
      { q: 'The client Rachel dates, played by Tate Donovan, whom she frightens with a fake proposal.', a: 'Joshua' },
      { q: 'First name of Monica and Ross\'s critical mother, played by Christina Pickles.', a: 'Judy', alt: ['Judy Geller'] },
      { q: 'The movie star who played Susie, a classmate who strands Chandler in a bathroom stall.', a: 'Julia Roberts', alt: ['Roberts'] },
      { q: 'The colleague Ross brings back from a dig in China, complicating Rachel\'s confession.', a: 'Julie' },
    ],
    K: [
      { q: 'The film actress cast as Chandler\'s drag performer parent.', a: 'Kathleen Turner', alt: ['Turner'] },
      { q: 'Joey\'s girlfriend whom Chandler kisses, causing a rift between the roommates.', a: 'Kathy' },
      { q: 'Co creator of the series with David Crane (surname).', a: 'Kauffman', alt: ['Marta Kauffman'] },
      { q: 'Chandler\'s old roommate who dated Monica and then vanished from the group.', a: 'Kip' },
      { q: 'The actress who played Phoebe (surname).', a: 'Kudrow', alt: ['Lisa Kudrow'] },
    ],
    L: [
      { q: 'The plastic coated celebrity roster Ross keeps, holding five allowed names.', a: 'Laminated list' },
      { q: 'The profession Mike abandons in order to play piano.', a: 'Lawyer' },
      { q: 'The trousers Ross cannot pull back up on a date after using lotion and powder.', a: 'Leather pants' },
      { q: 'The actor who played Joey (surname).', a: 'LeBlanc', alt: ['Matt LeBlanc'] },
      { q: 'First name of Rachel\'s short tempered doctor father.', a: 'Leonard', alt: ['Dr. Leonard Green'] },
      { q: 'The woman Phoebe grew up believing was her mother, who took her own life.', a: 'Lily' },
      { q: 'The sea creatures Phoebe says mate for life, comparing them to Ross and Rachel.', a: 'Lobsters' },
      { q: 'The city where Ross\'s second wedding takes place and Monica and Chandler first sleep together.', a: 'London' },
      { q: 'The luxury French label that offers Rachel a job abroad.', a: 'Louis Vuitton' },
    ],
    M: [
      { q: 'The short lived cop show in which Joey stars beside a talking robot.', a: 'Mac and C.H.E.E.S.E.', alt: ['Mac and Cheese'] },
      { q: 'The capuchin Ross adopts as a pet and later gives up.', a: 'Marcel' },
      { q: 'Phoebe\'s main profession, practised at a spa and on her friends.', a: 'Massage therapist', alt: ['Masseuse'] },
      { q: 'Joey\'s imaginary childhood friend, a space cowboy.', a: 'Maurice' },
      { q: 'The former sorority sister, played by Winona Ryder, who once kissed Rachel.', a: 'Melissa' },
      { q: 'Rachel\'s maid of honour who ends up marrying her ex fiancé.', a: 'Mindy', alt: ['Mindy Hunter'] },
      { q: 'The fake cocoa product Monica is hired to invent recipes for.', a: 'Mockolate' },
      { q: 'Ross\'s name for the gravy soaked middle bread slice of his Thanksgiving lunch.', a: 'Moist maker' },
      { q: 'The woman Ross dates while Rachel is pregnant, who sends holiday cards far too soon.', a: 'Mona' },
      { q: 'Which friend is the obsessively tidy and fiercely competitive sister of Ross?', a: 'Monica', alt: ['Monica Geller'] },
      { q: 'Joey\'s mangled phrase for an irrelevant argument, which he says is like a cow\'s opinion.', a: 'Moo point' },
      { q: 'Surname of the childhood classmate who takes revenge on Chandler in a restaurant bathroom.', a: 'Moss', alt: ['Susie Moss'] },
      { q: 'The New York institution where Ross works before he becomes a professor.', a: 'Museum of Natural History' },
    ],
    N: [
      { q: 'The family name for the grandmother who dies twice in a single episode.', a: 'Nana' },
      { q: 'The child care role Ross fires Sandy from out of pure jealousy.', a: 'Nanny' },
      { q: 'The American network that aired the show from 1994 to 2004.', a: 'NBC' },
      { q: 'The city where the series is set.', a: 'New York' },
      { q: 'Chandler\'s mother, a famous erotic novelist played by Morgan Fairchild.', a: 'Nora Bing', alt: ['Nora'] },
      { q: 'Chandler\'s own word for his extra third nipple.', a: 'Nubbin' },
    ],
    O: [
      { q: 'The state Erica travels from to have her babies in New York.', a: 'Ohio' },
      { q: 'The medical specialty of Richard, Monica\'s much older boyfriend.', a: 'Ophthalmologist' },
      { q: 'The bright piece of furniture the group always claims at the coffee house.', a: 'Orange couch' },
      { q: 'The dental profession of Rachel\'s runaway fiancé.', a: 'Orthodontist' },
      { q: 'The virus disaster film sequel Ross\'s monkey stars in after leaving the zoo.', a: 'Outbreak 2', alt: ['Outbreak'] },
    ],
    P: [
      { q: 'Ross\'s profession, studying fossils for a living.', a: 'Paleontologist', alt: ['Palaeontologist'] },
      { q: 'Rachel\'s Italian boyfriend who makes a pass at Phoebe during a massage.', a: 'Paolo' },
      { q: 'The city where Rachel is offered a fashion job in the final season.', a: 'Paris' },
      { q: 'The actor who played Chandler (surname).', a: 'Perry', alt: ['Matthew Perry'] },
      { q: 'Which friend has a twin sister and sings badly at the coffee house?', a: 'Phoebe', alt: ['Phoebe Buffay'] },
      { q: 'The word Ross screams over and over while carrying a sofa up a stairwell.', a: 'Pivot' },
      { q: 'The card game the women learn so that they can beat the men.', a: 'Poker' },
      { q: 'The German sports car Joey looks after and wears branded clothing for.', a: 'Porsche' },
      { q: 'The chain store whose furniture Rachel hides from Phoebe, who hates mass production.', a: 'Pottery Barn' },
      { q: 'The absurd new legal name Phoebe chooses for herself after marrying.', a: 'Princess Consuela Banana Hammock' },
      { q: 'The old recording of Rachel\'s high school dance that finally makes her kiss Ross.', a: 'Prom video' },
      { q: 'The colour of the walls in Monica\'s apartment.', a: 'Purple' },
      { q: 'The word association game show Joey appears on with Donny Osmond.', a: 'Pyramid' },
    ],
    Q: [
      { q: 'The New York borough where Joey\'s large Italian family lives.', a: 'Queens' },
      { q: 'Ross\'s homemade game of questions about the friends, played for very high stakes.', a: 'Quiz' },
    ],
    R: [
      { q: 'Which friend arrives in a soaked wedding dress in the very first episode?', a: 'Rachel', alt: ['Rachel Green'] },
      { q: 'The fashion house Rachel joins after leaving the department store.', a: 'Ralph Lauren' },
      { q: 'The fake identity Phoebe uses whenever she needs an alias.', a: 'Regina Phalange' },
      { q: 'The name Joey gives his beloved recliner.', a: 'Rosita' },
      { q: 'Which friend has been married to Carol, Emily and Rachel?', a: 'Ross', alt: ['Ross Geller'] },
      { q: 'The rough English sport Ross plays to impress Emily\'s friends.', a: 'Rugby' },
      { q: 'Rachel\'s dentist boyfriend who looks and sounds suspiciously like her ex.', a: 'Russ' },
      { q: 'The name given to the layered hairstyle copied worldwide in the mid nineties.', a: 'The Rachel' },
      { q: 'The band that recorded the show\'s theme song.', a: 'The Rembrandts', alt: ['Rembrandts'] },
    ],
    S: [
      { q: 'First name of Rachel\'s mother, played by Marlo Thomas.', a: 'Sandra', alt: ['Sandra Green'] },
      { q: 'The lunch Ross\'s boss eats, causing him to snap and take a leave of absence.', a: 'Sandwich' },
      { q: 'The sensitive male carer of Emma, played by Freddie Prinze Jr, whom Ross dismisses.', a: 'Sandy' },
      { q: 'The number Monica emphasises while teaching Chandler about erogenous zones.', a: 'Seven' },
      { q: 'Joey has seven of these siblings, one of them named Mary Angela.', a: 'Sisters' },
      { q: 'Phoebe\'s best known composition, about a pungent pet.', a: 'Smelly Cat' },
      { q: 'The salon treatment that leaves Ross very dark in front and pale behind.', a: 'Spray tan' },
      { q: 'The data field Chandler works in for years, a job nobody can explain.', a: 'Statistical analysis' },
      { q: 'The rock star whose son attends the school Ross wants Ben to get into.', a: 'Sting' },
      { q: 'The job Danny DeVito\'s character performs at Phoebe\'s bachelorette party.', a: 'Stripper' },
      { q: 'Treeger\'s role in the apartment building.', a: 'Superintendent' },
      { q: 'Carol\'s partner, who helps raise Ben.', a: 'Susan', alt: ['Susan Bunch'] },
      { q: 'The Stephen King novel Joey finds so frightening that he hides it in the freezer.', a: 'The Shining' },
    ],
    T: [
      { q: 'Rachel\'s much younger assistant, hired mostly because she fancies him.', a: 'Tag', alt: ['Tag Jones'] },
      { q: 'The permanent ink Rachel gets on her hip while Phoebe backs out.', a: 'Tattoo' },
      { q: 'The cosmetic dental job Ross overdoes, leaving him glowing under black light.', a: 'Teeth whitening' },
      { q: 'The number of seasons the series ran.', a: 'Ten' },
      { q: 'The November holiday the show marks with a special episode nearly every season.', a: 'Thanksgiving' },
      { q: 'The name Ross and Monica give the dance they perform hoping to get on television.', a: 'The Routine' },
      { q: 'The building superintendent Rachel teaches to dance for his sister\'s wedding.', a: 'Treeger', alt: ['Mr. Treeger'] },
      { q: 'Joey\'s Italian American surname.', a: 'Tribbiani' },
      { q: 'The layered English dessert Rachel ruins by adding beef and peas.', a: 'Trifle' },
      { q: 'The city Chandler\'s company transfers him to, where he eventually quits.', a: 'Tulsa' },
      { q: 'The Thanksgiving bird Monica wears on her head to make Chandler laugh.', a: 'Turkey' },
      { q: 'The number on Monica\'s apartment door after the renumbering from five.', a: 'Twenty' },
    ],
    U: [
      { q: 'The nickname of the neighbour across the courtyard whose apartment Ross eventually takes over.', a: 'Ugly Naked Guy' },
      { q: 'The prop each cast member holds while dancing in the fountain of the opening titles.', a: 'Umbrella' },
      { q: 'Ross\'s mistaken word for a state of total awareness, borrowed from a sushi menu.', a: 'Unagi' },
      { q: 'Phoebe\'s identical twin, a rude waitress who becomes an adult film star.', a: 'Ursula' },
    ],
    V: [
      { q: 'The action star Monica and Rachel both chase on a film set in Central Park (surname).', a: 'Van Damme', alt: ['Jean-Claude Van Damme'] },
      { q: 'The gambling city where Ross and Rachel drunkenly marry.', a: 'Vegas', alt: ['Las Vegas'] },
    ],
    W: [
      { q: 'Rachel\'s job at the coffee house before she moves into fashion.', a: 'Waitress' },
      { q: 'Emily\'s English family surname.', a: 'Waltham' },
      { q: 'The garment Monica wears around the apartment for fun before her engagement.', a: 'Wedding dress' },
      { q: 'Surname of the palaeontologist that Ross and Joey both date.', a: 'Wheeler' },
      { q: 'First name of the Brad Pitt character who founded a club devoted to hating Rachel.', a: 'Will', alt: ['Will Colbert'] },
      { q: 'Carol\'s surname, later hyphenated with her partner\'s.', a: 'Willick' },
    ],
    Y: [
      { q: 'The distant country Chandler pretends to move to in order to escape a girlfriend.', a: 'Yemen' },
      { q: 'Monica\'s nickname for the hairy new neighbour who startles her in the hallway.', a: 'Yeti' },
    ],
    Z: [
      { q: 'The kind of animal park in San Diego where Ross sends his monkey.', a: 'Zoo' },
    ],
  },
};
