import type { RawPack } from '../core/packs';

export const fandomZeldaPack: RawPack = {
  id: 'fandom-zelda',
  name: 'The Legend of Zelda',
  description: 'Heroes, races, relics and dungeons from the whole Hyrule saga.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🗡️',
  accent: '#047857',
  letters: {
    A: [
      { q: 'Link\'s younger sister, carried off by a giant masked bird at the start of The Wind Waker.', a: 'Aryll' },
      { q: 'The bug-loving woman in Twilight Princess who pays rupees for golden insects.', a: 'Agitha' },
      { q: 'The keeper of the Stock Pot Inn in Clock Town, who is engaged to Kafei.', a: 'Anju' },
      { q: 'The Skyward Sword dungeon flooded inside a giant flower, home to the boss Koloktos.', a: 'Ancient Cistern' },
      { q: 'The Twilight Princess desert dungeon built as a Gerudo prison and guarded by Stallord.', a: 'Arbiter\'s Grounds', alt: ['Arbiters Grounds'] },
      { q: 'The northeastern region of Breath of the Wild holding a ruined citadel and an ancient tech lab.', a: 'Akkala' },
      { q: 'The sword-carrying member of the Twilight Princess resistance who wears a heavy fur coat.', a: 'Ashei' },
      { q: 'Nintendo veteran Eiji who took over directing the series after Ocarina of Time (surname).', a: 'Aonuma' },
    ],
    B: [
      { q: 'The traveling merchant who hauls an enormous backpack shop around Hyrule.', a: 'Beedle' },
      { q: 'The mouse-shaped explosive that scurries along walls and ceilings.', a: 'Bombchu', alt: ['Bombchus'] },
      { q: 'The one-eyed phantom that pounds a giant drum with disembodied hands in the Shadow Temple.', a: 'Bongo Bongo' },
      { q: 'The glowing blue rabbit of Breath of the Wild that scatters rupees when struck.', a: 'Blupee' },
      { q: 'The common pig-faced red monster grunt of Breath of the Wild.', a: 'Bokoblin', alt: ['Bokoblins'] },
      { q: 'The easygoing construction boss who helps Link raise Tarrey Town.', a: 'Bolson' },
      { q: 'The armored Lokomo knight who serves Malladus in Spirit Tracks.', a: 'Byrne' },
      { q: 'The final foe of Phantom Hourglass, a demon that possesses the Ocean King.', a: 'Bellum' },
      { q: 'The ancient weapon Zelda uses to fire radiant arrows at the climax of Breath of the Wild.', a: 'Bow of Light' },
      { q: 'The crimson night event in Breath of the Wild that revives every defeated monster.', a: 'Blood Moon' },
    ],
    C: [
      { q: 'The chicken-like bird that summons a furious swarm if you strike it too often.', a: 'Cucco', alt: ['Cuccos'] },
      { q: 'The Ordon boy who idolizes Link and is carried off by King Bulblin.', a: 'Colin' },
      { q: 'The four heroes chosen to pilot the Divine Beasts a century before Breath of the Wild.', a: 'Champions' },
      { q: 'The swirling corrupted form the ancient evil takes above Hyrule Castle in Breath of the Wild.', a: 'Calamity Ganon' },
      { q: 'The Twilight Princess gauntlet of fifty underground rooms that ends in a fairy\'s blessing.', a: 'Cave of Ordeals' },
      { q: 'Romani\'s older sister, who drives the milk wagon to Clock Town.', a: 'Cremia' },
      { q: 'The spirit of courage who travels with Link as a fairy in Phantom Hourglass.', a: 'Ciela' },
      { q: 'The pink-haired spirit near Kakariko who upgrades Link\'s outfits in Breath of the Wild.', a: 'Cotera' },
    ],
    D: [
      { q: 'The Goron patriarch of Ocarina of Time who breaks into a dance when he hears Saria\'s Song.', a: 'Darunia' },
      { q: 'The Goron Champion who piloted Vah Rudania.', a: 'Daruk' },
      { q: 'The ancient guardian of Kokiri Forest who gives Link his very first quest.', a: 'Deku Tree', alt: ['Great Deku Tree'] },
      { q: 'The goddess of power among the three golden sisters.', a: 'Din' },
      { q: 'The shadowy doppelganger the hero duels inside the Water Temple.', a: 'Dark Link' },
      { q: 'The final foe of Skyward Sword, the origin of all the evil in the series.', a: 'Demise' },
      { q: 'The Ocarina of Time cave dungeon sealed behind a boulder on the trail up Death Mountain.', a: 'Dodongo\'s Cavern', alt: ['Dodongos Cavern'] },
      { q: 'The red spell that wraps Link in an expanding ring of flame in Ocarina of Time.', a: 'Din\'s Fire', alt: ['Dins Fire'] },
      { q: 'The hunchbacked gravekeeper of Kakariko who digs for prizes at night.', a: 'Dampe', alt: ['Dampé'] },
      { q: 'Each of the four giant machines the Sheikah built to fight the Calamity, piloted by Champions.', a: 'Divine Beast', alt: ['Divine Beasts'] },
      { q: 'The red fire dragon that circles the Eldin volcano in Breath of the Wild.', a: 'Dinraal' },
      { q: 'The true name of the talking boat that guides Link across the Great Sea.', a: 'Daphnes', alt: ['King Daphnes'] },
    ],
    E: [
      { q: 'Link\'s loyal chestnut mare, first named in Ocarina of Time.', a: 'Epona' },
      { q: 'The volcanic region of Breath of the Wild that contains Goron City.', a: 'Eldin' },
      { q: 'The talking hat who becomes Link\'s sword in The Minish Cap.', a: 'Ezlo' },
      { q: 'The Breath of the Wild trial that strips all your gear and makes you scavenge on a lone shore.', a: 'Eventide Island', alt: ['Eventide'] },
      { q: 'The mournful Majora\'s Mask melody that leaves a lifeless statue of Link behind.', a: 'Elegy of Emptiness' },
      { q: 'The fiery pellet fired from a slingshot to light torches in the Oracle games.', a: 'Ember Seed', alt: ['Ember Seeds'] },
    ],
    F: [
      { q: 'The goddess of courage among the three golden sisters.', a: 'Farore' },
      { q: 'The blue spirit who dwells inside the holy blade and guides Link in Skyward Sword.', a: 'Fi' },
      { q: 'The humid southern jungle region of Breath of the Wild, famous for its constant rain.', a: 'Faron' },
      { q: 'The towering white-haired war god form Link takes with a certain mask in Majora\'s Mask.', a: 'Fierce Deity' },
      { q: 'The first adult dungeon of Ocarina of Time, where Saria awakens as a sage.', a: 'Forest Temple' },
      { q: 'The Ocarina of Time dungeon inside the crater of Death Mountain, guarded by Volvagia.', a: 'Fire Temple' },
      { q: 'The dark helmet artifact of the Twili, rebuilt from three shards in Twilight Princess.', a: 'Fused Shadow', alt: ['Fused Shadows'] },
      { q: 'The great tree home of the Koroks in The Wind Waker, where their guardian sprout grows.', a: 'Forest Haven' },
      { q: 'The Korok sage of Wind whose spirit lingers in a temple in The Wind Waker.', a: 'Fado' },
      { q: 'The circular healing pool guarded by a giant spirit who grants Link upgrades.', a: 'Fairy Fountain' },
    ],
    G: [
      { q: 'The desert king of thieves who covets the Triforce.', a: 'Ganondorf' },
      { q: 'The monstrous boar-beast form the great evil takes.', a: 'Ganon' },
      { q: 'The all-female desert thief race led by a chief.', a: 'Gerudo' },
      { q: 'The rock-eating mountain race whose members curl up to roll.', a: 'Goron', alt: ['Gorons'] },
      { q: 'The one-eyed armored spider that lurks at the bottom of the Deku Tree.', a: 'Gohma' },
      { q: 'The pompadoured bully at the Skyloft knight academy who steals a Loftwing.', a: 'Groose' },
      { q: 'The bandaged mummy monster that shrieks in Ikana and out in the desert.', a: 'Gibdo', alt: ['Gibdos'] },
      { q: 'The six-legged ancient Sheikah machine with a tracking laser in Breath of the Wild.', a: 'Guardian', alt: ['Guardians'] },
      { q: 'The flamboyant white-haired demon lord who is the living spirit of Demise\'s blade.', a: 'Ghirahim' },
      { q: 'The huge masked fish boss of the coastal temple in Majora\'s Mask.', a: 'Gyorg' },
      { q: 'The northern coastal region of Termina, home to the Zora and their temple.', a: 'Great Bay' },
      { q: 'The Twilight Princess item that whips up whirlwinds and grabs distant objects.', a: 'Gale Boomerang' },
      { q: 'The holy blade that Fi inhabits, later reforged into the weapon that seals Demise.', a: 'Goddess Sword' },
      { q: 'The talking rock with a single eye that offers hints when it is struck.', a: 'Gossip Stone' },
    ],
    H: [
      { q: 'The kingdom in which most of the series takes place.', a: 'Hyrule' },
      { q: 'The pointed-eared human race that Link belongs to.', a: 'Hylian', alt: ['Hylians'] },
      { q: 'The goddess who took mortal form and was reborn as Zelda in Skyward Sword.', a: 'Hylia' },
      { q: 'The giant Korok who expands Link\'s weapon slots in exchange for seeds.', a: 'Hestu' },
      { q: 'The chain-and-claw tool used to grapple across gaps in Ocarina of Time.', a: 'Hookshot' },
      { q: 'The blue metal guard bearing the royal family crest, unbreakable in Breath of the Wild.', a: 'Hylian Shield' },
      { q: 'The besieged royal stronghold at the heart of the kingdom, wrapped in malice in Breath of the Wild.', a: 'Hyrule Castle' },
      { q: 'The giant masked bird boss of The Wind Waker who abducts Aryll.', a: 'Helmaroc King' },
      { q: 'The 2011 official compendium book that published the first canonical timeline for the series.', a: 'Hyrule Historia' },
      { q: 'The wide central plain surrounding the royal castle in Ocarina of Time.', a: 'Hyrule Field' },
    ],
    I: [
      { q: 'The Sheikah attendant who has advised the royal family across many games.', a: 'Impa' },
      { q: 'The Ordon girl who tends Epona and loses her memory in Twilight Princess.', a: 'Ilia' },
      { q: 'The heavy footwear that lets Link sink and walk along the bottom underwater.', a: 'Iron Boots' },
      { q: 'The frozen Ocarina of Time cave in Zora\'s Domain where Link claims the heavy boots.', a: 'Ice Cavern' },
      { q: 'The haunted eastern valley of Termina, ruled by an undead king in a stone castle.', a: 'Ikana Canyon', alt: ['Ikana'] },
      { q: 'The elderly descendant of the shadow tribe in Twilight Princess who lives in a hidden village.', a: 'Impaz' },
    ],
    J: [
      { q: 'The giant whale-like fish deity of the Zora that swallows Link in Ocarina of Time.', a: 'Jabu-Jabu', alt: ['Jabu Jabu', 'Lord Jabu-Jabu'] },
      { q: 'The huge water spirit hiding behind the rocks near Link\'s home in The Wind Waker.', a: 'Jabun' },
      { q: 'The man in Twilight Princess who is cursed into a golden cat and trades ghost souls.', a: 'Jovani' },
    ],
    K: [
      { q: 'The tiny leaf-faced forest folk of Breath of the Wild who hide seeds all over the map.', a: 'Korok', alt: ['Koroks'] },
      { q: 'The green-clad child race of the forest in Ocarina of Time.', a: 'Kokiri' },
      { q: 'The hillside village below Death Mountain that the shadow tribe founded.', a: 'Kakariko' },
      { q: 'The masked young man in Majora\'s Mask who is turned into a Deku Scrub and hides in Clock Town.', a: 'Kafei' },
      { q: 'The mask-wearing oddball who buys monster parts from a balloon shop in Breath of the Wild.', a: 'Kilton' },
      { q: 'The leader of the Yiga Clan, beaten in a sand pit beneath the desert.', a: 'Kohga', alt: ['Master Kohga'] },
      { q: 'The accordion-playing Rito bard of Breath of the Wild who sings his late teacher\'s verses.', a: 'Kass' },
      { q: 'The bat enemy that flutters through nearly every dungeon in the series.', a: 'Keese' },
      { q: 'The little blade a child hero pulls from a chest in the forest at the start of Ocarina of Time.', a: 'Kokiri Sword' },
      { q: 'The elder desert witch who wields ice, sister to Koume.', a: 'Kotake' },
      { q: 'The red-clad desert witch who wields flame, sister to Kotake.', a: 'Koume' },
      { q: 'The shy plant-like creatures of Faron Woods in Skyward Sword.', a: 'Kikwi', alt: ['Kikwis'] },
      { q: 'The dreamed-up land of Link\'s Awakening, which vanishes when its dreamer finally wakes.', a: 'Koholint', alt: ['Koholint Island'] },
    ],
    L: [
      { q: 'The green-clad silent hero of the series.', a: 'Link' },
      { q: 'The eastern province of Hyrule whose desert holds a timeshift mine in Skyward Sword.', a: 'Lanayru' },
      { q: 'The great red bird that Link rides through the sky in Skyward Sword.', a: 'Loftwing' },
      { q: 'Talon\'s farm, home to Epona and a thriving milk business.', a: 'Lon Lon Ranch' },
      { q: 'The maned centaur-like beast that is among the toughest foes in Breath of the Wild.', a: 'Lynel', alt: ['Lynels'] },
      { q: 'The greedy sea captain who sails Link around the world of Phantom Hourglass.', a: 'Linebeck' },
      { q: 'The magnifying item that reveals invisible walls and ghosts in Ocarina of Time.', a: 'Lens of Truth' },
      { q: 'The tropical fishing settlement on the southeast coast of Breath of the Wild.', a: 'Lurelin Village', alt: ['Lurelin'] },
      { q: 'The Zora singer of the coastal region whose eggs Link recovers in Majora\'s Mask.', a: 'Lulu' },
      { q: 'The land in which Oracle of Ages takes place.', a: 'Labrynna' },
    ],
    M: [
      { q: 'The cursed heart-shaped relic worn by a Skull Kid that drags the moon down on Termina.', a: 'Majora\'s Mask', alt: ['Majoras Mask', 'Majora'] },
      { q: 'Talon\'s daughter, who sings her mother\'s melody out at the farm.', a: 'Malon' },
      { q: 'The rude Kokiri boy who blocks the path to the Great Deku Tree.', a: 'Mido' },
      { q: 'The Twili imp who rides on the back of a blue-furred wolf.', a: 'Midna' },
      { q: 'The Rito attendant who becomes the Sage of Earth in The Wind Waker.', a: 'Medli' },
      { q: 'The Korok who becomes the Sage of Wind in The Wind Waker.', a: 'Makar' },
      { q: 'The girl on Koholint who sings the Ballad of the Wind Fish.', a: 'Marin' },
      { q: 'The giant sand-swimming worm boss of the Wind Temple in The Wind Waker.', a: 'Molgera' },
      { q: 'The Zora Champion who piloted Vah Ruta and is Sidon\'s older sister.', a: 'Mipha' },
      { q: 'The pig-faced spear-carrying brute, a bigger cousin of the Bokoblin.', a: 'Moblin', alt: ['Moblins'] },
      { q: 'The shattered artifact Link rebuilds at the Arbiter\'s Grounds to reach Zant\'s realm.', a: 'Mirror of Twilight' },
      { q: 'The enchanted blue plate in Twilight Princess that drains rupees while it is worn.', a: 'Magic Armor' },
      { q: 'The tiny hidden people who leave gifts for children and are seen only by the pure of heart.', a: 'Minish', alt: ['Picori'] },
      { q: 'The legendary blade that repels evil, resting in a sanctuary in Castle Town.', a: 'Master Sword' },
    ],
    N: [
      { q: 'The desert thief who becomes the Sage of Spirit in Ocarina of Time.', a: 'Nabooru' },
      { q: 'The fairy who follows the child hero and shouts for his attention in Ocarina of Time.', a: 'Navi' },
      { q: 'The goddess of wisdom among the three golden sisters.', a: 'Nayru' },
      { q: 'The blue spell in Ocarina of Time that surrounds Link in a protective crystal barrier.', a: 'Nayru\'s Love', alt: ['Nayrus Love'] },
      { q: 'The console on which Ocarina of Time debuted in 1998.', a: 'Nintendo 64', alt: ['N64'] },
    ],
    O: [
      { q: 'The 1998 game in which Link travels seven years into the future.', a: 'Ocarina of Time' },
      { q: 'The small clay wind instrument Link plays to cast melodies.', a: 'Ocarina' },
      { q: 'The odd hovering pot creature in Twilight Princess who warps Link out of dungeons.', a: 'Ooccoo' },
      { q: 'Link\'s quiet home hamlet in Twilight Princess, a farming settlement full of goats.', a: 'Ordon Village', alt: ['Ordon'] },
      { q: 'The 2001 Game Boy Color game set in Holodrum against the General of Darkness.', a: 'Oracle of Seasons' },
      { q: 'The 2001 Game Boy Color game set in Labrynna against the sorceress Veran.', a: 'Oracle of Ages' },
      { q: 'The rock-spitting sea creature that lurks in water and in sand.', a: 'Octorok', alt: ['Octoroks'] },
      { q: 'Link\'s home at the start of The Wind Waker, where his grandmother lives.', a: 'Outset Island', alt: ['Outset'] },
    ],
    P: [
      { q: 'The 2007 DS game in which Link sails with a greedy captain and battles Bellum.', a: 'Phantom Hourglass' },
      { q: 'The Sheikah scientist of Breath of the Wild who runs the laboratory in Hateno.', a: 'Purah' },
      { q: 'Impa\'s shy granddaughter in Kakariko, who has a crush on Link.', a: 'Paya' },
      { q: 'The armored spectral copy of the great evil that rides a horse through paintings.', a: 'Phantom Ganon' },
      { q: 'The lantern-carrying ghost that must be caught for a collector in Twilight Princess.', a: 'Poe', alt: ['Poes'] },
      { q: 'One of four fragments that combine to extend Link\'s life meter by one unit.', a: 'Piece of Heart' },
    ],
    Q: [
      { q: 'The Rito postman of The Wind Waker who first carries Link to Dragon Roost.', a: 'Quill' },
    ],
    R: [
      { q: 'The Zora princess who becomes the Sage of Water in Ocarina of Time.', a: 'Ruto', alt: ['Princess Ruto'] },
      { q: 'The bird people who live at Dragon Roost and in the Hebra highlands.', a: 'Rito' },
      { q: 'The young desert chief of Breath of the Wild who commands a sand seal.', a: 'Riju' },
      { q: 'The old Sheikah inventor in Akkala who upgrades ancient gear.', a: 'Robbie' },
      { q: 'The boastful Rito Champion who piloted Vah Medoh.', a: 'Revali' },
      { q: 'The Sage of Light and first king of Hyrule, a Zonai in Tears of the Kingdom.', a: 'Rauru' },
      { q: 'The hooded merchant in A Link Between Worlds who rents out items from Link\'s house.', a: 'Ravio' },
      { q: 'The gem-shaped currency of Hyrule.', a: 'Rupee', alt: ['Rupees'] },
      { q: 'Zelda\'s father, the last king before the Calamity in Breath of the Wild.', a: 'Rhoam', alt: ['King Rhoam'] },
      { q: 'The winged item in the Oracle games that finally lets Link jump.', a: 'Roc\'s Feather', alt: ['Rocs Feather'] },
    ],
    S: [
      { q: 'The mysterious harp-playing Sheikah who teaches Link songs in Ocarina of Time.', a: 'Sheik' },
      { q: 'The 2011 Wii game, set above the clouds, that tells the earliest story in the timeline.', a: 'Skyward Sword' },
      { q: 'The Zora prince of Breath of the Wild who asks Link to calm Vah Ruta.', a: 'Sidon', alt: ['Prince Sidon'] },
      { q: 'Link\'s Kokiri friend who becomes the Sage of Forest.', a: 'Saria' },
      { q: 'The imp who steals a cursed relic and drags the moon toward Termina.', a: 'Skull Kid' },
      { q: 'The red-eyed shadow tribe who serve the royal family and built the ancient technology.', a: 'Sheikah' },
      { q: 'The skeletal swordsman enemy that guards locked dungeon rooms.', a: 'Stalfos' },
      { q: 'The floating town above the clouds where Link trains as a knight.', a: 'Skyloft' },
      { q: 'The 2009 DS game in which Link becomes a train engineer.', a: 'Spirit Tracks' },
      { q: 'The ancient queen of Hyrule and wife of Rauru in Tears of the Kingdom.', a: 'Sonia' },
      { q: 'The Ocarina of Time melody, taught by a windmill man, that makes rain fall.', a: 'Song of Storms' },
      { q: 'The melody that returns Link to the first day in Majora\'s Mask.', a: 'Song of Time' },
      { q: 'The final dungeon of Majora\'s Mask, an inverted pyramid in Ikana.', a: 'Stone Tower Temple' },
      { q: 'The glowing tablet Link wakes with in Breath of the Wild, used for runes and maps.', a: 'Sheikah Slate' },
      { q: 'The chamber where Link awakens after a hundred years of healing.', a: 'Shrine of Resurrection' },
      { q: 'The golden spider whose tokens are collected for a cursed family in Ocarina of Time.', a: 'Skulltula', alt: ['Gold Skulltula'] },
    ],
    T: [
      { q: 'The three golden triangles left behind by the goddesses.', a: 'Triforce' },
      { q: 'The 2006 game in which Link becomes a wolf inside a shadowy realm.', a: 'Twilight Princess' },
      { q: 'The green forest man in Majora\'s Mask who floats by balloon and pays for maps.', a: 'Tingle' },
      { q: 'The pirate captain of The Wind Waker who turns out to be royalty.', a: 'Tetra' },
      { q: 'The parallel world of Majora\'s Mask with a clock tower at its center.', a: 'Termina' },
      { q: 'The 2023 Switch sequel that adds sky islands and a vast underground to Hyrule.', a: 'Tears of the Kingdom' },
      { q: 'Malon\'s father, the sleepy rancher who sells milk in Ocarina of Time.', a: 'Talon' },
      { q: 'The young Rito Sage of Wind in Tears of the Kingdom, son of Teba.', a: 'Tulin' },
      { q: 'The shadow people of the dark realm that Zant usurps.', a: 'Twili' },
      { q: 'The fused witch form of Kotake and Koume in Ocarina of Time.', a: 'Twinrova' },
      { q: 'The Wind Waker dungeon that rises from the sea to test Link\'s worth as a hero.', a: 'Tower of the Gods' },
      { q: 'The settlement Link helps build from scratch in Akkala in Breath of the Wild.', a: 'Tarrey Town' },
      { q: 'The sanctuary in Castle Town whose door opens once three spiritual stones are gathered.', a: 'Temple of Time' },
    ],
    U: [
      { q: 'The Gerudo Champion who piloted Vah Naboris.', a: 'Urbosa' },
      { q: 'The lightning power the Gerudo Champion grants Link in Breath of the Wild.', a: 'Urbosa\'s Fury', alt: ['Urbosas Fury'] },
      { q: 'The central grassland of Koholint that lies east of Mabe Village.', a: 'Ukuku Prairie' },
    ],
    V: [
      { q: 'The wind sorcerer who is the chief villain of The Minish Cap.', a: 'Vaati' },
      { q: 'The great sky dragon who watches over the Rito at Dragon Roost.', a: 'Valoo' },
      { q: 'The fire dragon boss of the mountain dungeon in Ocarina of Time.', a: 'Volvagia' },
      { q: 'The sorceress who possesses Nayru in Oracle of Ages.', a: 'Veran' },
      { q: 'The elephant-shaped Divine Beast that floods Zora\'s Domain.', a: 'Vah Ruta' },
    ],
    W: [
      { q: 'The 2002 GameCube game set on a flooded Great Sea with cel-shaded art.', a: 'Wind Waker', alt: ['The Wind Waker'] },
      { q: 'The four-legged blue-furred beast form the hero takes inside the Twilight Realm.', a: 'Wolf Link' },
      { q: 'The giant hand that drops from dungeon ceilings to snatch Link away.', a: 'Wallmaster' },
      { q: 'The bustling port town of the 2002 GameCube game, with an auction house and a school.', a: 'Windfall Island', alt: ['Windfall'] },
      { q: 'The Ocarina of Time dungeon beneath Lake Hylia, notorious for its rising and falling levels.', a: 'Water Temple' },
      { q: 'The winged whale who is dreaming Koholint into being.', a: 'Wind Fish' },
      { q: 'The first melody conducted in the 2002 GameCube game, which changes the breeze direction.', a: 'Wind\'s Requiem', alt: ['Winds Requiem'] },
      { q: 'The beast that howls and hunts in packs in the woods of Ocarina of Time, weak to a spin attack.', a: 'Wolfos' },
    ],
    Y: [
      { q: 'The banana-loving assassins of Breath of the Wild who broke away from the Sheikah.', a: 'Yiga Clan', alt: ['Yiga'] },
      { q: 'The timid Goron in Breath of the Wild who gets fired out of a cannon.', a: 'Yunobo' },
      { q: 'The huge snow-dwelling husband in Twilight Princess who cooks soup in his mansion.', a: 'Yeto' },
      { q: 'The ailing wife in the snowbound mansion of Twilight Princess who is cured by soup.', a: 'Yeta' },
    ],
    Z: [
      { q: 'The princess of Hyrule who bears the Triforce of Wisdom.', a: 'Zelda' },
      { q: 'The fish-like water-dwelling race of Hyrule.', a: 'Zora', alt: ['Zoras'] },
      { q: 'The usurper who seizes the Twili throne and serves the great evil in Twilight Princess.', a: 'Zant' },
      { q: 'The waterfall city where Ruto and later Sidon live.', a: 'Zora\'s Domain', alt: ['Zoras Domain'] },
      { q: 'The advanced ancient civilization of Tears of the Kingdom whose green energy powers devices.', a: 'Zonai' },
      { q: 'The 1987 side-scrolling sequel with towns, experience points and a magic meter.', a: 'Zelda II', alt: ['Zelda 2', 'The Adventure of Link'] },
      { q: 'The blue suit that lets Link swim straight up waterfalls in Breath of the Wild.', a: 'Zora Armor' },
      { q: 'The blue spiritual stone given to Link by a water princess in Ocarina of Time.', a: 'Zora\'s Sapphire', alt: ['Zoras Sapphire'] },
    ],
  },
};
