import type { RawPack } from '../core/packs';

export const fandomPokemonPack: RawPack = {
  id: 'fandom-pokemon',
  name: 'Pocket Monsters Trivia',
  description: 'Creatures, evolutions, types, regions, gyms and legendaries across the games and anime.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '⚡',
  accent: '#ca8a04',
  letters: {
    A: [
      { q: 'The Psychic type that sleeps eighteen hours a day and escapes battles by teleporting.', a: 'Abra' },
      { q: 'The fiery Legendary Pokemon of Chinese lore that Growlithe becomes with a Fire Stone.', a: 'Arcanine' },
      { q: 'The ten-year-old trainer from Pallet Town who stars in the anime.', a: 'Ash Ketchum', alt: ['Ash'] },
      { q: 'The Legendary bird of ice hidden deep in the Seafoam Islands.', a: 'Articuno' },
      { q: 'The spoon-bending final Psychic form with a stated IQ of 5000.', a: 'Alakazam' },
      { q: 'The white Dark type whose horn is said to warn people of coming disasters.', a: 'Absol' },
      { q: 'The final evolution of Mareep, whose glowing tail works like a lighthouse.', a: 'Ampharos' },
      { q: 'The Pokemon said to have shaped the universe with a thousand arms.', a: 'Arceus' },
      { q: 'The Rock and Flying prehistoric flyer revived from Old Amber.', a: 'Aerodactyl' },
      { q: 'The tropical island region introduced in Sun and Moon.', a: 'Alola' },
    ],
    B: [
      { q: 'The Grass and Poison starter of Kanto and number one in the National Dex.', a: 'Bulbasaur' },
      { q: 'The final form of Squirtle, firing jets from two cannons on its shell.', a: 'Blastoise' },
      { q: 'The Pewter City Gym Leader who travels with Ash and specialises in Rock types.', a: 'Brock' },
      { q: 'The Bug and Flying evolution of Metapod.', a: 'Butterfree' },
      { q: 'The Fire and Fighting kickboxer that Combusken becomes.', a: 'Blaziken' },
      { q: 'The final evolution of Weedle, armed with three poison stingers.', a: 'Beedrill' },
      { q: 'The Grass and Poison plant with a bud head that evolves into Weepinbell.', a: 'Bellsprout' },
      { q: 'The Normal type evolution of Chansey that carries an egg in a belly pouch.', a: 'Blissey' },
      { q: 'The Fighting type member of the Kanto Elite Four.', a: 'Bruno' },
      { q: 'The Canalave City Gym Leader who is the father of Roark.', a: 'Byron' },
      { q: 'The chubby Normal type rodent of Sinnoh that evolves into Bibarel.', a: 'Bidoof' },
    ],
    C: [
      { q: 'The Fire starter of Kanto with a small flame burning on its tail tip.', a: 'Charmander' },
      { q: 'The middle stage of the Kanto fire lizard line, just before Charizard.', a: 'Charmeleon' },
      { q: 'The Fire and Flying final evolution of Charmeleon.', a: 'Charizard' },
      { q: 'The Fire starter of the Johto region, a small echidna with a flaming back.', a: 'Cyndaquil' },
      { q: 'The Grass starter of Johto, a green creature with a large leaf on its head.', a: 'Chikorita' },
      { q: 'The pink Fairy type that evolves using a Moon Stone.', a: 'Clefairy' },
      { q: 'The Sinnoh Champion whose team is led by Garchomp.', a: 'Cynthia' },
      { q: 'The Grass and Psychic legendary that travels through time and guards Ilex Forest.', a: 'Celebi' },
      { q: 'The lonely Ground type that wears the skull of its lost mother.', a: 'Cubone' },
      { q: 'The green Bug type of Kanto that evolves into Metapod.', a: 'Caterpie' },
      { q: 'The Kanto city whose Gym Leader is Misty.', a: 'Cerulean City', alt: ['Cerulean'] },
      { q: 'The Poison and Fighting frog that keeps jabbing Brock in the Sinnoh anime.', a: 'Croagunk' },
    ],
    D: [
      { q: 'The rare Dragon serpent that evolves into Dragonair.', a: 'Dratini' },
      { q: 'The orange Dragon and Flying final evolution of Dragonair.', a: 'Dragonite' },
      { q: 'The brown Ground type mole whose body below the head is never shown.', a: 'Diglett' },
      { q: 'The purple blob that can transform into any opponent it sees.', a: 'Ditto' },
      { q: 'The Psychic alien said to have formed from a space virus inside a meteor.', a: 'Deoxys' },
      { q: 'The Dark legendary of Newmoon Island that causes nightmares.', a: 'Darkrai' },
      { q: 'The Steel and Dragon legendary of time on the cover of Diamond.', a: 'Dialga' },
      { q: 'The Psychic tapir that eats dreams and evolves into Hypno.', a: 'Drowzee' },
      { q: 'The female player character of Diamond and Pearl who travels with Ash in Sinnoh.', a: 'Dawn' },
      { q: 'The type added in Generation 2 that hits Psychic hard and ignores its attacks.', a: 'Dark' },
    ],
    E: [
      { q: 'The Normal type famous for having many different possible evolutions.', a: 'Eevee' },
      { q: 'The purple Poison snake whose name is a common word spelled backwards.', a: 'Ekans' },
      { q: 'The Psychic evolution reached by raising friendship during the daytime.', a: 'Espeon' },
      { q: 'The Fire legendary beast of the Johto trio said to be born from a volcano.', a: 'Entei' },
      { q: 'The Celadon City Gym Leader who battles with Grass types.', a: 'Erika' },
      { q: 'The Water and Steel final evolution of Piplup.', a: 'Empoleon' },
      { q: 'The Grass and Psychic walking palm tree with three heads.', a: 'Exeggutor' },
      { q: 'The Johto professor who hands out the starter in Gold and Silver (surname).', a: 'Elm' },
    ],
    F: [
      { q: 'The huge blue final evolution of Totodile.', a: 'Feraligatr' },
      { q: 'The fluffy Fire evolution of Eevee.', a: 'Flareon' },
      { q: 'The Normal and Flying duck that carries a leek stalk as a weapon.', a: 'Farfetch\'d' },
      { q: 'The type that Ground moves cannot touch at all.', a: 'Flying' },
      { q: 'The Sinnoh Elite Four member with red hair who battles using Fire types.', a: 'Flint' },
      { q: 'The plain brown Water fish that becomes beautiful once its looks are raised.', a: 'Feebas' },
      { q: 'The Water starter frog of the Kalos region.', a: 'Froakie' },
      { q: 'The type that is weak to Water, Rock and Ground attacks.', a: 'Fire' },
    ],
    G: [
      { q: 'The huge Water and Flying beast that Magikarp becomes at level twenty.', a: 'Gyarados' },
      { q: 'The grinning Ghost and Poison final evolution of Haunter.', a: 'Gengar' },
      { q: 'The Rock and Ground type with two arms that evolves into Graveler.', a: 'Geodude' },
      { q: 'The floating Ghost and Poison Pokemon that evolves into Haunter.', a: 'Gastly' },
      { q: 'The Ground type legendary on the cover of Ruby.', a: 'Groudon' },
      { q: 'The Ghost and Dragon legendary banished to the Distortion World.', a: 'Giratina' },
      { q: 'The Fire puppy that Officer Jenny keeps at her side in the anime.', a: 'Growlithe' },
      { q: 'The Rock and Ground boulder that Graveler becomes when traded.', a: 'Golem' },
      { q: 'The Team Rocket boss who is secretly the Viridian City Gym Leader.', a: 'Giovanni' },
      { q: 'The Psychic and Fairy type that evolves from Kirlia.', a: 'Gardevoir' },
      { q: 'The smug anime rival who is the grandson of the Pallet Town professor.', a: 'Gary Oak', alt: ['Gary'] },
      { q: 'The type that Fire, Ice, Flying and Bug attacks all hit hard.', a: 'Grass' },
    ],
    H: [
      { q: 'The Ghost type that must be traded away to reach its final form.', a: 'Haunter' },
      { q: 'The Fighting type with stretchy legs that evolves from Tyrogue and attacks with kicks.', a: 'Hitmonlee' },
      { q: 'The Fighting type boxer with padded gloves that evolves from Tyrogue.', a: 'Hitmonchan' },
      { q: 'The rainbow-feathered legendary bird on the cover of Gold.', a: 'Ho-Oh' },
      { q: 'The region introduced in Ruby and Sapphire.', a: 'Hoenn' },
      { q: 'The Bug and Fighting beetle of Johto with a large single horn.', a: 'Heracross' },
      { q: 'The Psychic type that swings a pendulum and evolves from Drowzee.', a: 'Hypno' },
      { q: 'The blue Water seahorse that evolves into Seadra.', a: 'Horsea' },
    ],
    I: [
      { q: 'The middle evolution of the Kanto Grass starter, with a closed bud on its back.', a: 'Ivysaur' },
      { q: 'The Fire and Fighting final evolution of Chimchar.', a: 'Infernape' },
      { q: 'The type strong against Dragon, Grass and Ground but easily resisted by Steel.', a: 'Ice' },
      { q: 'The Unova Champion with purple hair who specialises in Dragon types.', a: 'Iris' },
      { q: 'The pink baby stage that grows into Jigglypuff.', a: 'Igglybuff' },
    ],
    J: [
      { q: 'The pink balloon Fairy type that sings foes to sleep and doodles on their faces.', a: 'Jigglypuff' },
      { q: 'The spiky yellow Electric evolution of Eevee.', a: 'Jolteon' },
      { q: 'The region introduced in Gold and Silver.', a: 'Johto' },
      { q: 'The Ice and Psychic type known for the move Lovely Kiss.', a: 'Jynx' },
      { q: 'The red-haired woman of the Team Rocket trio in the anime.', a: 'Jessie' },
      { q: 'The blue-haired man of the Team Rocket trio in the anime.', a: 'James' },
    ],
    K: [
      { q: 'The very first region, home to the original 151 Pokemon.', a: 'Kanto' },
      { q: 'The ancient shellfish revived from the Dome Fossil.', a: 'Kabuto' },
      { q: 'The Psychic type that evolves from Abra and must be traded to evolve again.', a: 'Kadabra' },
      { q: 'The floating Poison gas sphere that evolves into Weezing.', a: 'Koffing' },
      { q: 'The small Water crab with big pincers that evolves into Kingler.', a: 'Krabby' },
      { q: 'The Water legendary on the cover of Sapphire.', a: 'Kyogre' },
      { q: 'The Water and Dragon final evolution of Seadra.', a: 'Kingdra' },
      { q: 'The Poison type Gym Leader of Fuchsia City who later joins the Elite Four.', a: 'Koga' },
      { q: 'The Psychic dancer that evolves from Ralts.', a: 'Kirlia' },
    ],
    L: [
      { q: 'The Psychic and Flying legendary of the sea on the cover of Silver.', a: 'Lugia' },
      { q: 'The gentle Water and Ice type that ferries trainers across the ocean.', a: 'Lapras' },
      { q: 'The Steel and Fighting type that senses aura and evolves from Riolu.', a: 'Lucario' },
      { q: 'The female half of the Hoenn Eon duo, the red one.', a: 'Latias' },
      { q: 'The male half of the Hoenn Eon duo, the blue one.', a: 'Latios' },
      { q: 'The pink Normal type with an enormously long tongue.', a: 'Lickitung' },
      { q: 'The Grass evolution of Eevee, created near a mossy stone.', a: 'Leafeon' },
      { q: 'The cape-wearing dragon master who is Champion in Gold and Silver.', a: 'Lance' },
      { q: 'The Electric type final evolution of Shinx.', a: 'Luxray' },
    ],
    M: [
      { q: 'The Psychic clone created in a laboratory on Cinnabar Island.', a: 'Mewtwo' },
      { q: 'The tiny pink Psychic legendary said to be the ancestor of every Pokemon.', a: 'Mew' },
      { q: 'The hopeless orange Water fish that starts out knowing only Splash.', a: 'Magikarp' },
      { q: 'The Electric and Steel magnet with a single eye that evolves into Magneton.', a: 'Magnemite' },
      { q: 'The talking Normal type cat of the Team Rocket trio.', a: 'Meowth' },
      { q: 'The Water starter of the Hoenn region, a blue mudfish.', a: 'Mudkip' },
      { q: 'The Cerulean City Gym Leader who travels with Ash and loves Water types.', a: 'Misty' },
      { q: 'The Electric sheep of Johto that evolves into Flaaffy.', a: 'Mareep' },
      { q: 'The green cocoon of Kanto that mostly just uses Harden.', a: 'Metapod' },
      { q: 'The small blue Water and Fairy mouse with a round tail tip.', a: 'Marill' },
      { q: 'The purple and gold item that never fails to catch a wild Pokemon.', a: 'Master Ball' },
      { q: 'The elegant Water serpent that Feebas becomes.', a: 'Milotic' },
      { q: 'The Kanto cave between Pewter and Cerulean where Clefairy gather.', a: 'Mount Moon' },
    ],
    N: [
      { q: 'The male Poison and Ground type with a large horn, evolved with a Moon Stone.', a: 'Nidoking' },
      { q: 'The female Poison and Ground counterpart also evolved with a Moon Stone.', a: 'Nidoqueen' },
      { q: 'The Fire fox said to live a thousand years, evolved from Vulpix.', a: 'Ninetales' },
      { q: 'The pink-haired healer who runs every Pokemon Center in the anime.', a: 'Nurse Joy' },
      { q: 'The small green Psychic and Flying bird that evolves into Xatu.', a: 'Natu' },
      { q: 'The type that Ghost attacks cannot affect at all.', a: 'Normal' },
      { q: 'The Kanto Poison type that comes in clearly different male and female forms.', a: 'Nidoran' },
      { q: 'The Rock type of Hoenn that behaves like a compass and evolves into Probopass.', a: 'Nosepass' },
    ],
    O: [
      { q: 'The giant Rock and Ground rock snake that Brock uses in his Gym.', a: 'Onix' },
      { q: 'The Grass and Poison weed with leaves on its head that evolves into Gloom.', a: 'Oddish' },
      { q: 'The Water starter otter of the Unova region.', a: 'Oshawott' },
      { q: 'The spiral-shelled ancient Pokemon revived from the Helix Fossil.', a: 'Omanyte' },
      { q: 'The Kanto professor based in Pallet Town (surname).', a: 'Oak' },
    ],
    P: [
      { q: 'The yellow Electric mouse mascot that rides on the shoulder of Ash.', a: 'Pikachu' },
      { q: 'The most common Normal and Flying bird on the early routes of Kanto.', a: 'Pidgey' },
      { q: 'The yellow Water duck that suffers a permanent headache.', a: 'Psyduck' },
      { q: 'The baby Electric type that grows up through friendship.', a: 'Pichu' },
      { q: 'The Water starter penguin of Sinnoh and the partner of Dawn.', a: 'Piplup' },
      { q: 'The Water and Dragon legendary of space on the cover of Pearl.', a: 'Palkia' },
      { q: 'The type that Steel Pokemon are completely immune to.', a: 'Poison' },
      { q: 'The Normal type made entirely of computer programming.', a: 'Porygon' },
      { q: 'The Fire horse with a blazing mane that evolves into Rapidash.', a: 'Ponyta' },
      { q: 'The Bug type of Kanto with huge gripping horns, often paired with Scyther.', a: 'Pinsir' },
      { q: 'The Kanto town with a museum and a Rock type Gym.', a: 'Pewter City', alt: ['Pewter'] },
      { q: 'The Fighting type in a permanent rage that evolves from Mankey.', a: 'Primeape' },
    ],
    Q: [
      { q: 'The middle evolution of the Johto Fire starter.', a: 'Quilava' },
      { q: 'The easygoing Water and Ground type that evolves from Wooper.', a: 'Quagsire' },
      { q: 'The Water starter duckling of the Paldea region.', a: 'Quaxly' },
    ],
    R: [
      { q: 'The Electric type reached by giving a Thunder Stone to the yellow mouse mascot.', a: 'Raichu' },
      { q: 'The purple Normal rodent found on almost every early route in Kanto.', a: 'Rattata' },
      { q: 'The Dragon and Flying legendary that lives high in the ozone layer.', a: 'Rayquaza' },
      { q: 'The armour-plated Ground and Rock quadruped of Kanto that charges in a straight line.', a: 'Rhydon' },
      { q: 'The type used by the Pewter City Gym that is weak to Water and Grass.', a: 'Rock' },
      { q: 'The baby Fighting type that evolves into Lucario.', a: 'Riolu' },
      { q: 'The Electric and Ghost type that possesses household appliances.', a: 'Rotom' },
      { q: 'The Oreburgh City Gym Leader who digs in the coal mine.', a: 'Roark' },
      { q: 'The stony golem of the Hoenn trio sealed inside the Desert Ruins.', a: 'Regirock' },
      { q: 'The frozen golem of the Hoenn trio sealed in Island Cave.', a: 'Regice' },
      { q: 'The Grass and Flying owl starter of Alola.', a: 'Rowlet' },
    ],
    S: [
      { q: 'The Water starter turtle of Kanto with a hard shell.', a: 'Squirtle' },
      { q: 'The enormous sleeping Normal type that blocks roads until woken by a flute.', a: 'Snorlax' },
      { q: 'The Bug and Flying mantis with blade arms that becomes Scizor when traded.', a: 'Scyther' },
      { q: 'The Water legendary beast said to purify springs, shown on the cover of Crystal.', a: 'Suicune' },
      { q: 'The Grass final evolution of Treecko.', a: 'Sceptile' },
      { q: 'The pink Water and Psychic dope that gets a Shellder clamped onto its tail.', a: 'Slowpoke' },
      { q: 'The type added in Generation 2 that resists more attack types than any other.', a: 'Steel' },
      { q: 'The Water type shaped like a star with a red core, favoured by Misty.', a: 'Staryu' },
      { q: 'The region introduced in Diamond and Pearl.', a: 'Sinnoh' },
      { q: 'The Ghost and Dark type of Hoenn with gemstones for eyes.', a: 'Sableye' },
      { q: 'The Rock type that pretends to be a tree and blocks a route in Johto.', a: 'Sudowoodo' },
      { q: 'The Dark and Ice cat of Johto that evolves into Weavile.', a: 'Sneasel' },
      { q: 'The Saffron City company whose office tower Team Rocket takes over.', a: 'Silph', alt: ['Silph Co', 'Silph Co.'] },
    ],
    T: [
      { q: 'The Water starter of Johto, a blue crocodile with big jaws.', a: 'Totodile' },
      { q: 'The Fire starter chick of the Hoenn region.', a: 'Torchic' },
      { q: 'The Grass starter of Sinnoh, a turtle with a sapling on its head.', a: 'Turtwig' },
      { q: 'The Normal bull with three tails commonly caught in the Safari Zone.', a: 'Tauros' },
      { q: 'The Water and Poison jellyfish that appears constantly while surfing.', a: 'Tentacool' },
      { q: 'The criminal organisation led by Giovanni in Kanto.', a: 'Team Rocket' },
      { q: 'The Grass starter gecko of the Hoenn region.', a: 'Treecko' },
      { q: 'The Fairy type that hatches from an egg and is raised by Misty.', a: 'Togepi' },
      { q: 'The Rock and Dark heavyweight that evolves from Pupitar.', a: 'Tyranitar' },
      { q: 'The Electric attack the partner of Ash uses most often in the anime.', a: 'Thunderbolt' },
      { q: 'The Sinnoh criminal organisation led by Cyrus.', a: 'Team Galactic' },
    ],
    U: [
      { q: 'The Dark evolution of Eevee reached by raising friendship at night.', a: 'Umbreon' },
      { q: 'The Psychic type whose many forms resemble letters of the alphabet.', a: 'Unown' },
      { q: 'The Psychic being of knowledge that rests beneath Lake Acuity.', a: 'Uxie' },
      { q: 'The Normal bear of Johto that evolves from Teddiursa.', a: 'Ursaring' },
      { q: 'The region introduced in Black and White.', a: 'Unova' },
    ],
    V: [
      { q: 'The final evolution of Ivysaur, with a huge flower on its back.', a: 'Venusaur' },
      { q: 'The Water evolution of Eevee, made using a Water Stone.', a: 'Vaporeon' },
      { q: 'The Electric sphere that is easily mistaken for a red and white capture device.', a: 'Voltorb' },
      { q: 'The small Fire fox with six curled tails.', a: 'Vulpix' },
      { q: 'The Grass and Poison pitcher plant that James keeps in the anime.', a: 'Victreebel' },
      { q: 'The Bug and Poison type with enormous eyes that evolves into Venomoth.', a: 'Venonat' },
      { q: 'The final cave a trainer must cross before reaching the Pokemon League.', a: 'Victory Road' },
    ],
    W: [
      { q: 'The middle evolution of the Kanto Water starter, with furry ears and tail.', a: 'Wartortle' },
      { q: 'The tiny Bug and Poison larva with a sharp horn on its head.', a: 'Weedle' },
      { q: 'The blue Psychic type that only counters attacks and joins Team Rocket in the anime.', a: 'Wobbuffet' },
      { q: 'The type that beats Fire, Rock and Ground.', a: 'Water' },
      { q: 'The enormous blue whale of the Hoenn region, 14.5 metres long.', a: 'Wailord' },
      { q: 'The Goldenrod City Gym Leader whose Miltank frustrates so many players.', a: 'Whitney' },
    ],
    X: [
      { q: 'The Psychic and Flying totem bird of Johto that stands still watching the sun.', a: 'Xatu' },
      { q: 'The Fairy legendary stag of Kalos with antlers full of colour.', a: 'Xerneas' },
    ],
    Y: [
      { q: 'The Dark and Flying legendary bird of Kalos shaped like the letter Y.', a: 'Yveltal' },
      { q: 'The Bug and Flying dragonfly of Johto that evolves into Yanmega.', a: 'Yanma' },
    ],
    Z: [
      { q: 'The Legendary Electric bird of the Kanto trio found at the Power Plant.', a: 'Zapdos' },
      { q: 'The Poison and Flying bat that swarms in nearly every cave.', a: 'Zubat' },
      { q: 'The white Normal type ferret of Hoenn locked in a feud with Seviper.', a: 'Zangoose' },
      { q: 'The Dragon and Electric legendary on the cover of Black.', a: 'Zekrom' },
      { q: 'The Dark type illusion fox of Unova that can disguise itself as another party member.', a: 'Zoroark' },
    ],
  },
};
