import type { RawPack } from '../core/packs';

export const fandomLotrPack: RawPack = {
  id: 'fandom-lotr',
  name: 'Lord of the Rings',
  description: 'Middle-earth from Bag End to Mount Doom: books, films, races and lore.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '💍',
  accent: '#15803d',
  letters: {
    A: [
      { q: "The ranger known as Strider who is crowned King Elessar.", a: "Aragorn" },
      { q: "The daughter of Elrond who gives up her immortality to marry the King of Gondor.", a: "Arwen" },
      { q: "The name given to the reforged sword of Elendil, the Flame of the West.", a: "Anduril" },
      { q: "The Great River the Fellowship travels by boat after leaving Lothlorien.", a: "Anduin", alt: ["The Anduin"] },
      { q: "The northern realm whose Witch-king once warred against Arnor.", a: "Angmar" },
      { q: "The pale orc chieftain who beheaded Thror at the gate of Moria.", a: "Azog" },
      { q: "The Seat of Seeing hill where the Fellowship breaks apart.", a: "Amon Hen" },
      { q: "The two colossal statues of ancient kings that flank the Great River.", a: "Argonath" },
      { q: "The Vala smith who created the Dwarves in secret.", a: "Aule" },
      { q: "The brother of Isildur, the other son of Elendil.", a: "Anarion" },
      { q: "The father of Aragorn, a chieftain of the Dunedain.", a: "Arathorn" },
      { q: "The actor who performed the motion capture and voice for Gollum.", a: "Andy Serkis" },
    ],
    B: [
      { q: "The hobbit who finds the One Ring in a cave under the Misty Mountains.", a: "Bilbo", alt: ["Bilbo Baggins"] },
      { q: "The son of Denethor who dies defending Merry and Pippin from orc arrows.", a: "Boromir" },
      { q: "The fiery demon of shadow that Gandalf fights on the Bridge of Khazad-dum.", a: "Balrog" },
      { q: "The name of the comfortable hobbit hole where Bilbo lives in Hobbiton.", a: "Bag End" },
      { q: "The village of Men where the hobbits first meet Strider at an inn.", a: "Bree" },
      { q: "The dwarf who becomes Lord of Moria and is found entombed there.", a: "Balin" },
      { q: "The skin-changer who becomes a great bear and shelters Thorin's company.", a: "Beorn" },
      { q: "Sauron's black fortress in Mordor, crowned by his Eye.", a: "Barad-dur" },
      { q: "The merry ancient master of the Old Forest, husband of Goldberry.", a: "Bombadil", alt: ["Tom Bombadil"] },
      { q: "The bowman of the lake town who slays Smaug with the Black Arrow.", a: "Bard" },
      { q: "The orc son of Azog who leads the army at the Battle of Five Armies.", a: "Bolg" },
      { q: "The forgetful innkeeper of the Prancing Pony (surname).", a: "Butterbur", alt: ["Barliman Butterbur"] },
      { q: "The Scottish actor who played Pippin and sang for Denethor.", a: "Billy Boyd" },
      { q: "The actor who played Theoden, King of Rohan.", a: "Bernard Hill" },
    ],
    C: [
      { q: "The Elf lord of Lothlorien and husband of Galadriel.", a: "Celeborn" },
      { q: "The high pass above the Morgul Vale whose stair leads to Shelob's lair.", a: "Cirith Ungol" },
      { q: "The cruel mountain the Fellowship tries to cross before turning underground.", a: "Caradhras" },
      { q: "The great rock beside the river near Beorn's house.", a: "Carrock", alt: ["The Carrock"] },
      { q: "The river island fortress north of Osgiliath.", a: "Cair Andros" },
      { q: "The Elf shipwright of the Grey Havens who kept the ring Narya.", a: "Cirdan" },
      { q: "The actress who played Galadriel in the films.", a: "Cate Blanchett" },
      { q: "The veteran horror actor who played Saruman.", a: "Christopher Lee" },
      { q: "The pirates of Umbar whose black ships Aragorn seizes.", a: "Corsairs" },
      { q: "The chained beast the Fellowship battles in the Chamber of Mazarbul.", a: "Cave troll" },
    ],
    D: [
      { q: "The despairing Steward of Gondor who burns himself on a pyre.", a: "Denethor" },
      { q: "The dark stronghold in southern Mirkwood where the Necromancer hid.", a: "Dol Guldur" },
      { q: "The first Dwarf king, called the Deathless, founder of Khazad-dum.", a: "Durin" },
      { q: "The brother of Balin, the first dwarf to arrive at Bilbo's door.", a: "Dwalin" },
      { q: "The dwarf who becomes King under the Mountain after Thorin's death.", a: "Dain", alt: ["Dain Ironfoot"] },
      { q: "The Stoor whom Smeagol murdered for the golden trinket.", a: "Deagol" },
      { q: "The corpse-filled swamp Gollum leads Frodo and Sam through.", a: "Dead Marshes" },
      { q: "The mountain refuge where the Rohirrim muster before riding to Gondor.", a: "Dunharrow" },
      { q: "The name for the Rangers of the North, descendants of Numenor.", a: "Dunedain" },
      { q: "The actor who played Merry Brandybuck.", a: "Dominic Monaghan" },
      { q: "The Common Speech name for the great delved dwarf city under the mountains.", a: "Dwarrowdelf" },
    ],
    E: [
      { q: "The White Lady of Rohan who slays the chief of the Nazgul.", a: "Eowyn" },
      { q: "The nephew of Theoden, Third Marshal of the Riddermark.", a: "Eomer" },
      { q: "The half-elven lord of Rivendell who calls the great Council.", a: "Elrond" },
      { q: "The tree-shepherds who march on Isengard and break its dam.", a: "Ents", alt: ["Ent"] },
      { q: "The hill-top capital of the horse-lords.", a: "Edoras" },
      { q: "The Lonely Mountain kingdom that Smaug seized from the dwarves.", a: "Erebor" },
      { q: "The high king who founded Arnor and Gondor after his island sank.", a: "Elendil" },
      { q: "The mariner whose star-light fills the phial Galadriel gives Frodo.", a: "Earendil" },
      { q: "The eldest daughter of Sam, named for a golden flower of Lothlorien.", a: "Elanor" },
      { q: "The actor who played Frodo Baggins.", a: "Elijah Wood" },
      { q: "The son of Aragorn and Arwen who inherits the throne of Gondor.", a: "Eldarion" },
      { q: "The great birds led by Gwaihir that rescue Frodo and Sam from the mountain.", a: "Eagles" },
      { q: "The father of Denethor, the previous Steward of Gondor.", a: "Ecthelion" },
    ],
    F: [
      { q: "The hobbit who carries the Ring to Mordor as its Bearer.", a: "Frodo", alt: ["Frodo Baggins"] },
      { q: "The ancient forest at the southern end of the Misty Mountains where Treebeard walks.", a: "Fangorn" },
      { q: "The younger son of Denethor who captures Frodo in Ithilien.", a: "Faramir" },
      { q: "The nine walkers set against the nine riders, formed at Rivendell.", a: "Fellowship", alt: ["The Fellowship"] },
      { q: "The brother of Kili, one of the youngest dwarves in Thorin's company.", a: "Fili" },
      { q: "The winged flying mount of a Nazgul.", a: "Fell beast" },
      { q: "The ruined northern city where the last king of Arnor was defeated.", a: "Fornost" },
      { q: "The Noldor smith who made the Silmarils.", a: "Feanor" },
      { q: "The Shire smallholder whose mushrooms Frodo stole as a boy.", a: "Farmer Maggot", alt: ["Maggot"] },
      { q: "The nickname of the plump hobbit Fredegar, left behind at Crickhollow.", a: "Fatty Bolger" },
      { q: "The Elf king of Nargothrond who died saving Beren.", a: "Finrod" },
    ],
    G: [
      { q: "The Grey Wizard who returns as the White after falling in Moria.", a: "Gandalf" },
      { q: "The son of Gloin who becomes Legolas's closest friend.", a: "Gimli" },
      { q: "The wretched creature who calls the Ring his precious.", a: "Gollum" },
      { q: "The Lady of Lothlorien who bears the ring Nenya.", a: "Galadriel" },
      { q: "The whispering counsellor who poisons Theoden's mind for Saruman.", a: "Grima", alt: ["Grima Wormtongue"] },
      { q: "The southern kingdom of Men whose capital is Minas Tirith.", a: "Gondor" },
      { q: "The Elvish sword called the Foe-hammer that Gandalf takes from a troll hoard.", a: "Glamdring" },
      { q: "The Elf lord who sets Frodo on his horse and rides for the Ford.", a: "Glorfindel" },
      { q: "The Windlord eagle who carries Gandalf from the pinnacle of Orthanc.", a: "Gwaihir" },
      { q: "The great wolf-headed battering ram used against the gate of Minas Tirith.", a: "Grond" },
      { q: "The last High King of the Noldor, slain by Sauron in the Last Alliance.", a: "Gil-galad" },
      { q: "The port of Mithlond where Frodo sails into the West.", a: "Grey Havens" },
      { q: "The orc stronghold in the far north of the Misty Mountains.", a: "Gundabad" },
      { q: "The River-daughter who is the wife of Tom Bombadil.", a: "Goldberry" },
    ],
    H: [
      { q: "The small folk of the Shire, also called Halflings.", a: "Hobbits", alt: ["Hobbit"] },
      { q: "The fortified Rohan valley where Theoden makes his stand.", a: "Helm's Deep" },
      { q: "The Galadhrim marchwarden who guides the Fellowship into the Golden Wood.", a: "Haldir" },
      { q: "The Shire village where Bilbo's birthday party is held.", a: "Hobbiton" },
      { q: "The keep that guards the head of Helm's Deep.", a: "Hornburg" },
      { q: "The Australian actor who played Elrond.", a: "Hugo Weaving" },
      { q: "The Canadian composer who scored Peter Jackson's trilogy.", a: "Howard Shore" },
      { q: "The Man of Dor-lomin who defied Morgoth and was chained to watch his children's doom.", a: "Hurin" },
      { q: "The hot land south of Gondor whose men ride great beasts to war.", a: "Harad" },
    ],
    I: [
      { q: "The man who cut the Ring from Sauron's hand and refused to destroy it.", a: "Isildur" },
      { q: "The ring of stone around Orthanc that Saruman fills with pits and forges.", a: "Isengard" },
      { q: "The green province of Gondor east of the river where Faramir's rangers hide.", a: "Ithilien" },
      { q: "The Elvish name for the hidden valley of Rivendell.", a: "Imladris" },
      { q: "The One, creator of all things in Tolkien's world, also called Eru.", a: "Iluvatar" },
      { q: "The English actor who played Gandalf.", a: "Ian McKellen" },
      { q: "The actor who played the older Bilbo in the film trilogy.", a: "Ian Holm" },
      { q: "The dwarf realm east of the Lonely Mountain ruled by Dain.", a: "Iron Hills" },
    ],
    J: [
      { q: "The Welsh actor who played Gimli and voiced Treebeard.", a: "John Rhys-Davies" },
      { q: "The Oxford philologist who wrote The Hobbit.", a: "J.R.R. Tolkien", alt: ["Tolkien"] },
    ],
    K: [
      { q: "The Dwarvish name for the great delved city under the Misty Mountains.", a: "Khazad-dum" },
      { q: "The younger dwarf brother who loves Tauriel in the films.", a: "Kili" },
      { q: "The New Zealand actor who played Eomer.", a: "Karl Urban" },
      { q: "The healing herb known to the Rangers as athelas, used against the Black Breath.", a: "Kingsfoil" },
    ],
    L: [
      { q: "The Elf prince of the Woodland Realm who joins the Fellowship.", a: "Legolas" },
      { q: "The golden wood of mallorn trees ruled by Galadriel.", a: "Lothlorien" },
      { q: "The peak the dwarves reclaim at the end of The Hobbit.", a: "Lonely Mountain" },
      { q: "The Sackville-Baggins relative who covets Bilbo's silver spoons.", a: "Lobelia" },
      { q: "The wooden settlement built on stilts over the water that Smaug burns.", a: "Laketown", alt: ["Lake-town", "Esgaroth"] },
      { q: "The Elf maiden of Doriath who loved a mortal man and defied Morgoth.", a: "Luthien" },
      { q: "The American actress who played Arwen.", a: "Liv Tyler" },
      { q: "The finest pipe-weed of the Southfarthing, found in Saruman's storerooms.", a: "Longbottom Leaf" },
      { q: "The union of Elves and Men that besieged Barad-dur at the end of the Second Age.", a: "Last Alliance" },
    ],
    M: [
      { q: "The Black Land behind the Ephel Duath where Sauron rules.", a: "Mordor" },
      { q: "The abandoned dwarf realm where the Fellowship loses Gandalf.", a: "Moria" },
      { q: "The hobbit who rides to war hidden on Dernhelm's horse.", a: "Merry", alt: ["Meriadoc", "Meriadoc Brandybuck"] },
      { q: "The volcano where the One Ring was forged and finally unmade.", a: "Mount Doom", alt: ["Orodruin"] },
      { q: "The seven-walled White City of Gondor.", a: "Minas Tirith" },
      { q: "The haunted green-lit tower city guarding the western pass into Mordor.", a: "Minas Morgul" },
      { q: "The vast shadowed forest where Thranduil's halls lie.", a: "Mirkwood" },
      { q: "The precious silver metal of Moria from which Bilbo's shirt was made.", a: "Mithril" },
      { q: "The first Dark Lord, once mightiest of the Valar and master of Sauron.", a: "Morgoth", alt: ["Melkor"] },
      { q: "The golden hall of Theoden at Edoras.", a: "Meduseld" },
      { q: "The Australian actress who played Eowyn.", a: "Miranda Otto" },
      { q: "The English actor who played the young Bilbo in The Hobbit films.", a: "Martin Freeman" },
      { q: "The Elvish name for the Grey Pilgrim wizard.", a: "Mithrandir" },
    ],
    N: [
      { q: "The nine Ringwraiths who serve Sauron.", a: "Nazgul" },
      { q: "The blade of Elendil that broke beneath him at the Dark Lord's fall.", a: "Narsil" },
      { q: "The island kingdom of Men drowned for assailing the Undying Lands.", a: "Numenor" },
      { q: "The dwarf in Thorin's company with a star-shaped hairstyle in the films.", a: "Nori" },
      { q: "The Ring of Adamant kept by the Lady of the Golden Wood.", a: "Nenya" },
      { q: "The stream in Lothlorien whose song Legolas sings.", a: "Nimrodel" },
      { q: "The country where Peter Jackson filmed all six Middle-earth movies.", a: "New Zealand" },
      { q: "The number of Rings of Power given to mortal Men.", a: "Nine" },
      { q: "The hidden underground city of Finrod in the First Age.", a: "Nargothrond" },
    ],
    O: [
      { q: "The crooked soldier-race bred long ago in mockery of the Elves.", a: "Orcs", alt: ["Orc"] },
      { q: "The hobbits' word for the huge war beasts of Harad.", a: "Oliphaunt", alt: ["Oliphaunts", "Mumakil"] },
      { q: "The dwarf scribe who wrote the last words in the Book of Mazarbul.", a: "Ori" },
      { q: "The black tower at the heart of Isengard.", a: "Orthanc" },
      { q: "The ruined former capital of Gondor astride the great river.", a: "Osgiliath" },
      { q: "The object Isildur cut from the Dark Lord's hand.", a: "One Ring", alt: ["The One Ring"] },
      { q: "The brother of Gloin who was lost at the watery gate of Moria.", a: "Oin" },
      { q: "The English actor who played Legolas.", a: "Orlando Bloom" },
      { q: "The wood east of Buckland where a willow tries to swallow Merry.", a: "Old Forest" },
      { q: "The name for the men of the mountains who broke their promise to Isildur.", a: "Oathbreakers" },
    ],
    P: [
      { q: "The youngest hobbit of the Fellowship, who looks into a seeing-stone.", a: "Pippin", alt: ["Peregrin", "Peregrin Took"] },
      { q: "The seeing-stone that Denethor uses in secret.", a: "Palantir" },
      { q: "The great tree in the field where Bilbo holds his farewell feast.", a: "Party Tree" },
      { q: "The inn at Bree kept by Barliman Butterbur.", a: "Prancing Pony", alt: ["The Prancing Pony"] },
      { q: "The New Zealand director of the film trilogy.", a: "Peter Jackson" },
      { q: "The wide plain before the White City where the Rohirrim charge.", a: "Pelennor Fields", alt: ["Pelennor"] },
      { q: "The southern haven where Aragorn seizes the black fleet.", a: "Pelargir" },
    ],
    R: [
      { q: "The kingdom of the horse-lords, also called the Riddermark.", a: "Rohan" },
      { q: "The hidden valley refuge ruled by Elrond.", a: "Rivendell" },
      { q: "The name for the riders of the Mark.", a: "Rohirrim" },
      { q: "The brown wizard of Rhosgobel who loves birds and beasts.", a: "Radagast" },
      { q: "The Black Riders who hunt Frodo out of the Shire.", a: "Ringwraiths", alt: ["Ringwraith"] },
      { q: "The hobbit lass Sam marries after the War of the Ring.", a: "Rosie", alt: ["Rosie Cotton"] },
      { q: "The great falls below Nen Hithoel where Boromir's boat is set adrift.", a: "Rauros" },
      { q: "The great inland sea far east of Mirkwood.", a: "Rhun" },
      { q: "The English actor who played Thorin Oakenshield.", a: "Richard Armitage" },
      { q: "The outer wall built to defend the fields before Minas Tirith.", a: "Rammas Echor" },
    ],
    S: [
      { q: "The gardener who carries Frodo up the slopes of Mount Doom.", a: "Sam", alt: ["Samwise", "Samwise Gamgee"] },
      { q: "The White Wizard who breeds an army beneath Orthanc.", a: "Saruman" },
      { q: "The Dark Lord who forged the Ruling Ring in secret.", a: "Sauron" },
      { q: "The giant spider that guards the pass above the Morgul Vale.", a: "Shelob" },
      { q: "The green hobbit homeland in Eriador.", a: "Shire", alt: ["The Shire"] },
      { q: "The dragon who hoards the dwarves' treasure under the Lonely Mountain.", a: "Smaug" },
      { q: "The original name of Gollum before the Ring twisted him.", a: "Smeagol" },
      { q: "The lord of all horses, the mount Gandalf rides.", a: "Shadowfax" },
      { q: "The Elvish dagger that glows blue when orcs are near.", a: "Sting" },
      { q: "The three jewels Feanor made that held the light of the Two Trees.", a: "Silmarils", alt: ["Silmaril"] },
      { q: "The grasping family name of the relatives who buy Bag End.", a: "Sackville-Baggins" },
      { q: "The hereditary office Denethor held in place of a king.", a: "Steward" },
      { q: "The actor who played Samwise Gamgee.", a: "Sean Astin" },
      { q: "The English actor who played Boromir.", a: "Sean Bean" },
      { q: "The quarter of the Shire famous for growing pipe-weed.", a: "Southfarthing" },
      { q: "The horse of Theoden, felled by a dart on the Pelennor.", a: "Snowmane" },
    ],
    T: [
      { q: "The King of Rohan freed from Saruman's spell by Gandalf.", a: "Theoden" },
      { q: "The dwarf leader nicknamed Oakenshield.", a: "Thorin" },
      { q: "The Elvenking of Mirkwood, father of Legolas.", a: "Thranduil" },
      { q: "The eldest Ent, who leads the assault on Isengard.", a: "Treebeard" },
      { q: "The King under the Mountain slain by Azog at the gate of Moria.", a: "Thror" },
      { q: "The father of Thorin, who lost his dwarf ring in Dol Guldur.", a: "Thrain" },
      { q: "The Silvan elf captain invented for the film trilogy of The Hobbit.", a: "Tauriel" },
      { q: "The tragic First Age hero who wielded the black sword Gurthang.", a: "Turin" },
      { q: "The Elf king of Doriath, father of Luthien.", a: "Thingol" },
      { q: "The name the Dwarves give to the Grey Wizard.", a: "Tharkun" },
      { q: "Telperion and Laurelin, the great lights of Valinor.", a: "Two Trees" },
      { q: "The era of Middle-earth that ended with the passing of the Ring-bearers over the sea.", a: "Third Age" },
    ],
    U: [
      { q: "The great crossbred orc soldiers of Saruman.", a: "Uruk-hai" },
      { q: "The primordial spider who drank the light of the Two Trees.", a: "Ungoliant" },
      { q: "The blessed western realm across the sea to which Frodo sails.", a: "Undying Lands" },
      { q: "The southern haven of the black corsair fleet.", a: "Umbar" },
      { q: "The Isengard orc captain who leads the band carrying Merry and Pippin.", a: "Ugluk" },
    ],
    V: [
      { q: "The fourteen great powers who shaped the world at its beginning.", a: "Valar" },
      { q: "The land of the Powers in the uttermost West.", a: "Valinor" },
      { q: "The mightiest of the Three, the blue Ring of Air held by Elrond.", a: "Vilya" },
      { q: "The queen of the stars among the Powers, invoked as Elbereth.", a: "Varda" },
      { q: "The Danish American actor who played Aragorn.", a: "Viggo Mortensen" },
    ],
    W: [
      { q: "The ruined watchtower hill where Frodo is stabbed with a Morgul blade.", a: "Weathertop" },
      { q: "The chief of the Nazgul, whom no living man could kill.", a: "Witch-king" },
      { q: "The nickname of Grima, the counsellor of Theoden.", a: "Wormtongue" },
      { q: "The great evil wolves that orcs ride to battle.", a: "Wargs", alt: ["Warg"] },
      { q: "The common name in The Hobbit for the wide lands beyond the Misty Mountains.", a: "Wilderland" },
      { q: "The withered emblem of Gondor standing in the Court of the Fountain.", a: "White Tree" },
      { q: "The forest kingdom of Thranduil in northern Mirkwood.", a: "Woodland Realm" },
      { q: "The many-tentacled creature lurking in the pool outside the west gate of Moria.", a: "Watcher", alt: ["The Watcher in the Water"] },
    ],
  },
};
