import type { RawPack } from '../core/packs';

export const fandomStrangerThingsPack: RawPack = {
  id: 'fandom-stranger-things',
  name: 'Stranger Things',
  description: 'Hawkins, the Upside Down, the kids, the monsters and all the 80s nods.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'teen',
  emoji: '🔴',
  accent: '#b91c1c',
  letters: {
    A: [
      { q: 'Jonathan\'s pizza-delivering stoner best friend in California.', a: 'Argyle' },
      { q: 'The Soviet scientist who loves cherry frozen drinks and wins a stuffed Woody Woodpecker at the fair.', a: 'Alexei' },
      { q: 'Surname of the prison guard nicknamed Enzo who escapes the camp with Hopper.', a: 'Antonov' },
      { q: 'The roller-rink bully who torments Eleven and gets a skate to the face.', a: 'Angela' },
      { q: 'Surname of the Goonies star who plays Bob Newby.', a: 'Astin' },
      { q: 'The bleach-blond member of Kali\'s Chicago gang who mocks Eleven.', a: 'Axel' },
      { q: 'The young daughter murdered in the Creel home in 1959.', a: 'Alice' },
      { q: 'The Georgia city and its suburbs where the series is filmed.', a: 'Atlanta' },
      { q: 'The 1979 Ridley Scott film whose petal-mouthed creature inspired the first monster design.', a: 'Alien' },
      { q: 'The console brand whose 2600 defined home gaming in the show\'s era.', a: 'Atari' },
    ],
    B: [
      { q: 'Nancy\'s bespectacled best friend who dies at the pool after cutting her hand.', a: 'Barbara', alt: ['Barb'] },
      { q: 'Surname of the family whose living room wall is strung with alphabet Christmas lights.', a: 'Byers' },
      { q: 'Surname of the white-haired scientist Eleven is made to call Papa.', a: 'Brenner' },
      { q: 'The kind diner owner who feeds Eleven before agents shoot him.', a: 'Benny' },
      { q: 'Max\'s cruel stepbrother, a lifeguard taken over by the shadow monster.', a: 'Billy' },
      { q: 'The electronics store manager and Joyce\'s sweet boyfriend who dies in the laboratory.', a: 'Bob Newby', alt: ['Bob'] },
      { q: 'Surname of the paranoid private investigator who translates Russian for the group.', a: 'Bauman' },
      { q: 'Surname of the girl who cracks the Soviet code with Dustin.', a: 'Buckley' },
      { q: 'Surname of the actor Jamie Campbell who plays the fourth-season villain.', a: 'Bower' },
      { q: 'Surname of the English actress whose first names are Millie Bobby.', a: 'Brown' },
      { q: 'The Chevrolet model the police chief drives around town.', a: 'Blazer' },
      { q: 'The grocery store where Eleven first steals frozen waffles.', a: 'Bradley\'s Big Buy' },
      { q: 'The salt-filled makeshift sensory tank the kids build in the school gym.', a: 'Bathtub' },
    ],
    C: [
      { q: 'The cheerleader who becomes the fourth-season villain\'s first victim.', a: 'Chrissy' },
      { q: 'The derelict mansion where a whole family was slaughtered in 1959.', a: 'Creel House' },
      { q: 'The bedsheet-flagged fort in the woods where Will hides out.', a: 'Castle Byers' },
      { q: 'The nickname for the giant hilltop radio antenna built to reach Utah.', a: 'Cerebro' },
      { q: 'Surname of the science teacher who explains parallel dimensions with a paper plate and an acrobat.', a: 'Clarke' },
      { q: 'The British punk band behind Will\'s favourite song.', a: 'The Clash', alt: ['Clash'] },
      { q: 'The state the Byers family moves to after leaving Indiana.', a: 'California' },
      { q: 'Surname of the basketball captain who leads the mob hunting Eddie.', a: 'Carver' },
      { q: 'The blue muscle car Billy roars around town in.', a: 'Camaro' },
      { q: 'The moustached officer who works alongside Powell at the police station.', a: 'Callahan' },
      { q: 'The strung decorations Joyce uses to spell out messages from the other side.', a: 'Christmas lights' },
      { q: 'The big city where Eleven tracks down her psychic sister and her gang.', a: 'Chicago' },
      { q: 'What the fourth-season villain places on his victims, marked by headaches and visions.', a: 'Curse' },
    ],
    D: [
      { q: 'The faceless, petal-mouthed predator the boys name after a tabletop monster.', a: 'Demogorgon' },
      { q: 'Dustin\'s name for the pack of creatures that grow from his pet.', a: 'Demodogs', alt: ['Demodog'] },
      { q: 'The musketeer-inspired name Dustin gives the creature he keeps in his storm cellar.', a: 'Dart', alt: ['D\'Artagnan'] },
      { q: 'The curly-haired boy with cleidocranial dysplasia who loves science and pudding.', a: 'Dustin' },
      { q: 'The identical twins credited as the series creators.', a: 'Duffer Brothers', alt: ['The Duffers', 'Duffers'] },
      { q: 'The tabletop role-playing game the boys are playing in the opening scene.', a: 'Dungeons and Dragons', alt: ['D&D'] },
      { q: 'The first name of the Soviet guard who calls himself Enzo.', a: 'Dmitri' },
      { q: 'The swarm of flying creatures guarding the villain\'s lair.', a: 'Demobats', alt: ['Demobat'] },
      { q: 'Surname of the actress Natalia who plays Nancy.', a: 'Dyer' },
      { q: 'The arcade cabinet where a new top score stuns the boys in the second season.', a: 'Dig Dug' },
      { q: 'The role Eddie plays at the head of the gaming table.', a: 'Dungeon Master' },
    ],
    E: [
      { q: 'The shaven-headed girl with a number tattooed on her forearm.', a: 'Eleven', alt: ['El', '011'] },
      { q: 'The frozen waffle brand that becomes her favourite food.', a: 'Eggo', alt: ['Eggos'] },
      { q: 'The long-haired gaming club president who shreds metal in the other dimension.', a: 'Eddie Munson', alt: ['Eddie'] },
      { q: 'The code name Hopper picks for his Soviet contact, borrowed from a restaurant.', a: 'Enzo' },
      { q: 'Lucas\'s sharp-tongued little sister who crawls through the Soviet air duct.', a: 'Erica' },
      { q: 'Surname of the horror legend Robert who plays the imprisoned Victor.', a: 'Englund' },
      { q: 'Surname of the Princess Bride actor Cary who plays the corrupt mayor.', a: 'Elwes' },
      { q: 'The 1982 Spielberg film about a hidden visitor whose blonde-wig disguise Eleven echoes.', a: 'E.T.', alt: ['ET'] },
      { q: 'The number that identified Eleven\'s psychic sister at the laboratory.', a: 'Eight', alt: ['008'] },
    ],
    F: [
      { q: 'The nickname for the townspeople melted together by the shadow monster.', a: 'The Flayed', alt: ['Flayed'] },
      { q: 'The rental shop where Steve and Robin work in the fourth season.', a: 'Family Video' },
      { q: 'The nervous student reporter who dies second in the fourth season.', a: 'Fred Benson', alt: ['Fred'] },
      { q: 'Surname of the young actress Priah who plays Erica.', a: 'Ferguson' },
      { q: 'The hairspray brand Steve swears by, named after a Charlie\'s Angels star.', a: 'Farrah Fawcett' },
      { q: 'The Stephen King novel about a girl with pyrokinesis that clearly inspired Eleven.', a: 'Firestarter' },
      { q: 'The trailer park where Eddie lives with his uncle.', a: 'Forest Hills' },
      { q: 'Surname of the actor Eduardo who plays Argyle.', a: 'Franco' },
      { q: 'The three-word rule about honesty that Eleven learns from Mike.', a: 'Friends don\'t lie' },
    ],
    G: [
      { q: 'The 1984 comedy whose proton-pack costumes the boys wear for Halloween.', a: 'Ghostbusters' },
      { q: 'The pulsing rift in the laboratory wall joining the two worlds.', a: 'The Gate', alt: ['Gate'] },
      { q: 'The hulking Soviet assassin the police chief nicknames after a killer robot.', a: 'Grigori' },
      { q: 'The 1985 Spielberg-produced kids adventure that the bike-riding gang evokes.', a: 'The Goonies', alt: ['Goonies'] },
      { q: 'Surname of the actor Brett who plays the paranoid investigator.', a: 'Gelman' },
      { q: 'The southern US state that stands in for Indiana during filming.', a: 'Georgia' },
      { q: 'The ticking antique timepiece that appears in visions before the villain strikes.', a: 'Grandfather clock' },
    ],
    H: [
      { q: 'The fictional Indiana town where the story is set.', a: 'Hawkins' },
      { q: 'Surname of the gruff police chief who becomes Eleven\'s adoptive father.', a: 'Hopper' },
      { q: 'The name of the high-school gaming society Eddie presides over.', a: 'Hellfire Club' },
      { q: 'The birth name of the boy who grew up to become the fourth-season villain.', a: 'Henry Creel', alt: ['Henry'] },
      { q: 'The Wheelers\' toddler daughter.', a: 'Holly' },
      { q: 'Surname of the actor Charlie who plays Jonathan.', a: 'Heaton' },
      { q: 'Surname of the actor David who plays the police chief.', a: 'Harbour' },
      { q: 'Surname of the actress Maya who plays Robin.', a: 'Hawke' },
      { q: 'Surname of Nancy\'s doomed best friend Barb.', a: 'Holland' },
      { q: 'Surname of the great-haired babysitter who fights with a spiked plank.', a: 'Harrington' },
      { q: 'Surname of Max and her bullying stepbrother\'s family.', a: 'Hargrove' },
      { q: 'The single-screen cinema in town where the kids sneak into films.', a: 'The Hawk', alt: ['Hawk'] },
      { q: 'The brand of ham radio kit Mr. Clarke lends the boys.', a: 'Heathkit' },
      { q: 'The lifeguard colleague of Billy who is the first person taken in the third season.', a: 'Heather' },
      { q: 'The local newspaper where Nancy works as an intern.', a: 'Hawkins Post' },
      { q: 'The autumn holiday when the boys dress up as the proton-pack crew.', a: 'Halloween' },
      { q: 'The Bowie song covered by Peter Gabriel over the scene at the flooded pit.', a: 'Heroes' },
      { q: 'The secret government research facility on the edge of town.', a: 'Hawkins Lab', alt: ['Hawkins National Laboratory'] },
      { q: 'The senior school Nancy, Steve and Jonathan attend.', a: 'Hawkins High' },
      { q: 'The surname of Dustin and his mother.', a: 'Henderson' },
    ],
    I: [
      { q: 'The Midwestern state where the town of Hawkins sits.', a: 'Indiana' },
      { q: 'Surname of Eleven\'s biological mother Terry.', a: 'Ives' },
      { q: 'The big city where Will and Jonathan\'s deadbeat father lives.', a: 'Indianapolis' },
    ],
    J: [
      { q: 'Will\'s frantic mother, who talks to her son through Christmas lights.', a: 'Joyce' },
      { q: 'Will\'s photographer older brother.', a: 'Jonathan' },
      { q: 'The birth name Eleven\'s mother gave her.', a: 'Jane' },
      { q: 'The 1975 shark thriller the creators cite for withholding the monster.', a: 'Jaws' },
      { q: 'The police chief\'s first name.', a: 'Jim' },
      { q: 'The scrapyard where the kids trap the creature using an abandoned bus.', a: 'Junkyard' },
    ],
    K: [
      { q: 'The English singer whose 1985 hit pulls Max back from the villain.', a: 'Kate Bush' },
      { q: 'Eleven\'s psychic sister, Subject Eight, who conjures illusions.', a: 'Kali' },
      { q: 'Mike\'s mother, who almost has an affair with a lifeguard.', a: 'Karen' },
      { q: 'Surname of the actor Joe who plays Steve.', a: 'Keery' },
      { q: 'The frozen Soviet region where the police chief is held in a labour camp.', a: 'Kamchatka' },
      { q: 'Surname of the corrupt mayor bribed by the Russians.', a: 'Kline' },
      { q: 'The device the Soviets build under the mall to force the rift open.', a: 'The Key', alt: ['Key'] },
    ],
    L: [
      { q: 'The boy in the red bandana who becomes a basketball star.', a: 'Lucas' },
      { q: 'The water where Steve dives and is dragged through by bats.', a: 'Lover\'s Lake' },
      { q: 'The California town where the Byers family starts over.', a: 'Lenora Hills', alt: ['Lenora'] },
      { q: 'The singer of the Neverending Story theme that Dustin and Suzie duet.', a: 'Limahl' },
      { q: 'Surname of the executive producer and frequent director whose first name is Shawn.', a: 'Levy' },
      { q: 'The name of Will and Jonathan\'s absent, deadbeat father.', a: 'Lonnie' },
      { q: 'The Star Wars smuggler Dustin invokes when accusing a friend of betrayal.', a: 'Lando' },
    ],
    M: [
      { q: 'The Wheeler boy who hides Eleven in his basement.', a: 'Mike' },
      { q: 'The skateboarding redhead who arrives from California in the second season.', a: 'Max' },
      { q: 'The towering shadow creature from the tabletop manual that possesses Will.', a: 'Mind Flayer' },
      { q: 'The paranoid investigator with a soundproofed house and a Russian vocabulary.', a: 'Murray' },
      { q: 'The boys\' Tolkien-inspired nickname for the road where Will vanishes.', a: 'Mirkwood' },
      { q: 'The general store in town where Joyce works behind the counter.', a: 'Melvald\'s', alt: ['Melvalds'] },
      { q: 'The 1986 Metallica track Eddie plays to lure the bats away.', a: 'Master of Puppets' },
      { q: 'The original working title of the series, a Long Island town.', a: 'Montauk' },
      { q: 'The Byers family cat, eaten in the second season.', a: 'Mews' },
      { q: 'Surname of the actor Gaten who plays Dustin.', a: 'Matarazzo' },
      { q: 'Surname of the actor Matthew who plays Papa.', a: 'Modine' },
      { q: 'Surname of the actor Caleb who plays Lucas.', a: 'McLaughlin' },
      { q: 'Surname of the Australian actor Dacre who plays the lifeguard bully.', a: 'Montgomery' },
      { q: 'The high-score name on the arcade cabinet that stuns the boys in the second season.', a: 'MADMAX' },
      { q: 'The residential road the Wheeler family lives on, name-checked in an episode title.', a: 'Maple Street', alt: ['Maple'] },
      { q: 'The thrash band whose 1986 anthem Eddie performs on a trailer roof.', a: 'Metallica' },
    ],
    N: [
      { q: 'The Wheeler daughter who becomes a reporter and grabs a shotgun.', a: 'Nancy' },
      { q: 'The streaming service that has released every season.', a: 'Netflix' },
      { q: 'The 1985 soft-drink reformulation Lucas raves about at the mall.', a: 'New Coke' },
      { q: 'The code name of the desert facility where Eleven regains her powers in a tank.', a: 'Nina', alt: ['Project Nina'] },
      { q: 'The physical side effect that appears whenever Eleven strains her powers.', a: 'Nosebleed' },
      { q: 'Steve\'s signature weapon, a plank studded with sharp points.', a: 'Nail bat', alt: ['Nailbat'] },
      { q: 'The clawed 1984 Wes Craven dream-stalker played by the actor cast as Victor Creel.', a: 'Freddy Krueger', alt: ['Freddy'] },
      { q: 'The 1984 fantasy film whose theme song Dustin sings over the radio.', a: 'The Neverending Story' },
      { q: 'The month of 1983 in which Will vanishes on his way home.', a: 'November' },
    ],
    O: [
      { q: 'Surname of the sympathetic government doctor played by Paul Reiser.', a: 'Owens' },
      { q: 'The number the villain was given as the laboratory\'s first test child.', a: 'One', alt: ['001', 'Subject One'] },
    ],
    P: [
      { q: 'The name Eleven is made to call the man who raised her in the laboratory.', a: 'Papa' },
      { q: 'The video-game hall where Dustin discovers the new record holder.', a: 'Palace Arcade', alt: ['The Palace'] },
      { q: 'Surname of the actress Shannon who played Nancy\'s doomed friend.', a: 'Purser' },
      { q: 'The tadpole-like creature Dustin finds in his trash can.', a: 'Pollywog' },
      { q: 'The asylum where Nancy and Robin interview the imprisoned Victor.', a: 'Pennhurst' },
      { q: 'The basketball player killed above the lake, the villain\'s third victim.', a: 'Patrick' },
      { q: 'The English musician whose slow cover of Bowie\'s Heroes closes an early episode.', a: 'Peter Gabriel' },
      { q: 'The deputy who searches the woods alongside Callahan and the chief.', a: 'Powell' },
    ],
    Q: [
      { q: 'Surname of the British actor Joseph who plays Eddie.', a: 'Quinn' },
      { q: 'The flooded rock pit where a fake body is pulled from the water.', a: 'Quarry' },
    ],
    R: [
      { q: 'The sharp-witted mall coworker who comes out to Steve in a bathroom.', a: 'Robin' },
      { q: 'The US president whose re-election signs dot the town in 1984.', a: 'Reagan' },
      { q: 'The California roller-skating venue where Eleven is humiliated.', a: 'Rink-O-Mania' },
      { q: 'Surname of the actress Winona who plays Joyce.', a: 'Ryder' },
      { q: 'Surname of the actor Paul who plays Doctor Owens.', a: 'Reiser' },
      { q: 'The electronics chain where Bob manages the store.', a: 'RadioShack', alt: ['Radio Shack'] },
      { q: 'The vermin that swarm to the old mill and burst into goo in the third season.', a: 'Rats' },
      { q: 'The nickname of the dealer whose lakeside house Eddie hides out in.', a: 'Reefer Rick' },
    ],
    S: [
      { q: 'The former king of the high school who becomes an unlikely babysitter.', a: 'Steve' },
      { q: 'The glossy new shopping mall built over a Soviet base.', a: 'Starcourt' },
      { q: 'The nautical-themed ice cream parlour where the staff wear sailor hats.', a: 'Scoops Ahoy' },
      { q: 'Dustin\'s brilliant girlfriend in Utah with a huge Mormon family.', a: 'Suzie' },
      { q: 'Surname of the family that includes Lucas and Erica.', a: 'Sinclair' },
      { q: 'Surname of the actress Sadie who plays Max.', a: 'Sink' },
      { q: 'Surname of the actor Noah who plays Will.', a: 'Schnapp' },
      { q: 'Surname of the military colonel who hunts Eleven in the fourth season.', a: 'Sullivan' },
      { q: 'The takeaway restaurant whose delivery van the California group drives cross-country.', a: 'Surfer Boy Pizza', alt: ['Surfer Boy'] },
      { q: 'The stone formation in the woods used as a meeting point.', a: 'Skull Rock' },
      { q: 'The Austin band whose Kyle Dixon and Michael Stein composed the theme music.', a: 'Survive' },
      { q: 'The frozen convenience-store drink Alexei becomes addicted to.', a: 'Slurpee' },
      { q: 'The name of the daughter the police chief lost to cancer.', a: 'Sara' },
      { q: 'The author of It and Carrie whose work the show constantly nods to.', a: 'Stephen King' },
      { q: 'The steam room where the group tests Billy with extreme heat.', a: 'Sauna' },
      { q: 'The winter middle-school dance where Mike and Eleven finally kiss.', a: 'Snow Ball' },
    ],
    T: [
      { q: 'The multi-headed monster the boys defeat in their campaign at the end of the first season.', a: 'Thessalhydra' },
      { q: 'The classmate Robin confesses to crushing on, surprising Steve.', a: 'Tammy Thompson', alt: ['Tammy'] },
      { q: 'The power to move objects with the mind, Eleven\'s main ability.', a: 'Telekinesis' },
      { q: 'Mike\'s oblivious father, usually asleep in his armchair.', a: 'Ted' },
      { q: 'Steve\'s obnoxious friend who helps deface the cinema marquee about Nancy.', a: 'Tommy H', alt: ['Tommy'] },
      { q: 'The vine-choked underground network spreading beneath the town in the second season.', a: 'Tunnels' },
      { q: 'The 1984 Cameron film whose killer robot inspires a nickname for a Soviet agent.', a: 'The Terminator', alt: ['Terminator'] },
    ],
    U: [
      { q: 'The dark, ash-filled mirror dimension beneath the town.', a: 'Upside Down', alt: ['The Upside Down'] },
      { q: 'The state where Dustin\'s long-distance girlfriend lives.', a: 'Utah' },
      { q: 'The country whose scientists build a machine under the mall.', a: 'USSR', alt: ['Soviet Union', 'Russia'] },
      { q: 'The boat-shaped sundae served at the mall ice cream counter.', a: 'USS Butterscotch' },
    ],
    V: [
      { q: 'The name Dustin gives the fourth-season villain, taken from a tabletop lich.', a: 'Vecna' },
      { q: 'The imprisoned father blamed for the 1959 killings in his own home.', a: 'Victor Creel', alt: ['Victor'] },
      { q: 'The black, watery mental space where Eleven searches for people.', a: 'The Void', alt: ['Void'] },
      { q: 'The band-geek girl Robin falls for in the fourth season.', a: 'Vickie' },
      { q: 'The creeping tendrils of the hive mind that recoil when burned.', a: 'Vines' },
      { q: 'The wife of the imprisoned Victor, found dead with her eyes removed.', a: 'Virginia' },
      { q: 'The chapter of Mr. Clarke\'s tabletop book describing a dark reflection world.', a: 'Vale of Shadows' },
      { q: 'Surname of the actress Grace who plays the doomed cheerleader.', a: 'Van Dien' },
    ],
    W: [
      { q: 'The boy who disappears on his bike in the very first episode.', a: 'Will' },
      { q: 'Surname of the family with three children including Mike and Nancy.', a: 'Wheeler' },
      { q: 'Surname of the Canadian actor Finn who plays Mike.', a: 'Wolfhard' },
      { q: 'The handheld two-way radio the boys use, a Supercom model.', a: 'Walkie-talkie', alt: ['Walkie talkie'] },
      { q: 'The portable cassette player Max wears when the song saves her.', a: 'Walkman' },
      { q: 'Eddie\'s uncle, who shares his trailer.', a: 'Wayne' },
      { q: 'The hilltop where the kids build their giant antenna, named for a Tolkien landmark.', a: 'Weathertop' },
      { q: 'Surname of the German actor Tom who plays Dmitri.', a: 'Wlaschiha' },
      { q: 'The disguise item Eleven wears with a pink dress when hiding in plain sight.', a: 'Wig' },
    ],
    Y: [
      { q: 'The name of Dustin\'s pet turtle.', a: 'Yertle' },
      { q: 'The Soviet smuggler with a peanut-butter plane who betrays Joyce and Murray.', a: 'Yuri' },
    ],
  },
};
