import type { RawPack } from '../core/packs';

export const fandomHarryPotterPack: RawPack = {
  id: 'fandom-harry-potter',
  name: 'Harry Potter',
  description: 'Spells, houses, creatures and castle lore from the seven books and eight films.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '⚡',
  accent: '#6d28d9',
  letters: {
    A: [
      { q: 'The wizard prison on a bleak island in the North Sea.', a: 'Azkaban' },
      { q: 'The blind Acromantula raised by Hagrid in a castle cupboard.', a: 'Aragog' },
      { q: 'The Summoning Charm Harry masters to fetch his broom in the first Triwizard task.', a: 'Accio' },
      { q: 'The charm that unlocks doors.', a: 'Alohomora' },
      { q: 'The bitter Squib caretaker of Hogwarts.', a: 'Argus Filch', alt: ['Filch'] },
      { q: 'The long-bearded headmaster of Hogwarts for most of the series.', a: 'Albus Dumbledore', alt: ['Dumbledore'] },
      { q: 'The scarred ex-Auror with a magical spinning eye who joins the staff in Harry\'s fourth year.', a: 'Alastor Moody', alt: ['Mad-Eye Moody', 'Moody'] },
      { q: 'The headmaster\'s brother, landlord of the Hog\'s Head.', a: 'Aberforth', alt: ['Aberforth Dumbledore'] },
      { q: 'The headmaster\'s young sister, killed in a three-way duel at Godric\'s Hollow.', a: 'Ariana', alt: ['Ariana Dumbledore'] },
      { q: 'The incantation of the Killing Curse.', a: 'Avada Kedavra' },
      { q: 'The term for a witch or wizard able to turn into a particular animal at will.', a: 'Animagus' },
      { q: 'The most powerful love potion in the world, which smells different to every person.', a: 'Amortentia' },
      { q: 'The Ministry official father of the Hufflepuff champion.', a: 'Amos Diggory', alt: ['Amos'] },
      { q: 'The Ministry\'s title for a trained dark-wizard catcher.', a: 'Auror' },
      { q: 'The actor who played the Potions master in the films.', a: 'Alan Rickman' },
    ],
    B: [
      { q: 'The wild-haired Death Eater who kills Sirius in the Department of Mysteries.', a: 'Bellatrix Lestrange', alt: ['Bellatrix'] },
      { q: 'The eldest of Ron\'s brothers, a curse-breaker for the wizarding bank who marries Fleur.', a: 'Bill Weasley', alt: ['Bill'] },
      { q: 'The Hippogriff sentenced to death after Draco provoked him.', a: 'Buckbeak' },
      { q: 'The shape-shifting creature that becomes whatever the viewer fears most.', a: 'Boggart' },
      { q: 'The stone taken from a goat\'s stomach that acts as an antidote to most poisons.', a: 'Bezoar' },
      { q: 'The warm frothy drink students order in the pubs of the wizarding village.', a: 'Butterbeer' },
      { q: 'The heavy black ball that Beaters knock towards opposing players.', a: 'Bludger' },
      { q: 'The French wizarding school led by the half-giantess Madame Maxime.', a: 'Beauxbatons' },
      { q: 'The droning ghost professor of History of Magic.', a: 'Binns', alt: ['Professor Binns', 'Cuthbert Binns'] },
      { q: 'The giant serpent that Salazar Slytherin left hidden beneath the castle.', a: 'Basilisk' },
      { q: 'The elderly author of A History of Magic, whose corpse concealed a snake.', a: 'Bathilda Bagshot', alt: ['Bathilda'] },
      { q: 'The crooked, many-storeyed family home of Ron\'s parents.', a: 'The Burrow', alt: ['Burrow'] },
      { q: 'The wizarding sweets sold in a huge range of tastes, including earwax and vomit.', a: 'Bertie Bott\'s Every Flavour Beans', alt: ['Bertie Botts', 'Every Flavour Beans'] },
    ],
    C: [
      { q: 'The Hufflepuff champion killed in a graveyard at the end of the fourth book.', a: 'Cedric Diggory', alt: ['Cedric'] },
      { q: 'The Ravenclaw Seeker Harry takes to the Yule Ball.', a: 'Cho Chang', alt: ['Cho'] },
      { q: 'The hidden underground room opened by an heir of Salazar Slytherin.', a: 'Chamber of Secrets' },
      { q: 'The bowler-hatted Minister for Magic who refuses to admit the Dark Lord has returned.', a: 'Cornelius Fudge', alt: ['Fudge'] },
      { q: 'Hermione\'s bandy-legged ginger cat, part Kneazle.', a: 'Crookshanks' },
      { q: 'The thickset Slytherin henchman of Draco who dies in a Fiendfyre blaze.', a: 'Crabbe', alt: ['Vincent Crabbe'] },
      { q: 'The brother of Ron who works with dragons in Romania.', a: 'Charlie Weasley', alt: ['Charlie'] },
      { q: 'The Unforgivable used to inflict unbearable pain on a victim.', a: 'Cruciatus Curse', alt: ['Cruciatus'] },
      { q: 'Ron\'s hopeless favourite Quidditch team, whose motto is about crossing fingers.', a: 'Chudley Cannons' },
      { q: 'The star-struck Gryffindor first year who follows Harry around with a camera.', a: 'Colin Creevey', alt: ['Colin'] },
      { q: 'The 2016 stage play sequel that follows Harry\'s son Albus Severus.', a: 'The Cursed Child', alt: ['Cursed Child'] },
      { q: 'The elective subject Hagrid begins teaching in Harry\'s third year.', a: 'Care of Magical Creatures' },
    ],
    D: [
      { q: 'The hooded guards of the wizard prison, who feed on happiness.', a: 'Dementors', alt: ['Dementor'] },
      { q: 'Harry\'s pale schoolyard rival, a Slytherin boy from a wealthy pure-blood family.', a: 'Draco Malfoy', alt: ['Draco'] },
      { q: 'Harry\'s spoiled cousin, who bullies him at Number Four.', a: 'Dudley Dursley', alt: ['Dudley'] },
      { q: 'The house-elf freed when Harry hides a sock inside a diary.', a: 'Dobby' },
      { q: 'The collective name for the three legendary objects sought by the Peverell brothers\' heirs.', a: 'Deathly Hallows', alt: ['Hallows'] },
      { q: 'The hidden London shopping street reached through the Leaky Cauldron.', a: 'Diagon Alley' },
      { q: 'The northern European wizarding school known for teaching the Dark Arts.', a: 'Durmstrang' },
      { q: 'The pink-clad High Inquisitor who decorates her office with kitten plates.', a: 'Dolores Umbridge', alt: ['Umbridge'] },
      { q: 'The Gryffindor boy and West Ham supporter who dates Ginny.', a: 'Dean Thomas', alt: ['Dean'] },
      { q: 'The actor who plays the title role in all eight films.', a: 'Daniel Radcliffe' },
      { q: 'The secret defence club Harry taught in the castle\'s hidden seventh-floor space.', a: 'Dumbledore\'s Army', alt: ['DA'] },
      { q: 'The silver device left to Ron in a will, which captures and releases light.', a: 'Deluminator' },
    ],
    E: [
      { q: 'The Disarming Charm that becomes Harry\'s signature spell.', a: 'Expelliarmus' },
      { q: 'The incantation for conjuring a silver guardian against the prison guards.', a: 'Expecto Patronum' },
      { q: 'The most powerful of the three Hallows, once owned by Grindelwald and later by the headmaster.', a: 'Elder Wand' },
      { q: 'The ancient and accident-prone owl belonging to Ron\'s family.', a: 'Errol' },
      { q: 'The actress who plays the cleverest witch of Harry\'s year.', a: 'Emma Watson' },
      { q: 'The enchanted mirror that shows the deepest desire of the viewer\'s heart carries this name.', a: 'Erised' },
      { q: 'The flesh-coloured listening devices the twins invent for eavesdropping through doors.', a: 'Extendable Ears' },
      { q: 'The healing spell Tonks uses to mend Harry\'s broken nose.', a: 'Episkey' },
      { q: 'The huge African beast whose horn explodes on impact.', a: 'Erumpent' },
    ],
    F: [
      { q: 'The three-headed dog guarding a trapdoor on the third floor.', a: 'Fluffy' },
      { q: 'The headmaster\'s scarlet bird, which bursts into flame and is reborn from the ashes.', a: 'Fawkes' },
      { q: 'The silver-blonde champion of the French school, who later marries into Ron\'s family.', a: 'Fleur Delacour', alt: ['Fleur'] },
      { q: 'The twin brother of George who was killed during the Battle of Hogwarts.', a: 'Fred Weasley', alt: ['Fred'] },
      { q: 'The palomino centaur who rescues Harry in the Forbidden Forest and later teaches Divination.', a: 'Firenze' },
      { q: 'The tiny Charms teacher and head of Ravenclaw house.', a: 'Filius Flitwick', alt: ['Flitwick'] },
      { q: 'The potion of liquid luck offered as a class prize in Harry\'s sixth year.', a: 'Felix Felicis' },
      { q: 'The Newt Scamander textbook that lends its title to a 2016 spin-off film.', a: 'Fantastic Beasts' },
      { q: 'The glittering green dust thrown into a fire to travel from hearth to hearth.', a: 'Floo Powder' },
      { q: 'The savage Death Eater wolf who bit Remus Lupin as a child.', a: 'Fenrir Greyback', alt: ['Greyback'] },
      { q: 'The racing broom Sirius sends Harry anonymously for Christmas.', a: 'Firebolt' },
    ],
    G: [
      { q: 'The Hogwarts house of the lion, in scarlet and gold.', a: 'Gryffindor' },
      { q: 'The wizarding bank in London staffed by goblins.', a: 'Gringotts' },
      { q: 'The youngest of Ron\'s siblings and the only girl, who Harry eventually marries.', a: 'Ginny Weasley', alt: ['Ginny'] },
      { q: 'The vain, golden-haired Defence teacher who loses his memory to a backfiring charm.', a: 'Gilderoy Lockhart', alt: ['Lockhart'] },
      { q: 'The dark wizard defeated in a famous 1945 duel.', a: 'Grindelwald', alt: ['Gellert Grindelwald'] },
      { q: 'The West Country village where Harry\'s parents were killed.', a: 'Godric\'s Hollow' },
      { q: 'The wooden cup that spits out the names of the chosen champions.', a: 'Goblet of Fire' },
      { q: 'The gloomy London house that serves as headquarters for the Order of the Phoenix.', a: 'Grimmauld Place' },
      { q: 'The other large Slytherin boy who follows Draco everywhere.', a: 'Gregory Goyle', alt: ['Goyle'] },
      { q: 'Hagrid\'s sixteen-foot giant half-brother.', a: 'Grawp' },
      { q: 'The slimy plant Harry eats to grow gills for the second task.', a: 'Gillyweed' },
      { q: 'The goblin who helps the trio break into Bellatrix\'s vault.', a: 'Griphook' },
    ],
    H: [
      { q: 'The Scottish castle school of witchcraft and wizardry.', a: 'Hogwarts' },
      { q: 'The Muggle-born witch who is top of Harry\'s year.', a: 'Hermione Granger', alt: ['Hermione'] },
      { q: 'The half-giant Keeper of Keys and Grounds who lives in a hut by the forest.', a: 'Hagrid', alt: ['Rubeus Hagrid'] },
      { q: 'The house of the badger, known for hard work and loyalty.', a: 'Hufflepuff' },
      { q: 'Harry\'s snowy owl, a birthday present from the gamekeeper.', a: 'Hedwig' },
      { q: 'The only all-wizarding village in Britain, visited by older students at weekends.', a: 'Hogsmeade' },
      { q: 'An object in which a dark wizard conceals a torn piece of his soul.', a: 'Horcrux' },
      { q: 'The nickname written inside Harry\'s second-hand Potions textbook.', a: 'Half-Blood Prince' },
      { q: 'The creature with an eagle\'s front half and a horse\'s hindquarters.', a: 'Hippogriff' },
      { q: 'The village sweetshop with a secret tunnel into the castle cellars.', a: 'Honeydukes' },
      { q: 'The scarlet envelope that screams its message at the recipient.', a: 'Howler' },
      { q: 'The withered severed limb sold in a dark shop that gives light only to its holder.', a: 'Hand of Glory' },
    ],
    I: [
      { q: 'The Hallow that James left in the headmaster\'s keeping and Harry received one Christmas.', a: 'Invisibility Cloak' },
      { q: 'The Unforgivable that gives one wizard total control over another\'s actions.', a: 'Imperius Curse', alt: ['Imperius'] },
      { q: 'The reanimated corpses that guard a locket in the lake of a seaside cave.', a: 'Inferi' },
      { q: 'The jinx that slows or halts an oncoming attacker.', a: 'Impedimenta' },
      { q: 'The national team that beat Bulgaria in the 1994 Quidditch World Cup final.', a: 'Ireland' },
    ],
    J: [
      { q: 'Harry\'s father, a Gryffindor Chaser whose Animagus form was a stag.', a: 'James Potter', alt: ['James'] },
      { q: 'The British author of the seven novels.', a: 'J. K. Rowling', alt: ['Rowling', 'Joanne Rowling'] },
      { q: 'The Muggle-born Hufflepuff boy petrified by the monster of the Chamber.', a: 'Justin Finch-Fletchley', alt: ['Justin'] },
      { q: 'The actor who plays Draco\'s long-haired father in the films.', a: 'Jason Isaacs' },
    ],
    K: [
      { q: 'The bitter old house-elf who served the Black family for generations.', a: 'Kreacher' },
      { q: 'The Bulgarian Seeker who competes for Durmstrang in the Triwizard Tournament.', a: 'Krum', alt: ['Viktor Krum'] },
      { q: 'The London railway station where platform nine and three-quarters is hidden.', a: 'King\'s Cross' },
      { q: 'The deep-voiced Auror who becomes Minister for Magic after the war.', a: 'Kingsley Shacklebolt', alt: ['Kingsley'] },
      { q: 'The dark side street of shops selling shrunken heads, where Harry lands after a Floo mishap.', a: 'Knockturn Alley' },
      { q: 'The goateed Durmstrang headmaster and former Death Eater who flees the Tournament.', a: 'Karkaroff', alt: ['Igor Karkaroff'] },
    ],
    L: [
      { q: 'The dreamy Ravenclaw girl who believes in Crumple-Horned Snorkacks.', a: 'Luna Lovegood', alt: ['Luna'] },
      { q: 'The Death Eater father of Harry\'s Slytherin rival, who slips a cursed diary into Ginny\'s cauldron.', a: 'Lucius Malfoy', alt: ['Lucius'] },
      { q: 'Harry\'s mother, whose sacrifice left him magically protected.', a: 'Lily Potter', alt: ['Lily'] },
      { q: 'The charm that makes a wand tip glow.', a: 'Lumos' },
      { q: 'The shabby pub on Charing Cross Road that hides the entrance to the wizarding street.', a: 'Leaky Cauldron' },
      { q: 'The spell that hoists a victim into the air upside down by one ankle.', a: 'Levicorpus' },
      { q: 'The dreadlocked Gryffindor friend of the twins who commentates on matches.', a: 'Lee Jordan', alt: ['Lee'] },
      { q: 'The Gryffindor girl who smothers Ron with affection in their sixth year.', a: 'Lavender Brown', alt: ['Lavender'] },
      { q: 'The Surrey town where Harry grows up with his aunt and uncle.', a: 'Little Whinging' },
      { q: 'The magical art of delving into another person\'s mind.', a: 'Legilimency' },
      { q: 'The former Beater and head of Magical Games who takes bets at the World Cup.', a: 'Ludo Bagman', alt: ['Bagman'] },
    ],
    M: [
      { q: 'The stern Transfiguration teacher and deputy headmistress.', a: 'Minerva McGonagall', alt: ['McGonagall'] },
      { q: 'The enchanted parchment that shows everyone\'s footsteps inside the castle.', a: 'Marauder\'s Map' },
      { q: 'The plant whose infant screams can be fatal, brewed into a restorative draught.', a: 'Mandrake' },
      { q: 'The wizarding word for a person born with no magic at all.', a: 'Muggle' },
      { q: 'The tearful ghost girl who haunts a second-floor bathroom.', a: 'Moaning Myrtle', alt: ['Myrtle'] },
      { q: 'Ron\'s mother, who duels Bellatrix during the final battle.', a: 'Molly Weasley', alt: ['Molly'] },
      { q: 'The thieving Order member who Disapparates and abandons Moody in mid-air.', a: 'Mundungus Fletcher', alt: ['Mundungus'] },
      { q: 'The Wiltshire mansion where Hermione is tortured by Bellatrix.', a: 'Malfoy Manor' },
      { q: 'The Hogwarts matron in charge of the hospital wing.', a: 'Madam Pomfrey', alt: ['Pomfrey'] },
      { q: 'The scrawny cat belonging to the Hogwarts caretaker.', a: 'Mrs Norris' },
      { q: 'The actor who took over as headmaster from the third film onwards.', a: 'Michael Gambon' },
      { q: 'The actress who plays the stern Transfiguration professor in the films.', a: 'Maggie Smith' },
    ],
    N: [
      { q: 'The clumsy Gryffindor boy who beheads the great snake with a goblin-made blade.', a: 'Neville Longbottom', alt: ['Neville'] },
      { q: 'The Dark Lord\'s great pet serpent, kept close and made into a Horcrux.', a: 'Nagini' },
      { q: 'The Gryffindor house ghost whose neck was severed by a blunt axe, leaving a flap of skin.', a: 'Nearly Headless Nick', alt: ['Sir Nicholas'] },
      { q: 'The broom McGonagall buys Harry when he joins the house team as a first year.', a: 'Nimbus Two Thousand', alt: ['Nimbus 2000'] },
      { q: 'The Magizoologist hero of the prequel film series, who carries a battered suitcase.', a: 'Newt Scamander', alt: ['Newt'] },
      { q: 'The Norwegian Ridgeback dragon Hagrid hatches in his hut.', a: 'Norbert', alt: ['Norberta'] },
      { q: 'The ancient alchemist who made the object guarded by Fluffy.', a: 'Nicolas Flamel', alt: ['Flamel'] },
      { q: 'The fluffy black creature with a long snout, irresistibly drawn to shiny treasure.', a: 'Niffler' },
    ],
    O: [
      { q: 'The secret society the headmaster founded to fight the Death Eaters.', a: 'Order of the Phoenix' },
      { q: 'The London wandmaker whose family has been in the trade since 382 BC.', a: 'Ollivander' },
      { q: 'The memory charm Hermione casts on her parents before leaving home.', a: 'Obliviate' },
      { q: 'The discipline of sealing the mind against magical intrusion.', a: 'Occlumency' },
      { q: 'The Gryffindor Keeper and team captain during Harry\'s early years.', a: 'Oliver Wood' },
    ],
    P: [
      { q: 'The alchemical object that produces the Elixir of Life, guarded on the third floor.', a: 'Philosopher\'s Stone', alt: ['Sorcerer\'s Stone'] },
      { q: 'The Marauder who betrayed Harry\'s parents and hid for years as Ron\'s pet.', a: 'Peter Pettigrew', alt: ['Pettigrew'] },
      { q: 'The name for the silver animal form a wizard conjures for protection; Harry\'s is a stag.', a: 'Patronus' },
      { q: 'The Surrey street where the Dursleys live.', a: 'Privet Drive' },
      { q: 'The pompous third-eldest brother of Ron who becomes a Ministry official.', a: 'Percy Weasley', alt: ['Percy'] },
      { q: 'The thick brew that lets a drinker take on someone else\'s appearance for an hour.', a: 'Polyjuice Potion', alt: ['Polyjuice'] },
      { q: 'The language of snakes, which Harry can speak without realising it.', a: 'Parseltongue' },
      { q: 'The tiny excitable owl Sirius gives Ron to replace his lost rat.', a: 'Pigwidgeon', alt: ['Pig'] },
      { q: 'The pug-faced Slytherin girl who shouts that the school should hand Harry over.', a: 'Pansy Parkinson', alt: ['Pansy'] },
      { q: 'The Herbology teacher and head of the badger house.', a: 'Pomona Sprout', alt: ['Sprout'] },
      { q: 'The mischievous poltergeist who torments students in the corridors.', a: 'Peeves' },
      { q: 'Harry\'s aunt, who is his mother\'s older sister.', a: 'Petunia Dursley', alt: ['Petunia'] },
      { q: 'The shallow stone basin used to store and revisit memories.', a: 'Pensieve' },
    ],
    Q: [
      { q: 'The wizarding sport played on brooms with four balls and six hoops.', a: 'Quidditch' },
      { q: 'The stammering turban-wearing teacher hiding a second face on the back of his head.', a: 'Quirinus Quirrell', alt: ['Quirrell'] },
      { q: 'The red ball thrown through the hoops for ten points.', a: 'Quaffle' },
    ],
    R: [
      { q: 'Harry\'s loyal best friend, from a large family of red-haired siblings.', a: 'Ron Weasley', alt: ['Ron'] },
      { q: 'The werewolf professor who teaches Harry to conjure a silver guardian.', a: 'Remus Lupin', alt: ['Lupin'] },
      { q: 'The hidden seventh-floor space that appears only when someone is in real need.', a: 'Room of Requirement' },
      { q: 'The Daily Prophet reporter with a poison quill who is secretly a beetle Animagus.', a: 'Rita Skeeter', alt: ['Skeeter'] },
      { q: 'The actor who plays Harry\'s red-haired best friend in the films.', a: 'Rupert Grint' },
      { q: 'The Hallow concealed inside the Golden Snitch that the headmaster left to Harry.', a: 'Resurrection Stone' },
      { q: 'The house of the eagle, prizing wit and learning.', a: 'Ravenclaw' },
      { q: 'The charm that defeats a Boggart by forcing it into something funny.', a: 'Riddikulus' },
      { q: 'Sirius\'s younger brother, who turned against the Dark Lord and stole a locket.', a: 'Regulus Black', alt: ['Regulus'] },
      { q: 'The lion-maned Minister for Magic who succeeds Cornelius Fudge.', a: 'Rufus Scrimgeour', alt: ['Scrimgeour'] },
    ],
    S: [
      { q: 'The greasy-haired Potions master whose Patronus was a doe.', a: 'Severus Snape', alt: ['Snape'] },
      { q: 'Harry\'s godfather, who spent twelve years in prison for a crime he did not commit.', a: 'Sirius Black', alt: ['Sirius'] },
      { q: 'The house of the serpent, favoured by ambitious pure-bloods.', a: 'Slytherin' },
      { q: 'The battered talking headwear that decides which house a first year joins.', a: 'Sorting Hat' },
      { q: 'The name Ron gave to his shabby pet rat.', a: 'Scabbers' },
      { q: 'The tiny golden winged ball worth one hundred and fifty points.', a: 'Snitch', alt: ['Golden Snitch'] },
      { q: 'The slashing curse Harry finds in an old textbook and uses on Draco in a bathroom.', a: 'Sectumsempra' },
      { q: 'The Irish Gryffindor boy whose spells keep exploding.', a: 'Seamus Finnigan', alt: ['Seamus'] },
      { q: 'The pimply conductor of the triple-decker Knight Bus.', a: 'Stan Shunpike', alt: ['Stan'] },
      { q: 'The goblin-made silver blade Harry pulls out of the talking hat in the Chamber.', a: 'Sword of Gryffindor' },
      { q: 'The seaside home of Bill and Fleur where the escapees take refuge.', a: 'Shell Cottage' },
      { q: 'The boarded-up village building reputed to be the most haunted in Britain.', a: 'Shrieking Shack' },
      { q: 'The foul-tasting potion that regrows lost bones.', a: 'Skele-Gro' },
      { q: 'The portly Potions teacher who returns in Harry\'s sixth year and collects gifted students.', a: 'Slughorn', alt: ['Horace Slughorn'] },
    ],
    T: [
      { q: 'The birth name of the orphanage boy who grew up to become the Dark Lord.', a: 'Tom Riddle', alt: ['Tom Marvolo Riddle', 'Riddle'] },
      { q: 'The contest between three schools featuring dragons, merpeople and a maze.', a: 'Triwizard Tournament' },
      { q: 'The young Metamorphmagus Auror with changeable hair who marries a werewolf.', a: 'Tonks', alt: ['Nymphadora Tonks'] },
      { q: 'The tiny hourglass on a chain McGonagall gives Hermione for her packed timetable.', a: 'Time-Turner' },
      { q: 'The skeletal winged horse visible only to those who have witnessed a death.', a: 'Thestral' },
      { q: 'The Divination teacher who made the true prophecy about the boy who could defeat the Dark Lord.', a: 'Trelawney', alt: ['Sybill Trelawney'] },
      { q: 'The village inn run by Madam Rosmerta.', a: 'Three Broomsticks' },
      { q: 'The twelve-foot creature Harry and Ron knock out in a bathroom on Halloween.', a: 'Troll' },
      { q: 'The actor who plays Harry\'s blond Slytherin rival in the films.', a: 'Tom Felton' },
    ],
    U: [
      { q: 'The collective name for the three most evil spells in wizarding law.', a: 'Unforgivable Curses', alt: ['Unforgivables'] },
      { q: 'The African wizarding school, the largest in the world.', a: 'Uagadou' },
    ],
    V: [
      { q: 'The name the Dark Lord chose for himself, which most witches and wizards dare not speak.', a: 'Voldemort', alt: ['Lord Voldemort'] },
      { q: 'Harry\'s bullying uncle, a director at the drill firm Grunnings.', a: 'Vernon Dursley', alt: ['Vernon', 'Uncle Vernon'] },
      { q: 'The alluring part-human beings whose blood Fleur inherits from her grandmother.', a: 'Veela' },
      { q: 'The broken cupboard Draco repairs to smuggle Death Eaters into the school.', a: 'Vanishing Cabinet' },
      { q: 'The colourless truth potion, three drops of which force honesty.', a: 'Veritaserum' },
    ],
    W: [
      { q: 'The levitation charm first years practise on feathers.', a: 'Wingardium Leviosa' },
      { q: 'The high court of wizarding law that tries Harry for underage magic.', a: 'Wizengamot' },
      { q: 'The joke shop the twins open in Diagon Alley.', a: 'Weasleys\' Wizard Wheezes', alt: ['Wizard Wheezes'] },
      { q: 'A person who transforms into a savage beast under the full moon.', a: 'Werewolf' },
      { q: 'The violent tree planted to hide the tunnel a young transforming student used.', a: 'Whomping Willow' },
      { q: 'The Marauder nickname of the traitor who spent years as a rat.', a: 'Wormtail' },
    ],
    X: [
      { q: 'The eccentric editor of The Quibbler, father of a dreamy Ravenclaw girl.', a: 'Xenophilius Lovegood', alt: ['Xenophilius'] },
    ],
    Y: [
      { q: 'The formal Christmas dance held during the Triwizard Tournament.', a: 'Yule Ball' },
      { q: 'The Death Eater at the Ministry who clings on as the trio Disapparate from Grimmauld Place.', a: 'Yaxley' },
    ],
    Z: [
      { q: 'The Slytherin classmate of Harry whose mother is a beautiful witch rumoured to have widowed herself seven times (surname).', a: 'Zabini', alt: ['Blaise Zabini'] },
      { q: 'The village joke shop popular with students before the twins opened their own.', a: 'Zonko\'s', alt: ['Zonkos'] },
    ],
  },
};
