import type { RawPack } from '../core/packs';

export const fandomStarWarsPack: RawPack = {
  id: 'fandom-star-wars',
  name: 'Star Wars',
  description: 'A galaxy far, far away: heroes, ships, planets, droids and the Force.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🌌',
  accent: '#1d4ed8',
  letters: {
    A: [
      { q: 'The slave boy who wins the Boonta Eve podrace and later falls to the dark side.', a: 'Anakin Skywalker', alt: ['Anakin'] },
      { q: 'The padawan assigned to Anakin during the Clone Wars who later walks away from the Order.', a: 'Ahsoka Tano', alt: ['Ahsoka'] },
      { q: 'The peaceful world destroyed to demonstrate the power of the Empire\'s battle station.', a: 'Alderaan' },
      { q: 'The fish-like admiral who declares the Rebel fleet has flown into a trap at Endor.', a: 'Ackbar', alt: ['Admiral Ackbar'] },
      { q: 'The remote ocean world of stone huts where the first Jedi temple stands.', a: 'Ahch-To' },
      { q: 'The four-legged armoured Imperial walker that leads the assault on the Rebel ice base.', a: 'AT-AT', alt: ['All Terrain Armored Transport'] },
      { q: 'The two-legged Imperial scout walker that Ewoks topple with swinging logs.', a: 'AT-ST', alt: ['Scout walker'] },
      { q: 'The English actor who has appeared in all nine saga films as a golden protocol droid.', a: 'Anthony Daniels' },
      { q: 'The blue-skinned Twi\'lek Jedi shot in the back by her own clones on a fungal jungle world.', a: 'Aayla Secura' },
      { q: 'The pale Dathomirian assassin who serves Count Dooku in the animated Clone Wars.', a: 'Asajj Ventress', alt: ['Ventress'] },
      { q: 'The pale bounty hunter with a long topknot antenna who mentors a young Boba Fett.', a: 'Aurra Sing' },
      { q: 'The highland world where a rebel cell robs an Imperial payroll in Andor.', a: 'Aldhani' },
    ],
    B: [
      { q: 'The armoured bounty hunter who claims a frozen smuggler on the cloud world and takes him to Jabba.', a: 'Boba Fett' },
      { q: 'The gas giant whose floating colony is mined for tibanna gas.', a: 'Bespin' },
      { q: 'The reptilian bounty hunter standing in the lineup aboard Darth Vader\'s flagship.', a: 'Bossk' },
      { q: 'The rolling white and orange astromech belonging to a Resistance pilot.', a: 'BB-8' },
      { q: 'The Alderaanian senator who adopts a newborn girl at the end of the prequel trilogy.', a: 'Bail Organa' },
      { q: 'The Mandalorian warrior and sister of Duchess Satine who later claims the Darksaber.', a: 'Bo-Katan', alt: ['Bo-Katan Kryze'] },
      { q: 'The defecting Imperial cargo pilot who joins the mission to steal the plans on Scarif.', a: 'Bodhi Rook', alt: ['Bodhi'] },
      { q: 'The shaggy horned beast that the desert nomads of Tatooine ride.', a: 'Bantha' },
      { q: 'Luke\'s aunt on the Tatooine moisture farm.', a: 'Beru', alt: ['Beru Lars'] },
      { q: 'The thin skeletal infantry unit mass-produced for the Trade Federation army.', a: 'Battle droid', alt: ['B1'] },
      { q: 'The heavy repeater gunner who guards his blind friend on the holy moon of Jedha.', a: 'Baze Malbus', alt: ['Baze'] },
      { q: 'The pale Twi\'lek majordomo of Jabba\'s palace.', a: 'Bib Fortuna' },
    ],
    C: [
      { q: 'The Wookiee co-pilot of the Millennium Falcon.', a: 'Chewbacca', alt: ['Chewie'] },
      { q: 'The golden protocol droid fluent in over six million forms of communication.', a: 'C-3PO', alt: ['See-Threepio'] },
      { q: 'The city-covered capital world of the Republic.', a: 'Coruscant' },
      { q: 'The Rebel intelligence officer sent to find the scientist Galen Erso.', a: 'Cassian Andor', alt: ['Cassian'] },
      { q: 'The blind Guardian of the Whills who fights with a staff on Jedha.', a: 'Chirrut Imwe', alt: ['Chirrut'] },
      { q: 'The blue-skinned Duros bounty hunter in a wide-brimmed hat.', a: 'Cad Bane' },
      { q: 'The floating mining colony where Lando serves as baron administrator.', a: 'Cloud City' },
      { q: 'The identical soldiers grown on a stormy ocean world to fight for the Republic.', a: 'Clone troopers', alt: ['Clones'] },
      { q: 'The mineral world of white salt over red earth where the Resistance makes its last stand.', a: 'Crait' },
      { q: 'The actress who played the princess of Alderaan.', a: 'Carrie Fisher' },
      { q: 'The cantankerous astromech aboard the freighter Ghost in Rebels.', a: 'Chopper', alt: ['C1-10P'] },
      { q: 'The former rebel shock trooper who becomes marshal of Nevarro.', a: 'Cara Dune', alt: ['Cara'] },
      { q: 'The seaside casino city where the wealthy bet on fathier races.', a: 'Canto Bight' },
    ],
    D: [
      { q: 'The armoured Sith lord who serves the Emperor and breathes through a black mask.', a: 'Darth Vader', alt: ['Vader'] },
      { q: 'The moon-sized Imperial battle station armed with a planet-killing superlaser.', a: 'Death Star' },
      { q: 'The swamp world where a small green master lives in exile.', a: 'Dagobah' },
      { q: 'The former Jedi turned Separatist leader played by Christopher Lee.', a: 'Dooku', alt: ['Count Dooku', 'Darth Tyranus'] },
      { q: 'The horned Zabrak apprentice who wields a double-bladed red weapon on Naboo.', a: 'Darth Maul', alt: ['Maul'] },
      { q: 'The unique black-bladed weapon that symbolises the right to rule Mandalore.', a: 'Darksaber' },
      { q: 'The bounty hunter known simply as Mando who protects the foundling Grogu.', a: 'Din Djarin' },
      { q: 'The red-hued world of witches and Zabrak brothers.', a: 'Dathomir' },
      { q: 'The world Leia falsely names as the location of the hidden Rebel base.', a: 'Dantooine' },
      { q: 'The wheel-shaped Separatist destroyer that unfolds into a shielded three-legged gun platform.', a: 'Droideka', alt: ['Destroyer droid'] },
      { q: 'The secret dark lord identity of the Republic\'s Supreme Chancellor.', a: 'Darth Sidious', alt: ['Sidious'] },
      { q: 'The splinter group of Mandalorian fighters who reject their world\'s pacifism.', a: 'Death Watch' },
    ],
    E: [
      { q: 'The forest moon hiding the shield generator for the second Imperial battle station.', a: 'Endor' },
      { q: 'The small furred natives of the forest moon who help beat the Imperial garrison.', a: 'Ewok', alt: ['Ewoks'] },
      { q: 'Darth Vader\'s personal Super Star Destroyer flagship.', a: 'Executor' },
      { q: 'The street orphan trained as a Jedi by Kanan in the animated series Rebels.', a: 'Ezra Bridger', alt: ['Ezra'] },
      { q: 'The hidden Sith world where an enormous fleet rises from beneath the surface.', a: 'Exegol' },
      { q: 'The masked leader of the Cloud-Riders who opposes Crimson Dawn.', a: 'Enfys Nest' },
      { q: 'The Rebel headquarters carved into the ice of Hoth.', a: 'Echo Base' },
      { q: 'The long-snouted pack beast used for hauling loads on Tatooine.', a: 'Eopie' },
    ],
    F: [
      { q: 'The runaway stormtrooper who befriends a scavenger and a Resistance pilot.', a: 'Finn' },
      { q: 'The military regime risen from the Empire\'s ashes and led by Supreme Leader Snoke.', a: 'First Order' },
      { q: 'The fungal jungle world where a blue-skinned Jedi is gunned down by her own troops.', a: 'Felucia' },
      { q: 'The crackling blue energy the Emperor unleashes from his fingertips.', a: 'Force lightning' },
      { q: 'The invisible grip Darth Vader uses to strangle officers from across a room.', a: 'Force choke' },
      { q: 'The elite mercenary sniper who becomes the partner of Boba Fett.', a: 'Fennec Shand', alt: ['Fennec'] },
      { q: 'The code name Ahsoka Tano uses as a secret rebel informant.', a: 'Fulcrum' },
      { q: 'The Star Destroyer that serves as Kylo Ren\'s flagship in The Force Awakens.', a: 'Finalizer' },
    ],
    G: [
      { q: 'The small green foundling widely nicknamed Baby Yoda by fans.', a: 'Grogu', alt: ['The Child'] },
      { q: 'The Rodian bounty hunter shot at a cantina table in Mos Eisley.', a: 'Greedo' },
      { q: 'The cyborg Kaleesh commander of the droid army who collects lightsabers as trophies.', a: 'Grievous', alt: ['General Grievous'] },
      { q: 'The red rocky world where the Clone Wars begin in an execution arena.', a: 'Geonosis' },
      { q: 'The amphibious species native to Naboo whose leader is Boss Nass.', a: 'Gungan', alt: ['Gungans'] },
      { q: 'The reluctant scientist forced to finish the Empire\'s planet-killing weapon.', a: 'Galen Erso' },
      { q: 'The battered freighter that serves as home to a rebel cell in the animated series Rebels.', a: 'Ghost' },
      { q: 'The guild agent on Nevarro who hires a Mandalorian to retrieve a child.', a: 'Greef Karga' },
      { q: 'The Pau\'an who leads the Empire\'s Jedi hunters in the animated series Rebels.', a: 'Grand Inquisitor' },
    ],
    H: [
      { q: 'The smuggler who boasts of making the Kessel Run in less than twelve parsecs.', a: 'Han Solo', alt: ['Han'] },
      { q: 'The sixth planet of its system, an ice world sheltering a Rebel outpost.', a: 'Hoth' },
      { q: 'The sneering First Order general who commands the star-draining superweapon.', a: 'Hux', alt: ['Armitage Hux', 'General Hux'] },
      { q: 'The Twi\'lek pilot who captains the freighter Ghost in Rebels.', a: 'Hera Syndulla', alt: ['Hera'] },
      { q: 'The actor who played the smuggler captain of the Millennium Falcon.', a: 'Harrison Ford' },
      { q: 'The purple-haired vice admiral who rams a cruiser through an enemy flagship at lightspeed.', a: 'Holdo', alt: ['Amilyn Holdo'] },
      { q: 'The pirate captain of Florrum and a recurring rogue of the animated series.', a: 'Hondo Ohnaka', alt: ['Hondo'] },
      { q: 'The propulsion system a starship needs to jump to lightspeed.', a: 'Hyperdrive' },
      { q: 'The slug-like crime species that rules cartels from desert palaces.', a: 'Hutt', alt: ['Hutts'] },
    ],
    I: [
      { q: 'The reprogrammed assassin machine that becomes a nurse and self-destructs on Nevarro.', a: 'IG-11' },
      { q: 'The icy world mined for lightsaber crystals, later hollowed out into a superweapon.', a: 'Ilum' },
      { q: 'The ominous theme John Williams composed for the saga\'s masked villain.', a: 'Imperial March' },
      { q: 'The Empire\'s red-bladed dark side operatives who hunt down surviving Force users.', a: 'Inquisitors', alt: ['Inquisitorius'] },
      { q: 'The Rebel ground weapon on the ice world that disables a Star Destroyer to cover fleeing transports.', a: 'Ion cannon' },
      { q: 'The hammer-headed cantina species with two mouths and four throats.', a: 'Ithorian' },
    ],
    J: [
      { q: 'The slug-like crime lord of Tatooine who keeps Leia chained at his palace.', a: 'Jabba the Hutt', alt: ['Jabba'] },
      { q: 'The clumsy amphibian banished by Boss Nass who guides Qui-Gon on Naboo.', a: 'Jar Jar Binks', alt: ['Jar Jar'] },
      { q: 'The desert world where Rey scavenges wrecks left by a great space battle.', a: 'Jakku' },
      { q: 'The reckless young woman who leads the theft of the battle station plans on Scarif.', a: 'Jyn Erso', alt: ['Jyn'] },
      { q: 'The desert moon whose holy city is destroyed by a single superlaser test.', a: 'Jedha' },
      { q: 'The American composer who wrote the saga\'s sweeping orchestral scores.', a: 'John Williams' },
      { q: 'The bounty hunter whose genes are the template for the Republic\'s clone army.', a: 'Jango Fett' },
      { q: 'The small hooded scavengers who sell salvaged droids in the desert.', a: 'Jawa', alt: ['Jawas'] },
      { q: 'The peacekeeping order of Force users guided by a Council on Coruscant.', a: 'Jedi' },
    ],
    K: [
      { q: 'The masked apprentice of Snoke who wields a crossguard blade and hunts a map to Luke.', a: 'Kylo Ren', alt: ['Ben Solo'] },
      { q: 'The stormy ocean world where the Republic\'s army is secretly grown.', a: 'Kamino' },
      { q: 'The forested homeworld of Chewbacca.', a: 'Kashyyyk' },
      { q: 'The world whose mines are worked by slaves digging spice and coaxium.', a: 'Kessel' },
      { q: 'The blinded Jedi survivor who teaches a Lothal orphan in the animated series.', a: 'Kanan Jarrus', alt: ['Kanan'] },
      { q: 'The Ugnaught moisture farmer who repeats the phrase "I have spoken".', a: 'Kuiil' },
      { q: 'The white-caped Imperial director who oversees the superweapon project.', a: 'Krennic', alt: ['Orson Krennic'] },
      { q: 'The Nautolan Jedi with head tentacles and a permanent grin.', a: 'Kit Fisto' },
      { q: 'The snowy mountain city world destroyed by the First Order in the final saga film.', a: 'Kijimi' },
      { q: 'The tall long-necked species who run the secret army facility on their ocean world.', a: 'Kaminoan', alt: ['Kaminoans'] },
    ],
    L: [
      { q: 'The farm boy who destroys the first Imperial battle station with a torpedo shot.', a: 'Luke Skywalker', alt: ['Luke'] },
      { q: 'The princess who hides stolen plans inside an astromech aboard a captured corvette.', a: 'Leia', alt: ['Leia Organa', 'Princess Leia'] },
      { q: 'The caped gambler who runs a floating mining colony above a gas giant.', a: 'Lando Calrissian', alt: ['Lando'] },
      { q: 'The elegant energy-bladed weapon carried by knights of the peacekeeping order.', a: 'Lightsaber' },
      { q: 'The Outer Rim world where the rebel crew of the animated series begins its fight.', a: 'Lothal' },
      { q: 'The quiet cyborg aide with a head implant who serves the baron administrator.', a: 'Lobot' },
      { q: 'The Irish actor who played the Jedi master killed by a Zabrak in 1999.', a: 'Liam Neeson' },
      { q: 'The antiques dealer who secretly builds the rebel network in Andor.', a: 'Luthen Rael', alt: ['Luthen'] },
    ],
    M: [
      { q: 'The battered freighter its captain calls the fastest hunk of junk in the galaxy.', a: 'Millennium Falcon', alt: ['The Falcon'] },
      { q: 'The volcanic world where Obi-Wan defeats his fallen apprentice beside lava rivers.', a: 'Mustafar' },
      { q: 'The war-torn homeworld of a famed warrior culture ruled by the Darksaber.', a: 'Mandalore' },
      { q: 'The Tatooine spaceport Obi-Wan calls a wretched hive of scum and villainy.', a: 'Mos Eisley' },
      { q: 'The ancient pirate queen of Takodana who keeps Luke\'s first weapon in a chest.', a: 'Maz Kanata', alt: ['Maz'] },
      { q: 'The actor who played the farm boy hero of the original trilogy.', a: 'Mark Hamill' },
      { q: 'The Jedi Council member who wields a purple blade.', a: 'Mace Windu', alt: ['Windu'] },
      { q: 'The Imperial remnant warlord who hunts Grogu and carries the Darksaber.', a: 'Moff Gideon', alt: ['Gideon'] },
      { q: 'The microscopic life forms whose count measures a being\'s potential in the Force.', a: 'Midi-chlorians' },
      { q: 'The Chandrilan senator who briefs the fleet before the assault on the forest moon.', a: 'Mon Mothma' },
      { q: 'The winged parasite that clings to starship hulls and chews power cables.', a: 'Mynock' },
      { q: 'The aquatic species whose shipyards build the Rebel Alliance\'s great cruisers.', a: 'Mon Calamari' },
    ],
    N: [
      { q: 'The green world of lakes and waterfalls ruled by an elected teenage queen.', a: 'Naboo' },
      { q: 'The Sullustan co-pilot of the Falcon during the Battle of Endor.', a: 'Nien Nunb' },
      { q: 'The Neimoidian viceroy who orders the blockade of Naboo.', a: 'Nute Gunray' },
      { q: 'The world whose common house serves as the Bounty Hunters\' Guild hub in The Mandalorian.', a: 'Nevarro' },
      { q: 'The witches of Dathomir who practise dark magick.', a: 'Nightsisters' },
      { q: 'The actress who played the young queen of Naboo in the prequels.', a: 'Natalie Portman' },
      { q: 'The swampy homeworld of the galaxy\'s slug-like crime lords.', a: 'Nal Hutta' },
    ],
    O: [
      { q: 'The Jedi who trains Anakin and later hides on Tatooine as a desert hermit.', a: 'Obi-Wan Kenobi', alt: ['Obi-Wan', 'Ben Kenobi'] },
      { q: 'The coded command that turns the clone soldiers against their Jedi generals.', a: 'Order 66' },
      { q: 'Luke\'s uncle who forbids him from leaving the farm for the Academy.', a: 'Owen Lars', alt: ['Owen'] },
      { q: 'The bubble city built beneath the lakes of Naboo.', a: 'Otoh Gunga' },
      { q: 'The Imperial admiral killed for bringing the fleet out of lightspeed too close to the ice world.', a: 'Ozzel', alt: ['Admiral Ozzel'] },
      { q: 'The lawless frontier region far from the galactic core.', a: 'Outer Rim' },
    ],
    P: [
      { q: 'The elected queen turned senator who secretly marries a Jedi.', a: 'Padme Amidala', alt: ['Padme', 'Amidala'] },
      { q: 'The Naboo senator who becomes Supreme Chancellor and then Emperor.', a: 'Palpatine' },
      { q: 'The hotshot Resistance pilot who owns the droid BB-8.', a: 'Poe Dameron', alt: ['Poe'] },
      { q: 'The chrome-armoured stormtrooper captain of the First Order.', a: 'Phasma', alt: ['Captain Phasma'] },
      { q: 'The wide-eyed seabirds nesting on the cliffs of Ahch-To.', a: 'Porg', alt: ['Porgs'] },
      { q: 'The dangerous repulsorlift sport that a young slave wins on Tatooine.', a: 'Podracing', alt: ['Podrace'] },
      { q: 'The Imperial admiral promoted on the spot after his superior is choked to death.', a: 'Piett', alt: ['Admiral Piett'] },
      { q: 'The Imperial scouting machine dropped on the ice world that betrays the Rebel base.', a: 'Probe droid', alt: ['Probot'] },
      { q: 'The Tatooine hangar mechanic who uses pit droids to patch up visiting ships.', a: 'Peli Motto', alt: ['Peli'] },
      { q: 'The spice-running criminal organisation from Oba Diah.', a: 'Pyke Syndicate', alt: ['Pykes'] },
      { q: 'The Kel Dor Council member who wears a breathing mask and dark goggles.', a: 'Plo Koon' },
    ],
    Q: [
      { q: 'The Jedi master who finds a gifted slave boy and dies at a Zabrak\'s hands.', a: 'Qui-Gon Jinn', alt: ['Qui-Gon'] },
      { q: 'The Kiffar Jedi tracker with yellow facial stripes who works undercover.', a: 'Quinlan Vos' },
      { q: 'The Corellian childhood friend of Han who rises within Crimson Dawn.', a: 'Qi\'ra' },
    ],
    R: [
      { q: 'The blue and white astromech who carries the plans to the first Imperial battle station.', a: 'R2-D2', alt: ['Artoo'] },
      { q: 'The desert scavenger revealed to be the Emperor\'s granddaughter.', a: 'Rey' },
      { q: 'The 2016 spin-off film about the theft of the battle station plans.', a: 'Rogue One' },
      { q: 'The horned beast kept in a pit beneath Jabba\'s throne room.', a: 'Rancor' },
      { q: 'The coalition of worlds that fights the Empire from a base on Yavin 4.', a: 'Rebel Alliance' },
      { q: 'The small force General Leia builds to fight the First Order.', a: 'Resistance' },
      { q: 'The mechanic who stops a deserter from fleeing the fleet in The Last Jedi.', a: 'Rose Tico', alt: ['Rose'] },
      { q: 'The homeworld of the head-tailed species that Cham Syndulla fights for.', a: 'Ryloth' },
      { q: 'The gunship a lone Mandalorian flies until an Imperial cruiser blasts it apart.', a: 'Razor Crest' },
    ],
    S: [
      { q: 'The ancient order of dark side users bound by the Rule of Two.', a: 'Sith' },
      { q: 'The tropical Imperial archive world protected by a planetary shield gate.', a: 'Scarif' },
      { q: 'The Supreme Leader cut in half by his own apprentice aboard the Supremacy.', a: 'Snoke' },
      { q: 'The First Order weapon carved into an icy planet that drains a nearby sun.', a: 'Starkiller Base' },
      { q: 'The white-armoured Imperial infantry famous for missing their shots.', a: 'Stormtrooper', alt: ['Stormtroopers'] },
      { q: 'The extremist partisan leader who once raised Jyn Erso.', a: 'Saw Gerrera', alt: ['Saw'] },
      { q: 'The Mandalorian graffiti artist and explosives expert of the rebel crew in Rebels.', a: 'Sabine Wren', alt: ['Sabine'] },
      { q: 'The tentacled pit-dwelling beast of the Dune Sea that swallows Boba Fett.', a: 'Sarlacc' },
      { q: 'The wedge-shaped Imperial capital warship over a kilometre long.', a: 'Star Destroyer' },
      { q: 'The pacifist duchess of Mandalore whom Obi-Wan once loved.', a: 'Satine', alt: ['Satine Kryze'] },
      { q: 'The cheating Dug who crashes out of the Boonta Eve race.', a: 'Sebulba' },
      { q: 'The slave mother left behind on Tatooine when her son joins the Jedi.', a: 'Shmi', alt: ['Shmi Skywalker'] },
      { q: 'The card game in which Lando loses his beloved ship to Han.', a: 'Sabacc' },
      { q: 'The giant treaded vehicle that the small hooded desert scavengers live in.', a: 'Sandcrawler' },
    ],
    T: [
      { q: 'The twin-sunned desert world where both Anakin and Luke grow up.', a: 'Tatooine' },
      { q: 'The Grand Moff who gives the order to destroy Alderaan.', a: 'Tarkin' },
      { q: 'The Imperial attack craft with hexagonal solar panels and a screaming twin engine.', a: 'TIE fighter' },
      { q: 'The Corellian corvette boarded above Tatooine at the start of the first film.', a: 'Tantive IV' },
      { q: 'The nomadic masked desert people who wield gaderffii sticks on Tatooine.', a: 'Tusken Raiders', alt: ['Tuskens', 'Sand People'] },
      { q: 'The forested world where Maz Kanata keeps her castle.', a: 'Takodana' },
      { q: 'The blue-skinned Chiss grand admiral who hunts the rebel crew of the Ghost.', a: 'Thrawn' },
      { q: 'The greedy commercial body whose battleships blockade Naboo.', a: 'Trade Federation' },
      { q: 'The species with long head-tails whose homeworld is Ryloth.', a: 'Twi\'lek', alt: ['Twi\'leks'] },
      { q: 'The reptilian species to which the bounty hunter Bossk belongs.', a: 'Trandoshan', alt: ['Trandoshans'] },
      { q: 'The horned species with striped head-tails to which Ahsoka belongs.', a: 'Togruta' },
    ],
    U: [
      { q: 'The sinkhole world where Obi-Wan kills the cyborg general of the droid army.', a: 'Utapau' },
      { q: 'The short-snouted workers who tend the machinery of Cloud City.', a: 'Ugnaught', alt: ['Ugnaughts'] },
      { q: 'The junk boss who trades food portions for salvage on Jakku.', a: 'Unkar Plutt', alt: ['Unkar'] },
    ],
    V: [
      { q: 'The Imperial general who leads the walker assault on the Rebel ice base.', a: 'Veers', alt: ['General Veers'] },
      { q: 'The crystalline fox that roams the salt caves of Crait.', a: 'Vulptex', alt: ['Crystal fox', 'Vulptices'] },
      { q: 'The Separatist starfighter that folds its wings down to walk like a bird.', a: 'Vulture droid' },
      { q: 'The rebel commander who leads the Aldhani garrison heist in Andor.', a: 'Vel Sartha', alt: ['Vel'] },
    ],
    W: [
      { q: 'The tall furred species from Kashyyyk that speaks in growls and roars.', a: 'Wookiee', alt: ['Wookiees'] },
      { q: 'The Rogue Squadron pilot who flies in both attacks on an Imperial battle station.', a: 'Wedge Antilles', alt: ['Wedge'] },
      { q: 'The winged Toydarian junk dealer who owns Anakin and his mother.', a: 'Watto' },
      { q: 'The white-furred predator that drags Luke to its cave on the ice world.', a: 'Wampa' },
      { q: 'The furry forest moon native who finds Leia among the trees.', a: 'Wicket' },
      { q: 'The leathery-skinned species of Jabba\'s skiff guards.', a: 'Weequay' },
    ],
    X: [
      { q: 'The Rebel snubfighter whose four S-foils lock into attack position.', a: 'X-wing' },
    ],
    Y: [
      { q: 'The small green grand master who trains Luke in a swamp.', a: 'Yoda' },
      { q: 'The jungle moon hosting the Rebel base in the climax of the first film.', a: 'Yavin 4', alt: ['Yavin'] },
      { q: 'The older Rebel bomber with twin engine nacelles and an exposed hull frame.', a: 'Y-wing' },
      { q: 'The female Council member of the same species as the Jedi grand master.', a: 'Yaddle' },
    ],
    Z: [
      { q: 'The purple Lasat muscle of the rebel crew in the animated series Rebels.', a: 'Zeb', alt: ['Garazeb Orrelios'] },
      { q: 'The Clawdite shapeshifter assassin silenced by a toxic dart on Coruscant.', a: 'Zam Wesell' },
      { q: 'The helmeted spice runner and old flame of Poe Dameron.', a: 'Zorii Bliss', alt: ['Zorii'] },
    ],
  },
};
