import type { RawPack } from '../core/packs';

export const fandomDcPack: RawPack = {
  id: 'fandom-dc',
  name: 'DC and Batman',
  description: 'Gotham, Metropolis and Themyscira: heroes, rogues, gadgets and the films.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🦇',
  accent: '#1e3a8a',
  letters: {
    A: [
      { q: 'The loyal butler who raised Bruce Wayne after his parents were killed.', a: 'Alfred Pennyworth', alt: ['Alfred'] },
      { q: 'The Justice League founder who rules the seven seas and commands sea life.', a: 'Aquaman' },
      { q: 'The Gotham psychiatric hospital that houses the city\'s criminally insane.', a: 'Arkham Asylum', alt: ['Arkham'] },
      { q: 'The all-female warrior race of Themyscira.', a: 'Amazons', alt: ['Amazon'] },
      { q: 'The ruthless government official who founded Task Force X.', a: 'Amanda Waller', alt: ['Waller'] },
      { q: 'Darkseid\'s fiery hellworld of firepits and slave armies.', a: 'Apokolips' },
      { q: 'The Greek god of war who is Wonder Woman\'s oldest enemy.', a: 'Ares' },
      { q: 'The Golden Age Green Lantern whose ring drew power from the Starheart.', a: 'Alan Scott' },
      { q: 'The actress who played Selina Kyle in The Dark Knight Rises.', a: 'Anne Hathaway', alt: ['Hathaway'] },
    ],
    B: [
      { q: 'The Caped Crusader known as the World\'s Greatest Detective.', a: 'Batman' },
      { q: 'The armoured black car the Dark Knight drives through Gotham.', a: 'Batmobile' },
      { q: 'The secret underground lair beneath Wayne Manor.', a: 'Batcave' },
      { q: 'The masked strongman pumped full of Venom who snapped the Dark Knight\'s spine.', a: 'Bane' },
      { q: 'The cowled heroine identity first taken by Barbara Gordon.', a: 'Batgirl' },
      { q: 'The Gotham billionaire orphaned by a mugging in Crime Alley.', a: 'Bruce Wayne' },
      { q: 'The actor who wore the cowl in Batman v Superman and Justice League.', a: 'Ben Affleck', alt: ['Affleck'] },
      { q: 'The green-skinned Coluan supercomputer villain who shrinks and bottles cities.', a: 'Brainiac' },
      { q: 'The chalk-white failed duplicate of Superman who speaks in opposites.', a: 'Bizarro' },
      { q: 'The Central City forensic scientist struck by lightning who became the Flash.', a: 'Barry Allen' },
      { q: 'Dinah Lance, the heroine whose sonic scream shatters glass.', a: 'Black Canary' },
      { q: 'Garfield Logan, the green shapeshifting Teen Titan.', a: 'Beast Boy' },
      { q: 'The helmeted undersea villain with red eye beams who hunts Aquaman.', a: 'Black Manta' },
    ],
    C: [
      { q: 'The whip-cracking Gotham cat burglar Selina Kyle.', a: 'Catwoman' },
      { q: 'The mild-mannered Daily Planet reporter who is secretly Superman.', a: 'Clark Kent' },
      { q: 'Victor Stone, the half-machine member of the Justice League.', a: 'Cyborg' },
      { q: 'The Welsh actor who starred as Batman in Christopher Nolan\'s trilogy.', a: 'Christian Bale', alt: ['Bale'] },
      { q: 'The actor who first played Superman on film in 1978.', a: 'Christopher Reeve', alt: ['Reeve'] },
      { q: 'The shapeshifting Gotham villain made of living mud.', a: 'Clayface' },
      { q: 'Barbara Ann Minerva, the feline archfoe of Wonder Woman.', a: 'Cheetah' },
      { q: 'The home town the Flash protects.', a: 'Central City' },
      { q: 'The 1985 event series that collapsed the DC multiverse into a single timeline.', a: 'Crisis on Infinite Earths', alt: ['Crisis'] },
      { q: 'The secret society of Gotham aristocrats served by Talon assassins.', a: 'Court of Owls' },
      { q: 'The actor who played the Joker in the 1966 television series and refused to shave his moustache.', a: 'Cesar Romero', alt: ['Romero'] },
      { q: 'Leonard Snart, the Flash rogue armed with a freeze gun.', a: 'Captain Cold' },
    ],
    D: [
      { q: 'The tyrant of Apokolips who fires Omega Beams from his eyes.', a: 'Darkseid' },
      { q: 'Slade Wilson, the one-eyed mercenary in orange and black armour.', a: 'Deathstroke' },
      { q: 'The bone-spiked grey monster who killed Superman in 1992.', a: 'Doomsday' },
      { q: 'The first Robin, a former circus acrobat.', a: 'Dick Grayson', alt: ['Grayson'] },
      { q: 'Floyd Lawton, the Suicide Squad marksman who never misses.', a: 'Deadshot' },
      { q: 'The actor who played the Penguin in Batman Returns.', a: 'Danny DeVito', alt: ['DeVito'] },
      { q: 'The human alias Wonder Woman uses away from Themyscira.', a: 'Diana Prince' },
      { q: 'The sorcerer who wears the golden Helmet of Nabu.', a: 'Doctor Fate', alt: ['Dr Fate', 'Dr. Fate'] },
      { q: 'The anthology title whose 27th issue introduced Batman in 1939.', a: 'Detective Comics' },
      { q: 'The son of Batman and Talia al Ghul who served as Robin.', a: 'Damian Wayne', alt: ['Damian'] },
      { q: 'Frank Miller\'s 1986 story about an ageing Bruce Wayne coming out of retirement.', a: 'The Dark Knight Returns', alt: ['Dark Knight Returns'] },
      { q: 'The team of misfit heroes led by Niles Caulder, the Chief.', a: 'Doom Patrol' },
    ],
    E: [
      { q: 'The rhyming demon bound to the human Jason Blood.', a: 'Etrigan' },
      { q: 'The real name of the Reverse-Flash.', a: 'Eobard Thawne', alt: ['Thawne'] },
      { q: 'The actor who played the Flash in the DC Extended Universe films.', a: 'Ezra Miller' },
      { q: 'The witch June Moone becomes in the 2016 Suicide Squad film.', a: 'Enchantress' },
      { q: 'The DC imprint label used for stories set outside the main continuity.', a: 'Elseworlds' },
    ],
    F: [
      { q: 'The Scarlet Speedster of Central City.', a: 'The Flash', alt: ['Flash'] },
      { q: 'Superman\'s crystalline hideaway in the Arctic.', a: 'Fortress of Solitude' },
      { q: 'The 2011 event that rewrote DC history and launched the New 52.', a: 'Flashpoint' },
      { q: 'The writer and artist behind Year One and the 1986 tale of an ageing Bruce Wayne.', a: 'Frank Miller' },
      { q: 'The nuclear hero formed when Ronnie Raymond and Martin Stein merge.', a: 'Firestorm' },
      { q: 'The Gotham crime family boss named Carmine who ruled before the costumed villains arrived.', a: 'Falcone' },
      { q: 'The Gotham arsonist in a jetpack who worships flames.', a: 'Firefly' },
      { q: 'The ancient sorcerer who bargains with demons to fight the Justice League.', a: 'Felix Faust' },
    ],
    G: [
      { q: 'The grim, gargoyle-covered home turf Batman patrols.', a: 'Gotham City', alt: ['Gotham'] },
      { q: 'The ring-bearing space police officer whose oath begins in brightest day.', a: 'Green Lantern' },
      { q: 'The bow-wielding emerald vigilante of Star City.', a: 'Green Arrow' },
      { q: 'The Israeli actress who plays Wonder Woman in the DC films.', a: 'Gal Gadot', alt: ['Gadot'] },
      { q: 'The telepathic super-intelligent ape from a hidden African city who battles the Flash.', a: 'Grodd', alt: ['Gorilla Grodd'] },
      { q: 'The brash Green Lantern with a bowl cut and a chip on his shoulder.', a: 'Guy Gardner' },
      { q: 'The actor who played Lex Luthor opposite Christopher Reeve.', a: 'Gene Hackman', alt: ['Hackman'] },
      { q: 'The actor who starred as Barry Allen in the CW series about the Scarlet Speedster.', a: 'Grant Gustin', alt: ['Gustin'] },
      { q: 'The Kryptonian military commander banished to the Phantom Zone.', a: 'General Zod', alt: ['Zod'] },
    ],
    H: [
      { q: 'The Joker\'s pigtailed sidekick, a former Arkham psychiatrist in red and black.', a: 'Harley Quinn', alt: ['Harley'] },
      { q: 'The test pilot from Coast City chosen by a dying alien to join the Green Lantern Corps.', a: 'Hal Jordan' },
      { q: 'The actor who won a posthumous Oscar for playing the Joker in 2008.', a: 'Heath Ledger', alt: ['Ledger'] },
      { q: 'The British actor who played Superman in Man of Steel.', a: 'Henry Cavill', alt: ['Cavill'] },
      { q: 'Carter Hall, the winged warrior armed with a mace.', a: 'Hawkman' },
      { q: 'The 2002 Batman arc by Jeph Loeb and Jim Lee featuring a bandage-wrapped foe.', a: 'Hush' },
      { q: 'Wonder Woman\'s mother, the queen of the Amazons.', a: 'Hippolyta' },
      { q: 'The obsessive Gotham psychiatrist who deduced Batman\'s secret and coveted his life.', a: 'Hugo Strange' },
      { q: 'The domed Super Friends headquarters from the 1970s cartoons.', a: 'Hall of Justice' },
      { q: 'The Gotham district attorney scarred by acid during a trial.', a: 'Harvey Dent' },
    ],
    I: [
      { q: 'The reporter who marries Barry Allen.', a: 'Iris West' },
      { q: 'Wonder Woman\'s see-through aircraft from the classic comics.', a: 'Invisible Jet' },
      { q: 'The 2004 murder mystery event that begins with the death of Sue Dibny.', a: 'Identity Crisis' },
      { q: 'The DC fighting game series in which Superman becomes a tyrant.', a: 'Injustice' },
    ],
    J: [
      { q: 'The Clown Prince of Crime and Batman\'s greatest enemy.', a: 'The Joker', alt: ['Joker'] },
      { q: 'The premier DC super-team that debuted in The Brave and the Bold #28.', a: 'Justice League' },
      { q: 'The second Robin, beaten with a crowbar in A Death in the Family.', a: 'Jason Todd' },
      { q: 'Superman\'s adoptive father on the Kansas farm.', a: 'Jonathan Kent', alt: ['Pa Kent'] },
      { q: 'The Kryptonian scientist who rocketed his infant son to Earth.', a: 'Jor-El' },
      { q: 'The Green Lantern who worked as an architect and served as a United States Marine.', a: 'John Stewart' },
      { q: 'The actor who played the Joker in the 2016 Suicide Squad film.', a: 'Jared Leto', alt: ['Leto'] },
      { q: 'The actor who won an Oscar for playing Arthur Fleck in 2019.', a: 'Joaquin Phoenix', alt: ['Phoenix'] },
      { q: 'The actor who played Lex Luthor in Batman v Superman.', a: 'Jesse Eisenberg', alt: ['Eisenberg'] },
      { q: 'The 1940s super-team that first gathered in All Star Comics #3.', a: 'Justice Society' },
      { q: 'The Korean-born artist of Hush who later became publisher of DC.', a: 'Jim Lee' },
      { q: 'The red-haired cub photographer who is Superman\'s pal at the Daily Planet.', a: 'Jimmy Olsen', alt: ['Olsen'] },
      { q: 'The Hawaiian-born actor who plays the king of the seven seas on film.', a: 'Jason Momoa', alt: ['Momoa'] },
    ],
    K: [
      { q: 'Superman\'s doomed home planet.', a: 'Krypton' },
      { q: 'The glowing green mineral that saps Superman\'s strength.', a: 'Kryptonite' },
      { q: 'Superman\'s cape-wearing dog.', a: 'Krypto' },
      { q: 'Superman\'s birth name, given by his alien parents.', a: 'Kal-El' },
      { q: 'The scaly, reptilian Gotham villain Waylon Jones.', a: 'Killer Croc' },
      { q: 'The voice actor who defined Batman in the 1992 animated series.', a: 'Kevin Conroy', alt: ['Conroy'] },
      { q: 'The ice-wielding villain who drains the heat from her victims and fights Firestorm.', a: 'Killer Frost' },
      { q: 'The gruff Green Lantern drill sergeant who calls rookies poozers.', a: 'Kilowog' },
      { q: 'Alan Moore\'s 1988 one-shot in which Barbara Gordon is shot and her father is tortured.', a: 'The Killing Joke', alt: ['Killing Joke'] },
      { q: 'The 1996 Elseworlds tale painted by Alex Ross about an older generation of heroes.', a: 'Kingdom Come' },
      { q: 'The 1993 arc in which Bane breaks the Bat and Jean-Paul Valley takes the cowl.', a: 'Knightfall' },
    ],
    L: [
      { q: 'The bald Metropolis billionaire who is Superman\'s greatest foe.', a: 'Lex Luthor', alt: ['Luthor'] },
      { q: 'The star investigative reporter in Metropolis who marries Superman.', a: 'Lois Lane' },
      { q: 'The Wayne Enterprises executive who supplies Batman\'s gear in the Nolan films.', a: 'Lucius Fox' },
      { q: 'The golden rope Wonder Woman uses to compel honesty.', a: 'Lasso of Truth' },
      { q: 'The villain team in Challenge of the Super Friends based in a swamp headquarters.', a: 'Legion of Doom' },
      { q: 'The actress who starred in the 1970s Wonder Woman television series.', a: 'Lynda Carter' },
      { q: 'The green chemical bath that restores life and youth to Ra\'s al Ghul.', a: 'Lazarus Pit' },
      { q: 'The cigar-chewing Czarnian bounty hunter who rides a space bike.', a: 'Lobo' },
      { q: 'The electric shock jock villain created for Superman: The Animated Series.', a: 'Livewire' },
    ],
    M: [
      { q: 'The gleaming modern city Superman protects.', a: 'Metropolis' },
      { q: 'J\'onn J\'onzz, the shapeshifting telepath from the red planet.', a: 'Martian Manhunter' },
      { q: 'The cold-suited Gotham villain desperate to cure his dying wife.', a: 'Mr. Freeze', alt: ['Mister Freeze', 'Mr Freeze'] },
      { q: 'The 2013 Zack Snyder film that launched the DC Extended Universe.', a: 'Man of Steel' },
      { q: 'The actor who wore the cowl in Tim Burton\'s 1989 film.', a: 'Michael Keaton', alt: ['Keaton'] },
      { q: 'The Star Wars actor who voiced the Joker in the 1992 animated series.', a: 'Mark Hamill', alt: ['Hamill'] },
      { q: 'The cyborg Superman villain powered by a kryptonite heart.', a: 'Metallo' },
      { q: 'The red-haired queen of Xebel who controls water and married Aquaman.', a: 'Mera' },
      { q: 'Jervis Tetch, the Gotham villain who hides mind-control chips in headwear.', a: 'Mad Hatter' },
      { q: 'The Australian actress who played Harley Quinn on film.', a: 'Margot Robbie', alt: ['Robbie'] },
      { q: 'The Hollywood legend paid a fortune to play Jor-El in 1978.', a: 'Marlon Brando', alt: ['Brando'] },
      { q: 'The fifth-dimensional imp who must say his own name backwards to be banished.', a: 'Mister Mxyzptlk', alt: ['Mxyzptlk'] },
    ],
    N: [
      { q: 'The identity Dick Grayson took after he outgrew Robin.', a: 'Nightwing' },
      { q: 'The paradise world ruled by Highfather.', a: 'New Genesis' },
      { q: 'The Thanagarian element that lets Hawkman fly.', a: 'Nth Metal' },
      { q: 'The cryogenically frozen wife whom the ice-suited Gotham villain wants to revive.', a: 'Nora Fries', alt: ['Nora'] },
      { q: 'The lord of the dead who raises an army of Black Lanterns.', a: 'Nekron' },
      { q: 'The actress who played Chase Meridian in Batman Forever.', a: 'Nicole Kidman', alt: ['Kidman'] },
    ],
    O: [
      { q: 'The information broker in a wheelchair who guides the Bat-family by computer.', a: 'Oracle' },
      { q: 'The planet at the centre of the universe where the Guardians keep their central power battery.', a: 'Oa' },
      { q: 'The son of Darkseid who was raised in peace by Highfather.', a: 'Orion' },
      { q: 'The civilian name of the emerald archer of Star City.', a: 'Oliver Queen' },
      { q: 'The Penguin\'s full given name.', a: 'Oswald Cobblepot', alt: ['Cobblepot'] },
      { q: 'The evil Batman counterpart from the Crime Syndicate.', a: 'Owlman' },
    ],
    P: [
      { q: 'The plant-controlling botanist villain Pamela Isley.', a: 'Poison Ivy' },
      { q: 'The umbrella-wielding Gotham crime boss in a top hat and monocle.', a: 'The Penguin', alt: ['Penguin'] },
      { q: 'The cigar-chewing editor who runs the Daily Planet.', a: 'Perry White' },
      { q: 'The classic comics name for the hidden Amazon homeland.', a: 'Paradise Island' },
      { q: 'The yellow fear entity that possessed Hal Jordan.', a: 'Parallax' },
      { q: 'The helmeted DC antihero played by John Cena in a 2022 series.', a: 'Peacemaker' },
      { q: 'The stretchy red-and-yellow hero who was once a crook called Eel O\'Brian.', a: 'Plastic Man' },
      { q: 'The prison dimension where Kryptonian criminals are exiled.', a: 'Phantom Zone' },
    ],
    Q: [
      { q: 'The faceless detective Vic Sage, a Charlton hero brought into DC.', a: 'The Question', alt: ['Question'] },
      { q: 'The royal title Hippolyta holds among the Amazons.', a: 'Queen' },
    ],
    R: [
      { q: 'The Boy Wonder who fights crime at Batman\'s side.', a: 'Robin' },
      { q: 'The green-suited villain Edward Nygma who leaves question-mark clues.', a: 'The Riddler', alt: ['Riddler'] },
      { q: 'The immortal leader of the League of Assassins who calls Batman the Detective.', a: 'Ra\'s al Ghul', alt: ['Ras al Ghul'] },
      { q: 'The criminal identity the Joker used before his chemical bath, later taken by Jason Todd.', a: 'Red Hood' },
      { q: 'The half-demon daughter of Trigon in the Teen Titans.', a: 'Raven' },
      { q: 'The childhood friend and prosecutor love interest in Batman Begins.', a: 'Rachel Dawes' },
      { q: 'The yellow-clad speedster who is Barry Allen\'s deadliest enemy.', a: 'Reverse-Flash', alt: ['Reverse Flash'] },
      { q: 'The actor who wore the cowl in the 2022 film directed by Matt Reeves.', a: 'Robert Pattinson', alt: ['Pattinson'] },
      { q: 'The director of the 1978 Superman film.', a: 'Richard Donner', alt: ['Donner'] },
      { q: 'The Gotham police detective partnered with Harvey Bullock who later became the Question.', a: 'Renee Montoya', alt: ['Montoya'] },
      { q: 'The physicist who shrinks himself to become the Atom.', a: 'Ray Palmer' },
    ],
    S: [
      { q: 'The Man of Steel who fights for truth and justice.', a: 'Superman' },
      { q: 'The team of jailed villains sent on deniable missions as Task Force X.', a: 'Suicide Squad' },
      { q: 'The American pilot who crash-lands on Themyscira.', a: 'Steve Trevor' },
      { q: 'The Kansas town where Clark Kent grew up.', a: 'Smallville' },
      { q: 'Jonathan Crane, the Gotham villain who weaponises fear toxin.', a: 'Scarecrow' },
      { q: 'The Korugarian who turned renegade and wields a yellow power ring.', a: 'Sinestro' },
      { q: 'The undead swamp giant who chants about being born on a Monday.', a: 'Solomon Grundy' },
      { q: 'Kara Zor-El, the Kryptonian cousin of Superman.', a: 'Supergirl' },
      { q: 'The magic word that transforms Billy Batson into a hero.', a: 'Shazam' },
      { q: 'The Tamaranean princess Koriand\'r of the Teen Titans.', a: 'Starfire' },
      { q: 'Catwoman\'s birth name.', a: 'Selina Kyle' },
      { q: 'The axe-wielding New God who leads the invasion in the 2017 Justice League film.', a: 'Steppenwolf' },
      { q: 'The plant elemental born from the death of Alec Holland in a Louisiana bog.', a: 'Swamp Thing' },
      { q: 'The mind-controlling alien conqueror shaped like a sea creature that the Justice League first fought.', a: 'Starro' },
      { q: 'The research facility in the CW Flash series where the hero\'s team works.', a: 'Star Labs', alt: ['S.T.A.R. Labs', 'STAR Labs'] },
    ],
    T: [
      { q: 'The hidden island home of the Amazons.', a: 'Themyscira' },
      { q: 'The scarred former prosecutor who decides everything with a coin flip.', a: 'Two-Face', alt: ['Two Face'] },
      { q: 'The team of young heroes led by Robin and later by Nightwing.', a: 'Teen Titans', alt: ['Titans'] },
      { q: 'The third Robin, who worked out Batman\'s secret identity as a boy.', a: 'Tim Drake' },
      { q: 'The daughter of the League of Assassins leader and mother of Damian.', a: 'Talia al Ghul', alt: ['Talia'] },
      { q: 'The director of the 1989 Batman film and its 1992 sequel.', a: 'Tim Burton', alt: ['Burton'] },
      { q: 'The actor who commanded Superman to kneel before him in the 1980 sequel.', a: 'Terence Stamp', alt: ['Stamp'] },
      { q: 'The Superman villain who kills with deadly playthings.', a: 'Toyman' },
      { q: 'The actor who played the coin-flipping villain in Batman Forever.', a: 'Tommy Lee Jones' },
      { q: 'The interdimensional demon who fathered Raven.', a: 'Trigon' },
    ],
    U: [
      { q: 'The gadget-filled yellow waistband Batman wears.', a: 'Utility Belt' },
      { q: 'The evil Superman counterpart of the Crime Syndicate.', a: 'Ultraman' },
      { q: 'The female Kryptonian criminal who follows General Zod in the 1980 film.', a: 'Ursa' },
      { q: 'The actress who played Poison Ivy in Batman and Robin.', a: 'Uma Thurman', alt: ['Thurman'] },
    ],
    V: [
      { q: 'The immortal caveman who has plotted his way through all of human history.', a: 'Vandal Savage' },
      { q: 'The Gotham photojournalist played by Kim Basinger in 1989.', a: 'Vicki Vale' },
      { q: 'The timid Gotham criminal who takes orders from a dummy named Scarface.', a: 'Ventriloquist' },
      { q: 'The actor who wore the cowl in Batman Forever.', a: 'Val Kilmer', alt: ['Kilmer'] },
      { q: 'The birth name of the villain called Mr. Freeze.', a: 'Victor Fries', alt: ['Fries'] },
    ],
    W: [
      { q: 'The Amazon princess who fights with a golden lasso and bulletproof bracelets.', a: 'Wonder Woman' },
      { q: 'The stately mansion that sits above the Batcave.', a: 'Wayne Manor' },
      { q: 'The third hero to carry the Flash mantle, once known as Kid Flash.', a: 'Wally West' },
      { q: 'Alan Moore and Dave Gibbons wrote and drew this 1986 series about Rorschach and Doctor Manhattan.', a: 'Watchmen' },
      { q: 'The Justice League\'s orbital headquarters on the moon.', a: 'Watchtower' },
      { q: 'The Gotham conglomerate whose profits secretly fund the Dark Knight.', a: 'Wayne Enterprises' },
      { q: 'The Flash rogue who controls storms with a wand.', a: 'Weather Wizard' },
      { q: 'The younger Amazon heroine Donna Troy of the Teen Titans.', a: 'Wonder Girl' },
    ],
    X: [
      { q: 'The immortal tarot-reading fortune teller of the DC magic corner.', a: 'Xanadu', alt: ['Madame Xanadu'] },
    ],
    Y: [
      { q: 'Frank Miller\'s 1987 arc about Bruce Wayne\'s first months in the cowl.', a: 'Year One' },
      { q: 'The animated series about teenage sidekicks running covert missions for the League.', a: 'Young Justice' },
    ],
    Z: [
      { q: 'The top-hatted magician who casts spells by speaking backwards.', a: 'Zatanna' },
      { q: 'The director of Man of Steel and Batman v Superman.', a: 'Zack Snyder', alt: ['Snyder'] },
      { q: 'The actress who played Selina Kyle in the 2022 film.', a: 'Zoe Kravitz', alt: ['Kravitz'] },
      { q: 'The stage magician father of the backwards-speaking sorceress of the Justice League.', a: 'Zatara' },
      { q: 'The strange planet in the phrase that triggers Batman\'s backup personality.', a: 'Zur-En-Arrh' },
      { q: 'The Reverse-Flash identity used by Hunter Zolomon.', a: 'Zoom' },
    ],
  },
};
