import type { RawPack } from '../core/packs';

export const fashionDesignersPack: RawPack = {
  id: 'fashion',
  name: 'Fashion & Designers',
  description: 'Houses, designers, fabrics and the language of style.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '👗',
  accent: '#be185d',
  letters: {
    A: [
      { q: 'Italian designer whose soft unstructured suits defined 1980s power dressing.', a: 'Armani' },
      { q: 'French word for the workshop where a couture house makes its clothes.', a: 'Atelier' },
      { q: 'Wide silk neck scarf tucked inside an open shirt, named after a racecourse.', a: 'Ascot' },
      { q: 'Soft fluffy fibre combed from a long-haired breed of rabbit.', a: 'Angora' },
      { q: 'Hooded waterproof pullover jacket, from an Inuit word.', a: 'Anorak' },
      { q: 'Decoration made by stitching one piece of cloth on top of another.', a: 'Applique' },
      { q: 'Editor-in-chief of American Vogue, known for her bob and dark glasses.', a: 'Anna Wintour' },
      { q: 'Protective garment tied over the front of your clothes for cooking.', a: 'Apron' },
      { q: 'Diamond-patterned knit design used on golf sweaters and socks.', a: 'Argyle' },
      { q: 'Dress shape that flares gently outwards towards the hem, named after a letter.', a: 'A-line' },
      { q: 'Term for experimental design that deliberately breaks the rules.', a: 'Avant-garde' },
    ],
    B: [
      { q: 'Spanish-born couturier who opened his celebrated Paris house in 1937.', a: 'Balenciaga' },
      { q: 'British house famous for its beige check lining and its raincoats.', a: 'Burberry' },
      { q: 'The fitted upper part of a dress, above the waist.', a: 'Bodice' },
      { q: 'Term for a suit cut individually to one customer\'s own measurements.', a: 'Bespoke' },
      { q: 'Soft round flat-crowned woollen cap associated with France.', a: 'Beret' },
      { q: 'Smart single-breasted jacket, often navy with brass buttons.', a: 'Blazer' },
      { q: 'Rich fabric woven with a raised pattern, often in gold or silver thread.', a: 'Brocade' },
      { q: 'Cutting cloth diagonally to the weave so a dress clings and falls softly.', a: 'Bias cut' },
      { q: 'Small spool that holds the lower thread in a sewing machine.', a: 'Bobbin' },
      { q: 'Very short open jacket that ends above the waist.', a: 'Bolero' },
      { q: 'Metal fastening at the end of a belt.', a: 'Buckle' },
      { q: 'Small disc pushed through a slit to fasten a shirt.', a: 'Button' },
      { q: 'Hermes handbag introduced in the 1980s and named after a British singer and actress.', a: 'Birkin' },
      { q: 'Frame worn under a Victorian skirt to puff it out at the back.', a: 'Bustle' },
      { q: 'Formal neckwear knotted symmetrically at the collar of a dinner jacket.', a: 'Bow tie' },
      { q: 'Square patterned cotton cloth folded and tied round the head or neck.', a: 'Bandana' },
    ],
    C: [
      { q: 'French house whose founder gave the world No. 5 and the tweed suit.', a: 'Chanel' },
      { q: 'Stiffened undergarment laced tight to shape the waist.', a: 'Corset' },
      { q: 'Luxury wool combed from goats bred in the Himalayas.', a: 'Cashmere' },
      { q: 'Sheer lightweight fabric with a slightly rough feel, used for floaty dresses.', a: 'Chiffon' },
      { q: 'The turned-back band at the end of a sleeve.', a: 'Cuff' },
      { q: 'The part of a shirt that folds around the neck.', a: 'Collar' },
      { q: 'Cotton fabric woven with raised vertical ridges.', a: 'Corduroy' },
      { q: 'British word for the raised platform models parade along at a show.', a: 'Catwalk' },
      { q: 'American designer whose 1980s jeans campaign starred Brooke Shields.', a: 'Calvin Klein' },
      { q: 'Knitted top that buttons up the front, named after a British earl.', a: 'Cardigan' },
      { q: 'Japanese label whose name is French for \'like boys\', founded in Tokyo in 1969.', a: 'Comme des Garcons' },
      { q: 'The most widely used natural plant fibre in clothing.', a: 'Cotton' },
      { q: 'Small evening handbag carried without a strap.', a: 'Clutch' },
      { q: 'Stiff hooped underskirt that held Victorian dresses out wide.', a: 'Crinoline' },
      { q: 'Neck cloth worn by men in earlier centuries, an ancestor of the tie.', a: 'Cravat' },
    ],
    D: [
      { q: 'French house whose founder launched the New Look in 1947.', a: 'Dior' },
      { q: 'Sturdy cotton twill, traditionally dyed indigo, used for jeans.', a: 'Denim' },
      { q: 'Stitched tapering fold that shapes flat cloth to the body.', a: 'Dart' },
      { q: 'Reversible figured fabric with a woven pattern, named after a Syrian city.', a: 'Damask' },
      { q: 'American designer who launched the DKNY label in 1989.', a: 'Donna Karan' },
      { q: 'The designer who created the jersey wrap dress in 1974.', a: 'Diane von Furstenberg' },
      { q: 'Trousers with a bib front and shoulder straps.', a: 'Dungarees' },
      { q: 'To arrange fabric in loose folds over the body or a stand.', a: 'Drape' },
      { q: 'Hooded woollen outer garment fastened with wooden toggles and rope loops.', a: 'Duffel coat' },
      { q: 'Italian design duo who founded their Milan label in 1985.', a: 'Dolce and Gabbana' },
      { q: 'Substance used to change the colour of cloth.', a: 'Dye' },
    ],
    E: [
      { q: 'Decorative needlework stitched onto the surface of cloth.', a: 'Embroidery' },
      { q: 'Flat Spanish shoe with a canvas upper and a rope sole.', a: 'Espadrille' },
      { q: 'Ornamental shoulder strap on a military-style coat.', a: 'Epaulette' },
      { q: 'Stretchy synthetic fibre also sold under the brand name Lycra.', a: 'Elastane' },
      { q: 'Small reinforced hole through which a lace is threaded.', a: 'Eyelet' },
      { q: 'White winter fur of the stoat, used to trim royal robes.', a: 'Ermine' },
      { q: 'High-waisted dress style sitting just under the bust, from Napoleon\'s day.', a: 'Empire line' },
      { q: 'Rubbery band sewn into a waistband so that it stretches.', a: 'Elastic' },
    ],
    F: [
      { q: 'Soft felt hat with a lengthwise crease in the crown.', a: 'Fedora' },
      { q: 'Italian shoemaker who made wedge heels for Hollywood stars.', a: 'Ferragamo' },
      { q: 'Young woman of the 1920s in a dropped-waist dress with bobbed hair.', a: 'Flapper' },
      { q: 'Soft brushed woollen cloth used for winter shirts and pyjamas.', a: 'Flannel' },
      { q: 'Decorative headpiece worn at weddings and races instead of a hat.', a: 'Fascinator' },
      { q: 'Border of loose hanging threads on the edge of a shawl.', a: 'Fringe' },
      { q: 'Animal pelt worn as a coat, now widely boycotted.', a: 'Fur' },
      { q: 'Session at which a garment is tried on and pinned for alteration.', a: 'Fitting' },
      { q: 'An old-fashioned word for a woman\'s dress.', a: 'Frock' },
      { q: 'Synthetic pile fabric made to imitate an animal pelt.', a: 'Faux fur' },
    ],
    G: [
      { q: 'Italian house founded in Florence in 1921, known for the horsebit loafer.', a: 'Gucci' },
      { q: 'French house whose founder dressed Audrey Hepburn in Breakfast at Tiffany\'s.', a: 'Givenchy' },
      { q: 'Checked cotton cloth woven in white and one other colour.', a: 'Gingham' },
      { q: 'Tightly woven twill invented by Thomas Burberry for raincoats.', a: 'Gabardine' },
      { q: 'Small extra piece of cloth sewn in to give room or strength.', a: 'Gusset' },
      { q: 'Crinkly sheer fabric named after a French dressmaker.', a: 'Georgette' },
      { q: 'French designer who made Madonna\'s cone bustier and wore a striped sailor top.', a: 'Gaultier' },
      { q: 'Hand covering with a separate sheath for each finger.', a: 'Glove' },
      { q: 'Early-1990s look of plaid shirts and ripped jeans, from Seattle music.', a: 'Grunge' },
      { q: 'The trade word for one finished piece of clothing, and the name of a New York manufacturing district.', a: 'Garment' },
      { q: 'Formal full-length dress for a ball or a wedding.', a: 'Gown' },
    ],
    H: [
      { q: 'French house known for its silk scarves and the Kelly bag.', a: 'Hermes' },
      { q: 'The finished bottom edge of a skirt or a pair of trousers.', a: 'Hem' },
      { q: 'French term for made-to-order clothes from a legally protected Paris house.', a: 'Haute couture' },
      { q: 'American designer of 1970s ultrasuede and jersey dresses for Studio 54.', a: 'Halston' },
      { q: 'Broken check pattern of small jagged shapes, usually black and white.', a: 'Houndstooth' },
      { q: 'Weave forming rows of slanting Vs, used in tweed jackets.', a: 'Herringbone' },
      { q: 'Casual sweatshirt with a head covering attached.', a: 'Hoodie' },
      { q: 'Small carrying case for a purse, keys and make-up.', a: 'Handbag' },
      { q: 'Word for a figure with a narrow waist and full bust and hips.', a: 'Hourglass' },
      { q: 'British couturier who designed the Queen\'s coronation gown in 1953.', a: 'Hartnell' },
      { q: 'Trade word for stockings, tights and socks.', a: 'Hosiery' },
    ],
    I: [
      { q: 'Deep blue plant dye traditionally used to colour denim.', a: 'Indigo' },
      { q: 'Measurement taken from the crotch to the bottom of a trouser leg.', a: 'Inseam' },
      { q: 'Japanese designer famous for permanently pleated polyester.', a: 'Issey Miyake' },
      { q: 'Heated appliance pressed over cloth to remove creases.', a: 'Iron' },
      { q: 'Stiffening layer sewn between the outer cloth and the inside of a collar.', a: 'Interfacing' },
    ],
    J: [
      { q: 'Trousers of blue cotton twill, first made for miners in California.', a: 'Jeans' },
      { q: 'Stretchy knitted fabric that Chanel made respectable for day dresses.', a: 'Jersey' },
      { q: 'One-piece garment that joins a top to a pair of trousers.', a: 'Jumpsuit' },
      { q: 'Malaysian-born shoemaker whose name became a luxury heel label.', a: 'Jimmy Choo' },
      { q: 'Ruffled frill of lace worn down the front of a shirt.', a: 'Jabot' },
      { q: 'Riding trousers, loose at the hip and tight from knee to ankle, named after an Indian city.', a: 'Jodhpurs' },
    ],
    K: [
      { q: 'Japanese T-shaped robe fastened with a wide sash.', a: 'Kimono' },
      { q: 'Long loose robe worn in North Africa and the Middle East.', a: 'Kaftan' },
      { q: 'German designer who led Chanel from 1983 until his death in 2019.', a: 'Karl Lagerfeld' },
      { q: 'Boxy Hermes leather purse named after the American film star who became Princess of Monaco.', a: 'Kelly bag' },
      { q: 'Category of clothing made from interlocking loops of wool.', a: 'Knitwear' },
      { q: 'Dust-coloured cotton cloth first used for army uniforms in India.', a: 'Khaki' },
    ],
    L: [
      { q: 'Delicate openwork fabric formed of patterned holes.', a: 'Lace' },
      { q: 'Folded flap on the front of a jacket, beside the collar.', a: 'Lapel' },
      { q: 'Cool summer cloth woven from the fibres of the flax plant.', a: 'Linen' },
      { q: 'French shoemaker whose towering heels have glossy red soles.', a: 'Louboutin' },
      { q: 'French house whose monogrammed trunks began with a 19th-century box maker.', a: 'Louis Vuitton' },
      { q: 'The simple dark garment Chanel made a wardrobe staple in the 1920s.', a: 'Little black dress' },
      { q: 'Slip-on leather shoe worn without laces.', a: 'Loafer' },
      { q: 'Treated animal hide used for jackets, bags and shoes.', a: 'Leather' },
      { q: 'Inner layer of smooth fabric that finishes the inside of a jacket.', a: 'Lining' },
      { q: 'Bavarian-born trader who patented riveted work trousers in 1873.', a: 'Levi Strauss' },
    ],
    M: [
      { q: 'Dummy figure used to display clothes in a shop window.', a: 'Mannequin' },
      { q: 'Loosely woven cotton used to make test versions of a garment.', a: 'Muslin' },
      { q: 'Silky fibre shorn from the Angora goat.', a: 'Mohair' },
      { q: 'The very short hemline that defined 1960s London style.', a: 'Miniskirt' },
      { q: 'American designer who was creative director of Louis Vuitton from 1997 to 2013.', a: 'Marc Jacobs' },
      { q: 'British designer of the low-cut bumster trousers who died in 2010.', a: 'McQueen' },
      { q: 'Italian city whose fashion week is one of the big four.', a: 'Milan' },
      { q: 'Design made from a person\'s initials, used on luggage and shirts.', a: 'Monogram' },
      { q: 'Soft flat shoe of Native American origin with a seam over the toe.', a: 'Moccasin' },
      { q: 'American designer who ran womenswear at Celine before building his own accessible luxury label.', a: 'Michael Kors' },
      { q: 'The annual New York museum fundraiser that is fashion\'s biggest party.', a: 'Met Gala' },
      { q: 'Backless slip-on shoes.', a: 'Mules' },
    ],
    N: [
      { q: 'Synthetic fibre introduced by DuPont in 1939 for stockings.', a: 'Nylon' },
      { q: 'Dior\'s 1947 collection of full skirts and tightly nipped waists.', a: 'New Look' },
      { q: 'Thin pointed tool with a hole at one end for thread.', a: 'Needle' },
      { q: 'Ornament worn around the throat.', a: 'Necklace' },
      { q: 'British supermodel who in 1988 became the first black woman on the cover of French Vogue.', a: 'Naomi Campbell' },
      { q: 'Loose garment worn in bed.', a: 'Nightgown' },
      { q: 'Straight-cut coat with a stand-up collar, named after an Indian prime minister.', a: 'Nehru jacket' },
    ],
    O: [
      { q: 'Crisp sheer fabric used for stiff overlays and bridal skirts.', a: 'Organza' },
      { q: 'Dominican-born couturier who dressed several American first ladies.', a: 'Oscar de la Renta' },
      { q: 'Long heavy garment worn on top of a suit in winter.', a: 'Overcoat' },
      { q: 'Colouring effect in which a shade fades gradually from dark to light.', a: 'Ombre' },
      { q: 'A complete set of clothes chosen to be worn together.', a: 'Outfit' },
      { q: 'Lace-up leather shoe with a closed front, named after a university city.', a: 'Oxford' },
    ],
    P: [
      { q: 'Italian house from Milan whose nylon backpacks became 1990s status symbols.', a: 'Prada' },
      { q: 'Fold pressed or stitched into cloth to create fullness.', a: 'Pleat' },
      { q: 'Light underskirt worn beneath a dress.', a: 'Petticoat' },
      { q: 'French couturier who freed women from corsets before the First World War.', a: 'Poiret' },
      { q: 'Cheap crease-resistant synthetic fabric made from oil.', a: 'Polyester' },
      { q: 'Long hooded winter jacket, often trimmed with fur at the hood.', a: 'Parka' },
      { q: 'Short flared frill attached at the waist of a jacket or dress.', a: 'Peplum' },
      { q: 'Sleeveless outer garment made from one piece of cloth with a hole for the head.', a: 'Poncho' },
      { q: 'The fine vertical white lines running down a formal business suit.', a: 'Pinstripe' },
      { q: 'Paper template that a dressmaker cuts the fabric around.', a: 'Pattern' },
      { q: 'Small pouch sewn into a garment for carrying things.', a: 'Pocket' },
      { q: 'Fine shawl woven from soft goat wool in Kashmir.', a: 'Pashmina' },
    ],
    R: [
      { q: 'American designer whose polo player logo appeared on shirts from 1972.', a: 'Ralph Lauren' },
      { q: 'Strip of gathered cloth sewn on as decoration.', a: 'Ruffle' },
      { q: 'Semi-synthetic fibre made from wood pulp, once sold as artificial silk.', a: 'Rayon' },
      { q: 'Japanese founder of the avant-garde label Comme des Garcons.', a: 'Rei Kawakubo' },
      { q: 'Shoulder style whose seam runs diagonally from the neck to the underarm.', a: 'Raglan' },
      { q: 'English term for factory-made collections sold in standard sizes.', a: 'Ready-to-wear' },
      { q: 'Loose gown thrown on over nightclothes.', a: 'Robe' },
      { q: 'Metal stud that strengthens the pocket corners on a pair of jeans.', a: 'Rivet' },
      { q: 'Sparkling imitation gem used to decorate a costume.', a: 'Rhinestone' },
    ],
    S: [
      { q: 'Fibre unwound from the cocoon of a moth caterpillar.', a: 'Silk' },
      { q: 'Fabric with a glossy front and a dull back.', a: 'Satin' },
      { q: 'Leather with a soft napped finish.', a: 'Suede' },
      { q: 'Small shiny disc sewn onto a dress for sparkle.', a: 'Sequin' },
      { q: 'Very high thin heel named after a dagger.', a: 'Stiletto' },
      { q: 'Italian couturier who worked with Dali and invented shocking pink.', a: 'Schiaparelli' },
      { q: 'The London street synonymous with bespoke tailoring.', a: 'Savile Row' },
      { q: 'Where two pieces of fabric are stitched together.', a: 'Seam' },
      { q: 'Length of cloth wrapped and draped as a garment in India.', a: 'Sari' },
      { q: 'The overall outline that a garment gives the body.', a: 'Silhouette' },
      { q: 'British designer, daughter of a Beatle, who refuses to use leather or fur.', a: 'Stella McCartney' },
      { q: 'Cloth wrapped round the waist as a skirt in Southeast Asia.', a: 'Sarong' },
      { q: 'Puckered striped cotton favoured for hot summer suits.', a: 'Seersucker' },
      { q: 'American word for a soft rubber-soled sports shoe.', a: 'Sneaker' },
    ],
    T: [
      { q: 'Rough woollen cloth woven in Scotland for country jackets.', a: 'Tweed' },
      { q: 'American name for a dinner jacket, from a New York country club.', a: 'Tuxedo' },
      { q: 'Crisp shiny fabric that rustles, used for ball gowns.', a: 'Taffeta' },
      { q: 'Fine stiff net used for veils and ballet skirts.', a: 'Tulle' },
      { q: 'Woven pattern of crossed bands identifying a Scottish clan.', a: 'Tartan' },
      { q: 'Belted military-style raincoat with a storm flap, from the First World War.', a: 'Trench coat' },
      { q: 'American designer who revived Gucci in the 1990s.', a: 'Tom Ford' },
      { q: 'American designer of preppy red, white and blue casual wear.', a: 'Tommy Hilfiger' },
      { q: 'Long cloth wound round the head.', a: 'Turban' },
      { q: 'Metal cap that protects a fingertip while sewing.', a: 'Thimble' },
      { q: 'Test version of a garment run up in cheap cloth before the real one.', a: 'Toile' },
      { q: 'Large open-topped bag with two handles.', a: 'Tote' },
      { q: 'Matching cardigan and short-sleeved sweater worn as a pair.', a: 'Twinset' },
    ],
    U: [
      { q: 'Japanese casual-wear chain owned by Fast Retailing.', a: 'Uniqlo' },
      { q: 'Standard set of clothing worn by every member of a school or a force.', a: 'Uniform' },
      { q: 'General term for garments worn next to the skin beneath everything else.', a: 'Underwear' },
      { q: 'Making desirable new garments out of discarded old ones.', a: 'Upcycling' },
    ],
    V: [
      { q: 'Italian house with a Medusa head logo whose founder was killed in 1997.', a: 'Versace' },
      { q: 'Fabric with a short dense pile that catches the light.', a: 'Velvet' },
      { q: 'Italian couturier known for one particular shade of red.', a: 'Valentino' },
      { q: 'French couturier who mastered cutting cloth on the diagonal in the 1920s.', a: 'Vionnet' },
      { q: 'The magazine first published in New York in 1892 and now the industry bible.', a: 'Vogue' },
      { q: 'Length of net that covers a bride\'s face.', a: 'Veil' },
      { q: 'Hook and loop fastening invented by a Swiss engineer.', a: 'Velcro' },
    ],
    W: [
      { q: 'British designer who dressed the punk scene from a King\'s Road shop.', a: 'Westwood' },
      { q: 'Fibre shorn from a sheep.', a: 'Wool' },
      { q: 'Sleeveless buttoned garment worn under a suit jacket.', a: 'Waistcoat' },
      { q: 'The tall cupboard in which clothes are hung.', a: 'Wardrobe' },
      { q: 'English-born couturier in Paris regarded as the father of made-to-order fashion.', a: 'Worth' },
      { q: 'Shoe with a solid sole that rises steadily from toe to heel.', a: 'Wedge' },
      { q: 'Wide triangular way of tying a necktie, named after a royal duke.', a: 'Windsor knot' },
      { q: 'The way threads cross over and under each other in a cloth.', a: 'Weave' },
    ],
    Y: [
      { q: 'The French designer who created Le Smoking, the 1966 dinner suit for women.', a: 'Yves Saint Laurent' },
      { q: 'Shaped panel across the shoulders of a shirt.', a: 'Yoke' },
      { q: 'Spun thread sold in balls for knitting.', a: 'Yarn' },
      { q: 'Japanese designer of oversized black draping who first showed in Paris in 1981.', a: 'Yohji Yamamoto' },
    ],
  },
};
