import type { RawPack } from '../core/packs';

export const footballEasyPack: RawPack = {
  id: 'football-easy',
  name: 'Football · Easy',
  description: 'Legendary players, big clubs, World Cup moments and the basics of the beautiful game.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '⚽',
  accent: '#15803d',
  letters: {
    A: [
      { q: 'National team that won the 2022 World Cup in Qatar.', a: 'Argentina' },
      { q: 'London club nicknamed the Gunners that went unbeaten through the 2003-04 Premier League season.', a: 'Arsenal' },
      { q: 'Italian club in red and black stripes that has lifted the European Cup and Champions League seven times.', a: 'AC Milan' },
      { q: 'Amsterdam club famous for its youth academy, where Johan Cruyff began his career.', a: 'Ajax' },
      { q: 'The home stadium of Liverpool FC.', a: 'Anfield' },
      { q: 'Brazilian goalkeeper who joined Liverpool in 2018 and won the 2019 Champions League with them.', a: 'Alisson' },
      { q: 'Spanish club managed for years by Diego Simeone that won La Liga in 2014 and 2021.', a: 'Atletico Madrid', alt: ['Atletico'] },
      { q: 'The term for the final pass that directly sets up a goal.', a: 'Assist' },
      { q: 'Argentine striker whose stoppage-time goal in 2012 won Manchester City their first Premier League title (surname).', a: 'Aguero', alt: ['Sergio Aguero'] },
      { q: 'Italian manager who has won the Champions League a record number of times as a coach (surname).', a: 'Ancelotti', alt: ['Carlo Ancelotti'] },
      { q: 'Spanish midfielder who won the 2010 World Cup and later led Bayer Leverkusen to an unbeaten league title as a manager (surname).', a: 'Alonso', alt: ['Xabi Alonso'] },
    ],
    B: [
      { q: 'The only national team to have won the World Cup five times.', a: 'Brazil' },
      { q: 'Spanish club whose home ground is the Camp Nou.', a: 'Barcelona', alt: ['FC Barcelona', 'Barca'] },
      { q: 'English midfielder famous for bending free kicks who wore number 7 at Manchester United (surname).', a: 'Beckham', alt: ['David Beckham'] },
      { q: 'German club that has won the Bundesliga far more often than any other.', a: 'Bayern Munich', alt: ['Bayern'] },
      { q: 'The acrobatic overhead volley that Pele made world famous.', a: 'Bicycle kick', alt: ['Overhead kick'] },
      { q: 'Italian goalkeeper who lifted the 2006 World Cup and played over 600 Serie A matches (surname).', a: 'Buffon', alt: ['Gianluigi Buffon'] },
      { q: 'The golden trophy awarded each year by France Football to the best player in the world.', a: "Ballon d'Or" },
      { q: 'German club whose Yellow Wall of fans fills one end of the Westfalenstadion.', a: 'Borussia Dortmund', alt: ['Dortmund'] },
      { q: 'National team of Kevin De Bruyne and Eden Hazard that finished third at the 2018 World Cup.', a: 'Belgium' },
      { q: 'French striker who won the 2022 Ballon d\'Or after a stunning Champions League run with Real Madrid (surname).', a: 'Benzema', alt: ['Karim Benzema'] },
      { q: 'Buenos Aires club in blue and gold where Maradona became an idol.', a: 'Boca Juniors', alt: ['Boca'] },
      { q: 'The flashy pass or flick made with the rear of the foot.', a: 'Back heel', alt: ['Backheel'] },
      { q: 'Welsh forward whose overhead kick lit up the 2018 Champions League final (surname).', a: 'Bale', alt: ['Gareth Bale'] },
    ],
    C: [
      { q: 'The restart awarded to the attacking team when defenders put the ball behind their own goal line.', a: 'Corner kick', alt: ['Corner'] },
      { q: 'The giant home stadium of FC Barcelona.', a: 'Camp Nou', alt: ['Nou Camp'] },
      { q: 'West London club that won the Champions League in 2012 and 2021.', a: 'Chelsea' },
      { q: 'Portuguese superstar who wears number 7 and has scored more than 100 goals for his national team.', a: 'Cristiano Ronaldo' },
      { q: 'Dutch legend of the 1974 World Cup who gave his name to a famous turn (surname).', a: 'Cruyff', alt: ['Johan Cruyff'] },
      { q: 'Spanish goalkeeper who captained his country to the 2010 World Cup title (surname).', a: 'Casillas', alt: ['Iker Casillas'] },
      { q: 'National team in a red and white checkerboard shirt that reached the 2018 World Cup final.', a: 'Croatia' },
      { q: 'The oldest international football championship, played between South American nations.', a: 'Copa America' },
      { q: 'French forward famous for his upturned collar and swagger at Manchester United in the 1990s (surname).', a: 'Cantona', alt: ['Eric Cantona'] },
      { q: 'The term for a match in which a goalkeeper concedes no goals.', a: 'Clean sheet' },
      { q: 'The player who wears the armband and leads the team out.', a: 'Captain' },
      { q: 'Brazilian right-back who played in three straight World Cup finals and lifted the trophy in 2002.', a: 'Cafu' },
    ],
    D: [
      { q: 'The skill of running with the ball under close control to beat defenders.', a: 'Dribbling', alt: ['Dribble'] },
      { q: 'The position of the players whose main job is stopping the opposition from scoring.', a: 'Defender' },
      { q: 'Argentine-born forward who starred in Real Madrid\'s five straight European Cup wins in the 1950s (surname).', a: 'Di Stefano', alt: ['Alfredo Di Stefano'] },
      { q: 'Ivorian striker who scored the decisive penalty to win Chelsea the 2012 Champions League (surname).', a: 'Drogba', alt: ['Didier Drogba'] },
      { q: 'The word for a match between two rival clubs from the same city.', a: 'Derby' },
      { q: 'Belgian midfield playmaker who won six Premier League titles with Manchester City (surname).', a: 'De Bruyne', alt: ['Kevin De Bruyne'] },
      { q: 'Italian goalkeeper named player of the tournament at Euro 2020 (surname).', a: 'Donnarumma', alt: ['Gianluigi Donnarumma'] },
      { q: 'Scandinavian national team that shocked Europe by winning Euro 1992.', a: 'Denmark' },
      { q: 'The word for falling to the ground pretending to have been fouled.', a: 'Dive' },
      { q: 'Italian forward who spent 19 seasons at Juventus and won the 2006 World Cup (surname).', a: 'Del Piero', alt: ['Alessandro Del Piero'] },
    ],
    E: [
      { q: 'National team that won its only World Cup on home soil in 1966.', a: 'England' },
      { q: 'The home stadium of Manchester City.', a: 'Etihad Stadium', alt: ['Etihad'] },
      { q: 'The name given to matches between Real Madrid and Barcelona.', a: 'El Clasico', alt: ['Clasico'] },
      { q: 'Cameroonian striker who won two Champions Leagues with Barcelona and one with Inter (surname).', a: 'Eto\'o', alt: ['Samuel Eto\'o'] },
      { q: 'The number of players each team fields at the start of a match.', a: 'Eleven', alt: ['11'] },
      { q: 'Merseyside club in blue that shares its city with a famous red rival.', a: 'Everton' },
      { q: 'Danish midfielder who collapsed on the pitch at Euro 2020 and returned to play at the 2022 World Cup (surname).', a: 'Eriksen', alt: ['Christian Eriksen'] },
      { q: 'The two additional 15-minute periods played when a knockout match is level after 90 minutes.', a: 'Extra time' },
      { q: 'African country that has won the Africa Cup of Nations a record seven times.', a: 'Egypt' },
      { q: 'Portuguese great nicknamed the Black Panther, top scorer at the 1966 World Cup.', a: 'Eusebio' },
    ],
    F: [
      { q: 'National team that won the World Cup in 1998 and again in 2018.', a: 'France' },
      { q: 'The set piece awarded after a foul outside the penalty area.', a: 'Free kick' },
      { q: 'The world governing body of the sport, which organises the World Cup.', a: 'FIFA' },
      { q: 'Scottish manager who won 13 Premier League titles with Manchester United (surname).', a: 'Ferguson', alt: ['Alex Ferguson', 'Sir Alex Ferguson'] },
      { q: 'The world\'s oldest national knockout competition, played in England since 1871.', a: 'FA Cup' },
      { q: 'Portuguese winger whose 2000 move from Barcelona to Real Madrid stunned the sport (surname).', a: 'Figo', alt: ['Luis Figo'] },
      { q: 'The referee\'s ruling when a player kicks, trips or pushes an opponent.', a: 'Foul' },
      { q: 'The defender who plays on the left or right of a defensive four, usually marking wingers.', a: 'Full-back', alt: ['Fullback'] },
      { q: 'French striker who scored a record 13 goals at the 1958 World Cup (surname).', a: 'Fontaine', alt: ['Just Fontaine'] },
    ],
    G: [
      { q: 'National team that has won four World Cups, including the 2014 final against Argentina.', a: 'Germany' },
      { q: 'The only player allowed to handle the ball inside the penalty area.', a: 'Goalkeeper', alt: ['Keeper', 'Goalie'] },
      { q: 'The award given to the top scorer at a World Cup.', a: 'Golden Boot' },
      { q: 'Liverpool captain who inspired the famous 2005 Champions League comeback in Istanbul (surname).', a: 'Gerrard', alt: ['Steven Gerrard'] },
      { q: 'Manager who won the treble with Barcelona in 2009 and with Manchester City in 2023 (surname).', a: 'Guardiola', alt: ['Pep Guardiola', 'Pep'] },
      { q: 'French forward who won the Silver Boot and the World Cup in 2018 (surname).', a: 'Griezmann', alt: ['Antoine Griezmann'] },
      { q: 'The marking between the posts that the whole ball must cross for a score to count.', a: 'Goal line' },
      { q: 'African team that came within a missed 2010 penalty of reaching a World Cup semi-final.', a: 'Ghana' },
      { q: 'Welsh winger who spent 24 seasons in the first team at Manchester United (surname).', a: 'Giggs', alt: ['Ryan Giggs'] },
      { q: 'What a team scores when the ball fully crosses the line between the posts and under the bar.', a: 'Goal' },
      { q: 'The restart the defending side takes from its own six-yard box.', a: 'Goal kick' },
    ],
    H: [
      { q: 'The term for three goals scored by one player in a single match.', a: 'Hat-trick', alt: ['Hat trick'] },
      { q: 'The offence of deliberately touching the ball with the arm.', a: 'Handball' },
      { q: 'French striker who became Arsenal\'s all-time top scorer (surname).', a: 'Henry', alt: ['Thierry Henry'] },
      { q: 'Belgian winger who starred for Chelsea before a big move to Real Madrid in 2019 (surname).', a: 'Hazard', alt: ['Eden Hazard'] },
      { q: 'Maradona\'s nickname for his punched goal against England at the 1986 World Cup.', a: 'Hand of God' },
      { q: 'The technique of scoring or passing the ball with the forehead.', a: 'Header' },
      { q: 'Norwegian striker who broke the Premier League single-season scoring record in 2022-23 (surname).', a: 'Haaland', alt: ['Erling Haaland'] },
      { q: 'Country of the great 1950s Mighty Magyars side led by Ferenc Puskas.', a: 'Hungary' },
      { q: 'Pioneering American women\'s forward who won two World Cups and scored 158 international goals (surname).', a: 'Hamm', alt: ['Mia Hamm'] },
    ],
    I: [
      { q: 'National team that won the World Cup in 2006 and Euro 2020.', a: 'Italy' },
      { q: 'Spanish midfielder who scored the winning goal in the 2010 World Cup final (surname).', a: 'Iniesta', alt: ['Andres Iniesta'] },
      { q: 'Italian club that won the treble in 2010 under Jose Mourinho.', a: 'Inter Milan', alt: ['Inter', 'Internazionale'] },
      { q: 'Swedish striker famous for spectacular goals and supreme self-confidence (surname).', a: 'Ibrahimovic', alt: ['Zlatan Ibrahimovic', 'Zlatan'] },
      { q: 'The minutes added at the end of each half to make up for stoppages.', a: 'Injury time', alt: ['Stoppage time', 'Added time'] },
      { q: 'Small island nation whose thunderclap celebration lit up Euro 2016.', a: 'Iceland' },
      { q: 'West African nation of Didier Drogba and Yaya Toure, nicknamed the Elephants.', a: 'Ivory Coast' },
      { q: 'City where Liverpool staged their famous 2005 Champions League final comeback.', a: 'Istanbul' },
    ],
    J: [
      { q: 'Turin club in black and white stripes that won nine straight Serie A titles in the 2010s.', a: 'Juventus', alt: ['Juve'] },
      { q: 'Asian team that beat both Germany and Spain at the 2022 World Cup.', a: 'Japan' },
      { q: 'Another word for the shirt a player wears.', a: 'Jersey' },
      { q: 'The name of the original World Cup trophy, given to Brazil to keep in 1970.', a: 'Jules Rimet Trophy', alt: ['Jules Rimet'] },
      { q: 'Colombian playmaker who won the Golden Boot at the 2014 World Cup.', a: 'James Rodriguez', alt: ['James'] },
      { q: 'Caribbean nation whose team is nicknamed the Reggae Boyz.', a: 'Jamaica' },
      { q: 'Italian midfielder who won Euro 2020 and the Champions League with Chelsea in the same year (surname).', a: 'Jorginho' },
    ],
    K: [
      { q: 'England striker who won the Golden Boot at the 2018 World Cup (surname).', a: 'Kane', alt: ['Harry Kane'] },
      { q: 'German manager who ended Liverpool\'s 30-year league title wait in 2020 (surname).', a: 'Klopp', alt: ['Jurgen Klopp'] },
      { q: 'Brazilian playmaker who won the 2007 Ballon d\'Or while at AC Milan.', a: 'Kaka' },
      { q: 'The way play starts at the beginning of each half and after every goal.', a: 'Kickoff', alt: ['Kick-off'] },
      { q: 'German midfielder who won the 2014 World Cup and multiple Champions Leagues with Real Madrid (surname).', a: 'Kroos', alt: ['Toni Kroos'] },
      { q: 'The famous stand of home supporters at Anfield.', a: 'Kop', alt: ['The Kop'] },
      { q: 'French midfielder who won back-to-back Premier League titles with Leicester and then Chelsea (surname).', a: 'Kante', alt: ['N\'Golo Kante'] },
      { q: 'Belgian captain of Manchester City\'s first Premier League title winners (surname).', a: 'Kompany', alt: ['Vincent Kompany'] },
    ],
    L: [
      { q: 'Merseyside club whose anthem is You\'ll Never Walk Alone.', a: 'Liverpool' },
      { q: 'The top division of Spanish club football.', a: 'La Liga' },
      { q: 'Polish striker who scored 41 Bundesliga goals in a single season for Bayern Munich (surname).', a: 'Lewandowski', alt: ['Robert Lewandowski'] },
      { q: 'Chelsea midfielder who became the club\'s all-time top scorer (surname).', a: 'Lampard', alt: ['Frank Lampard'] },
      { q: 'Club that won the 2016 Premier League title as 5000-1 outsiders.', a: 'Leicester City', alt: ['Leicester'] },
      { q: 'Argentine great who finally lifted the World Cup in 2022 after winning a record number of Ballons d\'Or.', a: 'Lionel Messi', alt: ['Messi'] },
      { q: 'The arrangement where a club lets a player join another team temporarily.', a: 'Loan' },
      { q: 'The top division of French club football.', a: 'Ligue 1' },
      { q: 'England striker who won the Golden Boot at the 1986 World Cup and was never booked in his career (surname).', a: 'Lineker', alt: ['Gary Lineker'] },
    ],
    M: [
      { q: 'Argentine legend who captained his country to the 1986 World Cup (surname).', a: 'Maradona', alt: ['Diego Maradona'] },
      { q: 'English club nicknamed the Red Devils that plays at Old Trafford.', a: 'Manchester United', alt: ['Man United', 'Man Utd'] },
      { q: 'Sky-blue English club that won the treble in 2023.', a: 'Manchester City', alt: ['Man City'] },
      { q: 'French forward who scored a hat-trick in the 2022 World Cup final (surname).', a: 'Mbappe', alt: ['Kylian Mbappe'] },
      { q: 'Croatian midfielder who won the 2018 Ballon d\'Or (surname).', a: 'Modric', alt: ['Luka Modric'] },
      { q: 'The self-styled Special One who won Champions League titles with Porto and Inter (surname).', a: 'Mourinho', alt: ['Jose Mourinho'] },
      { q: 'The giant Rio de Janeiro stadium that hosted the 1950 and 2014 World Cup finals.', a: 'Maracana' },
      { q: 'The position that links defence and attack in the middle of the pitch.', a: 'Midfielder' },
      { q: 'North American country that hosted the World Cup in both 1970 and 1986.', a: 'Mexico' },
      { q: 'The first African nation to reach a World Cup semi-final, in 2022.', a: 'Morocco' },
      { q: 'Surname shared by German greats Gerd and Thomas, both World Cup winners.', a: 'Muller', alt: ['Mueller'] },
      { q: 'The only French club to have won the Champions League, in 1993.', a: 'Marseille', alt: ['Olympique de Marseille'] },
    ],
    N: [
      { q: 'National team in orange famous for Total Football that has lost three World Cup finals.', a: 'Netherlands', alt: ['Holland'] },
      { q: 'Brazilian forward whose 2017 move to Paris Saint-Germain set the world transfer record.', a: 'Neymar' },
      { q: 'German goalkeeper famous for playing as a sweeper-keeper, a 2014 World Cup winner (surname).', a: 'Neuer', alt: ['Manuel Neuer'] },
      { q: 'The trick of playing the ball between an opponent\'s legs.', a: 'Nutmeg' },
      { q: 'African nation nicknamed the Super Eagles that won Olympic gold in 1996.', a: 'Nigeria' },
      { q: 'Surname of English full-back brothers Gary and Phil, long-serving Manchester United defenders.', a: 'Neville' },
      { q: 'The number of minutes in a standard match before any added time.', a: 'Ninety', alt: ['90'] },
    ],
    O: [
      { q: 'Manchester United\'s home stadium, nicknamed the Theatre of Dreams.', a: 'Old Trafford' },
      { q: 'The rule broken when an attacker is beyond the last defender as the ball is played forward.', a: 'Offside' },
      { q: 'The term for accidentally putting the ball into your own net.', a: 'Own goal' },
      { q: 'German playmaker who won the 2014 World Cup and starred for Real Madrid and Arsenal (surname).', a: 'Ozil', alt: ['Mesut Ozil'] },
      { q: 'English striker who scored a wonder goal against Argentina at the 1998 World Cup as a teenager (surname).', a: 'Owen', alt: ['Michael Owen'] },
      { q: 'The quick pass-and-return move also called a give-and-go.', a: 'One-two', alt: ['One two'] },
    ],
    P: [
      { q: 'Brazilian legend who won three World Cups, in 1958, 1962 and 1970.', a: 'Pele' },
      { q: 'The kick awarded from twelve yards after a foul inside the box.', a: 'Penalty', alt: ['Penalty kick'] },
      { q: 'England\'s top club division since 1992.', a: 'Premier League' },
      { q: 'National team that won its first major trophy at Euro 2016.', a: 'Portugal' },
      { q: 'French capital club backed by Qatari owners since 2011.', a: 'Paris Saint-Germain', alt: ['PSG'] },
      { q: 'The common word for the playing field.', a: 'Pitch' },
      { q: 'Hungarian great whose surname is on FIFA\'s award for the best goal of the year.', a: 'Puskas', alt: ['Ferenc Puskas'] },
      { q: 'Italian deep-lying playmaker famous for his beard and free kicks, a 2006 World Cup winner (surname).', a: 'Pirlo', alt: ['Andrea Pirlo'] },
      { q: 'England goalkeeper who starred in the 2018 World Cup shootout win over Colombia (surname).', a: 'Pickford', alt: ['Jordan Pickford'] },
      { q: 'The statistic measuring how much of the match a team keeps the ball.', a: 'Possession' },
      { q: 'French midfielder who scored in the 2018 World Cup final and joined Manchester United twice (surname).', a: 'Pogba', alt: ['Paul Pogba'] },
      { q: 'French playmaker who won three straight Ballons d\'Or in the 1980s (surname).', a: 'Platini', alt: ['Michel Platini'] },
    ],
    Q: [
      { q: 'The Middle Eastern country that hosted the 2022 World Cup.', a: 'Qatar' },
    ],
    R: [
      { q: 'Spanish club with a record number of European Cup and Champions League titles.', a: 'Real Madrid' },
      { q: 'Smiling Brazilian magician who won the 2005 Ballon d\'Or while at Barcelona.', a: 'Ronaldinho' },
      { q: 'The official who enforces the laws of the game on the pitch.', a: 'Referee' },
      { q: 'What a player is shown when being sent off.', a: 'Red card' },
      { q: 'Spanish defender who scored a famous 93rd-minute header in the 2014 Champions League final (surname).', a: 'Ramos', alt: ['Sergio Ramos'] },
      { q: 'Striker who became the all-time top scorer for both England and Manchester United (surname).', a: 'Rooney', alt: ['Wayne Rooney'] },
      { q: 'Brazilian striker nicknamed O Fenomeno who scored both goals in the 2002 World Cup final.', a: 'Ronaldo', alt: ['Ronaldo Nazario'] },
      { q: 'The fate of teams that finish at the bottom of a league.', a: 'Relegation' },
      { q: 'Dutch winger famous for cutting inside on his left foot, who won the 2013 Champions League with Bayern (surname).', a: 'Robben', alt: ['Arjen Robben'] },
      { q: 'Buenos Aires giant that contests the Superclasico with Boca Juniors.', a: 'River Plate' },
      { q: 'Brazilian 1999 Ballon d\'Or winner who starred in the 2002 World Cup-winning side.', a: 'Rivaldo' },
      { q: 'Brazilian left-back famous for a physics-defying banana free kick against France in 1997.', a: 'Roberto Carlos' },
    ],
    S: [
      { q: 'National team that won three straight major tournaments from 2008 to 2012.', a: 'Spain' },
      { q: 'The position whose main job is scoring goals at the front of the team.', a: 'Striker', alt: ['Forward'] },
      { q: 'The Milan stadium shared for decades by two great Italian rivals.', a: 'San Siro' },
      { q: 'Egyptian forward nicknamed the Pharaoh who broke Premier League scoring records with Liverpool (surname).', a: 'Salah', alt: ['Mohamed Salah', 'Mo Salah'] },
      { q: 'The Premier League\'s all-time record goalscorer with 260 goals (surname).', a: 'Shearer', alt: ['Alan Shearer'] },
      { q: 'The top division of Italian club football.', a: 'Serie A' },
      { q: 'Uruguayan striker who joined Barcelona\'s famous MSN attack in 2014 (surname).', a: 'Suarez', alt: ['Luis Suarez'] },
      { q: 'A player who comes off the bench to replace a teammate.', a: 'Substitute', alt: ['Sub'] },
      { q: 'African nation led by Sadio Mane that won its first Africa Cup of Nations in 2022.', a: 'Senegal' },
      { q: 'Manchester United midfielder famous for long-range strikes, part of the Class of 92 (surname).', a: 'Scholes', alt: ['Paul Scholes'] },
      { q: 'Brazilian club where Pele spent almost his entire career.', a: 'Santos' },
    ],
    T: [
      { q: 'The two-handed restart used when the ball crosses the touchline.', a: 'Throw-in', alt: ['Throw in'] },
      { q: 'The nickname for the short-passing style of Spain and Barcelona.', a: 'Tiki-taka', alt: ['Tiki taka'] },
      { q: 'One-club Roma legend who won the 2006 World Cup with Italy (surname).', a: 'Totti', alt: ['Francesco Totti'] },
      { q: 'North London club whose crest features a cockerel standing on a ball.', a: 'Tottenham Hotspur', alt: ['Tottenham', 'Spurs'] },
      { q: 'The word for winning the league, the domestic cup and the Champions League in one season.', a: 'Treble' },
      { q: 'The challenge used to win the ball cleanly from an opponent\'s feet.', a: 'Tackle' },
      { q: 'The period of the year when clubs are allowed to buy and sell players.', a: 'Transfer window' },
      { q: 'Ivorian midfielder Yaya, who powered Manchester City\'s early title wins (surname).', a: 'Toure', alt: ['Yaya Toure'] },
    ],
    U: [
      { q: 'South American country that won the very first World Cup in 1930.', a: 'Uruguay' },
      { q: 'The governing body of European football, which runs the Champions League.', a: 'UEFA' },
      { q: 'Country that co-hosts the 2026 World Cup along with Canada and Mexico.', a: 'United States', alt: ['USA', 'America'] },
      { q: 'Eastern European nation of Ballon d\'Or winner Andriy Shevchenko.', a: 'Ukraine' },
    ],
    V: [
      { q: 'The video review system introduced to help referees with big decisions.', a: 'VAR', alt: ['Video Assistant Referee'] },
      { q: 'Dutch striker famous for an unbelievable angled volley in the Euro 88 final (surname).', a: 'Van Basten', alt: ['Marco van Basten'] },
      { q: 'Striking the ball cleanly before it touches the ground.', a: 'Volley' },
      { q: 'Dutch centre-back who anchored Liverpool\'s 2019 Champions League-winning defence (surname).', a: 'Van Dijk', alt: ['Virgil van Dijk'] },
      { q: 'Brazilian winger who scored the winning goal in the 2022 Champions League final.', a: 'Vinicius Junior', alt: ['Vinicius', 'Vini Jr'] },
    ],
    W: [
      { q: 'The tournament held every four years to crown the best national team on the planet.', a: 'World Cup' },
      { q: 'London stadium with a giant arch that hosts England matches and FA Cup finals.', a: 'Wembley' },
      { q: 'The line of defenders standing together to block a free kick.', a: 'Wall' },
      { q: 'The position played wide near the touchlines.', a: 'Winger' },
      { q: 'British nation captained by Gareth Bale at the 2022 World Cup.', a: 'Wales' },
      { q: 'Frenchman who managed Arsenal for 22 years, including the Invincibles season (surname).', a: 'Wenger', alt: ['Arsene Wenger'] },
      { q: 'Liberian striker, the only African to win the Ballon d\'Or, who later became his country\'s president (surname).', a: 'Weah', alt: ['George Weah'] },
    ],
    X: [
      { q: 'Spanish midfield maestro who ran Barcelona\'s tiki-taka engine alongside Iniesta for over a decade.', a: 'Xavi', alt: ['Xavi Hernandez'] },
    ],
    Y: [
      { q: 'The caution a referee shows a player for a bad foul.', a: 'Yellow card' },
      { q: 'Soviet goalkeeper nicknamed the Black Spider, the only keeper to win the Ballon d\'Or (surname).', a: 'Yashin', alt: ['Lev Yashin'] },
      { q: 'Spanish teenager who became the youngest scorer in European Championship history in 2024 (surname).', a: 'Yamal', alt: ['Lamine Yamal'] },
    ],
    Z: [
      { q: 'French great who scored twice in the 1998 World Cup final and was sent off in the 2006 final (surname).', a: 'Zidane', alt: ['Zinedine Zidane'] },
      { q: 'Brazilian playmaker of the brilliant 1982 side, nicknamed the White Pele.', a: 'Zico' },
    ],
  },
};
