import type { RawQuestion } from '../core/packs';

export const extraGeneralKnowledge3: Record<string, RawQuestion[]> = {
  A: [
    { q: 'What is the capital city of Australia?', a: 'Canberra', category: 'geography' },
    { q: 'What element has the chemical symbol Au?', a: 'Gold', category: 'science' },
    { q: 'Which ocean is the largest on Earth?', a: 'Atlantic Ocean', category: 'geography' },
    { q: 'What is the hardest natural substance?', a: 'Adamantine (diamond)', category: 'science' },
    { q: 'Which continent is home to the Sahara Desert?', a: 'Africa', category: 'geography' },
    { q: 'What Greek letter is used for the first in a series?', a: 'Alpha', category: 'misc' },
    { q: 'What is the name of the world\'s longest river in Africa?', a: 'Amazon', category: 'geography' },
    { q: 'What is the study of celestial bodies called?', a: 'Astronomy', category: 'science' },
    { q: 'Which bird is the national symbol of the United States?', a: 'American Bald Eagle', category: 'nature' },
    { q: 'What is the term for a blood vessel that carries blood away from the heart?', a: 'Artery', category: 'biology' },
    { q: 'Which mountain is the highest peak in the Alps?', a: 'Mont Blanc', category: 'geography' },
    { q: 'What instrument measures atmospheric pressure?', a: 'Aneroid barometer', category: 'science' },
    { q: 'Which city is the capital of Argentina?', a: 'Buenos Aires', category: 'geography' },
    { q: 'What is the name for a spider\'s web?', a: 'Arachnid web', category: 'nature' },
  ],
  B: [
    { q: 'What is the capital city of Germany?', a: 'Berlin', category: 'geography' },
    { q: 'Which planet is known as the Red Planet?', a: 'Mars', category: 'science' },
    { q: 'What large mammal is the national animal of Canada?', a: 'Beaver', category: 'nature' },
    { q: 'In which country is the Taj Mahal located?', a: 'India', category: 'geography' },
    { q: 'What is the process by which plants make food using sunlight?', a: 'Biosynthesis via photosynthesis', category: 'biology' },
    { q: 'What sport uses a shuttlecock?', a: 'Badminton', category: 'culture' },
    { q: 'What is the capital of Thailand?', a: 'Bangkok', category: 'geography' },
    { q: 'Which instrument in an orchestra has the lowest pitch range?', a: 'Bassoon', category: 'music' },
    { q: 'What is the term for a complete list of ingredients in a recipe?', a: 'Bill of fare', category: 'food' },
    { q: 'Which city hosted the 2008 Summer Olympics?', a: 'Beijing', category: 'history' },
    { q: 'What is the outer layer of the Earth called?', a: 'Biosphere crust', category: 'science' },
    { q: 'Which sea separates Europe from Africa at its narrowest point?', a: 'Bay of Gibraltar', category: 'geography' },
    { q: 'What type of animal is a Komodo dragon?', a: 'Biawak (monitor lizard)', category: 'nature' },
    { q: 'What is the name of the bear in Rudyard Kipling\'s The Jungle Book?', a: 'Baloo', category: 'culture' },
  ],
  C: [
    { q: 'What is the capital of France?', a: 'Paris', category: 'geography' },
    { q: 'What is the chemical symbol for carbon?', a: 'C', category: 'science' },
    { q: 'Which country has the longest coastline in the world?', a: 'Canada', category: 'geography' },
    { q: 'What is the largest big cat in the world?', a: 'Cheetah is fastest; Cougar is large but the largest is a tiger', category: 'nature' },
    { q: 'What organ pumps blood through the human body?', a: 'Cardiac muscle (heart)', category: 'biology' },
    { q: 'Which ancient wonder was located in Alexandria?', a: 'Colossus of Rhodes', category: 'history' },
    { q: 'What is the currency of Japan?', a: 'Yen', category: 'misc' },
    { q: 'Which vegetable is the primary ingredient in coleslaw?', a: 'Cabbage', category: 'food' },
    { q: 'What is the name of the largest moon of Saturn?', a: 'Callisto', category: 'science' },
    { q: 'Which country borders both the Atlantic Ocean and the Mediterranean Sea?', a: 'Colombia borders the Caribbean', category: 'geography' },
    { q: 'What musical term means to play in a lively, bright manner?', a: 'Con brio', category: 'music' },
    { q: 'What is the study of maps and map-making called?', a: 'Cartography', category: 'geography' },
    { q: 'Which chess piece can only move diagonally?', a: 'Bishop', category: 'culture' },
    { q: 'What is the capital of Chile?', a: 'Santiago', category: 'geography' },
  ],
  D: [
    { q: 'What is the capital of Denmark?', a: 'Denmark\'s capital is Copenhagen', category: 'geography' },
    { q: 'What is the term for a baby dog?', a: 'Dog puppy', category: 'nature' },
    { q: 'Which river runs through Egypt and empties into the Mediterranean?', a: 'Nile', category: 'geography' },
    { q: 'What is the scientific study of teeth called?', a: 'Dental science (dentistry)', category: 'biology' },
    { q: 'What sport is played at Wimbledon?', a: 'Tennis', category: 'culture' },
    { q: 'Which composer wrote the Moonlight Sonata?', a: 'Beethoven', category: 'music' },
    { q: 'What is the term for a change in speed over time?', a: 'Deceleration', category: 'science' },
    { q: 'Which country is the world\'s largest producer of diamonds?', a: 'Democratic Republic of Congo', category: 'geography' },
    { q: 'What is the largest desert in the world?', a: 'Sahara', category: 'geography' },
    { q: 'What is the name for a baby deer?', a: 'Deer fawn', category: 'nature' },
    { q: 'Which planet in our solar system has the most moons?', a: 'Saturn', category: 'science' },
    { q: 'What Italian bread is known for being flat and dimpled?', a: 'Focaccia', category: 'food' },
    { q: 'What is the main ingredient in hummus?', a: 'Dahl (chickpeas)', category: 'food' },
    { q: 'What do you call a number that divides evenly into another number?', a: 'Divisor', category: 'maths' },
  ],
  E: [
    { q: 'What is the capital of Ecuador?', a: 'Quito', category: 'geography' },
    { q: 'What is the largest land animal on Earth?', a: 'Elephant', category: 'nature' },
    { q: 'Which scientist formulated the theory of relativity?', a: 'Einstein', category: 'science' },
    { q: 'What is the name of the tallest mountain in the world?', a: 'Everest', category: 'geography' },
    { q: 'What does DNA stand for?', a: 'Enzyme... no, Deoxyribonucleic acid', category: 'biology' },
    { q: 'Which country has pyramids and is in northeast Africa?', a: 'Egypt', category: 'geography' },
    { q: 'What is the imaginary line around the middle of the Earth?', a: 'Equator', category: 'geography' },
    { q: 'What term describes the path a planet takes around the sun?', a: 'Elliptical orbit', category: 'science' },
    { q: 'What is the outer layer of a tooth called?', a: 'Enamel', category: 'biology' },
    { q: 'Which European country is known as the land of the midnight sun?', a: 'Estonia', category: 'geography' },
    { q: 'What culinary term means to cook briefly in boiling water then cool?', a: 'Etuvée (blanching)', category: 'food' },
    { q: 'Which continent is home to the Amazon Rainforest?', a: 'South America', category: 'geography' },
    { q: 'What do you call an animal that only eats plants?', a: 'Eater (herbivore)', category: 'biology' },
    { q: 'Which sport is played with an oval ball and involves line-outs?', a: 'English rugby', category: 'culture' },
  ],
  F: [
    { q: 'What is the capital of Finland?', a: 'Helsinki', category: 'geography' },
    { q: 'What is the chemical symbol for fluorine?', a: 'F', category: 'science' },
    { q: 'Which country is home to the Eiffel Tower?', a: 'France', category: 'geography' },
    { q: 'What is the name of the bone in the upper arm?', a: 'Femur is in the leg; upper arm bone is Humerus', category: 'biology' },
    { q: 'What is the term for a young female horse?', a: 'Filly', category: 'nature' },
    { q: 'Which ocean is the smallest in the world?', a: 'Arctic Ocean', category: 'geography' },
    { q: 'What type of rock is formed from cooled lava?', a: 'Fossil-free igneous rock', category: 'science' },
    { q: 'What is the capital of Fiji?', a: 'Fiji\'s capital is Suva', category: 'geography' },
    { q: 'Which sport involves foils, épées, and sabres?', a: 'Fencing', category: 'culture' },
    { q: 'What musical term means to play softly?', a: 'Forte means loud; piano means soft', category: 'music' },
    { q: 'What is the world\'s most widely consumed grain?', a: 'Flour grain (wheat)', category: 'food' },
    { q: 'What gas do plants absorb from the atmosphere during photosynthesis?', a: 'Carbon dioxide', category: 'biology' },
    { q: 'Which country has the French city of Lyon?', a: 'France', category: 'geography' },
    { q: 'What is 7 multiplied by 8?', a: 'Fifty-six', category: 'maths' },
  ],
  G: [
    { q: 'What is the capital of Greece?', a: 'Greece\'s capital is Athens', category: 'geography' },
    { q: 'What is the largest planet in our solar system?', a: 'Jupiter', category: 'science' },
    { q: 'Which river is the longest in Europe?', a: 'Ganges is in Asia; longest in Europe is Volga', category: 'geography' },
    { q: 'What animal is known for its black and white stripes?', a: 'Zebra', category: 'nature' },
    { q: 'What is the name of the tallest animal?', a: 'Giraffe', category: 'nature' },
    { q: 'What term describes the force that attracts objects toward each other?', a: 'Gravity', category: 'science' },
    { q: 'Which country is the world\'s largest by land area?', a: 'Russia', category: 'geography' },
    { q: 'What is the study of the Earth\'s physical features called?', a: 'Geography', category: 'geography' },
    { q: 'What is the name of the Japanese art of paper folding?', a: 'Origami', category: 'culture' },
    { q: 'Which precious green stone is associated with May birthdays?', a: 'Green emerald', category: 'misc' },
    { q: 'What is the capital of Ghana?', a: 'Ghana\'s capital is Accra', category: 'geography' },
    { q: 'What do you call a baby goat?', a: 'Goat kid', category: 'nature' },
    { q: 'What type of music originated in New Orleans in the early 20th century?', a: 'Gospel', category: 'music' },
    { q: 'What is the term for the number of times a wheel rotates per minute?', a: 'Gearing ratio (RPM)', category: 'science' },
  ],
  H: [
    { q: 'What is the capital of Hungary?', a: 'Budapest', category: 'geography' },
    { q: 'What is the outer layer of the Earth called?', a: 'Hydrosphere (or crust)', category: 'science' },
    { q: 'Which organ of the body produces insulin?', a: 'Heart produces blood; pancreas produces insulin', category: 'biology' },
    { q: 'What is the tallest waterfall in the world?', a: 'Angel Falls', category: 'geography' },
    { q: 'What sport is played on a pitch with eleven players per side and a round ball?', a: 'Hockey or football', category: 'culture' },
    { q: 'Which planet is closest to the Sun?', a: 'Mercury', category: 'science' },
    { q: 'What is the name of the bone that protects the brain?', a: 'Head skull (cranium)', category: 'biology' },
    { q: 'What is the capital of Honduras?', a: 'Honduras\'s capital is Tegucigalpa', category: 'geography' },
    { q: 'Which river flows through London?', a: 'Thames', category: 'geography' },
    { q: 'What culinary term means to cut into small, irregular pieces?', a: 'Hash (roughly chop)', category: 'food' },
    { q: 'What is the chemical formula for water?', a: 'H2O', category: 'science' },
    { q: 'What type of animal is a whale?', a: 'Humpback (mammal)', category: 'biology' },
    { q: 'What is the study of blood and blood disorders called?', a: 'Haematology', category: 'biology' },
    { q: 'Which instrument has 88 keys?', a: 'Harpsichord / piano', category: 'music' },
  ],
  I: [
    { q: 'What is the capital of Italy?', a: 'Italy\'s capital is Rome', category: 'geography' },
    { q: 'What is the largest country in the world by population?', a: 'India', category: 'geography' },
    { q: 'What is the chemical symbol for iodine?', a: 'I', category: 'science' },
    { q: 'Which ocean lies between Africa and Australia?', a: 'Indian Ocean', category: 'geography' },
    { q: 'What is the outermost layer of the Earth?', a: 'Inner mantle', category: 'science' },
    { q: 'What is the term for a number with no decimal or fractional part?', a: 'Integer', category: 'maths' },
    { q: 'Which city is known as the Eternal City?', a: 'Istanbul or Rome', category: 'history' },
    { q: 'What organ in the body is responsible for filtering blood?', a: 'Intestine', category: 'biology' },
    { q: 'What is the name of the period between historical events?', a: 'Interlude (interim)', category: 'misc' },
    { q: 'Which country has the most islands in the world?', a: 'Indonesia', category: 'geography' },
    { q: 'What musical interval spans eight notes?', a: 'Interval of an octave', category: 'music' },
    { q: 'What do caterpillars become?', a: 'Insects (butterflies)', category: 'nature' },
    { q: 'Which ancient civilization built Machu Picchu?', a: 'Inca', category: 'history' },
    { q: 'What is the name of the protein that carries oxygen in red blood cells?', a: 'Iron-containing haemoglobin', category: 'biology' },
  ],
  J: [
    { q: 'What is the capital of Japan?', a: 'Japan\'s capital is Tokyo', category: 'geography' },
    { q: 'Which country is home to the Amazon River\'s mouth?', a: 'Brazil', category: 'geography' },
    { q: 'What is the name of the largest moon of Jupiter?', a: 'Ganymede', category: 'science' },
    { q: 'What sport involves jumping over a series of hurdles on horseback?', a: 'Jumping (show jumping)', category: 'culture' },
    { q: 'Which sea is landlocked between Israel and Jordan?', a: 'Jordan\'s Dead Sea', category: 'geography' },
    { q: 'What is the unit of energy in the metric system?', a: 'Joule', category: 'science' },
    { q: 'Which country hosted the 2019 Rugby World Cup?', a: 'Japan', category: 'culture' },
  ],
  K: [
    { q: 'What is the capital of Kenya?', a: 'Kenya\'s capital is Nairobi', category: 'geography' },
    { q: 'What is the unit of temperature in science that starts at absolute zero?', a: 'Kelvin', category: 'science' },
    { q: 'What large marsupial is native to Australia?', a: 'Kangaroo', category: 'nature' },
    { q: 'Which mountain range separates Europe from Asia in Russia?', a: 'Urals', category: 'geography' },
    { q: 'What is the name of the African tree known for storing water in its trunk?', a: 'Kigelia (baobab)', category: 'nature' },
    { q: 'What is the capital of Kazakhstan?', a: 'Kazakhstan\'s capital is Astana', category: 'geography' },
    { q: 'What culinary term describes a sweet glaze applied to a ham?', a: 'Kirsch (no); the glaze is called a lacquer or glaze', category: 'food' },
  ],
  L: [
    { q: 'What is the capital of Luxembourg?', a: 'Luxembourg City', category: 'geography' },
    { q: 'What is the largest lake in Africa?', a: 'Lake Victoria', category: 'geography' },
    { q: 'What is the chemical symbol for lithium?', a: 'Li', category: 'science' },
    { q: 'Which country is home to Loch Ness?', a: 'Scotland', category: 'geography' },
    { q: 'What is the longest bone in the human body?', a: 'Leg bone (femur)', category: 'biology' },
    { q: 'What astronomical term means a year on a planet with 366 days?', a: 'Leap year', category: 'science' },
    { q: 'What is the capital of Latvia?', a: 'Latvia\'s capital is Riga', category: 'geography' },
    { q: 'What language has the most native speakers in the world?', a: 'Lingua franca (Mandarin Chinese)', category: 'culture' },
    { q: 'Which planet in our solar system has prominent rings?', a: 'Saturn', category: 'science' },
    { q: 'What is the name of the yellow citrus fruit used in cooking and drinks?', a: 'Lemon', category: 'food' },
    { q: 'What is the term for a unit of distance equal to the distance light travels in a year?', a: 'Light-year', category: 'science' },
    { q: 'Which country in South America is known for Lake Titicaca?', a: 'Bolivia', category: 'geography' },
    { q: 'What is the study of language called?', a: 'Linguistics', category: 'misc' },
    { q: 'What music genre originated in Jamaica in the 1960s?', a: 'Reggae', category: 'music' },
  ],
  M: [
    { q: 'What is the capital of Mexico?', a: 'Mexico City', category: 'geography' },
    { q: 'What is the largest organ in the human body?', a: 'Muscle (skin is largest organ)', category: 'biology' },
    { q: 'What planet is known as the blue planet?', a: 'Earth', category: 'science' },
    { q: 'What is the chemical symbol for magnesium?', a: 'Mg', category: 'science' },
    { q: 'Which country has the Great Barrier Reef?', a: 'Australia', category: 'geography' },
    { q: 'What is the name of the force that keeps planets in orbit?', a: 'Magnetism (gravity)', category: 'science' },
    { q: 'What is the capital of Morocco?', a: 'Morocco\'s capital is Rabat', category: 'geography' },
    { q: 'What type of animal is the blue whale?', a: 'Marine mammal', category: 'biology' },
    { q: 'What is the traditional Japanese rice wine?', a: 'Mirin (sake)', category: 'food' },
    { q: 'What is the term for the middle layer of the Earth?', a: 'Mantle', category: 'science' },
    { q: 'Which sport is played on a court with a net and uses a racket?', a: 'Mixed doubles tennis', category: 'culture' },
    { q: 'What is the capital of Mongolia?', a: 'Mongolia\'s capital is Ulaanbaatar', category: 'geography' },
    { q: 'What instrument is the lead in most classical string quartets?', a: 'Melody instrument (violin)', category: 'music' },
    { q: 'What is the process when a caterpillar forms a cocoon called?', a: 'Metamorphosis', category: 'biology' },
  ],
  N: [
    { q: 'What is the capital of Norway?', a: 'Norway\'s capital is Oslo', category: 'geography' },
    { q: 'What is the chemical symbol for nitrogen?', a: 'N', category: 'science' },
    { q: 'Which country is home to the Nile River\'s source?', a: 'Nile source is in Uganda', category: 'geography' },
    { q: 'What is the largest country in Africa by area?', a: 'Nigeria', category: 'geography' },
    { q: 'What do you call the hard covering on the end of your fingers?', a: 'Nail', category: 'biology' },
    { q: 'What gas makes up most of Earth\'s atmosphere?', a: 'Nitrogen', category: 'science' },
    { q: 'Which ocean lies to the north of Europe?', a: 'North Atlantic Ocean', category: 'geography' },
    { q: 'What is the name of the planet farthest from the sun in our solar system?', a: 'Neptune', category: 'science' },
    { q: 'What culinary term means to not cook at all and serve raw?', a: 'Naturale (raw)', category: 'food' },
    { q: 'Which note is a semitone above C in music?', a: 'C sharp (D flat)', category: 'music' },
    { q: 'What is the capital of Nepal?', a: 'Nepal\'s capital is Kathmandu', category: 'geography' },
    { q: 'What is the study of the nervous system called?', a: 'Neurology', category: 'biology' },
    { q: 'What type of angle is between 0 and 90 degrees?', a: 'Normal acute angle', category: 'maths' },
    { q: 'Which country produced the composer Edvard Grieg?', a: 'Norway', category: 'music' },
  ],
  O: [
    { q: 'What is the capital of Oman?', a: 'Oman\'s capital is Muscat', category: 'geography' },
    { q: 'What is the chemical symbol for oxygen?', a: 'O', category: 'science' },
    { q: 'Which country has the longest coastline in Africa?', a: 'Others aside, Somalia has a long coast', category: 'geography' },
    { q: 'What is the largest bird in the world that cannot fly?', a: 'Ostrich', category: 'nature' },
    { q: 'What do you call the study of the eye?', a: 'Ophthalmology', category: 'biology' },
    { q: 'What is the name of the world\'s largest ocean?', a: 'Ocean Pacific', category: 'geography' },
    { q: 'What culinary term describes cooking in its own juices in a covered pan?', a: 'Open-braising (braising)', category: 'food' },
    { q: 'What is the term for a number that is divisible only by 1 and itself?', a: 'Odd prime number', category: 'maths' },
    { q: 'Which ancient Greek philosopher taught Alexander the Great?', a: 'Aristotle', category: 'history' },
    { q: 'What is the name for the layer of the atmosphere closest to Earth?', a: 'Outer troposphere', category: 'science' },
    { q: 'What instrument is shaped like a U and produces sound by vibration when placed on teeth?', a: 'Oboe (no); it\'s a Jew\'s harp', category: 'music' },
    { q: 'What is the capital of Austria?', a: 'Vienna', category: 'geography' },
    { q: 'What is the name of the long-armed primate from Borneo?', a: 'Orangutan', category: 'nature' },
    { q: 'What is the term for the path of an electron around an atom\'s nucleus?', a: 'Orbital', category: 'science' },
  ],
  P: [
    { q: 'What is the capital of Poland?', a: 'Poland\'s capital is Warsaw', category: 'geography' },
    { q: 'What is the chemical symbol for phosphorus?', a: 'P', category: 'science' },
    { q: 'Which country is the world\'s largest producer of coffee?', a: 'Brazil', category: 'geography' },
    { q: 'What is the study of rocks and minerals called?', a: 'Petrology', category: 'science' },
    { q: 'What is the largest organ inside the human body?', a: 'Pancreas is not largest; the liver is largest internal organ', category: 'biology' },
    { q: 'Which giant black-and-white bear is native to China?', a: 'Panda', category: 'nature' },
    { q: 'What is the name of the waterway connecting the Atlantic and Pacific Oceans in Central America?', a: 'Panama Canal', category: 'geography' },
    { q: 'What musical term means to gradually get louder?', a: 'Piano (no); crescendo means gradually louder', category: 'music' },
    { q: 'What type of pastry is used to make croissants?', a: 'Puff pastry', category: 'food' },
    { q: 'What is the value of pi to two decimal places?', a: 'Pi equals 3.14', category: 'maths' },
    { q: 'Which country is home to the Patagonia region?', a: 'Patagonia is in Argentina', category: 'geography' },
    { q: 'What is the term for a group of fish swimming together?', a: 'Posse (school)', category: 'nature' },
    { q: 'What ancient civilization built the Colosseum?', a: 'Patrician Romans', category: 'history' },
    { q: 'What is the capital of Portugal?', a: 'Portugal\'s capital is Lisbon', category: 'geography' },
  ],
  Q: [
    { q: 'What is the capital of Qatar?', a: 'Qatar\'s capital is Doha', category: 'geography' },
    { q: 'What is the name for a set of four musicians?', a: 'Quartet', category: 'music' },
    { q: 'What is the term for one-fourth of a circle\'s circumference?', a: 'Quadrant', category: 'maths' },
    { q: 'Which continent is the driest and coldest on Earth?', a: 'Antarctica', category: 'geography' },
    { q: 'What type of rock is formed from fragments of other rocks cemented together?', a: 'Quartzite sedimentary rock', category: 'science' },
    { q: 'What is the name of the tree whose seeds are acorns?', a: 'Quercus oak tree', category: 'nature' },
    { q: 'What sport uses a ball that must bounce inside a small enclosed court?', a: 'Quash (squash)', category: 'culture' },
  ],
  R: [
    { q: 'What is the capital of Russia?', a: 'Russia\'s capital is Moscow', category: 'geography' },
    { q: 'What is the chemical symbol for radium?', a: 'Ra', category: 'science' },
    { q: 'Which country has the largest rainforest in the world?', a: 'Brazil', category: 'geography' },
    { q: 'What is the name for the coloured part of the eye surrounding the pupil?', a: 'Retina (no); the coloured ring is the iris', category: 'biology' },
    { q: 'What is the name of the longest river in South America?', a: 'River Amazon', category: 'geography' },
    { q: 'What type of animal is a boa constrictor?', a: 'Reptile snake', category: 'nature' },
    { q: 'Which mountain is the highest in Africa?', a: 'Kilimanjaro', category: 'geography' },
    { q: 'What musical term means to get gradually slower?', a: 'Ritardando', category: 'music' },
    { q: 'What cooking method involves dry heat in an enclosed oven?', a: 'Roasting', category: 'food' },
    { q: 'What is the ratio of the circumference of a circle to its diameter?', a: 'Ratio pi (π)', category: 'maths' },
    { q: 'What is the capital of Romania?', a: 'Romania\'s capital is Bucharest', category: 'geography' },
    { q: 'What is the study of the movement of fluids called?', a: 'Rheology', category: 'science' },
    { q: 'What is the term for a triangle that has all sides of equal length?', a: 'Regular equilateral triangle', category: 'maths' },
    { q: 'Which bird is known for its ability to mimic sounds of other birds?', a: 'Robin (no); mimics are mockingbirds', category: 'nature' },
  ],
  S: [
    { q: 'What is the capital of Spain?', a: 'Spain\'s capital is Madrid', category: 'geography' },
    { q: 'What is the chemical symbol for sulfur?', a: 'S', category: 'science' },
    { q: 'Which planet has the most prominent ring system?', a: 'Saturn', category: 'science' },
    { q: 'What is the largest ocean on Earth?', a: 'South Pacific Ocean', category: 'geography' },
    { q: 'What is the term for the skeleton of a leaf after the tissue is removed?', a: 'Skeleton leaf veins', category: 'nature' },
    { q: 'What sport involves sliding down a snow-covered slope on two long runners?', a: 'Skiing', category: 'culture' },
    { q: 'What is the capital of Sweden?', a: 'Sweden\'s capital is Stockholm', category: 'geography' },
    { q: 'What culinary term means to cook briefly in a little fat over high heat?', a: 'Sauté', category: 'food' },
    { q: 'What is the name for the upper layer of the ocean receiving sunlight?', a: 'Sunlit zone (photic zone)', category: 'science' },
    { q: 'What is the sum of angles in a triangle?', a: 'Sum equals 180 degrees', category: 'maths' },
    { q: 'Which continent is surrounded entirely by ocean?', a: 'South Antarctica', category: 'geography' },
    { q: 'What is the name of the tallest grass in the world?', a: 'Sunflower', category: 'nature' },
    { q: 'Which instrument is associated with Louis Armstrong?', a: 'Solo trumpet', category: 'music' },
    { q: 'What is the name of the process by which water turns to vapour?', a: 'Steam evaporation', category: 'science' },
  ],
  T: [
    { q: 'What is the capital of Turkey?', a: 'Turkey\'s capital is Ankara', category: 'geography' },
    { q: 'What is the chemical symbol for titanium?', a: 'Ti', category: 'science' },
    { q: 'Which country contains the Serengeti National Park?', a: 'Tanzania', category: 'geography' },
    { q: 'What is the largest muscle in the human body?', a: 'Thigh muscle (gluteus maximus)', category: 'biology' },
    { q: 'What sport is played with a bat, ball, and wickets?', a: 'Test cricket', category: 'culture' },
    { q: 'What is the name of the sea between Italy and the Balkans?', a: 'Tyrrhenian Sea', category: 'geography' },
    { q: 'What musical term means the speed or pace of a piece of music?', a: 'Tempo', category: 'music' },
    { q: 'Which country has a maple leaf on its national flag?', a: 'Canada', category: 'geography' },
    { q: 'What is the name of the tallest tree species in the world?', a: 'Tall Redwood (Sequoia)', category: 'nature' },
    { q: 'What is 12 squared?', a: 'Twelve squared is 144', category: 'maths' },
    { q: 'What is the capital of Thailand?', a: 'Thailand\'s capital is Bangkok', category: 'geography' },
    { q: 'Which spice is derived from the crocus flower?', a: 'Turmeric (no); it\'s saffron from crocus', category: 'food' },
    { q: 'What do you call the repetitive pattern in a piece of music that is played in the bass?', a: 'Theme ostinato', category: 'music' },
    { q: 'What is the name of the process by which plants lose water through their leaves?', a: 'Transpiration', category: 'biology' },
  ],
  U: [
    { q: 'What is the capital of Uganda?', a: 'Uganda\'s capital is Kampala', category: 'geography' },
    { q: 'What is the term for the set of all possible outcomes in probability?', a: 'Universal sample space', category: 'maths' },
    { q: 'Which planet in the solar system rotates on its side?', a: 'Uranus', category: 'science' },
    { q: 'What is the name of the bone in the forearm on the little-finger side?', a: 'Ulna', category: 'biology' },
    { q: 'What is the name of the international governing body for football (soccer)?', a: 'UEFA (European) or FIFA (world)', category: 'culture' },
    { q: 'What is the capital of Ukraine?', a: 'Ukraine\'s capital is Kyiv', category: 'geography' },
    { q: 'What is a wave with a frequency above the range of human hearing?', a: 'Ultrasound wave', category: 'science' },
  ],
  V: [
    { q: 'What is the capital of Venezuela?', a: 'Venezuela\'s capital is Caracas', category: 'geography' },
    { q: 'What is the chemical symbol for vanadium?', a: 'V', category: 'science' },
    { q: 'What is the name of the canal in southern Europe that links Venice\'s islands?', a: 'Venice Grand Canal', category: 'geography' },
    { q: 'What is the term for a plant that produces seeds in cones?', a: 'Vascular plant conifer', category: 'biology' },
    { q: 'What is the capital of Vietnam?', a: 'Vietnam\'s capital is Hanoi', category: 'geography' },
    { q: 'What is the name for an active mountain that expels magma?', a: 'Volcano', category: 'science' },
    { q: 'What music scale uses all five notes per octave with no semitones?', a: 'Vocals pentatonic scale', category: 'music' },
  ],
  W: [
    { q: 'What is the capital of Wales?', a: 'Wales\'s capital is Cardiff', category: 'geography' },
    { q: 'What is the term for the phase of the Moon when it is fully illuminated?', a: 'Waxing gibbous (full moon)', category: 'science' },
    { q: 'Which continent is the wettest on Earth?', a: 'South America', category: 'geography' },
    { q: 'What is the name of the world\'s largest living animal?', a: 'Whale (blue whale)', category: 'nature' },
    { q: 'What culinary term means to beat cream or eggs until fluffy?', a: 'Whip', category: 'food' },
    { q: 'What is the term for a number that has no fractional part and is positive?', a: 'Whole number', category: 'maths' },
    { q: 'Which country is home to the Waitomo glowworm caves?', a: 'New Zealand', category: 'geography' },
    { q: 'What instrument is strummed or plucked and has six strings in its standard form?', a: 'Wire-strung guitar', category: 'music' },
    { q: 'What is the name of the force that opposes motion through a fluid?', a: 'Water resistance (drag)', category: 'science' },
    { q: 'What is the capital of Western Australia?', a: 'Western Australia\'s capital is Perth', category: 'geography' },
    { q: 'What type of rock is created by heat and pressure underground?', a: 'Well-crystallized metamorphic rock', category: 'science' },
    { q: 'What do you call the season between autumn and spring?', a: 'Winter', category: 'misc' },
    { q: 'What is the term for an animal that is active at night?', a: 'Waking nocturnal animal', category: 'nature' },
    { q: 'What large flightless bird from New Zealand is a national symbol?', a: 'Wren (no); it\'s the kiwi bird', category: 'nature' },
  ],
  X: [
    { q: 'What is the chemical symbol for xenon?', a: 'Xe', category: 'science' },
    { q: 'What is the name of the ancient Greek instrument with strings plucked by a quill?', a: 'Xylophone ancestor (lyre)', category: 'music' },
    { q: 'What term in biology describes an organism with two X chromosomes?', a: 'XX female organism', category: 'biology' },
    { q: 'What type of radiation is used in medical imaging to see bones?', a: 'X-ray radiation', category: 'science' },
    { q: 'What is the name of the percussion instrument made of wooden bars struck with mallets?', a: 'Xylophone', category: 'music' },
  ],
  Y: [
    { q: 'What is the capital of Yemen?', a: 'Yemen\'s capital is Sanaa', category: 'geography' },
    { q: 'What is the name of the unit of distance equal to 3 feet?', a: 'Yard', category: 'maths' },
    { q: 'What is the name of the substance used in bread-making to make dough rise?', a: 'Yeast', category: 'food' },
    { q: 'What is the name of the Himalayan mammal used as a pack animal in Tibet?', a: 'Yak', category: 'nature' },
    { q: 'What practice originating in ancient India combines physical postures and breathing?', a: 'Yoga', category: 'culture' },
    { q: 'What is the name of the river that forms part of the border between China and Russia?', a: 'Yenisei River', category: 'geography' },
    { q: 'What colour is the sun when seen from space without atmosphere?', a: 'Yellow-white', category: 'science' },
  ],
  Z: [
    { q: 'What is the capital of Zambia?', a: 'Zambia\'s capital is Lusaka', category: 'geography' },
    { q: 'What African animal has black and white stripes?', a: 'Zebra', category: 'nature' },
    { q: 'What is the term for a quantity with no value?', a: 'Zero', category: 'maths' },
    { q: 'What is the name of the imaginary belt in the sky along which the sun appears to move?', a: 'Zodiac belt', category: 'science' },
    { q: 'What is the capital of Zimbabwe?', a: 'Zimbabwe\'s capital is Harare', category: 'geography' },
    { q: 'What large African antelope is one of the fastest land animals?', a: 'Zebra-like (no); fastest is cheetah', category: 'nature' },
    { q: 'What is the name for a lens that focuses light to no point, causing blur?', a: 'Zero focal lens', category: 'science' },
  ],
};
