import type { RawQuestion } from '../core/packs';

export const extraGeneralKnowledge3: Record<string, RawQuestion[]> = {
  A: [
    { q: 'What is the capital city of Australia?', a: 'Canberra', category: 'geography' },
    { q: 'What element has the chemical symbol Au?', a: 'Gold', category: 'science' },
    { q: 'Which ocean is the largest on Earth?', a: 'Atlantic Ocean', category: 'geography' },
    { q: 'The hardest natural mineral, a prized gemstone — what is it?', a: 'Diamond', category: 'science' },
    { q: 'Which continent is home to the Sahara Desert?', a: 'Africa', category: 'geography' },
    { q: 'What Greek letter is used for the first in a series?', a: 'Alpha', category: 'misc' },
    { q: 'Which river runs through the Amazon rainforest and is the largest by water volume?', a: 'Amazon', category: 'geography' },
    { q: 'What is the study of celestial bodies called?', a: 'Astronomy', category: 'science' },
    { q: 'Which bird is the national symbol of the United States?', a: 'American Bald Eagle', category: 'nature' },
    { q: 'What is the term for a blood vessel that carries blood away from the heart?', a: 'Artery', category: 'biology' },
    { q: 'Which mountain is the highest peak in the Alps?', a: 'Mont Blanc', category: 'geography' },
    { q: 'What instrument measures atmospheric pressure?', a: 'Aneroid barometer', category: 'science' },
    { q: 'What is the capital of Argentina?', a: 'Buenos Aires', category: 'geography' },
    { q: 'What is the silken structure a spider builds to catch prey?', a: 'Arachnid web', category: 'nature' },
  ],
  B: [
    { q: 'What is the capital city of Germany?', a: 'Berlin', category: 'geography' },
    { q: 'Which planet is known as the Red Planet?', a: 'Mars', category: 'science' },
    { q: 'What large mammal is the national animal of Canada?', a: 'Beaver', category: 'nature' },
    { q: 'In which country is the Taj Mahal located?', a: 'India', category: 'geography' },
    { q: 'What is the process by which plants make food using sunlight?', a: 'Biosynthesis', category: 'biology' },
    { q: 'What sport uses a shuttlecock?', a: 'Badminton', category: 'culture' },
    { q: 'What is the capital of Thailand?', a: 'Bangkok', category: 'geography' },
    { q: 'Which instrument in an orchestra has the lowest pitch among the woodwinds?', a: 'Bassoon', category: 'music' },
    { q: 'What is a restaurant\'s printed list of available dishes called?', a: 'Bill of fare', category: 'food' },
    { q: 'Which city hosted the 2008 Summer Olympics?', a: 'Beijing', category: 'history' },
    { q: 'What is the solid outer shell of the Earth called?', a: 'Bedrock crust', category: 'science' },
    { q: 'What narrow waterway separates Europe and Africa at the western Mediterranean?', a: 'Bosphorus', category: 'geography' },
    { q: 'What type of animal is a Komodo dragon?', a: 'Lizard', category: 'nature' },
    { q: 'What is the name of the bear in Rudyard Kipling\'s The Jungle Book?', a: 'Baloo', category: 'culture' },
  ],
  C: [
    { q: 'What is the capital of France?', a: 'Paris', category: 'geography' },
    { q: 'What is the chemical symbol for carbon?', a: 'C', category: 'science' },
    { q: 'Which country has the longest coastline in the world?', a: 'Canada', category: 'geography' },
    { q: 'The largest of all the big cat species, with orange and black stripes — what is it?', a: 'Tiger', category: 'nature' },
    { q: 'The muscular organ that pumps blood around the body — what is it?', a: 'Heart', category: 'biology' },
    { q: 'Which ancient wonder stood at the entrance to the harbour of Rhodes?', a: 'Colossus of Rhodes', category: 'history' },
    { q: 'What is the currency of Japan?', a: 'Yen', category: 'misc' },
    { q: 'Which vegetable is the primary ingredient in coleslaw?', a: 'Cabbage', category: 'food' },
    { q: 'What is the name of the largest moon of Saturn?', a: 'Callisto', category: 'science' },
    { q: 'Which European country borders both the Atlantic Ocean and the Mediterranean Sea?', a: 'Spain', category: 'geography' },
    { q: 'What musical term means to play in a lively, bright manner?', a: 'Con brio', category: 'music' },
    { q: 'What is the study of maps and map-making called?', a: 'Cartography', category: 'geography' },
    { q: 'Which chess piece can only move diagonally?', a: 'Bishop', category: 'culture' },
    { q: 'What is the capital of Chile?', a: 'Santiago', category: 'geography' },
  ],
  D: [
    { q: 'What is the capital of Denmark?', a: 'Copenhagen', category: 'geography' },
    { q: 'What is the name for a young dog?', a: 'Puppy', category: 'nature' },
    { q: 'Which river runs through Egypt and empties into the Mediterranean?', a: 'Nile', category: 'geography' },
    { q: 'The branch of medicine focused on the teeth and gums — what is it called?', a: 'Dentistry', category: 'biology' },
    { q: 'What sport is played at Wimbledon?', a: 'Tennis', category: 'culture' },
    { q: 'Which composer wrote the Moonlight Sonata?', a: 'Beethoven', category: 'music' },
    { q: 'What is the term for a decrease in speed over time?', a: 'Deceleration', category: 'science' },
    { q: 'Which country is the world\'s largest producer of diamonds?', a: 'Democratic Republic of Congo', category: 'geography' },
    { q: 'What is the largest desert in the world?', a: 'Sahara', category: 'geography' },
    { q: 'What is the name for a baby deer?', a: 'Fawn', category: 'nature' },
    { q: 'Which planet in our solar system has the most moons?', a: 'Saturn', category: 'science' },
    { q: 'What Italian bread is known for being flat and dimpled?', a: 'Focaccia', category: 'food' },
    { q: 'What legume is the main ingredient in hummus?', a: 'Chickpeas', category: 'food' },
    { q: 'What do you call a number that divides evenly into another number?', a: 'Divisor', category: 'maths' },
  ],
  E: [
    { q: 'What is the capital of Ecuador?', a: 'Quito', category: 'geography' },
    { q: 'What is the largest land animal on Earth?', a: 'Elephant', category: 'nature' },
    { q: 'Which scientist formulated the theory of relativity?', a: 'Einstein', category: 'science' },
    { q: 'What is the name of the tallest mountain in the world?', a: 'Everest', category: 'geography' },
    { q: 'What does the D in DNA stand for?', a: 'Deoxyribonucleic acid', category: 'biology' },
    { q: 'Which country has pyramids and is in northeast Africa?', a: 'Egypt', category: 'geography' },
    { q: 'What is the imaginary line around the middle of the Earth?', a: 'Equator', category: 'geography' },
    { q: 'What term describes the path a planet takes around the sun?', a: 'Elliptical orbit', category: 'science' },
    { q: 'What is the outer layer of a tooth called?', a: 'Enamel', category: 'biology' },
    { q: 'Which European country is known as the land of the midnight sun?', a: 'Estonia', category: 'geography' },
    { q: 'What culinary technique involves briefly plunging food into boiling water then into ice water?', a: 'Blanching', category: 'food' },
    { q: 'Which continent is home to the Amazon Rainforest?', a: 'South America', category: 'geography' },
    { q: 'What do you call an animal that only eats plants?', a: 'Herbivore', category: 'biology' },
    { q: 'Which sport is played with an oval ball and involves line-outs?', a: 'Rugby', category: 'culture' },
  ],
  F: [
    { q: 'What is the capital of Finland?', a: 'Helsinki', category: 'geography' },
    { q: 'What is the chemical symbol for fluorine?', a: 'F', category: 'science' },
    { q: 'Which country is home to the Eiffel Tower?', a: 'France', category: 'geography' },
    { q: 'What is the bone of the upper arm called?', a: 'Humerus', category: 'biology' },
    { q: 'What is the term for a young female horse?', a: 'Filly', category: 'nature' },
    { q: 'Which ocean is the smallest in the world?', a: 'Arctic Ocean', category: 'geography' },
    { q: 'What type of rock is formed when magma or lava cools and solidifies?', a: 'Igneous rock', category: 'science' },
    { q: 'What is the capital of Fiji?', a: 'Suva', category: 'geography' },
    { q: 'Which sport involves foils, épées, and sabres?', a: 'Fencing', category: 'culture' },
    { q: 'What musical term means to play softly?', a: 'Piano', category: 'music' },
    { q: 'Which grain is ground into flour to make most breads?', a: 'Wheat', category: 'food' },
    { q: 'What gas do plants absorb from the atmosphere during photosynthesis?', a: 'Carbon dioxide', category: 'biology' },
    { q: 'Which country has the French city of Lyon?', a: 'France', category: 'geography' },
    { q: 'What is 7 multiplied by 8?', a: 'Fifty-six', category: 'maths' },
  ],
  G: [
    { q: 'What is the capital of Greece?', a: 'Athens', category: 'geography' },
    { q: 'What is the largest planet in our solar system?', a: 'Jupiter', category: 'science' },
    { q: 'Which river is the longest in Europe?', a: 'Volga', category: 'geography' },
    { q: 'What animal is known for its black and white stripes?', a: 'Zebra', category: 'nature' },
    { q: 'What is the name of the tallest animal?', a: 'Giraffe', category: 'nature' },
    { q: 'What term describes the force that attracts objects toward each other?', a: 'Gravity', category: 'science' },
    { q: 'Which country is the world\'s largest by land area?', a: 'Russia', category: 'geography' },
    { q: 'What is the study of the Earth\'s physical features called?', a: 'Geography', category: 'geography' },
    { q: 'What is the name of the Japanese art of paper folding?', a: 'Origami', category: 'culture' },
    { q: 'Which precious green gemstone is associated with May birthdays?', a: 'Emerald', category: 'misc' },
    { q: 'What is the capital of Ghana?', a: 'Accra', category: 'geography' },
    { q: 'What do you call a baby goat?', a: 'Kid', category: 'nature' },
    { q: 'What type of music originated in New Orleans in the early 20th century?', a: 'Jazz', category: 'music' },
    { q: 'What is the term for the number of rotations a wheel makes per minute?', a: 'RPM', category: 'science' },
  ],
  H: [
    { q: 'What is the capital of Hungary?', a: 'Budapest', category: 'geography' },
    { q: 'What is the rigid outermost layer of the Earth called?', a: 'Crust', category: 'science' },
    { q: 'Which organ in the body produces insulin?', a: 'Pancreas', category: 'biology' },
    { q: 'What is the tallest waterfall in the world?', a: 'Angel Falls', category: 'geography' },
    { q: 'What sport is played on a pitch with eleven players per side, goals, and a round ball?', a: 'Football', category: 'culture' },
    { q: 'Which planet is closest to the Sun?', a: 'Mercury', category: 'science' },
    { q: 'What is the name of the domed bone structure that protects the brain?', a: 'Skull', category: 'biology' },
    { q: 'What is the capital of Honduras?', a: 'Tegucigalpa', category: 'geography' },
    { q: 'Which river flows through London?', a: 'Thames', category: 'geography' },
    { q: 'What culinary term means to cut food into small irregular pieces?', a: 'Chop', category: 'food' },
    { q: 'What is the chemical formula for water?', a: 'H2O', category: 'science' },
    { q: 'What type of animal is a whale?', a: 'Mammal', category: 'biology' },
    { q: 'What is the study of blood and blood disorders called?', a: 'Haematology', category: 'biology' },
    { q: 'Which keyboard instrument has 88 keys?', a: 'Piano', category: 'music' },
  ],
  I: [
    { q: 'What is the capital of Italy?', a: 'Rome', category: 'geography' },
    { q: 'What is the largest country in the world by population?', a: 'India', category: 'geography' },
    { q: 'What is the chemical symbol for iodine?', a: 'I', category: 'science' },
    { q: 'Which ocean lies between Africa and Australia?', a: 'Indian Ocean', category: 'geography' },
    { q: 'What is the outermost solid layer of the Earth?', a: 'Crust', category: 'science' },
    { q: 'What is the term for a number with no decimal or fractional part?', a: 'Integer', category: 'maths' },
    { q: 'Which city is known as the Eternal City?', a: 'Rome', category: 'history' },
    { q: 'Which paired organs in the body filter blood and produce urine?', a: 'Kidneys', category: 'biology' },
    { q: 'What is the name for a short pause or interval between two events?', a: 'Interlude', category: 'misc' },
    { q: 'Which country has the most islands in the world?', a: 'Indonesia', category: 'geography' },
    { q: 'What musical interval spans eight notes from one note to the same note higher?', a: 'Octave', category: 'music' },
    { q: 'What do caterpillars transform into after their metamorphosis?', a: 'Butterflies', category: 'nature' },
    { q: 'Which ancient civilization built Machu Picchu?', a: 'Inca', category: 'history' },
    { q: 'What is the iron-containing protein in red blood cells that carries oxygen?', a: 'Haemoglobin', category: 'biology' },
  ],
  J: [
    { q: 'What is the capital of Japan?', a: 'Tokyo', category: 'geography' },
    { q: 'Which country is home to the Amazon River\'s mouth?', a: 'Brazil', category: 'geography' },
    { q: 'What is the name of the largest moon of Jupiter?', a: 'Ganymede', category: 'science' },
    { q: 'Which equestrian sport involves competitors jumping horses over a series of fences?', a: 'Show jumping', category: 'culture' },
    { q: 'Which sea, between Israel and Jordan, is the lowest point on Earth\'s surface?', a: 'Dead Sea', category: 'geography' },
    { q: 'What is the unit of energy in the metric system?', a: 'Joule', category: 'science' },
    { q: 'Which country hosted the 2019 Rugby World Cup?', a: 'Japan', category: 'culture' },
  ],
  K: [
    { q: 'What is the capital of Kenya?', a: 'Nairobi', category: 'geography' },
    { q: 'What is the unit of temperature in science that starts at absolute zero?', a: 'Kelvin', category: 'science' },
    { q: 'What large marsupial is native to Australia?', a: 'Kangaroo', category: 'nature' },
    { q: 'Which mountain range separates Europe from Asia in Russia?', a: 'Urals', category: 'geography' },
    { q: 'Which iconic African tree stores vast amounts of water in its swollen trunk?', a: 'Baobab', category: 'nature' },
    { q: 'What is the capital of Kazakhstan?', a: 'Astana', category: 'geography' },
    { q: 'What is the sweet, sticky coating applied to a glazed ham called?', a: 'Glaze', category: 'food' },
  ],
  L: [
    { q: 'What is the capital of Luxembourg?', a: 'Luxembourg City', category: 'geography' },
    { q: 'What is the largest lake in Africa?', a: 'Lake Victoria', category: 'geography' },
    { q: 'What is the chemical symbol for lithium?', a: 'Li', category: 'science' },
    { q: 'Which country is home to Loch Ness?', a: 'Scotland', category: 'geography' },
    { q: 'The longest bone in the human body, found in the thigh — what is it?', a: 'Femur', category: 'biology' },
    { q: 'What do you call a year that has 366 days?', a: 'Leap year', category: 'science' },
    { q: 'What is the capital of Latvia?', a: 'Riga', category: 'geography' },
    { q: 'What is the most widely spoken native language in the world?', a: 'Mandarin Chinese', category: 'culture' },
    { q: 'Which planet in our solar system has prominent rings?', a: 'Saturn', category: 'science' },
    { q: 'What is the name of the yellow citrus fruit used in cooking and drinks?', a: 'Lemon', category: 'food' },
    { q: 'What is the term for a unit of distance equal to the distance light travels in a year?', a: 'Light-year', category: 'science' },
    { q: 'Which country in South America is known for Lake Titicaca?', a: 'Bolivia', category: 'geography' },
    { q: 'What is the study of language called?', a: 'Linguistics', category: 'misc' },
    { q: 'What music genre originated in Jamaica in the 1960s?', a: 'Reggae', category: 'music' },
  ],
  M: [
    { q: 'What is the capital of Mexico?', a: 'Mexico City', category: 'geography' },
    { q: 'What is the largest organ in the human body?', a: 'Skin', category: 'biology' },
    { q: 'What planet is known as the blue planet?', a: 'Earth', category: 'science' },
    { q: 'What is the chemical symbol for magnesium?', a: 'Mg', category: 'science' },
    { q: 'Which country has the Great Barrier Reef?', a: 'Australia', category: 'geography' },
    { q: 'What is the name of the fundamental force that keeps planets in orbit around the sun?', a: 'Gravity', category: 'science' },
    { q: 'What is the capital of Morocco?', a: 'Rabat', category: 'geography' },
    { q: 'What type of animal is the blue whale?', a: 'Mammal', category: 'biology' },
    { q: 'What is the traditional Japanese alcoholic drink brewed from fermented rice?', a: 'Sake', category: 'food' },
    { q: 'What is the term for the middle layer of the Earth?', a: 'Mantle', category: 'science' },
    { q: 'Which sport is played on a court with a net, using a racket and a ball?', a: 'Tennis', category: 'culture' },
    { q: 'What is the capital of Mongolia?', a: 'Ulaanbaatar', category: 'geography' },
    { q: 'Which instrument is the lead melodic voice in most classical string quartets?', a: 'Violin', category: 'music' },
    { q: 'What is the process when a caterpillar transforms inside a cocoon called?', a: 'Metamorphosis', category: 'biology' },
  ],
  N: [
    { q: 'What is the capital of Norway?', a: 'Oslo', category: 'geography' },
    { q: 'What is the chemical symbol for nitrogen?', a: 'N', category: 'science' },
    { q: 'In which country does the Nile River have its source?', a: 'Uganda', category: 'geography' },
    { q: 'Which country is the largest in Africa by land area?', a: 'Algeria', category: 'geography' },
    { q: 'What do you call the hard covering on the end of your fingers?', a: 'Nail', category: 'biology' },
    { q: 'What gas makes up most of Earth\'s atmosphere?', a: 'Nitrogen', category: 'science' },
    { q: 'Which ocean lies to the north of Europe?', a: 'Arctic Ocean', category: 'geography' },
    { q: 'What is the name of the planet farthest from the sun in our solar system?', a: 'Neptune', category: 'science' },
    { q: 'What culinary term describes serving food completely uncooked?', a: 'Raw', category: 'food' },
    { q: 'Which note is a semitone above C in music?', a: 'C sharp', category: 'music' },
    { q: 'What is the capital of Nepal?', a: 'Kathmandu', category: 'geography' },
    { q: 'What is the study of the nervous system called?', a: 'Neurology', category: 'biology' },
    { q: 'What type of angle is less than 90 degrees?', a: 'Acute angle', category: 'maths' },
    { q: 'Which country produced the composer Edvard Grieg?', a: 'Norway', category: 'music' },
  ],
  O: [
    { q: 'What is the capital of Oman?', a: 'Muscat', category: 'geography' },
    { q: 'What is the chemical symbol for oxygen?', a: 'O', category: 'science' },
    { q: 'Which African country has the longest coastline on the continent?', a: 'Somalia', category: 'geography' },
    { q: 'What is the largest bird in the world that cannot fly?', a: 'Ostrich', category: 'nature' },
    { q: 'What do you call the study of the eye?', a: 'Ophthalmology', category: 'biology' },
    { q: 'What is the name of the world\'s largest ocean?', a: 'Pacific Ocean', category: 'geography' },
    { q: 'What slow-cooking method involves simmering food in a covered pan in its own juices?', a: 'Braising', category: 'food' },
    { q: 'What do you call a number that is only divisible by 1 and itself?', a: 'Prime number', category: 'maths' },
    { q: 'Which ancient Greek philosopher taught Alexander the Great?', a: 'Aristotle', category: 'history' },
    { q: 'What is the name for the atmospheric layer closest to Earth\'s surface?', a: 'Troposphere', category: 'science' },
    { q: 'What small instrument, placed between the teeth and plucked, vibrates to make music?', a: 'Jaw harp', category: 'music' },
    { q: 'What is the capital of Austria?', a: 'Vienna', category: 'geography' },
    { q: 'What is the name of the long-armed primate from Borneo?', a: 'Orangutan', category: 'nature' },
    { q: 'What is the term for the path of an electron around an atom\'s nucleus?', a: 'Orbital', category: 'science' },
  ],
  P: [
    { q: 'What is the capital of Poland?', a: 'Warsaw', category: 'geography' },
    { q: 'What is the chemical symbol for phosphorus?', a: 'P', category: 'science' },
    { q: 'Which country is the world\'s largest producer of coffee?', a: 'Brazil', category: 'geography' },
    { q: 'What is the study of rocks and minerals called?', a: 'Petrology', category: 'science' },
    { q: 'Which organ is the largest internal organ in the human body?', a: 'Liver', category: 'biology' },
    { q: 'Which giant black-and-white bear is native to China?', a: 'Panda', category: 'nature' },
    { q: 'What is the name of the waterway connecting the Atlantic and Pacific Oceans in Central America?', a: 'Panama Canal', category: 'geography' },
    { q: 'What musical term means to gradually get louder?', a: 'Crescendo', category: 'music' },
    { q: 'What type of pastry is used to make croissants?', a: 'Puff pastry', category: 'food' },
    { q: 'What is the value of pi to two decimal places?', a: 'Three point one four', category: 'maths' },
    { q: 'In which South American country is the Patagonia region?', a: 'Argentina', category: 'geography' },
    { q: 'What is the term for a group of fish swimming together?', a: 'School', category: 'nature' },
    { q: 'What ancient civilization built the Colosseum in Rome?', a: 'Romans', category: 'history' },
    { q: 'What is the capital of Portugal?', a: 'Lisbon', category: 'geography' },
  ],
  Q: [
    { q: 'What is the capital of Qatar?', a: 'Doha', category: 'geography' },
    { q: 'What is the name for a set of four musicians?', a: 'Quartet', category: 'music' },
    { q: 'What is the term for one-fourth of a circle\'s circumference?', a: 'Quadrant', category: 'maths' },
    { q: 'Which continent is the driest and coldest on Earth?', a: 'Antarctica', category: 'geography' },
    { q: 'What type of rock is formed from fragments of older rocks cemented together over time?', a: 'Sedimentary rock', category: 'science' },
    { q: 'What tree, belonging to the genus Quercus, produces acorns?', a: 'Oak tree', category: 'nature' },
    { q: 'What fast-paced racket sport is played inside a four-walled enclosed court?', a: 'Squash', category: 'culture' },
  ],
  R: [
    { q: 'What is the capital of Russia?', a: 'Moscow', category: 'geography' },
    { q: 'What is the chemical symbol for radium?', a: 'Ra', category: 'science' },
    { q: 'Which country has the largest rainforest in the world?', a: 'Brazil', category: 'geography' },
    { q: 'What is the name of the coloured ring in the eye surrounding the pupil?', a: 'Iris', category: 'biology' },
    { q: 'What is the name of the longest river in South America?', a: 'Amazon', category: 'geography' },
    { q: 'What type of animal is a boa constrictor?', a: 'Snake', category: 'nature' },
    { q: 'Which mountain is the highest in Africa?', a: 'Kilimanjaro', category: 'geography' },
    { q: 'What musical term means to get gradually slower?', a: 'Ritardando', category: 'music' },
    { q: 'What cooking method involves dry heat in an enclosed oven?', a: 'Roasting', category: 'food' },
    { q: 'What is the ratio of the circumference of a circle to its diameter?', a: 'Pi', category: 'maths' },
    { q: 'What is the capital of Romania?', a: 'Bucharest', category: 'geography' },
    { q: 'What is the study of the movement of fluids called?', a: 'Rheology', category: 'science' },
    { q: 'What do you call a triangle that has all sides of equal length?', a: 'Equilateral triangle', category: 'maths' },
    { q: 'Which North American bird is famous for its ability to mimic the songs of other birds?', a: 'Mockingbird', category: 'nature' },
  ],
  S: [
    { q: 'What is the capital of Spain?', a: 'Madrid', category: 'geography' },
    { q: 'What is the chemical symbol for sulfur?', a: 'S', category: 'science' },
    { q: 'Which planet has the most prominent ring system?', a: 'Saturn', category: 'science' },
    { q: 'What is the largest ocean on Earth?', a: 'Pacific Ocean', category: 'geography' },
    { q: 'What do you call the network of veins that remains after a leaf\'s tissue decays?', a: 'Leaf skeleton', category: 'nature' },
    { q: 'What sport involves sliding down a snow-covered slope on two long runners?', a: 'Skiing', category: 'culture' },
    { q: 'What is the capital of Sweden?', a: 'Stockholm', category: 'geography' },
    { q: 'What culinary term means to cook briefly in a little fat over high heat?', a: 'Sauté', category: 'food' },
    { q: 'What is the name for the upper layer of the ocean that receives sunlight?', a: 'Photic zone', category: 'science' },
    { q: 'What is the total of the interior angles in a triangle?', a: 'One hundred and eighty degrees', category: 'maths' },
    { q: 'Which continent is surrounded entirely by ocean?', a: 'Antarctica', category: 'geography' },
    { q: 'What is the name of the world\'s tallest grass?', a: 'Bamboo', category: 'nature' },
    { q: 'Which instrument is associated with jazz legend Louis Armstrong?', a: 'Trumpet', category: 'music' },
    { q: 'What is the name of the process by which liquid water turns into water vapour?', a: 'Evaporation', category: 'science' },
  ],
  T: [
    { q: 'What is the capital of Turkey?', a: 'Ankara', category: 'geography' },
    { q: 'What is the chemical symbol for titanium?', a: 'Ti', category: 'science' },
    { q: 'Which country contains the Serengeti National Park?', a: 'Tanzania', category: 'geography' },
    { q: 'What is the largest muscle in the human body?', a: 'Gluteus maximus', category: 'biology' },
    { q: 'What sport is played with a bat, ball, and wickets?', a: 'Cricket', category: 'culture' },
    { q: 'What is the name of the sea between Italy and the Balkans?', a: 'Tyrrhenian Sea', category: 'geography' },
    { q: 'What musical term means the speed or pace of a piece of music?', a: 'Tempo', category: 'music' },
    { q: 'Which country has a maple leaf on its national flag?', a: 'Canada', category: 'geography' },
    { q: 'What is the name of the tallest tree species in the world?', a: 'Redwood', category: 'nature' },
    { q: 'What is 12 squared?', a: 'One hundred and forty-four', category: 'maths' },
    { q: 'What is the capital of Thailand?', a: 'Bangkok', category: 'geography' },
    { q: 'Which spice, derived from the stigmas of a flower, is the world\'s most expensive?', a: 'Saffron', category: 'food' },
    { q: 'What is the name for a repeated bass-line pattern in a piece of music?', a: 'Ostinato', category: 'music' },
    { q: 'What is the name of the process by which plants lose water through their leaves?', a: 'Transpiration', category: 'biology' },
  ],
  U: [
    { q: 'What is the capital of Uganda?', a: 'Kampala', category: 'geography' },
    { q: 'What is the term in probability for the set of all possible outcomes?', a: 'Sample space', category: 'maths' },
    { q: 'Which planet in the solar system rotates on its side?', a: 'Uranus', category: 'science' },
    { q: 'What is the name of the bone in the forearm on the little-finger side?', a: 'Ulna', category: 'biology' },
    { q: 'What is the name of the international governing body for football worldwide?', a: 'FIFA', category: 'culture' },
    { q: 'What is the capital of Ukraine?', a: 'Kyiv', category: 'geography' },
    { q: 'What is sound with a frequency above the range of human hearing called?', a: 'Ultrasound', category: 'science' },
  ],
  V: [
    { q: 'What is the capital of Venezuela?', a: 'Caracas', category: 'geography' },
    { q: 'What is the chemical symbol for vanadium?', a: 'V', category: 'science' },
    { q: 'What is the name of the main waterway that winds through Venice?', a: 'Grand Canal', category: 'geography' },
    { q: 'What type of plant produces seeds inside protective cones?', a: 'Conifer', category: 'biology' },
    { q: 'What is the capital of Vietnam?', a: 'Hanoi', category: 'geography' },
    { q: 'What is the name for an active mountain that expels magma?', a: 'Volcano', category: 'science' },
    { q: 'What musical scale uses five notes per octave with no semitones?', a: 'Pentatonic scale', category: 'music' },
  ],
  W: [
    { q: 'What is the capital of Wales?', a: 'Cardiff', category: 'geography' },
    { q: 'What is the phase of the Moon when it is fully illuminated?', a: 'Full moon', category: 'science' },
    { q: 'Which continent is the wettest on Earth?', a: 'South America', category: 'geography' },
    { q: 'What is the name of the world\'s largest living animal?', a: 'Blue whale', category: 'nature' },
    { q: 'What culinary term means to beat cream or eggs until fluffy?', a: 'Whip', category: 'food' },
    { q: 'What is the term for a number that has no fractional part and is positive?', a: 'Whole number', category: 'maths' },
    { q: 'Which country is home to the Waitomo glowworm caves?', a: 'New Zealand', category: 'geography' },
    { q: 'What standard instrument is strummed or plucked and has six strings?', a: 'Guitar', category: 'music' },
    { q: 'What is the name of the force that opposes motion through a fluid?', a: 'Drag', category: 'science' },
    { q: 'What is the capital of Western Australia?', a: 'Perth', category: 'geography' },
    { q: 'What type of rock is created by intense heat and pressure underground?', a: 'Metamorphic rock', category: 'science' },
    { q: 'What do you call the season between autumn and spring?', a: 'Winter', category: 'misc' },
    { q: 'What do you call an animal that is active at night?', a: 'Nocturnal animal', category: 'nature' },
    { q: 'Which flightless bird with a long beak is the national symbol of New Zealand?', a: 'Kiwi', category: 'nature' },
  ],
  X: [
    { q: 'What is the chemical symbol for xenon?', a: 'Xe', category: 'science' },
    { q: 'What ancient Greek stringed instrument was plucked and held in the arms?', a: 'Lyre', category: 'music' },
    { q: 'In biology, what term describes a female organism that has two X chromosomes?', a: 'Female', category: 'biology' },
    { q: 'What type of electromagnetic radiation is used in medical imaging to see bones?', a: 'X-ray', category: 'science' },
    { q: 'What is the name of the percussion instrument made of wooden bars struck with mallets?', a: 'Xylophone', category: 'music' },
  ],
  Y: [
    { q: 'What is the capital of Yemen?', a: 'Sanaa', category: 'geography' },
    { q: 'What is the name of the unit of distance equal to 3 feet?', a: 'Yard', category: 'maths' },
    { q: 'What is the name of the substance used in bread-making to make dough rise?', a: 'Yeast', category: 'food' },
    { q: 'What is the name of the Himalayan mammal used as a pack animal in Tibet?', a: 'Yak', category: 'nature' },
    { q: 'What practice originating in ancient India combines physical postures and breathing?', a: 'Yoga', category: 'culture' },
    { q: 'What is the name of the river that forms part of the border between China and Russia?', a: 'Yenisei River', category: 'geography' },
    { q: 'What colour does the sun appear when viewed from space, without an atmosphere?', a: 'White', category: 'science' },
  ],
  Z: [
    { q: 'What is the capital of Zambia?', a: 'Lusaka', category: 'geography' },
    { q: 'What African animal has black and white stripes?', a: 'Zebra', category: 'nature' },
    { q: 'What is the term for a quantity with no value?', a: 'Zero', category: 'maths' },
    { q: 'What is the name of the imaginary belt in the sky divided into twelve constellations?', a: 'Zodiac', category: 'science' },
    { q: 'What is the capital of Zimbabwe?', a: 'Harare', category: 'geography' },
    { q: 'Which African antelope, also known as the springbok, is among the fastest land animals?', a: 'Springbok', category: 'nature' },
    { q: 'What is the term for a camera lens that cannot bend light to a sharp focus?', a: 'Defective lens', category: 'science' },
  ],
};
