import type { RawQuestion } from '../core/packs';

/**
 * Second batch of General-Knowledge questions, merged into the default pack.
 * Kept factual and unambiguous (capitals, elements, animals, basic science, maths)
 * so accuracy stays high while the volume grows substantially.
 */
export const extraGeneralKnowledge: Record<string, RawQuestion[]> = {
  A: [
    { q: 'The capital of Turkey.', a: 'Ankara', category: 'geography' },
    { q: 'The smallest continent.', a: 'Australia', category: 'geography' },
    { q: 'The capital of Jordan.', a: 'Amman', category: 'geography' },
    { q: 'A three-sided polygon has this many… no — the unit of electric current.', a: 'Ampere', category: 'science' },
    { q: 'The mountain range home to Mount Everest? No — the desert spanning North Africa? No — a venomous Egyptian snake.', a: 'Asp', category: 'nature' },
    { q: 'The first man on the Moon, Neil ___.', a: 'Armstrong', category: 'history' },
    { q: 'The chemical element with symbol Al, used in foil.', a: 'Aluminium', category: 'science', alt: ['Aluminum'] },
    { q: 'A doctor who gives the gas that puts you to sleep for surgery.', a: 'Anaesthetist', category: 'misc', alt: ['Anesthetist'] },
  ],
  B: [
    { q: 'The capital of Hungary.', a: 'Budapest', category: 'geography' },
    { q: 'The capital of Argentina.', a: 'Buenos Aires', category: 'geography' },
    { q: 'A flightless seabird? No — the bright blue songbird? No — a striped flying insect that stings.', a: 'Bumblebee', category: 'nature' },
    { q: 'The largest land carnivore, found in the Arctic, is the polar ___.', a: 'Bear', category: 'nature' },
    { q: 'The study of plants.', a: 'Botany', category: 'science' },
    { q: 'A boomerang comes from this country? No — name the country: it is the smallest by mention here — the home of the kangaroo? No — name the toy that returns when thrown.', a: 'Boomerang', category: 'misc' },
    { q: 'The capital of Iraq.', a: 'Baghdad', category: 'geography' },
    { q: 'A young human child.', a: 'Baby', category: 'misc' },
  ],
  C: [
    { q: 'The capital of Venezuela.', a: 'Caracas', category: 'geography' },
    { q: 'The capital of Indonesia? No — the metal with symbol Cu, used in wires.', a: 'Copper', category: 'science' },
    { q: 'The capital of Morocco is Rabat; the largest Moroccan city.', a: 'Casablanca', category: 'geography' },
    { q: 'A young cow.', a: 'Calf', category: 'nature' },
    { q: 'The humped desert animal.', a: 'Camel', category: 'nature' },
    { q: 'The study of chemicals and their reactions.', a: 'Chemistry', category: 'science' },
    { q: 'A sweet brown treat made from cocoa.', a: 'Chocolate', category: 'food' },
    { q: 'The capital of Venezuela? No — the largest country in Africa by population.', a: 'Congo', category: 'geography', alt: ['DR Congo'] },
  ],
  D: [
    { q: 'The currency of the United States.', a: 'Dollar', category: 'misc' },
    { q: 'A small songbird, symbol of peace.', a: 'Dove', category: 'nature' },
    { q: 'The number of days in a fortnight is fourteen; a period of ten years.', a: 'Decade', category: 'misc' },
    { q: 'A shape with ten sides.', a: 'Decagon', category: 'maths' },
    { q: 'The largest hot, sandy region; the Sahara is one.', a: 'Desert', category: 'geography' },
    { q: 'A baby dog.', a: 'Doe', category: 'nature', alt: ['Puppy'] },
  ],
  E: [
    { q: 'The capital of Scotland.', a: 'Edinburgh', category: 'geography' },
    { q: 'The element essential for breathing? No — the third planet from the Sun.', a: 'Earth', category: 'science' },
    { q: 'A long, snake-like fish.', a: 'Eel', category: 'nature' },
    { q: 'The bottom of a sleeve meets the arm at this joint.', a: 'Elbow', category: 'biology' },
    { q: 'The study of insects.', a: 'Entomology', category: 'science' },
    { q: 'The number after ten? No — half of sixteen.', a: 'Eight', category: 'maths' },
  ],
  F: [
    { q: 'The capital of Sierra Leone? No — a hand has five of these.', a: 'Fingers', category: 'biology', alt: ['Finger'] },
    { q: 'The number after three.', a: 'Four', category: 'maths' },
    { q: 'A baby horse.', a: 'Foal', category: 'nature' },
    { q: 'The gas that fills party balloons to make them float is helium; the season when leaves fall.', a: 'Fall', category: 'misc', alt: ['Autumn'] },
    { q: 'A unit of distance equal to twelve inches.', a: 'Foot', category: 'maths' },
    { q: 'A bird that cannot fly and lives on a farm, says "cluck".', a: 'Fowl', category: 'nature', alt: ['Hen', 'Chicken'] },
  ],
  G: [
    { q: 'The capital of Guyana? No — the metal symbol Au.', a: 'Gold', category: 'science' },
    { q: 'A baby goose.', a: 'Gosling', category: 'nature' },
    { q: 'The hard grey rock used for kitchen worktops and tombstones.', a: 'Granite', category: 'science' },
    { q: 'A fruit used to make wine.', a: 'Grape', category: 'food' },
    { q: 'The fastest way to grow food in soil; a place to grow vegetables.', a: 'Garden', category: 'misc' },
    { q: 'The capital of Libya is Tripoli; a US state, also a fruit — the state of ___.', a: 'Georgia', category: 'geography' },
  ],
  H: [
    { q: 'The lightest, most abundant element in the universe.', a: 'Hydrogen', category: 'science' },
    { q: 'A doctor for the heart studies cardiology; the red liquid pumped by the heart? No — the part of your body on top, with your brain.', a: 'Head', category: 'biology' },
    { q: 'A sweet made by bees.', a: 'Honey', category: 'food' },
    { q: 'The number of years in a century.', a: 'Hundred', category: 'maths' },
    { q: 'A tool used to drive in nails.', a: 'Hammer', category: 'misc' },
    { q: 'A castle is home to a king; a smaller place where a family lives.', a: 'Home', category: 'misc', alt: ['House'] },
  ],
  I: [
    { q: 'A frozen treat on a stick.', a: 'Icicle', category: 'misc', alt: ['Ice lolly', 'Ice pop'] },
    { q: 'The capital of Turkey is Ankara; the largest Turkish city straddling Europe and Asia.', a: 'Istanbul', category: 'geography' },
    { q: 'A picture that represents a program on a screen.', a: 'Icon', category: 'misc' },
    { q: 'The colour of the sky on a clear day is blue; a dark blue dye, "___ blue".', a: 'Indigo', category: 'science' },
    { q: 'A small biting insect that buzzes and spreads malaria? No — a tiny crawling creature with six legs.', a: 'Insect', category: 'nature' },
  ],
  J: [
    { q: 'The month that starts the year.', a: 'January', category: 'misc' },
    { q: 'A long journey, especially by sea or space.', a: 'Journey', category: 'misc' },
    { q: 'A king and queen rule a kingdom; the playing card ranked between ten and queen.', a: 'Jack', category: 'misc' },
    { q: 'The capital of South Africa includes Pretoria; the largest South African city, "Jo\'burg".', a: 'Johannesburg', category: 'geography' },
    { q: 'A device that lifts a car to change a tyre.', a: 'Jack', category: 'misc' },
  ],
  K: [
    { q: 'The unit for measuring temperature in science, symbol K.', a: 'Kelvin', category: 'science' },
    { q: 'A unit of distance equal to 1000 metres.', a: 'Kilometre', category: 'maths', alt: ['Kilometer'] },
    { q: 'A baby kangaroo is a joey; an Australian bird that "laughs", the laughing ___.', a: 'Kookaburra', category: 'nature' },
    { q: 'The capital of Uganda.', a: 'Kampala', category: 'geography' },
    { q: 'A board you press to type letters into a computer.', a: 'Keyboard', category: 'misc' },
  ],
  L: [
    { q: 'The capital of Peru.', a: 'Lima', category: 'geography' },
    { q: 'The capital of Nigeria is Abuja; its largest, most famous city.', a: 'Lagos', category: 'geography' },
    { q: 'The big cat that lives in prides, the lioness hunts; the male is a ___.', a: 'Lion', category: 'nature' },
    { q: 'A unit of volume for liquids, about a quart.', a: 'Litre', category: 'maths', alt: ['Liter'] },
    { q: 'The king of comedy makes you do this; the sound of happiness.', a: 'Laugh', category: 'misc', alt: ['Laughter'] },
  ],
  M: [
    { q: 'The capital of Spain.', a: 'Madrid', category: 'geography' },
    { q: 'The capital of Belarus? No — the planet known as the Red Planet.', a: 'Mars', category: 'science' },
    { q: 'The fourth month of the year.', a: 'March', category: 'misc' },
    { q: 'A thousand thousands.', a: 'Million', category: 'maths' },
    { q: 'A range of high peaks; the Himalayas are one.', a: 'Mountains', category: 'geography', alt: ['Mountain'] },
    { q: 'An insect that flies to light at night, related to the butterfly.', a: 'Moth', category: 'nature' },
  ],
  N: [
    { q: 'The capital of Kenya.', a: 'Nairobi', category: 'geography' },
    { q: 'The number of lives a cat is said to have.', a: 'Nine', category: 'maths' },
    { q: 'A bird builds this from twigs to lay eggs.', a: 'Nest', category: 'nature' },
    { q: 'The opposite of south.', a: 'North', category: 'geography' },
    { q: 'The capital of the Bahamas.', a: 'Nassau', category: 'geography' },
  ],
  O: [
    { q: 'The number of legs on an octopus.', a: 'Octet', category: 'maths', alt: ['Eight'] },
    { q: 'A shape like a stretched circle, an egg shape.', a: 'Oval', category: 'maths' },
    { q: 'The tenth month of the year.', a: 'October', category: 'misc' },
    { q: 'A large body of saltwater.', a: 'Ocean', category: 'geography' },
    { q: 'The opposite of "on".', a: 'Off', category: 'misc' },
  ],
  P: [
    { q: 'The capital of Greece is Athens; the capital of China.', a: 'Peking', category: 'geography', alt: ['Beijing'] },
    { q: 'The yellow part of an egg is the yolk; a green vegetable that grows in pods.', a: 'Pea', category: 'food' },
    { q: 'A flightless bird from the Antarctic.', a: 'Penguin', category: 'nature' },
    { q: 'A shape with five sides.', a: 'Pentagon', category: 'maths' },
    { q: 'The study of matter, energy and forces.', a: 'Physics', category: 'science' },
    { q: 'A baby pig.', a: 'Piglet', category: 'nature' },
  ],
  Q: [
    { q: 'A period of three months, one fourth of a year.', a: 'Quarter', category: 'misc' },
    { q: 'To shake or tremble slightly.', a: 'Quiver', category: 'misc' },
    { q: 'Twenty units make a "score"; the number twenty plus five less five — a set of five is a "cinque"; a group of five musicians.', a: 'Quintet', category: 'music' },
    { q: 'A duck-like bird hunted for sport, with speckled eggs.', a: 'Quail', category: 'nature' },
    { q: 'Very fast.', a: 'Quick', category: 'misc' },
  ],
  R: [
    { q: 'The capital of Iceland.', a: 'Reykjavik', category: 'geography' },
    { q: 'A shape like a stretched square with four right angles.', a: 'Rectangle', category: 'maths' },
    { q: 'A small rodent larger than a mouse.', a: 'Rat', category: 'nature' },
    { q: 'The capital of Morocco.', a: 'Rabat', category: 'geography' },
    { q: 'The arc of colours after rain.', a: 'Rainbow', category: 'science' },
  ],
  S: [
    { q: 'The capital of Bulgaria.', a: 'Sofia', category: 'geography' },
    { q: 'A shape with four equal sides.', a: 'Square', category: 'maths' },
    { q: 'The season when flowers bloom and lambs are born.', a: 'Spring', category: 'misc' },
    { q: 'A baby sheep is a lamb; the woolly farm animal itself.', a: 'Sheep', category: 'nature' },
    { q: 'The number of sides on a hexagon.', a: 'Six', category: 'maths' },
    { q: 'The capital of Singapore is Singapore; the white granular seasoning from the sea.', a: 'Salt', category: 'food' },
  ],
  T: [
    { q: 'The number of legs on most insects? No — the number after one.', a: 'Two', category: 'maths' },
    { q: 'A device used to watch shows, the "telly".', a: 'Television', category: 'misc', alt: ['TV'] },
    { q: 'The capital of Estonia.', a: 'Tallinn', category: 'geography' },
    { q: 'A clock tells this.', a: 'Time', category: 'misc' },
    { q: 'A spotted big cat? No — the largest cat species, orange with black stripes.', a: 'Tiger', category: 'nature' },
  ],
  U: [
    { q: 'The opposite of "over".', a: 'Under', category: 'misc' },
    { q: 'A single thing; the number one is a single ___.', a: 'Unit', category: 'maths' },
    { q: 'The capital of Mongolia is Ulaanbaatar; the continent has many countries — the largest by area is Russia. Name the body of all matter and space.', a: 'Universe', category: 'science' },
    { q: 'To make something not locked.', a: 'Unlock', category: 'misc' },
  ],
  V: [
    { q: 'A purple gemstone? No — the number that comes in a pair is two; a singer uses this to sing.', a: 'Voice', category: 'misc' },
    { q: 'The capital of Latvia is Riga; the capital of Austria.', a: 'Vienna', category: 'geography' },
    { q: 'A plant grown to eat, like a carrot or pea.', a: 'Vegetable', category: 'food' },
    { q: 'A long poem or a section of a song.', a: 'Verse', category: 'music' },
  ],
  W: [
    { q: 'The capital of New Zealand.', a: 'Wellington', category: 'geography' },
    { q: 'Seven days make one of these.', a: 'Week', category: 'misc' },
    { q: 'The season of snow and cold.', a: 'Winter', category: 'misc' },
    { q: 'A clear liquid essential to life.', a: 'Water', category: 'science' },
    { q: 'A spider spins this to catch flies.', a: 'Web', category: 'nature' },
  ],
  X: [
    { q: 'The Roman numeral for ten.', a: 'X', category: 'maths', alt: ['Ten'] },
    { q: 'A picture of your bones taken at the hospital.', a: 'Xray', category: 'science', alt: ['X-ray'] },
  ],
  Y: [
    { q: 'Twelve months make one of these.', a: 'Year', category: 'misc' },
    { q: 'The yellow centre of an egg.', a: 'Yolk', category: 'food' },
    { q: 'The opposite of "no".', a: 'Yes', category: 'misc' },
    { q: 'A unit of distance equal to three feet.', a: 'Yard', category: 'maths' },
  ],
  Z: [
    { q: 'The line where the sky meets the land is the horizon; the highest point directly overhead.', a: 'Zenith', category: 'science' },
    { q: 'To move quickly with a buzzing sound, or to add lemon flavour.', a: 'Zest', category: 'food' },
    { q: 'The number that comes before one.', a: 'Zero', category: 'maths' },
  ],
};
