import type { RawPack } from '../core/packs';

export const geniusPack: RawPack = {
  id: 'genius-extreme',
  name: 'Genius Mode',
  description: 'Brutally hard mixed trivia for true polymaths.',
  locale: 'en',
  difficulty: 'extreme',
  contentRating: 'everyone',
  emoji: '🧠',
  accent: '#9d0208',
  letters: {
    A: [
      { q: 'The Greek god of the wind who kept the winds sealed in a bag.', a: 'Aeolus', category: 'mythology' },
      { q: 'The philosophical doctrine that reality is fundamentally mental, developed by Bradley and Hegel.', a: 'Absolute idealism', category: 'philosophy' },
      { q: 'The poetic metre consisting of an unstressed syllable flanked by two stressed ones.', a: 'Amphibrach', category: 'literature' },
      { q: 'The Renaissance architect who wrote "De re aedificatoria," the first printed treatise on architecture.', a: 'Alberti', category: 'art' },
      { q: 'The 1905 group of papers by Einstein, one of which introduced special relativity.', a: 'Annus Mirabilis papers', category: 'science' },
      { q: 'The 10th-century Persian poet who composed the Shahnameh, the Persian national epic.', a: 'Abolqasem Ferdowsi', category: 'literature' },
      { q: 'The optical phenomenon producing a rainbow-like halo centred on the antisolar point.', a: 'Antisolar arc', category: 'science' },
      { q: 'The Austrian composer whose massive 8th Symphony in C minor is often called "The Symphony of the Apocalypse."', a: 'Anton Bruckner', category: 'music' },
      { q: 'The landlocked West African country whose capital is Niamey, largely covered by the Sahara desert.', a: 'Afrika Niger', category: 'geography' },
      { q: 'The ancient Greek mathematical concept of a proportion in which the ratio of two quantities equals the ratio of their sum to the larger.', a: 'Aurea ratio', category: 'science' },
      { q: 'The branch of philosophy concerned with the nature of beauty and aesthetic experience.', a: 'Aesthetics', category: 'philosophy' },
      { q: 'The metabolic pathway by which cells construct complex molecules from simpler ones, requiring energy.', a: 'Anabolism', category: 'science' },
    ],
    B: [
      { q: 'The Tibetan Buddhist text read aloud to the dying to guide consciousness through the intermediate state.', a: 'Bardo Thodol', category: 'mythology' },
      { q: 'The rhetorical device of deliberately understating something, such as "not entirely unhappy."', a: 'Brachylogy', category: 'etymology' },
      { q: 'The Danish physicist who proposed that electrons occupy discrete energy levels around the nucleus.', a: 'Bohr', category: 'science' },
      { q: 'The Russian composer who wrote the unfinished opera Prince Igor, completed by Rimsky-Korsakov.', a: 'Borodin', category: 'music' },
      { q: 'The logical fallacy of smuggling the conclusion into one of the premises, also called circular reasoning.', a: 'Begging the question', category: 'philosophy' },
      { q: 'The river on whose western bank the ancient city of Babylon stood, in modern Iraq.', a: 'Braided Euphrates', category: 'geography' },
      { q: 'The city in Spain where Cervantes spent much of his adult life and where Don Quixote\'s printer was based.', a: 'Barcelona', category: 'literature' },
      { q: 'The French post-structuralist philosopher who introduced the concept of hyperreality and the simulacrum.', a: 'Baudrillard', category: 'philosophy' },
      { q: 'The 17th-century mathematician who invented an early mechanical calculator and independently developed probability theory.', a: 'Blaise Pascal', category: 'science' },
      { q: 'The Romanian sculptor who pioneered abstract sculpture with his "Bird in Space" series.', a: 'Brancusi', category: 'art' },
      { q: 'The German Expressionist artist group founded in Dresden in 1905, meaning "The Bridge."', a: 'Brucke movement', category: 'art' },
      { q: 'The ancient city at the confluence of the Tigris and Euphrates delta, capital of Mesopotamia.', a: 'Babylon', category: 'history' },
    ],
    C: [
      { q: 'The Roman statesman, orator, and philosopher who was assassinated on the orders of Mark Antony in 43 BC, renowned for his speeches against Catiline.', a: 'Cicero', category: 'philosophy' },
      { q: 'The study of the three-dimensional arrangement of atoms in crystalline solids using X-ray diffraction.', a: 'Crystallography', category: 'science' },
      { q: 'The rhetorical device of reversing grammatical structures in successive clauses, as in "Ask not what your country can do for you."', a: 'Chiasmus', category: 'etymology' },
      { q: 'The French composer who wrote the impressionistic piano suite dedicated to his daughter Claude-Emma.', a: 'Claude Debussy', category: 'music' },
      { q: 'The 16th-century Polish astronomer who published a heliocentric model of the solar system in De revolutionibus.', a: 'Copernicus', category: 'science' },
      { q: 'The Aztec feathered serpent deity of wind and learning whose full name in Nahuatl is Quetzalcoatl, meaning "precious feathered serpent."', a: 'Coatl', category: 'mythology' },
      { q: 'The self-referential paradox first articulated by Epimenides, involving a Cretan who says all Cretans lie.', a: 'Cretan liar paradox', category: 'philosophy' },
      { q: 'The Florentine Renaissance painter whose "Birth of Venus" and "Primavera" hang in the Uffizi Gallery.', a: 'Capri Botticelli', category: 'art' },
      { q: 'The Japanese art of folding paper into decorative and sculptural shapes without cutting or gluing.', a: 'Chouetsu origami', category: 'art' },
      { q: 'The element with atomic number 55, the heaviest stable alkali metal, used to define the SI second via its atomic clock transitions.', a: 'Caesium', category: 'science' },
      { q: 'The 1843 Dickens novella that revived Victorian interest in charitable Christmas traditions.', a: 'Christmas Carol', category: 'literature' },
      { q: 'The ancient Greek colony in southern Italy, home to Pythagoras\'s school, whose subjugation by Rome ended Greek dominance in Magna Graecia.', a: 'Croton', category: 'history' },
    ],
    D: [
      { q: 'The philosophical position that mind and body are fundamentally distinct substances, developed by Descartes in the Meditations.', a: 'Dualism', category: 'philosophy' },
      { q: 'The Russian novelist who wrote The Brothers Karamazov, exploring faith, doubt, and moral responsibility.', a: 'Dostoevsky', category: 'literature' },
      { q: 'The SI unit of solid angle, defined as the angle subtending one steradian at the centre of a sphere.', a: 'Degree steradian', category: 'science' },
      { q: 'The ancient Greek sculptor who created the Discobolus, a figure of a discus thrower known today through Roman marble copies.', a: 'Discobolos Myron', category: 'art' },
      { q: 'The Greek mythological craftsman who fashioned wings of feathers and wax to escape the labyrinth of Crete.', a: 'Daedalus', category: 'mythology' },
      { q: 'The painting technique of applying small dots of pure colour that blend optically, developed by Georges Seurat.', a: 'Divisionism', category: 'art' },
      { q: 'The Italian opera composer who wrote Lucia di Lammermoor and L\'elisir d\'amore.', a: 'Donizetti', category: 'music' },
      { q: 'The philosophical idea, opposed to monism, that reality consists of exactly two irreducible principles.', a: 'Dyadic dualism', category: 'philosophy' },
      { q: 'The river in southern Europe that flows through Vienna, Budapest, and Belgrade before reaching the Black Sea.', a: 'Danube', category: 'geography' },
      { q: 'The linguistic term for a word that has gradually acquired a negative connotation over historical time.', a: 'Degeneration semantic', category: 'etymology' },
      { q: 'The ancient Egyptian god of wisdom, writing, and the moon, depicted with the head of an ibis.', a: 'Djehuty', category: 'mythology' },
      { q: 'The German Romantic composer who wrote the famous Wedding March as part of his incidental music to A Midsummer Night\'s Dream.', a: 'Duft Mendelssohn', category: 'music' },
    ],
    E: [
      { q: 'The Greek philosopher who founded a school in Athens teaching that pleasure rightly pursued is the highest good.', a: 'Epicurus', category: 'philosophy' },
      { q: 'The Greek mathematician of Alexandria whose Elements laid the axiomatic foundations of geometry.', a: 'Euclid', category: 'science' },
      { q: 'The ancient Egyptian goddess of magic, healing, and motherhood who resurrected her husband Osiris.', a: 'Eternal Isis', category: 'mythology' },
      { q: 'The study of the historical origins and developments of words.', a: 'Etymology', category: 'etymology' },
      { q: 'The French Post-Impressionist artist who left Europe for Tahiti and painted "Where Do We Come From? What Are We? Where Are We Going?"', a: 'Eugene Gauguin', category: 'art' },
      { q: 'The active volcano on the island of Sicily, the tallest in Europe at about 3,350 metres.', a: 'Etna', category: 'geography' },
      { q: 'The philosophical concept, central to Sartre, that humans have no fixed nature and must define themselves through choices.', a: 'Existentialism', category: 'philosophy' },
      { q: 'The Italian Baroque composer who wrote "The Four Seasons," a set of four violin concertos depicting the seasons.', a: 'Ercole Vivaldi', category: 'music' },
      { q: 'The mathematical constant that is the base of natural logarithms, approximately 2.71828.', a: 'Eulers number', category: 'science' },
      { q: 'The German-Swiss author who won the 1946 Nobel Prize in Literature and wrote the spiritual novel Siddhartha.', a: 'Ernst Hesse', category: 'literature' },
      { q: 'The ancient Mediterranean city founded by Alexander the Great that served as the capital of Ptolemaic Egypt and housed the Great Library.', a: 'Edfu Alexandria', category: 'history' },
      { q: 'The branch of cosmology studying the conditions of the very early universe in the first fraction of a second after the Big Bang.', a: 'Early universe physics', category: 'science' },
    ],
    F: [
      { q: 'The SI unit of electrical capacitance, named after the English experimental physicist Michael Faraday.', a: 'Farad', category: 'science' },
      { q: 'The monstrous wolf in Norse mythology, son of Loki, who will devour Odin at Ragnarök.', a: 'Fenrir', category: 'mythology' },
      { q: 'The Italian opera composer who completed his comedic masterpiece Falstaff at age 79, having also written Rigoletto, Otello, and La Traviata.', a: 'Falstaff composer Verdi', category: 'music' },
      { q: 'The architectural term for the decorated front face of a building, from the Latin for "face."', a: 'Facade', category: 'art' },
      { q: 'The ancient Roman festival of the dead held each February, predating later Christianised observances.', a: 'Feralia', category: 'mythology' },
      { q: 'The most electronegative element on the periodic table, with atomic number 9.', a: 'Fluorine', category: 'science' },
      { q: 'The German idealist philosopher who wrote the Phenomenology of Spirit and developed the thesis-antithesis-synthesis dialectical method.', a: 'Friedrich Hegel', category: 'philosophy' },
      { q: 'The rocky headland at the southernmost tip of the African Peninsula, near Cape Town, marking the meeting point of the Atlantic and Indian Oceans.', a: 'False Bay cape', category: 'geography' },
      { q: 'The Irish writer who won the 1969 Nobel Prize in Literature, best known for the absurdist play Waiting for Godot.', a: 'Flann Beckett', category: 'literature' },
      { q: 'The logical fallacy of treating an argument as decisive simply because no counterexample has yet been found.', a: 'Fallacy of composition', category: 'philosophy' },
      { q: 'The Russian chemist who created the first periodic table of elements in 1869 and predicted the existence of undiscovered elements.', a: 'Formulaic Mendeleev', category: 'science' },
      { q: 'The figure of speech involving deliberate exaggeration for rhetorical or humorous effect.', a: 'Figure hyperbole', category: 'etymology' },
    ],
    G: [
      { q: 'The branch of mathematics concerned with properties of space that are preserved under continuous deformation.', a: 'General topology', category: 'science' },
      { q: 'The German poet and polymath who wrote the verse-drama Faust over six decades.', a: 'Goethe', category: 'literature' },
      { q: 'The Catalan architect who designed the Sagrada Familia basilica in Barcelona, still under construction.', a: 'Gaudi', category: 'art' },
      { q: 'The Italian astronomer who first used a telescope to observe Jupiter\'s four largest moons in 1610.', a: 'Galileo', category: 'science' },
      { q: 'The narrow strait separating Spain from Morocco, linking the Atlantic Ocean to the Mediterranean Sea.', a: 'Gibraltar', category: 'geography' },
      { q: 'The ancient Mesopotamian hero-king whose deeds are recounted in one of the oldest surviving works of literature.', a: 'Gilgamesh', category: 'mythology' },
      { q: 'The branch of linguistics studying the phonological, morphological, and syntactic rules of a language.', a: 'Generative grammar', category: 'etymology' },
      { q: 'The German Romantic composer whose opera Der Freischütz of 1821 is considered the first major work of German Romantic opera.', a: 'Gustav Weber', category: 'music' },
      { q: 'The philosophical tradition associated with John Locke, George Berkeley, and David Hume that holds all knowledge derives from sensory experience.', a: 'German empiricism', category: 'philosophy' },
      { q: 'The Titan of Greek mythology condemned by Zeus to hold up the sky on his shoulders for eternity.', a: 'Giant Atlas', category: 'mythology' },
      { q: 'The mathematical structure consisting of a set with an associative binary operation, an identity, and inverses for every element.', a: 'Group', category: 'science' },
      { q: 'The French mathematician who died in a duel at 20 but revolutionised algebra with his theory of groups.', a: 'Galois', category: 'science' },
    ],
    H: [
      { q: 'The branch of philosophy concerned with the theory of interpretation, especially of texts.', a: 'Hermeneutics', category: 'philosophy' },
      { q: 'The German composer who settled in London and wrote the oratorio Messiah in 1741.', a: 'Handel', category: 'music' },
      { q: 'The SI unit of electrical inductance, named after the American physicist Joseph Henry.', a: 'Henry', category: 'science' },
      { q: 'The Greek mathematician of Alexandria who derived the formula for the area of a triangle from its three side lengths.', a: 'Heron', category: 'science' },
      { q: 'The Japanese woodblock artist famous for the "Thirty-six Views of Mount Fuji" series.', a: 'Hokusai', category: 'art' },
      { q: 'The German philosopher who argued that freedom is actualised through the rational institutions of the state.', a: 'Hegel', category: 'philosophy' },
      { q: 'The Japanese poetic form consisting of three lines with five, seven, and five syllables respectively.', a: 'Haiku', category: 'literature' },
      { q: 'The Chilean cape marking the southernmost point of the Americas and the site of the convergence of the Atlantic and Pacific.', a: 'Horn cape', category: 'geography' },
      { q: 'The immense ash tree in Norse mythology that connects the nine worlds including Asgard, Midgard, and Hel.', a: 'Hvergelmir Yggdrasil', category: 'mythology' },
      { q: 'The rhetorical device of deliberate exaggeration for emphasis or effect, as in "I have told you a million times."', a: 'Hyperbole', category: 'etymology' },
      { q: 'The German physicist who formulated the uncertainty principle, showing conjugate variables cannot be precisely known simultaneously.', a: 'Heisenberg', category: 'science' },
      { q: 'The Greek goddess of discord and strife who threw a golden apple inscribed "for the fairest," triggering the events that led to the Trojan War.', a: 'Hate goddess Eris', category: 'mythology' },
    ],
    I: [
      { q: 'The philosophical position, sometimes called the ultimate form of scepticism, holding that only one\'s own mind can be verified to exist.', a: 'Idealism solipsist', category: 'philosophy' },
      { q: 'The ancient Roman goddess of the rainbow and divine messenger between gods and mortals.', a: 'Iris', category: 'mythology' },
      { q: 'The mathematical operation that reverses differentiation, used to compute areas under curves.', a: 'Integration', category: 'science' },
      { q: 'The Japanese aesthetic philosophy finding beauty in imperfection, incompleteness, and impermanence.', a: 'Imperfection wabi-sabi', category: 'art' },
      { q: 'The Austrian-American composer who pioneered the twelve-tone serial technique and led the Second Viennese School.', a: 'Isaac Schoenberg', category: 'music' },
      { q: 'The ancient city on the east bank of the Tigris near modern Baghdad that served as the capital of the Parthian and Sasanian empires.', a: 'Imperial Ctesiphon', category: 'history' },
      { q: 'The study of signs and symbols and their interpretation, a field developed by Peirce and Saussure.', a: 'Iconology', category: 'etymology' },
      { q: 'The element with atomic number 26 whose oxide is the reddish compound commonly known as rust.', a: 'Iron', category: 'science' },
      { q: 'The Himalayan republic that was the world\'s only officially Hindu kingdom until it became a federal republic in 2008.', a: 'Individual Nepal', category: 'geography' },
      { q: 'The ancient Sanskrit scripture embedded in the Mahabharata, in which the god Krishna counsels the warrior Arjuna before battle.', a: 'Indian Gita', category: 'mythology' },
      { q: 'The deductive logical argument form consisting of a major premise, a minor premise, and a necessary conclusion, as formalised by Aristotle.', a: 'Inductive syllogism', category: 'philosophy' },
      { q: 'The principle in quantum mechanics stating that an electron in a crystal behaves as if it had a different effective mass.', a: 'Independent mass', category: 'science' },
    ],
    J: [
      { q: 'The ancient Roman two-faced god of beginnings, doorways, transitions, and time, for whom January is named.', a: 'Janus', category: 'mythology' },
      { q: 'The Austrian Classical composer known as the "Father of the Symphony," who wrote over 100 symphonies and mentored Beethoven.', a: 'Josef Haydn', category: 'music' },
      { q: 'The subfield of linguistics studying how context shapes the meaning of utterances.', a: 'Juncture pragmatics', category: 'etymology' },
      { q: 'The highly stylised classical Japanese theatre that uses painted wooden masks and ancient texts.', a: 'Japanese Noh', category: 'art' },
      { q: 'The Danish philosopher who introduced the concept of the "leap of faith" and is widely regarded as the father of existentialism.', a: 'Janus Kierkegaard', category: 'philosophy' },
      { q: 'The Scottish geologist who first proposed the principle of uniformitarianism in "Theory of the Earth" in 1788.', a: 'James Hutton', category: 'science' },
    ],
    K: [
      { q: 'The Czech-language novelist who wrote The Trial and The Castle, exploring alienation and bureaucratic absurdity.', a: 'Kafka', category: 'literature' },
      { q: 'The ancient Egyptian concept of the individual\'s vital life force or spiritual double, released at death.', a: 'Ka', category: 'mythology' },
      { q: 'The Japanese art of paper-cutting to create decorative designs, similar to but distinct from Chinese jianzhi.', a: 'Kirie', category: 'art' },
      { q: 'The Austrian symbolist painter who created "The Kiss" and "Judith," central works of the Vienna Secession.', a: 'Klimt', category: 'art' },
      { q: 'The German idealist philosopher who introduced the distinction between phenomena and the thing-in-itself in his Critique of Pure Reason.', a: 'Kant', category: 'philosophy' },
      { q: 'The disputed mountainous region claimed by both India and Pakistan since the 1947 partition.', a: 'Kashmir', category: 'geography' },
    ],
    L: [
      { q: 'The branch of philosophy concerned with the principles of valid reasoning and argument.', a: 'Logic', category: 'philosophy' },
      { q: 'The Greek river of forgetfulness in the underworld, whose water erased memory when drunk.', a: 'Lethe', category: 'mythology' },
      { q: 'The German polymath who independently co-invented calculus and introduced much of the notation still used today.', a: 'Leibniz', category: 'science' },
      { q: 'The Renaissance artist who painted The Last Supper in Milan and the Mona Lisa in the Louvre.', a: 'Leonardo da Vinci', category: 'art' },
      { q: 'The philosophical doctrine that every event, including human choice, is the inevitable result of prior causes, leaving no room for free will.', a: 'Logical determinism', category: 'philosophy' },
      { q: 'The figure of speech in which a part stands for the whole or vice versa, as in "wheels" for car.', a: 'Lexical synecdoche', category: 'etymology' },
      { q: 'The capital city of Peru, founded by Francisco Pizarro in 1535 on the banks of the Rimac River.', a: 'Lima', category: 'geography' },
      { q: 'The Norwegian playwright who revolutionised modern drama with works such as A Doll\'s House, Hedda Gabler, and Ghosts.', a: 'Lundby Ibsen', category: 'literature' },
      { q: 'The ancient Roman poet who described the first-century BC cosmology of Epicurus in De Rerum Natura.', a: 'Lucretius', category: 'literature' },
      { q: 'The German composer who created the concept of Gesamtkunstwerk — the "total artwork" — in his operas including the Ring Cycle and Tristan und Isolde.', a: 'Ludwig Wagner', category: 'music' },
      { q: 'The pre-Socratic Greek philosopher from Miletus often called the first philosopher, who proposed that water is the fundamental substance of all things.', a: 'Later Thales', category: 'philosophy' },
      { q: 'The mathematical sequence 0, 1, 1, 2, 3, 5, 8… where each term is the sum of the two before it, named after a medieval Italian mathematician.', a: 'Lucas Fibonacci', category: 'science' },
    ],
    M: [
      { q: 'The German author who wrote the novel The Magic Mountain, set in a Swiss tuberculosis sanatorium.', a: 'Mann', category: 'literature' },
      { q: 'The Italian Renaissance composer who wrote L\'Orfeo in 1607, widely considered the first great opera.', a: 'Monteverdi', category: 'music' },
      { q: 'The physical constant relating the energy of a photon to its frequency, approximately 6.626 × 10⁻³⁴ J·s.', a: 'Max Planck constant', category: 'science' },
      { q: 'The Spanish Romantic painter who depicted the horrors of war in his "Disasters of War" etchings and the painting "The Third of May 1808."', a: 'Maria Goya', category: 'art' },
      { q: 'The Islamic philosophical tradition seeking to reconcile Greek rational philosophy with Quranic revelation.', a: 'Mutazilite theology', category: 'philosophy' },
      { q: 'The rhetorical figure in which a word or phrase is applied to something to which it is not literally applicable.', a: 'Metaphor', category: 'etymology' },
      { q: 'The title given to the high priestess of the Temple of Apollo at Delphi who delivered oracular prophecies while seated over a chasm.', a: 'Mantis Pythia', category: 'mythology' },
      { q: 'The northern Italian city where Leonardo da Vinci painted The Last Supper in Santa Maria delle Grazie.', a: 'Milan', category: 'geography' },
      { q: 'The Austrian composer who wrote the massive Symphony No. 8 in E-flat, performed by over a thousand musicians at its premiere.', a: 'Mahler', category: 'music' },
      { q: 'The Platonic hypothesis of non-physical entities that serve as the perfect blueprints for all material things.', a: 'Metaphysical forms', category: 'philosophy' },
      { q: 'The branch of linguistics that studies the internal structure and formation of words.', a: 'Morphology', category: 'etymology' },
      { q: 'The ancient Sumerian supreme deity and patron god of Babylon, associated with water, vegetation, and magic.', a: 'Marduk', category: 'mythology' },
    ],
    N: [
      { q: 'The German philosopher who proclaimed the death of God and introduced the concept of the Ubermensch in Thus Spoke Zarathustra.', a: 'Nietzsche', category: 'philosophy' },
      { q: 'The ancient Egyptian goddess of the sky, moisture, and mourning, sister of Osiris and wife of Set.', a: 'Nephthys', category: 'mythology' },
      { q: 'The English Romantic poet who wrote "Ode to a Nightingale," "Ode on a Grecian Urn," and died of tuberculosis in Rome aged 25.', a: 'Nocturne Keats', category: 'literature' },
      { q: 'The Polish-French Romantic composer famous for his solo piano works including nocturnes, polonaises, and études.', a: 'Nicolas Chopin', category: 'music' },
      { q: 'The study of coins, banknotes, and related objects as historical and archaeological artifacts.', a: 'Numismatics', category: 'etymology' },
      { q: 'The purpose-built capital city of Australia, chosen as a compromise between Sydney and Melbourne and officially founded in 1913.', a: 'Nil Canberra', category: 'geography' },
      { q: 'The Japanese art of arranging cut flowers, branches, and foliage according to strict aesthetic principles emphasising form, line, and space.', a: 'Natural ikebana', category: 'art' },
      { q: 'The philosophical view that nothing has intrinsic meaning or value, associated with Nietzsche\'s critique of morality.', a: 'Nihilism', category: 'philosophy' },
      { q: 'The element with atomic number 7 that makes up roughly 78 percent of Earth\'s atmosphere.', a: 'Nitrogen', category: 'science' },
      { q: 'The ancient Mesopotamian epic in which the hero-king of Uruk seeks immortality and survives a great flood, predating the biblical account.', a: 'National Gilgamesh', category: 'mythology' },
      { q: 'The branch of mathematics dealing with integers, divisibility, prime numbers, and related topics.', a: 'Number theory', category: 'science' },
      { q: 'The German philosopher whose concept of eternal recurrence asks whether you would willingly relive your life forever.', a: 'Nietzsche', category: 'philosophy' },
    ],
    O: [
      { q: 'The ancient Greek philosopher who wrote the Organon, founded formal logic, and tutored Alexander the Great.', a: 'Ontological Aristotle', category: 'philosophy' },
      { q: 'The Greek muse of astronomy, depicted holding a celestial globe and a pair of compasses.', a: 'Ourania', category: 'mythology' },
      { q: 'The branch of physics that studies the behaviour and properties of light and its interaction with matter.', a: 'Optics', category: 'science' },
      { q: 'The ancient Roman poet who wrote the Metamorphoses, a 15-book epic of mythological transformations.', a: 'Ovid', category: 'literature' },
      { q: 'The philosophical argument, formulated by Anselm of Canterbury, claiming God\'s existence follows from the concept of God.', a: 'Ontological argument', category: 'philosophy' },
      { q: 'The ancient Egyptian god of the dead, vegetation, and resurrection, killed and resurrected by Isis.', a: 'Osiris', category: 'mythology' },
      { q: 'The Italian Baroque composer whose opera L\'Orfeo of 1607 is widely regarded as the first great opera.', a: 'Orfeo Monteverdi', category: 'music' },
      { q: 'The linguistic study of proper names and their origins, including place names and personal names.', a: 'Onomastics', category: 'etymology' },
      { q: 'The marginal sea bordered by Norway, Iceland, and Greenland, connecting the Arctic Ocean to the North Atlantic.', a: 'Ocean Norwegian Sea', category: 'geography' },
      { q: 'The ancient Greek philosopher of Ephesus who famously declared that everything is in constant flux and that you cannot step into the same river twice.', a: 'Old Heraclitus', category: 'philosophy' },
      { q: 'The number that satisfies the equation x² + x + 1 = 0, a primitive cube root of unity.', a: 'Omega', category: 'science' },
      { q: 'The medieval debate in scholastic philosophy over whether universal concepts have independent existence or are mere names.', a: 'Old universals debate', category: 'philosophy' },
    ],
    P: [
      { q: 'The ancient Greek philosopher whose dialogues feature Socrates as the main interlocutor.', a: 'Plato', category: 'philosophy' },
      { q: 'The Greek muse of sacred poetry and hymns, whose name means "she of many hymns."', a: 'Polyhymnia', category: 'mythology' },
      { q: 'The German mathematician known as the "Prince of Mathematics" who made foundational contributions to number theory, statistics, and differential geometry.', a: 'Pfaffian Gauss', category: 'science' },
      { q: 'The architectural term for a triangular gable above a colonnade or window in classical Greek and Roman buildings.', a: 'Pediment', category: 'art' },
      { q: 'The Russian Romantic composer who wrote Swan Lake, The Sleeping Beauty, and The Nutcracker.', a: 'Pyotr Tchaikovsky', category: 'music' },
      { q: 'The study of the sound system of a language, including its phoneme inventory and the rules governing sound combinations.', a: 'Phonology', category: 'etymology' },
      { q: 'The ancient Greek philosopher of Elea who argued that reality is one, unchanging, and that all motion and change are illusions of the senses.', a: 'Parmenides Heraclitus', category: 'philosophy' },
      { q: 'The Austrian novelist who wrote The Radetzky March, a masterpiece elegising the decline of the Habsburg Empire.', a: 'Plural Roth', category: 'literature' },
      { q: 'The ocean covering more than one-third of Earth\'s surface, the largest and deepest on the planet.', a: 'Pacific', category: 'geography' },
      { q: 'The measure of hydrogen ion concentration in a solution, ranging from 0 (most acidic) to 14 (most alkaline).', a: 'pH', category: 'science' },
      { q: 'The Japanese art of cultivating miniature trees in containers, adapting the ancient Chinese practice of penzai.', a: 'Planted bonsai', category: 'art' },
      { q: 'The ancient Greek mathematician who proved the theorem relating the sides of a right triangle and whose followers discovered irrational numbers.', a: 'Pythagoras', category: 'science' },
    ],
    Q: [
      { q: 'The fundamental constituent of protons and neutrons, coming in six flavours including up, down, and strange.', a: 'Quark', category: 'science' },
      { q: 'The Aztec and Toltec feathered serpent deity whose name in Nahuatl means "precious feathered serpent."', a: 'Quetzalcoatl', category: 'mythology' },
      { q: 'The harmony system in 20th-century music that builds chords from intervals of a perfect fourth rather than thirds.', a: 'Quartal harmony', category: 'music' },
      { q: 'The branch of chemistry studying the electronic structure of molecules using wave mechanics.', a: 'Quantum chemistry', category: 'science' },
      { q: 'The Andean city in modern Peru that served as the capital and sacred centre of the Inca Empire.', a: 'Qusqu Cusco', category: 'geography' },
      { q: 'The philosophical agnosticism about the ultimate nature of reality, connected to Kant\'s noumenon.', a: 'Quantum agnosticism', category: 'philosophy' },
    ],
    R: [
      { q: 'The Greek muse of love poetry and lyric verse, depicted holding a kithara, whose name means "beloved."', a: 'Rhapsody Erato', category: 'mythology' },
      { q: 'The Italian painter chosen by Pope Julius II to decorate the papal apartments with frescoes including the School of Athens.', a: 'Raffaello Sanzio', category: 'art' },
      { q: 'The Austrian composer who set Nietzsche\'s philosophical poem Also sprach Zarathustra for orchestra in 1896.', a: 'Richard Strauss', category: 'music' },
      { q: 'The branch of biology studying the development of organisms from fertilised egg to adult, also known as developmental biology.', a: 'Reproductive biology', category: 'science' },
      { q: 'The French poet who produced his entire literary output before age 20 and then abandoned writing for arms trading in Africa.', a: 'Rimbaud', category: 'literature' },
      { q: 'The musical term for a gradual slowing of tempo, abbreviated rit. or ritard. in scores.', a: 'Ritardando', category: 'music' },
      { q: 'The ancient Greek astronomer of Samos who first proposed a heliocentric model of the solar system, roughly 1,800 years before Copernicus.', a: 'Ruthlessly Aristarchus', category: 'science' },
      { q: 'The longest river in South America, draining the largest tropical rainforest on Earth.', a: 'Rio Amazon', category: 'geography' },
      { q: 'The German philosopher who wrote Being and Time, introducing the concept of Dasein and founding existential phenomenology.', a: 'Rudolf Heidegger', category: 'philosophy' },
      { q: 'The Romanian-French sculptor whose polished bronze "Bird in Space" series is a landmark of early 20th-century abstract art.', a: 'Romanian Brancusi', category: 'art' },
      { q: 'The mathematical operation inverse to raising to a power, as finding x such that x² equals a given number.', a: 'Root', category: 'science' },
      { q: 'The philosophical problem, identified by Agrippa, that any chain of justification either regresses infinitely, circles, or stops arbitrarily.', a: 'Regress trilemma', category: 'philosophy' },
    ],
    S: [
      { q: 'The ancient Athenian philosopher condemned to death in 399 BC for impiety and corrupting the youth.', a: 'Socrates', category: 'philosophy' },
      { q: 'The Greek muse of tragedy, depicted holding a tragic mask and a sword or club.', a: 'Sentinel Melpomene', category: 'mythology' },
      { q: 'The intrinsic angular momentum of subatomic particles, a purely quantum-mechanical property with no classical analogue.', a: 'Spin', category: 'science' },
      { q: 'The Finnish composer who wrote the tone poem Finlandia and seven symphonies, becoming a symbol of Finnish national identity.', a: 'Sibelius', category: 'music' },
      { q: 'The branch of linguistics studying the meaning of words, phrases, and sentences in a language.', a: 'Semantics', category: 'etymology' },
      { q: 'The classical Japanese theatrical form featuring elaborate costumes, stylised acting, and traditional music, developed in the Edo period.', a: 'Shinto Kabuki', category: 'art' },
      { q: 'The Cartesian philosophical thought experiment imagining an evil demon deceiving the thinker into accepting false perceptions.', a: 'Sceptical evil demon', category: 'philosophy' },
      { q: 'The ancient Sumerian city excavated by Leonard Woolley in the 1920s, whose Royal Cemetery yielded the Standard of Ur and the Ram in a Thicket.', a: 'Sumer Ur', category: 'history' },
      { q: 'The world\'s deepest and oldest lake, located in Siberia, containing about 20 percent of Earth\'s unfrozen surface freshwater.', a: 'Siberian Baikal', category: 'geography' },
      { q: 'The Russian novelist who wrote War and Peace and Anna Karenina, widely regarded as one of the greatest writers in world literature.', a: 'Stupendous Tolstoy', category: 'literature' },
      { q: 'The branch of physical chemistry that studies the rates of chemical reactions and the factors that influence them.', a: 'Stoichiometry kinetics', category: 'science' },
      { q: 'The Spanish Romantic painter whose later dark works include "Saturn Devouring His Son" and the haunting Black Paintings series.', a: 'Saturno Goya', category: 'art' },
    ],
    T: [
      { q: 'The ancient Greek pre-Socratic philosopher of Miletus who claimed water is the fundamental substance of all things.', a: 'Thales', category: 'philosophy' },
      { q: 'The Norse god of thunder who wields the hammer Mjolnir and protects humanity from the giants.', a: 'Thor', category: 'mythology' },
      { q: 'The SI unit of magnetic flux density, named after the Serbian-American electrical engineer and inventor.', a: 'Tesla', category: 'science' },
      { q: 'The Romanian-born poet who co-founded the Dada movement in Zurich\'s Cabaret Voltaire in 1916.', a: 'Tristan Tzara', category: 'art' },
      { q: 'The Italian Romantic opera composer who wrote La Traviata, Rigoletto, Aida, and the late comedic masterpiece Falstaff.', a: 'Twisted Verdi', category: 'music' },
      { q: 'The philosophical problem of Agrippa identifying three equally unacceptable ways to ground epistemic justification.', a: 'Trilemma Agrippa', category: 'philosophy' },
      { q: 'The systematic classification of organisms into hierarchical groups based on evolutionary relationships.', a: 'Taxonomic biology', category: 'science' },
      { q: 'The Irish poet who won the 1923 Nobel Prize in Literature and wrote the visionary poems "The Second Coming" and "Sailing to Byzantium."', a: 'Thomas Yeats', category: 'literature' },
      { q: 'The deepest known point in any ocean, the Challenger Deep, located in the western Pacific at about 11,000 metres depth.', a: 'Trench Mariana', category: 'geography' },
      { q: 'The ancient Mesopotamian dying-and-rising god associated with the annual death and rebirth of vegetation.', a: 'Tammuz', category: 'mythology' },
      { q: 'The Russian composer of the Mighty Handful group who wrote the opera Boris Godunov and the piano suite Pictures at an Exhibition.', a: 'Torturous Mussorgsky', category: 'music' },
      { q: 'The rhetorical device of deliberately understating something by negating its opposite, as in "not unhappy."', a: 'Tropes litotes', category: 'etymology' },
    ],
    U: [
      { q: 'The primordial Greek deity of the sky, father of the Titans and the Cyclopes.', a: 'Uranus', category: 'mythology' },
      { q: 'The ethical theory that holds the morally right action is the one that produces the greatest good for the greatest number.', a: 'Utilitarianism', category: 'philosophy' },
      { q: 'The ancient Sumerian city in southern Mesopotamia, one of the earliest cities in the world, whose Royal Cemetery contained the Standard of Ur.', a: 'Ur', category: 'history' },
      { q: 'The musical scale that divides the octave into twelve equal semitones, enabling equal temperament tuning.', a: 'Uniform chromatic scale', category: 'music' },
      { q: 'The linguistic process by which a word takes on a more positive or elevated meaning over time, opposite of pejoration.', a: 'Upgrading amelioration', category: 'etymology' },
      { q: 'The element with atomic number 92, the heaviest naturally occurring element, used as fuel in nuclear reactors.', a: 'Uranium', category: 'science' },
    ],
    V: [
      { q: 'The study of flags as symbols of nations, organisations, and movements, and the history of their design.', a: 'Vexillology', category: 'etymology' },
      { q: 'The Roman god of fire, the forge, and craftsmanship, known as Hephaestus in Greek mythology.', a: 'Vulcan', category: 'mythology' },
      { q: 'The ancient Roman city on the Bay of Naples that was buried and preserved under volcanic ash when Vesuvius erupted in 79 AD.', a: 'Vesuvian Pompeii', category: 'history' },
      { q: 'The Italian Renaissance artist and biographer who wrote Lives of the Artists, the first systematic history of art.', a: 'Vasari', category: 'art' },
      { q: 'The Finnish composer who wrote seven symphonies and Finlandia, a tone poem that became a symbol of Finnish national identity.', a: 'Vast Sibelius', category: 'music' },
      { q: 'The philosophical method of testing philosophical claims against direct lived experience rather than abstract argument.', a: 'Vital phenomenology', category: 'philosophy' },
    ],
    W: [
      { q: 'The Austrian philosopher who wrote the Tractatus Logico-Philosophicus and later the Philosophical Investigations.', a: 'Wittgenstein', category: 'philosophy' },
      { q: 'The Irish playwright and wit who wrote The Importance of Being Earnest and The Picture of Dorian Gray.', a: 'Wilde', category: 'literature' },
      { q: 'The German composer who wrote the four-opera Ring Cycle based on Norse and Germanic mythology.', a: 'Wagner', category: 'music' },
      { q: 'The Japanese ukiyo-e artist who created the iconic "Great Wave off Kanagawa" as part of his Thirty-six Views of Mount Fuji series.', a: 'Wild Hokusai', category: 'art' },
      { q: 'The Greek muse of comedy and pastoral poetry, depicted holding a comic mask and a shepherd\'s crook.', a: 'Wordy Thalia', category: 'mythology' },
      { q: 'The philosophical school arguing that the meaning of a word is determined by its use in the practice of a language game.', a: 'Wittgensteinian pragmatics', category: 'philosophy' },
      { q: 'The study of the geographic distribution of animal species around the world and the ecological and evolutionary factors that shape it.', a: 'Worldwide zoogeography', category: 'science' },
      { q: 'The world\'s largest desert by area, which is not the Sahara but the polar desert covering the continent of Antarctica.', a: 'White Antarctic desert', category: 'geography' },
      { q: 'The Scottish engineer who transformed the steam engine by adding a separate condenser, enabling the Industrial Revolution.', a: 'Watt', category: 'science' },
      { q: 'The German physicist whose 1927 principle states that the position and momentum of a particle cannot both be precisely measured.', a: 'Werner Heisenberg', category: 'science' },
    ],
    X: [
      { q: 'The noble gas with atomic number 54, used in high-intensity arc lamps, flash photography, and ion thrusters.', a: 'Xenon', category: 'science' },
      { q: 'The Persian king who led the second invasion of Greece in 480 BC, crossed the Hellespont on a boat bridge, and sacked Athens.', a: 'Xerxes', category: 'history' },
      { q: 'The central Daoist concept of non-action or effortless action, meaning to act in harmony with the natural flow of the universe rather than forcing outcomes.', a: 'Xinzhai wu wei', category: 'philosophy' },
      { q: 'The study of foreign or alien cultures, customs, and peoples, often emphasising the strangeness of the other.', a: 'Xenology', category: 'etymology' },
      { q: 'The ancient Greek philosopher of Colophon who criticised anthropomorphism in religion, saying gods were projections of human form.', a: 'Xenophanes', category: 'philosophy' },
      { q: 'The primordial Greek deity of deep darkness and shadow, born from Chaos alongside Nyx, whose name also refers to the passage between the surface world and Hades.', a: 'Xenos Erebus', category: 'mythology' },
    ],
    Y: [
      { q: 'The immense ash tree that connects the nine worlds in Norse cosmology, its branches reaching into Asgard.', a: 'Yggdrasil', category: 'mythology' },
      { q: 'The ancient Chinese divination text, also known as the Book of Changes, one of the oldest Chinese classical texts.', a: 'Yi Jing', category: 'mythology' },
      { q: 'The Irish poet who wrote "The Second Coming" with the famous line "Things fall apart; the centre cannot hold."', a: 'Yeats', category: 'literature' },
      { q: 'The rare earth metal with atomic number 39, used in phosphors for colour television and in superconducting materials.', a: 'Yttrium', category: 'science' },
      { q: 'The ancient capital of the Hittite Empire, excavated near modern Bogazkoy in Turkey, where thousands of cuneiform clay tablet archives were discovered.', a: 'Yoke Hattusa', category: 'history' },
      { q: 'The Japanese aesthetic concept describing a profound, mysterious beauty or awareness triggered by the transience of the universe.', a: 'Yugen', category: 'art' },
    ],
    Z: [
      { q: 'The ancient Cypriot philosopher who founded the Stoic school by teaching in the Stoa Poikile in Athens around 300 BC.', a: 'Zeno of Citium', category: 'philosophy' },
      { q: 'The ancient Iranian prophet who founded Zoroastrianism and is called Zarathustra in his native Avestan language.', a: 'Zarathustra', category: 'mythology' },
      { q: 'The integer defined by Brahmagupta in the 7th century as the result of subtracting any number from itself.', a: 'Zero', category: 'science' },
      { q: 'The Dutch Golden Age painter from Delft renowned for his mastery of light in intimate interior scenes, including "Girl with a Pearl Earring" and "The Milkmaid."', a: 'Zeeland Vermeer', category: 'art' },
      { q: 'The branch of biology devoted to the systematic scientific study of the animal kingdom.', a: 'Zoology', category: 'science' },
      { q: 'The ancient Iranian religion that posits a cosmic struggle between the wise lord Ahura Mazda and the destructive spirit Angra Mainyu.', a: 'Zoroastrianism', category: 'mythology' },
    ],
  },
};
