import type { RawQuestion } from '../core/packs';

export const gulfExtra2: Record<string, RawQuestion[]> = {
  A: [
    { q: 'The main Doha air gateway that opened in 2014, named after a late ruling emir.', a: 'Hamad International Airport', category: 'gcc', difficulty: 5, alt: ['Hamad Airport'] },
    { q: 'The Arabic word for the male ruler of an emirate, a title borne in Kuwait and Qatar.', a: 'Amir', category: 'gcc', difficulty: 3, alt: ['Emir'] },
    { q: 'The fragrant cooling herb steeped into a sweet tea served across Gulf majlis gatherings.', a: 'Mint', category: 'gcc', difficulty: 2, alt: ['Naana'] },
    { q: 'The Doha-based state airline repeatedly voted among the world\'s best carriers.', a: 'Qatar Airways', category: 'gcc', difficulty: 3 },
    { q: 'The pre-dawn meal eaten before the daylight fast begins during the holy month.', a: 'Suhoor', category: 'gcc', difficulty: 3, alt: ['Sahur'] },
    { q: 'The flagship long-haul carrier of the small oil state at the head of the Gulf, the oldest national airline in the region, founded in 1953.', a: 'Kuwait Airways', category: 'gcc', difficulty: 4 },
    { q: 'The lunar dating system that governs Muslim months and festivals, counted from the Prophet\'s migration.', a: 'Islamic calendar', category: 'gcc', difficulty: 3, alt: ['Hijri calendar', 'Lunar calendar'] },
  ],
  B: [
    { q: 'The grain that, ground and cooked with meat into a thick savoury porridge, makes the Ramadan dish harees.', a: 'Wheat', category: 'gcc', difficulty: 3 },
    { q: 'The thin crisp Gulf flatbread cooked on a domed iron griddle and drizzled with date syrup at breakfast.', a: 'Khubz', category: 'gcc', difficulty: 4, alt: ['Khubz rqaq'] },
    { q: 'The fertile coastal plain of northern Oman, a long belt of date plantations and trading ports facing the Gulf of Oman.', a: 'Batinah', category: 'gcc', difficulty: 5, alt: ['Al Batinah'] },
    { q: 'The Kuwaiti national dish of spiced rice and fish or meat; in Bahrain the same dish often pairs rice with this safflower-tinted grain.', a: 'Biryani', category: 'gcc', difficulty: 3 },
  ],
  C: [
    { q: 'The branch of Islam to which the great majority of Gulf Arabs belong, the larger of the faith\'s two main divisions.', a: 'Sunni Islam', category: 'gcc', difficulty: 3, alt: ['Sunni'] },
    { q: 'The branch of Islam practised by a large share of Bahrainis and eastern Gulf communities, the smaller of the two main divisions.', a: 'Shia Islam', category: 'gcc', difficulty: 3, alt: ['Shia', 'Shiite'] },
    { q: 'The direction toward the holy city of Mecca that Muslims face when they pray, marked by a niche in every mosque.', a: 'Qibla', category: 'gcc', difficulty: 4 },
    { q: 'The dried whole spice, a black bud, added with cardamom and saffron to flavour Gulf coffee and rice.', a: 'Cloves', category: 'gcc', difficulty: 4 },
    { q: 'The golden-red thread spice, the most costly in the world, that tints and perfumes festive Gulf rice and sweets.', a: 'Saffron', category: 'gcc', difficulty: 3 },
  ],
  D: [
    { q: 'The vast offshore gas reservoir Qatar shares with Iran, the world\'s largest single non-associated field, by its English name.', a: 'North Field', category: 'gcc', difficulty: 5, alt: ['North Dome'] },
    { q: 'The southern Iraqi port city near the Kuwaiti border, scene of fighting in the 1991 conflict.', a: 'Basra', category: 'gcc', difficulty: 3 },
    { q: 'The unit of currency used in Qatar and Oman as a sub-division, and the main currency of the Emirates and Morocco.', a: 'Dirham', category: 'gcc', difficulty: 3 },
    { q: 'The seasonal northerly wind that sweeps dust and sand across the Gulf in early summer, by its Arabic name.', a: 'Shamal', category: 'gcc', difficulty: 5 },
  ],
  E: [
    { q: 'The body of water that connects to the Gulf at its southern end via the Strait of Hormuz, leading toward the Indian Ocean.', a: 'Gulf of Oman', category: 'gcc', difficulty: 3 },
    { q: 'The festival concluding the fasting month with prayers, feasting and gifts, by its full Arabic name.', a: 'Eid al-Fitr', category: 'gcc', difficulty: 3 },
    { q: 'The festival of sacrifice marking the climax of the pilgrimage season, the second of the two major Islamic feasts.', a: 'Eid al-Adha', category: 'gcc', difficulty: 4 },
  ],
  F: [
    { q: 'The Friday congregational prayer at the mosque, the most important weekly gathering for Muslims.', a: 'Jumua', category: 'gcc', difficulty: 4, alt: ['Jumuah', 'Friday prayer'] },
    { q: 'The traditional flat round bread baked on the inner walls of a clay oven, eaten with most Gulf meals.', a: 'Flatbread', category: 'gcc', difficulty: 2 },
    { q: 'The deep-fried balls of ground chickpeas or fava beans, a popular Gulf and Levantine snack.', a: 'Falafel', category: 'gcc', difficulty: 2 },
    { q: 'The dawn prayer, the first of the five daily Islamic prayers, performed before sunrise.', a: 'Fajr', category: 'gcc', difficulty: 4 },
  ],
  G: [
    { q: 'The desert antelope of the Arabian Peninsula, smaller than the oryx, prized in Bedouin poetry for its grace.', a: 'Gazelle', category: 'gcc', difficulty: 3 },
    { q: 'The peninsula\'s great south-eastern sand sea, the world\'s largest continuous expanse of sand, shared by Saudi Arabia, Oman and the UAE.', a: 'Empty Quarter', category: 'gcc', difficulty: 3, alt: ['Rub al Khali'] },
    { q: 'The Doha district built as a row of mirrored towers along the bay, the country\'s glittering modern business hub.', a: 'West Bay', category: 'gcc', difficulty: 5 },
  ],
  H: [
    { q: 'The migration of the Prophet Muhammad from Mecca to Medina that marks year one of the Islamic calendar.', a: 'Hijra', category: 'gcc', difficulty: 4, alt: ['Hegira'] },
    { q: 'The Iraqi leader whose 1990 invasion of Kuwait triggered the Gulf War, by his given first name.', a: 'Saddam', category: 'gcc', difficulty: 4, alt: ['Saddam Hussein'] },
    { q: 'The headscarf worn by many Muslim women across the Gulf to cover the hair.', a: 'Hijab', category: 'gcc', difficulty: 2 },
    { q: 'The chickpea dip blended with tahini, lemon and garlic, a staple of the Gulf mezze table.', a: 'Hummus', category: 'gcc', difficulty: 2 },
  ],
  I: [
    { q: 'The leader who stands at the front of a mosque to lead the congregation in prayer.', a: 'Imam', category: 'gcc', difficulty: 3 },
    { q: 'The pre-Islamic age of ignorance that Muslims say ended with the coming of the Prophet, by its Arabic name.', a: 'Jahiliyyah', category: 'gcc', difficulty: 5 },
    { q: 'The ancient South Asian river-civilisation, east of Arabia, that Bahrain\'s Bronze Age Dilmun traded with through the Gulf.', a: 'Indus Valley', category: 'gcc', difficulty: 5, alt: ['Indus Valley Civilisation'] },
  ],
  J: [
    { q: 'The Arabic word for a mountain or rugged peak, appearing in Gulf place names from Oman to the Emirates.', a: 'Jabal', category: 'gcc', difficulty: 4, alt: ['Jebel'] },
    { q: 'The desert-rose-shaped landmark on Doha\'s waterfront that opened in 2019 to tell the country\'s story.', a: 'National Museum of Qatar', category: 'gcc', difficulty: 5 },
    { q: 'The pottery and palm-frond crafts and the oral poetry passed down by Gulf families, the broad word for such inherited tradition.', a: 'Heritage', category: 'gcc', difficulty: 3 },
  ],
  K: [
    { q: 'The white ankle-length men\'s robe of the Gulf as it is specifically called in the Emirates and Qatar.', a: 'Kandura', category: 'gcc', difficulty: 3 },
    { q: 'The grilled skewered meat dish, a staple of Gulf and Levantine tables, threaded onto metal rods over coals.', a: 'Kebab', category: 'gcc', difficulty: 2 },
    { q: 'The black cube-shaped shrine at the centre of Mecca\'s Grand Mosque toward which Muslims pray.', a: 'Kaaba', category: 'gcc', difficulty: 2 },
    { q: 'The fava-bean stew simmered overnight and ladled over bread for breakfast, a beloved Gulf and Egyptian morning dish.', a: 'Foul', category: 'gcc', difficulty: 4, alt: ['Ful medames', 'Foul medames'] },
  ],
  L: [
    { q: 'The aromatic resin burned across Oman and the Gulf for its sweet smoke, known regionally by this Arabic word.', a: 'Luban', category: 'gcc', difficulty: 5 },
    { q: 'The sun-dried black or dark limes dropped whole into Gulf rice and meat stews to give a deep sour tang.', a: 'Loomi', category: 'gcc', difficulty: 5, alt: ['Black lime', 'Dried lime'] },
  ],
  M: [
    { q: 'The reception hall where Gulf families and tribal leaders gather to receive guests and discuss affairs.', a: 'Majlis', category: 'gcc', difficulty: 3 },
    { q: 'The slender tower of a mosque from which the call to prayer is traditionally called.', a: 'Minaret', category: 'gcc', difficulty: 3 },
    { q: 'The official who climbs the tower or uses loudspeakers to chant the call to prayer five times a day.', a: 'Muezzin', category: 'gcc', difficulty: 4 },
    { q: 'Kuwait City\'s largest white house of worship, beside the seafront.', a: 'Grand Mosque', category: 'gcc', difficulty: 4, alt: ['Kuwait Grand Mosque'] },
    { q: 'The northern Omani coastal city, a historic trading port and former capital of the Batinah region near the UAE border.', a: 'Sohar', category: 'gcc', difficulty: 5 },
    { q: 'The chant called five times daily summoning the faithful to worship, by its Arabic name.', a: 'Adhan', category: 'gcc', difficulty: 3, alt: ['Azan', 'Call to prayer'] },
  ],
  N: [
    { q: 'The Bedouin custom of generously hosting and protecting any traveller for three days, a cornerstone of desert honour.', a: 'Diyafa', category: 'gcc', difficulty: 5, alt: ['Hospitality'] },
    { q: 'The northern Kuwaiti island, the country\'s largest, kept as an uninhabited nature reserve in the bay.', a: 'Bubiyan', category: 'gcc', difficulty: 5 },
    { q: 'The five daily Islamic prayers, the ritual repeated facing Mecca, by its Arabic name.', a: 'Salah', category: 'gcc', difficulty: 3, alt: ['Salat'] },
  ],
  O: [
    { q: 'The fragrant agarwood chips burned over coals to scent Gulf clothing and homes, also a stringed Arabic instrument.', a: 'Oud', category: 'gcc', difficulty: 4, alt: ['Agarwood'] },
    { q: 'The white-coated long-horned antelope of Arabia, hunted near to extinction then bred back in Gulf reserves.', a: 'Oryx', category: 'gcc', difficulty: 3, alt: ['Arabian oryx'] },
    { q: 'The lush watered spot in the desert where date palms and towns grew up around springs.', a: 'Oasis', category: 'gcc', difficulty: 2 },
  ],
  P: [
    { q: 'The traditional Gulf occupation, mostly extinct since the 1930s, of diving from dhows to gather oysters from the seabed.', a: 'Pearling', category: 'gcc', difficulty: 3 },
    { q: 'The fruit-bearing tree, with its dates and shade, that is the iconic plant of every Gulf oasis.', a: 'Palm tree', category: 'gcc', difficulty: 2, alt: ['Date palm'] },
    { q: 'The founder of Islam, born in Mecca around 570, whose teachings underpin the faith of all the Gulf states.', a: 'Prophet Muhammad', category: 'gcc', difficulty: 2, alt: ['Muhammad'] },
  ],
  R: [
    { q: 'The Islamic prayer cycle of standing, bowing and prostrating, repeated a set number of times in each prayer.', a: 'Rakat', category: 'gcc', difficulty: 5, alt: ['Rakah', 'Rakaat'] },
    { q: 'The currency of Qatar, divided into 100 dirhams, sharing its name with the units of Oman, Iran and Yemen.', a: 'Riyal', category: 'gcc', difficulty: 3, alt: ['Rial', 'Qatari riyal'] },
    { q: 'The Bedouin tribal collective and code of loyalty binding extended families across the desert, the social bedrock of Gulf society.', a: 'Tribe', category: 'gcc', difficulty: 3, alt: ['Qabila'] },
  ],
  S: [
    { q: 'The Islamic profession of faith, the first pillar, declaring there is no god but God and Muhammad is His messenger.', a: 'Shahada', category: 'gcc', difficulty: 3 },
    { q: 'The thinly sliced spit-roasted meat wrapped in flatbread, a beloved Gulf and Levantine street food.', a: 'Shawarma', category: 'gcc', difficulty: 2 },
    { q: 'The honorific Arabic title for a tribal elder, religious scholar or member of a ruling family.', a: 'Sheikh', category: 'gcc', difficulty: 2, alt: ['Shaikh'] },
    { q: 'The sunset prayer, the fourth of the five daily Islamic prayers, performed just after the sun goes down.', a: 'Maghrib', category: 'gcc', difficulty: 5 },
    { q: 'The annual heritage boat race and pearling-revival festival held in Qatar each winter.', a: 'Senyar', category: 'gcc', difficulty: 5 },
  ],
  T: [
    { q: 'The paste of ground sesame seeds stirred into hummus and drizzled over Gulf and Levantine dishes.', a: 'Tahini', category: 'gcc', difficulty: 3, alt: ['Tahina'] },
    { q: 'The white head-cloth Gulf men drape over the head, held in place by a black cord.', a: 'Ghutra', category: 'gcc', difficulty: 4, alt: ['Shemagh'] },
    { q: 'The clay oven, sunk in the ground or upright, in which Gulf and South Asian cooks bake bread on the inner wall.', a: 'Tandoor', category: 'gcc', difficulty: 3, alt: ['Tannour'] },
    { q: 'The black cord coiled atop a Gulf man\'s head-cloth to hold it in place, once used to hobble camels.', a: 'Agal', category: 'gcc', difficulty: 4, alt: ['Egal'] },
  ],
  U: [
    { q: 'The single Muslim global community of believers, transcending nation and tribe, by its Arabic name.', a: 'Ummah', category: 'gcc', difficulty: 4 },
    { q: 'The lesser pilgrimage to Mecca that can be undertaken at any time of year, unlike the fixed-date major one.', a: 'Umrah', category: 'gcc', difficulty: 3 },
  ],
  V: [
    { q: 'The all-covering outer cloth or face covering worn by some Gulf women, the English word for such a screen of modesty.', a: 'Veil', category: 'gcc', difficulty: 3 },
  ],
  W: [
    { q: 'The Islamic system of charitable endowment, by which property is dedicated in perpetuity for religious or public good.', a: 'Waqf', category: 'gcc', difficulty: 5 },
    { q: 'The ritual washing of hands, face, arms and feet a Muslim performs before each prayer.', a: 'Wudu', category: 'gcc', difficulty: 4, alt: ['Ablution'] },
  ],
  Y: [
    { q: 'The day of communal Islamic worship across the Gulf, when the main congregational prayer is held, falling at the end of the week.', a: 'Friday', category: 'gcc', difficulty: 3 },
  ],
  Z: [
    { q: 'The obligatory annual alms-giving, a fixed share of one\'s wealth, counted among the five pillars of Islam.', a: 'Zakat', category: 'gcc', difficulty: 3 },
    { q: 'The sacred spring water from Mecca that pilgrims drink and carry home from the holy sanctuary.', a: 'Zamzam', category: 'gcc', difficulty: 4 },
  ],
  AA: [
    { q: 'The first month of the Islamic calendar, sacred and the time of the Day of Ashura.', a: 'Muharram', category: 'gcc', difficulty: 5 },
    { q: 'The tenth-day commemoration in the first Islamic month, especially solemn for Shia communities in Bahrain.', a: 'Ashura', category: 'gcc', difficulty: 5 },
    { q: 'The prized fungus foraged from the sand after winter rains, a seasonal Gulf desert delicacy.', a: 'Desert truffle', category: 'gcc', difficulty: 4, alt: ['Faqa', 'Truffle'] },
    { q: 'The reddish-brown body art painted on hands and feet by Gulf women before weddings and festivals.', a: 'Henna', category: 'gcc', difficulty: 2 },
    { q: 'The lavish wedding-feast dish of a whole roasted lamb laid over spiced rice, served to many guests.', a: 'Ouzi', category: 'gcc', difficulty: 4, alt: ['Ghuzi', 'Quzi'] },
    { q: 'The large prized reef fish, known locally as hammour, grilled or fried with rice in Gulf coastal kitchens.', a: 'Grouper', category: 'gcc', difficulty: 4, alt: ['Hammour'] },
    { q: 'The traditional Gulf craft of plaiting mats and baskets from dried date-tree fronds.', a: 'Palm weaving', category: 'gcc', difficulty: 4, alt: ['Khoos', 'Safifah'] },
    { q: 'The 1981 founding-charter capital where the Gulf bloc of six states was established, the largest Emirati city by area.', a: 'Abu Dhabi', category: 'gcc', difficulty: 3 },
    { q: 'The shared regional ambition to move economies beyond crude oil into tourism, finance and industry.', a: 'Diversification', category: 'gcc', difficulty: 4 },
    { q: 'The state-owned investment vehicles, like Kuwait\'s and Qatar\'s, that channel oil money into global assets.', a: 'Sovereign wealth fund', category: 'gcc', difficulty: 4 },
    { q: 'The migrant labour force, largely from South Asia, that built the modern cities of the Gulf, the broad term for such overseas workers.', a: 'Expatriates', category: 'gcc', difficulty: 3, alt: ['Expats'] },
    { q: 'The flat coastal salt-crusted flat that whitens under the Gulf sun, common along Qatari and Emirati shores.', a: 'Sabkha', category: 'gcc', difficulty: 5 },
    { q: 'The mangrove-fringed tidal creek or lagoon along the Gulf coast, the Arabic word appearing in many place names.', a: 'Khor', category: 'gcc', difficulty: 4 },
    { q: 'The layered rice dish flipped onto a platter, topped with browned onions and lentils, often called "upside down".', a: 'Maqluba', category: 'gcc', difficulty: 4, alt: ['Maqlooba'] },
    { q: 'The crispy fried triangular pastry pockets filled with meat or cheese, popular at Ramadan iftar across the Gulf.', a: 'Sambousa', category: 'gcc', difficulty: 4, alt: ['Samosa', 'Sambusa'] },
    { q: 'The colloquial Bedouin verse tradition of the Gulf and Najd, recited at gatherings and festivals.', a: 'Nabati poetry', category: 'gcc', difficulty: 5, alt: ['Nabati'] },
    { q: 'The rhythmic seafaring work songs the old Gulf pearl divers chanted aboard their boats.', a: 'Fjiri', category: 'gcc', difficulty: 5, alt: ['Fidjeri'] },
    { q: 'The lively Gulf folk performance of swaying rows of men with sticks or swords, danced at weddings and national days.', a: 'Ardha', category: 'gcc', difficulty: 5, alt: ['Ardah', 'Al-Ardha'] },
    { q: 'The general term for the people, dialect and pop music of the Gulf coast, literally meaning "of the gulf".', a: 'Khaleeji', category: 'gcc', difficulty: 3, alt: ['Khaliji'] },
    { q: 'The decorative art of beautiful flowing handwriting that adorns Gulf mosques and manuscripts.', a: 'Calligraphy', category: 'gcc', difficulty: 3 },
    { q: 'The peace-wishing word that opens the standard Arabic greeting exchanged on meeting.', a: 'Salam', category: 'gcc', difficulty: 3, alt: ['Salaam', 'As-salamu alaykum'] },
    { q: 'The dietary standard marking food permissible under Islamic law, governing Gulf kitchens.', a: 'Halal', category: 'gcc', difficulty: 2 },
    { q: 'The category of food and conduct forbidden under Islamic law, the opposite of permitted.', a: 'Haram', category: 'gcc', difficulty: 3 },
    { q: 'The set of obligatory acts of Muslim faith — creed, prayer, alms, fasting and pilgrimage — that number a basic handful, observed across the Gulf.', a: 'Five Pillars', category: 'gcc', difficulty: 3 },
    { q: 'The daylight abstention from food and drink observed throughout the holy month.', a: 'Fasting', category: 'gcc', difficulty: 2, alt: ['Sawm'] },
    { q: 'The compiled sayings and deeds of the Prophet Muhammad, a key source of Islamic teaching.', a: 'Hadith', category: 'gcc', difficulty: 4 },
    { q: 'The body of Islamic law derived from the Quran and prophetic tradition, a legal foundation in Gulf states.', a: 'Sharia', category: 'gcc', difficulty: 3 },
    { q: 'The scholarly Islamic ruling or formal legal opinion issued by a qualified jurist.', a: 'Fatwa', category: 'gcc', difficulty: 4 },
    { q: 'The Muslim place of worship found in every Gulf town, where the faithful gather to pray.', a: 'Mosque', category: 'gcc', difficulty: 1, alt: ['Masjid'] },
    { q: 'The mystical, devotional strand of Islam emphasising inward seeking, present in some Gulf communities.', a: 'Sufism', category: 'gcc', difficulty: 4 },
    { q: 'The black goat-hair dwelling that sheltered nomadic desert families and could be packed onto camels.', a: 'Bedouin tent', category: 'gcc', difficulty: 4, alt: ['Bayt al-shaar', 'Goat-hair tent'] },
    { q: 'The breed of slender, swift hound the Bedouin prized for hunting gazelle in the desert.', a: 'Saluki', category: 'gcc', difficulty: 4 },
    { q: 'The wandering herder lifestyle of moving livestock between pastures, the way of life of the desert Bedouin.', a: 'Nomadism', category: 'gcc', difficulty: 4, alt: ['Nomadic life'] },
    { q: 'The southern Iraqi reed-channel marshes near the head of the Gulf, home to the Marsh Arabs.', a: 'Mesopotamian wetlands', category: 'gcc', difficulty: 5, alt: ['Ahwar', 'Iraqi marshes'] },
    { q: 'The chickpea-and-tahini, lemon and garlic dip is one mezze; the smoky aubergine version blended with tahini is this.', a: 'Baba ganoush', category: 'gcc', difficulty: 4, alt: ['Mutabbal'] },
    { q: 'The skewered grilled cubes of marinated lamb or chicken, the Omani and Gulf barbecue favourite over open coals.', a: 'Mishkak', category: 'gcc', difficulty: 5 },
    { q: 'The salted, sun-dried small fish, a pungent pantry staple of old Gulf coastal cooking.', a: 'Maleh', category: 'gcc', difficulty: 5, alt: ['Salted fish'] },
    { q: 'The fermented spongy flatbread of southern Arabia, leavened and griddle-baked full of holes, eaten with honey or stew.', a: 'Lahoh', category: 'gcc', difficulty: 5, alt: ['Lahooh'] },
    { q: 'The vast landmass between the Red Sea and the Gulf on which all six bloc states sit.', a: 'Arabian Peninsula', category: 'gcc', difficulty: 2 },
    { q: 'The royal title held by the ruler of Saudi Arabia, the only Gulf monarch with this rank.', a: 'King', category: 'gcc', difficulty: 2 },
    { q: 'The hereditary system of government, common to all six Gulf states, in which a royal family rules.', a: 'Monarchy', category: 'gcc', difficulty: 3 },
    { q: 'The consultative or parliamentary assembly that advises the ruler in several Gulf states, the Arabic word meaning "council".', a: 'Shura', category: 'gcc', difficulty: 4, alt: ['Majlis al-Shura'] },
    { q: 'The early Islamic ruling dynasty, based in Damascus, that first brought the faith\'s empire to the Gulf shores.', a: 'Umayyads', category: 'gcc', difficulty: 5, alt: ['Umayyad Caliphate'] },
    { q: 'The successor leader of the early Muslim community after the Prophet, the title held by Abu Bakr and Umar.', a: 'Caliph', category: 'gcc', difficulty: 4 },
    { q: 'The folded triangular pastry of flaky dough wrapped around minced meat or banana, a Gulf and South-East Asian street snack.', a: 'Murtabak', category: 'gcc', difficulty: 5, alt: ['Mutabbaq'] },
    { q: 'The thin saffron-and-cardamom drop pancakes eaten with date syrup or cheese at a Gulf breakfast.', a: 'Chebab', category: 'gcc', difficulty: 5 },
    { q: 'The sweet vermicelli-noodle dessert, fried crisp and bound with sugar and egg, served at Gulf celebrations.', a: 'Balaleet', category: 'gcc', difficulty: 5 },
    { q: 'The pilgrimage rite of walking seven times between the hills of Safa and Marwa near the Kaaba.', a: 'Saee', category: 'gcc', difficulty: 5, alt: ['Sai'] },
    { q: 'The vast region of dunes and gravel plains covering most of the peninsula, the great arid expanse of the interior.', a: 'Desert', category: 'gcc', difficulty: 1 },
    { q: 'The dried coconut-and-cardamom or rosewater puddings and sweets served with coffee at Gulf gatherings, the broad English word.', a: 'Dessert', category: 'gcc', difficulty: 2 },
  ],
};
