import type { RawPack } from '../core/packs';

export const historyEasyPack: RawPack = {
  id: 'history-easy',
  name: 'World History · Easy',
  description: 'Famous figures and major events of history that everyone knows.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '📜',
  accent: '#a16207',
  letters: {
    A: [
      { q: 'Macedonian king who conquered the Persian Empire and reached India by age 30.', a: 'Alexander the Great' },
      { q: 'The 16th US president, assassinated at Ford\'s Theatre in 1865.', a: 'Abraham Lincoln' },
      { q: 'The 1775–1783 colonial uprising against British rule that produced the thirteen states.', a: 'American Revolution' },
      { q: 'Tudor mother of Elizabeth I, second wife of Henry VIII, beheaded in 1536.', a: 'Anne Boleyn' },
      { q: 'The country invaded by the Soviets in 1979 and by NATO forces in 2001.', a: 'Afghanistan' },
      { q: 'The continent where ancient Egypt, Mali, and Carthage rose to power.', a: 'Africa' },
      { q: 'Pacific empire centered at Tenochtitlan, defeated by Cortés in 1521.', a: 'Aztec Empire' },
      { q: 'North African country that fought a brutal 1954–1962 war of independence from France.', a: 'Algeria' },
      { q: 'Greek city-state, birthplace of democracy and the Parthenon.', a: 'Athens' },
      { q: 'Country famous for kangaroos, colonized as a British penal settlement from 1788.', a: 'Australia' },
      { q: 'Greek philosopher, student of Plato and tutor to Alexander the Great.', a: 'Aristotle' },
      { q: 'Capital of Turkey since 1923, replacing Istanbul as the seat of government.', a: 'Ankara' },
    ],
    B: [
      { q: 'The 14th-century plague that killed roughly a third of Europe.', a: 'Black Death' },
      { q: 'East-West German concrete divider that fell in 1989.', a: 'Berlin Wall' },
      { q: 'The 1773 American colonial protest in which crates of leaves were dumped into a harbor.', a: 'Boston Tea Party' },
      { q: 'June 1944 Allied landings in northern France on a famous stretch of coast.', a: 'Beaches of Normandy' },
      { q: 'The 1815 clash in present-day Belgium where Napoleon was finally defeated.', a: 'Battle of Waterloo' },
      { q: 'Empire on which "the sun never sets," ruling India, Canada, Australia and more at its peak.', a: 'British Empire' },
      { q: 'Soviet-blockaded city saved by a massive 1948 Allied airlift.', a: 'Berlin' },
      { q: 'French general turned emperor in 1804, exiled to Elba and Saint Helena — his surname.', a: 'Bonaparte' },
      { q: 'Inventor of the telephone, born in Scotland — his surname.', a: 'Bell' },
      { q: 'Prison in Paris stormed on July 14, 1789.', a: 'Bastille' },
      { q: 'Russian communist revolutionaries who seized power in 1917.', a: 'Bolsheviks' },
      { q: 'Town in the West Bank traditionally regarded as the birthplace of Jesus.', a: 'Bethlehem' },
    ],
    C: [
      { q: 'The last active pharaoh of Egypt, lover of Mark Antony and Julius Caesar.', a: 'Cleopatra' },
      { q: 'Italian explorer who sailed for Spain in 1492 and reached the Caribbean.', a: 'Christopher Columbus' },
      { q: 'British prime minister who led the United Kingdom through the Second World War.', a: 'Churchill' },
      { q: 'The 1861–1865 American war between the Union and the Confederacy.', a: 'Civil War' },
      { q: 'The decades-long post-1945 standoff between the United States and the Soviet Union.', a: 'Cold War' },
      { q: 'Medieval religious military campaigns by European Christians to capture the Holy Land.', a: 'Crusades' },
      { q: 'Roman general who crossed the Rubicon in 49 BC and was murdered on the Ides of March.', a: 'Caesar' },
      { q: 'The 1962 missile crisis that nearly triggered nuclear war involved this Caribbean island.', a: 'Cuba' },
      { q: 'East Asian country whose first emperor unified it in 221 BC and began the famous wall.', a: 'China' },
      { q: 'Roman emperor who legalized Christianity with the Edict of Milan in 313 AD.', a: 'Constantine' },
      { q: 'Spaniard who toppled the Aztec capital in 1521 — surname.', a: 'Cortés' },
      { q: 'Polish astronomer who placed the Sun at the center of the universe — surname.', a: 'Copernicus' },
    ],
    D: [
      { q: 'June 6, 1944 — the Allied invasion of Normandy is known by this single-letter date.', a: 'D-Day' },
      { q: 'The 1776 American document that begins "We hold these truths to be self-evident".', a: 'Declaration of Independence' },
      { q: 'A reigning family line, such as the Tudors, Ming or Romanovs — generic name for such houses.', a: 'Dynasty' },
      { q: 'Florentine poet who wrote the Divine Comedy in the 14th century.', a: 'Dante' },
      { q: 'Persian king defeated by the Greeks at Marathon in 490 BC.', a: 'Darius' },
      { q: 'English navigator Francis who sailed around the world in 1577–1580 — surname.', a: 'Drake' },
      { q: 'Russian author of "Crime and Punishment" who lived under the czars — surname.', a: 'Dostoevsky' },
      { q: 'French port from which 1940 British forces were dramatically evacuated by sea.', a: 'Dunkirk' },
      { q: 'Long economic downturn of the 1930s that followed the 1929 Wall Street crash — "the Great ___".', a: 'Depression' },
    ],
    E: [
      { q: 'American inventor of the practical light bulb and phonograph.', a: 'Edison' },
      { q: 'Iconic Paris iron lattice landmark built for the 1889 World\'s Fair.', a: 'Eiffel Tower' },
      { q: 'German-born physicist famous for E = mc² and the theory of relativity.', a: 'Einstein' },
      { q: 'Long-reigning Tudor queen (1558–1603), daughter of Henry VIII.', a: 'Elizabeth I' },
      { q: 'Ancient North African civilization famous for pyramids, pharaohs and hieroglyphs.', a: 'Egypt' },
      { q: 'Five-star US Army general who led Allied forces on D-Day and later became 34th president.', a: 'Eisenhower' },
      { q: 'British queen who succeeded her father George VI in 1952 — her regnal name and number.', a: 'Elizabeth II' },
      { q: 'Continent that staged the Renaissance, the World Wars and the French Revolution.', a: 'Europe' },
      { q: 'Country whose capital is London, formed part of the United Kingdom in 1707.', a: 'England' },
      { q: 'Country invaded by Italy in 1935, only African nation to defeat European colonizers (at Adwa, 1896).', a: 'Ethiopia' },
    ],
    F: [
      { q: 'The 1789 uprising that ended the Bourbon monarchy and stormed the Bastille.', a: 'French Revolution' },
      { q: 'America\'s 32nd president, who led the nation through the Depression and most of WWII.', a: 'FDR' },
      { q: 'Spanish dictator who ruled the country from 1939 until his death in 1975.', a: 'Franco' },
      { q: 'Surname of the 1605 Gunpowder Plotter Guy who tried to blow up Parliament.', a: 'Fawkes' },
      { q: 'Italian Renaissance city of the Medici, home to Brunelleschi\'s Duomo.', a: 'Florence' },
      { q: 'Founding father and inventor who flew a kite in a thunderstorm — surname.', a: 'Franklin' },
      { q: 'Austrian archduke whose 1914 assassination at Sarajevo triggered the First World War.', a: 'Franz Ferdinand' },
      { q: 'Country whose 1789 revolution ended in the rise of Napoleon.', a: 'France' },
      { q: 'Roman public square that served as the heart of civic life in ancient Rome.', a: 'Forum' },
    ],
    G: [
      { q: 'Indian leader of non-violent resistance who helped end British rule in 1947.', a: 'Gandhi' },
      { q: 'Massive ancient stone defensive barrier visible from very high altitudes in East Asia.', a: 'Great Wall of China' },
      { q: 'Mongol founder who built the largest contiguous land empire in history in the 13th century.', a: 'Genghis Khan' },
      { q: 'German inventor of the movable-type printing press around 1440.', a: 'Gutenberg' },
      { q: 'The first US president, who led the Continental Army to victory.', a: 'George Washington' },
      { q: 'Soviet leader whose perestroika and glasnost helped end the Cold War.', a: 'Gorbachev' },
      { q: 'Italian astronomer who championed heliocentrism and was tried by the Inquisition.', a: 'Galileo' },
      { q: 'European country whose capital is Athens, the birthplace of democracy.', a: 'Greece' },
      { q: 'Egyptian plateau outside Cairo home to the famous pyramids and sphinx.', a: 'Giza' },
      { q: 'Argentine-Cuban revolutionary famously nicknamed Che — his surname.', a: 'Guevara' },
    ],
    H: [
      { q: 'Nazi dictator of Germany from 1933 to 1945.', a: 'Hitler' },
      { q: 'Tudor king famous for six wives and breaking from the Roman Catholic Church.', a: 'Henry VIII' },
      { q: 'Japanese city destroyed by the first wartime atomic bomb on August 6, 1945.', a: 'Hiroshima' },
      { q: 'Conflict between France and England from 1337 to 1453.', a: 'Hundred Years War' },
      { q: 'Carthaginian general who crossed the Alps with elephants to attack Rome.', a: 'Hannibal' },
      { q: 'The blind Greek poet credited with the Iliad and the Odyssey.', a: 'Homer' },
      { q: '1066 battle in southern England where William the Conqueror defeated King Harold.', a: 'Hastings' },
      { q: 'Persecution of European Jews by the Nazi regime during the Second World War.', a: 'Holocaust' },
      { q: 'Ancient Egyptian writing using pictographic symbols.', a: 'Hieroglyphs' },
    ],
    I: [
      { q: 'The 18th–19th-century shift from hand production to machines and factories.', a: 'Industrial Revolution' },
      { q: 'South American empire centered at Cusco, conquered by Pizarro in 1533.', a: 'Inca Empire' },
      { q: 'Catholic tribunal that tried Galileo and many "heretics" in medieval Spain.', a: 'Inquisition' },
      { q: 'Country that gained independence from Britain in 1947 under Mahatma Gandhi.', a: 'India' },
      { q: 'Metal Churchill named the symbolic Cold-War divider after — the "___ Curtain".', a: 'Iron' },
      { q: 'British physicist who described gravity after famously watching an apple fall.', a: 'Isaac Newton' },
      { q: 'Country in the Middle East founded as a Jewish state in 1948.', a: 'Israel' },
      { q: 'European peninsula shaped like a boot, home of the Roman Empire and the Renaissance.', a: 'Italy' },
      { q: 'Middle Eastern country, formerly Persia, ruled by ayatollahs since the 1979 revolution.', a: 'Iran' },
      { q: 'Middle Eastern country, ancient Mesopotamia, invaded by US-led forces in 2003.', a: 'Iraq' },
    ],
    J: [
      { q: 'French peasant girl who led armies in the Hundred Years\' War and was burned at the stake in 1431.', a: 'Joan of Arc' },
      { q: 'The 35th US president, assassinated in Dallas in 1963.', a: 'JFK' },
      { q: 'East Asian island nation that attacked Pearl Harbor on December 7, 1941.', a: 'Japan' },
      { q: 'British scientist who developed the smallpox vaccine in 1796 — surname.', a: 'Jenner' },
      { q: 'Christian founder born in Bethlehem around 4 BC, central figure of the New Testament.', a: 'Jesus' },
      { q: 'Roman general murdered in 44 BC — first name.', a: 'Julius' },
      { q: 'Holy city sacred to three major faiths, contested for millennia.', a: 'Jerusalem' },
      { q: 'Founder of Pakistan in 1947 — known as the Quaid-i-Azam, surname.', a: 'Jinnah' },
      { q: 'The 3rd US president and primary author of the Declaration of Independence.', a: 'Jefferson' },
    ],
    K: [
      { q: 'Soviet premier who clashed with JFK during the 1962 Cuban missile crisis.', a: 'Khrushchev' },
      { q: 'Long-reigning male monarch — generic title held by Henry VIII, Louis XIV and George III.', a: 'King' },
      { q: 'The 1950–1953 conflict between the communist North and the US-backed South of a peninsula.', a: 'Korean War' },
      { q: 'WWII Japanese suicide-pilot attacks against Allied ships.', a: 'Kamikaze' },
      { q: 'Founder of the Mongol-ruled Yuan dynasty of China; Marco Polo served at his court.', a: 'Kublai Khan' },
      { q: 'Site of the 1903 Wright Brothers powered flight, in North Carolina.', a: 'Kitty Hawk' },
      { q: 'German chancellor (1990–1998) who oversaw the reunification of Germany — surname.', a: 'Kohl' },
    ],
    L: [
      { q: 'Italian polymath who painted the Mona Lisa and The Last Supper.', a: 'Leonardo da Vinci' },
      { q: 'Russian revolutionary who founded the Soviet state in 1917.', a: 'Lenin' },
      { q: 'French king known as the Sun King, builder of Versailles.', a: 'Louis XIV' },
      { q: 'The 16th US president, assassinated in 1865 — surname.', a: 'Lincoln' },
      { q: 'German monk who in 1517 nailed 95 theses to a church door, starting the Reformation.', a: 'Luther' },
      { q: 'Capital of Portugal that flourished during the 15th-century Age of Exploration.', a: 'Lisbon' },
      { q: 'Capital of England and seat of Parliament.', a: 'London' },
      { q: 'French king beheaded with his queen during the 1789 Revolution — regnal name and number.', a: 'Louis XVI' },
      { q: 'Capital of Peru founded by Pizarro in 1535.', a: 'Lima' },
    ],
    M: [
      { q: 'South African leader imprisoned 27 years who became president in 1994.', a: 'Mandela' },
      { q: 'The 1215 charter of English liberties signed by King John at Runnymede.', a: 'Magna Carta' },
      { q: 'French queen executed by guillotine in 1793, wife of Louis XVI.', a: 'Marie Antoinette' },
      { q: 'Chinese communist leader who founded the People\'s Republic in 1949.', a: 'Mao Zedong' },
      { q: 'Pre-Columbian civilization of Central America famous for stepped pyramids and a calendar.', a: 'Maya' },
      { q: 'Italian explorer who traveled to the court of Kublai Khan — full name.', a: 'Marco Polo' },
      { q: 'American civil-rights leader famous for the "I Have a Dream" speech.', a: 'Martin Luther King' },
      { q: 'July 20, 1969 Apollo 11 event watched by millions — two-word phrase.', a: 'Moon landing' },
      { q: 'Italian fascist dictator overthrown in 1943.', a: 'Mussolini' },
      { q: 'Polish-French Nobel-winning scientist who discovered radium.', a: 'Marie Curie' },
      { q: 'Founder of Islam in the 7th century AD.', a: 'Muhammad' },
      { q: 'Battle of 490 BC where the Athenians defeated the Persians — a famous long-distance running event is named for it.', a: 'Marathon' },
    ],
    N: [
      { q: 'French emperor who lost the Battle of Waterloo and was exiled twice.', a: 'Napoleon' },
      { q: 'British admiral who died at Trafalgar in 1805, hero of the Royal Navy.', a: 'Nelson' },
      { q: 'Apollo 11 commander who said "one small step for man".', a: 'Neil Armstrong' },
      { q: 'Region of northwestern France famous for the 1944 D-Day beaches.', a: 'Normandy' },
      { q: 'Japanese city hit by the second atomic bomb on August 9, 1945.', a: 'Nagasaki' },
      { q: 'Last Russian czar, executed with his family by the Bolsheviks in 1918.', a: 'Nicholas II' },
      { q: 'Hitler\'s political party, in power in Germany from 1933 to 1945.', a: 'Nazis' },
      { q: 'Longest river of Africa, flowing through Egypt to the Mediterranean.', a: 'Nile' },
      { q: 'Scandinavian Viking-era kingdom whose capital is Oslo today.', a: 'Norway' },
    ],
    O: [
      { q: 'Vast Turkish-ruled empire that fell after the First World War.', a: 'Ottoman Empire' },
      { q: '1917 Russian revolution that brought the Bolsheviks to power — named for this month.', a: 'October Revolution' },
      { q: 'Roman emperor and adopted heir of Julius Caesar, first ruler of the empire.', a: 'Octavian' },
      { q: 'Worldwide athletic games held every four years, revived in 1896 in Athens.', a: 'Olympics' },
      { q: 'Capital of Norway, capital from 1814 onward.', a: 'Oslo' },
      { q: 'American physicist who led the Manhattan Project to develop the atomic bomb.', a: 'Oppenheimer' },
    ],
    P: [
      { q: 'December 7, 1941 surprise Japanese attack on a Hawaiian naval base.', a: 'Pearl Harbor' },
      { q: 'Russian czar who founded Saint Petersburg in 1703 and modernized his country — full title.', a: 'Peter the Great' },
      { q: 'Massive triangular Egyptian tombs built for ancient pharaohs.', a: 'Pyramids of Giza' },
      { q: 'Spaniard who conquered the Inca Empire — his surname.', a: 'Pizarro' },
      { q: 'Italian city buried by Vesuvius in 79 AD and rediscovered centuries later.', a: 'Pompeii' },
      { q: 'Eastern European country whose 1939 invasion by Hitler started WWII.', a: 'Poland' },
      { q: 'Greek philosopher, student of Socrates and teacher of Aristotle.', a: 'Plato' },
      { q: 'Iberian country whose explorers, like Vasco da Gama, opened a sea route to India.', a: 'Portugal' },
      { q: 'Capital of France and site of the 1789 storming of the Bastille.', a: 'Paris' },
      { q: 'Title of the head of the Roman Catholic Church, based at the Vatican.', a: 'Pope' },
      { q: 'South Asian country split from India in 1947 to become a Muslim-majority state.', a: 'Pakistan' },
    ],
    Q: [
      { q: 'Long-reigning female monarch — title held by Victoria, Elizabeth I and Elizabeth II.', a: 'Queen' },
      { q: 'Britain\'s longest-reigning 19th-century monarch, an empress of India.', a: 'Queen Victoria' },
      { q: 'Province of eastern Canada whose major city is Montreal — its French-speaking name.', a: 'Quebec' },
    ],
    R: [
      { q: 'Ancient civilization centered on a Mediterranean city famous for the Colosseum.', a: 'Roman Empire' },
      { q: 'European cultural rebirth that began in 14th-century Italy.', a: 'Renaissance' },
      { q: 'The 1917 uprising that ended the Romanov dynasty and brought the Bolsheviks to power.', a: 'Russian Revolution' },
      { q: 'Largest country by area, ruled by Putin since the early 2000s.', a: 'Russia' },
      { q: 'Confederate general who surrendered at Appomattox Court House in 1865 — full name.', a: 'Robert E Lee' },
      { q: 'Italian capital, heart of an ancient empire.', a: 'Rome' },
      { q: 'Royal family of Russia, overthrown in 1917 — dynasty name.', a: 'Romanov' },
      { q: 'Former British colony in Africa, renamed Zimbabwe at independence in 1980.', a: 'Rhodesia' },
      { q: 'Ronald, the 40th US president (1981–1989), former Hollywood actor — surname.', a: 'Reagan' },
    ],
    S: [
      { q: 'Soviet dictator who led the USSR through World War II.', a: 'Stalin' },
      { q: 'Iconic copper-clad gift from France to the United States, dedicated in 1886 in New York harbor.', a: 'Statue of Liberty' },
      { q: 'Iberian country that built a vast empire in the Americas after 1492.', a: 'Spain' },
      { q: 'Sea route through Egypt opened in 1869 connecting the Mediterranean to the Red Sea.', a: 'Suez Canal' },
      { q: 'Ancient Greek philosopher executed by drinking hemlock for "corrupting the youth".', a: 'Socrates' },
      { q: 'Bosnian city where Archduke Franz Ferdinand was assassinated in 1914.', a: 'Sarajevo' },
      { q: 'WWII city in western Russia where Soviets defeated the Germans in a 1942–43 siege.', a: 'Stalingrad' },
      { q: 'Egyptian colossal monument outside Cairo with a lion\'s body and human head.', a: 'Sphinx' },
      { q: 'Ancient Greek warrior city-state, rival of Athens, famous for its 300 at Thermopylae.', a: 'Sparta' },
      { q: 'British playwright known for Hamlet, Romeo and Juliet, Macbeth — surname.', a: 'Shakespeare' },
      { q: 'Massachusetts town infamous for 1692 witch trials.', a: 'Salem' },
    ],
    T: [
      { q: 'Indian marble mausoleum built by Shah Jahan for his wife in the 17th century.', a: 'Taj Mahal' },
      { q: 'The 1919 peace agreement that formally ended the First World War, signed near Paris.', a: 'Treaty of Versailles' },
      { q: 'Serbian-American electrical engineer who developed alternating current.', a: 'Tesla' },
      { q: 'The 33rd US president, who authorized dropping atomic bombs on Japan.', a: 'Truman' },
      { q: 'Aztec capital city, founded on a lake and destroyed by Cortés in 1521.', a: 'Tenochtitlan' },
      { q: 'Iconic central-Italian region named after an ancient pre-Roman people.', a: 'Tuscany' },
      { q: 'Title held by Russian emperors before the 1917 revolution — single short word.', a: 'Tsar' },
      { q: 'British prime minister of the 1980s known as the Iron Lady — surname.', a: 'Thatcher' },
      { q: 'Famous central Beijing plaza where 1989 pro-democracy protests were crushed by the army.', a: 'Tiananmen Square' },
      { q: '1805 naval battle off Spain where Nelson defeated the French and Spanish fleets.', a: 'Trafalgar' },
    ],
    U: [
      { q: 'Former federation led by Russia that broke apart in 1991 — abbreviation.', a: 'USSR' },
      { q: 'Global peace-keeping body headquartered in New York City, founded after WWII.', a: 'United Nations' },
      { q: 'North American country formed by the 1776 declaration and the 1787 constitution.', a: 'United States' },
      { q: 'Island nation formed in 1801 by the union of Great Britain and Ireland.', a: 'United Kingdom' },
      { q: 'Eastern European country whose Crimea was annexed by Russia in 2014.', a: 'Ukraine' },
    ],
    V: [
      { q: 'Palace and gardens outside Paris built by Louis XIV; site of the 1919 treaty.', a: 'Versailles' },
      { q: 'The 1955–1975 conflict in Southeast Asia between the communist North and the US-backed South.', a: 'Vietnam War' },
      { q: 'The 1945 Allied celebration when Germany surrendered — its abbreviation.', a: 'VE Day' },
      { q: 'Sovereign seat of the Roman Catholic pope in Rome.', a: 'Vatican' },
      { q: 'Italian volcano that erupted in 79 AD, burying Pompeii.', a: 'Vesuvius' },
      { q: 'Italian explorer for whom America is named — Amerigo ___.', a: 'Vespucci' },
      { q: 'Norse seafarers who raided and traded across Europe from the 8th to 11th century.', a: 'Vikings' },
      { q: '1945 holiday marking Allied triumph in the Pacific against Japan — abbreviation.', a: 'VJ Day' },
    ],
    W: [
      { q: 'Father of his country and the first president of the United States.', a: 'Washington' },
      { q: 'Belgian battlefield where Napoleon met his final defeat in June 1815.', a: 'Waterloo' },
      { q: 'The 1914–1918 global conflict triggered by the assassination of Franz Ferdinand.', a: 'World War One' },
      { q: 'The 1939–1945 global conflict involving the Allies and the Axis powers.', a: 'World War Two' },
      { q: 'Orville and Wilbur, the Ohio aviation pioneers of 1903 Kitty Hawk fame — their family name plus a fraternal noun.', a: 'Wright Brothers' },
      { q: 'Norman invader who became king of England after Hastings in 1066 — full epithet.', a: 'William the Conqueror' },
      { q: 'British wartime prime minister famed for "blood, toil, tears and sweat" — full name.', a: 'Winston Churchill' },
    ],
    X: [
      { q: 'Persian king who invaded Greece in 480 BC and was defeated at Salamis.', a: 'Xerxes' },
      { q: 'Chinese city near the famous terracotta army of the first emperor — ancient capital, eastern end of the Silk Road.', a: 'Xian' },
    ],
    Y: [
      { q: 'February 1945 Crimean meeting of Roosevelt, Churchill and Stalin to plan Europe\'s post-war order.', a: 'Yalta Conference' },
      { q: 'Slavic Balkan federation that broke apart violently in the 1990s.', a: 'Yugoslavia' },
      { q: 'Mongol-ruled imperial Chinese dynasty founded by Kublai Khan in 1271.', a: 'Yuan Dynasty' },
    ],
    Z: [
      { q: 'Bantu kingdom led by Shaka in 19th-century southern Africa.', a: 'Zulu Kingdom' },
      { q: 'Southern African country renamed at independence in 1980, formerly Southern Rhodesia.', a: 'Zimbabwe' },
    ],
  },
};
