import type { RawPack } from '../core/packs';

export const historyMediumPack: RawPack = {
  id: 'history-medium',
  name: 'World History · Medium',
  description: 'Battles, dynasties and turning points — deeper history facts.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🏛️',
  accent: '#854d0e',
  letters: {
    A: [
      { q: 'This 1415 battle in northern France saw English longbowmen under Henry V crush a much larger French army.', a: 'Agincourt', category: 'battles' },
      { q: 'This South African policy of enforced racial segregation, formally introduced in 1948, was dismantled in the early 1990s.', a: 'Apartheid', category: 'modern' },
      { q: 'This Indian Maurya emperor converted to Buddhism after the bloody Kalinga war and spread its teachings across Asia.', a: 'Ashoka', category: 'ancient' },
      { q: 'This 1918 ceasefire that ended the First World War took effect at the eleventh hour of the eleventh day of the eleventh month.', a: 'Armistice', category: 'wars' },
      { q: 'This Macedonian king toppled the Persian Empire after victories at Issus and Gaugamela.', a: 'Alexander the Great', category: 'ancient' },
      { q: 'This Sumerian king of legend, hero of the world\'s oldest surviving epic, ruled the city of Uruk.', a: 'Gilgamesh', category: 'ancient' },
      { q: 'This Hunnic king, nicknamed the Scourge of God, threatened Rome in the mid-5th century AD.', a: 'Attila', category: 'ancient' },
      { q: 'This Ethiopian kingdom centred on its namesake city was among the first states to officially adopt Christianity, in the 4th century.', a: 'Aksum', category: 'ancient', alt: ['Aksumite Empire', 'Axum'] },
      { q: 'This Islamic dynasty, founded in 750 after overthrowing the Umayyads, ruled from Baghdad through the Islamic Golden Age.', a: 'Abbasid Caliphate', category: 'medieval', alt: ['Abbasids'] },
      { q: 'This Persian dynasty founded by Cyrus the Great in the 6th century BC was the first Persian empire.', a: 'Achaemenid Empire', category: 'ancient', alt: ['Achaemenids'] },
    ],
    B: [
      { q: 'This Iron Chancellor unified Germany under Prussian leadership through wars with Denmark, Austria and France.', a: 'Bismarck', category: 'leaders' },
      { q: 'This 1940–41 nightly German aerial bombing of British cities, especially London, failed to break civilian morale.', a: 'The Blitz', category: 'wars', alt: ['Blitz'] },
      { q: 'This Venezuelan-born general, called El Libertador, led the wars of independence across much of South America.', a: 'Simón Bolívar', category: 'revolutions', alt: ['Bolivar', 'Simon Bolivar'] },
      { q: 'This 14th-century pandemic, peaking in 1347–1351, killed roughly a third of Europe.', a: 'Black Death', category: 'medieval' },
      { q: 'This 1346 battle saw English longbowmen devastate the French cavalry on a hill in northern France.', a: 'Battle of Crécy', category: 'battles', alt: ['Crécy', 'Crecy'] },
      { q: 'This 1898 conflict, sparked partly by the sinking of the USS Maine in Havana harbour, ended European colonial rule over Cuba and the Philippines.', a: 'Spanish–American War', category: 'wars', alt: ['Spanish American War'] },
      { q: 'This 1066 clash on a southern English ridge saw William of Normandy defeat the Saxon king Harold.', a: 'Battle of Hastings', category: 'battles', alt: ['Hastings'] },
      { q: 'This 1961 CIA-backed invasion of Cuba by exiles ended in humiliating defeat for the Kennedy administration.', a: 'Bay of Pigs', category: 'modern' },
      { q: 'This 1955–56 black-led protest against segregated public transport in Alabama lasted 381 days.', a: 'Montgomery Bus Boycott', category: 'modern', alt: ['Bus Boycott'] },
      { q: 'This empire that survived the fall of Rome\'s western half ruled from its capital on the Bosphorus for over a thousand years.', a: 'Byzantine Empire', category: 'medieval', alt: ['Byzantium'] },
      { q: 'This European royal house ruled France from 1589 and produced kings of Spain still reigning today.', a: 'Bourbon dynasty', category: 'leaders', alt: ['Bourbons', 'House of Bourbon'] },
    ],
    C: [
      { q: 'This Frankish king crowned Emperor of the Romans on Christmas Day 800 forged a vast empire across western Europe.', a: 'Charlemagne', category: 'medieval' },
      { q: 'This 1962 13-day standoff between the United States and the Soviet Union over nuclear weapons on a Caribbean island brought the world to the brink of war.', a: 'Cuban Missile Crisis', category: 'modern' },
      { q: 'This Russian empress, born a German princess, reigned 1762–1796 and expanded her empire dramatically.', a: 'Catherine the Great', category: 'leaders' },
      { q: 'This Spanish conquistador overthrew the Aztec Empire between 1519 and 1521.', a: 'Hernán Cortés', category: 'explorers', alt: ['Cortés', 'Cortes', 'Hernan Cortes'] },
      { q: 'This English Lord Protector ruled the Commonwealth after the execution of Charles I in 1649.', a: 'Oliver Cromwell', category: 'leaders', alt: ['Cromwell'] },
      { q: 'This 325 AD church meeting, convened by Constantine, produced the foundational Christian creed.', a: 'Council of Nicaea', category: 'religious', alt: ['First Council of Nicaea'] },
      { q: 'This 1545–63 Catholic reform meeting in northern Italy launched the Counter-Reformation in response to Protestantism.', a: 'Council of Trent', category: 'religious' },
      { q: 'This dynasty unified China for the first time in 221 BC under its first emperor, standardising script and measures.', a: 'Qin dynasty', category: 'ancient', alt: ['Qin Dynasty'] },
      { q: 'This decades-long post-1945 geopolitical rivalry between the United States and the Soviet Union never erupted into direct armed conflict between them.', a: 'Cold War', category: 'modern' },
      { q: 'This Persian king founded the Achaemenid Empire around 550 BC and issued a famous cylinder seen as an early charter of tolerance.', a: 'Cyrus the Great', category: 'ancient' },
      { q: 'This Byzantine capital fell to Mehmed II\'s Ottoman army on 29 May 1453, ending the Eastern Roman Empire.', a: 'Constantinople', category: 'medieval' },
    ],
    D: [
      { q: 'This 1944 Allied amphibious landing in Normandy on 6 June was the largest seaborne invasion in history.', a: 'D-Day', category: 'wars' },
      { q: 'This 1954 battle in a Vietnamese valley decisively ended French colonial rule in Indochina.', a: 'Dien Bien Phu', category: 'wars' },
      { q: 'This 1940 evacuation lifted over 330,000 Allied troops from a French Channel port under German air attack.', a: 'Dunkirk', category: 'wars' },
      { q: 'This Roman emperor introduced the Tetrarchy in 293 AD, splitting imperial authority among four rulers.', a: 'Diocletian', category: 'ancient' },
      { q: 'This Persian king launched the first invasion of Greece in 490 BC, repelled at the Battle of Marathon.', a: 'Darius I', category: 'ancient', alt: ['Darius the Great'] },
      { q: 'This Muslim dynasty ruled most of northern India from 1206 to 1526 and successfully repelled Mongol invasions from its capital in the north.', a: 'Delhi Sultanate', category: 'medieval' },
      { q: 'This 1936–1939 conflict on the Iberian peninsula, a proving ground for German and Italian fascists, ended with Franco taking power.', a: 'Spanish Civil War', category: 'wars' },
      { q: 'This English sea captain completed the second circumnavigation of the globe between 1577 and 1580.', a: 'Francis Drake', category: 'explorers', alt: ['Drake', 'Sir Francis Drake'] },
    ],
    E: [
      { q: 'This 313 AD proclamation by Emperor Constantine guaranteed religious tolerance and effectively legalised Christianity across the Roman Empire.', a: 'Edict of Milan', category: 'ancient' },
      { q: 'This 1642–1651 conflict between Crown and Parliament ended with the execution of King Charles I.', a: 'English Civil War', category: 'wars' },
      { q: 'This 1916 armed insurrection in Dublin against British rule, swiftly suppressed but its leaders executed, ignited Irish independence.', a: 'Easter Rising', category: 'modern' },
      { q: 'This Spanish navigator completed the first circumnavigation of the globe in 1522 after Magellan died in the Philippines.', a: 'Juan Sebastián Elcano', category: 'explorers', alt: ['Elcano', 'Juan Sebastian Elcano'] },
      { q: 'This 18th-Dynasty pharaoh briefly converted Egypt to worship of the sun-disc Aten and built a new capital at Amarna.', a: 'Akhenaten', category: 'ancient' },
      { q: 'This Tudor queen reigned 44 years, presided over the defeat of the Spanish Armada and gave her name to a literary era.', a: 'Elizabeth I', category: 'leaders' },
      { q: 'This 1863 presidential order by Abraham Lincoln declared enslaved people in Confederate states to be free.', a: 'Emancipation Proclamation', category: 'modern' },
    ],
    F: [
      { q: 'This Spanish generalísimo ruled as dictator from his 1939 civil war victory until his death in 1975.', a: 'Francisco Franco', category: 'leaders', alt: ['Franco'] },
      { q: 'This king of Prussia 1740–1786, a brilliant military commander and patron of the Enlightenment, doubled his kingdom\'s territory.', a: 'Frederick the Great', category: 'leaders' },
      { q: 'This Shia Islamic dynasty, founded in 909, ruled North Africa and Egypt and built Cairo as its capital.', a: 'Fatimid Caliphate', category: 'medieval', alt: ['Fatimids'] },
      { q: 'This Portuguese prince sponsored 15th-century voyages down the African coast that opened the Age of Exploration.', a: 'Henry the Navigator', category: 'explorers' },
      { q: 'This 1789 storming of a Paris fortress-prison on 14 July is now the national day of France.', a: 'Bastille Day', category: 'revolutions' },
      { q: 'This Indian leader led the nonviolent civil disobedience that won independence from British rule in 1947.', a: 'Mahatma Gandhi', category: 'modern', alt: ['Gandhi'] },
    ],
    G: [
      { q: 'This Italian revolutionary led the Redshirts and the Expedition of the Thousand that helped unify Italy in 1860.', a: 'Giuseppe Garibaldi', category: 'revolutions', alt: ['Garibaldi'] },
      { q: 'This 1915–16 Allied campaign against Ottoman Turkey on a Turkish peninsula was a disastrous failure.', a: 'Gallipoli', category: 'wars' },
      { q: 'This July 1863 three-day Civil War battle in Pennsylvania marked the high tide of the Confederacy.', a: 'Gettysburg', category: 'battles', alt: ['Battle of Gettysburg'] },
      { q: 'This 1054 mutual excommunication permanently divided the Christian church into Catholic and Orthodox branches.', a: 'Great Schism', category: 'religious', alt: ['East–West Schism', 'East-West Schism'] },
      { q: 'This Indian dynasty (c. 320–550 AD) presided over a golden age of mathematics, art and the decimal numeral system.', a: 'Gupta Empire', category: 'ancient', alt: ['Guptas'] },
      { q: 'This 1648 settlement ended the Thirty Years\' War and laid the foundation of the modern sovereign state system in Europe.', a: 'Peace of Westphalia', category: 'treaties', alt: ['Treaty of Westphalia', 'Westphalia'] },
      { q: 'This Portuguese explorer reached India by sea around the Cape of Good Hope in 1498.', a: 'Vasco da Gama', category: 'explorers', alt: ['da Gama'] },
    ],
    H: [
      { q: 'This European dynasty, originating in a Swiss castle, ruled Austria, Spain and the Holy Roman Empire for centuries.', a: 'Habsburg dynasty', category: 'leaders', alt: ['Habsburgs', 'House of Habsburg'] },
      { q: 'This 1791–1804 slave revolt produced the first independent state in Latin America and the only successful slave-led revolution.', a: 'Haitian Revolution', category: 'revolutions' },
      { q: 'This central-European multinational realm dissolved by Napoleon in 1806 was famously described by Voltaire as being neither sacred, nor Latin, nor imperial.', a: 'Holy Roman Empire', category: 'medieval' },
      { q: 'This ancient Anatolian people built an empire that rivalled Egypt and fought the Battle of Kadesh in the 13th century BC.', a: 'Hittites', category: 'ancient', alt: ['Hittite Empire'] },
      { q: 'This 1346 Black Death epidemic shares its name with this code-naming Carthaginian general who crossed the Alps with elephants in 218 BC.', a: 'Hannibal', category: 'ancient' },
      { q: 'This dynasty ruled China for over four centuries from 202 BC and gives its name to the ethnic majority.', a: 'Han dynasty', category: 'ancient', alt: ['Han Dynasty'] },
      { q: 'This 1945 American atomic bombing of a Japanese city on 6 August killed about 140,000 people.', a: 'Hiroshima', category: 'wars' },
    ],
    I: [
      { q: 'This 1979 popular uprising overthrew the Shah and established a Shia clerical republic under Ayatollah Khomeini.', a: 'Iranian Revolution', category: 'revolutions' },
      { q: 'This 1945 month-long battle for a small volcanic Pacific island produced the iconic flag-raising photograph.', a: 'Iwo Jima', category: 'wars', alt: ['Battle of Iwo Jima'] },
      { q: 'This Spanish queen, who together with her husband Ferdinand financed Columbus\'s first voyage, completed the Reconquista in 1492.', a: 'Isabella I', category: 'leaders', alt: ['Isabella of Castile'] },
      { q: 'This Churchill phrase, coined in a 1946 Missouri speech, described the postwar divide across Europe.', a: 'Iron Curtain', category: 'modern' },
      { q: 'This 1857 uprising of sepoys against the British East India Company prompted the Crown to take direct control of the subcontinent.', a: 'Indian Rebellion', category: 'modern', alt: ['Sepoy Mutiny', 'Indian Mutiny'] },
    ],
    J: [
      { q: 'This Byzantine emperor, reigning 527–565, reconquered much of the western Mediterranean and codified Roman law.', a: 'Justinian', category: 'medieval', alt: ['Justinian I'] },
      { q: 'This French peasant girl led armies against the English in the Hundred Years\' War before being burned at the stake in 1431.', a: 'Joan of Arc', category: 'medieval' },
      { q: 'This Roman general and dictator was assassinated by senators on the Ides of March, 44 BC.', a: 'Julius Caesar', category: 'ancient' },
      { q: 'This royal house ruled Sweden and was founded by one of Napoleon\'s marshals — give the marshal\'s name.', a: 'Jean-Baptiste Bernadotte', category: 'leaders', alt: ['Bernadotte', 'Charles XIV John'] },
    ],
    K: [
      { q: 'This July 1943 clash between German and Soviet forces was the largest tank battle in history.', a: 'Kursk', category: 'battles', alt: ['Battle of Kursk'] },
      { q: 'This Mongol conqueror, grandson of the steppe unifier Temüjin, founded the Yuan dynasty that ruled China from 1271.', a: 'Kublai Khan', category: 'medieval' },
      { q: 'This 1950–53 Cold War conflict on a divided Asian peninsula ended in an armistice rather than a peace treaty.', a: 'Korean War', category: 'wars' },
      { q: 'This Mongol founder united the steppe tribes and launched the conquests that built history\'s largest contiguous empire.', a: 'Genghis Khan', category: 'medieval', alt: ['Chinggis Khan'] },
    ],
    L: [
      { q: 'This 1571 naval battle off western Greece saw a Holy League fleet crush the Ottoman navy.', a: 'Lepanto', category: 'battles', alt: ['Battle of Lepanto'] },
      { q: 'This German monk\'s 1517 challenge to Catholic indulgences sparked the Protestant Reformation.', a: 'Martin Luther', category: 'religious' },
      { q: 'This 1781 Virginia siege saw a combined American and French force compel General Cornwallis to surrender to George Washington.', a: 'Yorktown', category: 'battles', alt: ['Siege of Yorktown'] },
      { q: 'This South African anti-apartheid leader was imprisoned for 27 years before becoming the country\'s first democratically elected president.', a: 'Nelson Mandela', category: 'modern', alt: ['Mandela'] },
    ],
    M: [
      { q: 'This 1815 battle in present-day Belgium ended Napoleon\'s Hundred Days and his rule.', a: 'Waterloo', category: 'battles', alt: ['Battle of Waterloo'] },
      { q: 'This 1942 Pacific naval battle near a small atoll turned the tide of the war against Japan.', a: 'Midway', category: 'battles', alt: ['Battle of Midway'] },
      { q: 'This 490 BC battle saw an outnumbered Athenian army defeat a Persian invasion on a coastal plain.', a: 'Marathon', category: 'battles', alt: ['Battle of Marathon'] },
      { q: 'This 1938 four-power conference let Nazi Germany annex the Sudetenland in return for a worthless promise of peace.', a: 'Munich Agreement', category: 'treaties' },
      { q: 'This 1948 US programme of economic aid rebuilt Western Europe after the Second World War.', a: 'Marshall Plan', category: 'modern' },
      { q: 'This Italian explorer\'s 13th-century travels in Asia were recounted in a famous book dictated while he was a prisoner in Genoa.', a: 'Marco Polo', category: 'explorers' },
      { q: 'This 1453 fall of the Eastern Roman capital is often used to mark the end of which medieval era — answer the era.', a: 'Middle Ages', category: 'medieval', alt: ['Medieval period'] },
      { q: 'This Indian Muslim dynasty founded by Babur in 1526 ruled most of the subcontinent until the British era.', a: 'Mughal Empire', category: 'medieval', alt: ['Mughals'] },
      { q: 'This dynasty ruled China 1368–1644 and built the surviving northern walls and the Forbidden City.', a: 'Ming dynasty', category: 'medieval', alt: ['Ming Dynasty'] },
      { q: 'This West African empire, ruled in the 14th century by the fabulously wealthy Mansa Musa, was centred on Timbuktu.', a: 'Mali Empire', category: 'medieval', alt: ['Mali'] },
      { q: 'This Cretan Bronze Age civilisation, named after a legendary king, flourished around the palace at Knossos.', a: 'Minoans', category: 'ancient', alt: ['Minoan civilisation', 'Minoan civilization'] },
      { q: 'This Indian dynasty founded by Chandragupta around 322 BC reached its greatest extent under his grandson Ashoka.', a: 'Maurya Empire', category: 'ancient', alt: ['Mauryan Empire'] },
    ],
    N: [
      { q: 'This 325 AD ecumenical gathering convened by Constantine produced the foundational Christian creed.', a: 'Nicaea', category: 'religious', alt: ['First Council of Nicaea'] },
      { q: 'This 1805 naval battle off the coast of Spain saw Admiral Nelson destroy a Franco-Spanish fleet.', a: 'Trafalgar', category: 'battles', alt: ['Battle of Trafalgar'] },
      { q: 'This Babylonian king destroyed the First Temple in Jerusalem in 587 BC and is traditionally credited with the Hanging Gardens.', a: 'Nebuchadnezzar II', category: 'ancient', alt: ['Nebuchadnezzar'] },
      { q: 'This 1517 act in Wittenberg by Martin Luther is conventionally seen as the start of the Reformation.', a: 'Ninety-Five Theses', category: 'religious', alt: ['95 Theses', 'Ninety Five Theses'] },
      { q: 'This 1955–75 conflict, fought to prevent communist unification of an Asian country, became the longest US war of the 20th century.', a: 'Vietnam War', category: 'wars' },
    ],
    O: [
      { q: 'This Turkish-Islamic empire founded around 1299 reached its peak under Suleiman the Magnificent in the 16th century.', a: 'Ottoman Empire', category: 'medieval', alt: ['Ottomans'] },
      { q: 'This 1917 takeover of Petrograd by Lenin\'s Bolsheviks toppled Russia\'s short-lived provisional government.', a: 'October Revolution', category: 'revolutions' },
      { q: 'This Roman, named Gaius Octavius at birth, defeated Mark Antony at Actium in 31 BC and became Rome\'s first emperor.', a: 'Augustus', category: 'ancient', alt: ['Octavian'] },
    ],
    P: [
      { q: 'This Russian tsar, reigning 1682–1725, dragged his country toward Europe and built a new capital on the Baltic.', a: 'Peter the Great', category: 'leaders' },
      { q: 'This Chilean general led a 1973 military coup and ruled as dictator until 1990.', a: 'Augusto Pinochet', category: 'leaders', alt: ['Pinochet'] },
      { q: 'This Spanish conquistador overthrew the Inca Empire in the 1530s.', a: 'Francisco Pizarro', category: 'explorers', alt: ['Pizarro'] },
      { q: 'This ancient seafaring Levantine people gave the Mediterranean their alphabet and the city of Carthage.', a: 'Phoenicians', category: 'ancient' },
      { q: 'This Iranian dynasty (247 BC–224 AD) repeatedly fought Rome over Mesopotamia and Armenia.', a: 'Parthian Empire', category: 'ancient', alt: ['Parthians'] },
      { q: 'This English royal house ruled from 1154 to 1485 and produced kings such as Henry II and Richard the Lionheart.', a: 'Plantagenet dynasty', category: 'medieval', alt: ['Plantagenets', 'House of Plantagenet'] },
      { q: 'This 264–146 BC series of three conflicts between Rome and Carthage ended with the total destruction of the latter.', a: 'Punic Wars', category: 'ancient' },
    ],
    Q: [
      { q: 'This final imperial dynasty of China, founded by the Manchus, ruled from 1644 until its overthrow in 1911.', a: 'Qing dynasty', category: 'medieval', alt: ['Qing Dynasty', "Ch'ing"] },
      { q: 'This Tudor queen, Henry VIII\'s elder daughter, earned a grim nickname for burning Protestants during her reign.', a: 'Mary I', category: 'leaders', alt: ['Mary Tudor', 'Bloody Mary'] },
    ],
    R: [
      { q: 'This Russian dynasty ruled from 1613 until its overthrow in the 1917 revolution.', a: 'Romanov dynasty', category: 'leaders', alt: ['Romanovs', 'House of Romanov'] },
      { q: 'This 16th-century religious movement, sparked by Martin Luther, split Western Christianity into Catholic and Protestant.', a: 'Reformation', category: 'religious', alt: ['Protestant Reformation'] },
      { q: 'This French revolutionary lawyer dominated the 1793–94 Reign of Terror before being guillotined himself.', a: 'Maximilien Robespierre', category: 'revolutions', alt: ['Robespierre'] },
      { q: 'This 1994 mass killing in Central Africa saw Hutu extremists murder around 800,000 Tutsi and moderate Hutu in about 100 days.', a: 'Rwandan Genocide', category: 'modern' },
      { q: 'This 1789–99 upheaval, ignited by the storming of the Bastille, abolished the Bourbon monarchy and ended with the rise of Napoleon.', a: 'French Revolution', category: 'revolutions' },
    ],
    S: [
      { q: 'This Kurdish-Muslim sultan recaptured Jerusalem from the Crusaders at the Battle of Hattin in 1187.', a: 'Saladin', category: 'medieval' },
      { q: 'This 1942–43 Soviet defence of a city on the Volga ended in the encirclement and surrender of an entire German army.', a: 'Stalingrad', category: 'battles', alt: ['Battle of Stalingrad'] },
      { q: 'This Ottoman sultan, reigning 1520–1566, took his empire to its greatest extent and besieged Vienna in 1529.', a: 'Suleiman the Magnificent', category: 'leaders' },
      { q: 'This Persian dynasty (224–651 AD) succeeded the Parthians and was the last pre-Islamic Iranian empire.', a: 'Sasanian Empire', category: 'ancient', alt: ['Sassanid Empire', 'Sassanid'] },
      { q: 'This West African empire ruled the Niger Bend in the 15th and 16th centuries, with its capital at Gao.', a: 'Songhai Empire', category: 'medieval', alt: ['Songhai'] },
      { q: 'This Polish trade union, founded in 1980 under Lech Wałęsa, became the first non-communist union in the Eastern Bloc.', a: 'Solidarity', category: 'modern' },
      { q: 'This 1916 five-month battle on a French river produced over a million casualties, including 57,000 British on the first day.', a: 'Somme', category: 'battles', alt: ['Battle of the Somme'] },
      { q: 'This Mesopotamian people of the 4th millennium BC produced the earliest known cities and writing.', a: 'Sumerians', category: 'ancient', alt: ['Sumer'] },
      { q: 'This Portuguese dictator, ruling 1932–1968, built the Estado Novo and clung to Portugal\'s African colonies.', a: 'António de Oliveira Salazar', category: 'leaders', alt: ['Salazar'] },
      { q: 'This 480 BC sea battle in a narrow strait saw the outnumbered Greek fleet crush the Persian navy of Xerxes.', a: 'Salamis', category: 'battles', alt: ['Battle of Salamis'] },
      { q: 'This Chinese dynasty (960–1279) is famed for inventing paper money, gunpowder weapons and movable-type printing.', a: 'Song dynasty', category: 'medieval', alt: ['Song Dynasty'] },
    ],
    T: [
      { q: 'This 1494 papal-brokered treaty divided the newly explored world between Spain and Portugal along a meridian.', a: 'Treaty of Tordesillas', category: 'treaties', alt: ['Tordesillas'] },
      { q: 'This 1919 peace treaty ended the First World War and imposed harsh terms on Germany.', a: 'Treaty of Versailles', category: 'treaties', alt: ['Versailles Treaty'] },
      { q: 'This 1713 settlement ended the War of the Spanish Succession and gave Britain Gibraltar.', a: 'Treaty of Utrecht', category: 'treaties', alt: ['Utrecht'] },
      { q: 'This 480 BC stand by 300 Spartans and their allies blocked a vast Persian army at a narrow pass.', a: 'Thermopylae', category: 'battles', alt: ['Battle of Thermopylae'] },
      { q: 'This 732 battle in Frankish Gaul saw Charles Martel halt Muslim expansion into western Europe.', a: 'Tours', category: 'battles', alt: ['Battle of Tours', 'Battle of Poitiers'] },
      { q: 'This 1914 battle in East Prussia ended in catastrophic Russian defeat by the Germans under Hindenburg and Ludendorff.', a: 'Tannenberg', category: 'battles', alt: ['Battle of Tannenberg'] },
      { q: 'This Turco-Mongol conqueror, called the Lame, built an empire from his capital at Samarkand in the late 14th century.', a: 'Timur', category: 'medieval', alt: ['Tamerlane'] },
      { q: 'This Yugoslav partisan leader founded a non-aligned communist federation and ruled it from 1945 until his death in 1980.', a: 'Josip Broz Tito', category: 'leaders', alt: ['Tito'] },
      { q: 'This Chinese dynasty (618–907 AD) is often regarded as a cultural golden age of poetry, painting and cosmopolitan trade.', a: 'Tang dynasty', category: 'medieval', alt: ['Tang Dynasty'] },
      { q: 'This 1989 Beijing protest by students was violently suppressed when tanks rolled into a famous central square.', a: 'Tiananmen Square protests', category: 'modern', alt: ['Tiananmen Square', 'Tiananmen'] },
      { q: 'This English royal house, founded by Henry VII after the Wars of the Roses, ended with Elizabeth I in 1603.', a: 'Tudor dynasty', category: 'leaders', alt: ['Tudors', 'House of Tudor'] },
    ],
    U: [
      { q: 'This first Islamic dynasty, ruling 661–750 from Damascus, expanded Muslim rule westward to the Atlantic and eastward to the Indus.', a: 'Umayyad Caliphate', category: 'medieval', alt: ['Umayyads'] },
    ],
    V: [
      { q: 'This 1989 peaceful overthrow of Czechoslovakia\'s communist government took its name from the smoothness of the transition.', a: 'Velvet Revolution', category: 'revolutions' },
      { q: 'This 1916 ten-month battle on the Western Front became the longest and one of the bloodiest of the First World War.', a: 'Verdun', category: 'battles', alt: ['Battle of Verdun'] },
      { q: 'This Portuguese explorer\'s 1498 sea route to India opened direct European trade with the East.', a: 'Vasco da Gama', category: 'explorers', alt: ['da Gama'] },
      { q: 'This pope who launched the First Crusade in 1095 called for it at the Council of Clermont — answer the pope.', a: 'Urban II', category: 'medieval', alt: ['Pope Urban II'] },
    ],
    W: [
      { q: 'This 1972 American political scandal forced President Nixon to resign in 1973.', a: 'Watergate', category: 'modern' },
      { q: 'This 1944–45 German counter-offensive through the Ardennes was the last major Nazi push on the Western Front.', a: 'Battle of the Bulge', category: 'battles', alt: ['Bulge'] },
      { q: 'This Polish electrician and Solidarity leader became his country\'s first post-communist president in 1990.', a: 'Lech Wałęsa', category: 'modern', alt: ['Walesa', 'Lech Walesa'] },
      { q: 'This first global conflict, fought 1914–1918, was triggered by the assassination of an Austrian archduke in Sarajevo.', a: 'World War I', category: 'wars', alt: ['First World War', 'WWI', 'Great War'] },
      { q: 'This 1939–1945 conflict became the deadliest in human history, ending with the atomic bombings of Japan.', a: 'World War II', category: 'wars', alt: ['Second World War', 'WWII'] },
    ],
    Y: [
      { q: 'This 1991–2001 series of conflicts followed the breakup of a Balkan federation, with the worst atrocities in Bosnia.', a: 'Yugoslav Wars', category: 'wars' },
      { q: 'This Mongol-founded dynasty ruled China from 1271 to 1368 under Kublai Khan and his successors.', a: 'Yuan dynasty', category: 'medieval', alt: ['Yuan Dynasty'] },
    ],
    Z: [
      { q: 'This Chinese Ming-era admiral commanded seven enormous treasure-fleet voyages across the Indian Ocean in the early 15th century.', a: 'Zheng He', category: 'explorers' },
    ],
    // additional questions — rebucketByAnswer will re-file each one under its answer's first letter
    X: [
      { q: 'This Persian king who succeeded Darius I led the second Persian invasion of Greece in 480 BC, sacking Athens before defeat at Salamis.', a: 'Xerxes I', category: 'ancient', alt: ['Xerxes', 'Xerxes the Great'] },
    ],
    // The rest are MISFILED on purpose under "extra" placeholders for visual grouping; rebucket sorts them.
    // Filling specifics: ancient civilizations, monarchs, treaties, 20th-century events, WW1/WW2 battles.
    '1': [
      { q: 'This Italian Etruscan-influenced ancient people of central Italy pre-dated Rome and gave it many cultural elements before being absorbed in the 4th century BC.', a: 'Etruscans', category: 'ancient' },
      { q: 'This Roman general who crossed the Rubicon in 49 BC defied the Senate and triggered civil war against Pompey.', a: 'Julius Caesar', category: 'ancient', alt: ['Caesar'] },
      { q: 'This 27 BC title, voted to the victor of Actium by the Senate, marked the formal start of the Roman Principate.', a: 'Augustus', category: 'ancient' },
      { q: 'This Greek city-state, defeated by Sparta in 404 BC, lost the Peloponnesian conflict despite its powerful navy.', a: 'Athens', category: 'ancient' },
      { q: 'This Carthaginian general led elephants over the Alps to invade the Italian peninsula during the Second Punic war.', a: 'Hannibal', category: 'ancient' },
      { q: 'This Roman senator and orator denounced Catiline\'s conspiracy in 63 BC and was later executed on Mark Antony\'s orders.', a: 'Cicero', category: 'ancient' },
      { q: 'This Greek philosopher, condemned to drink hemlock in 399 BC, taught Plato and is known through his student\'s dialogues.', a: 'Socrates', category: 'ancient' },
      { q: 'This Egyptian queen who allied with Julius Caesar and later Mark Antony died by reputed snakebite in 30 BC.', a: 'Cleopatra', category: 'ancient' },
      { q: 'This last pre-Islamic ruling house of Persia, defeated by Arab armies at Qadisiyyah in 636, ended a four-century reign.', a: 'Sasanian Empire', category: 'ancient', alt: ['Sassanid Empire'] },
      { q: 'This Roman Stoic emperor and author of the Meditations reigned 161–180 AD.', a: 'Marcus Aurelius', category: 'ancient' },
      { q: 'This volcanic eruption of 79 AD buried the Roman towns of Pompeii and Herculaneum.', a: 'Vesuvius', category: 'ancient', alt: ['Mount Vesuvius', 'eruption of Vesuvius'] },
      { q: 'This Greek historian, called the Father of History, chronicled the conflict between the Greek city-states and the Persian Empire.', a: 'Herodotus', category: 'ancient' },
    ],
    '2': [
      { q: 'This 1095 sermon by Pope Urban II at a southern French town launched the First Crusade.', a: 'Council of Clermont', category: 'medieval' },
      { q: 'This 1215 charter, sealed at Runnymede, limited the power of King John and is foundational to common-law tradition.', a: 'Magna Carta', category: 'medieval' },
      { q: 'This 1187 victory at the Horns gave Saladin control of Jerusalem and triggered the Third Crusade.', a: 'Battle of Hattin', category: 'medieval', alt: ['Hattin'] },
      { q: 'This English king nicknamed the Lionheart led the Third Crusade against Saladin in 1189–1192.', a: 'Richard I', category: 'medieval', alt: ['Richard the Lionheart'] },
      { q: 'This 1337–1453 series of conflicts between England and France was sparked by rival claims to the French throne.', a: 'Hundred Years\' War', category: 'medieval', alt: ['Hundred Years War'] },
      { q: 'This 14th-century Italian city-state, governed by the Medici, became the cradle of the Renaissance.', a: 'Florence', category: 'medieval' },
      { q: 'This 1492 Spanish conquest of the last Muslim emirate on the Iberian peninsula completed the Reconquista.', a: 'Fall of Granada', category: 'medieval', alt: ['Granada', 'conquest of Granada'] },
      { q: 'This Florentine banking dynasty produced four popes and two queens of France during the Renaissance.', a: 'Medici family', category: 'medieval', alt: ['Medici', 'House of Medici'] },
      { q: 'This Italian merchant of the 13th century reached Kublai Khan\'s court and dictated his travels while imprisoned in Genoa.', a: 'Marco Polo', category: 'medieval' },
      { q: 'This Mali ruler made a 1324 pilgrimage to Mecca so lavish he reportedly destabilised gold prices in Egypt for a decade.', a: 'Mansa Musa', category: 'medieval' },
      { q: 'This 1066 Yorkshire clash saw King Harold of England defeat a Norwegian army just three weeks before Hastings.', a: 'Stamford Bridge', category: 'medieval', alt: ['Battle of Stamford Bridge'] },
      { q: 'This crusader fortress in modern Syria, held by the Knights Hospitaller, fell to Sultan Baybars in 1271.', a: 'Krak des Chevaliers', category: 'medieval' },
      { q: 'This 800 AD ceremony in Rome saw Pope Leo III crown a Frankish king as Emperor of the Romans.', a: 'Coronation of Charlemagne', category: 'medieval' },
    ],
    '3': [
      { q: 'This Habsburg Spanish king, son of Charles V, sent the Armada against England in 1588.', a: 'Philip II', category: 'modern' },
      { q: 'This English statesman who beheaded Charles I led the New Model Army to victory at Naseby in 1645.', a: 'Oliver Cromwell', category: 'modern' },
      { q: 'This Genoese mariner\'s 1492 expedition under Spanish flag reached the Caribbean and is conventionally seen as opening the Americas to Europe.', a: 'Christopher Columbus', category: 'modern', alt: ['Columbus'] },
      { q: 'This 1607 settlement in Virginia was the first permanent English colony in mainland North America.', a: 'Jamestown', category: 'modern' },
      { q: 'This 1620 English Separatist ship carried Pilgrims to what became Plymouth Colony in Massachusetts.', a: 'Mayflower', category: 'modern' },
      { q: 'This 1773 colonial protest in a Massachusetts harbour saw activists dump tea overboard against British taxes.', a: 'Boston Tea Party', category: 'modern' },
      { q: 'This 1776 document, largely drafted by Thomas Jefferson, proclaimed the thirteen colonies free of British rule.', a: 'Declaration of Independence', category: 'modern' },
      { q: 'This 1804 self-coronation in Paris saw a Corsican-born general crown himself Emperor of the French.', a: 'Napoleon Bonaparte', category: 'modern', alt: ['Napoleon', 'Napoleon I'] },
      { q: 'This 1812 Russian campaign by a French emperor ended in catastrophic retreat from Moscow in winter.', a: 'Invasion of Russia', category: 'modern', alt: ['French invasion of Russia', 'Russian campaign'] },
      { q: 'This 1804 legal code, named for the emperor who promulgated it, became the basis of civil law across much of Europe.', a: 'Napoleonic Code', category: 'modern' },
      { q: 'This 1854–56 conflict pitted the Russian Empire against an alliance of Britain, France and the Ottomans on a Black Sea peninsula.', a: 'Crimean War', category: 'modern' },
      { q: 'This British nurse who reformed military hospitals during the Crimean conflict became known as the Lady with the Lamp.', a: 'Florence Nightingale', category: 'modern' },
      { q: 'This 1861–1865 conflict ended at a Virginia courthouse when General Lee surrendered to General Grant.', a: 'American Civil War', category: 'modern' },
      { q: 'This US president who delivered the Gettysburg Address was assassinated at Ford\'s Theatre in 1865.', a: 'Abraham Lincoln', category: 'modern' },
      { q: 'This 1869 American engineering achievement linked the east and west coasts with a single rail line meeting at Promontory Summit.', a: 'Transcontinental Railroad', category: 'modern' },
      { q: 'This 1898 American war hero and later 26th president led the Rough Riders at San Juan Hill.', a: 'Theodore Roosevelt', category: 'modern' },
    ],
    '4': [
      { q: 'This 1917 Russian uprising in the second month (Old Style) toppled the Romanov dynasty and ended tsarist rule.', a: 'February Revolution', category: 'revolutions' },
      { q: 'This 1789 Parisian female-led protest forced the royal family to leave their suburban palace for the capital.', a: 'Women\'s March on Versailles', category: 'revolutions', alt: ['March on Versailles'] },
      { q: 'This 1804 leader who proclaimed independence of his Caribbean island had served under Toussaint Louverture.', a: 'Jean-Jacques Dessalines', category: 'revolutions', alt: ['Dessalines'] },
      { q: 'This former slave led the 1791 uprising on Saint-Domingue that became the only successful slave revolution in history.', a: 'Toussaint Louverture', category: 'revolutions', alt: ['Toussaint L\'Ouverture', 'Louverture'] },
      { q: 'This mid-19th-century wave of liberal uprisings, also called the Spring of Nations, swept Paris, Vienna, Berlin and Budapest in a single year.', a: 'Revolutions of 1848', category: 'revolutions', alt: ['1848 revolutions', 'Spring of Nations'] },
      { q: 'This 1959 takeover led by Fidel Castro and Che Guevara ousted Fulgencio Batista from a Caribbean island.', a: 'Cuban Revolution', category: 'revolutions' },
      { q: 'This late-1980s cascading collapse of one-party rule across most of Eastern Europe, also called the Autumn of Nations, is grouped under one famous year.', a: 'Revolutions of 1989', category: 'revolutions', alt: ['1989 revolutions', 'Autumn of Nations'] },
      { q: 'This 1989 demolition of a divided-city barrier on 9 November became the iconic symbolic end of the Cold War in Europe.', a: 'Fall of the Berlin Wall', category: 'modern', alt: ['Berlin Wall'] },
      { q: 'This 1948 establishment of a Jewish state in the former British Mandate of Palestine sparked the first Arab–Israeli conflict.', a: 'Founding of Israel', category: 'modern', alt: ['Israel', 'Israeli Declaration of Independence'] },
      { q: 'This 1947 division of the British Raj into two independent states triggered mass migration and communal violence.', a: 'Partition of India', category: 'modern', alt: ['Partition'] },
    ],
    '5': [
      { q: 'This 1914 clash on a French river halted the opening German offensive through Belgium and saved Paris.', a: 'First Battle of the Marne', category: 'wars', alt: ['Marne'] },
      { q: 'This 1944–45 climactic Soviet–German urban fight ended with the Red Army raising a flag over the Reichstag.', a: 'Battle of Berlin', category: 'wars', alt: ['Berlin'] },
      { q: 'This 1940 air campaign saw the RAF defeat the Luftwaffe over southern England during the summer and autumn.', a: 'Battle of Britain', category: 'wars' },
      { q: 'This 1941 surprise Japanese air raid on a Hawaiian naval base brought the United States into the Second World War.', a: 'Pearl Harbor', category: 'wars', alt: ['attack on Pearl Harbor'] },
      { q: 'This 1944 doomed Allied airborne assault tried to seize bridges over the Rhine, including one at Arnhem.', a: 'Operation Market Garden', category: 'wars', alt: ['Market Garden'] },
      { q: 'This Soviet leader\'s 1928 first plan launched forced industrialisation and collectivisation of agriculture.', a: 'Joseph Stalin', category: 'leaders', alt: ['Stalin'] },
      { q: 'This Italian dictator known as Il Duce founded fascism and ruled from 1922 until his execution in 1945.', a: 'Benito Mussolini', category: 'leaders', alt: ['Mussolini'] },
      { q: 'This Chinese communist leader proclaimed the People\'s Republic in 1949 and launched the Cultural Revolution in 1966.', a: 'Mao Zedong', category: 'leaders', alt: ['Chairman Mao', 'Mao Tse-tung'] },
      { q: 'This Indian first prime minister, who took office in 1947, led his country through its first 17 years of independence.', a: 'Jawaharlal Nehru', category: 'leaders', alt: ['Nehru'] },
      { q: 'This South African statesman freed in 1990 after 27 years on Robben Island became his country\'s first black head of state.', a: 'Nelson Mandela', category: 'leaders' },
      { q: 'This Soviet leader whose policies of glasnost and perestroika in the late 1980s helped end the Cold War received the 1990 Nobel Peace Prize.', a: 'Mikhail Gorbachev', category: 'leaders', alt: ['Gorbachev'] },
      { q: 'This British prime minister, ousted in 1990, was Britain\'s first woman to hold the office and was nicknamed the Iron Lady.', a: 'Margaret Thatcher', category: 'leaders', alt: ['Thatcher'] },
      { q: 'This US president, in office 1981–1989, called the Soviet Union an evil empire and demanded a Berlin wall be torn down.', a: 'Ronald Reagan', category: 'leaders', alt: ['Reagan'] },
      { q: 'This US president nicknamed Ike commanded Allied forces in Europe during the Second World War.', a: 'Dwight D. Eisenhower', category: 'leaders', alt: ['Eisenhower', 'Dwight Eisenhower'] },
      { q: 'This British wartime prime minister rallied his country during 1940 with speeches such as "We shall fight on the beaches".', a: 'Winston Churchill', category: 'leaders', alt: ['Churchill'] },
      { q: 'This French wartime general led the Free French during the Second World War and founded the Fifth Republic in 1958.', a: 'Charles de Gaulle', category: 'leaders', alt: ['de Gaulle'] },
      { q: 'This US president, the 32nd, led his country through the Great Depression and most of the Second World War.', a: 'Franklin D. Roosevelt', category: 'leaders', alt: ['FDR', 'Franklin Roosevelt'] },
    ],
    '6': [
      { q: 'This 1815 Austrian-hosted diplomatic gathering, chaired by Metternich, redrew the map of Europe after Napoleon\'s defeat.', a: 'Congress of Vienna', category: 'treaties' },
      { q: 'This 1842 treaty ending the First Opium War ceded Hong Kong island to Britain.', a: 'Treaty of Nanking', category: 'treaties', alt: ['Treaty of Nanjing'] },
      { q: 'This 1814 Anglo-American peace treaty ending the War of 1812 was signed in a Belgian city.', a: 'Treaty of Ghent', category: 'treaties' },
      { q: 'This 1763 settlement ending the Seven Years\' War transferred most of New France to Britain.', a: 'Treaty of Paris', category: 'treaties' },
      { q: 'This 1493 papal bull, later modified by Tordesillas, drew an imaginary line of demarcation between Spanish and Portuguese spheres.', a: 'Inter caetera', category: 'treaties', alt: ['papal bull Inter caetera'] },
      { q: 'This 1928 international agreement, signed by 62 states, formally renounced war as an instrument of national policy.', a: 'Kellogg–Briand Pact', category: 'treaties', alt: ['Kellogg-Briand Pact'] },
      { q: 'This 1922 American-hosted maritime limitation pact capped capital-ship tonnage among the major powers.', a: 'Washington Naval Treaty', category: 'treaties' },
      { q: 'This 1944 New Hampshire summit established the postwar international monetary order including the IMF and World Bank.', a: 'Bretton Woods Conference', category: 'treaties', alt: ['Bretton Woods'] },
      { q: 'This 1992 Dutch-city agreement created the European Union out of the European Communities.', a: 'Maastricht Treaty', category: 'treaties' },
      { q: 'This 1884–85 German-hosted diplomatic meeting formalised the European Scramble for Africa.', a: 'Berlin Conference', category: 'treaties' },
    ],
    '7': [
      { q: 'This Chinese dynasty (1644–1911) collapsed when the boy-emperor Puyi abdicated after Sun Yat-sen\'s revolution.', a: 'Qing dynasty', category: 'medieval', alt: ['Qing'] },
      { q: 'This Japanese era from 1603 to 1868 saw the country closed to most foreign contact under a Tokugawa shogunate.', a: 'Edo period', category: 'medieval', alt: ['Tokugawa shogunate'] },
      { q: 'This 1868 Japanese return of power to the emperor ended samurai rule and launched rapid modernisation.', a: 'Meiji Restoration', category: 'modern' },
      { q: 'This 1853 American naval mission led by a US commodore forced Japan to open to Western trade.', a: 'Perry Expedition', category: 'modern', alt: ['Matthew Perry expedition', 'Perry\'s Expedition'] },
      { q: 'This 1900 Chinese uprising against foreign influence was crushed by an eight-nation alliance.', a: 'Boxer Rebellion', category: 'modern' },
      { q: 'This 1911 Chinese uprising overthrew the last imperial dynasty and established the Republic of China.', a: 'Xinhai Revolution', category: 'revolutions', alt: ['1911 Revolution'] },
      { q: 'This 1934–35 communist retreat across China, led by Mao Zedong, became a foundational legend of the Chinese Communist Party.', a: 'Long March', category: 'modern' },
      { q: 'This 1966–76 Chinese mass political upheaval was launched by Mao to reassert his ideological authority.', a: 'Cultural Revolution', category: 'modern' },
      { q: 'This Korean kingdom (1392–1897) gave the modern Korean script its name and ended with Japanese annexation.', a: 'Joseon dynasty', category: 'medieval', alt: ['Joseon', 'Chosŏn'] },
    ],
    '8': [
      { q: 'This Soviet leader, born Iosif Dzhugashvili in Georgia, ruled the USSR from the late 1920s until his death in 1953.', a: 'Joseph Stalin', category: 'leaders' },
      { q: 'This founding leader of the Soviet state died in 1924 after leading the October takeover seven years earlier.', a: 'Vladimir Lenin', category: 'leaders', alt: ['Lenin'] },
      { q: 'This Bolshevik who organised the Red Army was assassinated in Mexico in 1940 on Stalin\'s orders.', a: 'Leon Trotsky', category: 'leaders', alt: ['Trotsky'] },
      { q: 'This Romanian communist dictator was executed by firing squad on Christmas Day 1989 with his wife Elena.', a: 'Nicolae Ceaușescu', category: 'leaders', alt: ['Ceaușescu', 'Ceausescu'] },
      { q: 'This North Korean founder, who ruled from 1948 to his death in 1994, started a war with the south in 1950.', a: 'Kim Il-sung', category: 'leaders', alt: ['Kim Il Sung'] },
      { q: 'This Cambodian Khmer Rouge leader directed the killing fields, causing perhaps two million deaths from 1975 to 1979.', a: 'Pol Pot', category: 'leaders' },
      { q: 'This Iraqi Baathist ruler invaded Kuwait in 1990 and was overthrown by US-led forces in 2003.', a: 'Saddam Hussein', category: 'leaders' },
      { q: 'This Libyan colonel ruled for 42 years before being killed during the 2011 uprising.', a: 'Muammar Gaddafi', category: 'leaders', alt: ['Gaddafi', 'Qaddafi'] },
      { q: 'This Egyptian president signed the 1979 peace accord with Israel and was assassinated in 1981.', a: 'Anwar Sadat', category: 'leaders', alt: ['Sadat'] },
      { q: 'This Israeli prime minister, killed in 1995 by a far-right assassin, had signed the 1993 Oslo Accords.', a: 'Yitzhak Rabin', category: 'leaders', alt: ['Rabin'] },
      { q: 'This Polish-born Catholic pope (1978–2005) is credited with helping end communism in Eastern Europe.', a: 'John Paul II', category: 'leaders', alt: ['Pope John Paul II'] },
    ],
    'rare': [
      { q: 'This Roman general crushed Hannibal at the Battle of Zama in 202 BC, ending the Second Punic conflict.', a: 'Scipio Africanus', category: 'ancient', alt: ['Scipio'] },
      { q: 'This Bulgarian-born revolutionary, born Vladimir Ilyich Ulyanov, took the alias by which Soviet history would know him.', a: 'Lenin', category: 'leaders', alt: ['Vladimir Lenin'] },
      { q: 'This Italian explorer for whom two continents are named gave his given name to the New World after his 1499–1502 voyages.', a: 'Amerigo Vespucci', category: 'explorers', alt: ['Vespucci'] },
      { q: 'This Russian mystic and adviser to the Romanov royal family was murdered by nobles in 1916.', a: 'Grigori Rasputin', category: 'modern', alt: ['Rasputin'] },
      { q: 'This Roman Catholic monastic order founded in 1540 by Ignatius of Loyola spearheaded the Counter-Reformation.', a: 'Jesuits', category: 'religious', alt: ['Society of Jesus'] },
      { q: 'This first US president and victor of the American Revolution declined a third term, setting a lasting precedent.', a: 'George Washington', category: 'leaders' },
      { q: 'This French Sun King reigned 72 years from 1643 and built the palace of Versailles.', a: 'Louis XIV', category: 'leaders', alt: ['Sun King'] },
      { q: 'This French king who was beheaded by guillotine in 1793 had previously tried to flee to Varennes with his queen.', a: 'Louis XVI', category: 'revolutions' },
      { q: 'This French royal child of the beheaded king and Marie Antoinette is believed to have died in revolutionary prison in 1795 at age ten.', a: 'Louis XVII', category: 'revolutions' },
      { q: 'This Holy Roman Empress, only female Habsburg ruler, presided 40 years and mothered 16 children including Marie Antoinette.', a: 'Maria Theresa', category: 'leaders' },
      { q: 'This guillotined Habsburg-born queen of France, reportedly never said "let them eat cake".', a: 'Marie Antoinette', category: 'revolutions' },
      { q: 'This shortest-reigning English monarch ruled just nine days in 1553 before her cousin Mary I displaced and beheaded her.', a: 'Lady Jane Grey', category: 'leaders' },
      { q: 'This Habsburg Holy Roman Emperor who divided his vast realm between son and brother abdicated in 1556.', a: 'Charles V', category: 'leaders', alt: ['Emperor Charles V'] },
      { q: 'This Tudor king broke with Rome in the 1530s to obtain a divorce and married six wives in all.', a: 'Henry VIII', category: 'leaders' },
      { q: 'This Christian dualist sect of southern France was crushed by a 13th-century Catholic crusade.', a: 'Cathars', category: 'religious', alt: ['Cathar'] },
      { q: 'This crusading military-monastic order, suppressed in 1312, had been founded around 1119 to protect pilgrims to Jerusalem.', a: 'Knights Templar', category: 'medieval', alt: ['Templars'] },
      { q: 'This crusading order, surviving today as a charity, was founded around 1099 to care for sick pilgrims to the Holy Land.', a: 'Knights Hospitaller', category: 'medieval', alt: ['Hospitallers', 'Order of Malta'] },
      { q: 'This 1521 papal pronouncement formally excommunicated Martin Luther from the Catholic Church.', a: 'Decet Romanum Pontificem', category: 'religious', alt: ['Decet Romanum'] },
      { q: 'This Norman duke crossed the Channel in 1066 and defeated King Harold to claim the English throne.', a: 'William the Conqueror', category: 'medieval', alt: ['William I'] },
      { q: 'This 14th-century Florentine poet wrote the Divine Comedy in Tuscan vernacular.', a: 'Dante Alighieri', category: 'medieval', alt: ['Dante'] },
      { q: 'This French statesman whose 1950 declaration proposing pooled coal and steel kicked off European integration.', a: 'Robert Schuman', category: 'modern', alt: ['Schuman'] },
      { q: 'This 1957 Cold-War-era launch by the USSR of the first artificial satellite shocked the United States.', a: 'Sputnik', category: 'modern', alt: ['Sputnik 1'] },
      { q: 'This 1969 American program landing on the Moon fulfilled a Kennedy pledge made eight years earlier.', a: 'Apollo 11', category: 'modern' },
      { q: 'This 1928 Soviet economic blueprint launched forced collectivisation and rapid heavy industrialisation under Stalin.', a: 'First Five-Year Plan', category: 'modern', alt: ['Five-Year Plan'] },
      { q: 'This 1933 burning of Germany\'s parliament building gave the Nazis a pretext to suspend civil liberties.', a: 'Reichstag fire', category: 'modern' },
      { q: 'This Nazi propaganda minister and intellectual heir of Hitler killed himself and his family in the Berlin bunker in May 1945.', a: 'Joseph Goebbels', category: 'leaders', alt: ['Goebbels'] },
      { q: 'This Nazi-era SS chief and architect of the camps was captured by the British in 1945 and bit a cyanide capsule.', a: 'Heinrich Himmler', category: 'leaders', alt: ['Himmler'] },
      { q: 'This Spanish Habsburg artist painted Las Meninas in 1656 in the court of Philip IV — a touchstone of Western painting.', a: 'Diego Velázquez', category: 'modern', alt: ['Velázquez', 'Velazquez'] },
      { q: 'This Italian polymath painter of the Renaissance gave us the Mona Lisa and the Last Supper.', a: 'Leonardo da Vinci', category: 'medieval', alt: ['Leonardo'] },
      { q: 'This sculptor and painter of the Sistine Chapel ceiling carved David in marble around 1504.', a: 'Michelangelo', category: 'medieval' },
      { q: 'This Ottoman sultan who in 1453 captured Constantinople was just 21 years old at the time.', a: 'Mehmed II', category: 'medieval', alt: ['Mehmet II', 'Mehmed the Conqueror'] },
      { q: 'This Mongol khanate founded by Batu Khan in the 13th century dominated Russia until the late 1400s.', a: 'Golden Horde', category: 'medieval' },
      { q: 'This 1571 Spanish-Venetian fleet commander, half-brother of Philip II, led the Holy League to victory over the Ottomans.', a: 'Don John of Austria', category: 'battles', alt: ['John of Austria', 'Don Juan of Austria'] },
      { q: 'This Tudor naval commander whose ships scattered the Spanish Armada in 1588 also raided Cadiz.', a: 'Francis Drake', category: 'modern' },
      { q: 'This 1717–18 American pirate, real name Edward Teach, terrorised the Caribbean and was killed by the Royal Navy.', a: 'Blackbeard', category: 'modern', alt: ['Edward Teach'] },
      { q: 'This 19th-century Lakota chief defeated Custer at the Battle of the Little Bighorn in 1876.', a: 'Sitting Bull', category: 'modern' },
      { q: 'This Apache leader resisted American and Mexican expansion in the southwestern desert before surrendering in 1886.', a: 'Geronimo', category: 'modern' },
      { q: 'This Mexican revolutionary general led the División del Norte and was assassinated in 1923.', a: 'Pancho Villa', category: 'revolutions' },
      { q: 'This Mexican revolutionary peasant leader of the Plan of Ayala demanded land reform before his 1919 assassination.', a: 'Emiliano Zapata', category: 'revolutions', alt: ['Zapata'] },
      { q: 'This Argentine-born Marxist guerrilla helped lead the 1959 uprising in Cuba before being executed in Bolivia in 1967.', a: 'Che Guevara', category: 'revolutions', alt: ['Che', 'Ernesto Guevara'] },
      { q: 'This Cuban revolutionary led his island from 1959 until handing power to his brother in 2008.', a: 'Fidel Castro', category: 'leaders', alt: ['Castro'] },
      { q: 'This Vietnamese communist leader led the fight against French then American forces; the southern capital was renamed for him after 1975.', a: 'Ho Chi Minh', category: 'leaders' },
      { q: 'This Vietnamese general who masterminded Dien Bien Phu and the 1968 Tet Offensive was nicknamed the Red Napoleon.', a: 'Võ Nguyên Giáp', category: 'wars', alt: ['Vo Nguyen Giap', 'Giap'] },
      { q: 'This 1789 French revolutionary charter enshrined liberty, property, security and resistance to oppression.', a: 'Declaration of the Rights of Man', category: 'revolutions' },
      { q: 'This 1948 UN general-assembly document proclaimed a common standard of fundamental freedoms for all peoples.', a: 'Universal Declaration of Human Rights', category: 'modern' },
      { q: 'This 1945 international agreement signed in San Francisco founded the postwar successor to the League — name the founding document.', a: 'United Nations Charter', category: 'modern', alt: ['UN Charter'] },
      { q: 'This 1949 North Atlantic defensive alliance, signed in Washington, was created to deter Soviet expansion in Europe.', a: 'NATO', category: 'modern', alt: ['North Atlantic Treaty Organisation'] },
      { q: 'This 1955 Soviet-led military alliance was the eastern bloc\'s answer to NATO.', a: 'Warsaw Pact', category: 'modern' },
      { q: 'This Czech reformer launched the 1968 Prague Spring before Soviet tanks crushed it.', a: 'Alexander Dubček', category: 'modern', alt: ['Dubček', 'Dubcek'] },
      { q: 'This October uprising against communist rule, launched from Budapest, was crushed by Soviet tanks the next month — answer with the year of the revolt and its country.', a: 'Hungarian Revolution of 1956', category: 'revolutions', alt: ['Hungarian Uprising', '1956 Hungarian Revolution'] },
      { q: 'This 1935–36 Mussolini-led fascist conquest of an African empire prompted toothless League of Nations sanctions.', a: 'Italian invasion of Ethiopia', category: 'wars', alt: ['Second Italo-Ethiopian War'] },
      { q: 'This 1933 German political event saw Hindenburg appoint Adolf Hitler chancellor.', a: 'Machtergreifung', category: 'modern', alt: ['Nazi seizure of power'] },
      { q: 'This 1938 German pogrom against Jewish shops and synagogues took its name from the broken-glass shards left in the streets.', a: 'Kristallnacht', category: 'modern', alt: ['Night of Broken Glass'] },
      { q: 'This 1942 Berlin-suburb meeting of Nazi officials formalised the systematic murder of European Jewry.', a: 'Wannsee Conference', category: 'modern', alt: ['Wannsee'] },
      { q: 'This Nazi-built German extermination complex in southern Poland killed over a million people, mostly Jews.', a: 'Auschwitz', category: 'modern', alt: ['Auschwitz-Birkenau'] },
      { q: 'This Nazi-walled-off Polish-capital quarter where Jews mounted a 1943 armed revolt was the largest such enclosure in occupied Europe.', a: 'Warsaw Ghetto', category: 'modern' },
      { q: 'This 1944 Polish-capital revolt against German occupation, hoping for Soviet help that never came, was crushed after 63 days.', a: 'Warsaw Uprising', category: 'wars' },
      { q: 'This US-Pacific commander who fulfilled his "I shall return" pledge accepted Japanese surrender on the USS Missouri in 1945.', a: 'Douglas MacArthur', category: 'leaders', alt: ['MacArthur'] },
      { q: 'This 1942–46 secret American programme under Robert Oppenheimer produced the first atomic bombs.', a: 'Manhattan Project', category: 'wars' },
      { q: 'This 9 August 1945 American atomic bombing of a Japanese city helped force Japan\'s surrender.', a: 'Nagasaki', category: 'wars', alt: ['Bombing of Nagasaki'] },
      { q: 'This Korean general turned dictator who ruled the south 1961–79 was assassinated by his intelligence chief.', a: 'Park Chung-hee', category: 'leaders', alt: ['Park Chung Hee'] },
      { q: 'This Greek philosopher tutor of Alexander the Great founded the Lyceum and pioneered logic and biology.', a: 'Aristotle', category: 'ancient' },
      { q: 'This Greek philosopher of the 4th century BC, student of Socrates and teacher of Aristotle, founded the Academy in Athens.', a: 'Plato', category: 'ancient' },
      { q: 'This Greek thinker said one cannot step into the same river twice and championed change as the only constant.', a: 'Heraclitus', category: 'ancient' },
      { q: 'This Greek geometer who taught in Alexandria around 300 BC wrote the Elements, the foundational textbook of geometry.', a: 'Euclid', category: 'ancient' },
      { q: 'This Greek scientist of Syracuse cried "Eureka!" and devised the screw pump and principles of buoyancy.', a: 'Archimedes', category: 'ancient' },
      { q: 'This Roman epic poet of the 1st century BC wrote the Aeneid commissioned by Emperor Augustus.', a: 'Virgil', category: 'ancient' },
      { q: 'This Greek historian, sometimes called the Father of Scientific History, chronicled the Peloponnesian conflict.', a: 'Thucydides', category: 'ancient' },
      { q: 'This blind Greek epic poet is traditionally credited with the Iliad and the Odyssey.', a: 'Homer', category: 'ancient' },
      { q: 'This Frankish royal house that succeeded the Merovingians produced Charlemagne and ruled into the 10th century.', a: 'Carolingian dynasty', category: 'medieval', alt: ['Carolingians'] },
      { q: 'This Frankish royal house ruling from the 5th century gave way to the Carolingians in 751.', a: 'Merovingian dynasty', category: 'medieval', alt: ['Merovingians'] },
    ],
    'rare2': [
      // Q-letter boosters
      { q: 'This 17th-century body of English aristocratic supporters of the Stuart cause backed Charles I against Parliament.', a: 'Cavaliers', category: 'modern', alt: ['Royalists'] },
      { q: 'This 1759 city, capital of New France, fell to the British on the Plains of Abraham, sealing the loss of French Canada.', a: 'Quebec', category: 'modern', alt: ['Quebec City'] },
      { q: 'This British edict issued after the French and Indian War set the boundary of colonial settlement at the Appalachian Mountains, angering American colonists.', a: 'Royal Proclamation of 1763', category: 'modern', alt: ['Proclamation of 1763'] },
      // U-letter boosters
      { q: 'This 1929 collapse of the New York stock market kicked off the Great Depression.', a: 'Wall Street Crash', category: 'modern', alt: ['Wall Street Crash of 1929'] },
      { q: 'This Bolshevik leader of the Red Army, exiled and later assassinated in Mexico City on Stalin\'s orders, was born Lev Bronstein.', a: 'Leon Trotsky', category: 'leaders' },
      { q: 'This Soviet leader who oversaw the 1980s stagnation period preceded Andropov, Chernenko and Gorbachev.', a: 'Leonid Brezhnev', category: 'leaders', alt: ['Brezhnev'] },
      { q: 'This Soviet leader who denounced Stalin\'s personality cult banged his shoe at the UN in 1960.', a: 'Nikita Khrushchev', category: 'leaders', alt: ['Khrushchev'] },
      { q: 'This 1814 sacking of the US capital by British forces destroyed the executive mansion and the Capitol.', a: 'Burning of Washington', category: 'wars' },
      { q: 'This 1990 merger of the two post-war central-European states followed the fall of the Berlin Wall the previous year.', a: 'German reunification', category: 'modern', alt: ['Die Wende', 'Reunification of Germany'] },
      { q: 'This 1815 concluding settlement of the post-Napoleonic congress re-divided territory acquired by France across continental Europe.', a: 'Final Act of Vienna', category: 'treaties', alt: ['Vienna Final Act'] },
      // X-letter boosters
      { q: 'This Persian king who invaded Greece in 480 BC famously had the Hellespont whipped after a storm wrecked his bridges.', a: 'Xerxes', category: 'ancient' },
      { q: 'This Achaemenid Persian king, son of Darius I, lost the naval battle of Salamis in 480 BC.', a: 'Xerxes I', category: 'ancient' },
      { q: 'This Greek mercenary general led the Ten Thousand back from Persia in 401 BC and recorded the march in the Anabasis.', a: 'Xenophon', category: 'ancient' },
      { q: 'This 1911 Chinese uprising overthrew the Qing dynasty and ended over two millennia of imperial rule.', a: 'Xinhai Revolution', category: 'revolutions' },
      // Z-letter boosters
      { q: 'This Bantu kingdom under King Cetshwayo crushed a British force at Isandlwana in 1879.', a: 'Zulu Kingdom', category: 'modern', alt: ['Zululand', 'Zulu Empire'] },
      { q: 'This Persian prophet, founder of an ancient monotheistic religion that became the state faith of Sasanian Iran, lived in the first millennium BC.', a: 'Zoroaster', category: 'ancient', alt: ['Zarathustra'] },
      { q: 'This 6th-century BC Chinese philosopher founder of Taoism is traditionally credited with the Tao Te Ching.', a: 'Laozi', category: 'ancient', alt: ['Lao Tzu'] },
      { q: 'This West African kingdom around the Niger Bend was the centre of a Songhai-era successor that traded across the Sahara.', a: 'Zazzau', category: 'medieval', alt: ['Zaria'] },
      // F-letter (for variety)
      { q: 'This 14th-century English poet wrote the Canterbury Tales in the vernacular while serving the royal court.', a: 'Geoffrey Chaucer', category: 'medieval', alt: ['Chaucer'] },
      // J-letter
      { q: 'This Renaissance painter of the Last Judgement also designed much of the Sistine Chapel\'s decoration as a sculptor first.', a: 'Michelangelo Buonarroti', category: 'medieval' },
      // Z fillers continued
      { q: 'This Imperial Russian railroad colonel who became a famously incompetent admiral lost two fleets in the 1904–05 war with Japan.', a: 'Zinovy Rozhestvensky', category: 'wars', alt: ['Rozhestvensky'] },
      // Q-letter
      { q: 'This Mexican-Aztec emperor met Cortés in 1519 and was killed during the Spanish takeover the following year.', a: 'Moctezuma II', category: 'modern', alt: ['Montezuma II', 'Moctezuma'] },
      // X-letter
      { q: 'This Buddhist monk of the 7th century travelled overland from Tang China to India and brought back hundreds of Sanskrit scriptures.', a: 'Xuanzang', category: 'ancient', alt: ['Hsüan-tsang'] },
      // U-letter
      { q: 'This Italian-Greek mariner sailing for England in 1497 was the first European after the Norse to reach mainland North America.', a: 'John Cabot', category: 'explorers', alt: ['Giovanni Caboto', 'Cabot'] },
      // More Q answers (rare letter)
      { q: 'This Anglo-Saxon king of Wessex defended his realm against the Vikings and is the only English monarch to bear that exalted epithet.', a: 'Alfred the Great', category: 'medieval', alt: ['Alfred'] },
      { q: 'This Mongol-Yuan dynasty\'s longest-serving emperor after Kublai presided over a long decline in the 14th century.', a: 'Toghon Temür', category: 'medieval', alt: ['Toghon Temur', 'Toghan Temür'] },
      // More U-letter answers
      { q: 'This Ottoman-era treaty of 1774 ended a Russo-Turkish conflict and recognised Russian protection of Orthodox Christians under the Sublime Porte.', a: 'Treaty of Küçük Kaynarca', category: 'treaties', alt: ['Kuchuk Kainarji', 'Treaty of Kucuk Kaynarca'] },
      { q: 'This second Anglo-Bourbon settlement bearing the French capital\'s name ended the Napoleonic Hundred Days and exiled the emperor to Saint Helena.', a: 'Treaty of Paris (1815)', category: 'treaties' },
      { q: 'This Soviet leader who succeeded Stalin in 1953 was forced from power in 1964 over his erratic policies.', a: 'Nikita Khrushchev', category: 'leaders' },
      { q: 'This Indian dynasty of the 15th–16th centuries based in the Deccan plateau founded the great city of Hampi.', a: 'Vijayanagara Empire', category: 'medieval', alt: ['Vijayanagar'] },
      // Spreading: a few more Y for good measure
      { q: 'This Chinese Tang dynasty empress, the only woman in Chinese history to rule in her own name, took the throne in 690.', a: 'Wu Zetian', category: 'medieval', alt: ['Empress Wu'] },
      { q: 'This 1941 Moscow–Tokyo non-aggression accord kept Stalin\'s eastern flank quiet while he focused on Germany.', a: 'Soviet–Japanese Neutrality Pact', category: 'treaties', alt: ['Soviet-Japanese Neutrality Pact'] },
      { q: 'This 17-year-old shepherdess who claimed divine voices led France to victory at Orléans in 1429 was burned for heresy two years later.', a: 'Joan of Arc', category: 'medieval' },
      { q: 'This Boer republic in southern Africa fought a famous war against the British from 1899 to 1902.', a: 'South African Republic', category: 'wars', alt: ['Transvaal', 'Transvaal Republic'] },
      // More Q answers
      { q: 'This Andean civilization conquered by Pizarro in the 1530s had built a vast Andean empire centred on Cusco.', a: 'Inca Empire', category: 'modern', alt: ['Incas'] },
      { q: 'This Aztec capital, founded on an island in Lake Texcoco around 1325, fell to Cortés in 1521.', a: 'Tenochtitlan', category: 'modern', alt: ['Tenochtitlán'] },
      { q: 'This 17th-century English period after the execution of Charles I saw a republic established under Oliver Cromwell.', a: 'Interregnum', category: 'modern', alt: ['English Interregnum', 'Commonwealth of England'] },
      // More U answers
      { q: 'This 1846–48 US conflict with its southern neighbour ended with the cession of California and the Southwest under the Treaty of Guadalupe Hidalgo.', a: 'Mexican–American War', category: 'wars', alt: ['Mexican American War'] },
      { q: 'This 11-year American military presence in a Caribbean republic, begun under Woodrow Wilson, ended in 1934 under Franklin Roosevelt.', a: 'United States occupation of Haiti', category: 'wars', alt: ['US occupation of Haiti'] },
      { q: 'This 1820 American deal admitted one slave state and one free state in tandem to preserve sectional balance in the Senate.', a: 'Missouri Compromise', category: 'modern' },
      { q: 'This 1854 American law allowing two new western territories to decide on slavery by popular vote enflamed sectional tensions.', a: 'Kansas–Nebraska Act', category: 'modern', alt: ['Kansas Nebraska Act'] },
      // More Q-starting answers
      { q: 'This last Aztec emperor led the resistance against the Spanish after Moctezuma\'s death and was hanged by Cortés in 1525.', a: 'Quauhtémoc', category: 'modern', alt: ['Cuauhtémoc', 'Cuauhtemoc'] },
      { q: 'This pacifist Christian movement founded by George Fox in 17th-century England gave its members the nickname for trembling at God\'s word.', a: 'Quakers', category: 'religious', alt: ['Society of Friends'] },
      { q: 'This Inca knotted-cord recording device, used to track censuses and tribute, has only been partially decoded.', a: 'Quipu', category: 'ancient', alt: ['Khipu'] },
    ],
    '9': [
      { q: 'This 1992–95 blockade of a Bosnian capital became the longest such encirclement of a capital city in modern war.', a: 'Siege of Sarajevo', category: 'wars', alt: ['Sarajevo siege', 'Sarajevo'] },
      { q: 'This 1995 mass killing of Bosniak men and boys in eastern Bosnia was the worst atrocity on European soil since World War II.', a: 'Srebrenica massacre', category: 'wars', alt: ['Srebrenica'] },
      { q: 'This 1979–89 Moscow-led invasion of a Central Asian country supported a communist regime against US-backed mujahideen.', a: 'Soviet–Afghan War', category: 'wars', alt: ['Soviet Afghan War', 'Soviet war in Afghanistan'] },
      { q: 'This 1980–88 Gulf conflict between two large Middle Eastern states caused perhaps a million combined casualties.', a: 'Iran–Iraq War', category: 'wars', alt: ['Iran Iraq War'] },
      { q: 'This 1956 Anglo-French-Israeli action over a nationalised Egyptian waterway ended in US-pressured withdrawal.', a: 'Suez Crisis', category: 'wars' },
      { q: 'This 1973 Arab–Israeli conflict, beginning on a Jewish holy day, was followed by an Arab oil embargo against Western states.', a: 'Yom Kippur War', category: 'wars' },
      { q: 'This 1967 Arab–Israeli conflict gave Israel control of the West Bank, Gaza, Sinai and the Golan Heights.', a: 'Six-Day War', category: 'wars', alt: ['Six Day War'] },
      { q: 'This 1948–49 founding conflict between the new state of Israel and its neighbours is called by Arabs the Nakba, meaning catastrophe.', a: 'First Arab–Israeli War', category: 'wars', alt: ['1948 Arab-Israeli War', '1948 War', 'War of Independence'] },
      { q: 'This 1990–91 US-led coalition operation expelled Iraqi forces from Kuwait after the August 1990 invasion.', a: 'Gulf War', category: 'wars', alt: ['Persian Gulf War', 'First Gulf War'] },
      { q: 'This 1986 Soviet nuclear-plant accident in Ukraine spread radioactive contamination across much of Europe.', a: 'Chernobyl disaster', category: 'modern', alt: ['Chernobyl'] },
    ],
  },
};
