import type { RawPack } from '../core/packs';

export const historyPack: RawPack = {
  id: 'history',
  name: 'World History',
  description: 'Empires, revolutions, leaders and turning points.',
  locale: 'en',
  difficulty: 'hard',
  contentRating: 'everyone',
  emoji: '📜',
  accent: '#b5651d',
  letters: {
    A: [
      { q: 'This Macedonian king defeated Darius III at the Battle of Gaugamela in 331 BC.', a: 'Alexander the Great', category: 'ancient' },
      { q: 'This Roman emperor, born Gaius Octavius, defeated Mark Antony at Actium in 31 BC and became Rome\'s first emperor.', a: 'Augustus', category: 'ancient' },
      { q: 'This ancient Greek city-state defeated the Persians at the Battle of Marathon in 490 BC.', a: 'Athens', category: 'ancient' },
      { q: 'This 1918 agreement that ended World War I came into effect on the eleventh hour of the eleventh day of the eleventh month.', a: 'Armistice', category: 'modern' },
      { q: 'This South African system of racial segregation, formally enacted in 1948, was dismantled in the early 1990s.', a: 'Apartheid', category: 'modern' },
      { q: 'This Ethiopian kingdom, centred on the city of Aksum, was among the first states in the world to officially adopt Christianity, in the 4th century AD.', a: 'Aksumite Empire', category: 'ancient' },
      { q: 'This Indian emperor of the Maurya dynasty, reigning 268–232 BC, converted to Buddhism and spread its teachings across Asia.', a: 'Ashoka', category: 'ancient' },
      { q: 'The Paris fortress-prison stormed on 14 July 1789, sparking the French Revolution.', a: 'Bastille', category: 'revolutions' },
      { q: 'This Ottoman city, captured in 1361, served as the Ottoman capital before the conquest of Constantinople.', a: 'Adrianople', category: 'medieval' },
      { q: 'This ancient wonder, a giant bronze statue straddling the entrance of a Greek island harbour, was one of the Seven Wonders of the Ancient World.', a: 'Colossus of Rhodes', category: 'ancient' },
      { q: 'This 1954 landmark US Supreme Court ruling declared racial segregation in public schools unconstitutional.', a: 'Brown v. Board of Education', category: 'modern' },
      { q: 'This Spanish explorer completed the first circumnavigation of the globe in 1522, returning to Spain after Magellan\'s death in the Philippines.', a: 'Elcano', category: 'modern' },
    ],
    B: [
      { q: 'This 1940–1941 night-time German aerial bombing campaign against British cities, particularly London, killed over 43,000 civilians but failed to break British morale.', a: 'Blitz', category: 'wars' },
      { q: 'This 1905 Russian event saw peaceful workers shot by troops outside the Winter Palace, igniting nationwide unrest against the Tsar.', a: 'Bloody Sunday', category: 'revolutions' },
      { q: 'This 1942 German siege of a Soviet city on the Volga River became one of the deadliest battles in history.', a: 'Battle of Stalingrad', category: 'wars' },
      { q: 'This Iron Chancellor unified Germany under Prussian leadership through a series of wars in the 1860s and 1870s.', a: 'Bismarck', category: 'leaders' },
      { q: 'This 14th-century pandemic killed roughly a third of Europe\'s population between 1347 and 1351.', a: 'Black Death', category: 'medieval' },
      { q: 'This South American liberator defeated Spanish royalists at the Battle of Boyacá in 1819, freeing New Granada.', a: 'Bolívar', category: 'revolutions' },
      { q: 'This 1346 battle saw English longbowmen devastate the French cavalry near a village in northern France.', a: 'Battle of Crécy', category: 'wars' },
      { q: 'This ancient empire on the Euphrates, ruled by Nebuchadnezzar II in the 6th century BC, is traditionally credited with the Hanging Gardens, one of the Seven Wonders of the Ancient World.', a: 'Babylonian Empire', category: 'ancient' },
      { q: 'This 1689 English document confirmed parliamentary supremacy following the Glorious Revolution.', a: 'Bill of Rights', category: 'modern' },
      { q: 'This Byzantine capital city fell to Ottoman Turks on 29 May 1453, ending the Eastern Roman Empire.', a: 'Constantinople', category: 'medieval' },
      { q: 'This German field marshal surrendered at Stalingrad in February 1943, the first German field marshal captured alive.', a: 'Paulus', category: 'wars' },
      { q: 'This 1605 English conspiracy to blow up Parliament was uncovered the night before, leading to the arrest and execution of its ringleaders.', a: 'Gunpowder Plot', category: 'modern' },
    ],
    C: [
      { q: 'This Roman general and dictator was assassinated on the Ides of March, 44 BC.', a: 'Caesar', category: 'ancient' },
      { q: 'This ancient North African city was utterly destroyed by Rome at the end of the Third Punic War in 146 BC.', a: 'Carthage', category: 'ancient' },
      { q: 'This 1949 revolution led by Mao Zedong established the People\'s Republic on mainland China.', a: 'Chinese Communist Revolution', category: 'revolutions' },
      { q: 'This 1962 standoff between the US and USSR over ballistic missiles on an island nation brought the world to the brink of nuclear war.', a: 'Cuban Missile Crisis', category: 'modern' },
      { q: 'This Spanish conquistador overthrew the Aztec Empire between 1519 and 1521.', a: 'Cortés', category: 'modern' },
      { q: 'This ancient Egyptian queen allied successively with Julius Caesar and Mark Antony.', a: 'Cleopatra', category: 'ancient' },
      { q: 'This Polish astronomer published his heliocentric model of the solar system in 1543.', a: 'Copernicus', category: 'modern' },
      { q: 'This English Lord Protector ruled the Commonwealth of England after the execution of Charles I in 1649.', a: 'Cromwell', category: 'leaders' },
      { q: 'This post-1945 geopolitical standoff between the United States and the Soviet Union dominated world affairs for over four decades without direct armed conflict between the two superpowers.', a: 'Cold War', category: 'modern' },
      { q: 'This first dynasty to unify China standardised weights, measures, and writing under the first emperor.', a: 'Qin Dynasty', category: 'ancient' },
      { q: 'This Persian king, founder of the Achaemenid Empire around 550 BC, issued a famous cylinder proclaiming the rights of conquered peoples.', a: 'Cyrus the Great', category: 'ancient' },
      { q: 'This 1095 papal speech in southern France launched the First Crusade to recapture Jerusalem.', a: 'Council of Clermont', category: 'medieval' },
    ],
    D: [
      { q: 'This Roman emperor introduced the Tetrarchy in 293 AD, dividing imperial authority among four rulers.', a: 'Diocletian', category: 'ancient' },
      { q: 'This 1944 Allied amphibious assault on Normandy beaches was the largest seaborne invasion in history.', a: 'D-Day', category: 'wars' },
      { q: 'This ancient Athenian lawgiver of 621 BC is remembered for penalties so severe his name became an English adjective.', a: 'Draco', category: 'ancient' },
      { q: 'This ancient Greek philosopher, born around 460 BC, proposed that all matter is made of indivisible particles he called atoms — an idea that lay forgotten for 2,000 years before modern science confirmed it.', a: 'Democritus', category: 'ancient' },
      { q: 'This French Enlightenment philosopher edited the great Encyclopédie published between 1751 and 1772.', a: 'Diderot', category: 'modern' },
      { q: 'This 1954 battle in a Vietnamese valley decisively defeated the French colonial army and ended French Indochina.', a: 'Dien Bien Phu', category: 'wars' },
      { q: 'This English sea captain completed the second circumnavigation of the globe between 1577 and 1580.', a: 'Drake', category: 'modern' },
      { q: 'This Persian king launched the first invasion of Greece in 490 BC that was repelled at the Battle of Marathon.', a: 'Darius I', category: 'ancient' },
      { q: 'This 1940 Allied evacuation from a northern French port rescued over 330,000 troops from German encirclement and became a symbol of wartime resilience.', a: 'Dunkirk', category: 'wars' },
      { q: 'This Muslim dynasty ruling most of northern India from 1206 to 1526, based in the subcontinent\'s north, repelled Mongol invasions but was eventually overthrown by the Mughal founder Babur.', a: 'Delhi Sultanate', category: 'medieval' },
      { q: 'This Mughal emperor, reigning 1628–1658, built the Taj Mahal in memory of his wife Mumtaz Mahal.', a: 'Shah Jahan', category: 'medieval' },
    ],
    E: [
      { q: 'This English queen reigned for 44 years, presided over the defeat of the Spanish Armada, and gave her name to a literary era.', a: 'Elizabeth I', category: 'leaders' },
      { q: 'This 1863 presidential order by Abraham Lincoln declared enslaved people in Confederate states to be free.', a: 'Emancipation Proclamation', category: 'modern' },
      { q: 'This 18th-century intellectual movement championed reason, individual liberty, and challenged religious authority.', a: 'Enlightenment', category: 'modern' },
      { q: 'This ancient Mesopotamian civilisation, based in cities like Ur and Uruk, produced the world\'s earliest writing system.', a: 'Sumer', category: 'ancient' },
      { q: 'This 1957 treaty signed in Rome created the forerunner of the EU, initially uniting six Western nations in a common market.', a: 'European Economic Community', category: 'modern' },
      { q: 'This 1071 battle in eastern Anatolia saw the Seljuk Turks defeat the Byzantine Empire, opening Asia Minor to Turkish settlement.', a: 'Manzikert', category: 'medieval' },
      { q: 'This 18th-Dynasty Egyptian pharaoh controversially converted Egypt to worship of the sun disc Aten.', a: 'Akhenaten', category: 'ancient' },
      { q: 'This 313 AD proclamation by Emperor Constantine I guaranteed religious tolerance throughout the Roman Empire, effectively legalising Christianity.', a: 'Edict of Milan', category: 'ancient' },
      { q: 'This ancient wonder, a towering beacon guiding ships into an Egyptian harbour, was built by Ptolemy I around 280 BC.', a: 'Lighthouse of Alexandria', category: 'ancient' },
      { q: 'This Roman emperor issued the Edict of Milan in 313 AD legalising Christianity across the Roman Empire.', a: 'Constantine', category: 'ancient' },
      { q: 'This ancient Greek city on the Aegean coast of Asia Minor was home to one of the Seven Wonders of the Ancient World — a massive temple dedicated to the goddess Artemis.', a: 'Ephesus', category: 'ancient' },
      { q: 'This 1916 armed insurrection in Dublin against British rule, quickly suppressed but leading to the execution of its leaders, ignited the Irish independence movement.', a: 'Easter Rising', category: 'modern' },
    ],
    F: [
      { q: 'This 1789 French Revolution event saw crowds storm a Paris fortress and free its prisoners.', a: 'Fall of the Bastille', category: 'revolutions' },
      { q: 'This Spanish dictator ruled Spain from the end of the Civil War in 1939 until his death in 1975.', a: 'Franco', category: 'leaders' },
      { q: 'This 1914–1918 global conflict, also called the Great War, killed over 17 million people.', a: 'First World War', category: 'wars' },
      { q: 'This 1453 conquest by Ottoman forces ended the Byzantine Empire.', a: 'Fall of Constantinople', category: 'medieval' },
      { q: 'This 18th-century Prussian ruler who reigned 1740–1786 modernised his army and state, earning a famous superlative title.', a: 'Frederick the Great', category: 'leaders' },
      { q: 'This 1598 decree issued by Henry IV of France granted Protestant Huguenots significant civil rights, ending decades of religious warfare.', a: 'Edict of Nantes', category: 'modern' },
      { q: 'This German field marshal was defeated at El Alamein in 1942, ending Axis ambitions in North Africa.', a: 'Rommel', category: 'wars' },
      { q: 'This imperial palace complex in Beijing, built 1406–1420 under the Yongle Emperor, served as the home of 24 Chinese emperors across the Ming and Qing dynasties.', a: 'Forbidden City', category: 'medieval' },
      { q: 'This 1861–1865 American conflict was fought primarily over slavery and states\' rights.', a: 'Civil War', category: 'modern' },
      { q: 'This 1789–1799 political upheaval in France dismantled the monarchy, the aristocracy, and the Church, and gave the world the motto Liberté, Égalité, Fraternité.', a: 'French Revolution', category: 'revolutions' },
      { q: 'This medieval European social and political system, in which land was exchanged for military service, structured society into kings, lords, knights, and serfs.', a: 'Feudalism', category: 'medieval' },
      { q: 'This German revolutionary thinker co-authored the Communist Manifesto with Karl Marx in 1848.', a: 'Friedrich Engels', category: 'modern' },
    ],
    G: [
      { q: 'This Mongol ruler founded the largest contiguous land empire in history in the early 13th century.', a: 'Genghis Khan', category: 'medieval' },
      { q: 'This 1455 printing innovation by a German craftsman transformed the spread of knowledge across Europe.', a: 'Gutenberg press', category: 'modern' },
      { q: 'This Indian leader used non-violent civil disobedience to win independence from Britain, assassinated in 1948.', a: 'Gandhi', category: 'leaders' },
      { q: 'This 1215 English royal document, sealed by King John at Runnymede, was the first to place the monarch under the rule of law.', a: 'Great Charter', category: 'medieval' },
      { q: 'This 1688 English political event, in which William of Orange was invited to replace James II without a battle, is celebrated as the bloodless "revolution" that established parliamentary supremacy.', a: 'Glorious Revolution', category: 'modern' },
      { q: 'This Cold War division of a German city, erected in 1961 and torn down in 1989, became the symbol of the Iron Curtain.', a: 'Berlin Wall', category: 'modern' },
      { q: 'This 1066 invasion of England by William of Normandy began with the defeat of King Harold II at Hastings.', a: 'Norman Conquest', category: 'medieval' },
      { q: 'This Pope, born around 540 AD, dispatched Augustine to convert England and is called "the Great."', a: 'Gregory I', category: 'medieval' },
      { q: 'This Italian nationalist general whose "Expedition of the Thousand" in 1860 conquered southern Italy and handed it to Victor Emmanuel II, helping create the unified Kingdom of Italy.', a: 'Garibaldi', category: 'modern' },
      { q: 'This 1940 aerial campaign by Nazi Germany against the UK was the first major conflict fought entirely by air forces, and ended in German failure.', a: 'Battle of Britain', category: 'wars' },
      { q: 'This ancient structure, stretching thousands of kilometres, was substantially expanded under the Chinese Ming Dynasty.', a: 'Great Wall of China', category: 'ancient' },
      { q: 'This body convened by Louis XVI in May 1789 to address France\'s fiscal crisis was the last meeting of the French parliament before the Revolution.', a: 'Estates-General', category: 'revolutions' },
    ],
    H: [
      { q: 'This Carthaginian general famously crossed the Alps with war elephants to invade Italy in 218 BC.', a: 'Hannibal', category: 'ancient' },
      { q: 'This 1066 battle ended Anglo-Saxon England when Harold II was defeated by William of Normandy.', a: 'Hastings', category: 'medieval' },
      { q: 'This ancient Babylonian king who reigned c. 1792–1750 BC issued one of the earliest known law codes.', a: 'Hammurabi', category: 'ancient' },
      { q: 'This English Tudor monarch broke with the Catholic Church in 1534 to become Supreme Head of the Church of England.', a: 'Henry VIII', category: 'leaders' },
      { q: 'This Roman emperor who reigned 117–138 AD built a famous defensive wall across northern Britain.', a: 'Hadrian', category: 'ancient' },
      { q: 'This ancient Greek historian is known as the "father of history" for his Histories on the Persian Wars.', a: 'Herodotus', category: 'ancient' },
      { q: 'This 1337–1453 conflict between England and France, the longest in medieval European history, saw figures like Joan of Arc turn the tide for the French.', a: 'Hundred Years War', category: 'medieval' },
      { q: 'This Ottoman sultan who reigned 1520–1566 expanded the empire to its greatest territorial extent and is known by a grand epithet in the West.', a: 'Suleiman the Magnificent', category: 'medieval' },
      { q: 'This far-right German political movement, led by Adolf Hitler, seized power in January 1933 and ruled until 1945.', a: 'Nazi Party', category: 'modern' },
      { q: 'This Mongol ruler sacked Baghdad in 1258, ending the Abbasid Caliphate and killing the caliph, in one of history\'s most destructive conquests.', a: 'Hulagu Khan', category: 'medieval' },
      { q: 'This 1917 British foreign secretary\'s letter expressed support for a Jewish homeland in Palestine.', a: 'Balfour Declaration', category: 'modern' },
      { q: 'This 1945 atomic bomb dropped on a Japanese city on 6 August was the first nuclear weapon used in war.', a: 'Hiroshima', category: 'modern' },
    ],
    I: [
      { q: 'This 1857 uprising by sepoy soldiers and civilians against colonial rule on the subcontinent, also called the Sepoy Mutiny.', a: 'Indian Rebellion', category: 'modern' },
      { q: 'This 15th-century Spanish institution used confession, torture, and execution to enforce Catholic orthodoxy.', a: 'Inquisition', category: 'medieval' },
      { q: 'This 1979 revolution ousted Shah Mohammad Reza Pahlavi and established an Islamic Republic.', a: 'Iranian Revolution', category: 'revolutions' },
      { q: 'This Mughal emperor of India, reigning 1556–1605, promoted religious tolerance and expanded the empire greatly.', a: 'Akbar', category: 'medieval' },
      { q: 'This 1945 Pacific battle was the bloodiest assault in US Marine Corps history, fought on a volcanic island.', a: 'Iwo Jima', category: 'wars' },
      { q: 'This ancient city in northwest Anatolia was besieged for ten years in Homer\'s epic the Iliad and is identified with modern Hisarlik in Turkey.', a: 'Ilion', category: 'ancient' },
      { q: 'This 1947 division of the subcontinent along religious lines created two independent nations and triggered mass migrations and communal violence.', a: 'Indian partition', category: 'modern' },
      { q: 'This ancient Mesopotamian empire, founded around 2334 BC under the ruler Sargon, is considered the world\'s first empire.', a: 'Akkad', category: 'ancient' },
      { q: 'This ancient Persian empire, founded by Cyrus the Great around 550 BC, stretched from Egypt to Central Asia.', a: 'Achaemenid Empire', category: 'ancient' },
      { q: 'This network of paved highways radiating outward from the imperial capital symbolised the reach and unity of the ancient empire.', a: 'Roman roads', category: 'ancient' },
    ],
    J: [
      { q: 'This 1941 surprise attack on a US naval base in Hawaii brought America into World War II.', a: 'Pearl Harbor', category: 'wars' },
      { q: 'This French peasant girl led French armies to relieve the siege of Orléans in 1429, later burned at the stake.', a: 'Joan of Arc', category: 'medieval' },
      { q: 'This 1916 naval engagement in the North Sea was the largest surface fleet battle of World War I.', a: 'Jutland', category: 'wars' },
      { q: 'This ancient Canaanite city, considered one of the world\'s oldest continuously inhabited cities, fell to Israelites according to the Book of Joshua.', a: 'Jericho', category: 'ancient' },
      { q: 'This Roman emperor, son of Constantine\'s half-brother, died on campaign against Persia in 363 AD after attempting to revive the old pagan religion.', a: 'Julian', category: 'ancient' },
      { q: 'This 1799 coup by Napoleon Bonaparte, named after a month in the French Republican calendar, overthrew the Directory.', a: '18 Brumaire', category: 'revolutions' },
    ],
    K: [
      { q: 'This ancient Egyptian temple complex near Luxor, dedicated to Amun-Ra, is one of the largest religious sites ever built.', a: 'Karnak', category: 'ancient' },
      { q: 'This 1950–1953 conflict on an East Asian peninsula, fought between a UN-led coalition and communist forces backed by China, ended in an armistice rather than a peace treaty.', a: 'Korean War', category: 'modern' },
      { q: 'This 333 BC battle in modern Turkey saw Alexander the Great defeat Darius III of Persia for the first time.', a: 'Issus', category: 'ancient' },
      { q: 'This medieval kingdom centred on Angkor Wat was one of Southeast Asia\'s greatest empires, ruling much of the mainland.', a: 'Khmer Empire', category: 'medieval' },
      { q: 'This Polish king led the relief force that lifted the Ottoman siege of Vienna in September 1683.', a: 'Jan Sobieski', category: 'medieval' },
      { q: 'This 1905 sea battle where Japan annihilated Russia\'s Baltic Fleet was fought in the strait between Korea and Japan.', a: 'Tsushima', category: 'wars' },
    ],
    L: [
      { q: 'This Spartan king led 300 Spartans against the Persian army at Thermopylae in 480 BC.', a: 'Leonidas', category: 'ancient' },
      { q: 'This Bolshevik leader led the October Revolution of 1917 and founded the Soviet state.', a: 'Lenin', category: 'leaders' },
      { q: 'This 1571 naval battle off the coast of Greece was the last major engagement fought with oar-powered galleys.', a: 'Lepanto', category: 'wars' },
      { q: 'This US president issued the Emancipation Proclamation in 1863 and was assassinated in April 1865.', a: 'Lincoln', category: 'leaders' },
      { q: 'This ancient repository of scrolls in an Egyptian port city, founded under the Ptolemies, was one of the greatest centres of learning in antiquity.', a: 'Library of Alexandria', category: 'ancient' },
      { q: 'This German monk nailed 95 theses to a church door in Wittenberg in 1517, sparking the Protestant Reformation.', a: 'Luther', category: 'modern' },
      { q: 'This ancient Chinese philosopher, credited with writing the Tao Te Ching, founded Taoism.', a: 'Laozi', category: 'ancient' },
      { q: 'This 1915 sinking of a British ocean liner by a German U-boat off the Irish coast, killing 1,198 passengers including 128 Americans, helped turn US public opinion against Germany.', a: 'Lusitania', category: 'modern' },
      { q: 'This international organisation proposed by US President Wilson in 1918 aimed to prevent future wars through collective security, but was fatally weakened when the US Senate refused to join.', a: 'League of Nations', category: 'modern' },
      { q: 'This 6,000-mile strategic retreat by the Chinese Communist Party from 1934 to 1935 saved Mao\'s forces from Nationalist encirclement and became a founding myth of the People\'s Republic.', a: 'Long March', category: 'modern' },
      { q: 'This ancient Chinese philosophical school emphasising strict law and harsh punishment shaped the Qin dynasty.', a: 'Legalism', category: 'ancient' },
    ],
    M: [
      { q: 'This Ottoman sultan conquered Constantinople in 1453, ending the Byzantine Empire.', a: 'Mehmed II', category: 'medieval' },
      { q: 'This 490 BC battle saw Athens defeat a much larger Persian army on a coastal plain north of the city.', a: 'Marathon', category: 'ancient' },
      { q: 'This 1215 document sealed by King John of England limited royal authority and protected barons\' rights.', a: 'Magna Carta', category: 'medieval' },
      { q: 'This German philosopher co-wrote the Communist Manifesto in 1848 and wrote Das Kapital.', a: 'Marx', category: 'modern' },
      { q: 'This Italian Renaissance political thinker wrote "The Prince," advising rulers to prioritise power over morality.', a: 'Machiavelli', category: 'modern' },
      { q: 'This Florentine banking family dominated Renaissance politics, producing three popes and two French queens and patronising artists like Michelangelo.', a: 'Medici', category: 'modern' },
      { q: 'This catastrophic 1916 WWI battle on a French river produced over one million casualties for almost no territorial gain.', a: 'Somme', category: 'wars' },
      { q: 'This ancient Greek physician known as the "father of medicine" founded a medical school on the island of Cos.', a: 'Hippocrates', category: 'ancient' },
      { q: 'This 1948 US aid programme, named after the Secretary of State who proposed it, channelled $13 billion to rebuild post-war European economies.', a: 'Marshall Plan', category: 'modern' },
      { q: 'This 1953 agreement signed in a Korean village ended active hostilities in the Korean War.', a: 'Panmunjom Armistice', category: 'modern' },
      { q: 'This ancient Egyptian pharaoh of the 19th Dynasty fought the Hittites at Kadesh and signed history\'s earliest surviving peace treaty.', a: 'Ramesses II', category: 'ancient' },
      { q: 'This 1326 Ottoman capital city, the empire\'s first, was formerly known as Prusa in Byzantine times.', a: 'Bursa', category: 'medieval' },
    ],
    N: [
      { q: 'This French emperor was exiled to Saint Helena after his defeat at Waterloo in June 1815.', a: 'Napoleon', category: 'leaders' },
      { q: 'This 1917 Bolshevik seizure of power in Russia overthrew the Provisional Government and brought Lenin to power.', a: 'October Revolution', category: 'revolutions' },
      { q: 'This German ideology of racial superiority and authoritarian rule dominated Germany from 1933 to 1945.', a: 'Nazism', category: 'modern' },
      { q: 'This Assyrian capital city on the Tigris, capital of the Neo-Assyrian Empire, was sacked in 612 BC by a Babylonian-Median coalition.', a: 'Nineveh', category: 'ancient' },
      { q: 'This English admiral destroyed the French fleet at the Battle of the Nile in 1798, trapping Napoleon in Egypt.', a: 'Nelson', category: 'wars' },
      { q: 'This 1945 atomic bombing of a Japanese city on 9 August was the second and last nuclear attack in history.', a: 'Nagasaki', category: 'modern' },
      { q: 'This 1945–1946 international military tribunal tried Nazi leaders for war crimes in a German city.', a: 'Nuremberg Trials', category: 'modern' },
      { q: 'This 1960 wave of decolonisation saw 17 nations on one continent gain independence in a single calendar year, earning that year a famous nickname.', a: 'Year of Africa', category: 'modern' },
      { q: 'This Song-dynasty synthesis of classical Chinese moral philosophy with Buddhist and Daoist metaphysics became the dominant intellectual tradition from the 11th century onward.', a: 'Neo-Confucianism', category: 'medieval' },
      { q: 'This ancient Babylonian king, reigning c. 605–562 BC, destroyed the Temple in Jerusalem, built the Hanging Gardens, and is credited with the famous "writing on the wall" in the Bible.', a: 'Nebuchadnezzar II', category: 'ancient' },
      { q: 'This 1804 French legal code, promulgated by the emperor who rose from Corsican artillery officer to master of Europe, became the foundation of civil law in France and influenced legal systems across Europe and Latin America.', a: 'Napoleonic Code', category: 'modern' },
    ],
    O: [
      { q: 'This 1973 Arab-Israeli war, launched on a Jewish holy day, initially caught Israel by surprise.', a: 'October War', category: 'modern' },
      { q: 'This ancient trade network linking China to the Mediterranean flourished from the 2nd century BC.', a: 'Silk Road', category: 'ancient' },
      { q: 'This 1853–1856 conflict, partly fought on a Black Sea peninsula, pitted Russia against an Ottoman-British-French coalition.', a: 'Crimean War', category: 'modern' },
      { q: 'This was the Allied codename for the 1944 amphibious landings on the Normandy beaches — the largest seaborne invasion in history.', a: 'Operation Overlord', category: 'wars' },
      { q: 'This 1839–1842 conflict triggered by a narcotics trade dispute forced China to cede Hong Kong to Britain.', a: 'Opium War', category: 'modern' },
      { q: 'This Germanic king deposed Romulus Augustulus in 476 AD, traditionally marking the fall of the Western Roman Empire.', a: 'Odoacer', category: 'ancient' },
      { q: 'This vast multi-ethnic empire, founded around 1299 and lasting until 1922, at its height controlled territory stretching from Hungary to the Persian Gulf and from the Caucasus to North Africa.', a: 'Ottoman Empire', category: 'medieval' },
      { q: 'This 1898 battle near Khartoum where Kitchener\'s Anglo-Egyptian forces defeated the Mahdist army marked the climax of British imperialism in the Sudan.', a: 'Omdurman', category: 'modern' },
    ],
    P: [
      { q: 'This ancient Athenian statesman of the 5th century BC presided over the Golden Age and oversaw construction of the Parthenon.', a: 'Pericles', category: 'ancient' },
      { q: 'This July 1945 summit of Allied leaders, held in a palace near Berlin, decided the post-war occupation zones of the defeated nation.', a: 'Potsdam Conference', category: 'modern' },
      { q: 'This Spanish conquistador captured the Inca emperor Atahualpa in 1532 with fewer than 200 men and toppled the Inca Empire.', a: 'Pizarro', category: 'modern' },
      { q: 'This 1863 Pennsylvania battle was the turning point of the US Civil War, repelling Lee\'s final major northern invasion.', a: 'Gettysburg', category: 'wars' },
      { q: 'This 1526 battle in northern India where Babur defeated Ibrahim Lodi founded the Mughal dynasty.', a: 'Panipat', category: 'medieval' },
      { q: 'This ancient Greek philosopher described his ideal state in the "Republic" governed by philosopher-kings.', a: 'Plato', category: 'ancient' },
      { q: 'This ancient Greek war, 431–404 BC, pitted Athens against Sparta and its allies, ending Athenian hegemony and weakening all Greek city-states before Macedonian conquest.', a: 'Peloponnesian War', category: 'ancient' },
      { q: 'This ancient Roman city on the Bay of Naples was buried under volcanic ash after Vesuvius erupted in 79 AD.', a: 'Pompeii', category: 'ancient' },
      { q: 'This Roman author described the eruption of Vesuvius in 79 AD in vivid detail in letters to the historian Tacitus.', a: 'Pliny the Younger', category: 'ancient' },
      { q: 'This 1939 secret agreement between the Soviet Union and Germany divided Eastern Europe into spheres of influence and cleared the way for the invasion of Poland.', a: 'Molotov-Ribbentrop Pact', category: 'modern' },
      { q: 'This ancient Greek temple on the Athenian Acropolis, dedicated to the goddess Athena and completed in 438 BC, is considered the finest example of Doric architecture.', a: 'Parthenon', category: 'ancient' },
      { q: 'This French queen, widow of Louis XVI, was executed by guillotine in October 1793 during the Reign of Terror.', a: 'Marie Antoinette', category: 'revolutions' },
    ],
    Q: [
      { q: 'This Chinese dynasty, founded in 1644 and ruling until 1912, was the last imperial dynasty of China.', a: 'Qing Dynasty', category: 'medieval' },
      { q: 'This 1759 battle on the Plains of Abraham outside a Canadian fortress city secured British control of Canada from France.', a: 'Quebec', category: 'modern' },
      { q: 'This ancient Chinese philosopher, born in 551 BC, founded the school of thought called Confucianism.', a: 'Confucius', category: 'ancient' },
      { q: 'This ancient Persian highway stretching from Susa to Sardis allowed imperial couriers to cover its entire length in seven days.', a: 'Royal Road', category: 'ancient' },
      { q: 'This Islamic holy scripture, revealed to the Prophet Muhammad in the 7th century AD, is the central religious text of Islam and is written in classical Arabic.', a: 'Quran', category: 'medieval' },
      { q: 'This Chinese dynasty of 221–206 BC, whose name may be the origin of the word "China," created the first unified Chinese state.', a: 'Qin Dynasty', category: 'ancient' },
    ],
    R: [
      { q: 'This 1917 February uprising that overthrew Tsar Nicholas II ended three centuries of Romanov rule and sparked a chain of events that remade the world\'s largest country.', a: 'Russian Revolution', category: 'revolutions' },
      { q: 'This ancient city, founded according to legend in 753 BC by twin brothers, grew to dominate the Mediterranean world.', a: 'Rome', category: 'ancient' },
      { q: 'This centuries-long Christian campaign to recapture Iberia from Muslim rulers, completed in 1492 when Granada fell, shaped Spain and Portugal\'s subsequent identity.', a: 'Reconquista', category: 'medieval' },
      { q: 'This ancient republic, governed by a senate and two consuls, replaced Rome\'s monarchy in 509 BC and lasted until Julius Caesar\'s dictatorship ended it.', a: 'Roman Republic', category: 'ancient' },
      { q: 'This 1871 treaty ending the Franco-Prussian War forced France to cede Alsace-Lorraine and pay massive reparations.', a: 'Treaty of Frankfurt', category: 'modern' },
      { q: 'This 1789–1794 phase of the French Revolution, dominated by Robespierre and the Committee of Public Safety, saw thousands executed by guillotine.', a: 'Reign of Terror', category: 'revolutions' },
      { q: 'This ancient Roman road, one of the earliest and most strategically important, ran from Rome to the port of Brindisi.', a: 'Appian Way', category: 'ancient' },
      { q: 'This 1683 failed Ottoman assault on a Central European capital, repelled by a Polish-led relief army, marked the turning point of Ottoman expansion in Europe.', a: 'Siege of Vienna', category: 'medieval' },
      { q: 'This 1944 Pacific naval battle nicknamed the "Great Marianas Turkey Shoot" destroyed Japan\'s carrier aviation as an effective fighting force.', a: 'Philippine Sea', category: 'wars' },
      { q: 'This ancient military unit of approximately 5,000 soldiers, the backbone of the imperial army, was organised into cohorts and centuries.', a: 'Roman Legion', category: 'ancient' },
      { q: 'This student of Plato who tutored Alexander the Great wrote foundational works on logic, biology, and politics.', a: 'Aristotle', category: 'ancient' },
      { q: 'This Russian ruling family, founded by Michael I in 1613, produced the last tsar who abdicated in 1917 and was executed with his family in Yekaterinburg.', a: 'Romanov dynasty', category: 'modern' },
    ],
    S: [
      { q: 'This 1942–1943 siege on the Volga River, ending in Germany\'s largest surrender to that point, was a turning point of WW2.', a: 'Stalingrad', category: 'wars' },
      { q: 'This ancient Greek philosopher condemned to death by hemlock in 399 BC for impiety and corrupting Athenian youth.', a: 'Socrates', category: 'ancient' },
      { q: 'This 1956 confrontation, triggered by the nationalisation of a vital canal linking the Mediterranean and Red Sea, exposed the decline of British and French power.', a: 'Suez Crisis', category: 'modern' },
      { q: 'This Russian tsar, reigning 1682–1725, modernised Russia along Western lines and founded Saint Petersburg.', a: 'Peter the Great', category: 'leaders' },
      { q: 'This 1914 killing of Archduke Franz Ferdinand in a Bosnian capital city triggered the chain of events leading to WW1.', a: 'Sarajevo assassination', category: 'modern' },
      { q: 'This late 19th-century European competition to colonise the continent formalised at the Berlin Conference of 1884–1885 divided its territory among the major powers.', a: 'Scramble for Africa', category: 'modern' },
      { q: 'This Ottoman architect, chief imperial architect under Suleiman the Magnificent, designed hundreds of buildings including the Süleymaniye Mosque.', a: 'Sinan', category: 'medieval' },
      { q: 'This 480 BC Greek naval victory over the Persian fleet near Athens reversed the course of the Persian invasion.', a: 'Salamis', category: 'ancient' },
      { q: 'This 1588 attempted invasion of England by the Catholic superpower of the day was scattered by storms and English fire ships, ending in the loss of half its fleet.', a: 'Spanish Armada', category: 'modern' },
      { q: 'This 1957 Soviet satellite, the first artificial object to orbit the Earth, launched the space race and shocked the Western world.', a: 'Sputnik', category: 'modern' },
      { q: 'This transatlantic trafficking of enslaved Africans to the Americas, operating from the 16th to 19th century, is estimated to have forcibly transported over 12 million people.', a: 'Slave Trade', category: 'modern' },
      { q: 'This 1572 killing of thousands of Protestant Huguenots in Paris, which occurred on the feast day of an apostle, takes its name from that saint.', a: 'St Bartholomew\'s Day Massacre', category: 'modern' },
    ],
    T: [
      { q: 'This Aztec capital, built on an island in a lake in modern Mexico, was conquered by Cortés in 1521.', a: 'Tenochtitlan', category: 'ancient' },
      { q: 'This 1805 naval battle off the Spanish coast, where Nelson died, secured British naval supremacy for over a century.', a: 'Trafalgar', category: 'wars' },
      { q: 'This ancient city in modern Turkey, besieged for ten years according to Homer\'s Iliad, was also called Ilion.', a: 'Troy', category: 'ancient' },
      { q: 'This Roman emperor who made Christianity the state religion of the empire reigned from 379 to 395 AD.', a: 'Theodosius I', category: 'ancient' },
      { q: 'This 30-year European conflict beginning in 1618 as a religious war ended with the Peace of Westphalia in 1648.', a: 'Thirty Years\' War', category: 'wars' },
      { q: 'This ancient city on the Bosphorus, founded as a Roman capital in 330 AD by Constantine I, served as the heart of the Byzantine Empire for over a millennium.', a: 'Constantinople', category: 'ancient' },
      { q: 'This 480 BC mountain pass where 300 Spartans died holding back the Persian army is called "hot gates" in Greek.', a: 'Thermopylae', category: 'ancient' },
      { q: 'This 1854 British cavalry assault directly into Russian artillery in a Crimean valley became a byword for military futility and was immortalised in verse by Tennyson.', a: 'Charge of the Light Brigade', category: 'wars' },
      { q: 'This wave of liberal uprisings that swept Europe in a single year, from Paris to Budapest, became known as the Spring of Nations.', a: 'Revolutions of 1848', category: 'revolutions' },
      { q: 'This 1989 pro-democracy protest in Beijing, centred on a large public square, was violently suppressed by the Chinese military in June.', a: 'Tiananmen Square', category: 'modern' },
      { q: 'This ancient Chinese dynasty of 618–907 AD is often considered China\'s golden age of arts and foreign contact.', a: 'Tang Dynasty', category: 'medieval' },
      { q: 'This 1689 English law guaranteeing freedom of worship for Protestant dissenters followed the Glorious Revolution.', a: 'Toleration Act', category: 'modern' },
    ],
    U: [
      { q: 'This ancient Sumerian city in modern Iraq, associated with the biblical patriarch Abraham, was one of the world\'s earliest cities.', a: 'Ur', category: 'ancient' },
      { q: 'This 1776 document adopted by the Continental Congress formally announced the thirteen colonies\' separation from the British Crown, drafted primarily by Thomas Jefferson.', a: 'Declaration of Independence', category: 'modern' },
      { q: 'This Soviet space programme launched the first human, Yuri Gagarin, into orbit in April 1961.', a: 'Vostok programme', category: 'modern' },
      { q: 'This ancient Mesopotamian king, hero of an epic written around 2100 BC, built the walls of Uruk and sought immortality.', a: 'Gilgamesh', category: 'ancient' },
      { q: 'This 1918 peace framework proposed by the US president included 14 points and envisioned a League of Nations.', a: 'Fourteen Points', category: 'modern' },
      { q: 'This 1783 accord that ended the American Revolutionary War was signed in the French capital and formally recognised the new republic.', a: 'Treaty of Paris', category: 'modern' },
    ],
    V: [
      { q: 'This 1919 peace treaty that formally ended World War I imposed crippling reparations and territorial losses on Germany.', a: 'Versailles', category: 'modern' },
      { q: 'This Norse seafaring culture, originating in Scandinavia, raided and settled across Europe from the 8th to 11th centuries.', a: 'Vikings', category: 'medieval' },
      { q: 'This 1955–1975 conflict in Southeast Asia ended with the fall of Saigon and reunification under Communism.', a: 'Vietnam War', category: 'modern' },
      { q: 'This Italian city-state, built on a lagoon, dominated Mediterranean trade in the medieval period and gave its name to a style of glass and a carnival mask tradition.', a: 'Venice', category: 'medieval' },
      { q: 'This French philosopher and writer of the Enlightenment, author of "Candide," championed tolerance and reason.', a: 'Voltaire', category: 'modern' },
      { q: 'This ancient Roman poet wrote the "Aeneid," the founding epic myth tracing Rome\'s origins to the Trojan War.', a: 'Virgil', category: 'ancient' },
      { q: 'This 1683 Ottoman encirclement of a Central European capital was broken by a Polish-led relief army charging from the Kahlenberg ridge.', a: 'Vienna siege', category: 'medieval' },
      { q: 'This British queen, reigning 1837–1901, oversaw the height of the British Empire and gave her name to an era.', a: 'Victoria', category: 'leaders' },
    ],
    W: [
      { q: 'This 1815 battle in modern Belgium definitively ended Napoleon\'s rule during the Hundred Days.', a: 'Waterloo', category: 'wars' },
      { q: 'This 1066 Norman duke invaded England, defeated Harold II, and transformed English culture and language.', a: 'William the Conqueror', category: 'medieval' },
      { q: 'This 1648 series of treaties ended the Thirty Years\' War and established the principle of sovereign equality of states.', a: 'Peace of Westphalia', category: 'modern' },
      { q: 'This 1939–1945 global conflict, the deadliest in human history, ended with the defeat of Germany and Japan.', a: 'World War II', category: 'wars' },
      { q: 'This American Founding Father commanded the Continental Army and served as the first US president.', a: 'Washington', category: 'leaders' },
      { q: 'This 19th-century movement, which held a landmark convention in New York state in 1848, campaigned for the right to vote for half the population, achieving its goal in most Western countries by the early 20th century.', a: 'Women\'s suffrage', category: 'modern' },
      { q: 'This Dutch prince, invited by English parliamentarians in 1688 to replace the Catholic King James II, landed with an army and became King of England without a battle.', a: 'William of Orange', category: 'modern' },
      { q: 'This US president who led America through World War I proposed the Fourteen Points peace plan in 1918.', a: 'Wilson', category: 'leaders' },
      { q: 'This 1919 German republican government, named after the Thuringian city where its constitution was drafted, collapsed when Hitler became Chancellor in 1933.', a: 'Weimar Republic', category: 'modern' },
      { q: 'This 1914–1918 global conflict, beginning after the assassination of Archduke Franz Ferdinand, killed over 17 million.', a: 'World War I', category: 'wars' },
      { q: 'This 1955 Soviet-led military alliance among Eastern European communist states was formed in response to West Germany joining NATO.', a: 'Warsaw Pact', category: 'modern' },
    ],
    X: [
      { q: 'This Persian king launched a massive invasion of Greece in 480 BC, burning Athens before being defeated at Salamis.', a: 'Xerxes', category: 'ancient' },
      { q: 'This ancient Chinese city, formerly called Chang\'an, served as the Han and Tang dynasty capital and the eastern terminus of the Silk Road.', a: 'Xi\'an', category: 'ancient' },
      { q: 'This ancient Greek general and historian wrote the "Anabasis," an account of a 10,000-man Greek army retreating through Persia.', a: 'Xenophon', category: 'ancient' },
      { q: 'This Tang dynasty Chinese emperor, reigning 712–756 AD, presided over the dynasty\'s cultural golden age before the An Lushan Rebellion weakened imperial authority.', a: 'Xuanzong', category: 'medieval' },
      { q: 'This 1900 Chinese uprising by a secret society sought to expel foreign influence and was suppressed by an international alliance.', a: 'Boxer Rebellion', category: 'modern' },
    ],
    Y: [
      { q: 'This 1945 conference in Crimea between Roosevelt, Churchill, and Stalin shaped the post-war world order.', a: 'Yalta', category: 'modern' },
      { q: 'This Japanese admiral who planned the Pearl Harbor attack was killed in 1943 when US fighters ambushed his aircraft.', a: 'Yamamoto', category: 'wars' },
      { q: 'This 1781 Virginia battle, ending with Cornwallis\'s surrender, effectively secured American independence.', a: 'Yorktown', category: 'modern' },
      { q: 'This 1973 war launched by Egypt and Syria against Israel on a Jewish holy day began the fourth Arab-Israeli war.', a: 'Yom Kippur War', category: 'modern' },
      { q: 'This Slavic federation of communist states, formed after World War II, dissolved violently in the early 1990s.', a: 'Yugoslavia', category: 'modern' },
      { q: 'This ancient Chinese dynasty, c. 1600–1046 BC, is the earliest confirmed by archaeological evidence, ruling from the city of Anyang.', a: 'Shang Dynasty', category: 'ancient' },
    ],
    Z: [
      { q: 'This 19th-century South African kingdom defeated the British at Isandlwana in 1879 in one of the worst British colonial defeats.', a: 'Zulu Kingdom', category: 'modern' },
      { q: 'This ancient Chinese dynasty of c. 1046–256 BC, the longest in Chinese history, was the era of Confucius and Laozi.', a: 'Zhou Dynasty', category: 'ancient' },
      { q: 'This 1917 intercepted German diplomatic message proposed a military alliance with a southern neighbour of the US in exchange for help reclaiming lost territory, accelerating American entry into WWI.', a: 'Zimmermann Telegram', category: 'modern' },
      { q: 'This ancient Persian prophet founded a dualistic religion whose ideas of good versus evil influenced Judaism, Christianity, and Islam.', a: 'Zoroaster', category: 'ancient' },
      { q: 'This Chinese Communist revolutionary and close ally of Mao served as the first Premier of the People\'s Republic until 1976.', a: 'Zhou Enlai', category: 'leaders' },
      { q: 'This ancient Mesopotamian stepped temple tower, such as those found at Ur and Babylon, served as a sacred platform connecting earth and heaven in Sumerian religion.', a: 'Ziggurat', category: 'ancient' },
    ],
  },
};
