import type { RawPack } from '../core/packs';

export const horrorMoviesPack: RawPack = {
  id: 'horror-movies',
  name: 'Horror and Monsters',
  description: 'Classic monsters, masked slashers, haunted houses and the directors behind them.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'teen',
  emoji: '🧟',
  accent: '#7f1d1d',
  letters: {
    A: [
      { q: 'The Long Island town in the title of a famous 1979 haunted house film based on the Lutz family.', a: 'Amityville' },
      { q: 'Ridley Scott\'s 1979 film set aboard the towing ship Nostromo.', a: 'Alien' },
      { q: 'The possessed doll from The Conjuring who was given her own film series.', a: 'Annabelle' },
      { q: 'Takashi Miike\'s 1999 Japanese film about a widower who holds casting sessions to find a wife.', a: 'Audition' },
      { q: 'Bruce Campbell\'s chainsaw-handed hero of the Evil Dead films (first name).', a: 'Ash' },
      { q: 'James Cameron\'s 1986 sequel that sends colonial marines to the moon LV-426.', a: 'Aliens' },
      { q: 'Italian director of Suspiria and Deep Red (surname).', a: 'Argento' },
      { q: '1990 creature feature about deadly spiders loose in a small California town.', a: 'Arachnophobia' },
      { q: 'Director of Hereditary and Midsommar (surname).', a: 'Aster' },
    ],
    B: [
      { q: 'Hungarian-born actor who played the count in the 1931 Universal film of Dracula.', a: 'Bela Lugosi', alt: ['Lugosi'] },
      { q: 'Tim Burton\'s 1988 comedy about a bio-exorcist whose name must be said three times.', a: 'Beetlejuice' },
      { q: 'The roadside lodging run by Norman in Hitchcock\'s 1960 film.', a: 'Bates Motel' },
      { q: '1999 found-footage film about student film-makers lost in Maryland\'s Black Hills woods.', a: 'The Blair Witch Project' },
      { q: '2014 Australian film about a sinister top-hatted figure who steps out of a storybook.', a: 'The Babadook' },
      { q: 'Hitchcock\'s 1963 film about attacks on the residents of Bodega Bay.', a: 'The Birds' },
      { q: 'Irish author who published the novel Dracula in 1897.', a: 'Bram Stoker', alt: ['Stoker'] },
      { q: 'English actor who played the creature in the 1931 film of Frankenstein.', a: 'Boris Karloff', alt: ['Karloff'] },
      { q: 'Nickname the crew gave the mechanical shark in Jaws.', a: 'Bruce' },
      { q: '2021 film in which Ethan Hawke plays a masked kidnapper called The Grabber.', a: 'The Black Phone' },
      { q: '2018 Netflix film in which Sandra Bullock\'s character must stay blindfolded outdoors.', a: 'Bird Box' },
      { q: '1935 Universal sequel in which Doctor Pretorius helps build a mate for the monster.', a: 'Bride of Frankenstein' },
    ],
    C: [
      { q: 'Stephen King\'s first published novel, about a telekinetic teenager at a prom.', a: 'Carrie' },
      { q: 'Stephen King novel about a friendly Saint Bernard turned rabid.', a: 'Cujo' },
      { q: 'Hook-handed spirit summoned by saying his name five times into a mirror.', a: 'Candyman' },
      { q: 'The Good Guy doll possessed by the soul of Charles Lee Ray.', a: 'Chucky' },
      { q: 'Stephen King novel about a haunted 1958 Plymouth Fury.', a: 'Christine' },
      { q: 'Neil Gaiman story about a girl who finds an Other Mother with buttons for eyes.', a: 'Coraline' },
      { q: '2012 Drew Goddard film that reveals a secret facility manipulating five doomed teenagers.', a: 'The Cabin in the Woods' },
      { q: 'Canadian director of Videodrome and the 1986 remake of The Fly (surname).', a: 'Cronenberg' },
      { q: '2013 James Wan film that introduced paranormal investigators Ed and Lorraine.', a: 'The Conjuring' },
      { q: 'The name given to the vampire in Murnau\'s 1922 silent film.', a: 'Count Orlok', alt: ['Orlok'] },
      { q: '1954 Universal film about a Gill-man discovered on an Amazon expedition.', a: 'Creature from the Black Lagoon' },
      { q: 'Director and synthesizer composer of the 1978 film Halloween (surname).', a: 'Carpenter' },
      { q: 'The leather-clad beings summoned by the Lament Configuration puzzle box.', a: 'Cenobites' },
    ],
    D: [
      { q: 'The Transylvanian count at the centre of Bram Stoker\'s most famous novel.', a: 'Dracula' },
      { q: 'George Romero\'s 1978 sequel in which survivors barricade themselves inside a shopping mall.', a: 'Dawn of the Dead' },
      { q: 'The name of the antichrist child in The Omen.', a: 'Damien' },
      { q: '2005 Neil Marshall film about women caving in the Appalachians who meet pale crawlers.', a: 'The Descent' },
      { q: '1973 Nicolas Roeg film set in Venice, remembered for a small red raincoat.', a: 'Don\'t Look Now' },
      { q: 'Mexican director of Pan\'s Labyrinth and Crimson Peak (surname).', a: 'Del Toro' },
      { q: 'Stephen King novel about a man who wakes from a coma able to see people\'s futures.', a: 'The Dead Zone' },
      { q: 'The London physician whose potion unleashes a brutal second self.', a: 'Doctor Jekyll', alt: ['Jekyll', 'Dr Jekyll'] },
      { q: 'Argento\'s 1975 giallo about a pianist who witnesses a murder in Rome.', a: 'Deep Red' },
      { q: '2019 sequel that follows a grown-up Danny Torrance and a girl named Abra.', a: 'Doctor Sleep' },
      { q: '2009 Sam Raimi film about a loan officer cursed by an old woman.', a: 'Drag Me to Hell' },
    ],
    E: [
      { q: 'Sam Raimi\'s 1981 debut about students who play a tape found in a cellar.', a: 'The Evil Dead' },
      { q: '1973 William Friedkin film about the possession of young Regan MacNeil.', a: 'The Exorcist' },
      { q: 'David Lynch\'s 1977 black-and-white debut about Henry and a strange baby.', a: 'Eraserhead' },
      { q: 'The suburban address haunted by Freddy Krueger in the film titles.', a: 'Elm Street' },
      { q: 'The centuries-old child vampire in Let the Right One In.', a: 'Eli' },
      { q: '1997 film about a rescue crew boarding a ship that returned from another dimension.', a: 'Event Horizon' },
      { q: 'Cassandra Peterson\'s beehive-haired Mistress of the Dark.', a: 'Elvira' },
      { q: 'American writer of The Fall of the House of Usher and The Raven.', a: 'Edgar Allan Poe', alt: ['Poe'] },
      { q: '1960 French film about a surgeon trying to restore his daughter\'s features.', a: 'Eyes Without a Face' },
      { q: 'Hungarian countess of the 16th century tied to grisly legends about young servants.', a: 'Elizabeth Bathory', alt: ['Bathory'] },
      { q: 'Director of The Witch and the 2024 remake of Nosferatu (surname).', a: 'Eggers' },
    ],
    F: [
      { q: 'Mary Shelley\'s 1818 novel about a student who assembles a creature from dead tissue.', a: 'Frankenstein' },
      { q: 'Striped-sweater dream killer with knives fixed to his glove.', a: 'Freddy Krueger', alt: ['Krueger'] },
      { q: 'Genre term for the last surviving young woman who confronts the killer.', a: 'Final girl' },
      { q: '1986 Cronenberg remake in which Seth Brundle steps into a teleporter.', a: 'The Fly' },
      { q: '1980 film about a summer camp at Crystal Lake reopening after a drowning.', a: 'Friday the 13th' },
      { q: '1980 Carpenter film in which vengeful mariners return to Antonio Bay.', a: 'The Fog' },
      { q: 'Tim Burton stop-motion film about a boy who revives his dog Sparky.', a: 'Frankenweenie' },
      { q: 'Tod Browning\'s 1932 film cast with real sideshow performers.', a: 'Freaks' },
      { q: 'Italian director of Zombi 2 who was nicknamed the Godfather of Gore (surname).', a: 'Fulci' },
      { q: 'Stephen King novel about a girl named Charlie McGee who can set things alight.', a: 'Firestarter' },
      { q: 'Director of Doctor Sleep, Hush and The Haunting of Hill House (surname).', a: 'Flanagan' },
    ],
    G: [
      { q: 'Toho\'s 1954 reptilian giant awakened by nuclear testing in the Pacific.', a: 'Godzilla', alt: ['Gojira'] },
      { q: '1984 comedy about New York parapsychologists who battle the god Gozer.', a: 'Ghostbusters' },
      { q: 'Jordan Peele\'s 2017 directorial debut about a visit to the Armitage family.', a: 'Get Out' },
      { q: '1984 film with three rules about water, sunlight and feeding after midnight.', a: 'Gremlins' },
      { q: 'Surname of the twin girls who appear in the Overlook Hotel corridor.', a: 'Grady' },
      { q: 'Italian term for the stylish, lurid murder mysteries of the 1960s and 1970s.', a: 'Giallo' },
      { q: 'The white-masked phone caller who stalks Woodsboro in the Scream films.', a: 'Ghostface' },
      { q: 'Clay figure of Jewish folklore animated to protect the Jews of Prague.', a: 'Golem' },
      { q: '2004 American remake of Ju-On starring Sarah Michelle Gellar.', a: 'The Grudge' },
      { q: 'The little boy in the yellow raincoat who meets a clown at a storm drain in Derry.', a: 'Georgie' },
    ],
    H: [
      { q: 'Carpenter\'s 1978 film that introduced a masked killer stalking babysitters.', a: 'Halloween' },
      { q: 'The fictional Illinois hometown that Michael Myers keeps returning to.', a: 'Haddonfield' },
      { q: '1987 Clive Barker film that introduced a nail-studded Cenobite leader.', a: 'Hellraiser' },
      { q: 'British director of Psycho, Vertigo and The Birds (surname).', a: 'Hitchcock' },
      { q: '2018 Ari Aster film about the Graham family and a demon named Paimon.', a: 'Hereditary' },
      { q: '2005 Eli Roth film about backpackers lured to a Slovakian guest house.', a: 'Hostel' },
      { q: 'The brutal second self unleashed by a Victorian doctor\'s potion.', a: 'Hyde' },
      { q: '2016 Mike Flanagan film about a deaf writer besieged in her woodland home.', a: 'Hush' },
      { q: 'The reckless medical student of Lovecraft\'s reanimation stories.', a: 'Herbert West' },
      { q: '1953 Vincent Price film about a sculptor whose museum burns down.', a: 'House of Wax' },
      { q: 'British studio famous for its Technicolor Dracula films with Christopher Lee.', a: 'Hammer' },
      { q: 'The cultured cannibal psychiatrist created by Thomas Harris.', a: 'Hannibal Lecter', alt: ['Lecter'] },
    ],
    I: [
      { q: 'H G Wells novel about Griffin, a scientist who makes himself unseen.', a: 'The Invisible Man' },
      { q: '2010 James Wan film about an astral plane called The Further.', a: 'Insidious' },
      { q: '2014 film about a curse passed on by intimacy and pursued by a walking figure.', a: 'It Follows' },
      { q: 'Stock name for the hunchbacked assistant of a mad scientist.', a: 'Igor' },
      { q: '1956 film about seed pods replacing the people of Santa Mira.', a: 'Invasion of the Body Snatchers' },
      { q: 'Richard Matheson novel about the last healthy man in a city of the infected.', a: 'I Am Legend' },
      { q: 'Decaying Lovecraft seaport whose residents have a fishy look about them.', a: 'Innsmouth' },
      { q: 'The revived priest played by Boris Karloff in the 1932 Universal mummy film.', a: 'Imhotep' },
      { q: '1994 film starring Tom Cruise as Lestat and Brad Pitt as Louis.', a: 'Interview with the Vampire' },
      { q: '1961 film of Henry James\' novella The Turn of the Screw, starring Deborah Kerr.', a: 'The Innocents' },
    ],
    J: [
      { q: '1975 Spielberg film about a shark terrorising Amity Island.', a: 'Jaws' },
      { q: 'Hockey-masked killer who returns again and again to Camp Crystal Lake.', a: 'Jason Voorhees', alt: ['Voorhees'] },
      { q: 'Director who scored his own 1978 slasher on synthesizers and later made The Thing.', a: 'John Carpenter' },
      { q: 'Actress who first played Laurie Strode in 1978 and returned decades later.', a: 'Jamie Lee Curtis' },
      { q: 'The frustrated writer who takes a caretaker job at the Overlook Hotel.', a: 'Jack Torrance', alt: ['Torrance'] },
      { q: 'Comedian turned director of Get Out, Us and Nope.', a: 'Jordan Peele', alt: ['Peele'] },
      { q: 'Nickname of John Kramer, the trap-building killer of the Saw films.', a: 'Jigsaw' },
      { q: 'Actor who played the caretaker in Kubrick\'s 1980 adaptation of The Shining.', a: 'Jack Nicholson', alt: ['Nicholson'] },
    ],
    K: [
      { q: '1933 film about a giant ape brought to New York from Skull Island.', a: 'King Kong' },
      { q: 'Director of the 1980 film version of The Shining (surname).', a: 'Kubrick' },
      { q: 'The long-haired vengeful spirit of the Ju-On films (first name).', a: 'Kayako' },
      { q: 'Horned Alpine companion of Saint Nicholas who punishes badly behaved children.', a: 'Krampus' },
      { q: 'The Nostromo crew member who first hosts the creature in Alien.', a: 'Kane' },
      { q: 'Giant many-armed sea monster of Scandinavian legend.', a: 'Kraken' },
      { q: 'The young woman who first outwits Pinhead in the 1987 film (first name).', a: 'Kirsty' },
    ],
    L: [
      { q: 'Providence author who created Cthulhu and the Necronomicon (surname).', a: 'Lovecraft' },
      { q: 'The babysitter stalked by Michael Myers in the 1978 film.', a: 'Laurie Strode' },
      { q: 'Mask-wearing chainsaw killer of a 1974 Tobe Hooper classic.', a: 'Leatherface' },
      { q: 'The elegant vampire who turns Louis in Anne Rice\'s novel.', a: 'Lestat' },
      { q: 'Long-necked creature said to live in a deep Scottish lake near Inverness.', a: 'Loch Ness Monster' },
      { q: 'Clinical-sounding term for the transformation of a person into a wolf.', a: 'Lycanthropy' },
      { q: 'The puzzle box that opens the way for the Cenobites.', a: 'Lament Configuration' },
      { q: '2008 Swedish film about a bullied boy and his pale new neighbour.', a: 'Let the Right One In' },
      { q: 'Silent film star called the Man of a Thousand Faces, famed for The Phantom of the Opera.', a: 'Lon Chaney', alt: ['Chaney'] },
    ],
    M: [
      { q: 'The masked killer who escapes Smith\'s Grove sanitarium in the 1978 film.', a: 'Michael Myers', alt: ['Myers'] },
      { q: '1932 Universal film about a revived Egyptian priest searching for a lost love.', a: 'The Mummy' },
      { q: 'Author who conceived Frankenstein during a rainy 1816 summer near Geneva.', a: 'Mary Shelley', alt: ['Shelley'] },
      { q: '2019 Ari Aster film about a nine-day festival in a remote Swedish commune.', a: 'Midsommar' },
      { q: 'Stephen King novel about writer Paul Sheldon and his number one fan Annie Wilkes.', a: 'Misery' },
      { q: 'The pale matriarch of the Addams Family.', a: 'Morticia' },
      { q: 'Winged red-eyed creature reported around Point Pleasant, West Virginia.', a: 'Mothman' },
      { q: 'German director of the 1922 silent vampire film Nosferatu (surname).', a: 'Murnau' },
      { q: 'The office worker who checks into a roadside motel with stolen money in Psycho.', a: 'Marion Crane' },
      { q: 'Stephen King novella about shoppers trapped in a supermarket by unseen creatures.', a: 'The Mist' },
    ],
    N: [
      { q: 'Murnau\'s 1922 unauthorised film version of Bram Stoker\'s vampire novel.', a: 'Nosferatu' },
      { q: 'Romero\'s 1968 black-and-white film about strangers besieged in a Pennsylvania farmhouse.', a: 'Night of the Living Dead' },
      { q: 'The Book of the Dead read aloud in the Evil Dead films.', a: 'Necronomicon' },
      { q: 'The taxidermy-loving motel keeper of Hitchcock\'s 1960 film.', a: 'Norman Bates' },
      { q: '1984 Wes Craven film that introduced a killer who attacks teenagers in their sleep.', a: 'A Nightmare on Elm Street' },
      { q: 'Jordan Peele\'s 2022 film about a horse ranch and something hiding in the clouds.', a: 'Nope' },
      { q: 'The teenager who first fights back against Freddy Krueger in 1984.', a: 'Nancy Thompson' },
      { q: 'The Conjuring spin-off about a demon named Valak in a Romanian abbey.', a: 'The Nun' },
    ],
    O: [
      { q: '1976 film about a diplomat\'s adopted son who bears the mark 666.', a: 'The Omen' },
      { q: 'The snowbound Colorado resort where the Torrance family spends a winter.', a: 'Overlook Hotel' },
      { q: '2001 Nicole Kidman film set in a darkened house on Jersey after the war.', a: 'The Others' },
      { q: '2009 film about a couple who adopt a girl calling herself Esther.', a: 'Orphan' },
      { q: 'Lettered board used in many films to contact the spirits of the dead.', a: 'Ouija' },
      { q: 'Actor who played the count in Coppola\'s 1992 version of Dracula (surname).', a: 'Oldman' },
    ],
    P: [
      { q: 'Hitchcock\'s 1960 film remembered for a shower scene and a shrieking violin score.', a: 'Psycho' },
      { q: 'Cenobite leader whose head is studded with nails.', a: 'Pinhead' },
      { q: '1982 film about a suburban family whose daughter is pulled into a television.', a: 'Poltergeist' },
      { q: 'The dancing clown who lures children in Derry, Maine.', a: 'Pennywise' },
      { q: 'Del Toro\'s 2006 film about a girl, a faun and Franco\'s Spain.', a: 'Pan\'s Labyrinth' },
      { q: 'Masked musical figure who haunts the cellars of the Paris opera house.', a: 'The Phantom of the Opera' },
      { q: 'Hammer star who often played the vampire hunter Van Helsing.', a: 'Peter Cushing', alt: ['Cushing'] },
      { q: '2007 found-footage film shot mostly by a camera left running in a bedroom.', a: 'Paranormal Activity' },
      { q: 'Stephen King novel about a burial ground behind the Creed family\'s new home.', a: 'Pet Sematary' },
      { q: '1960 Michael Powell film about a cameraman that wrecked the director\'s reputation.', a: 'Peeping Tom' },
    ],
    Q: [
      { q: 'British rocket scientist hero of Hammer\'s 1950s science-horror serials (surname).', a: 'Quatermass' },
      { q: 'The grizzled shark hunter who captains the Orca in Jaws.', a: 'Quint' },
      { q: '2018 John Krasinski film in which a family must live in near silence.', a: 'A Quiet Place' },
    ],
    R: [
      { q: '1968 Roman Polanski film set in New York\'s Bramford apartment building.', a: 'Rosemary\'s Baby' },
      { q: '1998 Japanese film about a videotape that kills whoever watches it.', a: 'Ringu', alt: ['The Ring'] },
      { q: 'Director whose 1968 farmhouse film defined the modern zombie (surname).', a: 'Romero' },
      { q: 'The possessed twelve-year-old at the centre of The Exorcist (first name).', a: 'Regan' },
      { q: '1985 film about Herbert West and his glowing green serum.', a: 'Re-Animator' },
      { q: 'Dracula\'s insect-eating servant in Stoker\'s novel.', a: 'Renfield' },
      { q: 'The warrant officer who is the sole human survivor of the Nostromo.', a: 'Ripley' },
      { q: 'Director of the Evil Dead trilogy and Drag Me to Hell (surname).', a: 'Raimi' },
      { q: 'Musician turned film-maker who remade Halloween in 2007.', a: 'Rob Zombie' },
      { q: '2007 Spanish found-footage film about a news crew sealed inside a Barcelona apartment block.', a: 'Rec' },
    ],
    S: [
      { q: 'Kubrick\'s 1980 film about a family alone in a haunted mountain hotel.', a: 'The Shining' },
      { q: '1996 Wes Craven film that mocked the rules of slashers while obeying them.', a: 'Scream' },
      { q: '2004 film that opens with two men chained in a filthy bathroom.', a: 'Saw' },
      { q: 'Argento\'s 1977 film set at a German dance academy run by a coven.', a: 'Suspiria' },
      { q: '1991 film in which Clarice Starling hunts a killer called Buffalo Bill.', a: 'The Silence of the Lambs' },
      { q: 'Maine author of Carrie, Misery and Pet Sematary.', a: 'Stephen King' },
      { q: '1999 Shyamalan film about a boy who sees dead people.', a: 'The Sixth Sense' },
      { q: 'Stephen King novel about a vampire taking over a small Maine town.', a: 'Salem\'s Lot' },
      { q: 'The girl who crawls out of a well in the American version of Ringu.', a: 'Samara' },
      { q: 'Washington Irving\'s village terrorised by a headless horseman.', a: 'Sleepy Hollow' },
      { q: 'Scottish author of Strange Case of Doctor Jekyll and Mister Hyde (surname).', a: 'Stevenson' },
      { q: 'Subgenre name for films in which a masked killer picks off young people one by one.', a: 'Slasher' },
    ],
    T: [
      { q: '1974 Tobe Hooper film about travellers who meet a cannibal family in rural America.', a: 'The Texas Chain Saw Massacre', alt: ['Texas Chainsaw Massacre'] },
      { q: 'Carpenter\'s 1982 film about a shape-shifter at an Antarctic research station.', a: 'The Thing' },
      { q: 'Director of Poltergeist and a 1974 chainsaw classic.', a: 'Tobe Hooper', alt: ['Hooper'] },
      { q: 'Romanian region where Bram Stoker placed his count\'s castle.', a: 'Transylvania' },
      { q: '1955 film about a giant spider loose in the Arizona desert.', a: 'Tarantula' },
      { q: '1990 film about underground creatures called graboids in Perfection, Nevada.', a: 'Tremors' },
      { q: 'Actor who played Pennywise in the 1990 television version of It.', a: 'Tim Curry' },
      { q: '2022 Australian film about an embalmed ceramic hand used to contact spirits.', a: 'Talk to Me' },
    ],
    U: [
      { q: 'Hollywood studio behind the 1930s cycle of monster pictures.', a: 'Universal' },
      { q: 'General term for a being that is neither alive nor at rest in its grave.', a: 'Undead' },
      { q: 'The bald, light-bulb-swallowing relative in the Addams Family.', a: 'Uncle Fester', alt: ['Fester'] },
    ],
    V: [
      { q: 'Blood-drinking creature of folklore said to be repelled by garlic and sunlight.', a: 'Vampire' },
      { q: 'The Dutch professor who leads the hunt for Dracula in Stoker\'s novel.', a: 'Van Helsing' },
      { q: 'Velvet-voiced actor who narrated the closing rap of Michael Jackson\'s Thriller.', a: 'Vincent Price' },
      { q: 'The demon who appears in the habit of a nun in The Conjuring films.', a: 'Valak' },
      { q: 'Cronenberg\'s 1983 film about a television signal that warps its viewers.', a: 'Videodrome' },
      { q: 'Wallachian ruler of the 1400s often cited as inspiration for Stoker\'s count.', a: 'Vlad the Impaler', alt: ['Vlad Tepes'] },
      { q: '1960 film about blond, glowing-eyed children born in the English town of Midwich.', a: 'Village of the Damned' },
    ],
    W: [
      { q: 'Human who takes on a beast\'s shape under the light of a full moon.', a: 'Werewolf' },
      { q: 'Director who created Freddy Krueger and later the Scream series.', a: 'Wes Craven', alt: ['Craven'] },
      { q: '1941 Universal film with Lon Chaney Junior as the cursed Larry Talbot.', a: 'The Wolf Man' },
      { q: '1973 film about a policeman investigating a disappearance on Summerisle.', a: 'The Wicker Man' },
      { q: '2015 Robert Eggers film about a Puritan family exiled to the New England woods.', a: 'The Witch' },
      { q: 'Director of the 1931 Frankenstein and its 1935 sequel (surname).', a: 'Whale' },
      { q: 'Surname of the real paranormal investigators Ed and Lorraine.', a: 'Warren' },
      { q: 'Gaunt, hungry forest spirit of Algonquian legend.', a: 'Wendigo' },
    ],
    X: [
      { q: 'The proper name of the acid-blooded creature that stalks the Nostromo crew.', a: 'Xenomorph' },
      { q: 'Hammer\'s 1956 film about radioactive mud rising from a Scottish crater.', a: 'X the Unknown' },
    ],
    Y: [
      { q: 'Mel Brooks\' 1974 parody starring Gene Wilder as a reluctant heir to a laboratory.', a: 'Young Frankenstein' },
      { q: 'Shaggy ape-like creature said to roam the Himalayan snows.', a: 'Yeti' },
    ],
    Z: [
      { q: 'Reanimated corpse of Haitian folklore that became a film staple.', a: 'Zombie' },
      { q: '2009 comedy in which a nervous survivor called Columbus follows a list of rules.', a: 'Zombieland' },
      { q: 'The gatekeeper demon that possesses Dana Barrett in Ghostbusters.', a: 'Zuul' },
    ],
  },
};
