import type { RawPack } from '../core/packs';

export const internetMemesPack: RawPack = {
  id: 'internet-memes',
  name: 'Internet and Memes',
  description: 'Viral videos, old web nostalgia, slang and the people who broke the internet.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'teen',
  emoji: '📱',
  accent: '#c026d3',
  letters: {
    A: [
      { q: 'Dial-up service whose cheerful You have got mail greeting defined the 1990s web.', a: 'AOL' },
      { q: 'Popular search engine of the late 1990s that Yahoo eventually shut down.', a: 'AltaVista' },
      { q: 'Pictures drawn purely from keyboard characters, common on old bulletin boards.', a: 'ASCII art', alt: ['ASCII'] },
      { q: 'Google\'s mobile operating system, the main rival to iOS.', a: 'Android' },
      { q: 'Chat shorthand telling people you have stepped away from your computer.', a: 'AFK' },
      { q: 'The picture or cartoon figure that stands in for you on a profile.', a: 'Avatar' },
      { q: 'Search engine that let you type whole questions to a fictional butler.', a: 'Ask Jeeves', alt: ['Jeeves'] },
      { q: 'Mobile hit from 2009 in which you catapult small creatures at green pigs.', a: 'Angry Birds' },
      { q: 'Party game of 2020 about finding the impostor aboard a spaceship.', a: 'Among Us' },
      { q: 'Browser extension that stops advertising from loading on a page.', a: 'Adblock' },
      { q: 'Three-letter word for a small program you install on a phone.', a: 'App' },
    ],
    B: [
      { q: 'Children\'s song video that became the first clip to pass ten billion YouTube views.', a: 'Baby Shark' },
      { q: 'Digital currency introduced in a 2008 paper credited to Satoshi Nakamoto.', a: 'Bitcoin' },
      { q: 'Short name for a personal online journal kept in reverse date order.', a: 'Blog' },
      { q: 'Chat shorthand promising you will be back in a moment.', a: 'BRB' },
      { q: 'Meme of a grinning teenager in braces and a sweater vest, captioned with misfortunes.', a: 'Bad Luck Brian' },
      { q: 'Microsoft\'s search engine, launched in 2009.', a: 'Bing' },
      { q: 'Site founded in 2006 that made numbered lists and personality quizzes go viral.', a: 'BuzzFeed' },
      { q: 'Term for how much data a connection can carry at once.', a: 'Bandwidth' },
      { q: 'Short-range wireless standard named after a tenth-century Danish king.', a: 'Bluetooth' },
      { q: 'Cartoon version of yourself popularised by Snapchat stickers.', a: 'Bitmoji' },
      { q: 'One-syllable slang exclamation of disbelief, aimed at a friend.', a: 'Bruh' },
    ],
    C: [
      { q: 'Google\'s web browser, first released in 2008.', a: 'Chrome' },
      { q: 'Term for a headline written only to make you tap it.', a: 'Clickbait' },
      { q: 'Small files a site stores in your browser so it remembers you.', a: 'Cookies' },
      { q: 'Word for keeping your files on somebody else\'s servers over the internet.', a: 'Cloud' },
      { q: 'In the famous 2007 home video, this is the name of the baby who bites his brother\'s finger.', a: 'Charlie' },
      { q: 'Test with wobbly letters or picture tiles that proves you are not a robot.', a: 'Captcha' },
      { q: 'OpenAI chatbot released in November 2022 that reached a hundred million users in two months.', a: 'ChatGPT' },
      { q: 'Match-three mobile puzzle released by King in 2012 that flooded Facebook with requests.', a: 'Candy Crush' },
      { q: 'Plain-text classified adverts site started in San Francisco in 1995.', a: 'Craigslist' },
      { q: 'Block of text pasted again and again around forums as a running joke.', a: 'Copypasta' },
      { q: 'Older word for an online space where strangers typed at each other in real time.', a: 'Chatroom' },
    ],
    D: [
      { q: 'Chat platform organised into servers and channels, adored by gamers.', a: 'Discord' },
      { q: 'Shiba Inu meme captioned in broken phrases like much wow and so scare.', a: 'Doge' },
      { q: 'Old way of getting online that screeched and squealed down a phone line.', a: 'Dial-up' },
      { q: 'File syncing service founded in 2007 whose logo is a blue open box.', a: 'Dropbox' },
      { q: 'Stock photo meme of a man glancing back at a passing woman while his partner glares.', a: 'Distracted Boyfriend' },
      { q: 'Display setting that swaps white backgrounds for near black ones.', a: 'Dark mode' },
      { q: 'Word for copying a file from the internet onto your own device.', a: 'Download' },
      { q: 'Dance move of dropping your head into a bent arm, everywhere around 2015.', a: 'Dab' },
      { q: 'Two letters for a private message sent to one person on social media.', a: 'DM' },
      { q: 'Joke cryptocurrency launched in 2013 built entirely around a dog picture.', a: 'Dogecoin' },
    ],
    E: [
      { q: 'Little picture characters that came from Japanese mobile phones in the late 1990s.', a: 'Emoji' },
      { q: 'Sideways face built from punctuation, such as a colon and a bracket.', a: 'Emoticon' },
      { q: 'Messaging system whose addresses use the at sign, a choice made by Ray Tomlinson in 1971.', a: 'Email' },
      { q: 'Cable standard for wired local networks, invented at Xerox PARC.', a: 'Ethernet' },
      { q: 'Marketplace launched in 2005 for handmade and vintage goods.', a: 'Etsy' },
      { q: 'Popular late-2000s caption slapped on a spectacularly botched attempt.', a: 'Epic fail' },
      { q: 'Sesame Street character whose fiery arms-raised picture became a rage meme.', a: 'Elmo' },
      { q: 'Small animated icon that a streamer\'s chat spams by the hundred.', a: 'Emote' },
      { q: 'The most-liked Instagram post of 2019 was a plain photo of this ordinary food item.', a: 'Egg' },
    ],
    F: [
      { q: 'Open-source browser released by Mozilla in 2004.', a: 'Firefox' },
      { q: 'Social network of 2004 whose parent company was renamed Meta in 2021.', a: 'Facebook' },
      { q: 'Punishing 2013 mobile game that its own creator pulled from the app stores.', a: 'Flappy Bird' },
      { q: 'Battle royale game from Epic whose emotes turned into playground dance moves.', a: 'Fortnite' },
      { q: 'Adobe plug-in that powered browser games and cartoons until it was killed off in 2020.', a: 'Flash' },
      { q: 'Acronym for the worry that something better is happening without you.', a: 'FOMO' },
      { q: 'Security barrier that filters traffic passing between networks.', a: 'Firewall' },
      { q: 'Person who subscribes to see your posts on social media.', a: 'Follower' },
      { q: 'Twitter\'s old overloaded-site picture, showing birds hauling a sea creature from the water.', a: 'Fail Whale' },
      { q: 'The endless scrolling column of posts on a social app.', a: 'Feed' },
    ],
    G: [
      { q: 'Search engine so dominant that its name became a verb for looking something up.', a: 'Google' },
      { q: 'Silent looping image format from 1987 whose pronunciation people still argue about.', a: 'GIF' },
      { q: 'Internet-famous feline with a permanent scowl, really named Tardar Sauce.', a: 'Grumpy Cat' },
      { q: 'PSY video from 2012 that became the first clip to reach a billion YouTube views.', a: 'Gangnam Style' },
      { q: 'Four-letter acronym crowning someone the best of all time.', a: 'GOAT' },
      { q: 'Google\'s mail service, launched on April Fools\' Day 2004 with a whole gigabyte of space.', a: 'Gmail' },
      { q: 'Free 1990s hosting service full of animated banners, visitor counters and midi music.', a: 'Geocities' },
      { q: 'Suddenly cutting off all contact with someone online without a word.', a: 'Ghosting' },
      { q: 'Two letters typed at the end of a match to say well played.', a: 'GG' },
      { q: 'Search engine devoted entirely to looping animations, founded in 2013.', a: 'Giphy' },
    ],
    H: [
      { q: 'Symbol plus keyword used to group posts, popularised on Twitter from 2007.', a: 'Hashtag' },
      { q: 'Markup language used to write the structure of a web page.', a: 'HTML' },
      { q: 'Clickable text that jumps you straight to another page.', a: 'Hyperlink' },
      { q: 'Video craze of 2013 where a still room erupts into chaos after a bass drop.', a: 'Harlem Shake' },
      { q: 'Free webmail service launched in 1996 and bought by Microsoft a year later.', a: 'Hotmail' },
      { q: 'Stock photo meme of a smiling older Hungarian man who looks quietly miserable; his first name.', a: 'Harold', alt: ['Hide the Pain Harold'] },
      { q: 'American streaming service launched in 2008 by a group of broadcast networks.', a: 'Hulu' },
      { q: 'Another word for the username you pick on a platform.', a: 'Handle' },
      { q: 'Person who breaks into computer systems, whether for mischief or money.', a: 'Hacker' },
    ],
    I: [
      { q: 'Photo sharing app launched in 2010, once known for square pictures and heavy filters.', a: 'Instagram' },
      { q: 'Microsoft browser bundled with Windows from 1995 and finally retired in 2022.', a: 'Internet Explorer' },
      { q: 'Text chat protocol from 1988 organised into channels that start with a hash.', a: 'IRC' },
      { q: 'Numeric label that identifies a device on a network.', a: 'IP address' },
      { q: 'Device Steve Jobs unveiled in January 2007 that changed how people browse.', a: 'iPhone' },
      { q: 'Viral 2014 fundraiser for motor neurone disease involving freezing water and a nomination.', a: 'Ice Bucket Challenge' },
      { q: 'Person who earns a living recommending products to an online audience.', a: 'Influencer' },
      { q: 'Film and television database site that began in 1990 as a Usenet list.', a: 'IMDb' },
      { q: 'Image hosting site created in 2009 mainly to serve pictures to Reddit.', a: 'Imgur' },
    ],
    J: [
      { q: 'Programming language written in about ten days in 1995 to make pages interactive.', a: 'JavaScript' },
      { q: 'Lossy image format standardised in 1992 and used for most photographs.', a: 'JPEG' },
      { q: 'Irish creator known for very loud gaming videos and bright green hair (channel name).', a: 'Jacksepticeye' },
      { q: 'Singer discovered through home videos posted online in 2007 (full name).', a: 'Justin Bieber' },
      { q: 'Language whose slogan was write once and run anywhere, and whose applets ran in 1990s browsers.', a: 'Java' },
      { q: 'Two letters added to a message to say you were only joking.', a: 'JK' },
    ],
    K: [
      { q: 'Nickname for someone fierce in an argument online but meek in person.', a: 'Keyboard warrior' },
      { q: 'British creator turned boxer and rapper, a founder of the Sidemen group (channel name).', a: 'KSI' },
      { q: 'Meme first name for a demanding customer who wants to speak to the manager.', a: 'Karen' },
      { q: 'Muppet whose tea-sipping photo became the But That Is None Of My Business meme.', a: 'Kermit' },
      { q: 'Crowdfunding site launched in 2009 where a project only gets the money if it hits its goal.', a: 'Kickstarter' },
      { q: 'Meme clip of a striped feline in a blue shirt seeming to play an electric organ.', a: 'Keyboard Cat' },
      { q: 'Documentary short about a Ugandan warlord that became one of the fastest-spreading videos in internet history.', a: 'Kony 2012', alt: ['Kony'] },
    ],
    L: [
      { q: 'Three letters typed to show that something is funny.', a: 'LOL' },
      { q: 'Professional networking site founded in 2002 and bought by Microsoft in 2016.', a: 'LinkedIn' },
      { q: 'Someone who reads a forum for years without ever posting.', a: 'Lurker' },
      { q: 'The thumbs-up button Facebook introduced in 2009.', a: 'Like' },
      { q: 'Broadcasting video to an audience in real time.', a: 'Livestream' },
      { q: 'Peer-to-peer file sharing program that courts shut down in 2010.', a: 'LimeWire' },
      { q: 'Famous 2005 World of Warcraft clip in which one player wrecks a careful raid plan by charging in.', a: 'Leeroy Jenkins' },
      { q: 'Four-letter acronym for laughing far harder than the three-letter version.', a: 'LMAO' },
    ],
    M: [
      { q: 'Word for a spreading cultural idea, coined by Richard Dawkins in 1976 and now used for funny pictures.', a: 'Meme' },
      { q: 'Block-building game created by Markus Persson, the best-selling video game ever made.', a: 'Minecraft' },
      { q: 'Social network that ruled before Facebook and let you set a song on your profile.', a: 'MySpace' },
      { q: 'American creator famous for enormous cash-giveaway stunt videos and a chocolate brand.', a: 'MrBeast' },
      { q: 'Name that Facebook\'s parent company adopted in October 2021.', a: 'Meta' },
      { q: 'Device that turns digital data into signals a phone line can carry.', a: 'Modem' },
      { q: 'Audio compression format that made swapping music practical in the late 1990s.', a: 'MP3' },
      { q: 'Non-profit foundation that develops the Firefox browser.', a: 'Mozilla' },
      { q: 'The 1993 graphical browser that pushed the World Wide Web into the mainstream.', a: 'Mosaic' },
      { q: 'American creator best known for horror game playthroughs and a red-haired persona (channel name).', a: 'Markiplier' },
    ],
    N: [
      { q: 'Company that posted DVDs before becoming the biggest streaming service in the world.', a: 'Netflix' },
      { q: 'File sharing program of 1999 that Metallica famously sued.', a: 'Napster' },
      { q: 'Meme animation of a pastry-bodied feline flying through space on a rainbow trail.', a: 'Nyan Cat' },
      { q: 'Word for good manners when posting online.', a: 'Netiquette' },
      { q: 'Slang for a clueless newcomer in an online game.', a: 'Noob' },
      { q: 'Browser company of the 1990s whose Navigator lost the browser war to Microsoft.', a: 'Netscape' },
      { q: 'Alert that pops up on your screen when something happens in an app.', a: 'Notification' },
      { q: 'Gaming slang for weakening a weapon or character in a patch.', a: 'Nerf' },
    ],
    O: [
      { q: 'Three letters expressing sudden shock in a text message.', a: 'OMG' },
      { q: 'Lil Nas X song of 2019 that blew up on TikTok and spent nineteen weeks at number one.', a: 'Old Town Road' },
      { q: 'Norwegian web browser first released in 1995.', a: 'Opera' },
      { q: 'Software whose code anybody is free to read, change and share.', a: 'Open source' },
      { q: 'Word for not being connected to the network at all.', a: 'Offline' },
      { q: 'Two-letter forum abbreviation for the person who started the thread.', a: 'OP' },
      { q: 'American state whose name is used in modern slang to mean cursed or bizarre.', a: 'Ohio' },
    ],
    P: [
      { q: 'Swedish creator who held the most-subscribed spot on YouTube for years (channel name).', a: 'PewDiePie' },
      { q: 'On-demand audio series whose name blends an Apple music player with broadcasting.', a: 'Podcast' },
      { q: 'When somebody deliberately intrudes into a picture as it is being taken.', a: 'Photobomb' },
      { q: 'Unwanted advertising window that springs open over the page you wanted.', a: 'Pop-up' },
      { q: 'Phone game of 2016 that sent crowds into the streets hunting creatures on a map.', a: 'Pokemon Go' },
      { q: 'Scam message pretending to be your bank in order to steal your password.', a: 'Phishing' },
      { q: 'Site launched in 2010 for pinning pictures onto themed boards.', a: 'Pinterest' },
      { q: 'Basic Windows drawing program used to make crude early memes.', a: 'Paint', alt: ['MS Paint'] },
      { q: 'The secret string you type to prove an account belongs to you.', a: 'Password' },
      { q: 'A single dot of colour on a screen.', a: 'Pixel' },
      { q: 'Fad of 2011 involving lying rigidly face down in unlikely public places.', a: 'Planking' },
    ],
    Q: [
      { q: 'Square pattern of black and white blocks that a phone camera can read.', a: 'QR code' },
      { q: 'Question and answer site founded in 2009 by two former Facebook employees.', a: 'Quora' },
      { q: 'Word for the line of videos waiting to play after this one.', a: 'Queue' },
      { q: 'Sharing somebody\'s post with your own comment stuck on top of it.', a: 'Quote tweet' },
    ],
    R: [
      { q: 'Prank of hiding a link that actually opens a cheesy 1987 pop video.', a: 'Rickroll' },
      { q: 'Site of upvotes and niche topic forums that calls itself the front page of the internet.', a: 'Reddit' },
      { q: 'Box at home that shares one internet connection among your devices.', a: 'Router' },
      { q: 'Singer whose 1987 hit Never Gonna Give You Up powers a famous link prank (full name).', a: 'Rick Astley' },
      { q: 'Four-letter acronym stronger than LOL, about collapsing onto the floor with laughter.', a: 'ROFL' },
      { q: 'Platform where users build and play each other\'s blocky games, hugely popular with children.', a: 'Roblox' },
      { q: 'Passing somebody else\'s Twitter post along to your own followers.', a: 'Retweet' },
      { q: 'Singer whose 2011 song Friday was mocked into infamy online (full name).', a: 'Rebecca Black' },
    ],
    S: [
      { q: 'Video calling service launched in 2003 and bought by Microsoft in 2011.', a: 'Skype' },
      { q: 'App launched in 2011 whose photos vanish once they have been viewed.', a: 'Snapchat' },
      { q: 'Unwanted bulk email, named after a Monty Python sketch about tinned meat.', a: 'Spam' },
      { q: 'Person who broadcasts themselves playing games live to an audience.', a: 'Streamer' },
      { q: 'Photograph you take of yourself, chosen as word of the year in 2013.', a: 'Selfie' },
      { q: 'Computer that hosts a website or a game world for everybody else.', a: 'Server' },
      { q: 'Apple\'s web browser, introduced in 2003.', a: 'Safari' },
      { q: 'Meme photo of a determined toddler on a beach clenching a fistful of sand.', a: 'Success Kid' },
      { q: 'Pocket device that runs apps, takes photos and browses the web.', a: 'Smartphone' },
      { q: 'The button creators beg you to press at the end of every video.', a: 'Subscribe' },
      { q: 'Slang for an obsessive fan, taken from an Eminem song about a letter writer.', a: 'Stan' },
    ],
    T: [
      { q: 'Short-video app that absorbed Musical.ly in 2018 and conquered the world.', a: 'TikTok' },
      { q: 'Live streaming site that grew out of Justin.tv and was bought by Amazon in 2014.', a: 'Twitch' },
      { q: 'Someone who posts deliberately provoking comments just to start arguments.', a: 'Troll' },
      { q: 'Microblogging site launched in 2007, famous for reblogging and intense fandoms.', a: 'Tumblr' },
      { q: 'Small preview picture you click to start playing a video.', a: 'Thumbnail' },
      { q: 'Four-letter acronym warning that a post is far too long to read.', a: 'TLDR' },
      { q: 'Platform of short public posts that rebranded itself to a single letter in 2023.', a: 'Twitter' },
      { q: 'Browser and network that bounces your traffic through relays to hide who you are.', a: 'Tor' },
      { q: 'Dating app launched in 2012 that made swiping right a household phrase.', a: 'Tinder' },
      { q: 'Word for a topic suddenly attracting a flood of posts.', a: 'Trending' },
    ],
    U: [
      { q: 'The web address you type into the bar at the top of a browser.', a: 'URL' },
      { q: 'Reddit button that pushes a post further up the page.', a: 'Upvote' },
      { q: 'Distributed discussion system from 1980, the ancestor of web forums.', a: 'Usenet' },
      { q: 'Video genre built entirely on slowly opening a new product on camera.', a: 'Unboxing' },
      { q: 'The name you choose in order to log in and be recognised.', a: 'Username' },
      { q: 'Removing somebody from your list of Facebook connections.', a: 'Unfriend' },
      { q: 'Sending a file from your own device up to a website.', a: 'Upload' },
    ],
    V: [
      { q: 'App of six-second looping clips that closed down in 2017.', a: 'Vine' },
      { q: 'Word for content that spreads explosively through sharing.', a: 'Viral' },
      { q: 'Encrypted tunnel that hides your browsing from your internet provider.', a: 'VPN' },
      { q: 'Video diary posted regularly to a channel.', a: 'Vlog' },
      { q: 'Badge showing that an account really is who it claims to be.', a: 'Verified' },
      { q: 'Malicious program that copies itself from one computer to another.', a: 'Virus' },
    ],
    W: [
      { q: 'Messaging app with over two billion users, bought by Facebook in 2014.', a: 'WhatsApp' },
      { q: 'Free encyclopedia anybody can edit, launched in January 2001.', a: 'Wikipedia' },
      { q: 'Wireless local networking standard whose name is a made-up marketing term.', a: 'WiFi' },
      { q: 'Small camera pointed at your face during a video call.', a: 'Webcam' },
      { q: 'Daily five-letter guessing puzzle bought by the New York Times in 2022.', a: 'Wordle' },
      { q: 'Blizzard\'s 2004 online role-playing game, source of the Leeroy Jenkins clip.', a: 'World of Warcraft', alt: ['WoW'] },
    ],
    X: [
      { q: 'Single letter that Twitter renamed itself to in 2023.', a: 'X' },
      { q: 'Stick-figure webcomic about maths, romance, language and sarcasm.', a: 'xkcd' },
      { q: 'Two letters naming the 2001 Windows release with the rolling green hill wallpaper.', a: 'XP' },
    ],
    Y: [
      { q: 'Video site founded in 2005 whose first upload was titled Me at the Zoo.', a: 'YouTube' },
      { q: 'Portal and search company founded in 1994 whose logo ends with an exclamation mark.', a: 'Yahoo' },
      { q: 'Four-letter acronym urging you to take the risk because life happens only once.', a: 'YOLO' },
      { q: 'Site of crowd-sourced restaurant and business reviews, founded in 2004.', a: 'Yelp' },
      { q: 'Slang cry shouted while flinging something across a room.', a: 'Yeet' },
    ],
    Z: [
      { q: 'Video meeting app whose daily users leapt from ten million to three hundred million in 2020.', a: 'Zoom' },
      { q: 'Facebook co-founder who started the site as a Harvard student (surname).', a: 'Zuckerberg' },
      { q: 'Compressed archive format used to bundle several files into one.', a: 'Zip' },
      { q: 'Company behind FarmVille, the Facebook game craze of 2009.', a: 'Zynga' },
    ],
  },
};
