import type { RawPack } from '../core/packs';

export const inventionsPack: RawPack = {
  id: 'inventions',
  name: 'Inventions and Technology',
  description: 'Breakthroughs, gadgets, patents and the people who built them.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '💡',
  accent: '#b45309',
  letters: {
    A: [
      { q: 'French physicist whose surname became the unit of electric current.', a: 'Ampere', alt: ['Ampère', 'Andre-Marie Ampere'] },
      { q: 'Painkiller sold by Bayer from 1899, developed from willow bark chemistry.', a: 'Aspirin' },
      { q: 'Willis Carrier\'s 1902 system for cooling and drying the atmosphere indoors.', a: 'Air conditioning', alt: ['Air conditioner'] },
      { q: 'Production method Ford introduced in 1913 that cut car build time from twelve hours to under two.', a: 'Assembly line' },
      { q: 'Cash-dispensing machine first installed by Barclays in London in 1967.', a: 'ATM', alt: ['Automated teller machine', 'Cash machine'] },
      { q: 'Car safety device that inflates in milliseconds during a crash.', a: 'Airbag' },
      { q: 'Ancient bead-and-rod counting frame still used for fast arithmetic.', a: 'Abacus' },
      { q: 'Spiral device inside a tube, turned by hand to raise water for irrigation.', a: 'Archimedes screw' },
      { q: 'Brass instrument used by medieval navigators to measure the altitude of stars.', a: 'Astrolabe' },
      { q: 'Company founded in 1976 in a Los Altos garage to sell a hand-built computer kit.', a: 'Apple' },
      { q: 'Military research network of 1969 that became the ancestor of today\'s global network.', a: 'ARPANET' },
      { q: 'Charles Babbage\'s never-finished mechanical general-purpose calculating machine.', a: 'Analytical Engine' },
      { q: 'Instrument with spinning cups that measures wind speed.', a: 'Anemometer' },
      { q: 'Cousteau and Gagnan\'s demand-valve gear for breathing while diving.', a: 'Aqualung', alt: ['Scuba'] },
      { q: 'Light metal that only became cheap once electrolysis replaced chemical extraction.', a: 'Aluminium', alt: ['Aluminum'] },
    ],
    B: [
      { q: 'Torricelli\'s mercury tube for measuring the pressure of the atmosphere.', a: 'Barometer' },
      { q: 'Volta\'s stack of zinc and copper discs, the first steady source of electric current.', a: 'Battery' },
      { q: 'The first fully synthetic plastic, patented in 1907 and used for early radio cases.', a: 'Bakelite' },
      { q: 'Raised-dot reading system devised by a blind French teenager.', a: 'Braille' },
      { q: 'Fencing patented by Joseph Glidden in 1874 that transformed the American plains.', a: 'Barbed wire' },
      { q: 'Writing tool patented by Laszlo Biro using thick quick-drying ink and a rolling tip.', a: 'Ballpoint pen', alt: ['Biro'] },
      { q: 'Two-wheeled pedal machine whose chain-driven safety design arrived in the 1880s.', a: 'Bicycle' },
      { q: 'Short-range wireless standard named after a tenth-century Danish king.', a: 'Bluetooth' },
      { q: 'Cheap steelmaking method that blew cold air through molten iron to burn off carbon.', a: 'Bessemer process', alt: ['Bessemer converter'] },
      { q: 'Scottish-born inventor awarded the 1876 telephone patent.', a: 'Bell', alt: ['Alexander Graham Bell'] },
      { q: 'Striped label read by a laser at the checkout, first scanned on chewing gum in 1974.', a: 'Barcode' },
      { q: 'Tall shaft where iron ore, coke and limestone are smelted with a hot draught.', a: 'Blast furnace' },
    ],
    C: [
      { q: 'Chinese magnetic navigation instrument that let ships sail out of sight of land.', a: 'Compass' },
      { q: 'Eli Whitney\'s 1793 machine for separating fibre from seed.', a: 'Cotton gin' },
      { q: 'Physicist who won two Nobel prizes and whose surname names a unit of radioactivity.', a: 'Curie', alt: ['Marie Curie'] },
      { q: 'Dark room or box that projects an inverted image through a tiny hole.', a: 'Camera obscura' },
      { q: 'Roman-perfected mix of aggregate, water and binder that hardens into artificial stone.', a: 'Concrete' },
      { q: 'Optical music format launched jointly by Sony and Philips in 1982.', a: 'Compact disc', alt: ['CD'] },
      { q: 'Funnel-shaped glass display that painted pictures with a scanned electron beam.', a: 'Cathode ray tube', alt: ['CRT'] },
      { q: 'Device that restores a sense of hearing by stimulating the auditory nerve directly.', a: 'Cochlear implant' },
      { q: 'Farm machine that reaps, threshes and winnows in a single pass.', a: 'Combine harvester', alt: ['Combine'] },
      { q: 'John Harrison\'s precision sea clock that finally solved the longitude problem.', a: 'Chronometer' },
      { q: 'Swedish astronomer whose surname names a temperature scale with 100 as boiling.', a: 'Celsius' },
      { q: 'Transparent moisture-proof wrapping film invented by Jacques Brandenberger.', a: 'Cellophane' },
      { q: 'Pocket electronic adding device that made the slide rule obsolete.', a: 'Calculator' },
      { q: 'Shop machine invented by a saloon owner to stop his staff pocketing coins.', a: 'Cash register' },
    ],
    D: [
      { q: 'Nobel\'s 1867 explosive that tamed nitroglycerin by soaking it into a porous earth.', a: 'Dynamite' },
      { q: 'Compression-ignition motor patented in 1892 that needs no spark plug.', a: 'Diesel engine', alt: ['Diesel'] },
      { q: 'Josephine Cochrane\'s 1886 machine that cleaned crockery with jets of hot water.', a: 'Dishwasher' },
      { q: 'Earliest commercial photograph, a one-off image on a silvered copper plate.', a: 'Daguerreotype' },
      { q: 'First mammal cloned from an adult cell, born in Scotland in 1996.', a: 'Dolly' },
      { q: 'Vacuum-walled vessel that keeps liquids hot or cold for hours.', a: 'Dewar flask', alt: ['Thermos', 'Vacuum flask'] },
      { q: 'Machine that turns rotation into electric current, built on Faraday\'s discovery.', a: 'Dynamo', alt: ['Generator'] },
      { q: 'Device that shocks a fluttering heart back into a normal rhythm.', a: 'Defibrillator' },
      { q: 'Uncrewed aircraft flown by remote control or by onboard software.', a: 'Drone', alt: ['UAV'] },
    ],
    E: [
      { q: 'Vertical transport whose 1853 safety brake let cities finally build upward.', a: 'Elevator', alt: ['Lift'] },
      { q: 'Moving staircase patented in the 1890s and shown off at the Paris Exposition.', a: 'Escalator' },
      { q: 'Prolific American holder of 1,093 patents, including one for a practical light bulb.', a: 'Edison', alt: ['Thomas Edison'] },
      { q: 'Room-sized 1945 American electronic computer programmed by rewiring plugboards.', a: 'ENIAC' },
      { q: 'Vapour first used publicly as a surgical anaesthetic in Boston in 1846.', a: 'Ether' },
      { q: 'Ray Tomlinson\'s 1971 messaging system that gave the @ sign its modern job.', a: 'Email' },
      { q: 'German wartime cipher machine whose traffic was broken at Bletchley Park.', a: 'Enigma' },
      { q: 'Italian device that forces hot water through ground coffee under high pressure.', a: 'Espresso machine' },
      { q: 'Instrument of 1931 that uses a beam of particles to see far smaller than light allows.', a: 'Electron microscope' },
      { q: 'American who rolled flexible film and founded a giant camera company.', a: 'Eastman', alt: ['George Eastman'] },
    ],
    F: [
      { q: 'German physicist whose surname names a temperature scale with 32 as freezing.', a: 'Fahrenheit' },
      { q: 'English experimenter who discovered electromagnetic induction with a coil and a magnet.', a: 'Faraday', alt: ['Michael Faraday'] },
      { q: 'Writing instrument with an internal ink reservoir, perfected by Lewis Waterman in 1884.', a: 'Fountain pen' },
      { q: 'Hair-thin glass strands that carry data as pulses of light.', a: 'Fibre optics', alt: ['Fiber optics', 'Optical fibre'] },
      { q: 'Detroit carmaker who paid five dollars a day and mass-produced a cheap black automobile.', a: 'Ford', alt: ['Henry Ford'] },
      { q: 'Office device that scans a page and prints a copy of it down a phone line.', a: 'Fax machine', alt: ['Fax', 'Facsimile machine'] },
      { q: 'Scot who noticed mould killing bacteria on a forgotten laboratory dish.', a: 'Fleming', alt: ['Alexander Fleming'] },
      { q: 'Non-volatile chip storage invented at Toshiba and used in camera cards.', a: 'Flash memory' },
      { q: 'John Kay\'s 1733 device that let a single weaver work a wide loom.', a: 'Flying shuttle' },
    ],
    G: [
      { q: 'German goldsmith who brought movable metal type and a printing workshop to Europe.', a: 'Gutenberg', alt: ['Johannes Gutenberg'] },
      { q: 'Emile Berliner\'s flat-disc sound player that pushed aside recording cylinders.', a: 'Gramophone' },
      { q: 'Satellite network that fixes a receiver\'s position by timing radio signals.', a: 'GPS', alt: ['Global Positioning System'] },
      { q: 'Chinese mixture of saltpetre, sulphur and charcoal that changed warfare forever.', a: 'Gunpowder' },
      { q: 'Italian who made frog legs twitch and whose name is attached to a zinc plating process.', a: 'Galvani', alt: ['Luigi Galvani'] },
      { q: 'Handheld device that clicks faster the more ionising radiation it detects.', a: 'Geiger counter' },
      { q: 'Spinning wheel in a gimbal that resists changes of orientation, used in navigation.', a: 'Gyroscope' },
      { q: 'One-atom-thick sheet of carbon first isolated in Manchester in 2004.', a: 'Graphene' },
      { q: 'American pioneer who launched the first liquid-fuelled rocket in 1926.', a: 'Goddard', alt: ['Robert Goddard'] },
    ],
    H: [
      { q: 'German physicist whose surname became the unit of frequency.', a: 'Hertz' },
      { q: 'Aircraft lifted by rotating blades, made practical by Igor Sikorsky in 1939.', a: 'Helicopter' },
      { q: 'Vehicle that rides on a cushion of air, invented by Christopher Cockerell.', a: 'Hovercraft' },
      { q: 'American whose tabulating machines counted the 1890 census and grew into IBM.', a: 'Hollerith', alt: ['Herman Hollerith'] },
      { q: 'Orbiting observatory launched in 1990 that needed a repair mission for its blurred mirror.', a: 'Hubble Space Telescope', alt: ['Hubble'] },
      { q: 'Hollow-needle instrument for injecting a drug beneath the skin.', a: 'Hypodermic syringe', alt: ['Syringe'] },
      { q: 'IBM\'s 1956 magnetic storage stack of spinning platters read by moving heads.', a: 'Hard disk', alt: ['Hard drive'] },
      { q: 'Montgolfier craft that first carried people aloft in 1783.', a: 'Hot air balloon', alt: ['Balloon'] },
    ],
    I: [
      { q: 'Global network of networks built on packet switching and a shared protocol suite.', a: 'Internet' },
      { q: 'Power plant that burns its fuel inside its own cylinders rather than in a boiler.', a: 'Internal combustion engine' },
      { q: 'Touchscreen device Steve Jobs unveiled on stage in 2007.', a: 'iPhone' },
      { q: 'Lamp that glows by heating a thin filament white hot in a vacuum.', a: 'Incandescent bulb', alt: ['Light bulb', 'Incandescent lamp'] },
      { q: 'Hormone extracted in Toronto in 1921 that turned diabetes from fatal to manageable.', a: 'Insulin' },
      { q: 'Chip that packs many components onto one small slice of semiconductor.', a: 'Integrated circuit', alt: ['Microchip'] },
      { q: 'Process that squirts molten plastic into a shaped cavity to make identical parts fast.', a: 'Injection moulding', alt: ['Injection molding'] },
      { q: 'Company formed from a tabulator business, later maker of the System/360 mainframe.', a: 'IBM' },
    ],
    J: [
      { q: 'Punched-card weaving machine of 1804 that later inspired computing pioneers.', a: 'Jacquard loom', alt: ['Jacquard'] },
      { q: 'Frank Whittle\'s turbine power plant that made airliners fast and high-flying.', a: 'Jet engine' },
      { q: 'English brewer and physicist whose surname is the unit of energy.', a: 'Joule', alt: ['James Joule'] },
      { q: 'English doctor who used cowpox to protect patients against smallpox.', a: 'Jenner', alt: ['Edward Jenner'] },
      { q: 'Coin-fed machine that plays a customer\'s chosen record in a bar or diner.', a: 'Jukebox' },
    ],
    K: [
      { q: 'Stephanie Kwolek\'s strong lightweight fibre used in body armour and tyres.', a: 'Kevlar' },
      { q: 'Scottish physicist whose surname names the absolute temperature scale.', a: 'Kelvin', alt: ['Lord Kelvin'] },
      { q: 'Company whose 1888 box camera let ordinary people take snapshots.', a: 'Kodak' },
      { q: 'Metric base unit of mass, redefined in 2019 in terms of the Planck constant.', a: 'Kilogram' },
      { q: 'American engineer at Texas Instruments who won a Nobel for a 1958 semiconductor breakthrough.', a: 'Kilby', alt: ['Jack Kilby'] },
    ],
    L: [
      { q: 'Device built in 1960 that emits a narrow coherent beam by stimulated emission.', a: 'Laser' },
      { q: 'Rechargeable cell behind phones and electric cars, honoured with a 2019 Nobel prize.', a: 'Lithium-ion battery', alt: ['Lithium ion battery'] },
      { q: 'Self-propelled engine that hauls trains along rails.', a: 'Locomotive' },
      { q: 'Franklin\'s pointed metal spike that conducts a strike safely down to earth.', a: 'Lightning rod', alt: ['Lightning conductor'] },
      { q: 'Machine that cast a whole row of metal letters at once, speeding up newspaper work.', a: 'Linotype' },
      { q: 'Semiconductor lamp that glows when current crosses a junction, now used everywhere.', a: 'LED', alt: ['Light emitting diode'] },
      { q: 'Frame for weaving thread into cloth, mechanised during the Industrial Revolution.', a: 'Loom' },
      { q: 'Cone and coil that turns an electrical signal back into audible waves.', a: 'Loudspeaker', alt: ['Speaker'] },
    ],
    M: [
      { q: 'Instrument of lenses that first revealed cells and micro-organisms.', a: 'Microscope' },
      { q: 'Cooker born when Percy Spencer\'s chocolate bar melted beside a radar set.', a: 'Microwave oven', alt: ['Microwave'] },
      { q: 'Dot-and-dash alphabet that let telegraph wires carry ordinary words.', a: 'Morse code' },
      { q: 'Ford\'s cheap black car of 1908 that put America on wheels.', a: 'Model T' },
      { q: 'Scanner that images soft tissue using strong magnets and radio waves.', a: 'MRI', alt: ['Magnetic resonance imaging'] },
      { q: 'Douglas Engelbart\'s wooden pointing box, demonstrated to the world in 1968.', a: 'Mouse' },
      { q: 'First synthetic dye, stumbled on by William Perkin in 1856 while chasing quinine.', a: 'Mauveine', alt: ['Mauve'] },
      { q: 'Italian who sent the first wireless signal across the Atlantic in 1901.', a: 'Marconi', alt: ['Guglielmo Marconi'] },
      { q: 'Vacuum tube that generates the short waves used by radar sets and kitchen cookers.', a: 'Magnetron' },
      { q: 'Handheld wireless handset first demonstrated on a New York street in 1973.', a: 'Mobile phone', alt: ['Cell phone', 'Cellphone'] },
    ],
    N: [
      { q: 'English scientist whose surname is the unit of force.', a: 'Newton', alt: ['Isaac Newton'] },
      { q: 'DuPont\'s 1935 synthetic fibre first sold to the public as stockings.', a: 'Nylon' },
      { q: 'Swedish inventor of a safe blasting explosive who endowed the world\'s famous prizes.', a: 'Nobel', alt: ['Alfred Nobel'] },
      { q: 'Pile of uranium and graphite that first sustained a controlled chain reaction in 1942.', a: 'Nuclear reactor' },
      { q: 'Glass tube that glows orange-red when a noble gas inside it is excited, used for signs.', a: 'Neon lamp', alt: ['Neon light', 'Neon sign'] },
      { q: 'Englishman whose 1712 atmospheric engine first pumped water out of deep mines.', a: 'Newcomen', alt: ['Thomas Newcomen'] },
    ],
    O: [
      { q: 'American whose 1853 safety brake made passenger elevators trustworthy.', a: 'Otis', alt: ['Elisha Otis'] },
      { q: 'German whose surname is the unit of electrical resistance.', a: 'Ohm', alt: ['Georg Ohm'] },
      { q: 'Instrument that draws the shape of a changing voltage against time on a screen.', a: 'Oscilloscope' },
      { q: 'Four-stroke engine sequence of intake, compression, power and exhaust, named after its German developer.', a: 'Otto cycle', alt: ['Otto'] },
      { q: 'Instrument that lets a doctor look through the pupil at the back of the eye.', a: 'Ophthalmoscope' },
      { q: 'Portable engine clamped to the stern of a small boat.', a: 'Outboard motor', alt: ['Outboard'] },
    ],
    P: [
      { q: 'First widely used antibiotic, mass-produced in time for the Normandy landings.', a: 'Penicillin' },
      { q: 'Machine of movable type and a screw clamp that spread books across Europe.', a: 'Printing press' },
      { q: 'Art of fixing images with light-sensitive chemicals, announced to the world in 1839.', a: 'Photography' },
      { q: 'French chemist who gave his name to a gentle heat treatment that keeps milk safe.', a: 'Pasteur', alt: ['Louis Pasteur'] },
      { q: 'Legal grant giving an inventor exclusive rights for a limited term.', a: 'Patent' },
      { q: 'Implanted device that keeps a heart beating in rhythm with small electrical pulses.', a: 'Pacemaker' },
      { q: 'Weak-adhesive paper square that came out of a failed 3M glue.', a: 'Post-it note', alt: ['Post-it'] },
      { q: 'Camera that developed its own picture in your hand within a minute.', a: 'Polaroid' },
      { q: 'Farm implement that turns soil, transformed by a curved iron mouldboard.', a: 'Plough', alt: ['Plow'] },
      { q: 'Canopy that slows a fall through the air, first jumped from a balloon in 1797.', a: 'Parachute' },
      { q: 'French thinker whose surname is the unit of pressure.', a: 'Pascal', alt: ['Blaise Pascal'] },
      { q: 'Chester Carlson\'s dry electrostatic office machine, sold worldwide by Xerox.', a: 'Photocopier' },
      { q: 'Huygens\' timekeeper of 1656 that cut daily error from minutes to seconds.', a: 'Pendulum clock' },
      { q: 'Air-filled rubber ring patented by John Dunlop in 1888 for a child\'s tricycle.', a: 'Pneumatic tyre', alt: ['Pneumatic tire'] },
    ],
    Q: [
      { q: 'Timepiece kept accurate by a vibrating crystal, launched by Seiko in 1969.', a: 'Quartz watch' },
      { q: 'Keyboard layout arranged in the 1870s for a Sholes typewriter.', a: 'QWERTY' },
      { q: 'Bark extract that became the first effective treatment for malaria.', a: 'Quinine' },
      { q: 'Nanocrystal that glows a pure colour set by its size, now used in bright displays.', a: 'Quantum dot' },
    ],
    R: [
      { q: 'Wireless transmission of speech and music by electromagnetic waves.', a: 'Radio' },
      { q: 'Wartime system that finds aircraft by timing reflected pulses of radio energy.', a: 'Radar' },
      { q: 'Kitchen appliance that keeps food cold by compressing and evaporating a fluid.', a: 'Refrigerator', alt: ['Fridge'] },
      { q: 'Vehicle that carries its own oxidiser so it can push even in a vacuum.', a: 'Rocket' },
      { q: 'German physicist who found a penetrating new kind of ray in 1895.', a: 'Roentgen', alt: ['Röntgen', 'Wilhelm Roentgen'] },
      { q: 'Colt\'s repeating handgun with a turning cylinder of six chambers.', a: 'Revolver' },
      { q: 'McCormick\'s horse-drawn machine that cut standing grain far faster than a scythe.', a: 'Reaper' },
      { q: 'Handset that lets you command a television from across the room.', a: 'Remote control' },
    ],
    S: [
      { q: 'Watt\'s improved power plant with a separate condenser that drove the factory age.', a: 'Steam engine' },
      { q: 'Household device whose lockstitch needle carries thread through an eye at its point.', a: 'Sewing machine' },
      { q: 'Doctor\'s tube for listening to the chest, invented by Laennec in 1816.', a: 'Stethoscope' },
      { q: 'Instrument that records ground shaking as a wobbling trace on a moving drum.', a: 'Seismograph', alt: ['Seismometer'] },
      { q: 'Beach-ball-sized satellite whose 1957 beeps started the space race.', a: 'Sputnik' },
      { q: 'Friction-lit fire stick, tamed by moving the phosphorus onto the box instead.', a: 'Safety match', alt: ['Match'] },
      { q: 'Vessel that dives and travels underwater, made practical by John Holland.', a: 'Submarine' },
      { q: 'Bell Labs device of 1954 that turns sunlight straight into electricity.', a: 'Solar cell', alt: ['Photovoltaic cell'] },
      { q: 'Hargreaves\' machine that let one worker draw out eight threads at once.', a: 'Spinning jenny' },
      { q: 'Alloy of iron with a little carbon, cheap to make in bulk after 1856.', a: 'Steel' },
      { q: 'Engineer of the Rocket, widely called the father of railways.', a: 'Stephenson', alt: ['George Stephenson'] },
      { q: 'System that finds underwater objects by listening for the echo of a pulse.', a: 'Sonar' },
      { q: 'Sliding logarithmic scales used for multiplication before electronics took over.', a: 'Slide rule' },
    ],
    T: [
      { q: 'Device patented in 1876 that carried human speech along a wire.', a: 'Telephone' },
      { q: 'Wire system that sent messages across countries as coded electrical pulses.', a: 'Telegraph' },
      { q: 'Household box that shows moving pictures sent out as a broadcast signal.', a: 'Television' },
      { q: '1947 Bell Labs switch of germanium that replaced the fragile glass valve.', a: 'Transistor' },
      { q: 'Instrument Galileo turned on Jupiter to discover its four large moons.', a: 'Telescope' },
      { q: 'Instrument that measures temperature with a rising column or an electronic sensor.', a: 'Thermometer' },
      { q: 'Serbian-American champion of alternating current whose surname is a magnetic unit.', a: 'Tesla', alt: ['Nikola Tesla'] },
      { q: 'Keyboard machine that struck inked letters straight onto paper.', a: 'Typewriter' },
      { q: 'British mathematician who defined a universal computing machine and broke wartime ciphers.', a: 'Turing', alt: ['Alan Turing'] },
      { q: 'Slippery non-stick coating found by accident at DuPont in 1938.', a: 'Teflon', alt: ['PTFE'] },
      { q: 'Sealed metal container patented in 1810 for preserving food on long voyages.', a: 'Tin can', alt: ['Can'] },
      { q: 'Signal with coloured lamps that took control of busy road junctions.', a: 'Traffic light', alt: ['Traffic signal'] },
    ],
    U: [
      { q: 'Scanner that images a foetus using high-frequency echoes.', a: 'Ultrasound' },
      { q: 'Standard plug of 1996 that replaced a mess of different computer ports.', a: 'USB' },
      { q: 'First commercial American computer, which correctly called a 1952 election result.', a: 'UNIVAC' },
      { q: 'City transit line dug beneath the streets, opened in London in 1863.', a: 'Underground railway', alt: ['Underground', 'Subway', 'Metro'] },
    ],
    V: [
      { q: 'Preparation that trains the immune system using a weakened or killed germ.', a: 'Vaccine' },
      { q: 'Hook-and-loop fastener inspired by burrs stuck to a dog\'s coat.', a: 'Velcro' },
      { q: 'Goodyear\'s heat-and-sulphur process that made rubber tough and springy.', a: 'Vulcanisation', alt: ['Vulcanization'] },
      { q: 'Italian who built the first electric pile and lent his name to a unit.', a: 'Volta', alt: ['Alessandro Volta'] },
      { q: 'Suction machine for carpets, made portable by James Spangler and sold by Hoover.', a: 'Vacuum cleaner' },
      { q: 'Glass valve that amplified signals before solid-state parts arrived.', a: 'Vacuum tube', alt: ['Valve', 'Thermionic valve'] },
      { q: 'Home video cassette format that beat Betamax in the living room.', a: 'VHS' },
    ],
    W: [
      { q: 'Scottish engineer whose surname became the unit of power.', a: 'Watt', alt: ['James Watt'] },
      { q: 'Hand carrier with a single roller at the front and two lifting shafts.', a: 'Wheelbarrow' },
      { q: 'Tower with cloth sails that grinds grain using moving air.', a: 'Windmill' },
      { q: 'Ohio bicycle makers who achieved the first controlled powered flight in 1903.', a: 'Wright brothers', alt: ['Wrights'] },
      { q: 'Tim Berners-Lee\'s 1989 system of linked pages served over the internet.', a: 'World Wide Web', alt: ['Web', 'WWW'] },
      { q: 'Domestic drum that cleans clothes by tumbling them in soapy water.', a: 'Washing machine' },
      { q: 'Local radio networking standard given its catchy brand name in 1999.', a: 'Wi-Fi', alt: ['WiFi'] },
      { q: 'Paddled disc turned by a stream to drive millstones and bellows.', a: 'Waterwheel', alt: ['Water wheel'] },
    ],
    X: [
      { q: 'Penetrating radiation used to photograph bones through flesh.', a: 'X-ray', alt: ['X-rays'] },
      { q: 'Dry printing process using powder, static charge and heat, and the root of a company name.', a: 'Xerography' },
      { q: 'Gas-filled tube that gives a camera its sudden burst of light.', a: 'Xenon flash', alt: ['Flash tube'] },
    ],
    Y: [
      { q: 'Pin tumbler cylinder mechanism patented in 1861 and fitted to millions of doors.', a: 'Yale lock', alt: ['Yale'] },
      { q: 'Directional rooftop television aerial of rods on a boom, developed in Japan in the 1920s.', a: 'Yagi antenna', alt: ['Yagi'] },
    ],
    Z: [
      { q: 'Rigid hydrogen airship named after the German count who built the first ones.', a: 'Zeppelin' },
      { q: 'Interlocking-tooth fastener whose catchy name was coined by a boot company.', a: 'Zipper', alt: ['Zip fastener'] },
      { q: 'German engineer whose Z3 of 1941 was the first programmable working computer.', a: 'Zuse', alt: ['Konrad Zuse'] },
    ],
  },
};
