import type { RawQuestion } from '../core/packs';

export const extraKids: Record<string, RawQuestion[]> = {
  A: [
    { q: 'A red fruit that keeps the doctor away.', a: 'Apple' },
    { q: 'A big grey animal with a long trunk.', a: 'Elephant' },
    { q: 'You wear this over your clothes when it rains.', a: 'Anorak' },
    { q: 'A flying insect that makes honey.', a: 'Ant' },
    { q: 'This is the first letter of the alphabet.', a: 'A' },
    { q: 'A sea creature with eight arms.', a: 'Octopus' },
    { q: 'A fruit that monkeys love to eat.', a: 'Apple' },
    { q: 'A small insect that marches in a line.', a: 'Ant' },
    { q: 'A vehicle that flies in the sky.', a: 'Aeroplane' },
    { q: 'A round fruit, green or red, that grows on trees.', a: 'Apple' },
  ],
  B: [
    { q: 'A yellow fruit that monkeys love.', a: 'Banana' },
    { q: 'An animal that gives us milk and says "moo".', a: 'Bull' },
    { q: 'You use this to hit a baseball.', a: 'Bat' },
    { q: 'A small furry animal that says "woof".', a: 'Bulldog' },
    { q: 'A tiny creature that lights up at night.', a: 'Bug' },
    { q: 'You bounce this in a playground game.', a: 'Ball' },
    { q: 'A bear that is cuddly and soft, a toy.', a: 'Bear' },
    { q: 'A colourful flying insect that visits flowers.', a: 'Butterfly' },
    { q: 'A vehicle with two wheels you pedal.', a: 'Bicycle' },
    { q: 'A yellow and black striped insect that can sting.', a: 'Bee' },
  ],
  C: [
    { q: 'An orange vegetable rabbits love to eat.', a: 'Carrot' },
    { q: 'A pet animal that says "meow".', a: 'Cat' },
    { q: 'You might eat this sweet food on your birthday.', a: 'Cake' },
    { q: 'A large animal with a hump on its back.', a: 'Camel' },
    { q: 'You use this to draw pictures on paper.', a: 'Crayon' },
    { q: 'A round yellow fruit that tastes sour.', a: 'Citrus' },
    { q: 'An animal that lives in the sea and has claws.', a: 'Crab' },
    { q: 'A bird with colourful feathers that can talk.', a: 'Cockatoo' },
    { q: 'You sit on this piece of furniture.', a: 'Chair' },
    { q: 'A white fluffy animal that gives us wool.', a: 'Cat' },
  ],
  D: [
    { q: 'A loyal pet animal that says "woof".', a: 'Dog' },
    { q: 'A reptile that breathes fire in fairy tales.', a: 'Dragon' },
    { q: 'You use this to draw straight lines.', a: 'Dotted ruler' },
    { q: 'A small fairy tale person who lives in caves.', a: 'Dwarf' },
    { q: 'A spotted animal that runs very fast.', a: 'Deer' },
    { q: 'A rubber toy that floats in the bathtub.', a: 'Duck' },
    { q: 'An animal that swims and has a bill.', a: 'Duck' },
    { q: 'You do this to move your body to music.', a: 'Dance' },
    { q: 'A tasty sweet treat on a stick.', a: 'Donut' },
    { q: 'The time of day when the sun goes down.', a: 'Dusk' },
  ],
  E: [
    { q: 'A big grey animal with large ears and a trunk.', a: 'Elephant' },
    { q: 'A bird lays this oval-shaped thing.', a: 'Egg' },
    { q: 'You send this message on a computer.', a: 'Email' },
    { q: 'A large bird that is the symbol of the USA.', a: 'Eagle' },
    { q: 'A slithery, worm-like fish.', a: 'Eel' },
    { q: 'People from another planet are sometimes called this.', a: 'Extraterrestrial' },
    { q: 'You use this to rub out pencil marks.', a: 'Eraser' },
    { q: 'A number that can be divided exactly by two.', a: 'Even' },
    { q: 'You press this to go up or down in a building.', a: 'Elevator' },
    { q: 'The meal you eat in the evening.', a: 'Evening meal' },
  ],
  F: [
    { q: 'A creature that lives in water and swims.', a: 'Fish' },
    { q: 'A red fruit with tiny seeds on the outside.', a: 'Fig' },
    { q: 'A soft, fluffy animal with a bushy tail.', a: 'Fox' },
    { q: 'The colour of grass and leaves.', a: 'Forest green' },
    { q: 'An amphibian that jumps and says "ribbit".', a: 'Frog' },
    { q: 'We eat these at a fair — they are potato sticks.', a: 'Fries' },
    { q: 'A colourful insect that flutters around flowers.', a: 'Fly' },
    { q: 'You use this to eat pasta or salad.', a: 'Fork' },
    { q: 'Fruits like apples and bananas are types of this.', a: 'Food' },
    { q: 'A bird with beautiful tail feathers that fans out.', a: 'Flamingo' },
  ],
  G: [
    { q: 'A farm animal that says "baa" and gives us wool.', a: 'Goat' },
    { q: 'A long-necked animal that eats leaves from tall trees.', a: 'Giraffe' },
    { q: 'This colour is the same as grass.', a: 'Green' },
    { q: 'A sweet food that bees make.', a: 'Golden honey' },
    { q: 'A round fruit that grows in clusters on a vine.', a: 'Grape' },
    { q: 'You wear this when it is cold outside.', a: 'Gloves' },
    { q: 'A large silver or gold fish often kept as a pet.', a: 'Goldfish' },
    { q: 'A person who looks after your health.', a: 'General practitioner' },
    { q: 'A small insect that hops in the grass.', a: 'Grasshopper' },
    { q: 'The person who takes care of a garden.', a: 'Gardener' },
  ],
  H: [
    { q: 'A large animal that you can ride.', a: 'Horse' },
    { q: 'You wear this on your head to stay warm.', a: 'Hat' },
    { q: 'This is where you live with your family.', a: 'Home' },
    { q: 'A small spiny animal that curls into a ball.', a: 'Hedgehog' },
    { q: 'A flying vehicle with spinning blades on top.', a: 'Helicopter' },
    { q: 'You use this to hit a nail into wood.', a: 'Hammer' },
    { q: 'Bees live in this.', a: 'Hive' },
    { q: 'A tall shape with four walls and a roof.', a: 'House' },
    { q: 'A large bird that hoots at night.', a: 'Hawk' },
    { q: 'The organ in your chest that pumps blood.', a: 'Heart' },
  ],
  I: [
    { q: 'Water becomes this when it freezes.', a: 'Ice' },
    { q: 'A cold sweet treat on a stick or in a cone.', a: 'Ice cream' },
    { q: 'A very large area of land surrounded by water.', a: 'Island' },
    { q: 'A small insect with six legs.', a: 'Insect' },
    { q: 'You use this to make clothes smooth and flat.', a: 'Iron' },
    { q: 'A painting or drawing in a book.', a: 'Illustration' },
    { q: 'The colour between green and violet in a rainbow.', a: 'Indigo' },
    { q: 'You decorate a cake with this sweet topping.', a: 'Icing' },
    { q: 'A mythical horse with a horn on its head.', a: 'Imaginary unicorn' },
    { q: 'A prickly plant that stays green all winter.', a: 'Ivy' },
  ],
  J: [
    { q: 'A big spotted cat that lives in the jungle.', a: 'Jaguar' },
    { q: 'You wear these trousers, often made of denim.', a: 'Jeans' },
    { q: 'A sweet spread made from fruit that you put on toast.', a: 'Jam' },
    { q: 'A person who makes people laugh at the circus.', a: 'Juggler' },
    { q: 'A large hopping animal from Australia.', a: 'Jumper' },
    { q: 'You wear this warm top in cold weather.', a: 'Jacket' },
  ],
  K: [
    { q: 'You use this to cut food in the kitchen.', a: 'Knife' },
    { q: 'A fluffy animal from Australia that eats eucalyptus.', a: 'Koala' },
    { q: 'You fly this in the wind on a string.', a: 'Kite' },
    { q: 'A baby cat is called this.', a: 'Kitten' },
    { q: 'You use these on a piano or computer.', a: 'Keys' },
    { q: 'A place where children learn before primary school.', a: 'Kindergarten' },
  ],
  L: [
    { q: 'A big cat with a fluffy mane.', a: 'Lion' },
    { q: 'A small crawling creature with lots of legs.', a: 'Ladybird' },
    { q: 'A flat, green part of a plant or tree.', a: 'Leaf' },
    { q: 'You use this to climb up to a high place.', a: 'Ladder' },
    { q: 'A baby sheep.', a: 'Lamb' },
    { q: 'This is used to light up a room.', a: 'Lamp' },
    { q: 'A yellow sour citrus fruit.', a: 'Lemon' },
    { q: 'A spotted wild cat.', a: 'Leopard' },
    { q: 'You lick this cold treat on a hot day.', a: 'Lollipop' },
    { q: 'A reptile that has four legs and a long tail.', a: 'Lizard' },
  ],
  M: [
    { q: 'A large sea animal that sprays water from its blowhole.', a: 'Mammal' },
    { q: 'An insect that bites and buzzes near your ear.', a: 'Mosquito' },
    { q: 'A small furry animal that likes cheese.', a: 'Mouse' },
    { q: 'You drink this white liquid from a cow.', a: 'Milk' },
    { q: 'A large hairy animal that swings in trees.', a: 'Monkey' },
    { q: 'The name for your female parent.', a: 'Mum' },
    { q: 'You see this bright object in the sky at night.', a: 'Moon' },
    { q: 'A fungus you put on pizza.', a: 'Mushroom' },
    { q: 'You use this to listen to tunes.', a: 'Music' },
    { q: 'A colourful sweet made of sugar.', a: 'Marshmallow' },
  ],
  N: [
    { q: 'You blow this body part when you have a cold.', a: 'Nose' },
    { q: 'The time of day when you eat a midday meal.', a: 'Noon' },
    { q: 'You read stories in this book at bedtime.', a: 'Novel' },
    { q: 'You write and draw in this book at school.', a: 'Notebook' },
    { q: 'A hard, round food that squirrels love.', a: 'Nut' },
    { q: 'A large bird that cannot fly and runs fast.', a: 'Nighthawk' },
    { q: 'You count with these — 1, 2, 3 are examples.', a: 'Numbers' },
    { q: 'A baby needs this to suck on for comfort.', a: 'Nummy' },
    { q: 'A nocturnal bird that says "hoot".', a: 'Night owl' },
    { q: 'The number that means none or nothing.', a: 'Naught' },
  ],
  O: [
    { q: 'A round orange fruit you peel before eating.', a: 'Orange' },
    { q: 'A sea creature with eight arms and ink.', a: 'Octopus' },
    { q: 'A large wise bird with big round eyes.', a: 'Owl' },
    { q: 'A fruit with a stone in the middle, green or black.', a: 'Olive' },
    { q: 'A vegetable that makes your eyes water when you cut it.', a: 'Onion' },
    { q: 'A type of big ape that has reddish fur.', a: 'Orangutan' },
    { q: 'A large flightless bird that hides its head in sand.', a: 'Ostrich' },
    { q: 'A huge ocean — the Pacific is one.', a: 'Ocean' },
    { q: 'A musical instrument with black and white keys.', a: 'Organ' },
    { q: 'A sea animal that is a type of shellfish.', a: 'Oyster' },
  ],
  P: [
    { q: 'A black and white bear from China.', a: 'Panda' },
    { q: 'A bird that cannot fly and lives in cold places.', a: 'Penguin' },
    { q: 'A round fruit with red or green skin.', a: 'Pear' },
    { q: 'A pig makes this sound.', a: 'Piglet' },
    { q: 'A colourful bird that can copy your words.', a: 'Parrot' },
    { q: 'Something you bounce or kick in sports.', a: 'Puck' },
    { q: 'A yellow flower that blooms in spring.', a: 'Pansy' },
    { q: 'An animal with a bushy striped tail and a mask.', a: 'Porcupine' },
    { q: 'You use this to colour pictures.', a: 'Pencil' },
    { q: 'A salty snack that comes in a bag and is crispy.', a: 'Popcorn' },
  ],
  Q: [
    { q: 'The female ruler of a country.', a: 'Queen' },
    { q: 'The sound a duck makes.', a: 'Quack' },
    { q: 'A warm blanket made of patches of fabric.', a: 'Quilt' },
    { q: 'Very fast or speedy.', a: 'Quick' },
    { q: 'A group of singers who perform together.', a: 'Quartet' },
    { q: 'A bird with a round body and small tail.', a: 'Quail' },
  ],
  R: [
    { q: 'A small furry animal with long ears that hops.', a: 'Rabbit' },
    { q: 'Colourful arched bands you see in the sky after rain.', a: 'Rainbow' },
    { q: 'A large striped cat from Asia.', a: 'Rhino' },
    { q: 'Water that falls from clouds.', a: 'Rain' },
    { q: 'A small red and black spotted insect.', a: 'Rescue bug' },
    { q: 'A bird with a red chest that hops on lawns.', a: 'Robin' },
    { q: 'A toy you build with colourful bricks.', a: 'Rocket' },
    { q: 'A small mammal with a long bushy tail that climbs trees.', a: 'Raccoon' },
    { q: 'You find this on a road for cars to drive on.', a: 'Road' },
    { q: 'A large grey animal with a horn on its nose.', a: 'Rhinoceros' },
  ],
  S: [
    { q: 'A star you see shining in the sky at night.', a: 'Star' },
    { q: 'A reptile that slithers and has no legs.', a: 'Snake' },
    { q: 'A bright yellow ball in the sky that gives us warmth.', a: 'Sun' },
    { q: 'You build a castle with this at the beach.', a: 'Sand' },
    { q: 'A sea creature with five points on its body.', a: 'Starfish' },
    { q: 'You sit on this to slide down at the playground.', a: 'Slide' },
    { q: 'A slow animal that carries its home on its back.', a: 'Snail' },
    { q: 'A yellow smiley face emoji is this colour.', a: 'Sunshine yellow' },
    { q: 'A person who flies through space.', a: 'Spaceman' },
    { q: 'A tiny arachnid that spins a web.', a: 'Spider' },
  ],
  T: [
    { q: 'A large striped wild cat.', a: 'Tiger' },
    { q: 'You climb up into this toy.', a: 'Treehouse' },
    { q: 'A large reptile that lived millions of years ago.', a: 'Tyrannosaurus' },
    { q: 'A vehicle with long tracks that drives on rough ground.', a: 'Tank' },
    { q: 'You use this to clean your teeth.', a: 'Toothbrush' },
    { q: 'A tropical fruit with spiky skin and sweet yellow inside.', a: 'Tangerine' },
    { q: 'You jump on this bouncy springy surface.', a: 'Trampoline' },
    { q: 'A vehicle with lots of wheels that carries heavy loads.', a: 'Truck' },
    { q: 'A small toy that spins on a point.', a: 'Top' },
    { q: 'A large animal with a trunk, tusks, and big ears.', a: 'Tiger elephant' },
  ],
  U: [
    { q: 'You open this to keep dry in the rain.', a: 'Umbrella' },
    { q: 'A magical horse with a single horn on its head.', a: 'Unicorn' },
    { q: 'A Pixar movie about a house lifted by balloons.', a: 'Up' },
    { q: 'The space beyond Earth is called the outer this.', a: 'Universe' },
    { q: 'You wear this for school every day.', a: 'Uniform' },
    { q: 'The opposite of down.', a: 'Up' },
  ],
  V: [
    { q: 'A purple flower shaped like a tiny bell.', a: 'Violet' },
    { q: 'A vehicle with a large box at the back for carrying things.', a: 'Van' },
    { q: 'A doctor for animals.', a: 'Vet' },
    { q: 'A plant that climbs up a wall.', a: 'Vine' },
    { q: 'A musical instrument shaped like a body you play with a bow.', a: 'Violin' },
    { q: 'You eat these green vegetables — they look like tiny trees.', a: 'Veggies' },
  ],
  W: [
    { q: 'A large animal that lives in the sea and sprays water.', a: 'Whale' },
    { q: 'Air that blows outside on a breezy day.', a: 'Wind' },
    { q: 'A small furry animal that digs holes in the garden.', a: 'Worm' },
    { q: 'You look through this clear opening in a wall.', a: 'Window' },
    { q: 'A wild dog that howls at the moon.', a: 'Wolf' },
    { q: 'You use this in the forest to build a fire.', a: 'Wood' },
    { q: 'A person who uses magic and a broomstick.', a: 'Witch' },
    { q: 'An insect that makes a buzzing sound like a bee.', a: 'Wasp' },
    { q: 'You drink this clear liquid to stay healthy.', a: 'Water' },
    { q: 'A soft toy that looks like a bear.', a: 'Wombat' },
  ],
  X: [
    { q: 'A doctor takes this picture to see inside your body.', a: 'Xray' },
    { q: 'A musical instrument with wooden bars that you hit.', a: 'Xylophone' },
    { q: 'The letter that looks like two crossed lines.', a: 'X' },
    { q: 'A shape with four equal arms pointing outward, like this letter.', a: 'X shape' },
  ],
  Y: [
    { q: 'The colour of a banana or the sun.', a: 'Yellow' },
    { q: 'A round toy that goes up and down on a string.', a: 'Yoyo' },
    { q: 'A shaggy animal from the mountains of Asia.', a: 'Yak' },
    { q: 'A creamy food often eaten at breakfast with fruit.', a: 'Yoghurt' },
    { q: 'You open your mouth wide and do this when you are sleepy.', a: 'Yawn' },
    { q: 'The opposite of old, when something is brand new.', a: 'Young' },
  ],
  Z: [
    { q: 'A black and white striped African animal.', a: 'Zebra' },
    { q: 'A place where you can see many animals.', a: 'Zoo' },
    { q: 'The number that means nothing — 0.', a: 'Zero' },
    { q: 'You do this when you sleep, making a buzzing sound.', a: 'Zzz' },
    { q: 'A small fastener on a jacket or bag.', a: 'Zip' },
    { q: 'A lively or energetic feeling — full of life.', a: 'Zest' },
  ],
};
