import type { RawPack } from '../core/packs';

export const medicineBodyPack: RawPack = {
  id: 'medicine-body',
  name: 'Medicine and the Human Body',
  description: 'Organs, bones, blood, vitamins, vaccines and the pioneers who figured it all out.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🩺',
  accent: '#be123c',
  letters: {
    A: [
      { q: 'The largest artery in the body, carrying blood away from the left ventricle.', a: 'Aorta' },
      { q: 'The small worm-shaped pouch attached to the large intestine, often removed when it becomes inflamed.', a: 'Appendix' },
      { q: 'The tiny air sacs in the lungs where oxygen passes into the bloodstream.', a: 'Alveoli' },
      { q: 'The hormone released in a fight-or-flight moment, produced by glands above the kidneys.', a: 'Adrenaline', alt: ['Epinephrine'] },
      { q: 'The medical practice of putting a patient to sleep or numbing them so surgery is painless.', a: 'Anaesthesia', alt: ['Anesthesia'] },
      { q: 'The common painkiller derived from willow bark and sold by Bayer from 1899.', a: 'Aspirin' },
      { q: 'The condition of having too few oxygen-carrying red cells, causing tiredness and pallor.', a: 'Anaemia', alt: ['Anemia'] },
      { q: 'The long-term condition in which the airways narrow, usually treated with an inhaler.', a: 'Asthma' },
      { q: 'Either of the two upper chambers of the heart that receive incoming blood.', a: 'Atrium' },
      { q: 'The almond-shaped brain structure central to fear and emotional memory.', a: 'Amygdala' },
      { q: 'The thick cord joining the calf muscles to the heel, named after a Greek warrior.', a: 'Achilles tendon' },
      { q: 'Drugs such as penicillin that kill bacteria or stop them multiplying.', a: 'Antibiotics' },
    ],
    B: [
      { q: 'The organ inside the skull that controls thought, memory and movement.', a: 'Brain' },
      { q: 'The muscular sac that stores urine before it leaves the body.', a: 'Bladder' },
      { q: 'The muscle at the front of the upper arm that bulges when you flex.', a: 'Biceps' },
      { q: 'The greenish digestive fluid made by the liver and released to break down fats.', a: 'Bile' },
      { q: 'The two large tubes that branch off the windpipe, one into each lung.', a: 'Bronchi' },
      { q: 'The soft spongy tissue in the hollow centre of the skeleton where new blood cells are made.', a: 'Bone marrow' },
      { q: 'The nerve and heart illness caused by a lack of thiamine, common where polished rice was the staple food.', a: 'Beriberi' },
      { q: 'Canadian scientist who, with Charles Best, first isolated insulin in 1921 (surname).', a: 'Banting' },
      { q: 'South African surgeon who performed the first human heart transplant in 1967 (surname).', a: 'Barnard' },
      { q: 'The reading taken with an inflatable arm cuff, given as two numbers such as 120 over 80.', a: 'Blood pressure' },
      { q: 'Severe poisoning by a toxin from improperly canned food that paralyses the muscles.', a: 'Botulism' },
      { q: 'Single-celled microbes, some helpful in the gut and others causing illness.', a: 'Bacteria' },
    ],
    C: [
      { q: 'The tough flexible tissue that cushions joints and shapes the nose and ears.', a: 'Cartilage' },
      { q: 'The spiral snail-shaped part of the inner ear that turns vibrations into nerve signals.', a: 'Cochlea' },
      { q: 'The clear front covering of the eye, reshaped in laser vision surgery.', a: 'Cornea' },
      { q: 'The slender bone linking the breastbone to the shoulder blade, often broken in falls.', a: 'Clavicle', alt: ['Collarbone'] },
      { q: 'The narrowest blood vessels, only one cell wide, where gases pass into the tissues.', a: 'Capillaries' },
      { q: 'The cauliflower-shaped region at the back of the brain that coordinates balance.', a: 'Cerebellum' },
      { q: 'The fatty substance in the blood measured as HDL and LDL.', a: 'Cholesterol' },
      { q: 'The itchy childhood illness of spots and blisters caused by the varicella virus.', a: 'Chickenpox' },
      { q: 'The severe diarrhoeal illness John Snow traced to a Broad Street water pump in 1854.', a: 'Cholera' },
      { q: 'The mineral abundant in milk that hardens the bones and teeth.', a: 'Calcium' },
      { q: 'The branch of medicine dealing with the heart and its blood vessels.', a: 'Cardiology' },
      { q: 'The small triangular bone at the base of the spine, a remnant of a tail.', a: 'Coccyx', alt: ['Tailbone'] },
      { q: 'The most abundant protein in the body, giving skin its firmness.', a: 'Collagen' },
      { q: 'The main length of the large intestine, where water is absorbed from waste.', a: 'Colon' },
      { q: 'Treating cancer with powerful drugs that kill fast-dividing cells.', a: 'Chemotherapy' },
    ],
    D: [
      { q: 'The thicker inner layer of the skin, holding sweat glands, vessels and nerve endings.', a: 'Dermis' },
      { q: 'The dome-shaped sheet of muscle below the lungs that drives breathing.', a: 'Diaphragm' },
      { q: 'The condition in which the body cannot control blood sugar properly, often managed with insulin.', a: 'Diabetes' },
      { q: 'The branch of medicine concerned with the skin and its conditions.', a: 'Dermatology' },
      { q: 'The machine treatment that filters the blood when the kidneys have failed.', a: 'Dialysis' },
      { q: 'The first short section of the small intestine, just beyond the stomach.', a: 'Duodenum' },
      { q: 'The brain chemical linked to reward and motivation, lacking in Parkinson\'s.', a: 'Dopamine' },
      { q: 'The device that delivers a shock to restore a normal heart rhythm.', a: 'Defibrillator' },
      { q: 'The hard yellowish layer that lies beneath tooth enamel.', a: 'Dentine', alt: ['Dentin'] },
    ],
    E: [
      { q: 'The outermost layer of the skin, constantly shedding dead cells.', a: 'Epidermis' },
      { q: 'The hardest substance in the human body, coating the teeth.', a: 'Enamel' },
      { q: 'The muscular tube that carries swallowed food down to the stomach.', a: 'Esophagus', alt: ['Oesophagus', 'Gullet'] },
      { q: 'The thin membrane that vibrates when sound reaches it, also called the tympanic membrane.', a: 'Eardrum' },
      { q: 'The flap of cartilage that folds down over the windpipe when you swallow.', a: 'Epiglottis' },
      { q: 'The neurological disorder marked by recurring seizures.', a: 'Epilepsy' },
      { q: 'The often fatal haemorrhagic fever first identified near a river in Zaire in 1976.', a: 'Ebola' },
      { q: 'The flexible camera on a tube that a doctor passes inside the body to look at the gut.', a: 'Endoscope' },
      { q: 'The main female sex hormone, produced chiefly by the ovaries.', a: 'Estrogen', alt: ['Oestrogen'] },
      { q: 'The very common skin complaint of dry, itchy, inflamed patches.', a: 'Eczema' },
    ],
    F: [
      { q: 'The longest and strongest bone in the human body.', a: 'Femur', alt: ['Thigh bone'] },
      { q: 'The thinner of the two bones in the lower leg, running beside the shin.', a: 'Fibula' },
      { q: 'Scottish scientist who noticed a mould killing bacteria in 1928 and so found penicillin (surname).', a: 'Fleming' },
      { q: 'The mineral added to toothpaste and drinking water to prevent decay.', a: 'Fluoride' },
      { q: 'Viennese founder of psychoanalysis and author of The Interpretation of Dreams (surname).', a: 'Freud' },
      { q: 'Tissue damage caused by extreme cold, most often to fingers and toes.', a: 'Frostbite' },
      { q: 'The small pocket in the skin from which a single hair grows.', a: 'Follicle' },
      { q: 'A body temperature raised above normal while the immune system fights infection.', a: 'Fever' },
      { q: 'The unborn baby from about the ninth week of pregnancy onward.', a: 'Foetus', alt: ['Fetus'] },
      { q: 'The soft spot between the skull bones of a newborn baby.', a: 'Fontanelle' },
    ],
    G: [
      { q: 'The small pear-shaped sac tucked under the liver that stores bile.', a: 'Gall bladder', alt: ['Gallbladder'] },
      { q: 'The simple sugar carried in the blood as the body\'s main fuel.', a: 'Glucose' },
      { q: 'The visible neck swelling caused by an enlarged thyroid, often from lack of iodine.', a: 'Goitre', alt: ['Goiter'] },
      { q: 'Greek physician of the Roman era whose anatomy writings went unchallenged for over a thousand years.', a: 'Galen' },
      { q: 'Units of inheritance carried along the chromosomes.', a: 'Genes' },
      { q: 'The branch of medicine dealing with the stomach and intestines.', a: 'Gastroenterology' },
      { q: 'The eye condition in which raised internal pressure damages the optic nerve and steals sight.', a: 'Glaucoma' },
    ],
    H: [
      { q: 'The muscular pump in the chest that drives blood around the body.', a: 'Heart' },
      { q: 'The iron-rich protein in red cells that binds and carries oxygen.', a: 'Haemoglobin', alt: ['Hemoglobin'] },
      { q: 'The single long bone of the upper arm.', a: 'Humerus' },
      { q: 'The small brain region that regulates temperature, hunger and thirst.', a: 'Hypothalamus' },
      { q: 'The seahorse-shaped brain structure essential to forming new memories.', a: 'Hippocampus' },
      { q: 'Inflammation of the liver, with viral types labelled A, B and C.', a: 'Hepatitis' },
      { q: 'The chemical the body releases in an allergic reaction, causing itching and swelling.', a: 'Histamine' },
      { q: 'Ancient Greek physician of Kos regarded as the father of medicine and remembered in an oath.', a: 'Hippocrates' },
      { q: 'English physician who showed in 1628 that blood circulates, pushed round by the heart (surname).', a: 'Harvey' },
      { q: 'Chemical messengers released into the blood by glands.', a: 'Hormones' },
    ],
    I: [
      { q: 'The pancreatic hormone that lowers blood sugar and is injected by many diabetics.', a: 'Insulin' },
      { q: 'The coloured ring of muscle that controls how much light enters the eye.', a: 'Iris' },
      { q: 'The viral illness of fever, aches and chills that is vaccinated against each winter.', a: 'Influenza', alt: ['Flu'] },
      { q: 'The element once painted on wounds as an antiseptic and needed by the thyroid.', a: 'Iodine' },
      { q: 'The common anti-inflammatory painkiller sold as Advil or Nurofen.', a: 'Ibuprofen' },
      { q: 'The mineral in red meat and spinach needed to build haemoglobin.', a: 'Iron' },
      { q: 'The flat front teeth used for cutting into food.', a: 'Incisors' },
      { q: 'The study of the body\'s defences against infection.', a: 'Immunology' },
      { q: 'The persistent inability to fall asleep or stay asleep.', a: 'Insomnia' },
    ],
    J: [
      { q: 'The yellowing of skin and eyes from a build-up of bilirubin, often a sign of liver trouble.', a: 'Jaundice' },
      { q: 'English doctor who used cowpox in 1796 to create the first vaccine against smallpox (surname).', a: 'Jenner' },
      { q: 'The large vein in the neck that returns blood from the head towards the heart.', a: 'Jugular' },
      { q: 'Places where two bones meet, such as the knee and the elbow.', a: 'Joints' },
    ],
    K: [
      { q: 'The pair of bean-shaped organs that filter waste from the blood to make urine.', a: 'Kidneys' },
      { q: 'The tough protein that hair and nails are made of.', a: 'Keratin' },
      { q: 'German bacteriologist who identified the germs behind tuberculosis and cholera (surname).', a: 'Koch' },
      { q: 'The bony ridge formed by a finger joint at the back of the hand.', a: 'Knuckle' },
    ],
    L: [
      { q: 'The organ in the throat holding the vocal cords, better known as the voice box.', a: 'Larynx' },
      { q: 'The largest internal organ, which detoxifies blood, stores sugar and makes bile.', a: 'Liver' },
      { q: 'The pair of spongy organs in the chest that take in oxygen.', a: 'Lungs' },
      { q: 'The clear fluid that drains through nodes as part of the immune system.', a: 'Lymph' },
      { q: 'Cancer of the blood-forming tissue, marked by huge numbers of abnormal white cells.', a: 'Leukaemia', alt: ['Leukemia'] },
      { q: 'The tough band of tissue that connects one bone to another at a joint.', a: 'Ligament' },
      { q: 'British surgeon who brought carbolic acid antiseptics into the operating theatre (surname).', a: 'Lister' },
      { q: 'The clear structure behind the pupil that focuses light on the retina and clouds in a cataract.', a: 'Lens' },
      { q: 'The ancient bacterial illness of nerve damage and skin lesions whose sufferers were once isolated in colonies.', a: 'Leprosy' },
    ],
    M: [
      { q: 'The pigment that gives skin and hair their colour and deepens in the sun.', a: 'Melanin' },
      { q: 'The broad back teeth used for grinding food.', a: 'Molars' },
      { q: 'The parasitic illness spread by the bite of the Anopheles mosquito.', a: 'Malaria' },
      { q: 'The highly contagious viral rash illness prevented by the MMR jab.', a: 'Measles' },
      { q: 'The whole set of chemical reactions that turn food into energy inside the body.', a: 'Metabolism' },
      { q: 'The organelles known as the powerhouses of the cell.', a: 'Mitochondria' },
      { q: 'The viral infection that swells the salivary glands beside the jaw.', a: 'Mumps' },
      { q: 'The powerful opium-derived painkiller named after the Greek god of dreams.', a: 'Morphine' },
      { q: 'The only movable bone of the skull, carrying the lower teeth.', a: 'Mandible', alt: ['Jawbone'] },
      { q: 'The hormone from the pineal gland that tells the body it is time to sleep.', a: 'Melatonin' },
      { q: 'The trained professional who assists a woman through childbirth.', a: 'Midwife' },
    ],
    N: [
      { q: 'The microscopic filtering unit of the kidney, with about a million in each one.', a: 'Nephron' },
      { q: 'The cell that carries electrical signals through the nervous system.', a: 'Neuron' },
      { q: 'English nurse of the Crimean War known as the Lady with the Lamp (surname).', a: 'Nightingale' },
      { q: 'The queasy feeling that you are about to vomit.', a: 'Nausea' },
      { q: 'The B vitamin, also labelled B3, whose deficiency causes pellagra.', a: 'Niacin' },
      { q: 'The branch of medicine dealing with the brain, spine and nerves.', a: 'Neurology' },
      { q: 'The two openings of the nose through which air is drawn in.', a: 'Nostrils' },
    ],
    O: [
      { q: 'The bundle of fibres carrying visual signals from the retina to the brain.', a: 'Optic nerve' },
      { q: 'The condition of thinning, brittle bones, common in older women after menopause.', a: 'Osteoporosis' },
      { q: 'The pair of female organs that release eggs and make estrogen.', a: 'Ovaries' },
      { q: 'The hormone released during childbirth and bonding, nicknamed the love hormone.', a: 'Oxytocin' },
      { q: 'The branch of medicine devoted to the treatment of cancer.', a: 'Oncology' },
      { q: 'The branch of medicine dealing with pregnancy and childbirth.', a: 'Obstetrics' },
      { q: 'The surgical speciality dealing with bones and joints.', a: 'Orthopaedics', alt: ['Orthopedics'] },
    ],
    P: [
      { q: 'The gland behind the stomach that makes insulin and digestive juices.', a: 'Pancreas' },
      { q: 'The small flat bone that shields the front of the knee.', a: 'Patella', alt: ['Kneecap'] },
      { q: 'The dark opening at the centre of the eye that widens in dim light.', a: 'Pupil' },
      { q: 'The pea-sized gland at the base of the brain, nicknamed the master gland.', a: 'Pituitary' },
      { q: 'The pale yellow liquid part of blood in which the cells are suspended.', a: 'Plasma' },
      { q: 'The tiny fragments in blood that clump together to start a clot.', a: 'Platelets' },
      { q: 'The first widely used antibiotic, discovered growing as a mould in a dish.', a: 'Penicillin' },
      { q: 'French scientist behind germ theory, a rabies vaccine and a milk-heating process (surname).', a: 'Pasteur' },
      { q: 'The viral illness that paralysed children until vaccines by Salk and Sabin.', a: 'Polio' },
      { q: 'Infection that fills the air sacs of the lungs with fluid, once called the old man\'s friend.', a: 'Pneumonia' },
      { q: 'The branch of medicine that treats babies and children.', a: 'Paediatrics', alt: ['Pediatrics'] },
      { q: 'The organ that grows in the womb to feed the developing baby.', a: 'Placenta' },
      { q: 'The passage behind the nose and mouth that leads to the gullet and windpipe.', a: 'Pharynx' },
      { q: 'An artificial replacement for a missing limb.', a: 'Prosthesis' },
      { q: 'The branch of medicine that treats mental illness with therapy and drugs.', a: 'Psychiatry' },
    ],
    Q: [
      { q: 'The big four-part muscle group at the front of the thigh that straightens the knee.', a: 'Quadriceps' },
      { q: 'The bitter bark extract long used against malaria and still found in tonic water.', a: 'Quinine' },
      { q: 'Keeping possibly infectious people apart from others, named from a forty-day wait in Venice.', a: 'Quarantine' },
    ],
    R: [
      { q: 'The light-sensitive layer at the back of the eye holding the rods and cones.', a: 'Retina' },
      { q: 'The twelve pairs of curved bones that form a cage around the heart and lungs.', a: 'Ribs' },
      { q: 'The disc-shaped carriers of oxygen that give circulation its characteristic colour.', a: 'Red blood cells', alt: ['Erythrocytes'] },
      { q: 'The virus of the nervous system spread by animal bites and once almost always fatal.', a: 'Rabies' },
      { q: 'The childhood bone-softening illness caused by a lack of vitamin D.', a: 'Rickets' },
      { q: 'The medical field that reads X-rays and other scans.', a: 'Radiology' },
      { q: 'The forearm bone on the thumb side.', a: 'Radius' },
      { q: 'German physicist who discovered X-rays in 1895 (surname).', a: 'Roentgen', alt: ['Rontgen'] },
      { q: 'The blood group property that makes a type positive or negative.', a: 'Rhesus factor' },
    ],
    S: [
      { q: 'The flat bone down the front of the chest where the ribs meet.', a: 'Sternum', alt: ['Breastbone'] },
      { q: 'The organ below the left ribs that filters blood and stores white cells.', a: 'Spleen' },
      { q: 'The largest organ of the body, covering about two square metres in an adult.', a: 'Skin' },
      { q: 'The watery fluid in the mouth that starts digesting starch.', a: 'Saliva' },
      { q: 'The flat triangular bone at the back of the shoulder.', a: 'Scapula', alt: ['Shoulder blade'] },
      { q: 'The instrument a doctor holds to your chest to listen to the heart and lungs.', a: 'Stethoscope' },
      { q: 'The sailors\' illness of bleeding gums and loose teeth caused by lack of vitamin C.', a: 'Scurvy' },
      { q: 'A sudden loss of blood supply to part of the brain, causing weakness or slurred speech.', a: 'Stroke' },
      { q: 'The bony case of twenty-two bones that protects the brain.', a: 'Skull' },
      { q: 'The tiny gap across which one nerve cell passes a signal to the next.', a: 'Synapse' },
      { q: 'The longest single strand of the nervous system, running from the lower back down the leg.', a: 'Sciatic nerve' },
      { q: 'The scarring viral disease declared eradicated worldwide in 1980.', a: 'Smallpox' },
      { q: 'The brain chemical linked to mood, targeted by SSRI antidepressants.', a: 'Serotonin' },
      { q: 'Hungarian doctor who cut childbed deaths by insisting that staff wash their hands (surname).', a: 'Semmelweis' },
    ],
    T: [
      { q: 'The cartilage-ringed tube that carries air from the throat down to the lungs.', a: 'Trachea', alt: ['Windpipe'] },
      { q: 'The larger weight-bearing bone of the lower leg, known as the shin bone.', a: 'Tibia' },
      { q: 'The butterfly-shaped gland in the neck that sets the body\'s metabolic rate.', a: 'Thyroid' },
      { q: 'The tough cord that attaches a muscle to a bone.', a: 'Tendon' },
      { q: 'The pair of lymph tissue lumps at the back of the throat, often removed in childhood.', a: 'Tonsils' },
      { q: 'The main male sex hormone, driving muscle growth and a deeper voice.', a: 'Testosterone' },
      { q: 'The lung disease once called consumption, caused by a bacillus Koch identified.', a: 'Tuberculosis' },
      { q: 'The muscle-locking illness caught through dirty wounds, also known as lockjaw.', a: 'Tetanus' },
      { q: 'The instrument used to measure body temperature.', a: 'Thermometer' },
      { q: 'The fever spread by contaminated food and water, famously carried by Mary Mallon.', a: 'Typhoid' },
      { q: 'The three-headed muscle at the back of the upper arm that straightens the elbow.', a: 'Triceps' },
    ],
    U: [
      { q: 'The forearm bone on the little-finger side.', a: 'Ulna' },
      { q: 'The tube through which urine is passed out of the body.', a: 'Urethra' },
      { q: 'Either of the two tubes that carry urine from a kidney down to the bladder.', a: 'Ureter' },
      { q: 'The muscular organ in which a baby grows during pregnancy.', a: 'Uterus', alt: ['Womb'] },
      { q: 'The scan that uses high-frequency sound to picture a baby before birth.', a: 'Ultrasound' },
      { q: 'The branch of medicine dealing with the kidneys, bladder and their tubes.', a: 'Urology' },
      { q: 'The lifeline connecting an unborn baby to the placenta, cut at birth.', a: 'Umbilical cord' },
    ],
    V: [
      { q: 'Vessels that carry blood back towards the heart, fitted with one-way valves.', a: 'Veins' },
      { q: 'The thirty-three bones stacked on top of each other to form the spine.', a: 'Vertebrae' },
      { q: 'The tiny finger-like projections lining the small intestine to absorb nutrients.', a: 'Villi' },
      { q: 'A preparation that trains the immune system to recognise a germ before it strikes.', a: 'Vaccine' },
      { q: 'Either of the two lower pumping chambers of the heart.', a: 'Ventricle' },
      { q: 'A tiny infectious agent that can only reproduce inside a living host cell.', a: 'Virus' },
      { q: 'Flemish anatomist whose 1543 book corrected Galen using real dissections (surname).', a: 'Vesalius' },
      { q: 'The nutrient the skin makes from sunlight, needed for strong bones.', a: 'Vitamin D' },
    ],
    W: [
      { q: 'The defensive bodies of the immune system that engulf invading microbes, also called leucocytes.', a: 'White blood cells' },
      { q: 'The small rough skin growths caused by a papillomavirus.', a: 'Warts' },
      { q: 'The childhood infection whose violent fits end in a high gasping noise, also called pertussis.', a: 'Whooping cough' },
      { q: 'American who, with Francis Crick, described the double helix in 1953 (surname).', a: 'Watson' },
      { q: 'The four rearmost molars that appear in early adulthood and are often extracted.', a: 'Wisdom teeth' },
    ],
    X: [
      { q: 'The imaging beam used to see whether a bone is broken.', a: 'X-ray' },
      { q: 'The small cartilage tip at the very bottom of the breastbone.', a: 'Xiphoid process' },
    ],
    Y: [
      { q: 'The involuntary wide-mouthed deep breath associated with tiredness.', a: 'Yawn' },
      { q: 'The mosquito-borne viral illness that plagued the builders of the Panama Canal.', a: 'Yellow fever' },
    ],
    Z: [
      { q: 'The trace mineral important for wound healing and taste, plentiful in oysters.', a: 'Zinc' },
      { q: 'The single cell formed the moment a sperm fertilises an egg.', a: 'Zygote' },
    ],
  },
};
