import type { RawPack, RawQuestion } from '../core/packs';

/**
 * "Guess the Melody" — a real audio-clip pack. Each clip is an ORIGINAL synthesized
 * rendition of a famous PUBLIC-DOMAIN melody (compositions are public domain; the
 * rendition is ours), generated by scripts/genclips.mjs into /public/clips. Fully
 * legal to bundle. The board letters are hidden so the tune is the only clue.
 */
const clip = (id: string): string => `/clips/${id}.wav`;
const PROMPT = 'Name this famous tune.';
function q(name: string, id: string, alt?: string[]): RawQuestion {
  return { q: PROMPT, a: name, audio: clip(id), category: 'music', ...(alt ? { alt } : {}) };
}

export const melodiesPack: RawPack = {
  id: 'melodies',
  name: 'Guess the Melody',
  description: 'Listen to a famous tune and name it. Real audio clips!',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎼',
  accent: '#0ea5e9',
  hideBoardLetters: true,
  letters: {
    A: [q('Amazing Grace', 'amazinggrace')],
    B: [q('Beethoven', 'beethoven5', ["beethoven's fifth", 'fifth symphony', 'symphony no 5']), q('Blue Danube', 'bluedanube', ['the blue danube', 'danube'])],
    C: [q('Canon in D', 'canon', ['pachelbel', "pachelbel's canon", 'canon']), q('Can-Can', 'cancan', ['cancan'])],
    E: [q('Eine kleine Nachtmusik', 'einekleine', ['mozart', 'a little night music'])],
    F: [q('Für Elise', 'furelise', ['fur elise', 'beethoven'])],
    G: [q('Greensleeves', 'greensleeves')],
    H: [q('Hall of the Mountain King', 'mountainking', ['grieg', 'in the hall of the mountain king']), q('Happy Birthday', 'happybirthday')],
    J: [q('Jingle Bells', 'jinglebells')],
    L: [q('Lullaby', 'lullaby', ['brahms', "brahms' lullaby", 'cradle song'])],
    M: [q('Mary Had a Little Lamb', 'marylamb')],
    N: [q('Nutcracker', 'nutcracker', ['the nutcracker', 'tchaikovsky', 'dance of the sugar plum fairy'])],
    O: [q('Ode to Joy', 'odetojoy', ['beethoven', 'ninth symphony'])],
    R: [q('Row Row Row Your Boat', 'rowboat', ['row your boat'])],
    S: [q('Swan Lake', 'swanlake', ['tchaikovsky']), q('Spring', 'springvivaldi', ['vivaldi', 'the four seasons', 'four seasons'])],
    T: [q('Turkish March', 'turkishmarch', ['mozart', 'rondo alla turca']), q('Twinkle Twinkle', 'twinkle', ['twinkle twinkle little star', 'twinkle'])],
    V: [q('Valkyries', 'valkyries', ['ride of the valkyries', 'wagner'])],
    W: [q('William Tell', 'williamtell', ['william tell overture', 'rossini']), q('Wedding March', 'weddingmarch', ['mendelssohn'])],
  },
};
