import type { RawPack } from '../core/packs';

export const moneyEconomicsPack: RawPack = {
  id: 'money-economics',
  name: 'Money & Economics',
  description: 'Currencies, markets, famous economists and how money works.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '💰',
  accent: '#15803d',
  letters: {
    A: [
      { q: 'Profiting from a price gap for the same asset in two markets at once.', a: 'Arbitrage' },
      { q: 'The online retailer Jeff Bezos founded in 1994.', a: 'Amazon' },
      { q: 'Government policy of cutting public spending to shrink deficits.', a: 'Austerity' },
      { q: 'The first US company to reach a one trillion dollar market value, in 2018.', a: 'Apple' },
      { q: 'A product that pays a fixed sum every year for the rest of your life.', a: 'Annuity' },
      { q: 'The Scottish author of The Wealth of Nations.', a: 'Adam Smith' },
      { q: 'Anything of value that a business owns and can put a figure on.', a: 'Asset' },
      { q: 'Spreading the cost of an intangible item over its useful life in the accounts.', a: 'Amortization' },
      { q: 'This South American nation defaulted on about 100 billion dollars of debt in 2001.', a: 'Argentina' },
      { q: 'The body of law aimed at breaking up monopolies and stopping price fixing.', a: 'Antitrust' },
      { q: 'A rise in the value of one currency measured against others.', a: 'Appreciation' },
      { q: 'The Saudi oil giant whose 2019 flotation was the largest ever.', a: 'Aramco' },
    ],
    B: [
      { q: 'The first cryptocurrency, launched in 2009 by Satoshi Nakamoto.', a: 'Bitcoin' },
      { q: 'The name for a long stretch of steadily rising share prices.', a: 'Bull Market' },
      { q: 'The institution founded in 1694 that now sets interest rates for the United Kingdom.', a: 'Bank of England' },
      { q: 'A tradable IOU issued by a government or firm that pays a coupon.', a: 'Bond' },
      { q: 'A drop of 20 percent or more from recent highs in share prices.', a: 'Bear Market' },
      { q: 'Trading goods directly for other goods without using money.', a: 'Barter' },
      { q: 'The 1944 New Hampshire conference that created the IMF and the World Bank.', a: 'Bretton Woods' },
      { q: 'What exists when a government spends more in a year than it takes in.', a: 'Budget Deficit' },
      { q: 'Warren Buffett\'s holding company, based in Omaha.', a: 'Berkshire Hathaway' },
      { q: 'The statement listing what a firm owns and owes at a single point in time.', a: 'Balance Sheet' },
      { q: 'Germany\'s central bank, long famous for its hard line on inflation.', a: 'Bundesbank' },
      { q: 'Nickname for shares in a large, long established and reliable company.', a: 'Blue Chip' },
    ],
    C: [
      { q: 'Earnings that themselves go on to earn further returns over time.', a: 'Compound Interest' },
      { q: 'The institution that issues a nation\'s money and sets its base rate.', a: 'Central Bank' },
      { q: 'The basket-of-goods measure used to report inflation each month.', a: 'Consumer Price Index' },
      { q: 'Property pledged to a lender that can be seized if a loan is not repaid.', a: 'Collateral' },
      { q: 'A group of producers that agrees to limit output to keep prices high.', a: 'Cartel' },
      { q: 'The Atlanta drinks giant whose shares Warren Buffett began buying in 1988.', a: 'Coca-Cola' },
      { q: 'In the national accounts, household spending on goods and services.', a: 'Consumption' },
      { q: 'The insurance-like derivative that paid out when mortgage securities failed in 2008.', a: 'Credit Default Swap' },
      { q: 'The movement of money in and out of a business over a period.', a: 'Cash Flow' },
      { q: 'The US city whose Mercantile Exchange runs the biggest futures marketplace.', a: 'Chicago' },
      { q: 'The economic system built on private ownership of the means of production.', a: 'Capitalism' },
      { q: 'A raw material such as copper or wheat traded in standardised units.', a: 'Commodity' },
      { q: 'The amount of money needed to afford everyday basics in a given place.', a: 'Cost of Living' },
    ],
    D: [
      { q: 'A sustained general fall in prices.', a: 'Deflation' },
      { q: 'The currency of the United States, Canada and Australia.', a: 'Dollar' },
      { q: 'The American share average of 30 big industrial firms, launched in 1896 with just 12.', a: 'Dow Jones' },
      { q: 'Spreading investments so that one loss cannot sink a portfolio.', a: 'Diversification' },
      { q: 'The quantity buyers are willing to purchase at a given price.', a: 'Demand' },
      { q: 'The term for a severe and prolonged economic slump, as in the 1930s.', a: 'Depression' },
      { q: 'A share of profits paid out to a company\'s owners.', a: 'Dividend' },
      { q: 'A deliberate official cut in a fixed exchange rate.', a: 'Devaluation' },
      { q: 'The German currency withdrawn in favour of the euro in 2002.', a: 'Deutsche Mark' },
      { q: 'Cutting the precious metal content of coins while keeping their face value.', a: 'Debasement' },
      { q: 'Removing government rules from an industry, as with US airlines in 1978.', a: 'Deregulation' },
      { q: 'The plastic that takes payment straight out of a current account.', a: 'Debit Card' },
    ],
    E: [
      { q: 'The single currency adopted by eleven countries in 1999.', a: 'Euro' },
      { q: 'The measure of how much quantity demanded responds to a price change.', a: 'Elasticity' },
      { q: 'The price at which supply and demand are balanced.', a: 'Equilibrium' },
      { q: 'The owners\' residual stake in a company once its debts are counted.', a: 'Equity' },
      { q: 'An account where funds are held by a third party until a deal completes.', a: 'Escrow' },
      { q: 'A cost imposed on bystanders, such as pollution from a factory.', a: 'Externality' },
      { q: 'The price of one nation\'s money in terms of another\'s.', a: 'Exchange Rate' },
      { q: 'A total official ban on trade with a particular country.', a: 'Embargo' },
      { q: 'The Houston energy firm whose 2001 collapse also destroyed Arthur Andersen.', a: 'Enron' },
      { q: 'Falling unit costs as a factory produces more.', a: 'Economies of Scale' },
      { q: 'A good sold to a buyer abroad.', a: 'Export' },
      { q: 'The Frankfurt institution that sets interest rates for the eurozone.', a: 'European Central Bank' },
    ],
    F: [
      { q: 'The US central banking system created in 1913.', a: 'Federal Reserve' },
      { q: 'Currency that has value only by government decree and is not backed by metal.', a: 'Fiat Money' },
      { q: 'The use of taxation and public spending to steer the economy.', a: 'Fiscal Policy' },
      { q: 'The index of the largest hundred companies listed in London.', a: 'FTSE 100' },
      { q: 'Standardised contracts to buy a commodity at a fixed price on a later date.', a: 'Futures' },
      { q: 'The carmaker that introduced a five dollar working day in 1914.', a: 'Ford' },
      { q: 'The currency Switzerland still uses.', a: 'Franc' },
      { q: 'Commerce between nations with no tariffs or quotas.', a: 'Free Trade' },
      { q: 'The Austrian-born author of The Road to Serfdom.', a: 'Friedrich Hayek' },
      { q: 'A lender taking possession of a house after mortgage payments stop.', a: 'Foreclosure' },
      { q: 'The American mortgage giant taken into government conservatorship in 2008.', a: 'Fannie Mae' },
    ],
    G: [
      { q: 'The total value of all goods and services a country makes in a year.', a: 'Gross Domestic Product' },
      { q: 'The system tying a currency\'s value to a fixed weight of precious metal.', a: 'Gold Standard' },
      { q: 'The global slump that began with the 1929 Wall Street crash.', a: 'Great Depression' },
      { q: 'The New York investment bank once nicknamed the vampire squid.', a: 'Goldman Sachs' },
      { q: 'The eurozone member that took three international bailouts after 2010.', a: 'Greece' },
      { q: 'The Dutch currency withdrawn in favour of the euro.', a: 'Guilder' },
      { q: 'The 1933 US act that separated commercial from investment banking.', a: 'Glass-Steagall' },
      { q: 'The maxim that bad money drives out good.', a: 'Gresham\'s Law' },
      { q: 'Nickname for the paper currency issued to fund the American Civil War.', a: 'Greenback' },
      { q: 'The percentage rise in a country\'s output over a year.', a: 'Growth' },
      { q: 'The Detroit carmaker that went through a government-backed bankruptcy in 2009.', a: 'General Motors' },
    ],
    H: [
      { q: 'Prices rising so fast that cash becomes almost worthless, as in Weimar Germany.', a: 'Hyperinflation' },
      { q: 'A lightly regulated investment pool open only to wealthy clients.', a: 'Hedge Fund' },
      { q: 'The economic value of a workforce\'s skills and education.', a: 'Human Capital' },
      { q: 'The Asian territory whose dollar is pegged to the American one.', a: 'Hong Kong' },
      { q: 'The informal, trust-based transfer network used across South Asia and the Middle East.', a: 'Hawala' },
      { q: 'The inflated American property prices whose 2007 collapse triggered a global crisis.', a: 'Housing Bubble' },
      { q: 'A firm whose only business is owning shares in other firms.', a: 'Holding Company' },
      { q: 'A widely trusted money that holds its value and is freely traded.', a: 'Hard Currency' },
      { q: 'The American president in office when the 1929 crash struck.', a: 'Hoover' },
    ],
    I: [
      { q: 'The rate at which the general level of prices rises.', a: 'Inflation' },
      { q: 'Adam Smith\'s metaphor for markets turning self-interest into public benefit.', a: 'Invisible Hand' },
      { q: 'The price of borrowing money, quoted as a percentage.', a: 'Interest Rate' },
      { q: 'The Washington lender of last resort for countries in balance of payments crisis.', a: 'International Monetary Fund' },
      { q: 'A passive vehicle that simply tracks a whole market instead of picking winners.', a: 'Index Fund' },
      { q: 'The event at which a private company first sells shares on a stock exchange.', a: 'Initial Public Offering' },
      { q: 'The state of being unable to pay debts as they fall due.', a: 'Insolvency' },
      { q: 'The document a seller sends asking a buyer for payment.', a: 'Invoice' },
      { q: 'A good bought in from abroad.', a: 'Import' },
      { q: 'The business of pooling premiums to cover individual losses.', a: 'Insurance' },
    ],
    J: [
      { q: 'The British economist who urged public spending to fight the 1930s slump.', a: 'John Maynard Keynes' },
      { q: 'The country whose 1990s stagnation is known as the lost decade.', a: 'Japan' },
      { q: 'The largest American bank measured by assets.', a: 'JPMorgan Chase' },
      { q: 'A high-yield debt security rated below investment grade.', a: 'Junk Bond' },
      { q: 'A separate business created and co-owned by two parent firms for one project.', a: 'Joint Venture' },
      { q: 'The Federal Reserve chair who took office in 2018.', a: 'Jerome Powell' },
      { q: 'The biblical practice of periodically cancelling debts, revived as a campaign name in 2000.', a: 'Jubilee' },
    ],
    K: [
      { q: 'The currency of Sweden.', a: 'Krona' },
      { q: 'The Gulf state whose dinar is the highest-valued currency unit in the world.', a: 'Kuwait' },
      { q: 'The author of Das Kapital.', a: 'Karl Marx' },
      { q: 'The Japanese network of interlocking company and bank shareholdings.', a: 'Keiretsu' },
      { q: 'The currency of Zambia and Malawi.', a: 'Kwacha' },
      { q: 'An illicit payment made in return for awarding a contract.', a: 'Kickback' },
    ],
    L: [
      { q: 'How easily an asset can be turned into ready cash without moving its price.', a: 'Liquidity' },
      { q: 'The graph suggesting that tax revenue falls if rates are pushed too high.', a: 'Laffer Curve' },
      { q: 'Using borrowed funds to magnify potential returns.', a: 'Leverage' },
      { q: 'The investment bank whose September 2008 failure was the biggest bankruptcy in US history.', a: 'Lehman Brothers' },
      { q: 'The London benchmark borrowing rate rigged by traders and phased out in 2023.', a: 'LIBOR' },
      { q: 'The doctrine that government should leave business alone.', a: 'Laissez-faire' },
      { q: 'Money advanced on a promise of repayment with interest.', a: 'Loan' },
      { q: 'The Italian currency replaced by the euro, and the money of Turkey today.', a: 'Lira' },
      { q: 'The principle that shareholders can lose no more than they put in.', a: 'Limited Liability' },
      { q: 'The city that hosts the biggest foreign exchange trading centre in the world.', a: 'London' },
    ],
    M: [
      { q: 'Central bank management of interest rates and the supply of money.', a: 'Monetary Policy' },
      { q: 'A market with only one seller.', a: 'Monopoly' },
      { q: 'The Chicago economist who said inflation is always a monetary phenomenon.', a: 'Milton Friedman' },
      { q: 'A long-term loan secured against a house.', a: 'Mortgage' },
      { q: 'Tiny loans to poor entrepreneurs, pioneered by Grameen Bank.', a: 'Microfinance' },
      { q: 'The government works where coins are struck.', a: 'Mint' },
      { q: 'The extra expense of producing one more unit.', a: 'Marginal Cost' },
      { q: 'The old doctrine that a nation should maximise exports and hoard bullion.', a: 'Mercantilism' },
      { q: 'Taking bigger risks because someone else will bear the losses.', a: 'Moral Hazard' },
      { q: 'The software company that paid its first dividend in 2003.', a: 'Microsoft' },
      { q: 'A market with only one buyer.', a: 'Monopsony' },
    ],
    N: [
      { q: 'The electronic American exchange dominated by technology stocks.', a: 'Nasdaq' },
      { q: 'The total a government owes, built up over many years.', a: 'National Debt' },
      { q: 'The currency of Nigeria.', a: 'Naira' },
      { q: 'The main share index of the Japanese market.', a: 'Nikkei' },
      { q: 'Franklin Roosevelt\'s programme of public works and reform after 1933.', a: 'New Deal' },
      { q: 'A government taking a private industry into state ownership.', a: 'Nationalisation' },
      { q: 'Total assets minus total liabilities.', a: 'Net Worth' },
      { q: 'The country that runs the biggest sovereign wealth fund in the world.', a: 'Norway' },
      { q: 'The chipmaker that passed a one trillion dollar valuation in 2023.', a: 'Nvidia' },
    ],
    O: [
      { q: 'The oil producers\' group founded in Baghdad in 1960.', a: 'OPEC' },
      { q: 'A market dominated by just a few large sellers.', a: 'Oligopoly' },
      { q: 'The value of the best alternative you gave up.', a: 'Opportunity Cost' },
      { q: 'Permission to take a bank balance below zero.', a: 'Overdraft' },
      { q: 'A contract giving the right but not the duty to buy at a set price.', a: 'Option' },
      { q: 'Contracting work out to another firm, often abroad.', a: 'Outsourcing' },
      { q: 'Fixed running costs such as rent and heating.', a: 'Overhead' },
      { q: 'Central bank buying and selling of government debt to steer interest rates.', a: 'Open Market Operations' },
    ],
    P: [
      { q: 'Shielding home industry with tariffs and quotas.', a: 'Protectionism' },
      { q: 'The whole collection of investments held by one owner.', a: 'Portfolio' },
      { q: 'Firms that buy whole companies with borrowed cash and later resell them.', a: 'Private Equity' },
      { q: 'The currency of Mexico, Argentina and the Philippines.', a: 'Peso' },
      { q: 'Output per hour worked.', a: 'Productivity' },
      { q: 'A fraud that pays old investors with money from new ones.', a: 'Ponzi Scheme' },
      { q: 'The currency of the United Kingdom.', a: 'Pound Sterling' },
      { q: 'What a unit of money will actually buy.', a: 'Purchasing Power' },
      { q: 'A legal maximum charge, as with rent control.', a: 'Price Ceiling' },
      { q: 'What is left of revenue after all costs are paid.', a: 'Profit' },
      { q: 'Term for the American currency earned by oil exporters.', a: 'Petrodollar' },
    ],
    R: [
      { q: 'Commonly defined as two consecutive quarters of falling output.', a: 'Recession' },
      { q: 'The currency of India, Pakistan and Sri Lanka.', a: 'Rupee' },
      { q: 'The economist who set out the theory of comparative advantage.', a: 'Ricardo' },
      { q: 'The currency of Saudi Arabia and Qatar.', a: 'Riyal' },
      { q: 'The share of deposits a bank is not allowed to lend out.', a: 'Reserve Requirement' },
      { q: 'The currency of Russia.', a: 'Ruble' },
      { q: 'Total sales income before any costs are subtracted.', a: 'Revenue' },
      { q: 'The currency of South Africa.', a: 'Rand' },
      { q: 'A levy that takes a bigger share of income from the poor than from the rich.', a: 'Regressive Tax' },
      { q: 'The gain from a project measured against what it cost.', a: 'Return on Investment' },
    ],
    S: [
      { q: 'High inflation combined with high joblessness, as in the 1970s.', a: 'Stagflation' },
      { q: 'The quantity producers offer at a given price.', a: 'Supply' },
      { q: 'A government payment that lowers a producer\'s costs.', a: 'Subsidy' },
      { q: 'The marketplace where company shares are bought and sold.', a: 'Stock Exchange' },
      { q: 'A trade that profits when a share price falls, made by borrowing the stock first.', a: 'Short Selling' },
      { q: 'The ability to meet long-term financial obligations.', a: 'Solvency' },
      { q: 'Money borrowed by a national government.', a: 'Sovereign Debt' },
      { q: 'The currency of Israel.', a: 'Shekel' },
      { q: 'The 1930 US tariff act blamed for deepening the global slump.', a: 'Smoot-Hawley' },
      { q: 'Buying an asset purely in the hope of a quick price rise.', a: 'Speculation' },
      { q: 'The California lender that failed in March 2023 after a run on deposits.', a: 'Silicon Valley Bank' },
      { q: 'Spending already made that should not affect future decisions.', a: 'Sunk Cost' },
    ],
    T: [
      { q: 'A tax charged on imported goods.', a: 'Tariff' },
      { q: 'Long-dated debt issued by the American government.', a: 'Treasury Bond' },
      { q: 'What a country has when it buys more from abroad than it sells.', a: 'Trade Deficit' },
      { q: 'The compulsory levy that funds government.', a: 'Taxation' },
      { q: 'The 1630s Dutch flower frenzy, often called the first speculative bubble.', a: 'Tulip Mania' },
      { q: 'The carmaker that joined the S and P 500 index in December 2020.', a: 'Tesla' },
      { q: 'A legal arrangement where one party holds assets for the benefit of another.', a: 'Trust' },
      { q: 'The British term for a company\'s total sales in a period.', a: 'Turnover' },
      { q: 'The idea that gains at the top eventually benefit everyone below.', a: 'Trickle-down' },
    ],
    U: [
      { q: 'The share of the labour force seeking work but without it.', a: 'Unemployment' },
      { q: 'In economics, the satisfaction a consumer gets from a good.', a: 'Utility' },
      { q: 'Lending at extortionate rates, condemned by medieval church law.', a: 'Usury' },
      { q: 'The bank that guarantees to buy up an unsold share issue.', a: 'Underwriter' },
      { q: 'The ride-hailing company that listed in New York in 2019.', a: 'Uber' },
      { q: 'The workers\' organisation that bargains collectively over pay.', a: 'Union' },
      { q: 'A private start-up valued at more than a billion dollars.', a: 'Unicorn' },
    ],
    V: [
      { q: 'The consumption levy charged at each stage of production and reclaimed by businesses.', a: 'Value Added Tax' },
      { q: 'Money put into young, unproven companies in return for a stake.', a: 'Venture Capital' },
      { q: 'The degree to which a price swings up and down.', a: 'Volatility' },
      { q: 'How many times a year the average unit of currency changes hands.', a: 'Velocity of Money' },
      { q: 'The payments network whose 2008 flotation was then the biggest in American history.', a: 'Visa' },
      { q: 'The dong is the currency of this country.', a: 'Vietnam' },
      { q: 'The secure room where a bank keeps its cash.', a: 'Vault' },
    ],
    W: [
      { q: 'The lower Manhattan address that stands for American finance.', a: 'Wall Street' },
      { q: 'The Washington institution that lends for development projects in poorer countries.', a: 'World Bank' },
      { q: 'Payment for labour, usually reckoned by the hour.', a: 'Wage' },
      { q: 'The currency of both Koreas.', a: 'Won' },
      { q: 'The Arkansas-based firm that is the biggest company by revenue in the world.', a: 'Walmart' },
      { q: 'The Geneva body created in 1995 to police the rules of global commerce.', a: 'World Trade Organization' },
      { q: 'The Omaha investor nicknamed the Oracle.', a: 'Warren Buffett' },
      { q: 'A one-off levy on unexpectedly large profits.', a: 'Windfall Tax' },
    ],
    Y: [
      { q: 'The currency of Japan.', a: 'Yen' },
      { q: 'The annual income from an investment as a percentage of its price.', a: 'Yield' },
      { q: 'The unit of Chinese currency.', a: 'Yuan' },
      { q: 'The line plotting government borrowing costs across different maturities.', a: 'Yield Curve' },
      { q: 'The web portal that turned down a 44 billion dollar Microsoft bid in 2008.', a: 'Yahoo' },
    ],
  },
};
