import type { RawQuestion } from '../core/packs';

// ~150 medium Movies & TV questions. Answers are natural film/show/person names.
export const moviesMediumExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: "Jean-Pierre Jeunet's whimsical 2001 French film about a shy Parisian waitress who secretly improves the lives of others.", a: 'Amélie', category: 'screen', difficulty: 2 },
    { q: 'Ridley Scott space-horror tale aboard the Nostromo, with a creature designed by H.R. Giger.', a: 'Alien', category: 'screen', difficulty: 2 },
    { q: 'Christian Bale plays Patrick Bateman, a murderous Wall Street yuppie, in this 2000 satire.', a: 'American Psycho', category: 'screen', difficulty: 2 },
    { q: 'Sam Mendes 1999 drama about a suburban father\'s midlife crisis, narrated by a dead man.', a: 'American Beauty', category: 'screen', difficulty: 2 },
    { q: 'Disney 1992 animated film about a street urchin, a genie, and a magic carpet in Agrabah.', a: 'Aladdin', category: 'screen', difficulty: 2 },
    { q: 'Ben Affleck 2012 thriller about a CIA rescue disguised as a fake film shoot during the Iran hostage crisis.', a: 'Argo', category: 'screen', difficulty: 2 },
    { q: 'Denis Villeneuve 2016 sci-fi film about a linguist who decodes the language of visiting aliens.', a: 'Arrival', category: 'screen', difficulty: 2 },
    { q: 'Francis Ford Coppola 1979 Vietnam War epic loosely based on "Heart of Darkness."', a: 'Apocalypse Now', category: 'screen', difficulty: 2 },
    { q: 'Director nicknamed the "Master of Suspense," who made "Psycho," "Rear Window," and "The Birds."', a: 'Alfred Hitchcock', category: 'screen', difficulty: 2 },
    { q: 'James Cameron 1989 underwater thriller about a deep-sea oil-rig crew encountering strange beings.', a: 'The Abyss', category: 'screen', difficulty: 3 },
  ],
  B: [
    { q: 'Robert Zemeckis 1985 time-travel film featuring a DeLorean and Doc Brown.', a: 'Back to the Future', category: 'screen', difficulty: 2 },
    { q: 'AMC prequel following the con-man lawyer Jimmy McGill before he becomes Walter White\'s attorney.', a: 'Better Call Saul', category: 'screen', difficulty: 2 },
    { q: 'Tim Burton 1988 dark comedy about a mischievous ghost summoned to scare the living.', a: 'Beetlejuice', category: 'screen', difficulty: 2 },
    { q: 'Disney 1991 animated film about a bookish girl who falls for a cursed prince, the first animated Best Picture nominee.', a: 'Beauty and the Beast', category: 'screen', difficulty: 2 },
    { q: 'Marvel 2018 film set in the fictional African nation of Wakanda, starring Chadwick Boseman.', a: 'Black Panther', category: 'screen', difficulty: 2 },
    { q: 'Ridley Scott 1982 cyberpunk film about a cop hunting replicants in a future Los Angeles.', a: 'Blade Runner', category: 'screen', difficulty: 2 },
    { q: 'Mel Gibson 1995 epic about Scottish warrior William Wallace fighting English rule.', a: 'Braveheart', category: 'screen', difficulty: 2 },
    { q: 'Actress who played Captain Marvel and won an Oscar for "Room."', a: 'Brie Larson', category: 'screen', difficulty: 3 },
    { q: 'British actor who played Sherlock for the BBC and Doctor Strange in the Marvel films.', a: 'Benedict Cumberbatch', category: 'screen', difficulty: 3 },
    { q: '1985 John Hughes teen film about five very different students stuck in weekend detention.', a: 'The Breakfast Club', category: 'screen', difficulty: 2 },
    { q: 'Wes Anderson 2014 comedy about a legendary concierge and a lobby boy at a fictional alpine resort.', a: 'The Grand Budapest Hotel', category: 'screen', difficulty: 3 },
  ],
  C: [
    { q: 'Orson Welles 1941 film about a newspaper magnate whose dying word is "Rosebud."', a: 'Citizen Kane', category: 'screen', difficulty: 2 },
    { q: 'Ang Lee 2000 martial-arts film set in Qing-dynasty China, famed for its wuxia wirework.', a: 'Crouching Tiger, Hidden Dragon', category: 'screen', difficulty: 3 },
    { q: 'Roman Polanski 1974 noir with Jack Nicholson as a detective uncovering corruption over LA water.', a: 'Chinatown', category: 'screen', difficulty: 3 },
    { q: 'Pixar 2017 animated film set in Mexico during the Day of the Dead, about a boy named Miguel.', a: 'Coco', category: 'screen', difficulty: 2 },
    { q: 'British director of "Memento," "Interstellar," "Inception," and "Oppenheimer."', a: 'Christopher Nolan', category: 'screen', difficulty: 2 },
    { q: 'Silent-era star and director with a bowler hat and cane, famed for "The Tramp" character.', a: 'Charlie Chaplin', category: 'screen', difficulty: 2 },
    { q: 'Matt Groening\'s long-running yellow-skinned animated family sitcom set in Springfield.', a: 'The Simpsons', category: 'screen', difficulty: 2 },
    { q: 'Robert Zemeckis 2000 survival film in which Tom Hanks is marooned and befriends a volleyball.', a: 'Cast Away', category: 'screen', difficulty: 2 },
    { q: 'Hit US sitcom about a group of nerdy physicists and their neighbor Penny, featuring Sheldon Cooper.', a: 'The Big Bang Theory', category: 'screen', difficulty: 2 },
  ],
  D: [
    { q: 'Leonardo DiCaprio plays a freed slave-turned-bounty-hunter in this 2012 Tarantino western.', a: 'Django Unchained', category: 'screen', difficulty: 2 },
    { q: 'Showtime crime drama about a Miami blood-spatter analyst who is secretly a serial killer.', a: 'Dexter', category: 'screen', difficulty: 2 },
    { q: 'Christopher Nolan 2017 war film depicting the WWII evacuation of British troops from a French beach.', a: 'Dunkirk', category: 'screen', difficulty: 2 },
    { q: 'Sci-fi blockbuster set on the desert planet Arrakis, directed by Denis Villeneuve from a Frank Herbert novel.', a: 'Dune', category: 'screen', difficulty: 2 },
    { q: 'Actor who played Jack in "Titanic" and won his first acting Oscar for "The Revenant."', a: 'Leonardo DiCaprio', category: 'screen', difficulty: 2 },
    { q: 'Canadian director behind "Blade Runner 2049," "Arrival," and the recent "Dune" films.', a: 'Denis Villeneuve', category: 'screen', difficulty: 3 },
    { q: 'Christopher Nolan 2008 superhero sequel featuring Heath Ledger\'s acclaimed turn as the Joker.', a: 'The Dark Knight', category: 'screen', difficulty: 2 },
  ],
  E: [
    { q: 'Steven Spielberg 1982 film about a boy who befriends a stranded alien wanting to phone home.', a: 'E.T. the Extra-Terrestrial', category: 'screen', difficulty: 2 },
    { q: 'A24 2022 multiverse film with Michelle Yeoh as a laundromat owner; swept the 2023 Oscars.', a: 'Everything Everywhere All at Once', category: 'screen', difficulty: 2 },
    { q: 'Michel Gondry 2004 film in which a couple medically erase all memories of their relationship.', a: 'Eternal Sunshine of the Spotless Mind', category: 'screen', difficulty: 3 },
  ],
  F: [
    { q: 'David Fincher 1999 film based on a Chuck Palahniuk novel; its first rule is not to talk about it.', a: 'Fight Club', category: 'screen', difficulty: 2 },
    { q: 'Action franchise about street-racing driver Dominic Toretto and his "family" of drivers.', a: 'Fast & Furious', category: 'screen', difficulty: 2 },
    { q: 'Robert Zemeckis 1994 film about a slow-witted Alabama man who keeps stumbling into history.', a: 'Forrest Gump', category: 'screen', difficulty: 2 },
    { q: 'Pixar 2003 underwater adventure about a clownfish searching the ocean for his lost son.', a: 'Finding Nemo', category: 'screen', difficulty: 2 },
    { q: 'Coen brothers 1996 dark comedy set in snowy Minnesota, with a pregnant police chief named Marge.', a: 'Fargo', category: 'screen', difficulty: 2 },
  ],
  G: [
    { q: 'Alfonso Cuarón 2013 film about astronauts stranded in orbit after debris destroys their shuttle.', a: 'Gravity', category: 'screen', difficulty: 2 },
    { q: 'Martin Scorsese 1990 mob film narrated by Henry Hill, with Joe Pesci and Robert De Niro.', a: 'Goodfellas', category: 'screen', difficulty: 2 },
    { q: '1939 epic set on a Georgia plantation during the American Civil War, starring Vivien Leigh as Scarlett O\'Hara.', a: 'Gone with the Wind', category: 'screen', difficulty: 2 },
    { q: '1984 comedy about paranormal exterminators in New York City who battle a giant marshmallow man.', a: 'Ghostbusters', category: 'screen', difficulty: 2 },
    { q: 'HBO fantasy series adapted from George R.R. Martin, where noble houses fight for the Iron Throne.', a: 'Game of Thrones', category: 'screen', difficulty: 2 },
    { q: 'Bill Murray comedy where a weatherman relives the same February day over and over in Punxsutawney.', a: 'Groundhog Day', category: 'screen', difficulty: 2 },
    { q: 'Marvel team led by Star-Lord, including a talking raccoon and a tree named Groot.', a: 'Guardians of the Galaxy', category: 'screen', difficulty: 2 },
    { q: 'Long-running medical drama set at Seattle Grace Hospital, centered on intern Meredith.', a: "Grey's Anatomy", category: 'screen', difficulty: 2 },
  ],
  H: [
    { q: 'Studio Ghibli 2004 fantasy about a young woman cursed into old age who shelters in a wizard\'s walking home.', a: "Howl's Moving Castle", category: 'screen', difficulty: 3 },
    { q: 'Animated franchise about a Viking boy who befriends an injured winged creature named Toothless.', a: 'How to Train Your Dragon', category: 'screen', difficulty: 2 },
    { q: 'Japanese animation master who co-founded Studio Ghibli and directed "Spirited Away."', a: 'Hayao Miyazaki', category: 'screen', difficulty: 2 },
  ],
  I: [
    { q: 'Christopher Nolan 2010 thriller about thieves who steal secrets by entering shared dreams.', a: 'Inception', category: 'screen', difficulty: 2 },
    { q: 'Pixar 2004 film about a family of superheroes living undercover in suburbia.', a: 'The Incredibles', category: 'screen', difficulty: 2 },
    { q: 'Will Smith 1996 sci-fi blockbuster about an alien invasion repelled on the Fourth of July.', a: 'Independence Day', category: 'screen', difficulty: 2 },
    { q: 'Quentin Tarantino 2009 war film in which a Jewish-American squad hunts Nazis in occupied France.', a: 'Inglourious Basterds', category: 'screen', difficulty: 3 },
    { q: 'Pixar 2015 film set within a young girl\'s mind, where Joy and Sadness are personified emotions.', a: 'Inside Out', category: 'screen', difficulty: 2 },
  ],
  J: [
    { q: 'Steven Spielberg 1993 film in which cloned dinosaurs run amok on an island wildlife attraction.', a: 'Jurassic Park', category: 'screen', difficulty: 2 },
    { q: 'Spielberg 1975 thriller about a great white shark terrorizing the town of Amity Island.', a: 'Jaws', category: 'screen', difficulty: 2 },
    { q: 'Todd Phillips 2019 origin film starring Joaquin Phoenix as a failed comedian who becomes Batman\'s nemesis.', a: 'Joker', category: 'screen', difficulty: 2 },
    { q: 'Keanu Reeves plays a retired hitman who returns to violence after gangsters kill his dog.', a: 'John Wick', category: 'screen', difficulty: 2 },
  ],
  K: [
    { q: 'Uma Thurman seeks revenge against an assassination squad in this two-volume Tarantino saga.', a: 'Kill Bill', category: 'screen', difficulty: 2 },
    { q: 'Robert Benton 1979 drama about a custody battle, with Dustin Hoffman and Meryl Streep.', a: 'Kramer vs. Kramer', category: 'screen', difficulty: 3 },
    { q: 'Wes Anderson 2018 stop-motion film about exiled canines on a Japanese island of garbage.', a: 'Isle of Dogs', category: 'screen', difficulty: 3 },
  ],
  L: [
    { q: 'Damien Chazelle 2016 musical with Ryan Gosling and Emma Stone falling in love in Los Angeles.', a: 'La La Land', category: 'screen', difficulty: 2 },
    { q: 'Sofia Coppola 2003 film about a fading actor and a young woman who bond in a Tokyo hotel.', a: 'Lost in Translation', category: 'screen', difficulty: 3 },
    { q: 'Peter Jackson trilogy based on Tolkien, beginning with "The Fellowship of the Ring."', a: 'The Lord of the Rings', category: 'screen', difficulty: 2 },
    { q: 'Greta Gerwig 2017 coming-of-age film about a Sacramento teen who renames herself.', a: 'Lady Bird', category: 'screen', difficulty: 3 },
    { q: 'David Lean 1962 epic about a British officer uniting Arab tribes during World War I.', a: 'Lawrence of Arabia', category: 'screen', difficulty: 3 },
  ],
  M: [
    { q: 'The Wachowskis 1999 sci-fi film about a hacker named Neo who learns reality is a simulation.', a: 'The Matrix', category: 'screen', difficulty: 2 },
    { q: 'Hayao Miyazaki 1988 Ghibli film about two sisters who befriend forest spirits, including a giant furry one.', a: 'My Neighbor Totoro', category: 'screen', difficulty: 3 },
    { q: 'AMC period drama about 1960s advertising executives, centered on Don Draper.', a: 'Mad Men', category: 'screen', difficulty: 2 },
    { q: 'Disney 2016 animated film about a Polynesian girl who sails the Pacific with the demigod Maui.', a: 'Moana', category: 'screen', difficulty: 2 },
    { q: 'George Miller 2015 action film with Tom Hardy and Charlize Theron\'s warrior Furiosa fleeing across a desert wasteland.', a: 'Mad Max: Fury Road', category: 'screen', difficulty: 2 },
    { q: 'Italian-American director of "Goodfellas," "Taxi Driver," and "The Departed."', a: 'Martin Scorsese', category: 'screen', difficulty: 2 },
    { q: 'Pixar 2001 film about two factory workers who scare children to harvest screams for energy.', a: 'Monsters, Inc.', category: 'screen', difficulty: 2 },
    { q: 'Disney 1998 animated film about a Chinese girl who disguises herself as a man to join the army.', a: 'Mulan', category: 'screen', difficulty: 2 },
  ],
  N: [
    { q: 'David Lynch surreal 2001 mystery set in Hollywood, starring Naomi Watts.', a: 'Mulholland Drive', category: 'screen', difficulty: 3 },
    { q: 'Coen brothers 2007 thriller based on a Cormac McCarthy novel, with the killer Anton Chigurh.', a: 'No Country for Old Men', category: 'screen', difficulty: 2 },
    { q: 'Tim Burton-produced 1993 stop-motion film where Jack Skellington, king of Halloween Town, discovers the December holiday.', a: 'The Nightmare Before Christmas', category: 'screen', difficulty: 2 },
  ],
  O: [
    { q: 'Netflix dark comedy set in a women\'s prison, centered on Piper Chapman.', a: 'Orange Is the New Black', category: 'screen', difficulty: 2 },
    { q: '1975 film set in a mental institution where Randle McMurphy clashes with Nurse Ratched.', a: "One Flew Over the Cuckoo's Nest", category: 'screen', difficulty: 3 },
    { q: 'Christopher Nolan 2023 biopic about the physicist who led the Manhattan Project.', a: 'Oppenheimer', category: 'screen', difficulty: 2 },
  ],
  P: [
    { q: 'Guillermo del Toro 2006 dark fairy tale set after the Spanish Civil War, about a girl and a faun.', a: "Pan's Labyrinth", category: 'screen', difficulty: 3 },
    { q: 'Quentin Tarantino 1994 crime film with intersecting stories, Jules and Vincent, and a glowing briefcase.', a: 'Pulp Fiction', category: 'screen', difficulty: 2 },
    { q: 'Bong Joon-ho thriller about a poor family infiltrating a wealthy household, first non-English Best Picture winner.', a: 'Parasite', category: 'screen', difficulty: 2 },
    { q: 'NBC mockumentary sitcom about the public-works department of Pawnee, Indiana, led by Leslie Knope.', a: 'Parks and Recreation', category: 'screen', difficulty: 2 },
    { q: 'Acclaimed director of "There Will Be Blood" and "Boogie Nights," known by his initials P.T.A.', a: 'Paul Thomas Anderson', category: 'screen', difficulty: 3 },
    { q: 'New Zealand director of the Lord of the Rings trilogy and 2005\'s "King Kong."', a: 'Peter Jackson', category: 'screen', difficulty: 2 },
    { q: 'Wes Anderson 2001 comedy-drama about a dysfunctional family of former child prodigies.', a: 'The Royal Tenenbaums', category: 'screen', difficulty: 3 },
    { q: 'Disney 2009 hand-drawn musical set in jazz-age New Orleans, about a waitress named Tiana and an amphibian prince.', a: 'The Princess and the Frog', category: 'screen', difficulty: 3 },
  ],
  R: [
    { q: 'Sylvester Stallone plays an underdog Philadelphia boxer in this 1976 Best Picture winner.', a: 'Rocky', category: 'screen', difficulty: 2 },
    { q: 'Harrison Ford plays a whip-cracking archaeologist hunting the Ark of the Covenant in this 1981 adventure.', a: 'Raiders of the Lost Ark', category: 'screen', difficulty: 2 },
    { q: 'Disney-Pixar 2007 film about a Parisian rat who dreams of becoming a great chef.', a: 'Ratatouille', category: 'screen', difficulty: 2 },
    { q: 'Actress and producer who starred in "Pretty Woman" and "Erin Brockovich," famed for her smile.', a: 'Julia Roberts', category: 'screen', difficulty: 2 },
    { q: 'Marvel actor who plays the wisecracking Deadpool and starred in "The Proposal."', a: 'Ryan Reynolds', category: 'screen', difficulty: 2 },
  ],
  S: [
    { q: 'Steven Spielberg 1993 black-and-white film about a German businessman who saves Jews during the Holocaust.', a: "Schindler's List", category: 'screen', difficulty: 2 },
    { q: 'George Lucas 1977 space saga introducing Luke Skywalker, Darth Vader, and the Force.', a: 'Star Wars', category: 'screen', difficulty: 2 },
    { q: 'Sci-fi franchise begun by Gene Roddenberry, following the USS Enterprise and Captain Kirk.', a: 'Star Trek', category: 'screen', difficulty: 2 },
    { q: 'Animated DreamWorks ogre voiced by Mike Myers who lives in a swamp.', a: 'Shrek', category: 'screen', difficulty: 2 },
    { q: 'Netflix sci-fi series about a missing boy and a girl with powers in 1980s Hawkins, Indiana.', a: 'Stranger Things', category: 'screen', difficulty: 2 },
    { q: 'Frank Darabont 1994 prison film about Andy Dufresne, based on a Stephen King novella.', a: 'The Shawshank Redemption', category: 'screen', difficulty: 2 },
    { q: 'Wes Craven 1990s slasher franchise with a killer in a white ghost-face mask phoning victims.', a: 'Scream', category: 'screen', difficulty: 2 },
    { q: 'Director who made "Jaws," "E.T.," "Jurassic Park," and "Saving Private Ryan."', a: 'Steven Spielberg', category: 'screen', difficulty: 2 },
    { q: 'Actress who played Black Widow in the Marvel films and starred in "Lost in Translation."', a: 'Scarlett Johansson', category: 'screen', difficulty: 3 },
    { q: 'Hayao Miyazaki 2001 Oscar-winning film about a girl whose parents are turned into pigs at a spirit bathhouse.', a: 'Spirited Away', category: 'screen', difficulty: 2 },
    { q: 'NBC sketch-comedy institution broadcast from New York every weekend since 1975, known by three initials.', a: 'Saturday Night Live', category: 'screen', difficulty: 2 },
    { q: 'Pete Docter Pixar 2020 film in which a jazz pianist\'s essence ends up in the Great Before.', a: 'Soul', category: 'screen', difficulty: 2 },
    { q: 'M. Night Shyamalan 1999 film about a boy who sees dead people and the psychologist treating him.', a: 'The Sixth Sense', category: 'screen', difficulty: 2 },
    { q: 'HBO dark comedy about wealthy media-mogul siblings fighting to inherit their aging father\'s empire.', a: 'Succession', category: 'screen', difficulty: 2 },
  ],
  T: [
    { q: 'James Cameron 1984 sci-fi film about a cyborg assassin sent back in time to kill Sarah Connor.', a: 'The Terminator', category: 'screen', difficulty: 2 },
    { q: 'Ridley Scott 1991 road film about two women on the run after a crime, ending at the Grand Canyon.', a: 'Thelma & Louise', category: 'screen', difficulty: 3 },
    { q: 'Peter Weir 1998 film about a man whose entire life is secretly a televised reality show.', a: 'The Truman Show', category: 'screen', difficulty: 2 },
    { q: 'Pixar 1995 film, the first fully computer-animated feature, about a cowboy doll named Woody.', a: 'Toy Story', category: 'screen', difficulty: 2 },
    { q: 'Martin Scorsese 1976 film with Robert De Niro as the unhinged New York cabbie Travis Bickle.', a: 'Taxi Driver', category: 'screen', difficulty: 3 },
    { q: 'Disney 2010 animated film about a long-haired princess locked in a tower.', a: 'Tangled', category: 'screen', difficulty: 2 },
    { q: 'Actor known for "Mission: Impossible," "Top Gun," and doing his own stunts.', a: 'Tom Cruise', category: 'screen', difficulty: 2 },
    { q: 'Actor who played Forrest Gump, the cowboy doll Woody, and a marooned man with a volleyball.', a: 'Tom Hanks', category: 'screen', difficulty: 2 },
  ],
  U: [
    { q: 'Bryan Singer 1995 crime film with a twist ending and the elusive Keyser Söze.', a: 'The Usual Suspects', category: 'screen', difficulty: 3 },
    { q: 'Disney-Pixar 2009 film about an old widower who ties balloons to his house and flies to South America.', a: 'Up', category: 'screen', difficulty: 2 },
  ],
  V: [
    { q: 'James McTeigue 2005 dystopian film about a masked anarchist in a totalitarian Britain.', a: 'V for Vendetta', category: 'screen', difficulty: 3 },
    { q: 'Alfred Hitchcock 1958 thriller with James Stewart as a detective with a fear of heights.', a: 'Vertigo', category: 'screen', difficulty: 3 },
    { q: 'HBO political comedy starring Julia Louis-Dreyfus as a self-serving Vice President named Selina Meyer.', a: 'Veep', category: 'screen', difficulty: 2 },
  ],
  W: [
    { q: 'Martin Scorsese 2013 film with Leonardo DiCaprio as fraudulent stockbroker Jordan Belfort.', a: 'The Wolf of Wall Street', category: 'screen', difficulty: 2 },
    { q: '1939 musical fantasy in which Dorothy and her dog Toto follow a yellow brick road to the Emerald City.', a: 'The Wizard of Oz', category: 'screen', difficulty: 2 },
    { q: 'Mel Stuart 1971 film in which a poor boy named Charlie wins a golden ticket to tour an eccentric candy-maker\'s plant.', a: 'Willy Wonka & the Chocolate Factory', category: 'screen', difficulty: 2 },
    { q: 'Damien Chazelle 2014 drama about a young jazz drummer pushed to the brink by a tyrannical teacher.', a: 'Whiplash', category: 'screen', difficulty: 2 },
    { q: 'Pixar 2008 film about a waste-collecting robot left alone on a trash-covered Earth.', a: 'WALL-E', category: 'screen', difficulty: 2 },
    { q: '2017 superhero film, the first major studio one led by a female hero, set partly in World War I.', a: 'Wonder Woman', category: 'screen', difficulty: 2 },
    { q: 'HBO crime drama set in Baltimore exploring drugs, police, and city institutions, created by David Simon.', a: 'The Wire', category: 'screen', difficulty: 3 },
    { q: 'HBO sci-fi series set in a futuristic theme park where lifelike android hosts serve wealthy guests.', a: 'Westworld', category: 'screen', difficulty: 3 },
  ],
  Z: [
    { q: 'Ruben Fleischer 2009 horror-comedy road trip across a U.S. overrun by the undead.', a: 'Zombieland', category: 'screen', difficulty: 2 },
    { q: 'Disney 2016 animated film set in a mammal metropolis where a rabbit cop teams with a fox con artist.', a: 'Zootopia', category: 'screen', difficulty: 2 },
  ],
  Q: [
    { q: 'Director of "Pulp Fiction," "Kill Bill," and "Once Upon a Time in Hollywood," known for stylized violence.', a: 'Quentin Tarantino', category: 'screen', difficulty: 2 },
  ],
};
