import type { RawQuestion } from '../core/packs';

// EXPANSION pack — additional 1980s pop songs, albums, artists not in the base pack.
// Every answer starts with its letter and never appears in its question.
export const music80sPopExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: "Sheffield synth-pop group whose 1982 debut produced 'The Look of Love' and 'Poison Arrow'.", a: 'ABC', category: 'music', difficulty: 3 },
    { q: "Soft-rock duo of Russell Hitchcock and Graham Russell behind 'All Out of Love' in 1980.", a: 'Air Supply', category: 'music', difficulty: 2 },
    { q: "New wave act behind the 1984 hit 'Obsession'.", a: 'Animotion', category: 'music', difficulty: 4 },
    { q: "Sydney rock outfit whose 1981 hit was 'Reckless (Don't Be So…)'.", a: 'Australian Crawl', category: 'music', difficulty: 4 },
    { q: "1980 Pink Floyd chart-topper about classroom rebellion with a children's chorus.", a: 'Another Brick in the Wall', category: 'music', difficulty: 2 },
    { q: "1986 Robert Palmer single whose video featured identically dressed female 'musicians'.", a: 'Addicted to Love', category: 'music', difficulty: 3 },
    { q: "1988 Phil Collins #1 about a homeless man — from 'But Seriously'.", a: 'Another Day in Paradise', category: 'music', difficulty: 3 },
    { q: "1980 Queen funk-rock single from 'The Game' with a famous bass riff by John Deacon.", a: 'Another One Bites the Dust', category: 'music', difficulty: 2 },
    { q: "Roxy Music's 1982 final studio album with the title track 'More Than This'.", a: 'Avalon', category: 'music', difficulty: 4 },
    { q: "1984 Footloose-soundtrack duet between Mike Reno and Ann Wilson.", a: 'Almost Paradise', category: 'music', difficulty: 4 },
    { q: "1988 Phil Collins ballad from the Norman Jewison-produced 'Buster' film.", a: 'A Groovy Kind of Love', category: 'music', difficulty: 4 },
  ],
  B: [
    { q: "British trio of brothers Matt and Luke Goss who hit big in 1988 with 'When Will I Be Famous?'.", a: 'Bros', category: 'music', difficulty: 3 },
    { q: "Los Angeles band led by Terri Nunn whose 1986 #1 came from a Tom Cruise jet film.", a: 'Berlin', category: 'music', difficulty: 3 },
    { q: "Roxy Music frontman whose 1985 solo single 'Slave to Love' charted across Europe.", a: 'Bryan Ferry', category: 'music', difficulty: 3 },
    { q: "1981 Kim Carnes #1 named for a Hollywood screen legend's gaze.", a: 'Bette Davis Eyes', category: 'music', difficulty: 3 },
    { q: "Don Henley's 1984 nostalgic single from 'Building the Perfect Beast'.", a: 'Boys of Summer', category: 'music', difficulty: 3 },
    { q: "Stevie Nicks's 1981 solo debut album featuring 'Edge of Seventeen'.", a: 'Bella Donna', category: 'music', difficulty: 3 },
  ],
  C: [
    { q: "New Zealand-Australian band led by Neil Finn whose 1986 hit was 'Don't Dream It's Over'.", a: 'Crowded House', category: 'music', difficulty: 3 },
    { q: "Canadian soft-rock singer whose 1980 debut LP yielded 'Sailing' and 'Ride Like the Wind'.", a: 'Christopher Cross', category: 'music', difficulty: 3 },
    { q: "Canadian new wave singer whose 1984 sunglasses-themed single hit #7 in America.", a: 'Corey Hart', category: 'music', difficulty: 3 },
    { q: "Carly Simon's 1986 hit from the Mike Nichols film 'Heartburn' with Meryl Streep.", a: 'Coming Around Again', category: 'music', difficulty: 4 },
    { q: "1980 Kool & the Gang chart-topper that became the global party anthem of weddings.", a: 'Celebration', category: 'music', difficulty: 3 },
  ],
  D: [
    { q: "Eagles drummer turned solo star whose 1989 LP was 'The End of the Innocence'.", a: 'Don Henley', category: 'music', difficulty: 3 },
    { q: "Soundtrack album that topped charts in 1987 from a film about a Catskills resort summer.", a: 'Dirty Dancing', category: 'music', difficulty: 2 },
    { q: "1987 Crowded House single about a relationship's quiet, inevitable end.", a: "Don't Dream It's Over", category: 'music', difficulty: 3 },
    { q: "British rock chameleon whose 1983 'Let's Dance' album was produced by Nile Rodgers.", a: 'David Bowie', category: 'music', difficulty: 2 },
    { q: "1984 Band Aid charity single about Yuletide awareness in Africa.", a: "Do They Know It's Christmas?", category: 'music', difficulty: 3 },
    { q: "1988 Bobby McFerrin a cappella worldwide #1 with a reassuring catchphrase.", a: "Don't Worry, Be Happy", category: 'music', difficulty: 3 },
    { q: "Sting's 1985 solo debut LP featuring 'If You Love Somebody Set Them Free'.", a: 'Dream of the Blue Turtles', category: 'music', difficulty: 4, alt: ['The Dream of the Blue Turtles'] },
  ],
  E: [
    { q: "Guyanese-born singer behind the 1983 reggae-rock hit 'Electric Avenue'.", a: 'Eddy Grant', category: 'music', difficulty: 3 },
    { q: "Singer whose 1988 self-titled debut with the New Bohemians featured 'What I Am'.", a: 'Edie Brickell', category: 'music', difficulty: 4 },
    { q: "1985 Tears for Fears #1 single asserting the planet is desired by all.", a: 'Everybody Wants to Rule the World', category: 'music', difficulty: 2 },
    { q: "1983 #1 by the Police about voyeuristic surveillance disguised as devotion.", a: 'Every Breath You Take', category: 'music', difficulty: 2 },
    { q: "1981 #1 by the Police about a Bahamian shipwreck and longing.", a: 'Every Little Thing She Does Is Magic', category: 'music', difficulty: 4 },
    { q: "1989 Don Henley album about American idealism lost.", a: 'End of the Innocence', category: 'music', difficulty: 4, alt: ['The End of the Innocence'] },
  ],
  F: [
    { q: "Austrian singer of the 1985 worldwide #1 about Wolfgang Amadeus in rock styling.", a: 'Falco', category: 'music', difficulty: 3 },
    { q: "British band whose 1987 album 'Tango in the Night' featured 'Little Lies'.", a: 'Fleetwood Mac', category: 'music', difficulty: 2 },
    { q: "1980 Lipps Inc. dance smash about an imaginary place where the music never stops.", a: 'Funkytown', category: 'music', difficulty: 3 },
    { q: "1988 Tracy Chapman single about driving away from a small-town life.", a: 'Fast Car', category: 'music', difficulty: 3 },
  ],
  G: [
    { q: "British electro-pop pioneer whose 1980 single was 'Cars'.", a: 'Gary Numan', category: 'music', difficulty: 3 },
    { q: "Canadian band whose 1986 debut single was 'Don't Forget Me (When I'm Gone)'.", a: 'Glass Tiger', category: 'music', difficulty: 4 },
    { q: "Eagles guitarist whose 1985 solo hit 'You Belong to the City' came from a Miami TV series.", a: 'Glenn Frey', category: 'music', difficulty: 3 },
    { q: "Bruce Springsteen's 1985 single about an aging former high-school baseball star.", a: 'Glory Days', category: 'music', difficulty: 4 },
  ],
  H: [
    { q: "British synth-pop singer whose 1983 single 'New Song' launched a string of UK Top 10s.", a: 'Howard Jones', category: 'music', difficulty: 3 },
    { q: "Sheffield trio behind the 1981 single '(We Don't Need This) Fascist Groove Thang'.", a: 'Heaven 17', category: 'music', difficulty: 4 },
    { q: "Canadian band whose 1984 single 'New Girl Now' broke them onto US rock radio.", a: 'Honeymoon Suite', category: 'music', difficulty: 5 },
    { q: "Bonnie Tyler's 1984 Jim Steinman-produced anthem from the 'Footloose' soundtrack.", a: 'Holding Out for a Hero', category: 'music', difficulty: 3 },
  ],
  I: [
    { q: "1984 Stevie Wonder Oscar-winning ballad from 'The Woman in Red'.", a: 'I Just Called to Say I Love You', category: 'music', difficulty: 2 },
    { q: "1980 Diana Ross single co-written by Chic's Nile Rodgers about self-acceptance.", a: "I'm Coming Out", category: 'music', difficulty: 3 },
    { q: "Eddie Rabbitt 1980 crossover hit about driving with the windshield wipers slapping.", a: 'I Love a Rainy Night', category: 'music', difficulty: 4 },
    { q: "Australian band led by Iva Davies whose 1987 single was 'Crazy'.", a: 'Icehouse', category: 'music', difficulty: 4 },
    { q: "Genesis 1986 album that produced 'Land of Confusion' and 'Tonight, Tonight, Tonight'.", a: 'Invisible Touch', category: 'music', difficulty: 3 },
    { q: "1987 U2 single about searching that hasn't yielded the desired result yet.", a: "I Still Haven't Found What I'm Looking For", category: 'music', difficulty: 3 },
  ],
  J: [
    { q: "British soft-rock singer whose 1984 #1 single was 'Missing You'.", a: 'John Waite', category: 'music', difficulty: 3 },
    { q: "Australian veteran whose 1986 comeback LP 'Whispering Jack' included 'You're the Voice'.", a: 'John Farnham', category: 'music', difficulty: 3 },
    { q: "Heartland rocker whose 1982 song 'Jack & Diane' came from the 'American Fool' album.", a: 'John Mellencamp', category: 'music', difficulty: 3, alt: ['John Cougar Mellencamp'] },
    { q: "Ohio-born R&B singer of the 1986 dance hit 'We Don't Have to Take Our Clothes Off'.", a: 'Jermaine Stewart', category: 'music', difficulty: 4 },
  ],
  K: [
    { q: "Australian soap-star-turned-pop singer whose 1988 cover of 'Locomotion' hit big.", a: 'Kylie Minogue', category: 'music', difficulty: 2 },
    { q: "Soft-rock singer whose 1980 'Caddyshack' theme was 'I'm Alright'.", a: 'Kenny Loggins', category: 'music', difficulty: 3 },
    { q: "Funk-soul band whose 1980 hit 'Celebration' became a wedding-DJ staple.", a: 'Kool & the Gang', category: 'music', difficulty: 2 },
    { q: "American singer of 'Bette Davis Eyes' with a raspy vocal style.", a: 'Kim Carnes', category: 'music', difficulty: 3 },
    { q: "Hall & Oates 1980 single from 'Voices' about a soulful Philly farewell.", a: 'Kiss on My List', category: 'music', difficulty: 3 },
  ],
  L: [
    { q: "Manchester soul singer whose 1989 hit 'All Around the World' topped UK charts.", a: 'Lisa Stansfield', category: 'music', difficulty: 4 },
    { q: "Canadian rock band whose 1981 hit 'Working for the Weekend' became an MTV staple.", a: 'Loverboy', category: 'music', difficulty: 3 },
    { q: "1984 Deniece Williams hit from the 'Footloose' soundtrack celebrating young men.", a: "Let's Hear It for the Boy", category: 'music', difficulty: 3 },
    { q: "Robert Plant's 1985 power-pop solo single from 'Shaken 'n' Stirred'.", a: 'Little by Little', category: 'music', difficulty: 4 },
    { q: "Stevie Nicks's 1981 duet with Don Henley about a romantic partnership of opposites.", a: 'Leather and Lace', category: 'music', difficulty: 4 },
    { q: "Carly Simon's 1988 Oscar-winning theme from the Mike Nichols film 'Working Girl'.", a: 'Let the River Run', category: 'music', difficulty: 4 },
    { q: "1989 Roxette ballad from the album 'Look Sharp!' about an angel's smile.", a: 'Listen to Your Heart', category: 'music', difficulty: 3 },
  ],
  M: [
    { q: "British supergroup featuring a Genesis guitarist whose 1988 single was 'The Living Years'.", a: 'Mike + the Mechanics', category: 'music', difficulty: 4 },
    { q: "British singer of the 1984 song 'One Night in Bangkok' from a chess musical.", a: 'Murray Head', category: 'music', difficulty: 4 },
    { q: "Female pop duo whose 1987 hit was 'Respectable'.", a: 'Mel and Kim', category: 'music', difficulty: 4, alt: ['Mel & Kim'] },
    { q: "Australian band led by Colin Hay whose 1981 single 'Down Under' became a #1 in the US.", a: 'Men at Work', category: 'music', difficulty: 2 },
    { q: "Mike Oldfield's 1983 single featuring Maggie Reilly on vocals.", a: 'Moonlight Shadow', category: 'music', difficulty: 4 },
  ],
  N: [
    { q: "Swedish-Swiss rapper-singer whose 1988 hit 'Buffalo Stance' launched her career.", a: 'Neneh Cherry', category: 'music', difficulty: 4 },
    { q: "British duo behind the 1983 synth-pop single 'Always Something There to Remind Me'.", a: 'Naked Eyes', category: 'music', difficulty: 4 },
    { q: "1987 Rick Astley debut single produced by Stock Aitken Waterman that topped UK and US charts.", a: 'Never Gonna Give You Up', category: 'music', difficulty: 3 },
    { q: "Phil Collins's brassy 1981 Genesis single from 'Abacab' featuring Earth, Wind & Fire's horn section.", a: 'No Reply at All', category: 'music', difficulty: 5 },
  ],
  O: [
    { q: "Yes's 1983 #1 single from '90125' produced by Trevor Horn.", a: 'Owner of a Lonely Heart', category: 'music', difficulty: 3 },
    { q: "Hall & Oates 1983 R&B-flavoured ballad from the 'H2O' album.", a: 'One on One', category: 'music', difficulty: 4 },
  ],
  P: [
    { q: "Australian band whose 1986 cover of a Lipps Inc. hit reached #1 down under.", a: 'Pseudo Echo', category: 'music', difficulty: 4 },
    { q: "1986 Madonna single from 'True Blue' addressed to a future child.", a: "Papa Don't Preach", category: 'music', difficulty: 3 },
    { q: "1988 Annie Lennox-Al Green duet from the 'Scrooged' soundtrack.", a: 'Put a Little Love in Your Heart', category: 'music', difficulty: 4 },
    { q: "Bruce Springsteen B-side that became a hit when covered by Natalie Cole — names a luxury automobile.", a: 'Pink Cadillac', category: 'music', difficulty: 4 },
  ],
  Q: [],
  R: [
    { q: "1987 worldwide debut #1 by a redheaded Lancashire singer produced by Stock Aitken Waterman.", a: 'Rick Astley', category: 'music', difficulty: 2 },
    { q: "Bryan Ferry's longtime art-rock band whose final album was 1982's 'Avalon'.", a: 'Roxy Music', category: 'music', difficulty: 3 },
    { q: "British glam-tinted singer of 'Simply Irresistible' in 1988.", a: 'Robert Palmer', category: 'music', difficulty: 3 },
    { q: "1984 Queen single from 'The Works' nostalgic about youth and the wireless.", a: 'Radio Ga Ga', category: 'music', difficulty: 3 },
    { q: "Led Zeppelin frontman whose 1988 album 'Now and Zen' featured 'Tall Cool One'.", a: 'Robert Plant', category: 'music', difficulty: 4 },
  ],
  S: [
    { q: "Dance-pop singer signed to Fanfare whose 1986 hit 'So Macho' reached UK #2.", a: 'Sinitta', category: 'music', difficulty: 5 },
    { q: "British synth-rock band whose 1983 ballad 'True' topped UK charts.", a: 'Spandau Ballet', category: 'music', difficulty: 3 },
    { q: "British duo Marc Almond and David Ball whose 1981 cover of 'Tainted Love' became iconic.", a: 'Soft Cell', category: 'music', difficulty: 3 },
    { q: "British dance act behind the 1989 chart-topper 'Back to Life'.", a: 'Soul II Soul', category: 'music', difficulty: 4 },
    { q: "American singer-songwriter whose 1987 hit 'Luka' described an abused child.", a: 'Suzanne Vega', category: 'music', difficulty: 4 },
    { q: "1989 Tears for Fears single with gospel choir and clear Beatles influences.", a: 'Sowing the Seeds of Love', category: 'music', difficulty: 4 },
    { q: "1983 Aussie band Real Life's synth-pop hit that became an MTV favourite.", a: 'Send Me an Angel', category: 'music', difficulty: 4 },
    { q: "1985 Eurythmics-Aretha duet promoting female solidarity.", a: "Sisters Are Doin' It for Themselves", category: 'music', difficulty: 3 },
    { q: "1985 Whitney Houston hit about hoarding affection for one's partner.", a: 'Saving All My Love for You', category: 'music', difficulty: 3 },
    { q: "1984 Sade single from 'Diamond Life' about a slick, jet-setting heartbreaker.", a: 'Smooth Operator', category: 'music', difficulty: 3 },
    { q: "Nigerian-British singer-songwriter Helen Adu's stage name, behind the 1984 hit 'Your Love Is King'.", a: 'Sade', category: 'music', difficulty: 3 },
  ],
  T: [
    { q: "British band led by Mark Hollis whose 1984 hit was 'It's My Life'.", a: 'Talk Talk', category: 'music', difficulty: 4 },
    { q: "British band of Curt Smith and Roland Orzabal behind 'Shout' and 'Mad World'.", a: 'Tears for Fears', category: 'music', difficulty: 2 },
    { q: "American band led by Aimee Mann behind the 1985 hit 'Voices Carry'.", a: "Til Tuesday", category: 'music', difficulty: 4, alt: ["'Til Tuesday"] },
    { q: "Singer-songwriter whose 1988 self-titled debut included 'Fast Car'.", a: 'Tracy Chapman', category: 'music', difficulty: 3 },
    { q: "American choreographer-singer who hit #1 in 1982 with 'Mickey'.", a: 'Toni Basil', category: 'music', difficulty: 3 },
    { q: "1989 Phil Collins #1 ballad written for the Taylor Hackford 'Buster' film.", a: 'Two Hearts', category: 'music', difficulty: 3 },
    { q: "1986 dance-pop hit by Stacey Q with an effervescent synth hook.", a: 'Two of Hearts', category: 'music', difficulty: 4 },
    { q: "1985 charity single by Northern Lights raising funds for Ethiopian famine relief in Canada.", a: 'Tears Are Not Enough', category: 'music', difficulty: 4 },
  ],
  U: [
    { q: "1980 Diana Ross single from a Chic-produced album of the same name.", a: 'Upside Down', category: 'music', difficulty: 3 },
  ],
  V: [
    { q: "1986 Falco single about being a chic urban person riding the rails.", a: 'Vienna Calling', category: 'music', difficulty: 4 },
    { q: "1985 'Til Tuesday breakthrough single about a hushed secret partner.", a: 'Voices Carry', category: 'music', difficulty: 4 },
  ],
  W: [
    { q: "Hong Kong-styled British band whose 1986 single was 'Everybody Have Fun Tonight'.", a: 'Wang Chung', category: 'music', difficulty: 4 },
    { q: "British synth-pop trio behind the 1988 single 'The Promise' featuring a heartfelt phone-call vow.", a: 'When in Rome', category: 'music', difficulty: 4 },
    { q: "U2's 1987 single about a relentless lover from 'The Joshua Tree'.", a: 'With or Without You', category: 'music', difficulty: 2 },
    { q: "1986 Bangles #1 with arms-out hieroglyphic dance moves.", a: 'Walk Like an Egyptian', category: 'music', difficulty: 4 },
  ],
  Y: [
    { q: "British dance-pop singer behind the 1988 #1 'The Only Way Is Up'.", a: 'Yazz', category: 'music', difficulty: 4 },
    { q: "Roy Orbison's 1989 posthumous comeback hit with Jeff Lynne production.", a: 'You Got It', category: 'music', difficulty: 4 },
    { q: "1985 Dead or Alive UK #1 produced by Stock Aitken Waterman with a turntable lyric hook.", a: 'You Spin Me Round', category: 'music', difficulty: 3 },
  ],
};
