import type { RawPack } from '../core/packs';

export const music90sPopPack: RawPack = {
  id: 'music-90s-pop',
  name: '90s Pop',
  description: 'Pop bangers, boy bands, divas and dance hits of the 1990s.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '✨',
  accent: '#e11d48',
  letters: {
    A: [
      { q: 'Canadian singer whose 1995 album "Jagged Little Pill" launched a decade of confessional rock-pop.', a: 'Alanis Morissette', category: 'music' },
      { q: 'British-Canadian girl group whose late-90s hits included "Never Ever" and "Bootie Call".', a: 'All Saints', category: 'music' },
      { q: 'Swedish group whose 1993 worldwide mega-hit "The Sign" sold over 23 million copies.', a: 'Ace of Base', category: 'music' },
      { q: 'Danish-Norwegian-Swedish quartet best known for the bubblegum smash "Barbie Girl" in 1997.', a: 'Aqua', category: 'music' },
      { q: 'Mariah Carey ballad released in 1995 promising eternal devotion to her child or lover — "_____ Be My Baby".', a: 'Always', category: 'music' },
      { q: 'Smash Mouth\'s 1999 sing-along smash from the album "Astro Lounge" later featured in a 2001 Shrek film.', a: 'All Star', category: 'music' },
    ],
    B: [
      { q: 'Five-man Florida vocal group whose 1999 album "Millennium" sold over a million copies in its first week.', a: 'Backstreet Boys', category: 'music' },
      { q: 'Louisiana teen pop star whose debut single dropped in late 1998 and reshaped the decade\'s final months.', a: 'Britney Spears', category: 'music' },
      { q: 'Irish-British four-piece girl quartet whose 1998 debut "C\'est la Vie" hit number one in the UK.', a: 'B*Witched', category: 'music' },
      { q: 'Aqua\'s 1997 plastic-fantastic novelty smash named for a famous Mattel doll.', a: 'Barbie Girl', category: 'music' },
      { q: 'Eiffel 65\'s 1999 Eurodance hit subtitled "Da Ba Dee".', a: 'Blue', category: 'music' },
      { q: 'Philadelphia R&B vocal quartet behind "End of the Road" and "I\'ll Make Love to You".', a: 'Boyz II Men', category: 'music' },
      { q: 'Alannah Myles\'s 1989-90 bluesy crossover smash about an Elvis-inspired sound.', a: 'Black Velvet', category: 'music' },
      { q: 'Cher\'s 1998 dance comeback single that pioneered the use of Auto-Tune as a vocal effect.', a: 'Believe', category: 'music' },
      { q: 'British band fronted by Damon Albarn whose Britpop anthem "Song 2" went global in 1997.', a: 'Blur', category: 'music' },
      { q: 'Britney Spears\' 1999 debut single, a love letter from a schoolgirl missing her ex.', a: 'Baby One More Time', category: 'music', alt: ['...Baby One More Time'] },
      { q: 'The Verve\'s 1997 hit built on an orchestral sample of the Rolling Stones\' "The Last Time".', a: 'Bittersweet Symphony', category: 'music' },
      { q: 'Destiny\'s Child\'s 1999 sass anthem dismissing a freeloading boyfriend who only sends invoices.', a: 'Bills, Bills, Bills', category: 'music' },
    ],
    C: [
      { q: 'Quebec diva whose voice carried the theme from a 1997 James Cameron disaster epic.', a: 'Celine Dion', category: 'music' },
      { q: 'Veteran star whose 1998 Auto-Tuned dance comeback gave the world a single called "Believe".', a: 'Cher', category: 'music' },
      { q: 'Jennifer Paige\'s 1998 one-hit-wonder single about a fleeting infatuation.', a: 'Crush', category: 'music' },
      { q: 'Pop diva who debuted in 1999 with "Genie in a Bottle" and later released the album "Stripped".', a: 'Christina Aguilera', category: 'music' },
      { q: 'TLC\'s second album, released in 1994 and certified diamond — three adjectives crammed into one word.', a: 'CrazySexyCool', category: 'music' },
      { q: 'Pulp\'s 1995 Britpop anthem about a rich girl slumming it for kicks among the working class.', a: 'Common People', category: 'music' },
    ],
    D: [
      { q: 'No Doubt\'s plaintive 1995 breakup ballad from "Tragic Kingdom" that begged silence.', a: 'Don\'t Speak', category: 'music' },
      { q: 'Ace of Base\'s 1994 follow-up hit, a cover of an Aswad reggae song urging you\'ll be fine.', a: 'Don\'t Turn Around', category: 'music' },
      { q: 'Mariah Carey\'s 1995 album that produced "Fantasy" and "One Sweet Day".', a: 'Daydream', category: 'music' },
      { q: 'Houston R&B trio of Beyoncé, Kelly and Michelle whose self-titled 1998 debut included "No, No, No".', a: 'Destiny\'s Child', category: 'music' },
    ],
    E: [
      { q: 'Spanish heartthrob and son of Julio who broke through in the late 90s with "Bailamos".', a: 'Enrique Iglesias', category: 'music' },
      { q: 'Italian dance trio whose 1999 worldwide hit "Blue (Da Ba Dee)" came from the album "Europop".', a: 'Eiffel 65', category: 'music' },
      { q: 'Backstreet Boys\' breakthrough 1996 European single whose title parenthetically promised they were back.', a: 'Everybody', category: 'music' },
      { q: 'Boyz II Men\'s 1992 chart-topping ballad that spent 13 weeks at number one in the US.', a: 'End of the Road', category: 'music' },
    ],
    F: [
      { q: 'British boy band signed by Simon Cowell in 1997, charting with "Slam Dunk (Da Funk)" and "Keep On Movin\'".', a: 'Five', category: 'music', alt: ['5ive'] },
      { q: 'Mariah Carey\'s 1995 album cut sampling Tom Tom Club\'s "Genius of Love".', a: 'Fantasy', category: 'music' },
      { q: 'Jewel\'s 1996 second single, a piano ballad addressed to a thoughtless former lover.', a: 'Foolish Games', category: 'music' },
    ],
    G: [
      { q: 'Ginger Spice\'s real first name in the famous British five-piece.', a: 'Geri', category: 'music' },
      { q: 'Christina Aguilera\'s 1999 debut single comparing her to a wish-granting spirit in a vessel.', a: 'Genie in a Bottle', category: 'music' },
      { q: 'Will Smith\'s 1997 hit sampling Sister Sledge\'s "He\'s the Greatest Dancer", boasting a new attitude.', a: 'Gettin\' Jiggy wit It', category: 'music' },
      { q: 'Spice Girls\' 1998 farewell ballad released as Geri\'s parting single from the group.', a: 'Goodbye', category: 'music' },
    ],
    H: [
      { q: 'Tulsa brothers Isaac, Taylor and Zac whose 1997 falsetto-led smash "MMMBop" topped charts worldwide.', a: 'Hanson', category: 'music' },
      { q: 'Mariah Carey\'s 1993 single from "Music Box" inspiring listeners to find strength within.', a: 'Hero', category: 'music' },
      { q: 'Mariah Carey\'s 1997 single from "Butterfly", named for a sweetener and sampled by Bad Boy producers.', a: 'Honey', category: 'music' },
      { q: 'Alanis Morissette\'s 1995 list-song from "Jagged Little Pill" naming what she keeps tucked beside her thigh.', a: 'Hand in My Pocket', category: 'music' },
    ],
    I: [
      { q: 'Backstreet Boys\' 1999 ballad whose chorus repeatedly asks "tell me why".', a: 'I Want It That Way', category: 'music' },
      { q: 'Whitney Houston\'s 1992 mega-hit, a cover of a Dolly Parton country ballad from "The Bodyguard".', a: 'I Will Always Love You', category: 'music' },
      { q: 'Whitney Houston\'s 1993 desperate ballad from "The Bodyguard" insisting she\'s left with empty arms if she loses him.', a: 'I Have Nothing', category: 'music' },
      { q: 'Alanis Morissette\'s 1996 hit listing rain on a wedding day and a free ride when you\'ve already paid.', a: 'Ironic', category: 'music' },
      { q: 'NSYNC\'s 1998 European hit pleading with an ex to give the relationship another chance.', a: 'I Want You Back', category: 'music' },
      { q: 'Backstreet Boys\' 1995 debut ballad, a single promising eternal romantic safety to a partner.', a: 'I\'ll Never Break Your Heart', category: 'music' },
    ],
    J: [
      { q: 'Alaska-raised yodelly singer-songwriter whose 1995 debut "Pieces of You" sold 12 million copies.', a: 'Jewel', category: 'music' },
      { q: 'Alanis Morissette\'s 1995 breakout album of confessional rock — three words of broken-glass imagery.', a: 'Jagged Little Pill', category: 'music' },
    ],
    K: [
      { q: 'Fugees\' 1996 cover of a Roberta Flack standard, sung by Lauryn Hill.', a: 'Killing Me Softly', category: 'music' },
      { q: 'Seal\'s 1994 ballad that became the love theme to a 1995 Batman film.', a: 'Kiss from a Rose', category: 'music' },
    ],
    L: [
      { q: 'German-born singer whose 1999 Latin-flavoured hit "Mambo No. 5" name-checks a string of women.', a: 'Lou Bega', category: 'music' },
      { q: 'Spanish duo behind the 1995 worldwide line-dance smash "Macarena".', a: 'Los del Rio', category: 'music' },
      { q: 'Ricky Martin\'s 1999 explosive English-language breakthrough about a wild lover.', a: 'Livin\' la Vida Loca', category: 'music' },
      { q: 'Swedish band the Cardigans\' 1996 single asking a partner to pretend to care.', a: 'Lovefool', category: 'music' },
    ],
    M: [
      { q: 'Long-reigning diva whose 1990 debut single "Vision of Love" launched her career.', a: 'Mariah Carey', category: 'music' },
      { q: 'Sporty Spice — her real first name.', a: 'Melanie', category: 'music', alt: ['Mel C', 'Melanie C', 'Melanie Chisholm'] },
      { q: 'Celine Dion\'s 1997 ballad written for a doomed ocean-liner romance film.', a: 'My Heart Will Go On', category: 'music' },
      { q: 'Hanson\'s 1997 debut hit famous for its rapid-fire nonsense-syllable chorus.', a: 'MMMBop', category: 'music' },
      { q: 'Lou Bega\'s 1999 hit, a Latin-jazz cover-update naming Monica, Erica and several other girls.', a: 'Mambo No. 5', category: 'music' },
      { q: 'Los del Rio\'s 1995 line-dance smash whose Bayside Boys remix dominated 1996.', a: 'Macarena', category: 'music' },
      { q: 'Scary Spice — her real first name.', a: 'Mel B', category: 'music', alt: ['Melanie Brown', 'Melanie B'] },
    ],
    N: [
      { q: 'Five-man Orlando boy band who released "Tearin\' Up My Heart" and "I Want You Back".', a: 'NSYNC', category: 'music' },
      { q: 'Five-man group from Massachusetts whose 1998 ballad "Because of You" went top ten.', a: 'Ninety-Eight Degrees', category: 'music', alt: ['98 Degrees', '98°'] },
      { q: 'TLC\'s 1999 sass anthem warning women off freeloading men hanging out the passenger side.', a: 'No Scrubs', category: 'music' },
      { q: 'Australian-British actress turned singer whose 1997 single "Torn" launched her music career.', a: 'Natalie Imbruglia', category: 'music' },
      { q: 'Californian pop band fronted by Gwen Stefani whose 1995 album "Tragic Kingdom" sold 16 million copies.', a: 'No Doubt', category: 'music' },
      { q: 'Sinead O\'Connor\'s 1990 Prince-penned ballad with a famous tearful close-up music video.', a: 'Nothing Compares 2 U', category: 'music' },
    ],
    O: [
      { q: 'Manchester rock band of brothers Noel and Liam Gallagher whose 1995 album "(What\'s the Story) Morning Glory?" defined Britpop.', a: 'Oasis', category: 'music' },
      { q: 'Boyz II Men\'s 1995 collaboration with Mariah Carey, a 16-week US chart-topper tribute ballad.', a: 'One Sweet Day', category: 'music' },
    ],
    P: [
      { q: 'British rock band led by Jarvis Cocker whose 1995 Britpop anthem "Common People" hit number two in the UK.', a: 'Pulp', category: 'music' },
    ],
    Q: [
      { q: 'Backstreet Boys\' 1996 debut single, a plea to stop fooling around with affection.', a: 'Quit Playing Games (With My Heart)', category: 'music' },
    ],
    R: [
      { q: 'Puerto Rican former Menudo member whose 1999 self-titled English album exploded on the Grammys.', a: 'Ricky Martin', category: 'music' },
      { q: 'Swedish singer whose 1997 international breakthrough single "Show Me Love" later became a Eurodance anthem.', a: 'Robyn', category: 'music' },
      { q: 'Swedish duo of Marie Fredriksson and Per Gessle behind 1991\'s "Joyride" and 1994\'s "Crash! Boom! Bang!".', a: 'Roxette', category: 'music' },
      { q: 'Madonna\'s 1998 William Orbit-produced dance-pop comeback album whose title track won a Grammy.', a: 'Ray of Light', category: 'music' },
      { q: 'Mark Morrison\'s 1996 R&B hit announcing the singer\'s triumphant comeback.', a: 'Return of the Mack', category: 'music' },
    ],
    S: [
      { q: 'Five-piece British girl group born from a 1994 newspaper ad, soundtracking the decade with "Wannabe".', a: 'Spice Girls', category: 'music' },
      { q: 'British seven-piece pop act assembled by Simon Fuller, charting with "Bring It All Back" in 1999.', a: 'S Club 7', category: 'music' },
      { q: 'British line-dancing pop quintet whose 1998 cover of "Tragedy" topped the UK charts.', a: 'Steps', category: 'music' },
      { q: 'Canadian country-pop crossover star whose 1997 album "Come On Over" became the best-selling by a female artist in country history.', a: 'Shania Twain', category: 'music' },
      { q: 'American singer-songwriter behind 1993\'s "All I Wanna Do" and a 1996 self-titled second album.', a: 'Sheryl Crow', category: 'music' },
      { q: 'Spice Girls\' second UK number one, a 1996 ballad sung in three-part harmony.', a: 'Say You\'ll Be There', category: 'music' },
      { q: 'The British five-piece\'s kaleidoscopic 1997 single celebrating their multicoloured personalities.', a: 'Spice Up Your Life', category: 'music' },
      { q: 'Eagle-Eye Cherry\'s 1998 acoustic-driven hit promising one more night together.', a: 'Save Tonight', category: 'music' },
      { q: 'Ace of Base\'s 1993 worldwide number one whose opening lyric is "I, I got a new life".', a: 'The Sign', category: 'music', alt: ['Sign'] },
      { q: 'Robyn\'s 1997 international single asking a partner to demonstrate affection — also a Robin S hit four years earlier with the same title.', a: 'Show Me Love', category: 'music' },
      { q: 'Spice Girls\' second studio album, released in November 1997 alongside the band\'s feature film of the same name.', a: 'Spiceworld', category: 'music' },
      { q: 'Santana\'s 1999 collaboration with Rob Thomas — a hot Latin-rock crossover from the album "Supernatural".', a: 'Smooth', category: 'music' },
    ],
    T: [
      { q: 'Atlanta R&B trio of Tionne, Lisa and Rozonda whose 1994 album "CrazySexyCool" sold over 11 million copies in the US.', a: 'TLC', category: 'music' },
      { q: 'NSYNC\'s 1997 debut breakout single about a relationship in pieces, released first in Germany.', a: 'Tearin\' Up My Heart', category: 'music' },
      { q: 'Natalie Imbruglia\'s 1997 cover of an Ednaswap song about feeling cold and ashamed.', a: 'Torn', category: 'music' },
      { q: 'Spice Girls\' Christmas 1996 number one ballad about love uniting a couple into a single soul.', a: 'Two Become One', category: 'music', alt: ['2 Become 1'] },
      { q: 'No Doubt\'s 1995 album that produced "Don\'t Speak" and "Just a Girl" — a two-word title evoking fallen royalty.', a: 'Tragic Kingdom', category: 'music' },
      { q: 'American R&B singer whose 1996 album "Secrets" produced "Un-Break My Heart" and "You\'re Makin\' Me High".', a: 'Toni Braxton', category: 'music' },
      { q: 'Savage Garden\'s 1997 sweeping declaration of romantic devotion, with three adverbs in the title.', a: 'Truly Madly Deeply', category: 'music' },
    ],
    U: [
      { q: 'Irish rock band whose 1991 album "Achtung Baby" and 1997 release "Pop" continued their decade-long reign.', a: 'U2', category: 'music' },
      { q: 'Toni Braxton\'s 1996 Diane Warren-penned mega-ballad pleading to undo a goodbye.', a: 'Un-Break My Heart', category: 'music' },
    ],
    V: [
      { q: 'Dutch dance-pop group of party DJs whose late-90s hits included "We Like to Party!" and "Boom, Boom, Boom, Boom!!".', a: 'Vengaboys', category: 'music' },
      { q: 'Mariah Carey\'s 1990 debut single — a three-word title about seeing romance.', a: 'Vision of Love', category: 'music' },
      { q: 'Posh Spice\'s real first name.', a: 'Victoria', category: 'music', alt: ['Victoria Beckham', 'Victoria Adams'] },
    ],
    W: [
      { q: 'The very first Spice Girls single, released in 1996, demanding to know what a partner really, really wants.', a: 'Wannabe', category: 'music' },
      { q: 'TLC\'s 1995 hit cautioning against chasing impossible dreams, with a famous cascading-river metaphor.', a: 'Waterfalls', category: 'music' },
      { q: 'Irish four-piece launched in 1998 by Louis Walsh, debuting with the cover "Swear It Again".', a: 'Westlife', category: 'music' },
      { q: 'The American rapper and "Fresh Prince" actor who topped 90s pop charts with "Gettin\' Jiggy wit It".', a: 'Will Smith', category: 'music' },
      { q: 'New Jersey vocal powerhouse who, with Bobby Brown, dominated the early decade.', a: 'Whitney Houston', category: 'music' },
      { q: 'Oasis\'s 1995 acoustic anthem about a saviour figure, written by Noel for his then-girlfriend.', a: 'Wonderwall', category: 'music' },
      { q: '4 Non Blondes\' 1992 alt-rock anthem whose wailing chorus repeatedly cries "hey yeah".', a: 'What\'s Up?', category: 'music', alt: ['What\'s Up'] },
    ],
    Y: [
      { q: 'Alanis Morissette\'s scorching 1995 first single accusing an ex of moving on too fast.', a: 'You Oughta Know', category: 'music' },
    ],
  },
};
