import type { RawPack } from '../core/packs';

export const music10sPopPack: RawPack = {
  id: 'music-10s-pop',
  name: '2010s Pop & EDM',
  description: 'Streaming-era pop and EDM crossover of 2010–2019.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎧',
  accent: '#06b6d4',
  letters: {
    A: [
      { q: 'British soul singer behind the 2011 album "21" and the 2015 follow-up "25".', a: 'Adele', category: 'music' },
      { q: 'Ponytailed American pop powerhouse who broke through with 2014\'s "Problem" and "Bang Bang".', a: 'Ariana Grande', category: 'music' },
      { q: 'Swedish DJ-producer behind 2013\'s "Wake Me Up" and "Hey Brother" who tragically died in 2018.', a: 'Avicii', category: 'music' },
      { q: 'California rock band whose 2011 hit "Sail" became a sleeper streaming smash.', a: 'AWOLNATION', category: 'music' },
      { q: 'Nicki Minaj\'s 2014 single sampling Sir Mix-a-Lot\'s "Baby Got Back".', a: 'Anaconda', category: 'music' },
      { q: 'Lady Gaga\'s 2013 album whose title fuses high art and pop music.', a: 'ARTPOP', category: 'music', alt: ['Artpop'] },
      { q: 'Lady Gaga\'s 2013 lead single from "ARTPOP" celebrating the roar of the crowd.', a: 'Applause', category: 'music' },
      { q: 'Meghan Trainor\'s 2014 bubblegum doo-wop smash celebrating body positivity.', a: 'All About That Bass', category: 'music' },
    ],
    B: [
      { q: 'Hawaiian-born pop star behind "Grenade", "Locked Out of Heaven" and "Uptown Funk".', a: 'Bruno Mars', category: 'music' },
      { q: 'Lady Gaga\'s 2011 LGBTQ-positive anthem and album title track.', a: 'Born This Way', category: 'music' },
      { q: 'Taylor Swift\'s 2014 mega-single from "1989" pairing her with kiss-list jokes.', a: 'Blank Space', category: 'music' },
      { q: 'Taylor Swift\'s 2015 Kendrick-Lamar-assisted single from "1989" about betrayal.', a: 'Bad Blood', category: 'music' },
      { q: 'British synth-pop band fronted by Dan Smith behind 2013\'s "Pompeii".', a: 'Bastille', category: 'music' },
      { q: 'Imagine Dragons\' 2017 single from "Evolve" with the chorus "I\'m the greatest".', a: 'Believer', category: 'music' },
      { q: 'Lana Del Rey\'s 2012 major-label debut album with the title track about romanticised doom.', a: 'Born to Die', category: 'music' },
      { q: 'Ariana Grande and Jessie J duet from 2014 also featuring Nicki Minaj.', a: 'Bang Bang', category: 'music' },
      { q: 'Halsey\'s 2017 single from "hopeless fountain kingdom" about being terrible at relationships.', a: 'Bad at Love', category: 'music' },
    ],
    C: [
      { q: 'Scottish DJ-producer behind 2012\'s "18 Months" and 2017\'s "Funk Wav Bounces Vol. 1".', a: 'Calvin Harris', category: 'music' },
      { q: 'Cuban-American singer who left Fifth Harmony and topped charts in 2017 with "Havana".', a: 'Camila Cabello', category: 'music' },
      { q: 'Country-pop crossover star whose 2018 album "Cry Pretty" debuted at number one.', a: 'Carrie Underwood', category: 'music' },
      { q: 'The Chainsmokers\' 2016 mega-hit featuring Halsey about a back-seat reunion.', a: 'Closer', category: 'music' },
      { q: 'Zedd\'s 2012 Grammy-winning single featuring Foxes.', a: 'Clarity', category: 'music' },
      { q: 'OneRepublic\'s 2013 hit from "Native" about losing sleep dreaming.', a: 'Counting Stars', category: 'music' },
      { q: 'Ed Sheeran\'s 2017 single from "÷" referencing his Suffolk hometown.', a: 'Castle on the Hill', category: 'music' },
      { q: 'OMI\'s 2014 reggae-pop smash about a girl he could lean on.', a: 'Cheerleader', category: 'music' },
      { q: 'Katy Perry\'s 2017 lead single from "Witness" produced by Skrillex.', a: 'Chained to the Rhythm', category: 'music' },
    ],
    D: [
      { q: 'Australian DJ duo behind 2014\'s "Latch" and 2015\'s "Caracal".', a: 'Disclosure', category: 'music' },
      { q: 'French robot-helmeted duo behind 2013\'s "Random Access Memories" and "Get Lucky".', a: 'Daft Punk', category: 'music' },
      { q: 'Katy Perry\'s 2013 Juicy-J-featuring smash from "Prism" about a magical mystery love.', a: 'Dark Horse', category: 'music' },
      { q: 'Rihanna\'s 2012 Sia-co-written smash about love sparkling like jewels.', a: 'Diamonds', category: 'music' },
      { q: 'Luis Fonsi\'s 2017 Daddy-Yankee-featuring Spanish-language global smash.', a: 'Despacito', category: 'music' },
      { q: 'The Chainsmokers\' 2016 single featuring Daya about needing someone right now.', a: 'Don\'t Let Me Down', category: 'music' },
      { q: 'One Direction\'s 2015 single from "Made in the A.M." featuring vocoder bass.', a: 'Drag Me Down', category: 'music' },
      { q: 'Imagine Dragons\' 2012 single from "Night Visions" about inner darkness.', a: 'Demons', category: 'music' },
    ],
    E: [
      { q: 'Suffolk-raised singer-songwriter behind "+", "x", "÷" and "Shape of You".', a: 'Ed Sheeran', category: 'music' },
      { q: 'British solo artist whose 2010 debut "Lights" launched her career.', a: 'Ellie Goulding', category: 'music' },
      { q: 'Lady Gaga\'s 2011 single from "Born This Way" about being on the brink.', a: 'Edge of Glory', category: 'music', alt: ['The Edge of Glory'] },
    ],
    F: [
      { q: 'British indie-rock group whose lead singer\'s first name is in the band\'s title, behind 2011\'s "Ceremonials".', a: 'Florence + the Machine', category: 'music', alt: ['Florence and the Machine'] },
      { q: 'Katy Perry\'s 2010 empowerment single comparing her listener to a pyrotechnic display.', a: 'Firework', category: 'music' },
      { q: 'Bruno Mars and Cardi B\'s 2017 remix from the deluxe "24K Magic".', a: 'Finesse', category: 'music' },
      { q: 'Iggy Azalea\'s 2014 chart-topping single featuring Charli XCX.', a: 'Fancy', category: 'music' },
      { q: 'Florida-Cuban quintet who released hits "Worth It" and "Work from Home" in the mid-2010s.', a: 'Fifth Harmony', category: 'music' },
    ],
    G: [
      { q: 'Daft Punk\'s 2013 Pharrell-Williams-featuring lead single from "Random Access Memories".', a: 'Get Lucky', category: 'music' },
      { q: 'Ed Sheeran\'s 2017 jiggy-influenced single from "÷" about an Irish dance.', a: 'Galway Girl', category: 'music' },
      { q: 'Bruno Mars\'s 2010 debut solo single about being prepared to take a bullet for love.', a: 'Grenade', category: 'music' },
      { q: 'Maroon 5\'s 2018 Cardi-B-featuring single from "Red Pill Blues".', a: 'Girls Like You', category: 'music' },
      { q: 'Lorde\'s 2017 lead single from "Melodrama" about leaving an unhealthy relationship.', a: 'Green Light', category: 'music' },
    ],
    H: [
      { q: 'Solo project of New Jersey singer Ashley Frangipane, who released "Badlands" in 2015.', a: 'Halsey', category: 'music' },
      { q: 'One Direction member who released the solo single "Sign of the Times" in 2017.', a: 'Harry Styles', category: 'music' },
      { q: 'Adele\'s 2015 worldwide smash and lead single from "25".', a: 'Hello', category: 'music' },
      { q: 'Camila Cabello\'s 2017 solo breakthrough single featuring Young Thug.', a: 'Havana', category: 'music' },
      { q: 'Twenty One Pilots\' 2016 single from the "Suicide Squad" soundtrack.', a: 'Heathens', category: 'music' },
      { q: 'Marshmello and Bastille\'s 2018 collaboration from his album "Joytime II".', a: 'Happier', category: 'music' },
      { q: 'Avicii\'s 2014 single from "True" featuring vocals about siblings sticking together.', a: 'Hey Brother', category: 'music' },
      { q: 'Irish singer-songwriter behind 2013\'s "Take Me to Church".', a: 'Hozier', category: 'music' },
    ],
    I: [
      { q: 'Las Vegas band fronted by Dan Reynolds behind 2012\'s "Night Visions".', a: 'Imagine Dragons', category: 'music' },
      { q: 'Australian rapper born Amethyst Kelly behind 2014\'s "Fancy".', a: 'Iggy Azalea', category: 'music' },
      { q: 'Taylor Swift\'s 2012 single from "Red" warning about a magnet for badness.', a: 'I Knew You Were Trouble', category: 'music' },
      { q: 'Sam Smith\'s 2014 single insisting his lover has more than just him.', a: 'I\'m Not the Only One', category: 'music' },
      { q: 'Shawn Mendes\'s 2018 single from his self-titled third album.', a: 'In My Blood', category: 'music' },
      { q: 'Ed Sheeran and Justin Bieber\'s 2019 chart-topping duet.', a: 'I Don\'t Care', category: 'music' },
      { q: 'Imagine Dragons\' 2012 indie-rock single from "Continued Silence" about facing the road ahead.', a: 'It\'s Time', category: 'music' },
    ],
    J: [
      { q: 'Canadian teen heart-throb behind 2010\'s "Baby" and 2015\'s "Purpose".', a: 'Justin Bieber', category: 'music' },
      { q: 'Miami-born singer behind "Talk Dirty", "Wiggle" and "Want to Want Me".', a: 'Jason Derulo', category: 'music' },
      { q: 'Lady Gaga\'s 2016 country-pop album named after her late aunt.', a: 'Joanne', category: 'music' },
      { q: 'Bruno Mars\'s 2010 single from "Doo-Wops & Hooligans" complimenting natural beauty.', a: 'Just the Way You Are', category: 'music' },
    ],
    K: [
      { q: 'California pop star behind 2010\'s "Teenage Dream" and 2013\'s "Prism".', a: 'Katy Perry', category: 'music' },
      { q: 'Norwegian tropical-house producer behind "Firestone" and "Stole the Show".', a: 'Kygo', category: 'music' },
      { q: 'Selena Gomez\'s 2016 single from "Revival" about killing them with affection.', a: 'Kill Em with Kindness', category: 'music', alt: ['Kill \'Em with Kindness'] },
    ],
    L: [
      { q: 'Sultry American singer born Elizabeth Grant who released "Born to Die" in 2012 and "Norman Fucking Rockwell!" in 2019.', a: 'Lana Del Rey', category: 'music' },
      { q: 'New Zealand teen who debuted in 2013 with "Royals" and the album "Pure Heroine".', a: 'Lorde', category: 'music' },
      { q: 'British girl group formed on "The X Factor" in 2011 behind "Black Magic".', a: 'Little Mix', category: 'music' },
      { q: 'Taylor Swift\'s 2017 single from "Reputation" referencing a phone snake call.', a: 'Look What You Made Me Do', category: 'music' },
      { q: 'Bruno Mars\'s 2012 single about a heavenly relationship.', a: 'Locked Out of Heaven', category: 'music' },
      { q: 'Avicii\'s 2011 breakthrough single sampling Etta James.', a: 'Levels', category: 'music' },
      { q: 'Ellie Goulding\'s 2015 single from the "Fifty Shades of Grey" soundtrack.', a: 'Love Me Like You Do', category: 'music' },
      { q: 'Taylor Swift\'s 2019 album with a pastel cover and the title-track romance.', a: 'Lover', category: 'music' },
      { q: 'American folk-rock trio behind 2012\'s "Ho Hey".', a: 'Lumineers', category: 'music', alt: ['The Lumineers'] },
    ],
    M: [
      { q: 'LA pop-rock band led by Adam Levine behind "Moves Like Jagger" and "Sugar".', a: 'Maroon 5', category: 'music' },
      { q: 'Lady Gaga\'s 2011 single from "Born This Way" about a moonlit wedding.', a: 'Marry the Night', category: 'music' },
      { q: 'Maroon 5\'s 2014 single from "V" about a love GPS.', a: 'Maps', category: 'music' },
      { q: 'Helmet-wearing electronic producer behind 2018\'s "Happier" with Bastille.', a: 'Marshmello', category: 'music' },
      { q: 'Lady Gaga\'s 2016 piano ballad from "Joanne" about loving anyway.', a: 'Million Reasons', category: 'music' },
      { q: 'Maroon 5\'s 2017 single dedicated to a late mentor.', a: 'Memories', category: 'music' },
      { q: 'Dutch DJ behind 2013\'s "Animals" who became one of the world\'s top DJs as a teenager.', a: 'Martin Garrix', category: 'music' },
    ],
    N: [
      { q: 'Imagine Dragons\' 2018 lead single from "Origins" used as a sports anthem.', a: 'Natural', category: 'music' },
      { q: 'Rihanna\'s 2016 single from "Anti" admitting reluctance about requiring affection.', a: 'Needed Me', category: 'music' },
      { q: 'One Direction\'s 2014 single from "Four" about late-evening transformations.', a: 'Night Changes', category: 'music' },
      { q: 'Irish ex-One Direction member who solo-debuted with "This Town" in 2016.', a: 'Niall Horan', category: 'music' },
      { q: 'Halsey\'s 2017 collaboration with Yungblud and Stefflon Don.', a: 'Now or Never', category: 'music' },
    ],
    O: [
      { q: 'Colorado pop-rock band fronted by Ryan Tedder behind "Counting Stars".', a: 'OneRepublic', category: 'music' },
      { q: 'British boy band formed on "The X Factor" in 2010 behind "What Makes You Beautiful".', a: 'One Direction', category: 'music' },
      { q: 'Maroon 5\'s 2012 single from "Overexposed" about lasting affection.', a: 'One More Night', category: 'music' },
      { q: 'Taylor Swift\'s 2014 deluxe-edition single from "1989" about getting back into the brush.', a: 'Out of the Woods', category: 'music' },
    ],
    P: [
      { q: 'Bastille\'s 2013 worldwide breakthrough single named after a destroyed Roman city.', a: 'Pompeii', category: 'music' },
      { q: 'Maroon 5\'s 2012 Wiz-Khalifa-featuring single about calling someone collect.', a: 'Payphone', category: 'music' },
      { q: 'Ed Sheeran\'s 2014 acoustic single from "x" about a love captured in a photo.', a: 'Photograph', category: 'music' },
      { q: 'Pop singer born Alecia Moore behind "Try" and 2017\'s "Beautiful Trauma".', a: 'Pink', category: 'music', alt: ['P!nk'] },
      { q: 'Justin Bieber\'s 2015 comeback album featuring "Sorry" and "Love Yourself".', a: 'Purpose', category: 'music' },
      { q: 'One Direction\'s 2015 ballad later re-recorded with strings on "Made in the A.M.".', a: 'Perfect', category: 'music' },
      { q: 'Lady Gaga\'s 2016 single from "Joanne" co-written with Mark Ronson and Kevin Parker.', a: 'Perfect Illusion', category: 'music' },
    ],
    R: [
      { q: 'Lorde\'s 2013 debut single mocking lavish hip-hop lifestyles.', a: 'Royals', category: 'music' },
      { q: 'Adele\'s 2010 lead single from "21" about a deeply burning love.', a: 'Rolling in the Deep', category: 'music' },
      { q: 'Katy Perry\'s 2013 lead single from "Prism" with the eye-of-the-tiger chorus.', a: 'Roar', category: 'music' },
      { q: 'Imagine Dragons\' 2012 breakout single from "Night Visions" about waking up to a new age.', a: 'Radioactive', category: 'music' },
      { q: 'Taylor Swift\'s 2012 album featuring the title track and "I Knew You Were Trouble".', a: 'Red', category: 'music' },
      { q: 'Twenty One Pilots\' 2015 single from "Blurryface" with falling and shotgun lyrics.', a: 'Ride', category: 'music' },
      { q: 'Vance Joy\'s 2013 acoustic-driven hit comparing a girl to a dangerous wave.', a: 'Riptide', category: 'music' },
      { q: 'Taylor Swift\'s 2017 album whose era featured snake imagery.', a: 'Reputation', category: 'music' },
    ],
    S: [
      { q: 'Taylor Swift\'s 2014 lead "1989" single dismissing the haters.', a: 'Shake It Off', category: 'music' },
      { q: 'Ed Sheeran\'s 2017 global smash with a tropical-house lilt and Galway lyric.', a: 'Shape of You', category: 'music' },
      { q: 'British singer behind 2014\'s "In the Lonely Hour" and "Stay With Me".', a: 'Sam Smith', category: 'music' },
      { q: 'Australian wig-wearing singer behind 2014\'s "Chandelier".', a: 'Sia', category: 'music' },
      { q: 'Lady Gaga and Bradley Cooper\'s 2018 duet from "A Star Is Born".', a: 'Shallow', category: 'music' },
      { q: 'Justin Bieber\'s 2015 lead single from "Purpose" about apologising.', a: 'Sorry', category: 'music' },
      { q: 'Adele\'s 2011 single from "21" combining ignited passion with stormy weather imagery.', a: 'Set Fire to the Rain', category: 'music' },
      { q: 'Adele\'s 2012 Bond theme from the 23rd 007 film.', a: 'Skyfall', category: 'music' },
      { q: 'Sam Smith\'s 2014 ballad about a one-night-stand pleading.', a: 'Stay With Me', category: 'music' },
      { q: 'Twenty One Pilots\' 2015 single from "Blurryface" about adulthood anxiety.', a: 'Stressed Out', category: 'music' },
      { q: 'Shawn Mendes\'s 2015 debut breakthrough single about wounds and bandages.', a: 'Stitches', category: 'music' },
      { q: 'Shawn Mendes and Camila Cabello\'s 2019 Latin-flavoured duet.', a: 'Señorita', category: 'music', alt: ['Senorita'] },
      { q: 'One Direction\'s 2013 single from "Midnight Memories" about a partner-in-crime worth defending.', a: 'Story of My Life', category: 'music' },
      { q: 'Harry Styles\'s 2017 debut solo single nostalgic for the past.', a: 'Sign of the Times', category: 'music' },
      { q: 'Coldplay and The Chainsmokers\' 2017 collaboration about wanting an ordinary love.', a: 'Something Just Like This', category: 'music' },
      { q: 'Lana Del Rey\'s 2012 single from "Born to Die" about endless summer melancholy.', a: 'Summertime Sadness', category: 'music' },
      { q: 'Maroon 5\'s 2014 single from "V" with a 70s-style strings hook.', a: 'Sugar', category: 'music' },
      { q: 'Texas-born "Body Like a Back Road" country-pop singer who broke through in 2014.', a: 'Sam Hunt', category: 'music' },
    ],
    T: [
      { q: 'Pennsylvania singer-songwriter behind "Red" (2012), "1989" (2014) and "Reputation" (2017).', a: 'Taylor Swift', category: 'music' },
      { q: 'Canadian R&B artist born Abel Tesfaye behind 2015\'s "Can\'t Feel My Face".', a: 'The Weeknd', category: 'music' },
      { q: 'New York DJ duo Drew Taggart and Alex Pall behind "Closer".', a: 'The Chainsmokers', category: 'music' },
      { q: 'Imagine Dragons\' 2017 single from "Evolve" about being struck by lightning.', a: 'Thunder', category: 'music' },
      { q: 'Hozier\'s 2013 worldwide breakthrough single inviting his lover to worship.', a: 'Take Me to Church', category: 'music' },
      { q: 'Ed Sheeran\'s 2014 acoustic ballad about people falling in love at 70.', a: 'Thinking Out Loud', category: 'music' },
      { q: 'Ohio duo Tyler Joseph and Josh Dun behind "Stressed Out".', a: 'Twenty One Pilots', category: 'music' },
      { q: 'Bruno Mars\'s 2013 single from "Unorthodox Jukebox" giving compliments.', a: 'Treasure', category: 'music' },
      { q: 'Shawn Mendes\'s 2016 single promising to outdo his rival.', a: 'Treat You Better', category: 'music' },
      { q: 'Jason Derulo\'s 2013 single about kissing skills exceeding language.', a: 'Talk Dirty', category: 'music' },
      { q: 'Avicii\'s 2014 anthemic deep-house track sampling Etta James and Nile Rodgers.', a: 'The Nights', category: 'music' },
      { q: 'Shawn Mendes\'s 2017 single declaring his feelings are unstoppable.', a: 'There\'s Nothing Holdin\' Me Back', category: 'music', alt: ['Theres Nothing Holding Me Back'] },
    ],
    U: [
      { q: 'Mark Ronson and Bruno Mars\'s 2014 retro-disco worldwide smash about a swaggering nightlife.', a: 'Uptown Funk', category: 'music' },
    ],
    V: [
      { q: 'Lana Del Rey\'s 2011 viral debut single about Hollywood escapism.', a: 'Video Games', category: 'music' },
      { q: 'Bruno Mars\'s 2016 R&B ballad name-checking an Italian luxury fashion house.', a: 'Versace on the Floor', category: 'music' },
    ],
    W: [
      { q: 'Avicii\'s 2013 hit featuring Aloe Blacc with a folk-house fusion.', a: 'Wake Me Up', category: 'music' },
      { q: 'Taylor Swift\'s 2012 single from "Red" about a recurring on-off romance.', a: 'We Are Never Ever Getting Back Together', category: 'music' },
      { q: 'Rihanna and Calvin Harris\'s 2011 chart-topping dance smash.', a: 'We Found Love', category: 'music' },
      { q: 'One Direction\'s 2011 debut single produced by Rami Yacoub.', a: 'What Makes You Beautiful', category: 'music' },
      { q: 'Miley Cyrus\'s 2013 lead "Bangerz" single about a giant orb of destruction.', a: 'Wrecking Ball', category: 'music' },
      { q: 'Justin Bieber\'s 2015 deep-house single from "Purpose".', a: 'What Do You Mean?', category: 'music', alt: ['What Do You Mean'] },
      { q: 'Miley Cyrus\'s 2013 party anthem about no-one stopping the band.', a: 'We Can\'t Stop', category: 'music', alt: ['We Cant Stop'] },
      { q: 'Avicii\'s 2015 single counselling patience for true romance.', a: 'Waiting for Love', category: 'music' },
      { q: 'Ohio rock band whose 2014 retro-80s breakthrough single was "Shut Up and Dance".', a: 'Walk the Moon', category: 'music' },
      { q: 'Imagine Dragons\' 2017 single from "Evolve" about giving everything.', a: 'Whatever It Takes', category: 'music' },
      { q: 'Bruno Mars\'s 2012 ballad about regret over a lost love.', a: 'When I Was Your Man', category: 'music' },
      { q: 'Halsey\'s 2018 solo single about being treated like an afterthought.', a: 'Without Me', category: 'music' },
    ],
    Y: [
      { q: 'Taylor Swift\'s 2019 single from "Lover" preaching tolerance.', a: 'You Need to Calm Down', category: 'music' },
      { q: 'Lana Del Rey\'s 2013 ballad from "The Great Gatsby" soundtrack.', a: 'Young and Beautiful', category: 'music' },
    ],
    Z: [
      { q: 'German DJ-producer born Anton Zaslavski behind 2012\'s "Clarity".', a: 'Zedd', category: 'music' },
      { q: 'Ex-One Direction member born in Bradford who solo-debuted with "Pillowtalk" in 2016.', a: 'Zayn', category: 'music', alt: ['Zayn Malik'] },
    ],
  },
};
