import type { RawPack } from '../core/packs';

// 80s Pop music pack — songs, albums, artists, MTV-era moments.
// Every answer starts with the letter it sits under, never appears in the
// question, is a real named entity (song / album / artist / venue), is
// factually accurate, and is non-padded.

export const music80sPopPack: RawPack = {
  id: 'music-80s-pop',
  name: '80s Pop',
  description: 'Pop hits and icons of the 1980s.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎤',
  accent: '#ec4899',
  letters: {
    A: [
      { q: "Norwegian synth-pop trio behind the 1985 worldwide smash 'Take On Me'.", a: 'A-ha', category: '80s-pop' },
      { q: "Phil Collins ballad from the 1984 Taylor Hackford film about a man hired to find his boss's girlfriend.", a: 'Against All Odds', category: '80s-pop' },
      { q: "Lionel Richie's 1983 chart-topping party single from his 'Can't Slow Down' album.", a: 'All Night Long', category: '80s-pop' },
      { q: "Detroit-born R&B icon who sang 'Freeway of Love' in 1985 and was crowned Queen of Soul.", a: 'Aretha Franklin', category: '80s-pop' },
      { q: "Wham!'s guitarist and George Michael's musical partner.", a: 'Andrew Ridgeley', category: '80s-pop' },
    ],
    B: [
      { q: "Michael Jackson's 1987 follow-up album to 'Thriller', spawning seven Top 10 singles.", a: 'Bad', category: '80s-pop' },
      { q: "Michael Jackson 1983 single featuring Eddie Van Halen's guitar solo about urban conflict.", a: 'Beat It', category: '80s-pop' },
      { q: "1982 Michael Jackson hit about a woman claiming he fathered her child.", a: 'Billie Jean', category: '80s-pop' },
      { q: "British girl group from Bristol whose 1986 remake of a Shocking Blue song topped the US charts.", a: 'Bananarama', category: '80s-pop' },
      { q: "Welsh singer of the 1983 power ballad 'Total Eclipse of the Heart'.", a: 'Bonnie Tyler', category: '80s-pop' },
      { q: "Former Go-Go's lead singer who hit #1 in 1987 with 'Heaven Is a Place on Earth'.", a: 'Belinda Carlisle', category: '80s-pop' },
      { q: "Lead vocalist of Culture Club known for 'Karma Chameleon' and his colourful style.", a: 'Boy George', category: '80s-pop' },
      { q: "New Jersey rocker who released 'Born in the U.S.A.' in 1984.", a: 'Bruce Springsteen', category: '80s-pop' },
    ],
    C: [
      { q: "1984 saxophone-led George Michael single about guilty feet that have no rhythm.", a: 'Careless Whisper', category: '80s-pop' },
      { q: "Boy George's flamboyant new wave band that hit it big with 'Karma Chameleon'.", a: 'Culture Club', category: '80s-pop' },
      { q: "Singer of 'If I Could Turn Back Time' who starred opposite Nicolas Cage in 'Moonstruck'.", a: 'Cher', category: '80s-pop' },
      { q: "Singer of 'Girls Just Want to Have Fun' known for her colourful hair and Brooklyn accent.", a: 'Cyndi Lauper', category: '80s-pop' },
      { q: "Lionel Richie's 1983 second solo album that produced five Top 10 singles.", a: "Can't Slow Down", category: '80s-pop' },
      { q: "Janet Jackson's 1986 breakthrough album with the singles 'Nasty' and 'When I Think of You'.", a: 'Control', category: '80s-pop' },
    ],
    D: [
      { q: "Birmingham band named after a 'Barbarella' villain that recorded 'Hungry Like the Wolf'.", a: 'Duran Duran', category: '80s-pop' },
      { q: "Motown legend who sang the 1981 #1 'Endless Love' with Lionel Richie.", a: 'Diana Ross', category: '80s-pop' },
      { q: "Teenage pop singer whose 1987 debut LP 'Out of the Blue' produced four Top 5 singles.", a: 'Debbie Gibson', category: '80s-pop' },
      { q: "British rock outfit fronted by Mark Knopfler who hit #1 in 1985 with 'Money for Nothing'.", a: 'Dire Straits', category: '80s-pop' },
      { q: "Tall half of the Philadelphia duo with John Oates — first and last name of the lead singer.", a: 'Daryl Hall', category: '80s-pop' },
    ],
    E: [
      { q: "1981 #1 duet by Lionel Richie and Diana Ross from a Franco Zeffirelli film of the same name.", a: 'Endless Love', category: '80s-pop' },
      { q: "Annie Lennox and Dave Stewart's synth-pop duo behind 'Here Comes the Rain Again'.", a: 'Eurythmics', category: '80s-pop' },
      { q: "Guitarist who played the legendary solo on 'Beat It'.", a: 'Eddie Van Halen', category: '80s-pop' },
      { q: "British band led by Jeff Lynne, abbreviated as three initials, who scored 'Xanadu' with Olivia Newton-John.", a: 'ELO', category: '80s-pop' },
    ],
    F: [
      { q: "1980 Irene Cara title song from a film about students at New York's High School for the Performing Arts.", a: 'Fame', category: '80s-pop' },
      { q: "George Michael's 1987 debut solo album whose title track topped the US chart.", a: 'Faith', category: '80s-pop' },
      { q: "Liverpool band of the 80s known for the BBC-banned single 'Relax'.", a: 'Frankie Goes to Hollywood', category: '80s-pop' },
      { q: "Aretha Franklin's 1985 chart hit celebrating fast cars and romance.", a: 'Freeway of Love', category: '80s-pop' },
      { q: "1983 Irene Cara title song from a movie about a steel-town welder who dreams of dancing.", a: 'Flashdance... What a Feeling', category: '80s-pop' },
      { q: "AOR band whose 1984 power ballad asks for guidance about an emotion they don't understand.", a: 'Foreigner', category: '80s-pop' },
    ],
    G: [
      { q: "Wham!'s lead singer whose solo career exploded with 'Faith' in 1987.", a: 'George Michael', category: '80s-pop' },
      { q: "Cyndi Lauper's playful 1983 anthem about young women wanting independence after a hard day.", a: 'Girls Just Want to Have Fun', category: '80s-pop' },
      { q: "Whitney Houston's 1986 anthem about loving yourself, originally written for a Muhammad Ali biopic.", a: 'Greatest Love of All', category: '80s-pop' },
      { q: "Prog-rock band fronted by Phil Collins after Peter Gabriel left, who went pop in the 80s.", a: 'Genesis', category: '80s-pop' },
    ],
    H: [
      { q: "Lionel Richie's 1984 ballad whose iconic music video features a blind sculpture student.", a: 'Hello', category: '80s-pop' },
      { q: "Daryl and John, the Philadelphia duo with hits like 'Maneater' and 'Out of Touch'.", a: 'Hall & Oates', category: '80s-pop' },
      { q: "Belinda Carlisle's 1987 chart-topper about how being together makes any spot paradise.", a: 'Heaven Is a Place on Earth', category: '80s-pop' },
      { q: "Eurythmics's 1984 single referencing thunder, lightning, and a frightening kind of love.", a: 'Here Comes the Rain Again', category: '80s-pop' },
      { q: "Duran Duran's 1982 second single, predator-themed and inspired by Bowie.", a: 'Hungry Like the Wolf', category: '80s-pop' },
    ],
    I: [
      { q: "Phil Collins's brooding 1981 debut solo single famous for its delayed drum fill.", a: 'In the Air Tonight', category: '80s-pop' },
      { q: "Whitney Houston's 1987 dance-pop chart-topper expressing a wish for partnership and rhythm.", a: 'I Wanna Dance with Somebody', category: '80s-pop' },
      { q: "Madonna's 1985 hit from 'Desperately Seeking Susan' about a dance-floor connection.", a: 'Into the Groove', category: '80s-pop' },
      { q: "Foreigner's 1984 power ballad title pleading for guidance on emotional confusion.", a: 'I Want to Know What Love Is', category: '80s-pop' },
      { q: "Australian band led by Michael Hutchence who hit big with 'Need You Tonight'.", a: 'INXS', category: '80s-pop' },
      { q: "Singer of 'Fame' (1980) and 'Flashdance... What a Feeling' (1983).", a: 'Irene Cara', category: '80s-pop' },
    ],
    J: [
      { q: "Michael's pop-star sister whose 1986 album 'Control' marked her artistic independence.", a: 'Janet Jackson', category: '80s-pop' },
      { q: "Van Halen's 1984 chart-topping single inviting listeners to leap.", a: 'Jump', category: '80s-pop' },
      { q: "Michael Jackson's older brothers' family band of the 80s, formerly the J5.", a: 'Jacksons', category: '80s-pop' },
      { q: "First name of the moustached partner of Daryl Hall in their soul-pop duo.", a: 'John', category: '80s-pop', alt: ['John Oates'] },
    ],
    K: [
      { q: "Culture Club's 1983 worldwide #1, the title evoking a colour-changing reptile.", a: 'Karma Chameleon', category: '80s-pop' },
      { q: "Prince's 1986 minimalist funk single from the 'Parade' album.", a: 'Kiss', category: '80s-pop' },
      { q: "British singer of the 1981 hit 'Kids in America', daughter of rocker Marty.", a: 'Kim Wilde', category: '80s-pop' },
      { q: "Michael Jackson's nickname as the undisputed top male pop artist of the decade.", a: 'King of Pop', category: '80s-pop' },
    ],
    L: [
      { q: "Madonna's 1984 breakthrough single about feeling new again because of a lover's touch.", a: 'Like a Virgin', category: '80s-pop' },
      { q: "Singer of 'All Night Long' and 'Hello' formerly of the Commodores.", a: 'Lionel Richie', category: '80s-pop' },
      { q: "Madonna's controversial 1989 title track that drew Vatican condemnation for its gospel-tinged video.", a: 'Like a Prayer', category: '80s-pop' },
      { q: "Wham!'s tender 1984 holiday single about giving a heart away the previous December.", a: 'Last Christmas', category: '80s-pop' },
      { q: "1985 dual-venue charity concert at Wembley and JFK Stadium organised by Bob Geldof.", a: 'Live Aid', category: '80s-pop' },
    ],
    M: [
      { q: "Pop superstar born Louise Veronica Ciccone in Bay City, Michigan.", a: 'Madonna', category: '80s-pop' },
      { q: "Madonna's 1984 single declaring she lives in a world dominated by economics.", a: 'Material Girl', category: '80s-pop' },
      { q: "Hall & Oates' 1982 #1 about a dangerous, prowling woman.", a: 'Maneater', category: '80s-pop' },
      { q: "Pop icon nicknamed the King of Pop who released 'Thriller' in 1982.", a: 'Michael Jackson', category: '80s-pop' },
      { q: "Dire Straits's 1985 satirical hit whose video pioneered computer animation on the music channel.", a: 'Money for Nothing', category: '80s-pop' },
      { q: "Cable channel launched 1 August 1981 that revolutionised 80s pop visuals.", a: 'MTV', category: '80s-pop' },
      { q: "INXS frontman who died in 1997.", a: 'Michael Hutchence', category: '80s-pop' },
      { q: "Singer of the 1983 song 'Maniac' from the 'Flashdance' soundtrack.", a: 'Michael Sembello', category: '80s-pop' },
    ],
    N: [
      { q: "Janet Jackson's 1986 single from 'Control' whose narrator insists on being called 'Miss' if you please.", a: 'Nasty', category: '80s-pop' },
      { q: "German singer behind the 1983 anti-war balloon song that crossed over in two languages.", a: 'Nena', category: '80s-pop' },
      { q: "INXS's 1987 single whose video had a chequerboard floor and a prowling frontman.", a: 'Need You Tonight', category: '80s-pop' },
      { q: "Phil Collins's 1985 album that won Album of the Year at the Grammys.", a: 'No Jacket Required', category: '80s-pop' },
    ],
    O: [
      { q: "Australian-born singer who starred in 'Grease' as Sandy and topped charts in 1981 with 'Physical'.", a: 'Olivia Newton-John', category: '80s-pop' },
      { q: "Hall & Oates 1984 single from the 'Big Bam Boom' album about feeling disconnected.", a: 'Out of Touch', category: '80s-pop' },
      { q: "Surname of John, the moustached half of the Philadelphia soul duo whose other member is Daryl Hall.", a: 'Oates', category: '80s-pop' },
    ],
    P: [
      { q: "Drummer and singer of Genesis who released 'No Jacket Required' in 1985.", a: 'Phil Collins', category: '80s-pop' },
      { q: "Minneapolis multi-instrumentalist born Rogers Nelson who released 'Purple Rain' in 1984.", a: 'Prince', category: '80s-pop' },
      { q: "Title track from a 1984 film starring its musical creator alongside Apollonia.", a: 'Purple Rain', category: '80s-pop' },
      { q: "Synth-pop duo of Neil Tennant and Chris Lowe who hit #1 with 'West End Girls'.", a: 'Pet Shop Boys', category: '80s-pop' },
      { q: "Singer who broke through with 'Straight Up' in 1988 and later became an 'American Idol' judge.", a: 'Paula Abdul', category: '80s-pop' },
      { q: "Olivia Newton-John's 1981 fitness-themed #1 single, ten weeks atop Billboard.", a: 'Physical', category: '80s-pop' },
      { q: "Tina Turner's 1984 comeback album whose title track depicts a paid-by-the-hour escort.", a: 'Private Dancer', category: '80s-pop' },
    ],
    Q: [
      { q: "British rock band fronted by Freddie Mercury whose 1985 Live Aid set is considered legendary.", a: 'Queen', category: '80s-pop' },
      { q: "Producer behind 'Thriller', 'Bad', and 'We Are the World'.", a: 'Quincy Jones', category: '80s-pop' },
    ],
    R: [
      { q: "1984 Frankie Goes to Hollywood single famously banned by the BBC.", a: 'Relax', category: '80s-pop' },
      { q: "Toto's 1982 chart-topper named after a woman, from the album 'IV'.", a: 'Rosanna', category: '80s-pop' },
      { q: "Bryan Adams's 1984 album that produced 'Summer of '69' and 'Run to You'.", a: 'Reckless', category: '80s-pop' },
      { q: "Bryan Adams's 1985 single about chasing toward a lover when wandering away.", a: 'Run to You', category: '80s-pop' },
    ],
    S: [
      { q: "Michael Jackson's 1988 single featuring an anti-gravity lean in its short film.", a: 'Smooth Criminal', category: '80s-pop' },
      { q: "Eurythmics's 1983 worldwide breakthrough whose video features Annie Lennox with cropped orange hair in a man's suit.", a: 'Sweet Dreams', category: '80s-pop', alt: ['Sweet Dreams (Are Made of This)'] },
      { q: "Scottish singer whose 1981 hit was 'Modern Girl' before she duetted with Prince on '99'.", a: 'Sheena Easton', category: '80s-pop' },
      { q: "Paula Abdul's 1988 #1 about an honest, no-games approach to romance.", a: 'Straight Up', category: '80s-pop' },
      { q: "Bassist-vocalist who left The Police and released 'The Dream of the Blue Turtles' in 1985.", a: 'Sting', category: '80s-pop' },
      { q: "Bryan Adams's 1985 wistful hit looking back on a band that played until the season's end.", a: "Summer of '69", category: '80s-pop' },
    ],
    T: [
      { q: "Michael Jackson's record-shattering 1982 album with the cover featuring him in a white suit.", a: 'Thriller', category: '80s-pop' },
      { q: "Rock and soul singer who topped the charts with 'Private Dancer' after leaving Ike.", a: 'Tina Turner', category: '80s-pop' },
      { q: "1984 Cyndi Lauper ballad about waiting forever for a slower partner.", a: 'Time After Time', category: '80s-pop' },
      { q: "a-ha's 1985 #1 with a famous pencil-sketch and live-action rotoscoped music video.", a: 'Take On Me', category: '80s-pop' },
      { q: "Bubblegum pop singer born Renee Darwish whose 1987 mall-tour debut hit #1.", a: 'Tiffany', category: '80s-pop' },
      { q: "Berlin's 1986 power ballad from the 'Top Gun' soundtrack.", a: 'Take My Breath Away', category: '80s-pop' },
      { q: "Bonnie Tyler's 1983 worldwide #1 about being lost in the dark and turning around.", a: 'Total Eclipse of the Heart', category: '80s-pop' },
      { q: "Soft-rock band behind the 1982 album 'IV' with hits 'Rosanna' and 'Africa'.", a: 'Toto', category: '80s-pop' },
    ],
    U: [
      { q: "Irish rock band who released 'The Joshua Tree' in 1987 with 'With or Without You'.", a: 'U2', category: '80s-pop' },
      { q: "Charity supergroup behind 'We Are the World' — three-word famine-relief collective from 1985.", a: 'USA for Africa', category: '80s-pop' },
    ],
    V: [
      { q: "Bananarama's 1986 #1, a remake of a 1969 Shocking Blue hit named after a Roman goddess.", a: 'Venus', category: '80s-pop' },
      { q: "American hard-rock band fronted by David Lee Roth who scored 1984's 'Jump'.", a: 'Van Halen', category: '80s-pop' },
      { q: "1981 Buggles single — the first clip ever broadcast on MTV when it launched on August 1.", a: 'Video Killed the Radio Star', category: '80s-pop' },
    ],
    W: [
      { q: "British pop duo of George Michael and Andrew Ridgeley with the 1984 hit about not being left on the dancefloor.", a: 'Wham!', category: '80s-pop' },
      { q: "1985 USA for Africa charity single co-written by Michael Jackson and Lionel Richie.", a: 'We Are the World', category: '80s-pop' },
      { q: "Newark-born pop and R&B singer known as 'The Voice' who broke through in 1985.", a: 'Whitney Houston', category: '80s-pop' },
      { q: "Prince's 1984 hit from 'Purple Rain' asking why birds make a mournful sound.", a: 'When Doves Cry', category: '80s-pop' },
      { q: "Pet Shop Boys' breakthrough 1985 #1 named after a part of London.", a: 'West End Girls', category: '80s-pop' },
      { q: "Tina Turner's 1984 Grammy-winning rhetorical question about emotion versus passion.", a: "What's Love Got to Do with It", category: '80s-pop' },
      { q: "Wham!'s upbeat 1984 #1 single featuring jitterbug rhythms and yellow t-shirts in its music video.", a: 'Wake Me Up Before You Go-Go', category: '80s-pop' },
    ],
    X: [
      { q: "Olivia Newton-John's 1980 fantasy-musical title hit co-recorded with Electric Light Orchestra.", a: 'Xanadu', category: '80s-pop' },
    ],
    Y: [
      { q: "1984 Wham! single subtitled '(Go for It!)' that became a UK Top 3 hit.", a: 'Young Guns', category: '80s-pop' },
      { q: "British synth-pop duo of Vince Clarke and Alison Moyet active 1982 to 1983.", a: 'Yazoo', category: '80s-pop' },
    ],
    Z: [
      { q: "Frank's experimental composer whose 1982 novelty hit 'Valley Girl' featured his daughter Moon Unit.", a: 'Zappa', category: '80s-pop', alt: ['Frank Zappa'] },
    ],
  },
};
