import type { RawQuestion } from '../core/packs';

export const musicMediumExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: 'The Swedish pop group behind "Dancing Queen" and "Mamma Mia".', a: 'ABBA', category: 'music', difficulty: 2 },
    { q: 'British soul singer known for the albums "19" and "21".', a: 'Adele', category: 'music', difficulty: 2 },
    { q: 'American rock band led by Steven Tyler, often called "the bad boys from Boston".', a: 'Aerosmith', category: 'music', difficulty: 2 },
    { q: 'Hard-rock band from Australia known for "Highway to Hell" and "Back in Black".', a: 'AC/DC', category: 'music', difficulty: 2 },
    { q: 'Hip-hop trio whose Grammy-winning album "Speakerboxxx/The Love Below" gave us "Hey Ya!".', a: 'OutKast', category: 'music', difficulty: 2 },
    { q: 'British rock band led by Chris Martin, known for "Yellow" and "Clocks".', a: 'Coldplay', category: 'music', difficulty: 2, alt: ['cold play'] },
    { q: 'American singer born Alecia Moore, famous for acrobatic stage shows and the hit "So What".', a: 'Pink', category: 'music', difficulty: 2, alt: ['p!nk'] },
  ],
  B: [
    { q: 'The Liverpool group of John, Paul, George and Ringo, the most famous band in pop history.', a: 'Beatles', category: 'music', difficulty: 2, alt: ['the beatles'] },
    { q: 'New Jersey rocker behind "Born in the U.S.A.", nicknamed "The Boss".', a: 'Bruce Springsteen', category: 'music', difficulty: 2 },
    { q: 'Pop superstar formerly of Destiny\'s Child, who released the visual album "Lemonade".', a: 'Beyoncé', category: 'music', difficulty: 2, alt: ['beyonce'] },
    { q: 'Canadian pop star discovered on YouTube as a teen, known for "Baby" and "Sorry".', a: 'Justin Bieber', category: 'music', difficulty: 2 },
    { q: 'British rock band fronted by Freddie Mercury who recorded "Don\'t Stop Me Now".', a: 'Queen', category: 'music', difficulty: 2 },
    { q: 'American singer of "...Baby One More Time" who became the princess of pop.', a: 'Britney Spears', category: 'music', difficulty: 2 },
    { q: 'Jamaican reggae icon behind "No Woman, No Cry" and "Redemption Song".', a: 'Bob Marley', category: 'music', difficulty: 2 },
    { q: 'Folk-rock legend born Robert Zimmerman who won the 2016 Nobel Prize in Literature.', a: 'Bob Dylan', category: 'music', difficulty: 2 },
    { q: 'British boy band of the 1990s and 2000s whose members included Gary Barlow and Robbie Williams.', a: 'Take That', category: 'music', difficulty: 2 },
  ],
  C: [
    { q: 'American country and rock star nicknamed "The Man in Black" who recorded at Folsom Prison.', a: 'Johnny Cash', category: 'music', difficulty: 2 },
    { q: 'Colombian singer behind "Hips Don\'t Lie" and the 2010 World Cup anthem "Waka Waka".', a: 'Shakira', category: 'music', difficulty: 2 },
    { q: 'British singer-songwriter of "Someone You Loved", a Scottish star with a self-deprecating wit.', a: 'Lewis Capaldi', category: 'music', difficulty: 2 },
    { q: 'American rapper and singer behind "Old Town Road", a record-breaking chart hit of 2019.', a: 'Lil Nas X', category: 'music', difficulty: 2 },
    { q: 'British band of brothers Liam and Noel Gallagher who released "Wonderwall".', a: 'Oasis', category: 'music', difficulty: 2 },
  ],
  D: [
    { q: 'French electronic duo in robot helmets behind "Get Lucky" and "One More Time".', a: 'Daft Punk', category: 'music', difficulty: 2 },
    { q: 'The Latin-pop hit by Luis Fonsi featuring Daddy Yankee that broke streaming records in 2017.', a: 'Despacito', category: 'music', difficulty: 2 },
    { q: 'British heavy-metal band from Birmingham known for the song "The Trooper" and a zombie mascot named Eddie.', a: 'Iron Maiden', category: 'music', difficulty: 2 },
    { q: 'American singer-rapper behind "Don\'t Start Now" and "Levitating", who revived disco-pop in 2020.', a: 'Dua Lipa', category: 'music', difficulty: 2 },
    { q: 'British synth-pop group from Essex who recorded "Enjoy the Silence" and "Personal Jesus".', a: 'Depeche Mode', category: 'music', difficulty: 2 },
    { q: 'American hip-hop producer and rapper, founder of Beats headphones and a mentor to Eminem.', a: 'Dr. Dre', category: 'music', difficulty: 2, alt: ['dre'] },
  ],
  E: [
    { q: 'American rock band from California behind "Hotel California" and "Take It Easy".', a: 'Eagles', category: 'music', difficulty: 2, alt: ['the eagles'] },
    { q: 'British singer born Reginald Dwight, famous for "Rocket Man" and "Tiny Dancer".', a: 'Elton John', category: 'music', difficulty: 2 },
    { q: 'American rapper born Marshall Mathers behind "Lose Yourself".', a: 'Eminem', category: 'music', difficulty: 2 },
    { q: 'The American rock singer of "Jailhouse Rock", widely called "The King".', a: 'Elvis Presley', category: 'music', difficulty: 2, alt: ['elvis'] },
    { q: 'British band led by Dave Grohl, formed after the death of his Nirvana bandmate.', a: 'Foo Fighters', category: 'music', difficulty: 2 },
  ],
  F: [
    { q: 'American hip-hop and pop group whose hits include "Where Is the Love?" and "I Gotta Feeling".', a: 'Black Eyed Peas', category: 'music', difficulty: 2 },
    { q: 'The frontman of Queen, born Farrokh Bulsara, who sang "Somebody to Love".', a: 'Freddie Mercury', category: 'music', difficulty: 2 },
    { q: 'British-American rock band behind "Go Your Own Way" and the album "Rumours".', a: 'Fleetwood Mac', category: 'music', difficulty: 2 },
    { q: 'The crooner nicknamed "Ol\' Blue Eyes" who sang "My Way" and "New York, New York".', a: 'Frank Sinatra', category: 'music', difficulty: 2 },
  ],
  G: [
    { q: 'American rock band behind "Sweet Child o\' Mine" and "November Rain", fronted by Axl Rose.', a: 'Guns N\' Roses', category: 'music', difficulty: 2, alt: ['guns n roses', 'gnr'] },
    { q: 'American pop singer behind the LGBTQ anthem "Born This Way" and the hit "Bad Romance".', a: 'Lady Gaga', category: 'music', difficulty: 2 },
    { q: 'British rock band of David Gilmour and Roger Waters behind the album "The Dark Side of the Moon".', a: 'Pink Floyd', category: 'music', difficulty: 2 },
  ],
  H: [
    { q: 'The American guitarist who set his instrument on fire at Monterey and recorded "Purple Haze".', a: 'Jimi Hendrix', category: 'music', difficulty: 2 },
    { q: 'British rock band famous for the rock opera "Tommy" and the song "Baba O\'Riley".', a: 'The Who', category: 'music', difficulty: 2 },
    { q: 'British singer of "Easy on Me" and "Rolling in the Deep" who names her albums after her age.', a: 'Adele', category: 'music', difficulty: 2 },
  ],
  I: [
    { q: 'American folk-rock duo behind "The Sound of Silence" and "Bridge over Troubled Water".', a: 'Simon & Garfunkel', category: 'music', difficulty: 2, alt: ['simon and garfunkel'] },
    { q: 'The short opening passage of a song, before the first verse.', a: 'Intro', category: 'music', difficulty: 2 },
  ],
  J: [
    { q: 'The American pop superstar called "The King of Pop", behind the album "Thriller".', a: 'Michael Jackson', category: 'music', difficulty: 2 },
    { q: 'The English rock band of Mick Jagger and Keith Richards, active since the 1960s.', a: 'The Rolling Stones', category: 'music', difficulty: 2, alt: ['rolling stones'] },
    { q: 'Canadian-American singer behind "Call Me Maybe", a viral 2012 pop smash.', a: 'Carly Rae Jepsen', category: 'music', difficulty: 2 },
  ],
  K: [
    { q: 'American singer-songwriter of "Roar" and "Firework" who once kissed a girl and liked it.', a: 'Katy Perry', category: 'music', difficulty: 2 },
    { q: 'American singer-songwriter behind "All I Want for Christmas Is You", a vocalist famed for her range.', a: 'Mariah Carey', category: 'music', difficulty: 2 },
    { q: 'The general name for an electronic instrument played by pressing a row of black and white keys.', a: 'Keyboard', category: 'music', difficulty: 2 },
  ],
  L: [
    { q: 'British rock band of Robert Plant and Jimmy Page behind "Stairway to Heaven".', a: 'Led Zeppelin', category: 'music', difficulty: 2 },
    { q: 'American singer-songwriter behind "Bad Guy" and "Ocean Eyes", who broke through as a teenager.', a: 'Billie Eilish', category: 'music', difficulty: 2 },
    { q: 'American pop singer of "Bad Romance"; her surname means "joke" in Italian, sort of.', a: 'Lady Gaga', category: 'music', difficulty: 2 },
    { q: 'British rock band whose debut album "Definitely Maybe" and "Wonderwall" defined Britpop.', a: 'Oasis', category: 'music', difficulty: 2 },
  ],
  M: [
    { q: 'American pop icon called "The Material Girl", behind "Like a Prayer" and "Vogue".', a: 'Madonna', category: 'music', difficulty: 2 },
    { q: 'American pop-rock band led by Adam Levine behind "Sugar" and "Moves Like Jagger".', a: 'Maroon 5', category: 'music', difficulty: 2 },
    { q: 'American singer behind "Uptown Funk" and "24K Magic", known for slick retro funk.', a: 'Bruno Mars', category: 'music', difficulty: 2 },
    { q: 'British singer-songwriter of "Back to Black", whose beehive hairdo became iconic.', a: 'Amy Winehouse', category: 'music', difficulty: 2 },
    { q: 'A brass wind instrument with a slide used to change pitch.', a: 'Trombone', category: 'music', difficulty: 2 },
  ],
  N: [
    { q: 'American grunge band led by Kurt Cobain behind "Smells Like Teen Spirit".', a: 'Nirvana', category: 'music', difficulty: 2 },
    { q: 'British-Albanian singer behind "Don\'t Start Now"; her first name means "love".', a: 'Dua Lipa', category: 'music', difficulty: 2 },
    { q: 'A genre of dark, fast, lo-fi music with shrieked vocals and corpse paint that emerged from Norway in the early 1990s.', a: 'Black metal', category: 'music', difficulty: 2 },
  ],
  O: [
    { q: 'British rock band of the Gallagher brothers behind the album "(What\'s the Story) Morning Glory?".', a: 'Oasis', category: 'music', difficulty: 2 },
    { q: 'American hip-hop duo of André 3000 and Big Boi behind "Ms. Jackson".', a: 'OutKast', category: 'music', difficulty: 2 },
    { q: 'A large ensemble of strings, brass, woodwinds and percussion led by a conductor.', a: 'Orchestra', category: 'music', difficulty: 2 },
  ],
  P: [
    { q: 'American singer and pianist behind "Piano Man" and "Uptown Girl".', a: 'Billy Joel', category: 'music', difficulty: 2 },
    { q: 'British band of David Gilmour and Roger Waters behind "The Wall".', a: 'Pink Floyd', category: 'music', difficulty: 2 },
    { q: 'American musician born in Minnesota behind "Purple Rain", known for a love of the color purple.', a: 'Prince', category: 'music', difficulty: 2 },
    { q: 'A keyboard instrument with hammered strings, central to classical and jazz music.', a: 'Piano', category: 'music', difficulty: 2 },
  ],
  Q: [
    { q: 'British rock band behind "We Will Rock You" and "Bohemian Rhapsody".', a: 'Queen', category: 'music', difficulty: 2 },
    { q: 'A group of four musicians performing together.', a: 'Quartet', category: 'music', difficulty: 2 },
  ],
  R: [
    { q: 'British singer-songwriter behind "Diamonds" and "Umbrella", born in Barbados.', a: 'Rihanna', category: 'music', difficulty: 2 },
    { q: 'British alternative band led by Thom Yorke behind "Creep" and the album "OK Computer".', a: 'Radiohead', category: 'music', difficulty: 2 },
    { q: 'American funk-rock band from California behind "Californication" and "Under the Bridge".', a: 'Red Hot Chili Peppers', category: 'music', difficulty: 2 },
    { q: 'American pop-soul singer behind "Respect", crowned the "Queen of Soul".', a: 'Aretha Franklin', category: 'music', difficulty: 2 },
    { q: 'British rock band of Mick Jagger behind "Paint It Black" and "Angie".', a: 'The Rolling Stones', category: 'music', difficulty: 2, alt: ['rolling stones'] },
  ],
  S: [
    { q: 'American pop megastar behind "Shake It Off" and the album "1989".', a: 'Taylor Swift', category: 'music', difficulty: 2 },
    { q: 'British singer-songwriter behind "Shape of You" and "Thinking Out Loud", known for a guitar loop pedal.', a: 'Ed Sheeran', category: 'music', difficulty: 2 },
    { q: 'Canadian singer behind "Blinding Lights" and "Starboy".', a: 'The Weeknd', category: 'music', difficulty: 2, alt: ['weeknd'] },
    { q: 'British soul singer behind "Stay With Me", whose debut album was "In the Lonely Hour".', a: 'Sam Smith', category: 'music', difficulty: 2 },
    { q: 'A six-stringed plucked instrument central to rock and folk music.', a: 'Guitar', category: 'music', difficulty: 2 },
  ],
  T: [
    { q: 'American pop singer behind the albums "Red", "Lover" and "Folklore".', a: 'Taylor Swift', category: 'music', difficulty: 2 },
    { q: 'British pop band behind "Greatest Day" and "Patience" who reunited without Robbie Williams.', a: 'Take That', category: 'music', difficulty: 2 },
    { q: 'American singer-songwriter behind "Fire and Rain", a soft-rock voice of the 1970s.', a: 'James Taylor', category: 'music', difficulty: 2 },
    { q: 'A brass wind instrument with three valves and a bright, piercing tone.', a: 'Trumpet', category: 'music', difficulty: 2 },
  ],
  U: [
    { q: 'Irish rock band fronted by Bono behind "With or Without You" and "One".', a: 'U2', category: 'music', difficulty: 2 },
    { q: 'A small four-stringed Hawaiian guitar.', a: 'Ukulele', category: 'music', difficulty: 2 },
  ],
  V: [
    { q: 'A bowed four-stringed instrument, the smallest and highest of the string family.', a: 'Violin', category: 'music', difficulty: 2 },
  ],
  W: [
    { q: 'British boy band of the 1980s behind "Wake Me Up Before You Go-Go", featuring George Michael.', a: 'Wham!', category: 'music', difficulty: 2 },
    { q: 'American singer of "I Will Always Love You", a powerhouse voice of the 1990s.', a: 'Whitney Houston', category: 'music', difficulty: 2 },
  ],
  X: [
    { q: 'A percussion instrument of wooden bars struck with mallets.', a: 'Xylophone', category: 'music', difficulty: 2 },
  ],
  Y: [
    { q: 'A high-pitched Alpine singing style that rapidly switches between chest and head voice.', a: 'Yodeling', category: 'music', difficulty: 2 },
  ],
  Z: [
    { q: 'British glam-rock band of the 1970s behind "Cum On Feel the Noize", famous for misspelled titles.', a: 'Slade', category: 'music', difficulty: 2 },
  ],
  AA: [
    { q: 'American R&B singer behind "Thank U, Next" and "7 rings", a former Nickelodeon star.', a: 'Ariana Grande', category: 'music', difficulty: 2 },
    { q: 'American rock band of the 1980s and 90s behind "Don\'t Stop Believin\'".', a: 'Journey', category: 'music', difficulty: 2 },
    { q: 'British rock band fronted by Sting in the late 1970s and early 80s behind "Roxanne".', a: 'The Police', category: 'music', difficulty: 2, alt: ['police'] },
    { q: 'British soul singer behind "Rehab" and "Valerie" who died at 27.', a: 'Amy Winehouse', category: 'music', difficulty: 2 },
    { q: 'American hip-hop mogul and rapper behind "99 Problems", married to Beyoncé.', a: 'Jay-Z', category: 'music', difficulty: 2, alt: ['jay z'] },
    { q: 'American rapper and entrepreneur, founder of Bad Boy Records, once known as Puff Daddy.', a: 'Diddy', category: 'music', difficulty: 2, alt: ['p diddy', 'sean combs'] },
    { q: 'American country superstar behind "Friends in Low Places", the best-selling solo act in U.S. history.', a: 'Garth Brooks', category: 'music', difficulty: 2 },
    { q: 'American pop-punk band behind "American Idiot" and "Boulevard of Broken Dreams".', a: 'Green Day', category: 'music', difficulty: 2 },
    { q: 'Irish family group of the 1990s behind "When You Say Nothing at All", featuring Ronan Keating.', a: 'Boyzone', category: 'music', difficulty: 2 },
    { q: 'British girl group of the 1990s whose members had nicknames like Posh, Scary and Baby.', a: 'Spice Girls', category: 'music', difficulty: 2 },
    { q: 'American singer behind "Vision of Love" famed for a five-octave range and the whistle register.', a: 'Mariah Carey', category: 'music', difficulty: 2 },
    { q: 'American country crossover star behind "Jolene" and "9 to 5", with a Tennessee theme park.', a: 'Dolly Parton', category: 'music', difficulty: 2 },
    { q: 'American rock band from Seattle behind "Black" and "Alive", fronted by Eddie Vedder.', a: 'Pearl Jam', category: 'music', difficulty: 2 },
    { q: 'British electronic-pop duo behind "West End Girls", a synth act of two men.', a: 'Pet Shop Boys', category: 'music', difficulty: 2 },
    { q: 'American singer behind "Halo" and the album "B\'Day", once part of a 90s girl trio.', a: 'Beyoncé', category: 'music', difficulty: 2, alt: ['beyonce'] },
    { q: 'British rock band behind "Creep" who later went experimental on "Kid A".', a: 'Radiohead', category: 'music', difficulty: 2 },
    { q: 'American singer-songwriter behind "Tangled Up in Blue" and "Like a Rolling Stone".', a: 'Bob Dylan', category: 'music', difficulty: 2 },
    { q: 'American rock band from Las Vegas behind "Mr. Brightside" and "Human".', a: 'The Killers', category: 'music', difficulty: 2, alt: ['killers'] },
    { q: 'American singer behind "Genie in a Bottle" and "Beautiful", a powerhouse of the early 2000s.', a: 'Christina Aguilera', category: 'music', difficulty: 2 },
    { q: 'British acid-jazz and funk band behind "Virtual Insanity", led by the hat-wearing Jay Kay.', a: 'Jamiroquai', category: 'music', difficulty: 2 },
    { q: 'American hip-hop artist behind "In Da Club" and "21 Questions".', a: 'Fifty Cent', category: 'music', difficulty: 2, alt: ['50 cent'] },
    { q: 'American singer behind "Toxic" and "Oops!... I Did It Again".', a: 'Britney Spears', category: 'music', difficulty: 2 },
    { q: 'British band behind "Bitter Sweet Symphony", led by Richard Ashcroft.', a: 'The Verve', category: 'music', difficulty: 2, alt: ['verve'] },
    { q: 'American funk and pop legend behind "Superstition" and "Isn\'t She Lovely", blind since infancy.', a: 'Stevie Wonder', category: 'music', difficulty: 2 },
    { q: 'British singer behind "Faith" and "Careless Whisper" who began in the duo Wham!.', a: 'George Michael', category: 'music', difficulty: 2 },
    { q: 'A vocal piece for a solo singer in an opera, often the dramatic highlight.', a: 'Aria', category: 'music', difficulty: 2 },
    { q: 'A musical performance in front of an audience, often recorded live for an album.', a: 'Concert', category: 'music', difficulty: 2 },
    { q: 'The leader who directs an orchestra with a baton.', a: 'Conductor', category: 'music', difficulty: 2 },
    { q: 'A group of singers performing together, often in a church or school.', a: 'Choir', category: 'music', difficulty: 2 },
    { q: 'The repeated, catchy section of a song between verses.', a: 'Chorus', category: 'music', difficulty: 2 },
    { q: 'The words of a song.', a: 'Lyrics', category: 'music', difficulty: 2 },
    { q: 'A tune that you can hum; the main line of pitches in a song.', a: 'Melody', category: 'music', difficulty: 2 },
    { q: 'The collection of songs released together as one body of work by an artist.', a: 'Album', category: 'music', difficulty: 2 },
    { q: 'A large keyboard instrument with pipes, often found in churches.', a: 'Organ', category: 'music', difficulty: 2 },
    { q: 'A small handheld percussion instrument with metal jingles, shaken or struck.', a: 'Tambourine', category: 'music', difficulty: 2 },
    { q: 'A wind instrument with a long body, finger holes and a high, clear voice — the highest of the woodwinds.', a: 'Flute', category: 'music', difficulty: 2 },
    { q: 'A single-reed woodwind instrument with a warm tone, prominent in jazz and orchestras.', a: 'Clarinet', category: 'music', difficulty: 2 },
    { q: 'A brass instrument curled into a circle with a wide flaring opening, played in marching bands.', a: 'Tuba', category: 'music', difficulty: 2, alt: ['french horn'] },
    { q: 'A large bowed string instrument played upright between the knees, lower than a viola.', a: 'Cello', category: 'music', difficulty: 2 },
    { q: 'The lowest and largest bowed string instrument in the orchestra.', a: 'Double bass', category: 'music', difficulty: 2 },
    { q: 'Canadian poet and singer-songwriter who wrote "Hallelujah" and "Suzanne".', a: 'Leonard Cohen', category: 'music', difficulty: 2 },
    { q: 'American rock band behind "Livin\' on a Prayer", a New Jersey arena act.', a: 'Bon Jovi', category: 'music', difficulty: 2 },
    { q: 'British singer behind "Rolling in the Deep" and the album "25".', a: 'Adele', category: 'music', difficulty: 2 },
    { q: 'A popular Latin American dance and music style of Cuban origin in 4/4 time.', a: 'Salsa', category: 'music', difficulty: 2 },
    { q: 'A genre of electronic dance music with a fast, repetitive beat, born in 1980s Detroit and Chicago.', a: 'Techno', category: 'music', difficulty: 2 },
    { q: 'A style of music with a strong off-beat and Jamaican roots, predecessor to reggae.', a: 'Ska', category: 'music', difficulty: 2 },
    { q: 'A genre of music featuring rapping over beats, born in 1970s New York.', a: 'Hip-hop', category: 'music', difficulty: 2, alt: ['hip hop', 'rap'] },
    { q: 'A four-beat-driven dance genre of electronic music with a steady kick, popular in clubs.', a: 'House', category: 'music', difficulty: 2 },
    { q: 'A genre defined by amplified guitars, drums and rebellious energy, emerging in the 1950s.', a: 'Rock and roll', category: 'music', difficulty: 2, alt: ['rock n roll', "rock 'n' roll"] },
    { q: 'A Brazilian dance and music genre, the heartbeat of Rio\'s Carnival.', a: 'Samba', category: 'music', difficulty: 2 },
  ],
};

export const musicHardExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: 'American jazz saxophonist behind the spiritual masterpiece "A Love Supreme".', a: 'John Coltrane', category: 'music', difficulty: 4 },
    { q: 'A chord whose notes are sounded one after another rather than together, ascending or descending.', a: 'Arpeggio', category: 'music', difficulty: 4 },
    { q: 'The opening dance movement of a Baroque suite, in moderate 4/4 and of German origin.', a: 'Allemande', category: 'music', difficulty: 4 },
    { q: 'A chromatic note foreign to the prevailing key, often spelled with a sharp, flat, or natural sign.', a: 'Accidental', category: 'music', difficulty: 4 },
    { q: 'A gradual quickening of the tempo, the opposite of a ritardando.', a: 'Accelerando', category: 'music', difficulty: 4 },
    { q: 'British prog-rock group behind the suite "Supper\'s Ready" and the album "Foxtrot".', a: 'Genesis', category: 'music', difficulty: 4 },
  ],
  B: [
    { q: 'German composer of the "Brandenburg Concertos" and "The Well-Tempered Clavier".', a: 'Johann Sebastian Bach', category: 'music', difficulty: 4, alt: ['bach', 'j.s. bach'] },
    { q: 'The German composer of nine symphonies who continued writing after going deaf.', a: 'Ludwig van Beethoven', category: 'music', difficulty: 4, alt: ['beethoven'] },
    { q: 'American jazz trumpeter and bandleader behind the modal album "Kind of Blue".', a: 'Miles Davis', category: 'music', difficulty: 4 },
    { q: 'The first scale degree of a key; the foundational note on which a triad is built.', a: 'Tonic', category: 'music', difficulty: 4 },
    { q: 'The lowest male singing voice.', a: 'Bass', category: 'music', difficulty: 4 },
    { q: 'A 12-bar harmonic progression rooted in African-American folk music, foundational to rock and jazz.', a: 'Blues', category: 'music', difficulty: 4 },
  ],
  C: [
    { q: 'Polish-French Romantic composer of nocturnes, études and mazurkas for solo piano.', a: 'Frédéric Chopin', category: 'music', difficulty: 4, alt: ['chopin'] },
    { q: 'A simultaneous sounding of three or more notes; the harmonic building block.', a: 'Chord', category: 'music', difficulty: 4 },
    { q: 'The musical sign at the start of a staff that fixes the pitch of the lines, such as treble or bass.', a: 'Clef', category: 'music', difficulty: 4 },
    { q: 'The technique of overlapping a melody with itself at a fixed delay, as in "Row, Row, Row Your Boat".', a: 'Canon', category: 'music', difficulty: 4 },
    { q: 'American avant-garde composer behind the silent piece "4\'33\\"".', a: 'John Cage', category: 'music', difficulty: 4 },
  ],
  D: [
    { q: 'Czech composer of the "New World" Symphony, written during his stay in America.', a: 'Antonín Dvořák', category: 'music', difficulty: 4, alt: ['dvorak'] },
    { q: 'French Impressionist composer of "Clair de Lune" and "Prélude à l\'après-midi d\'un faune".', a: 'Claude Debussy', category: 'music', difficulty: 4, alt: ['debussy'] },
    { q: 'A loud passage marking in scores, abbreviated "f".', a: 'Forte', category: 'music', difficulty: 4 },
    { q: 'The interval spanning eight notes, where the upper note vibrates at twice the frequency.', a: 'Octave', category: 'music', difficulty: 4 },
    { q: 'An interval of three whole tones, historically nicknamed "the devil in music".', a: 'Tritone', category: 'music', difficulty: 4 },
  ],
  E: [
    { q: 'American jazz pianist, composer and bandleader behind "Take the \'A\' Train" with Billy Strayhorn.', a: 'Duke Ellington', category: 'music', difficulty: 4 },
    { q: 'British ambient pioneer and producer, formerly of Roxy Music, who coined the genre term in the 1970s.', a: 'Brian Eno', category: 'music', difficulty: 4 },
    { q: 'The compositional study or exercise designed to develop a particular technical skill, like Chopin\'s for piano.', a: 'Étude', category: 'music', difficulty: 4, alt: ['etude'] },
  ],
  F: [
    { q: 'Austrian "Father of the Symphony" who mentored Mozart and taught Beethoven.', a: 'Joseph Haydn', category: 'music', difficulty: 4, alt: ['haydn'] },
    { q: 'A polyphonic compositional form built on a theme stated in successive imitative voices, perfected by Bach.', a: 'Fugue', category: 'music', difficulty: 4 },
    { q: 'A soft, breathy singing register above the normal range, used by countertenors and pop singers alike.', a: 'Falsetto', category: 'music', difficulty: 4 },
    { q: 'American jazz-fusion band of Joe Zawinul and Wayne Shorter where bassist Jaco Pastorius redefined his instrument.', a: 'Weather Report', category: 'music', difficulty: 4 },
  ],
  G: [
    { q: 'American composer of "Rhapsody in Blue" who blended jazz with classical concert music.', a: 'George Gershwin', category: 'music', difficulty: 4 },
    { q: 'The monophonic sacred plainsong of the medieval Western Church, named for a 6th-century pope.', a: 'Gregorian chant', category: 'music', difficulty: 4 },
    { q: 'A sliding from one pitch to another, common on trombone and slide guitar.', a: 'Glissando', category: 'music', difficulty: 4 },
  ],
  H: [
    { q: 'German-British Baroque composer of "Messiah" and "Water Music".', a: 'George Frideric Handel', category: 'music', difficulty: 4, alt: ['handel', 'haendel'] },
    { q: 'The combination of simultaneously sounded notes to produce chords and chord progressions.', a: 'Harmony', category: 'music', difficulty: 4 },
    { q: 'A keyboard instrument whose strings are plucked rather than struck, dominant in the Baroque era.', a: 'Harpsichord', category: 'music', difficulty: 4 },
    { q: 'American producer and Wall of Sound creator later convicted of murder, known for "Be My Baby".', a: 'Phil Spector', category: 'music', difficulty: 4 },
  ],
  I: [
    { q: 'A short orchestral passage between sung sections of an opera or a separating piece between acts.', a: 'Interlude', category: 'music', difficulty: 4 },
    { q: 'The act of composing or performing music spontaneously, central to jazz solos.', a: 'Improvisation', category: 'music', difficulty: 4 },
    { q: 'Russian-American composer of "The Rite of Spring", which caused a riot at its 1913 premiere.', a: 'Igor Stravinsky', category: 'music', difficulty: 4, alt: ['stravinsky'] },
  ],
  J: [
    { q: 'The genre born in early-20th-century New Orleans, defined by swing and improvisation.', a: 'Jazz', category: 'music', difficulty: 4 },
    { q: 'American singer-songwriter who died at 27 in 1970; her band was Big Brother and the Holding Company.', a: 'Janis Joplin', category: 'music', difficulty: 4 },
    { q: 'British rock band of the 1970s behind "Aqualung" famous for a flute-playing frontman, Ian Anderson.', a: 'Jethro Tull', category: 'music', difficulty: 4 },
  ],
  K: [
    { q: 'A set of notes forming the tonal basis of a piece, indicated by a signature of sharps or flats.', a: 'Key', category: 'music', difficulty: 4 },
    { q: 'A large hemispherical orchestral drum tuned to a definite pitch, also called timpani.', a: 'Kettledrum', category: 'music', difficulty: 4, alt: ['timpani'] },
  ],
  L: [
    { q: 'Hungarian Romantic composer and virtuoso pianist of the "Hungarian Rhapsodies".', a: 'Franz Liszt', category: 'music', difficulty: 4, alt: ['liszt'] },
    { q: 'A recurring musical theme associated with a character or idea, devised by Wagner for his operas.', a: 'Leitmotif', category: 'music', difficulty: 4, alt: ['leitmotiv'] },
    { q: 'A song-like piece, especially a German art song of the Romantic era such as those by Schubert.', a: 'Lied', category: 'music', difficulty: 4 },
  ],
  M: [
    { q: 'Austrian child prodigy and composer of "The Marriage of Figaro" and a famous Requiem.', a: 'Wolfgang Amadeus Mozart', category: 'music', difficulty: 4, alt: ['mozart'] },
    { q: 'A scale or melodic framework in Indian classical music, the basis for improvisation.', a: 'Raga', category: 'music', difficulty: 4 },
    { q: 'A unit of musical time between two barlines.', a: 'Measure', category: 'music', difficulty: 4, alt: ['bar'] },
    { q: 'The seven-mode system inherited from Greek and church music, including Dorian and Phrygian.', a: 'Modes', category: 'music', difficulty: 4 },
    { q: 'The marking indicating moderate tempo, between andante and allegro.', a: 'Moderato', category: 'music', difficulty: 4 },
  ],
  N: [
    { q: 'A lyrical, dreamy piano piece evoking the night, a form perfected by Chopin.', a: 'Nocturne', category: 'music', difficulty: 4 },
    { q: 'A symbol on the staff representing a single pitch and duration.', a: 'Note', category: 'music', difficulty: 4 },
    { q: 'A sign that cancels a previous sharp or flat, restoring a pitch to its unaltered state.', a: 'Natural', category: 'music', difficulty: 4 },
  ],
  O: [
    { q: 'A staged dramatic work set entirely to music, with arias, recitative and orchestra.', a: 'Opera', category: 'music', difficulty: 4 },
    { q: 'A double-reed woodwind instrument that sounds the tuning A for the orchestra.', a: 'Oboe', category: 'music', difficulty: 4 },
    { q: 'A large-scale sacred work for voices and orchestra without staging, like Handel\'s "Messiah".', a: 'Oratorio', category: 'music', difficulty: 4 },
    { q: 'A persistent repeated musical figure or bass line, the foundation of much electronic and minimalist music.', a: 'Ostinato', category: 'music', difficulty: 4 },
  ],
  P: [
    { q: 'Russian composer of "Peter and the Wolf" and the ballet "Romeo and Juliet".', a: 'Sergei Prokofiev', category: 'music', difficulty: 4, alt: ['prokofiev'] },
    { q: 'A five-note scale common in folk, blues and rock; the black keys of a keyboard form one.', a: 'Pentatonic scale', category: 'music', difficulty: 4 },
    { q: 'A very soft dynamic marking, abbreviated "p".', a: 'Piano', category: 'music', difficulty: 4 },
    { q: 'The rate of vibration that determines how high or low a note sounds.', a: 'Pitch', category: 'music', difficulty: 4 },
    { q: 'Plucking the strings of a bowed instrument with the fingers instead of the bow.', a: 'Pizzicato', category: 'music', difficulty: 4 },
  ],
  Q: [
    { q: 'A note value lasting one beat in common time, drawn with a filled head and a stem.', a: 'Quarter note', category: 'music', difficulty: 4, alt: ['crotchet'] },
    { q: 'A grouping of five notes played in the time of four, an irregular rhythmic figure.', a: 'Quintuplet', category: 'music', difficulty: 4 },
  ],
  R: [
    { q: 'Russian composer and pianist of the famous Piano Concerto No. 2 and "Rhapsody on a Theme of Paganini".', a: 'Sergei Rachmaninoff', category: 'music', difficulty: 4, alt: ['rachmaninoff', 'rachmaninov'] },
    { q: 'Speech-like singing that advances the plot in opera, accompanied sparsely.', a: 'Recitative', category: 'music', difficulty: 4 },
    { q: 'French composer of "Boléro", famed for its single repeating crescendo theme.', a: 'Maurice Ravel', category: 'music', difficulty: 4, alt: ['ravel'] },
    { q: 'A musical pattern of strong and weak beats, the organisation of sound in time.', a: 'Rhythm', category: 'music', difficulty: 4 },
  ],
  S: [
    { q: 'Austrian composer of "Erlkönig" and over 600 art songs, dead at 31.', a: 'Franz Schubert', category: 'music', difficulty: 4, alt: ['schubert'] },
    { q: 'Austrian pioneer of atonality and the twelve-tone technique in the early 20th century.', a: 'Arnold Schoenberg', category: 'music', difficulty: 4, alt: ['schoenberg', 'schönberg'] },
    { q: 'A multi-movement orchestral work, the grandest form of classical instrumental music.', a: 'Symphony', category: 'music', difficulty: 4 },
    { q: 'A rhythmic displacement that stresses the off-beats, central to jazz and ragtime.', a: 'Syncopation', category: 'music', difficulty: 4 },
    { q: 'A run of consecutive notes ascending or descending, like the do-re-mi sequence.', a: 'Scale', category: 'music', difficulty: 4 },
    { q: 'The smallest interval in standard Western tuning, between two adjacent keys.', a: 'Semitone', category: 'music', difficulty: 4, alt: ['half step', 'half-step'] },
  ],
  T: [
    { q: 'Russian Romantic composer of "Swan Lake", "The Nutcracker" and the "1812 Overture".', a: 'Pyotr Ilyich Tchaikovsky', category: 'music', difficulty: 4, alt: ['tchaikovsky'] },
    { q: 'The speed of a piece of music, measured in beats per minute.', a: 'Tempo', category: 'music', difficulty: 4 },
    { q: 'The number of beats per measure and the note value that gets one beat, shown as a fraction.', a: 'Time signature', category: 'music', difficulty: 4 },
    { q: 'The highest male singing voice in the standard choral range.', a: 'Tenor', category: 'music', difficulty: 4 },
    { q: 'A wavering, pulsing variation in pitch used to enrich a sustained note.', a: 'Vibrato', category: 'music', difficulty: 4 },
  ],
  U: [
    { q: 'The interval between two notes of the same pitch, sounding as one.', a: 'Unison', category: 'music', difficulty: 4 },
    { q: 'An anacrusis: one or more notes preceding the first downbeat of a phrase.', a: 'Upbeat', category: 'music', difficulty: 4 },
  ],
  V: [
    { q: 'Italian Baroque composer and violinist of "The Four Seasons".', a: 'Antonio Vivaldi', category: 'music', difficulty: 4, alt: ['vivaldi'] },
    { q: 'German opera composer of the four-part "Ring" cycle, including "Die Walküre".', a: 'Richard Wagner', category: 'music', difficulty: 4, alt: ['wagner'] },
    { q: 'A solo passage near the end of a concerto movement showing off the performer, often improvised.', a: 'Cadenza', category: 'music', difficulty: 4 },
  ],
  W: [
    { q: 'A dance in triple time, popularised in 19th-century Vienna by the Strauss family.', a: 'Waltz', category: 'music', difficulty: 4 },
    { q: 'A wind instrument whose tone is produced by a vibrating reed or an air stream, like the clarinet.', a: 'Woodwind', category: 'music', difficulty: 4 },
    { q: 'British art-rock band of the late 1960s behind "21st Century Schizoid Man", a pioneering progressive group led by Robert Fripp.', a: 'King Crimson', category: 'music', difficulty: 4 },
  ],
  X: [
    { q: 'Iannis Xenakis pioneered this kind of computer-aided composition using probability and mathematical models.', a: 'Stochastic music', category: 'music', difficulty: 4 },
  ],
  Y: [
    { q: 'British-American singer of "Cars", a synth-pioneer who fronted Tubeway Army.', a: 'Gary Numan', category: 'music', difficulty: 4 },
    { q: 'British progressive-rock band behind "Roundabout" and the album "Close to the Edge".', a: 'Yes', category: 'music', difficulty: 4 },
  ],
  Z: [
    { q: 'American experimental rock composer and guitarist behind "Hot Rats" and "Apostrophe (\')".', a: 'Frank Zappa', category: 'music', difficulty: 4 },
    { q: 'A flat stringed instrument of central Europe, played on the lap and famous from "The Third Man" theme.', a: 'Zither', category: 'music', difficulty: 4 },
  ],
  ZZ: [
    { q: 'Hungarian composer and pioneer of ethnomusicology behind "Concerto for Orchestra" and "Bluebeard\'s Castle".', a: 'Béla Bartók', category: 'music', difficulty: 4, alt: ['bartok'] },
    { q: 'German composer and theorist whose "Tristan und Isolde" chord pushed harmony toward atonality.', a: 'Richard Wagner', category: 'music', difficulty: 4, alt: ['wagner'] },
    { q: 'Finnish national composer of "Finlandia" and seven symphonies.', a: 'Jean Sibelius', category: 'music', difficulty: 4, alt: ['sibelius'] },
    { q: 'Russian composer of "Pictures at an Exhibition" and "Night on Bald Mountain", one of "The Five".', a: 'Modest Mussorgsky', category: 'music', difficulty: 4, alt: ['mussorgsky'] },
    { q: 'Italian composer of operas "Tosca", "La Bohème" and "Madama Butterfly".', a: 'Giacomo Puccini', category: 'music', difficulty: 4, alt: ['puccini'] },
    { q: 'Italian opera composer of "Aida", "Rigoletto" and "La Traviata".', a: 'Giuseppe Verdi', category: 'music', difficulty: 4, alt: ['verdi'] },
    { q: 'German Romantic composer of four symphonies and "A German Requiem", often grouped with the great Bs.', a: 'Johannes Brahms', category: 'music', difficulty: 4, alt: ['brahms'] },
    { q: 'American minimalist composer of "Einstein on the Beach" and many film scores including "The Hours".', a: 'Philip Glass', category: 'music', difficulty: 4 },
    { q: 'American jazz bandleader and clarinetist crowned the "King of Swing" in the 1930s.', a: 'Benny Goodman', category: 'music', difficulty: 4 },
    { q: 'American jazz singer nicknamed "Lady Day", famed for "Strange Fruit".', a: 'Billie Holiday', category: 'music', difficulty: 4 },
    { q: 'American jazz vocalist called the "First Lady of Song", known for scat singing.', a: 'Ella Fitzgerald', category: 'music', difficulty: 4 },
    { q: 'American jazz trumpeter and gravel-voiced singer nicknamed "Satchmo".', a: 'Louis Armstrong', category: 'music', difficulty: 4 },
    { q: 'American jazz pianist and composer known for angular tunes like "Round Midnight" and a distinctive hat.', a: 'Thelonious Monk', category: 'music', difficulty: 4 },
    { q: 'American jazz bassist and bandleader behind the album "Ah Um", famed for a fiery temperament.', a: 'Charles Mingus', category: 'music', difficulty: 4 },
    { q: 'American jazz saxophonist nicknamed "Bird", a founder of bebop.', a: 'Charlie Parker', category: 'music', difficulty: 4 },
    { q: 'American jazz pianist of the 1960s trio behind "Sunday at the Village Vanguard", master of impressionistic harmony.', a: 'Bill Evans', category: 'music', difficulty: 4 },
    { q: 'British glam-rock pioneer who created the alter ego Ziggy Stardust.', a: 'David Bowie', category: 'music', difficulty: 4 },
    { q: 'German experimental band of the 1970s, electronic pioneers behind "Autobahn".', a: 'Kraftwerk', category: 'music', difficulty: 4 },
    { q: 'German krautrock band behind the album "Tago Mago", a motorik-rhythm pioneer.', a: 'Can', category: 'music', difficulty: 4 },
    { q: 'British post-punk band behind "Love Will Tear Us Apart", whose singer Ian Curtis died in 1980.', a: 'Joy Division', category: 'music', difficulty: 4 },
    { q: 'British band that rose from the ashes of Joy Division, behind "Blue Monday".', a: 'New Order', category: 'music', difficulty: 4 },
    { q: 'American art-rock group of the 1960s managed by Andy Warhol, fronted by Lou Reed.', a: 'The Velvet Underground', category: 'music', difficulty: 4, alt: ['velvet underground'] },
    { q: 'American singer-songwriter and poet behind "Horses", the "godmother of punk".', a: 'Patti Smith', category: 'music', difficulty: 4 },
    { q: 'American funk pioneer and bandleader nicknamed the "Godfather of Soul".', a: 'James Brown', category: 'music', difficulty: 4 },
    { q: 'Nigerian multi-instrumentalist who pioneered Afrobeat and the song "Zombie".', a: 'Fela Kuti', category: 'music', difficulty: 4 },
    { q: 'Cape Verdean singer called the "Barefoot Diva", famed for the morna style.', a: 'Cesária Évora', category: 'music', difficulty: 4, alt: ['cesaria evora'] },
    { q: 'Brazilian singer and guitarist who co-founded bossa nova, behind "The Girl from Ipanema".', a: 'João Gilberto', category: 'music', difficulty: 4, alt: ['joao gilberto'] },
    { q: 'The compositional technique of writing for an orchestra, deciding which instruments play each line.', a: 'Orchestration', category: 'music', difficulty: 4 },
    { q: 'The lowest-sounding note of a chord, which need not be its root.', a: 'Bass note', category: 'music', difficulty: 4 },
    { q: 'A chord whose lowest note is not the root, named "first" or "second" by which tone sits on the bottom.', a: 'Inversion', category: 'music', difficulty: 4 },
    { q: 'The simultaneous combination of independent melodic lines, perfected by Bach.', a: 'Counterpoint', category: 'music', difficulty: 4 },
    { q: 'The harmonic resolution at the end of a phrase, such as the perfect or plagal type.', a: 'Cadence', category: 'music', difficulty: 4 },
    { q: 'A gradual increase in loudness, marked by a widening hairpin in the score.', a: 'Crescendo', category: 'music', difficulty: 4 },
    { q: 'A gradual decrease in loudness, the opposite of a growing dynamic.', a: 'Diminuendo', category: 'music', difficulty: 4, alt: ['decrescendo'] },
    { q: 'A smooth, connected manner of playing notes without breaks between them.', a: 'Legato', category: 'music', difficulty: 4 },
    { q: 'A short, detached manner of playing notes, marked with dots above the heads.', a: 'Staccato', category: 'music', difficulty: 4 },
    { q: 'A whole-step-and-half-step scale built from seven notes, the basis of Western tonal music.', a: 'Diatonic scale', category: 'music', difficulty: 4 },
    { q: 'A scale using all twelve pitches of the octave in succession.', a: 'Chromatic scale', category: 'music', difficulty: 4 },
    { q: 'A sustained or repeated low note held under changing harmonies, as in bagpipe music.', a: 'Drone', category: 'music', difficulty: 4, alt: ['pedal point'] },
    { q: 'The Italian term for "at ease", a fast and lively tempo marking.', a: 'Allegro', category: 'music', difficulty: 4 },
    { q: 'A very slow, solemn tempo marking, the slowest of the common Italian terms.', a: 'Largo', category: 'music', difficulty: 4 },
    { q: 'The simplest three-note chord, built of a root, a third and a fifth.', a: 'Triad', category: 'music', difficulty: 4 },
    { q: 'The frequency standard to which an orchestra tunes, usually A at 440 hertz.', a: 'Concert pitch', category: 'music', difficulty: 4 },
    { q: 'A standalone instrumental introduction to an opera or ballet, performed before the curtain.', a: 'Overture', category: 'music', difficulty: 4 },
    { q: 'A three-movement work for a soloist and orchestra, the showcase form of the virtuoso.', a: 'Concerto', category: 'music', difficulty: 4 },
    { q: 'A composition for one or two instruments in several movements, like Beethoven\'s "Moonlight".', a: 'Sonata', category: 'music', difficulty: 4 },
    { q: 'A lively Baroque dance in compound time, the energetic finale of many suites.', a: 'Gigue', category: 'music', difficulty: 4, alt: ['jig'] },
    { q: 'The deliberate clipping of a guitar signal into a gritty, saturated tone, central to heavy rock.', a: 'Distortion', category: 'music', difficulty: 4, alt: ['overdrive'] },
    { q: 'An effect that records and replays a phrase to build layers in real time, used by Ed Sheeran live.', a: 'Loop pedal', category: 'music', difficulty: 4, alt: ['looper'] },
    { q: 'The studio technique of layering one recorded part over another, pioneered by Les Paul.', a: 'Multitrack recording', category: 'music', difficulty: 4, alt: ['overdubbing'] },
    { q: 'A wheel beside a synthesizer\'s keys that slides notes smoothly up or down in frequency.', a: 'Pitch bend', category: 'music', difficulty: 4 },
  ],
};
