import type { RawQuestion } from '../core/packs';

// 2000s Pop & Rock — extra questions (no duplicates with music00sPop.ts).
// Strict 2000–2009. Specific named entities; answers verified by year.

export const music00sPopExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: "Christina Aguilera's 2006 lead single from 'Back to Basics' celebrating a one-of-a-kind lover.", a: "Ain't No Other Man", category: '00s' },
    { q: "Vampire Weekend's 2008 single about a punctuation mark and being above caring.", a: 'A-Punk', category: '00s' },
    { q: "Kelly Clarkson's 2002 'American Idol' coronation song, her debut single.", a: 'A Moment Like This', category: '00s' },
    { q: "Interpol's 2004 second album, follow-up to 'Turn On the Bright Lights'.", a: 'Antics', category: '00s' },
    { q: "Vanessa Carlton's 2002 piano-driven single about going great distances for love.", a: 'A Thousand Miles', category: '00s' },
    { q: "Coldplay's 2002 sophomore album featuring 'Clocks' and 'In My Place'.", a: 'A Rush of Blood to the Head', category: '00s' },
  ],
  B: [
    { q: "Amy Winehouse's 2006 retro-soul album that won six Grammys.", a: 'Back to Black', category: '00s' },
    { q: "Carrie Underwood's 2006 single about taking a baseball bat to a cheating man's truck.", a: 'Before He Cheats', category: '00s' },
    { q: "Kelly Clarkson's 2005 single about emotional damage inherited from a parent.", a: 'Because of You', category: '00s' },
    { q: "Kelly Clarkson's 2005 single from 'Breakaway' with a piano-rock chorus about hidden pain.", a: 'Behind These Hazel Eyes', category: '00s' },
    { q: "Linkin Park's 2007 single from 'Minutes to Midnight' with an a cappella opening about war.", a: 'Bleed It Out', category: '00s' },
    { q: "Daniel Powter's 2005 ubiquitous single sympathising with a rough morning.", a: 'Bad Day', category: '00s' },
    { q: "Beyoncé's 2003 single with Sean Paul about a teenage romance, from 'Dangerously in Love'.", a: 'Baby Boy', category: '00s' },
    { q: "Destiny's Child's 2001 hit celebrating curvaceous figures.", a: 'Bootylicious', category: '00s' },
    { q: "Jack Johnson's 2005 single from 'In Between Dreams' about a lazy morning together.", a: 'Banana Pancakes', category: '00s' },
  ],
  C: [
    { q: "Adele's 2008 debut single about pursuing love that may be one-sided.", a: 'Chasing Pavements', category: '00s' },
    { q: "Snow Patrol's 2006 ballad about lying on the grass to talk about the universe.", a: 'Chasing Cars', category: '00s' },
    { q: "Damien Rice's 2003 song from 'O' about an obsessive attraction.", a: 'Cannonball', category: '00s' },
    { q: "Britney Spears's 2008 comeback album with a ringmaster theme.", a: 'Circus', category: '00s' },
    { q: "Gwen Stefani's 2005 single from 'Love. Angel. Music. Baby.' reflecting on a past relationship.", a: 'Cool', category: '00s' },
    { q: "Carrie Underwood's 2009 single about a cheating boyfriend, from 'Play On'.", a: 'Cowboy Casanova', category: '00s' },
    { q: "John Mayer's 2006 third studio album featuring 'Waiting on the World to Change'.", a: 'Continuum', category: '00s' },
  ],
  D: [
    { q: "Beyoncé's 2003 debut solo album whose title track is an ode to obsessive devotion.", a: 'Dangerously in Love', category: '00s' },
    { q: "Beyoncé's 2006 single with Jay-Z sampling 'Stop, Look, Listen (To Your Heart)'.", a: 'Deja Vu', category: '00s' },
    { q: "John Mayer's 2003 single from 'Heavier Things' offering advice on raising girls.", a: 'Daughters', category: '00s' },
    { q: "Florence + the Machine's 2008 single from 'Lungs' urging escape from sorrow.", a: 'Dog Days Are Over', category: '00s' },
    { q: "Norah Jones's 2002 Grammy-winning debut single from 'Come Away with Me'.", a: "Don't Know Why", category: '00s' },
    { q: "Train's 2001 Grammy-winning single about love and astronomy.", a: 'Drops of Jupiter', category: '00s' },
  ],
  E: [
    { q: "Michelle Branch's 2001 single from 'The Spirit Room' about a love that follows you around.", a: 'Everywhere', category: '00s' },
    { q: "Britney Spears's 2004 ballad written about the rush of recurring affection.", a: 'Everytime', category: '00s' },
    { q: "MGMT's 2008 funk-tinged single about an unusual sensory experience.", a: 'Electric Feel', category: '00s' },
    { q: "The White Stripes' 2003 album featuring 'Seven Nation Army'.", a: 'Elephant', category: '00s' },
  ],
  F: [
    { q: "Christina Aguilera's 2002 single from 'Stripped' thanking an ex for making her stronger.", a: 'Fighter', category: '00s' },
    { q: "Modest Mouse's 2004 surprise hit about resilience and drifting on.", a: 'Float On', category: '00s' },
    { q: "Arcade Fire's 2004 acclaimed debut album.", a: 'Funeral', category: '00s' },
    { q: "Bon Iver's 2007 sparse debut album recorded in a Wisconsin cabin.", a: 'For Emma, Forever Ago', category: '00s' },
    { q: "P!nk's 2008 album featuring 'So What' and 'Sober'.", a: 'Funhouse', category: '00s' },
  ],
  G: [
    { q: "All-American Rejects' 2008 break-up single from 'When the World Comes Down'.", a: 'Gives You Hell', category: '00s' },
    { q: "John Mayer's 2006 single from 'Continuum' about wanting to stay grounded.", a: 'Gravity', category: '00s' },
    { q: "Britney Spears's 2007 single from 'Blackout' about being insatiable on the dancefloor.", a: 'Gimme More', category: '00s' },
    { q: "Rihanna's 2007 album that produced 'Umbrella' and 'Shut Up and Drive'.", a: 'Good Girl Gone Bad', category: '00s' },
  ],
  H: [
    { q: "Plain White T's 2007 acoustic single addressed to a long-distance love in New York.", a: 'Hey There Delilah', category: '00s' },
    { q: "Train's 2009 reggae-tinged hit comparing a girl to a Mr. Mister song.", a: 'Hey, Soul Sister', category: '00s', alt: ['Hey Soul Sister'] },
    { q: "Imogen Heap's 2005 a cappella-style single popularised by 'The OC' finale.", a: 'Hide and Seek', category: '00s' },
    { q: "Linkin Park's 2000 debut album that sold over 30 million copies worldwide.", a: 'Hybrid Theory', category: '00s' },
    { q: "Christina Aguilera's 2006 ballad addressed to her late grandfather.", a: 'Hurt', category: '00s' },
    { q: "Maroon 5's 2002 debut single from 'Songs About Jane' about romantic frustration.", a: 'Harder to Breathe', category: '00s' },
    { q: "The Killers' 2008 single from 'Day & Age' about empathy and connection.", a: 'Human', category: '00s' },
    { q: "Lifehouse's 2001 breakthrough single from 'No Name Face'.", a: 'Hanging by a Moment', category: '00s' },
    { q: "No Doubt's 2001 single from 'Rock Steady' with a Caribbean lilt.", a: 'Hey Baby', category: '00s' },
  ],
  I: [
    { q: "Coldplay's 2002 single from 'A Rush of Blood to the Head' about regretful absence.", a: 'In My Place', category: '00s' },
    { q: "Destiny's Child's 2000 chart-topper from the 'Charlie's Angels' soundtrack.", a: 'Independent Women', category: '00s' },
    { q: "Clay Aiken's 2003 debut single from 'Measure of a Man'.", a: 'Invisible', category: '00s' },
    { q: "Paramore's 2009 lead single from 'Brand New Eyes'.", a: 'Ignorance', category: '00s' },
    { q: "The Strokes' 2001 garage-rock debut album that ignited a New York scene revival.", a: 'Is This It', category: '00s' },
    { q: "My Chemical Romance's 2004 breakthrough single from 'Three Cheers for Sweet Revenge'.", a: "I'm Not Okay (I Promise)", category: '00s', alt: ["I'm Not Okay"] },
    { q: "Death Cab for Cutie's 2005 single from 'Plans' about devotion beyond death.", a: 'I Will Follow You into the Dark', category: '00s' },
    { q: "Nelly Furtado's 2000 debut single about freedom and flight.", a: "I'm Like a Bird", category: '00s' },
    { q: "Jason Mraz's 2008 single from 'We Sing. We Dance. We Steal Things.'.", a: "I'm Yours", category: '00s' },
  ],
  J: [
    { q: "Carrie Underwood's 2005 country-crossover hit about a driver praying for divine intervention on an icy road.", a: 'Jesus Take the Wheel', category: '00s' },
    { q: "Justin Timberlake's 2002 solo debut album.", a: 'Justified', category: '00s' },
  ],
  K: [
    { q: "MGMT's 2008 single with the chorus 'control yourself, take only what you need from it'.", a: 'Kids', category: '00s' },
  ],
  L: [
    { q: "Mumford & Sons' 2009 debut single about cowardice and growth.", a: 'Little Lion Man', category: '00s' },
    { q: "The Strokes' 2001 second single channelling Tom Petty's 'American Girl'.", a: 'Last Nite', category: '00s' },
    { q: "Justin Timberlake's 2002 debut solo single produced by The Neptunes.", a: 'Like I Love You', category: '00s' },
    { q: "Sara Bareilles's 2007 single resisting being told what to write.", a: 'Love Song', category: '00s' },
    { q: "Shakira's 2001 English-language crossover album.", a: 'Laundry Service', category: '00s' },
    { q: "Nelly Furtado's 2006 Timbaland-produced album.", a: 'Loose', category: '00s' },
  ],
  M: [
    { q: "Yeah Yeah Yeahs' 2003 indie ballad from 'Fever to Tell' with the line 'wait, they don't love you like I love you'.", a: 'Maps', category: '00s' },
    { q: "Maroon 5's 2010 lead single from 'Hands All Over' begging for forgiveness.", a: 'Misery', category: '00s' },
    { q: "Paramore's 2007 breakthrough single from 'Riot!' about taking a guy from someone else.", a: 'Misery Business', category: '00s' },
    { q: "Kelly Clarkson's 2003 single from 'Thankful' about self-reliance.", a: 'Miss Independent', category: '00s' },
    { q: "Kelly Clarkson's 2009 lead single from 'All I Ever Wanted'.", a: 'My Life Would Suck Without You', category: '00s' },
    { q: "Beyoncé's 2003 single from 'Dangerously in Love' written about a rival's intrusion.", a: 'Me, Myself and I', category: '00s' },
    { q: "Justin Timberlake's 2006 single with T.I. from 'FutureSex/LoveSounds'.", a: 'My Love', category: '00s' },
  ],
  N: [
    { q: "Jordin Sparks's 2008 duet with Chris Brown about emotional suffocation after a breakup.", a: 'No Air', category: '00s' },
    { q: "The Shins' 2003 single popularised by the film 'Garden State'.", a: 'New Slang', category: '00s' },
    { q: "Panic! at the Disco's 2008 single inspired by an early-morning songwriting epiphany.", a: 'Nine in the Afternoon', category: '00s' },
    { q: "Kelly Clarkson's 2007 single from 'My December' refusing reconciliation.", a: 'Never Again', category: '00s' },
    { q: "Beyoncé's 2003 single from 'Dangerously in Love' about embracing one's wild side.", a: 'Naughty Girl', category: '00s' },
  ],
  O: [
    { q: "Yellowcard's 2003 violin-laced single about a childhood street.", a: 'Ocean Avenue', category: '00s' },
    { q: "Vampire Weekend's 2008 single referencing a grammatical punctuation debate.", a: 'Oxford Comma', category: '00s' },
    { q: "MGMT's 2007 debut album whose title hints at futuristic vision.", a: 'Oracular Spectacular', category: '00s' },
    { q: "Linkin Park's 2000 explosive debut single from 'Hybrid Theory'.", a: 'One Step Closer', category: '00s' },
  ],
  P: [
    { q: "Coldplay's 2000 debut album featuring 'Yellow' and 'Trouble'.", a: 'Parachutes', category: '00s' },
    { q: "Linkin Park's 2000 single about secrets bleeding through, from 'Hybrid Theory'.", a: 'Papercut', category: '00s' },
    { q: "Britney Spears's 2008 single from 'Circus' about media scrutiny.", a: 'Piece of Me', category: '00s' },
  ],
  R: [
    { q: "Amy Winehouse's 2006 breakthrough single refusing addiction treatment.", a: 'Rehab', category: '00s' },
    { q: "John Mayer's 2001 debut album featuring 'No Such Thing'.", a: 'Room for Squares', category: '00s' },
    { q: "Rihanna's 2009 lead single from 'Rated R' likening love to a game of chance with bullets.", a: 'Russian Roulette', category: '00s' },
    { q: "Beyoncé's 2006 single from 'B'Day' warning about a domestic ultimatum.", a: 'Ring the Alarm', category: '00s' },
    { q: "Rihanna's 2009 album that included 'Russian Roulette' and 'Hard'.", a: 'Rated R', category: '00s' },
  ],
  S: [
    { q: "Carrie Underwood's 2005 debut album that sold over 8 million copies in the US.", a: 'Some Hearts', category: '00s' },
    { q: "Kings of Leon's 2008 lead single from 'Only by the Night' about combustion.", a: 'Sex on Fire', category: '00s' },
    { q: "Destiny's Child's 2001 anthem about overcoming hardship from the album of the same name.", a: 'Survivor', category: '00s' },
    { q: "The White Stripes' 2003 single with one of rock's most recognisable riffs.", a: 'Seven Nation Army', category: '00s' },
    { q: "Beyoncé's 2009 single from 'I Am... Sasha Fierce' with a euphoric club beat.", a: 'Sweet Dreams', category: '00s' },
    { q: "Linkin Park's 2007 single from 'Minutes to Midnight' about a darkening cityscape.", a: 'Shadow of the Day', category: '00s' },
    { q: "P!nk's 2008 single from 'Funhouse' about feeling clear-headed after a breakup.", a: 'Sober', category: '00s' },
    { q: "OneRepublic's 2008 follow-up single about hesitation and indecision.", a: 'Stop and Stare', category: '00s' },
    { q: "Death Cab for Cutie's 2005 single from 'Plans' about complete attraction.", a: 'Soul Meets Body', category: '00s' },
    { q: "Destiny's Child's 2004 single from 'Destiny Fulfilled' praising men in uniform.", a: 'Soldier', category: '00s' },
  ],
  T: [
    { q: "Death Cab for Cutie's 2003 album whose title evokes a transatlantic journey.", a: 'Transatlanticism', category: '00s' },
    { q: "MGMT's 2008 indie-pop single about youthful escape and rock-star fantasy.", a: 'Time to Pretend', category: '00s' },
    { q: "Jordin Sparks's 2007 single about a love that leaves a permanent mark.", a: 'Tattoo', category: '00s' },
    { q: "Coldplay's 2005 single from 'X&Y' about communication and Kraftwerk-inspired synths.", a: 'Talk', category: '00s' },
    { q: "Gwen Stefani's 2006 second solo album featuring 'Wind It Up'.", a: 'The Sweet Escape', category: '00s' },
    { q: "Coldplay's 2000 single from 'Parachutes' about being in deep emotional difficulty.", a: 'Trouble', category: '00s' },
  ],
  U: [
    { q: "Kings of Leon's 2008 single from 'Only by the Night' about lasting attachment.", a: 'Use Somebody', category: '00s' },
    { q: "Jay-Z's 2006 single from 'Kingdom Come' featuring Beyoncé about elevating a partner.", a: 'Upgrade U', category: '00s' },
  ],
  V: [
    { q: "Mark Ronson's 2007 cover of a Zutons song featuring Amy Winehouse on vocals.", a: 'Valerie', category: '00s' },
  ],
  W: [
    { q: "John Mayer's 2006 single from 'Continuum' lamenting passive observers of injustice.", a: 'Waiting on the World to Change', category: '00s' },
    { q: "Justin Timberlake's 2007 second single from 'FutureSex/LoveSounds' about karma.", a: 'What Goes Around... Comes Around', category: '00s', alt: ['What Goes Around Comes Around'] },
    { q: "Katy Perry's 2009 single from 'One of the Boys' set in a Nevada casino city.", a: 'Waking Up in Vegas', category: '00s' },
    { q: "Arcade Fire's 2004 anthem from 'Funeral' with a famous gang-vocal climax.", a: 'Wake Up', category: '00s' },
    { q: "Gwen Stefani's 2004 lead solo single produced by The Neptunes.", a: 'What You Waiting For?', category: '00s', alt: ['What You Waiting For'] },
  ],
  Y: [
    { q: "Florence + the Machine's 2009 single covering a 1986 gospel-house track.", a: "You've Got the Love", category: '00s' },
    { q: "Amy Winehouse's 2006 single from 'Back to Black' about regretful infidelity.", a: "You Know I'm No Good", category: '00s' },
    { q: "John Mayer's 2002 single from 'Room for Squares' about a lover's physique.", a: 'Your Body Is a Wonderland', category: '00s' },
  ],
};
