import type { RawQuestion } from '../core/packs';

// 90s R&B / soul / new jack swing — EXTRA questions.
// Strictly 1990–1999. Authored to avoid duplicates with music90sRnB.ts.

export const music90sRnBExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: "TLC's 1992 single from 'Ooooooohhh... On the TLC Tip' begging a partner to stop pleading.", a: "Ain't 2 Proud 2 Beg", category: '90s-rnb', alt: ["Aint 2 Proud 2 Beg", "Ain't Too Proud to Beg"] },
    { q: "Boyz II Men's 1997 Diane Warren tribute ballad written for mothers.", a: 'A Song for Mama', category: '90s-rnb' },
    { q: "Mariah Carey's 1994 single from 'Music Box' about always being there when troubles come.", a: 'Anytime You Need a Friend', category: '90s-rnb' },
    { q: "Aaliyah's 1994 R. Kelly-produced ballad covering an Isley Brothers song reassuring a partner at their peak.", a: 'At Your Best (You Are Love)', category: '90s-rnb', alt: ['At Your Best', 'At Your Best You Are Love'] },
    { q: "Monica's 1998 #1 ballad sampling The Commodores about the perfect partner.", a: 'Angel of Mine', category: '90s-rnb' },
    { q: "Tony! Toni! Toné!'s 1993 ballad celebrating love that lasts year after year.", a: 'Anniversary', category: '90s-rnb' },
    { q: "Maxwell's 1996 lead single from his neo-soul debut about rising free of doubt.", a: "Ascension (Don't Ever Wonder)", category: '90s-rnb', alt: ['Ascension', 'Ascension Dont Ever Wonder'] },
    { q: "Aaliyah's R. Kelly-produced 1994 debut LP whose title insists that age is just a number.", a: "Age Ain't Nothing but a Number", category: '90s-rnb', alt: ["Age Aint Nothing but a Number"] },
  ],
  B: [
    { q: "Aaliyah's 1994 debut single from 'Age Ain't Nothing but a Number', a swaying groove produced by R. Kelly.", a: 'Back & Forth', category: '90s-rnb', alt: ['Back and Forth'] },
    { q: "Mary J. Blige's 1994 single from 'My Life' urging a partner to find joy.", a: 'Be Happy', category: '90s-rnb' },
    { q: "Brandy's 1994 third single from her debut about a closest companion.", a: 'Best Friend', category: '90s-rnb' },
    { q: "Bell Biv DeVoe's 1990 third single from 'Poison', named with the trio's initials.", a: 'BBD (I Thought It Was Me)', category: '90s-rnb', alt: ['BBD', 'BBD I Thought It Was Me'] },
    { q: "D'Angelo's 1995 debut album that helped launch the neo-soul movement.", a: 'Brown Sugar', category: '90s-rnb' },
    { q: "Erykah Badu's 1997 debut album whose title fuses her name with a philosophy.", a: 'Baduizm', category: '90s-rnb' },
    { q: "Songwriter-singer Kandi who co-wrote TLC's 'No Scrubs' as a member of Xscape.", a: 'Burruss', category: '90s-rnb', alt: ['Kandi Burruss', 'Kandi'] },
  ],
  C: [
    { q: "Mariah Carey's 1991 #1 from 'Emotions' about being unable to release a lover.", a: "Can't Let Go", category: '90s-rnb', alt: ['Cant Let Go'] },
    { q: "Jodeci's 1992 single from 'Forever My Lady' inviting a lover to converse.", a: 'Come and Talk to Me', category: '90s-rnb' },
    { q: "Jodeci's 1993 ballad from 'Diary of a Mad Band' about weeping over heartache.", a: 'Cry for You', category: '90s-rnb' },
    { q: "Total's 1995 Puff Daddy-produced debut single asking if a lover is paying attention.", a: "Can't You See", category: '90s-rnb', alt: ['Cant You See'] },
    { q: "Brandy's character role in the 1997 Wonderful World of Disney TV movie alongside Whitney Houston.", a: 'Cinderella', category: '90s-rnb' },
    { q: "After 7's 1990 follow-up single from their self-titled debut, a relentless soul groove.", a: "Can't Stop", category: '90s-rnb', alt: ['Cant Stop'] },
  ],
  D: [
    { q: "TLC's 1995 single from 'CrazySexyCool' about being fascinated by an attractive person.", a: "Diggin' on You", category: '90s-rnb', alt: ['Diggin on You', 'Digging on You'] },
    { q: "R. Kelly's 1995 single from his self-titled album about keeping an affair a secret.", a: 'Down Low (Nobody Has to Know)', category: '90s-rnb', alt: ['Down Low', 'Down Low Nobody Has to Know'] },
    { q: "Bell Biv DeVoe's 1990 follow-up to 'Poison' with a sexually charged hook.", a: 'Do Me!', category: '90s-rnb', alt: ['Do Me'] },
  ],
  E: [
    { q: "Lauryn Hill's 1998 single from 'Miseducation' about love as a complication.", a: 'Ex-Factor', category: '90s-rnb', alt: ['Ex Factor', 'ExFactor'] },
    { q: "Maxwell's 1998 sophomore studio LP that experimented with a more ambient sound.", a: 'Embrya', category: '90s-rnb' },
    { q: "Boyz II Men's 1997 studio album that produced '4 Seasons of Loneliness'.", a: 'Evolution', category: '90s-rnb' },
    { q: "Mary J. Blige's 1997 single from 'Share My World' interpolating a 1971 Stylistics classic about a beloved being all to her.", a: 'Everything', category: '90s-rnb' },
  ],
  F: [
    { q: "Jodeci's 1993 single from 'Diary of a Mad Band' about an obsessive craving for love.", a: "Feenin'", category: '90s-rnb', alt: ['Feenin', 'Feening'] },
    { q: "Jodeci's 1991 debut album that announced their Uptown Records arrival.", a: 'Forever My Lady', category: '90s-rnb' },
    { q: "Tony! Toni! Toné!'s 1990 hit from 'The Revival' celebrating a great moment together.", a: 'Feels Good', category: '90s-rnb' },
    { q: "Adina Howard's 1995 sexually frank breakthrough single.", a: 'Freak Like Me', category: '90s-rnb' },
    { q: "Silk's 1993 #1 single from their debut album about an intimate request.", a: 'Freak Me', category: '90s-rnb' },
    { q: "En Vogue's 1992 sophomore album titled for their feminine power.", a: 'Funky Divas', category: '90s-rnb' },
    { q: "TLC's 1999 album that produced 'No Scrubs' and 'Unpretty'.", a: 'FanMail', category: '90s-rnb' },
  ],
  G: [
    { q: "R. Kelly's 1997 ballad from the 'Batman & Robin' soundtrack.", a: 'Gotham City', category: '90s-rnb' },
    { q: "Changing Faces's 1997 R. Kelly-produced single whose title is an acronym demanding someone leave.", a: 'G.H.E.T.T.O.U.T.', category: '90s-rnb', alt: ['GHETTOUT', 'Ghettout', 'G H E T T O U T'] },
  ],
  H: [
    { q: "TLC's 1992 second single from their debut about a partner's place behind them.", a: 'Hat 2 da Back', category: '90s-rnb', alt: ['Hat 2 Da Back', 'Hat to da Back', 'Hat to the Back'] },
    { q: "Whitney Houston's 1998 single from 'My Love Is Your Love' featuring Faith Evans and Kelly Price.", a: 'Heartbreak Hotel', category: '90s-rnb' },
    { q: "Az Yet's 1997 single, a remake of a Chicago ballad featuring Peter Cetera.", a: "Hard to Say I'm Sorry", category: '90s-rnb', alt: ["Hard to Say Im Sorry"] },
    { q: "New Edition's 1996 reunion single from the 'Home Again' album.", a: 'Hit Me Off', category: '90s-rnb' },
    { q: "Mokenstef's 1995 single about an ex who already belongs to the singer.", a: "He's Mine", category: '90s-rnb', alt: ["Hes Mine"] },
    { q: "Toni Braxton's 1994 single from her debut counting the things she adores about her partner.", a: 'How Many Ways', category: '90s-rnb' },
    { q: "New Edition's 1996 reunion studio album.", a: 'Home Again', category: '90s-rnb' },
    { q: "Aaliyah's 1996 single produced by Timbaland with a fiery one-line title.", a: 'Hot Like Fire', category: '90s-rnb' },
    { q: "R. Kelly's 1998 single from his self-titled album about a partial commitment.", a: 'Half on a Baby', category: '90s-rnb' },
  ],
  I: [
    { q: "Whitney Houston's 1992 'Bodyguard' soundtrack single, a Chaka Khan cover-style anthem.", a: "I'm Every Woman", category: '90s-rnb', alt: ['Im Every Woman'] },
    { q: "Whitney Houston's 1992 ballad from 'The Bodyguard' that immediately preceded 'I Will Always Love You' at #4.", a: 'I Have Nothing', category: '90s-rnb' },
    { q: "Whitney Houston's 1998 single from 'My Love Is Your Love' about leaving a controlling lover.", a: "It's Not Right but It's Okay", category: '90s-rnb', alt: ["Its Not Right but Its Okay"] },
    { q: "Mariah Carey's 1998 single from the 'Prince of Egypt' soundtrack with Whitney Houston.", a: 'I Still Believe', category: '90s-rnb' },
    { q: "Color Me Badd's 1991 #1 ballad sung partly in Spanish about adoring a love.", a: 'I Adore Mi Amor', category: '90s-rnb' },
    { q: "All-4-One's 1994 #1 cover of a John Michael Montgomery country ballad.", a: 'I Swear', category: '90s-rnb' },
    { q: "All-4-One's 1995 follow-up single about loving in a particular way.", a: 'I Can Love You Like That', category: '90s-rnb' },
    { q: "Shai's 1992 a cappella hit, a delicate ballad about hesitating to confess feelings.", a: 'If I Ever Fall in Love', category: '90s-rnb' },
    { q: "Color Me Badd's 1991 debut single from 'New Jack City' with an explicit proposition.", a: 'I Wanna Sex You Up', category: '90s-rnb' },
    { q: "Dru Hill's 1996 sultry single from their debut about an illicit affair.", a: 'In My Bed', category: '90s-rnb' },
    { q: "Tony! Toni! Toné!'s 1993 hit imagining freedom from financial worry.", a: 'If I Had No Loot', category: '90s-rnb' },
    { q: "Faith Evans and Puff Daddy's 1997 #1 tribute to The Notorious B.I.G. sampling The Police.", a: "I'll Be Missing You", category: '90s-rnb', alt: ['Ill Be Missing You'] },
    { q: "R. Kelly and Celine Dion's 1998 #1 Christmas ballad from 'R.'", a: "I'm Your Angel", category: '90s-rnb', alt: ['Im Your Angel'] },
    { q: "Mary J. Blige's 1997 single from 'Share My World' featuring K-Ci of Jodeci.", a: 'I Can Love You', category: '90s-rnb' },
    { q: "Boyz II Men's 1994 sophomore studio album numbered with Roman numerals.", a: 'II', category: '90s-rnb', alt: ['Two'] },
  ],
  J: [
    { q: "Jodeci member Cedric 'K-Ci' Hailey's brother and duet partner.", a: 'JoJo', category: '90s-rnb', alt: ['Joel Hailey'] },
  ],
  L: [
    { q: "Jodeci's 1993 ballad from 'Diary of a Mad Band' about apologizing for recent behavior.", a: 'Lately', category: '90s-rnb' },
    { q: "D'Angelo's 1995 second single from 'Brown Sugar' addressed to a partner.", a: 'Lady', category: '90s-rnb' },
    { q: "Lauryn Hill's 1998 'Miseducation' track confronting people corrupted by success.", a: 'Lost Ones', category: '90s-rnb' },
    { q: "Az Yet's 1996 LaFace debut single, a slow-jam Babyface ballad about regret.", a: 'Last Night', category: '90s-rnb' },
  ],
  M: [
    { q: "Mariah Carey's 1991 single from 'Emotions' encouraging perseverance.", a: 'Make It Happen', category: '90s-rnb' },
    { q: "Whitney Houston's 1998 fourth studio album featuring 'Heartbreak Hotel' and 'It's Not Right but It's Okay'.", a: 'My Love Is Your Love', category: '90s-rnb' },
    { q: "Monica's 1995 debut album whose title playfully refers to a stylish woman.", a: 'Miss Thang', category: '90s-rnb' },
    { q: "Xscape's 1998 ballad duet with Brandy and Tamia from 'Traces of My Lipstick'.", a: 'My Little Secret', category: '90s-rnb' },
    { q: "The Queen of Hip-Hop Soul's 1999 self-titled fourth studio album.", a: 'Mary', category: '90s-rnb' },
  ],
  N: [
    { q: "Brandy's 1998 sophomore album featuring 'The Boy Is Mine' and 'Have You Ever?'.", a: 'Never Say Never', category: '90s-rnb' },
    { q: "Dru Hill's 1997 single from 'Enter the Dru' about commitment hesitation.", a: 'Never Make a Promise', category: '90s-rnb' },
    { q: "Mary J. Blige's 1996 ballad from the 'Waiting to Exhale' soundtrack about staying composed.", a: 'Not Gon Cry', category: '90s-rnb', alt: ['Not Gon\' Cry', 'Not Gonna Cry'] },
    { q: "Tony Rich Project's 1995 Babyface-produced single about heartache no one else understands.", a: 'Nobody Knows', category: '90s-rnb' },
  ],
  O: [
    { q: "Erykah Badu's 1997 debut single from 'Baduizm' with a flowing pentatonic hook.", a: 'On & On', category: '90s-rnb', alt: ['On and On'] },
    { q: "112's 1996 debut single, a slow-jam ballad about an exclusive love.", a: 'Only You', category: '90s-rnb' },
    { q: "Erykah Badu's 1997 single from 'Baduizm' about a man with a second relationship.", a: 'Otherside of the Game', category: '90s-rnb' },
    { q: "Mariah Carey's 1995 #1 with Boyz II Men dedicated to a lost loved one.", a: 'One Sweet Day', category: '90s-rnb' },
  ],
  P: [
    { q: "Mint Condition's 1991 debut single about a captivating gaze.", a: 'Pretty Brown Eyes', category: '90s-rnb', alt: ["Breakin' My Heart (Pretty Brown Eyes)", "Breakin My Heart"] },
    { q: "Quartet whose 1992 ballad 'Here We Go Again' charted from their self-titled debut.", a: 'Portrait', category: '90s-rnb' },
  ],
  Q: [
    { q: "Whitney Houston's 1992 'Bodyguard' track describing a powerful woman after dark.", a: 'Queen of the Night', category: '90s-rnb' },
  ],
  R: [
    { q: "TLC's 1995 single from 'CrazySexyCool' about an explicit sensual signal.", a: 'Red Light Special', category: '90s-rnb' },
    { q: "Whitney Houston's 1992 'Bodyguard' ballad about escaping to a lover's arms.", a: 'Run to You', category: '90s-rnb' },
    { q: "After 7's 1990 debut single asking if a lover is prepared.", a: 'Ready or Not', category: '90s-rnb' },
    { q: "SWV's 1997 ballad from 'Release Some Tension' likening passion to a downpour.", a: 'Rain', category: '90s-rnb' },
  ],
  S: [
    { q: "Toni Braxton's 1996 third studio album that produced 'Un-Break My Heart'.", a: 'Secrets', category: '90s-rnb' },
    { q: "Jodeci's 1991 second single from 'Forever My Lady' begging a partner not to leave.", a: 'Stay', category: '90s-rnb' },
    { q: "Changing Faces's 1994 R. Kelly-penned debut single with a slow-jam come-on.", a: 'Stroke You Up', category: '90s-rnb' },
    { q: "All-4-One's 1994 debut single, a cover of a 1963 Tymes ballad.", a: 'So Much in Love', category: '90s-rnb' },
    { q: "Total's 1998 single about waiting alone for an absent lover.", a: "Sittin' Home", category: '90s-rnb', alt: ['Sittin Home', 'Sitting Home'] },
    { q: "Changing Faces's 1997 follow-up single about being in matching rhythm with a lover.", a: 'Same Tempo', category: '90s-rnb' },
  ],
  T: [
    { q: "Next's 1998 #1 single about a dance partner pressing in.", a: 'Too Close', category: '90s-rnb' },
    { q: "Brandy's 1998 single from 'Never Say Never' about feeling exhilarated in love.", a: 'Top of the World', category: '90s-rnb' },
    { q: "Dru Hill's 1996 ballad asking a lover to confide everything.", a: 'Tell Me', category: '90s-rnb' },
    { q: "Erykah Badu's 1997 live single about telling a man's friend off — first name Eephus.", a: 'Tyrone', category: '90s-rnb' },
    { q: "Lauryn Hill's 1998 ballad from 'Miseducation' dedicated to her newborn son.", a: 'To Zion', category: '90s-rnb' },
    { q: "Xscape's 1998 ballad from 'Traces of My Lipstick' covering Adore-style devotion.", a: 'The Arms of the One Who Loves You', category: '90s-rnb' },
  ],
  U: [
    { q: "TLC's 1999 #1 ballad about not letting beauty standards define you.", a: 'Unpretty', category: '90s-rnb' },
    { q: "Maxwell's 1996 debut studio album, a continuous neo-soul song cycle set in the city.", a: 'Urban Hang Suite', category: '90s-rnb' },
    { q: "Brandy's 1998 single from 'Never Say Never' about hidden depths.", a: "U Don't Know Me", category: '90s-rnb', alt: ['U Dont Know Me', 'You Dont Know Me', "You Don't Know Me"] },
  ],
  W: [
    { q: "Boyz II Men's 1995 single from 'II' likening lost love to evaporated streams.", a: 'Water Runs Dry', category: '90s-rnb' },
    { q: "TLC's 1992 single from their debut questioning a partner's loyal inner circle.", a: 'What About Your Friends', category: '90s-rnb' },
    { q: "Mariah Carey and Whitney Houston's 1998 #15 duet from 'The Prince of Egypt'.", a: 'When You Believe', category: '90s-rnb' },
    { q: "Monica's 1995 second single from 'Miss Thang' about intense affection.", a: 'Why I Love You So Much', category: '90s-rnb' },
    { q: "Xscape's 1995 cover of The Jones Girls about searching for shelter.", a: 'Who Can I Run To', category: '90s-rnb' },
    { q: "Tony! Toni! Toné!'s 1990 debut single from 'The Revival' offering to please.", a: 'Whatever You Want', category: '90s-rnb' },
    { q: "Mint Condition's 1996 single from 'Definition of a Band' about meeting expectations.", a: 'What Kind of Man Would I Be', category: '90s-rnb' },
    { q: "Total's 1996 single pleading from the side of a love triangle.", a: 'What About Us', category: '90s-rnb' },
  ],
  Y: [
    { q: "Mary J. Blige's 1992 debut single from 'What's the 411?' built on a Patrice Rushen sample.", a: 'You Remind Me', category: '90s-rnb' },
    { q: "SWV's 1996 single from 'New Beginning' about a specific irreplaceable partner.", a: "You're the One", category: '90s-rnb', alt: ['Youre the One', 'You Are the One'] },
    { q: "Toni Braxton's 1994 single from her debut about everything a love means.", a: 'You Mean the World to Me', category: '90s-rnb' },
    { q: "Mint Condition's 1996 ballad from 'Definition of a Band' about reassurance after pain.", a: "You Don't Have to Hurt No More", category: '90s-rnb', alt: ["You Dont Have to Hurt No More"] },
    { q: "Faith Evans's 1995 debut solo single from her self-titled album.", a: 'You Used to Love Me', category: '90s-rnb', alt: ['You Used To Love Me'] },
  ],
};
