import type { RawQuestion } from '../core/packs';

// Additional 1990s hip-hop questions. Grouped here by the first letter of the
// answer for readability; `rebucketByAnswer` in index.ts re-files every question
// by its answer's true first letter at load time, so the grouping is purely a
// human aid.
export const music90sHipHopExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: '1996 Nas Mafioso-rap posse cut from "It Was Written" featuring AZ, Foxy Brown and Cormega — title sounds like a government policy.', a: 'Affirmative Action', category: 'music' },
    { q: 'Brooklyn-bred rapper born Anthony Cruz — Nas\'s Firm partner whose 1995 debut was "Doe or Die".', a: 'AZ', category: 'music' },
    { q: '1996 Tha Dogg Pound-featuring 2Pac track from "All Eyez on Me" — title is a sweeping declaration of feelings for a woman.', a: 'All About U', category: 'music', alt: ['All About You'] },
    { q: 'M.O.P.\'s 1998 brawler anthem demanding you raise your fists.', a: 'Ante Up', category: 'music' },
    { q: 'L.A. drinking trio of Tash, J-Ro and E-Swift whose 1993 debut "21 & Over" launched their party-rap career.', a: 'Tha Alkaholiks', category: 'music', alt: ['Alkaholiks', 'Liks'] },
  ],
  B: [
    { q: '1991 2Pac debut single from "2Pacalypse Now" about a teenage girl forced into the streets.', a: 'Brenda\'s Got a Baby', category: 'music', alt: ['Brendas Got a Baby'] },
    { q: 'Harlem MC born Lamont Coleman who died young — 1995\'s "Lifestylez ov da Poor & Dangerous" is his only studio LP.', a: 'Big L', category: 'music' },
    { q: 'Brooklyn group of Buckshot, 5ft and DJ Evil Dee — 1993\'s "Enta da Stage" is a Boot Camp Clik cornerstone.', a: 'Black Moon', category: 'music' },
    { q: 'New York collective of Grand Puba, Sadat X and Lord Jamar — 1990\'s "One for All".', a: 'Brand Nubian', category: 'music' },
    { q: 'Bronx-born Cypress Hill rapper Louis Freese — the Latino half of the group with Sen Dog.', a: 'B-Real', category: 'music' },
    { q: 'Memphis duo of Premro Smith and Marlon Goodwin who dropped 1993\'s "Comin\' Out Hard".', a: '8Ball & MJG', category: 'music', alt: ['8Ball and MJG', '8Ball'] },
    { q: 'KRS-One\'s seminal Bronx group — "By All Means Necessary" 1988, active into the early 90s.', a: 'Boogie Down Productions', category: 'music', alt: ['BDP'] },
    { q: 'Latin rap trio from Queens — "Reign of the Tec" 1994, "Watch Out Now" 1999, named after a snack.', a: 'Beatnuts', category: 'music', alt: ['The Beatnuts'] },
    { q: 'Bomb Squad-produced group fronted by Chuck D — "Fear of a Black Planet" 1990, "Apocalypse 91" 1991.', a: 'Public Enemy', category: 'music' },
    { q: 'Notorious B.I.G.\'s "Ready to Die" track laying down a stern caution to rivals — "I told you these niggas…".', a: 'Warning', category: 'music' },
  ],
  C: [
    { q: '1998 Jay-Z single with Ja Rule and Amil — its title is a beggar\'s question.', a: 'Can I Get A...', category: 'music', alt: ['Can I Get A'] },
    { q: 'New Orleans rapper born Corey Miller — Master P\'s brother, the "Down for My N\'s" emcee.', a: 'C-Murder', category: 'music' },
    { q: '1994 Common Sense album whose lead single "I Used to Love H.E.R." personifies the genre as a woman.', a: 'Resurrection', category: 'music' },
    { q: 'Queens duo behind 1997\'s "The War Report" — known by an acronym (CNN).', a: 'Capone-N-Noreaga', category: 'music', alt: ['CNN', 'Capone N Noreaga'] },
    { q: 'Chicago Midwest crew behind 1996\'s "Hay" — name hints at urgent inner-city tension.', a: 'Crucial Conflict', category: 'music' },
    { q: 'Goodie Mob\'s soulful frontman born Thomas Callaway — Atlanta solo veteran before forming Gnarls Barkley.', a: 'Cee-Lo', category: 'music', alt: ['CeeLo', 'CeeLo Green'] },
    { q: 'Chicago rapper born Lonnie Lynn — author of 1994\'s "Resurrection".', a: 'Common', category: 'music', alt: ['Common Sense'] },
  ],
  D: [
    { q: 'Compton producer/rapper born David Blake whose 1991 Profile Records debut set his template.', a: 'DJ Quik', category: 'music' },
    { q: 'Brooklyn producer born Christopher Martin — Gang Starr\'s legendary beatmaker.', a: 'DJ Premier', category: 'music', alt: ['Premier', 'Preemo'] },
    { q: 'Chicago female rapper born Shawntae Harris whose 1994 platinum debut was "Funkdafied".', a: 'Da Brat', category: 'music' },
    { q: 'Gang Starr\'s 1992 album that defined the duo\'s jazz-tinged boom-bap. (Two words.)', a: 'Daily Operation', category: 'music' },
    { q: 'Bronx producer/MC from D.I.T.C. — beatmaker on Big L and Fat Joe records.', a: 'Diamond D', category: 'music' },
    { q: 'Chicago duo of AK and Belo with 1996\'s pimp-themed crossover smash "Po Pimp".', a: 'Do or Die', category: 'music' },
    { q: 'Bronx producer/MC born Robert Hall — D.I.T.C. founder credited with discovering Big L.', a: 'Lord Finesse', category: 'music' },
  ],
  E: [
    { q: 'N.W.A founding member born Eric Wright whose 1993 EP hosted "Real Muthaphuckkin G\'s".', a: 'Eazy-E', category: 'music', alt: ['Eazy E'] },
    { q: 'Long Island duo of Erick Sermon and Parrish Smith — "Strictly Business" originators who reunited on 1997\'s "Back in Business".', a: 'EPMD', category: 'music' },
    { q: 'Vallejo rapper born Earl Stevens — Bay Area kingpin behind "Captain Save a Hoe" 1994 and "Sprinkle Me" 1995.', a: 'E-40', category: 'music', alt: ['E40'] },
    { q: 'Brooklyn producer who shaped Biggie\'s sound and crafted "Flava in Ya Ear" for Craig Mack.', a: 'Easy Mo Bee', category: 'music' },
    { q: 'Philadelphia rapper born Eve Jihan Jeffers — Ruff Ryders\' First Lady whose 1999 debut topped the chart.', a: 'Eve', category: 'music' },
  ],
  F: [
    { q: 'Brooklyn female rapper born Inga Marchand whose 1996 debut album was "Ill Na Na".', a: 'Foxy Brown', category: 'music' },
    { q: 'Nas-led 1997 Mafioso-rap supergroup with AZ, Foxy Brown and Cormega — its lone LP was self-titled (with "The" prefix).', a: 'The Firm', category: 'music', alt: ['Firm'] },
  ],
  G: [
    { q: 'Brooklyn duo of DJ Premier and Guru whose 1989 debut "No More Mr. Nice Guy" launched a jazz-rap dynasty.', a: 'Gang Starr', category: 'music' },
    { q: 'Houston trio of Scarface, Willie D and Bushwick Bill — 1991\'s "Mind Playing Tricks on Me".', a: 'Geto Boys', category: 'music' },
    { q: 'Brooklyn duo of Lil Dap and Melachi the Nutcracker — Gang Starr Foundation members, "Livin\' Proof" 1995.', a: 'Group Home', category: 'music' },
    { q: 'Pete Rock & CL Smooth\'s 1992 elegy for Trouble T-Roy — its title acronym means "They Reminisce Over You".', a: 'T.R.O.Y.', category: 'music', alt: ['TROY', 'They Reminisce Over You'] },
  ],
  H: [
    { q: 'Jay-Z\'s 1998 commercial breakthrough sampling "Annie" — its chorus quotes the Broadway orphan anthem.', a: 'Hard Knock Life', category: 'music', alt: ['Hard Knock Life (Ghetto Anthem)'] },
    { q: '1999 Nas single with Diddy from "I Am..." — its title is a defiant taunt to the rapper\'s critics.', a: 'Hate Me Now', category: 'music' },
    { q: '2Pac\'s 1993 single from "Strictly 4 My N.I.G.G.A.Z." encouraging respect for women, especially single mothers.', a: 'Keep Ya Head Up', category: 'music', alt: ['Keep Your Head Up'] },
    { q: 'Boston-born female MC who debuted on KRS-One\'s "Edutainment" — "All Glocks Down" 1995.', a: 'Heather B', category: 'music' },
    { q: '2Pac\'s "All Eyez on Me" track with Dr. Dre — title plays on a Pacino film.', a: 'Heartz of Men', category: 'music' },
    { q: '1996 2Pac & K-Ci & JoJo collab — its title asks a romantic question.', a: 'How Do U Want It', category: 'music', alt: ['How Do You Want It'] },
    { q: 'Brooklyn duo of Rock and Ruck (Sean Price) — 1996\'s "Nocturnal", part of Boot Camp Clik.', a: 'Heltah Skeltah', category: 'music' },
    { q: '1992 House of Pain anthem produced by DJ Muggs — "Pack it up, pack it in, let me begin".', a: 'Jump Around', category: 'music' },
  ],
  I: [
    { q: 'Mobb Deep\'s 1995 second LP, the Queensbridge duo\'s classic featuring "Shook Ones".', a: 'The Infamous', category: 'music', alt: ['Infamous'] },
    { q: '1993 2Pac single from "Strictly 4 My N.I.G.G.A.Z." — a flirtatious anthem about juggling many women in different cities.', a: 'I Get Around', category: 'music' },
    { q: '1996 Nas single with Lauryn Hill sampling Kurtis Blow — its title supposes a hypothetical sovereign.', a: 'If I Ruled the World (Imagine That)', category: 'music', alt: ['If I Ruled the World'] },
    { q: 'Compton rapper born Aaron Tyler — "Streiht Up Menace" 1993 from the "Menace II Society" soundtrack.', a: 'MC Eiht', category: 'music' },
    { q: 'Ghostface Killah\'s 1996 Wu solo debut — title invokes a Marvel hero.', a: 'Ironman', category: 'music' },
    { q: 'Jay-Z\'s 1997 sophomore Roc-A-Fella record, numbered the first in the series of Volumes that followed his debut.', a: 'In My Lifetime, Vol. 1', category: 'music', alt: ['In My Lifetime Vol 1'] },
  ],
  J: [
    { q: 'Detroit producer also known as J Dilla — Slum Village beatmaker on 1998\'s "Fan-Tas-Tic Vol. 1". (His earlier "J___ ___" stage name.)', a: 'Jay Dee', category: 'music' },
    { q: 'Brooklyn rapper born Kendrick Davis — DJ Premier protégé whose 1994 debut was "The Sun Rises in the East".', a: 'Jeru the Damaja', category: 'music' },
    { q: 'Atlanta producer/MC, founder of So So Def, behind Kris Kross and Da Brat hits.', a: 'Jermaine Dupri', category: 'music', alt: ['JD'] },
  ],
  K: [
    { q: 'Bronx-born rapper-philosopher Lawrence Parker — "Sound of da Police" 1993 announces his solo career after Scott La Rock.', a: 'KRS-One', category: 'music', alt: ['KRS One'] },
    { q: 'MF DOOM\'s early group with his brother DJ Subroc — their 1991 debut was "Mr. Hood". (Acronym.)', a: 'KMD', category: 'music' },
  ],
  L: [
    { q: 'Big L\'s 1995 debut LP on Columbia — title fuses fast living with peril and poverty.', a: 'Lifestylez ov da Poor & Dangerous', category: 'music', alt: ['Lifestylez ov da Poor and Dangerous'] },
    { q: 'GZA\'s 1995 RZA-produced sophomore — widely cited as the greatest Wu solo album.', a: 'Liquid Swords', category: 'music' },
    { q: 'Brooklyn group with future star Busta Rhymes — their 1991 debut was "A Future Without a Past...".', a: 'Leaders of the New School', category: 'music' },
    { q: 'Brooklyn female rapper born Kimberly Jones whose 1996 Biggie-produced debut was "Hard Core".', a: 'Lil\' Kim', category: 'music', alt: ['Lil Kim'] },
  ],
  M: [
    { q: 'Method Man\'s 1994 debut LP — its title is slang for marijuana.', a: 'Tical', category: 'music' },
    { q: 'Jay-Z & DMX\'s 1998 duet from "Vol. 2... Hard Knock Life". ("___, ___, ___" — three M-words.)', a: 'Money, Cash, Hoes', category: 'music', alt: ['Money Cash Hoes'] },
    { q: 'Jay-Z & Jermaine Dupri\'s 1998 single from JD\'s "Life in 1472" — title denies a thing\'s being.', a: 'Money Ain\'t a Thang', category: 'music', alt: ['Money Aint a Thang'] },
    { q: '2Pac & Outlawz "Makaveli" track addressed to his loaded firearm.', a: 'Me and My Girlfriend', category: 'music' },
    { q: '1997 Notorious B.I.G., Puff Daddy and Mase No. 1 sampling Diana Ross.', a: 'Mo Money Mo Problems', category: 'music' },
    { q: 'Geto Boys\' 1991 paranoia anthem — sampled Isaac Hayes\'s "Hung Up on My Baby".', a: 'Mind Playing Tricks on Me', category: 'music' },
    { q: 'Queensbridge producer born Marlon Williams — Juice Crew architect of Big Daddy Kane and Roxanne Shanté hits.', a: 'Marley Marl', category: 'music' },
    { q: 'New Orleans rapper born Michael Tyler — No Limit emcee with the throaty bark behind 1998\'s "Ghetto Fabulous".', a: 'Mystikal', category: 'music' },
    { q: 'Brownsville duo of Lil\' Fame and Billy Danze — "How About Some Hardcore" 1994, "Ante Up" 1998. (Acronym.)', a: 'M.O.P.', category: 'music', alt: ['MOP', 'Mash Out Posse'] },
    { q: 'Louisiana mogul born Percy Miller — No Limit Records founder behind 1997\'s "Ghetto D".', a: 'Master P', category: 'music' },
    { q: 'Gang Starr\'s late-career masterpiece released in 1998 — features "You Know My Steez" and "Above the Clouds".', a: 'Moment of Truth', category: 'music' },
  ],
  N: [
    { q: 'Nas\'s 1999 single from "I Am..." — title compares the rapper to his stylistic peers.', a: 'Nas Is Like', category: 'music' },
    { q: 'Posthumous Brooklyn-Cleveland collaboration on the 1997 double LP "Life After Death" — title combines the two groups\' names.', a: 'Notorious Thugs', category: 'music' },
  ],
  O: [
    { q: 'Notorious B.I.G.\'s 1995 single — its title asks for an additional shot at love.', a: 'One More Chance', category: 'music' },
    { q: 'Outkast\'s 1994 debut LP — its long compound title fuses a Southern locale with Cadillac sound.', a: 'Southernplayalisticadillacmuzik', category: 'music' },
    { q: 'Nas\'s 1994 "Illmatic" track produced by Q-Tip — an epistolary track about a prison letter. (Two words.)', a: 'One Love', category: 'music' },
    { q: 'Onyx\'s 1993 mosh-pit anthem from "Bacdafucup". (One word.)', a: 'Slam', category: 'music' },
    { q: 'Queens duo of Pharoahe Monch and Prince Po — "Stress: The Extinction Agenda" 1994.', a: 'Organized Konfusion', category: 'music' },
    { q: 'ODB\'s 1995 Wu solo debut.', a: 'Return to the 36 Chambers', category: 'music' },
    { q: 'Brooklyn-born D.I.T.C. soldier Omar Credle — "Word...Life" 1994 debut. (Two letters.)', a: 'O.C.', category: 'music', alt: ['OC'] },
    { q: 'Raekwon\'s 1995 RZA-produced solo debut — the original "purple tape".', a: 'Only Built 4 Cuban Linx', category: 'music' },
  ],
  P: [
    { q: '1992 Pharcyde single about unrequited crush — their biggest hit.', a: 'Passing Me By', category: 'music' },
    { q: 'Houston UGK rapper born Chad Butler — Bun B\'s partner on 1996\'s "Ridin\' Dirty".', a: 'Pimp C', category: 'music' },
    { q: '2Pac\'s "All Eyez on Me" closer foreshadowing his death — title imagines him cruising in his car.', a: 'Picture Me Rollin\'', category: 'music', alt: ['Picture Me Rollin'] },
    { q: 'Mt. Vernon producer-MC born Peter Phillips — half of the duo with CL Smooth.', a: 'Pete Rock', category: 'music' },
    { q: 'Queens MC born Troy Jamerson — Organized Konfusion\'s lyrical half whose 1999 solo "Internal Affairs" featured "Simon Says".', a: 'Pharoahe Monch', category: 'music' },
    { q: 'Nas\'s 1992 first-ever single, produced by Large Professor — appeared on the "Zebrahead" soundtrack and on "Illmatic". (One word.)', a: 'Halftime', category: 'music' },
  ],
  Q: [
    { q: 'New Jersey rapper born Dana Owens whose 1993 album "Black Reign" earned her a Grammy for "U.N.I.T.Y.".', a: 'Queen Latifah', category: 'music' },
  ],
  R: [
    { q: 'Eric B. & Rakim\'s 1992 final album as a duo — title commands you not to perspire.', a: 'Don\'t Sweat the Technique', category: 'music', alt: ['Dont Sweat the Technique'] },
    { q: 'God MC born William Griffin Jr. — Eric B.\'s rhyming partner, who debuted solo with 1997\'s "The 18th Letter".', a: 'Rakim', category: 'music' },
    { q: 'UGK\'s 1996 Southern-rap classic — title pairs a dusty verb with a state of grime.', a: 'Ridin\' Dirty', category: 'music', alt: ['Ridin Dirty'] },
    { q: 'Eazy-E\'s 1993 N.W.A diss EP track aimed at Dr. Dre.', a: 'Real Muthaphuckkin G\'s', category: 'music', alt: ['Real Muthaphuckkin Gs', 'Real Muthaphuckkin Gz'] },
    { q: 'Philadelphia female MC born Antonia Reed — Gang Starr Foundation member, "Kollage" 1996.', a: 'Bahamadia', category: 'music' },
    { q: 'Brooklyn-born female pioneer Lolita Gooden — the Juice Crew member behind 1984\'s answer-record dismantling of UTFO\'s big hit. (Her one-word-plus-accented-surname stage name.)', a: 'Roxanne Shanté', category: 'music', alt: ['Roxanne Shante'] },
  ],
  S: [
    { q: 'Mobb Deep\'s 1995 dread-soaked single from "The Infamous".', a: 'Shook Ones Pt. II', category: 'music', alt: ['Shook Ones Part II', 'Shook Ones Pt 2'] },
    { q: 'Houston rapper born Brad Jordan — Geto Boys frontman, 1994\'s "The Diary" solo classic.', a: 'Scarface', category: 'music' },
    { q: 'Notorious B.I.G.\'s "Ready to Die" final track — a chilling spoken-word call to Puffy.', a: 'Suicidal Thoughts', category: 'music' },
    { q: 'New Orleans rapper born Vyshonn Miller — Master P\'s brother, "Charge It 2 da Game" 1998.', a: 'Silkk the Shocker', category: 'music' },
    { q: 'Brooklyn duo of Tek and Steele — Boot Camp Clik\'s gun-themed pair, 1995\'s "Dah Shinin\'".', a: 'Smif-N-Wessun', category: 'music' },
    { q: 'Souls of Mischief\'s 1993 Bay Area debut LP — its title pairs the year of release with a forever-and-ever endpoint.', a: '93 \'til Infinity', category: 'music', alt: ['93 til Infinity'] },
    { q: 'Goodie Mob\'s 1995 LP that helped launch the Dirty South — title pairs nourishment with the spirit.', a: 'Soul Food', category: 'music' },
    { q: 'Bronx-via-NY rapper born Ricky Walters — 1994\'s "Behind Bars" was his comeback after prison.', a: 'Slick Rick', category: 'music' },
    { q: 'Hayward, California rapper born Robert Beck — 1993\'s "187 He Wrote" Crips-affiliated lyricist.', a: 'Spice 1', category: 'music' },
    { q: 'Mobb Deep\'s aggressive opener from "The Infamous" — title invokes Darwinian endurance.', a: 'Survival of the Fittest', category: 'music' },
  ],
  T: [
    { q: 'Memphis trio of DJ Paul, Juicy J and Lord Infamous behind 1995\'s "Mystic Stylez".', a: 'Three 6 Mafia', category: 'music' },
    { q: '2Pac\'s 1996 "All Eyez on Me" track about coastal urban warfare — its title references the western city he repped.', a: 'To Live & Die in L.A.', category: 'music', alt: ['To Live and Die in LA', 'To Live and Die in L.A.'] },
    { q: 'Chicago rapper born Carl Mitchell — formerly known as "Tung ___" — set a Guinness record for fastest emcee. (One-word current stage name.)', a: 'Twista', category: 'music' },
    { q: 'Houston UGK rapper born Bernard Freeman — Pimp C\'s partner on "Ridin\' Dirty".', a: 'Bun B', category: 'music' },
    { q: 'Oakland Bay Area legend born Todd Shaw — independent-rap pioneer behind 1993\'s "Get In Where You Fit In".', a: 'Too Short', category: 'music' },
    { q: '2Pac\'s 1996 "All Eyez on Me" duet with Snoop Doggy Dogg. ("___ of Amerikaz Most Wanted".)', a: '2 of Amerikaz Most Wanted', category: 'music', alt: ['2 of Americaz Most Wanted'] },
  ],
  U: [
    { q: 'Port Arthur, Texas duo of Pimp C and Bun B — 1996\'s "Ridin\' Dirty" is their Southern-rap canon. (Acronym.)', a: 'UGK', category: 'music', alt: ['Underground Kingz'] },
    { q: 'Queen Latifah\'s 1993 Grammy-winning women\'s-empowerment anthem. (Acronym with periods.)', a: 'U.N.I.T.Y.', category: 'music', alt: ['UNITY'] },
  ],
  V: [
    { q: 'Jay-Z\'s 1998 platinum breakthrough album. (Begins with an abbreviation for "Volume".)', a: 'Vol. 2... Hard Knock Life', category: 'music', alt: ['Vol 2 Hard Knock Life'] },
    { q: 'Jay-Z\'s 1999 album whose subtitle references his birth name. (Begins with an abbreviation for "Volume".)', a: 'Vol. 3... Life and Times of S. Carter', category: 'music', alt: ['Vol 3 Life and Times of S. Carter'] },
  ],
  W: [
    { q: 'The Staten Island collective\'s 1997 sprawling double-LP sophomore.', a: 'Wu-Tang Forever', category: 'music', alt: ['Wu Tang Forever'] },
    { q: 'Nas\'s "Illmatic" track produced by Pete Rock sampling Ahmad Jamal — title is a globe-claiming aphorism.', a: 'The World Is Yours', category: 'music', alt: ['World Is Yours'] },
  ],
  X: [
    { q: 'Detroit-born L.A. rapper born Alvin Joiner whose 1996 debut "At the Speed of Life" launched his career.', a: 'Xzibit', category: 'music' },
  ],
  Y: [
    { q: 'L.A. female MC born Yolanda Whitaker — Ice Cube protégée whose 1991 debut was "Make Way for the Motherlode".', a: 'Yo-Yo', category: 'music', alt: ['YoYo'] },
  ],
  Z: [
    { q: 'Bronx social-political organization founded by Afrika Bambaataa that mentored 1990s New York hip-hop. (Two words.)', a: 'Zulu Nation', category: 'music', alt: ['Universal Zulu Nation'] },
  ],
};
