import type { RawQuestion } from '../core/packs';

// Deeper-cut 1990s grunge / alternative / indie / post-grunge.
// Every answer's first letter matches its bucket; the answer never appears verbatim
// in its question; no duplicates of the base music90sAlt pack. Strict 1990–1999.
export const music90sAltExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: 'Nirvana ballad closing "In Utero" 1993 whose chorus repeats "all in all is all we are".', a: 'All Apologies', category: '90s-alt' },
    { q: 'Smashing Pumpkins 1998 fourth LP, a synth-heavy goth-pop pivot from "Mellon Collie".', a: 'Adore', category: '90s-alt' },
    { q: 'Smashing Pumpkins\' Latin-feeling lead single from their 1998 fourth LP — a girl\'s name plus a verb of worship.', a: 'Ava Adore', category: '90s-alt' },
    { q: 'Deftones 1997 second LP whose title evokes the pelt under a bear.', a: 'Around the Fur', category: '90s-alt' },
    { q: 'Tool\'s 1996 second studio LP, often stylized with an Æ ligature.', a: 'Aenima', alt: ['Ænima'], category: '90s-alt' },
    { q: 'Marilyn Manson\'s 1996 breakthrough concept LP about the death of God.', a: 'Antichrist Superstar', category: '90s-alt' },
    { q: 'Supergrass 1995 debut single whose one-word title is a casual greeting.', a: 'Alright', category: '90s-alt' },
    { q: 'Toad the Wet Sprocket 1991 hit beginning "Nothing\'s so loud as hearing when we lie".', a: 'All I Want', category: '90s-alt' },
    { q: 'Suede 1993 debut single titled after an animal and a substance.', a: 'Animal Nitrate', category: '90s-alt' },
    { q: 'Counting Crows 1996 single from "Recovering the Satellites" lamenting a chilly month.', a: 'A Long December', category: '90s-alt' },
  ],
  B: [
    { q: 'Blur 1997 single from the self-titled album, a lurching ode to a heroin nickname.', a: 'Beetlebum', category: '90s-alt' },
    { q: 'Green Day single from "Insomniac" 1995 whose title is slang for an amphetamine come-down.', a: 'Brain Stew', category: '90s-alt' },
    { q: 'The Verve 1997 single sampling an Andrew Loog Oldham orchestral cover of a Stones tune.', a: 'Bitter Sweet Symphony', category: '90s-alt' },
    { q: 'Rage Against the Machine\'s opening track on their 1992 debut, a call-to-arms namecheck.', a: 'Bombtrack', category: '90s-alt' },
    { q: 'Soundgarden\'s 1996 "Down on the Upside" lead single whose title weighs a heavy load.', a: 'Burden in My Hand', category: '90s-alt' },
  ],
  C: [
    { q: 'Nine Inch Nails 1994 single from "The Downward Spiral" with the infamous "I want to ___ you" hook.', a: 'Closer', category: '90s-alt' },
    { q: 'Smashing Pumpkins 1993 grunge anthem from "Siamese Dream" namechecking a winged baby.', a: 'Cherub Rock', category: '90s-alt' },
    { q: 'The Breeders\' 1993 alt-radio smash from "Last Splash" whose title is artillery.', a: 'Cannonball', category: '90s-alt' },
    { q: 'Offspring 1994 hit from "Smash" whose parenthetical commands "Keep \'Em Separated".', a: 'Come Out and Play', category: '90s-alt' },
    { q: 'Oasis 1995 "Morning Glory" track Noel wrote in tribute to Richard Ashcroft — about a man who fails to leave a silhouette.', a: 'Cast No Shadow', category: '90s-alt' },
    { q: 'Pavement\'s 1994 alt-radio breakthrough from "Crooked Rain, Crooked Rain" telling barbers to back off.', a: 'Cut Your Hair', category: '90s-alt' },
    { q: 'Pulp 1995 Britpop anthem from "Different Class" sneering at class tourism.', a: 'Common People', category: '90s-alt' },
  ],
  D: [
    { q: 'Pearl Jam 1993 "Vs." single about a father and a girl raised to think she\'s pretty.', a: 'Daughter', category: '90s-alt' },
    { q: 'Pearl Jam 1998 single from "Yield" whose video is an animated Marxist parable.', a: 'Do the Evolution', category: '90s-alt' },
    { q: 'Nirvana "Nevermind" track whose title is a vampiric come-on.', a: 'Drain You', category: '90s-alt' },
    { q: 'Pulp 1995 single about a girl born in late 1979 whose adulthood arrives at the millennium.', a: 'Disco 2000', category: '90s-alt' },
    { q: 'Smashing Pumpkins 1994 string-driven single from "Siamese Dream" with the line "the killer in me…".', a: 'Disarm', category: '90s-alt' },
  ],
  E: [
    { q: 'Vertical Horizon 1999 hit beginning "Somewhere there\'s speaking…".', a: 'Everything You Want', category: '90s-alt' },
    { q: 'Radiohead "OK Computer" track subtitled "(For a Film)" — the wedding scene in Baz Luhrmann\'s Romeo + Juliet.', a: 'Exit Music', alt: ['Exit Music (For a Film)'], category: '90s-alt' },
  ],
  F: [
    { q: 'Korn 1998 single from "Follow the Leader" — Jonathan Davis scats his way through this carnival-of-misfits chart hit.', a: 'Freak on a Leash', category: '90s-alt' },
    { q: 'Gin Blossoms 1993 follow-up to "Hey Jealousy" whose title hints at a discovered truth.', a: 'Found Out About You', category: '90s-alt' },
    { q: 'Korn\'s 1998 third LP whose title commands obedience to a guide.', a: 'Follow the Leader', category: '90s-alt' },
  ],
  G: [
    { q: 'Alice in Chains\' 1992 acoustic Sap EP track later beloved in MTV Unplugged form.', a: 'Got Me Wrong', category: '90s-alt' },
    { q: 'Pearl Jam 1998 lead single from "Yield" whose title is an avian command.', a: 'Given to Fly', category: '90s-alt' },
    { q: 'Korn 1998 single from "Follow the Leader" guesting Cheech Marin in the video.', a: 'Got the Life', category: '90s-alt' },
    { q: 'Green Day "Insomniac" 1995 single about hygiene during a meth bender.', a: 'Geek Stink Breath', category: '90s-alt' },
    { q: 'Better Than Ezra 1995 college-rock breakthrough whose one-word title is a positive review.', a: 'Good', category: '90s-alt' },
  ],
  H: [
    { q: 'Nine Inch Nails 1995 ballad closing "The Downward Spiral" later covered by Johnny Cash.', a: 'Hurt', category: '90s-alt' },
    { q: 'Gin Blossoms 1992 single from "New Miserable Experience" with the line "Tell me do you think it\'d be all right…".', a: 'Hey Jealousy', category: '90s-alt' },
    { q: 'Creed 1999 power-ballad from "Human Clay" reaching for a celestial level.', a: 'Higher', category: '90s-alt' },
    { q: 'Alice in Chains 1995 single from their self-titled "tripod" album begging not to feel that way.', a: 'Heaven Beside You', category: '90s-alt' },
    { q: 'Green Day "Nimrod" 1997 single about thumbing for a lift.', a: "Hitchin' a Ride", alt: ['Hitchin a Ride'], category: '90s-alt' },
    { q: 'Filter 1995 industrial single from "Short Bus" with a brusque insult of a title.', a: 'Hey Man Nice Shot', alt: ['Hey Man, Nice Shot'], category: '90s-alt' },
  ],
  I: [
    { q: 'Pearl Jam 1994 "Vitalogy" track in which Eddie insists he is on his own.', a: 'I Alone', category: '90s-alt' },
    { q: 'Tonic 1996 hit beginning "Just what you wanted…" from "Lemon Parade".', a: 'If You Could Only See', category: '90s-alt' },
    { q: 'Alice in Chains "Jar of Flies" 1994 single about wanting to be left alone.', a: 'I Stay Away', category: '90s-alt' },
    { q: 'Eve 6 1998 debut single asking to be put in a blender of feelings.', a: 'Inside Out', category: '90s-alt' },
  ],
  J: [
    { q: 'Korn frontman from Bakersfield, California, known for his bagpipes and the scat vocals on "Freak on a Leash".', a: 'Jonathan Davis', category: '90s-alt' },
    { q: 'Bespectacled Sheffield Britpop frontman of "Common People" and "Disco 2000", born September 1963.', a: 'Jarvis Cocker', category: '90s-alt' },
    { q: 'Alice in Chains\' 1994 acoustic EP shaped like a container of insects.', a: 'Jar of Flies', category: '90s-alt' },
    { q: 'Soundgarden 1992 "Badmotorfinger" single decrying messianic posturing.', a: 'Jesus Christ Pose', category: '90s-alt' },
  ],
  L: [
    { q: 'Nirvana 1992 "Nevermind" single whose chorus chants "I\'m so happy because today I found my friends".', a: 'Lithium', category: '90s-alt' },
    { q: 'Pearl Jam\'s 1999 chart-topping cover of a J. Frank Wilson death-ballad.', a: 'Last Kiss', category: '90s-alt' },
    { q: 'Live 1994 "Throwing Copper" smash about a baby born and a grandmother passing.', a: 'Lightning Crashes', category: '90s-alt' },
    { q: 'Beck\'s 1993 slacker-rap breakthrough whose chorus repeats "Soy un perdedor" — Spanish self-deprecation.', a: 'Loser', category: '90s-alt' },
    { q: 'Radiohead "OK Computer" track whose protagonist feels disappointed and aimless after a transport delay.', a: 'Let Down', category: '90s-alt' },
    { q: 'The Cardigans 1996 sugar-pop smash from "First Band on the Moon".', a: 'Lovefool', category: '90s-alt' },
    { q: 'Radiohead "OK Computer" anthem opening "pull me out of the aircrash".', a: 'Lucky', category: '90s-alt' },
  ],
  M: [
    { q: 'Smashing Pumpkins\' Siamese Dream slow-burner often cited as Corgan\'s prettiest — named for a condiment.', a: 'Mayonaise', category: '90s-alt' },
    { q: 'Marilyn Manson 1998 glam-rock concept LP whose title pairs an adjective with creatures.', a: 'Mechanical Animals', category: '90s-alt' },
    { q: 'White Zombie 1995 single from "Astro-Creep: 2000" whose hook compares us favorably to ourselves.', a: 'More Human Than Human', category: '90s-alt' },
    { q: 'Counting Crows 1993 breakthrough single about wanting to be Bob Dylan with a guy named after a Welsh nobody.', a: 'Mr. Jones', alt: ['Mr Jones'], category: '90s-alt' },
    { q: 'Bush 1994 single from "Sixteen Stone" whose one-word title is also a guitar tuning peg.', a: 'Machinehead', category: '90s-alt' },
    { q: 'Creed\'s 1997 debut single sharing the title of their first LP — Scott Stapp metaphorizes inner confinement.', a: 'My Own Prison', category: '90s-alt' },
    { q: 'Deftones 1997 lead single whose title personalizes the warm season.', a: 'My Own Summer', alt: ["My Own Summer (Shove It)"], category: '90s-alt' },
  ],
  N: [
    { q: 'Limp Bizkit 1999 hit from "Significant Other" whose chorus brags "I did it all for the ___".', a: 'Nookie', category: '90s-alt' },
    { q: 'Alice in Chains "Jar of Flies" 1994 acoustic meditation Layne sings "We chase misprinted lies".', a: 'Nutshell', category: '90s-alt' },
    { q: 'Radiohead "OK Computer" lullaby whose narrator wants a quiet life and a handshake of carbon monoxide.', a: 'No Surprises', category: '90s-alt' },
  ],
  O: [
    { q: 'Beck\'s 1996 Grammy-winning genre-blender LP including "Where It\'s At".', a: 'Odelay', category: '90s-alt' },
    { q: 'Soundgarden 1991 "Badmotorfinger" single brought to the spotlight.', a: 'Outshined', category: '90s-alt' },
  ],
  P: [
    { q: 'Nirvana "Nevermind" acoustic track sung from the perspective of an abductor.', a: 'Polly', category: '90s-alt' },
    { q: 'Radiohead\'s 1993 debut LP named for a Jerky Boys prank-call target.', a: 'Pablo Honey', category: '90s-alt' },
    { q: 'Nirvana "In Utero" single whose title is a tea Cobain drank for stomach pain.', a: 'Pennyroyal Tea', category: '90s-alt' },
    { q: 'Soundgarden 1996 "Down on the Upside" lead single whose two-word title pairs an aesthetic adjective with a hangman\'s loop.', a: 'Pretty Noose', category: '90s-alt' },
    { q: 'Smashing Pumpkins 1998 "Adore" ballad whose title is a one-word ideal.', a: 'Perfect', category: '90s-alt' },
    { q: 'Offspring 1998 single from "Americana" mocking a wannabe in parentheses for a White Guy.', a: 'Pretty Fly', alt: ['Pretty Fly (For a White Guy)'], category: '90s-alt' },
    { q: 'Matchbox Twenty 1996 single from their debut whose title is a pleading shove.', a: 'Push', category: '90s-alt' },
  ],
  R: [
    { q: 'Nirvana "In Utero" track whose retitled video card on MTV read "Sexually Assault Me".', a: 'Rape Me', category: '90s-alt' },
    { q: 'Soundgarden 1991 single from "Badmotorfinger" later covered by Johnny Cash — chorus snarls "I\'m gonna break my ___".', a: 'Rusty Cage', category: '90s-alt' },
    { q: 'Smashing Pumpkins 1993 "Siamese Dream" track whose title is a propulsion device.', a: 'Rocket', category: '90s-alt' },
    { q: 'Bush 1996 second LP whose title is a razor-and-luggage portmanteau.', a: 'Razorblade Suitcase', category: '90s-alt' },
    { q: 'Rancid 1995 single from "…And Out Come the Wolves" with a girl\'s name in the title.', a: 'Ruby Soho', category: '90s-alt' },
    { q: 'Counting Crows 1993 "August and Everything After" track that asks "what\'s the matter with you?"', a: 'Round Here', category: '90s-alt' },
    { q: 'Wigan-born singer who fronted The Verve through "Urban Hymns" and "Bitter Sweet Symphony" — sometimes nicknamed "Mad ___".', a: 'Richard Ashcroft', category: '90s-alt' },
  ],
  S: [
    { q: 'Pulp 1995 single from "Different Class" whose title references club drugs and shrugs.', a: "Sorted for E's & Wizz", alt: ['Sorted for Es and Wizz', "Sorted for E's and Wizz"], category: '90s-alt' },
    { q: 'Third Eye Blind 1997 debut single nicknamed "the doo-doo song" for its scat refrain.', a: 'Semi-Charmed Life', category: '90s-alt' },
    { q: 'Marcy Playground 1997 hit opening "Hangin\' round downtown by myself" with a famously dreamy, smell-evoking chorus.', a: 'Sex and Candy', alt: ['Sex & Candy'], category: '90s-alt' },
    { q: 'Goo Goo Dolls 1998 single from "Dizzy Up the Girl" — a kiss before…',  a: 'Slide', category: '90s-alt' },
    { q: 'Collective Soul 1994 single from "Hints Allegations and Things Left Unsaid" whose title is what you ask the light to do.', a: 'Shine', category: '90s-alt' },
    { q: 'Tool 1993 "Undertow" single about clarity after intoxication.', a: 'Sober', category: '90s-alt' },
    { q: 'Offspring 1994 "Smash" single whose narrator keeps coming back to a girlfriend who treats him like a "lapdog".', a: 'Self Esteem', category: '90s-alt' },
    { q: 'Reel Big Fish 1996 ska-punk single whose title is what corporations do.', a: 'Sell Out', category: '90s-alt' },
    { q: 'Live 1994 "Throwing Copper" track about commerce in the theater of life.', a: 'Selling the Drama', category: '90s-alt' },
    { q: 'Manson 1995 cover of a Eurythmics synth-classic.', a: 'Sweet Dreams', alt: ['Sweet Dreams (Are Made of This)'], category: '90s-alt' },
    { q: 'Oasis 1995 number-one single from "Morning Glory" — opens "I\'ve been standing at the station…".', a: 'Some Might Say', category: '90s-alt' },
  ],
  T: [
    { q: 'Live\'s 1994 breakthrough LP featuring "Lightning Crashes" and "Selling the Drama".', a: 'Throwing Copper', category: '90s-alt' },
    { q: 'Alice in Chains "Dirt" opener whose title is two body parts.', a: 'Them Bones', category: '90s-alt' },
    { q: 'Spin Doctors 1992 single from "Pocket Full of Kryptonite" about a pair of royals.', a: 'Two Princes', category: '90s-alt' },
    { q: 'Rancid 1995 ska-punk single from "…And Out Come the Wolves" with an explosive title.', a: 'Time Bomb', category: '90s-alt' },
    { q: 'Days of the New 1997 acoustic-grunge single whose chorus instructs a three-step.', a: 'Touch, Peel and Stand', alt: ['Touch Peel and Stand'], category: '90s-alt' },
    { q: 'Bowie cover Nirvana performed on their 1993 MTV Unplugged set, eponymous with a 1970 Bowie LP.', a: 'The Man Who Sold the World', category: '90s-alt' },
    { q: 'Marilyn Manson 1996 single from "Antichrist Superstar" calling out an attractive elite.', a: 'The Beautiful People', category: '90s-alt' },
    { q: 'Cake 1996 single from "Fashion Nugget" whose narrator "is racing and pacing and plotting the course" — going the ___.', a: 'The Distance', category: '90s-alt' },
    { q: 'The Verve 1997 follow-up to "Bitter Sweet Symphony" about ineffective pharmaceuticals.', a: "The Drugs Don't Work", alt: ['The Drugs Dont Work'], category: '90s-alt' },
    { q: 'Mighty Mighty Bosstones 1997 ska-punk smash about being a "shot in the dark" lucky guy.', a: 'The Impression That I Get', category: '90s-alt' },
    { q: 'Nine Inch Nails 1994 concept LP about self-destruction.', a: 'The Downward Spiral', category: '90s-alt' },
    { q: 'Nine Inch Nails 1999 double LP follow-up to "The Downward Spiral".', a: 'The Fragile', category: '90s-alt' },
    { q: 'Limp Bizkit\'s 1997 debut LP whose title is a banknote-pun threat.', a: "Three Dollar Bill, Y'all", alt: ['Three Dollar Bill Yall', 'Three Dollar Bill, Yall'], category: '90s-alt' },
    { q: 'Britpop band of Richard Ashcroft from Wigan; their 1997 LP was "Urban Hymns".', a: 'The Verve', alt: ['Verve'], category: '90s-alt' },
  ],
  W: [
    { q: 'Nirvana\'s "Unplugged" closer, a Lead Belly traditional often called "In the Pines".', a: 'Where Did You Sleep Last Night', category: '90s-alt' },
    { q: 'Pearl Jam 1998 single from "Yield" listing things the singer would like to be.', a: 'Wishlist', category: '90s-alt' },
    { q: 'Beck 1996 "Odelay" single with the chant "two turntables and a microphone".', a: "Where It's At", alt: ['Where Its At'], category: '90s-alt' },
    { q: 'Offspring 1998 single from "Americana" demanding employment.', a: "Why Don't You Get a Job?", alt: ["Why Dont You Get a Job", "Why Don't You Get a Job"], category: '90s-alt' },
    { q: 'Travis 1999 hit from "The Man Who" lamenting precipitation timing.', a: 'Why Does It Always Rain on Me?', alt: ['Why Does It Always Rain on Me'], category: '90s-alt' },
  ],
  Y: [
    { q: 'Pearl Jam\'s 1998 fifth studio LP, named for a road sign.', a: 'Yield', category: '90s-alt' },
    { q: 'Pearl Jam B-side and concert favorite whose title is a color of a vehicle light.', a: 'Yellow Ledbetter', category: '90s-alt' },
  ],
};
