import type { RawPack } from '../core/packs';

// 90s R&B / soul / new jack swing pack.
// Authoring rules followed: answers begin A–Z, never restated in the question,
// specific named entities, strictly 1990–1999 release dates, no padding.

export const music90sRnBPack: RawPack = {
  id: 'music-90s-rnb',
  name: '90s R&B',
  description: 'Smooth ballads, new jack swing, and R&B icons of the 1990s.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎶',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: "Princess-pop R&B singer whose 1994 debut 'Age Ain't Nothing but a Number' was produced by R. Kelly.", a: 'Aaliyah', category: '90s-rnb' },
      { q: "Mariah Carey's #1 single from the 1995 album 'Daydream' that begins 'We were as one, babe'.", a: 'Always Be My Baby', category: '90s-rnb' },
      { q: "K-Ci & JoJo's 1997 ballad whose video features the duo serenading a wedding party.", a: 'All My Life', category: '90s-rnb' },
      { q: "Toni Braxton's 1993 single from her self-titled debut, a tearful breakup ballad written by Babyface.", a: 'Another Sad Love Song', category: '90s-rnb' },
      { q: "Aaliyah's mysterious 1998 single from the 'Dr. Dolittle' soundtrack produced by Timbaland.", a: 'Are You That Somebody?', category: '90s-rnb' },
      { q: "112 single from 1998 featuring a Notorious B.I.G. verse, the lead from their 'Room 112' album.", a: 'Anywhere', category: '90s-rnb' },
      { q: "Brian McKnight's 1997 ballad asking 'do I ever cross your mind', his highest-charting Hot 100 hit at the time.", a: 'Anytime', category: '90s-rnb' },
      { q: "Brandy's 1999 ballad written by Shelly Peiken about how a partial effort still isn't enough to fix the hurt.", a: "Almost Doesn't Count", category: '90s-rnb' },
    ],
    B: [
      { q: "Philadelphia quartet behind 'Motownphilly' and 'End of the Road'.", a: 'Boyz II Men', category: '90s-rnb' },
      { q: "California teen sensation whose 1994 self-titled debut yielded 'I Wanna Be Down'.", a: 'Brandy', category: '90s-rnb' },
      { q: "Former New Edition front man whose 1992 self-titled album followed his solo smash 'Don't Be Cruel'.", a: 'Bobby Brown', category: '90s-rnb' },
      { q: "Kenneth Edmonds, the prolific singer-producer of countless 90s R&B hits including 'When Can I See You'.", a: 'Babyface', category: '90s-rnb' },
      { q: "Buffalo-born tenor whose 1999 ballad 'Back at One' became one of the year's biggest singles.", a: 'Brian McKnight', category: '90s-rnb' },
      { q: "Trio of former New Edition members behind the 1990 new jack swing classic 'Poison'.", a: 'Bell Biv DeVoe', category: '90s-rnb' },
      { q: "Teddy Riley-founded quartet whose 1996 hit 'No Diggity' featured Dr. Dre.", a: 'Blackstreet', category: '90s-rnb' },
      { q: "Brian McKnight's 1999 #2 ballad that counts down from five to one as the singer reaches for his love.", a: 'Back at One', category: '90s-rnb' },
      { q: "R. Kelly's slow-jam 1993 single from his debut '12 Play' that became a quiet-storm staple.", a: "Bump n' Grind", category: '90s-rnb', alt: ['Bump n Grind', 'Bump and Grind'] },
      { q: "Toni Braxton's 1993 debut single, a Babyface-penned ballad about reuniting with a lost love.", a: 'Breathe Again', category: '90s-rnb' },
      { q: "Brandy's 1995 single from her debut album about feeling crushed after a breakup.", a: 'Brokenhearted', category: '90s-rnb' },
    ],
    C: [
      { q: "TLC's 1994 #1 from 'CrazySexyCool' featuring Left Eye's spoken-word bridge about an unfaithful man.", a: 'Creep', category: '90s-rnb' },
      { q: "TLC's diamond-certified 1994 album that produced 'Waterfalls' and 'Red Light Special'.", a: 'CrazySexyCool', category: '90s-rnb' },
      { q: "Multi-ethnic quartet whose 1991 ballad 'I Adore Mi Amor' hit #1.", a: 'Color Me Badd', category: '90s-rnb' },
      { q: "Duo that scored a 1994 hit with the Babyface-produced 'Stroke You Up'.", a: 'Changing Faces', category: '90s-rnb' },
      { q: "SWV lead singer Cheryl Gamble, who released a 1999 solo album named for her own stage moniker.", a: 'Coko', category: '90s-rnb' },
      { q: "112 single from 1997 that interpolates Sam Cooke and pleads to a heart with an arrow.", a: 'Cupid', category: '90s-rnb' },
      { q: "Boyz II Men's 1991 debut album whose title nods to their Philly high school.", a: 'Cooleyhighharmony', category: '90s-rnb' },
    ],
    D: [
      { q: "Neo-soul pioneer Michael Archer whose 1995 album 'Brown Sugar' redefined R&B.", a: "D'Angelo", category: '90s-rnb', alt: ['DAngelo'] },
      { q: "Houston-based girl group whose 1998 self-titled debut included 'No, No, No'.", a: "Destiny's Child", category: '90s-rnb', alt: ['Destinys Child'] },
      { q: "Baltimore quartet led by Sisqó that hit big in 1998 with 'In My Bed' and 'How Deep Is Your Love'.", a: 'Dru Hill', category: '90s-rnb' },
      { q: "Chicago crooner whose 1999 single 'U Know What's Up' featured Lisa Lopes.", a: 'Donell Jones', category: '90s-rnb' },
      { q: "Lauryn Hill's 1998 #1 from 'The Miseducation of Lauryn Hill' warning women and men about deceit.", a: 'Doo Wop (That Thing)', category: '90s-rnb', alt: ['Doo Wop That Thing', 'Doo-Wop (That Thing)'] },
      { q: "Mariah Carey's 1993 #1 from 'Music Box' that interpolates The Emotions' 'Blind Alley'.", a: 'Dreamlover', category: '90s-rnb' },
      { q: "Mariah Carey's 1995 album that included 'Fantasy', 'One Sweet Day' and 'Always Be My Baby'.", a: 'Daydream', category: '90s-rnb' },
      { q: "En Vogue's 1996 Diane Warren-penned plea about a relationship slipping away.", a: "Don't Let Go (Love)", category: '90s-rnb', alt: ["Dont Let Go", "Don't Let Go", "Don't Let Go Love"] },
      { q: "Monica's 1995 hit at age 14 about an off day, often subtitled 'Just One of Dem Days'.", a: "Don't Take It Personal", category: '90s-rnb', alt: ["Dont Take It Personal", "Don't Take It Personal (Just One of Dem Days)"] },
    ],
    E: [
      { q: "Oakland quartet behind 1992's 'My Lovin' (You're Never Gonna Get It)' and 'Free Your Mind'.", a: 'En Vogue', category: '90s-rnb' },
      { q: "Neo-soul artist whose 1997 debut 'Baduizm' introduced the world to 'On & On'.", a: 'Erykah Badu', category: '90s-rnb' },
      { q: "Minneapolis-born singer of the 1999 hit 'Spend My Life with You' with Tamia.", a: 'Eric Benét', category: '90s-rnb', alt: ['Eric Benet'] },
      { q: "Boyz II Men's 1992 chart-topping ballad from the 'Boomerang' soundtrack written by Babyface.", a: 'End of the Road', category: '90s-rnb' },
    ],
    F: [
      { q: "Bad Boy Records first lady whose 1995 self-titled debut included 'Soon as I Get Home'.", a: 'Faith Evans', category: '90s-rnb' },
      { q: "Mariah Carey's 1995 #1 lead single from 'Daydream' that samples Tom Tom Club's 'Genius of Love'.", a: 'Fantasy', category: '90s-rnb' },
      { q: "Monica ballad from the 1996 'Space Jam' soundtrack that became her second #1.", a: 'For You I Will', category: '90s-rnb' },
      { q: "En Vogue's 1992 funk-rock single from 'Funky Divas' urging listeners not to judge by appearance.", a: 'Free Your Mind', category: '90s-rnb' },
    ],
    G: [
      { q: "Virginia-born Elgin Lumpkin whose 1996 Timbaland-produced debut yielded 'Pony'.", a: 'Ginuwine', category: '90s-rnb' },
      { q: "New York R&B duo of Amel Larrieux and Bryce Wilson whose 1995 single 'Tell Me' became a Top 5 hit.", a: 'Groove Theory', category: '90s-rnb' },
    ],
    H: [
      { q: "Mariah Carey's 1993 #1 ballad about the strength inside you, from 'Music Box'.", a: 'Hero', category: '90s-rnb' },
      { q: "Mariah Carey's 1997 #1 from 'Butterfly' that samples The Treacherous Three's 'Body Rock'.", a: 'Honey', category: '90s-rnb' },
      { q: "En Vogue's 1990 debut single from 'Born to Sing' produced by Foster & McElroy.", a: 'Hold On', category: '90s-rnb' },
      { q: "Brandy's 1998 #1 single from her sophomore Diane Warren-penned LP, begging an ex to reconsider.", a: 'Have You Ever?', category: '90s-rnb', alt: ['Have You Ever'] },
      { q: "Dru Hill 1998 single with Redman, a remake of the Bee Gees classic for the 'Rush Hour' soundtrack.", a: 'How Deep Is Your Love', category: '90s-rnb' },
    ],
    I: [
      { q: "Boyz II Men's 1994 #1 ballad from 'II', often played as a wedding first-dance song.", a: "I'll Make Love to You", category: '90s-rnb', alt: ['Ill Make Love to You', "I'll Make Love To You"] },
      { q: "R. Kelly's inspirational 1996 single from the 'Space Jam' soundtrack about soaring.", a: 'I Believe I Can Fly', category: '90s-rnb' },
      { q: "Brandy's 1994 debut single produced by Keith Crouch.", a: 'I Wanna Be Down', category: '90s-rnb' },
      { q: "SWV's 1993 single from 'It's About Time' produced by Brian Alexander Morgan.", a: "I'm So Into You", category: '90s-rnb', alt: ['Im So Into You'] },
      { q: "Aaliyah's 1996 single produced by Timbaland that asks if her boyfriend's secret is safe.", a: 'If Your Girl Only Knew', category: '90s-rnb' },
      { q: "1991 Boyz II Men a cappella ballad from their debut, a doo-wop-tinged dedication to a lost friend.", a: "It's So Hard to Say Goodbye to Yesterday", category: '90s-rnb', alt: ["Its So Hard to Say Goodbye to Yesterday"] },
    ],
    J: [
      { q: "Pop-R&B icon whose 1993 fifth studio album included 'That's the Way Love Goes' and 'Again'.", a: 'Janet Jackson', category: '90s-rnb' },
      { q: "Joseph Lewis Thomas, the Georgia tenor of the 1997 single 'Don't Wanna Be a Player'.", a: 'Joe', category: '90s-rnb' },
      { q: "Charlotte-formed quartet behind the 1993 album 'Diary of a Mad Band'.", a: 'Jodeci', category: '90s-rnb' },
      { q: "Xscape's 1993 debut single from 'Hummin' Comin' at 'Cha' produced by Jermaine Dupri.", a: "Just Kickin' It", category: '90s-rnb', alt: ['Just Kickin It'] },
    ],
    K: [
      { q: "Brothers Cedric and Joel Hailey, formerly of Jodeci, who hit #1 in 1997 with 'All My Life'.", a: 'K-Ci & JoJo', category: '90s-rnb', alt: ['K-Ci and JoJo', 'KCi and JoJo', 'KCi & JoJo'] },
      { q: "Fugees 1996 cover of a Roberta Flack song that became a global hit from 'The Score'.", a: 'Killing Me Softly', category: '90s-rnb' },
      { q: "Houston trio H-Town's 1993 sexually charged debut single.", a: "Knockin' Da Boots", category: '90s-rnb', alt: ['Knockin Da Boots', 'Knockin the Boots'] },
    ],
    L: [
      { q: "Fugees frontwoman whose 1998 debut solo album won Album of the Year and five Grammys total.", a: 'Lauryn Hill', category: '90s-rnb' },
      { q: "TLC member born Lisa Nicole Lopes, known for her rapped verses and a black stripe of face paint.", a: 'Left Eye', category: '90s-rnb', alt: ['Lisa Lopes', 'Lisa Left Eye Lopes'] },
    ],
    M: [
      { q: "Long Island singer whose seven-octave range debuted on 1990's 'Vision of Love'.", a: 'Mariah Carey', category: '90s-rnb' },
      { q: "Brooklyn-born neo-soul artist whose 1996 debut LP 'Urban Hang Suite' arrived alongside D'Angelo's rise.", a: 'Maxwell', category: '90s-rnb' },
      { q: "Atlanta-born singer whose 1995 debut 'Miss Thang' arrived when she was just 14.", a: 'Monica', category: '90s-rnb' },
      { q: "Yonkers singer dubbed the Queen of Hip-Hop Soul whose 1992 debut was 'What's the 411?'.", a: 'Mary J. Blige', category: '90s-rnb', alt: ['Mary J Blige'] },
      { q: "Los Angeles singer whose 1995 anthem 'This Is How We Do It' topped the charts.", a: 'Montell Jordan', category: '90s-rnb' },
      { q: "Mariah Carey's 1993 third studio album that produced 'Dreamlover' and 'Hero'.", a: 'Music Box', category: '90s-rnb' },
      { q: "Boyz II Men's 1991 debut single celebrating their hometown record-label heritage.", a: 'Motownphilly', category: '90s-rnb' },
      { q: "Mariah Carey's 1997/98 #1 from 'Butterfly' featuring a Latin-tinged ballad arrangement.", a: 'My All', category: '90s-rnb' },
      { q: "En Vogue's 1992 hit from 'Funky Divas' whose parenthetical title warns a man he won't get something.", a: "My Lovin' (You're Never Gonna Get It)", category: '90s-rnb', alt: ['My Lovin', "My Lovin'", "My Lovin' Youre Never Gonna Get It"] },
      { q: "Mary J. Blige's 1994 second studio album, named simply for her existence.", a: 'My Life', category: '90s-rnb' },
      { q: "Arrested Development's 1992 social-commentary single about a homeless friend.", a: 'Mr. Wendal', category: '90s-rnb', alt: ['Mr Wendal'] },
    ],
    N: [
      { q: "Boston quintet that reunited in 1996 for the 'Home Again' tour and album.", a: 'New Edition', category: '90s-rnb' },
      { q: "Minnesota R&B trio whose 1997 hit 'Too Close' topped the Billboard Hot 100.", a: 'Next', category: '90s-rnb' },
      { q: "TLC's 1999 #1 single from 'FanMail' dismissing men who try to game them from the passenger side.", a: 'No Scrubs', category: '90s-rnb' },
      { q: "Blackstreet's 1996 chart-topping single featuring Dr. Dre and Queen Pen with the 'shorty get down good Lord' hook.", a: 'No Diggity', category: '90s-rnb' },
    ],
    O: [
      { q: "Boyz II Men's 1994 #1 ballad from 'II' about pleading for forgiveness in a relationship.", a: 'On Bended Knee', category: '90s-rnb' },
      { q: "Aaliyah's 1996 Timbaland-produced album that announced her new sound after R. Kelly.", a: 'One in a Million', category: '90s-rnb' },
    ],
    P: [
      { q: "Ginuwine's 1996 Timbaland-produced debut single about a sexually charged ride.", a: 'Pony', category: '90s-rnb' },
      { q: "Bell Biv DeVoe's 1990 debut single warning that beauty can be deceptive — 'never trust a big butt and a smile'.", a: 'Poison', category: '90s-rnb' },
    ],
    R: [
      { q: "Chicago singer whose 1995 self-titled album included 'You Remind Me of Something' and 'Down Low'.", a: 'R. Kelly', category: '90s-rnb', alt: ['R Kelly', 'RKelly'] },
      { q: "Mary J. Blige's 1992 debut single from 'What's the 411?' sampling Audio Two's 'Top Billin''.", a: 'Real Love', category: '90s-rnb' },
      { q: "SWV's 1993 hit medley from 'It's About Time' that interpolates a Michael Jackson classic.", a: 'Right Here / Human Nature', category: '90s-rnb', alt: ['Right Here Human Nature', 'Right Here/Human Nature'] },
    ],
    S: [
      { q: "Sisters With Voices, the New York R&B trio behind 1993's 'Weak'.", a: 'SWV', category: '90s-rnb' },
      { q: "Maryland singer Mark Andrews who fronted Dru Hill and scored a 1999 solo hit with 'Thong Song'.", a: 'Sisqó', category: '90s-rnb', alt: ['Sisqo'] },
      { q: "Quartet whose a cappella 1992 single 'If I Ever Fall in Love' reached #2 on the Hot 100.", a: 'Shai', category: '90s-rnb' },
      { q: "Mary J. Blige's 1997 album that included 'I Can Love You' and 'Everything'.", a: 'Share My World', category: '90s-rnb' },
      { q: "Brandy Babyface-produced single from the 1995 'Waiting to Exhale' soundtrack about pining for a crush.", a: "Sittin' Up in My Room", category: '90s-rnb', alt: ['Sittin Up in My Room', 'Sitting Up in My Room'] },
    ],
    T: [
      { q: "Atlanta trio of T-Boz, Left Eye and Chilli behind 'Waterfalls' and 'No Scrubs'.", a: 'TLC', category: '90s-rnb' },
      { q: "Maryland-born contralto whose 1993 LaFace debut included 'Breathe Again' and 'You Mean the World to Me'.", a: 'Toni Braxton', category: '90s-rnb' },
      { q: "Oakland brothers whose 1990 album 'The Revival' featured 'Feels Good' and 'It Never Rains'.", a: 'Tony! Toni! Toné!', category: '90s-rnb', alt: ['Tony Toni Tone', 'Tony! Toni! Tone!'] },
      { q: "Bad Boy trio whose 1996 debut produced 'Can't You See' with The Notorious B.I.G.", a: 'Total', category: '90s-rnb' },
      { q: "Quincy Jones-mentored singer whose 1991 debut album featured 'Tomorrow' and 'Tell Me What You Want Me to Do'.", a: 'Tevin Campbell', category: '90s-rnb' },
      { q: "Los Angeles singer whose 1998 self-titled debut included 'Sweet Lady'.", a: 'Tyrese', category: '90s-rnb' },
      { q: "1998 Brandy and Monica duet that became the longest-running #1 of the year.", a: 'The Boy Is Mine', category: '90s-rnb' },
      { q: "Bone Thugs-n-Harmony's 1996 Grammy-winning tribute to fallen friends.", a: 'Tha Crossroads', category: '90s-rnb' },
      { q: "Arrested Development's 1992 debut single naming the southern state of their forebears.", a: 'Tennessee', category: '90s-rnb' },
      { q: "TLC member born Tionne Watkins who handled lead vocals on 'Unpretty'.", a: 'T-Boz', category: '90s-rnb', alt: ['TBoz', 'Tionne Watkins'] },
    ],
    U: [
      { q: "Chattanooga-born singer whose 1997 album 'My Way' produced 'You Make Me Wanna...'.", a: 'Usher', category: '90s-rnb' },
      { q: "Toni Braxton's 1996 Diane Warren-penned #1 from her 'Secrets' album.", a: 'Un-Break My Heart', category: '90s-rnb', alt: ['Unbreak My Heart', 'Un Break My Heart'] },
      { q: "Xscape's 1993 follow-up single that pleads for the listener to comprehend their love.", a: 'Understanding', category: '90s-rnb' },
      { q: "Donell Jones's 1999 single featuring Lisa Lopes, the lead from his 'Where I Wanna Be' album.", a: "U Know What's Up", category: '90s-rnb', alt: ['U Know Whats Up', 'You Know What\'s Up'] },
    ],
    V: [
      { q: "Mariah Carey's 1990 debut single that announced her seven-octave range.", a: 'Vision of Love', category: '90s-rnb' },
    ],
    W: [
      { q: "New Jersey-born icon whose 1992 cover of 'I Will Always Love You' broke records.", a: 'Whitney Houston', category: '90s-rnb' },
      { q: "TLC's 1995 #1 single about chasing dreams that aren't yours, from 'CrazySexyCool'.", a: 'Waterfalls', category: '90s-rnb' },
      { q: "SWV's 1993 #1 single about being incapable of resisting a lover's pull.", a: 'Weak', category: '90s-rnb' },
      { q: "Salt-N-Pepa 1993 collaboration with En Vogue celebrating a good man, from 'Very Necessary'.", a: 'Whatta Man', category: '90s-rnb' },
    ],
    X: [
      { q: "Atlanta quartet signed to Jermaine Dupri's So So Def label whose 1993 debut was 'Hummin' Comin' at 'Cha'.", a: 'Xscape', category: '90s-rnb' },
    ],
    Y: [
      { q: "Toni Braxton's 1996 single from 'Secrets' that became her first US Top 10 hit from that album.", a: "You're Makin' Me High", category: '90s-rnb', alt: ["Youre Makin Me High", "You're Making Me High", "Youre Making Me High"] },
    ],
  },
};
