import type { RawQuestion } from '../core/packs';

// Deeper-cut 1980s rock: thrash-metal pioneers, hair-metal also-rans, post-punk and
// alt-rock, guitar-virtuoso shred era, and classic-rockers continuing through the decade.
// Every answer's first letter matches its bucket; the answer never appears verbatim in
// its own question; no duplicates of the base 80s Rock pack.
export const music80sRockExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: 'New York thrash quartet of Scott Ian whose 1987 "Among the Living" cemented their Big Four status.', a: 'Anthrax', category: '80s-rock' },
    { q: 'German "Balls to the Wall" metallers fronted by Udo Dirkschneider.', a: 'Accept', category: '80s-rock' },
    { q: 'Prog supergroup of Steve Howe, Geoff Downes and John Wetton — 1982 debut single "Heat of the Moment".', a: 'Asia', category: '80s-rock' },
    { q: 'Iron Maiden\'s 1984 single about WWII fighter pilots — title evokes top cards.', a: 'Aces High', category: '80s-rock' },
    { q: 'Canadian rock star whose 1984 "Reckless" gave us "Run to You" and "Summer of \'69" — surname only.', a: 'Adams', category: '80s-rock' },
    { q: 'Metallica\'s 1988 album whose title finishes Lady Justice with "...And Justice for ___" — last word.', a: 'All', alt: ['And Justice for All'], category: '80s-rock' },
  ],
  B: [
    { q: 'British dark-rock band of Peter Murphy whose "Bela Lugosi\'s Dead" launched goth.', a: 'Bauhaus', category: '80s-rock' },
    { q: 'D.C. hardcore-reggae fusion pioneers led by H.R. whose 1986 "I Against I" widened punk\'s palette.', a: 'Bad Brains', category: '80s-rock' },
    { q: 'Henry Rollins-era SST hardcore band founded by guitarist Greg Ginn — name evokes a dark pennant.', a: 'Black Flag', category: '80s-rock' },
    { q: 'L.A. glam-metal also-rans behind 1988\'s "Long Way to Love" — name pairs a girl\'s name with a sly mammal.', a: 'Britny Fox', category: '80s-rock' },
    { q: 'Geffen-signed AOR supergroup of John Waite and Neal Schon — 1989 self-titled debut had "When I See You Smile".', a: 'Bad English', category: '80s-rock' },
    { q: 'Don Henley\'s 1984 solo single about nostalgic seaside summers, with the iconic synth-and-snare line.', a: 'Boys of Summer', alt: ['The Boys of Summer'], category: '80s-rock' },
  ],
  C: [
    { q: 'Robert Smith\'s gloom-pop band whose 1989 "Disintegration" gave us "Lovesong" and "Pictures of You".', a: 'The Cure', alt: ['Cure'], category: '80s-rock' },
    { q: 'Slowhand Cream alum whose 1989 "Journeyman" signalled a guitar-hero return — surname.', a: 'Clapton', alt: ['Eric Clapton'], category: '80s-rock' },
    { q: 'Randy Rhoads-penned Ozzy 1980 single about a fast-moving locomotive of madness.', a: 'Crazy Train', category: '80s-rock' },
    { q: 'Ian Astbury and Billy Duffy\'s British band whose 1987 "Electric" rode a Zeppelin-style riff revival.', a: 'The Cult', alt: ['Cult'], category: '80s-rock' },
    { q: 'Poison\'s flamboyant lead guitarist who joined in 1985 — full stage name uses two initials and a French-sounding surname.', a: 'C.C. DeVille', alt: ['CC DeVille', 'C.C.'], category: '80s-rock' },
  ],
  D: [
    { q: 'Dave Mustaine\'s thrash band founded after his Metallica firing — debut "Killing Is My Business...".', a: 'Megadeth', alt: ['Megadeath'], category: '80s-rock' },
    { q: 'L.A. metal band of Don whose 1984 "Tooth and Nail" featured George Lynch shredding — eponymous.', a: 'Dokken', category: '80s-rock' },
    { q: 'San Francisco hardcore-punk satirists fronted by Jello Biafra whose 1980 "Holiday in Cambodia" still stings.', a: 'Dead Kennedys', category: '80s-rock' },
    { q: 'J Mascis\'s Massachusetts noise-rock trio whose 1987 "You\'re Living All Over Me" defined the era.', a: 'Dinosaur Jr.', alt: ['Dinosaur Jr', 'Dinosaur'], category: '80s-rock' },
    { q: 'Sonic Youth\'s 1988 double-LP masterpiece with the candle on the cover.', a: 'Daydream Nation', category: '80s-rock' },
    { q: 'Ozzy\'s 1981 follow-up to "Blizzard of Ozz" — title sounds like a deranged person\'s journal.', a: 'Diary of a Madman', category: '80s-rock' },
  ],
  E: [
    { q: 'Liverpool moody post-punkers of Ian McCulloch whose 1984 "Ocean Rain" gave us "The Killing Moon".', a: 'Echo & the Bunnymen', alt: ['Echo and the Bunnymen'], category: '80s-rock' },
    { q: 'Jeff Lynne\'s symphonic-rock outfit whose 1981 "Time" album spawned "Hold On Tight".', a: 'ELO', alt: ['Electric Light Orchestra'], category: '80s-rock' },
    { q: 'Bay Area thrash band of Gary Holt whose 1985 debut "Bonded by Blood" predated Metallica\'s breakthrough.', a: 'Exodus', category: '80s-rock' },
    { q: 'The Cult\'s 1987 album that took them American — title is a single charged word.', a: 'Electric', category: '80s-rock' },
    { q: 'Pasadena guitar genius who pioneered the two-handed tapping technique — first-and-last name; band shares his surname.', a: 'Eddie Van Halen', alt: ['Eddie'], category: '80s-rock' },
  ],
  F: [
    { q: 'L.A. sleaze quintet whose 1987 self-titled debut had "Bathroom Wall" — name suggests a feline of looser virtue.', a: 'Faster Pussycat', category: '80s-rock' },
    { q: 'Angelo Moore-fronted L.A. ska-punk-funk band whose 1988 "Truth and Soul" mixed genres without apology.', a: 'Fishbone', category: '80s-rock' },
    { q: 'San Francisco genre-blending alt-metal band whose 1987 "Introduce Yourself" preceded Patton — three-word name.', a: 'Faith No More', category: '80s-rock' },
    { q: 'Ex-Runaways guitarist whose 1988 "Close My Eyes Forever" duet with Ozzy stormed MTV — surname matches an American car company.', a: 'Ford', category: '80s-rock' },
    { q: 'Mötley Crüe\'s 1989 fifth LP whose title parodies a kindly doctor — "Dr. ___".', a: 'Feelgood', alt: ['Dr. Feelgood'], category: '80s-rock' },
  ],
  G: [
    { q: 'Genesis\'s original frontman whose 1986 "So" album gave us "Sledgehammer" — surname suggests an archangel.', a: 'Gabriel', category: '80s-rock' },
    { q: 'L.A. shredder of Dokken known for the "Tooth and Nail" sound — first-and-last name.', a: 'George Lynch', alt: ['Lynch'], category: '80s-rock' },
    { q: 'Synthpop-rock star behind 1980\'s "Cars" — first-and-last name, surname matches a famous explorer-numbered prefix.', a: 'Gary Numan', alt: ['Numan'], category: '80s-rock' },
    { q: 'Irish blues-rock guitarist whose 1987 "Wild Frontier" and 1989 "After the War" featured ex-Sweet keyboardists — full first-and-last name, "Parisienne Walkways" was his earlier classic.', a: 'Gary Moore', alt: ['Moore'], category: '80s-rock' },
  ],
  H: [
    { q: 'German power-metal band of Michael Kiske whose two-part "Keeper of the Seven Keys" defined the genre.', a: 'Helloween', category: '80s-rock' },
    { q: 'Minneapolis hardcore trio of Bob Mould whose 1984 "Zen Arcade" was punk\'s "Quadrophenia" — umlauts mandatory.', a: 'Hüsker Dü', alt: ['Husker Du'], category: '80s-rock' },
    { q: 'Indiana singer-songwriter whose 1987 "Bring the Family" launched a roots-rock revival — surname rhymes with "kit at".', a: 'Hiatt', category: '80s-rock' },
    { q: 'Guy Chadwick\'s British neo-psychedelic band on Creation whose 1988 self-titled debut included "Christine".', a: 'House of Love', alt: ['The House of Love'], category: '80s-rock' },
  ],
  I: [
    { q: 'Iron Maiden\'s 1982 chart-topping album opener — a galloping tale of an escaping convict.', a: 'Invaders', category: '80s-rock' },
    { q: 'U2 gospel-infused single from "The Joshua Tree" about a never-ending search — opening four words.', a: 'I Still Haven\'t Found What I\'m Looking For', alt: ['I Still Havent Found What Im Looking For'], category: '80s-rock' },
    { q: 'U2\'s 1980 debut single from "Boy" with a hypnotic, chant-like chorus about loyally trailing someone.', a: 'I Will Follow', category: '80s-rock' },
    { q: 'Sammy Hagar\'s 1984 solo single defying the federal speed limit — three words.', a: 'I Can\'t Drive 55', alt: ['I Cant Drive 55'], category: '80s-rock' },
  ],
  J: [
    { q: 'Perry Farrell\'s L.A. alt-rock band whose 1988 "Nothing\'s Shocking" sleeve was banned in many stores.', a: 'Jane\'s Addiction', alt: ['Janes Addiction'], category: '80s-rock' },
    { q: 'Manchester post-punk band of Ian Curtis whose 1980 "Closer" was released after the singer\'s death.', a: 'Joy Division', category: '80s-rock' },
    { q: 'Surfing instrumental-rock virtuoso of "Surfing with the Alien" — first-and-last name.', a: 'Joe Satriani', alt: ['Satriani'], category: '80s-rock' },
    { q: 'Led Zeppelin guitarist whose 1988 solo "Outrider" reunited him with Robert Plant — full first-and-last name.', a: 'Jimmy Page', alt: ['Page'], category: '80s-rock' },
  ],
  K: [
    { q: 'Birmingham post-punk band of Jaz Coleman whose 1985 "Night Time" influenced Metallica — name pairs murder with mirth.', a: 'Killing Joke', category: '80s-rock' },
    { q: 'Swiss hard rockers whose 1981 "Headhunter" album earned them a US support slot with Aerosmith.', a: 'Krokus', category: '80s-rock' },
    { q: 'Gene Simmons\' face-painted band whose 1983 "Lick It Up" album dropped the makeup — four-letter name.', a: 'KISS', category: '80s-rock' },
    { q: 'Cinderella\'s raspy-voiced frontman who defined the Philadelphia glam-metal band — surname.', a: 'Keifer', category: '80s-rock' },
    { q: 'Maryland hard-rock band whose 1988 "Blow My Fuse" featured "Don\'t Close Your Eyes" — three-letter band name evokes a sharp jab.', a: 'Kix', category: '80s-rock' },
  ],
  L: [
    { q: 'Vernon Reid-fronted NYC band whose 1988 "Vivid" mixed hard rock with funk — name is a chromatic adjective.', a: 'Living Colour', alt: ['Living Color'], category: '80s-rock' },
    { q: 'Dio\'s 1984 sophomore album and title track — phrase also describes a runner at the back.', a: 'Last in Line', alt: ['The Last in Line'], category: '80s-rock' },
    { q: 'British indie crooner whose Commotions released 1984\'s "Rattlesnakes" — first-and-last stage name.', a: 'Lloyd Cole', alt: ['Lloyd'], category: '80s-rock' },
    { q: 'Aerosmith\'s 1989 single from "Pump" about an erotic encounter in a vertical mode of transport — three words.', a: 'Love in an Elevator', category: '80s-rock' },
    { q: 'Cinderella\'s 1988 single about an interminable chilly season — finishes the three-word title beginning with this adjective for "extended".', a: 'Long', category: '80s-rock' },
  ],
  M: [
    { q: 'D.C. hardcore band of Ian MacKaye whose 1981 EP defined straight-edge — name suggests a small risk.', a: 'Minor Threat', category: '80s-rock' },
    { q: 'New Jersey horror-punk band of Glenn Danzig whose skull logo became iconic.', a: 'Misfits', category: '80s-rock' },
    { q: 'Seattle proto-grunge band of Andrew Wood whose 1990 "Apple" arrived posthumously — three-word name.', a: 'Mother Love Bone', category: '80s-rock' },
    { q: 'Eric Martin-fronted hard-rock outfit whose 1989 self-titled debut featured shred guitar by Paul Gilbert.', a: 'Mr. Big', alt: ['Mr Big'], category: '80s-rock' },
    { q: 'Wayne Hussey-led offshoot of Sisters of Mercy whose 1986 "God\'s Own Medicine" was a UK goth landmark.', a: 'The Mission', alt: ['Mission'], category: '80s-rock' },
    { q: 'Ozzy\'s 1980 debut single addressed to Aleister, an English occultist — opens with an honorific.', a: 'Mr. Crowley', alt: ['Mr Crowley'], category: '80s-rock' },
    { q: 'Birmingham indie-pop band whose 1987 "Happy Head" jangled — name pairs a strong-flavored citrus with confections.', a: 'Mighty Lemon Drops', alt: ['The Mighty Lemon Drops'], category: '80s-rock' },
    { q: 'Lemmy-fronted British speed-metal band whose 1980 "Ace of Spades" became the genre\'s anthem — name has an umlaut and means "speed-freak".', a: 'Motörhead', alt: ['Motorhead'], category: '80s-rock' },
  ],
  N: [
    { q: 'Jane\'s Addiction\'s 1988 breakthrough album — title sounds like jadedness made audible.', a: 'Nothing\'s Shocking', alt: ['Nothings Shocking'], category: '80s-rock' },
    { q: 'Manchester post-punk outfit formed from Joy Division\'s ashes whose 1983 "Blue Monday" 12-inch was the bestselling of all time — name suggests a successor regime.', a: 'New Order', category: '80s-rock' },
    { q: 'Phil Collins\'s 1985 chart-dominating solo LP whose cover shows him in formalwear — title is a three-word dress-code rejoinder.', a: 'No Jacket Required', category: '80s-rock' },
  ],
  O: [
    { q: 'Queensrÿche\'s 1988 concept album about a brainwashed assassin — three words with a colon between.', a: 'Operation: Mindcrime', alt: ['Operation Mindcrime'], category: '80s-rock' },
  ],
  P: [
    { q: 'Black Francis\'s Boston-area quartet whose 1989 "Doolittle" gave us "Here Comes Your Man".', a: 'Pixies', category: '80s-rock' },
    { q: 'Led Zeppelin frontman whose 1988 "Now and Zen" featured Jimmy Page guesting — surname suggests a factory or greenery.', a: 'Plant', category: '80s-rock' },
    { q: 'Chrissie Hynde-led Anglo-American band whose 1984 "Learning to Crawl" included "Back on the Chain Gang".', a: 'Pretenders', alt: ['The Pretenders'], category: '80s-rock' },
    { q: 'Richard Butler\'s British band whose 1986 title song became a John Hughes movie\'s anthem — full three-word name.', a: 'Psychedelic Furs', alt: ['The Psychedelic Furs'], category: '80s-rock' },
    { q: 'Guns N\' Roses 1988 acoustic ballad from "G N\' R Lies" — title is a virtue the band famously lacked.', a: 'Patience', category: '80s-rock' },
    { q: 'Guns N\' Roses 1987 anthem about an L.A. utopia — also a Disneyland nickname.', a: 'Paradise City', category: '80s-rock' },
    { q: 'Aerosmith\'s 1989 album that gave us "Love in an Elevator" and "Janie\'s Got a Gun" — one-syllable verb.', a: 'Pump', category: '80s-rock' },
    { q: 'Aerosmith\'s 1987 comeback album that put them back on top — title evokes an endless holiday.', a: 'Permanent Vacation', category: '80s-rock' },
  ],
  Q: [
    { q: 'Geoff Tate-fronted Seattle prog-metal band whose 1988 concept album about a brainwashed assassin sold 3+ million.', a: 'Queensrÿche', alt: ['Queensryche'], category: '80s-rock' },
  ],
  R: [
    { q: 'Anthony Kiedis-fronted L.A. funk-rockers whose 1984 self-titled debut preceded 1989\'s "Mother\'s Milk".', a: 'Red Hot Chili Peppers', alt: ['RHCP', 'Chili Peppers'], category: '80s-rock' },
    { q: 'Minneapolis indie-rockers of Paul Westerberg whose 1984 album famously shared its title with a Beatles LP.', a: 'The Replacements', alt: ['Replacements'], category: '80s-rock' },
    { q: 'Dio\'s 1983 single about a colorful arc visible at night — finishes "___ in the Dark".', a: 'Rainbow', category: '80s-rock' },
    { q: 'Yngwie Malmsteen\'s 1984 instrumental shred debut — title evokes an awakening martial impulse.', a: 'Rising Force', category: '80s-rock' },
    { q: 'Slayer\'s 1986 thrash-classic closing title track — two words pairing a downpour with crimson fluid.', a: 'Raining Blood', category: '80s-rock' },
    { q: 'Bon Jovi\'s charismatic lead guitarist, long-haired and known for shared lead vocals — first name; surname starts with S.', a: 'Richie', alt: ['Richie Sambora'], category: '80s-rock' },
  ],
  S: [
    { q: 'Andrew Eldritch\'s Leeds goth band whose 1987 "Floodland" included "This Corrosion".', a: 'Sisters of Mercy', alt: ['The Sisters of Mercy'], category: '80s-rock' },
    { q: 'Thurston Moore and Kim Gordon\'s NYC noise band whose 1988 double LP was hailed as art-rock\'s peak.', a: 'Sonic Youth', category: '80s-rock' },
    { q: 'Seattle band of Chris Cornell whose 1989 "Louder Than Love" was the first major-label grunge release.', a: 'Soundgarden', category: '80s-rock' },
    { q: 'Hannover hard rockers whose 1984 "Love at First Sting" gave us "Rock You Like a Hurricane".', a: 'Scorpions', category: '80s-rock' },
    { q: 'Mark, Vinnie and friends\' glam-metal act whose 1990 "Stick It to Ya" went double-platinum with "Up All Night".', a: 'Slaughter', category: '80s-rock' },
    { q: 'Tom Araya-fronted L.A. thrash band whose 1986 "Reign in Blood" runs 29 minutes of carnage.', a: 'Slayer', category: '80s-rock' },
    { q: 'Spencer Davis Group alum whose 1986 solo "Back in the High Life" hit big — full name, surname pairs a verb of victory with a forest sound.', a: 'Steve Winwood', alt: ['Winwood'], category: '80s-rock' },
    { q: 'Iron Maiden\'s 1988 concept LP based on Orson Scott Card — title is "___ of a ___".', a: 'Seventh Son of a Seventh Son', alt: ['Seventh Son'], category: '80s-rock' },
    { q: 'Mötley Crüe\'s 1983 sophomore album, title shouts disrespect at the Prince of Darkness.', a: 'Shout at the Devil', category: '80s-rock' },
  ],
  T: [
    { q: 'Sacramento bluesy hard rockers whose 1989 "The Great Radio Controversy" included "Love Song".', a: 'Tesla', category: '80s-rock' },
    { q: 'Bay Area thrash band whose debut "The Legacy" (with Skolnick on lead) made them genre lifers.', a: 'Testament', category: '80s-rock' },
    { q: 'Chattanooga hard rockers whose 1989 "Surprise Attack" gave us "Walkin\' Shoes" — name is a city doubled.', a: 'Tora Tora', category: '80s-rock' },
    { q: 'Stevie Ray Vaughan\'s 1983 debut album, sharing its name with a watery disaster in his home state.', a: 'Texas Flood', category: '80s-rock' },
    { q: 'Iron Maiden\'s 1983 single about the Charge of the Light Brigade — finishes "The ___" with a cavalryman noun.', a: 'Trooper', alt: ['The Trooper'], category: '80s-rock' },
    { q: 'Genesis\'s 1986 #1 single about an unseen but irresistible attraction — title is "Invisible ___" finishing here.', a: 'Touch', category: '80s-rock' },
  ],
  V: [
    { q: 'All-female hair-metal band whose 1988 self-titled debut produced "Edge of a Broken Heart".', a: 'Vixen', category: '80s-rock' },
    { q: 'Zappa-trained instrumental shred virtuoso whose 1990 "Passion and Warfare" set a high bar — surname is a string of vowels.', a: 'Vai', category: '80s-rock' },
    { q: 'Texas blues-rock guitarist Stephen Ray whose 1983 "Texas Flood" launched his career — surname; brother of Jimmie.', a: 'Vaughan', category: '80s-rock' },
  ],
  W: [
    { q: 'Jani Lane-fronted L.A. band whose 1989 "Dirty Rotten Filthy Stinking Rich" featured "Down Boys".', a: 'Warrant', category: '80s-rock' },
    { q: 'Kip ___, whose self-titled 1988 debut produced "Seventeen" and "Headed for a Heartbreak" — eponymous band.', a: 'Winger', category: '80s-rock' },
    { q: 'Blackie Lawless\'s shock-metal band whose 1984 debut helped trigger the PMRC — four letters with periods.', a: 'W.A.S.P.', alt: ['WASP'], category: '80s-rock' },
    { q: 'Dee Snider\'s 1984 Twisted Sister anthem of teen defiance from "Stay Hungry" — chorus declares refusal in five words.', a: 'We\'re Not Gonna Take It', alt: ['We Are Not Gonna Take It'], category: '80s-rock' },
  ],
  Y: [
    { q: 'Swedish neoclassical shred guitarist of Rising Force fame — first name famously hard to spell.', a: 'Yngwie', alt: ['Yngwie Malmsteen', 'Malmsteen'], category: '80s-rock' },
    { q: 'Oakland hard-rock vets of Dave Meniketti whose 1981 "Earthshaker" was a US breakthrough — two letters joined by an ampersand.', a: 'Y&T', alt: ['Y and T'], category: '80s-rock' },
  ],
};
