import type { RawPack } from '../core/packs';

// 2000s Hip-Hop & R&B trivia: the artists, songs, albums, labels and lore that
// defined commercial rap and R&B between 2000 and 2010. Every answer's first
// letter matches its bucket; the answer never appears verbatim inside its own
// question. Pop-side singles that primarily belong to the 00s/10s Pop & Rock
// pack (e.g. Beyonce's "Single Ladies", Rihanna's pop singles, JT's "SexyBack")
// are intentionally NOT duplicated here.

export const music00sHipHopPack: RawPack = {
  id: 'music-00s-hiphop',
  name: '2000s Hip-Hop & R&B',
  description: 'Hip-hop and R&B that defined 2000–2010.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎤',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: 'Senegalese-American singer behind 2004\'s "Lonely" and 2006\'s "Smack That" — first name only.', a: 'Akon', category: '00s-hiphop' },
      { q: 'Lil Wayne\'s 2008 chart-topping single whose title spells out the number "1,000,000" — short and snappy.', a: 'A Milli', category: '00s-hiphop' },
      { q: 'Estelle\'s 2008 Kanye-featuring transatlantic love letter — "___ Boy".', a: 'American Boy', category: '00s-hiphop' },
      { q: '2005 OneRepublic ballad first made famous in a Timbaland remix featuring its writer Ryan Tedder.', a: 'Apologize', category: '00s-hiphop' },
      { q: 'Outkast member born Benjamin who took most of the singing on "Hey Ya!" — stage name pairing a first name with a four-digit number.', a: 'Andre 3000', alt: ['André 3000', '3000'], category: '00s-hiphop' },
      { q: 'Nelly\'s 2002 ode to a particular Nike sneaker model named for a presidential aircraft — three-word title beginning A.', a: 'Air Force Ones', alt: ['Air Force One'], category: '00s-hiphop' },
      { q: 'Charlotte-born neo-soul singer whose 2003 album "Comin\' from Where I\'m From" went platinum — full name beginning with A.', a: 'Anthony Hamilton', category: '00s-hiphop' },
      { q: 'DC-via-Boston R&B singer behind 2005\'s "1 Thing" — one-word stage name beginning A.', a: 'Amerie', category: '00s-hiphop' },
      { q: 'R&B singer-actress born Haughton whose self-titled 2001 album was released just weeks before her death — first name only.', a: 'Aaliyah', category: '00s-hiphop' },
    ],
    B: [
      { q: 'Drake\'s 2009 "So Far Gone" single declaring his new partner the finest of all his past romances — four-word title beginning B.', a: 'Best I Ever Had', category: '00s-hiphop' },
      { q: 'Outkast\'s Antwan Patton — André 3000\'s rapping partner.', a: 'Big Boi', category: '00s-hiphop' },
      { q: 'Beyonce\'s 2007 duet with Shakira about a man playing them both — title pairs an adjective with a noun for "deceiver".', a: 'Beautiful Liar', category: '00s-hiphop' },
      { q: 'T-Pain\'s 2007 ode to a mixologist that he\'d like to take home.', a: 'Bartender', category: '00s-hiphop' },
      { q: 'Akon\'s 2008 single with Kardinal Offishall and Colby O\'Donis simply titled with one breathtaking adjective.', a: 'Beautiful', category: '00s-hiphop' },
      { q: 'Ne-Yo\'s 2007 ballad in which his girl is the very reason he can\'t move on — "___ of You".', a: 'Because of You', category: '00s-hiphop' },
      { q: 'Jay-Z\'s 1999 sample-driven Timbaland anthem with UGK that he was still riding into 2000 — "___" — completes the title beginning with B.', a: 'Big Pimpin\'', alt: ['Big Pimpin'], category: '00s-hiphop' },
      { q: 'Cleveland\'s harmonised quintet who scored a 2007 comeback hit with "I Tried" featuring Akon — hyphenated group name.', a: 'Bone Thugs-N-Harmony', alt: ['Bone Thugs N Harmony', 'Bone Thugs'], category: '00s-hiphop' },
      { q: 'Lil Bow Wow\'s shortened adult stage name from 2003 onwards.', a: 'Bow Wow', category: '00s-hiphop' },
      { q: 'Soulful R&B singer Norwood whose 2002 "Full Moon" album showed her grown-up sound — first name only (a wine-related word).', a: 'Brandy', category: '00s-hiphop' },
      { q: 'T.I.\'s 2004 breakout single ordering an entrance — "___ \'Em Out".', a: 'Bring \'Em Out', alt: ['Bring Em Out'], category: '00s-hiphop' },
    ],
    C: [
      { q: 'Soulja Boy\'s 2007 ringtone-era dance anthem with the "YOUUUU" ad-lib — two-word title beginning C.', a: 'Crank That', alt: ['Crank That (Soulja Boy)'], category: '00s-hiphop' },
      { q: 'Usher\'s 2004 mega-album whose Part II revealed he\'d fathered a child outside his relationship.', a: 'Confessions', category: '00s-hiphop' },
      { q: '50 Cent\'s 2005 lollipop-themed single about a sweets store.', a: 'Candy Shop', category: '00s-hiphop' },
      { q: 'Nelly\'s 2000 debut album, named for the dialect of the state from which St. Louis hails.', a: 'Country Grammar', category: '00s-hiphop' },
      { q: 'Diddy-signed model-turned-singer behind 2006\'s breathy "Me & U".', a: 'Cassie', category: '00s-hiphop' },
      { q: 'Eminem, Dr. Dre and 50 Cent\'s 2009 "Relapse"-era posse cut about popping open a celebratory drink — three-word title beginning C.', a: 'Crack a Bottle', category: '00s-hiphop' },
      { q: 'Virginia-born R&B-pop singer-dancer whose 2005 "Run It!" went straight to #1 — full stage name beginning C.', a: 'Chris Brown', category: '00s-hiphop' },
      { q: 'Houston rapper born Hakeem Seriki whose 2005 "Ridin\'" with Krayzie Bone won a Grammy.', a: 'Chamillionaire', category: '00s-hiphop' },
      { q: 'Chicago rapper born Lonnie Lynn whose 2005 Kanye-helmed album "Be" went platinum — one-word stage name.', a: 'Common', category: '00s-hiphop' },
      { q: 'St. Louis rapper-turned-actor whose 2003 debut "Jackpot" featured "Right Thurr" — one word, ends in -y.', a: 'Chingy', category: '00s-hiphop' },
      { q: 'Atlanta R&B singer-dancer surnamed Harris whose 2004 "Goodies" and 2006 "Promise" made her a crunk&B icon — first name only beginning with C.', a: 'Ciara', category: '00s-hiphop' },
    ],
    D: [
      { q: 'Toronto rapper-singer born Aubrey Graham whose 2009 "So Far Gone" mixtape made him a star — stage name.', a: 'Drake', category: '00s-hiphop' },
      { q: 'Jay-Z\'s 2003 "Black Album" single that became a Pharrell-styled brush-it-away signature move — four-word title beginning D.', a: 'Dirt Off Your Shoulder', category: '00s-hiphop' },
      { q: 'T.I.\'s 2008 Justin Timberlake-featuring rebirth ballad from "Paper Trail" about leaving the old self behind — three-word title beginning D.', a: 'Dead and Gone', category: '00s-hiphop' },
      { q: 'Nelly and Kelly Rowland\'s 2002 #1 ballad about love-induced confusion.', a: 'Dilemma', category: '00s-hiphop' },
      { q: 'Snoop Dogg and Pharrell\'s 2004 hypnotic Neptunes-produced #1 — five-word title beginning D telling you to release something the way you would something that just burned your hand.', a: 'Drop It Like It\'s Hot', alt: ['Drop It Like Its Hot'], category: '00s-hiphop' },
      { q: 'Kanye West\'s 2005 Bonnie-and-Clyde-flavoured single sampling a Shirley Bassey 007 theme, about conflict gems from a West African nation — full title beginning D.', a: 'Diamonds from Sierra Leone', category: '00s-hiphop' },
      { q: 'Usher\'s 2010 #1 with Pitbull crediting the booth spinner for sparking the romance on the dancefloor — six-word title beginning D.', a: 'DJ Got Us Fallin\' in Love', alt: ['DJ Got Us Fallin in Love'], category: '00s-hiphop' },
      { q: 'Akon\'s 2007 plea sung in falsetto over a tropical beat — "___ Matter" (it\'s where you\'ve been).', a: 'Don\'t Matter', alt: ['Dont Matter'], category: '00s-hiphop' },
      { q: 'Neo-soul singer behind 2000\'s "Voodoo" album — one stylised stage name with an apostrophe.', a: 'D\'Angelo', alt: ['DAngelo'], category: '00s-hiphop' },
      { q: 'Yonkers rapper born Earl Simmons whose Ruff Ryders run continued into 2003\'s "Grand Champ".', a: 'DMX', alt: ['Dark Man X', 'Earl Simmons'], category: '00s-hiphop' },
    ],
    E: [
      { q: 'Detroit rapper born Marshall Mathers — the best-selling artist of the 2000s.', a: 'Eminem', category: '00s-hiphop' },
      { q: 'Jay-Z and Alicia Keys\'s 2009 anthem to New York City featuring her piano hook over a Bobby Womack sample — four-word title beginning E.', a: 'Empire State of Mind', category: '00s-hiphop' },
      { q: 'Jay-Z\'s 2003 single from "The Black Album" intended as his on-stage farewell.', a: 'Encore', category: '00s-hiphop' },
      { q: 'Dallas-born neo-soul singer surnamed Badu whose 2008 fourth studio album continued her reign — first name only beginning with E.', a: 'Erykah', category: '00s-hiphop' },
      { q: 'British singer-songwriter surnamed Swaray who teamed with Kanye on the 2008 hit "American Boy" — one-word stage name beginning E.', a: 'Estelle', category: '00s-hiphop' },
    ],
    F: [
      { q: 'Drake, Kanye, Lil Wayne and Eminem\'s 2009 posse cut from the "More Than a Game" soundtrack — single-word title.', a: 'Forever', category: '00s-hiphop' },
      { q: 'Brooklyn rapper born John Jackson whose 2003 album "Street Dreams" hit big — stage name.', a: 'Fabolous', category: '00s-hiphop' },
      { q: 'Jay-Z\'s 2009 ballad sampling Alphaville\'s 80s synth-pop hit about staying eternally youthful, with Mr Hudson — two-word title beginning F.', a: 'Forever Young', category: '00s-hiphop' },
      { q: 'Kanye West\'s 2008 single from "808s & Heartbreak" featuring red strobing camera-bulb imagery and tear-stained car windows — two-word title beginning F.', a: 'Flashing Lights', category: '00s-hiphop' },
      { q: 'Carol City rapper born Tramar Dillard whose 2008 "Low" with T-Pain topped the Hot 100 — two-word stage name beginning with F.', a: 'Flo Rida', category: '00s-hiphop' },
      { q: 'Bad Boy R&B singer Evans whose 2005 "The First Lady" continued her career — first name only.', a: 'Faith', category: '00s-hiphop' },
      { q: 'UK duo Marsha Ambrosius and Natalie Stewart who scored 2003\'s "Say Yes" — group name beginning F.', a: 'Floetry', category: '00s-hiphop' },
    ],
    G: [
      { q: 'Kanye West and Jamie Foxx\'s 2005 Grammy-winning Ray Charles–sampling #1.', a: 'Gold Digger', category: '00s-hiphop' },
      { q: 'Ciara\'s 2004 Lil Jon-produced debut single about treats you can\'t have.', a: 'Goodies', category: '00s-hiphop' },
      { q: 'Missy Elliott\'s 2001 Timbaland-produced banger ordering the listener to unleash their wild side — four-word title beginning G with "Ur" in the middle.', a: 'Get Ur Freak On', category: '00s-hiphop' },
      { q: 'Sean Paul\'s 2003 dancehall command from "Dutty Rock" — two-word title urging the listener to get to work.', a: 'Get Busy', category: '00s-hiphop' },
      { q: 'Nelly\'s 2005 ode to jeweled teeth featuring Paul Wall and Ali & Gipp.', a: 'Grillz', category: '00s-hiphop' },
      { q: 'Lil Wayne\'s 2008 T-Pain duet from "Tha Carter III" boasting about having plenty of cash — two-word title beginning G.', a: 'Got Money', category: '00s-hiphop' },
      { q: 'Missy Elliott\'s 2002 cult favorite about chatty rumour-spreaders, featuring Ms. Jade and Ludacris — two-word title beginning G.', a: 'Gossip Folks', category: '00s-hiphop' },
    ],
    H: [
      { q: 'Outkast\'s 2003 #1 from "Speakerboxxx/The Love Below" with a "shake it like a Polaroid picture" hook — "___ Ya!".', a: 'Hey Ya!', alt: ['Hey Ya'], category: '00s-hiphop' },
      { q: 'Nelly\'s 2002 hot-weather single from "Nellyville" — three-word title beginning H about high temperatures indoors (spelled with two Rs).', a: 'Hot in Herre', alt: ['Hot in Here'], category: '00s-hiphop' },
      { q: 'Kanye West\'s 2008 break-up anthem from "808s & Heartbreak".', a: 'Heartless', category: '00s-hiphop' },
      { q: 'Jay-Z\'s 2001 "Blueprint" single — "___ of the City (Ain\'t No Love)".', a: 'Heart of the City', alt: ['Heart of the City (Ain\'t No Love)'], category: '00s-hiphop' },
      { q: 'Trick Daddy\'s 2001 anthem — three-word title beginning H telling the listener to get his attention (dawg).', a: 'Holla at Me', category: '00s-hiphop' },
    ],
    I: [
      { q: 'Beyoncé\'s 2006 break-up smash about replacing a careless lover — opening "To the left, to the left".', a: 'Irreplaceable', category: '00s-hiphop' },
      { q: 'Neo-soul singer-songwriter surnamed Simpson behind 2001\'s "Video" — full stage name beginning I (often stylised with a dot).', a: 'India.Arie', alt: ['India Arie', 'India Aire'], category: '00s-hiphop' },
      { q: 'Akon\'s 2006 Snoop Dogg–featuring falsetto-led #1 declaration of desire — four-word title beginning with the singular pronoun I.', a: 'I Wanna Love You', category: '00s-hiphop' },
      { q: '50 Cent\'s 2003 club single hailing the listener for being at his party.', a: 'In Da Club', alt: ['In da Club'], category: '00s-hiphop' },
      { q: 'Jay-Z\'s 2001 "Blueprint" single named with H-to-the-O-V — completes "___ (H.O.V.A.)".', a: 'Izzo', alt: ['Izzo (H.O.V.A.)', 'Izzo (HOVA)'], category: '00s-hiphop' },
    ],
    J: [
      { q: 'Kanye West\'s 2004 gospel-tinged statement single from "The College Dropout".', a: 'Jesus Walks', category: '00s-hiphop' },
      { q: 'Brooklyn mogul-MC born Shawn Carter, the founder of Roc-A-Fella.', a: 'Jay-Z', alt: ['Jay Z', 'Hova', 'Jigga'], category: '00s-hiphop' },
      { q: 'Singer-pianist born Stephens whose 2004 "Get Lifted" featured "Ordinary People" — surname-style stage name beginning J that suggests mythic status.', a: 'John Legend', category: '00s-hiphop' },
      { q: 'Fayetteville-raised rapper born Jermaine Lamarr whose 2007 mixtape "The Come Up" introduced him — initialed two-part stage name.', a: 'J. Cole', alt: ['J Cole', 'JCole'], category: '00s-hiphop' },
      { q: 'Slaughterhouse rapper from Jersey City who scored a 2003 hit with "Pump It Up" — full stage name beginning J.', a: 'Joe Budden', category: '00s-hiphop' },
      { q: 'Philly neo-soul poet whose 2000 debut album opened with the title question "Who Is...?" referencing her own identity — full name beginning with J.', a: 'Jill Scott', category: '00s-hiphop' },
    ],
    K: [
      { q: 'Chicago rapper-producer born with middle name Omari whose 2004 debut was "The College Dropout".', a: 'Kanye West', alt: ['Kanye'], category: '00s-hiphop' },
      { q: 'Cleveland rapper born Scott Mescudi behind 2008\'s "Day \'n\' Nite" — stage name.', a: 'Kid Cudi', category: '00s-hiphop' },
      { q: 'Oakland-born R&B singer behind 2005\'s "Love" and the album "The Way It Is" — full stage name beginning K.', a: 'Keyshia Cole', alt: ['Keyshia'], category: '00s-hiphop' },
      { q: 'Destiny\'s Child member Rowland who duetted with Nelly on 2002\'s "Dilemma" — first name only.', a: 'Kelly', category: '00s-hiphop' },
    ],
    L: [
      { q: 'Eminem\'s 2002 8-Mile theme that won the Oscar for Best Original Song — two-word title beginning L urging you to seize one chance and dissolve fully into the moment.', a: 'Lose Yourself', category: '00s-hiphop' },
      { q: 'New Orleans MC surnamed Carter — Cash Money\'s self-styled "best rapper alive" behind 2008\'s "Tha Carter III" — stage name beginning with a diminutive.', a: 'Lil Wayne', alt: ['Lil\' Wayne', 'Weezy'], category: '00s-hiphop' },
      { q: 'Lil Wayne\'s 2008 #1 with Static Major — sweet, sticky candy on a stick.', a: 'Lollipop', category: '00s-hiphop' },
      { q: 'Atlanta rapper born Christopher Bridges whose 2000 debut "Back for the First Time" went platinum.', a: 'Ludacris', category: '00s-hiphop' },
      { q: 'T.I.\'s 2008 inspirational comeback single produced by Just Blaze featuring Rihanna, urging the listener to seize the day — three-word title beginning L.', a: 'Live Your Life', category: '00s-hiphop' },
      { q: 'Missy Elliott\'s 2005 "Cookbook" single sampling Cybotron, urging you to abandon restraint on the dancefloor — two-word title beginning L.', a: 'Lose Control', category: '00s-hiphop' },
      { q: 'Usher\'s 2008 R&B/dance fusion with Young Jeezy about romance on the dancefloor — four-word title beginning L.', a: 'Love in This Club', alt: ['Love In This Club'], category: '00s-hiphop' },
      { q: 'Kanye West\'s 2008 single from "808s & Heartbreak" about romantic captivity — two-word title beginning L.', a: 'Love Lockdown', category: '00s-hiphop' },
      { q: 'D4L\'s 2005 Atlanta snap-music smash about a chewy candy with a brand-name title.', a: 'Laffy Taffy', category: '00s-hiphop' },
      { q: 'Fat Joe\'s 2004 Terror Squad dance anthem — two-word title beginning L about reclining backwards.', a: 'Lean Back', category: '00s-hiphop' },
      { q: 'Beyoncé\'s 2006 Dreamgirls Oscar-nominated showstopper — one-word title commanding the audience\'s ears.', a: 'Listen', category: '00s-hiphop' },
      { q: 'Chicago rapper born Wasalu Jaco whose 2006 "Food & Liquor" debut won critical acclaim — full stage name beginning L.', a: 'Lupe Fiasco', category: '00s-hiphop' },
    ],
    M: [
      { q: 'Eminem\'s 2004 ballad to his daughter Hailie sampling a familiar lullaby bird.', a: 'Mockingbird', category: '00s-hiphop' },
      { q: 'Outkast\'s 2000 ode to Stankonia featuring an apology to a mother-in-law named Erykah Badu — completes "___, ___".', a: 'Ms. Jackson', alt: ['Ms Jackson', 'Mrs. Jackson'], category: '00s-hiphop' },
      { q: 'Houston rapper who broke through in 2005 with "Still Tippin\'" alongside Slim Thug and Paul Wall — two-word stage name beginning M and ending with a very common surname.', a: 'Mike Jones', category: '00s-hiphop' },
      { q: 'Brooklyn MC born Dante Smith — Black Star half who released 1999\'s "Black on Both Sides" — stage name beginning M.', a: 'Mos Def', category: '00s-hiphop' },
      { q: 'Philly singer behind 2000\'s "Aijuswanaseing" — full stage name with a Q.', a: 'Musiq Soulchild', alt: ['Musiq'], category: '00s-hiphop' },
      { q: 'DC-born singer of "Case of the Ex" whose 2003 "Moodring" continued her hits — first name beginning M (often written with an accent).', a: 'Mýa', alt: ['Mya'], category: '00s-hiphop' },
      { q: 'Long Beach R&B singer Barrett whose 2004 "Let Me Love You" topped the Hot 100 — first name only.', a: 'Mario', category: '00s-hiphop' },
      { q: 'New York neo-soul falsettist whose 2009 "BLACKsummers\'night" earned Album-of-the-Year buzz — single stage name beginning M.', a: 'Maxwell', category: '00s-hiphop' },
      { q: 'Virginia rapper-producer-singer born Melissa Arnette — Timbaland\'s closest collaborator throughout the 00s.', a: 'Missy Elliott', category: '00s-hiphop' },
      { q: 'Bronx R&B singer-actress whose 2001 "No More Drama" album sold millions — the "Queen of Hip-Hop Soul" — full stage name beginning M.', a: 'Mary J. Blige', alt: ['Mary J Blige'], category: '00s-hiphop' },
      { q: 'Mariah Carey\'s mid-2000s nickname — used in the title of her 2005 comeback album about being "emancipated" — short and cute.', a: 'Mimi', category: '00s-hiphop' },
    ],
    N: [
      { q: 'St. Louis rapper born Cornell Haynes Jr. whose 2000–02 run with "Country Grammar" and "Nellyville" was inescapable.', a: 'Nelly', category: '00s-hiphop' },
      { q: 'R&B singer-songwriter born Shaffer Chimere Smith — the man behind "So Sick" and "Miss Independent".', a: 'Ne-Yo', alt: ['NeYo', 'Ne Yo'], category: '00s-hiphop' },
      { q: 'Pharrell Williams\'s trio with Chad Hugo and Shay Haley — punctuated stage name beginning N.', a: 'N.E.R.D.', alt: ['NERD', 'N*E*R*D'], category: '00s-hiphop' },
      { q: 'Queens MC born Jones with Illmatic in his catalog whose 2001 "Stillmatic" reignited a famous feud with Jay-Z — three-letter stage name.', a: 'Nas', category: '00s-hiphop' },
    ],
    O: [
      { q: 'Andre 3000 and Big Boi\'s Atlanta duo whose 2000 album was "Stankonia".', a: 'Outkast', alt: ['OutKast'], category: '00s-hiphop' },
      { q: 'Usher\'s 2010 single from "Raymond v. Raymond" — three letters that scream "oh my god".', a: 'OMG', category: '00s-hiphop' },
      { q: 'B2K\'s teen-idol lead surnamed Grandberry who went solo with 2005\'s "O" — one-word stage name beginning O.', a: 'Omarion', category: '00s-hiphop' },
      { q: 'John Legend\'s 2004 Kanye-helmed piano ballad about everyday folks falling in and out of love — two-word title beginning O.', a: 'Ordinary People', category: '00s-hiphop' },
    ],
    P: [
      { q: '50 Cent\'s 2003 Snoop Dogg-featuring single about a certain hustler with a fur coat and cane.', a: 'P.I.M.P.', alt: ['PIMP', 'Pimp'], category: '00s-hiphop' },
      { q: 'Virginia-born producer-singer Williams of the Neptunes — first name only.', a: 'Pharrell', category: '00s-hiphop' },
      { q: 'Houston rapper born Slayton whose 2005 "The Peoples Champ" topped the Billboard 200 — two-word stage name beginning P, famed for grillz.', a: 'Paul Wall', category: '00s-hiphop' },
      { q: 'Nelly Furtado\'s 2006 Timbaland-produced #1 about flirting freely.', a: 'Promiscuous', category: '00s-hiphop' },
      { q: 'Ciara\'s 2006 sultry slow-jam single — single-word title meaning a vow.', a: 'Promise', category: '00s-hiphop' },
      { q: 'Florida rapper surnamed Washington — Slip-N-Slide signee behind 2007\'s "The Real Testament" — single-word stage name beginning P.', a: 'Plies', category: '00s-hiphop' },
      { q: 'Huey\'s 2006 St. Louis dance smash about three sequenced moves — full title beginning P.', a: 'Pop, Lock & Drop It', alt: ['Pop Lock and Drop It'], category: '00s-hiphop' },
      { q: 'Three 6 Mafia member born in Memphis surnamed Houston, Juicy J\'s older brother, behind 2002\'s "Chickenhead" — full stage name beginning P.', a: 'Project Pat', category: '00s-hiphop' },
    ],
    R: [
      { q: 'Miami rapper born William Roberts II whose 2006 "Hustlin\'" debut put him on the map — full stage name.', a: 'Rick Ross', category: '00s-hiphop' },
      { q: 'Outkast\'s 2003 "Speakerboxxx" hit that\'s really about a girl who\'s "not so pleasant" — the plural of a flower.', a: 'Roses', category: '00s-hiphop' },
      { q: 'Nelly\'s 2000 follow-up single requesting accompaniment — three-word title beginning R using a Southern contraction of "with".', a: 'Ride wit Me', alt: ['Ride With Me'], category: '00s-hiphop' },
      { q: 'Flo Rida\'s 2009 #1 sampling Dead or Alive\'s 80s record-on-the-turntable hit — two-word title beginning R that\'s a synonym for "all the way around".', a: 'Right Round', category: '00s-hiphop' },
    ],
    S: [
      { q: 'Eminem\'s 2000 epistolary single about an obsessive fan — sampled Dido.', a: 'Stan', category: '00s-hiphop' },
      { q: 'Kanye West\'s 2007 Daft Punk-sampling #1 — one-word title beginning S meaning "more powerful".', a: 'Stronger', category: '00s-hiphop' },
      { q: 'Jamaican dancehall star surnamed Henriques whose 2002 "Dutty Rock" crossed over globally — full stage name (two first names).', a: 'Sean Paul', category: '00s-hiphop' },
      { q: 'Akon\'s 2006 Eminem-featuring single about slapping someone affectionately.', a: 'Smack That', category: '00s-hiphop' },
      { q: 'Atlanta rapper born DeAndre Cortez Way behind 2007\'s "Crank That" — full stage name.', a: 'Soulja Boy', alt: ['Soulja Boy Tell\'Em'], category: '00s-hiphop' },
      { q: 'Ne-Yo\'s 2005 debut single about a love that\'s making him ill — two-word title beginning S.', a: 'So Sick', category: '00s-hiphop' },
      { q: 'Drake\'s 2009 Trey Songz / Lil Wayne single about being on top — single-word title.', a: 'Successful', category: '00s-hiphop' },
      { q: 'Outkast\'s 2000 "Stankonia" single about being freshly groomed — four-word title beginning S, pairing two synonyms for "newly washed".', a: 'So Fresh, So Clean', alt: ['So Fresh So Clean'], category: '00s-hiphop' },
      { q: 'Outkast\'s 2000 album whose title fuses "stank" and "Atlanta" — a single-word imaginary state.', a: 'Stankonia', category: '00s-hiphop' },
      { q: 'Long Beach rapper born Calvin Broadus who continued his hot run into 2004\'s "R&G (Rhythm & Gangsta)".', a: 'Snoop Dogg', alt: ['Snoop'], category: '00s-hiphop' },
      { q: 'Outkast\'s 2003 double album whose two discs spotlit Big Boi and Andre 3000 — completes "___/The Love Below".', a: 'Speakerboxxx', alt: ['Speakerboxxx/The Love Below'], category: '00s-hiphop' },
      { q: 'Mario\'s 2007 ballad about a girl who\'s got him gone — two-word title beginning S pairing an alluring adjective with an emotion.', a: 'Sexy Love', category: '00s-hiphop' },
      { q: 'Alicia Keys\'s 2001 debut album, named after the key signature of "Fallin\'".', a: 'Songs in A Minor', category: '00s-hiphop' },
    ],
    T: [
      { q: 'Tallahassee-born singer-rapper born Faheem Najm — the auto-tune ambassador behind "Buy U a Drank".', a: 'T-Pain', alt: ['T Pain', 'TPain'], category: '00s-hiphop' },
      { q: 'Virginia producer born Timothy Mosley — Missy Elliott\'s right hand and Justin Timberlake\'s 00s architect.', a: 'Timbaland', category: '00s-hiphop' },
      { q: 'Kanye West\'s 2003 single recorded before his jaw was fully healed from a car crash — three-word title beginning T.', a: 'Through the Wire', category: '00s-hiphop' },
      { q: 'Kanye West\'s 2007 single from "Graduation" featuring Lupe Fiasco about reaching for the heavens — three-word title beginning T.', a: 'Touch the Sky', category: '00s-hiphop' },
      { q: 'Sean Paul\'s 2005 single about rising mercury — single-word title.', a: 'Temperature', category: '00s-hiphop' },
      { q: 'Memphis trio behind 2005\'s Oscar-winning "It\'s Hard out Here for a Pimp" — they took their name from a dark numeric trinity.', a: 'Three 6 Mafia', alt: ['Three Six Mafia'], category: '00s-hiphop' },
      { q: 'Atlanta rapper Clifford Harris Jr. — the self-styled "King of the South" — initialed stage name.', a: 'T.I.', alt: ['T.I', 'TI'], category: '00s-hiphop' },
      { q: 'Miami rapper-mogul born Maurice Young — known as "Mr. Welcome to Miami" with hits like "I\'m a Thug".', a: 'Trick Daddy', category: '00s-hiphop' },
      { q: 'Miami rapper surnamed Taylor — Trick Daddy collaborator known as the "Diamond Princess" — short stage name beginning T.', a: 'Trina', category: '00s-hiphop' },
      { q: 'Virginia R&B singer born Tremaine Neverson whose 2005 "I Gotta Make It" debut launched him — full stage name beginning T.', a: 'Trey Songz', category: '00s-hiphop' },
      { q: 'Mos Def\'s Brooklyn rap partner in Black Star — full stage name beginning T.', a: 'Talib Kweli', category: '00s-hiphop' },
      { q: 'Compton rapper born Jayceon Taylor — Aftermath signee behind 2005\'s "The Documentary" — definite-article stage name.', a: 'The Game', alt: ['Game'], category: '00s-hiphop' },
      { q: 'Pharrell Williams\'s production duo with Chad Hugo, named for the eighth planet — definite-article stage name.', a: 'The Neptunes', alt: ['Neptunes'], category: '00s-hiphop' },
    ],
    U: [
      { q: 'Atlanta R&B megastar born Raymond IV — the man behind "Confessions" and "Yeah!" — single-word stage name beginning U.', a: 'Usher', category: '00s-hiphop' },
      { q: 'Usher\'s 2001 single recognising someone from a dream — completes "U ___ Me".', a: 'U Remind Me', category: '00s-hiphop' },
      { q: 'Usher\'s 2001 ballad about a girl who has him in a bad way — completes "U Got It ___".', a: 'U Got It Bad', category: '00s-hiphop' },
    ],
    V: [
      { q: 'Philadelphia neo-soul singer behind 2002\'s "A Love Story" and the single "Emotional Rollercoaster" — full stage name beginning V.', a: 'Vivian Green', category: '00s-hiphop' },
    ],
    W: [
      { q: 'T.I.\'s 2006 "King" hit about being familiar with the trap — three-word title beginning W.', a: 'What You Know', category: '00s-hiphop' },
      { q: 'T.I.\'s 2008 "Paper Trail" #1 promising to buy his girl anything — two-word title beginning W.', a: 'Whatever You Like', category: '00s-hiphop' },
      { q: 'Eminem\'s 2002 Dr. Dre-produced kiss-off single about being indispensable — two-word title beginning W.', a: 'Without Me', category: '00s-hiphop' },
      { q: 'Pittsburgh rapper born Cameron Thomaz whose 2009 "Deal or No Deal" preceded his major-label breakout.', a: 'Wiz Khalifa', category: '00s-hiphop' },
      { q: 'Unk\'s 2006 Atlanta snap-dance instructional ordering the listener to step outdoors — three-word title beginning W.', a: 'Walk It Out', category: '00s-hiphop' },
      { q: 'Missy Elliott\'s 2002 backwards-hook single from "Under Construction".', a: 'Work It', category: '00s-hiphop' },
      { q: 'Eminem\'s 2009 "Relapse"-cycle Sixties-flavoured single addressed to the listener — three-word title beginning W.', a: 'We Made You', category: '00s-hiphop' },
      { q: 'Sean Paul\'s 2005 single about getting hot — three-word title beginning W with a contracted "burning".', a: 'We Be Burnin\'', alt: ['We Be Burning', 'We Be Burnin'], category: '00s-hiphop' },
      { q: 'DC rapper of Nigerian descent surnamed Akintimehin — XXL Freshman whose 2008 mixtape titled after a Seinfeld trope made his name — four-letter stage name beginning W.', a: 'Wale', category: '00s-hiphop' },
    ],
    Y: [
      { q: 'Usher\'s 2004 Lil Jon and Ludacris-featuring crunk-pop #1 — single-word celebratory shout.', a: 'Yeah!', alt: ['Yeah'], category: '00s-hiphop' },
      { q: 'Atlanta rapper born Jay Wayne Jenkins — "Snowman" behind 2005\'s "Let\'s Get It: Thug Motivation 101".', a: 'Young Jeezy', alt: ['Jeezy'], category: '00s-hiphop' },
      { q: 'Atlanta rapper born Jasiel Robinson — Block Entertainment signee behind 2006\'s "It\'s Goin\' Down".', a: 'Yung Joc', category: '00s-hiphop' },
    ],
  },
};
