import type { RawQuestion } from '../core/packs';

export const music90sPopExtra: Record<string, RawQuestion[]> = {
  A: [
    { q: 'Sarah McLachlan\'s 1998 single from "Surfacing" beginning "Spend all your time waiting / for that second chance".', a: 'Adia', category: 'music' },
    { q: 'Sarah McLachlan\'s 1997 ballad from "Surfacing" used in countless ASPCA commercials, with a heavenly winged-being embrace as its hook.', a: 'Angel', category: 'music' },
    { q: 'Bryan Adams, Rod Stewart and Sting\'s 1993 chart-topping ballad from "The Three Musketeers".', a: 'All for Love', category: 'music' },
    { q: 'Sheryl Crow\'s 1993 breakout single from "Tuesday Night Music Club" celebrating idle pleasures with strangers.', a: 'All I Wanna Do', category: 'music' },
    { q: 'Mariah Carey\'s 1996 emotional cover of Eric Carmen\'s 1975 ballad about loneliness.', a: 'All by Myself', category: 'music' },
    { q: 'Mariah Carey\'s 1996 single from "Daydream" pledging eternal childlike devotion.', a: 'Always Be My Baby', category: 'music' },
    { q: 'Alanis Morissette\'s opening 1995 track from "Jagged Little Pill" — six-word title listing what she truly desires.', a: 'All I Really Want', category: 'music' },
    { q: 'Real McCoy\'s 1994 Eurodance smash featuring the line "here I go again".', a: 'Another Night', category: 'music' },
    { q: 'Backstreet Boys\' 1997 ballad whose chorus pleads "I don\'t care who you are, where you\'re from".', a: 'As Long As You Love Me', category: 'music' },
  ],
  B: [
    { q: 'Britney Spears\' 1999 ballad about waiting for a relationship to feel right — five-word title saying she came into the world destined to bring her partner joy.', a: 'Born to Make You Happy', category: 'music' },
    { q: 'Celine Dion\'s 1996 Diane Warren-penned chart-topper from "Falling into You" thanking a soulmate.', a: 'Because You Loved Me', category: 'music' },
    { q: '98 Degrees\' 1998 top-ten single declaring devotion thanks to the listener.', a: 'Because of You', category: 'music' },
    { q: 'La Bouche\'s 1995 Eurodance hit pleading for a romantic partner all night.', a: 'Be My Lover', category: 'music' },
    { q: 'Sarah McLachlan\'s 1997 lead single from "Surfacing" — three-word title about a romantic enigma.', a: 'Building a Mystery', category: 'music' },
    { q: 'Meredith Brooks\' 1997 alt-pop single self-identifying as a saint, a sinner, and several other contradictions.', a: 'Bitch', category: 'music' },
    { q: 'All Saints\' 1998 single mocking a 3 a.m. text from an ex looking for company.', a: 'Bootie Call', category: 'music' },
    { q: 'S Club 7\'s 1999 debut single about restoring a fading romance.', a: 'Bring It All Back', category: 'music' },
    { q: 'Big Mountain\'s 1994 reggae-pop cover of a Peter Frampton song from "Reality Bites".', a: 'Baby I Love Your Way', category: 'music' },
  ],
  C: [
    { q: 'Mandy Moore\'s 1999 debut single comparing her need for a lover to a sugar craving.', a: 'Candy', category: 'music' },
    { q: 'B*Witched\'s 1998 UK number-one debut whose chorus mixes English with a French phrase.', a: 'C\'est la Vie', category: 'music' },
    { q: 'Semisonic\'s 1998 alt-radio anthem about the bar emptying out at the end of the night.', a: 'Closing Time', category: 'music' },
    { q: 'Dishwalla\'s 1995 alt-rock single about overhearing a woman in a parking lot — three-word title about tallying azure automobiles.', a: 'Counting Blue Cars', category: 'music' },
    { q: 'Mr. President\'s 1996 Eurodance smash named for a tropical drink, pairing a coconut-flavored word with a nonsense partner.', a: 'Coco Jamboo', category: 'music' },
  ],
  D: [
    { q: 'NSYNC\'s 1999 single from their debut album about being haunted by a lost love — three-word title meaning he is pushing himself into madness.', a: 'Drive Myself Crazy', category: 'music' },
    { q: 'Lauryn Hill\'s 1998 number-one single from "The Miseducation" — four-word title naming a 1950s vocal-harmony R&B style, with a parenthetical referring vaguely to a habit.', a: 'Doo Wop (That Thing)', category: 'music', alt: ['Doo Wop'] },
  ],
  E: [
    { q: 'Whitney Houston\'s 1995 single matching the title of its film, about releasing breath — single-word main title plus a repeated nonsense parenthetical.', a: 'Exhale (Shoop Shoop)', category: 'music' },
    { q: 'Mariah Carey\'s 1994 duet with Luther Vandross, a cover of a Diana Ross / Lionel Richie 1981 ballad.', a: 'Endless Love', category: 'music' },
    { q: 'Bryan Adams\'s 1991 ballad written for "Robin Hood: Prince of Thieves" — title in parentheses opens "(Everything I Do)".', a: '(Everything I Do) I Do It for You', category: 'music', alt: ['Everything I Do I Do It for You'] },
    { q: 'Black Box\'s 1990 house-pop hit with the chant "_____, ride the rhythm" — single-word title repeated.', a: 'Everybody Everybody', category: 'music' },
  ],
  F: [
    { q: 'Britney Spears\' 1999 ballad about a girl picking up the pieces, with a seven-word title evoking a shattered organ\'s deepest place.', a: 'From the Bottom of My Broken Heart', category: 'music' },
    { q: 'Lenny Kravitz\'s 1998 single from "5" — two-word title — about wishing to take wing and depart.', a: 'Fly Away', category: 'music' },
    { q: 'En Vogue\'s 1992 single from "Funky Divas" urging open-mindedness — three-word title commanding the listener to liberate their thinking.', a: 'Free Your Mind', category: 'music' },
  ],
  G: [
    { q: 'NSYNC\'s 1998 sentimental single — parenthetical opening "(God Must Have Spent)".', a: '(God Must Have Spent) A Little More Time on You', category: 'music', alt: ['A Little More Time on You'] },
    { q: 'C+C Music Factory\'s 1990 dance smash whose chorus shouts "everybody dance now".', a: 'Gonna Make You Sweat', category: 'music', alt: ['Gonna Make You Sweat (Everybody Dance Now)'] },
    { q: '2 Unlimited\'s 1991 Eurodance debut single — four-word title — a sports-arena staple telling the crowd to brace themselves for what\'s coming.', a: 'Get Ready for This', category: 'music' },
  ],
  H: [
    { q: 'Alanis Morissette\'s 1995 sweet single from "Jagged Little Pill" — three-word title twisting the usual "heels" idiom for falling in love.', a: 'Head Over Feet', category: 'music' },
    { q: 'Jewel\'s 1998 single from "Spirit" — single-word title about what we use to help each other.', a: 'Hands', category: 'music' },
    { q: 'Hootie & the Blowfish\'s 1994 debut single asking for a partner\'s grip.', a: 'Hold My Hand', category: 'music' },
    { q: 'Mariah Carey\'s 1999 single from "Rainbow" — single-word title about a romantic wrecker.', a: 'Heartbreaker', category: 'music' },
    { q: 'Bryan Adams\'s 1995 single from "Don Juan DeMarco" — a six-word interrogative posed to the listener about deep cherishing of a female partner.', a: 'Have You Ever Really Loved a Woman', category: 'music' },
  ],
  I: [
    { q: 'Sheryl Crow\'s 1996 self-titled second album single questioning whether contentment justifies betrayal.', a: 'If It Makes You Happy', category: 'music' },
    { q: 'Tonic\'s 1996 alt-rock single from "Lemon Parade" — a five-word title wishing a parent might perceive things through the narrator\'s eyes.', a: 'If You Could Only See', category: 'music' },
    { q: 'Edwin McCain\'s 1998 sweeping power ballad — two-word title — beginning "I\'ll…".', a: 'I\'ll Be', category: 'music' },
    { q: 'Goo Goo Dolls\' 1998 single from "City of Angels" about wanting to be felt and known — single-word title.', a: 'Iris', category: 'music' },
    { q: 'Savage Garden\'s 1996 debut single from their self-titled album — three-word title featuring rapid-fire "chic-a-cherry-cola" lyrics, a direct expression of desire for someone.', a: 'I Want You', category: 'music' },
    { q: 'Savage Garden\'s 1999 sweeping ballad from "Affirmation" with the line "before I met you" — five-word title about recognizing soulmate feelings from the start.', a: 'I Knew I Loved You', category: 'music' },
    { q: 'Jessica Simpson\'s 1999 debut single — five-word title declaring a wish to adore someone for all eternity.', a: 'I Wanna Love You Forever', category: 'music' },
    { q: 'Celine Dion and R. Kelly\'s 1998 duet single — three-word title "I\'m Your _____".', a: 'I\'m Your Angel', category: 'music' },
    { q: 'Celine Dion\'s 1996 Jim Steinman-penned epic — seven-word title beginning "It\'s All…".', a: 'It\'s All Coming Back to Me Now', category: 'music' },
    { q: 'Sarah McLachlan\'s 1995/1999 ballad about loved ones who have passed — five-word title promising to keep the listener\'s memory alive.', a: 'I Will Remember You', category: 'music' },
  ],
  J: [
    { q: 'No Doubt\'s 1995 anthem from "Tragic Kingdom" railing against being underestimated for her gender.', a: 'Just a Girl', category: 'music' },
    { q: 'Will Smith\'s 1997 single from "Big Willie Style", a tender song to his son sampling a 1981 Bill Withers / Grover Washington Jr. tune.', a: 'Just the Two of Us', category: 'music' },
  ],
  K: [
    { q: 'Sixpence None the Richer\'s 1998 single famous from "She\'s All That" — two-word title pleading for a smooch.', a: 'Kiss Me', category: 'music' },
    { q: 'Five\'s 1999 UK number-one cover-meets-original — three-word title urging perpetual motion (dropping the final "g").', a: 'Keep On Movin\'', category: 'music', alt: ['Keep On Moving'] },
  ],
  L: [
    { q: 'All Saints\' 1998 cover medley single mixing a Red Hot Chili Peppers song with a Patti LaBelle classic.', a: 'Lady Marmalade', category: 'music' },
    { q: 'Hootie & the Blowfish\'s 1994 second single, a plea to a partner to let her grief out — three-word title.', a: 'Let Her Cry', category: 'music' },
    { q: 'Cranberries\' 1993 international debut single about a one-sided crush — single-word title.', a: 'Linger', category: 'music' },
    { q: 'Backstreet Boys\' 1999 single from "Millennium" — a three-word idiom celebrating fans worldwide, meaning outsized or mythical.', a: 'Larger Than Life', category: 'music' },
  ],
  M: [
    { q: 'Spice Girls\' 1997 tender ballad written for Mother\'s Day — single-word title.', a: 'Mama', category: 'music' },
    { q: 'Will Smith\'s 1998 single sampling The Whispers — single-word title naming a Florida city.', a: 'Miami', category: 'music' },
    { q: 'Crash Test Dummies\' 1993 hit with a hummed-syllable chorus — four repeated identical "Mmm" sounds.', a: 'Mmm Mmm Mmm Mmm', category: 'music' },
    { q: 'Culture Beat\'s 1993 Eurodance number one — title is the name of the unreliable lover, prefixed "Mr.".', a: 'Mr. Vain', category: 'music' },
    { q: 'Sheryl Crow\'s 1998 single from "The Globe Sessions" — three-word title where she affectionately calls an old flame the best error she ever made.', a: 'My Favorite Mistake', category: 'music' },
    { q: 'Extreme\'s 1990 acoustic ballad — three-word title — saying real love is shown beyond what you say aloud.', a: 'More Than Words', category: 'music' },
  ],
  N: [
    { q: 'All Saints\' 1997 UK number-one debut — two-word title repeated, dismissing an unreliable partner.', a: 'Never Ever', category: 'music' },
    { q: '2 Unlimited\'s 1993 Eurodance smash with the shouted "there\'s no limits!" hook.', a: 'No Limit', category: 'music' },
    { q: 'Destiny\'s Child\'s 1997 debut single — repeated-word title — about rebuffing a smooth-talker.', a: 'No, No, No', category: 'music' },
  ],
  O: [
    { q: 'Joan Osborne\'s 1995 single wondering about God riding the bus — four-word title.', a: 'One of Us', category: 'music' },
    { q: 'Hootie & the Blowfish\'s 1995 single from "Cracked Rear View" — six-word title featuring Bob Dylan references, declaring exclusive romantic desire.', a: 'Only Wanna Be with You', category: 'music' },
    { q: 'Steps\' 1998 lovelorn UK hit — three-word title beginning "One for…".', a: 'One for Sorrow', category: 'music' },
    { q: 'The Wallflowers\' 1996 alt-rock single from "Bringing Down the Horse" — two-word title beginning "One…".', a: 'One Headlight', category: 'music' },
  ],
  P: [
    { q: 'Matchbox Twenty\'s 1997 single from "Yourself or Someone Like You" — single-word title about emotional shoving.', a: 'Push', category: 'music' },
    { q: 'Snap!\'s 1990 Eurodance debut single with the iconic "I\'ve got the…" hook — two-word title naming a forceful energy.', a: 'The Power', category: 'music' },
  ],
  R: [
    { q: 'Snap!\'s 1992 Eurodance smash declaring a serpentine girl knows how to move — four-word title.', a: 'Rhythm Is a Dancer', category: 'music' },
    { q: 'Corona\'s 1993 Eurodance hit — five-word title about the pulse of after-dark dancing.', a: 'The Rhythm of the Night', category: 'music' },
    { q: 'Real McCoy\'s 1995 follow-up Eurodance single — two-word title urging escape.', a: 'Run Away', category: 'music' },
    { q: 'Madonna\'s 1992 single from "Erotica" — single-word title evoking a weather phenomenon.', a: 'Rain', category: 'music' },
  ],
  S: [
    { q: 'Britney Spears\' 1999 second single — one-word title — about needing space to think.', a: 'Sometimes', category: 'music' },
    { q: 'Five\'s 1997 debut single — title combines a basketball scoring move with a parenthetical street-slang for the groove.', a: 'Slam Dunk (Da Funk)', category: 'music' },
    { q: 'Spice Girls\' 1998 single demanding a Romeo halt — single-word title.', a: 'Stop', category: 'music' },
    { q: 'Lisa Loeb\'s 1994 number-one single from "Reality Bites" — a plea for someone not to leave, with a parenthetical aside confessing her longing.', a: 'Stay (I Missed You)', category: 'music', alt: ['Stay'] },
    { q: 'Sheryl Crow\'s 1994 ballad from her debut album about endurance in love — two-word title.', a: 'Strong Enough', category: 'music' },
    { q: 'No Doubt\'s 1995 single from "Tragic Kingdom" about creepy crawlies and obsessive love — single-word title.', a: 'Spiderwebs', category: 'music' },
    { q: 'Backstreet Boys\' 1999 single — seven-word title beginning "Show Me the…".', a: 'Show Me the Meaning of Being Lonely', category: 'music' },
    { q: 'Natalie Imbruglia\'s 1998 follow-up single from "Left of the Middle" — single-word title evoking a haze.', a: 'Smoke', category: 'music' },
  ],
  T: [
    { q: 'Steps\' 1999 UK number-one cover of a 1979 Bee Gees disco song — single-word title.', a: 'Tragedy', category: 'music' },
    { q: 'Spice Girls\' 1997 single — two-word title — admitting affection has become overwhelming.', a: 'Too Much', category: 'music' },
    { q: 'Alanis Morissette\'s 1998 lead single from "Supposed Former Infatuation Junkie" — abbreviated two-word title.', a: 'Thank U', category: 'music' },
    { q: 'Spin Doctors\' 1992 single from "Pocket Full of Kryptonite" naming royal siblings.', a: 'Two Princes', category: 'music' },
    { q: 'Sixpence None the Richer\'s 1999 cover of an original by The La\'s — three-word title pointing out a woman walking by (with the line "racing through my brain").', a: 'There She Goes', category: 'music' },
    { q: 'A name shared by ballads from Huey Lewis, Frankie Goes to Hollywood, Jennifer Rush, Celine Dion and others — four-word title about romance\'s strength.', a: 'The Power of Love', category: 'music' },
    { q: 'Mariah Carey and Joe & 98 Degrees\' 1999 collaboration — five-word title expressing gratitude to the heavens for discovering one\'s soulmate.', a: 'Thank God I Found You', category: 'music' },
  ],
  U: [
    { q: 'All Saints\' 1998 cover of a Red Hot Chili Peppers song from "Blood Sugar Sex Magik" — three-word title set beneath an LA overpass.', a: 'Under the Bridge', category: 'music' },
    { q: 'EMF\'s 1990 baggy-pop debut single — single-word title — about an astonishing romance, later a Vanilla Ice / Chips Ahoy! ad staple.', a: 'Unbelievable', category: 'music' },
  ],
  V: [
    { q: 'Spice Girls\' 1998 farewell-tinged single with Spanish flamenco flavour — two-word title pairing a Latin "long live" exclamation with eternity.', a: 'Viva Forever', category: 'music' },
    { q: 'Madonna\'s 1990 single from "I\'m Breathless" — single-word title name-checking Garbo and Monroe over a house beat.', a: 'Vogue', category: 'music' },
  ],
  W: [
    { q: 'Haddaway\'s 1993 Eurodance smash whose chorus famously asks "_____ — baby don\'t hurt me".', a: 'What Is Love', category: 'music' },
    { q: 'Christina Aguilera\'s 1999 second single — four-word title naming the desires of a young woman ("Thanks for letting me be me…").', a: 'What a Girl Wants', category: 'music' },
    { q: 'Paula Cole\'s 1997 single asking about a vanished masculine archetype — six-word title (a question) about the disappearance of Wild West gunslingers.', a: 'Where Have All the Cowboys Gone?', category: 'music', alt: ['Where Have All the Cowboys Gone'] },
    { q: 'Mariah Carey\'s 1994 cover of a Badfinger song from her album "Music Box" — two-word title — "I can\'t live, if living is _____".', a: 'Without You', category: 'music' },
    { q: 'Spice Girls\' 1997 second-album single questioning a starstruck wannabe — six-word title beginning "Who Do…".', a: 'Who Do You Think You Are', category: 'music' },
    { q: 'Jewel\'s 1996 debut single from "Pieces of You" — a five-word interrogative about who might rescue one\'s spirit.', a: 'Who Will Save Your Soul', category: 'music' },
    { q: 'Will Smith\'s 1999 movie-titled single from the Robert Conrad remake.', a: 'Wild Wild West', category: 'music' },
    { q: 'Five\'s 1998 UK number-three single — five-word title about what happens once illumination ceases.', a: 'When the Lights Go Out', category: 'music' },
    { q: 'Natalie Imbruglia\'s 1998 follow-up single — four-word title expressing the wish to be present somewhere far away.', a: 'Wishing I Was There', category: 'music' },
  ],
  Y: [
    { q: 'New Radicals\' 1998 sole hit from "Maybe You\'ve Been Brainwashed Too" — five-word title beginning "You Get…".', a: 'You Get What You Give', category: 'music' },
    { q: 'Jewel\'s 1996 second single from "Pieces of You" — five-word title about destined romantic compatibility.', a: 'You Were Meant for Me', category: 'music' },
    { q: 'Toni Braxton\'s 1996 sultry single — four-word title saying her lover is sending her into a euphoric state.', a: 'You\'re Makin\' Me High', category: 'music' },
    { q: 'White Town\'s 1997 surprise number-one in the UK — two-word title with a sample of an Egyptian dance band.', a: 'Your Woman', category: 'music' },
  ],
  Z: [
    { q: 'Cherry Poppin\' Daddies\' 1997 swing-revival single — three-word title naming the kind of disturbance involving 1940s baggy-trousered jazz attire.', a: 'Zoot Suit Riot', category: 'music' },
    { q: 'Cranberries\' 1994 protest-rock single from "No Need to Argue" — single-word title evoking the undead.', a: 'Zombie', category: 'music' },
  ],
};
