import type { RawPack } from '../core/packs';

export const music90sAltPack: RawPack = {
  id: 'music-90s-alt',
  name: '90s Grunge & Alt',
  description: 'Grunge, alternative rock and post-grunge of the 1990s.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎸',
  accent: '#475569',
  letters: {
    A: [
      { q: 'Seattle band fronted by Layne Staley behind "Man in the Box" and "Rooster".', a: 'Alice in Chains', category: 'music', difficulty: 2 },
      { q: 'Pearl Jam\'s breakthrough opener on "Ten", a son\'s defiant declaration of survival.', a: 'Alive', category: 'music', difficulty: 2 },
      { q: 'Red Hot Chili Peppers single from their 1999 album "Californication" about touring the globe.', a: 'Around the World', category: 'music', difficulty: 3 },
      { q: 'Counting Crows\' 1993 debut album, "August and Everything ___".', a: 'After', category: 'music', difficulty: 4 },
    ],
    B: [
      { q: 'Green Day single from "Dookie" whose chorus begins "Do you have the time…".', a: 'Basket Case', category: 'music', difficulty: 2 },
      { q: 'Hip-hop trio of Mike D, MCA and Ad-Rock whose 1994 album "Ill Communication" gave us "Sabotage".', a: 'Beastie Boys', category: 'music', difficulty: 2 },
      { q: 'Stone Temple Pilots ballad from "Purple" with the line "Conversations kill".', a: 'Big Empty', category: 'music', difficulty: 3 },
      { q: 'Foo Fighters single about the singer himself, released on their 1995 self-titled debut.', a: 'Big Me', category: 'music', difficulty: 3 },
      { q: 'Pearl Jam song from "Ten" with no chorus, named for a single colour.', a: 'Black', category: 'music', difficulty: 2 },
      { q: 'Soundgarden\'s 1994 chart-topper from "Superunknown" with the line "In my eyes, indisposed".', a: 'Black Hole Sun', category: 'music', difficulty: 2 },
      { q: 'Nirvana\'s 1989 debut studio album, released on Sub Pop.', a: 'Bleach', category: 'music', difficulty: 3 },
      { q: 'Damon Albarn-fronted British band behind "Song 2" and "Parklife".', a: 'Blur', category: 'music', difficulty: 2 },
      { q: 'Weezer song from the Blue Album whose video pays homage to "Happy Days".', a: 'Buddy Holly', category: 'music', difficulty: 2 },
      { q: 'Smashing Pumpkins single from "Mellon Collie" with the lyric "Despite all my rage…".', a: 'Bullet with Butterfly Wings', category: 'music', difficulty: 3 },
      { q: 'Rage Against the Machine single from "Evil Empire" with the line "Rally round the family".', a: 'Bulls on Parade', category: 'music', difficulty: 3 },
      { q: 'London-formed band fronted by Gavin Rossdale whose 1994 debut was "Sixteen Stone".', a: 'Bush', category: 'music', difficulty: 2 },
      { q: 'Smashing Pumpkins frontman, the bald guitarist-singer of the band.', a: 'Billy Corgan', category: 'music', difficulty: 2 },
      { q: 'Pearl Jam song from "Vitalogy" about being self-employed; opens "Hey, hey…".', a: 'Better Man', category: 'music', difficulty: 3 },
      { q: 'Louisiana band whose 1995 single "Good" was a college-rock hit; their name compares themselves to a poet.', a: 'Better Than Ezra', category: 'music', difficulty: 4 },
    ],
    C: [
      { q: 'Oasis ballad from "(What\'s the Story) Morning Glory?" that closes the album with bubbly imagery in the sky.', a: 'Champagne Supernova', category: 'music', difficulty: 3 },
      { q: 'Soundgarden frontman who later led Audioslave; died in 2017.', a: 'Chris Cornell', category: 'music', difficulty: 2 },
      { q: 'Bush single from "Sixteen Stone" with the line "I don\'t want to come back down from this cloud".', a: 'Comedown', category: 'music', difficulty: 3 },
      { q: 'Nirvana single from "Nevermind" whose lyric tells the listener "as you were" and "as a friend".', a: 'Come as You Are', category: 'music', difficulty: 2 },
      { q: 'Adam Duritz\'s band whose 1993 debut "August and Everything After" included "Mr. Jones".', a: 'Counting Crows', category: 'music', difficulty: 2 },
      { q: 'Irish band fronted by Dolores O\'Riordan who recorded "Linger" and "Zombie".', a: 'Cranberries', category: 'music', difficulty: 2, alt: ['the cranberries'] },
      { q: 'Hole frontwoman who married Kurt Cobain in 1992.', a: 'Courtney Love', category: 'music', difficulty: 2 },
      { q: 'Radiohead breakthrough single from their 1993 debut album "Pablo Honey".', a: 'Creep', category: 'music', difficulty: 2 },
    ],
    D: [
      { q: 'Nirvana drummer who later founded Foo Fighters.', a: 'Dave Grohl', category: 'music', difficulty: 1 },
      { q: 'Alice in Chains\' second studio album, released in 1992.', a: 'Dirt', category: 'music', difficulty: 3 },
      { q: 'Irish singer of The Cranberries who died in 2018.', a: "Dolores O'Riordan", category: 'music', difficulty: 3, alt: ['dolores oriordan'] },
      { q: 'Green Day\'s breakthrough 1994 album on Reprise Records.', a: 'Dookie', category: 'music', difficulty: 2 },
      { q: 'Alice in Chains ballad from their 1992 album "Dirt" beginning "Bury me softly in this womb".', a: 'Down in a Hole', category: 'music', difficulty: 3 },
      { q: 'Oasis song from "Definitely Maybe" later released in the wake of Princess Diana\'s death.', a: "Don't Look Back in Anger", category: 'music', difficulty: 3 },
      { q: 'No Doubt single from "Tragic Kingdom" pleading not to be told it\'s over.', a: "Don't Speak", category: 'music', difficulty: 2 },
      { q: 'Cranberries song that opens "Oh my life is changing every day…".', a: 'Dreams', category: 'music', difficulty: 3 },
    ],
    E: [
      { q: 'Pearl Jam frontman, born December 23 1964 in Evanston, Illinois.', a: 'Eddie Vedder', category: 'music', difficulty: 2 },
      { q: 'Foo Fighters single from "The Colour and the Shape" written by Dave Grohl about his then-wife.', a: 'Everlong', category: 'music', difficulty: 2 },
      { q: 'Pearl Jam single from "Ten" about a homeless man drifting through life.', a: 'Even Flow', category: 'music', difficulty: 3 },
    ],
    F: [
      { q: 'San Francisco funk-metal band behind 1992\'s "Angel Dust" and "Epic", fronted by Mike Patton.', a: 'Faith No More', category: 'music', difficulty: 3 },
      { q: 'Soundgarden track from "Superunknown" whose name describes a gloomy slump.', a: 'Fell on Black Days', category: 'music', difficulty: 3 },
      { q: 'Dave Grohl\'s post-Nirvana band, formed in 1994.', a: 'Foo Fighters', category: 'music', difficulty: 2 },
    ],
    G: [
      { q: 'Bush singer who later married Gwen Stefani.', a: 'Gavin Rossdale', category: 'music', difficulty: 3 },
      { q: 'Bush single from "Sixteen Stone" with the line "Must be your skin I\'m sinkin\' in".', a: 'Glycerine', category: 'music', difficulty: 3 },
      { q: 'Buffalo band behind "Iris" and "Name", a duo of Robby Takac and John Rzeznik plus drummer.', a: 'Goo Goo Dolls', category: 'music', difficulty: 2 },
      { q: 'Green Day acoustic single from "Nimrod" whose alternate title is "Time of Your Life".', a: 'Good Riddance', category: 'music', difficulty: 3, alt: ['good riddance time of your life', 'time of your life'] },
      { q: 'Berkeley pop-punk trio of Billie Joe, Mike and Tré.', a: 'Green Day', category: 'music', difficulty: 1 },
      { q: 'No Doubt frontwoman with the platinum-blonde hair and bindi.', a: 'Gwen Stefani', category: 'music', difficulty: 2 },
      { q: 'Shirley Manson-fronted Wisconsin band behind "Stupid Girl" and "Only Happy When It Rains".', a: 'Garbage', category: 'music', difficulty: 2 },
    ],
    H: [
      { q: 'Nirvana single from "In Utero" whose video features a man in a Santa hat on a cross.', a: 'Heart-Shaped Box', category: 'music', difficulty: 3, alt: ['heart shaped box'] },
      { q: 'Courtney Love\'s band who released "Live Through This" in 1994.', a: 'Hole', category: 'music', difficulty: 3 },
    ],
    I: [
      { q: 'Nirvana track from "Nevermind" whose chorus describes a man who likes "all our pretty songs".', a: 'In Bloom', category: 'music', difficulty: 3 },
      { q: 'Stone Temple Pilots single from "Purple" with the line "Feelin\' like a hand in rusted shame".', a: 'Interstate Love Song', category: 'music', difficulty: 3 },
      { q: 'Green Day\'s 1995 follow-up album to "Dookie".', a: 'Insomniac', category: 'music', difficulty: 3 },
      { q: 'Nirvana\'s 1993 final studio album.', a: 'In Utero', category: 'music', difficulty: 2 },
      { q: 'Goo Goo Dolls 1998 ballad written for the film "City of Angels".', a: 'Iris', category: 'music', difficulty: 2 },
      { q: 'Foo Fighters single from their 1995 self-titled debut; the title promises persistence.', a: "I'll Stick Around", category: 'music', difficulty: 4 },
    ],
    J: [
      { q: 'Pearl Jam song from "Ten" about a boy who "spoke in class today".', a: 'Jeremy', category: 'music', difficulty: 2 },
      { q: 'Perry Farrell\'s LA band behind "Been Caught Stealing".', a: "Jane's Addiction", category: 'music', difficulty: 3, alt: ['janes addiction'] },
      { q: 'No Doubt single from "Tragic Kingdom" with the line "Take this pink ribbon off my eyes".', a: 'Just a Girl', category: 'music', difficulty: 3 },
    ],
    K: [
      { q: 'Radiohead single from "OK Computer" whose chorus pleads "for a minute there I lost myself".', a: 'Karma Police', category: 'music', difficulty: 2 },
      { q: 'Rage Against the Machine\'s most famous single, from their 1992 debut album.', a: 'Killing in the Name', category: 'music', difficulty: 2 },
      { q: 'Nirvana bassist, the third founding member alongside the singer and drummer.', a: 'Krist Novoselic', category: 'music', difficulty: 3 },
      { q: 'Nirvana frontman who died in April 1994.', a: 'Kurt Cobain', category: 'music', difficulty: 1 },
    ],
    L: [
      { q: 'Alice in Chains frontman who died in 2002.', a: 'Layne Staley', category: 'music', difficulty: 3 },
      { q: 'Cranberries single from "Everybody Else Is Doing It, So Why Can\'t We?" with the lyric "If you, if you could return".', a: 'Linger', category: 'music', difficulty: 3 },
      { q: 'Pennsylvania band whose 1994 album "Throwing Copper" produced "Lightning Crashes".', a: 'Live', category: 'music', difficulty: 3 },
      { q: 'Oasis single from "Definitely Maybe" that opens "Maybe I don\'t really want to know…".', a: 'Live Forever', category: 'music', difficulty: 3 },
      { q: 'Younger Oasis brother, the lead singer.', a: 'Liam Gallagher', category: 'music', difficulty: 2 },
    ],
    M: [
      { q: 'Alice in Chains single from "Dirt" with the lyric "Jesus Christ, deny your maker".', a: 'Man in the Box', category: 'music', difficulty: 3 },
      { q: 'Smashing Pumpkins\' sprawling 1995 double album, titled "___ and the Infinite Sadness".', a: 'Mellon Collie', category: 'music', difficulty: 3, alt: ['mellon collie and the infinite sadness'] },
      { q: 'Rob Thomas\'s band behind "3 AM" and "Push" from "Yourself or Someone Like You".', a: 'Matchbox Twenty', category: 'music', difficulty: 3, alt: ['matchbox 20'] },
      { q: 'Foo Fighters single from "The Colour and the Shape" whose chorus growls "Why don\'t you do me a favor?".', a: 'Monkey Wrench', category: 'music', difficulty: 3 },
      { q: 'Hope Sandoval-fronted dream-pop duo of "Fade Into You" fame.', a: 'Mazzy Star', category: 'music', difficulty: 3 },
    ],
    N: [
      { q: 'Goo Goo Dolls single about a forgotten old friend, from 1995\'s "A Boy Named Goo".', a: 'Name', category: 'music', difficulty: 3 },
      { q: 'Nirvana\'s breakthrough 1991 album on DGC.', a: 'Nevermind', category: 'music', difficulty: 1 },
      { q: 'Green Day\'s 1997 album that included "Good Riddance".', a: 'Nimrod', category: 'music', difficulty: 3 },
      { q: 'Aberdeen, Washington trio of Cobain, Novoselic and Grohl.', a: 'Nirvana', category: 'music', difficulty: 1 },
      { q: 'Anaheim band fronted by Gwen Stefani whose 1995 album was "Tragic Kingdom".', a: 'No Doubt', category: 'music', difficulty: 2 },
      { q: 'Older Oasis brother, the guitarist and main songwriter.', a: 'Noel Gallagher', category: 'music', difficulty: 2 },
    ],
    O: [
      { q: 'Manchester band of the Gallagher brothers.', a: 'Oasis', category: 'music', difficulty: 1 },
      { q: 'Radiohead\'s 1997 third studio album, widely cited as one of the greatest of all time.', a: 'OK Computer', category: 'music', difficulty: 2 },
    ],
    P: [
      { q: 'Radiohead song from "OK Computer" subtitled with two adjectives joined by a comma.', a: 'Paranoid Android', category: 'music', difficulty: 3 },
      { q: 'Seattle quintet of Eddie Vedder, Stone Gossard, Jeff Ament, Mike McCready and Dave Krusen on debut.', a: 'Pearl Jam', category: 'music', difficulty: 1 },
      { q: 'Black Francis-fronted Boston band whose "Doolittle" influenced grunge\'s loud-quiet-loud formula.', a: 'Pixies', category: 'music', difficulty: 3 },
      { q: 'Stone Temple Pilots\' breakthrough single from their 1992 debut "Core".', a: 'Plush', category: 'music', difficulty: 3 },
      { q: 'Stone Temple Pilots\' 1994 second studio album, named for a colour.', a: 'Purple', category: 'music', difficulty: 3 },
    ],
    R: [
      { q: 'LA rap-metal band of Zack de la Rocha and Tom Morello.', a: 'Rage Against the Machine', category: 'music', difficulty: 2 },
      { q: 'Athens, Georgia band of Michael Stipe behind "Losing My Religion".', a: 'R.E.M.', category: 'music', difficulty: 2, alt: ['rem'] },
      { q: 'LA funk-rock band of Anthony Kiedis and Flea.', a: 'Red Hot Chili Peppers', category: 'music', difficulty: 2 },
      { q: 'Thom Yorke\'s Abingdon-formed band behind "Creep" and "Karma Police".', a: 'Radiohead', category: 'music', difficulty: 2 },
      { q: 'Weezer frontman, the bespectacled singer-guitarist behind "Buddy Holly".', a: 'Rivers Cuomo', category: 'music', difficulty: 3 },
      { q: 'Alice in Chains single from "Dirt" inspired by guitarist Jerry Cantrell\'s father\'s Vietnam service.', a: 'Rooster', category: 'music', difficulty: 3 },
    ],
    S: [
      { q: 'Weezer single from the Blue Album whose chorus repeats the title as an apologetic plea.', a: "Say It Ain't So", category: 'music', difficulty: 3 },
      { q: 'Smashing Pumpkins\' 1993 second studio album.', a: 'Siamese Dream', category: 'music', difficulty: 2 },
      { q: 'Bush\'s 1994 debut album.', a: 'Sixteen Stone', category: 'music', difficulty: 3 },
      { q: 'Billy Corgan\'s Chicago band who recorded "Today" and "1979".', a: 'Smashing Pumpkins', category: 'music', difficulty: 2, alt: ['the smashing pumpkins'] },
      { q: 'Nirvana\'s most famous single, the opening track of "Nevermind".', a: 'Smells Like Teen Spirit', category: 'music', difficulty: 1 },
      { q: 'Thurston Moore-fronted New York noise-rock band who recorded "Goo" and "Dirty".', a: 'Sonic Youth', category: 'music', difficulty: 3 },
      { q: 'Blur 1997 single whose chorus is just "woo-hoo" repeated.', a: 'Song 2', category: 'music', difficulty: 3 },
      { q: 'Seattle band of Chris Cornell and Kim Thayil.', a: 'Soundgarden', category: 'music', difficulty: 2 },
      { q: 'Soundgarden single from "Superunknown" about a one-man band on a Seattle pier.', a: 'Spoonman', category: 'music', difficulty: 3 },
      { q: 'No Doubt single from "Tragic Kingdom" with the line "Communication, telephone, telephone".', a: 'Spiderwebs', category: 'music', difficulty: 3 },
      { q: 'Stone Temple Pilots\' lead vocalist, who later sang for Velvet Revolver; died in 2015.', a: 'Scott Weiland', category: 'music', difficulty: 4, alt: ['weiland'] },
      { q: 'Long Beach ska-punk band behind "What I Got" whose frontman Bradley Nowell died in 1996.', a: 'Sublime', category: 'music', difficulty: 3 },
      { q: 'Soundgarden\'s commercially huge 1994 album.', a: 'Superunknown', category: 'music', difficulty: 3 },
      { q: 'Armenian-American LA band whose self-titled 1998 debut launched their career.', a: 'System of a Down', category: 'music', difficulty: 3 },
      { q: 'Stone Temple Pilots, often abbreviated by this three-letter initialism.', a: 'STP', category: 'music', difficulty: 3, alt: ['stone temple pilots'] },
      { q: 'Scott Weiland\'s LA band who recorded "Plush" and "Vasoline".', a: 'Stone Temple Pilots', category: 'music', difficulty: 2 },
    ],
    T: [
      { q: 'Pearl Jam\'s 1991 debut album.', a: 'Ten', category: 'music', difficulty: 2 },
      { q: 'Radiohead\'s 1995 second studio album.', a: 'The Bends', category: 'music', difficulty: 3 },
      { q: 'Smashing Pumpkins single from "Siamese Dream" whose video features the band painting an ice-cream truck.', a: 'Today', category: 'music', difficulty: 3 },
      { q: 'LA prog-metal band of Maynard James Keenan behind 1996\'s "Ænima".', a: 'Tool', category: 'music', difficulty: 3 },
      { q: 'Smashing Pumpkins single from "Mellon Collie" addressed to the audience twice in its title.', a: 'Tonight, Tonight', category: 'music', difficulty: 3, alt: ['tonight tonight'] },
      { q: 'Radiohead\'s Oxfordshire singer, the high-voiced frontman.', a: 'Thom Yorke', category: 'music', difficulty: 2 },
    ],
    U: [
      { q: 'Weezer single from the Blue Album also known as "The Sweater Song".', a: 'Undone', category: 'music', difficulty: 3, alt: ['undone the sweater song', 'the sweater song'] },
    ],
    V: [
      { q: 'Pearl Jam\'s 1993 second studio album, often stylized with a period.', a: 'Vs.', category: 'music', difficulty: 3, alt: ['vs'] },
      { q: 'Pearl Jam\'s 1994 third studio album.', a: 'Vitalogy', category: 'music', difficulty: 3 },
      { q: 'Stone Temple Pilots single from "Purple" whose title is a brand of jelly.', a: 'Vasoline', category: 'music', difficulty: 3 },
      { q: 'Chicago band of Louise Post and Nina Gordon behind 1994\'s "American Thighs".', a: 'Veruca Salt', category: 'music', difficulty: 4 },
    ],
    W: [
      { q: 'LA band of Rivers Cuomo behind the Blue Album and "Pinkerton".', a: 'Weezer', category: 'music', difficulty: 2 },
      { q: 'Green Day single from "Dookie" whose narrator lives in a sewer.', a: 'Welcome to Paradise', category: 'music', difficulty: 3 },
      { q: 'Oasis\'s biggest single, from "(What\'s the Story) Morning Glory?".', a: 'Wonderwall', category: 'music', difficulty: 2 },
      { q: 'Alice in Chains track from "Dirt" with the chorus "Into the flood again".', a: 'Would?', category: 'music', difficulty: 3, alt: ['would'] },
    ],
    Z: [
      { q: 'Cranberries protest song about The Troubles, from 1994\'s "No Need to Argue".', a: 'Zombie', category: 'music', difficulty: 2 },
    ],
  },
};
