import type { RawPack } from '../core/packs';

export const music10sHipHopPack: RawPack = {
  id: 'music-10s-hiphop',
  name: '2010s Hip-Hop & R&B',
  description: 'Streaming-era hip-hop and R&B, 2010–2019.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🔥',
  accent: '#f97316',
  letters: {
    A: [
      { q: 'Kendrick Lamar\'s 2015 protest anthem from "To Pimp a Butterfly" — "We gon\' be ___".', a: 'Alright', category: 'music' },
      { q: 'Travis Scott\'s 2015 breakout single from his debut album "Rodeo".', a: 'Antidote', category: 'music' },
      { q: 'Nicki Minaj\'s 2014 single sampling Sir Mix-a-Lot\'s "Baby Got Back".', a: 'Anaconda', category: 'music' },
      { q: 'Travis Scott\'s 2018 chart-topping third studio album, named after a defunct Houston theme park.', a: 'Astroworld', category: 'music' },
      { q: 'Childish Gambino\'s 2016 funk-soul album, full title "___ My Love!".', a: 'Awaken', category: 'music', alt: ['Awaken My Love'] },
      { q: 'Harlem rapper born Rakim Mayers — released "Long.Live.A$AP" in 2013.', a: 'A$AP Rocky', category: 'music', alt: ['ASAP Rocky'] },
      { q: 'A$AP Rocky\'s Harlem hip-hop collective and crew name.', a: 'A$AP Mob', category: 'music', alt: ['ASAP Mob'] },
      { q: 'J. Cole\'s 2018 lead single from "KOD" — three-letter cash-machine title.', a: 'ATM', category: 'music' },
      { q: 'T.I.\'s 2014 single featuring Young Thug — "I ain\'t worried ___".', a: 'About the Money', category: 'music', alt: ['About The Money'] },
      { q: 'Chance the Rapper\'s 2013 mixtape with "Cocoa Butter Kisses" — "___ Rap".', a: 'Acid Rap', category: 'music' },
      { q: 'Drake\'s 2013 album closer from "Nothing Was the Same" featuring 2 Chainz and Big Sean — "All ___".', a: 'All Me', category: 'music' },
      { q: 'California rapper-singer-drummer (real first name Brandon); 2016 album "Malibu".', a: 'Anderson .Paak', category: 'music', alt: ['Anderson Paak'] },
    ],
    B: [
      { q: 'Cardi B\'s 2017 breakout No. 1 single — "those is bloody shoes".', a: 'Bodak Yellow', category: 'music' },
      { q: 'Migos\'s 2016 trap smash featuring Lil Uzi Vert — "Rain drop, drop top".', a: 'Bad and Boujee', category: 'music' },
      { q: 'Post Malone\'s 2018 single from "beerbongs & bentleys" — "I\'m a lot ___ now".', a: 'Better Now', category: 'music' },
      { q: 'Nicki Minaj, Jessie J and Ariana Grande\'s 2014 collaboration with "boom-clap" hook.', a: 'Bang Bang', category: 'music' },
      { q: 'H.E.R. & Daniel Caesar\'s 2017 Grammy-winning R&B duet about love being a particular component of something.', a: 'Best Part', category: 'music' },
      { q: 'Ella Mai\'s 2018 R&B hit produced by DJ Mustard — "Did you fall in love with me?".', a: 'Boo\'d Up', category: 'music', alt: ['Booed Up'] },
      { q: 'Kendrick Lamar track from "good kid, m.A.A.d city" — "All my life I want money and power."', a: 'Backseat Freestyle', category: 'music' },
      { q: 'Kanye West\'s 2013 "Yeezus" lead single — "I\'m a god".', a: 'Black Skinhead', category: 'music' },
      { q: 'Cardi B\'s 2018 piano ballad from "Invasion of Privacy" addressing Offset cheating.', a: 'Be Careful', category: 'music' },
      { q: 'Nicki Minaj\'s 2018 Notorious B.I.G.–sampling track listing male rappers, named after her doll-themed alter ego.', a: 'Barbie Dreams', category: 'music' },
      { q: 'Kanye West\'s 2013 "Yeezus" closer sampling Charlie Wilson — "Uh-huh honey".', a: 'Bound 2', category: 'music' },
      { q: 'Drake\'s 2015 mixtape track with Future — "Big ___".', a: 'Big Rings', category: 'music' },
    ],
    C: [
      { q: 'Post Malone\'s 2017 No. 1 single featuring Quavo — "We were way too young, we were just ___".', a: 'Congratulations', category: 'music' },
      { q: 'Post Malone\'s 2019 jangly soft-rock hit — "We couldn\'t turn around \'til we were upside down".', a: 'Circles', category: 'music' },
      { q: 'Nicki Minaj\'s 2018 single with martial-arts video — Hong Kong fighting-game name reference.', a: 'Chun-Li', category: 'music' },
      { q: 'Solange\'s 2016 single from "A Seat at the Table" — "I just want to fly".', a: 'Cranes in the Sky', category: 'music' },
      { q: 'Frank Ocean\'s 2017 single tied to a fashion-house double-C — "I see both sides like ___".', a: 'Chanel', category: 'music' },
      { q: 'J. Cole\'s 2013 single from "Born Sinner" featuring TLC — about not being ashamed of teeth.', a: 'Crooked Smile', category: 'music' },
      { q: 'Lizzo\'s 2019 album title and single — four-word phrase starting with an affectionate slang contraction meaning "because".', a: 'Cuz I Love You', category: 'music' },
      { q: 'Migos\'s breakthrough 2017 album, home to "Bad and Boujee".', a: 'Culture', category: 'music' },
      { q: 'Janelle Monáe\'s 2018 single from "Dirty Computer" — three adjectives describing existence, last word means a person\'s lifetime.', a: 'Crazy Classic Life', category: 'music' },
      { q: 'SZA\'s 2017 Grammy-nominated debut studio album on TDE.', a: 'CTRL', category: 'music', alt: ['Ctrl'] },
      { q: '2Pac-sampling XXXTentacion 2018 single — single word, present-participle title.', a: 'Changes', category: 'music' },
    ],
    D: [
      { q: 'Kendrick Lamar\'s 2017 album whose title is a single word in all caps with a full stop.', a: 'DAMN.', category: 'music', alt: ['DAMN', 'Damn'] },
      { q: 'Kendrick Lamar\'s 2017 "DAMN." track — three-letter biological acronym.', a: 'DNA.', category: 'music', alt: ['DNA'] },
      { q: 'Beyoncé\'s 2016 "Lemonade" track honoring her father — country-leaning two-word title.', a: 'Daddy Lessons', category: 'music' },
      { q: 'Future\'s 2015 album whose title abbreviates "Dirty Sprite 2".', a: 'DS2', category: 'music' },
      { q: 'Solange\'s 2016 "A Seat at the Table" song asserting body autonomy.', a: 'Don\'t Touch My Hair', category: 'music' },
      { q: 'Beyoncé\'s 2013 self-titled hit with Jay-Z — "watermelon" lyric.', a: 'Drunk in Love', category: 'music' },
      { q: 'Charlotte rapper born Jonathan Kirk who broke through with 2019\'s "Suge".', a: 'DaBaby', category: 'music' },
      { q: 'Bryson Tiller\'s 2015 PartyNextDoor-sampling single — "___ play with her".', a: 'Don\'t', category: 'music' },
      { q: 'Drake & Future\'s 2015 "What a Time to Be Alive" track — gemstones plus a present-participle verb meaning moving rhythmically.', a: 'Diamonds Dancing', category: 'music' },
      { q: 'Toronto rapper born Aubrey Graham who released "Take Care" in 2011.', a: 'Drake', category: 'music' },
      { q: 'Compton hip-hop legend, producer of Kendrick Lamar and Eminem; released "Compton" in 2015.', a: 'Dr. Dre', category: 'music', alt: ['Dre'] },
    ],
    E: [
      { q: 'Kendrick Lamar\'s 2017 "DAMN." track featuring U2 production — single-word capitalized title with full stop.', a: 'ELEMENT.', category: 'music', alt: ['ELEMENT', 'Element'] },
      { q: 'Drake\'s 2015 mixtape track from "If You\'re Reading This It\'s Too Late" — "I got ___".', a: 'Energy', category: 'music' },
      { q: 'The Weeknd\'s 2015 single from the "Fifty Shades of Grey" soundtrack.', a: 'Earned It', category: 'music' },
      { q: 'Bryson Tiller\'s 2015 "Trapsoul" single — "You and your man on bad terms".', a: 'Exchange', category: 'music' },
      { q: 'L.A. rapper born Thebe Kgositsile, formerly of Odd Future — dropped "Doris" in 2013.', a: 'Earl Sweatshirt', category: 'music' },
      { q: 'Detroit rapper-producer born Marshall Mathers whose 2010 album "Recovery" was the year\'s best-seller.', a: 'Eminem', category: 'music', alt: ['Marshall Mathers', 'Slim Shady'] },
    ],
    F: [
      { q: 'Beyoncé\'s 2016 "Lemonade" song with the "I came to slay" hook.', a: 'Formation', category: 'music' },
      { q: 'Beyoncé\'s 2013 self-titled track featuring Chimamanda Ngozi Adichie\'s definition of feminism.', a: 'Flawless', category: 'music', alt: ['***Flawless'] },
      { q: 'Jay-Z\'s 2017 "4:44" track tackling generational wealth featuring Beyoncé.', a: 'Family Feud', category: 'music' },
      { q: 'Tyler, the Creator\'s 2017 album with "See You Again" and "Boredom".', a: 'Flower Boy', category: 'music' },
      { q: 'XXXTentacion\'s 2018 posthumous-charting single — present-participle verb of descent, repeated three times in the hook.', a: 'Falling Down', category: 'music' },
      { q: 'H.E.R.\'s 2017 R&B single — "I just need you to ___".', a: 'Focus', category: 'music' },
      { q: 'Trenton, NJ rapper born Willie Maxwell — 2015\'s "Trap Queen" star.', a: 'Fetty Wap', category: 'music' },
      { q: 'Odd Future singer born Christopher Breaux whose 2012 debut was "Channel Orange".', a: 'Frank Ocean', category: 'music', alt: ['Frank'] },
      { q: 'Kanye West\'s 2016 "Life of Pablo" track addressing Taylor Swift drama.', a: 'Famous', category: 'music' },
      { q: 'Kanye West\'s 2016 "Life of Pablo" two-part opener pair sampling Pastor T.L. Barrett — four-word title beginning with a paternal address.', a: 'Father Stretch My Hands', category: 'music' },
      { q: 'Kanye West\'s 2019 single from "Jesus Is King" — "___ God".', a: 'Follow God', category: 'music' },
    ],
    G: [
      { q: 'Drake\'s 2018 "Scorpion" lead single attributing his success to a higher being\'s intentions.', a: 'God\'s Plan', category: 'music', alt: ['Gods Plan'] },
      { q: 'Travis Scott\'s 2016 single with Kendrick Lamar from "Birds in the Trap" — skin-prickling title.', a: 'Goosebumps', category: 'music' },
      { q: 'Kanye West\'s 2018 "ye" track sampling Shirley Ann Lee.', a: 'Ghost Town', category: 'music' },
      { q: 'Lizzo\'s 2016 single from "Coconut Oil" turned 2019 chart hit — "Boss up and change your life".', a: 'Good as Hell', category: 'music' },
      { q: 'Post Malone\'s 2019 single with Young Thug.', a: 'Goodbyes', category: 'music' },
      { q: 'Cardi B\'s 2018 "Invasion of Privacy" intro — "Get Up ___".', a: 'Get Up 10', category: 'music' },
      { q: 'Kendrick Lamar\'s 2012 major-label debut with "Swimming Pools" and "Backseat Freestyle".', a: 'good kid, m.A.A.d city', category: 'music', alt: ['Good Kid Maad City', 'GKMC'] },
    ],
    H: [
      { q: 'Kendrick Lamar\'s 2017 "DAMN." mega-single — "Sit down, be ___".', a: 'HUMBLE.', category: 'music', alt: ['HUMBLE', 'Humble'] },
      { q: 'Drake\'s 2015 Billboard chart-dweller — "You used to call me on my cellphone".', a: 'Hotline Bling', category: 'music' },
      { q: 'Drake\'s 2011 single from "Take Care" — "I might be too strung out on compliments".', a: 'Headlines', category: 'music' },
      { q: 'Drake\'s 2013 R&B-leaning ballad — "\'Cause you\'re a good girl and you know it".', a: 'Hold On, We\'re Going Home', category: 'music', alt: ['Hold On Were Going Home'] },
      { q: 'Beyoncé\'s 2016 "Lemonade" track sampling Yeah Yeah Yeahs — "I tried to change".', a: 'Hold Up', category: 'music' },
      { q: 'The Weeknd\'s 2011 debut mixtape — a dwelling of inflatable rubber toys.', a: 'House of Balloons', category: 'music' },
      { q: 'The Weeknd\'s 2019 single, the lead from his "After Hours" rollout.', a: 'Heartless', category: 'music' },
      { q: 'Travis Scott\'s 2019 No. 1 collaboration with Drake — "Just got back from the moon".', a: 'Highest in the Room', category: 'music' },
      { q: 'Jay-Z\'s 2013 album title track with Justin Timberlake referencing Arthurian legend.', a: 'Holy Grail', category: 'music' },
    ],
    I: [
      { q: 'Cardi B\'s 2018 No. 1 single with Bad Bunny and J Balvin sampling Pete Rodriguez.', a: 'I Like It', category: 'music' },
      { q: 'Drake\'s 2018 "Scorpion" track addressing Pusha-T beef — two-word phrase about being annoyed.', a: 'I\'m Upset', category: 'music' },
      { q: 'Kendrick Lamar\'s 2014 single celebrating self-love — single lowercase letter title.', a: 'i', category: 'music' },
      { q: 'Tyler, the Creator\'s 2019 Grammy-winning album, all-caps single-word title.', a: 'IGOR', category: 'music', alt: ['Igor'] },
      { q: 'Cardi B\'s 2018 debut studio album that won the Best Rap Album Grammy.', a: 'Invasion of Privacy', category: 'music' },
      { q: 'The Weeknd\'s 2017 "Starboy" Daft Punk co-produced single about romance approaching.', a: 'I Feel It Coming', category: 'music' },
      { q: 'Drake\'s 2015 surprise mixtape opening with a conditional address to the listener about tardiness.', a: 'If You\'re Reading This It\'s Too Late', category: 'music', alt: ['IYRTITL'] },
      { q: 'DJ Khaled\'s 2017 No. 1 with Justin Bieber, Quavo, Chance, and Lil Wayne — "I\'m ___".', a: 'I\'m the One', category: 'music', alt: ['Im the One'] },
      { q: 'Frank Ocean\'s 2016 "Blonde" opener about a relationship growing — single word.', a: 'Ivy', category: 'music' },
      { q: 'DJ Khaled\'s 2016 single with Future, Jay-Z, Rick Ross and Big Sean.', a: 'I Got the Keys', category: 'music' },
      { q: 'Drake\'s 2018 viral "Scorpion" single sparking a "Kiki" dance challenge.', a: 'In My Feelings', category: 'music' },
    ],
    J: [
      { q: 'Drake & Future\'s 2015 "What a Time to Be Alive" track — "I be ballin\' like ___".', a: 'Jumpman', category: 'music' },
      { q: 'Fayetteville-raised rapper whose 2014 album "Forest Hills Drive" went platinum with no features.', a: 'J. Cole', category: 'music', alt: ['J Cole', 'Jermaine Cole'] },
      { q: 'Brooklyn rapper Jo-Vaughn Scott\'s stage name — Pro Era founder, "1999" mixtape.', a: 'Joey Bada$$', category: 'music', alt: ['Joey Badass'] },
      { q: 'XXXTentacion\'s 2017 single from "17" — first name of a friend who died.', a: 'Jocelyn Flores', category: 'music' },
      { q: 'Lizzo\'s 2019 single from "Cuz I Love You" — "If I\'m shinin\', everybody gonna shine".', a: 'Juice', category: 'music' },
      { q: 'Chicago rapper born Jarad Higgins who broke through with "Lucid Dreams" in 2018.', a: 'Juice WRLD', category: 'music', alt: ['Juice World'] },
      { q: 'Brooklyn-born rapper-singer turned global pop star — Beyoncé\'s husband, born Shawn Carter.', a: 'Jay-Z', category: 'music', alt: ['Jay Z'] },
      { q: 'Kanye West\'s 2019 gospel album — "___ Is King".', a: 'Jesus Is King', category: 'music' },
    ],
    K: [
      { q: 'Kendrick Lamar\'s 2015 "To Pimp a Butterfly" single — "King ___".', a: 'King Kunta', category: 'music' },
      { q: 'Compton rapper born with the surname Duckworth, the TDE flagship behind "To Pimp a Butterfly".', a: 'Kendrick Lamar', category: 'music', alt: ['Kendrick'] },
      { q: 'J. Cole\'s 2018 album whose initials stand for "Kids on Drugs".', a: 'KOD', category: 'music' },
      { q: 'Texas-raised R&B singer with the surname Robinson whose 2017 debut was "American Teen".', a: 'Khalid', category: 'music' },
      { q: 'Bay Area R&B singer with the surname Parrish — "SweetSexySavage" dropped in 2017.', a: 'Kehlani', category: 'music' },
      { q: 'Chicago rapper-producer behind 2010\'s "MBDTF" and 2013\'s "Yeezus".', a: 'Kanye West', category: 'music', alt: ['Kanye'] },
      { q: 'Cleveland rapper born Scott Mescudi whose 2010 album was "Man on the Moon II".', a: 'Kid Cudi', category: 'music' },
    ],
    L: [
      { q: 'Juice WRLD\'s 2018 breakout single sampling Sting\'s "Shape of My Heart".', a: 'Lucid Dreams', category: 'music' },
      { q: 'Kendrick Lamar\'s 2017 single with Rihanna from "DAMN." — single-word capitalized title with full stop.', a: 'LOYALTY.', category: 'music', alt: ['LOYALTY', 'Loyalty'] },
      { q: 'Beyoncé\'s 2016 visual album with "Formation" and "Sorry".', a: 'Lemonade', category: 'music' },
      { q: 'XXXTentacion\'s 2017 single from "17" — three-word imperative.', a: 'Look at Me!', category: 'music', alt: ['Look at Me'] },
      { q: 'Future\'s 2015 single with The Weeknd from "DS2".', a: 'Low Life', category: 'music' },
      { q: 'Maryland rapper born Sir Robert Bryson Hall II whose 2014 debut was "Under Pressure".', a: 'Logic', category: 'music' },
    ],
    M: [
      { q: 'Future\'s 2017 single from "Future" — "Percocets, molly, Percocets".', a: 'Mask Off', category: 'music' },
      { q: 'Kendrick Lamar\'s "good kid, m.A.A.d city" cut — "Halle Berry or Hallelujah".', a: 'Money Trees', category: 'music' },
      { q: 'Drake\'s 2011 "Take Care" track addressed to an ex over wine — "I\'m just sayin\' you can do better".', a: 'Marvin\'s Room', category: 'music', alt: ['Marvins Room'] },
      { q: 'Drake\'s 2018 "Scorpion" track about custody and gangsters.', a: 'Mob Ties', category: 'music' },
      { q: 'Kanye West\'s 2010 "MBDTF" posse cut with Jay-Z, Nicki Minaj, Rick Ross, and Bon Iver.', a: 'Monster', category: 'music' },
      { q: 'Migos, Nicki Minaj and Cardi B\'s 2017 single — "If Offset get locked up I\'m bailing him out".', a: 'MotorSport', category: 'music' },
      { q: 'Kanye West\'s 2010 album whose acronym is "MBDTF".', a: 'My Beautiful Dark Twisted Fantasy', category: 'music', alt: ['MBDTF'] },
      { q: 'XXXTentacion\'s 2018 single from "?" with a falsetto chorus.', a: 'Moonlight', category: 'music' },
      { q: 'J. Cole\'s 2019 track addressing the rap generation gap.', a: 'Middle Child', category: 'music' },
      { q: 'Janelle Monáe\'s 2018 Prince-influenced single from "Dirty Computer" — imperative verb, first-person pronoun, then a sensory verb.', a: 'Make Me Feel', category: 'music' },
      { q: 'Atlanta hip-hop trio of Quavo, Offset, and Takeoff.', a: 'Migos', category: 'music' },
      { q: 'Pittsburgh rapper born Malcolm McCormick — released "Faces" in 2014, died 2018.', a: 'Mac Miller', category: 'music' },
    ],
    N: [
      { q: 'Drake\'s 2018 No. 1 from "Scorpion" sampling Lauryn Hill.', a: 'Nice for What', category: 'music' },
      { q: 'Frank Ocean\'s 2016 "Blonde" single with a high-pitched and a deep-pitched verse.', a: 'Nikes', category: 'music' },
      { q: 'Frank Ocean\'s 2016 "Blonde" track — "All my night, been ready for you, you, you".', a: 'Nights', category: 'music' },
      { q: 'J. Cole\'s 2014 "Forest Hills Drive" highlight lamenting a lack of figures to look up to.', a: 'No Role Modelz', category: 'music' },
      { q: 'Drake\'s 2018 streaming-record-setting "Scorpion" track — "Look, I just flipped a switch".', a: 'Nonstop', category: 'music' },
      { q: 'DJ Khaled\'s 2018 single with Justin Bieber, Chance the Rapper, Quavo.', a: 'No Brainer', category: 'music' },
      { q: 'Kanye West\'s 2013 "Yeezus" track sampling Marilyn Manson.', a: 'New Slaves', category: 'music' },
      { q: 'Drake\'s 2013 third studio album with "Started from the Bottom" and "Hold On, We\'re Going Home".', a: 'Nothing Was the Same', category: 'music' },
    ],
    O: [
      { q: 'Drake\'s 2016 No. 1 single featuring Wizkid and Kyla.', a: 'One Dance', category: 'music' },
      { q: 'Lil Nas X\'s 2019 country-trap single with a Billy Ray Cyrus remix.', a: 'Old Town Road', category: 'music' },
      { q: 'Jay-Z\'s 2013 "Magna Carta Holy Grail" track addressed to the music industry.', a: 'Open Letter', category: 'music' },
      { q: 'Jay-Z & Kanye West\'s 2011 "Watch the Throne" single sampling the late soul singer of the same name.', a: 'Otis', category: 'music' },
      { q: 'Nicki Minaj, Drake and Lil Wayne\'s 2014 single — "And ___ from now I bet you you\'ll be missing me".', a: 'Only', category: 'music' },
      { q: 'The Weeknd\'s 2014 single from his Trilogy era — "She a freak, she a freak".', a: 'Often', category: 'music' },
    ],
    P: [
      { q: 'Kanye West\'s 2010 single from "MBDTF" sampling King Crimson\'s "21st Century Schizoid Man".', a: 'POWER', category: 'music', alt: ['Power'] },
      { q: 'Beyoncé\'s 2013 self-titled single referencing limo windows.', a: 'Partition', category: 'music' },
      { q: 'Beyoncé\'s 2013 self-titled ballad confronting beauty standards.', a: 'Pretty Hurts', category: 'music' },
      { q: 'Cardi B & Bruno Mars\'s 2019 single — "I\'m so ___ed up".', a: 'Please Me', category: 'music' },
      { q: 'Cardi B\'s 2019 single addressing media scrutiny — single word title.', a: 'Press', category: 'music' },
      { q: 'Frank Ocean\'s 2012 "Channel Orange" single about a love triangle — a pastel rose hue plus the colour of snow.', a: 'Pink + White', category: 'music', alt: ['Pink and White'] },
      { q: 'Frank Ocean\'s 2012 "Channel Orange" highlight — "Set the cheetahs on the loose".', a: 'Pyramids', category: 'music' },
      { q: 'Nicki Minaj\'s 2010 debut studio album — a pastel rose hue plus the day before Saturday.', a: 'Pink Friday', category: 'music' },
      { q: 'Nicki Minaj\'s 2012 single from "Roman Reloaded" — three-word title: a striking verb, an article, then a warning-signal noun.', a: 'Pound the Alarm', category: 'music' },
      { q: 'The Weeknd\'s 2018 single from the "Black Panther" soundtrack.', a: 'Pray for Me', category: 'music' },
      { q: 'J. Cole\'s 2013 "Born Sinner" single with Miguel.', a: 'Power Trip', category: 'music' },
      { q: 'Janelle Monáe\'s 2018 sapphic single from "Dirty Computer" featuring Grimes — color title.', a: 'Pynk', category: 'music' },
      { q: 'Texas-raised face-tattooed rapper born Austin Richard — "Congratulations" and "Rockstar" hitmaker.', a: 'Post Malone', category: 'music' },
      { q: 'Toronto R&B singer born Jahron Brathwaite, OVO labelmate.', a: 'PartyNextDoor', category: 'music', alt: ['PND'] },
      { q: 'Virginia rapper, half of Clipse, who became GOOD Music president and released "DAYTONA" in 2018.', a: 'Pusha T', category: 'music', alt: ['Pusha-T'] },
    ],
    R: [
      { q: 'Kanye West\'s 2010 "MBDTF" Pusha T–featuring single about toasting losers.', a: 'Runaway', category: 'music' },
      { q: 'Post Malone\'s 2017 No. 1 with 21 Savage — "I\'ve been fuckin\' hoes and poppin\' pillies".', a: 'Rockstar', category: 'music' },
      { q: 'Travis Scott\'s 2015 debut studio album.', a: 'Rodeo', category: 'music' },
      { q: 'Beyoncé\'s 2011 feminist anthem from "4" answering its own question with a single word about young women.', a: 'Run the World (Girls)', category: 'music', alt: ['Run the World', 'Girls Run the World'] },
      { q: 'Juice WRLD\'s 2018 single — "Bringing a Glock to a store, it\'s a ___".', a: 'Robbery', category: 'music' },
      { q: 'Compton-born rapper born Rodrick Moore who broke through with 2019\'s "Die Young".', a: 'Roddy Ricch', category: 'music' },
    ],
    S: [
      { q: 'Travis Scott\'s 2018 "Astroworld" No. 1 with Drake — three-part song with multiple beat switches.', a: 'SICKO MODE', category: 'music', alt: ['Sicko Mode'] },
      { q: 'Drake\'s 2013 single from "Nothing Was the Same" boasting an underdog origin and rapid ascent — five-word phrase.', a: 'Started from the Bottom', category: 'music' },
      { q: 'Beyoncé\'s 2016 "Lemonade" diss single — "He better call Becky with the good hair".', a: 'Sorry', category: 'music' },
      { q: 'Beyoncé\'s 2016 "Lemonade" piano apology track.', a: 'Sandcastles', category: 'music' },
      { q: 'Frank Ocean\'s 2016 "Blonde" cut — "Yes, of course I remember, how could I forget".', a: 'Self Control', category: 'music' },
      { q: 'Travis Scott\'s 2018 "Astroworld" track about hopping in a Wraith — "Yeah, I been up on ___".', a: 'Stargazing', category: 'music' },
      { q: 'The Weeknd\'s 2016 No. 1 album-titled single with Daft Punk.', a: 'Starboy', category: 'music' },
      { q: 'Ariana Grande & Nicki Minaj\'s 2016 single — "Wouldn\'t put nobody over me, ___".', a: 'Side to Side', category: 'music' },
      { q: 'Nicki Minaj\'s 2012 hit — "We\'re ___ meant to fly".', a: 'Starships', category: 'music' },
      { q: 'Migos\'s 2017 No. 1 with Gucci Mane on "Culture" — "I just hopped out of the pool".', a: 'Slippery', category: 'music' },
      { q: 'Nicki Minaj\'s 2010 mega-single from "Pink Friday" — "Boom, badoom, boom".', a: 'Super Bass', category: 'music' },
      { q: 'Post Malone & Swae Lee\'s 2018 "Spider-Verse" single — "Needless to say, I keep her in check".', a: 'Sunflower', category: 'music' },
      { q: 'DaBaby\'s 2019 chart-topping single about a rap legend\'s last name.', a: 'Suge', category: 'music' },
      { q: 'Kendrick Lamar\'s 2012 single about alcohol abuse — "I got a ___ full of liquor".', a: 'Swimming Pools (Drank)', category: 'music', alt: ['Swimming Pools'] },
      { q: 'TDE singer-songwriter born Solána Rowe whose 2017 debut was "CTRL".', a: 'SZA', category: 'music' },
      { q: 'Texas-raised R&B singer with the surname Knowles, Beyoncé\'s younger sister.', a: 'Solange', category: 'music' },
      { q: 'Migos\'s 2018 "Culture II" single — "___ Fry".', a: 'Stir Fry', category: 'music' },
      { q: 'Travis Scott\'s 2018 "Astroworld" track addressing fame and ego — imperative about ceasing to act like a deity.', a: 'Stop Trying to Be God', category: 'music' },
      { q: 'TDE rapper born Quincy Hanley — released "Oxymoron" in 2014 and "Blank Face LP" in 2016.', a: 'Schoolboy Q', category: 'music', alt: ['ScHoolboy Q'] },
    ],
    T: [
      { q: 'Drake\'s 2011 second studio album title track featuring Rihanna.', a: 'Take Care', category: 'music' },
      { q: 'Fetty Wap\'s 2015 breakout — "I\'m like, \'Hey, what\'s up, hello\'".', a: 'Trap Queen', category: 'music' },
      { q: 'Jay-Z\'s 2017 "4:44" intro — "The ___ of O.J.".', a: 'The Story of O.J.', category: 'music', alt: ['Story of OJ'] },
      { q: 'Kendrick Lamar\'s 2015 third studio album with "Alright" and "King Kunta".', a: 'To Pimp a Butterfly', category: 'music', alt: ['TPAB'] },
      { q: 'Lizzo\'s 2017 single that became a 2019 Grammy-winning No. 1 — "I just took a DNA test".', a: 'Truth Hurts', category: 'music' },
      { q: 'Nicki Minaj, Lil Wayne and Drake\'s 2015 single — a luxury fungus delicacy followed by a dairy spread.', a: 'Truffle Butter', category: 'music' },
      { q: 'Migos\'s 2017 "Culture" track about wearing only one piece of clothing.', a: 'T-Shirt', category: 'music' },
      { q: 'Jay-Z\'s 2013 "Magna Carta Holy Grail" track named after a luxury fashion designer — short male name plus a surname shared with a US president.', a: 'Tom Ford', category: 'music' },
      { q: 'Frank Ocean\'s 2012 "Channel Orange" lead single — three-word phrase of romantic preoccupation rendered in dropped-G casual speech.', a: 'Thinkin Bout You', category: 'music', alt: ['Thinking About You'] },
      { q: 'Lizzo\'s 2019 single from "Cuz I Love You" — "Slow song, baby, we could ___".', a: 'Tempo', category: 'music' },
      { q: 'Houston-born rapper born Jacques Webster II — released "Astroworld" in 2018.', a: 'Travis Scott', category: 'music' },
      { q: 'Odd Future leader born with the surname Okonma whose 2019 album "IGOR" won Best Rap Album.', a: 'Tyler, the Creator', category: 'music', alt: ['Tyler the Creator', 'Tyler'] },
    ],
    U: [
      { q: 'Future & Drake\'s 2015 mixtape "What a Time to Be Alive" single — "___ to This".', a: 'Used to This', category: 'music', alt: ['Used to This Future'] },
      { q: 'Kanye West\'s 2016 "The Life of Pablo" opener featuring Chance the Rapper, Kelly Price and The-Dream.', a: 'Ultralight Beam', category: 'music' },
    ],
    V: [
      { q: 'Drake\'s 2016 fourth studio album — Toronto-themed cover.', a: 'Views', category: 'music' },
      { q: 'Migos\'s 2013 breakout single — Italian fashion-house repetition.', a: 'Versace', category: 'music' },
      { q: 'Long Beach rapper whose 2017 album "Big Fish Theory" got critical raves; he later voiced an animated Netflix series about himself.', a: 'Vince Staples', category: 'music' },
    ],
    W: [
      { q: 'DJ Khaled\'s 2017 single with Rihanna and Bryson Tiller sampling Carlos Santana.', a: 'Wild Thoughts', category: 'music' },
      { q: 'Migos & Drake\'s 2018 single from "Culture II" — a verb of locomotion, "It", then a verb of speech and "It".', a: 'Walk It Talk It', category: 'music' },
      { q: 'Post Malone\'s 2015 debut single named after a Philadelphia 76ers point guard\'s surname plus a contrasting colour adjective.', a: 'White Iverson', category: 'music' },
      { q: 'Post Malone\'s 2019 single from "Hollywood\'s Bleeding" — single-word title with full stop.', a: 'Wow.', category: 'music', alt: ['Wow'] },
      { q: 'Kanye West\'s 2016 "Life of Pablo" cut featuring Sia and Vic Mensa.', a: 'Wolves', category: 'music' },
      { q: 'Drake\'s 2013 "Nothing Was the Same" track — superlative of "bad" plus a noun for one\'s conduct.', a: 'Worst Behavior', category: 'music' },
      { q: 'Jay-Z & Kanye West\'s 2011 collaborative album.', a: 'Watch the Throne', category: 'music' },
      { q: 'The Weeknd\'s 2012 "Trilogy"-era classic — "So tell me you love me, only for tonight".', a: 'Wicked Games', category: 'music' },
      { q: 'Pittsburgh rapper born Cameron Thomaz — "Black and Yellow" (2010) star.', a: 'Wiz Khalifa', category: 'music' },
    ],
    X: [
      { q: 'Florida rapper born Jahseh Onfroy whose 2018 album "?" hit No. 1; died June 2018.', a: 'XXXTentacion', category: 'music', alt: ['X'] },
      { q: 'Beyoncé\'s 2013 self-titled track named after hugs-and-kisses shorthand.', a: 'XO', category: 'music' },
    ],
    Y: [
      { q: 'Kanye West\'s 2018 album that runs ~23 minutes — Wyoming-recorded.', a: 'ye', category: 'music', alt: ['Ye'] },
      { q: 'Kanye West\'s 2013 sixth studio album that broke from soul samples.', a: 'Yeezus', category: 'music' },
      { q: 'Kanye West\'s 2018 "ye" lead single — single-word title.', a: 'Yikes', category: 'music' },
    ],
  },
};
