import type { RawPack } from '../core/packs';

export const mythologyPack: RawPack = {
  id: 'mythology',
  name: 'Mythology',
  description: 'Gods, heroes, creatures and tales from world mythology.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '⚡',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: 'Greek goddess of love and beauty, born from sea foam.', a: 'Aphrodite', category: 'greek' },
      { q: 'Greek god of the sun, music, poetry and prophecy, twin brother of Artemis.', a: 'Apollo', category: 'greek' },
      { q: 'Greek god of war, son of Zeus and Hera.', a: 'Ares', category: 'greek' },
      { q: 'Greek goddess of wisdom, war and crafts, who sprang fully armed from the head of Zeus.', a: 'Athena', category: 'greek' },
      { q: 'Greek goddess of the hunt, the moon, and wild animals, twin sister of Apollo.', a: 'Artemis', category: 'greek' },
      { q: 'Greatest warrior of the Greeks in the Trojan War, killed by an arrow to his heel.', a: 'Achilles', category: 'greek-heroes' },
      { q: 'Trojan prince and son of Aphrodite who fled the sack of Troy and founded the Roman line.', a: 'Aeneas', category: 'roman' },
      { q: 'Virgil\'s Latin epic poem about a Trojan refugee who becomes the ancestor of the Romans.', a: 'Aeneid', category: 'roman' },
      { q: 'Egyptian jackal-headed god of mummification and the dead.', a: 'Anubis', category: 'egyptian' },
      { q: 'Egyptian serpent of chaos who battles the sun god each night in the underworld.', a: 'Apophis', category: 'egyptian' },
      { q: 'Hindu fire god, messenger between humans and the gods, who consumes offerings.', a: 'Agni', category: 'hindu' },
      { q: 'Greek heroine raised by bears, famous huntress who joined the Calydonian boar hunt.', a: 'Atalanta', category: 'greek-heroes' },
      { q: 'Heroes who sailed with Jason aboard the Argo in search of the Golden Fleece.', a: 'Argonauts', category: 'greek-heroes' },
      { q: 'Japanese sun goddess and chief deity of the Shinto pantheon, ancestor of the emperors.', a: 'Amaterasu', category: 'japanese' },
      { q: 'Irish god of love and youth, son of the Dagda.', a: 'Aengus', category: 'celtic' },
      { q: 'Mesopotamian sky god, the supreme deity of the heavens in Sumerian myth.', a: 'Anu', category: 'mesopotamian' },
      { q: 'Norse realm of the gods, ruled by Odin, connected to Midgard by the Bifrost bridge.', a: 'Asgard', category: 'norse' },
      { q: 'Greek princess of Crete who gave Theseus a ball of thread to escape the Labyrinth.', a: 'Ariadne', category: 'greek' },
      { q: 'Ethiopian princess of Greek myth chained to a rock as sacrifice and rescued by Perseus.', a: 'Andromeda', category: 'greek-heroes' },
      { q: 'Greek king of Mycenae who led the Greek forces against Troy.', a: 'Agamemnon', category: 'greek-heroes' },
      { q: 'Egyptian sun god of Thebes who merged with Ra to become a supreme creator deity.', a: 'Amun', category: 'egyptian' },
    ],
    B: [
      { q: 'Norse god of light, beauty and joy, son of Odin and Frigg whose death foreshadows Ragnarok.', a: 'Balder', category: 'norse' },
      { q: 'Norse god of poetry and eloquence, husband of Idunn.', a: 'Bragi', category: 'norse' },
      { q: 'Roman god of wine and revelry, equivalent of Dionysus.', a: 'Bacchus', category: 'roman' },
      { q: 'Hindu creator god, first of the Trimurti alongside Vishnu and Shiva.', a: 'Brahma', category: 'hindu' },
      { q: 'Egyptian cat-headed goddess of home, fertility and protection.', a: 'Bastet', category: 'egyptian' },
      { q: 'Greek hero who tamed Pegasus and slew the Chimera.', a: 'Bellerophon', category: 'greek-heroes' },
      { q: 'Irish goddess of poetry, healing and smithcraft, daughter of the Dagda.', a: 'Brigid', category: 'celtic' },
      { q: 'Egyptian heron-like bird associated with creation and rebirth, parallel to the phoenix.', a: 'Bennu', category: 'egyptian' },
      { q: 'Slavic witch of Russian folklore who lives in a hut on chicken legs.', a: 'Baba Yaga', category: 'slavic' },
      { q: 'Rainbow bridge of Norse myth connecting Asgard to Midgard.', a: 'Bifrost', category: 'norse' },
      { q: 'Egyptian god of music, dance and fertility, often shown as a dwarf with a lion-like face.', a: 'Bes', category: 'egyptian' },
    ],
    C: [
      { q: 'Three-headed dog who guards the entrance to the Greek underworld.', a: 'Cerberus', category: 'greek-creatures' },
      { q: 'Half-human, half-horse creatures of Greek myth.', a: 'Centaur', category: 'greek-creatures' },
      { q: 'One-eyed giants of Greek myth, sons of Uranus and Gaia who forged Zeus\'s thunderbolts.', a: 'Cyclops', category: 'greek-creatures' },
      { q: 'Fire-breathing Greek monster with the heads of a lion, goat and serpent, slain by Bellerophon.', a: 'Chimera', category: 'greek-creatures' },
      { q: 'Roman goddess of agriculture and grain, equivalent of Demeter.', a: 'Ceres', category: 'roman' },
      { q: 'Hindu moon god, brother of Surya the sun.', a: 'Chandra', category: 'hindu' },
      { q: 'Irish hero of Ulster, born Setanta, famed for his rage-fuelled warp spasm.', a: 'Cú Chulainn', category: 'celtic' },
      { q: 'Greek titan father of Zeus who swallowed his children to avoid being overthrown.', a: 'Cronus', category: 'greek' },
      { q: 'Greek sorceress who turned Odysseus\'s men into pigs on her island.', a: 'Circe', category: 'greek' },
      { q: 'Greek ferryman of the underworld who carries souls across the river Styx.', a: 'Charon', category: 'greek' },
      { q: 'Greek sea monster personifying a deadly whirlpool, paired with Scylla.', a: 'Charybdis', category: 'greek-creatures' },
      { q: 'Greek priestess of Apollo at Delphi whose true prophecies were never believed; daughter of Priam.', a: 'Cassandra', category: 'greek-heroes' },
    ],
    D: [
      { q: 'Greek goddess of the harvest and grain, mother of Persephone.', a: 'Demeter', category: 'greek' },
      { q: 'Greek god of wine, theatre and ecstasy.', a: 'Dionysus', category: 'greek' },
      { q: 'Roman goddess of the hunt and moon, equivalent of Artemis.', a: 'Diana', category: 'roman' },
      { q: 'Hindu warrior goddess who rides a tiger and slays demons, fierce form of Parvati.', a: 'Durga', category: 'hindu' },
      { q: 'Chief of the Tuatha Dé Danann in Irish myth, a father-god with a magical cauldron and club.', a: 'Dagda', category: 'celtic' },
      { q: 'Egyptian realm of the dead through which Ra journeys each night.', a: 'Duat', category: 'egyptian' },
      { q: 'Greek princess and queen of Carthage who fell in love with Aeneas in Virgil\'s epic.', a: 'Dido', category: 'roman' },
      { q: 'Greek and Etruscan craftsman who built the Labyrinth and made wings of wax and feathers.', a: 'Daedalus', category: 'greek' },
    ],
    E: [
      { q: 'Companion of Gilgamesh in Mesopotamian myth, a wild man created by the gods.', a: 'Enkidu', category: 'mesopotamian' },
      { q: 'Mesopotamian god of water, wisdom and creation, known as Ea to the Babylonians.', a: 'Enki', category: 'mesopotamian' },
      { q: 'Mesopotamian god of wind and storms, chief deity of Nippur.', a: 'Enlil', category: 'mesopotamian' },
      { q: 'Mesopotamian queen of the underworld, sister of Ishtar.', a: 'Ereshkigal', category: 'mesopotamian' },
      { q: 'Greek nymph beloved by Orpheus who died of a snake bite on their wedding day.', a: 'Eurydice', category: 'greek-heroes' },
      { q: 'Greek god of love, son of Aphrodite, who shoots arrows that cause people to fall in love.', a: 'Eros', category: 'greek' },
      { q: 'Greek personification of dawn who rises each morning to herald her brother Helios.', a: 'Eos', category: 'greek' },
      { q: 'Greek hero and king of Argos who sent Heracles on his twelve labours.', a: 'Eurystheus', category: 'greek-heroes' },
    ],
    F: [
      { q: 'Norse goddess of love, fertility and war, owner of the necklace Brísingamen.', a: 'Freyja', category: 'norse' },
      { q: 'Norse god of fertility, peace and prosperity, twin brother of Freyja.', a: 'Freyr', category: 'norse' },
      { q: 'Norse goddess and queen of Asgard, wife of Odin and mother of Balder.', a: 'Frigg', category: 'norse' },
      { q: 'Monstrous wolf of Norse myth, son of Loki, who will kill Odin at Ragnarok.', a: 'Fenrir', category: 'norse' },
      { q: 'Legendary Irish hunter-warrior and leader of the Fianna.', a: 'Finn MacCool', category: 'celtic' },
      { q: 'Japanese god of the wind, often depicted carrying a bag of winds on his shoulders.', a: 'Fujin', category: 'japanese' },
      { q: 'Three Greek goddesses of destiny who spin, measure and cut the thread of human life.', a: 'Fates', category: 'greek' },
      { q: 'Roman goddess of fortune and luck, often depicted with a wheel and cornucopia.', a: 'Fortuna', category: 'roman' },
    ],
    G: [
      { q: 'Hindu elephant-headed god of wisdom and remover of obstacles, son of Shiva and Parvati.', a: 'Ganesha', category: 'hindu' },
      { q: 'Hindu eagle-like mount of Vishnu, king of the birds.', a: 'Garuda', category: 'hindu' },
      { q: 'Sumerian king of Uruk and hero of the world\'s oldest surviving epic poem.', a: 'Gilgamesh', category: 'mesopotamian' },
      { q: 'Egyptian god of the earth, husband and brother of Nut the sky.', a: 'Geb', category: 'egyptian' },
      { q: 'Greek primordial earth goddess, mother of the Titans, Cyclopes and Giants.', a: 'Gaia', category: 'greek' },
      { q: 'Three Greek goddesses of charm and beauty who attended Aphrodite.', a: 'Graces', category: 'greek' },
      { q: 'Trojan prince of Greek myth taken to Olympus by Zeus to be cupbearer to the gods.', a: 'Ganymede', category: 'greek' },
    ],
    H: [
      { q: 'Greek queen of the gods, wife and sister of Zeus.', a: 'Hera', category: 'greek' },
      { q: 'Greek god of the underworld, brother of Zeus and Poseidon.', a: 'Hades', category: 'greek' },
      { q: 'Greek messenger god, conductor of souls, wearer of winged sandals.', a: 'Hermes', category: 'greek' },
      { q: 'Greek god of fire, forges and craftsmanship, smith of the gods.', a: 'Hephaestus', category: 'greek' },
      { q: 'Greek goddess of the hearth and home, eldest child of Cronus and Rhea.', a: 'Hestia', category: 'greek' },
      { q: 'Greek hero of immense strength, son of Zeus, famous for completing twelve labours.', a: 'Heracles', category: 'greek-heroes', alt: ['Hercules'] },
      { q: 'Egyptian falcon-headed sky god, son of Osiris and Isis, who avenged his father.', a: 'Horus', category: 'egyptian' },
      { q: 'Egyptian cow-headed goddess of music, love and motherhood.', a: 'Hathor', category: 'egyptian' },
      { q: 'Norse watchman of the gods who guards the Bifrost bridge with the horn Gjallarhorn.', a: 'Heimdall', category: 'norse' },
      { q: 'Hindu monkey god, devoted servant of Rama in the Ramayana.', a: 'Hanuman', category: 'hindu' },
      { q: 'Norse goddess who rules over the realm of the dead bearing her name.', a: 'Hel', category: 'norse' },
      { q: 'Many-headed serpent of Greek myth slain by Heracles as his second labour.', a: 'Hydra', category: 'greek-creatures' },
      { q: 'Winged Greek monster with the head of a woman and body of a bird who snatched souls.', a: 'Harpy', category: 'greek-creatures' },
      { q: 'Aztec god of the sun, war and human sacrifice, patron of Tenochtitlan.', a: 'Huitzilopochtli', category: 'aztec' },
      { q: 'Japanese god of war and patron of warriors, often associated with the emperor.', a: 'Hachiman', category: 'japanese' },
      { q: 'Greek titan god of the sun who drives a fiery chariot across the sky.', a: 'Helios', category: 'greek' },
      { q: 'Most beautiful woman in Greek myth whose abduction sparked the Trojan War.', a: 'Helen of Troy', category: 'greek-heroes' },
      { q: 'Trojan prince and greatest warrior of Troy, killed by Achilles before the city\'s walls.', a: 'Hector', category: 'greek-heroes' },
      { q: 'Greek goddess of witchcraft, magic and crossroads, often shown with torches.', a: 'Hecate', category: 'greek' },
    ],
    I: [
      { q: 'Egyptian goddess of magic and motherhood, wife of Osiris and mother of Horus.', a: 'Isis', category: 'egyptian' },
      { q: 'Greek youth who flew too close to the sun on waxen wings and fell to his death.', a: 'Icarus', category: 'greek' },
      { q: 'Homer\'s Greek epic poem about the wrath of Achilles during the Trojan War.', a: 'Iliad', category: 'greek-heroes' },
      { q: 'Hindu king of the gods, ruler of heaven and god of thunder and rain.', a: 'Indra', category: 'hindu' },
      { q: 'Norse goddess who keeps the golden apples of immortality.', a: 'Idunn', category: 'norse' },
      { q: 'Mesopotamian goddess of love and war, the Sumerian counterpart of Ishtar.', a: 'Inanna', category: 'mesopotamian' },
      { q: 'Japanese god of rice and prosperity, associated with foxes as messengers.', a: 'Inari', category: 'japanese' },
      { q: 'Japanese primordial god who, with his sister-wife, created the islands of Japan.', a: 'Izanagi', category: 'japanese' },
      { q: 'Japanese primordial goddess and creator of the islands of Japan, wife of Izanagi.', a: 'Izanami', category: 'japanese' },
      { q: 'Mesopotamian goddess of love, fertility and war, Babylonian form of Inanna.', a: 'Ishtar', category: 'mesopotamian' },
    ],
    J: [
      { q: 'Greek leader of the Argonauts who sought the Golden Fleece.', a: 'Jason', category: 'greek-heroes' },
      { q: 'Roman king of the gods, equivalent of Zeus, who wields thunderbolts.', a: 'Jupiter', category: 'roman' },
      { q: 'Roman queen of the gods, wife of Jupiter, equivalent of Hera.', a: 'Juno', category: 'roman' },
      { q: 'World serpent of Norse myth that encircles Midgard, archenemy of Thor.', a: 'Jörmungandr', category: 'norse', alt: ['Midgard Serpent'] },
      { q: 'Norse giants, often enemies of the Aesir, who dwell in Jotunheim.', a: 'Jotnar', category: 'norse', alt: ['Jotuns'] },
      { q: 'Greek god with two faces who looks to past and future, namesake of January.', a: 'Janus', category: 'roman' },
    ],
    K: [
      { q: 'Hindu goddess of death, time and destruction, depicted with a garland of skulls.', a: 'Kali', category: 'hindu' },
      { q: 'Hindu blue-skinned avatar of Vishnu, charioteer of Arjuna in the Bhagavad Gita.', a: 'Krishna', category: 'hindu' },
      { q: 'Egyptian ram-headed creator god who forms human bodies on his potter\'s wheel.', a: 'Khnum', category: 'egyptian' },
      { q: 'Maya feathered-serpent god, equivalent of the Aztec Quetzalcoatl.', a: 'Kukulkan', category: 'maya' },
      { q: 'Japanese shapeshifting fox spirit of folklore.', a: 'Kitsune', category: 'japanese' },
      { q: 'Japanese water imp of folklore, with a saucer of liquid atop its head.', a: 'Kappa', category: 'japanese' },
    ],
    L: [
      { q: 'Norse trickster god, blood-brother of Odin and father of Fenrir and the Midgard Serpent.', a: 'Loki', category: 'norse' },
      { q: 'Hindu goddess of wealth, fortune and prosperity, wife of Vishnu.', a: 'Lakshmi', category: 'hindu' },
      { q: 'Irish god of skill, light and the harvest, master of all crafts.', a: 'Lugh', category: 'celtic' },
      { q: 'Greek mortal woman seduced by Zeus disguised as a swan, mother of Helen.', a: 'Leda', category: 'greek' },
      { q: 'Greek titaness mother of Apollo and Artemis by Zeus.', a: 'Leto', category: 'greek' },
    ],
    M: [
      { q: 'Greek gorgon with snakes for hair whose gaze turned onlookers to stone, slain by Perseus.', a: 'Medusa', category: 'greek-creatures' },
      { q: 'Bull-headed Greek monster kept in the Labyrinth on Crete and slain by Theseus.', a: 'Minotaur', category: 'greek-creatures' },
      { q: 'Phrygian king of Greek myth whose touch turned everything to gold.', a: 'Midas', category: 'greek' },
      { q: 'Roman god of war, equivalent of Ares and father of Romulus.', a: 'Mars', category: 'roman' },
      { q: 'Roman messenger god, equivalent of Hermes.', a: 'Mercury', category: 'roman' },
      { q: 'Roman goddess of wisdom and crafts, equivalent of Athena.', a: 'Minerva', category: 'roman' },
      { q: 'Babylonian chief god who slew the chaos dragon Tiamat and created the world from her body.', a: 'Marduk', category: 'mesopotamian' },
      { q: 'Norse realm of humans, encircled by the world serpent.', a: 'Midgard', category: 'norse' },
      { q: 'Thor\'s legendary Norse hammer, forged by dwarves.', a: 'Mjölnir', category: 'norse' },
      { q: 'Irish goddess of war and fate who appears as a crow on the battlefield.', a: 'Morrigan', category: 'celtic' },
      { q: 'Slavic earth goddess of fertility and women\'s work in pre-Christian Russia.', a: 'Mokosh', category: 'slavic' },
      { q: 'Egyptian goddess of truth, justice and cosmic order, whose feather weighs the soul.', a: 'Ma\'at', category: 'egyptian' },
      { q: 'Nine Greek goddesses who inspire literature, science and the arts.', a: 'Muses', category: 'greek' },
    ],
    N: [
      { q: 'Roman god of the sea, equivalent of Poseidon.', a: 'Neptune', category: 'roman' },
      { q: 'Norse god of the sea, wind and wealth, father of Freyr and Freyja.', a: 'Njord', category: 'norse' },
      { q: 'Egyptian sky goddess often shown arching over her husband Geb the earth.', a: 'Nut', category: 'egyptian' },
      { q: 'Serpent-beings of Hindu myth who guard treasures and waters.', a: 'Naga', category: 'hindu' },
      { q: 'Mesopotamian god of plague, war and the underworld, husband of Ereshkigal.', a: 'Nergal', category: 'mesopotamian' },
      { q: 'Mesopotamian mother goddess of fertility and the earth.', a: 'Ninhursag', category: 'mesopotamian' },
      { q: 'Greek nymph who fell in love with her own reflection and pined away.', a: 'Narcissus', category: 'greek' },
      { q: 'Greek goddess of victory, often depicted with wings.', a: 'Nike', category: 'greek' },
      { q: 'Greek primordial goddess of the night.', a: 'Nyx', category: 'greek' },
    ],
    O: [
      { q: 'Greek king of Ithaca whose ten-year voyage home is told in Homer\'s epic.', a: 'Odysseus', category: 'greek-heroes' },
      { q: 'Homer\'s Greek epic about a hero\'s long voyage home from the Trojan War.', a: 'Odyssey', category: 'greek-heroes' },
      { q: 'Greek musician whose lyre charmed even the dead when he descended to retrieve Eurydice.', a: 'Orpheus', category: 'greek-heroes' },
      { q: 'Norse all-father, chief of the Aesir, who hung from Yggdrasil to gain knowledge of the runes.', a: 'Odin', category: 'norse' },
      { q: 'Egyptian god of the afterlife and resurrection, judge of the dead.', a: 'Osiris', category: 'egyptian' },
      { q: 'Japanese ogre-like demon of folklore, often depicted with horns and a club.', a: 'Oni', category: 'japanese' },
      { q: 'Greek mountain home of the twelve principal gods.', a: 'Olympus', category: 'greek' },
      { q: 'Giant Greek hunter placed in the stars as a constellation after his death.', a: 'Orion', category: 'greek' },
    ],
    P: [
      { q: 'Greek god of the sea who carries a trident.', a: 'Poseidon', category: 'greek' },
      { q: 'Greek goddess of spring and queen of the underworld, daughter of Demeter.', a: 'Persephone', category: 'greek' },
      { q: 'First woman of Greek myth, who opened a forbidden jar releasing all evils into the world.', a: 'Pandora', category: 'greek' },
      { q: 'Greek hero who slew Medusa and rescued Andromeda.', a: 'Perseus', category: 'greek-heroes' },
      { q: 'Winged horse of Greek myth, sprung from the blood of Medusa.', a: 'Pegasus', category: 'greek-creatures' },
      { q: 'Hindu goddess of love and devotion, wife of Shiva and mother of Ganesha.', a: 'Parvati', category: 'hindu' },
      { q: 'Egyptian creator god of Memphis, patron of craftsmen and architects.', a: 'Ptah', category: 'egyptian' },
      { q: 'Roman god of the underworld, equivalent of Hades.', a: 'Pluto', category: 'roman' },
      { q: 'Chief god of Slavic myth, lord of thunder and lightning.', a: 'Perun', category: 'slavic' },
      { q: 'Greek titan who stole fire from the gods and gave it to humanity.', a: 'Prometheus', category: 'greek' },
      { q: 'King of Troy during the Trojan War, father of Hector and Paris.', a: 'Priam', category: 'greek-heroes' },
      { q: 'Greek god of fear, son of Ares, who accompanied his father into battle.', a: 'Phobos', category: 'greek' },
      { q: 'Greek mortal princess of unsurpassed beauty who married the god of love.', a: 'Psyche', category: 'greek' },
    ],
    Q: [
      { q: 'Aztec feathered-serpent god of wind, learning and creation.', a: 'Quetzalcoatl', category: 'aztec' },
    ],
    R: [
      { q: 'Egyptian sun god who sails across the sky each day in his solar barque.', a: 'Ra', category: 'egyptian' },
      { q: 'Hindu seventh avatar of Vishnu, prince of Ayodhya whose wife Sita was abducted by Ravana.', a: 'Rama', category: 'hindu' },
      { q: 'Norse foretold end of the world in which the gods fall in battle.', a: 'Ragnarok', category: 'norse' },
      { q: 'Twin brothers of Roman myth raised by a she-wolf who founded the city of Rome.', a: 'Romulus and Remus', category: 'roman' },
      { q: 'Squirrel that runs along Yggdrasil carrying messages between the eagle and the dragon.', a: 'Ratatoskr', category: 'norse' },
      { q: 'Japanese god of thunder and lightning, often paired with the wind god Fujin.', a: 'Raijin', category: 'japanese' },
      { q: 'Demon king of Lanka who abducted Sita in the Hindu epic Ramayana.', a: 'Ravana', category: 'hindu' },
      { q: 'Greek mother of Zeus who hid him from his child-eating father.', a: 'Rhea', category: 'greek' },
    ],
    S: [
      { q: 'Hindu destroyer god, third of the Trimurti, often depicted in cosmic dance.', a: 'Shiva', category: 'hindu' },
      { q: 'Hindu goddess of knowledge, music and learning, consort of Brahma.', a: 'Saraswati', category: 'hindu' },
      { q: 'Hindu wife of Rama, abducted by Ravana in the Ramayana.', a: 'Sita', category: 'hindu' },
      { q: 'Hindu sun god who drives a chariot pulled by seven horses across the sky.', a: 'Surya', category: 'hindu' },
      { q: 'Greek king condemned to roll a boulder up a hill in Tartarus for eternity.', a: 'Sisyphus', category: 'greek' },
      { q: 'Greek monster with a lion\'s body and a woman\'s head who posed a riddle outside Thebes.', a: 'Sphinx', category: 'greek-creatures' },
      { q: 'Odin\'s eight-legged Norse horse, swiftest of all steeds.', a: 'Sleipnir', category: 'norse' },
      { q: 'Japanese storm god, brother of Amaterasu, who slew the eight-headed dragon.', a: 'Susanoo', category: 'japanese' },
      { q: 'Egyptian crocodile god of the Nile, associated with strength and fertility.', a: 'Sobek', category: 'egyptian' },
      { q: 'Egyptian god of the desert, storms and chaos, who murdered his brother Osiris.', a: 'Set', category: 'egyptian' },
      { q: 'Egyptian lion-headed warrior goddess and daughter of Ra.', a: 'Sekhmet', category: 'egyptian' },
      { q: 'Greek sea monster paired with Charybdis, depicted with six heads on long necks.', a: 'Scylla', category: 'greek-creatures' },
      { q: 'Greek dangerous bird-women whose enchanting song lured sailors to their doom.', a: 'Sirens', category: 'greek-creatures' },
      { q: 'Greek river of the underworld that souls cross to reach the realm of the dead.', a: 'Styx', category: 'greek' },
      { q: 'Greek mortal princess and mother of Dionysus by Zeus, who was incinerated by his true form.', a: 'Semele', category: 'greek' },
    ],
    T: [
      { q: 'Norse god of thunder, son of Odin, wielder of a great hammer.', a: 'Thor', category: 'norse' },
      { q: 'Egyptian ibis-headed god of wisdom, writing and the moon.', a: 'Thoth', category: 'egyptian' },
      { q: 'Greek hero of Athens who slew the Minotaur in the Labyrinth.', a: 'Theseus', category: 'greek-heroes' },
      { q: 'Greek king of Phrygia tormented by food and water just out of reach in the underworld.', a: 'Tantalus', category: 'greek' },
      { q: 'Ten-year Greek war fought over the abduction of Helen.', a: 'Trojan War', category: 'greek-heroes' },
      { q: 'Norse one-handed god of war and justice, who sacrificed his hand to bind Fenrir.', a: 'Tyr', category: 'norse' },
      { q: 'Mesopotamian primordial saltwater goddess of chaos, slain by Marduk.', a: 'Tiamat', category: 'mesopotamian' },
      { q: 'Aztec god of the night sky, sorcery and conflict, rival of Quetzalcoatl.', a: 'Tezcatlipoca', category: 'aztec' },
      { q: 'Aztec rain and fertility god to whom children were sacrificed on mountain tops.', a: 'Tlaloc', category: 'aztec' },
      { q: 'Race of pre-Christian Irish gods who once ruled the island.', a: 'Tuatha Dé Danann', category: 'celtic' },
      { q: 'Long-nosed Japanese mountain spirit of folklore, often depicted with red skin and wings.', a: 'Tengu', category: 'japanese' },
      { q: 'Japanese moon god, brother of Amaterasu and Susanoo.', a: 'Tsukuyomi', category: 'japanese' },
      { q: 'Pre-Olympian Greek deities who ruled before Zeus, including Cronus and Rhea.', a: 'Titans', category: 'greek' },
      { q: 'Deepest abyss of the Greek underworld, where the worst sinners are punished.', a: 'Tartarus', category: 'greek' },
      { q: 'Greek city besieged for ten years by the Greeks in Homer\'s Iliad.', a: 'Troy', category: 'greek-heroes' },
    ],
    U: [
      { q: 'Greek primordial sky god overthrown by his son Cronus.', a: 'Uranus', category: 'greek' },
      { q: 'Sumerian king and survivor of the Mesopotamian flood, who tells his tale to Gilgamesh.', a: 'Utnapishtim', category: 'mesopotamian' },
      { q: 'Sumerian sun god of justice, equivalent of Shamash, brother of Inanna.', a: 'Utu', category: 'mesopotamian' },
    ],
    V: [
      { q: 'Hindu preserver god, second of the Trimurti, who descends as avatars to save the world.', a: 'Vishnu', category: 'hindu' },
      { q: 'Roman goddess of love and beauty, equivalent of Aphrodite.', a: 'Venus', category: 'roman' },
      { q: 'Roman goddess of the hearth, equivalent of Hestia.', a: 'Vesta', category: 'roman' },
      { q: 'Roman god of fire and forges, equivalent of Hephaestus.', a: 'Vulcan', category: 'roman' },
      { q: 'Norse hall of Odin where slain warriors feast until Ragnarok.', a: 'Valhalla', category: 'norse' },
      { q: 'Norse female spirits who choose the slain on the battlefield and bear them to Odin\'s hall.', a: 'Valkyries', category: 'norse' },
      { q: 'Slavic god of the earth, cattle and the underworld, rival of Perun.', a: 'Veles', category: 'slavic' },
    ],
    W: [
      { q: 'Norse fierce, trance-like warriors clad in wolfskins, kin to the berserkers.', a: 'Wulfhednar', category: 'norse', alt: ['Ulfhednar'] },
      { q: 'German legendary smith of Norse and Anglo-Saxon myth, also known as Volund.', a: 'Wayland', category: 'norse' },
    ],
    Y: [
      { q: 'Great world ash tree of Norse myth whose branches and roots connect the nine worlds.', a: 'Yggdrasil', category: 'norse' },
      { q: 'Hindu god of death who judges the souls of the dead.', a: 'Yama', category: 'hindu' },
      { q: 'Eight-headed serpent of Japanese myth slain by Susanoo.', a: 'Yamata-no-Orochi', category: 'japanese' },
    ],
    Z: [
      { q: 'Greek king of the gods, ruler of Olympus, wielder of the thunderbolt.', a: 'Zeus', category: 'greek' },
    ],
    X: [
      { q: 'Aztec god of agriculture, vegetation and renewal, often depicted wearing a flayed human skin.', a: 'Xipe Totec', category: 'aztec' },
    ],
  },
};
