import type { RawPack } from '../core/packs';

export const plantsTreesPack: RawPack = {
  id: 'plants-trees',
  name: 'Plants & Trees',
  description: 'Flowers, trees, crops and the everyday botany of the garden.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '🌳',
  accent: '#15803d',
  letters: {
    A: [
      { q: 'This thorny savanna tree has feathery leaves and yellow puffball blooms.', a: 'Acacia' },
      { q: 'This is the nut that an oak drops in autumn.', a: 'Acorn' },
      { q: 'The thick gel inside this spiky succulent is rubbed on sunburn.', a: 'Aloe vera' },
      { q: 'Granny Smith and Pink Lady are varieties of this orchard fruit.', a: 'Apple' },
      { q: 'This small orange stone fruit is often sold dried in bags.', a: 'Apricot' },
      { q: 'This thistle-like vegetable is eaten by pulling off its scaly leaves.', a: 'Artichoke' },
      { q: 'These green spears are cut in spring and often served with butter.', a: 'Asparagus' },
      { q: 'This slender pale-barked tree has leaves that quiver in the slightest breeze.', a: 'Aspen' },
      { q: 'This daisy-shaped garden bloom takes its name from the Greek word for star.', a: 'Aster' },
      { q: 'This green-fleshed tropical fruit with one large seed is mashed into guacamole.', a: 'Avocado' },
      { q: 'This nut grows on a pink-blossomed tree and is ground to make marzipan.', a: 'Almond' },
      { q: 'This tip of a stamen is the sac that holds the pollen.', a: 'Anther' },
      { q: 'This word describes a plant that grows, blooms, seeds and dies in one year.', a: 'Annual' },
      { q: 'This big trumpet-flowered bulb is a popular indoor Christmas gift.', a: 'Amaryllis' },
    ],
    B: [
      { q: 'This fast-growing woody grass is the main food of the giant panda.', a: 'Bamboo' },
      { q: 'This curved yellow fruit is peeled and grows in bunches called hands.', a: 'Banana' },
      { q: 'This African tree has a hugely swollen trunk that stores water.', a: 'Baobab' },
      { q: 'This is the protective outer layer on the trunk of a tree.', a: 'Bark' },
      { q: 'This aromatic leaf is torn over a Margherita pizza and blended into pesto.', a: 'Basil' },
      { q: 'This tall tree has smooth grey bark and shiny oval leaves that turn coppery.', a: 'Beech' },
      { q: 'This deep purple root vegetable stains your hands and is often pickled in jars.', a: 'Beetroot' },
      { q: 'This shade-loving bedding plant has waxy leaves and clusters of small pink blooms.', a: 'Begonia' },
      { q: 'This slender northern tree has papery white bark that peels away in strips.', a: 'Birch' },
      { q: 'This dark hedgerow fruit is picked in September from thorny brambles.', a: 'Blackberry' },
      { q: 'This nodding spring bulb carpets British woodland in a haze of violet.', a: 'Bluebell' },
      { q: 'This Japanese art keeps a tree tiny by trimming its roots and branches.', a: 'Bonsai' },
      { q: 'This green vegetable is sold as florets and looks like a little tree.', a: 'Broccoli' },
      { q: 'This shiny yellow meadow bloom is held under the chin in a childhood game.', a: 'Buttercup' },
    ],
    C: [
      { q: 'This desert plant stores water in a fleshy stem and is covered in spines.', a: 'Cactus' },
      { q: 'This glossy evergreen shrub bears large rose-like blooms in early spring.', a: 'Camellia' },
      { q: 'This frilly-petalled florist flower has a clove-like scent and is worn in buttonholes.', a: 'Carnation' },
      { q: 'This orange root vegetable is pulled up by its feathery green top.', a: 'Carrot' },
      { q: 'This conifer has fragrant reddish timber used to line clothes chests.', a: 'Cedar' },
      { q: 'These crunchy pale green stalks are dipped in peanut butter or chopped into soup.', a: 'Celery' },
      { q: 'This little daisy-like bloom is dried to make a soothing bedtime tea.', a: 'Chamomile' },
      { q: 'This small red stone fruit grows on a tree famed for its blossom in Japan.', a: 'Cherry' },
      { q: 'These glossy brown nuts are roasted on street stalls in winter.', a: 'Chestnut' },
      { q: 'This green pigment lets a leaf capture the energy in sunlight.', a: 'Chlorophyll' },
      { q: 'This warm brown spice is the rolled inner bark of a tropical tree.', a: 'Cinnamon' },
      { q: 'This three-leaved lawn plant is lucky when a fourth leaflet appears.', a: 'Clover' },
      { q: 'This big husked brown fruit grows atop a palm and holds sweet water.', a: 'Coconut' },
      { q: 'This crumbly dark stuff is made by rotting down kitchen and garden waste.', a: 'Compost' },
      { q: 'This low cup-shaped bulb pushes up through the grass in earliest spring.', a: 'Crocus' },
    ],
    D: [
      { q: 'This yellow trumpet-shaped bulb is the national emblem of Wales.', a: 'Daffodil' },
      { q: 'This showy late-summer tuber comes in pompom and waterlily flowered forms.', a: 'Dahlia' },
      { q: 'This little white-petalled lawn bloom with a yellow centre is threaded into chains.', a: 'Daisy' },
      { q: 'This yellow lawn weed turns into a white clock of seeds that children blow away.', a: 'Dandelion' },
      { q: 'This desert tree bears sticky brown fruit in heavy hanging bunches.', a: 'Date palm' },
      { q: 'This is the job of snipping off faded blooms to encourage more.', a: 'Deadheading' },
      { q: 'This feathery herb with a mild aniseed taste is chopped over salmon.', a: 'Dill' },
      { q: 'This shrub is grown for its bright red winter stems and white spring bracts.', a: 'Dogwood' },
      { q: 'This tall North American conifer is a favourite Christmas tree.', a: 'Douglas fir' },
      { q: 'This tall cottage-garden spire of blue blooms is also called larkspur.', a: 'Delphinium' },
    ],
    E: [
      { q: 'This hedgerow shrub gives creamy summer blossom and dark purple berries for wine.', a: 'Elder' },
      { q: 'A Dutch disease wiped out most of these hedgerow trees in Britain.', a: 'Elm' },
      { q: 'This Australian tree has blue-grey leaves that koalas feed on.', a: 'Eucalyptus' },
      { q: 'This word describes a tree that keeps its leaves right through the winter.', a: 'Evergreen' },
      { q: 'This is the American name for the aubergine.', a: 'Eggplant' },
      { q: 'This bitter salad leaf is grown in the dark to keep its tips pale yellow.', a: 'Endive' },
      { q: 'This woolly white alpine bloom is celebrated in a song from The Sound of Music.', a: 'Edelweiss' },
      { q: 'This yellow wildflower opens at dusk and its seed oil is sold in capsules.', a: 'Evening primrose' },
    ],
    F: [
      { q: 'This shade-loving plant has no blooms and unrolls new fronds from a curled tip.', a: 'Fern' },
      { q: 'This soft purple fruit full of tiny seeds is dried and used in a rolled biscuit bar.', a: 'Fig' },
      { q: 'This vegetable has a swollen white bulb and a strong aniseed flavour.', a: 'Fennel' },
      { q: 'Gardeners spread this to add nutrients such as nitrogen to the soil.', a: 'Fertilizer' },
      { q: 'This tiny sky-blue spring bloom has a name that asks you to remember it.', a: 'Forget-me-not' },
      { q: 'This tall woodland spire of speckled purple bells is poisonous to eat.', a: 'Foxglove' },
      { q: 'This tropical tree bears waxy scented blooms used in Hawaiian garlands.', a: 'Frangipani' },
      { q: 'This scented florist bloom grows from a corm and flowers in a one-sided row.', a: 'Freesia' },
      { q: 'This shrub dangles ballerina-shaped blooms in purple and pink.', a: 'Fuchsia' },
      { q: 'This blue-flowered crop gives linen fibre and linseed oil.', a: 'Flax' },
    ],
    G: [
      { q: 'This pungent bulb is split into cloves and crushed into cooking.', a: 'Garlic' },
      { q: 'This common windowbox plant has rounded scented leaves and heads of red blooms.', a: 'Geranium' },
      { q: 'This bold daisy-shaped florist bloom comes in bright orange, pink and yellow.', a: 'Gerbera' },
      { q: 'This knobbly underground stem is grated into curries and crystallised as a sweet.', a: 'Ginger' },
      { q: 'This ancient tree with fan-shaped leaves is often called a living fossil.', a: 'Ginkgo' },
      { q: 'This sword-leaved corm sends up a tall one-sided spike of funnel blooms.', a: 'Gladiolus' },
      { q: 'This fruit grows in bunches on a vine and is pressed to make wine.', a: 'Grape' },
      { q: 'This glass building keeps tender plants warm out of season.', a: 'Greenhouse' },
      { q: 'This tropical fruit has pink flesh, a strong perfume and is drunk as a juice.', a: 'Guava' },
      { q: 'This tart green hairy fruit is stewed with cream into a fool.', a: 'Gooseberry' },
    ],
    H: [
      { q: 'This thorny hedgerow tree covers itself in white May blossom.', a: 'Hawthorn' },
      { q: 'This shrub gives cobnuts and its whippy stems are woven into fences.', a: 'Hazel' },
      { q: 'This low purple-flowered shrub covers Scottish moorland.', a: 'Heather' },
      { q: 'This tropical shrub bears huge trumpet blooms with a long central column.', a: 'Hibiscus' },
      { q: 'This prickly evergreen with red berries is cut for Christmas decoration.', a: 'Holly' },
      { q: 'This hedgerow climber has tubular cream blooms with a sweet evening scent.', a: 'Honeysuckle' },
      { q: 'This shade plant is grown for big ribbed leaves that slugs love to chew.', a: 'Hosta' },
      { q: 'This bulb is forced indoors for a dense spike of heavily scented spring bells.', a: 'Hyacinth' },
      { q: 'This shrub has big mophead blooms that turn blue in acid soil.', a: 'Hydrangea' },
    ],
    I: [
      { q: 'This evergreen climber clings to walls with tiny aerial roots.', a: 'Ivy' },
      { q: 'This waterside bloom has three upright petals and three drooping falls.', a: 'Iris' },
      { q: 'This bedding plant is also known as busy lizzie.', a: 'Impatiens' },
      { q: 'This crisp pale round salad head is named after a floating mass of frozen water.', a: 'Iceberg lettuce' },
      { q: 'This botanical word means a cluster of blooms carried on one stalk.', a: 'Inflorescence' },
      { q: 'This narrow dark green column tree lines the driveways of Tuscan villas.', a: 'Italian cypress' },
    ],
    J: [
      { q: 'This climber has small white star-shaped blooms with a heady night scent.', a: 'Jasmine' },
      { q: 'This prickly conifer gives the blue-black berries that flavour gin.', a: 'Juniper' },
      { q: 'This huge spiky green tropical fruit is shredded as a meat substitute.', a: 'Jackfruit' },
      { q: 'This thick-stemmed succulent with fat oval leaves is nicknamed the money tree.', a: 'Jade plant' },
      { q: 'This small narcissus carries several strongly scented blooms on each stalk.', a: 'Jonquil' },
    ],
    K: [
      { q: 'This tough curly green leaf is a hardy winter member of the cabbage family.', a: 'Kale' },
      { q: 'This brown fuzzy fruit has bright green flesh and rows of tiny black seeds.', a: 'Kiwi' },
      { q: 'This swollen pale green stem vegetable looks like a turnip growing above ground.', a: 'Kohlrabi' },
      { q: 'This tiny oval citrus fruit is eaten whole, peel and all.', a: 'Kumquat' },
      { q: 'This succulent houseplant carries dense heads of tiny red or yellow blooms.', a: 'Kalanchoe' },
    ],
    L: [
      { q: 'This grey-leaved shrub gives fragrant purple spikes dried into scented bags.', a: 'Lavender' },
      { q: 'This is the mown grassy area at the centre of most gardens.', a: 'Lawn' },
      { q: 'This flat green part of a plant is where photosynthesis happens.', a: 'Leaf' },
      { q: 'This long white and green vegetable of the onion family is a Welsh emblem.', a: 'Leek' },
      { q: 'This sour yellow citrus fruit is squeezed over pancakes on Shrove Tuesday.', a: 'Lemon' },
      { q: 'Cos and butterhead are types of this salad leaf.', a: 'Lettuce' },
      { q: 'This shrub carries cones of scented mauve blossom in late spring.', a: 'Lilac' },
      { q: 'This bulb opens six broad petals and sheds heavy orange pollen.', a: 'Lily' },
      { q: 'This small green citrus fruit is wedged into a bottle of Mexican beer.', a: 'Lime' },
      { q: 'This water plant sits on round floating leaves and is sacred in Buddhism.', a: 'Lotus' },
      { q: 'This cottage-garden favourite sends up a dense spire of pea-like blooms.', a: 'Lupin' },
    ],
    M: [
      { q: 'This tree opens huge waxy pink or white blooms on bare branches in spring.', a: 'Magnolia' },
      { q: 'This tropical hardwood has a rich reddish brown colour prized for furniture.', a: 'Mahogany' },
      { q: 'This tall cereal crop grows cobs of yellow kernels.', a: 'Maize' },
      { q: 'The leaf of this tree appears on the flag of Canada.', a: 'Maple' },
      { q: 'This orange bedding bloom is planted beside vegetables to deter pests.', a: 'Marigold' },
      { q: 'This spreading herb is chopped into a sauce for roast lamb.', a: 'Mint' },
      { q: 'This white-berried plant grows on tree branches and you kiss beneath it.', a: 'Mistletoe' },
      { q: 'This soft green carpet of tiny plants grows on damp shady stones.', a: 'Moss' },
      { q: 'Gardeners spread this layer of bark or straw to hold in moisture.', a: 'Mulch' },
      { q: 'This fungus has a cap on a stalk and is fried for breakfast.', a: 'Mushroom' },
      { q: 'This aromatic Mediterranean evergreen has white blooms and dark berries.', a: 'Myrtle' },
      { q: 'These coastal trees grow in salt water on tangled stilt-like roots.', a: 'Mangrove' },
      { q: 'This orange spice is the lacy net that covers a nutmeg seed inside its fruit.', a: 'Mace' },
    ],
    N: [
      { q: 'This trailing plant has round leaves and peppery orange blooms you can eat.', a: 'Nasturtium' },
      { q: 'This smooth-skinned stone fruit is a fuzz-free cousin of the peach.', a: 'Nectarine' },
      { q: 'This weed stings your legs and is boiled into a green soup.', a: 'Nettle' },
      { q: 'This hard brown kernel is grated over custard and rice pudding.', a: 'Nutmeg' },
      { q: 'This is the botanical name for the group of bulbs that includes the daffodil.', a: 'Narcissus' },
      { q: 'Leafy growth needs plenty of this element, shown as N on a feed packet.', a: 'Nitrogen' },
    ],
    O: [
      { q: 'This mighty tree drops acorns and its timber built old warships.', a: 'Oak' },
      { q: 'This cereal crop is rolled into flakes for porridge.', a: 'Oats' },
      { q: 'These green ridged pods are also called ladies\' fingers.', a: 'Okra' },
      { q: 'Every part of this pink-flowered Mediterranean shrub is poisonous.', a: 'Oleander' },
      { q: 'This small bitter fruit is cured in brine and pressed for oil.', a: 'Olive' },
      { q: 'This bulb makes your eyes water when you slice it.', a: 'Onion' },
      { q: 'This round citrus fruit is squeezed for breakfast juice.', a: 'Orange' },
      { q: 'This houseplant sends an arching stem of waxy blooms above thick pale roots.', a: 'Orchid' },
      { q: 'This dried Mediterranean herb is sprinkled over pizza and tomato sauce.', a: 'Oregano' },
    ],
    P: [
      { q: 'This tropical tree has a bare trunk topped by a crown of huge fronds.', a: 'Palm' },
      { q: 'This low bedding bloom has a face-like blotch on overlapping velvety petals.', a: 'Pansy' },
      { q: 'This tropical fruit has orange flesh and a hollow of round black seeds.', a: 'Papaya' },
      { q: 'This curly green herb is stirred into a white sauce and used as a garnish.', a: 'Parsley' },
      { q: 'This pale cream root vegetable is roasted alongside a Sunday joint.', a: 'Parsnip' },
      { q: 'These small green spheres are shelled from a pod and often sold frozen.', a: 'Pea' },
      { q: 'This fuzzy-skinned stone fruit is grown in Georgia and canned in syrup.', a: 'Peach' },
      { q: 'Conference and Williams are varieties of this soft orchard fruit.', a: 'Pear' },
      { q: 'This cottage-garden plant opens enormous blowsy globes of pink in early summer.', a: 'Peony' },
      { q: 'This is the coloured part of a bloom that attracts insects.', a: 'Petal' },
      { q: 'This is the process by which a green leaf turns sunlight into sugar.', a: 'Photosynthesis' },
      { q: 'This conifer has needles in bundles and hard woody cones.', a: 'Pine' },
      { q: 'This tropical fruit has a spiky crown and a rough diamond-patterned skin.', a: 'Pineapple' },
      { q: 'This purple stone fruit is dried to make a prune.', a: 'Plum' },
      { q: 'This yellow dust is carried between blooms by bees.', a: 'Pollen' },
      { q: 'This leathery red fruit is packed with juicy ruby seeds.', a: 'Pomegranate' },
      { q: 'This scarlet field bloom is worn to remember the war dead.', a: 'Poppy' },
      { q: 'This underground tuber came from the Andes and is chipped or mashed.', a: 'Potato' },
      { q: 'This is the cutting back of branches to shape a plant and spur new growth.', a: 'Pruning' },
      { q: 'This big orange squash is hollowed out at Halloween.', a: 'Pumpkin' },
      { q: 'This trailing bedding plant has wide trumpet blooms and slightly sticky leaves.', a: 'Petunia' },
    ],
    Q: [
      { q: 'This hard yellow pear-shaped fruit is too sour to eat raw and is cooked into jelly.', a: 'Quince' },
      { q: 'This tiny South American seed is cooked like a grain and served in salads.', a: 'Quinoa' },
      { q: 'This American tree is named for the way its trembling leaves shake in the wind.', a: 'Quaking aspen' },
      { q: 'This frothy white wild carrot of summer roadsides is named for a British monarch.', a: 'Queen Anne\'s lace' },
    ],
    R: [
      { q: 'This small round red salad root has a hot peppery bite.', a: 'Radish' },
      { q: 'This soft red summer fruit is a hollow cone of tiny juicy beads.', a: 'Raspberry' },
      { q: 'This giant Californian conifer has thick fibrous bark and grows in coastal fog.', a: 'Redwood' },
      { q: 'This big-leaved evergreen shrub smothers itself in purple trusses each May.', a: 'Rhododendron' },
      { q: 'These tart pink stalks are stewed with sugar into a crumble.', a: 'Rhubarb' },
      { q: 'This cereal is grown in flooded paddies and feeds much of Asia.', a: 'Rice' },
      { q: 'This underground part of a plant takes up water and anchors it.', a: 'Root' },
      { q: 'This thorny shrub is the national flower of England.', a: 'Rose' },
      { q: 'This woody herb has needle-like leaves and is tucked under roast lamb.', a: 'Rosemary' },
      { q: 'This small mountain tree carries bunches of bright orange-red berries in autumn.', a: 'Rowan' },
      { q: 'This climbing vegetable has red blooms and long flat green pods.', a: 'Runner bean' },
    ],
    S: [
      { q: 'This grey-green herb is rubbed into stuffing with onion.', a: 'Sage' },
      { q: 'This costly golden spice is the dried stigmas of a purple crocus.', a: 'Saffron' },
      { q: 'This is the watery fluid that flows through a tree and is boiled down for syrup.', a: 'Sap' },
      { q: 'This is the part a plant makes so that a new one can grow.', a: 'Seed' },
      { q: 'Squeeze the sides of this bloom and its mouth opens like a jaw.', a: 'Snapdragon' },
      { q: 'This nodding white bulb is the first bloom of the new year in many gardens.', a: 'Snowdrop' },
      { q: 'This is the mixture of minerals and rotted matter that plants root into.', a: 'Soil' },
      { q: 'This dark green leaf wilts to almost nothing and is baked in a pie with feta.', a: 'Spinach' },
      { q: 'This conifer with short stiff needles is the classic Norway Christmas tree.', a: 'Spruce' },
      { q: 'This is the male pollen-bearing part of a bloom.', a: 'Stamen' },
      { q: 'This is the main upright part of a plant that holds up the leaves.', a: 'Stem' },
      { q: 'This red summer fruit is eaten with cream at Wimbledon.', a: 'Strawberry' },
      { q: 'This towering annual carries one huge yellow head packed with seeds.', a: 'Sunflower' },
      { q: 'This scented climbing annual is grown up wigwams of canes for cutting.', a: 'Sweet pea' },
      { q: 'This large tree drops winged seeds that spin down like helicopters.', a: 'Sycamore' },
      { q: 'This word describes a plant with thick fleshy leaves that hold a store of water.', a: 'Succulent' },
      { q: 'This small mild onion grows in clusters and is prized in French cooking.', a: 'Shallot' },
      { q: 'Butternut and acorn are types of this thick-skinned vegetable.', a: 'Squash' },
    ],
    T: [
      { q: 'This slim-leaved French herb is the key flavour of bearnaise sauce.', a: 'Tarragon' },
      { q: 'This spiny purple-headed plant is the emblem of Scotland.', a: 'Thistle' },
      { q: 'This tiny-leaved creeping herb is a standard part of a bouquet garni.', a: 'Thyme' },
      { q: 'Beefsteak and cherry are types of this red salad fruit.', a: 'Tomato' },
      { q: 'This is the art of clipping hedges and shrubs into animal shapes.', a: 'Topiary' },
      { q: 'This spring bulb set off a speculative mania in the Dutch Golden Age.', a: 'Tulip' },
      { q: 'This round white root vegetable with a purple top is often fed to sheep.', a: 'Turnip' },
      { q: 'This dense oily tropical hardwood is used for garden furniture and boat decks.', a: 'Teak' },
      { q: 'This is the thick woody main stem of a tree.', a: 'Trunk' },
      { q: 'This curling thread lets a vine or a sweet pea grip its support.', a: 'Tendril' },
    ],
    U: [
      { q: 'This wrinkly Jamaican citrus is a cross between a grapefruit and a tangerine.', a: 'Ugli fruit' },
      { q: 'This glossy-leaved houseplant holds its leaflets in a spoke-like whorl.', a: 'Umbrella tree' },
      { q: 'This silver-banded bromeliad holds water in the funnel of its leaves.', a: 'Urn plant' },
      { q: 'This is the layer of shrubs and small trees growing beneath a forest canopy.', a: 'Understorey' },
    ],
    V: [
      { q: 'This flavour comes from the cured seed pod of a climbing orchid.', a: 'Vanilla' },
      { q: 'This bog plant snaps its hinged leaves shut on an insect.', a: 'Venus flytrap' },
      { q: 'Grapes are grown on this trained climbing plant.', a: 'Vine' },
      { q: 'This small shy purple woodland bloom has heart-shaped leaves and a sweet scent.', a: 'Violet' },
      { q: 'This half-hardy bedding plant carries flat heads of small bright blooms all summer.', a: 'Verbena' },
    ],
    W: [
      { q: 'This wrinkled brown nut has a shell in two halves and gives a dark furniture timber.', a: 'Walnut' },
      { q: 'This peppery salad leaf is grown in shallow flowing beds.', a: 'Watercress' },
      { q: 'This huge green-skinned summer fruit has sweet pink flesh and black pips.', a: 'Watermelon' },
      { q: 'This is the gardener\'s word for any plant growing where it is not wanted.', a: 'Weed' },
      { q: 'This cereal crop is milled into white flour for bread.', a: 'Wheat' },
      { q: 'This waterside tree has long drooping branches and its timber makes cricket bats.', a: 'Willow' },
      { q: 'This vigorous climber drapes a house front in hanging mauve chains in May.', a: 'Wisteria' },
      { q: 'This scented spring bedding plant in velvety orange and red is planted with tulips.', a: 'Wallflower' },
    ],
    Y: [
      { q: 'This dark evergreen conifer with red berry-like cones is found in old churchyards.', a: 'Yew' },
      { q: 'This spiky-leaved desert plant is grown indoors as a stiff architectural feature.', a: 'Yucca' },
      { q: 'This starchy tropical tuber is a staple food across West Africa.', a: 'Yam' },
      { q: 'This feathery-leaved meadow plant carries flat white heads on wiry stems.', a: 'Yarrow' },
    ],
    Z: [
      { q: 'This bright Mexican annual gives long-lasting daisy-shaped blooms for cutting.', a: 'Zinnia' },
      { q: 'This is the American name for the courgette.', a: 'Zucchini' },
      { q: 'This houseplant has dark green leaves boldly striped with white veins.', a: 'Zebra plant' },
      { q: 'This is the grated outer coloured layer of a citrus peel.', a: 'Zest' },
    ],
  },
};
