import type { RawPack } from '../core/packs';

export const riversLakesPack: RawPack = {
  id: 'rivers-lakes',
  name: 'Rivers, Lakes & Waterfalls',
  description: 'The great waterways of the world, from mountain springs to thundering falls.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🌊',
  accent: '#0369a1',
  letters: {
    A: [
      { q: 'The South American river that carries more water than any other on Earth.', a: 'Amazon' },
      { q: 'The Venezuelan cascade, the tallest in the world, named after an American aviator.', a: 'Angel Falls' },
      { q: 'The Egyptian city whose High Dam created a vast reservoir in the 1960s.', a: 'Aswan' },
      { q: 'The Central Asian inland sea that has almost dried up since the 1960s.', a: 'Aral Sea' },
      { q: 'The longest river of Central Asia, once feeding that dying sea.', a: 'Amu Darya' },
      { q: 'The underground layer of porous rock that holds and yields water.', a: 'Aquifer' },
      { q: 'The word for the fertile silt spread out by a river in flood.', a: 'Alluvial' },
      { q: 'The Italian river that flows through Florence and flooded it in 1966.', a: 'Arno' },
      { q: 'The Canadian river and lake in Alberta whose oil sands bear their name.', a: 'Athabasca' },
      { q: 'The only river that flows out of Lake Baikal.', a: 'Angara' },
    ],
    B: [
      { q: 'The Siberian lake that holds a fifth of all the fresh surface water on Earth.', a: 'Baikal' },
      { q: 'The branch that rises in Ethiopia and brings most of the flood to Khartoum.', a: 'Blue Nile' },
      { q: 'The mighty river of Tibet and Assam that joins the Ganges in Bangladesh.', a: 'Brahmaputra' },
      { q: 'The whole area of land that drains into one river system.', a: 'Basin' },
      { q: 'The side of a channel, called left or right as you face downstream.', a: 'Bank' },
      { q: 'The bottom of a channel, over which the water runs.', a: 'Bed' },
      { q: 'The Congo cataracts that carry more water each second than any other falls.', a: 'Boyoma' },
      { q: 'The largest lake in central Europe, in Hungary.', a: 'Balaton' },
      { q: 'The Australian word for a cut-off pool left beside a dried river course.', a: 'Billabong' },
      { q: 'The German town where the Rhine gorge begins, with the Mouse Tower on its islet.', a: 'Bingen' },
    ],
    C: [
      { q: 'The African river, second longest on that continent, that drains a huge rainforest.', a: 'Congo' },
      { q: 'The river that carved the Grand Canyon.', a: 'Colorado' },
      { q: 'The place where two streams join into one.', a: 'Confluence' },
      { q: 'The word for a large steep rush of falling water, or a rocky Nile rapid.', a: 'Cataract' },
      { q: 'The shallow African lake, once huge, that has shrunk drastically since 1960.', a: 'Chad' },
      { q: 'The deepest part of a waterway, kept dredged for boats.', a: 'Channel' },
      { q: 'The largest inland body of water in the world, bordered by five countries.', a: 'Caspian Sea' },
      { q: 'The great river of the Pacific Northwest, dammed at Grand Coulee.', a: 'Columbia' },
      { q: 'The steady flow of water in one direction along a channel.', a: 'Current' },
      { q: 'The southern Indian river disputed between Karnataka and Tamil Nadu.', a: 'Cauvery' },
      { q: 'The river that flows through Bangkok.', a: 'Chao Phraya' },
    ],
    D: [
      { q: 'The European river that passes through ten countries and four capitals.', a: 'Danube' },
      { q: 'The fan of silt and channels a river builds where it enters the sea.', a: 'Delta' },
      { q: 'The wall built across a valley to hold water back.', a: 'Dam' },
      { q: 'The river that flows through Kyiv to the Black Sea.', a: 'Dnieper' },
      { q: 'The Iberian river of the port wine terraces, called Duero in Spain.', a: 'Douro' },
      { q: 'The volume of water passing a point each second, measured in cumecs.', a: 'Discharge' },
      { q: 'The pattern of streams that carry rainfall off a landscape.', a: 'Drainage' },
      { q: 'The Russian river that gave its name to the Cossack heartland.', a: 'Don' },
      { q: 'The direction the water is going, away from the source.', a: 'Downstream' },
      { q: 'The river that flows through Chester and out into the Irish Sea.', a: 'Dee' },
      { q: 'The salt lake at the lowest land surface on Earth, in which nothing swims.', a: 'Dead Sea' },
    ],
    E: [
      { q: 'The shallowest and warmest of the five North American Great Lakes.', a: 'Erie' },
      { q: 'The Mesopotamian river that runs beside the Tigris to the Gulf.', a: 'Euphrates' },
      { q: 'The tidal mouth of a river, where salt and fresh water mingle.', a: 'Estuary' },
      { q: 'The German river that reaches the sea at Hamburg.', a: 'Elbe' },
      { q: 'A small swirl of water spinning against the main flow.', a: 'Eddy' },
      { q: 'The Spanish river that gave its name to the whole peninsula.', a: 'Ebro' },
      { q: 'The wearing away of rock and soil by moving water.', a: 'Erosion' },
      { q: 'The vast slow sheet of Florida marsh water, a river of grass.', a: 'Everglades' },
      { q: 'The choking of a lake by algae after fertiliser washes into it.', a: 'Eutrophication' },
      { q: 'The north German river that reaches the sea near Emden.', a: 'Ems' },
    ],
    F: [
      { q: 'The shallow crossing place where a road meets a stream.', a: 'Ford' },
      { q: 'The overflow of water onto land that is normally dry.', a: 'Flood' },
      { q: 'The flat land beside a channel, built up by silt and covered when the water rises.', a: 'Floodplain' },
      { q: 'Water with little dissolved salt, as in rivers and most lakes.', a: 'Freshwater' },
      { q: 'The stepped structure built beside a dam so salmon can climb it.', a: 'Fish ladder' },
      { q: 'The great river of British Columbia, named after an explorer.', a: 'Fraser' },
      { q: 'The Tasmanian river saved from a dam by mass protest in 1983.', a: 'Franklin' },
      { q: 'The rate at which water moves past a point.', a: 'Flow' },
      { q: 'The white spray thrown up at the foot of a cascade.', a: 'Foam' },
    ],
    G: [
      { q: 'The sacred river of India, worshipped as a goddess.', a: 'Ganges' },
      { q: 'The five vast freshwater bodies shared by Canada and the United States.', a: 'Great Lakes' },
      { q: 'The river forming part of the southern border between Spain and Portugal.', a: 'Guadiana' },
      { q: 'The staff or instrument that reads the height of a river.', a: 'Gauge' },
      { q: 'The Swiss lake, shaped like a crescent, on which Lausanne stands.', a: 'Geneva' },
      { q: 'A narrow steep-sided valley cut by a river through rock.', a: 'Gorge' },
      { q: 'The broad Icelandic cascade on the Hvita, on the Golden Circle route.', a: 'Gullfoss' },
      { q: 'The slow river of ice whose meltwater feeds many great rivers.', a: 'Glacier' },
      { q: 'The Arizona chasm, over a mile deep, cut by the Colorado.', a: 'Grand Canyon' },
      { q: 'The second longest river of India, flowing east across the Deccan.', a: 'Godavari' },
      { q: 'The Andalusian river on which Seville stands, navigable to the sea.', a: 'Guadalquivir' },
    ],
    H: [
      { q: 'The Chinese river whose silt gives it a colour and whose floods earned it the name sorrow.', a: 'Huang He' },
      { q: 'The New York river named after the English navigator who sailed up it in 1609.', a: 'Hudson' },
      { q: 'The Nevada dam on the Colorado, completed in 1936, that made Lake Mead.', a: 'Hoover Dam' },
      { q: 'The stream at the very top of a river system, nearest its source.', a: 'Headwater' },
      { q: 'Electricity generated by falling or flowing water.', a: 'Hydroelectric' },
      { q: 'The Great Lake between Michigan and Ontario, with Georgian Bay on its side.', a: 'Huron' },
      { q: 'The larger Canadian half of the great cascade on the Niagara.', a: 'Horseshoe Falls' },
      { q: 'The English estuary at Hull, formed by the Ouse and the Trent.', a: 'Humber' },
      { q: 'The scientific study of water on and under the land.', a: 'Hydrology' },
    ],
    I: [
      { q: 'The river that gave its name to a subcontinent and now flows through Pakistan.', a: 'Indus' },
      { q: 'The chief river of Myanmar, flowing from the north to the Andaman Sea.', a: 'Irrawaddy' },
      { q: 'The vast horseshoe of cascades on the border of Argentina and Brazil.', a: 'Iguazu' },
      { q: 'The Siberian river that joins the Ob to form one of the longest systems.', a: 'Irtysh' },
      { q: 'A small arm of a lake or sea reaching into the land.', a: 'Inlet' },
      { q: 'The diversion of river water onto fields to grow crops.', a: 'Irrigation' },
      { q: 'The great mountain lake of Kyrgyzstan, salty and never frozen.', a: 'Issyk-Kul' },
      { q: 'The Alpine river that joins the Danube at Passau.', a: 'Inn' },
    ],
    J: [
      { q: 'The river of the Holy Land that flows into the Dead Sea.', a: 'Jordan' },
      { q: 'The Kashmiri river, one of the five that name the Punjab.', a: 'Jhelum' },
      { q: 'The Ugandan town on Lake Victoria where the White Nile begins.', a: 'Jinja' },
      { q: 'The Chinese word for river, as in Chang and Zhu.', a: 'Jiang' },
      { q: 'The Somali river that reaches the Indian Ocean near Kismayo.', a: 'Juba' },
    ],
    K: [
      { q: 'The huge reservoir on the Zambezi, made by a dam finished in 1959.', a: 'Kariba' },
      { q: 'The single-drop cascade on the Potaro in Guyana, one of the most powerful anywhere.', a: 'Kaieteur' },
      { q: 'The river of far north-eastern Siberia, frozen most of the year.', a: 'Kolyma' },
      { q: 'The largest left-bank tributary of the Volga.', a: 'Kama' },
      { q: 'The only navigable river of Iran, flowing past Ahvaz.', a: 'Karun' },
      { q: 'The longest headstream feeding Lake Victoria, from Burundi and Rwanda.', a: 'Kagera' },
    ],
    L: [
      { q: 'A body of standing water surrounded by land.', a: 'Lake' },
      { q: 'The longest river entirely within France, famous for its chateaux.', a: 'Loire' },
      { q: 'The African river that forms the northern border of South Africa.', a: 'Limpopo' },
      { q: 'The raised embankment built along a channel to stop it overflowing.', a: 'Levee' },
      { q: 'The Siberian river that flows north to the Arctic through Yakutsk.', a: 'Lena' },
      { q: 'The Irish and Scottish word for a lake.', a: 'Lough' },
      { q: 'The chamber with gates that lifts a boat from one water level to another.', a: 'Lock' },
      { q: 'The largest lake in Europe, in north-western Russia.', a: 'Ladoga' },
      { q: 'The study of inland waters, the freshwater counterpart of oceanography.', a: 'Limnology' },
    ],
    M: [
      { q: 'The great river of the United States, joined by the Missouri at St Louis.', a: 'Mississippi' },
      { q: 'The longest river in North America, rising in the Rockies.', a: 'Missouri' },
      { q: 'A wide sweeping bend in a slow lowland channel.', a: 'Meander' },
      { q: 'The river of Southeast Asia that runs through six countries to a huge delta.', a: 'Mekong' },
      { q: 'The longest river in Australia, joined by the Darling.', a: 'Murray' },
      { q: 'Low waterlogged ground thick with reeds and grasses.', a: 'Marsh' },
      { q: 'The only Great Lake wholly inside the United States.', a: 'Michigan' },
      { q: 'The Nevada reservoir behind the Hoover Dam.', a: 'Mead' },
      { q: 'The long deep African lake, also called Nyasa, third largest on the continent.', a: 'Malawi' },
      { q: 'The end of a river, where it finally empties out.', a: 'Mouth' },
      { q: 'The chief river of Colombia, flowing north to the Caribbean.', a: 'Magdalena' },
      { q: 'The longest river in Canada, flowing to the Beaufort Sea.', a: 'Mackenzie' },
    ],
    N: [
      { q: 'The river traditionally called the longest in the world.', a: 'Nile' },
      { q: 'The cascades between Lake Erie and Lake Ontario, a honeymoon byword.', a: 'Niagara' },
      { q: 'The great West African river that loops through Mali and Nigeria.', a: 'Niger' },
      { q: 'The Egyptian reservoir behind the High Dam, named after a president.', a: 'Nasser' },
      { q: 'The short Russian river on which St Petersburg was built.', a: 'Neva' },
      { q: 'The Indian river of the Vindhya gorge, flowing west to the Arabian Sea.', a: 'Narmada' },
      { q: 'The long deep Scottish loch said to hold a monster.', a: 'Ness' },
      { q: 'The largest lake in the British Isles, in Northern Ireland.', a: 'Neagh' },
    ],
    O: [
      { q: 'The South American river of Venezuela with a great fan-shaped delta.', a: 'Orinoco' },
      { q: 'The curved pond left behind when a meander is cut off.', a: 'Oxbow' },
      { q: 'The American river that joins the Mississippi at Cairo, Illinois.', a: 'Ohio' },
      { q: 'The vast Siberian river that empties into a great Arctic gulf.', a: 'Ob' },
      { q: 'The smallest by area of the five Great Lakes, into which the Niagara falls.', a: 'Ontario' },
      { q: 'The Botswanan inland delta where a river dies in the Kalahari sands.', a: 'Okavango' },
      { q: 'The river that forms much of the border between Germany and Poland.', a: 'Oder' },
      { q: 'The point at which water leaves a lake to continue on its way.', a: 'Outlet' },
      { q: 'The longest river in South Africa, reaching the Atlantic.', a: 'Orange' },
    ],
    P: [
      { q: 'The longest river in Italy, flowing east across the northern plain.', a: 'Po' },
      { q: 'The second longest river in South America, dammed at Itaipu.', a: 'Parana' },
      { q: 'The deep basin scoured out at the foot of a cascade.', a: 'Plunge pool' },
      { q: 'The river on whose bank Washington DC stands.', a: 'Potomac' },
      { q: 'A small still body of water, smaller than a lake.', a: 'Pond' },
      { q: 'The closed pipe that carries water down to a turbine in a hydro station.', a: 'Penstock' },
      { q: 'The Bangladeshi name for the lower Ganges.', a: 'Padma' },
      { q: 'A deep still stretch of a stream, where the fish lie.', a: 'Pool' },
      { q: 'The river that gives its name to a landlocked South American country.', a: 'Paraguay' },
    ],
    Q: [
      { q: 'Soft wet ground that swallows a boot, a bog at its worst.', a: 'Quagmire' },
      { q: 'Wet sand so saturated that it cannot bear weight.', a: 'Quicksand' },
    ],
    R: [
      { q: 'The great river of western Germany, from the Alps to the Dutch delta.', a: 'Rhine' },
      { q: 'The swift French river from a Swiss glacier to the Mediterranean.', a: 'Rhone' },
      { q: 'The stretch of broken white water rushing over rocks.', a: 'Rapids' },
      { q: 'The artificial lake held behind a dam.', a: 'Reservoir' },
      { q: 'The word for the strip of land and life along a bank.', a: 'Riparian' },
      { q: 'The border river between Texas and Mexico.', a: 'Rio Grande' },
      { q: 'One of the five Punjab rivers, flowing past Lahore.', a: 'Ravi' },
      { q: 'The tall marsh grass whose hollow stems are cut for thatch and pens.', a: 'Reed' },
      { q: 'The share of rainfall that flows over the surface instead of soaking in.', a: 'Runoff' },
    ],
    S: [
      { q: 'The river that flows through Paris.', a: 'Seine' },
      { q: 'The longest river in Britain, with a famous tidal bore.', a: 'Severn' },
      { q: 'The largest of the Great Lakes, and the biggest freshwater lake by area.', a: 'Superior' },
      { q: 'The spring or glacier where a river begins.', a: 'Source' },
      { q: 'The fine mud a river carries and drops when it slows.', a: 'Silt' },
      { q: 'The place where groundwater comes out of the ground naturally.', a: 'Spring' },
      { q: 'All the material a flow carries and lays down on its bed.', a: 'Sediment' },
      { q: 'The American river that carved Hells Canyon in Idaho.', a: 'Snake' },
      { q: 'The longest river in Ireland.', a: 'Shannon' },
      { q: 'The gate in a channel that can be raised to let water through.', a: 'Sluice' },
      { q: 'The Danube tributary that flows through Belgrade.', a: 'Sava' },
      { q: 'The long river of China and Myanmar, largely undammed and hard to navigate.', a: 'Salween' },
    ],
    T: [
      { q: 'The river that flows through London.', a: 'Thames' },
      { q: 'The Iraqi river on which Baghdad and Mosul stand.', a: 'Tigris' },
      { q: 'A smaller stream that flows into a larger one.', a: 'Tributary' },
      { q: 'The Andean lake, the highest in the world that ships can work on.', a: 'Titicaca' },
      { q: 'The long African lake, the second deepest on Earth, west of Tanzania.', a: 'Tanganyika' },
      { q: 'The bladed wheel that a jet of water spins to make power.', a: 'Turbine' },
      { q: 'The clear blue lake high in the Sierra Nevada.', a: 'Tahoe' },
      { q: 'The South African cascade in the Drakensberg, among the tallest anywhere.', a: 'Tugela' },
      { q: 'A violently fast rush of water down a steep bed.', a: 'Torrent' },
      { q: 'The longest river in Scotland.', a: 'Tay' },
      { q: 'The Hungarian river that joins the Danube in Serbia.', a: 'Tisza' },
    ],
    U: [
      { q: 'The river that runs from the mountains of the same name to the Caspian.', a: 'Ural' },
      { q: 'The direction against the flow, toward the source.', a: 'Upstream' },
      { q: 'The African river that forms the border of the two Congos.', a: 'Ubangi' },
      { q: 'The sacred river of the Inca, running below Machu Picchu.', a: 'Urubamba' },
      { q: 'The river that separates Argentina from the country of the same name.', a: 'Uruguay' },
    ],
    V: [
      { q: 'The longest river in Europe, flowing to the Caspian.', a: 'Volga' },
      { q: 'The mile-wide curtain on the Zambezi, called the smoke that thunders.', a: 'Victoria Falls' },
      { q: 'The Ghanaian river whose Akosombo dam made one of the largest reservoirs on Earth.', a: 'Volta' },
      { q: 'The low ground between hills through which a river runs.', a: 'Valley' },
      { q: 'The chief tributary of the Orange, which flows past Johannesburg.', a: 'Vaal' },
      { q: 'The longest river in Poland, flowing through Warsaw to the Baltic.', a: 'Vistula' },
      { q: 'The largest lake in Sweden, and in the whole European Union.', a: 'Vanern' },
    ],
    W: [
      { q: 'The ridge of high ground that separates one drainage basin from the next.', a: 'Watershed' },
      { q: 'The low barrier built across a stream to raise the level or measure the flow.', a: 'Weir' },
      { q: 'Marsh, bog or swamp, ground saturated for much of the year.', a: 'Wetland' },
      { q: 'A place where a river drops over a step of rock.', a: 'Waterfall' },
      { q: 'The sport of paddling deliberately through the roughest rapids.', a: 'Whitewater' },
      { q: 'The level below which the ground is saturated, and which wells must reach.', a: 'Water table' },
      { q: 'The river that forms much of the border between England and Wales.', a: 'Wye' },
      { q: 'The longest river in New Zealand.', a: 'Waikato' },
    ],
    X: [
      { q: 'The Brazilian tributary of the Amazon whose indigenous park bears its name.', a: 'Xingu' },
      { q: 'The Chinese river of the south, also called the West River, that reaches Guangzhou.', a: 'Xi' },
    ],
    Y: [
      { q: 'The Siberian river that divides western from eastern Siberia.', a: 'Yenisei' },
      { q: 'The great river of Alaska and the Canadian territory that shares its name.', a: 'Yukon' },
      { q: 'The English county whose Dales hold Aysgarth and Hardraw Force.', a: 'Yorkshire' },
      { q: 'The Chinese river of Nanjing and Wuhan, the longest in Asia.', a: 'Yangtze' },
      { q: 'The Indian river that flows past the Taj Mahal and joins the Ganges at Prayagraj.', a: 'Yamuna' },
    ],
    Z: [
      { q: 'The fourth longest river in Africa, which drops over a famous curtain of water.', a: 'Zambezi' },
      { q: 'The Swiss lake on which the country largest city stands.', a: 'Zurich' },
      { q: 'The old colonial name for the Congo, still used for the river in some atlases.', a: 'Zaire' },
      { q: 'The Himalayan river of Ladakh whose winter ice becomes a trekking route.', a: 'Zanskar' },
    ],
  },
};
