import type { RawPack } from '../core/packs';

export const roboticsAiPack: RawPack = {
  id: 'robotics-ai',
  name: 'Robots & AI',
  description: 'Machines that think and move, from Turing to self-driving cars.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🤖',
  accent: '#0891b2',
  letters: {
    A: [
      { q: 'The set of step-by-step rules a computer follows to solve a problem.', a: 'Algorithm' },
      { q: 'The two-word field name coined by John McCarthy for the 1956 Dartmouth workshop.', a: 'Artificial intelligence' },
      { q: 'The mechanical joint and limb that lets a machine reach and grip.', a: 'Arm' },
      { q: 'A piece of software that acts on its own initiative to reach a goal you set.', a: 'Agent' },
      { q: 'The lab, founded in 2021 by former OpenAI staff, that built Claude.', a: 'Anthropic' },
      { q: 'The Boston Dynamics humanoid that does parkour and backflips.', a: 'Atlas' },
      { q: 'The Amazon voice assistant, launched in 2014, that answers to a name.', a: 'Alexa' },
      { q: 'The Google program that beat Lee Sedol at Go in 2016.', a: 'AlphaGo' },
      { q: 'The self-moving mechanical figure of the 18th century, built to mimic life.', a: 'Automaton' },
      { q: 'The word for a machine working without human control at all.', a: 'Autonomous' },
      { q: 'The 2001 Spielberg film whose title is the two initials of the field.', a: 'AI' },
      { q: 'The far-off machine that would match a person at every mental task, three letters.', a: 'AGI' },
      { q: 'The Honda humanoid, retired in 2018, that walked and climbed stairs.', a: 'Asimo' },
      { q: 'The Sony entertainment dog, launched in 1999, that learned tricks.', a: 'Aibo' },
      { q: 'The replacing of human labour by machines on a production line.', a: 'Automation' },
      { q: 'The 2017 mechanism that lets a model weigh which words matter most.', a: 'Attention' },
      { q: 'The research problem of making a system pursue what people actually want.', a: 'Alignment' },
    ],
    B: [
      { q: 'The digit that is either nought or one.', a: 'Bit' },
      { q: 'The number system of noughts and ones in which all machines compute.', a: 'Binary' },
      { q: 'The training method that pushes the error backwards through a network to fix weights.', a: 'Backpropagation' },
      { q: 'The American firm of the walking robot dog Spot and the humanoid Atlas.', a: 'Boston Dynamics' },
      { q: 'A program that talks to people in text, from Eliza to the modern kind.', a: 'Bot' },
      { q: 'The number of samples a model chews through before it updates its weights.', a: 'Batch' },
      { q: 'The unfair skew a model learns from lopsided training data.', a: 'Bias' },
      { q: 'The standard test set on which rival models are compared.', a: 'Benchmark' },
      { q: 'The crude approach of trying every possible answer in turn.', a: 'Brute force' },
      { q: 'The word for a machine that walks on two legs, like a person.', a: 'Bipedal' },
    ],
    C: [
      { q: 'The program that holds a conversation in text with whoever types to it.', a: 'Chatbot' },
      { q: 'The 1948 Wiener science of control and communication in animal and machine.', a: 'Cybernetics' },
      { q: 'The network layer type that slides a small filter over an image to find features.', a: 'Convolution' },
      { q: 'The processor at the heart of a computer, three letters.', a: 'CPU' },
      { q: 'The teaching of a machine to see and understand pictures.', a: 'Computer vision' },
      { q: 'The being that is part human, part machine.', a: 'Cyborg' },
      { q: 'The Anthropic assistant named after a pioneer of information theory.', a: 'Claude' },
      { q: 'The cloud service that rents out computing power by the hour.', a: 'Compute' },
      { q: 'The programmed path a welding robot repeats exactly on a car line.', a: 'Cycle' },
      { q: 'The grouping an unsupervised method finds by itself in unlabelled data.', a: 'Cluster' },
      { q: 'The GitHub tool that suggests the next lines of code as you type.', a: 'Copilot' },
      { q: 'The written instructions a programmer gives a machine.', a: 'Code' },
    ],
    D: [
      { q: 'The many-layered branch that took over the whole field after 2012.', a: 'Deep learning' },
      { q: 'The information a model is trained on.', a: 'Data' },
      { q: 'The IBM machine that beat Kasparov at chess in 1997.', a: 'Deep Blue' },
      { q: 'The London lab, bought by Google in 2014, that made the Go champion program.', a: 'DeepMind' },
      { q: 'The remote-controlled flying machine now used for delivery and for filming.', a: 'Drone' },
      { q: 'The American defence research agency whose 2005 desert race spurred self-driving cars.', a: 'DARPA' },
      { q: 'The tree-shaped diagram of yes-or-no splits used as a simple classifier.', a: 'Decision tree' },
      { q: 'The assembled collection of examples used to train and test a model.', a: 'Dataset' },
      { q: 'The image-making method that starts from noise and cleans it up step by step.', a: 'Diffusion' },
      { q: 'The pair of networks that compete, one making fakes and one judging them.', a: 'Discriminator' },
      { q: 'The technique of dropping random units in training so a model does not memorise.', a: 'Dropout' },
    ],
    E: [
      { q: 'The end tool of a robot arm, whether gripper, welder or suction cup.', a: 'End effector' },
      { q: 'The 1966 MIT program that imitated a therapist by turning statements into questions.', a: 'Eliza' },
      { q: 'One full pass of the whole training set through a model.', a: 'Epoch' },
      { q: 'The turning of words into lists of numbers a model can compare.', a: 'Embedding' },
      { q: 'The sensor that counts shaft rotations so a motor knows where it is.', a: 'Encoder' },
      { q: 'The branch of philosophy a self-driving car forces engineers to think about.', a: 'Ethics' },
      { q: 'The rule-based program of the 1980s that captured a specialist knowledge.', a: 'Expert system' },
      { q: 'The tiny computer built into a washing machine or a car, not sold on its own.', a: 'Embedded system' },
      { q: 'The method that copies natural selection to breed better solutions.', a: 'Evolutionary algorithm' },
    ],
    F: [
      { q: 'The forward pass of data through a network from input to output.', a: 'Feedforward' },
      { q: 'The measurable property of the input that a model actually learns from.', a: 'Feature' },
      { q: 'The further training of a general model on a narrow task.', a: 'Fine-tuning' },
      { q: 'The reasoning that allows values between true and false, used in rice cookers.', a: 'Fuzzy logic' },
      { q: 'The moving assembly line where welding robots outnumber people.', a: 'Factory' },
      { q: 'The approach that trains across many phones without ever pooling their data.', a: 'Federated learning' },
      { q: 'The signal a system sends back to itself to keep its output on target.', a: 'Feedback' },
      { q: 'The video or picture generated to look real but showing something that never happened.', a: 'Fake' },
      { q: 'The Japanese maker whose yellow arms are the most numerous in the world.', a: 'Fanuc' },
    ],
    G: [
      { q: 'The graphics chip whose parallel maths made deep learning practical.', a: 'GPU' },
      { q: 'The pair of duelling networks introduced by Goodfellow in 2014, three letters.', a: 'GAN' },
      { q: 'The claw or suction device with which a machine picks something up.', a: 'Gripper' },
      { q: 'The optimisation method that rolls downhill to the lowest error.', a: 'Gradient descent' },
      { q: 'The generative pre-trained model family whose third version stunned the public in 2020.', a: 'GPT' },
      { q: 'The search giant whose Waymo unit runs driverless taxis in Phoenix.', a: 'Google' },
      { q: 'The kind of AI that produces new text, images or sound rather than just classifying.', a: 'Generative' },
      { q: 'The ability of a model to do well on data it has never seen before.', a: 'Generalisation' },
      { q: 'The Google family of multimodal models launched in December 2023.', a: 'Gemini' },
    ],
    H: [
      { q: 'A robot shaped like a person, with head, torso and two legs.', a: 'Humanoid' },
      { q: 'The confident invention of a false fact by a language model.', a: 'Hallucination' },
      { q: 'The physical parts of a machine, as against the programs.', a: 'Hardware' },
      { q: 'The rule of thumb a search uses to guess which branch to try first.', a: 'Heuristic' },
      { q: 'The 1968 Kubrick film computer that refused to open the pod bay doors.', a: 'HAL' },
      { q: 'The setting chosen before training begins, such as the learning rate.', a: 'Hyperparameter' },
      { q: 'The British-Canadian godfather of deep learning who left Google in 2023.', a: 'Hinton' },
      { q: 'The person kept in the loop so a machine decision can be checked.', a: 'Human oversight' },
      { q: 'The insect-like six-legged design that still stands if one limb fails.', a: 'Hexapod' },
    ],
    I: [
      { q: 'The running of a trained model to get an answer, as opposed to training it.', a: 'Inference' },
      { q: 'The data fed into a model or a machine.', a: 'Input' },
      { q: 'The mechanical worker on a car line, the commonest kind in the world.', a: 'Industrial robot' },
      { q: 'The network of everyday objects with chips and connections, three initials.', a: 'IoT' },
      { q: 'The Asimov collection of nine stories that set out the famous three laws.', a: 'I, Robot' },
      { q: 'The maths of working out what joint angles will put a hand in a given place.', a: 'Inverse kinematics' },
      { q: 'The picture recognition contest whose 2012 result launched deep learning.', a: 'ImageNet' },
      { q: 'The chip designed for one job only, faster than a general processor.', a: 'Integrated circuit' },
    ],
    J: [
      { q: 'The moving connection between two rigid links of a robot arm.', a: 'Joint' },
      { q: 'The stick control used to drive a machine by hand.', a: 'Joystick' },
      { q: 'The Nvidia board, named after a cartoon family, used in student robots.', a: 'Jetson' },
      { q: 'The Python notebook, named after three planets, in which most model code is written.', a: 'Jupyter' },
    ],
    K: [
      { q: 'The study of motion and joint geometry in a mechanical limb.', a: 'Kinematics' },
      { q: 'The structured store of facts and relations a reasoning system draws on.', a: 'Knowledge base' },
      { q: 'The Japanese giant whose orange arms weld cars all over the world.', a: 'Kawasaki' },
      { q: 'The simple classifier that labels a point by the vote of the closest examples.', a: 'K-nearest neighbours' },
      { q: 'The German orange-armed maker that is one of the big four in factory automation.', a: 'KUKA' },
    ],
    L: [
      { q: 'The model trained on a huge corpus of text to predict the next word, three initials.', a: 'LLM' },
      { q: 'The step size at which a model adjusts its weights during training.', a: 'Learning rate' },
      { q: 'The laser scanner that gives a self-driving car a 3D map of the road.', a: 'Lidar' },
      { q: 'The stack of transformations a network applies one after another.', a: 'Layer' },
      { q: 'The measure of how wrong a prediction was, which training tries to reduce.', a: 'Loss' },
      { q: 'The tag put on training data to say what the right answer is.', a: 'Label' },
      { q: 'The Frenchman whose convolutional networks read bank cheques in the 1990s.', a: 'LeCun' },
      { q: 'The recurrent network type with a memory gate, four initials, that ruled before 2017.', a: 'LSTM' },
      { q: 'The Meta family of open-weight language models named after a pack animal.', a: 'Llama' },
      { q: 'The three rules Asimov invented in 1942 to govern mechanical servants.', a: 'Laws of robotics' },
    ],
    M: [
      { q: 'The field of getting computers to improve at a task from data rather than rules.', a: 'Machine learning' },
      { q: 'The trained mathematical object that makes the predictions.', a: 'Model' },
      { q: 'The electric device that turns current into rotation and drives a joint.', a: 'Motor' },
      { q: 'The doubling of transistor count every two years, named after an Intel founder.', a: 'Moore law' },
      { q: 'The company behind the Llama models and the Quest headset.', a: 'Meta' },
      { q: 'The mechanical hand or foot that touches the world.', a: 'Manipulator' },
      { q: 'The engineering of moving parts, gears and linkages.', a: 'Mechanics' },
      { q: 'The MIT co-founder whose 1969 book stalled neural nets for a decade.', a: 'Minsky' },
      { q: 'The device that turns sound into a signal a voice assistant can read.', a: 'Microphone' },
      { q: 'The full-body suit of markers used to record a human action for a machine to copy.', a: 'Motion capture' },
      { q: 'The Discord-based picture generator launched in 2022.', a: 'Midjourney' },
    ],
    N: [
      { q: 'The web of weighted connections loosely modelled on the brain.', a: 'Neural network' },
      { q: 'The teaching of a computer to read and write human speech, three initials.', a: 'NLP' },
      { q: 'The random unwanted variation in a signal or a dataset.', a: 'Noise' },
      { q: 'The chip company whose H100 became the currency of the AI boom.', a: 'Nvidia' },
      { q: 'The single unit of a network that sums its inputs and fires.', a: 'Node' },
      { q: 'The mathematical function, such as ReLU, that decides whether a unit fires.', a: 'Nonlinearity' },
      { q: 'The elementary unit of a network, modelled on a brain cell.', a: 'Neuron' },
    ],
    O: [
      { q: 'The San Francisco lab that released ChatGPT in November 2022.', a: 'OpenAI' },
      { q: 'The answer a model gives.', a: 'Output' },
      { q: 'The failure in which a model learns the training set by heart and fails on new data.', a: 'Overfitting' },
      { q: 'The formal map of concepts and their relations used in symbolic systems.', a: 'Ontology' },
      { q: 'The process of searching for the best values, whether of weights or of a design.', a: 'Optimisation' },
      { q: 'The light-based sensor that reads a printed page into text.', a: 'Optical scanner' },
      { q: 'The publishing of trained parameters for anyone to download and run.', a: 'Open weights' },
    ],
    P: [
      { q: 'The instruction you type to get an answer from a language model.', a: 'Prompt' },
      { q: 'The adjustable number inside a model, counted in the billions.', a: 'Parameter' },
      { q: 'The teaching of a machine to spot a regular shape in data.', a: 'Pattern recognition' },
      { q: 'The industrial controller, three initials, that runs most factory machinery.', a: 'PLC' },
      { q: 'The mechanical device driven by air or oil pressure to push a limb.', a: 'Piston' },
      { q: 'The knowing of where a robot is, from wheel counts and landmarks.', a: 'Positioning' },
      { q: 'The cutting away of unneeded weights to make a model smaller and faster.', a: 'Pruning' },
      { q: 'The working out of a route across a room that avoids all the furniture.', a: 'Path planning' },
      { q: 'The stage in which a big model is first trained on raw text, before any tuning.', a: 'Pre-training' },
      { q: 'The white waist-high SoftBank greeter machine with a tablet on its chest.', a: 'Pepper' },
      { q: 'The one-unit classifier Rosenblatt built in 1958 out of a room of wires.', a: 'Perceptron' },
      { q: 'The craft of wording a request to get the best out of a model.', a: 'Prompt engineering' },
    ],
    Q: [
      { q: 'The reduction of a model numbers to fewer bits so it fits on a phone.', a: 'Quantisation' },
      { q: 'The kind of machine that computes with superposed states instead of bits.', a: 'Quantum computing' },
      { q: 'The reinforcement method that scores every action in every state.', a: 'Q-learning' },
    ],
    R: [
      { q: 'The mechanical worker whose name comes from a 1920 Czech play.', a: 'Robot' },
      { q: 'The training approach that gives a reward and lets the machine work out how to earn it.', a: 'Reinforcement learning' },
      { q: 'The architecture with loops, which carries information from one step to the next.', a: 'Recurrent network' },
      { q: 'The engineering and science of building mechanical workers.', a: 'Robotics' },
      { q: 'The technique of looking facts up in a document store before answering, three initials.', a: 'RAG' },
      { q: 'The signal that tells a learning agent it did the right thing.', a: 'Reward' },
      { q: 'The commonest activation function in modern networks, four letters.', a: 'ReLU' },
      { q: 'The 1920 Karel Capek play whose initials name its artificial workers.', a: 'RUR' },
      { q: 'The teaching of a model from human preference rankings, five initials.', a: 'RLHF' },
      { q: 'The operating system, three initials, on which most research platforms run.', a: 'ROS' },
      { q: 'The vacuum-cleaning machine that maps a room and bumps its way round.', a: 'Roomba' },
      { q: 'The connection that lets one link spin about an axis relative to the next.', a: 'Rotary joint' },
    ],
    S: [
      { q: 'The device that senses light, heat, pressure or distance for a machine.', a: 'Sensor' },
      { q: 'The motor with built-in position feedback used in every hobby robot.', a: 'Servo' },
      { q: 'The programs that run on the hardware.', a: 'Software' },
      { q: 'The setting in which every training example comes with the right answer attached.', a: 'Supervised learning' },
      { q: 'The mapping and locating a robot does at once as it explores, five initials.', a: 'SLAM' },
      { q: 'The Boston Dynamics four-legged machine that patrols building sites.', a: 'Spot' },
      { q: 'The Hanson Robotics android granted Saudi citizenship in 2017.', a: 'Sophia' },
      { q: 'The making of an artificial voice out of written text.', a: 'Speech synthesis' },
      { q: 'The open-weight image generator released by Stability AI in August 2022.', a: 'Stable Diffusion' },
      { q: 'The American philosopher whose Chinese Room argument denies machines understand.', a: 'Searle' },
      { q: 'The rise of machine intelligence beyond human level, sometimes called this event.', a: 'Singularity' },
      { q: 'The mathematical function that squashes any number into the range nought to one.', a: 'Sigmoid' },
      { q: 'The simulated world in which a robot is trained before it touches reality.', a: 'Simulation' },
    ],
    T: [
      { q: 'The 1950 test of machine intelligence by conversation, named after its proposer.', a: 'Turing test' },
      { q: 'The 2017 network architecture whose attention mechanism made modern chatbots possible.', a: 'Transformer' },
      { q: 'The teaching phase in which a model learns from data.', a: 'Training' },
      { q: 'The reuse of a model trained on one task as a head start on another.', a: 'Transfer learning' },
      { q: 'The Google chip built only for tensor maths, three initials.', a: 'TPU' },
      { q: 'The word for a piece of a word, the unit a language model actually reads.', a: 'Token' },
      { q: 'The company whose Autopilot brought driver assistance to the mass market.', a: 'Tesla' },
      { q: 'The Google library, open-sourced in 2015, for building neural networks.', a: 'TensorFlow' },
      { q: 'The multi-dimensional array of numbers that all this maths runs on.', a: 'Tensor' },
      { q: 'The setting that controls how random a language model answers.', a: 'Temperature' },
      { q: 'The 1984 film in which a defence network decides to wipe out humanity.', a: 'Terminator' },
    ],
    U: [
      { q: 'The setting with no labels at all, in which the model finds its own structure.', a: 'Unsupervised learning' },
      { q: 'The uncrewed aerial vehicle, three initials, that the public calls a drone.', a: 'UAV' },
      { q: 'The eerie feeling given by a face that is almost but not quite human.', a: 'Uncanny valley' },
      { q: 'The sound-pulse device that lets a robot measure the distance to a wall.', a: 'Ultrasonic sensor' },
    ],
    V: [
      { q: 'The turning of spoken words into text, by which a phone obeys orders.', a: 'Voice recognition' },
      { q: 'The camera-and-software sense that lets a machine read the world.', a: 'Vision' },
      { q: 'The computer-made world you enter through a headset, two initials.', a: 'VR' },
      { q: 'The list of numbers that stands for a word or an image inside a model.', a: 'Vector' },
      { q: 'The German firm whose Golf line pioneered welding automation in Europe.', a: 'Volkswagen' },
    ],
    W: [
      { q: 'The number on each connection of a network, adjusted during training.', a: 'Weight' },
      { q: 'The Alphabet company running driverless taxi services in American cities.', a: 'Waymo' },
      { q: 'The IBM system that won at Jeopardy in 2011.', a: 'Watson' },
      { q: 'The American who founded cybernetics and wrote the 1948 book of that name.', a: 'Wiener' },
      { q: 'The rolling base on which a warehouse machine carries a shelf about.', a: 'Wheeled platform' },
      { q: 'The HBO series about a theme park of artificial people who begin to remember.', a: 'Westworld' },
    ],
    X: [
      { q: 'The explainable kind of artificial intelligence, whose reasoning can be inspected.', a: 'XAI' },
      { q: 'The Microsoft games console whose Kinect camera gave cheap 3D vision to researchers.', a: 'Xbox' },
    ],
    Y: [
      { q: 'The Canadian deep learning pioneer, a Turing Award winner with Hinton and LeCun.', a: 'Yoshua Bengio' },
      { q: 'The real-time object detector whose name is an acronym for looking only once.', a: 'YOLO' },
    ],
    Z: [
      { q: 'The asking of a model to do a task it has seen no examples of at all.', a: 'Zero-shot' },
      { q: 'The German who built the first programmable computer, the Z3, in 1941.', a: 'Zuse' },
      { q: 'The setting of all weights to nought before training starts.', a: 'Zero initialisation' },
    ],
  },
};
