import type { RawPack } from '../core/packs';

export const royalsPack: RawPack = {
  id: 'royals',
  name: 'Royals and Dynasties',
  description: 'Kings, queens, pharaohs and emperors, plus the palaces, crowns and houses behind them.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '👑',
  accent: '#7e22ce',
  letters: {
    A: [
      { q: 'Egyptian pharaoh who moved worship to the sun disc Aten and built a new capital at Amarna.', a: 'Akhenaten' },
      { q: 'Second wife of Henry the Eighth and mother of Elizabeth the First.', a: 'Anne Boleyn', alt: ['Boleyn'] },
      { q: 'Macedonian king who conquered the Persian empire and reached the Indus.', a: 'Alexander the Great' },
      { q: 'King of Wessex who held off the Vikings and was later called England\'s only monarch styled Great.', a: 'Alfred' },
      { q: 'First Roman emperor, born with the name Octavian.', a: 'Augustus' },
      { q: 'Red-walled palace fortress built by the Nasrid rulers above Granada.', a: 'Alhambra' },
      { q: 'Sixth Mughal emperor, a son of Shah Jahan who expanded the empire southwards.', a: 'Aurangzeb' },
      { q: 'Third Mughal emperor, remembered for his religious tolerance and his court at Fatehpur Sikri.', a: 'Akbar' },
      { q: 'Formal act by which a monarch gives up the throne.', a: 'Abdication' },
      { q: 'Mauryan emperor who turned to Buddhism after the bloody Kalinga campaign.', a: 'Ashoka' },
      { q: 'Youngest daughter of Nicholas the Second, the subject of many false survival claims.', a: 'Anastasia' },
      { q: 'The last Stuart ruler of Great Britain, whose reign began in 1702.', a: 'Anne' },
      { q: 'The fourth wife of Henry the Eighth, set aside after only six months in 1540.', a: 'Anne of Cleves' },
      { q: 'German city where Charlemagne kept his court and where he was buried.', a: 'Aachen' },
    ],
    B: [
      { q: 'French royal house of Louis the Fourteenth and Louis the Sixteenth.', a: 'Bourbon' },
      { q: 'London home of the British sovereign since 1837.', a: 'Buckingham Palace' },
      { q: 'Queen of the Iceni who led a revolt against Roman rule in Britain.', a: 'Boudica', alt: ['Boadicea'] },
      { q: 'Scottish highland estate bought by Victoria and Albert in 1852.', a: 'Balmoral' },
      { q: 'Paris fortress prison stormed by a crowd in July 1789.', a: 'Bastille' },
      { q: 'Adjective for the eastern Roman empire ruled from Constantinople.', a: 'Byzantine' },
      { q: 'Thai king whose seventy-year reign ended in 2016.', a: 'Bhumibol' },
      { q: 'Portuguese royal house that took the throne in 1640 and later ruled Brazil.', a: 'Braganza' },
      { q: 'Nickname earned by the Tudor queen who tried to restore Catholicism by force.', a: 'Bloody Mary' },
      { q: 'Popular name for the Yeomen Warders who guard the Tower of London.', a: 'Beefeaters' },
      { q: 'Gulf island kingdom ruled by the Al Khalifa family.', a: 'Bahrain' },
      { q: 'Himalayan kingdom whose monarch is titled the Dragon King.', a: 'Bhutan' },
    ],
    C: [
      { q: 'Ceremony at which a sovereign is formally crowned.', a: 'Coronation' },
      { q: 'Frankish ruler crowned Emperor of the Romans on Christmas Day in the year 800.', a: 'Charlemagne' },
      { q: 'Last active ruler of Ptolemaic Egypt, allied with Caesar and Mark Antony.', a: 'Cleopatra' },
      { q: 'Empress who greatly expanded Russia during the second half of the 1700s.', a: 'Catherine the Great' },
      { q: 'English king beheaded outside Whitehall in 1649 after losing a civil war.', a: 'Charles the First', alt: ['Charles I'] },
      { q: 'Founder of the Achaemenid Persian empire, praised for freeing the Babylonian exiles.', a: 'Cyrus the Great' },
      { q: 'Roman emperor who legalised Christianity and founded a new capital on the Bosphorus.', a: 'Constantine' },
      { q: 'French dynasty founded by Hugh, who was elected king in 987.', a: 'Capet' },
      { q: 'Poetic name for the imperial seat of Japan.', a: 'Chrysanthemum Throne' },
      { q: 'The Merry Monarch, restored to the English throne in 1660.', a: 'Charles the Second', alt: ['Charles II'] },
      { q: 'Collective name for the regalia kept under guard in the Tower of London.', a: 'Crown Jewels' },
      { q: 'Title given to the successor of Muhammad as leader of the Muslim community.', a: 'Caliph' },
      { q: 'Danish ruler who became king of England in 1016 and later of Norway too.', a: 'Cnut', alt: ['Canute'] },
    ],
    D: [
      { q: 'Traditional title of the heir to the French throne.', a: 'Dauphin' },
      { q: 'Plain jewelled band worn in antiquity as a mark of royal rank.', a: 'Diadem' },
      { q: 'A run of rulers drawn from the same family.', a: 'Dynasty' },
      { q: 'Persian king who built Persepolis and whose army lost at Marathon.', a: 'Darius' },
      { q: 'Territory ruled by a duke.', a: 'Duchy' },
      { q: 'Israelite king who followed Saul and made Jerusalem his capital.', a: 'David' },
      { q: 'Title given to the widow of a king or emperor.', a: 'Dowager' },
      { q: 'Doctrine that a sovereign\'s authority comes straight from God and not from the people.', a: 'Divine right' },
      { q: 'Roman emperor who split rule of the empire between four men around 293.', a: 'Diocletian' },
      { q: 'Scandinavian kingdom often called the oldest continuous monarchy in Europe.', a: 'Denmark' },
    ],
    E: [
      { q: 'Tudor queen nicknamed the Virgin Queen, whose fleet met the Armada.', a: 'Elizabeth the First', alt: ['Elizabeth I'] },
      { q: 'Vast palace and monastery near Madrid built for Philip the Second.', a: 'El Escorial', alt: ['Escorial'] },
      { q: 'Pious English king who founded Westminster Abbey and died in 1066.', a: 'Edward the Confessor' },
      { q: 'Title of a ruling prince in the Arab world, used across the Gulf states.', a: 'Emir' },
      { q: 'Female counterpart of an emperor.', a: 'Empress' },
      { q: 'British king who gave up the throne in 1936 to marry Wallis Simpson.', a: 'Edward the Eighth', alt: ['Edward VIII'] },
      { q: 'White winter fur traditionally used to trim robes of state.', a: 'Ermine' },
      { q: 'British monarch whose reign ran from 1952 until 2022.', a: 'Elizabeth the Second', alt: ['Elizabeth II'] },
      { q: 'Queen of France and then of England, and mother of Richard the Lionheart.', a: 'Eleanor of Aquitaine' },
      { q: 'Long-legged English king nicknamed Longshanks who subdued Wales.', a: 'Edward the First', alt: ['Edward I'] },
    ],
    F: [
      { q: 'Aragonese king whose marriage to Isabella of Castile united Spain.', a: 'Ferdinand' },
      { q: 'Habsburg emperor who ruled Austria and Hungary from 1848 until 1916.', a: 'Franz Joseph' },
      { q: 'Prussian king and keen flute player who fought the Seven Years War.', a: 'Frederick the Great' },
      { q: 'French royal chateau where Napoleon signed his first abdication in 1814.', a: 'Fontainebleau' },
      { q: 'Walled Beijing palace complex used by Ming and Qing rulers.', a: 'Forbidden City' },
      { q: 'Stylised lily emblem long used by the kings of France.', a: 'Fleur-de-lis' },
      { q: 'First king of Iraq, installed by the British in 1921.', a: 'Faisal' },
      { q: 'Shia dynasty that founded Cairo in 969 and ruled North Africa.', a: 'Fatimid' },
      { q: 'Last reigning king of Egypt, deposed by officers in 1952.', a: 'Farouk' },
    ],
    G: [
      { q: 'British king who lost the American colonies and suffered long bouts of illness.', a: 'George the Third', alt: ['George III'] },
      { q: 'Bladed device used to execute Louis the Sixteenth in 1793.', a: 'Guillotine' },
      { q: 'Warrior proclaimed ruler of all the Mongols in 1206.', a: 'Genghis Khan' },
      { q: 'Rank above a prince but below a king, still held in Luxembourg.', a: 'Grand Duke' },
      { q: 'Swedish warrior king killed at the battle of Lutzen in 1632.', a: 'Gustavus Adolphus' },
      { q: 'The nearly bloodless 1688 change of monarch in England.', a: 'Glorious Revolution' },
      { q: 'The Mongol khanate that dominated the Russian principalities for centuries.', a: 'Golden Horde' },
      { q: 'British monarch who reigned through the Second World War and had a stammer.', a: 'George the Sixth', alt: ['George VI'] },
      { q: 'Last king of Nepal, whose throne was abolished in 2008.', a: 'Gyanendra' },
    ],
    H: [
      { q: 'Dynasty that ruled Austria and Spain and was known for a distinctive jaw.', a: 'Habsburg' },
      { q: 'Tudor king who took six wives and broke with Rome.', a: 'Henry the Eighth', alt: ['Henry VIII'] },
      { q: 'Riverside Tudor palace handed to the crown by Cardinal Wolsey.', a: 'Hampton Court' },
      { q: 'Female pharaoh who ruled as king and built a terraced temple at Deir el-Bahari.', a: 'Hatshepsut' },
      { q: 'Japanese emperor on the throne throughout the Second World War.', a: 'Hirohito' },
      { q: 'Last emperor of Ethiopia, deposed in 1974.', a: 'Haile Selassie' },
      { q: 'German house that supplied Britain with four kings called George.', a: 'Hanover' },
      { q: 'Jordanian king who reigned from 1952 until 1999.', a: 'Hussein' },
      { q: 'Client king of Judea who rebuilt the Temple in Jerusalem.', a: 'Herod' },
      { q: 'Central European realm of electors and emperors that was dissolved in 1806.', a: 'Holy Roman Empire' },
      { q: 'Dynasty that ruled Prussia and then the German empire until 1918.', a: 'Hohenzollern' },
    ],
    I: [
      { q: 'Queen of Castile who paid for the voyages of Columbus.', a: 'Isabella' },
      { q: 'First Russian ruler to be crowned tsar, notorious for his cruelty.', a: 'Ivan the Terrible' },
      { q: 'Adjective describing anything belonging to an emperor.', a: 'Imperial' },
      { q: 'Ancient Lombard regalia said to contain a nail from the Crucifixion.', a: 'Iron Crown' },
      { q: 'Title borne by a daughter of the Spanish sovereign.', a: 'Infanta' },
      { q: 'The gap between the end of one reign and the start of the next.', a: 'Interregnum' },
      { q: 'Warrior who founded the modern Saudi kingdom in 1932.', a: 'Ibn Saud' },
      { q: 'Only king of Libya, overthrown by Gaddafi in 1969.', a: 'Idris' },
      { q: 'Andean empire whose ruler was called the Sapa.', a: 'Inca' },
    ],
    J: [
      { q: 'Scottish king who also inherited the English throne in 1603.', a: 'James the First', alt: ['James I', 'James VI'] },
      { q: 'Byzantine emperor who built Hagia Sophia and had Roman law codified.', a: 'Justinian' },
      { q: 'Spanish king who guided the country back to democracy after Franco.', a: 'Juan Carlos' },
      { q: 'Celebration marking a milestone anniversary of a reign.', a: 'Jubilee' },
      { q: 'First wife of Napoleon, crowned empress alongside him in 1804.', a: 'Josephine' },
      { q: 'Dynasty that ruled Poland and Lithuania from the late 1300s.', a: 'Jagiellon' },
      { q: 'English king who lost Normandy and sealed a famous charter at Runnymede.', a: 'John' },
      { q: 'Arab kingdom on the east bank of its namesake river, ruled by the Hashemites.', a: 'Jordan' },
    ],
    K: [
      { q: 'Pharaoh whose tomb is the Great Pyramid at Giza.', a: 'Khufu', alt: ['Cheops'] },
      { q: 'Walled Moscow fortress that was the seat of the tsars.', a: 'Kremlin' },
      { q: 'German word for emperor, taken from the name Caesar.', a: 'Kaiser' },
      { q: 'Nickname given to the Earl of Warwick for putting rival English kings on the throne.', a: 'Kingmaker' },
      { q: 'Title borne by Mongol and Turkic rulers of the steppe.', a: 'Khan' },
      { q: 'Mongol ruler who founded the Yuan dynasty in China and hosted Marco Polo.', a: 'Kublai Khan' },
      { q: 'Bronze Age palace on Crete linked with the legendary King Minos.', a: 'Knossos' },
      { q: 'Ruler who unified the Hawaiian islands under one crown around 1810.', a: 'Kamehameha' },
    ],
    L: [
      { q: 'The Sun King, whose seventy-two-year reign was the longest in European history.', a: 'Louis the Fourteenth', alt: ['Louis XIV'] },
      { q: 'Former Paris royal palace that is now the world\'s most visited museum.', a: 'Louvre' },
      { q: 'French king executed by the revolutionaries in January 1793.', a: 'Louis the Sixteenth', alt: ['Louis XVI'] },
      { q: 'Nickname of Richard the First of England, famed for his crusading courage.', a: 'Lionheart' },
      { q: 'Teenage claimant proclaimed queen of England for nine days in 1553.', a: 'Lady Jane Grey' },
      { q: 'Feudal term for the lord to whom a vassal owed allegiance.', a: 'Liege' },
      { q: 'Belgian king who ran the Congo as a personal possession.', a: 'Leopold the Second', alt: ['Leopold II'] },
      { q: 'The red rose house in the fifteenth-century English dynastic wars.', a: 'Lancaster' },
      { q: 'Spartan king who died holding the pass at Thermopylae.', a: 'Leonidas' },
    ],
    M: [
      { q: 'Austrian-born French queen executed in 1793 and wrongly quoted about cake.', a: 'Marie Antoinette' },
      { q: 'Catholic cousin of Elizabeth the First, beheaded at Fotheringhay in 1587.', a: 'Mary Queen of Scots' },
      { q: 'Chinese dynasty of 1368 to 1644, famous for blue and white porcelain.', a: 'Ming' },
      { q: 'Muslim dynasty that ruled much of India and built the Taj Mahal.', a: 'Mughal' },
      { q: 'Aztec ruler who received Cortes in his capital in 1519.', a: 'Montezuma', alt: ['Moctezuma'] },
      { q: 'System of government in which a hereditary sovereign reigns.', a: 'Monarchy' },
      { q: 'Japanese emperor whose restoration in 1868 opened the country to industry.', a: 'Meiji' },
      { q: 'Grand free-standing tomb built to hold a ruler\'s remains.', a: 'Mausoleum' },
      { q: 'Charter of 1215 that placed limits on the power of King John.', a: 'Magna Carta' },
      { q: 'Habsburg ruler of Austria who bore sixteen children, including a French queen.', a: 'Maria Theresa' },
      { q: 'North African kingdom ruled by the Alaouite family since the 1600s.', a: 'Morocco' },
    ],
    N: [
      { q: 'Corsican general who crowned himself emperor of the French in 1804.', a: 'Napoleon' },
      { q: 'Last Russian tsar, who gave up the throne in 1917.', a: 'Nicholas the Second', alt: ['Nicholas II'] },
      { q: 'Egyptian queen known worldwide from a painted limestone bust found at Amarna.', a: 'Nefertiti' },
      { q: 'The house of William the Conqueror and his sons.', a: 'Norman' },
      { q: 'Roman emperor blamed for a great fire in the year 64.', a: 'Nero' },
      { q: 'Babylonian king who destroyed the first Temple in Jerusalem.', a: 'Nebuchadnezzar' },
      { q: 'Title borne by the ruler of the princely state of Hyderabad.', a: 'Nizam' },
    ],
    O: [
      { q: 'Golden globe topped with a cross that a sovereign holds at a crowning.', a: 'Orb' },
      { q: 'Turkish empire ruled by sultans from about 1299 until 1922.', a: 'Ottoman' },
      { q: 'Warrior chief around 1300 whose descendants ruled Turkey for six centuries.', a: 'Osman' },
      { q: 'German king crowned Holy Roman Emperor in 962.', a: 'Otto the Great' },
      { q: 'The Dutch royal house, whose name is also worn as a colour by its supporters.', a: 'Orange' },
      { q: 'Lord Protector who governed England without a crown in the 1650s.', a: 'Oliver Cromwell', alt: ['Cromwell'] },
    ],
    P: [
      { q: 'Title of the rulers of ancient Egypt.', a: 'Pharaoh' },
      { q: 'Tsar who founded a new capital on the Baltic marshes in 1703.', a: 'Peter the Great' },
      { q: 'Title held by the future George the Fourth while his father was too ill to rule.', a: 'Prince Regent' },
      { q: 'Rule by which the eldest child inherits ahead of the others.', a: 'Primogeniture' },
      { q: 'Jewelled seat commissioned by Shah Jahan and later carried off to Persia.', a: 'Peacock Throne' },
      { q: 'English royal house that ran from Henry the Second to Richard the Third.', a: 'Plantagenet' },
      { q: 'Spanish king who sent the Armada against England in 1588.', a: 'Philip the Second', alt: ['Philip II'] },
      { q: 'Hilltop palace in Lhasa that was the winter seat of the Dalai Lamas.', a: 'Potala' },
      { q: 'Macedonian general who founded the last dynasty to rule ancient Egypt.', a: 'Ptolemy' },
      { q: 'Someone who claims a throne that others say is not theirs.', a: 'Pretender' },
    ],
    Q: [
      { q: 'Last imperial dynasty of China, founded by the Manchus.', a: 'Qing' },
      { q: 'Title of the wife of a reigning king.', a: 'Queen consort' },
      { q: 'Title of a widowed royal wife whose child now sits on the throne.', a: 'Queen mother' },
      { q: 'Gulf peninsula state ruled by the Al Thani family.', a: 'Qatar' },
    ],
    R: [
      { q: 'Russian dynasty that ruled for three centuries until 1917.', a: 'Romanov' },
      { q: 'Collective word for the crown, orb and sceptre of a monarchy.', a: 'Regalia' },
      { q: 'Last Plantagenet king of England, killed at Bosworth Field in 1485.', a: 'Richard the Third', alt: ['Richard III'] },
      { q: 'Person who rules in place of a sovereign who is a child or absent.', a: 'Regent' },
      { q: 'Long-reigning pharaoh who built the rock temples at Abu Simbel.', a: 'Rameses the Second', alt: ['Ramses II'] },
      { q: 'Name given to the return of the English monarchy in 1660.', a: 'Restoration' },
      { q: 'Legendary Norse chief said to have founded the first Russian ruling line.', a: 'Rurik' },
      { q: 'Indian title for a king or a princely ruler.', a: 'Rajah' },
    ],
    S: [
      { q: 'Title borne by the ruler of the Turkish empire in Istanbul.', a: 'Sultan' },
      { q: 'Ornamented rod carried by a sovereign as a sign of authority.', a: 'Sceptre' },
      { q: 'Ottoman ruler from 1520 whose armies besieged Vienna in 1529.', a: 'Suleiman the Magnificent', alt: ['Suleiman'] },
      { q: 'Royal house of James the First and Charles the Second.', a: 'Stuart' },
      { q: 'Mughal emperor who raised a marble tomb for his wife Mumtaz Mahal.', a: 'Shah Jahan' },
      { q: 'The fixed order in which people inherit a throne.', a: 'Succession' },
      { q: 'Old Frankish rule that barred women from inheriting the French crown.', a: 'Salic law' },
      { q: 'Yellow Vienna palace used as a summer home by the Habsburgs.', a: 'Schonbrunn' },
      { q: 'Potsdam summer palace built for Frederick the Great, its name meaning without care.', a: 'Sanssouci' },
      { q: 'Israelite king famed for his wisdom and for building the first Temple.', a: 'Solomon' },
      { q: 'Ruler who forged the Zulu kingdom in the early 1800s.', a: 'Shaka' },
      { q: 'Korean king who sponsored the creation of the Hangul alphabet.', a: 'Sejong' },
    ],
    T: [
      { q: 'English royal house that ruled from 1485 until 1603.', a: 'Tudor' },
      { q: 'Boy pharaoh whose intact tomb was opened by Howard Carter in 1922.', a: 'Tutankhamun' },
      { q: 'Ceremonial chair on which a sovereign sits.', a: 'Throne' },
      { q: 'Russian imperial title taken from the name Caesar.', a: 'Tsar', alt: ['Czar'] },
      { q: 'Marble mausoleum at Agra built for a Mughal emperor\'s favourite wife.', a: 'Taj Mahal' },
      { q: 'Jewelled half-circle headpiece worn by royal women at formal events.', a: 'Tiara' },
      { q: 'Riverside fortress where two young princes vanished in 1483.', a: 'Tower of London' },
      { q: 'Sprawling Istanbul palace that housed the Ottoman court for four centuries.', a: 'Topkapi' },
      { q: 'Turco-Mongol conqueror of the late 1300s who founded the Timurid line.', a: 'Tamerlane', alt: ['Timur'] },
    ],
    U: [
      { q: 'First great caliphal dynasty, ruling the Muslim world from Damascus.', a: 'Umayyad' },
      { q: 'Person who seizes a throne without a rightful claim.', a: 'Usurper' },
      { q: 'Name for the 1603 joining of the Scottish and English monarchies under one man.', a: 'Union of the Crowns' },
      { q: 'Last king of Italy, who reigned for barely a month in 1946.', a: 'Umberto' },
    ],
    V: [
      { q: 'Palace to which Louis the Fourteenth moved his whole court in 1682.', a: 'Versailles' },
      { q: 'British queen whose reign ran from 1837 to 1901 and gave an age its name.', a: 'Victoria' },
      { q: 'Official who governs a colony or province in the sovereign\'s name.', a: 'Viceroy' },
      { q: 'French dynasty that held the throne from 1328 until 1589.', a: 'Valois' },
      { q: 'Swedish dynasty whose namesake warship sank on its maiden voyage in 1628.', a: 'Vasa' },
    ],
    W: [
      { q: 'Name adopted by the British royal house in 1917 to sound less German.', a: 'Windsor' },
      { q: 'Duke of Normandy who took the English crown after Hastings in 1066.', a: 'William the Conqueror' },
      { q: 'Fifteenth-century English struggle between the houses of Lancaster and York.', a: 'Wars of the Roses' },
      { q: 'London church where English sovereigns have been crowned since 1066.', a: 'Westminster Abbey' },
      { q: 'Last German emperor, who fled to the Netherlands in 1918.', a: 'Wilhelm the Second', alt: ['Wilhelm II', 'Kaiser Wilhelm'] },
      { q: 'Saint Petersburg residence of the Russian emperors, stormed in 1917.', a: 'Winter Palace' },
      { q: 'Bohemian duke remembered in a Christmas carol about deep snow.', a: 'Wenceslas' },
    ],
    X: [
      { q: 'Persian king who invaded Greece in 480 BC and lost his fleet at Salamis.', a: 'Xerxes' },
      { q: 'Semi-legendary first dynasty of China, said to precede the Shang.', a: 'Xia' },
    ],
    Y: [
      { q: 'Mongol-founded dynasty that ruled China from 1271 until 1368.', a: 'Yuan' },
      { q: 'The white rose house in the fifteenth-century English dynastic wars.', a: 'York' },
      { q: 'Ming emperor who moved the Chinese capital to Beijing and built its walled palace.', a: 'Yongle' },
    ],
    Z: [
      { q: 'Queen of Palmyra who defied Rome in the third century.', a: 'Zenobia' },
      { q: 'The only man ever to reign as king of Albania.', a: 'Zog' },
    ],
  },
};
