import type { RawQuestion } from '../core/packs';

export const saudiExtra2: Record<string, RawQuestion[]> = {
  A: [
    { q: 'The founding king\'s personal name, after whom the capital\'s main international airport is named.', a: 'Abdulaziz', category: 'gcc', difficulty: 3, alt: ['Abdul Aziz', 'Abdulaziz Al Saud'] },
    { q: 'The king who ruled from 2005 to 2015 and founded a major graduate science university by the Red Sea.', a: 'Abdullah', category: 'gcc', difficulty: 4, alt: ['King Abdullah'] },
    { q: 'The continent on which the kingdom lies, joined to Africa at the Sinai land bridge.', a: 'Asia', category: 'gcc', difficulty: 2 },
    { q: 'The official language of the kingdom, the tongue in which the Quran was revealed.', a: 'Arabic', category: 'gcc', difficulty: 2 },
    { q: 'The vast entertainment and sports city rising on the capital\'s south-western edge, planned around theme parks and a racetrack.', a: 'Al Qiddiya', category: 'gcc', difficulty: 5, alt: ['Qiddiya'] },
    { q: 'The lively folk sword dance performed in lines by men to drumming and chanted poetry on national occasions.', a: 'Ardah', category: 'gcc', difficulty: 4, alt: ['Ardha', 'Saudi Ardah'] },
    { q: 'The black cord ring worn over the headscarf to hold it in place, part of Saudi men\'s traditional dress.', a: 'Agal', category: 'gcc', difficulty: 5, alt: ['Igal', 'Egal'] },
    { q: 'The Jeddah football club, one of the oldest and most decorated in the kingdom, nicknamed the Pride of the Pitch.', a: 'Al-Ahli', category: 'gcc', difficulty: 5, alt: ['Ahli'] },
    { q: 'The single name by which Muslims refer to the one God they worship.', a: 'Allah', category: 'gcc', difficulty: 2 },
    { q: 'The critically endangered spotted big cat of the kingdom\'s mountains, the focus of a high-profile NEOM conservation programme.', a: 'Arabian leopard', category: 'gcc', difficulty: 4 },
    { q: 'The northern province around Sakaka and Dumat al-Jandal, an ancient oasis region near the Jordanian border.', a: 'Al-Jawf', category: 'gcc', difficulty: 5, alt: ['Al Jawf', 'Jawf'] },
    { q: 'The Riyadh football club founded in 1947, one of the capital\'s big three alongside the blue and yellow giants.', a: 'Al-Shabab', category: 'gcc', difficulty: 5, alt: ['Shabab'] },
    { q: 'The call to prayer broadcast from minarets, summoning Muslims to worship five times a day.', a: 'Azan', category: 'gcc', difficulty: 3, alt: ['Adhaan'] },
    { q: 'The pen-shaped capital skyscraper topped with a giant golden glass globe, one of Riyadh\'s landmark towers.', a: 'Al Faisaliah', category: 'gcc', difficulty: 5, alt: ['Al Faisaliyah Tower'] },
  ],
  B: [
    { q: 'The major Islamic battle of 624 CE near Medina in which the early Muslims won their first decisive victory.', a: 'Battle of Badr', category: 'gcc', difficulty: 5, alt: ['Badr'] },
    { q: 'The 627 CE defence of Medina by the Muslims, named for the defensive ditch dug around the city.', a: 'Battle of the Trench', category: 'gcc', difficulty: 5, alt: ['Battle of Khandaq', 'Battle of Khandak'] },
    { q: 'The central Qassim city, the province\'s capital and a famous date-market town.', a: 'Buraidah', category: 'gcc', difficulty: 5, alt: ['Buraydah'] },
    { q: 'The lush green south-western province of mountains and valleys between Asir and the lowlands, by its name.', a: 'Al-Bahah', category: 'gcc', difficulty: 5, alt: ['Al Baha', 'Baha'] },
    { q: 'The sacred dark stone set in a corner of the Kaaba that pilgrims try to touch or salute during the circling.', a: 'Black Stone', category: 'gcc', difficulty: 4, alt: ['Hajar al-Aswad'] },
  ],
  C: [
    { q: 'The form of government of the kingdom, an absolute one ruled by a single royal head of state.', a: 'Monarchy', category: 'gcc', difficulty: 3, alt: ['Absolute monarchy'] },
    { q: 'The kingdom\'s supreme executive body, chaired by the king, whose members each head a department of state.', a: 'Council of Ministers', category: 'gcc', difficulty: 4, alt: ['Cabinet'] },
    { q: 'The footballer who joined a capital club in 2023 in one of football\'s biggest transfers, a Portuguese superstar.', a: 'Cristiano Ronaldo', category: 'gcc', difficulty: 3, alt: ['Ronaldo'] },
    { q: 'The title of the heir to the throne, the king\'s designated successor.', a: 'Crown Prince', category: 'gcc', difficulty: 3 },
  ],
  D: [
    { q: 'The white ankle-length men\'s robe worn daily across the kingdom, the everyday national garment.', a: 'Dishdasha', category: 'gcc', difficulty: 3, alt: ['Thawb'] },
    { q: 'The oldest centre of higher learning in the kingdom, founded in the capital in 1957 and named after the founding monarch.', a: 'King Saud University', category: 'gcc', difficulty: 5, alt: ['KSU'] },
    { q: 'The heritage giga-project restoring the historic mud-brick birthplace of the Saudi state on the capital\'s edge.', a: 'Diriyah Gate', category: 'gcc', difficulty: 5 },
    { q: 'The pre-Islamic age of ignorance, the term for Arabian society before the Prophet\'s message.', a: 'Jahiliyyah', category: 'gcc', difficulty: 5, alt: ['Jahiliyya'] },
    { q: 'The ancient northern Al-Jawf town with a famous early mosque attributed to a caliph and a great mud fortress.', a: 'Dumat al-Jandal', category: 'gcc', difficulty: 5 },
    { q: 'The act of inviting others to Islam, the missionary outreach the kingdom has long funded worldwide.', a: 'Dawah', category: 'gcc', difficulty: 5, alt: ["Da'wah"] },
  ],
  E: [
    { q: 'The trade ban Arab oil states led against Western nations in 1973, which sent crude prices soaring.', a: 'Oil embargo', category: 'gcc', difficulty: 4, alt: ['1973 oil embargo'] },
    { q: 'The title of the rulers of the early Saudi realms before the modern kingdom was proclaimed.', a: 'Emir', category: 'gcc', difficulty: 4, alt: ['Amir'] },
    { q: 'The dramatic desert cliff north-west of the capital where the Tuwaiq escarpment drops away to a vast plain, a hiking landmark.', a: 'Edge of the World', category: 'gcc', difficulty: 4, alt: ['Jebel Fihrayn'] },
  ],
  F: [
    { q: 'The king assassinated in 1975 who abolished slavery and led the kingdom during the 1973 oil crisis.', a: 'Faisal', category: 'gcc', difficulty: 4, alt: ['King Faisal'] },
    { q: 'The traditional Najdi dish of shredded bread soaked in meat broth, eaten from a shared platter.', a: 'Fattah', category: 'gcc', difficulty: 5, alt: ['Fatteh'] },
    { q: 'The Islamic legal ruling issued by a qualified scholar in answer to a religious question.', a: 'Fatwa', category: 'gcc', difficulty: 3 },
    { q: 'The fourth pillar of Islam, abstaining from food and drink during daylight through the holy month.', a: 'Fasting', category: 'gcc', difficulty: 3, alt: ['Sawm'] },
    { q: 'The most popular spectator sport in the kingdom, whose Pro League draws huge crowds.', a: 'Football', category: 'gcc', difficulty: 2, alt: ['Soccer'] },
    { q: 'The coral archipelago in the southern Red Sea off Jazan, a protected reserve for dugongs and migratory birds.', a: 'Farasan Islands', category: 'gcc', difficulty: 5, alt: ['Farasan'] },
    { q: 'The 1727 realm centred on Diriyah, the original dynastic polity later destroyed by an Ottoman-Egyptian army, by its ordinal name.', a: 'First Saudi State', category: 'gcc', difficulty: 5, alt: ['Emirate of Diriyah'] },
  ],
  G: [
    { q: 'The arm of the sea forming the kingdom\'s eastern coastline, shared with Bahrain, Qatar and Kuwait.', a: 'Gulf', category: 'gcc', difficulty: 2, alt: ['Persian Gulf', 'Arabian Gulf'] },
    { q: 'The collective nickname for the cluster of vast flagship developments, from the linear city to Qiddiya, driving the kingdom\'s diversification.', a: 'Giga-projects', category: 'gcc', difficulty: 4, alt: ['Gigaprojects'] },
    { q: 'The Eastern Province field that is the largest conventional crude oil field on Earth.', a: 'Ghawar', category: 'gcc', difficulty: 5 },
    { q: 'The kingdom\'s highest religious authority, the chief cleric who heads the council of senior scholars.', a: 'Grand Mufti', category: 'gcc', difficulty: 5 },
    { q: 'The nickname of the national football team, evoking the bird of prey and the team kit colour.', a: 'Green Falcons', category: 'gcc', difficulty: 4 },
  ],
  H: [
    { q: 'The ancient caravan city in the north-west with rock-cut Nabataean tombs, the kingdom\'s first UNESCO World Heritage Site.', a: 'Hegra', category: 'gcc', difficulty: 5, alt: ['Madain Salih', "Mada'in Salih"] },
    { q: 'The slow-cooked porridge of wheat pounded with meat, a beloved dish during the fasting month.', a: 'Harees', category: 'gcc', difficulty: 4, alt: ['Jareesh'] },
    { q: 'The migration of the Prophet from Mecca to Medina in 622 CE that marks year one of the Islamic calendar.', a: 'Hijra', category: 'gcc', difficulty: 5, alt: ['Hegira'] },
    { q: 'The mountain cave outside Mecca where, according to Islamic tradition, the Prophet first received revelation.', a: 'Hira', category: 'gcc', difficulty: 5, alt: ['Cave of Hira', 'Ghar Hira'] },
    { q: 'The vast black volcanic lava fields that scatter across the kingdom\'s western and central plateau, by their Arabic name.', a: 'Harrat', category: 'gcc', difficulty: 5, alt: ['Harrah', 'Lava fields'] },
    { q: 'The fast electric rail line opened in 2018 whisking pilgrims between the two holy cities by way of Jeddah, by its English name.', a: 'Haramain High Speed Railway', category: 'gcc', difficulty: 5, alt: ['Haramain railway'] },
    { q: 'The eastern oasis city in the Al-Ahsa region, a major palm-grove and date-producing centre.', a: 'Hofuf', category: 'gcc', difficulty: 5, alt: ['Al-Hofuf'] },
    { q: 'The deeply held desert value of welcoming and generously feeding any guest, central to Saudi culture.', a: 'Hospitality', category: 'gcc', difficulty: 3 },
    { q: 'The modest head covering worn by Muslim women, also the general term for veiling in public.', a: 'Hijab', category: 'gcc', difficulty: 3 },
    { q: 'The reported sayings and deeds of the Prophet, a primary source of Islamic teaching alongside the Quran.', a: 'Hadith', category: 'gcc', difficulty: 4, alt: ['Ahadith'] },
  ],
  I: [
    { q: 'The prayer leader who stands at the front of the mosque and guides the congregation in worship.', a: 'Imam', category: 'gcc', difficulty: 3 },
    { q: 'The branch of Islam followed by the great majority of Saudis, the larger of the faith\'s two main divisions.', a: 'Sunni Islam', category: 'gcc', difficulty: 4, alt: ['Sunni'] },
    { q: 'The 2019 stock-market flotation of the national oil giant, at the time the largest ever held.', a: 'Initial public offering', category: 'gcc', difficulty: 5, alt: ['IPO'] },
    { q: 'The second call announced just before a congregation rises to begin the formal prayer.', a: 'Iqama', category: 'gcc', difficulty: 5, alt: ['Iqamah'] },
  ],
  J: [
    { q: 'The huge Gulf-coast industrial city north of Dammam, one of the world\'s largest petrochemical and refining hubs.', a: 'Jubail', category: 'gcc', difficulty: 5, alt: ['Al Jubail'] },
    { q: 'The highest mountain in the kingdom, a roughly 3,000-metre peak in the Asir highlands near Abha.', a: 'Jabal Sawda', category: 'gcc', difficulty: 5, alt: ['Jabal al-Soudah', 'Soudah'] },
  ],
  K: [
    { q: 'The graduate research university founded in 2009 on the Red Sea coast north of Jeddah, named for a late monarch, by its initials.', a: 'KAUST', category: 'gcc', difficulty: 5, alt: ['King Abdullah University of Science and Technology'] },
    { q: 'The white knitted skullcap worn under the headscarf by men across the kingdom.', a: 'Kufi', category: 'gcc', difficulty: 5, alt: ['Taqiyah'] },
    { q: 'The title of the male royal head of state who reigns over the kingdom and serves as its prime minister.', a: 'King', category: 'gcc', difficulty: 2 },
    { q: 'The Asir highland city beside Abha that forms the region\'s commercial twin, home to a major air base.', a: 'Khamis Mushait', category: 'gcc', difficulty: 5 },
    { q: 'The monarch who reigned 1982 to 2005 and built much of the modern kingdom\'s infrastructure, lending his name to a causeway and an airport.', a: 'King Fahd', category: 'gcc', difficulty: 4, alt: ['Fahd'] },
    { q: 'The monarch who came to the throne in 2015, father of the reform-driving crown prince.', a: 'King Salman', category: 'gcc', difficulty: 3, alt: ['Salman'] },
    { q: 'The monarch who reigned from 1975 to 1982, succeeding his assassinated half-brother, who lends his name to a Riyadh airport.', a: 'King Khalid', category: 'gcc', difficulty: 5, alt: ['Khalid'] },
  ],
  L: [
    { q: 'The planned 170-kilometre mirror-clad linear city, the flagship piece of the north-western megaproject.', a: 'The Line', category: 'gcc', difficulty: 4 },
    { q: 'The common nickname for the kingdom as guardian of the two holiest places of Islam.', a: 'Land of the Two Holy Mosques', category: 'gcc', difficulty: 4 },
  ],
  M: [
    { q: 'The valley town near Mecca where pilgrims camp in tents and perform the stoning rite during the pilgrimage.', a: 'Mina', category: 'gcc', difficulty: 4 },
    { q: 'The reception room where Saudi families traditionally receive guests, also a word for a consultative council.', a: 'Majlis', category: 'gcc', difficulty: 4 },
    { q: 'The open plain near Mecca where pilgrims gather overnight to collect pebbles after the standing rite.', a: 'Muzdalifah', category: 'gcc', difficulty: 5 },
    { q: 'The 18th-century preacher whose alliance with the first Saudi emir founded the religious movement behind the state, by his full name.', a: 'Muhammad ibn Abd al-Wahhab', category: 'gcc', difficulty: 5, alt: ['Ibn Abd al-Wahhab'] },
    { q: 'The man who chants the call to prayer from the mosque five times daily.', a: 'Muezzin', category: 'gcc', difficulty: 4, alt: ['Muadhin'] },
    { q: 'The hill on the outskirts of Medina where a major 625 CE battle was fought, also the name of that battle.', a: 'Mount Uhud', category: 'gcc', difficulty: 5, alt: ['Uhud', 'Battle of Uhud'] },
    { q: 'The historic Medina mosque where the prayer direction was switched mid-worship from Jerusalem to Mecca, by its English name.', a: 'Mosque of the Two Qiblas', category: 'gcc', difficulty: 5, alt: ['Masjid al-Qiblatayn', 'Qiblatain Mosque'] },
    { q: 'The lightly spiced rice steamed with meat in a pit, a Hadhrami-origin dish hugely popular across the kingdom.', a: 'Mandi', category: 'gcc', difficulty: 4 },
    { q: 'The flat-roofed clay or stone prayer house found in every Saudi town and village.', a: 'Mosque', category: 'gcc', difficulty: 2 },
    { q: 'The emir of Diriyah who founded the first Saudi state in 1727, ancestor of the ruling dynasty, by his full name.', a: 'Muhammad bin Saud', category: 'gcc', difficulty: 5 },
    { q: 'The state mining company developing the kingdom\'s gold, phosphate and aluminium, a Vision 2030 industrial pillar.', a: 'Maaden', category: 'gcc', difficulty: 5, alt: ['Saudi Arabian Mining Company'] },
    { q: 'The niche or alcove in a mosque wall that marks the direction of prayer toward Mecca.', a: 'Mihrab', category: 'gcc', difficulty: 5 },
    { q: 'The raised pulpit from which the imam delivers the Friday sermon in a mosque.', a: 'Minbar', category: 'gcc', difficulty: 5, alt: ['Mimbar'] },
  ],
  N: [
    { q: 'The ancient Arab people who carved the elaborate rock tombs at the kingdom\'s famous northern heritage site.', a: 'Nabataeans', category: 'gcc', difficulty: 5, alt: ['Nabateans'] },
    { q: 'The southern province and its highland capital near the Yemeni border, known for its mud high-rise towers.', a: 'Najran', category: 'gcc', difficulty: 5 },
    { q: 'The central-heartland dialect of the national tongue, spoken around the capital and the Najd region.', a: 'Najdi Arabic', category: 'gcc', difficulty: 5, alt: ['Najdi'] },
    { q: 'The kingdom\'s northernmost province bordering Iraq, the least populated, by its English region name.', a: 'Northern Borders', category: 'gcc', difficulty: 5, alt: ['Northern Borders Province', 'Al-Hudud ash-Shamaliyah'] },
  ],
  O: [
    { q: 'The proposed floating industrial port and manufacturing hub of the north-western megaproject, named for its eight-sided shape.', a: 'Oxagon', category: 'gcc', difficulty: 5 },
  ],
  P: [
    { q: 'The form of religious worship performed five times daily, one of the pillars of the faith.', a: 'Prayer', category: 'gcc', difficulty: 2, alt: ['Salah'] },
    { q: 'The English word for a member of the ruling family, of whom there are thousands in the kingdom.', a: 'Prince', category: 'gcc', difficulty: 3 },
    { q: 'The sovereign wealth body behind the kingdom\'s giga-projects and global investments, by its three initials.', a: 'PIF', category: 'gcc', difficulty: 4, alt: ['Public Investment Fund'] },
    { q: 'A person undertaking the holy journey to Mecca, of whom millions arrive each year.', a: 'Pilgrim', category: 'gcc', difficulty: 2 },
  ],
  Q: [
    { q: 'The direction Muslims turn toward in prayer, oriented to the holy sanctuary in Mecca.', a: 'Qibla', category: 'gcc', difficulty: 3 },
    { q: 'The central agricultural province around Buraidah, the kingdom\'s breadbasket and a famous date-growing region.', a: 'Qassim', category: 'gcc', difficulty: 5, alt: ['Al-Qassim'] },
    { q: 'The leading tribe of Mecca to which the Prophet Muhammad belonged.', a: 'Quraysh', category: 'gcc', difficulty: 4, alt: ['Quraish'] },
  ],
  R: [
    { q: 'The hilly south-western highland village whose terraced stone houses and watchtowers form a heritage museum.', a: 'Rijal Almaa', category: 'gcc', difficulty: 5, alt: ['Rijal Alma'] },
    { q: 'The forested escarpment reserve in the Asir highlands near Abha, prized for its cool air and juniper woodland.', a: 'Raydah', category: 'gcc', difficulty: 5, alt: ['Raydah Reserve'] },
    { q: 'The Eastern Province cape and town home to one of the world\'s largest oil refineries and an early Aramco terminal.', a: 'Ras Tanura', category: 'gcc', difficulty: 5 },
    { q: 'The huge state-backed developer building new residential communities across the kingdom under Vision 2030.', a: 'Roshn', category: 'gcc', difficulty: 5 },
    { q: 'The revered green-carpeted area inside the Prophet\'s Mosque in Medina, between his tomb and pulpit, that worshippers crowd to pray in.', a: 'Rawdah', category: 'gcc', difficulty: 5, alt: ['Riyadh al-Jannah'] },
  ],
  S: [
    { q: 'The kingdom\'s flag carrier and national airline, based in Jeddah.', a: 'Saudia', category: 'gcc', difficulty: 3, alt: ['Saudi Arabian Airlines'] },
    { q: 'The kingdom\'s top-flight football competition, home to clubs like Al-Hilal and Al-Nassr.', a: 'Saudi Pro League', category: 'gcc', difficulty: 3, alt: ['SPL', 'Roshn Saudi League'] },
    { q: 'The brisk walk pilgrims make seven times between the hills of Safa and Marwa, a rite of the pilgrimage.', a: 'Saee', category: 'gcc', difficulty: 5, alt: ["Sa'i", 'Say'] },
    { q: 'The ancient seasonal poetry and trade fair of pre-Islamic Arabia, held near Taif.', a: 'Souk Okaz', category: 'gcc', difficulty: 5, alt: ['Ukaz', 'Souk Ukaz'] },
    { q: 'The petrochemical manufacturing company, among the world\'s largest, founded by the kingdom in 1976, by its initials.', a: 'SABIC', category: 'gcc', difficulty: 5 },
    { q: 'The northern Al-Jawf province city of palm groves and the ancient Za\'abal castle, by its name.', a: 'Sakaka', category: 'gcc', difficulty: 5 },
    { q: 'The collective name for the companions of the Prophet Muhammad, the earliest generation of Muslims.', a: 'Sahaba', category: 'gcc', difficulty: 5, alt: ['Sahabah', 'Companions'] },
    { q: 'The traditional Bedouin geometric weaving of bright wool used for tents, cushions and rugs, recognised by UNESCO.', a: 'Sadu', category: 'gcc', difficulty: 5, alt: ['Al-Sadu', 'Sadu weaving'] },
    { q: 'The example and practice of the Prophet Muhammad that Muslims seek to follow alongside the Quran.', a: 'Sunnah', category: 'gcc', difficulty: 4, alt: ['Sunna'] },
    { q: 'The kingdom\'s largest telecommunications operator, a former state monopoly, by its three-letter brand.', a: 'STC', category: 'gcc', difficulty: 5, alt: ['Saudi Telecom Company'] },
    { q: 'The body that advises the king and reviews laws, the kingdom\'s appointed consultative assembly.', a: 'Shura Council', category: 'gcc', difficulty: 4, alt: ['Shura', 'Majlis al-Shura'] },
    { q: 'The 19th-century realm centred on Riyadh that followed the fall of the Diriyah emirate, by its ordinal name.', a: 'Second Saudi State', category: 'gcc', difficulty: 5, alt: ['Emirate of Nejd'] },
    { q: 'The kingdom\'s green flag bears the Islamic declaration of faith above this horizontal weapon, a symbol of justice.', a: 'Sword', category: 'gcc', difficulty: 3 },
    { q: 'The Islamic declaration of faith proclaiming one God and Muhammad as His messenger, the first pillar.', a: 'Shahada', category: 'gcc', difficulty: 4, alt: ['Shahadah'] },
    { q: 'The grand restored 19th-century mud-brick royal seat at the heart of historic Diriyah, by its palace name.', a: 'Salwa Palace', category: 'gcc', difficulty: 5, alt: ['At-Turaif Palace'] },
  ],
  T: [
    { q: 'The white ankle-length robe worn by Saudi men, the everyday national dress.', a: 'Thobe', category: 'gcc', difficulty: 2, alt: ['Thawb'] },
    { q: 'The narrow Red Sea coastal plain running along the kingdom\'s south-west, separating the highlands from the sea.', a: 'Tihama', category: 'gcc', difficulty: 5, alt: ['Tihamah'] },
    { q: 'The north-western city and province near Jordan, an oasis on the ancient incense and pilgrimage routes.', a: 'Tabuk', category: 'gcc', difficulty: 4 },
    { q: 'The thick chewy round flatbread baked against the wall of a clay oven, sold hot across the kingdom.', a: 'Tameez', category: 'gcc', difficulty: 5, alt: ['Tamees', 'Afghani bread'] },
    { q: 'The kingdom\'s stock exchange, the largest bourse in the Arab world, based in the capital.', a: 'Tadawul', category: 'gcc', difficulty: 5, alt: ['Saudi Exchange'] },
    { q: 'The mountain ski and outdoor resort planned in NEOM\'s highlands, set to host the 2029 Asian Winter Games.', a: 'Trojena', category: 'gcc', difficulty: 5 },
    { q: 'The special voluntary night prayers Muslims perform in congregation throughout the holy fasting month.', a: 'Tarawih', category: 'gcc', difficulty: 5, alt: ['Taraweeh'] },
    { q: 'The Islamic doctrine of the absolute oneness of God, the central tenet of the faith.', a: 'Tawhid', category: 'gcc', difficulty: 5, alt: ['Tawheed', 'Monotheism'] },
    { q: 'The ancient inhabited island off the Eastern Province coast near Qatif, site of a Bronze Age fortress and tell.', a: 'Tarout', category: 'gcc', difficulty: 5, alt: ['Tarout Island'] },
  ],
  U: [
    { q: 'The 1932 act of merging the Najd and Hejaz realms into one kingdom under the founding monarch.', a: 'Unification', category: 'gcc', difficulty: 3 },
    { q: 'The collective term for the kingdom\'s body of Islamic religious scholars and clerics.', a: 'Ulema', category: 'gcc', difficulty: 5, alt: ['Ulama'] },
    { q: 'The early caliph and companion of the Prophet who greatly expanded the Muslim state and whose name many Saudi men bear.', a: 'Umar', category: 'gcc', difficulty: 4, alt: ['Omar', 'Umar ibn al-Khattab'] },
  ],
  W: [
    { q: 'The dry desert valley or riverbed that fills with water only after rare rains.', a: 'Wadi', category: 'gcc', difficulty: 3 },
    { q: 'The long valley running through the capital, a green riverbed park beside the historic seat of the ruling family.', a: 'Wadi Hanifa', category: 'gcc', difficulty: 5 },
  ],
  Y: [
    { q: 'The Red Sea industrial port city and oil-export terminal in the west, a western pipeline terminus.', a: 'Yanbu', category: 'gcc', difficulty: 4, alt: ["Yanbu' al Bahr"] },
  ],
  Z: [
    { q: 'The branch of Islam, a minority in the kingdom, concentrated in parts of the Eastern Province.', a: 'Shia Islam', category: 'gcc', difficulty: 4, alt: ['Shia', 'Shiite'] },
  ],
};
