import type { RawPack } from '../core/packs';

export const sitcomsEasyPack: RawPack = {
  id: 'sitcoms-easy',
  name: 'Sitcoms Easy',
  description: 'Classic and mainstream sitcoms everyone knows.',
  locale: 'en',
  difficulty: 'easy',
  contentRating: 'everyone',
  emoji: '📺',
  accent: '#f59e0b',
  letters: {
    A: [
      { q: 'Surname of Jennifer who played Rachel Green on the 1994 NBC hangout ensemble.', a: 'Aniston' },
      { q: 'First name of the youngest Banks daughter on the 1990 NBC Bel-Air comedy starring Will Smith.', a: 'Ashley' },
      { q: 'The lovable little brother on the 1970s NBC comedy with Gary Coleman known for "Whatchu talkin\' bout, Willis?".', a: 'Arnold Jackson' },
      { q: 'Actress who played the deadpan, dry-witted assistant to Ron Swanson on the Indiana-set NBC government comedy.', a: 'Aubrey Plaza' },
      { q: 'Short for Alien Life Form — the fuzzy puppet who crash-landed with the Tanner household on a late-80s NBC show.', a: 'ALF' },
      { q: 'Actress who played the relentlessly upbeat deputy parks director Leslie Knope on the Indiana-set NBC government comedy.', a: 'Amy Poehler' },
      { q: 'First name of Carrie\'s loud, hot-tempered father played by Jerry Stiller on the 1998 CBS Kevin James deliveryman comedy.', a: 'Arthur' },
      { q: 'Norman Lear\'s 1971 CBS hit set in Queens with patriarch Archie Bunker and his liberal son-in-law Meathead — its title.', a: 'All in the Family' },
      { q: 'Full first and last name of the well-meaning a-cappella-loving paper salesman from Cornell on the Scranton mockumentary, played by Ed Helms.', a: 'Andy Bernard' },
      { q: 'Leslie Knope\'s sensible best friend who works at the health clinic in the Indiana-set NBC government comedy — her full name.', a: 'Ann Perkins' },
      { q: 'Surname of the cynical, deadpan intern-turned-assistant played by Aubrey Plaza on the NBC Indiana-set government comedy.', a: 'April Ludgate' },
      { q: 'Carroll O\'Connor\'s opinionated working-class Queens patriarch on the 1971 CBS Norman Lear hit — full first and last name.', a: 'Archie Bunker' },
    ],
    B: [
      { q: 'Surname of Mike, Carol, Greg and Marcia on the 1969 ABC blended-household comedy with six kids.', a: 'Brady' },
      { q: 'Surname of the patriarch Archie on the 1971 CBS Norman Lear hit set in Queens.', a: 'Bunker' },
      { q: 'Surname of Chandler on the 1994 NBC hangout ensemble.', a: 'Bing' },
      { q: 'Catchphrase shouted by Sheldon Cooper after a successful joke on the CBS Pasadena physicists hit.', a: 'Bazinga' },
      { q: 'The cheerful, naive Mediterranean cousin of Larry Appleton on the late-80s ABC immigrant-themed comedy "Perfect Strangers".', a: 'Balki Bartokomous' },
      { q: 'Last name of the Long Island newspaper writer Ray on the 1996 CBS Ray Romano hit.', a: 'Barone' },
      { q: 'The deadpan paper-company receptionist Pam\'s maiden surname on the Scranton mockumentary, before she married Jim Halpert.', a: 'Beesly' },
      { q: 'The 1965 ABC suburban-magic comedy about a witch named Samantha married to a mortal ad executive Darrin — its one-word title.', a: 'Bewitched' },
      { q: 'The fictional Pacific Palisades secondary school where Zack Morris and his friends ruled the hallways on the 1989 NBC teen-comedy.', a: 'Bayside High' },
      { q: 'The 1993 ABC teen comedy about Cory Matthews growing up in suburban Philadelphia — its three-word title.', a: 'Boy Meets World' },
      { q: 'Actress who played Dorothy Zbornak, the tall sarcastic divorcée on the 1985 NBC Miami-set senior-citizen comedy "The Golden Girls".', a: 'Bea Arthur' },
      { q: 'Howard Wolowitz\'s pharma-microbiologist wife played by Melissa Rauch on the CBS Pasadena physicists comedy — full first and last name.', a: 'Bernadette Rostenkowski' },
    ],
    C: [
      { q: 'The Manhattan coffeehouse where the six twenty-somethings on the 1994 NBC hangout ensemble met every day.', a: 'Central Perk' },
      { q: 'The Boston neighborhood bar at the heart of the 1982 NBC ensemble where Norm and Cliff drank — the show\'s one-word title.', a: 'Cheers' },
      { q: 'First name of Joey\'s sarcastic, banter-loving roommate on the 1994 NBC hangout ensemble who later married Monica.', a: 'Chandler' },
      { q: 'Surname of Frasier and his fastidious psychiatrist brother Niles on the Seattle-set NBC spin-off.', a: 'Crane' },
      { q: 'Surname of the neurotic bald loser George on the 1990s NBC New York ensemble — his parents are Frank and Estelle.', a: 'Costanza' },
      { q: 'The mailman who held court at the end of the Boston bar on the 1982 NBC ensemble — his last name.', a: 'Clavin' },
      { q: 'The smooth-talking, pampered preppy cousin of Will on the 1990 NBC Bel-Air comedy — his full first and last name.', a: 'Carlton Banks' },
      { q: 'Full name of the hedonistic bachelor jingle-writer brother played by Sheen on the 2003 CBS Malibu beach-house sitcom.', a: 'Charlie Harper' },
      { q: 'First name of the eccentric, hair-sproinging neighbor who slides into Jerry\'s apartment without knocking on the 1990s NBC ensemble.', a: 'Cosmo' },
      { q: 'The 1984 NBC family hit centered on the Huxtable household in Brooklyn — its title (drop the leading "The").', a: 'Cosby Show' },
      { q: 'Ben Savage\'s character on the 1993 ABC Philadelphia teen comedy where he grew up alongside best friend Shawn and girlfriend Topanga — full first and last name.', a: 'Cory Matthews' },
      { q: 'Surname of Candace, the actress who played D.J. on the late-80s ABC San Francisco family comedy raising three girls.', a: 'Cameron' },
    ],
    D: [
      { q: 'First name of Bob Saget\'s widowed sportscaster character on the late-80s ABC San Francisco family comedy raising three little girls.', a: 'Danny Tanner' },
      { q: 'The Scranton-based paper company at the center of the Steve Carell NBC mockumentary.', a: 'Dunder Mifflin' },
      { q: 'First name of Mr. Schrute, the beet-farming assistant-to-the-regional-manager on the Scranton paper-company show.', a: 'Dwight' },
      { q: 'The 1978 NBC comedy about two adopted Black boys taken in by a rich white Manhattan father — starring Gary Coleman.', a: 'Diff\'rent Strokes' },
      { q: 'Eldest daughter played by Candace Cameron on the late-80s ABC San Francisco family comedy — initials and surname.', a: 'D.J. Tanner' },
      { q: 'Neil Patrick Harris\'s breakthrough role: a teenage prodigy doctor on the 1989 ABC sitcom — character\'s full name.', a: 'Doogie Howser' },
      { q: 'Kevin James\'s parcel-delivery character on the 1998 CBS Queens-set hit — his full first and last name.', a: 'Doug Heffernan' },
      { q: 'Actor who played the paleontologist Ross on the 1994 NBC hangout ensemble.', a: 'David Schwimmer' },
      { q: 'First name and surname of Ray\'s long-suffering wife on the 1996 CBS Long Island family hit.', a: 'Debra Barone' },
      { q: 'Full name of the mortal advertising-executive husband of the 1960s ABC suburban witch Samantha.', a: 'Darrin Stephens' },
      { q: 'The English physical therapist who marries Niles on the 1993 NBC Seattle psychiatrist spin-off — full first and last name.', a: 'Daphne Moon' },
      { q: 'Eric Forman\'s tomboy redheaded girlfriend played by Laura Prepon on the 1998 Fox 1970s-Wisconsin nostalgia comedy — full first and last name.', a: 'Donna Pinciotti' },
    ],
    E: [
      { q: 'Dim-witted oldest son with parents Red and Kitty on the 1998 Fox 1970s-Wisconsin nostalgia comedy — full first and last name.', a: 'Eric Forman' },
      { q: 'Full name of the strong-willed female friend played by Julia Louis-Dreyfus on the 1990s NBC New York comedy.', a: 'Elaine Benes' },
      { q: 'Surname of Marshall and Lily, the long-time couple in the 2005 CBS narrated ensemble about meeting Ted\'s wife.', a: 'Eriksen' },
      { q: 'Actress who played the bubbly receptionist Erin Hannon on the Scranton paper-company mockumentary.', a: 'Ellie Kemper' },
      { q: 'Full name of Archie\'s sweet-natured, "dingbat"-called wife on the 1971 CBS Norman Lear hit in Queens.', a: 'Edith Bunker' },
      { q: 'The brassy, gossipy mother of Samantha on the 1960s ABC suburban-witch comedy — first name.', a: 'Endora' },
      { q: 'George\'s shrill-voiced mother on the 1990s NBC New York comedy — full first and last name.', a: 'Estelle Costanza' },
      { q: 'The 1996 CBS family hit starring stand-up Ray Romano as a Long Island newspaper writer with overbearing parents next door — its full title.', a: 'Everybody Loves Raymond' },
      { q: 'Actor who plays the gruff Jay Pritchett patriarch on the 2009 ABC mockumentary about three connected suburban households.', a: 'Ed O\'Neill' },
      { q: 'Cory\'s charming but slacker older brother on the 1993 ABC Philadelphia teen comedy — full first and last name.', a: 'Eric Matthews' },
      { q: 'Full first and last name of the bubbly receptionist played by Ellie Kemper who replaces Pam at Dunder Mifflin Scranton.', a: 'Erin Hannon' },
      { q: 'Actor (also famous from "The Hangover") who played the well-meaning a-cappella-loving Andy Bernard on the Scranton paper-company mockumentary.', a: 'Ed Helms' },
    ],
    F: [
      { q: 'The 1994 NBC ensemble about six twenty-somethings sharing Manhattan apartments and a coffeehouse — its one-word title.', a: 'Friends' },
      { q: 'The 1993 NBC psychiatrist spin-off set in Seattle starring Kelsey Grammer — its one-word title.', a: 'Frasier' },
      { q: 'The 1989 ABC Chicago sitcom about the Winslow household that became dominated by their nerdy suspender-wearing neighbor Steve Urkel.', a: 'Family Matters' },
      { q: 'The late-80s ABC San Francisco comedy where Danny, Joey and Jesse co-raise three little girls.', a: 'Full House' },
      { q: 'George\'s shouting cigar-chomping father on the 1990s NBC New York comedy — first and last name.', a: 'Frank Costanza' },
      { q: 'The pompous, snivelling major often called "Ferret Face" by Hawkeye on the CBS Korean-War surgery comedy — full first and last name.', a: 'Frank Burns' },
      { q: 'The leather-jacketed cool guy whose real name was Arthur Fonzarelli on the 1974 ABC nostalgia hit set in Milwaukee — his nickname.', a: 'Fonzie' },
      { q: 'The 1990 NBC fish-out-of-water comedy about a West Philadelphia teen sent to live with wealthy California relatives — its first two title words.', a: 'Fresh Prince' },
      { q: 'The 1982 NBC sitcom about ex-hippie liberal parents Steven and Elyse and their young-Republican son Alex P. Keaton played by Michael J. Fox.', a: 'Family Ties' },
      { q: 'The wise-cracking Black housekeeper played by Marla Gibbs on the 1970s CBS spin-off about a successful Manhattan dry-cleaning family — full first and last name.', a: 'Florence Johnston' },
      { q: 'Kelsey Grammer\'s pompous Seattle radio-psychiatrist character — full first and last name.', a: 'Frasier Crane' },
      { q: 'Drescher\'s nasally Queens nanny character on the 1993 CBS sitcom about working for a wealthy Broadway producer — full first and last name.', a: 'Fran Fine' },
    ],
    G: [
      { q: 'Surname of Ross and Monica, the brother and sister on the 1994 NBC Manhattan hangout ensemble.', a: 'Geller' },
      { q: 'Jerry\'s bald, neurotic best friend on the 1990s NBC New York comedy — full first and last name.', a: 'George Costanza' },
      { q: 'Surname of Johnny who played experimental physicist Leonard Hofstadter on the CBS Pasadena comedy.', a: 'Galecki' },
      { q: 'The 1985 ABC suburban-family comedy starring Alan Thicke as a psychiatrist dad and Kirk Cameron as his teenage son Mike Seaver.', a: 'Growing Pains' },
      { q: 'Surname of Kimmy, the annoying neighbor of the Tanners on the late-80s ABC San Francisco family comedy.', a: 'Gibbler' },
      { q: 'The blond Central Perk barista secretly in love with Rachel on the 1994 NBC hangout ensemble — his first name.', a: 'Gunther' },
      { q: 'Surname of Andy, the easygoing sheriff of fictional Mayberry on the 1960s CBS comedy bearing his real name.', a: 'Griffith' },
      { q: 'The eldest son on the 1969 ABC blended-household comedy with six kids — full first and last name.', a: 'Greg Brady' },
      { q: 'The proud, hot-tempered dry-cleaning patriarch played by Sherman Hemsley on the 1975 CBS All-in-the-Family spin-off about a wealthy New York Black family — full name.', a: 'George Jefferson' },
      { q: 'Archie\'s sweet daughter played by Sally Struthers on the 1971 CBS Norman Lear Queens-set hit — full first and last name.', a: 'Gloria Stivic' },
      { q: 'The straight interior-designer best friend of the gay lawyer on the 1998 NBC New York sitcom — full first and last name.', a: 'Grace Adler' },
      { q: 'Sheldon\'s slightly dim older brother on the 2017 CBS prequel sitcom about a young Texas genius — his first name.', a: 'Georgie' },
    ],
    H: [
      { q: 'Surname of the title family on the 1984 NBC Bill Cosby comedy about a Brooklyn obstetrician and his lawyer wife.', a: 'Huxtable' },
      { q: 'The 1974 ABC nostalgia hit set in 1950s Milwaukee featuring Richie Cunningham and the cool Fonz — its two-word title.', a: 'Happy Days' },
      { q: 'Surname of Jim, the prankster paper salesman who marries the receptionist on the Scranton mockumentary.', a: 'Halpert' },
      { q: 'First-name nickname of Captain Pierce, the wisecracking surgeon at the 4077th on the CBS Korean-War hit.', a: 'Hawkeye' },
      { q: 'Surname of the experimental physicist Leonard who shares an apartment with Sheldon on the CBS Pasadena comedy.', a: 'Hofstadter' },
      { q: 'The 1991 ABC sitcom starring Tim Allen as Detroit handyman-turned-TV-host Tim "The Tool Man" Taylor.', a: 'Home Improvement' },
      { q: 'The 2005 CBS sitcom narrated by future-Ted recounting his romantic past to his kids — its five-word title.', a: 'How I Met Your Mother' },
      { q: 'Surname of the stone-faced gay Captain Raymond played by Andre Braugher on the precinct-99 cop comedy.', a: 'Holt' },
      { q: 'Surname of Doug and Carrie, the parcel-driver husband and wife on the 1998 CBS Queens-set hit.', a: 'Heffernan' },
      { q: 'Surname of Lily, the kindergarten teacher who marries Marshall on the 2005 CBS narrated ensemble.', a: 'Hannigan' },
      { q: 'The nerdy aerospace-engineer-and-astronaut friend with the bowl haircut and dickie collars on the CBS Pasadena physicists comedy — full first and last name.', a: 'Howard Wolowitz' },
      { q: 'The matriarch of the Chicago family on the 1989 ABC sitcom dominated by neighbor Steve Urkel — full first and last name.', a: 'Harriette Winslow' },
    ],
    I: [
      { q: 'The 1951 CBS classic comedy starring a Cuban bandleader and his redheaded American wife — its three-word title.', a: 'I Love Lucy' },
      { q: 'The 1965 NBC fantasy comedy about an astronaut Tony Nelson who finds a bottle on a beach containing a beautiful 2,000-year-old genie.', a: 'I Dream of Jeannie' },
      { q: 'The U.S. state where the fictional town of Pawnee\'s Parks Department is located on the NBC Amy Poehler comedy.', a: 'Indiana' },
    ],
    J: [
      { q: 'The stand-up comedian and co-creator who plays a fictionalized version of himself on the 1989 NBC New York comedy — full first and last name.', a: 'Jerry Seinfeld' },
      { q: 'Actress who played Rachel Green on the 1994 NBC hangout ensemble — full first and last name.', a: 'Jennifer Aniston' },
      { q: 'The struggling Italian-American actor roommate on the 1994 NBC hangout ensemble known for "How you doin\'?" — his full name.', a: 'Joey Tribbiani' },
      { q: 'Full first and last name of the prankster paper salesman played by John Krasinski on the Scranton mockumentary.', a: 'Jim Halpert' },
      { q: 'Surname of the family who "moved on up to the East Side" on the 1975 CBS All-in-the-Family spin-off.', a: 'Jefferson' },
      { q: 'Actress who played the strong-willed female friend Elaine Benes on the 1990s NBC New York comedy — three-name credit.', a: 'Julia Louis-Dreyfus' },
      { q: 'Actor who played the bald, neurotic loser George Costanza on the 1990s NBC New York comedy — full first and last name.', a: 'Jason Alexander' },
      { q: 'Actress who played the deadpan receptionist Pam Beesly on the Scranton paper-company mockumentary.', a: 'Jenna Fischer' },
      { q: 'The leather-jacketed musician uncle played by John Stamos on the late-80s ABC San Francisco family comedy — full first and last name.', a: 'Jesse Katsopolis' },
      { q: 'Actor who played the eccentric theoretical physicist Sheldon Cooper on the CBS Pasadena comedy.', a: 'Jim Parsons' },
      { q: 'The pudgy preteen nephew character on the 2003 CBS Charlie Sheen Malibu beach-house comedy — full first and last name.', a: 'Jake Harper' },
      { q: 'Stand-up comedian best friend of Danny who helps raise the three girls on the late-80s ABC San Francisco family comedy — full first and last name.', a: 'Joey Gladstone' },
    ],
    K: [
      { q: 'Surname of the eccentric, hair-sproinging neighbor Cosmo who slides into Jerry\'s apartment without knocking on the 1990s NBC New York comedy.', a: 'Kramer' },
      { q: 'Actress who played the cheerful blonde across-the-hall waitress Penny on the CBS Pasadena physicists comedy — full first and last name.', a: 'Kaley Cuoco' },
      { q: 'The warm-hearted, giggly nurse mom married to grumpy Red on the 1998 Fox Wisconsin-set 1970s nostalgia comedy — full first and last name.', a: 'Kitty Forman' },
      { q: 'The 1998 CBS sitcom about an IPS parcel deliveryman Doug Heffernan and his wife Carrie in Rego Park — its title (drop the leading "The").', a: 'King of Queens' },
      { q: 'Actor who played the pompous psychiatrist Frasier Crane on both the Boston bar comedy and its Seattle spin-off — full first and last name.', a: 'Kelsey Grammer' },
      { q: 'The annoying next-door neighbor and friend of D.J. on the late-80s ABC San Francisco family comedy — full first and last name.', a: 'Kimmy Gibbler' },
      { q: 'Actor who played the Indian astrophysicist Raj Koothrappali on the CBS Pasadena physicists comedy — full first and last name.', a: 'Kunal Nayyar' },
      { q: 'Surname of Leslie, the upbeat deputy director played by Amy Poehler on the NBC Indiana-set government comedy.', a: 'Knope' },
    ],
    L: [
      { q: 'Actress who played the spacey, vegetarian guitarist Phoebe Buffay on the 1994 NBC hangout ensemble — full first and last name.', a: 'Lisa Kudrow' },
      { q: 'Co-creator of the 1989 NBC New York Jerry-as-himself comedy who later played a fictionalized version of himself on an HBO improv-style series.', a: 'Larry David' },
      { q: 'The bespectacled experimental physicist roommate of Sheldon on the CBS Pasadena comedy — full first and last name.', a: 'Leonard Hofstadter' },
      { q: 'The 1976 ABC Happy Days spin-off about two best-friend roommates working at a Milwaukee brewery — its two-name title.', a: 'Laverne & Shirley' },
      { q: 'The lovable mechanic with a made-up immigrant accent played by Andy Kaufman on the 1978 ABC New York cab-company comedy.', a: 'Latka' },
      { q: 'The bumbling redheaded title character of the 1951 CBS comedy with the Cuban bandleader husband — full first and last name.', a: 'Lucy Ricardo' },
      { q: 'The relentlessly upbeat deputy parks director played by Amy Poehler on the NBC Indiana-set government comedy — full first and last name.', a: 'Leslie Knope' },
      { q: 'The kindergarten-teacher wife of Marshall, played by Alyson Hannigan on the 2005 CBS narrated ensemble — her full first and last name.', a: 'Lily Aldrin' },
      { q: 'The yelling, frazzled mother of four troublesome boys on the 2000 Fox sitcom about a gifted middle son — her full first and last name.', a: 'Lois Wilkerson' },
      { q: 'The real name of the redheaded star of the 1951 CBS Cuban-bandleader sitcom — full first and last name.', a: 'Lucille Ball' },
      { q: 'Cousin of Balki, the uptight Wisconsin-born American photographer on the late-80s ABC immigrant fish-out-of-water sitcom — full first and last name.', a: 'Larry Appleton' },
      { q: 'The patient adult son in the 1972 NBC junkyard comedy starring Redd Foxx — full first and last name.', a: 'Lamont Sanford' },
    ],
    M: [
      { q: 'The 2009 ABC mockumentary ensemble about three connected suburban Los Angeles households — its two-word title.', a: 'Modern Family' },
      { q: 'The bossy, type-A chef big sister roommate of Rachel on the 1994 NBC hangout ensemble — full first and last name.', a: 'Monica Geller' },
      { q: 'The 1972 CBS comedy-drama set at a U.S. Army surgical hospital during the Korean War with Hawkeye Pierce — its punctuation-rich title.', a: 'M*A*S*H' },
      { q: 'The 2010 CBS sitcom about an overweight Chicago police officer and his teacher girlfriend who meet at Overeaters Anonymous — its two-name title.', a: 'Mike & Molly' },
      { q: 'The 2000 Fox single-camera comedy about a gifted boy whose narration breaks the fourth wall, with troublesome brothers and parents Hal and Lois.', a: 'Malcolm in the Middle' },
      { q: 'The cringeworthy regional manager played by Steve Carell at Dunder Mifflin Scranton — full first and last name.', a: 'Michael Scott' },
      { q: 'Actor who played the lovable, dim Italian-American Joey Tribbiani on the 1994 NBC hangout ensemble.', a: 'Matt LeBlanc' },
      { q: 'Actor who played the sarcastic banter-loving Chandler Bing on the 1994 NBC hangout ensemble.', a: 'Matthew Perry' },
      { q: 'The single working-career-woman star of the 1970 CBS Minneapolis TV-newsroom sitcom that bore her own real name — three names.', a: 'Mary Tyler Moore' },
      { q: 'The 1987 Fox sitcom about Al Bundy, a misanthropic Chicago shoe salesman, his loud-mouthed wife Peg, and their kids Kelly and Bud — its three-word title.', a: 'Married with Children' },
      { q: 'Ted\'s lawyer best friend played by Jason Segel on the 2005 CBS narrated New York ensemble — full first and last name.', a: 'Marshall Eriksen' },
      { q: 'Archie\'s long-haired liberal son-in-law Mike Stivic\'s contemptuous nickname on the 1971 CBS Norman Lear Queens hit.', a: 'Meathead' },
    ],
    N: [
      { q: 'The city where Jerry Seinfeld\'s 1989 NBC comedy and the 1994 NBC hangout ensemble are both set.', a: 'New York' },
      { q: 'Surname of the heavy-set mailman nemesis of Jerry on the 1990s NBC ensemble whose name Jerry hisses with hatred.', a: 'Newman' },
      { q: 'Frasier\'s younger, fastidious psychiatrist brother on the Seattle-set NBC spin-off — full first and last name.', a: 'Niles Crane' },
      { q: 'The chubby, beer-loving accountant who sits at the end of the bar on the 1982 NBC Boston ensemble — full first and last name.', a: 'Norm Peterson' },
      { q: 'First name of the British butler played by Daniel Davis on the 1993 CBS Fran Drescher sitcom about a Queens nanny working for a wealthy Broadway producer.', a: 'Niles' },
      { q: 'The precinct number used as the title of the Andy Samberg cop comedy set in Brooklyn.', a: 'Nine-Nine' },
      { q: 'Actor who played the suit-loving womanizer Barney Stinson on the 2005 CBS narrated ensemble — three names.', a: 'Neil Patrick Harris' },
    ],
    O: [
      { q: 'The 2005 NBC mockumentary about a Scranton, Pennsylvania paper-company branch — its one-word title (drop the leading "The").', a: 'Office' },
      { q: 'The 1970s ABC adaptation of the Neil Simon play about a meticulous photographer and a slob sportswriter sharing a Manhattan apartment — its two-word title (drop the leading "The").', a: 'Odd Couple' },
      { q: 'The famous twin-sister surname of the actresses who shared the role of Michelle on the late-80s ABC San Francisco family comedy.', a: 'Olsen' },
      { q: 'The slovenly sportswriter character on the 1970 ABC Neil Simon sitcom — full first and last name.', a: 'Oscar Madison' },
      { q: 'The cheerful town drunk who would lock himself into the jail cell on the 1960s CBS Mayberry sheriff comedy — full first and last name.', a: 'Otis Campbell' },
      { q: 'The young blond cousin added to the Brady household in the show\'s final season, often blamed for "jumping the shark" — his first name.', a: 'Oliver' },
    ],
    P: [
      { q: 'The spacey vegetarian guitarist friend played by Lisa Kudrow on the 1994 NBC hangout ensemble — full first and last name.', a: 'Phoebe Buffay' },
      { q: 'The fictional Indiana town where Leslie Knope\'s parks department is set on the NBC Amy Poehler comedy.', a: 'Pawnee' },
      { q: 'The U.S. city where Will Smith\'s character grew up before being sent to Bel-Air on the 1990 NBC comedy.', a: 'Philadelphia' },
      { q: 'The deadpan brunette receptionist played by Jenna Fischer on the Scranton paper-company mockumentary — her full first and maiden last name.', a: 'Pam Beesly' },
      { q: 'Uncle Phil\'s full first and last name — the wealthy Bel-Air judge on the 1990 NBC Will Smith comedy.', a: 'Philip Banks' },
      { q: 'Surname of Captain Hawkeye on the 1972 CBS Korean-War surgical comedy at the 4077th.', a: 'Pierce' },
      { q: 'Surname of Jay, Claire and Mitchell on the 2009 ABC mockumentary about three connected suburban households.', a: 'Pritchett' },
      { q: 'First name of the cheerful blonde across-the-hall waitress played by Kaley Cuoco on the CBS Pasadena physicists comedy.', a: 'Penny' },
      { q: 'Actress who played Debra Barone, Ray\'s long-suffering wife on the 1996 CBS Long Island family hit — full first and last name.', a: 'Patricia Heaton' },
      { q: 'The late-80s ABC immigrant fish-out-of-water sitcom with Cousin Larry Appleton and Balki Bartokomous — its two-word title.', a: 'Perfect Strangers' },
      { q: 'Al\'s big-haired bonbon-eating wife on the 1987 Fox Chicago shoe-salesman sitcom — full first and last name.', a: 'Peg Bundy' },
      { q: 'Deep-voiced actor who played Elaine\'s on-and-off boyfriend David Puddy on the 1990s NBC New York comedy — full first and last name.', a: 'Patrick Warburton' },
    ],
    Q: [
      { q: 'The New York City borough where Doug and Carrie Heffernan live in the 1998 CBS Kevin James deliveryman comedy, and also where Archie Bunker lives.', a: 'Queens' },
    ],
    R: [
      { q: 'Jennifer Aniston\'s ex-runaway-bride coffeehouse-waitress fashion-loving character on the 1994 NBC hangout ensemble — full first and last name.', a: 'Rachel Green' },
      { q: 'Monica\'s paleontologist older brother on the 1994 NBC hangout ensemble — full first and last name.', a: 'Ross Geller' },
      { q: 'The Cuban bandleader husband on the 1951 CBS classic with the redheaded title star — full first and last name.', a: 'Ricky Ricardo' },
      { q: 'Comedian who created and starred as the redheaded blue-collar matriarch on the 1988 ABC family hit set in Lanford, Illinois — full first and last name.', a: 'Roseanne Barr' },
      { q: 'The unflappable, deadpan precinct captain played by Andre Braugher on the precinct-99 cop comedy — full first and last name.', a: 'Raymond Holt' },
      { q: 'Comedian who starred as the long-suffering Long Island newspaper writer and son on the 1996 CBS family hit — full first and last name.', a: 'Ray Romano' },
      { q: 'Eric\'s grumpy ex-Navy father with the catchphrase "Dumbass" on the 1998 Fox 1970s-Wisconsin nostalgia comedy — full first and last name.', a: 'Red Forman' },
      { q: 'The Indian astrophysicist friend played by Kunal Nayyar on the CBS Pasadena physicists comedy — full first and last name.', a: 'Raj Koothrappali' },
      { q: 'Youngest daughter played by Keshia Knight Pulliam on the 1984 NBC Bill Cosby family hit — full first and last name.', a: 'Rudy Huxtable' },
      { q: 'Mary Richards\'s wisecracking Bronx-born best friend and neighbor played by Valerie Harper, who got her own 1974 CBS spin-off — first name.', a: 'Rhoda' },
      { q: 'Kirstie Alley\'s neurotic uptight bar manager who replaced Diane on the 1982 NBC Boston ensemble — full first and last name.', a: 'Rebecca Howe' },
      { q: 'Frasier\'s sharp-tongued radio producer played by Peri Gilpin on the 1993 NBC Seattle spin-off — her first name.', a: 'Roz' },
    ],
    S: [
      { q: 'The 1989 NBC ensemble named after its stand-up star, about a Manhattan comedian and his friends George, Elaine and Cosmo — its one-word title.', a: 'Seinfeld' },
      { q: 'The pedantic theoretical physicist played by Jim Parsons on the CBS Pasadena comedy who says "Bazinga" — full first and last name.', a: 'Sheldon Cooper' },
      { q: 'The 2001 NBC hospital comedy about an intern John "J.D." Dorian and his best friend, surgeon Christopher Turk — its one-word title.', a: 'Scrubs' },
      { q: 'The 1991 ABC family sitcom about a divorced single mom and a widowed dad each with three kids who marry and blend their households — three-word title.', a: 'Step by Step' },
      { q: 'The 1972 NBC comedy starring Redd Foxx as a Watts, Los Angeles junkyard dealer and his adult son Lamont — its three-word title with conjunction.', a: 'Sanford and Son' },
      { q: 'The 1989 NBC teen comedy set at Bayside High School in Pacific Palisades featuring slick blond Zack Morris — its four-word title.', a: 'Saved by the Bell' },
      { q: 'The nerdy, suspender-wearing, accordion-playing neighbor of the Winslow family played by Jaleel White on the 1989 ABC Chicago sitcom — full first and last name.', a: 'Steve Urkel' },
      { q: 'The womanizing former Red Sox relief pitcher who owns the Boston bar on the 1982 NBC ensemble — full first and last name.', a: 'Sam Malone' },
      { q: 'Actor who played the cringeworthy regional manager Michael Scott on the Scranton paper-company mockumentary — full first and last name.', a: 'Steve Carell' },
      { q: 'The blonde suburban witch who wiggles her nose to cast spells on the 1964 ABC suburban-magic comedy — full first and last name.', a: 'Samantha Stephens' },
      { q: 'Middle daughter played by Jodie Sweetin on the late-80s ABC San Francisco family comedy with the catchphrase "How rude!" — full first and last name.', a: 'Stephanie Tanner' },
      { q: 'Cory\'s long-haired troubled best friend on the 1993 ABC Philadelphia teen comedy — full first and last name.', a: 'Shawn Hunter' },
    ],
    T: [
      { q: 'The 1978 ABC comedy about a Manhattan cab company featuring drivers Alex, Louie and Latka — its one-word title.', a: 'Taxi' },
      { q: 'Surname of Joey on the 1994 NBC hangout ensemble.', a: 'Tribbiani' },
      { q: 'Surname of Danny, D.J., Stephanie and Michelle on the late-80s ABC San Francisco family comedy.', a: 'Tanner' },
      { q: 'The architect father narrator played by Josh Radnor on the 2005 CBS sitcom about meeting his wife — full first and last name.', a: 'Ted Mosby' },
      { q: 'Comedian who starred as Detroit handyman-turned-TV-host Tim "The Tool Man" Taylor on the 1991 ABC home-renovation sitcom — full first and last name.', a: 'Tim Allen' },
      { q: 'Actor who played the live-in housekeeper for an advertising executive and her son on the 1984 ABC sitcom "Who\'s the Boss?" — full first and last name.', a: 'Tony Danza' },
      { q: 'Nickname of Dr. Christopher, J.D.\'s surgeon best friend on the 2001 NBC hospital comedy.', a: 'Turk' },
      { q: 'Full first and last name of the accident-prone "Tool Time" host character played by Tim Allen on the 1991 ABC home-renovation sitcom.', a: 'Tim Taylor' },
      { q: 'The 2003 CBS sitcom starring Charlie Sheen and Jon Cryer as mismatched brothers in Malibu raising young Jake — its five-word title.', a: 'Two and a Half Men' },
      { q: 'Cory\'s long-time girlfriend and eventual wife on the 1993 ABC Philadelphia teen comedy — full first and last name.', a: 'Topanga Lawrence' },
      { q: 'Actor who played the sarcastic Eric Forman on the 1998 Fox 1970s-Wisconsin nostalgia comedy — full first and last name.', a: 'Topher Grace' },
      { q: 'Actor who played the womanizing former Red Sox pitcher who owns the Boston bar on the 1982 NBC ensemble — full first and last name.', a: 'Ted Danson' },
    ],
    U: [
      { q: 'Surname of the geeky high-pitched-voiced suspender-wearing neighbor of the Winslow family on the 1989 ABC Chicago sitcom — also says "Did I do that?".', a: 'Urkel' },
      { q: 'The musician played by John Stamos who helps raise his nieces on the late-80s ABC San Francisco family comedy — his on-screen nickname.', a: 'Uncle Jesse' },
      { q: 'Carlton and Hilary\'s father, the wealthy Bel-Air judge on the 1990 NBC Will Smith comedy — what avuncular nickname did Will give him?', a: 'Uncle Phil' },
    ],
    V: [
      { q: 'Aunt Viv\'s full first and last name — the matriarch of the wealthy household on the 1990 NBC Will Smith Bel-Air comedy.', a: 'Vivian Banks' },
      { q: 'John Travolta\'s breakthrough role as the dumb-but-cool leader of the Sweathogs on the 1975 ABC classroom comedy "Welcome Back, Kotter" — full first and last name.', a: 'Vinnie Barbarino' },
    ],
    W: [
      { q: 'The rapper-turned-actor who played a fictionalized version of himself as a West Philadelphia teen sent to live with rich relatives on the 1990 NBC comedy — full first and last name.', a: 'Will Smith' },
      { q: 'Surname of the nerdy aerospace engineer Howard played by Simon Helberg on the CBS Pasadena physicists comedy.', a: 'Wolowitz' },
      { q: 'Surname of the wise neighbor whose face was always partially hidden behind a backyard fence on the 1991 ABC Tim Allen home-renovation sitcom.', a: 'Wilson' },
      { q: 'The 1998 NBC ensemble about a gay lawyer and his straight female interior-designer best friend living in Manhattan — its three-symbol title with an ampersand.', a: 'Will & Grace' },
      { q: 'Surname of the Chicago police family with Carl, Harriette and Laura on the 1989 ABC sitcom that became dominated by their geeky neighbor Steve Urkel.', a: 'Winslow' },
      { q: 'The naive farm-boy bartender from Indiana on the 1982 NBC Boston ensemble — character\'s full first and last name (played by Harrelson).', a: 'Woody Boyd' },
      { q: 'The 1988 ABC nostalgic suburban-1960s sitcom about young Kevin Arnold narrated by his adult self — its title (drop the leading "The").', a: 'Wonder Years' },
      { q: 'Surname of George who played the bar regular Norm Peterson on the 1982 NBC Boston ensemble.', a: 'Wendt' },
    ],
    Y: [
      { q: 'The phrase used to skip over details in Elaine\'s storytelling on the 1990s NBC New York comedy — three-word verbal shorthand.', a: 'Yada yada yada' },
      { q: 'The 2017 CBS spin-off prequel about a boy genius growing up in East Texas, narrated by Jim Parsons — its two-word title.', a: 'Young Sheldon' },
    ],
    Z: [
      { q: 'The slick blond troublemaking lead at Bayside High played by Mark-Paul Gosselaar on the 1989 NBC teen comedy — full first and last name.', a: 'Zack Morris' },
    ],
  },
};
