import type { RawPack } from '../core/packs';

/**
 * "Guess the Song" — real audio clips via the free iTunes Search API (official
 * 30s preview URLs on Apple's preview CDN, hotlinked, nothing stored). Board
 * letters hidden so the clip is the only clue. Generated by scripts/gensongs.mjs.
 */
export const songsPack: RawPack = {
  id: 'songs',
  name: 'Guess the Song',
  description: 'Hear a clip of a famous song and name it. Real audio!',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎧',
  accent: '#db2777',
  hideBoardLetters: true,
  letters: {
    A: [
      { q: 'Name this famous song.', a: "Africa", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/12/e5/ba/12e5ba45-05c1-7060-25a8-c9b718e7f6e8/mzaf_4488601364870711408.plus.aac.p.m4a", category: 'music', alt: ["toto"] },
      { q: 'Name this famous song.', a: "All Star", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/b0/03/ef/b003ef4c-1a22-6b15-e851-fb106ad96a3b/mzaf_3320656447657988367.plus.aac.p.m4a", category: 'music', alt: ["smash mouth"] },
    ],
    B: [
      { q: 'Name this famous song.', a: "Believer", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/c0/3f/36/c03f367a-b66b-fd0a-a54c-30f8250c4410/mzaf_12768434238801682952.plus.aac.p.m4a", category: 'music', alt: ["imagine dragons"] },
      { q: 'Name this famous song.', a: "Bohemian Rhapsody", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/8f/11/52/8f1152a9-fd5f-0021-f546-b97579c22ec3/mzaf_3962258993076347789.plus.aac.p.m4a", category: 'music', alt: ["queen"] },
      { q: 'Name this famous song.', a: "Bad Guy", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/c3/87/1f/c3871f7e-3260-d615-1c66-5fdca2c3a48f/mzaf_10721331211699880949.plus.aac.p.m4a", category: 'music', alt: ["billie eilish"] },
    ],
    C: [
      { q: 'Name this famous song.', a: "Counting Stars", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/b0/db/7f/b0db7fbe-f8ff-1f67-fe72-ca8185ffbca2/mzaf_15298650366584767800.plus.aac.p.m4a", category: 'music', alt: ["onerepublic"] },
      { q: 'Name this famous song.', a: "Creep", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/8d/e0/bb/8de0bb10-0593-83cc-4d2c-4e9f6ea9b575/mzaf_16440589638018943894.plus.aac.p.m4a", category: 'music', alt: ["radiohead"] },
    ],
    D: [
      { q: 'Name this famous song.', a: "Dynamite", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/3b/f2/5c/3bf25cc9-a395-6858-1ef8-5c29956afaf6/mzaf_6007556042949037280.plus.aac.p.m4a", category: 'music', alt: ["bts"] },
      { q: 'Name this famous song.', a: "Dancing Queen", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/1a/47/93/1a4793fc-1586-87bc-00d2-dc4916a61c7c/mzaf_13920610926910283055.plus.aac.p.m4a", category: 'music', alt: ["abba"] },
    ],
    E: [
      { q: 'Name this famous song.', a: "Eye of the Tiger", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/fe/fa/9e/fefa9edd-c023-4d1c-1012-08bfb0ec69e6/mzaf_4651653238471209843.plus.aac.p.m4a", category: 'music', alt: ["survivor"] },
    ],
    F: [
      { q: 'Name this famous song.', a: "Faded", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/f4/32/01/f43201b9-4bba-7654-2e43-d59e2d907e9f/mzaf_2440137894989713967.plus.aac.p.m4a", category: 'music', alt: ["alan walker"] },
      { q: 'Name this famous song.', a: "Firework", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/ab/27/3b/ab273b22-1eb1-dd49-5332-5ef70c35683b/mzaf_4912325324633099647.plus.aac.p.m4a", category: 'music', alt: ["katy perry"] },
    ],
    H: [
      { q: 'Name this famous song.', a: "Hello", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/93/22/22/93222271-8d55-d923-e0ff-b2964a5abefe/mzaf_3513742103157153222.plus.aac.p.m4a", category: 'music', alt: ["adele"] },
      { q: 'Name this famous song.', a: "Happy", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/4c/ba/89/4cba89f1-1a8a-3f33-b3ac-d88bcad8b996/mzaf_17135561476274403451.plus.aac.p.m4a", category: 'music', alt: ["pharrell williams"] },
      { q: 'Name this famous song.', a: "Hey Jude", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/3d/08/f5/3d08f5d7-1e0a-99d9-1085-d50ecc972bb9/mzaf_1689604474306790314.plus.aac.p.m4a", category: 'music', alt: ["the beatles"] },
    ],
    I: [
      { q: 'Name this famous song.', a: "Imagine", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/7d/4e/8c/7d4e8ced-a37b-fab9-c66a-f3b4d6f043cb/mzaf_1566428042492234227.plus.aac.p.m4a", category: 'music', alt: ["john lennon"] },
      { q: 'Name this famous song.', a: "In the End", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/3f/cb/c7/3fcbc7cc-0606-7f6e-7fc3-793318cfd1ed/mzaf_16081918663584534594.plus.aac.p.m4a", category: 'music', alt: ["linkin park"] },
    ],
    J: [
      { q: 'Name this famous song.', a: "Jolene", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/43/ef/95/43ef956b-4a1c-8ab1-a843-4ac691dc45d9/mzaf_17631698820105622615.plus.aac.p.m4a", category: 'music', alt: ["dolly parton"] },
      { q: 'Name this famous song.', a: "Just the Way You Are", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/cb/2f/e8/cb2fe83a-2676-0cb6-0eb9-aeefe1347a8d/mzaf_8776765404617928155.plus.aac.p.m4a", category: 'music', alt: ["bruno mars"] },
    ],
    L: [
      { q: 'Name this famous song.', a: "Levitating", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/59/dc/4d/59dc4dda-93ff-8f1c-c536-f005f6ea6af5/mzaf_3066686759813252385.plus.aac.p.m4a", category: 'music', alt: ["dua lipa"] },
      { q: 'Name this famous song.', a: "Let It Be", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/0f/f7/e1/0ff7e145-6be6-4341-4fa1-32999d20707f/mzaf_15493778815944217662.plus.aac.p.m4a", category: 'music', alt: ["the beatles"] },
      { q: 'Name this famous song.', a: "Lose Yourself", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/62/0a/a5/620aa56f-189e-708a-80f0-cebdada3872e/mzaf_7131619873177773332.plus.aac.p.m4a", category: 'music', alt: ["eminem"] },
    ],
    M: [
      { q: 'Name this famous song.', a: "Mamma Mia", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/b6/11/b6/b611b634-d2ea-3413-19be-b3c19daddfe5/mzaf_11228048896593074702.plus.aac.p.m4a", category: 'music', alt: ["abba"] },
      { q: 'Name this famous song.', a: "My Heart Will Go On", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/ad/10/9c/ad109c62-aa02-8345-bfcc-b50f98345475/mzaf_3279697888712975539.plus.aac.p.m4a", category: 'music', alt: ["celine dion"] },
    ],
    N: [
      { q: 'Name this famous song.', a: "Numb", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/bb/13/76/bb1376a7-4db0-ed68-c1a6-d0278cc4b320/mzaf_17832584344687833283.plus.aac.p.m4a", category: 'music', alt: ["linkin park"] },
      { q: 'Name this famous song.', a: "November Rain", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/3c/eb/6b/3ceb6b17-b62b-9cb9-ee69-6c161aea7506/mzaf_11294109330794350435.plus.aac.p.m4a", category: 'music', alt: ["guns n' roses"] },
    ],
    O: [
      { q: 'Name this famous song.', a: "One Dance", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/a8/bd/68/a8bd68a2-dcd2-9024-3859-3a9fd6d53576/mzaf_16864609147187531487.plus.aac.p.m4a", category: 'music', alt: ["drake"] },
    ],
    P: [
      { q: 'Name this famous song.', a: "Perfect", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/c7/ba/bc/c7babc66-f598-aaa6-bcf6-307281795817/mzaf_16337361235117168274.plus.aac.p.m4a", category: 'music', alt: ["ed sheeran"] },
      { q: 'Name this famous song.', a: "Paranoid", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/87/7e/c4/877ec400-6e44-8bc4-bb22-b88273a3330d/mzaf_15381783367282008011.plus.aac.p.m4a", category: 'music', alt: ["black sabbath"] },
    ],
    R: [
      { q: 'Name this famous song.', a: "Radioactive", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/77/70/88/777088e9-60a1-c459-bfa5-6e66f2fd2695/mzaf_7685408661765681881.plus.aac.p.m4a", category: 'music', alt: ["imagine dragons"] },
      { q: 'Name this famous song.', a: "Rolling in the Deep", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/9f/07/1d/9f071dc7-791c-c869-dfa2-06b25936a287/mzaf_11077490630806345321.plus.aac.p.m4a", category: 'music', alt: ["adele"] },
      { q: 'Name this famous song.', a: "Roar", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/21/a8/76/21a87607-1fe3-2bd2-753c-0b4b73c22b90/mzaf_9666996724668759977.plus.aac.p.m4a", category: 'music', alt: ["katy perry"] },
    ],
    S: [
      { q: 'Name this famous song.', a: "Shape of You", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/44/c7/4f/44c74f0d-72dc-6143-d4d0-ba14d661ca0d/mzaf_9566898362556366703.plus.aac.p.m4a", category: 'music', alt: ["ed sheeran"] },
      { q: 'Name this famous song.', a: "Smells Like Teen Spirit", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/a6/53/1e/a6531efa-397c-eb73-ecab-9b2790c1471e/mzaf_16440344883389407474.plus.aac.p.m4a", category: 'music', alt: ["nirvana"] },
      { q: 'Name this famous song.', a: "Stairway to Heaven", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/60/61/5f/60615fd1-7425-78b3-21ab-fed7411a89ea/mzaf_7178841208140363975.plus.aac.p.m4a", category: 'music', alt: ["led zeppelin"] },
      { q: 'Name this famous song.', a: "Sweet Child o' Mine", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/bc/fd/73/bcfd7312-9f1e-a1b0-524b-cbda6e0c1050/mzaf_248640128027576869.plus.aac.p.m4a", category: 'music', alt: ["sweet child of mine"] },
    ],
    T: [
      { q: 'Name this famous song.', a: "Thriller", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/58/8c/cb/588ccb9a-ab79-4a38-43b5-d4c24ea42859/mzaf_2083607504726567992.plus.aac.p.m4a", category: 'music', alt: ["michael jackson"] },
    ],
    W: [
      { q: 'Name this famous song.', a: "We Will Rock You", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/e9/37/42/e9374231-9cef-ad56-365c-a7ba09e4fa55/mzaf_10566507321838390251.plus.aac.p.m4a", category: 'music', alt: ["queen"] },
    ],
  },
};
