import type { RawPack } from '../core/packs';

// More iTunes-preview songs merged into the songs pack. Generated by scripts/gensongs_add.mjs.
export const songsExtra: RawPack['letters'] = {
  'A': [
    { q: 'Name this famous song.', a: "Apologize", artist: "OneRepublic", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/d7/a5/ac/d7a5ac54-0dbf-5bea-df14-c9965ac2e682/mzaf_2048711194344336393.plus.aac.p.m4a", category: 'music', alt: ["onerepublic"] },
  ],
  'B': [
    { q: 'Name this famous song.', a: "Beautiful Day", artist: "U2", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/29/ec/84/29ec846c-769f-91f2-5e28-768fa9de514b/mzaf_17613297004823866094.plus.aac.p.m4a", category: 'music', alt: ["u2"] },
    { q: 'Name this famous song.', a: "Black Hole Sun", artist: "Soundgarden", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/c3/7c/32/c37c32b4-b95d-1714-a205-4848458c0ba1/mzaf_7576631968114037271.plus.aac.p.m4a", category: 'music', alt: ["soundgarden"] },
    { q: 'Name this famous song.', a: "Black or White", artist: "Michael Jackson", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/69/01/0c/69010c8e-2ff7-2809-589d-6f304400a359/mzaf_3468624104964279051.plus.aac.p.m4a", category: 'music', alt: ["michael jackson"] },
    { q: 'Name this famous song.', a: "Born to Be Wild", artist: "Steppenwolf", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/79/1f/26/791f26bf-abc4-d9fc-4dd1-f93a27533059/mzaf_7059983360387846257.plus.aac.p.m4a", category: 'music', alt: ["steppenwolf"] },
    { q: 'Name this famous song.', a: "Buddy Holly", artist: "Weezer", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/00/82/10/008210b3-c5b0-c8fe-14f1-16e8c4189609/mzaf_3151660340378036823.plus.aac.p.m4a", category: 'music', alt: ["weezer"] },
  ],
  'C': [
    { q: 'Name this famous song.', a: "Chop Suey", artist: "System of a Down", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/f4/a1/c2/f4a1c207-6d73-e3bd-8fcb-bd6c5037021a/mzaf_16212608709217830172.plus.aac.p.m4a", category: 'music', alt: ["system of a down"] },
  ],
  'D': [
    { q: 'Name this famous song.', a: "Don't Speak", artist: "No Doubt", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/eb/d3/dd/ebd3dd7b-ef82-0855-54b0-3c978e7f1594/mzaf_13350123702531292562.plus.aac.p.m4a", category: 'music', alt: ["no doubt"] },
    { q: 'Name this famous song.', a: "Demons", artist: "Imagine Dragons", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/fc/d4/e8/fcd4e814-39f4-19e8-f421-c2d269698025/mzaf_1039703479531920971.plus.aac.p.m4a", category: 'music', alt: ["imagine dragons"] },
  ],
  'E': [
    { q: 'Name this famous song.', a: "Everybody Hurts", artist: "R.E.M.", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/35/d3/75/35d3756f-e346-3d3b-a4b6-032e498120b4/mzaf_7316380479935001754.plus.aac.p.m4a", category: 'music', alt: ["r.e.m."] },
  ],
  'G': [
    { q: 'Name this famous song.', a: "Great Balls of Fire", artist: "Jerry Lee Lewis", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/6e/a8/37/6ea837ab-2a0e-5630-d6d1-ab0aeb606d9c/mzaf_2847959104357510098.plus.aac.p.m4a", category: 'music', alt: ["jerry lee lewis"] },
  ],
  'H': [
    { q: 'Name this famous song.', a: "Hallelujah", artist: "Jeff Buckley", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/3d/f9/7f/3df97f47-c0a4-bdf8-53fa-19e99fa891f1/mzaf_16433687184189443153.plus.aac.p.m4a", category: 'music', alt: ["jeff buckley"] },
    { q: 'Name this famous song.', a: "Hurt", artist: "Johnny Cash", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/2c/0d/06/2c0d06a0-ba56-5a16-1091-76e741f8af52/mzaf_191467376579052128.plus.aac.p.m4a", category: 'music', alt: ["johnny cash"] },
  ],
  'L': [
    { q: 'Name this famous song.', a: "Losing My Religion", artist: "R.E.M.", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/af/be/f5/afbef592-8f00-fe28-8ab4-5c070827b2f8/mzaf_4959761764791628207.plus.aac.p.m4a", category: 'music', alt: ["r.e.m."] },
    { q: 'Name this famous song.', a: "Like a Virgin", artist: "Madonna", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/c4/73/7d/c4737db8-ce9b-e83a-02e7-f21bceeef8a3/mzaf_16709283913248490027.plus.aac.p.m4a", category: 'music', alt: ["madonna"] },
    { q: 'Name this famous song.', a: "Layla", artist: "Derek and the Dominos", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/5f/16/3e/5f163e12-a57d-594f-5132-24576593f72f/mzaf_985921962610857060.plus.aac.p.m4a", category: 'music', alt: ["eric clapton"] },
  ],
  'M': [
    { q: 'Name this famous song.', a: "Mr. Blue Sky", artist: "Electric Light Orchestra", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/66/57/4a/66574ac6-6e8f-3250-1b95-8dc97e3c2023/mzaf_11018520996084989072.plus.aac.p.m4a", category: 'music', alt: ["mr blue sky"] },
    { q: 'Name this famous song.', a: "Man in the Mirror", artist: "Michael Jackson", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/c8/6e/f4/c86ef435-d79a-095b-0cb0-49962be38e7a/mzaf_8312750545964829072.plus.aac.p.m4a", category: 'music', alt: ["michael jackson"] },
    { q: 'Name this famous song.', a: "Moves Like Jagger", artist: "Maroon 5", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/1a/e8/be/1ae8bea8-8962-8168-80d5-65bf3b1478ba/mzaf_471500839444486606.plus.aac.p.m4a", category: 'music', alt: ["maroon 5"] },
    { q: 'Name this famous song.', a: "Money", artist: "Pink Floyd", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/34/87/de/3487de29-7188-04d9-1f5d-3bc113aec69a/mzaf_17953706114080313317.plus.aac.p.m4a", category: 'music', alt: ["pink floyd"] },
  ],
  'O': [
    { q: 'Name this famous song.', a: "One", artist: "U2", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/80/d6/ad/80d6ad67-3920-ffb2-a3c9-e76c0428cd31/mzaf_8418791865712780774.plus.aac.p.m4a", category: 'music', alt: ["u2"] },
  ],
  'S': [
    { q: 'Name this famous song.', a: "Sugar", artist: "Maroon 5", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/1b/3f/68/1b3f68e0-3c42-f367-cd0f-e46c746e0668/mzaf_15052021441666328650.plus.aac.p.m4a", category: 'music', alt: ["maroon 5"] },
    { q: 'Name this famous song.', a: "Sweet Dreams", artist: "Eurythmics", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/a7/dd/3e/a7dd3e79-dacc-460a-ba25-c9827938a7f1/mzaf_9265723838672937705.plus.aac.p.m4a", category: 'music', alt: ["eurythmics"] },
  ],
  'T': [
    { q: 'Name this famous song.', a: "Tainted Love", artist: "Soft Cell", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/59/ad/28/59ad2888-2b61-7f07-a779-b18cc013c698/mzaf_5227993960460210837.plus.aac.p.m4a", category: 'music', alt: ["soft cell"] },
    { q: 'Name this famous song.', a: "Thunder", artist: "Imagine Dragons", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/78/7d/8b/787d8b89-7b57-d3bc-1f9d-6378fad1b4f5/mzaf_5131352572683029126.plus.aac.p.m4a", category: 'music', alt: ["imagine dragons"] },
    { q: 'Name this famous song.', a: "Take Me Home, Country Roads", artist: "John Denver", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/3a/d4/ed/3ad4ed7c-c395-fb5b-cb9e-09da11308881/mzaf_9789459917359346736.plus.aac.p.m4a", category: 'music', alt: ["country roads"] },
    { q: 'Name this famous song.', a: "Tutti Frutti", artist: "Little Richard", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/99/a3/50/99a350f2-a073-b5dc-3be9-dc54765bc16e/mzaf_572709223409242354.plus.aac.p.m4a", category: 'music', alt: ["little richard"] },
  ],
  'V': [
    { q: 'Name this famous song.', a: "Vienna", artist: "Billy Joel", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/e8/d2/03/e8d203cc-ce97-278b-5abb-c6de33d36d37/mzaf_5153648922176185845.plus.aac.p.m4a", category: 'music', alt: ["billy joel"] },
  ],
  'W': [
    { q: 'Name this famous song.', a: "With or Without You", artist: "U2", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/77/08/84/77088446-6e2d-e624-a959-ba44f81c539f/mzaf_10549980225388125542.plus.aac.p.m4a", category: 'music', alt: ["u2"] },
    { q: 'Name this famous song.', a: "Wake Me Up When September Ends", artist: "Green Day", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/95/5b/10/955b1049-c8ab-ddda-2353-2ec84ab04a10/mzaf_6914292074393017741.plus.aac.p.m4a", category: 'music', alt: ["green day"] },
    { q: 'Name this famous song.', a: "Wish You Were Here", artist: "Pink Floyd", audio: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/5e/4b/35/5e4b3554-282d-12dd-e420-728287a1d3b1/mzaf_14938061551507100947.plus.aac.p.m4a", category: 'music', alt: ["pink floyd"] },
  ],
};
