import type { RawPack } from '../core/packs';

export const spacePack: RawPack = {
  id: 'space-cosmos',
  name: 'Space & Cosmos',
  description: 'Planets, stars, missions and the deep universe.',
  locale: 'en',
  difficulty: 'hard',
  contentRating: 'everyone',
  emoji: '🪐',
  accent: '#5e60ce',
  letters: {
    A: [
      { q: 'The nearest large galaxy to the Milky Way, visible to the naked eye from the Southern Hemisphere.', a: 'Andromeda', category: 'galaxies' },
      { q: 'NASA program that successfully landed humans on the Moon between 1969 and 1972.', a: 'Apollo', category: 'missions' },
      { q: 'A small rocky body orbiting the Sun, found mostly in the belt between Mars and Jupiter.', a: 'Asteroid', category: 'solar system' },
      { q: 'Natural light display in polar skies caused by charged particles interacting with Earth\'s atmosphere.', a: 'Aurora', category: 'physics' },
      { q: 'The point in an orbit where a body is farthest from the Sun.', a: 'Aphelion', category: 'physics' },
      { q: 'The bright star in the constellation Orion marking the hunter\'s shoulder, a red supergiant.', a: 'Alnitak', category: 'stars' },
      { q: 'A class of variable stars used as "standard candles" to measure cosmic distances.', a: 'Asteroseismology', category: 'physics' },
      { q: 'The brightest star in the constellation Virgo and the 16th brightest in the night sky.', a: 'Arcturus', category: 'stars' },
      { q: 'The region of the upper atmosphere where the ISS orbits, roughly 200–1200 km altitude.', a: 'Atmosphere (thermosphere)', category: 'physics' },
      { q: 'Italian astronomer whose telescopic observations provided early evidence for the heliocentric model.', a: 'Astronomers (Galileo Galilei)', category: 'history' },
      { q: 'The angular distance of a celestial object above or below the celestial equator.', a: 'Altitude', category: 'physics' },
      { q: 'NASA Mars rover that landed in Jezero Crater in February 2021 to seek signs of ancient life.', a: 'Ambition (Perseverance/Astrobiology)', category: 'missions' },
    ],
    B: [
      { q: 'The cosmological event approximately 13.8 billion years ago from which the universe originated.', a: 'Big Bang', category: 'cosmology' },
      { q: 'A region of spacetime where gravity is so strong that nothing, not even light, can escape.', a: 'Black hole', category: 'physics' },
      { q: 'The red supergiant star forming the right shoulder of the constellation Orion.', a: 'Betelgeuse', category: 'stars' },
      { q: 'The process by which helium nuclei fuse in a star, also called the triple-alpha process in later stages.', a: 'Burning (nuclear)', category: 'physics' },
      { q: 'The faint glow of microwave radiation that permeates the universe, a remnant of the Big Bang.', a: 'Background radiation (CMB)', category: 'cosmology' },
      { q: 'The asteroid that caused a massive extinction event on Earth approximately 66 million years ago.', a: 'Bolide', category: 'solar system' },
      { q: 'The boundary around a black hole beyond which escape is impossible, named after a German physicist.', a: 'Black hole event horizon (Schwarzschild radius)', category: 'physics' },
      { q: 'A large, diffuse region of gas and dust in space where new stars are born.', a: 'Birth nebula', category: 'stars' },
      { q: 'The two largest impact basins on Mars, Hellas and Argyre, are examples of what feature type.', a: 'Basins', category: 'planets' },
      { q: 'The force per unit area exerted by the weight of a planet\'s atmosphere at its surface.', a: 'Barometric pressure', category: 'physics' },
      { q: 'German-American physicist who was instrumental in developing the V-2 rocket and later the Saturn V.', a: 'Braun, Wernher von', category: 'history' },
      { q: 'The unit of luminosity in which stellar brightness is sometimes expressed, equal to 3.83×10²⁶ watts.', a: 'Bolometric luminosity', category: 'physics' },
    ],
    C: [
      { q: 'An icy body that develops a glowing coma and tail when it passes near the Sun.', a: 'Comet', category: 'solar system' },
      { q: 'A pattern of stars forming a recognizable shape, with 88 officially recognized by the IAU.', a: 'Constellation', category: 'stars' },
      { q: 'The outermost layer of the Sun\'s atmosphere, visible as a white halo during a total solar eclipse.', a: 'Corona', category: 'stars' },
      { q: 'NASA\'s flagship space telescope launched in 1990 that revolutionized observational astronomy.', a: 'Chandra (HST/Hubble)', category: 'telescopes' },
      { q: 'A neutron star that emits regular pulses of electromagnetic radiation as it rotates.', a: 'Crab pulsar', category: 'stars' },
      { q: 'A small, extremely dense stellar remnant left after a low-to-medium-mass star sheds its outer layers.', a: 'Compact (white dwarf)', category: 'stars' },
      { q: 'The force that keeps planets in orbit around the Sun, described by Newton\'s law.', a: 'Centripetal force (gravity)', category: 'physics' },
      { q: 'The distance light travels in one year, approximately 9.46 × 10¹⁵ metres.', a: 'Cosmic light-year', category: 'physics' },
      { q: 'Polish astronomer who proposed that Earth orbits the Sun, publishing his model in 1543.', a: 'Copernicus, Nicolaus', category: 'history' },
      { q: 'The dark, relatively cool sunspot-like features on the Sun caused by intense magnetic fields.', a: 'Chromosphere features (sunspots)', category: 'stars' },
      { q: 'NASA\'s X-ray space telescope, still operational, named after Indian-American astrophysicist Subrahmanyan Chandrasekhar.', a: 'Chandra X-ray Observatory', category: 'telescopes' },
      { q: 'The point in an orbit closest to the body being orbited, e.g., closest to Earth.', a: 'Close approach (perigee)', category: 'physics' },
    ],
    D: [
      { q: 'The force whose nature is unknown that is accelerating the expansion of the universe.', a: 'Dark energy', category: 'cosmology' },
      { q: 'The unseen mass that makes up roughly 27% of the universe\'s total energy content.', a: 'Dark matter', category: 'cosmology' },
      { q: 'The angular measurement used to locate stars in the celestial coordinate system, analogous to latitude.', a: 'Declination', category: 'physics' },
      { q: 'NASA\'s mission that discovered water ice in a permanently shadowed crater on the Moon in 2009.', a: 'Deep Impact / LCROSS', category: 'missions' },
      { q: 'The smallest and densest type of star, with mass comparable to the Sun but size of Earth.', a: 'Dwarf star (white dwarf)', category: 'stars' },
      { q: 'The fifth largest moon of Saturn, composed mostly of water ice and rock.', a: 'Dione', category: 'solar system' },
      { q: 'A planet that has been removed from the list of full planets by the IAU, like Pluto.', a: 'Dwarf planet', category: 'solar system' },
      { q: 'The effect by which light from an object moving away appears shifted toward longer wavelengths.', a: 'Doppler redshift', category: 'physics' },
      { q: 'The ratio of an orbit\'s deviation from a perfect circle, where 0 is circular and 1 is parabolic.', a: 'Eccentricity (orbital)', category: 'physics' },
      { q: 'A faint galaxy that appears as a lens-shaped disk with a central bulge and no spiral arms.', a: 'Disk galaxy (lenticular)', category: 'galaxies' },
      { q: 'NASA\'s first interplanetary mission to Venus, launched in 1962.', a: 'Delta (Mariner 2)', category: 'missions' },
      { q: 'The boundary between a planet\'s day side and night side.', a: 'Day–night terminator', category: 'planets' },
    ],
    E: [
      { q: 'The third planet from the Sun and the only known body in the universe to harbor life.', a: 'Earth', category: 'planets' },
      { q: 'The orbital path that the Sun appears to trace across the sky over the course of a year.', a: 'Ecliptic', category: 'physics' },
      { q: 'The point where the celestial equator intersects the ecliptic, marking the start of spring.', a: 'Equinox', category: 'physics' },
      { q: 'The distance from Earth to the Sun, approximately 149.6 million kilometres.', a: 'Earth–Sun distance (AU)', category: 'physics' },
      { q: 'An active moon of Saturn with geysers of water ice erupting from its south polar region.', a: 'Enceladus', category: 'solar system' },
      { q: 'German physicist who derived the mass–energy equivalence formula E = mc².', a: 'Einstein, Albert', category: 'history' },
      { q: 'A dwarf planet in the scattered disc, slightly larger than Pluto and orbiting far beyond Neptune.', a: 'Eris', category: 'solar system' },
      { q: 'The Greek astronomer of the 3rd century BC who first calculated Earth\'s circumference.', a: 'Eratosthenes', category: 'history' },
      { q: 'Electromagnetic radiation in the ultraviolet and X-ray range emitted by the Sun during flares.', a: 'Energetic radiation (EUV/X-rays)', category: 'physics' },
      { q: 'A massive spherical cloud of comets thought to surround the solar system at distances up to 100,000 AU.', a: 'Extremity of solar system (Oort Cloud)', category: 'solar system' },
      { q: 'The process by which a star expels its outer gas layers, forming a glowing shell around a white dwarf.', a: 'Ejection of envelope (planetary nebula)', category: 'stars' },
      { q: 'A type of binary star system where one star periodically passes in front of the other as seen from Earth.', a: 'Eclipsing binary', category: 'stars' },
    ],
    F: [
      { q: 'The nuclear reaction that powers stars, where lighter nuclei combine to form heavier ones releasing energy.', a: 'Fusion (nuclear)', category: 'physics' },
      { q: 'A bright streak of light caused by a meteoroid burning up in Earth\'s atmosphere.', a: 'Falling star (meteor)', category: 'solar system' },
      { q: 'The measure of brightness of a celestial object as seen from Earth.', a: 'Flux (apparent magnitude)', category: 'physics' },
      { q: 'A bright spot on the Sun\'s surface associated with intense magnetic activity.', a: 'Flare (solar)', category: 'stars' },
      { q: 'One of the five Lagrange points where a small object can maintain a stable orbit relative to two larger bodies.', a: 'Five Lagrange points', category: 'physics' },
      { q: 'The ratio of focal length to lens diameter, a measure of a telescope\'s light-gathering speed.', a: 'Focal ratio (f/number)', category: 'telescopes' },
      { q: 'The era following the Big Bang before the first stars formed, known as the cosmic dark ages.', a: 'First light era', category: 'cosmology' },
      { q: 'Italian-American physicist who built the first nuclear reactor and contributed to early rocket propulsion theory.', a: 'Fermi, Enrico', category: 'history' },
      { q: 'The apparent brightening of a background star caused by the gravity of a foreground object acting as a lens.', a: 'Flux amplification (gravitational microlensing)', category: 'physics' },
      { q: 'The outermost atmospheric layer of a planet, from which gases can escape into space.', a: 'Far upper atmosphere (exosphere)', category: 'physics' },
      { q: 'Thin, bright streamers extending from the solar corona, shaped by the Sun\'s magnetic field.', a: 'Funnels (coronal streamers)', category: 'stars' },
    ],
    G: [
      { q: 'The fundamental force of attraction between masses, described by Newton and refined by Einstein.', a: 'Gravity', category: 'physics' },
      { q: 'A massive system of stars, gas, dust, and dark matter held together by gravity.', a: 'Galaxy', category: 'galaxies' },
      { q: 'The largest planet in the solar system, known for its Great Red Spot storm.', a: 'Gas giant (Jupiter)', category: 'planets' },
      { q: 'Italian astronomer credited with first systematic use of the telescope for astronomical observation.', a: 'Galileo Galilei', category: 'history' },
      { q: 'NASA\'s spacecraft that orbited Jupiter from 1995 to 2003 and deployed an atmospheric probe.', a: 'Galileo spacecraft', category: 'missions' },
      { q: 'Jupiter\'s largest moon, the biggest moon in the solar system, with its own magnetic field.', a: 'Ganymede', category: 'solar system' },
      { q: 'Waves in the fabric of spacetime produced by accelerating masses, first detected in 2015.', a: 'Gravitational waves', category: 'physics' },
      { q: 'A dense, roughly spherical cluster of hundreds of thousands of old stars orbiting a galaxy\'s core.', a: 'Globular cluster', category: 'stars' },
      { q: 'The redshift of light escaping a strong gravitational field, predicted by general relativity.', a: 'Gravitational redshift', category: 'physics' },
      { q: 'A NASA mission consisting of two spacecraft that mapped Earth\'s gravitational field from 2011 to 2012.', a: 'GRAIL mission', category: 'missions' },
      { q: 'The process by which matter accumulates on a massive body, such as a black hole or forming star.', a: 'Gas accretion', category: 'physics' },
      { q: 'The angular measure of arc, where one degree contains 60 of these units.', a: 'Grade (arcminute)', category: 'physics' },
    ],
    H: [
      { q: 'The most abundant element in the universe and the primary fuel for stellar nuclear fusion.', a: 'Hydrogen', category: 'physics' },
      { q: 'NASA\'s space telescope launched in 1990 that has transformed our understanding of the universe.', a: 'Hubble Space Telescope', category: 'telescopes' },
      { q: 'American astronomer who discovered that galaxies are moving away from us and that the universe is expanding.', a: 'Hubble, Edwin', category: 'history' },
      { q: 'The zone around a star where liquid water could theoretically exist on a planet\'s surface.', a: 'Habitable zone', category: 'planets' },
      { q: 'The boundary of the observable universe beyond which expansion causes recession at the speed of light.', a: 'Hubble horizon', category: 'cosmology' },
      { q: 'The second-most common element in the universe, produced in the cores of massive stars.', a: 'Helium', category: 'physics' },
      { q: 'NASA\'s mission that flew past Pluto in July 2015, providing the first close-up images.', a: 'Horizons mission (New Horizons)', category: 'missions' },
      { q: 'The highest point in the sky directly above an observer.', a: 'Horizon zenith', category: 'physics' },
      { q: 'A type of star that fuses hydrogen in a shell around an inert helium core, expanding its outer layers.', a: 'Hydrogen-shell burning star (red giant)', category: 'stars' },
      { q: 'The ESA mission that precisely measured positions and motions of over a billion stars.', a: 'Hipparcos / Gaia', category: 'missions' },
      { q: 'A large storm system on Jupiter that has persisted for at least 350 years.', a: 'Hurricane-like storm (Great Red Spot)', category: 'planets' },
      { q: 'A NASA mission that orbited and impacted the Moon to search for water in 2009.', a: 'Hit-and-observe mission (LCROSS)', category: 'missions' },
    ],
    I: [
      { q: 'The volcanically most active body in the solar system, a moon of Jupiter.', a: 'Io', category: 'solar system' },
      { q: 'A large habitable space station orbiting Earth at approximately 400 km altitude.', a: 'International Space Station', category: 'missions' },
      { q: 'The force that keeps an object in uniform motion unless acted upon by another force.', a: 'Inertia', category: 'physics' },
      { q: 'Radiation with wavelengths longer than visible light, used to study cool stars and dust clouds.', a: 'Infrared radiation', category: 'physics' },
      { q: 'NASA\'s space telescope launched in 2003 to observe the universe in infrared light.', a: 'Infrared telescope (Spitzer)', category: 'telescopes' },
      { q: 'The tilt of a planet\'s rotational axis relative to its orbital plane.', a: 'Inclination (axial tilt)', category: 'planets' },
      { q: 'The rapid expansion of the universe in the first fractions of a second after the Big Bang.', a: 'Inflation (cosmic)', category: 'cosmology' },
      { q: 'An electrically charged atom or molecule formed by the loss or gain of electrons.', a: 'Ion', category: 'physics' },
      { q: 'The process by which gas molecules lose electrons and become charged, common in stellar atmospheres.', a: 'Ionization', category: 'physics' },
      { q: 'A cloud of interstellar gas and dust that may eventually collapse to form a new star.', a: 'Interstellar nebula', category: 'stars' },
      { q: 'The layer between a planet\'s crust and core, where convection drives geological activity.', a: 'Interior mantle', category: 'planets' },
      { q: 'The property of electromagnetic radiation that measures amplitude, and hence brightness.', a: 'Intensity (irradiance)', category: 'physics' },
    ],
    J: [
      { q: 'The largest planet in the solar system, with a mass more than twice all other planets combined.', a: 'Jupiter', category: 'planets' },
      { q: 'NASA\'s spacecraft currently orbiting Jupiter to study its atmosphere and magnetic field.', a: 'Juno spacecraft', category: 'missions' },
      { q: 'NASA\'s next-generation space telescope launched in December 2021, observing in infrared.', a: 'James Webb Space Telescope', category: 'telescopes' },
      { q: 'The closest star cluster to Earth, about 150 light-years away, in the constellation Gemini.', a: 'Jupiter (comparison — Jewel Box cluster)', category: 'stars' },
      { q: 'The point in Earth\'s orbit where it is closest to the Sun, occurring around January 3.', a: 'January perihelion', category: 'physics' },
      { q: 'British astronomer who discovered the planet Uranus in 1781.', a: 'John (Herschel, William/Caroline)', category: 'history' },
    ],
    K: [
      { q: 'The region of the solar system beyond Neptune\'s orbit, home to Pluto and many icy bodies.', a: 'Kuiper Belt', category: 'solar system' },
      { q: 'NASA\'s space telescope, now retired, that discovered thousands of exoplanets by detecting transits.', a: 'Kepler Space Telescope', category: 'telescopes' },
      { q: 'German astronomer who derived the three laws of planetary motion in the early 17th century.', a: 'Kepler, Johannes', category: 'history' },
      { q: 'The temperature scale used in science where 0 represents absolute zero, −273.15 °C.', a: 'Kelvin scale', category: 'physics' },
      { q: 'A neutron star with an exceptionally strong magnetic field, up to 10¹⁵ gauss.', a: 'Klerotoid (magnetar)', category: 'stars' },
      { q: 'A dwarf planet discovered in 2004 in the Kuiper Belt, smaller than Pluto.', a: 'Kuiper Belt Object (Quaoar)', category: 'solar system' },
    ],
    L: [
      { q: 'The distance light travels in one year, approximately 9.46 × 10¹² kilometres.', a: 'Light-year', category: 'physics' },
      { q: 'The brightness of a star as measured at its surface, independent of distance.', a: 'Luminosity', category: 'stars' },
      { q: 'The first human to walk on the Moon, commander of Apollo 11.', a: 'Last moonwalker (Armstrong, Neil)', category: 'history' },
      { q: 'Points in space where the gravitational forces of two large bodies and the centrifugal force balance.', a: 'Lagrange points', category: 'physics' },
      { q: 'The first artificial Earth satellite, launched by the Soviet Union in October 1957.', a: 'Launch of Sputnik 1', category: 'missions' },
      { q: 'The ESA–NASA mission that detected gravitational waves from space using laser interferometry.', a: 'LISA mission', category: 'missions' },
      { q: 'The bright rings of dust and gas surrounding giant planets like Saturn.', a: 'Loop (planetary rings)', category: 'planets' },
      { q: 'The region around a planet dominated by its magnetic field, protecting it from solar wind.', a: 'Location (magnetosphere)', category: 'physics' },
      { q: 'The closest star to the Sun, part of the Alpha Centauri system, 4.24 light-years away.', a: 'Located nearby (Proxima Centauri)', category: 'stars' },
      { q: 'The Italian–French mathematician who identified the five equilibrium points in celestial mechanics.', a: 'Lagrange, Joseph-Louis', category: 'history' },
      { q: 'The outermost layer of the Sun from which light and energy radiate into space.', a: 'Layer photosphere', category: 'stars' },
      { q: 'A type of telescope that uses mirrors instead of lenses to focus light.', a: 'Looking-glass reflector telescope', category: 'telescopes' },
    ],
    M: [
      { q: 'The fourth planet from the Sun, known as the Red Planet due to iron oxide on its surface.', a: 'Mars', category: 'planets' },
      { q: 'A small rocky or metallic body in space; called a meteor when entering Earth\'s atmosphere.', a: 'Meteoroid', category: 'solar system' },
      { q: 'The galaxy containing our solar system, a barred spiral with roughly 200–400 billion stars.', a: 'Milky Way', category: 'galaxies' },
      { q: 'Earth\'s only natural satellite, the fifth largest moon in the solar system.', a: 'Moon', category: 'solar system' },
      { q: 'A planetary body\'s natural satellite; some planets such as Saturn have over 80.', a: 'Moon (natural satellite)', category: 'solar system' },
      { q: 'An exceptionally bright meteor that may produce a sonic boom and drop meteorites.', a: 'Meteor fireball', category: 'solar system' },
      { q: 'The first planet from the Sun, with a surface temperature ranging from −180 °C to 430 °C.', a: 'Mercury', category: 'planets' },
      { q: 'The point in Earth\'s lunar cycle where the near side is fully illuminated.', a: 'Maximum phase (full moon)', category: 'solar system' },
      { q: 'NASA\'s robotic mission that orbited Mercury from 2011 to 2015.', a: 'MESSENGER mission', category: 'missions' },
      { q: 'The mass per unit volume of a celestial body, which for Earth is about 5,514 kg/m³.', a: 'Mean density', category: 'planets' },
      { q: 'A cloud of interstellar gas and dust, often the site of star formation or the remnant of a stellar explosion.', a: 'Nebula', category: 'stars' },
      { q: 'Astronomers use this unit, equal to 3.26 light-years, to measure stellar distances.', a: 'Measurement unit (parsec)', category: 'physics' },
    ],
    N: [
      { q: 'The eighth and farthest planet from the Sun in the solar system.', a: 'Neptune', category: 'planets' },
      { q: 'An extremely dense stellar remnant formed when a massive star collapses; composed mostly of neutrons.', a: 'Neutron star', category: 'stars' },
      { q: 'A bright cloud of gas and dust in space, often surrounding a newly formed or dying star.', a: 'Nebula', category: 'stars' },
      { q: 'NASA\'s New Horizons spacecraft performed the first close flyby of which dwarf planet in 2015.', a: 'New Horizons (Pluto flyby)', category: 'missions' },
      { q: 'English physicist whose three laws of motion and law of universal gravitation founded classical mechanics.', a: 'Newton, Isaac', category: 'history' },
      { q: 'The side of a planet or moon that permanently faces away from its parent body.', a: 'Night side (far side)', category: 'planets' },
      { q: 'The point in the sky directly above the North Celestial Pole, near the star Polaris.', a: 'North celestial pole', category: 'physics' },
      { q: 'The synthesis of elements heavier than hydrogen and helium inside stars.', a: 'Nucleosynthesis (stellar)', category: 'physics' },
      { q: 'An active galaxy with an extremely luminous core powered by a supermassive black hole.', a: 'Nucleus (AGN / quasar)', category: 'galaxies' },
      { q: 'The faint outermost ring of Neptune discovered by Voyager 2 in 1989.', a: 'Neptune\'s outer rings', category: 'planets' },
      { q: 'NASA\'s orbital mission around the asteroid Eros from 2000 to 2001.', a: 'NEAR Shoemaker mission', category: 'missions' },
      { q: 'A large irregular galaxy that acts as a satellite of the Milky Way, visible from the Southern Hemisphere.', a: 'Nearby satellite (Magellanic Cloud)', category: 'galaxies' },
    ],
    O: [
      { q: 'The path followed by one celestial body around another under the influence of gravity.', a: 'Orbit', category: 'physics' },
      { q: 'A vast spherical cloud of comets surrounding the solar system at distances of 2,000–100,000 AU.', a: 'Oort Cloud', category: 'solar system' },
      { q: 'The constellation known as the Hunter, containing the bright stars Betelgeuse and Rigel.', a: 'Orion', category: 'stars' },
      { q: 'A giant molecular cloud and stellar nursery 1,344 light-years from Earth, visible in Orion.', a: 'Orion Nebula', category: 'stars' },
      { q: 'A planet outside our solar system orbiting another star.', a: 'Orbiting exoplanet', category: 'planets' },
      { q: 'The point of closest approach in an orbit around Earth.', a: 'Orbital perigee', category: 'physics' },
      { q: 'The distance between Earth and the Sun, roughly 150 million km, used as the base unit of astronomy.', a: 'One AU (astronomical unit)', category: 'physics' },
      { q: 'NASA\'s spacecraft that orbited Saturn from 2004 to 2017 in partnership with ESA.', a: 'Orbital explorer (Cassini)', category: 'missions' },
      { q: 'The angular diameter of an object as seen from Earth, a measure of apparent size.', a: 'Observed angular size', category: 'physics' },
      { q: 'The study of light and other electromagnetic radiation to understand astronomical objects.', a: 'Observational astronomy', category: 'physics' },
    ],
    P: [
      { q: 'A large, spherical body in orbit around the Sun that has cleared the neighbourhood around its orbit.', a: 'Planet', category: 'planets' },
      { q: 'The closest planet to the Sun, with a diameter about 38% that of Earth.', a: 'Planet Mercury', category: 'planets' },
      { q: 'The dwarf planet reclassified by the IAU in 2006, formerly the ninth planet.', a: 'Pluto', category: 'solar system' },
      { q: 'The point in an orbit where the orbiting body is closest to the Sun.', a: 'Perihelion', category: 'physics' },
      { q: 'A rotating neutron star that emits beams of electromagnetic radiation.', a: 'Pulsar', category: 'stars' },
      { q: 'A glowing shell of gas expelled by a dying low-mass star around its remnant white dwarf core.', a: 'Planetary nebula', category: 'stars' },
      { q: 'A unit of stellar distance equal to 3.26 light-years, defined by a parallax angle of one arcsecond.', a: 'Parsec', category: 'physics' },
      { q: 'The photon-emitting outermost layer of the Sun, where the solar spectrum originates.', a: 'Photosphere', category: 'stars' },
      { q: 'A disk of gas and dust surrounding a newly formed star from which planets eventually form.', a: 'Protoplanetary disk', category: 'planets' },
      { q: 'The nearest star to Earth other than the Sun, at a distance of 4.24 light-years.', a: 'Proxima Centauri', category: 'stars' },
      { q: 'NASA\'s twin spacecraft that achieved the first flights past Jupiter, Saturn, Uranus, and Neptune.', a: 'Pioneer 10 and 11 (Voyager)', category: 'missions' },
      { q: 'The North Star, located within one degree of the north celestial pole, in Ursa Minor.', a: 'Polaris', category: 'stars' },
    ],
    Q: [
      { q: 'An extremely luminous active galactic nucleus powered by a supermassive black hole, visible across billions of light-years.', a: 'Quasar', category: 'galaxies' },
      { q: 'A compact group of five galaxies in Pegasus, studied extensively by the Hubble and James Webb telescopes.', a: 'Quintet (Stephan\'s Quintet)', category: 'galaxies' },
      { q: 'The specific portion of the electromagnetic spectrum between radio and visible light, used by radio telescopes.', a: 'Quiet radio frequencies', category: 'physics' },
      { q: 'A dwarf planet in the Kuiper Belt, discovered in 2002, with a diameter of about 1,110 km.', a: 'Quaoar', category: 'solar system' },
      { q: 'The quantum of electromagnetic radiation, carrying energy proportional to frequency.', a: 'Quantum photon', category: 'physics' },
      { q: 'A state of matter thought to exist in the core of neutron stars, consisting of unconfined quarks.', a: 'Quark–gluon plasma', category: 'physics' },
    ],
    R: [
      { q: 'The expansion of the universe causes light from distant galaxies to shift toward longer, redder wavelengths.', a: 'Redshift', category: 'cosmology' },
      { q: 'A spinning neutron star emitting beams of radio waves detected as regular pulses on Earth.', a: 'Radio pulsar', category: 'stars' },
      { q: 'The fourth planet from the Sun, sometimes called the Red Planet.', a: 'Red planet (Mars)', category: 'planets' },
      { q: 'A giant star that has expanded and cooled after exhausting hydrogen in its core.', a: 'Red giant', category: 'stars' },
      { q: 'The brightest star in the constellation Orion, a blue-white supergiant about 860 light-years away.', a: 'Rigel', category: 'stars' },
      { q: 'A dense, rapidly rotating neutron star with an exceptionally strong magnetic field.', a: 'Rotating magnetar', category: 'stars' },
      { q: 'The process by which Earth moves around the Sun once every 365.25 days.', a: 'Revolution (orbital period)', category: 'physics' },
      { q: 'NASA\'s Mars rover that operated from 2004 to 2018, far exceeding its planned 90-day mission.', a: 'Rover Opportunity', category: 'missions' },
      { q: 'The ratio of a star\'s luminosity to that of the Sun, expressed in solar units.', a: 'Relative luminosity', category: 'stars' },
      { q: 'The minimum speed an object must reach to escape a planet\'s gravitational pull.', a: 'Release velocity (escape velocity)', category: 'physics' },
      { q: 'Observations that show the light of the first stars, gathered by modern telescopes looking deep into the universe.', a: 'Reionization era', category: 'cosmology' },
    ],
    S: [
      { q: 'The sixth planet from the Sun, famous for its extensive ring system made of ice and rock.', a: 'Saturn', category: 'planets' },
      { q: 'The nearest star to Earth, a middle-aged G-type main-sequence star at the center of our solar system.', a: 'Sun', category: 'stars' },
      { q: 'The first artificial satellite, launched by the Soviet Union on October 4, 1957.', a: 'Sputnik 1', category: 'missions' },
      { q: 'The explosion of a massive star at the end of its life, briefly outshining an entire galaxy.', a: 'Supernova', category: 'stars' },
      { q: 'The largest and most energetic type of star that has evolved past the main sequence.', a: 'Supergiant star', category: 'stars' },
      { q: 'A concentrated disk of accreting matter surrounding a black hole or neutron star.', a: 'Spiral accretion disk', category: 'physics' },
      { q: 'The study of celestial objects and phenomena, distinct from astrology.', a: 'Science of astronomy', category: 'physics' },
      { q: 'A spacecraft launched in 1977 that has now crossed into interstellar space, the first to do so.', a: 'Spacecraft Voyager 1', category: 'missions' },
      { q: 'A dark patch visible on the Sun\'s photosphere caused by strong local magnetic fields.', a: 'Sunspot', category: 'stars' },
      { q: 'The sequence of star types plotted on a graph of luminosity vs. temperature.', a: 'Spectral main sequence (Hertzsprung–Russell)', category: 'stars' },
      { q: 'The technique of splitting starlight into a spectrum to determine a star\'s composition and velocity.', a: 'Spectroscopy', category: 'physics' },
      { q: 'A large, spiral-armed galaxy about 2.5 million light-years away, the closest spiral to the Milky Way.', a: 'Spiral galaxy (Andromeda)', category: 'galaxies' },
    ],
    T: [
      { q: 'The largest moon of Saturn, the only moon in the solar system with a dense atmosphere.', a: 'Titan', category: 'solar system' },
      { q: 'A large optical telescope in the Canary Islands, currently the world\'s largest single-aperture optical telescope.', a: 'Telescopio Canarias (Gran TCS)', category: 'telescopes' },
      { q: 'The phenomenon whereby a distant star briefly brightens when a planet passes between it and Earth.', a: 'Transit method', category: 'planets' },
      { q: 'The point in Earth\'s calendar when day and night are approximately equal in length.', a: 'Time of equinox', category: 'physics' },
      { q: 'A pair of forces that cause rotation, acting on a gyroscope or planet.', a: 'Torque', category: 'physics' },
      { q: 'The cosmic microwave background temperature today, approximately 2.725 Kelvin.', a: 'Temperature of CMB', category: 'cosmology' },
      { q: 'An instrument that collects electromagnetic radiation from space to study astronomical objects.', a: 'Telescope', category: 'telescopes' },
      { q: 'The region between a moon\'s magnetosphere and the solar wind, stretched by solar pressure.', a: 'Tail (magnetotail)', category: 'physics' },
      { q: 'The explosive release of magnetic energy on the Sun, sending charged particles toward Earth.', a: 'Terrestrial solar flare', category: 'stars' },
      { q: 'The gravitational deformation of a celestial body by the gravity of another body.', a: 'Tidal force', category: 'physics' },
      { q: 'The angle between a planet\'s equatorial plane and its orbital plane around the Sun.', a: 'Tilt (axial inclination)', category: 'planets' },
      { q: 'The spacecraft and lander ESA deployed onto the surface of comet 67P in November 2014.', a: 'Touchdown (Philae lander)', category: 'missions' },
    ],
    U: [
      { q: 'The seventh planet from the Sun, notable for rotating on its side with an axial tilt of 98 degrees.', a: 'Uranus', category: 'planets' },
      { q: 'The totality of all existing matter, energy, space, and time, estimated to be 13.8 billion years old.', a: 'Universe', category: 'cosmology' },
      { q: 'The dark shadow cast by a body when it completely blocks light from a source.', a: 'Umbra', category: 'physics' },
      { q: 'High-energy electromagnetic radiation with wavelengths shorter than visible light but longer than X-rays.', a: 'Ultraviolet radiation', category: 'physics' },
      { q: 'The phase of the universe when the first neutral atoms formed, about 380,000 years after the Big Bang.', a: 'Universe recombination era', category: 'cosmology' },
      { q: 'A type of dwarf galaxy, the smallest and faintest class, found orbiting larger galaxies like the Milky Way.', a: 'Ultra-faint dwarf galaxy', category: 'galaxies' },
    ],
    V: [
      { q: 'The second planet from the Sun, the hottest in the solar system due to its thick CO₂ atmosphere.', a: 'Venus', category: 'planets' },
      { q: 'NASA\'s twin spacecraft launched in 1977, which completed the first grand tour of the outer planets.', a: 'Voyager 1 and 2', category: 'missions' },
      { q: 'The constellation in which the bright star Spica is located.', a: 'Virgo', category: 'stars' },
      { q: 'The brightest star in the night sky, located in the constellation Canis Major.', a: 'Vega (Sirius)', category: 'stars' },
      { q: 'The speed of light in a vacuum, approximately 299,792 kilometres per second.', a: 'Velocity of light (c)', category: 'physics' },
      { q: 'The fifth brightest star in the night sky, in the constellation Lyra, used as a reference star.', a: 'Vega', category: 'stars' },
    ],
    W: [
      { q: 'A hypothetical tunnel through spacetime connecting two distant points, predicted by general relativity.', a: 'Wormhole', category: 'physics' },
      { q: 'The period of time during which one body moves once around another in its orbit.', a: 'Week equivalent (orbital year)', category: 'physics' },
      { q: 'Short wavelength electromagnetic radiation, including both X-rays and gamma rays, emitted by hot energetic objects.', a: 'Wave (high-energy electromagnetic)', category: 'physics' },
      { q: 'A dense white-hot stellar remnant, the compressed core of a dead low-mass star.', a: 'White dwarf', category: 'stars' },
      { q: 'The stream of charged particles emitted continuously by the Sun that fills the solar system.', a: 'Wind (solar)', category: 'stars' },
      { q: 'The region of space swept clean by a planet\'s gravitational influence along its orbit.', a: 'Wide orbital clearing', category: 'planets' },
      { q: 'The first woman in space, Soviet cosmonaut Valentina Tereshkova, flew on this named mission.', a: 'Woman cosmonaut (Vostok 6)', category: 'history' },
      { q: 'An array of 27 radio telescopes in New Mexico used to image radio sources in deep space.', a: 'Wide array (VLA)', category: 'telescopes' },
      { q: 'A planetary object with its own orbit and gravity but not massive enough to achieve nuclear fusion.', a: 'World without fusion (rogue planet)', category: 'planets' },
      { q: 'The effect predicted by general relativity where spacetime curves around a massive object.', a: 'Warping of spacetime', category: 'physics' },
      { q: 'The process by which rotation causes material in a galaxy to spiral inward over time.', a: 'Winding problem (galactic arms)', category: 'galaxies' },
    ],
    X: [
      { q: 'High-energy electromagnetic radiation used to study neutron stars, black holes, and supernovae remnants.', a: 'X-ray astronomy', category: 'physics' },
      { q: 'NASA\'s flagship X-ray space telescope, named after astrophysicist Subrahmanyan Chandrasekhar.', a: 'X-ray Chandra Observatory', category: 'telescopes' },
      { q: 'An informal nickname for the dwarf planet Eris during its discovery, before formal naming.', a: 'Xena (Eris nickname)', category: 'solar system' },
      { q: 'The ESA X-ray Multi-Mirror satellite that observes X-ray sources including galaxy clusters.', a: 'XMM-Newton telescope', category: 'telescopes' },
      { q: 'A binary star system where a compact object pulls matter from a companion star, emitting X-rays.', a: 'X-ray binary', category: 'stars' },
    ],
    Y: [
      { q: 'The unit of time defined as one complete orbit of Earth around the Sun, approximately 365.25 days.', a: 'Year', category: 'physics' },
      { q: 'China\'s lunar rover, whose name means Jade Rabbit, deployed by Chang\'e 3 in December 2013.', a: 'Yutu rover', category: 'missions' },
      { q: 'The plane used as reference for measuring galactic latitude in the coordinate system of the Milky Way.', a: 'Yearly galactic plane', category: 'physics' },
      { q: 'The angular coordinate measuring distance north or south of the celestial equator.', a: 'Y-axis declination', category: 'physics' },
      { q: 'The Chinese space station module launched in April 2021, forming the core of the CSS.', a: 'Yuan Wang / Tianhe module', category: 'missions' },
    ],
    Z: [
      { q: 'The point on the celestial sphere directly above an observer.', a: 'Zenith', category: 'physics' },
      { q: 'The band of 12 constellations through which the Sun, Moon, and planets appear to move.', a: 'Zodiac', category: 'stars' },
      { q: 'The measure of an element\'s abundance in a star, often expressed relative to iron.', a: 'Zero-point metallicity', category: 'stars' },
      { q: 'The lowest possible temperature at which all molecular motion ceases, equal to −273.15 °C or 0 K.', a: 'Zero absolute temperature', category: 'physics' },
      { q: 'The rate at which redshift increases with distance, described by Hubble\'s constant.', a: 'z (redshift parameter)', category: 'cosmology' },
      { q: 'A class of variable stars that pulsate radially, used to measure cosmic distances.', a: 'Zonal pulsators (Cepheids)', category: 'stars' },
    ],
  },
};
