import type { RawPack } from '../core/packs';

export const spacePack: RawPack = {
  id: 'space-cosmos',
  name: 'Space & Cosmos',
  description: 'Planets, stars, missions and the deep universe.',
  locale: 'en',
  difficulty: 'hard',
  contentRating: 'everyone',
  emoji: '🪐',
  accent: '#5e60ce',
  letters: {
    A: [
      { q: 'The nearest large galaxy to the Milky Way, visible to the naked eye from the Southern Hemisphere.', a: 'Andromeda', category: 'galaxies' },
      { q: 'NASA program that successfully landed humans on the Moon between 1969 and 1972.', a: 'Apollo', category: 'missions' },
      { q: 'A small rocky body orbiting the Sun, found mostly in the belt between Mars and Jupiter.', a: 'Asteroid', category: 'solar system' },
      { q: 'Natural light display in polar skies caused by charged particles interacting with Earth\'s atmosphere.', a: 'Aurora', category: 'physics' },
      { q: 'The point in an orbit where a body is farthest from the Sun.', a: 'Aphelion', category: 'physics' },
      { q: 'The easternmost star in the three-star belt of the constellation Orion, a blue supergiant.', a: 'Alnitak', category: 'stars' },
      { q: 'A class of variable stars used as "standard candles" to measure cosmic distances.', a: 'Asteroseismology', category: 'physics' },
      { q: 'The brightest star in the constellation Boötes and the fourth brightest star in the night sky overall.', a: 'Arcturus', category: 'stars' },
      { q: 'The uppermost layer of Earth\'s atmosphere, beginning around 80 km altitude, where the ISS orbits.', a: 'Thermosphere', category: 'physics' },
      { q: 'Italian astronomer who first used a telescope to observe the moons of Jupiter in 1610.', a: 'Galileo Galilei', category: 'history' },
      { q: 'The angular distance of a celestial object above or below the celestial equator.', a: 'Altitude', category: 'physics' },
      { q: 'The NASA rover that landed in Jezero Crater in February 2021 to seek signs of ancient life on Mars.', a: 'Perseverance', category: 'missions' },
    ],
    B: [
      { q: 'The cosmological event approximately 13.8 billion years ago from which the universe originated.', a: 'Big Bang', category: 'cosmology' },
      { q: 'A region of spacetime where gravity is so strong that nothing, not even light, can escape.', a: 'Black hole', category: 'physics' },
      { q: 'The red supergiant star forming the right shoulder of the constellation Orion.', a: 'Betelgeuse', category: 'stars' },
      { q: 'The process that powers stars by combining hydrogen nuclei into helium and releasing enormous energy.', a: 'Nuclear fusion', category: 'physics' },
      { q: 'The faint glow of microwave radiation that permeates the universe, a remnant of the Big Bang.', a: 'Cosmic microwave background', category: 'cosmology' },
      { q: 'The asteroid that caused a massive extinction event on Earth approximately 66 million years ago.', a: 'Bolide', category: 'solar system' },
      { q: 'The critical radius below which a mass must be compressed to form a black hole, named after a German physicist.', a: 'Schwarzschild radius', category: 'physics' },
      { q: 'A dense cloud of gas and dust in interstellar space where new stars are born.', a: 'Stellar nursery', category: 'stars' },
      { q: 'The two largest impact basins on Mars, Hellas and Argyre, are examples of what feature type.', a: 'Basins', category: 'planets' },
      { q: 'The force per unit area exerted by the weight of a planet\'s atmosphere at its surface.', a: 'Barometric pressure', category: 'physics' },
      { q: 'German-American rocket engineer instrumental in developing the V-2 and later the Saturn V launch vehicle.', a: 'Wernher von Braun', category: 'history' },
      { q: 'The unit of luminosity in which stellar brightness is sometimes expressed, equal to 3.83×10²⁶ watts.', a: 'Bolometric luminosity', category: 'physics' },
    ],
    C: [
      { q: 'An icy body that develops a glowing coma and tail when it passes near the Sun.', a: 'Comet', category: 'solar system' },
      { q: 'A pattern of stars forming a recognizable shape, with 88 officially recognized by the IAU.', a: 'Constellation', category: 'stars' },
      { q: 'The outermost layer of the Sun\'s atmosphere, visible as a white halo during a total solar eclipse.', a: 'Corona', category: 'stars' },
      { q: 'NASA\'s flagship space telescope launched in 1990 that revolutionized observational astronomy with visible-light imaging.', a: 'Hubble Space Telescope', category: 'telescopes' },
      { q: 'A neutron star that emits regular pulses of electromagnetic radiation as it rotates.', a: 'Crab pulsar', category: 'stars' },
      { q: 'A small, extremely dense stellar remnant left after a low-to-medium-mass star sheds its outer layers.', a: 'White dwarf', category: 'stars' },
      { q: 'The inward-directed force that keeps a planet moving in a curved orbit around the Sun.', a: 'Gravity', category: 'physics' },
      { q: 'The distance light travels in one year, approximately 9.46 × 10¹⁵ metres.', a: 'Light-year', category: 'physics' },
      { q: 'Polish astronomer who proposed that Earth orbits the Sun, publishing his heliocentric model in 1543.', a: 'Nicolaus Copernicus', category: 'history' },
      { q: 'Dark, relatively cool regions on the Sun\'s photosphere caused by intense local magnetic fields.', a: 'Sunspots', category: 'stars' },
      { q: 'NASA\'s X-ray space telescope, still operational, named after Indian-American astrophysicist Subrahmanyan Chandrasekhar.', a: 'Chandra X-ray Observatory', category: 'telescopes' },
      { q: 'The point in an orbit where the orbiting body is closest to Earth.', a: 'Perigee', category: 'physics' },
    ],
    D: [
      { q: 'The force whose nature is unknown that is accelerating the expansion of the universe.', a: 'Dark energy', category: 'cosmology' },
      { q: 'The unseen mass that makes up roughly 27% of the universe\'s total energy content.', a: 'Dark matter', category: 'cosmology' },
      { q: 'The angular measurement used to locate stars in the celestial coordinate system, analogous to latitude.', a: 'Declination', category: 'physics' },
      { q: 'The NASA mission that intentionally crashed an impactor into comet Tempel 1 in 2005 to study its interior.', a: 'Deep Impact', category: 'missions' },
      { q: 'A small, extremely dense stellar remnant composed mostly of electron-degenerate matter, the end state of a Sun-like star.', a: 'White dwarf', category: 'stars' },
      { q: 'The fifth largest moon of Saturn, composed mostly of water ice and rock.', a: 'Dione', category: 'solar system' },
      { q: 'A planet that has been removed from the list of full planets by the IAU, like Pluto.', a: 'Dwarf planet', category: 'solar system' },
      { q: 'The expansion of the universe causes light from distant galaxies to shift toward longer, redder wavelengths.', a: 'Doppler redshift', category: 'physics' },
      { q: 'The ratio of an orbit\'s deviation from a perfect circle, where 0 is circular and 1 is parabolic.', a: 'Eccentricity', category: 'physics' },
      { q: 'A faint galaxy that appears as a lens-shaped disk with a central bulge and no spiral arms.', a: 'Lenticular galaxy', category: 'galaxies' },
      { q: 'NASA\'s first successful interplanetary spacecraft, which flew past Venus in 1962.', a: 'Mariner 2', category: 'missions' },
      { q: 'The boundary between a planet\'s day side and night side, dividing light from darkness.', a: 'Terminator', category: 'planets' },
    ],
    E: [
      { q: 'The third planet from the Sun and the only known body in the universe to harbor life.', a: 'Earth', category: 'planets' },
      { q: 'The orbital path that the Sun appears to trace across the sky over the course of a year.', a: 'Ecliptic', category: 'physics' },
      { q: 'The point where the celestial equator intersects the ecliptic, marking the start of spring.', a: 'Equinox', category: 'physics' },
      { q: 'The standard unit of distance in astronomy, equal to the mean distance from Earth to the Sun.', a: 'Astronomical unit', category: 'physics' },
      { q: 'An active moon of Saturn with geysers of water ice erupting from its south polar region.', a: 'Enceladus', category: 'solar system' },
      { q: 'German physicist who derived the mass–energy equivalence formula E = mc².', a: 'Einstein, Albert', category: 'history' },
      { q: 'A dwarf planet in the scattered disc, slightly larger than Pluto and orbiting far beyond Neptune.', a: 'Eris', category: 'solar system' },
      { q: 'The Greek astronomer of the 3rd century BC who first calculated Earth\'s circumference.', a: 'Eratosthenes', category: 'history' },
      { q: 'Short-wavelength radiation in the ultraviolet range emitted intensely by the Sun during solar flares.', a: 'Extreme ultraviolet radiation', category: 'physics' },
      { q: 'A vast spherical cloud of comets thought to surround the solar system at distances up to 100,000 AU.', a: 'Oort Cloud', category: 'solar system' },
      { q: 'A glowing shell of gas expelled by a dying low-mass star, surrounding its remnant white dwarf core.', a: 'Planetary nebula', category: 'stars' },
      { q: 'A type of binary star system where one star periodically passes in front of the other as seen from Earth.', a: 'Eclipsing binary', category: 'stars' },
    ],
    F: [
      { q: 'The nuclear reaction that powers stars, where lighter nuclei combine to form heavier ones releasing energy.', a: 'Fusion', category: 'physics' },
      { q: 'A bright streak of light caused by a meteoroid burning up in Earth\'s atmosphere.', a: 'Meteor', category: 'solar system' },
      { q: 'The measure of brightness of a celestial object as seen from Earth.', a: 'Apparent magnitude', category: 'physics' },
      { q: 'A sudden, intense burst of energy on the Sun\'s surface associated with intense magnetic activity.', a: 'Solar flare', category: 'stars' },
      { q: 'The five equilibrium points in a two-body gravitational system where a small object can maintain a stable position.', a: 'Lagrange points', category: 'physics' },
      { q: 'The ratio of focal length to lens diameter, a measure of a telescope\'s light-gathering speed.', a: 'Focal ratio', category: 'telescopes' },
      { q: 'The era following the Big Bang before the first stars formed, known as the cosmic dark ages.', a: 'First light era', category: 'cosmology' },
      { q: 'Italian-American physicist who built the first nuclear reactor and contributed to early rocket propulsion theory.', a: 'Fermi, Enrico', category: 'history' },
      { q: 'The temporary brightening of a distant star caused by the gravitational lensing effect of a closer object passing in front of it.', a: 'Gravitational microlensing', category: 'physics' },
      { q: 'The outermost atmospheric layer of a planet, from which gas molecules can escape into space.', a: 'Exosphere', category: 'physics' },
      { q: 'Thin, bright streamers extending from the solar corona, shaped by the Sun\'s magnetic field lines.', a: 'Coronal streamers', category: 'stars' },
    ],
    G: [
      { q: 'The fundamental force of attraction between masses, described by Newton and refined by Einstein.', a: 'Gravity', category: 'physics' },
      { q: 'A massive system of stars, gas, dust, and dark matter held together by gravity.', a: 'Galaxy', category: 'galaxies' },
      { q: 'The largest planet in the solar system, known for its Great Red Spot storm.', a: 'Jupiter', category: 'planets' },
      { q: 'Italian astronomer credited with first systematic use of the telescope for astronomical observation.', a: 'Galileo Galilei', category: 'history' },
      { q: 'NASA\'s spacecraft that orbited Jupiter from 1995 to 2003 and deployed an atmospheric probe.', a: 'Galileo spacecraft', category: 'missions' },
      { q: 'Jupiter\'s largest moon, the biggest moon in the solar system, with its own magnetic field.', a: 'Ganymede', category: 'solar system' },
      { q: 'Waves in the fabric of spacetime produced by accelerating masses, first detected in 2015.', a: 'Gravitational waves', category: 'physics' },
      { q: 'A dense, roughly spherical cluster of hundreds of thousands of old stars orbiting a galaxy\'s core.', a: 'Globular cluster', category: 'stars' },
      { q: 'The redshift of light escaping a strong gravitational field, predicted by general relativity.', a: 'Gravitational redshift', category: 'physics' },
      { q: 'A NASA mission consisting of two spacecraft that mapped Earth\'s gravitational field from 2011 to 2012.', a: 'GRAIL mission', category: 'missions' },
      { q: 'The process by which matter accumulates on a massive body, such as a black hole or forming star.', a: 'Gas accretion', category: 'physics' },
      { q: 'The angular measure of arc equal to one sixtieth of a degree, used in precise positional astronomy.', a: 'Arcminute', category: 'physics' },
    ],
    H: [
      { q: 'The most abundant element in the universe and the primary fuel for stellar nuclear fusion.', a: 'Hydrogen', category: 'physics' },
      { q: 'NASA\'s space telescope launched in 1990 that has transformed our understanding of the universe.', a: 'Hubble Space Telescope', category: 'telescopes' },
      { q: 'American astronomer who discovered that galaxies are moving away from us and that the universe is expanding.', a: 'Hubble, Edwin', category: 'history' },
      { q: 'The zone around a star where liquid water could theoretically exist on a planet\'s surface.', a: 'Habitable zone', category: 'planets' },
      { q: 'The boundary of the observable universe beyond which expansion causes recession at the speed of light.', a: 'Hubble horizon', category: 'cosmology' },
      { q: 'The second-most common element in the universe, produced in the cores of massive stars.', a: 'Helium', category: 'physics' },
      { q: 'The NASA spacecraft that performed the first close flyby of Pluto in July 2015.', a: 'New Horizons', category: 'missions' },
      { q: 'The point on the celestial sphere directly above an observer, at 90 degrees altitude.', a: 'Zenith', category: 'physics' },
      { q: 'A cool, luminous star that has expanded after exhausting hydrogen in its core.', a: 'Red giant', category: 'stars' },
      { q: 'The ESA astrometry mission that precisely measured positions and proper motions of over one billion stars.', a: 'Gaia', category: 'missions' },
      { q: 'The long-lived anticyclonic storm on Jupiter that has persisted for at least 350 years.', a: 'Great Red Spot', category: 'planets' },
      { q: 'The NASA mission that intentionally impacted the Moon\'s south pole in 2009 to confirm the presence of water ice.', a: 'LCROSS', category: 'missions' },
    ],
    I: [
      { q: 'The volcanically most active body in the solar system, a moon of Jupiter.', a: 'Io', category: 'solar system' },
      { q: 'A large habitable space station orbiting Earth at approximately 400 km altitude.', a: 'International Space Station', category: 'missions' },
      { q: 'The force that keeps an object in uniform motion unless acted upon by another force.', a: 'Inertia', category: 'physics' },
      { q: 'Radiation with wavelengths longer than visible light, used to study cool stars and dust clouds.', a: 'Infrared radiation', category: 'physics' },
      { q: 'NASA\'s space telescope launched in 2003 to observe the universe in infrared light.', a: 'Spitzer Space Telescope', category: 'telescopes' },
      { q: 'The tilt of a planet\'s rotational axis relative to its orbital plane.', a: 'Axial tilt', category: 'planets' },
      { q: 'The extremely rapid expansion of the universe in the first fractions of a second after the Big Bang.', a: 'Cosmic inflation', category: 'cosmology' },
      { q: 'An electrically charged atom or molecule formed by the loss or gain of electrons.', a: 'Ion', category: 'physics' },
      { q: 'The process by which gas molecules lose electrons and become charged, common in stellar atmospheres.', a: 'Ionization', category: 'physics' },
      { q: 'A dense cloud of interstellar gas and dust that may eventually collapse under gravity to form new stars.', a: 'Molecular cloud', category: 'stars' },
      { q: 'The layer between a planet\'s crust and core, where convection currents drive geological activity.', a: 'Mantle', category: 'planets' },
      { q: 'The power of electromagnetic radiation incident on a surface per unit area, used to measure solar output.', a: 'Irradiance', category: 'physics' },
    ],
    J: [
      { q: 'The largest planet in the solar system, with a mass more than twice all other planets combined.', a: 'Jupiter', category: 'planets' },
      { q: 'NASA\'s spacecraft currently orbiting Jupiter to study its atmosphere and magnetic field.', a: 'Juno spacecraft', category: 'missions' },
      { q: 'NASA\'s next-generation space telescope launched in December 2021, observing in infrared.', a: 'James Webb Space Telescope', category: 'telescopes' },
      { q: 'The open star cluster NGC 4755 in the constellation Crux, nicknamed for its colourful gems visible through a small telescope.', a: 'Jewel Box cluster', category: 'stars' },
      { q: 'The point in Earth\'s orbit where it is closest to the Sun, occurring around January 3.', a: 'January perihelion', category: 'physics' },
      { q: 'British astronomer who discovered Uranus in 1781 and catalogued thousands of nebulae and double stars.', a: 'William Herschel', category: 'history' },
    ],
    K: [
      { q: 'The region of the solar system beyond Neptune\'s orbit, home to Pluto and many icy bodies.', a: 'Kuiper Belt', category: 'solar system' },
      { q: 'NASA\'s space telescope, now retired, that discovered thousands of exoplanets by detecting transits.', a: 'Kepler Space Telescope', category: 'telescopes' },
      { q: 'German astronomer who derived the three laws of planetary motion in the early 17th century.', a: 'Kepler, Johannes', category: 'history' },
      { q: 'The temperature scale used in science where 0 represents absolute zero, −273.15 °C.', a: 'Kelvin scale', category: 'physics' },
      { q: 'A neutron star with an exceptionally strong magnetic field, up to 10¹⁵ gauss.', a: 'Magnetar', category: 'stars' },
      { q: 'A dwarf planet discovered in 2002 in the Kuiper Belt with a diameter of about 1,110 km, also known as 50000 Quaoar.', a: 'Quaoar', category: 'solar system' },
    ],
    L: [
      { q: 'The distance light travels in one year, approximately 9.46 × 10¹² kilometres.', a: 'Light-year', category: 'physics' },
      { q: 'The brightness of a star as measured at its surface, independent of distance.', a: 'Luminosity', category: 'stars' },
      { q: 'American astronaut who became the first person to walk on the Moon on 20 July 1969 as commander of Apollo 11.', a: 'Neil Armstrong', category: 'history' },
      { q: 'Points in space where the gravitational forces of two large bodies and the centrifugal force balance.', a: 'Lagrange points', category: 'physics' },
      { q: 'The first artificial Earth satellite, launched by the Soviet Union in October 1957.', a: 'Sputnik 1', category: 'missions' },
      { q: 'The ESA–NASA mission designed to detect gravitational waves from space using laser interferometry.', a: 'LISA mission', category: 'missions' },
      { q: 'Rings of dust and ice orbiting a giant planet such as Saturn or Uranus.', a: 'Planetary rings', category: 'planets' },
      { q: 'The region around a planet dominated by its own magnetic field, shielding it from the solar wind.', a: 'Magnetosphere', category: 'physics' },
      { q: 'The closest star to the Sun, part of the Alpha Centauri system, 4.24 light-years away.', a: 'Proxima Centauri', category: 'stars' },
      { q: 'The Italian–French mathematician who identified the five equilibrium points in two-body celestial mechanics.', a: 'Lagrange, Joseph-Louis', category: 'history' },
      { q: 'The outermost visible layer of the Sun from which light and energy radiate into space.', a: 'Photosphere', category: 'stars' },
      { q: 'A type of optical telescope that uses mirrors instead of lenses to gather and focus light.', a: 'Reflecting telescope', category: 'telescopes' },
    ],
    M: [
      { q: 'The fourth planet from the Sun, known as the Red Planet due to iron oxide on its surface.', a: 'Mars', category: 'planets' },
      { q: 'A small rocky or metallic body in space; called a meteor when entering Earth\'s atmosphere.', a: 'Meteoroid', category: 'solar system' },
      { q: 'The galaxy containing our solar system, a barred spiral with roughly 200–400 billion stars.', a: 'Milky Way', category: 'galaxies' },
      { q: 'Earth\'s only natural satellite, the fifth largest moon in the solar system.', a: 'Moon', category: 'solar system' },
      { q: 'An extremely bright meteor, brighter than Venus, that may produce a sonic boom and drop meteorites.', a: 'Fireball', category: 'solar system' },
      { q: 'An exceptionally bright meteor that may produce a sonic boom and drop meteorites.', a: 'Meteor fireball', category: 'solar system' },
      { q: 'The first planet from the Sun, with a surface temperature ranging from −180 °C to 430 °C.', a: 'Mercury', category: 'planets' },
      { q: 'The lunar phase where the near side of the Moon is fully illuminated as seen from Earth.', a: 'Full moon', category: 'solar system' },
      { q: 'NASA\'s robotic mission that orbited Mercury from 2011 to 2015.', a: 'MESSENGER mission', category: 'missions' },
      { q: 'The mass per unit volume of a celestial body, which for Earth is about 5,514 kg/m³.', a: 'Mean density', category: 'planets' },
      { q: 'A cloud of interstellar gas and dust, often the site of star formation or the remnant of a stellar explosion.', a: 'Nebula', category: 'stars' },
      { q: 'A unit of stellar distance equal to 3.26 light-years, defined by a parallax angle of one arcsecond.', a: 'Parsec', category: 'physics' },
    ],
    N: [
      { q: 'The eighth and farthest planet from the Sun in the solar system.', a: 'Neptune', category: 'planets' },
      { q: 'An extremely dense stellar remnant formed when a massive star collapses; composed mostly of neutrons.', a: 'Neutron star', category: 'stars' },
      { q: 'A bright cloud of gas and dust in space, often surrounding a newly formed or dying star.', a: 'Nebula', category: 'stars' },
      { q: 'The dwarf planet that the New Horizons spacecraft flew past in July 2015, revealing its heart-shaped plain.', a: 'Pluto', category: 'missions' },
      { q: 'English physicist whose three laws of motion and law of universal gravitation founded classical mechanics.', a: 'Newton, Isaac', category: 'history' },
      { q: 'The hemisphere of the Moon that permanently faces away from Earth, never visible from the ground.', a: 'Far side', category: 'planets' },
      { q: 'The point in the sky directly above the North Celestial Pole, near the star Polaris.', a: 'North celestial pole', category: 'physics' },
      { q: 'The synthesis of elements heavier than hydrogen and helium inside stars.', a: 'Stellar nucleosynthesis', category: 'physics' },
      { q: 'An active galaxy with an extremely luminous core powered by a supermassive black hole.', a: 'Active galactic nucleus', category: 'galaxies' },
      { q: 'The faint outermost ring of Neptune discovered by Voyager 2 in 1989.', a: 'Neptune\'s outer rings', category: 'planets' },
      { q: 'NASA\'s orbital mission around the asteroid Eros from 2000 to 2001.', a: 'NEAR Shoemaker mission', category: 'missions' },
      { q: 'A pair of small, irregular galaxies that act as satellite galaxies of the Milky Way, visible from the Southern Hemisphere.', a: 'Magellanic Cloud', category: 'galaxies' },
    ],
    O: [
      { q: 'The path followed by one celestial body around another under the influence of gravity.', a: 'Orbit', category: 'physics' },
      { q: 'A vast spherical cloud of comets surrounding the solar system at distances of 2,000–100,000 AU.', a: 'Oort Cloud', category: 'solar system' },
      { q: 'The constellation known as the Hunter, containing the bright stars Betelgeuse and Rigel.', a: 'Orion', category: 'stars' },
      { q: 'A giant molecular cloud and stellar nursery 1,344 light-years from Earth, visible in Orion.', a: 'Orion Nebula', category: 'stars' },
      { q: 'A planet orbiting a star other than the Sun.', a: 'Exoplanet', category: 'planets' },
      { q: 'The point of closest approach in an orbit around Earth, where orbital velocity is highest.', a: 'Orbital perigee', category: 'physics' },
      { q: 'The time a body takes to complete one full orbit around another object.', a: 'Orbital period', category: 'physics' },
      { q: 'NASA\'s spacecraft that orbited Saturn from 2004 to 2017 in partnership with ESA.', a: 'Cassini', category: 'missions' },
      { q: 'The angular diameter of a celestial object as seen from Earth, a measure of apparent size.', a: 'Angular diameter', category: 'physics' },
      { q: 'The study of light and other electromagnetic radiation to understand astronomical objects.', a: 'Observational astronomy', category: 'physics' },
    ],
    P: [
      { q: 'A large, spherical body in orbit around the Sun that has cleared the neighbourhood around its orbit.', a: 'Planet', category: 'planets' },
      { q: 'The closest planet to the Sun, with a diameter about 38% that of Earth.', a: 'Mercury', category: 'planets' },
      { q: 'The dwarf planet reclassified by the IAU in 2006, formerly the ninth planet.', a: 'Pluto', category: 'solar system' },
      { q: 'The point in an orbit where the orbiting body is closest to the Sun.', a: 'Perihelion', category: 'physics' },
      { q: 'A rotating neutron star that emits beams of electromagnetic radiation.', a: 'Pulsar', category: 'stars' },
      { q: 'A glowing shell of gas expelled by a dying low-mass star around its remnant white dwarf core.', a: 'Planetary nebula', category: 'stars' },
      { q: 'A unit of stellar distance equal to 3.26 light-years, defined by a parallax angle of one arcsecond.', a: 'Parsec', category: 'physics' },
      { q: 'The photon-emitting outermost layer of the Sun, where the solar spectrum originates.', a: 'Photosphere', category: 'stars' },
      { q: 'A disk of gas and dust surrounding a newly formed star from which planets eventually form.', a: 'Protoplanetary disk', category: 'planets' },
      { q: 'The nearest star to Earth other than the Sun, at a distance of 4.24 light-years.', a: 'Proxima Centauri', category: 'stars' },
      { q: 'NASA\'s twin spacecraft launched in 1977 that performed the first flybys of Jupiter, Saturn, Uranus, and Neptune.', a: 'Voyager', category: 'missions' },
      { q: 'The North Star, located within one degree of the north celestial pole, in Ursa Minor.', a: 'Polaris', category: 'stars' },
    ],
    Q: [
      { q: 'An extremely luminous active galactic nucleus powered by a supermassive black hole, visible across billions of light-years.', a: 'Quasar', category: 'galaxies' },
      { q: 'A compact group of five galaxies in Pegasus, studied extensively by the Hubble and James Webb telescopes.', a: 'Stephan\'s Quintet', category: 'galaxies' },
      { q: 'The portion of the electromagnetic spectrum between radio waves and visible light, used by microwave telescopes.', a: 'Radio waves', category: 'physics' },
      { q: 'A dwarf planet in the Kuiper Belt, discovered in 2002, with a diameter of about 1,110 km.', a: 'Quaoar', category: 'solar system' },
      { q: 'The elementary particle and quantum of electromagnetic radiation, carrying energy proportional to its frequency.', a: 'Photon', category: 'physics' },
      { q: 'A state of matter thought to exist in the core of neutron stars, consisting of unconfined quarks.', a: 'Quark–gluon plasma', category: 'physics' },
    ],
    R: [
      { q: 'The expansion of the universe causes light from distant galaxies to shift toward longer, redder wavelengths.', a: 'Redshift', category: 'cosmology' },
      { q: 'A spinning neutron star emitting beams of radio waves detected as regular pulses on Earth.', a: 'Radio pulsar', category: 'stars' },
      { q: 'The fourth planet from the Sun, also called the Red Planet.', a: 'Mars', category: 'planets' },
      { q: 'A giant star that has expanded and cooled after exhausting hydrogen in its core.', a: 'Red giant', category: 'stars' },
      { q: 'The brightest star in the constellation Orion, a blue-white supergiant about 860 light-years away.', a: 'Rigel', category: 'stars' },
      { q: 'A neutron star with an exceptionally strong magnetic field, up to 10¹⁵ gauss, that powers explosive X-ray bursts.', a: 'Magnetar', category: 'stars' },
      { q: 'The time a planet takes to complete one full orbit around the Sun.', a: 'Orbital period', category: 'physics' },
      { q: 'NASA\'s Mars rover that operated from 2004 to 2018, far exceeding its planned 90-day mission.', a: 'Opportunity', category: 'missions' },
      { q: 'The intrinsic power output of a star expressed in units of the Sun\'s total power output.', a: 'Solar luminosity', category: 'stars' },
      { q: 'The minimum speed an object must reach to escape a planet\'s gravitational pull without further propulsion.', a: 'Escape velocity', category: 'physics' },
      { q: 'The cosmic epoch when ultraviolet light from the first stars ionized the neutral hydrogen that had filled the universe.', a: 'Reionization era', category: 'cosmology' },
    ],
    S: [
      { q: 'The sixth planet from the Sun, famous for its extensive ring system made of ice and rock.', a: 'Saturn', category: 'planets' },
      { q: 'The nearest star to Earth, a middle-aged G-type main-sequence star at the center of our solar system.', a: 'Sun', category: 'stars' },
      { q: 'The first artificial satellite, launched by the Soviet Union on October 4, 1957.', a: 'Sputnik 1', category: 'missions' },
      { q: 'The explosion of a massive star at the end of its life, briefly outshining an entire galaxy.', a: 'Supernova', category: 'stars' },
      { q: 'The largest and most energetic type of star that has evolved past the main sequence.', a: 'Supergiant star', category: 'stars' },
      { q: 'A concentrated disk of accreting matter surrounding a black hole or neutron star.', a: 'Accretion disk', category: 'physics' },
      { q: 'The scientific study of celestial objects, phenomena, and the universe as a whole.', a: 'Astronomy', category: 'physics' },
      { q: 'The spacecraft launched in 1977 that became the first human-made object to enter interstellar space.', a: 'Voyager 1', category: 'missions' },
      { q: 'A dark patch visible on the Sun\'s photosphere caused by strong local magnetic fields.', a: 'Sunspot', category: 'stars' },
      { q: 'A graph plotting stars by luminosity against surface temperature, used to classify stellar evolution.', a: 'Hertzsprung-Russell diagram', category: 'stars' },
      { q: 'The technique of splitting starlight into a spectrum to determine a star\'s composition and velocity.', a: 'Spectroscopy', category: 'physics' },
      { q: 'A large barred spiral galaxy about 2.5 million light-years away, the nearest spiral galaxy to the Milky Way.', a: 'Andromeda Galaxy', category: 'galaxies' },
    ],
    T: [
      { q: 'The largest moon of Saturn, the only moon in the solar system with a dense atmosphere.', a: 'Titan', category: 'solar system' },
      { q: 'The world\'s largest single-aperture optical telescope, located in the Canary Islands.', a: 'Gran Telescopio Canarias', category: 'telescopes' },
      { q: 'The phenomenon whereby a distant star briefly brightens when a planet passes between it and Earth.', a: 'Transit method', category: 'planets' },
      { q: 'One of the two moments each year when the length of day and night are approximately equal worldwide.', a: 'Equinox', category: 'physics' },
      { q: 'A pair of forces that cause rotation, acting on a gyroscope or planet.', a: 'Torque', category: 'physics' },
      { q: 'The temperature of the cosmic microwave background radiation today, approximately 2.725 Kelvin.', a: 'Cosmic microwave background temperature', category: 'cosmology' },
      { q: 'An instrument that collects electromagnetic radiation from space to study astronomical objects.', a: 'Telescope', category: 'telescopes' },
      { q: 'The elongated region of a planet\'s magnetosphere stretched away from the Sun by the solar wind.', a: 'Magnetotail', category: 'physics' },
      { q: 'A sudden, intense release of magnetic energy on the Sun that sends charged particles toward Earth.', a: 'Solar flare', category: 'stars' },
      { q: 'The gravitational deformation of a celestial body by the gravity of a nearby body.', a: 'Tidal force', category: 'physics' },
      { q: 'The angle between a planet\'s equatorial plane and its orbital plane around the Sun.', a: 'Axial inclination', category: 'planets' },
      { q: 'The ESA lander that touched down on comet 67P in November 2014, the first spacecraft to land on a comet.', a: 'Philae', category: 'missions' },
    ],
    U: [
      { q: 'The seventh planet from the Sun, notable for rotating on its side with an axial tilt of 98 degrees.', a: 'Uranus', category: 'planets' },
      { q: 'The totality of all existing matter, energy, space, and time, estimated to be 13.8 billion years old.', a: 'Universe', category: 'cosmology' },
      { q: 'The dark shadow cast by a body when it completely blocks light from a source.', a: 'Umbra', category: 'physics' },
      { q: 'High-energy electromagnetic radiation with wavelengths shorter than visible light but longer than X-rays.', a: 'Ultraviolet radiation', category: 'physics' },
      { q: 'The phase of the early universe, about 380,000 years after the Big Bang, when electrons combined with protons to form neutral hydrogen.', a: 'Recombination', category: 'cosmology' },
      { q: 'A type of dwarf galaxy, the smallest and faintest class, found orbiting larger galaxies like the Milky Way.', a: 'Ultra-faint dwarf galaxy', category: 'galaxies' },
    ],
    V: [
      { q: 'The second planet from the Sun, the hottest in the solar system due to its thick CO₂ atmosphere.', a: 'Venus', category: 'planets' },
      { q: 'NASA\'s twin spacecraft launched in 1977, which completed the first grand tour of the outer planets.', a: 'Voyager 1 and 2', category: 'missions' },
      { q: 'The constellation in which the bright star Spica is located.', a: 'Virgo', category: 'stars' },
      { q: 'The fifth brightest star in the night sky, located in the constellation Lyra and used as a standard reference star for brightness.', a: 'Vega', category: 'stars' },
      { q: 'The speed of light in a vacuum, approximately 299,792 kilometres per second.', a: 'Speed of light', category: 'physics' },
    ],
    W: [
      { q: 'A hypothetical tunnel through spacetime connecting two distant points, predicted by general relativity.', a: 'Wormhole', category: 'physics' },
      { q: 'The time a planet takes to orbit the Sun once, equal to 365.25 days for Earth.', a: 'Orbital year', category: 'physics' },
      { q: 'The most energetic form of electromagnetic radiation, with wavelengths shorter than X-rays, emitted in nuclear reactions.', a: 'Gamma ray', category: 'physics' },
      { q: 'A dense white-hot stellar remnant, the compressed core of a dead low-mass star.', a: 'White dwarf', category: 'stars' },
      { q: 'The continuous stream of charged particles, mostly protons and electrons, emitted by the Sun.', a: 'Solar wind', category: 'stars' },
      { q: 'The requirement that a planet must have gravitationally swept clear its orbital neighbourhood to be classified as a full planet.', a: 'Orbital clearing', category: 'planets' },
      { q: 'The Soviet mission in June 1963 that carried the first woman into space.', a: 'Vostok 6', category: 'history' },
      { q: 'A system of 27 radio telescopes in New Mexico used to image radio sources in deep space.', a: 'Very Large Array', category: 'telescopes' },
      { q: 'A planet that has been ejected from its solar system and drifts through space without orbiting any star.', a: 'Rogue planet', category: 'planets' },
      { q: 'The effect predicted by general relativity where spacetime curves in the presence of a massive object.', a: 'Warping of spacetime', category: 'physics' },
      { q: 'The tendency of spiral arms to wind tighter and tighter over time, a puzzle in galactic dynamics.', a: 'Winding problem', category: 'galaxies' },
    ],
    X: [
      { q: 'High-energy electromagnetic radiation used to study neutron stars, black holes, and supernova remnants.', a: 'X-ray astronomy', category: 'physics' },
      { q: 'NASA\'s flagship X-ray space telescope, named after astrophysicist Subrahmanyan Chandrasekhar.', a: 'Chandra X-ray Observatory', category: 'telescopes' },
      { q: 'The informal nickname given to the dwarf planet Eris during its discovery before it was formally named.', a: 'Xena', category: 'solar system' },
      { q: 'The ESA X-ray Multi-Mirror satellite that observes X-ray sources including galaxy clusters.', a: 'XMM-Newton telescope', category: 'telescopes' },
      { q: 'A binary star system where a compact object pulls matter from a companion star, emitting X-rays.', a: 'X-ray binary', category: 'stars' },
    ],
    Y: [
      { q: 'The unit of time defined as one complete orbit of Earth around the Sun, approximately 365.25 days.', a: 'Year', category: 'physics' },
      { q: 'China\'s lunar rover, whose name means Jade Rabbit, deployed by Chang\'e 3 in December 2013.', a: 'Yutu rover', category: 'missions' },
      { q: 'The reference plane used for measuring galactic latitude in the coordinate system centred on the Milky Way.', a: 'Galactic plane', category: 'physics' },
      { q: 'The angular coordinate in the equatorial system that measures a star\'s position north or south of the celestial equator.', a: 'Declination', category: 'physics' },
      { q: 'The core module of China\'s space station launched in April 2021, around which the CSS is built.', a: 'Tianhe', category: 'missions' },
    ],
    Z: [
      { q: 'The point on the celestial sphere directly above an observer.', a: 'Zenith', category: 'physics' },
      { q: 'The band of 12 constellations through which the Sun, Moon, and planets appear to move.', a: 'Zodiac', category: 'stars' },
      { q: 'A measure of the proportion of elements heavier than helium in a star, often expressed relative to the Sun.', a: 'Metallicity', category: 'stars' },
      { q: 'The lowest possible temperature, −273.15 °C or 0 K, at which all molecular motion ceases.', a: 'Absolute zero', category: 'physics' },
      { q: 'The dimensionless quantity astronomers use to measure how much a galaxy\'s light has been redshifted by cosmic expansion.', a: 'Redshift parameter', category: 'cosmology' },
      { q: 'A class of pulsating variable stars whose regular period–luminosity relationship makes them reliable distance markers.', a: 'Cepheid variables', category: 'stars' },
    ],
  },
};
