import type { RawPack } from '../core/packs';

export const superheroesMediumPack: RawPack = {
  id: 'superheroes-medium',
  name: 'Superheroes & Comics · Medium',
  description: 'Deeper Marvel + DC lore, comics history and villains.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🦹',
  accent: '#991b1b',
  letters: {
    A: [
      { q: 'Arthur Curry, DC\'s trident-wielding king of the seas, played by Jason Momoa.', a: 'Aquaman' },
      { q: 'The shrinking hero suit created by Hank Pym and later worn by ex-thief Scott Lang.', a: 'Ant-Man' },
      { q: 'Earth\'s Mightiest Heroes, the Marvel super-team that first assembled in 1963.', a: 'Avengers', alt: ['The Avengers'] },
      { q: 'Warren Worthington III, the founding X-Man with giant feathered wings.', a: 'Angel' },
      { q: 'Thor\'s golden home realm, connected to Earth by the Bifrost.', a: 'Asgard' },
      { q: 'The kindly widow who raised Peter Parker in Queens.', a: 'Aunt May', alt: ['May Parker'] },
      { q: 'The anthology comic whose 1962 issue number 15 introduced Spider-Man.', a: 'Amazing Fantasy' },
      { q: 'Bruce Wayne\'s loyal butler and lifelong father figure.', a: 'Alfred Pennyworth', alt: ['Alfred'] },
      { q: 'En Sabah Nur, the ancient Egyptian-born mutant villain of the X-Men.', a: 'Apocalypse' },
      { q: 'The sunken ocean kingdom ruled by Namor in Marvel comics.', a: 'Atlantis' },
    ],
    B: [
      { q: 'Gotham\'s Caped Crusader, also called the Dark Knight.', a: 'Batman' },
      { q: 'The long-uncredited writer who co-created the Dark Knight with Bob Kane.', a: 'Bill Finger' },
      { q: 'The scientist who becomes the Hulk after a gamma bomb accident.', a: 'Bruce Banner' },
      { q: 'T\'Challa\'s vibranium-suited hero mantle, protector of Wakanda.', a: 'Black Panther' },
      { q: 'Natasha Romanoff\'s Avenger codename.', a: 'Black Widow' },
      { q: 'Steve Rogers\' childhood best friend, brainwashed into a Hydra assassin.', a: 'Bucky Barnes', alt: ['Bucky'] },
      { q: 'The forensic scientist struck by lightning in 1956 who became the Flash.', a: 'Barry Allen' },
      { q: 'The masked Gotham strongman pumped full of a super-steroid who snapped the Dark Knight\'s spine.', a: 'Bane' },
      { q: 'Barbara Gordon\'s caped Gotham crime-fighting identity.', a: 'Batgirl' },
      { q: 'Marvel\'s half-vampire vampire hunter, played on film by Wesley Snipes.', a: 'Blade' },
      { q: 'Superman\'s imperfect chalk-white duplicate who speaks in opposites.', a: 'Bizarro' },
      { q: 'The Dark Knight\'s armored signature car.', a: 'Batmobile' },
    ],
    C: [
      { q: 'Steve Rogers, the star-spangled super-soldier with an indestructible shield.', a: 'Captain America' },
      { q: 'Carol Danvers\' cosmic-powered alter ego, played by Brie Larson.', a: 'Captain Marvel' },
      { q: 'Selina Kyle, Gotham\'s whip-cracking master burglar.', a: 'Catwoman' },
      { q: 'The wheelchair-using telepath who founded the X-Men, full name.', a: 'Charles Xavier', alt: ['Professor X'] },
      { q: 'The actor who carried the shield as Steve Rogers in the MCU.', a: 'Chris Evans' },
      { q: 'The Australian actor who swings the hammer as the God of Thunder on screen.', a: 'Chris Hemsworth' },
      { q: 'X-Men field leader Scott Summers, whose eyes fire ruby optic blasts.', a: 'Cyclops' },
      { q: 'Superman\'s mild-mannered reporter alter ego.', a: 'Clark Kent' },
      { q: 'Russian X-Man Piotr Rasputin, who turns his body into organic steel.', a: 'Colossus' },
      { q: 'Leonard Snart, the Flash\'s ice-gun-wielding rogue.', a: 'Captain Cold' },
      { q: 'Nathan Summers, the time-traveling mutant soldier who partners with Deadpool in his second film.', a: 'Cable' },
      { q: 'The actor who portrayed T\'Challa on the big screen until 2020.', a: 'Chadwick Boseman' },
    ],
    D: [
      { q: 'Matt Murdock, the blind guardian of Hell\'s Kitchen.', a: 'Daredevil' },
      { q: 'Wade Wilson, the fourth-wall-breaking Merc with a Mouth.', a: 'Deadpool' },
      { q: 'Marvel\'s Sorcerer Supreme, a former neurosurgeon played by Benedict Cumberbatch.', a: 'Doctor Strange', alt: ['Dr Strange', 'Stephen Strange'] },
      { q: 'Victor, the armored Latverian monarch and arch-enemy of the Fantastic Four.', a: 'Doctor Doom', alt: ['Dr Doom'] },
      { q: 'The stone-faced tyrant of Apokolips who seeks the Anti-Life Equation.', a: 'Darkseid' },
      { q: 'The Metropolis newspaper that employs Clark Kent and Lois Lane.', a: 'Daily Planet', alt: ['The Daily Planet'] },
      { q: 'The publisher of Superman, Batman and Wonder Woman.', a: 'DC Comics', alt: ['DC'] },
      { q: 'The long-running series whose 27th issue introduced Batman in 1939.', a: 'Detective Comics' },
      { q: 'Otto, the Spider-Man arch-foe wielding four mechanical arms.', a: 'Doctor Octopus', alt: ['Doc Ock'] },
      { q: 'The full name of Batman\'s first sidekick, once a circus acrobat.', a: 'Dick Grayson' },
      { q: 'The spiked gray monster that killed Superman in a famous 1992 storyline.', a: 'Doomsday' },
      { q: 'The literal-minded, knife-loving Guardian played by Dave Bautista.', a: 'Drax' },
    ],
    E: [
      { q: 'Marvel\'s sai-wielding Greek assassin, Daredevil\'s great love.', a: 'Elektra' },
      { q: 'The 2021 MCU film about ageless protectors created by the Celestials.', a: 'Eternals' },
      { q: 'The living planet revealed as Peter Quill\'s father in Guardians of the Galaxy Vol. 2.', a: 'Ego' },
      { q: 'The civilian name the X-Men films give to Magneto.', a: 'Erik Lehnsherr' },
      { q: 'The Britain-based Marvel super-team co-founded by Captain Britain and Nightcrawler.', a: 'Excalibur' },
      { q: 'The Hellfire Club\'s telepathic White Queen, who can turn her skin to living diamond.', a: 'Emma Frost' },
      { q: 'Max Dillon, the Spider-Man villain who hurls living lightning.', a: 'Electro' },
      { q: 'The journalist who bonds with a hostile black alien symbiote.', a: 'Eddie Brock' },
    ],
    F: [
      { q: 'Marvel\'s first family, transformed by cosmic rays on a 1961 space flight.', a: 'Fantastic Four' },
      { q: 'DC\'s Scarlet Speedster, the fastest man alive.', a: 'Flash', alt: ['The Flash'] },
      { q: 'Sam Wilson\'s winged codename before he inherited the shield.', a: 'Falcon', alt: ['The Falcon'] },
      { q: 'The real name of Marvel\'s skull-chested one-man-army vigilante.', a: 'Frank Castle' },
      { q: 'Superman\'s crystalline Arctic hideaway.', a: 'Fortress of Solitude' },
      { q: 'Loki\'s towering blue birth race from the icy realm of Jotunheim.', a: 'Frost Giants' },
      { q: 'The DC nuclear hero with a blazing head, formed when two people merge into one body.', a: 'Firestorm' },
      { q: 'The reality-warping mutant son of Reed and Sue in the Fantastic Four.', a: 'Franklin Richards' },
    ],
    G: [
      { q: 'Hal Jordan\'s emerald-ring hero identity, part of an intergalactic police corps.', a: 'Green Lantern' },
      { q: 'The glider-riding, pumpkin-bomb-hurling Spider-Man arch-villain.', a: 'Green Goblin' },
      { q: 'The gargoyle-studded, crime-ridden home city of Batman.', a: 'Gotham City', alt: ['Gotham'] },
      { q: 'The green-skinned adopted daughter of Thanos, called the deadliest woman in the galaxy.', a: 'Gamora' },
      { q: 'The Guardians\' gentle walking tree, who says only one three-word phrase.', a: 'Groot' },
      { q: 'Peter Parker\'s first great love, who fell from a New York bridge.', a: 'Gwen Stacy' },
      { q: 'Johnny Blaze, the flaming-skulled spirit of vengeance on a motorcycle.', a: 'Ghost Rider' },
      { q: 'Oliver Queen\'s hooded archer identity, defender of Star City.', a: 'Green Arrow' },
      { q: 'The planet-devouring cosmic giant whose arrival is announced by a chrome herald.', a: 'Galactus' },
      { q: 'Remy LeBeau, the Cajun X-Man who charges playing cards to explode.', a: 'Gambit' },
    ],
    H: [
      { q: 'The rampaging green giant Bruce Banner turns into when angry.', a: 'Hulk', alt: ['The Hulk'] },
      { q: 'Clint Barton\'s sharpshooting Avenger codename.', a: 'Hawkeye' },
      { q: 'The Joker\'s acrobatic, mallet-swinging partner in crime, a former Arkham psychiatrist.', a: 'Harley Quinn' },
      { q: 'The Goddess of Death and Thor\'s older sister in Ragnarok, played by Cate Blanchett.', a: 'Hela' },
      { q: 'The terror organization hidden inside S.H.I.E.L.D.: cut off one head, two more take its place.', a: 'Hydra' },
      { q: 'The Australian actor who played Wolverine for nearly two decades.', a: 'Hugh Jackman' },
      { q: 'Johnny Storm\'s blazing Fantastic Four identity, famous for shouting "Flame on!".', a: 'Human Torch' },
      { q: 'Mike Mignola\'s red-skinned demon investigator, published by Dark Horse Comics.', a: 'Hellboy' },
      { q: 'Tony\'s inventor father, a founding figure of S.H.I.E.L.D. in the MCU.', a: 'Howard Stark' },
      { q: 'The winged, mace-swinging DC heroine reincarnated across the centuries.', a: 'Hawkgirl' },
    ],
    I: [
      { q: 'Tony Stark\'s armored alter ego.', a: 'Iron Man' },
      { q: 'The golden glove Thanos uses to wield all six cosmic gems at once.', a: 'Infinity Gauntlet' },
      { q: 'Danny Rand\'s chi-powered martial-arts mantle, earned in the hidden city of K\'un-Lun.', a: 'Iron Fist' },
      { q: 'Sue Storm\'s Fantastic Four identity, a generator of force fields.', a: 'Invisible Woman' },
      { q: 'Founding X-Man Bobby Drake, who glides around on ramps of frost.', a: 'Iceman' },
      { q: 'The 2018 Avengers film that ends with half of all life turning to dust.', a: 'Infinity War' },
      { q: 'Robert Kirkman\'s superhero comic about teen hero Mark Grayson, now an animated hit.', a: 'Invincible' },
      { q: 'The Superman-like Eternal played by Richard Madden.', a: 'Ikaris' },
    ],
    J: [
      { q: 'Batman\'s grinning arch-nemesis, the Clown Prince of Crime.', a: 'Joker', alt: ['The Joker'] },
      { q: 'Nicknamed the King of Comics, he co-created Captain America, Thor and the Fantastic Four.', a: 'Jack Kirby' },
      { q: 'The blustering Daily Bugle publisher who brands Spider-Man a menace.', a: 'J. Jonah Jameson', alt: ['Jonah Jameson'] },
      { q: 'The founding telepathic X-Man consumed by a cosmic firebird force.', a: 'Jean Grey' },
      { q: 'DC\'s flagship super-team, uniting its seven greatest heroes.', a: 'Justice League' },
      { q: 'Marvel\'s hard-boiled, super-strong private investigator from the Netflix era.', a: 'Jessica Jones' },
      { q: 'The director of the Guardians of the Galaxy trilogy, now co-head of DC Studios.', a: 'James Gunn' },
      { q: 'Tony Stark\'s original British-voiced AI assistant, later reborn inside Vision.', a: 'JARVIS', alt: ['Jarvis'] },
    ],
    K: [
      { q: 'Superman\'s home planet, destroyed shortly after his birth.', a: 'Krypton' },
      { q: 'The radioactive green mineral that is deadly to the Man of Steel.', a: 'Kryptonite' },
      { q: 'Wilson Fisk, the massive New York crime lord and Daredevil\'s nemesis.', a: 'Kingpin', alt: ['The Kingpin'] },
      { q: 'Erik Stevens, the vengeful royal cousin who seizes the Wakandan throne in the 2018 film.', a: 'Killmonger', alt: ['Erik Killmonger'] },
      { q: 'The time-traveling multiversal warlord played by Jonathan Majors.', a: 'Kang', alt: ['Kang the Conqueror'] },
      { q: 'The young X-Man codenamed Shadowcat, who walks through solid walls.', a: 'Kitty Pryde' },
      { q: 'The Spider-Man foe who stalks the wall-crawler as his ultimate big-game prey.', a: 'Kraven', alt: ['Kraven the Hunter'] },
      { q: 'The 1993 storyline in which Batman\'s back is broken and Azrael takes up the cowl.', a: 'Knightfall' },
    ],
    L: [
      { q: 'Thor\'s shape-shifting trickster brother, the God of Mischief.', a: 'Loki' },
      { q: 'Superman\'s bald billionaire arch-enemy.', a: 'Lex Luthor' },
      { q: 'The star Metropolis reporter who is Superman\'s great love.', a: 'Lois Lane' },
      { q: 'Marvel\'s unbreakable-skinned hero for hire from Harlem.', a: 'Luke Cage' },
      { q: 'Curt Connors, whose limb-regrowth serum turns him into a reptilian Spider-Man foe.', a: 'Lizard', alt: ['The Lizard'] },
      { q: 'Wolverine\'s everyday name, also the title of his 2017 farewell film.', a: 'Logan' },
      { q: 'The ancient order of killers that trained Bruce Wayne in Batman Begins.', a: 'League of Assassins', alt: ['League of Shadows'] },
      { q: 'Doctor Doom\'s small fictional European dictatorship.', a: 'Latveria' },
      { q: 'Samuel Sterns, the giant-brained gamma villain who schemes against the Hulk.', a: 'Leader', alt: ['The Leader'] },
      { q: 'Wonder Woman\'s unbreakable golden rope that forces captives to be honest.', a: 'Lasso of Truth', alt: ['Golden Lasso'] },
    ],
    M: [
      { q: 'Thor\'s enchanted hammer, liftable only by the worthy.', a: 'Mjolnir' },
      { q: 'The X-Men\'s helmeted arch-foe, who bends metal to his will.', a: 'Magneto' },
      { q: 'The red-headed girl next door who greets Peter Parker with "Face it, tiger".', a: 'Mary Jane Watson', alt: ['Mary Jane', 'MJ'] },
      { q: 'The blue-skinned shape-shifter of the X-Men films, played by Rebecca Romijn and Jennifer Lawrence.', a: 'Mystique' },
      { q: 'Superman\'s gleaming home city.', a: 'Metropolis' },
      { q: 'The Brooklyn teen web-slinger of the animated Spider-Verse films.', a: 'Miles Morales' },
      { q: 'The publisher of the Avengers, X-Men and Spider-Man.', a: 'Marvel Comics', alt: ['Marvel'] },
      { q: 'The yellow gem in Loki\'s scepter, later set into Vision\'s forehead.', a: 'Mind Stone' },
      { q: 'Marc Spector, Marvel\'s mercenary avatar of the Egyptian god Khonshu.', a: 'Moon Knight' },
      { q: 'Victor Fries, the cold-gun Batman villain trying to cure his cryogenically preserved wife.', a: 'Mr. Freeze', alt: ['Mister Freeze'] },
      { q: 'Quentin Beck, the fishbowl-helmeted illusionist played by Jake Gyllenhaal.', a: 'Mysterio' },
      { q: 'J\'onn J\'onzz, the Justice League\'s shape-shifting green telepath.', a: 'Martian Manhunter' },
    ],
    N: [
      { q: 'The eye-patched spymaster of S.H.I.E.L.D., played by Samuel L. Jackson.', a: 'Nick Fury' },
      { q: 'The adult hero identity Batman\'s first sidekick adopted in the city of Bludhaven.', a: 'Nightwing' },
      { q: 'The ankle-winged Marvel king of Atlantis who surfaced in Wakanda Forever.', a: 'Namor', alt: ['Sub-Mariner'] },
      { q: 'Kurt Wagner, the blue X-Man who teleports in puffs of smoke.', a: 'Nightcrawler' },
      { q: 'The blue cyborg daughter of Thanos, played by Karen Gillan.', a: 'Nebula' },
      { q: 'The Oscorp founder who becomes the Green Goblin.', a: 'Norman Osborn' },
      { q: 'The Wakandan spy and love of T\'Challa, played by Lupita Nyong\'o.', a: 'Nakia' },
      { q: 'Marvel\'s human-rocket hero, member of an intergalactic peacekeeping corps.', a: 'Nova' },
    ],
    O: [
      { q: 'The one-eyed All-Father of Asgard, played by Anthony Hopkins.', a: 'Odin' },
      { q: 'The wheelchair-using information broker Barbara Gordon becomes.', a: 'Oracle' },
      { q: 'The Green Goblin family\'s New York tech corporation in Spider-Man.', a: 'Oscorp' },
      { q: 'The general of the Dora Milaje in Black Panther.', a: 'Okoye' },
      { q: 'Mark Grayson\'s superpowered Viltrumite father in Invincible.', a: 'Omni-Man' },
      { q: 'The home planet of the Guardians of the Universe and their emerald ring corps.', a: 'Oa' },
    ],
    P: [
      { q: 'Spider-Man\'s bookish real name.', a: 'Peter Parker' },
      { q: 'Pamela Isley, Gotham\'s plant-controlling eco-villainess.', a: 'Poison Ivy' },
      { q: 'Oswald Cobblepot, the umbrella-wielding Gotham crime boss.', a: 'Penguin', alt: ['The Penguin'] },
      { q: 'Tony Stark\'s assistant turned CEO and wife, played by Gwyneth Paltrow.', a: 'Pepper Potts' },
      { q: 'The destructive cosmic firebird entity that possesses Jean Grey.', a: 'Phoenix', alt: ['Phoenix Force', 'Dark Phoenix'] },
      { q: 'Frank Castle\'s skull-emblazoned vigilante identity.', a: 'Punisher', alt: ['The Punisher'] },
      { q: 'The size-altering subatomic substance that powers Ant-Man\'s suit.', a: 'Pym Particles' },
      { q: 'Eel O\'Brian, DC\'s stretchable, red-goggled comic-relief hero.', a: 'Plastic Man' },
      { q: 'The first name of the Scarlet Witch\'s speedster twin brother.', a: 'Pietro', alt: ['Pietro Maximoff'] },
      { q: 'Darkseid\'s winged shock-troop swarm from Apokolips.', a: 'Parademons' },
    ],
    Q: [
      { q: 'The super-fast Maximoff twin who races bullets in the X-Men and Avengers films.', a: 'Quicksilver' },
      { q: 'The Avengers\' vertical-takeoff team aircraft.', a: 'Quinjet' },
      { q: 'The New York City borough Spider-Man calls home.', a: 'Queens' },
    ],
    R: [
      { q: 'Batman\'s young sidekick, known as the Boy Wonder.', a: 'Robin' },
      { q: 'The Guardians\' trigger-happy talking mammal, voiced by Bradley Cooper.', a: 'Rocket', alt: ['Rocket Raccoon'] },
      { q: 'Johann Schmidt, the crimson-faced Hydra founder who battles Captain America.', a: 'Red Skull' },
      { q: 'Edward Nygma, the Gotham villain obsessed with puzzles and question marks.', a: 'Riddler', alt: ['The Riddler'] },
      { q: 'The immortal Demon\'s Head who leads the League of Assassins and bathes in Lazarus Pits.', a: 'Ra\'s al Ghul' },
      { q: 'The stretching super-genius known as Mr. Fantastic, full name.', a: 'Reed Richards' },
      { q: 'The white-streaked southern X-Man whose bare skin absorbs powers and memories.', a: 'Rogue' },
      { q: 'The actor whose 2008 turn as Tony Stark launched the MCU.', a: 'Robert Downey Jr.', alt: ['Robert Downey Junior'] },
    ],
    S: [
      { q: 'Marvel\'s wall-crawling web-slinger from Queens.', a: 'Spider-Man', alt: ['Spiderman'] },
      { q: 'Kal-El of Krypton, the Man of Steel.', a: 'Superman' },
      { q: 'The Marvel legend famous for his cameos, co-creator of the Avengers and the X-Men.', a: 'Stan Lee' },
      { q: 'The Marvel spy agency run from a flying Helicarrier.', a: 'SHIELD', alt: ['S.H.I.E.L.D.'] },
      { q: 'Peter Quill\'s self-chosen outlaw nickname.', a: 'Star-Lord', alt: ['Starlord'] },
      { q: 'The chaos-magic Avenger who trapped the town of Westview inside a sitcom hex.', a: 'Scarlet Witch' },
      { q: 'Norrin Radd, the chrome-skinned cosmic herald of Galactus.', a: 'Silver Surfer' },
      { q: 'The magic word young Billy Batson shouts to transform into a caped champion.', a: 'Shazam' },
      { q: 'Flint Marko, the Spider-Man villain whose body is made of living grains.', a: 'Sandman', alt: ['The Sandman'] },
      { q: 'The Kansas farm town where young Clark Kent grew up.', a: 'Smallville' },
      { q: 'The family weapons company Tony turned into a clean-energy tech giant.', a: 'Stark Industries' },
      { q: 'Ororo Munroe, the X-Men\'s weather-controlling goddess.', a: 'Storm' },
      { q: 'The classic alliance of Spider-Man villains first assembled by Doctor Octopus.', a: 'Sinister Six' },
      { q: 'The Eastern European country lifted into the sky in Age of Ultron, later namesake of the Accords.', a: 'Sokovia' },
    ],
    T: [
      { q: 'Asgard\'s hammer-swinging God of Thunder.', a: 'Thor' },
      { q: 'The Mad Titan who erased half of all life with a single snap.', a: 'Thanos' },
      { q: 'Ben Grimm, the rocky orange strongman of the Fantastic Four.', a: 'Thing', alt: ['The Thing', 'Ben Grimm'] },
      { q: 'The Wakandan king behind the Black Panther mask.', a: 'T\'Challa' },
      { q: 'Wonder Woman\'s hidden Amazon island, also called Paradise Island.', a: 'Themyscira' },
      { q: 'Harvey Dent, the scarred Gotham district attorney who decides fates with a coin flip.', a: 'Two-Face', alt: ['Harvey Dent'] },
      { q: 'The genius billionaire playboy philanthropist inside the red-and-gold armor.', a: 'Tony Stark' },
      { q: 'DC\'s junior hero team, famously led by Robin.', a: 'Teen Titans' },
      { q: 'The glowing blue cube Loki steals, which contains the Space Stone.', a: 'Tesseract' },
      { q: 'The 1939 publisher that later grew into Marvel.', a: 'Timely Comics', alt: ['Timely'] },
      { q: 'The director of the 1989 Batman film starring Michael Keaton.', a: 'Tim Burton' },
      { q: 'The Marvel team of reformed villains and misfits that headlined a 2025 MCU film.', a: 'Thunderbolts' },
    ],
    U: [
      { q: 'The rogue peacekeeping AI, voiced by James Spader, who decided humanity must end.', a: 'Ultron' },
      { q: 'Peter Parker\'s late guardian, forever tied to the words about great power and great responsibility.', a: 'Uncle Ben', alt: ['Ben Parker'] },
      { q: 'The enchanted Asgardian metal used to forge Thor\'s hammer and Stormbreaker.', a: 'Uru' },
      { q: 'The adjective that traditionally fronts the title of Marvel\'s flagship mutant-team comic.', a: 'Uncanny' },
      { q: 'The 2000s reboot imprint that modernized classic heroes and introduced Miles Morales.', a: 'Ultimate Marvel', alt: ['Ultimate Universe'] },
    ],
    V: [
      { q: 'The rare, shock-absorbing Wakandan metal in Captain America\'s shield.', a: 'Vibranium' },
      { q: 'The toothy black alien symbiote antihero bonded to Eddie Brock.', a: 'Venom' },
      { q: 'The synthetic android Avenger born from Ultron\'s body and the Mind Stone.', a: 'Vision', alt: ['The Vision'] },
      { q: 'Adrian Toomes, the winged salvage-dealer villain of Spider-Man: Homecoming.', a: 'Vulture', alt: ['The Vulture'] },
      { q: 'The real name of the Justice League\'s half-robot hero, Cyborg.', a: 'Victor Stone' },
      { q: 'The Asgardian warrior played by Tessa Thompson who becomes king of New Asgard.', a: 'Valkyrie' },
      { q: 'DC\'s immortal caveman villain, alive for over 50,000 years.', a: 'Vandal Savage' },
    ],
    W: [
      { q: 'The clawed X-Man with an adamantium skeleton and a healing factor.', a: 'Wolverine' },
      { q: 'Amazon warrior princess Diana, armed with bracelets and a golden rope.', a: 'Wonder Woman' },
      { q: 'The hidden, technologically supreme African homeland of the Black Panther.', a: 'Wakanda' },
      { q: 'The size-shifting, winged founding Avenger Janet van Dyne.', a: 'Wasp', alt: ['The Wasp'] },
      { q: 'James Rhodes\' heavily armed gunmetal armor callsign.', a: 'War Machine' },
      { q: 'The Scarlet Witch\'s real first and last name.', a: 'Wanda Maximoff', alt: ['Wanda'] },
      { q: 'The covert program that coated Wolverine\'s skeleton in adamantium.', a: 'Weapon X' },
      { q: 'Doctor Strange\'s librarian ally who becomes Sorcerer Supreme in the MCU.', a: 'Wong' },
    ],
    X: [
      { q: 'Marvel\'s mutant hero team, schooled at a Westchester mansion.', a: 'X-Men' },
      { q: 'The Nova Corps home world, seen in the first Guardians of the Galaxy.', a: 'Xandar' },
      { q: 'The strike team of mutants Deadpool recruits in his second film.', a: 'X-Force' },
      { q: 'Laura, the young female clone of Wolverine introduced in the film Logan.', a: 'X-23', alt: ['Laura Kinney'] },
    ],
    Y: [
      { q: 'The blue Ravager with a whistle-controlled arrow who raised Peter Quill.', a: 'Yondu' },
      { q: 'Darren Cross\'s villainous shrinking suit in the first Ant-Man film.', a: 'Yellowjacket' },
      { q: 'Natasha Romanoff\'s little-sister assassin, played by Florence Pugh.', a: 'Yelena Belova', alt: ['Yelena'] },
    ],
    Z: [
      { q: 'The Kryptonian military commander who demands that Earth kneel before him.', a: 'Zod', alt: ['General Zod'] },
      { q: 'The Sokovian baron who framed Bucky and split the Avengers apart in Civil War.', a: 'Zemo', alt: ['Baron Zemo', 'Helmut Zemo'] },
      { q: 'DC\'s top-hatted stage magician heroine who casts spells by speaking backwards.', a: 'Zatanna' },
      { q: 'The director whose restored four-hour Justice League cut was released in 2021.', a: 'Zack Snyder' },
    ],
  },
};
