import type { RawPack } from '../core/packs';

export const tennisPack: RawPack = {
  id: 'tennis',
  name: 'Tennis',
  description: 'Grand Slams, champions, courts and the language of the scoreboard.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🎾',
  accent: '#65a30d',
  letters: {
    A: [
      { q: 'A delivery the receiver never touches, winning the point at once.', a: 'Ace' },
      { q: 'The Las Vegas-born American who married Steffi Graf.', a: 'Agassi' },
      { q: 'The main show arena at Flushing Meadows carries the name of this American champion.', a: 'Arthur Ashe' },
      { q: 'The first of the four majors each year, played in Melbourne.', a: 'Australian Open' },
      { q: 'The score called when a player takes the next point after deuce.', a: 'Advantage' },
      { q: 'A stroke played while moving forward, to set up a finish at the net.', a: 'Approach shot' },
      { q: 'The Spaniard from El Palmar in Murcia coached by Juan Carlos Ferrero.', a: 'Alcaraz' },
      { q: 'The left-hand half of a player\'s own side, where the point after deuce is played.', a: 'Ad court' },
      { q: 'The nation Rod Laver and Ken Rosewall represented in the Davis Cup.', a: 'Australia' },
      { q: 'The Queenslander who walked away from the sport in 2022 while ranked number one.', a: 'Ashleigh Barty' },
      { q: 'The private members\' organisation in SW19 that stages Wimbledon.', a: 'All England Club' },
      { q: 'The Serbian woman who won the 2008 clay major in Paris.', a: 'Ana Ivanovic' },
      { q: 'The Scot who won the Wimbledon men\'s singles title in 2013.', a: 'Andy Murray' },
    ],
    B: [
      { q: 'The Swede who beat John McEnroe in the 1980 Wimbledon final.', a: 'Bjorn Borg' },
      { q: 'The situation in which the receiver is one point away from winning the game.', a: 'Break point' },
      { q: 'The line at the back of the court, behind which a delivery is struck.', a: 'Baseline' },
      { q: 'The groundstroke played on the side away from the racket hand.', a: 'Backhand' },
      { q: 'The German who won the Wimbledon men\'s title in 1985 aged seventeen.', a: 'Boris Becker' },
      { q: 'The American who beat Bobby Riggs in the 1973 Battle of the Sexes.', a: 'Billie Jean King' },
      { q: 'Slang for a set won six games to none, named after the shape of a zero.', a: 'Bagel' },
      { q: 'The Queensland capital that stages a January warm-up event.', a: 'Brisbane' },
      { q: 'The American identical twins Bob and Mike who dominated men\'s pairs play.', a: 'Bryan brothers' },
      { q: 'The American coach who wrote the book Winning Ugly.', a: 'Brad Gilbert' },
      { q: 'The reverse rotation that makes a ball check up after it lands.', a: 'Backspin' },
      { q: 'The upward release that begins a service motion.', a: 'Ball toss' },
      { q: 'The Paris arena district that hosts an indoor Masters event in the autumn.', a: 'Bercy' },
      { q: 'The nation of Kim Clijsters and Justine Henin.', a: 'Belgium' },
    ],
    C: [
      { q: 'The American whose long rivalry with Martina Navratilova defined the women\'s game.', a: 'Chris Evert' },
      { q: 'The slow red surface used in Paris and Monte Carlo.', a: 'Clay' },
      { q: 'The main show arena at the All England Club, fitted with a retractable roof.', a: 'Centre Court' },
      { q: 'The official who sits high beside the net and calls the score.', a: 'Chair umpire' },
      { q: 'A player\'s formal request for an electronic review of a line call.', a: 'Challenge' },
      { q: 'A stroke hit diagonally to the far side of the opponent\'s half.', a: 'Cross-court' },
      { q: 'The hold on the handle favoured for serving and volleying.', a: 'Continental grip' },
      { q: 'The Ohio city that stages a hard-court Masters event in August.', a: 'Cincinnati' },
      { q: 'The American who won the 2023 women\'s singles title in New York.', a: 'Coco Gauff' },
      { q: 'The nation of Goran Ivanisevic and Marin Cilic.', a: 'Croatia' },
      { q: 'The tall Croatian who beat Kei Nishikori in the 2014 final in New York.', a: 'Cilic' },
      { q: 'The Spaniard from Mallorca who won the 1998 Paris title and later coached Rafael Nadal.', a: 'Carlos Moya' },
      { q: 'The infrared device once used at Wimbledon to spot a service line fault.', a: 'Cyclops' },
      { q: 'The indoor artificial surface, now rare, once common at winter events.', a: 'Carpet' },
    ],
    D: [
      { q: 'The score called when both players have won three points in a game.', a: 'Deuce' },
      { q: 'The Serbian born in Belgrade in 1987, famous for his flexibility in defence.', a: 'Djokovic' },
      { q: 'The men\'s international team competition first played in 1900.', a: 'Davis Cup' },
      { q: 'Two service errors in a row, handing the point to the receiver.', a: 'Double fault' },
      { q: 'A softly struck ball that dies just over the net to catch a deep opponent.', a: 'Drop shot' },
      { q: 'The format played with two players on each side of the net.', a: 'Doubles' },
      { q: 'The tall Argentine who beat Roger Federer in the 2009 final in New York.', a: 'Del Potro' },
      { q: 'The largest city of the United Arab Emirates, host of a February tour event.', a: 'Dubai' },
      { q: 'A stroke driven straight along the side of the court rather than diagonally.', a: 'Down the line' },
      { q: 'The Russian who won the 2021 men\'s singles title in New York.', a: 'Daniil Medvedev' },
      { q: 'The narrow strip of the court used only when four players are on it.', a: 'Doubles alley' },
      { q: 'An attacking stroke taken out of the air with a full swing.', a: 'Drive volley' },
      { q: 'The ruling that ends a contest when a player is disqualified for misconduct.', a: 'Default' },
      { q: 'The British sporting goods brand long associated with rackets and balls.', a: 'Dunlop' },
      { q: 'The Austrian who won the 2020 men\'s singles title in New York.', a: 'Dominic Thiem' },
    ],
    E: [
      { q: 'The forehand hold named after a region of the United States, with the palm behind the handle.', a: 'Eastern grip' },
      { q: 'The country where the oldest of the four majors is staged.', a: 'England' },
      { q: 'The seaside resort on the Sussex coast that stages a grass event before Wimbledon.', a: 'Eastbourne' },
      { q: 'The Moscow-born player representing Kazakhstan who won Wimbledon in 2022.', a: 'Elena Rybakina' },
      { q: 'The British player who came through qualifying to win the 2021 title in New York.', a: 'Emma Raducanu' },
      { q: 'The Indigenous Australian who won the Wimbledon women\'s title in 1971 and 1980.', a: 'Evonne Goolagong' },
    ],
    F: [
      { q: 'The groundstroke played on the same side of the body as the racket hand.', a: 'Forehand' },
      { q: 'A delivery that fails to land in the correct box.', a: 'Fault' },
      { q: 'The park in Queens where the US Open is played.', a: 'Flushing Meadows' },
      { q: 'The clay major staged at Roland Garros.', a: 'French Open' },
      { q: 'The service infringement of touching the baseline before striking the ball.', a: 'Foot fault' },
      { q: 'The score announced when a player wins the opening point of a game.', a: 'Fifteen' },
      { q: 'The former name of the women\'s international team competition now called the Billie Jean King Cup.', a: 'Fed Cup' },
      { q: 'A delivery struck with almost no rotation, aimed purely at speed.', a: 'Flat serve' },
      { q: 'The call for a player\'s third point within a game.', a: 'Forty' },
      { q: 'The nation whose Four Musketeers dominated the 1920s.', a: 'France' },
      { q: 'The West Side club in Queens that staged the US Championships before 1978.', a: 'Forest Hills' },
      { q: 'The continuation of the swing after the ball has left the strings.', a: 'Follow through' },
    ],
    G: [
      { q: 'The feat of taking all four major titles and the Olympic singles gold in one calendar year.', a: 'Golden Slam' },
      { q: 'The collective name for the four biggest championships of the season.', a: 'Grand Slam' },
      { q: 'The fast natural surface used at Wimbledon.', a: 'Grass' },
      { q: 'The Croatian left-hander who won Wimbledon in 2001 as a wild card.', a: 'Goran Ivanisevic' },
      { q: 'The Brazilian who drew a heart in the dirt after winning in Paris in 2001.', a: 'Gustavo Kuerten' },
      { q: 'The wrap on a racket handle that a player holds.', a: 'Grip' },
      { q: 'A ball struck after it has bounced, usually from near the back of the court.', a: 'Groundstroke' },
      { q: 'The nation of Boris Becker and Michael Stich.', a: 'Germany' },
      { q: 'The Davis Cup nation Andy Murray led to the 2015 title.', a: 'Great Britain' },
      { q: 'The Argentine left-hander who won in Paris and New York in 1977.', a: 'Guillermo Vilas' },
      { q: 'The Bulgarian with a one-handed backhand once nicknamed Baby Fed.', a: 'Grigor Dimitrov' },
    ],
    H: [
      { q: 'The acrylic surface laid over concrete, used in Melbourne and New York.', a: 'Hard court' },
      { q: 'The camera-based ball-tracking system used to review line calls.', a: 'Hawk-Eye' },
      { q: 'A ball taken immediately as it comes off the ground, right at the feet.', a: 'Half volley' },
      { q: 'The mixed-teams event long staged in Perth in January.', a: 'Hopman Cup' },
      { q: 'To win the game in which you are the one delivering.', a: 'Hold' },
      { q: 'The German port city that stages a long-running clay event.', a: 'Hamburg' },
      { q: 'The Austrian brand that makes rackets as well as skis.', a: 'Head' },
      { q: 'The Czech player who won the 1985 women\'s title in New York.', a: 'Hana Mandlikova' },
      { q: 'The call when a player is obstructed during a point and it must be replayed.', a: 'Hindrance' },
    ],
    I: [
      { q: 'The Coachella Valley venue that stages a March Masters event.', a: 'Indian Wells' },
      { q: 'The nation of Adriano Panatta and Jannik Sinner.', a: 'Italy' },
      { q: 'The Czech-born player who later coached Andy Murray to his major titles.', a: 'Ivan Lendl' },
      { q: 'The call confirming a ball has landed within the boundary.', a: 'In' },
      { q: 'The Polish player who won her first Paris title in 2020.', a: 'Iga Swiatek' },
      { q: 'The Romanian showman who won the 1972 men\'s title in New York.', a: 'Ilie Nastase' },
    ],
    J: [
      { q: 'The combative American left-hander who reached the 1991 US Open semi-finals at thirty-nine.', a: 'Jimmy Connors' },
      { q: 'The Belgian with a celebrated one-handed backhand who retired in 2008 while ranked number one.', a: 'Justine Henin' },
      { q: 'The American famous for shouting You cannot be serious at an official.', a: 'John McEnroe' },
      { q: 'The Spaniard who won the 2003 Paris title and now coaches a fellow countryman.', a: 'Juan Carlos Ferrero' },
      { q: 'The Italian from South Tyrol who was a junior skiing champion before turning to the racket.', a: 'Jannik Sinner' },
      { q: 'The American who won Wimbledon in 1947 and later promoted the professional circuit.', a: 'Jack Kramer' },
      { q: 'The tall American who played an eleven-hour first-round marathon at Wimbledon in 2010.', a: 'John Isner' },
      { q: 'The Frenchman who reached the 2008 Melbourne final.', a: 'Jo-Wilfried Tsonga' },
      { q: 'The American credited with inventing the tiebreak scoring system.', a: 'Jimmy Van Alen' },
    ],
    K: [
      { q: 'The Australian nicknamed Muscles.', a: 'Ken Rosewall' },
      { q: 'The Belgian who came out of retirement to win the 2009 title in New York.', a: 'Kim Clijsters' },
      { q: 'The Japanese player coached by Michael Chang.', a: 'Kei Nishikori' },
      { q: 'A high-bouncing topspin delivery aimed at the backhand.', a: 'Kick serve' },
      { q: 'The Melbourne club that staged the Australian Open before it moved to Flinders Park in 1988.', a: 'Kooyong' },
      { q: 'The South African who reached the 2018 Wimbledon final.', a: 'Kevin Anderson' },
    ],
    L: [
      { q: 'The call when a service clips the top of the net and must be taken again.', a: 'Let' },
      { q: 'The term used on the scoreboard for zero.', a: 'Love' },
      { q: 'A ball hit high over an opponent who has come to the net.', a: 'Lob' },
      { q: 'The official positioned to rule on whether a ball lands in or out.', a: 'Line judge' },
      { q: 'The Australian who won the Wimbledon men\'s title in 2002.', a: 'Lleyton Hewitt' },
      { q: 'A game won without conceding a single point.', a: 'Love game' },
      { q: 'The British capital where the grass major is staged.', a: 'London' },
      { q: 'The Australian who won Wimbledon in 1956 and 1957.', a: 'Lew Hoad' },
    ],
    M: [
      { q: 'The Czech-born left-hander who defected to the United States in 1975.', a: 'Martina Navratilova' },
      { q: 'The Australian woman who won all four majors in 1970.', a: 'Margaret Court' },
      { q: 'The Victorian precinct that has staged the year\'s first major since 1988.', a: 'Melbourne Park' },
      { q: 'The stage at which a player can end the whole contest with one more point.', a: 'Match point' },
      { q: 'The Monaco event that opens the European clay Masters season.', a: 'Monte Carlo' },
      { q: 'The format in which each pair has one man and one woman.', a: 'Mixed doubles' },
      { q: 'The Russian who won Wimbledon in 2004 at seventeen.', a: 'Maria Sharapova' },
      { q: 'The American who won the 1989 Paris title at seventeen.', a: 'Michael Chang' },
      { q: 'The Florida city whose Masters event moved to a football stadium in 2019.', a: 'Miami' },
      { q: 'The Swede who won three of the four majors in 1988.', a: 'Mats Wilander' },
      { q: 'Slang for an extremely high, deep topspin ball used to push an opponent back.', a: 'Moonball' },
      { q: 'The Russian who beat Pete Sampras in the 2000 final in New York.', a: 'Marat Safin' },
      { q: 'The Swiss who won the 1997 Melbourne title at sixteen.', a: 'Martina Hingis' },
      { q: 'The tier of ATP events ranked just below the four majors.', a: 'Masters 1000' },
    ],
    N: [
      { q: 'The barrier stretched across the middle of the playing area.', a: 'Net' },
      { q: 'The band along the top edge of the barrier that a ball can clip.', a: 'Net cord' },
      { q: 'The awkward zone between the back of the court and the service line.', a: 'No-man\'s land' },
      { q: 'The Japanese player who won the 2018 title in New York and the 2019 Melbourne title.', a: 'Naomi Osaka' },
      { q: 'The moustachioed Australian who won the 1973 men\'s title in New York.', a: 'Newcombe' },
      { q: 'The Australian showman known for his tweeners and his rows with officials.', a: 'Nick Kyrgios' },
      { q: 'The nation of Richard Krajicek and Kiki Bertens.', a: 'Netherlands' },
      { q: 'The string material made from animal intestine, prized for its feel.', a: 'Natural gut' },
      { q: 'The American city that hosts the last major of the year.', a: 'New York' },
      { q: 'The Rhode Island town whose grass event is played at the International Tennis Hall of Fame.', a: 'Newport' },
    ],
    O: [
      { q: 'The call when a ball lands beyond the boundary.', a: 'Out' },
      { q: 'A stroke struck from above to punish a high floating ball.', a: 'Overhead' },
      { q: 'What happens when the official in the chair reverses a line call.', a: 'Overrule' },
      { q: 'The period beginning in 1968 when professionals were admitted to the major championships.', a: 'Open era' },
      { q: 'The thin replaceable wrap a player adds over a racket handle.', a: 'Overgrip' },
      { q: 'The hard-hitting Latvian who won the 2017 Paris title while unseeded.', a: 'Ostapenko' },
      { q: 'The London dome venue that staged the season-ending ATP Finals from 2009 to 2020.', a: 'O2 Arena' },
    ],
    P: [
      { q: 'A ball driven beyond an opponent who has moved forward.', a: 'Passing shot' },
      { q: 'In a pairs match, to cross over and intercept a ball meant for your partner.', a: 'Poach' },
      { q: 'The American with a famous running forehand who won in New York in 1990 at nineteen.', a: 'Pete Sampras' },
      { q: 'The Australian net-rusher who won in New York in 1997 and 1998.', a: 'Pat Rafter' },
      { q: 'The French city whose major is played on clay in the west of the city.', a: 'Paris' },
      { q: 'Slang for a defensive player who simply keeps the ball in play without pace.', a: 'Pusher' },
      { q: 'The nation of Iga Swiatek and Hubert Hurkacz.', a: 'Poland' },
      { q: 'The Czech left-hander who won Wimbledon in 2011 and 2014.', a: 'Petra Kvitova' },
      { q: 'The second step of the code violation ladder, after a warning.', a: 'Point penalty' },
      { q: 'The Australian who climbed into the crowd after winning Wimbledon in 1987.', a: 'Pat Cash' },
      { q: 'The payment a player earns from a result at an event.', a: 'Prize money' },
      { q: 'The equipment brand that popularised the oversized racket in the 1970s.', a: 'Prince' },
    ],
    Q: [
      { q: 'A player who earns a main-draw place through the preliminary rounds.', a: 'Qualifier' },
      { q: 'The west London venue that stages a grass event in June.', a: 'Queen\'s Club' },
      { q: 'The round played when eight competitors remain.', a: 'Quarter-final' },
      { q: 'The Gulf nation whose capital Doha stages an early-season tour event.', a: 'Qatar' },
      { q: 'The two-word request an official makes to hush a noisy crowd.', a: 'Quiet please' },
    ],
    R: [
      { q: 'The Swiss with the one-handed backhand who was born in Basel.', a: 'Roger Federer' },
      { q: 'The Spanish left-hander from Mallorca nicknamed the King of Clay.', a: 'Rafael Nadal' },
      { q: 'The Paris stadium named after a pioneering French aviator.', a: 'Roland Garros' },
      { q: 'The Australian left-hander who completed the calendar Grand Slam in 1962 and 1969.', a: 'Rod Laver' },
      { q: 'The stroke a receiver plays off the delivery.', a: 'Return' },
      { q: 'The strung implement used to strike the ball.', a: 'Racket' },
      { q: 'An extended exchange of strokes within one point.', a: 'Rally' },
      { q: 'The withdrawal of an injured player during play, handing the win to the opponent.', a: 'Retirement' },
      { q: 'The Australian who won Wimbledon in 1964 and 1965.', a: 'Roy Emerson' },
      { q: 'The Italian capital whose clay Masters is played at the Foro Italico.', a: 'Rome' },
      { q: 'The nation of Marat Safin and Yevgeny Kafelnikov.', a: 'Russia' },
      { q: 'The cushioned green surface used in Melbourne before Plexicushion.', a: 'Rebound Ace' },
      { q: 'The retractable covering installed over Centre Court in 2009.', a: 'Roof' },
      { q: 'The group format in which each player meets every other in the section.', a: 'Round robin' },
    ],
    S: [
      { q: 'The stroke that begins every point.', a: 'Serve' },
      { q: 'The unit won by taking six games with a margin of two.', a: 'Set' },
      { q: 'A powerful overhead put-away struck steeply downward.', a: 'Smash' },
      { q: 'A stroke cut with spin so that it stays low after landing.', a: 'Slice' },
      { q: 'The German who won all four majors and the Olympic singles gold in 1988.', a: 'Steffi Graf' },
      { q: 'The younger of the two American sisters from Compton.', a: 'Serena Williams' },
      { q: 'The Swedish net-rusher who won Wimbledon in 1988 and 1990.', a: 'Stefan Edberg' },
      { q: 'The nation of Rafael Nadal and Carlos Moya.', a: 'Spain' },
      { q: 'The tactic of rushing forward immediately behind your own delivery.', a: 'Serve and volley' },
      { q: 'The format played one against one.', a: 'Singles' },
      { q: 'The boundary running along the length of the playing area.', a: 'Sideline' },
      { q: 'The rectangle a delivery must land in to be legal.', a: 'Service box' },
      { q: 'The central area of the strings that gives the cleanest strike.', a: 'Sweet spot' },
      { q: 'The countdown display that limits the seconds between points.', a: 'Shot clock' },
      { q: 'The nation of Roger Federer and Martina Hingis.', a: 'Switzerland' },
      { q: 'The Swiss with a heavy one-handed backhand who won the 2015 Paris title.', a: 'Stan Wawrinka' },
      { q: 'The nation of Bjorn Borg and Mats Wilander.', a: 'Sweden' },
    ],
    T: [
      { q: 'The special game played when a set reaches six games each.', a: 'Tiebreak' },
      { q: 'The forward rotation that makes a ball dip and then kick up.', a: 'Topspin' },
      { q: 'The British term for the narrow side corridors used in pairs play.', a: 'Tramlines' },
      { q: 'The common overuse injury of the outer forearm named after this sport.', a: 'Tennis elbow' },
      { q: 'The spin of a racket before play that decides who delivers first.', a: 'Toss' },
      { q: 'The British player after whom a grassy Wimbledon viewing slope is nicknamed.', a: 'Tim Henman' },
      { q: 'The American who won the 1979 title in New York at sixteen.', a: 'Tracy Austin' },
      { q: 'The Australian half of the pairs partnership known as the Woodies.', a: 'Todd Woodbridge' },
      { q: 'The stroke on the non-racket side played with both palms on the handle.', a: 'Two-handed backhand' },
      { q: 'The felt-covered yellow sphere used in play.', a: 'Tennis ball' },
      { q: 'The offence of exceeding the allowed seconds between points.', a: 'Time violation' },
      { q: 'The Greek with a one-handed backhand who won the 2019 season finale.', a: 'Tsitsipas' },
    ],
    U: [
      { q: 'A mistake a player makes with no real pressure from the opponent.', a: 'Unforced error' },
      { q: 'A delivery struck from below the waist to surprise a deep receiver.', a: 'Underarm serve' },
      { q: 'The last of the four majors in the calendar year.', a: 'US Open' },
      { q: 'The nation of Jimmy Connors and John McEnroe.', a: 'United States' },
      { q: 'The nation of Elina Svitolina.', a: 'Ukraine' },
    ],
    V: [
      { q: 'A ball struck out of the air before it touches the ground.', a: 'Volley' },
      { q: 'The elder of the two American sisters from Compton.', a: 'Venus Williams' },
      { q: 'The silver salver presented to the Wimbledon women\'s singles champion.', a: 'Venus Rosewater Dish' },
      { q: 'The Spanish shout of encouragement Rafael Nadal is known for.', a: 'Vamos' },
      { q: 'The Belarusian who won the Melbourne title in 2012 and 2013.', a: 'Victoria Azarenka' },
      { q: 'The British woman who won the Wimbledon singles title in 1977.', a: 'Virginia Wade' },
    ],
    W: [
      { q: 'The oldest of the four majors, played on grass in south-west London.', a: 'Wimbledon' },
      { q: 'The result recorded when an opponent withdraws before play begins.', a: 'Walkover' },
      { q: 'The first step of the code violation ladder, before any points are deducted.', a: 'Warning' },
      { q: 'The extreme forehand hold on the handle that produces heavy topspin.', a: 'Western grip' },
      { q: 'A free main-draw place given at the organisers\' discretion.', a: 'Wild card' },
      { q: 'A stroke the opponent cannot reach at all, ending the point.', a: 'Winner' },
      { q: 'The American siblings Venus and Serena, who also won pairs titles together.', a: 'Williams sisters' },
      { q: 'The seated version of the sport contested at all four majors.', a: 'Wheelchair tennis' },
      { q: 'The American brand that supplies the balls used at the US Open.', a: 'Wilson' },
      { q: 'The Dane who won the 2018 Melbourne title.', a: 'Wozniacki' },
      { q: 'The call for a ball landing beyond the side boundary.', a: 'Wide' },
      { q: 'The top position in the official rankings.', a: 'World number one' },
      { q: 'The towelling band worn on the forearm to soak up sweat.', a: 'Wristband' },
    ],
    Y: [
      { q: 'The Frenchman who won the 1983 Paris title.', a: 'Yannick Noah' },
      { q: 'The Russian who won the 1999 Melbourne title.', a: 'Yevgeny Kafelnikov' },
      { q: 'The Japanese brand whose rackets and shoes are common on tour.', a: 'Yonex' },
      { q: 'The colour of the ball adopted at Wimbledon in 1986.', a: 'Yellow' },
    ],
    Z: [
      { q: 'The German who won the 2018 season-ending finals in London.', a: 'Zverev' },
      { q: 'The Russian who reached the 2010 Wimbledon final.', a: 'Zvonareva' },
      { q: 'The Croatian capital that staged an indoor tour event.', a: 'Zagreb' },
      { q: 'The American who reached the 1990 Wimbledon final.', a: 'Zina Garrison' },
    ],
  },
};
