import type { RawPack } from '../core/packs';

export const trainsShipsPack: RawPack = {
  id: 'trains-ships',
  name: 'Trains & Ships',
  description: 'Famous locomotives, liners, canals and the age of rail and sail.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🚂',
  accent: '#7c3aed',
  letters: {
    A: [
      { q: 'Heavy hooked weight dropped to hold a vessel in one place.', a: 'Anchor' },
      { q: 'Direction word meaning towards the rear on a vessel.', a: 'Aft' },
      { q: 'The national passenger rail operator of the United States.', a: 'Amtrak' },
      { q: 'Warship with a long flat deck for launching and landing planes.', a: 'Aircraft carrier' },
      { q: 'Traditional sailor\'s shout used to hail another vessel.', a: 'Ahoy' },
      { q: 'The great Spanish fleet defeated by English ships in 1588.', a: 'Armada' },
      { q: 'Cunard liner that served in both world wars and sailed for 36 years.', a: 'Aquitania' },
      { q: 'The ocean in which the Titanic went down in 1912.', a: 'Atlantic' },
      { q: 'The great wooden vessel Noah built in the Bible.', a: 'Ark' },
      { q: 'Nautical term for the middle section of a vessel.', a: 'Amidships' },
    ],
    B: [
      { q: 'Petty officer in charge of a ship\'s crew, rigging and deck gear.', a: 'Bosun' },
      { q: 'The front end of a vessel.', a: 'Bow' },
      { q: 'English nickname for Japan\'s high-speed Shinkansen service.', a: 'Bullet train' },
      { q: 'Flat-bottomed craft used to carry cargo on rivers and inland waterways.', a: 'Barge' },
      { q: 'German battleship sunk by the Royal Navy in May 1941.', a: 'Bismarck' },
      { q: 'The measure of wind force running from calm up to hurricane.', a: 'Beaufort scale' },
      { q: 'Raised platform from which a ship\'s captain gives orders.', a: 'Bridge' },
      { q: 'Heavy material carried low in a hull to keep it steady.', a: 'Ballast' },
      { q: 'Spring-loaded pad on the end of a railway wagon that absorbs impact.', a: 'Buffer' },
      { q: 'Engineer of the Great Western Railway and the steamship Great Eastern.', a: 'Brunel' },
      { q: 'The part of a locomotive in which water is heated to raise pressure.', a: 'Boiler' },
      { q: 'Upright dividing wall inside a hull that forms watertight compartments.', a: 'Bulkhead' },
    ],
    C: [
      { q: 'The crew car once coupled at the end of an American freight train.', a: 'Caboose' },
      { q: 'British line whose ships included the Lusitania and the Queen Mary.', a: 'Cunard' },
      { q: 'Narrow cut opened through a Greek isthmus in 1893.', a: 'Corinth Canal' },
      { q: 'The officer in overall command of a merchant vessel.', a: 'Captain' },
      { q: 'Fast, sharp-hulled sailing merchantman of the 19th-century tea trade.', a: 'Clipper' },
      { q: 'Boat built on two parallel hulls.', a: 'Catamaran' },
      { q: 'The tea trader preserved on dry land at Greenwich in London.', a: 'Cutty Sark' },
      { q: 'On American railways, the crew member in charge who collects tickets.', a: 'Conductor' },
      { q: 'Lookout platform fixed high up on a mast.', a: 'Crow\'s nest' },
      { q: 'Instrument whose magnetised needle always points north.', a: 'Compass' },
      { q: 'The 1797 American frigate nicknamed Old Ironsides.', a: 'Constitution' },
      { q: 'The rail link that runs beneath the sea between England and France.', a: 'Channel Tunnel' },
      { q: 'Modern cargo vessel that carries goods in stacked steel boxes.', a: 'Container ship' },
    ],
    D: [
      { q: 'Enclosed stretch of water where vessels are loaded and unloaded.', a: 'Dock' },
      { q: 'Type of engine, named after a German inventor, that replaced steam on most railways.', a: 'Diesel' },
      { q: 'The floor level of a ship.', a: 'Deck' },
      { q: 'Class of battleship, launched by Britain in 1906, that made older warships obsolete.', a: 'Dreadnought' },
      { q: 'Basin that can be pumped empty so that a hull may be repaired.', a: 'Dry dock' },
      { q: 'Small crane on a ship\'s side used to lower a lifeboat.', a: 'Davit' },
      { q: 'The depth of water a loaded vessel needs in order to stay afloat.', a: 'Draft' },
      { q: 'The coach on a long-distance train where meals are served.', a: 'Dining car' },
      { q: 'Traditional Arab sailing vessel with a triangular sail.', a: 'Dhow' },
      { q: 'Belt of calm near the equator where sailing ships were once becalmed for weeks.', a: 'Doldrums' },
      { q: 'English seaman who sailed round the world and fought the Spanish fleet in 1588.', a: 'Drake' },
      { q: 'Fast warship built to escort a fleet and hunt submarines.', a: 'Destroyer' },
    ],
    E: [
      { q: 'American word for the person who drives a locomotive.', a: 'Engineer' },
      { q: 'Shackleton\'s vessel, crushed by ice in the Weddell Sea in 1915.', a: 'Endurance' },
      { q: 'The 1825 New York waterway that linked the Hudson to the Great Lakes.', a: 'Erie Canal' },
      { q: 'High-speed rail service running from London to Paris and Brussels.', a: 'Eurostar' },
      { q: 'Flag flown at a ship\'s rear to show which country she belongs to.', a: 'Ensign' },
      { q: 'Tanker that spilled crude oil off the coast of Alaska in 1989.', a: 'Exxon Valdez' },
      { q: 'Canadian Pacific liner lost in the St Lawrence after a collision in 1914.', a: 'Empress of Ireland' },
      { q: 'Wide tidal mouth where a river meets the sea.', a: 'Estuary' },
      { q: 'To go aboard a vessel at the start of a journey.', a: 'Embark' },
      { q: 'Word for a train that stops only at the biggest stations.', a: 'Express' },
    ],
    F: [
      { q: 'Vessel that runs back and forth across a stretch of water on a fixed route.', a: 'Ferry' },
      { q: 'The chimney of a steamship, through which smoke escapes.', a: 'Funnel' },
      { q: 'Carved wooden ornament fixed below the front of an old sailing ship.', a: 'Figurehead' },
      { q: 'Nautical unit of depth equal to six feet.', a: 'Fathom' },
      { q: 'Locomotive number 4472, first authenticated at 100 mph in 1934.', a: 'Flying Scotsman' },
      { q: 'The chamber of a steam locomotive in which the coal actually burns.', a: 'Firebox' },
      { q: 'Word for goods carried in bulk by rail or by sea.', a: 'Freight' },
      { q: 'Cable railway on a steep slope where two cars counterbalance each other.', a: 'Funicular' },
      { q: 'The raised deck at the front of a ship, where the crew was once housed.', a: 'Forecastle' },
      { q: 'Naval escort vessel, ranked below a destroyer in most modern fleets.', a: 'Frigate' },
      { q: 'The crew member who shovelled coal on a steam locomotive.', a: 'Fireman' },
    ],
    G: [
      { q: 'The kitchen on board a ship.', a: 'Galley' },
      { q: 'Movable walkway used to get on and off a moored vessel.', a: 'Gangway' },
      { q: 'The distance measured between the two rails of a track.', a: 'Gauge' },
      { q: 'Brunel\'s huge iron steamship that laid the first lasting transatlantic telegraph cable.', a: 'Great Eastern' },
      { q: 'New York\'s vast Beaux-Arts railway station on 42nd Street.', a: 'Grand Central Terminal' },
      { q: 'Flat-bottomed rowing craft propelled with a single oar in Venice.', a: 'Gondola' },
      { q: 'Drake\'s vessel, the first English one to sail right round the world.', a: 'Golden Hind' },
      { q: 'Large multi-decked Spanish sailing warship of the 16th century.', a: 'Galleon' },
      { q: 'British territory guarding the western entrance to the Mediterranean.', a: 'Gibraltar' },
      { q: 'The ceremonial last nail driven at Promontory Summit in 1869.', a: 'Golden Spike' },
    ],
    H: [
      { q: 'The main watertight body of a vessel.', a: 'Hull' },
      { q: 'The wheel or tiller by which a vessel is steered.', a: 'Helm' },
      { q: 'Sheltered stretch of coast where vessels can lie safely.', a: 'Harbour' },
      { q: 'Covered opening in a deck giving access to the space below.', a: 'Hatch' },
      { q: 'The space below deck in which cargo is stowed.', a: 'Hold' },
      { q: 'Vehicle that rides over water on a cushion of air.', a: 'Hovercraft' },
      { q: 'C. S. Forester\'s fictional Royal Navy officer of the Napoleonic wars.', a: 'Hornblower' },
      { q: 'New York river named after the English navigator who sailed up it in 1609.', a: 'Hudson' },
      { q: 'Thick rope or cable used for mooring or towing a ship.', a: 'Hawser' },
      { q: 'Rope used to pull a sail up its mast.', a: 'Halyard' },
    ],
    I: [
      { q: 'Floating mountain of frozen fresh water that fatally holed the Titanic.', a: 'Iceberg' },
      { q: 'Wooden warship sheathed in metal plates, first used in the 1860s.', a: 'Ironclad' },
      { q: 'The eastern end of the famous luxury rail route from Paris.', a: 'Istanbul' },
      { q: 'Australian train that crosses the continent between Sydney and Perth.', a: 'Indian Pacific' },
      { q: 'Vessel with a strengthened bow built to force a way through frozen sea.', a: 'Icebreaker' },
      { q: 'Term for an engine mounted inside a small boat rather than hung on the back.', a: 'Inboard' },
      { q: 'The railroad Casey Jones was driving for when he died in 1900.', a: 'Illinois Central' },
    ],
    J: [
      { q: 'Small landing stage built out from the shore for boats.', a: 'Jetty' },
      { q: 'Triangular sail set forward of the mast.', a: 'Jib' },
      { q: 'Traditional Chinese sailing vessel with battened sails.', a: 'Junk' },
      { q: 'The black pirate flag bearing a skull and crossbones.', a: 'Jolly Roger' },
      { q: 'Scottish-born American captain of the Bonhomme Richard in 1779.', a: 'John Paul Jones' },
      { q: 'Small national flag flown at the front of a warship.', a: 'Jack' },
    ],
    K: [
      { q: 'The backbone timber running along the bottom of a hull.', a: 'Keel' },
      { q: 'Unit of speed equal to one nautical mile an hour.', a: 'Knot' },
      { q: 'Narrow one-person craft moved with a double-ended paddle.', a: 'Kayak' },
      { q: 'Two-masted sailing boat whose shorter mast stands at the rear.', a: 'Ketch' },
      { q: 'The London terminus for trains to Edinburgh on the East Coast route.', a: 'King\'s Cross' },
      { q: 'The balsa raft Thor Heyerdahl sailed across the Pacific in 1947.', a: 'Kon-Tiki' },
      { q: 'German waterway joining the North Sea to the Baltic.', a: 'Kiel Canal' },
    ],
    L: [
      { q: 'Small craft carried aboard for use in an emergency at sea.', a: 'Lifeboat' },
      { q: 'Coastal tower whose beam warns vessels away from rocks.', a: 'Lighthouse' },
      { q: 'The powered vehicle that hauls a train.', a: 'Locomotive' },
      { q: 'Cunard liner torpedoed by a German submarine in 1915.', a: 'Lusitania' },
      { q: 'The official record book of a ship\'s daily events.', a: 'Log' },
      { q: 'The side of a vessel that is sheltered from the wind.', a: 'Leeward' },
      { q: 'English port city that was home to both the Cunard and White Star lines.', a: 'Liverpool' },
      { q: 'Ring-shaped float thrown to someone who has gone into the water.', a: 'Lifebuoy' },
      { q: 'Point where a road meets a railway on the flat, guarded by barriers.', a: 'Level crossing' },
      { q: 'Measure of how far north or south of the equator a vessel is.', a: 'Latitude' },
      { q: 'Viking vessel with a shallow hull and a single square sail.', a: 'Longship' },
    ],
    M: [
      { q: 'Upright pole that carries a sail.', a: 'Mast' },
      { q: 'The vessel that carried the Pilgrims to America in 1620.', a: 'Mayflower' },
      { q: 'Henry VIII\'s warship that capsized in 1545 and was raised in 1982.', a: 'Mary Rose' },
      { q: 'Cunard liner, sister of the Lusitania, that held the Blue Riband for two decades.', a: 'Mauretania' },
      { q: 'Railway whose cars run along a single beam.', a: 'Monorail' },
      { q: 'The rope or chain by which a vessel is secured to a quay.', a: 'Mooring' },
      { q: 'The official list of everything a vessel is carrying.', a: 'Manifest' },
      { q: 'Name of the rearmost mast on a three-masted sailing ship.', a: 'Mizzen' },
      { q: 'Term for a ship\'s very first journey in service.', a: 'Maiden voyage' },
      { q: 'The usual name for the Paris underground railway.', a: 'Metro' },
      { q: 'A country\'s fleet of commercial vessels and the crews who sail them.', a: 'Merchant navy' },
    ],
    N: [
      { q: 'The submarine commanded by Captain Nemo in a Jules Verne novel.', a: 'Nautilus' },
      { q: 'Crew member responsible for plotting a ship\'s course.', a: 'Navigator' },
      { q: 'The admiral who died at Trafalgar in 1805.', a: 'Nelson' },
      { q: 'Railway built with its rails set closer together than the standard distance.', a: 'Narrow gauge' },
      { q: 'French liner of the 1930s that burned and capsized in New York in 1942.', a: 'Normandie' },
      { q: 'Unit of distance at sea equal to about 1,852 metres.', a: 'Nautical mile' },
      { q: 'The river cruised by tourist boats between Luxor and Aswan.', a: 'Nile' },
      { q: 'One of Columbus\'s three vessels of 1492, along with the Pinta.', a: 'Nina' },
    ],
    O: [
      { q: 'Wooden blade used to row a boat.', a: 'Oar' },
      { q: 'The luxury train from Paris to Istanbul in an Agatha Christie mystery.', a: 'Orient Express' },
      { q: 'Big ship built to carry passengers on long scheduled crossings.', a: 'Ocean liner' },
      { q: 'Word describing someone who has fallen from a vessel into the sea.', a: 'Overboard' },
      { q: 'Engine clamped to the back of a small boat.', a: 'Outboard motor' },
      { q: 'Sister of the Titanic that went on to serve for 24 years.', a: 'Olympic' },
      { q: 'Rail coach with big windows fitted for viewing the scenery.', a: 'Observation car' },
    ],
    P: [
      { q: 'The left-hand side of a vessel when facing forward.', a: 'Port' },
      { q: 'The mark on a hull showing how deeply it may safely be loaded.', a: 'Plimsoll line' },
      { q: 'Name for a luxurious American railway sleeping car.', a: 'Pullman' },
      { q: 'Long structure running out into the sea, often with amusements on it.', a: 'Pier' },
      { q: 'The 1914 shortcut that let ships pass between the Atlantic and the Pacific.', a: 'Panama Canal' },
      { q: 'Vessel driven along by large revolving wheels on its sides.', a: 'Paddle steamer' },
      { q: 'Screw-like device that drives a modern ship through the water.', a: 'Propeller' },
      { q: 'Ship\'s officer who handles the money and the passenger accounts.', a: 'Purser' },
      { q: 'The hinged arm on an electric train that presses against the overhead wire.', a: 'Pantograph' },
      { q: 'British name for the movable rails that send a train onto another track.', a: 'Points' },
      { q: 'Local expert who comes aboard to guide a ship safely into harbour.', a: 'Pilot' },
    ],
    R: [
      { q: 'Hinged blade at the rear of a vessel used to steer it.', a: 'Rudder' },
      { q: 'All the ropes and wires that hold up a ship\'s masts and sails.', a: 'Rigging' },
      { q: 'Stephenson\'s locomotive that won the Rainhill Trials in 1829.', a: 'Rocket' },
      { q: 'A series of boat races held as a sporting event.', a: 'Regatta' },
      { q: 'Flat floating platform of logs or planks lashed together.', a: 'Raft' },
      { q: 'Circular engine shed with a rotating platform at its centre.', a: 'Roundhouse' },
      { q: 'Fitting on a boat\'s side that holds an oar in place.', a: 'Rowlock' },
      { q: 'Verb meaning to shorten sail in a strong wind.', a: 'Reef' },
      { q: 'Dutch city that is the busiest container port in Europe.', a: 'Rotterdam' },
      { q: 'The United Kingdom\'s sea service, the oldest of its armed forces.', a: 'Royal Navy' },
    ],
    S: [
      { q: 'The rearmost part of a ship\'s structure.', a: 'Stern' },
      { q: 'The right-hand side of a vessel when facing forward.', a: 'Starboard' },
      { q: 'The 1869 Egyptian waterway joining the Mediterranean to the Red Sea.', a: 'Suez Canal' },
      { q: 'Engineer called the father of railways, who built the Liverpool and Manchester line.', a: 'Stephenson' },
      { q: 'Sheet of cloth that catches the wind and drives a boat along.', a: 'Sail' },
      { q: 'Instrument used to measure the angle of the sun above the horizon.', a: 'Sextant' },
      { q: 'Sailing vessel with two or more masts rigged fore and aft.', a: 'Schooner' },
      { q: 'Wooden or concrete beam laid across a track to support the rails.', a: 'Sleeper' },
      { q: 'Trackside building where a worker pulled levers to set the route for trains.', a: 'Signal box' },
      { q: 'Vessel designed to travel beneath the surface of the sea.', a: 'Submarine' },
      { q: 'The hot vapour that drove railway engines before oil took over.', a: 'Steam' },
      { q: 'Vitamin C deficiency that plagued crews on long voyages.', a: 'Scurvy' },
      { q: 'Code sent by holding two flags out in different positions.', a: 'Semaphore' },
      { q: 'American term for an urban railway running below street level.', a: 'Subway' },
    ],
    T: [
      { q: 'White Star liner that sank on her first crossing in April 1912.', a: 'Titanic' },
      { q: 'Lever fixed to a rudder for steering a small boat.', a: 'Tiller' },
      { q: 'Small powerful craft that pushes and pulls big ships around a port.', a: 'Tugboat' },
      { q: 'Revolving circle of track used to swing a locomotive round to face the other way.', a: 'Turntable' },
      { q: 'The 1805 sea battle off Spain where Nelson beat the French and Spanish fleets.', a: 'Trafalgar' },
      { q: 'Ship built to carry liquid cargo such as oil in bulk.', a: 'Tanker' },
      { q: 'Ancient Greek warship rowed with three banks of oars.', a: 'Trireme' },
      { q: 'The world\'s longest railway line, running from Moscow to Vladivostok.', a: 'Trans-Siberian' },
      { q: 'Self-propelled underwater missile fired at ships.', a: 'Torpedo' },
      { q: 'Printed schedule of departures and arrivals.', a: 'Timetable' },
      { q: 'Passenger vehicle that runs on rails laid in a city street.', a: 'Tram' },
    ],
    U: [
      { q: 'The London railway system nicknamed the Tube.', a: 'Underground' },
      { q: 'Name given to a German submarine in the world wars.', a: 'U-boat' },
      { q: 'The company that laid track westward from Omaha to Promontory Summit.', a: 'Union Pacific' },
      { q: 'The highest continuous floor level on a ship.', a: 'Upper deck' },
      { q: 'The battleship on which Japan signed its surrender in 1945.', a: 'USS Missouri' },
    ],
    V: [
      { q: 'A long journey made across the sea.', a: 'Voyage' },
      { q: 'The umbrella term maritime law uses for every watercraft, from a dinghy to a supertanker.', a: 'Vessel' },
      { q: 'Nelson\'s flagship, preserved in dry dock at Portsmouth.', a: 'Victory' },
      { q: 'Scandinavian raider who crossed the seas in longships.', a: 'Viking' },
      { q: 'Swedish warship that sank in Stockholm in 1628 and now has her own museum.', a: 'Vasa' },
      { q: 'Russian Pacific port at the far end of the great trans-continental railway.', a: 'Vladivostok' },
    ],
    W: [
      { q: 'Landing place built along the shore where cargo is loaded.', a: 'Wharf' },
      { q: 'Enclosed shelter on deck containing a ship\'s steering position.', a: 'Wheelhouse' },
      { q: 'Winch on the foredeck used to haul in a heavy chain.', a: 'Windlass' },
      { q: 'The line that owned the Titanic and her sister the Olympic.', a: 'White Star' },
      { q: 'The level to which a hull sinks when it is afloat.', a: 'Waterline' },
      { q: 'Railway vehicle for carrying goods rather than people.', a: 'Wagon' },
      { q: 'The device a locomotive sounds to warn people it is coming.', a: 'Whistle' },
      { q: 'The trail of churned water left behind a moving ship.', a: 'Wake' },
      { q: 'A four-hour spell of duty served by part of a ship\'s crew.', a: 'Watch' },
    ],
    Y: [
      { q: 'Pleasure boat used for cruising or for racing.', a: 'Yacht' },
      { q: 'Horizontal spar across a mast from which a square sail hangs.', a: 'Yard' },
      { q: 'Unwanted swing of a vessel\'s head to one side of her course.', a: 'Yaw' },
      { q: 'Small two-masted boat whose short rear mast stands behind the steering post.', a: 'Yawl' },
    ],
  },
};
