import type { RawPack } from '../core/packs';

export const travelAirlinesPack: RawPack = {
  id: 'travel-airlines',
  name: 'Travel & Airlines',
  description: 'Airports, carriers, landmarks and the business of getting there.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '✈️',
  accent: '#0369a1',
  letters: {
    A: [
      { q: 'The European planemaker headquartered in Toulouse.', a: 'Airbus' },
      { q: 'Hartsfield-Jackson, long the world\'s busiest passenger airport, serves this American city.', a: 'Atlanta' },
      { q: 'Schiphol is the main airport of this Dutch city.', a: 'Amsterdam' },
      { q: 'The flag carrier airline of Russia.', a: 'Aeroflot' },
      { q: 'The vast Hindu-Buddhist temple complex in Cambodia.', a: 'Angkor Wat' },
      { q: 'The ancient citadel in Athens crowned by the Parthenon.', a: 'Acropolis' },
      { q: 'The mountain range crossing eight European countries, busiest in the ski season.', a: 'Alps' },
      { q: 'The Turkish Mediterranean resort city that is among the world\'s most visited destinations.', a: 'Antalya' },
      { q: 'The national airline whose main hub is Paris Charles de Gaulle.', a: 'Air France' },
      { q: 'The online marketplace for short-term home rentals founded in 2008.', a: 'Airbnb' },
      { q: 'The national passenger railroad of the United States.', a: 'Amtrak' },
      { q: 'The largest city and busiest airport of New Zealand.', a: 'Auckland' },
      { q: 'The former island prison in San Francisco Bay, now a tourist attraction.', a: 'Alcatraz' },
      { q: 'The place next to the walkway, chosen by travellers who like to stretch their legs.', a: 'Aisle seat' },
      { q: 'The longest continental mountain range, running down western South America.', a: 'Andes' },
    ],
    B: [
      { q: 'The American aircraft manufacturer that builds the 737.', a: 'Boeing' },
      { q: 'The flag carrier airline of the United Kingdom.', a: 'British Airways' },
      { q: 'The nickname of the great bell in the clock tower at the Palace of Westminster.', a: 'Big Ben' },
      { q: 'Suvarnabhumi Airport serves this Southeast Asian capital.', a: 'Bangkok' },
      { q: 'The world\'s tallest building, in Dubai.', a: 'Burj Khalifa' },
      { q: 'The Spanish city where the Sagrada Familia stands.', a: 'Barcelona' },
      { q: 'The document you must show to be allowed onto an aircraft.', a: 'Boarding pass' },
      { q: 'The Indonesian holiday island whose main airport is at Denpasar.', a: 'Bali' },
      { q: 'Ezeiza international airport serves this South American capital.', a: 'Buenos Aires' },
      { q: 'The carousel area where you collect checked bags after landing.', a: 'Baggage claim' },
      { q: 'The Hungarian capital split by the Danube into two former towns.', a: 'Budapest' },
      { q: 'The Belgian capital that hosts the main European Union institutions.', a: 'Brussels' },
      { q: 'The French Polynesian island ringed by a turquoise lagoon.', a: 'Bora Bora' },
      { q: 'The German capital where the Brandenburg Gate stands.', a: 'Berlin' },
    ],
    C: [
      { q: 'The flag carrier airline of Hong Kong.', a: 'Cathay Pacific' },
      { q: 'The huge ancient amphitheatre in the centre of Rome.', a: 'Colosseum' },
      { q: 'The compartment at the front of an aircraft where the pilots sit.', a: 'Cockpit' },
      { q: 'O\'Hare International Airport serves this American city.', a: 'Chicago' },
      { q: 'The Danish capital where the Little Mermaid statue sits by the harbour.', a: 'Copenhagen' },
      { q: 'The supersonic airliner retired from service in 2003.', a: 'Concorde' },
      { q: 'The border desk where you declare goods you are bringing into a country.', a: 'Customs' },
      { q: 'The Mexican Caribbean resort famous for its beachfront hotel zone.', a: 'Cancun' },
      { q: 'The Egyptian capital beside the Giza pyramids.', a: 'Cairo' },
      { q: 'The largest airport serving Paris, named after a French president.', a: 'Charles de Gaulle' },
      { q: 'The Singapore airport famous for its indoor waterfall.', a: 'Changi' },
      { q: 'The Turkish region of rock chimneys where hot-air balloons fly at dawn.', a: 'Cappadocia' },
      { q: 'The South African city that sits beneath Table Mountain.', a: 'Cape Town' },
      { q: 'The small bag you take into the cabin with you.', a: 'Carry-on' },
    ],
    D: [
      { q: 'The major American airline whose largest hub is Atlanta.', a: 'Delta' },
      { q: 'The Gulf city whose airport handles more international passengers than any other.', a: 'Dubai' },
      { q: 'Hamad International Airport serves this Qatari capital.', a: 'Doha' },
      { q: 'The airport shops that sell goods without local sales tax.', a: 'Duty free' },
      { q: 'The marketing name of the Boeing 787.', a: 'Dreamliner' },
      { q: 'The biggest airport in the United States by land area serves this Colorado city.', a: 'Denver' },
      { q: 'Indira Gandhi International Airport serves this Indian capital.', a: 'Delhi' },
      { q: 'The capital of Ireland and site of its busiest airport.', a: 'Dublin' },
      { q: 'River cruises run from Germany to the Black Sea along this waterway.', a: 'Danube' },
      { q: 'The board in a terminal listing the flights that are leaving.', a: 'Departures' },
      { q: 'The walled Croatian city on the Adriatic.', a: 'Dubrovnik' },
      { q: 'The salt lake between Israel and Jordan where bathers float easily.', a: 'Dead Sea' },
    ],
    E: [
      { q: 'The Dubai-based airline that flies more A380s than any other.', a: 'Emirates' },
      { q: 'The high-speed train service through the Channel Tunnel.', a: 'Eurostar' },
      { q: 'The iron landmark on the Champ de Mars in Paris.', a: 'Eiffel Tower' },
      { q: 'The cheapest cabin on a passenger aircraft.', a: 'Economy' },
      { q: 'Trekkers fly into Lukla to reach the base camp of this mountain.', a: 'Everest' },
      { q: 'The largest airline in Africa, with its hub at Addis Ababa.', a: 'Ethiopian Airlines' },
      { q: 'The Nile country whose pyramids draw millions of visitors a year.', a: 'Egypt' },
      { q: 'The Scottish capital whose castle sits on a volcanic rock.', a: 'Edinburgh' },
      { q: 'The orange-branded British low-cost airline founded in 1995.', a: 'EasyJet' },
      { q: 'The extra fee charged when a checked bag is over the weight limit.', a: 'Excess baggage' },
      { q: 'The 1931 New York skyscraper with a famous observation deck.', a: 'Empire State Building' },
    ],
    F: [
      { q: 'The most expensive cabin on an airliner, ahead of business.', a: 'First class' },
      { q: 'Lufthansa\'s main hub airport is in this German city.', a: 'Frankfurt' },
      { q: 'The South Pacific nation of hundreds of islands whose main airport is Nadi.', a: 'Fiji' },
      { q: 'The kind of loyalty scheme that rewards regular air travellers with points.', a: 'Frequent flyer' },
      { q: 'The Tuscan city where the Uffizi Gallery stands.', a: 'Florence' },
      { q: 'The main body of an aeroplane, to which the wings attach.', a: 'Fuselage' },
      { q: 'The Memphis-based parcel company that runs the world\'s biggest cargo airline.', a: 'FedEx' },
      { q: 'A long, deep coastal inlet carved by a glacier, of the kind cruise ships visit in Norway.', a: 'Fjord' },
      { q: 'The crew member who serves passengers and handles cabin safety.', a: 'Flight attendant' },
      { q: 'The vast walled palace complex at the heart of Beijing.', a: 'Forbidden City' },
      { q: 'The boat service that carries cars and people across a strait.', a: 'Ferry' },
    ],
    G: [
      { q: 'London\'s second-busiest airport, south of the city.', a: 'Gatwick' },
      { q: 'The immense defensive structure that snakes across northern China.', a: 'Great Wall' },
      { q: 'The vast gorge carved by the Colorado River in Arizona.', a: 'Grand Canyon' },
      { q: 'The Swiss city at the western tip of its namesake lake, home to many UN offices.', a: 'Geneva' },
      { q: 'The numbered point in a terminal where you board your flight.', a: 'Gate' },
      { q: 'The Ecuadorian island group famous for its giant tortoises.', a: 'Galapagos' },
      { q: 'The plateau outside Cairo where the Great Pyramid stands.', a: 'Giza' },
      { q: 'The red suspension crossing at the mouth of San Francisco Bay.', a: 'Golden Gate Bridge' },
      { q: 'The titanium-clad museum in Bilbao designed by Frank Gehry.', a: 'Guggenheim' },
      { q: 'The Mediterranean country whose thousands of islands draw summer visitors.', a: 'Greece' },
      { q: 'The scenic Swiss train that runs between Zermatt and St Moritz.', a: 'Glacier Express' },
    ],
    H: [
      { q: 'The busiest airport in the United Kingdom.', a: 'Heathrow' },
      { q: 'Chek Lap Kok airport serves this Chinese territory.', a: 'Hong Kong' },
      { q: 'The American state made of Pacific islands, reached only by long flights.', a: 'Hawaii' },
      { q: 'Budget lodging where travellers sleep in shared dormitories.', a: 'Hostel' },
      { q: 'The Cuban capital known for classic American cars and old colonial squares.', a: 'Havana' },
      { q: 'The great domed building in Istanbul, once a cathedral and later a mosque.', a: 'Hagia Sophia' },
      { q: 'Finnair\'s base is the airport of this Nordic capital.', a: 'Helsinki' },
      { q: 'The most common kind of paid lodging for travellers.', a: 'Hotel' },
      { q: 'The central airport through which an airline routes most connecting traffic.', a: 'Hub' },
      { q: 'The Asian mountain system that contains Everest and most of the highest peaks on Earth.', a: 'Himalayas' },
      { q: 'The Vietnamese capital in the north of the country.', a: 'Hanoi' },
    ],
    I: [
      { q: 'The Turkish city split between Europe and Asia by the Bosphorus.', a: 'Istanbul' },
      { q: 'Keflavik airport is the gateway to this North Atlantic island nation.', a: 'Iceland' },
      { q: 'The desk where officials check your passport and visa on arrival.', a: 'Immigration' },
      { q: 'The airline trade body that assigns the three-letter airport codes.', a: 'IATA' },
      { q: 'The Taj Mahal draws visitors to this country.', a: 'India' },
      { q: 'The Balearic island famous for its nightclubs.', a: 'Ibiza' },
      { q: 'The pass that lets travellers ride trains across many European countries.', a: 'Interrail' },
      { q: 'The Cliffs of Moher rise on the west coast of this country.', a: 'Ireland' },
      { q: 'The Amalfi Coast and the Trevi Fountain are both in this country.', a: 'Italy' },
      { q: 'The enormous waterfalls on the border of Brazil and Argentina.', a: 'Iguazu Falls' },
    ],
    J: [
      { q: 'The tiredness caused by crossing several time zones quickly.', a: 'Jet lag' },
      { q: 'The popular nickname for the Boeing 747.', a: 'Jumbo jet' },
      { q: 'Soekarno-Hatta airport serves this Indonesian capital.', a: 'Jakarta' },
      { q: 'The Middle Eastern kingdom where the rock-cut city of Petra lies.', a: 'Jordan' },
      { q: 'The Caribbean island whose main tourist airport is at Montego Bay.', a: 'Jamaica' },
      { q: 'The city holy to Jews, Christians and Muslims where the Western Wall stands.', a: 'Jerusalem' },
      { q: 'The Saudi port city that is the main air gateway for pilgrims heading to Mecca.', a: 'Jeddah' },
      { q: 'South Africa\'s largest city, served by O R Tambo airport.', a: 'Johannesburg' },
      { q: 'The fast high-altitude wind that speeds up eastbound flights.', a: 'Jet stream' },
    ],
    K: [
      { q: 'The Dutch flag carrier, the oldest airline still operating under its original name.', a: 'KLM' },
      { q: 'The Petronas Towers rise over this Malaysian capital.', a: 'Kuala Lumpur' },
      { q: 'The Japanese city of a thousand temples that was the imperial capital before Tokyo.', a: 'Kyoto' },
      { q: 'The Maasai Mara reserve draws safari visitors to this African country.', a: 'Kenya' },
      { q: 'Africa\'s highest mountain, climbed by trekkers in Tanzania.', a: 'Kilimanjaro' },
      { q: 'The Nepalese capital where trekkers begin their Himalayan journeys.', a: 'Kathmandu' },
      { q: 'South Africa\'s biggest game reserve, named after a former president.', a: 'Kruger' },
      { q: 'The Polish city with a huge medieval market square and Wawel Castle.', a: 'Krakow' },
      { q: 'The southernmost city of the continental United States, at the end of a highway of bridges.', a: 'Key West' },
    ],
    L: [
      { q: 'The flag carrier airline of Germany.', a: 'Lufthansa' },
      { q: 'The Paris museum that holds the Mona Lisa.', a: 'Louvre' },
      { q: 'The waiting time between two connecting flights.', a: 'Layover' },
      { q: 'The Portuguese capital on the Tagus estuary.', a: 'Lisbon' },
      { q: 'The bags a traveller checks in for the hold of an aircraft.', a: 'Luggage' },
      { q: 'The Nevada desert resort city built around casinos.', a: 'Las Vegas' },
      { q: 'The city where Tower Bridge crosses the Thames.', a: 'London' },
      { q: 'The private room at an airport where premium passengers wait before a flight.', a: 'Lounge' },
      { q: 'The Peruvian capital on the Pacific coast.', a: 'Lima' },
      { q: 'The Scottish lake said to hide a monster.', a: 'Loch Ness' },
    ],
    M: [
      { q: 'The Inca citadel high in the Peruvian Andes.', a: 'Machu Picchu' },
      { q: 'The Moroccan city whose main square is the Jemaa el-Fnaa.', a: 'Marrakesh' },
      { q: 'The Indian Ocean nation of low coral atolls famous for overwater villas.', a: 'Maldives' },
      { q: 'The holiest city of Islam, visited each year by pilgrims performing the Hajj.', a: 'Mecca' },
      { q: 'The Bavarian city that hosts Oktoberfest.', a: 'Munich' },
      { q: 'The Florida city whose port handles more cruise passengers than any other.', a: 'Miami' },
      { q: 'The Gateway of India arch stands on the waterfront of this city.', a: 'Mumbai' },
      { q: 'Barajas airport serves this Spanish capital.', a: 'Madrid' },
      { q: 'The Italian fashion capital whose cathedral bristles with spires.', a: 'Milan' },
      { q: 'The capital of the Philippines.', a: 'Manila' },
    ],
    N: [
      { q: 'Along with Haneda, one of the two big airports serving Tokyo.', a: 'Narita' },
      { q: 'The famous waterfalls on the border between Ontario and New York state.', a: 'Niagara Falls' },
      { q: 'John F. Kennedy International Airport serves this American city.', a: 'New York' },
      { q: 'The Kenyan capital with a national park on its edge.', a: 'Nairobi' },
      { q: 'The Himalayan country whose Annapurna trails draw trekkers.', a: 'Nepal' },
      { q: 'Cruise boats carry tourists between Luxor and Aswan along this river.', a: 'Nile' },
      { q: 'The New Jersey airport that is one of three serving the New York area.', a: 'Newark' },
      { q: 'The Nordic country whose long western coast is cut by deep glacial inlets.', a: 'Norway' },
      { q: 'The Gothic cathedral on the Ile de la Cite in Paris, badly damaged by fire in 2019.', a: 'Notre Dame' },
    ],
    O: [
      { q: 'Chicago\'s biggest airport, named after a naval aviator.', a: 'O\'Hare' },
      { q: 'The Norwegian capital at the head of a long fjord.', a: 'Oslo' },
      { q: 'The luxury train made famous by an Agatha Christie mystery set on the way to Istanbul.', a: 'Orient Express' },
      { q: 'Kansai airport, built on an artificial island, serves this Japanese city.', a: 'Osaka' },
      { q: 'Selling more seats than the aircraft has, in the hope that some passengers will not turn up.', a: 'Overbooking' },
      { q: 'The Florida city with more theme parks than anywhere else.', a: 'Orlando' },
      { q: 'The locker above the seats where cabin bags are stowed.', a: 'Overhead bin' },
      { q: 'The capital of Canada.', a: 'Ottawa' },
      { q: 'The subtropical Japanese island chain in the far south.', a: 'Okinawa' },
    ],
    P: [
      { q: 'The rose-red city carved into cliffs in southern Jordan.', a: 'Petra' },
      { q: 'The official booklet you need to cross an international border.', a: 'Passport' },
      { q: 'The Czech capital famous for its astronomical clock and Charles Bridge.', a: 'Prague' },
      { q: 'The ruined marble temple of Athena above Athens.', a: 'Parthenon' },
      { q: 'The Tuscan city with a famous leaning bell tower.', a: 'Pisa' },
      { q: 'Thailand\'s largest island, a major beach holiday destination.', a: 'Phuket' },
      { q: 'The waterway that carries ships between the Atlantic and the Pacific through Central America.', a: 'Panama Canal' },
      { q: 'The French capital that is one of the world\'s most visited cities.', a: 'Paris' },
      { q: 'The person who flies the aircraft.', a: 'Pilot' },
      { q: 'The northern Portuguese city that gave its name to a fortified wine.', a: 'Porto' },
      { q: 'The Roman town buried by Vesuvius in AD 79, now a major site for visitors.', a: 'Pompeii' },
    ],
    Q: [
      { q: 'The flag carrier airline of Australia.', a: 'Qantas' },
      { q: 'The Doha-based carrier often voted the world\'s best airline.', a: 'Qatar Airways' },
      { q: 'The New Zealand resort on Lake Wakatipu billed as the adventure capital of the world.', a: 'Queenstown' },
      { q: 'The Ecuadorian capital, one of the highest in the world.', a: 'Quito' },
      { q: 'The Australian state where the Great Barrier Reef lies offshore.', a: 'Queensland' },
    ],
    R: [
      { q: 'The Irish low-cost carrier that flies more passengers than any other in Europe.', a: 'Ryanair' },
      { q: 'Fiumicino airport serves this Italian capital.', a: 'Rome' },
      { q: 'The paved strip an aircraft uses to take off and land.', a: 'Runway' },
      { q: 'The statue of Christ the Redeemer looks out over this Brazilian city.', a: 'Rio de Janeiro' },
      { q: 'The northernmost capital city of a sovereign state.', a: 'Reykjavik' },
      { q: 'Divers visit Sharm el-Sheikh and Hurghada on the shores of this body of water.', a: 'Red Sea' },
      { q: 'An overnight flight that lands early in the morning.', a: 'Red-eye' },
      { q: 'Castles line the banks of this German waterway, popular with cruise passengers.', a: 'Rhine' },
      { q: 'The historic American highway that ran from Chicago to Santa Monica.', a: 'Route 66' },
    ],
    S: [
      { q: 'The carrier based at Changi, long rated among the world\'s best.', a: 'Singapore Airlines' },
      { q: 'The shell-roofed performing arts landmark on Bennelong Point.', a: 'Sydney Opera House' },
      { q: 'The main airport of the Netherlands, built below sea level.', a: 'Schiphol' },
      { q: 'A deliberate break of a day or more in a journey, often offered free on long-haul tickets.', a: 'Stopover' },
      { q: 'The Greek island with whitewashed villages perched on a volcanic caldera.', a: 'Santorini' },
      { q: 'The prehistoric monument of huge upright rocks on Salisbury Plain.', a: 'Stonehenge' },
      { q: 'The checkpoint where bags are screened before you reach the departure gates.', a: 'Security' },
      { q: 'Incheon airport serves this East Asian capital.', a: 'Seoul' },
      { q: 'The Egyptian waterway that links the Mediterranean to the Red Sea.', a: 'Suez Canal' },
      { q: 'The vast desert crossed on camel tours out of Morocco.', a: 'Sahara' },
      { q: 'Guarulhos airport, the busiest in South America, serves this Brazilian city.', a: 'Sao Paulo' },
      { q: 'The Andalusian city with the world\'s largest Gothic cathedral.', a: 'Seville' },
    ],
    T: [
      { q: 'The white marble mausoleum at Agra.', a: 'Taj Mahal' },
      { q: 'The airport building where passengers check in and board.', a: 'Terminal' },
      { q: 'The rough air that makes the seat belt sign come on in flight.', a: 'Turbulence' },
      { q: 'Haneda is the closer of the two main airports serving this Japanese capital.', a: 'Tokyo' },
      { q: 'Pearson airport, the busiest in Canada, serves this city.', a: 'Toronto' },
      { q: 'The largest of the Canary Islands, dominated by the Teide volcano.', a: 'Tenerife' },
      { q: 'The Southeast Asian kingdom whose beaches and temples draw tens of millions of visitors.', a: 'Thailand' },
      { q: 'The carrier that serves more countries than any other airline, hubbed at Istanbul.', a: 'Turkish Airlines' },
      { q: 'The paved apron where aircraft park and are loaded.', a: 'Tarmac' },
      { q: 'The Italian region of Chianti vineyards and hill towns.', a: 'Tuscany' },
    ],
    U: [
      { q: 'The huge red sandstone monolith in the Australian outback.', a: 'Uluru' },
      { q: 'The American carrier with hubs at Chicago and Newark.', a: 'United Airlines' },
      { q: 'The ride-hailing app travellers use instead of flagging down a taxi.', a: 'Uber' },
      { q: 'The Florence gallery that holds Botticelli\'s Birth of Venus.', a: 'Uffizi' },
      { q: 'The Argentine port billed as the world\'s southernmost city, where Antarctic cruises begin.', a: 'Ushuaia' },
      { q: 'Being moved to a better cabin than the one on your ticket.', a: 'Upgrade' },
    ],
    V: [
      { q: 'The Italian lagoon city where gondolas glide along the waterways.', a: 'Venice' },
      { q: 'The permit stamped into a travel document allowing entry to a country.', a: 'Visa' },
      { q: 'The Austrian capital famous for coffee houses and Habsburg palaces.', a: 'Vienna' },
      { q: 'The British airline founded by Richard Branson in 1984.', a: 'Virgin Atlantic' },
      { q: 'The huge waterfall on the Zambezi between Zambia and Zimbabwe.', a: 'Victoria Falls' },
      { q: 'The Canadian Pacific city between mountains and sea, a major cruise departure point.', a: 'Vancouver' },
      { q: 'The enormous royal palace south-west of Paris.', a: 'Versailles' },
    ],
    W: [
      { q: 'The place on a plane preferred by passengers who want a view.', a: 'Window seat' },
      { q: 'The aerofoil surface that generates lift on an aircraft.', a: 'Wing' },
      { q: 'Dulles airport serves this American capital.', a: 'Washington' },
      { q: 'The strong desire to travel and see the world.', a: 'Wanderlust' },
      { q: 'The Polish capital rebuilt almost from scratch after the Second World War.', a: 'Warsaw' },
      { q: 'The famous beach district of Honolulu.', a: 'Waikiki' },
      { q: 'The Hungarian low-cost airline with a purple and pink livery.', a: 'Wizz Air' },
    ],
    Y: [
      { q: 'The American national park famous for the Old Faithful geyser.', a: 'Yellowstone' },
      { q: 'The Californian park known for El Capitan and Half Dome.', a: 'Yosemite' },
      { q: 'The walled English cathedral city with a lane called the Shambles.', a: 'York' },
      { q: 'The Mexican peninsula where Chichen Itza stands.', a: 'Yucatan' },
      { q: 'Cruise boats pass the Three Gorges on this Chinese river.', a: 'Yangtze' },
    ],
  },
};
