import type { RawPack } from '../core/packs';

export const weatherDisastersPack: RawPack = {
  id: 'weather-disasters',
  name: 'Weather and Natural Disasters',
  description: 'Clouds, storms, scales and instruments, plus the volcanoes, quakes and floods that made history.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🌪️',
  accent: '#0369a1',
  letters: {
    A: [
      { q: 'A mass of snow that breaks loose and slides suddenly down a mountainside.', a: 'Avalanche' },
      { q: 'The blanket of gases held around the Earth by gravity.', a: 'Atmosphere' },
      { q: 'The instrument with spinning cups that measures wind speed.', a: 'Anemometer' },
      { q: 'The shimmering polar light display caused by solar particles striking the upper air.', a: 'Aurora', alt: ['Northern lights'] },
      { q: 'A region of high pressure that brings settled, calm, dry conditions.', a: 'Anticyclone' },
      { q: 'A smaller tremor that follows a major earthquake in the same place.', a: 'Aftershock' },
      { q: 'The mid-level cloud that forms rounded white patches in neat rows.', a: 'Altocumulus' },
      { q: 'The fine grey powder thrown high by a volcano that grounds aircraft.', a: 'Ash' },
      { q: 'The word describing a climate that is extremely dry.', a: 'Arid' },
      { q: 'An underground layer of porous rock that holds water and can be tapped by wells.', a: 'Aquifer' },
      { q: 'The US state hit by the second most powerful quake ever recorded, in 1964.', a: 'Alaska' },
      { q: 'Precipitation made corrosive by sulphur dioxide from burning coal.', a: 'Acid rain' },
    ],
    B: [
      { q: 'The instrument that measures air pressure and so helps forecast a change.', a: 'Barometer' },
      { q: 'A severe snowstorm with strong winds and almost no visibility.', a: 'Blizzard' },
      { q: 'The 0 to 12 measure of wind force devised by a British admiral.', a: 'Beaufort scale' },
      { q: 'The Australian term for a fast-spreading blaze in dry country.', a: 'Bushfire' },
      { q: 'A thin invisible glaze on the road surface that makes driving treacherous.', a: 'Black ice' },
      { q: 'A light, pleasant, gentle wind.', a: 'Breeze' },
      { q: 'The dark fine-grained rock formed when lava cools quickly.', a: 'Basalt' },
      { q: 'The low-lying delta country devastated by the Bhola cyclone of 1970.', a: 'Bangladesh' },
      { q: 'A storm whose central pressure plunges at least 24 millibars in a single day.', a: 'Bomb cyclone' },
      { q: 'The cold dry northeasterly that sweeps down onto the Adriatic coast.', a: 'Bora' },
      { q: 'The Indonesian city nearest the epicentre of the Boxing Day tsunami of 2004.', a: 'Banda Aceh' },
    ],
    C: [
      { q: 'The puffy cotton-wool fair-weather cloud with a flat base.', a: 'Cumulus' },
      { q: 'The wispy high cloud of ice crystals sometimes called mare\'s tails.', a: 'Cirrus' },
      { q: 'The name used around the Indian Ocean for a tropical revolving storm.', a: 'Cyclone' },
      { q: 'The huge basin left behind when a volcano collapses after emptying its magma chamber.', a: 'Caldera' },
      { q: 'The warm dry wind that pours down the eastern Rockies and melts snow fast.', a: 'Chinook' },
      { q: 'The change of water vapour back into liquid, forming droplets on a cold window.', a: 'Condensation' },
      { q: 'The thin white line an aircraft leaves stretched across the sky.', a: 'Contrail' },
      { q: 'The average pattern of weather in a place measured over many decades.', a: 'Climate' },
      { q: 'The towering anvil-topped cloud that brings thunder, hail and downpours.', a: 'Cumulonimbus' },
      { q: 'The spin of the planet that makes storms rotate opposite ways in the two hemispheres.', a: 'Coriolis effect' },
      { q: 'The bowl-shaped mouth at the summit of a volcano.', a: 'Crater' },
      { q: 'The advancing edge of a cooler air mass, drawn on charts with blue triangles.', a: 'Cold front' },
      { q: 'The thin high veil of cloud that puts a halo around the sun.', a: 'Cirrostratus' },
      { q: 'The rising of warm air and sinking of cool air that keeps the atmosphere stirred.', a: 'Convection' },
    ],
    D: [
      { q: 'A long spell of abnormally low rainfall that dries up crops and reservoirs.', a: 'Drought' },
      { q: 'The moisture that settles on grass overnight as the ground cools.', a: 'Dew' },
      { q: 'The type of weather scanning that detects motion inside a storm and reveals rotation.', a: 'Doppler radar' },
      { q: 'A small whirling column of grit that spins across dry ground on a hot day.', a: 'Dust devil' },
      { q: 'The 1930s catastrophe on the American plains when ploughed-up soil blew away in black blizzards.', a: 'Dust Bowl' },
      { q: 'The process by which fertile land turns barren at the edge of a dry region.', a: 'Desertification' },
      { q: 'The temperature at which air becomes saturated and moisture starts to form.', a: 'Dew point' },
      { q: 'Very fine, light rain that falls steadily for hours.', a: 'Drizzle' },
      { q: 'Clearing of trees that leaves hillsides prone to landslides and flooding.', a: 'Deforestation' },
    ],
    E: [
      { q: 'The sudden shaking of the ground when rock slips along a fault.', a: 'Earthquake' },
      { q: 'The calm clear centre of a hurricane.', a: 'Eye' },
      { q: 'The Pacific warming pattern that upends weather worldwide every few years.', a: 'El Nino' },
      { q: 'The point on the surface directly above where an earthquake begins.', a: 'Epicentre', alt: ['Epicenter'] },
      { q: 'The violent expulsion of lava, ash and gas from a volcano.', a: 'Eruption' },
      { q: 'The change of liquid water into vapour as it is warmed.', a: 'Evaporation' },
      { q: 'The imaginary line around the middle of the Earth where the sun beats down most directly.', a: 'Equator' },
      { q: 'The gradual wearing away of land by wind, water and ice.', a: 'Erosion' },
      { q: 'Europe\'s most active volcano, on the island of Sicily.', a: 'Etna' },
      { q: 'The ring of fierce thunderstorms surrounding the calm centre of a hurricane.', a: 'Eye wall' },
    ],
    F: [
      { q: 'The overflowing of water onto land that is normally dry.', a: 'Flood' },
      { q: 'Cloud that forms at ground level and cuts visibility to a few metres.', a: 'Fog' },
      { q: 'The white crystals that form on surfaces when the temperature dips below freezing.', a: 'Frost' },
      { q: 'The rating from 0 to 5 that measures tornado damage, named for a Japanese-American scientist.', a: 'Fujita scale' },
      { q: 'A sudden torrent that fills a dry gully within minutes of heavy rain.', a: 'Flash flood' },
      { q: 'A crack in the Earth\'s crust along which blocks of rock slide past each other.', a: 'Fault' },
      { q: 'The rotating cone hanging from a storm base before it reaches the ground.', a: 'Funnel cloud' },
      { q: 'The warm dry Alpine wind that descends the sheltered side of a mountain range.', a: 'Foehn' },
      { q: 'Liquid drops that turn to ice the instant they touch a cold surface.', a: 'Freezing rain' },
      { q: 'The temperature scale on which water freezes at 32 degrees.', a: 'Fahrenheit' },
      { q: 'A long crack from which lava can erupt in a curtain of fire.', a: 'Fissure' },
    ],
    G: [
      { q: 'A very strong wind, rated force 8 on the Beaufort scale.', a: 'Gale' },
      { q: 'A slow-moving river of ice that carves out a valley as it creeps.', a: 'Glacier' },
      { q: 'The trapping of heat near the surface by gases in the atmosphere.', a: 'Greenhouse effect' },
      { q: 'Soft white pellets formed when snowflakes pick up a coating of frozen droplets.', a: 'Graupel' },
      { q: 'A hot spring that periodically blasts steam and boiling water into the air.', a: 'Geyser' },
      { q: 'A brief, sudden increase in wind speed.', a: 'Gust' },
      { q: 'The Texas city destroyed by the deadliest hurricane in United States history, in 1900.', a: 'Galveston' },
      { q: 'The long-term rise in the planet\'s average temperature.', a: 'Global warming' },
      { q: 'The warm Atlantic current that keeps northwest Europe mild for its latitude.', a: 'Gulf Stream' },
      { q: 'The adjective for energy drawn from heat stored inside the Earth.', a: 'Geothermal' },
    ],
    H: [
      { q: 'The Atlantic name for a tropical storm with winds above 74 miles per hour.', a: 'Hurricane' },
      { q: 'Balls of ice that fall from a thunderstorm, sometimes as big as golf balls.', a: 'Hail' },
      { q: 'The amount of water vapour present in the air.', a: 'Humidity' },
      { q: 'A thin suspension of dust or smoke that dulls the horizon.', a: 'Haze' },
      { q: 'The instrument that measures how much moisture the air is holding.', a: 'Hygrometer' },
      { q: 'A prolonged spell of unusually hot weather.', a: 'Heatwave' },
      { q: 'The calm high-pressure belts near 30 degrees where sailing ships used to stall.', a: 'Horse latitudes' },
      { q: 'The immense wall of dust driven ahead of a thunderstorm in Sudan and Arizona.', a: 'Haboob' },
      { q: 'The dangerous fall in body temperature suffered by people trapped in the cold.', a: 'Hypothermia' },
      { q: 'The metric unit used on weather charts for air pressure.', a: 'Hectopascal' },
    ],
    I: [
      { q: 'The line on a weather map joining points of equal air pressure.', a: 'Isobar' },
      { q: 'The event that coats trees and power lines in a heavy glaze and snaps them.', a: 'Ice storm' },
      { q: 'A mass of freshwater ice that has broken from a glacier and floats out to sea.', a: 'Iceberg' },
      { q: 'The situation where air grows warmer with height, trapping pollution below.', a: 'Inversion' },
      { q: 'The line on a map joining places of equal temperature.', a: 'Isotherm' },
      { q: 'The North Atlantic island whose 2010 eruption shut down European airspace.', a: 'Iceland' },
      { q: 'The body of water where the Boxing Day tsunami of 2004 began.', a: 'Indian Ocean' },
      { q: 'The electrically charged upper layer of the atmosphere that bounces radio waves back.', a: 'Ionosphere' },
    ],
    J: [
      { q: 'The narrow ribbon of very fast high-altitude wind that steers storm tracks.', a: 'Jet stream' },
      { q: 'The country struck by a magnitude 9 quake and huge sea waves on 11 March 2011.', a: 'Japan' },
      { q: 'The crowded Indonesian island over which the volcano Merapi looms.', a: 'Java' },
    ],
    K: [
      { q: 'The Indonesian volcano whose 1883 blast was heard three thousand miles away.', a: 'Krakatoa' },
      { q: 'The 2005 hurricane that breached levees and drowned much of New Orleans.', a: 'Katrina' },
      { q: 'The Hawaiian volcano that has erupted almost continuously for decades.', a: 'Kilauea' },
      { q: 'The temperature scale that begins at absolute zero.', a: 'Kelvin' },
      { q: 'The Japanese port city wrecked by a devastating earthquake in 1995.', a: 'Kobe' },
      { q: 'The type of wind formed by cold dense air draining downhill, fiercest in Antarctica.', a: 'Katabatic' },
    ],
    L: [
      { q: 'The huge electrical discharge between cloud and ground during a thunderstorm.', a: 'Lightning' },
      { q: 'Molten rock once it has reached the surface and flows.', a: 'Lava' },
      { q: 'The downhill collapse of soil and rock, often triggered by heavy rain.', a: 'Landslide' },
      { q: 'The cooling phase of the Pacific cycle, opposite to its warm counterpart.', a: 'La Nina' },
      { q: 'The deadly slurry of volcanic ash and melted ice that races down a mountain valley.', a: 'Lahar' },
      { q: 'The European capital flattened by quake, fire and sea waves on All Saints Day 1755.', a: 'Lisbon' },
      { q: 'The process in which shaken wet soil behaves like a fluid and buildings sink into it.', a: 'Liquefaction' },
      { q: 'The raised embankment built along a river to hold back high water.', a: 'Levee' },
    ],
    M: [
      { q: 'The seasonal wind reversal that brings months of heavy rain to South Asia.', a: 'Monsoon' },
      { q: 'A light suspension of water droplets in the air, thinner than fog.', a: 'Mist' },
      { q: 'The scientific study of the atmosphere and its weather.', a: 'Meteorology' },
      { q: 'Molten rock while it is still beneath the surface.', a: 'Magma' },
      { q: 'A flow of saturated earth that buries roads and houses after a downpour.', a: 'Mudslide' },
      { q: 'The scale that rates an earthquake by the damage observed rather than the energy released.', a: 'Mercalli scale' },
      { q: 'A small violent downward blast of air from a storm, notoriously hazardous to aircraft.', a: 'Microburst' },
      { q: 'The Philippine volcano whose 1991 eruption cooled the entire planet for two years.', a: 'Mount Pinatubo', alt: ['Pinatubo'] },
      { q: 'The cold northwesterly that funnels down the Rhone valley into Provence.', a: 'Mistral' },
      { q: 'The unit of pressure in which 1013 is roughly average at sea level.', a: 'Millibar' },
    ],
    N: [
      { q: 'The thick grey cloud sheet that delivers steady rain for hours on end.', a: 'Nimbostratus' },
      { q: 'The powerful winter storm that batters the Atlantic seaboard of the United States with snow.', a: 'Nor\'easter' },
      { q: 'The gas that makes up 78 percent of the air we breathe.', a: 'Nitrogen' },
      { q: 'The Louisiana city where most of the built-up area flooded after levees failed in 2005.', a: 'New Orleans' },
      { q: 'The Latin word for a rain-bearing cloud, used in several cloud names.', a: 'Nimbus' },
    ],
    O: [
      { q: 'The three-atom form of oxygen in a high layer that shields us from ultraviolet rays.', a: 'Ozone' },
      { q: 'The boundary formed when a cold air mass catches up with a warm one and lifts it clear of the ground.', a: 'Occluded front' },
      { q: 'The word for a sky completely covered by cloud.', a: 'Overcast' },
      { q: 'A large continuous flow of seawater that carries heat around the globe.', a: 'Ocean current' },
      { q: 'The gas making up about 21 percent of the atmosphere and needed for anything to burn.', a: 'Oxygen' },
      { q: 'Precipitation produced when moist air is forced to rise over a mountain barrier.', a: 'Orographic rainfall' },
      { q: 'A fertile watered spot in the middle of a desert.', a: 'Oasis' },
    ],
    P: [
      { q: 'The collective term for rain, snow, sleet and hail.', a: 'Precipitation' },
      { q: 'Ground that stays frozen all year round and is thawing dangerously as the climate warms.', a: 'Permafrost' },
      { q: 'The searing avalanche of gas and rock that races down a volcano at a hundred miles an hour.', a: 'Pyroclastic flow' },
      { q: 'The Roman town buried under volcanic ash in AD 79.', a: 'Pompeii' },
      { q: 'The weight of air above a place, marked high or low on a forecast chart.', a: 'Pressure' },
      { q: 'The theory that the crust is split into slabs that drift, collide and grind past each other.', a: 'Plate tectonics' },
      { q: 'The ring of circling cold air whose weakening lets Arctic blasts reach mid latitudes.', a: 'Polar vortex' },
      { q: 'The frothy volcanic rock so full of holes that it floats on water.', a: 'Pumice' },
      { q: 'The direction from which the wind most often blows in a given region.', a: 'Prevailing winds' },
      { q: 'The name for the most explosive eruption style, after a Roman writer who described one.', a: 'Plinian' },
    ],
    Q: [
      { q: 'Waterlogged sand that gives way underfoot and traps the unwary.', a: 'Quicksand' },
      { q: 'The Australian state whose towns were inundated in the great floods of 2010 and 2011.', a: 'Queensland' },
    ],
    R: [
      { q: 'Liquid water falling from cloud to ground.', a: 'Rain' },
      { q: 'The arc of colours seen when sunlight is bent and split by falling droplets.', a: 'Rainbow' },
      { q: 'The logarithmic measure of earthquake magnitude devised in 1935.', a: 'Richter scale' },
      { q: 'The system that bounces radio pulses off droplets to map storms.', a: 'Radar' },
      { q: 'The simple funnel and cylinder used to record how much has fallen.', a: 'Rain gauge' },
      { q: 'The horseshoe-shaped belt around the Pacific where most volcanoes and quakes occur.', a: 'Ring of Fire' },
      { q: 'Water that flows over the surface instead of soaking in, swelling rivers after a storm.', a: 'Runoff' },
      { q: 'The feathery ice deposit left when supercooled fog freezes onto branches and wires.', a: 'Rime' },
      { q: 'The dense tropical woodland where more than 2,000 millimetres falls every year.', a: 'Rainforest' },
      { q: 'The dry zone on the sheltered side of a mountain range.', a: 'Rain shadow' },
    ],
    S: [
      { q: 'Frozen crystals that fall from cloud and settle white on the ground.', a: 'Snow' },
      { q: 'The messy mix of rain and partly melted ice pellets.', a: 'Sleet' },
      { q: 'The wall of seawater pushed ashore by a hurricane, usually its biggest killer.', a: 'Storm surge' },
      { q: 'The featureless low cloud layer that sits over a town like a grey blanket.', a: 'Stratus' },
      { q: 'The instrument that traces ground shaking as a jagged line on a rolling chart.', a: 'Seismograph' },
      { q: 'The hot dusty wind that blows off the Sahara across the Mediterranean.', a: 'Sirocco' },
      { q: 'A desert event in which wind lifts loose grains into a blinding wall.', a: 'Sandstorm' },
      { q: 'A cooler dark patch on the solar surface, counted through an eleven-year cycle.', a: 'Sunspot' },
      { q: 'The long-lived rotating thunderstorm that spawns the strongest tornadoes.', a: 'Supercell' },
      { q: 'The choking mix of fog and pollution that killed thousands in London in 1952.', a: 'Smog' },
      { q: 'The calm atmospheric layer above the weather where airliners cruise.', a: 'Stratosphere' },
      { q: 'The sinking of one tectonic plate beneath another, the source of the largest quakes.', a: 'Subduction' },
      { q: 'The famous Californian fault where two plates grind past one another.', a: 'San Andreas' },
      { q: 'The category 1 to 5 rating of hurricane strength.', a: 'Saffir-Simpson scale' },
      { q: 'A sudden sharp burst of wind, often with rain, running along a storm line.', a: 'Squall' },
      { q: 'The pit that opens when underground limestone dissolves and the surface caves in.', a: 'Sinkhole' },
      { q: 'The 2012 superstorm that flooded the New York subway.', a: 'Sandy' },
    ],
    T: [
      { q: 'The violently rotating column of air that touches both cloud and ground.', a: 'Tornado' },
      { q: 'The series of giant sea waves generated by an undersea quake.', a: 'Tsunami' },
      { q: 'The sound made by air exploding outward from a lightning channel.', a: 'Thunder' },
      { q: 'The name for a tropical cyclone in the northwest Pacific.', a: 'Typhoon' },
      { q: 'The lowest atmospheric layer, where nearly all weather happens.', a: 'Troposphere' },
      { q: 'A slight shaking of the ground, weaker than a full quake.', a: 'Tremor' },
      { q: 'The steady easterly flow near the tropics that once carried sailing ships west.', a: 'Trade winds' },
      { q: 'The Indonesian volcano whose 1815 eruption caused the year without a summer.', a: 'Tambora' },
      { q: 'The instrument used to measure air temperature.', a: 'Thermometer' },
      { q: 'The nickname for the central corridor of the United States where twisters are most frequent.', a: 'Tornado Alley' },
      { q: 'The general term for all the fragments blasted out by a volcano.', a: 'Tephra' },
    ],
    U: [
      { q: 'The rising current of air inside a storm that holds hailstones aloft.', a: 'Updraft' },
      { q: 'The invisible solar radiation that causes sunburn, reported as an index.', a: 'Ultraviolet' },
      { q: 'The seaward pull beneath breaking waves that drags swimmers away from the beach.', a: 'Undertow' },
      { q: 'The raising of land by tectonic forces, slowly building mountain ranges.', a: 'Uplift' },
      { q: 'The effect that makes a city several degrees warmer than the countryside around it.', a: 'Urban heat island' },
    ],
    V: [
      { q: 'A vent in the crust through which lava, ash and gas escape.', a: 'Volcano' },
      { q: 'Water in its invisible gaseous state in the air.', a: 'Vapour', alt: ['Vapor', 'Water vapour'] },
      { q: 'The Italian volcano overlooking Naples that buried Pompeii.', a: 'Vesuvius' },
      { q: 'A whirling mass of air or water spinning around a centre.', a: 'Vortex' },
      { q: 'The forecast measure of how far you can clearly see.', a: 'Visibility' },
      { q: 'The scientist who studies eruptions and monitors restless mountains.', a: 'Volcanologist' },
      { q: 'The global cooling that follows a huge eruption veiling the sun with dust.', a: 'Volcanic winter' },
    ],
    W: [
      { q: 'Air moving from an area of high pressure towards one of low pressure.', a: 'Wind' },
      { q: 'A tornado that forms over the sea or a lake.', a: 'Waterspout' },
      { q: 'A small rotating column of air that lifts leaves and dust as it passes.', a: 'Whirlwind' },
      { q: 'An uncontrolled blaze spreading through forest or scrub.', a: 'Wildfire' },
      { q: 'The rooftop arrow, often shaped like a cockerel, that shows which way the wind blows.', a: 'Weather vane' },
      { q: 'The measure of how much colder moving air makes exposed skin feel.', a: 'Wind chill' },
      { q: 'The advancing edge of a milder air mass, drawn with red half circles on a chart.', a: 'Warm front' },
      { q: 'The endless circuit of evaporation, condensation and precipitation.', a: 'Water cycle' },
      { q: 'The instrument-carrying craft released twice a day to sound the upper air.', a: 'Weather balloon' },
      { q: 'The blinding condition in a blizzard where ground and sky merge into one.', a: 'Whiteout' },
    ],
    Y: [
      { q: 'The Chinese river whose catastrophic 1931 flood killed millions.', a: 'Yangtze' },
      { q: 'The American national park sitting on top of a giant volcanic caldera.', a: 'Yellowstone' },
      { q: 'The Chinese waterway nicknamed China\'s Sorrow for its devastating breaches.', a: 'Yellow River' },
    ],
    Z: [
      { q: 'The poetic word for a soft gentle west wind.', a: 'Zephyr' },
      { q: 'The hot dry wind that descends the Argentine side of the Andes.', a: 'Zonda' },
    ],
  },
};
