import type { RawPack } from '../core/packs';

export const worldReligionsPack: RawPack = {
  id: 'world-religions',
  name: 'World Religions',
  description: 'Festivals, texts, places of worship and traditions around the world.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🕊️',
  accent: '#0d9488',
  letters: {
    A: [
      { q: 'The four-week season of preparation kept in many churches before 25 December.', a: 'Advent' },
      { q: 'The general English term for ritual washing before an act of worship.', a: 'Ablution' },
      { q: 'The call to prayer announced from a minaret five times each day.', a: 'Adhan' },
      { q: 'The Sanskrit principle of non-violence that is central to Jain teaching.', a: 'Ahimsa' },
      { q: 'The Arabic word for God used by Muslims and by Arabic-speaking Christians.', a: 'Allah' },
      { q: 'The Punjabi city that is home to Harmandir Sahib.', a: 'Amritsar' },
      { q: 'The Christian group in North America known for plain dress and horse-drawn buggies.', a: 'Amish' },
      { q: 'The word describing the Christian communion whose mother church stands at Canterbury.', a: 'Anglican' },
      { q: 'A heavenly messenger described in Jewish, Christian and Muslim scripture.', a: 'Angel' },
      { q: 'Any one of the twelve close followers chosen by Jesus during his ministry.', a: 'Apostle' },
      { q: 'The Semitic language, related to Hebrew, in which parts of the book of Daniel are written.', a: 'Aramaic' },
      { q: 'The cabinet in a synagogue in which the Torah scrolls are kept.', a: 'Ark' },
      { q: 'The Hindu ritual in which lamps are waved in front of an image of a deity.', a: 'Arti' },
      { q: 'The Christian feast marking Jesus being taken up into heaven forty days after Easter.', a: 'Ascension' },
      { q: 'The day that begins Lent in Western churches, marked by a smudge on the forehead.', a: 'Ash Wednesday' },
      { q: 'The hill town in Umbria linked with Saint Francis.', a: 'Assisi' },
      { q: 'The north Indian city that the Ramayana describes as the home of Rama.', a: 'Ayodhya' },
    ],
    B: [
      { q: 'The spring harvest festival of the Punjab, an important day for Sikhs.', a: 'Baisakhi' },
      { q: 'The religion whose Indian house of worship in Delhi is shaped like a lotus flower.', a: 'Baha\'i Faith' },
      { q: 'The Persian-born founder who announced his mission in Baghdad in 1863 and taught the oneness of humanity.', a: 'Baha\'u\'llah' },
      { q: 'The Christian rite of initiation performed with water.', a: 'Baptism' },
      { q: 'The Jewish ceremony marking a boy reaching religious adulthood at thirteen.', a: 'Bar Mitzvah' },
      { q: 'The title of honour the pope gives to certain major churches.', a: 'Basilica' },
      { q: 'The Jewish ceremony marking a girl reaching religious adulthood.', a: 'Bat Mitzvah' },
      { q: 'The monastic order that lives by a sixth-century rule of prayer and work.', a: 'Benedictine' },
      { q: 'The town Christians honour as the birthplace of Jesus.', a: 'Bethlehem' },
      { q: 'The Hindu scripture set on a battlefield in which Arjuna receives counsel before a war.', a: 'Bhagavad Gita' },
      { q: 'The name for the collected scriptures of Christianity.', a: 'Bible' },
      { q: 'The decorative mark worn on the forehead by many Hindu women.', a: 'Bindi' },
      { q: 'The senior Christian minister who has charge of a diocese.', a: 'Bishop' },
      { q: 'The town in the Indian state of Bihar where Buddhists honour the site of the awakening.', a: 'Bodh Gaya' },
      { q: 'The sacred fig beneath which Siddhartha is said to have gained awakening.', a: 'Bodhi Tree' },
      { q: 'The Hindu creator deity of the trimurti.', a: 'Brahma' },
      { q: 'The priestly class in the traditional fourfold Hindu social order.', a: 'Brahmin' },
      { q: 'The title meaning "awakened one" given to Siddhartha Gautama.', a: 'Buddha' },
    ],
    C: [
      { q: 'A historic title for the leader of the Muslim community.', a: 'Caliph' },
      { q: 'The English cathedral city whose archbishop leads the Church of England.', a: 'Canterbury' },
      { q: 'The trained singer who leads the sung prayers in a synagogue.', a: 'Cantor' },
      { q: 'The long close-fitting robe worn by Christian clergy.', a: 'Cassock' },
      { q: 'The church that holds a bishop\'s official seat.', a: 'Cathedral' },
      { q: 'The cup that holds the wine at a Christian communion service.', a: 'Chalice' },
      { q: 'The Christian festival on 25 December that celebrates the birth of Jesus.', a: 'Christmas' },
      { q: 'The canopy under which a Jewish couple stands at a wedding.', a: 'Chuppah' },
      { q: 'The Christian sharing of consecrated bread and wine at a service.', a: 'Communion' },
      { q: 'The Christian rite in which a baptised person publicly affirms the faith.', a: 'Confirmation' },
      { q: 'The Chinese ethical tradition based on the teachings of Kong Fuzi.', a: 'Confucianism' },
      { q: 'The house in which a community of nuns lives.', a: 'Convent' },
      { q: 'The word describing the ancient Christian church of Egypt.', a: 'Coptic' },
      { q: 'The Catholic feast honouring the Eucharist with outdoor processions.', a: 'Corpus Christi' },
      { q: 'The farm animal that Hindu tradition holds sacred and protects.', a: 'Cow' },
      { q: 'The thin moon shape widely used as a symbol of Islam.', a: 'Crescent' },
      { q: 'The central symbol of Christianity, recalling the death of Jesus.', a: 'Cross' },
    ],
    D: [
      { q: 'The title held by the senior teacher of the Gelug school of Tibetan Buddhism.', a: 'Dalai Lama' },
      { q: 'The Punjabi name for the turban worn by many Sikh men.', a: 'Dastar' },
      { q: 'The ordained assistant who serves in a rank below a priest in many churches.', a: 'Deacon' },
      { q: 'The Sanskrit word for duty, law and the right way of living in Indian religions.', a: 'Dharma' },
      { q: 'The Muslim practice of the repeated remembrance of God, often counted on beads.', a: 'Dhikr' },
      { q: 'The district of churches placed under the care of a bishop.', a: 'Diocese' },
      { q: 'The Hindu festival of lights held in the autumn.', a: 'Diwali' },
      { q: 'The gold-topped shrine that stands on the Haram al-Sharif in Jerusalem.', a: 'Dome of the Rock' },
      { q: 'The four-sided spinning top played with at Hanukkah.', a: 'Dreidel' },
      { q: 'The Buddhist term for the suffering that marks ordinary existence.', a: 'Dukkha' },
      { q: 'The Hindu goddess honoured at the great autumn festival of Bengal.', a: 'Durga' },
    ],
    E: [
      { q: 'The Christian festival that celebrates Jesus rising from the dead.', a: 'Easter' },
      { q: 'The Muslim festival that marks the end of Ramadan.', a: 'Eid al-Fitr' },
      { q: 'The Muslim festival of sacrifice kept in the month of Dhul Hijjah.', a: 'Eid al-Adha' },
      { q: 'The Buddhist way of practice made up of right view, right speech and six further steps.', a: 'Eightfold Path' },
      { q: 'The English word used for the awakening that Buddhists call bodhi.', a: 'Enlightenment' },
      { q: 'The Christian feast on 6 January that recalls the visit of the Magi.', a: 'Epiphany' },
      { q: 'The Christian sacrament of bread and wine, from a Greek word for thanksgiving.', a: 'Eucharist' },
      { q: 'The sung evening service of the Church of England.', a: 'Evensong' },
      { q: 'The book of the Hebrew Bible that tells of the escape from Egypt.', a: 'Exodus' },
    ],
    F: [
      { q: 'Going without food for religious reasons, as Muslims do in Ramadan.', a: 'Fasting' },
      { q: 'The opening chapter of the Quran, recited in every Muslim prayer.', a: 'Fatiha' },
      { q: 'The core duties of Islam that include prayer, almsgiving and pilgrimage.', a: 'Five Pillars' },
      { q: 'The stone basin in a church that holds the water for baptisms.', a: 'Font' },
      { q: 'The Buddha\'s central teaching about suffering, its cause, its ending and the way there.', a: 'Four Noble Truths' },
      { q: 'The fragrant resin burned as incense and named among the gifts of the Magi.', a: 'Frankincense' },
      { q: 'A member of an order such as the Franciscans who lives by preaching rather than in an enclosed house.', a: 'Friar' },
    ],
    G: [
      { q: 'The great north Indian river that Hindus revere as a goddess.', a: 'Ganges' },
      { q: 'The opening book of the Hebrew Bible and of the Christian Old Testament.', a: 'Genesis' },
      { q: 'The Sikh shrine in the Punjab also known as Harmandir Sahib.', a: 'Golden Temple' },
      { q: 'Any of the four accounts of the life of Jesus that open the Christian New Testament.', a: 'Gospel' },
      { q: 'The Sikh place of worship.', a: 'Gurdwara' },
      { q: 'The Sikh scripture honoured as a living teacher.', a: 'Guru Granth Sahib' },
      { q: 'The founder of Sikhism, born in the Punjab in 1469.', a: 'Guru Nanak' },
    ],
    H: [
      { q: 'A recorded saying or action of the Prophet Muhammad.', a: 'Hadith' },
      { q: 'The book read aloud at the Passover meal.', a: 'Haggadah' },
      { q: 'The pilgrimage to Mecca that Muslims make in the twelfth month of their calendar.', a: 'Hajj' },
      { q: 'The Arabic word for what is permitted, used especially of food.', a: 'Halal' },
      { q: 'The Arabic word for what is forbidden, the opposite of halal.', a: 'Haram' },
      { q: 'The eight-day Jewish festival of lights.', a: 'Hanukkah' },
      { q: 'The Hindu deity in monkey form who serves Rama.', a: 'Hanuman' },
      { q: 'The short Jewish ceremony with wine, spices and a candle that closes the day of rest.', a: 'Havdalah' },
      { q: 'The headscarf worn by many Muslim women.', a: 'Hijab' },
      { q: 'The name of the Islamic lunar calendar era, counted from the migration to Medina.', a: 'Hijri' },
      { q: 'The Hindu spring festival famous for the throwing of coloured powder.', a: 'Holi' },
      { q: 'A song of praise sung by a Christian congregation.', a: 'Hymn' },
    ],
    I: [
      { q: 'The painted image of Christ or a saint venerated in Orthodox churches.', a: 'Icon' },
      { q: 'The evening meal that breaks the daily fast during Ramadan.', a: 'Iftar' },
      { q: 'The plain white cloth worn by male pilgrims at Mecca.', a: 'Ihram' },
      { q: 'The person who leads the prayers in a mosque.', a: 'Imam' },
      { q: 'Fragrant material burned to make sweet smoke during worship in many traditions.', a: 'Incense' },
      { q: 'The Hebrew prophet whose book comes just before Jeremiah.', a: 'Isaiah' },
      { q: 'The Japanese city whose grand shrine honours the sun goddess Amaterasu.', a: 'Ise' },
    ],
    J: [
      { q: 'The Indian religion that teaches strict non-violence and is symbolised by an open palm.', a: 'Jainism' },
      { q: 'The collection of stories about the earlier lives of the Buddha.', a: 'Jataka' },
      { q: 'The city held holy by Jews, Christians and Muslims alike.', a: 'Jerusalem' },
      { q: 'The teacher from Nazareth whose life is told in the Gospels.', a: 'Jesus' },
      { q: 'The river that runs from the Sea of Galilee to the Dead Sea, where John baptised.', a: 'Jordan' },
      { q: 'A special holy year proclaimed by the pope.', a: 'Jubilee' },
      { q: 'The religion whose scriptures include the Torah and the Talmud.', a: 'Judaism' },
      { q: 'The Friday congregational prayer of Muslims.', a: 'Jumuah' },
    ],
    K: [
      { q: 'The cube-shaped building at the centre of the Grand Mosque in Mecca.', a: 'Kaaba' },
      { q: 'The Jewish prayer of praise that mourners recite.', a: 'Kaddish' },
      { q: 'The word for the spirits and deities honoured at the shrines of Japan.', a: 'Kami' },
      { q: 'The Indian idea that a person\'s actions shape their future experience.', a: 'Karma' },
      { q: 'The double-edged sword at the centre of the Sikh emblem.', a: 'Khanda' },
      { q: 'The small skullcap worn by many Jewish men.', a: 'Kippah' },
      { q: 'The small ceremonial dagger carried by initiated Sikhs.', a: 'Kirpan' },
      { q: 'The devotional group singing practised in gurdwaras and temples.', a: 'Kirtan' },
      { q: 'The puzzling question set for a student in Zen practice.', a: 'Koan' },
      { q: 'The word for food that is fit to eat under Jewish law.', a: 'Kosher' },
      { q: 'The Hindu deity often shown as a blue-skinned flute player.', a: 'Krishna' },
    ],
    L: [
      { q: 'The Hindu goddess of wealth honoured at Diwali.', a: 'Lakshmi' },
      { q: 'The Tibetan word for a religious teacher.', a: 'Lama' },
      { q: 'The free community kitchen attached to a gurdwara.', a: 'Langar' },
      { q: 'The forty-day Christian season of penitence before Easter.', a: 'Lent' },
      { q: 'The set order of words and actions for public worship.', a: 'Liturgy' },
      { q: 'The water flower used as a symbol of purity in Buddhism and Hinduism.', a: 'Lotus' },
      { q: 'The French town whose spring draws Catholic pilgrims who seek healing.', a: 'Lourdes' },
      { q: 'The palm branch waved with a citron during Sukkot.', a: 'Lulav' },
    ],
    M: [
      { q: 'The wise visitors from the east in the Christmas story.', a: 'Magi' },
      { q: 'The Jain teacher, a contemporary of the Buddha, honoured as the twenty-fourth tirthankara.', a: 'Mahavira' },
      { q: 'The string of beads used for counting recitations in Hindu and Buddhist practice.', a: 'Mala' },
      { q: 'The Hindu name for a temple.', a: 'Mandir' },
      { q: 'A sacred sound or phrase repeated during Hindu and Buddhist meditation.', a: 'Mantra' },
      { q: 'The Catholic celebration of the Eucharist.', a: 'Mass' },
      { q: 'The city in Arabia that Muslims face when they pray.', a: 'Mecca' },
      { q: 'The city in Arabia where the Prophet Muhammad is buried.', a: 'Medina' },
      { q: 'The disciplined practice of quiet mental focus, central to Buddhist training.', a: 'Meditation' },
      { q: 'The ancient seven-branched lampstand used as a Jewish symbol.', a: 'Menorah' },
      { q: 'The niche in the wall of a mosque that shows the direction of Mecca.', a: 'Mihrab' },
      { q: 'The slender tower of a mosque from which the call to prayer is given.', a: 'Minaret' },
      { q: 'The Hebrew word for a commandment or a good deed.', a: 'Mitzvah' },
      { q: 'The building in which a community of monks lives.', a: 'Monastery' },
      { q: 'A man who takes religious vows and lives in a community under a rule.', a: 'Monk' },
      { q: 'The prophet who led the Israelites out of slavery in Egypt.', a: 'Moses' },
      { q: 'The Muslim place of worship.', a: 'Mosque' },
      { q: 'The Prophet of Islam, born in Mecca in about 570.', a: 'Muhammad' },
      { q: 'The opening month of the Islamic calendar.', a: 'Muharram' },
    ],
    N: [
      { q: 'The scene of the birth of Jesus that is modelled in Christmas cribs.', a: 'Nativity' },
      { q: 'The nine-night Hindu festival honouring the goddess in her many forms.', a: 'Navaratri' },
      { q: 'The town in Galilee where Jesus grew up.', a: 'Nazareth' },
      { q: 'The part of Christian scripture that opens with Matthew, Mark, Luke and John.', a: 'New Testament' },
      { q: 'The Buddhist goal of release from suffering and rebirth.', a: 'Nirvana' },
      { q: 'The man in the book of Genesis who built a great vessel before the flood.', a: 'Noah' },
      { q: 'A woman who takes religious vows and lives in a convent.', a: 'Nun' },
    ],
    O: [
      { q: 'The Christian name for the scriptures shared with the Jewish tradition.', a: 'Old Testament' },
      { q: 'The sacred syllable chanted at the beginning of Hindu prayers.', a: 'Om' },
      { q: 'The ceremony in which a person is made a priest or minister.', a: 'Ordination' },
      { q: 'The large pipe instrument that traditionally accompanies hymns in a church.', a: 'Organ' },
      { q: 'The word describing the eastern Christian churches led by patriarchs.', a: 'Orthodox' },
    ],
    P: [
      { q: 'The tiered tower built at Buddhist sites across East Asia.', a: 'Pagoda' },
      { q: 'The ancient language of the Theravada Buddhist scriptures.', a: 'Pali' },
      { q: 'The local district served by one church and its priest.', a: 'Parish' },
      { q: 'The Jewish spring festival that recalls the escape from slavery in Egypt.', a: 'Passover' },
      { q: 'The title of the most senior bishop in an Eastern Orthodox church.', a: 'Patriarch' },
      { q: 'The Christian feast fifty days after Easter that marks the coming of the Holy Spirit.', a: 'Pentecost' },
      { q: 'A journey made to a holy place as an act of devotion.', a: 'Pilgrimage' },
      { q: 'The bishop of Rome, who heads the Catholic Church.', a: 'Pope' },
      { q: 'The blessed food shared out after a Hindu ceremony.', a: 'Prasad' },
      { q: 'The person who leads worship and the sacraments in a Catholic parish.', a: 'Priest' },
      { q: 'The book of one hundred and fifty songs in the Hebrew Bible.', a: 'Psalms' },
      { q: 'The Hindu act of worship offering light, flowers and food to a deity.', a: 'Puja' },
      { q: 'The raised stand from which a sermon is preached.', a: 'Pulpit' },
      { q: 'The Jewish festival with costumes and the reading of the scroll of Esther.', a: 'Purim' },
    ],
    Q: [
      { q: 'The Chinese term for the life energy that flows through the body.', a: 'Qi' },
      { q: 'The direction that Muslims turn to face during prayer.', a: 'Qibla' },
      { q: 'The Chinese tomb-sweeping festival held in early April.', a: 'Qingming' },
      { q: 'The common name for a member of the Religious Society of Friends.', a: 'Quaker' },
      { q: 'The holy book of Islam, which Muslims believe was revealed to the Prophet Muhammad.', a: 'Quran' },
    ],
    R: [
      { q: 'The teacher and leader of a Jewish congregation.', a: 'Rabbi' },
      { q: 'The Muslim month of daily fasting from dawn until sunset.', a: 'Ramadan' },
      { q: 'The Sanskrit epic in which a prince rescues his wife from Lanka.', a: 'Ramayana' },
      { q: 'The rebirth of a soul in a new body, taught in the religions of India.', a: 'Reincarnation' },
      { q: 'The decorated container that holds the remains of a saint.', a: 'Reliquary' },
      { q: 'The Christian belief that Jesus rose from the dead on the third day.', a: 'Resurrection' },
      { q: 'The string of beads that Catholics use to count their prayers.', a: 'Rosary' },
      { q: 'The Jewish festival that opens the ten days of repentance in early autumn.', a: 'Rosh Hashanah' },
    ],
    S: [
      { q: 'The weekly day of rest commanded in the Hebrew Bible.', a: 'Sabbath' },
      { q: 'A Christian rite regarded as an outward sign of inward grace.', a: 'Sacrament' },
      { q: 'The Hindu holy man who gives up possessions and wanders.', a: 'Sadhu' },
      { q: 'A person a church recognises for holiness of life.', a: 'Saint' },
      { q: 'The Arabic name for the five daily prayers of Islam.', a: 'Salat' },
      { q: 'The Buddhist community of monks and nuns.', a: 'Sangha' },
      { q: 'The ancient language of the Hindu scriptures.', a: 'Sanskrit' },
      { q: 'The Arabic word for the fast kept during Ramadan.', a: 'Sawm' },
      { q: 'The Passover meal at which a plate of symbolic foods is set out.', a: 'Seder' },
      { q: 'The talk a preacher gives during a service.', a: 'Sermon' },
      { q: 'The traditional religion of Japan, centred on shrines and reverence for nature.', a: 'Shinto' },
      { q: 'The Hindu deity shown with a trident and known as lord of the dance.', a: 'Shiva' },
      { q: 'The ram\'s horn blown in a synagogue at the Jewish new year.', a: 'Shofar' },
      { q: 'A holy place built around a sacred object or the tomb of a saint.', a: 'Shrine' },
      { q: 'The religion of the ten gurus, begun in the Punjab in the fifteenth century.', a: 'Sikhism' },
      { q: 'The peninsula whose mountain appears in the story of Moses receiving the law.', a: 'Sinai' },
      { q: 'The dome-shaped Buddhist monument raised over relics.', a: 'Stupa' },
      { q: 'The Jewish autumn festival when families eat in leafy booths.', a: 'Sukkot' },
      { q: 'The example set by the Prophet Muhammad that Muslims seek to follow.', a: 'Sunnah' },
      { q: 'A Buddhist text presented as a discourse of the Buddha.', a: 'Sutra' },
      { q: 'The Jewish place of worship and study.', a: 'Synagogue' },
    ],
    T: [
      { q: 'The fringed prayer shawl worn by Jewish worshippers.', a: 'Tallit' },
      { q: 'The Jewish collection of rabbinic discussion and commentary on the law.', a: 'Talmud' },
      { q: 'The Chinese tradition founded on the teachings attributed to Laozi.', a: 'Taoism' },
      { q: 'The pair of small leather boxes bound to the arm and head at Jewish morning prayer.', a: 'Tefillin' },
      { q: 'The Jerusalem building destroyed in 70 CE whose western retaining wall still stands.', a: 'Temple' },
      { q: 'The laws given to Moses that open with a call to have no other gods.', a: 'Ten Commandments' },
      { q: 'The painted Tibetan Buddhist scroll hung in monasteries and homes.', a: 'Thangka' },
      { q: 'The Jain title for one of the twenty-four teachers who show the way across the stream of rebirth.', a: 'Tirthankara' },
      { q: 'The traditional giving of a tenth of what one earns to the church.', a: 'Tithe' },
      { q: 'The five books of Moses, read from a scroll in a synagogue.', a: 'Torah' },
      { q: 'The gateway of two uprights and two crossbars that marks the entrance to a Japanese shrine.', a: 'Torii' },
      { q: 'The Christian understanding of God as Father, Son and Holy Spirit.', a: 'Trinity' },
      { q: 'The three baskets of scripture in Theravada Buddhism.', a: 'Tripitaka' },
    ],
    U: [
      { q: 'The Arabic word for the worldwide Muslim community.', a: 'Ummah' },
      { q: 'The shorter Muslim pilgrimage to Mecca that may be made at any time of year.', a: 'Umrah' },
      { q: 'The philosophical texts that bring the Vedas to a close.', a: 'Upanishads' },
      { q: 'The Buddhist observance day kept at the full moon and the new moon.', a: 'Uposatha' },
    ],
    V: [
      { q: 'The Indian city on the Ganges where Hindus bathe in the river and cremate their dead.', a: 'Varanasi' },
      { q: 'The walled city state that is the home of the pope.', a: 'Vatican' },
      { q: 'The four ancient collections of Sanskrit hymns at the root of Hindu scripture.', a: 'Vedas' },
      { q: 'The festival at the May full moon that celebrates the birth of the Buddha.', a: 'Vesak' },
      { q: 'The special garments a priest puts on to lead a service.', a: 'Vestments' },
      { q: 'The title of a parish clergyman in the Church of England.', a: 'Vicar' },
      { q: 'The Hindu deity whose avatars include Rama and Krishna.', a: 'Vishnu' },
    ],
    W: [
      { q: 'The word for a Buddhist temple in Thailand.', a: 'Wat' },
      { q: 'The eighteenth-century English preacher whose movement grew into Methodism.', a: 'Wesley' },
      { q: 'The ancient Jerusalem stonework beside the Temple Mount where Jewish people gather to pray.', a: 'Western Wall' },
      { q: 'The drink shared with bread at a Christian communion.', a: 'Wine' },
      { q: 'The general word for the reverence offered to God in a service.', a: 'Worship' },
      { q: 'The washing of hands, face and feet that Muslims perform before prayer.', a: 'Wudu' },
    ],
    Y: [
      { q: 'The Jewish school where students study the Talmud.', a: 'Yeshiva' },
      { q: 'The Chinese pair of complementary principles shown as a black and white circle.', a: 'Yin and Yang' },
      { q: 'The Indian discipline of posture, breath and mental focus.', a: 'Yoga' },
      { q: 'The Jewish day of atonement, kept with fasting and prayer.', a: 'Yom Kippur' },
      { q: 'The old northern European name for the midwinter festival season.', a: 'Yule' },
    ],
    Z: [
      { q: 'The yearly Muslim giving of a share of wealth to those in need.', a: 'Zakat' },
      { q: 'The well inside the Grand Mosque at Mecca whose water pilgrims drink.', a: 'Zamzam' },
      { q: 'The Japanese school of Buddhism that stresses seated meditation.', a: 'Zen' },
      { q: 'The stepped temple tower built in ancient Mesopotamia.', a: 'Ziggurat' },
      { q: 'The ancient Persian religion whose communities keep a sacred fire in their temples.', a: 'Zoroastrianism' },
    ],
  },
};
