import type { RawPack } from '../core/packs';

export const worldLeadersPack: RawPack = {
  id: 'world-leaders',
  name: 'World Leaders & Politics',
  description: 'Presidents, prime ministers, parliaments and the treaties they signed.',
  locale: 'en',
  difficulty: 'medium',
  contentRating: 'everyone',
  emoji: '🏛️',
  accent: '#b91c1c',
  letters: {
    A: [
      { q: 'The West German chancellor who took office in 1949 had this surname.', a: 'Adenauer' },
      { q: 'The British prime minister who took office in 1945 and served until 1951 had this surname.', a: 'Attlee' },
      { q: 'The Liberal prime minister of the United Kingdom who took office in 1908 had this surname.', a: 'Asquith' },
      { q: 'A formal change to the text of a written constitution is called this.', a: 'Amendment' },
      { q: 'In a parliamentary division, recording neither a yes nor a no is called this.', a: 'Abstention' },
      { q: 'A general pardon granted by a state to a group of offenders is called this.', a: 'Amnesty' },
      { q: 'The Grand National Assembly of Turkey sits in this capital city.', a: 'Ankara' },
      { q: 'Greece is governed from this capital city.', a: 'Athens' },
      { q: 'A system in which a single ruler holds unlimited power is known as this.', a: 'Autocracy' },
      { q: 'The system of legally enforced racial segregation in South Africa, repealed in 1991, was known by this Afrikaans word.', a: 'Apartheid' },
      { q: 'Buenos Aires is the seat of government of this South American country.', a: 'Argentina' },
      { q: 'The senior diplomat a state posts to another country holds this title.', a: 'Ambassador' },
      { q: 'This small Pyrenean principality has two co-princes as its joint heads of state.', a: 'Andorra' },
    ],
    B: [
      { q: 'The prime minister who took office in Israel in 1948 had this surname.', a: 'Ben-Gurion' },
      { q: 'The lower house of the German federal parliament carries this name.', a: 'Bundestag' },
      { q: 'The German states are represented in Berlin by this federal chamber.', a: 'Bundesrat' },
      { q: 'A legislature divided into two separate chambers is described by this word.', a: 'Bicameral' },
      { q: 'The paper on which a voter marks a choice is called this.', a: 'Ballot' },
      { q: 'The European Commission has its headquarters in this city.', a: 'Brussels' },
      { q: 'The National People\'s Congress of China meets in this capital.', a: 'Beijing' },
      { q: 'Brazil moved its national capital in 1960 to this purpose built city.', a: 'Brasilia' },
      { q: 'The West German chancellor who took office in 1969 and received the 1971 Nobel Peace Prize had this surname.', a: 'Brandt' },
      { q: 'The prime minister who took office in Pakistan in 1988 had this surname.', a: 'Bhutto' },
      { q: 'The Venezuelan born leader of the South American independence campaigns against Spanish rule had this surname.', a: 'Bolivar' },
      { q: 'The Prussian statesman who became chancellor of the German Empire in 1871 had this surname.', a: 'Bismarck' },
      { q: 'The Swiss federal government sits in this city.', a: 'Bern' },
      { q: 'The British prime minister who took office in 1997 had this surname.', a: 'Blair' },
      { q: 'The Hungarian parliament building stands beside the Danube in this capital.', a: 'Budapest' },
      { q: 'The body of permanent officials who administer a state is known as this.', a: 'Bureaucracy' },
    ],
    C: [
      { q: 'The British prime minister who took office in May 1940 had this surname.', a: 'Churchill' },
      { q: 'The national legislature of the United States as a whole is known by this name.', a: 'Congress' },
      { q: 'The founding legal document that sets out how a state is governed is called this.', a: 'Constitution' },
      { q: 'The head of government of modern Germany holds this title.', a: 'Chancellor' },
      { q: 'The federal parliament of Australia sits in this purpose built capital.', a: 'Canberra' },
      { q: 'A closed meeting of a party\'s members held to pick a candidate is called this.', a: 'Caucus' },
      { q: 'A government formed jointly by two or more parties is described as this.', a: 'Coalition' },
      { q: 'The senior group of ministers who advise a head of government is called this.', a: 'Cabinet' },
      { q: 'The official count of a population, used to allocate seats, is called this.', a: 'Census' },
      { q: 'The British prime minister who took office in 2010 had this surname.', a: 'Cameron' },
      { q: 'The French prime minister at the 1919 Paris peace conference had this surname.', a: 'Clemenceau' },
      { q: 'The Danish parliament, the Folketing, meets in this capital.', a: 'Copenhagen' },
      { q: 'The Egyptian parliament sits in this capital city.', a: 'Cairo' },
      { q: 'A temporary government that serves only until an election is described as this.', a: 'Caretaker' },
      { q: 'The elected lower chamber of the British parliament is known as the House of this.', a: 'Commons' },
      { q: 'The founding document of the United Nations, signed at San Francisco in 1945, is known by this word.', a: 'Charter' },
    ],
    D: [
      { q: 'The French general who founded the Fifth Republic and became its president in 1959 had this surname.', a: 'De Gaulle' },
      { q: 'The lower house of the Russian Federal Assembly carries this name.', a: 'Duma' },
      { q: 'Government in which authority rests with the whole body of citizens is called this.', a: 'Democracy' },
      { q: 'The conduct of relations between states by negotiation is called this.', a: 'Diplomacy' },
      { q: 'Transferring powers from a central government to a regional one is called this.', a: 'Devolution' },
      { q: 'Leinster House, the seat of the Irish parliament, stands in this capital.', a: 'Dublin' },
      { q: 'Bangladesh is governed from this capital city.', a: 'Dhaka' },
      { q: 'The British prime minister whose government bought Suez Canal shares in 1875 had this surname.', a: 'Disraeli' },
      { q: 'A member of the French National Assembly is known by this title.', a: 'Deputy' },
      { q: 'An order issued by a head of state that carries the force of law is called this.', a: 'Decree' },
      { q: 'A regime in which one leader holds absolute power without elections is called this.', a: 'Dictatorship' },
      { q: 'A self governing nation within the British Empire, such as Canada after 1867, was called this.', a: 'Dominion' },
      { q: 'The national legislature of Japan is known in English by this short word.', a: 'Diet' },
      { q: 'The 1995 accords that ended the war in Bosnia were negotiated at an air base near this Ohio city.', a: 'Dayton' },
    ],
    E: [
      { q: 'The American general who became president in 1953 had this surname.', a: 'Eisenhower' },
      { q: 'All the people of a district entitled to cast a vote are collectively called this.', a: 'Electorate' },
      { q: 'The ruler of Kuwait holds this title.', a: 'Emir' },
      { q: 'A country\'s permanent diplomatic mission in a foreign capital is called this.', a: 'Embassy' },
      { q: 'The Riigikogu is the parliament of this Baltic country.', a: 'Estonia' },
      { q: 'Asmara is the capital of this country on the Red Sea.', a: 'Eritrea' },
      { q: 'The branch of government that carries out the laws is called this.', a: 'Executive' },
      { q: 'This Andean country adopted the United States dollar as its currency in 2000.', a: 'Ecuador' },
      { q: 'The British prime minister who took office in 1955 had this surname.', a: 'Eden' },
      { q: 'The single currency adopted by eleven member states of the EU in 1999 is called this.', a: 'Euro' },
      { q: 'The official residence of the French president is this palace in Paris.', a: 'Elysee' },
    ],
    F: [
      { q: 'Speaking at length in a legislature to delay a vote is known as this tactic.', a: 'Filibuster' },
      { q: 'Dividing power between a central authority and constituent states is called this.', a: 'Federalism' },
      { q: 'The head of state of Spain from 1939 until 1975 had this surname.', a: 'Franco' },
      { q: 'The single chamber parliament of Denmark carries this name.', a: 'Folketing' },
      { q: 'The National Assembly and the Senate together form the parliament of this country.', a: 'France' },
      { q: 'The American diplomat who negotiated the 1778 treaty of alliance in Paris had this surname.', a: 'Franklin' },
      { q: 'The Eduskunta is the parliament of this Nordic country.', a: 'Finland' },
      { q: 'The American vice president who became president in 1974 had this surname.', a: 'Ford' },
      { q: 'The official name of Russia includes this word describing its union of republics.', a: 'Federation' },
      { q: 'Woodrow Wilson set out American peace aims in 1918 in this many Points.', a: 'Fourteen' },
    ],
    G: [
      { q: 'The leader of the Indian independence movement who was called Mahatma had this surname.', a: 'Gandhi' },
      { q: 'The Soviet leader who became general secretary in 1985 had this surname.', a: 'Gorbachev' },
      { q: 'The United Nations has its European headquarters in this Swiss city.', a: 'Geneva' },
      { q: 'Drawing electoral district boundaries to favour one party is called this.', a: 'Gerrymandering' },
      { q: 'The elected head of an American state holds this title.', a: 'Governor' },
      { q: 'The Hellenic Republic is the official name of this country.', a: 'Greece' },
      { q: 'The British prime minister who formed four separate governments in the nineteenth century had this surname.', a: 'Gladstone' },
      { q: 'Accra is the capital of this West African country, independent in 1957.', a: 'Ghana' },
      { q: 'This Central American country shares its name with its own capital city.', a: 'Guatemala' },
      { q: 'The Soviet policy of greater openness introduced under Mikhail Gorbachev was called this.', a: 'Glasnost' },
      { q: 'The Union general who became American president in 1869 had this surname.', a: 'Grant' },
      { q: 'Conakry is the capital of this West African country.', a: 'Guinea' },
    ],
    H: [
      { q: 'The International Court of Justice sits in this Dutch city.', a: 'Hague' },
      { q: 'The government of Finland sits in this capital city.', a: 'Helsinki' },
      { q: 'The playwright who became president of Czechoslovakia in 1989 had this surname.', a: 'Havel' },
      { q: 'The American president who took office in 1929 had this surname.', a: 'Hoover' },
      { q: 'The Danube separates Buda from Pest in the capital of this country.', a: 'Hungary' },
      { q: 'The Japanese emperor whose reign began in 1926 is known by this name.', a: 'Hirohito' },
      { q: 'The legal writ requiring a detained person to be brought before a court is known by this Latin phrase.', a: 'Habeas corpus' },
      { q: 'The American president who took office in 1921 had this surname.', a: 'Harding' },
      { q: 'The Swedish diplomat who became United Nations secretary general in 1953 had this surname.', a: 'Hammarskjold' },
      { q: 'The Scottish Parliament building stands in this district of Edinburgh.', a: 'Holyrood' },
      { q: 'The National Assembly of Vietnam meets in this capital.', a: 'Hanoi' },
    ],
    I: [
      { q: 'The formal process of charging a public official with misconduct before a legislature is called this.', a: 'Impeachment' },
      { q: 'The Althing, founded in 930, is the parliament of this country.', a: 'Iceland' },
      { q: 'The Lok Sabha is the lower house of the parliament of this country.', a: 'India' },
      { q: 'The Taoiseach is the head of government of this country.', a: 'Ireland' },
      { q: 'The Chamber of Deputies and the Senate of the Republic form the parliament of this country.', a: 'Italy' },
      { q: 'The ceremony at which an American president formally takes office is called this.', a: 'Inauguration' },
      { q: 'The person currently holding an elected office is described by this word.', a: 'Incumbent' },
      { q: 'Jakarta is the capital of this archipelago republic.', a: 'Indonesia' },
      { q: 'The national government of Pakistan sits in this purpose built capital.', a: 'Islamabad' },
    ],
    J: [
      { q: 'The principal author of the American Declaration of Independence, later president in 1801, had this surname.', a: 'Jefferson' },
      { q: 'The governor general who led Pakistan at its founding in 1947 had this surname.', a: 'Jinnah' },
      { q: 'The American vice president who became president in 1963 had this surname.', a: 'Johnson' },
      { q: 'The People\'s Consultative Assembly of Indonesia meets in this capital.', a: 'Jakarta' },
      { q: 'The branch of government made up of the courts is called this.', a: 'Judiciary' },
      { q: 'Amman is the capital of this Hashemite kingdom.', a: 'Jordan' },
      { q: 'A House of Representatives and a House of Councillors form the legislature of this country.', a: 'Japan' },
      { q: 'The Mexican president who led the republic during the French intervention of the 1860s had this surname.', a: 'Juarez' },
    ],
    K: [
      { q: 'The single chamber parliament of Israel carries this name.', a: 'Knesset' },
      { q: 'The American president who took office in 1961 had this surname.', a: 'Kennedy' },
      { q: 'The German chancellor in office at reunification in 1990 had this surname.', a: 'Kohl' },
      { q: 'The Soviet leader who became first secretary of the Communist Party in 1953 had this surname.', a: 'Khrushchev' },
      { q: 'The fortified complex in Moscow that houses the Russian presidency is known by this name.', a: 'Kremlin' },
      { q: 'This East African country became independent from Britain in 1963.', a: 'Kenya' },
      { q: 'The German emperor before 1918 was known by this title.', a: 'Kaiser' },
      { q: 'The parliament of Malaysia meets in this capital city.', a: 'Kuala Lumpur' },
      { q: 'Rwanda is governed from this capital city.', a: 'Kigali' },
      { q: 'The 1997 protocol on greenhouse gas emissions was named after this Japanese city.', a: 'Kyoto' },
    ],
    L: [
      { q: 'The American president who took office in 1861 had this surname.', a: 'Lincoln' },
      { q: 'The Assembly of the Republic of Portugal meets in this capital.', a: 'Lisbon' },
      { q: 'The upper chamber of the British parliament, whose members are not elected, is the House of these.', a: 'Lords' },
      { q: 'The branch of government that makes the laws is called this.', a: 'Legislature' },
      { q: 'Seeking to influence lawmakers on behalf of an interest group is called this.', a: 'Lobbying' },
      { q: 'The directly elected house of the Indian parliament carries this name.', a: 'Lok Sabha' },
      { q: 'The international body founded in 1920 and replaced by the United Nations was called this of Nations.', a: 'League' },
      { q: 'The Court of Justice of the European Union sits in this grand duchy.', a: 'Luxembourg' },
      { q: 'The 1925 treaties that settled the western borders of Germany were signed in this Swiss town.', a: 'Locarno' },
      { q: 'The Congress of Peru meets in this capital city.', a: 'Lima' },
      { q: 'The Bolshevik leader who headed the Soviet government from 1917 had this surname.', a: 'Lenin' },
    ],
    M: [
      { q: 'The 1992 treaty that created the European Union was signed in this Dutch city.', a: 'Maastricht' },
      { q: 'The South African president elected in 1994 had this surname.', a: 'Mandela' },
      { q: 'The Cortes Generales of Spain meets in this capital.', a: 'Madrid' },
      { q: 'A system in which a hereditary ruler is head of state is called this.', a: 'Monarchy' },
      { q: 'The published statement of a party\'s promises before an election is called this.', a: 'Manifesto' },
      { q: 'The German chancellor who took office in 2005 had this surname.', a: 'Merkel' },
      { q: 'The British prime minister who took office in 1957 had this surname.', a: 'Macmillan' },
      { q: 'The French president who took office in 1981 had this surname.', a: 'Mitterrand' },
      { q: 'A party holding more than half the seats in a chamber is said to have this.', a: 'Majority' },
      { q: 'The Federal Assembly of Russia meets in this capital.', a: 'Moscow' },
      { q: 'A Chamber of Deputies and a Senate form the congress of this North American country.', a: 'Mexico' },
      { q: 'A formal proposal put before a legislature for debate is called this.', a: 'Motion' },
      { q: 'The American president who gave his name to an 1823 doctrine on the Americas had this surname.', a: 'Monroe' },
      { q: 'The elected head of a city government holds this title.', a: 'Mayor' },
      { q: 'The Japanese era beginning in 1868 that restored imperial rule is known by this name.', a: 'Meiji' },
      { q: 'This Mediterranean island state joined the European Union in 2004.', a: 'Malta' },
    ],
    N: [
      { q: 'The military alliance created by a treaty signed in Washington in 1949 is known by this acronym.', a: 'NATO' },
      { q: 'The prime minister who took office in India in 1947 had this surname.', a: 'Nehru' },
      { q: 'The American president who took office in 1969 had this surname.', a: 'Nixon' },
      { q: 'The National Assembly of Kenya meets in this capital city.', a: 'Nairobi' },
      { q: 'The States General is the parliament of this kingdom.', a: 'Netherlands' },
      { q: 'Managua is the capital of this Central American country.', a: 'Nicaragua' },
      { q: 'The Storting is the parliament of this Nordic kingdom.', a: 'Norway' },
      { q: 'Formally proposing a person as a candidate for office is called this.', a: 'Nomination' },
      { q: 'The 2001 European Union treaty reforming its institutions was signed in this French city.', a: 'Nice' },
      { q: 'The president of Tanzania from 1964 until 1985 had this surname.', a: 'Nyerere' },
      { q: 'The French general proclaimed emperor in 1804 is known by this first name.', a: 'Napoleon' },
      { q: 'The president of Egypt from 1956 until 1970 had this surname.', a: 'Nasser' },
    ],
    O: [
      { q: 'The Storting meets in this capital city.', a: 'Oslo' },
      { q: 'The House of Commons of Canada meets in this capital.', a: 'Ottawa' },
      { q: 'The formal promise a president swears before taking office is called this.', a: 'Oath' },
      { q: 'The group of oil exporting countries founded in Baghdad in 1960 is known by this acronym.', a: 'OPEC' },
      { q: 'The largest party outside government in a parliamentary system is called this.', a: 'Opposition' },
      { q: 'Rule by a small group of powerful people is called this.', a: 'Oligarchy' },
      { q: 'The American president who took office in 2009 had this surname.', a: 'Obama' },
      { q: 'The national parliament of Ireland carries this Irish language name.', a: 'Oireachtas' },
      { q: 'An official appointed to investigate public complaints against a government is called this.', a: 'Ombudsman' },
    ],
    P: [
      { q: 'A representative assembly with the power to make laws is called this.', a: 'Parliament' },
      { q: 'The elected head of state of a republic usually holds this title.', a: 'President' },
      { q: 'The Chamber of Deputies of the Czech Republic meets in this capital.', a: 'Prague' },
      { q: 'A direct popular vote on a question of sovereignty is called this.', a: 'Plebiscite' },
      { q: 'The chief policy making committee of a communist party was known by this name.', a: 'Politburo' },
      { q: 'The 1945 conference near Berlin that set Allied policy for occupied Germany was held in this town.', a: 'Potsdam' },
      { q: 'The Carnation Revolution of 1974 took place in this country.', a: 'Portugal' },
      { q: 'The Sejm is the lower house of the parliament of this country.', a: 'Poland' },
      { q: 'The British prime minister who first took office in 1783 at the age of 24 had this surname.', a: 'Pitt' },
      { q: 'An electoral system that allocates seats in line with each party\'s share of the votes is described as this representation.', a: 'Proportional' },
      { q: 'An American election in which a party\'s own voters choose its candidate is called this.', a: 'Primary' },
      { q: 'The president who took office in Argentina in 1946 had this surname.', a: 'Peron' },
      { q: 'The executive branch of the South African government is based in this city.', a: 'Pretoria' },
    ],
    Q: [
      { q: 'The minimum number of members needed for a legislature to do business is called this.', a: 'Quorum' },
      { q: 'Canadians voted on sovereignty in referendums held in 1980 and 1995 in this province.', a: 'Quebec' },
      { q: 'The official residence of the Italian president is this palace in Rome.', a: 'Quirinal' },
      { q: 'The National Assembly of Ecuador meets in this capital city.', a: 'Quito' },
      { q: 'Elizabeth II held this title as head of state of the United Kingdom from 1952.', a: 'Queen' },
    ],
    R: [
      { q: 'A vote in which an entire electorate is asked to decide a single question is called this.', a: 'Referendum' },
      { q: 'A state in which authority rests with elected representatives rather than a monarch is called this.', a: 'Republic' },
      { q: 'The American president who took office in 1981 had this surname.', a: 'Reagan' },
      { q: 'The American president elected four times, beginning in 1932, had this surname.', a: 'Roosevelt' },
      { q: 'The single chamber parliament of Sweden carries this name.', a: 'Riksdag' },
      { q: 'The 1957 treaty that established the European Economic Community was signed in this city.', a: 'Rome' },
      { q: 'The Althing of Iceland meets in this capital city.', a: 'Reykjavik' },
      { q: 'The Shura Council of Saudi Arabia sits in this capital.', a: 'Riyadh' },
      { q: 'The formal approval of a treaty by the legislature of a state is called this.', a: 'Ratification' },
      { q: 'A change of ministers within a cabinet by the head of government is called this.', a: 'Reshuffle' },
      { q: 'A person who rules on behalf of a monarch who is absent or under age holds this title.', a: 'Regent' },
      { q: 'The Genevan philosopher who published The Social Contract in 1762 had this surname.', a: 'Rousseau' },
      { q: 'The German parliament building in Berlin carries this historic name.', a: 'Reichstag' },
    ],
    S: [
      { q: 'The upper chamber of the United States Congress is called this.', a: 'Senate' },
      { q: 'The lower house of the Polish parliament carries this name.', a: 'Sejm' },
      { q: 'The right to cast a vote in political elections is called this.', a: 'Suffrage' },
      { q: 'The government of Sweden sits in this capital city.', a: 'Stockholm' },
      { q: 'The National Assembly of South Korea meets in this capital.', a: 'Seoul' },
      { q: 'The supreme authority of a state over its own territory is called this.', a: 'Sovereignty' },
      { q: 'The 1985 agreement abolishing many European border checks was signed in this Luxembourg village.', a: 'Schengen' },
      { q: 'The presiding officer of a legislative chamber holds this title.', a: 'Speaker' },
      { q: 'The Soviet leader who headed the state throughout the Second World War had this surname.', a: 'Stalin' },
      { q: 'The president of Egypt from 1970 until 1981 had this surname.', a: 'Sadat' },
      { q: 'This city state separated from Malaysia in 1965.', a: 'Singapore' },
      { q: 'A Federal Council of seven members governs this country.', a: 'Switzerland' },
      { q: 'The national parliament of Norway carries this name.', a: 'Storting' },
      { q: 'A penalty such as a trade restriction imposed on a country to change its conduct is called this.', a: 'Sanction' },
      { q: 'This Nordic country joined the European Union in 1995.', a: 'Sweden' },
    ],
    T: [
      { q: 'The American vice president who became president in 1945 had this surname.', a: 'Truman' },
      { q: 'The British prime minister who took office in 1979 had this surname.', a: 'Thatcher' },
      { q: 'The national legislature of Japan meets in this capital city.', a: 'Tokyo' },
      { q: 'The head of government of Ireland holds this title.', a: 'Taoiseach' },
      { q: 'A formal written agreement between states is called this.', a: 'Treaty' },
      { q: 'The Canadian prime minister who took office in 1968 had this surname.', a: 'Trudeau' },
      { q: 'The emperor of Russia before 1917 was known by this title.', a: 'Tsar' },
      { q: 'The 1943 conference of Allied leaders held in Iran took place in this city.', a: 'Tehran' },
      { q: 'The Grand National Assembly is the legislature of this country.', a: 'Turkey' },
      { q: 'This North African country east of Algeria became independent from France in 1956.', a: 'Tunisia' },
      { q: 'The fixed length of time an elected official serves before facing voters again is called this.', a: 'Term' },
      { q: 'The government of Estonia sits in this capital city.', a: 'Tallinn' },
    ],
    U: [
      { q: 'The agency for education, science and culture based in Paris is known by this acronym.', a: 'UNESCO' },
      { q: 'The agency of the world body that works for children is known by this acronym.', a: 'UNICEF' },
      { q: 'A legislature with only one chamber is described by this word.', a: 'Unicameral' },
      { q: 'Montevideo is the capital of this South American country.', a: 'Uruguay' },
      { q: 'Kampala is the capital of this East African country.', a: 'Uganda' },
      { q: 'The 1713 treaty that ended the War of the Spanish Succession was signed in this Dutch city.', a: 'Utrecht' },
      { q: 'The principle that every adult citizen may vote, whatever their wealth, is called this suffrage.', a: 'Universal' },
      { q: 'The international organisation founded in 1945 with headquarters in New York carries this name.', a: 'United Nations' },
    ],
    V: [
      { q: 'The power of a head of state to reject a bill passed by a legislature is called this.', a: 'Veto' },
      { q: 'The 1919 treaty that ended the First World War with Germany was signed at this palace.', a: 'Versailles' },
      { q: 'The 1961 convention on diplomatic relations was signed in this Austrian capital.', a: 'Vienna' },
      { q: 'The smallest sovereign state in the world, governed by the pope, is this city state.', a: 'Vatican' },
      { q: 'The formal expression of a choice in an election is called this.', a: 'Vote' },
      { q: 'Caracas is the capital of this South American country.', a: 'Venezuela' },
      { q: 'Hanoi has been the capital of this reunified country since 1976.', a: 'Vietnam' },
      { q: 'The official who governed British India on behalf of the crown held this title.', a: 'Viceroy' },
      { q: 'The parliament of Malta sits in this capital city.', a: 'Valletta' },
    ],
    W: [
      { q: 'The Capitol building that houses the United States Congress stands in this city.', a: 'Washington' },
      { q: 'The British parliament sits in a palace of this name.', a: 'Westminster' },
      { q: 'British government departments are traditionally based on this London street.', a: 'Whitehall' },
      { q: 'The American president who took office in 1913 had this surname.', a: 'Wilson' },
      { q: 'The Sejm meets in this capital city.', a: 'Warsaw' },
      { q: 'The parliament of New Zealand sits in this capital city.', a: 'Wellington' },
      { q: 'The party official who enforces discipline among members of a legislature is called this.', a: 'Whip' },
      { q: 'The German republic proclaimed in 1919 is named after this town.', a: 'Weimar' },
      { q: 'The royal house of the United Kingdom has carried this name since 1917.', a: 'Windsor' },
    ],
    Y: [
      { q: 'The February 1945 conference of Allied leaders was held at this Black Sea resort.', a: 'Yalta' },
      { q: 'The Balkan federation established in 1945 and dissolved during the 1990s was known by this name.', a: 'Yugoslavia' },
      { q: 'The National Assembly of Cameroon meets in this capital city.', a: 'Yaounde' },
      { q: 'The president of Russia from 1991 until 1999 had this surname.', a: 'Yeltsin' },
      { q: 'The National Assembly of Armenia meets in this capital city.', a: 'Yerevan' },
    ],
    Z: [
      { q: 'The Croatian parliament, the Sabor, meets in this capital.', a: 'Zagreb' },
      { q: 'Lusaka is the capital of this southern African country.', a: 'Zambia' },
      { q: 'Harare is the capital of this southern African country.', a: 'Zimbabwe' },
      { q: 'The largest Swiss city, which is not the seat of the federal government, is this.', a: 'Zurich' },
    ],
  },
};
